function segment = azElHs3SegmentTemplate()
%% Section 0: Header & Readme
% SYNTAX
%   segment = azElHs3SegmentTemplate()
%**************************************************************************
% PURPOSE
%   - Return one editable azimuth/elevation HS-3 segment record.
%**************************************************************************
% INPUTS
%   - This function has no inputs.
%**************************************************************************
% OUTPUTS
%   - segment (scalar struct)
%       Endpoint states, per-axis limits, maximum duration, and arrival
%       mode accepted by solveAzElHs3Segments.
%**************************************************************************
% UNITS
%   - Position is degrees. Time is seconds. Derivative units are stated in
%     each field name. Vectors use [azimuth elevation] order.
%**************************************************************************

%% Section 1: Create The Segment Template

segment = struct( ...
    "startPosition_deg", [-5 0], ...
    "endPosition_deg", [5 0], ...
    "initialVelocity_deg_s", [0 0], ...
    "finalVelocity_deg_s", [0 0], ...
    "initialAcceleration_deg_s2", [0 0], ...
    "finalAcceleration_deg_s2", [0 0], ...
    "limits", struct( ...
        "maxVelocity_deg_s", [3 3], ...
        "maxAcceleration_deg_s2", [2 2], ...
        "maxJerk_deg_s3", [4 4]), ...
    "maximumDuration_s", 20, ...
    "arrivalMode", "earliestArrival");
end
