function app = azElHs3Sandbox(optionOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   app = azElHs3Sandbox()
%   app = azElHs3Sandbox(optionOverrides)
%**************************************************************************
% PURPOSE
%   - Provide an azimuth/elevation grid for user-defined motion segments.
%   - Build and plot certified HS-3 profiles from editable endpoint states
%     and per-segment physical limits.
%**************************************************************************
% INPUTS
%   - optionOverrides (scalar struct, optional; default struct())
%       .FigureVisible is "on" or "off" (default "on").
%       .AzimuthInterval_deg is increasing two-element (default [-20 20]).
%       .ElevationInterval_deg is increasing two-element (default [-15 15]).
%       .SolverOptions is a partial solveAzElHs3Segments option struct.
%**************************************************************************
% OUTPUTS
%   - app (scalar struct)
%       Figure, axes, table, controls, and callable AddRow, BuildMotion,
%       ReadSegments, and Close function handles.
%**************************************************************************
% UNITS
%   - Grid position is degrees. Table derivative and time units are stated
%     in each column name. Vectors use [azimuth elevation] order.
%**************************************************************************

%% Section 1: Validate Inputs & Apply Defaults

if nargin < 1 || isempty(optionOverrides)
    optionOverrides = struct();
end
defaults = struct( ...
    "FigureVisible", "on", ...
    "AzimuthInterval_deg", [-20 20], ...
    "ElevationInterval_deg", [-15 15], ...
    "SolverOptions", struct());
[options, unknownOptions] = azElInternal.resolveOptions( ...
    defaults, optionOverrides);
if ~isempty(unknownOptions)
    warning("azElHs3Sandbox:UnknownOptions", ...
        "Ignored unknown option fields: %s. No behavior changed.", ...
        strjoin(unknownOptions, ", "));
end
options.FigureVisible = lower(string(options.FigureVisible));
if ~isscalar(options.FigureVisible) || ~any( ...
        options.FigureVisible == ["on" "off"])
    error("azElHs3Sandbox:InvalidFigureVisible", ...
        "FigureVisible must be on or off.");
end
options.AzimuthInterval_deg = validateInterval( ...
    options.AzimuthInterval_deg, "AzimuthInterval_deg");
options.ElevationInterval_deg = validateInterval( ...
    options.ElevationInterval_deg, "ElevationInterval_deg");
if ~isstruct(options.SolverOptions) || ~isscalar(options.SolverOptions)
    error("azElHs3Sandbox:InvalidSolverOptions", ...
        "SolverOptions must be a scalar struct.");
end

%% Section 2: Build The Grid And Controls

figureHandle = figure( ...
    "Visible", options.FigureVisible, ...
    "Name", "Azimuth/elevation HS-3 sandbox", ...
    "NumberTitle", "off", ...
    "Units", "normalized", ...
    "Position", [0.08 0.08 0.84 0.82]);
axesHandle = axes( ...
    "Parent", figureHandle, ...
    "Units", "normalized", ...
    "Position", [0.06 0.41 0.52 0.54], ...
    "ButtonDownFcn", @captureGridPoint);
xlim(axesHandle, options.AzimuthInterval_deg);
ylim(axesHandle, options.ElevationInterval_deg);
xlabel(axesHandle, "Azimuth (deg)");
ylabel(axesHandle, "Elevation (deg)");
title(axesHandle, "Draw two points or edit the segment table");
grid(axesHandle, "on");
box(axesHandle, "on");
axis(axesHandle, "equal");
hold(axesHandle, "on");

columnNames = sandboxColumnNames();
columnFormats = repmat({'numeric'}, 1, numel(columnNames));
columnFormats{end} = 'logical';
segmentTable = uitable( ...
    "Parent", figureHandle, ...
    "Units", "normalized", ...
    "Position", [0.03 0.04 0.94 0.29], ...
    "Data", cell(0, numel(columnNames)), ...
    "ColumnName", cellstr(columnNames), ...
    "ColumnEditable", true(1, numel(columnNames)), ...
    "ColumnFormat", columnFormats, ...
    "RowName", []);

drawButton = uicontrol( ...
    "Parent", figureHandle, ...
    "Style", "pushbutton", ...
    "Units", "normalized", ...
    "Position", [0.63 0.84 0.15 0.06], ...
    "String", "Draw segment", ...
    "Callback", @beginGridSegment);
addButton = uicontrol( ...
    "Parent", figureHandle, ...
    "Style", "pushbutton", ...
    "Units", "normalized", ...
    "Position", [0.80 0.84 0.15 0.06], ...
    "String", "Add row", ...
    "Callback", @addSegmentRow);
removeButton = uicontrol( ...
    "Parent", figureHandle, ...
    "Style", "pushbutton", ...
    "Units", "normalized", ...
    "Position", [0.63 0.75 0.15 0.06], ...
    "String", "Remove last", ...
    "Callback", @removeLastSegment);
buildButton = uicontrol( ...
    "Parent", figureHandle, ...
    "Style", "pushbutton", ...
    "Units", "normalized", ...
    "Position", [0.80 0.75 0.15 0.06], ...
    "String", "Build HS-3 motion", ...
    "FontWeight", "bold", ...
    "Callback", @buildMotion);
statusText = uicontrol( ...
    "Parent", figureHandle, ...
    "Style", "text", ...
    "Units", "normalized", ...
    "Position", [0.62 0.43 0.34 0.27], ...
    "HorizontalAlignment", "left", ...
    "String", sandboxInstructions());

state = struct( ...
    "Options", options, ...
    "Axes", axesHandle, ...
    "Table", segmentTable, ...
    "StatusText", statusText, ...
    "IsCapturing", false, ...
    "FirstPoint_deg", [NaN NaN], ...
    "TemporaryMarker", gobjects(0, 1), ...
    "MotionLine", gobjects(0, 1), ...
    "ProfileFigure", gobjects(0, 1), ...
    "Result", struct(), ...
    "Diagnostics", struct());
guidata(figureHandle, state);

%% Section 3: Return The App Interface

app = struct( ...
    "Figure", figureHandle, ...
    "Axes", axesHandle, ...
    "SegmentTable", segmentTable, ...
    "DrawButton", drawButton, ...
    "AddButton", addButton, ...
    "RemoveButton", removeButton, ...
    "BuildButton", buildButton, ...
    "StatusText", statusText, ...
    "AddRow", @() addSegmentRow(addButton, []), ...
    "BuildMotion", @() buildMotion(buildButton, []), ...
    "ReadSegments", @() readSegments(segmentTable), ...
    "Close", @() closeSandbox(figureHandle));
end

%% Section 4: Local Functions

function interval = validateInterval(interval, name)
% PURPOSE
%   - Normalize one two-element increasing grid interval.
validateattributes(interval, {'numeric'}, ...
    {'real','finite','vector','numel',2});
interval = reshape(double(interval), 1, 2);
if interval(2) <= interval(1)
    error("azElHs3Sandbox:InvalidInterval", ...
        "%s must contain two increasing values.", name);
end
end

function names = sandboxColumnNames()
% PURPOSE
%   - Keep the table-to-segment mapping stable in one place.
names = [ ...
    "StartAz_deg" "StartEl_deg" "EndAz_deg" "EndEl_deg" ...
    "InitialAzVel_deg_s" "InitialElVel_deg_s" ...
    "FinalAzVel_deg_s" "FinalElVel_deg_s" ...
    "InitialAzAcc_deg_s2" "InitialElAcc_deg_s2" ...
    "FinalAzAcc_deg_s2" "FinalElAcc_deg_s2" ...
    "MaxAzVel_deg_s" "MaxElVel_deg_s" ...
    "MaxAzAcc_deg_s2" "MaxElAcc_deg_s2" ...
    "MaxAzJerk_deg_s3" "MaxElJerk_deg_s3" ...
    "Horizon_s" "FixedArrival"];
end

function textValue = sandboxInstructions()
% PURPOSE
%   - Give short operating instructions and state the jerk boundary rule.
textValue = sprintf([ ...
    '1. Select Draw segment.\n' ...
    '2. Select start and end points on the grid.\n' ...
    '3. Edit endpoint states and limits in the table.\n' ...
    '4. Select Build HS-3 motion.\n\n' ...
    'Connected rows must share position, velocity, and acceleration.\n' ...
    'Jerk is bounded. Jerk continuity and zero terminal jerk are reported ' ...
    'but are not imposed.']);
end

function beginGridSegment(source, ~)
% PURPOSE
%   - Arm the grid to capture two segment endpoints.
figureHandle = ancestor(source, "figure");
state = guidata(figureHandle);
state.IsCapturing = true;
state.FirstPoint_deg = [NaN NaN];
deleteValidGraphics(state.TemporaryMarker);
state.TemporaryMarker = gobjects(0, 1);
set(state.StatusText, "String", ...
    "Select the segment start point on the grid.");
guidata(figureHandle, state);
end

function captureGridPoint(axesHandle, ~)
% PURPOSE
%   - Add a table row after two grid selections.
figureHandle = ancestor(axesHandle, "figure");
state = guidata(figureHandle);
if ~state.IsCapturing
    return;
end
currentPoint = get(axesHandle, "CurrentPoint");
point_deg = currentPoint(1, 1:2);
azimuthLimits_deg = xlim(axesHandle);
elevationLimits_deg = ylim(axesHandle);
point_deg(1) = min(max(point_deg(1), azimuthLimits_deg(1)), ...
    azimuthLimits_deg(2));
point_deg(2) = min(max(point_deg(2), elevationLimits_deg(1)), ...
    elevationLimits_deg(2));
if any(isnan(state.FirstPoint_deg))
    state.FirstPoint_deg = point_deg;
    state.TemporaryMarker = plot(axesHandle, point_deg(1), point_deg(2), ...
        "o", "MarkerSize", 7, "LineWidth", 1.3, ...
        "Color", [0.85 0.33 0.10], "HitTest", "off");
    set(state.StatusText, "String", ...
        "Select the segment end point on the grid.");
    guidata(figureHandle, state);
    return;
end
appendTableSegment(state.Table, state.FirstPoint_deg, point_deg);
plot(axesHandle, ...
    [state.FirstPoint_deg(1) point_deg(1)], ...
    [state.FirstPoint_deg(2) point_deg(2)], "--", ...
    "Color", [0.45 0.45 0.45], "LineWidth", 1.1, ...
    "HitTest", "off");
deleteValidGraphics(state.TemporaryMarker);
state.TemporaryMarker = gobjects(0, 1);
state.IsCapturing = false;
state.FirstPoint_deg = [NaN NaN];
set(state.StatusText, "String", ...
    "Segment added. Edit its states and limits, then build the motion.");
guidata(figureHandle, state);
end

function addSegmentRow(source, ~)
% PURPOSE
%   - Add one editable default row, connected to the prior row when present.
figureHandle = ancestor(source, "figure");
state = guidata(figureHandle);
data = get(state.Table, "Data");
template = azElHs3SegmentTemplate();
if isempty(data)
    start_deg = template.startPosition_deg;
    end_deg = template.endPosition_deg;
else
    start_deg = cell2mat(data(end, 3:4));
    end_deg = start_deg + [5 0];
    template.initialVelocity_deg_s = cell2mat(data(end, 7:8));
    template.initialAcceleration_deg_s2 = cell2mat(data(end, 11:12));
end
appendTableSegment(state.Table, start_deg, end_deg, template);
set(state.StatusText, "String", ...
    "Row added. Edit the endpoint states and physical limits.");
end

function appendTableSegment(tableHandle, start_deg, end_deg, template)
% PURPOSE
%   - Convert one segment record to the stable table column order.
if nargin < 4
    template = azElHs3SegmentTemplate();
end
template.startPosition_deg = start_deg;
template.endPosition_deg = end_deg;
isFixedArrival = lower(string(template.arrivalMode)) == "fixedarrival";
row = num2cell([ ...
    template.startPosition_deg, template.endPosition_deg, ...
    template.initialVelocity_deg_s, template.finalVelocity_deg_s, ...
    template.initialAcceleration_deg_s2, ...
    template.finalAcceleration_deg_s2, ...
    template.limits.maxVelocity_deg_s, ...
    template.limits.maxAcceleration_deg_s2, ...
    template.limits.maxJerk_deg_s3, ...
    template.maximumDuration_s]);
row{end + 1} = isFixedArrival;
data = get(tableHandle, "Data");
set(tableHandle, "Data", [data; row]);
end

function removeLastSegment(source, ~)
% PURPOSE
%   - Remove the last table row without changing planner data.
figureHandle = ancestor(source, "figure");
state = guidata(figureHandle);
data = get(state.Table, "Data");
if ~isempty(data)
    data(end, :) = [];
    set(state.Table, "Data", data);
end
set(state.StatusText, "String", "The last segment row was removed.");
end

function segments = readSegments(tableHandle)
% PURPOSE
%   - Convert the editable table to validated segment records.
data = get(tableHandle, "Data");
if isempty(data)
    error("azElHs3Sandbox:NoSegments", ...
        "Add at least one segment before building motion.");
end
template = azElHs3SegmentTemplate();
segments = repmat(template, size(data, 1), 1);
for segmentIndex = 1:size(data, 1)
    values = zeros(1, 19);
    for columnIndex = 1:19
        value = data{segmentIndex, columnIndex};
        if ~isnumeric(value) || ~isscalar(value)
            error("azElHs3Sandbox:InvalidTableValue", ...
                "Row %d column %d must contain one numeric value.", ...
                segmentIndex, columnIndex);
        end
        values(columnIndex) = value;
    end
    segment = template;
    segment.startPosition_deg = values(1:2);
    segment.endPosition_deg = values(3:4);
    segment.initialVelocity_deg_s = values(5:6);
    segment.finalVelocity_deg_s = values(7:8);
    segment.initialAcceleration_deg_s2 = values(9:10);
    segment.finalAcceleration_deg_s2 = values(11:12);
    segment.limits.maxVelocity_deg_s = values(13:14);
    segment.limits.maxAcceleration_deg_s2 = values(15:16);
    segment.limits.maxJerk_deg_s3 = values(17:18);
    segment.maximumDuration_s = values(19);
    segment.arrivalMode = "earliestArrival";
    if logical(data{segmentIndex, 20})
        segment.arrivalMode = "fixedArrival";
    end
    segments(segmentIndex) = segment;
end
end

function result = buildMotion(source, ~)
% PURPOSE
%   - Solve table segments and update the grid and profile figure.
figureHandle = ancestor(source, "figure");
state = guidata(figureHandle);
result = struct();
try
    segments = readSegments(state.Table);
    set(state.StatusText, "String", "Building the HS-3 motion profile...");
    drawnow;
    [result, diagnostics] = solveAzElHs3Segments( ...
        segments, state.Options.SolverOptions);
    state.Result = result;
    state.Diagnostics = diagnostics;
    if ~result.Success
        set(state.StatusText, "String", result.Message);
        guidata(figureHandle, state);
        return;
    end
    deleteValidGraphics(state.MotionLine);
    state.MotionLine = plot(state.Axes, ...
        result.position_deg(:, 1), result.position_deg(:, 2), ...
        "Color", [0 0.45 0.74], "LineWidth", 2.0, ...
        "DisplayName", "HS-3 motion", "HitTest", "off");
    if any(isgraphics(state.ProfileFigure))
        close(state.ProfileFigure(isgraphics(state.ProfileFigure)));
    end
    profileHandles = plotAzElHs3Motion(result, struct( ...
        "FigureVisible", state.Options.FigureVisible));
    state.ProfileFigure = profileHandles.Figure;
    jerkText = "Jerk is continuous at segment boundaries.";
    if ~result.Validation.JerkIsContinuous
        jerkText = "Jerk has a boundary jump. This is reported, not hidden.";
    end
    set(state.StatusText, "String", result.Message + newline + jerkText);
    guidata(figureHandle, state);
catch exception
    set(state.StatusText, "String", exception.message);
    guidata(figureHandle, state);
    if nargout > 0
        rethrow(exception);
    end
end
end

function deleteValidGraphics(graphicsHandles)
% PURPOSE
%   - Delete only graphics objects that still exist.
if ~isempty(graphicsHandles)
    delete(graphicsHandles(isgraphics(graphicsHandles)));
end
end

function closeSandbox(figureHandle)
% PURPOSE
%   - Close the sandbox and its profile figure.
if ~isgraphics(figureHandle)
    return;
end
state = guidata(figureHandle);
if isstruct(state) && isfield(state, "ProfileFigure") && ...
        any(isgraphics(state.ProfileFigure))
    close(state.ProfileFigure(isgraphics(state.ProfileFigure)));
end
close(figureHandle);
end
