function exportInfo = exportAzElSandboxDiagnosis( ...
        filePath, sandboxState, modeName)
%% Section 0: Header & Readme
% SYNTAX
%   exportInfo = exportAzElSandboxDiagnosis( ...
%       filePath, sandboxState, modeName)
%**************************************************************************
% PURPOSE
%   - Save one diagnosis-ready MAT bundle from the persistent sandbox.
%   - Preserve exact planner inputs, results, validation, retained scene
%     geometry, segment evidence, controls, logs, and reproduction guidance.
%   - Exclude graphics handles and callbacks that cannot aid diagnosis.
%**************************************************************************
% INPUTS
%   - filePath (scalar text)
%       Destination MAT file. A missing .mat extension is added. Existing
%       files are replaced only when the caller supplies that exact path.
%   - sandboxState (scalar struct)
%       Current value returned by sandboxState.ReadState().
%   - modeName (scalar text)
%       "goal" or "free"; selects the independent tab record to export.
%**************************************************************************
% OUTPUTS
%   - exportInfo (scalar struct)
%       Absolute file path, byte count, mode, planner status, and schema.
%**************************************************************************
% UNITS
%   - Preserved positions are degrees, time is seconds, and derivatives use
%     deg/s, deg/s^2, and deg/s^3.
%**************************************************************************

%% Section 1: Validate Destination And Sandbox State

filePath = string(filePath);
if ~isscalar(filePath) || ismissing(filePath) || strlength(filePath) == 0
    error("exportAzElSandboxDiagnosis:InvalidFilePath", ...
        "filePath must be nonempty scalar text.");
end
modeName = lower(string(modeName));
if ~isscalar(modeName) || ~any(modeName == ["goal" "free"])
    error("exportAzElSandboxDiagnosis:InvalidMode", ...
        "modeName must be 'goal' or 'free'.");
end
if ~isstruct(sandboxState) || ~isscalar(sandboxState)
    error("exportAzElSandboxDiagnosis:InvalidState", ...
        "sandboxState must be the scalar struct returned by ReadState().");
end
requiredStateFields = {'Options', 'GoalMode', 'FreeMode'};
if ~all(isfield(sandboxState, requiredStateFields))
    error("exportAzElSandboxDiagnosis:InvalidState", ...
        "sandboxState must contain Options, GoalMode, and FreeMode.");
end

[destinationFolder, destinationName, destinationExtension] = ...
    fileparts(char(filePath));
if isempty(destinationExtension)
    destinationExtension = '.mat';
elseif ~strcmpi(destinationExtension, '.mat')
    error("exportAzElSandboxDiagnosis:InvalidExtension", ...
        "filePath must use the .mat extension.");
end
if isempty(destinationFolder)
    destinationFolder = pwd;
end
if ~isfolder(destinationFolder)
    error("exportAzElSandboxDiagnosis:MissingFolder", ...
        "Destination folder does not exist: %s", destinationFolder);
end
absoluteFilePath = string(fullfile( ...
    destinationFolder, [destinationName destinationExtension]));

%% Section 2: Build A Handle-Free Diagnosis Bundle

if modeName == "goal"
    modeState = sandboxState.GoalMode;
else
    modeState = sandboxState.FreeMode;
end
requiredModeFields = { ...
    'StartPosition_deg', 'GoalPosition_deg', ...
    'WaypointPositions_deg', 'RawObstacleStrokes_deg', ...
    'LineObstaclePositions_deg', 'PolygonObstaclePositions_deg', ...
    'CanonicalObstacles', 'SegmentResults', 'CombinedTrajectory', ...
    'LastPlannerResult', 'LastValidation', 'Status', 'PlannerLog', ...
    'ResolvedControls'};
if ~isstruct(modeState) || ~isscalar(modeState) || ...
        ~all(isfield(modeState, requiredModeFields))
    error("exportAzElSandboxDiagnosis:InvalidModeState", ...
        "The selected mode record does not have the stable sandbox schema.");
end
result = modeState.LastPlannerResult;
if ~isstruct(result) || ~isscalar(result) || isempty(fieldnames(result))
    error("exportAzElSandboxDiagnosis:NoResult", ...
        "Run the selected sandbox mode before exporting a diagnosis bundle.");
end
if ~isfield(result, "Inputs") || ~isfield(result, "Options")
    error("exportAzElSandboxDiagnosis:InvalidResult", ...
        "The retained planner result must contain Inputs and Options.");
end

scene = struct( ...
    "StartPosition_deg", modeState.StartPosition_deg, ...
    "GoalPosition_deg", modeState.GoalPosition_deg, ...
    "WaypointPositions_deg", modeState.WaypointPositions_deg, ...
    "RawObstacleStrokes_deg", {modeState.RawObstacleStrokes_deg}, ...
    "LineObstaclePositions_deg", ...
        {modeState.LineObstaclePositions_deg}, ...
    "PolygonObstaclePositions_deg", ...
        {modeState.PolygonObstaclePositions_deg}, ...
    "CanonicalObstacles", modeState.CanonicalObstacles, ...
    "ResolvedControls", modeState.ResolvedControls);
environment = struct( ...
    "MATLABVersion", string(version), ...
    "MATLABRelease", string(version("-release")), ...
    "Computer", string(computer), ...
    "WorkingDirectory", string(pwd));
reproduction = struct( ...
    "LoadCommand", ...
        "loaded = load(filePath, 'diagnosisBundle');", ...
    "PlannerCommand", ...
        "reproduced = planAzElMotion(" + ...
        "diagnosisBundle.PlannerInputs.obstacles, " + ...
        "diagnosisBundle.PlannerInputs.initialState, " + ...
        "diagnosisBundle.PlannerInputs.goalState, " + ...
        "diagnosisBundle.PlannerInputs.limits, " + ...
        "diagnosisBundle.PlannerOptions);", ...
    "ValidationCommand", ...
        "reproducedValidation = validateAzElTrajectory(reproduced);");
diagnosisBundle = struct( ...
    "Schema", "azElSandboxDiagnosis-v1", ...
    "CreatedUTC", string(datetime( ...
        "now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX")), ...
    "Mode", modeName, ...
    "Environment", environment, ...
    "SandboxOptions", sandboxState.Options, ...
    "Scene", scene, ...
    "PlannerInputs", result.Inputs, ...
    "PlannerOptions", result.Options, ...
    "Result", result, ...
    "IndependentValidation", modeState.LastValidation, ...
    "SegmentResults", modeState.SegmentResults, ...
    "CombinedTrajectory", modeState.CombinedTrajectory, ...
    "Status", string(modeState.Status), ...
    "PlannerLog", string(modeState.PlannerLog), ...
    "Reproduction", reproduction);

%% Section 3: Save And Report The Export

save(char(absoluteFilePath), "diagnosisBundle", "-v7.3");
fileRecord = dir(char(absoluteFilePath));
exportInfo = struct( ...
    "FilePath", absoluteFilePath, ...
    "Bytes", double(fileRecord.bytes), ...
    "Mode", modeName, ...
    "PlannerSuccess", logical(result.Success), ...
    "TerminationReason", string(result.TerminationReason), ...
    "Schema", diagnosisBundle.Schema);
end
