function exportInfo = exportSandboxDiagnosis( ...
        filePath, sandboxState, modeName)
%% Section 0: Header & Readme
% SYNTAX
%   exportInfo = exportSandboxDiagnosis( ...
%       filePath, sandboxState, modeName)
%**************************************************************************
% PURPOSE
%   - Save one diagnosis-ready MAT bundle from the persistent sandbox.
%   - Preserve a pre-run request or completed planner evidence, retained scene
%     geometry, controls, logs, and applicable reproduction guidance.
%   - Exclude graphics handles and callbacks that cannot aid diagnosis.
%**************************************************************************
% INPUTS
%   - filePath (scalar text)
%       Destination MAT file. A missing .mat extension is added. Existing
%       files are replaced only when the caller supplies that exact path.
%   - sandboxState (scalar struct)
%       Current value returned by sandboxState.ReadState().
%   - modeName (scalar text)
%       "goal" or "free"; selects the independent tab record to export.
%**************************************************************************
% OUTPUTS
%   - exportInfo (scalar struct)
%       Absolute path, byte count, mode, HasPlannerResult, planner status,
%       termination reason, and schema. A pre-run export reports notRun.
%**************************************************************************
% UNITS
%   - Preserved positions are degrees, time is seconds, and derivatives use
%     deg/s, deg/s^2, and deg/s^3.
%**************************************************************************

%% Section 1: Validate Destination And Sandbox State

filePath = string(filePath);
if ~isscalar(filePath) || ismissing(filePath) || strlength(filePath) == 0
    error("exportSandboxDiagnosis:InvalidFilePath", ...
        "filePath must be nonempty scalar text.");
end
modeName = lower(string(modeName));
if ~isscalar(modeName) || ~any(modeName == ["goal" "free"])
    error("exportSandboxDiagnosis:InvalidMode", ...
        "modeName must be 'goal' or 'free'.");
end
if ~isstruct(sandboxState) || ~isscalar(sandboxState)
    error("exportSandboxDiagnosis:InvalidState", ...
        "sandboxState must be the scalar struct returned by ReadState().");
end
requiredStateFields = {'Options', 'GoalMode', 'FreeMode'};
if ~all(isfield(sandboxState, requiredStateFields))
    error("exportSandboxDiagnosis:InvalidState", ...
        "sandboxState must contain Options, GoalMode, and FreeMode.");
end

[destinationFolder, destinationName, destinationExtension] = ...
    fileparts(char(filePath));
if isempty(destinationExtension)
    destinationExtension = '.mat';
elseif ~strcmpi(destinationExtension, '.mat')
    error("exportSandboxDiagnosis:InvalidExtension", ...
        "filePath must use the .mat extension.");
end
if isempty(destinationFolder)
    destinationFolder = pwd;
end
if ~isfolder(destinationFolder)
    error("exportSandboxDiagnosis:MissingFolder", ...
        "Destination folder does not exist: %s", destinationFolder);
end
absoluteFilePath = string(fullfile( ...
    destinationFolder, [destinationName destinationExtension]));

%% Section 2: Build A Handle-Free Diagnosis Bundle

if modeName == "goal"
    modeState = sandboxState.GoalMode;
else
    modeState = sandboxState.FreeMode;
end
requiredModeFields = { ...
    'StartPosition_deg', 'GoalPosition_deg', ...
    'WaypointPositions_deg', 'RawObstacleStrokes_deg', ...
    'LineObstaclePositions_deg', 'PolygonObstaclePositions_deg', ...
    'CanonicalObstacles', 'SegmentResults', 'CombinedTrajectory', ...
    'LastPlannerResult', 'LastValidation', 'Status', 'PlannerLog', ...
    'ResolvedControls'};
if ~isstruct(modeState) || ~isscalar(modeState) || ...
        ~all(isfield(modeState, requiredModeFields))
    error("exportSandboxDiagnosis:InvalidModeState", ...
        "The selected mode record does not have the stable sandbox schema.");
end
result = modeState.LastPlannerResult;
hasPlannerResult = isstruct(result) && isscalar(result) && ...
    ~isempty(fieldnames(result));
if hasPlannerResult && ...
        (~isfield(result, "Inputs") || ~isfield(result, "Options"))
    error("exportSandboxDiagnosis:InvalidResult", ...
        "The retained planner result must contain Inputs and Options.");
end
if hasPlannerResult
    planningState = "completed";
    plannerInputs = result.Inputs;
    plannerOptions = result.Options;
    independentValidation = modeState.LastValidation;
    plannerSuccess = logical(result.Success);
    terminationReason = string(result.TerminationReason);
    exportRequest = struct();
elseif isfield(modeState, "ExportRequest") && ...
        isstruct(modeState.ExportRequest) && ...
        isscalar(modeState.ExportRequest)
    planningState = "notRun";
    exportRequest = modeState.ExportRequest;
    plannerInputs = exportRequest.PlannerInputs;
    plannerOptions = exportRequest.PlannerOptions;
    independentValidation = obstacleAvoidance.validateTrajectory();
    plannerSuccess = false;
    terminationReason = "notRun";
else
    planningState = "notRun";
    exportRequest = struct();
    plannerInputs = struct();
    plannerOptions = struct();
    independentValidation = obstacleAvoidance.validateTrajectory();
    plannerSuccess = false;
    terminationReason = "notRun";
end

scene = struct( ...
    "StartPosition_deg", modeState.StartPosition_deg, ...
    "GoalPosition_deg", modeState.GoalPosition_deg, ...
    "WaypointPositions_deg", modeState.WaypointPositions_deg, ...
    "RawObstacleStrokes_deg", {modeState.RawObstacleStrokes_deg}, ...
    "LineObstaclePositions_deg", ...
        {modeState.LineObstaclePositions_deg}, ...
    "PolygonObstaclePositions_deg", ...
        {modeState.PolygonObstaclePositions_deg}, ...
    "CanonicalObstacles", modeState.CanonicalObstacles, ...
    "ResolvedControls", modeState.ResolvedControls);
environment = struct( ...
    "MATLABVersion", string(version), ...
    "MATLABRelease", string(version('-release')), ...
    "Computer", string(computer), ...
    "WorkingDirectory", string(pwd));
hasReplayableInputs = all(isfield(plannerInputs, ...
    {'obstacles', 'initialState', 'goalState', 'limits'}));
plannerCommand = "";
validationCommand = "";
if hasReplayableInputs
    plannerCommand = ...
        "reproduced = obstacleAvoidance.planTrajectory(" + ...
        "diagnosisBundle.PlannerInputs.obstacles, " + ...
        "diagnosisBundle.PlannerInputs.initialState, " + ...
        "diagnosisBundle.PlannerInputs.goalState, " + ...
        "diagnosisBundle.PlannerInputs.limits, " + ...
        "diagnosisBundle.PlannerOptions);";
    validationCommand = ...
        "reproducedValidation = obstacleAvoidance.validateTrajectory(reproduced);";
end
reproduction = struct( ...
    "LoadCommand", ...
        "loaded = load(filePath, 'diagnosisBundle');", ...
    "PlannerCommand", plannerCommand, ...
    "ValidationCommand", validationCommand);
diagnosisBundle = struct( ...
    "Schema", "obstacleAvoidanceSandboxDiagnosis-v1", ...
    "CreatedUTC", string(datetime( ...
        'now', 'TimeZone', 'UTC', ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSSXXX')), ...
    "Mode", modeName, ...
    "PlanningState", planningState, ...
    "HasPlannerResult", hasPlannerResult, ...
    "Environment", environment, ...
    "SandboxOptions", sandboxState.Options, ...
    "Scene", scene, ...
    "ExportRequest", exportRequest, ...
    "PlannerInputs", plannerInputs, ...
    "PlannerOptions", plannerOptions, ...
    "Result", result, ...
    "IndependentValidation", independentValidation, ...
    "SegmentResults", modeState.SegmentResults, ...
    "CombinedTrajectory", modeState.CombinedTrajectory, ...
    "Status", string(modeState.Status), ...
    "PlannerLog", string(modeState.PlannerLog), ...
    "Reproduction", reproduction);

%% Section 3: Save And Report The Export

save(char(absoluteFilePath), 'diagnosisBundle', '-v7.3');
fileRecord = dir(char(absoluteFilePath));
if isempty(fileRecord) || fileRecord.bytes <= 0
    error("exportSandboxDiagnosis:SaveVerificationFailed", ...
        "MATLAB returned from save, but no nonempty bundle exists at %s.", ...
        absoluteFilePath);
end
savedVariables = whos('-file', char(absoluteFilePath));
hasDiagnosisBundle = any(string({savedVariables.name}) == "diagnosisBundle");
if ~hasDiagnosisBundle
    error("exportSandboxDiagnosis:SaveVerificationFailed", ...
        "The MAT file at %s does not contain diagnosisBundle.", ...
        absoluteFilePath);
end
exportInfo = struct( ...
    "FilePath", absoluteFilePath, ...
    "Bytes", double(fileRecord.bytes), ...
    "Mode", modeName, ...
    "HasPlannerResult", hasPlannerResult, ...
    "PlannerSuccess", plannerSuccess, ...
    "TerminationReason", terminationReason, ...
    "Schema", diagnosisBundle.Schema);
end
