function exportInfo = exportSandboxDiagnosis( ...
        filePath, sandboxState, modeName)
%% Section 0: Header & Readme
% SYNTAX
%   exportInfo = exportSandboxDiagnosis( ...
%       filePath, sandboxState, modeName)
%**************************************************************************
% PURPOSE
%   - Save sandbox data in one MAT file for later fault investigation.
%   - Preserve a request before planning or evidence after planning.
%   - Preserve scene geometry, controls, logs, and reproduction commands.
%   - Exclude graphics handles and callbacks. They cannot reproduce a plan.
%**************************************************************************
% INPUTS
%   - filePath (scalar text)
%       Destination MAT file. A missing .mat extension is added. Existing
%       files are replaced only when the caller supplies that exact path.
%   - sandboxState (scalar struct)
%       Current value returned by sandboxState.ReadState().
%   - modeName (scalar text)
%       Only "goal" is supported.
%**************************************************************************
% OUTPUTS
%   - exportInfo (scalar struct)
%       Absolute path, byte count, mode, HasPlannerResult, planner status,
%       termination reason, and file-format version. An export before planning
%       reports notRun.
%**************************************************************************
% UNITS
%   - Preserved positions are in degrees. Time is in seconds.
%   - Derivatives use deg/s, deg/s^2, and deg/s^3.
%**************************************************************************

%% Section 1: Validate Destination And Sandbox State

% Validate the path before collecting a large bundle. Add .mat only when the
% caller omitted an extension. Do not create a missing folder because a typing
% error could otherwise save evidence in an unintended location.

filePath = string(filePath);
if ~isscalar(filePath) || ismissing(filePath) || strlength(filePath) == 0
    error("exportSandboxDiagnosis:InvalidFilePath", ...
        "filePath must be nonempty scalar text.");
end
modeName = lower(string(modeName));
if ~isscalar(modeName) || modeName ~= "goal"
    error("exportSandboxDiagnosis:InvalidMode", ...
        "modeName must be 'goal'.");
end
if ~isstruct(sandboxState) || ~isscalar(sandboxState)
    error("exportSandboxDiagnosis:InvalidState", ...
        "sandboxState must be the scalar struct returned by ReadState().");
end
requiredStateFields = {'Options', 'GoalMode'};
if ~all(isfield(sandboxState, requiredStateFields))
    error("exportSandboxDiagnosis:InvalidState", ...
        "sandboxState must contain Options and GoalMode.");
end

[destinationFolder, destinationName, destinationExtension] = ...
    fileparts(char(filePath));
if isempty(destinationExtension)
    destinationExtension = '.mat';
elseif ~strcmpi(destinationExtension, '.mat')
    error("exportSandboxDiagnosis:InvalidExtension", ...
        "filePath must use the .mat extension.");
end
if isempty(destinationFolder)
    destinationFolder = pwd;
end
if ~isfolder(destinationFolder)
    error("exportSandboxDiagnosis:MissingFolder", ...
        "Destination folder does not exist: %s", destinationFolder);
end
absoluteFilePath = string(fullfile( ...
    destinationFolder, [destinationName destinationExtension]));

%% Section 2: Build A Handle-Free Diagnosis Bundle

% Goal Mode is the sandbox's only supported workflow.
modeState = sandboxState.GoalMode;
requiredModeFields = { ...
    'StartPosition_deg', 'GoalPosition_deg', ...
    'RawObstacleStrokes_deg', ...
    'LineObstaclePositions_deg', 'PolygonObstaclePositions_deg', ...
    'CanonicalObstacles', ...
    'LastPlannerResult', 'LastValidation', 'Status', 'PlannerLog', ...
    'ResolvedControls'};
if ~isstruct(modeState) || ~isscalar(modeState) || ...
        ~all(isfield(modeState, requiredModeFields))
    error("exportSandboxDiagnosis:InvalidModeState", ...
        "The selected mode record does not have the stable sandbox format.");
end
result = modeState.LastPlannerResult;
hasPlannerResult = isstruct(result) && isscalar(result) && ...
    ~isempty(fieldnames(result));
if hasPlannerResult && ...
        (~isfield(result, "Inputs") || ~isfield(result, "Options"))
    error("exportSandboxDiagnosis:InvalidResult", ...
        "The retained planner result must contain Inputs and Options.");
end
if hasPlannerResult
    % A completed plan contains the exact normalized inputs and resolved
    % options. These values are the preferred reproduction data.
    planningState = "completed";
    plannerInputs = result.Inputs;
    plannerOptions = result.Options;
    independentValidation = modeState.LastValidation;
    plannerSuccess = logical(result.Success);
    terminationReason = string(result.TerminationReason);
    exportRequest = struct();
elseif isfield(modeState, "ExportRequest") && ...
        isstruct(modeState.ExportRequest) && ...
        isscalar(modeState.ExportRequest)
    planningState = "notRun";
    exportRequest = modeState.ExportRequest;
    plannerInputs = exportRequest.PlannerInputs;
    plannerOptions = exportRequest.PlannerOptions;
    independentValidation = obstacleAvoidance.validateTrajectory();
    plannerSuccess = false;
    terminationReason = "notRun";
else
    % Older or incomplete state can contain neither result nor request. Export
    % the available scene, but leave reproduction inputs empty and visible.
    planningState = "notRun";
    exportRequest = struct();
    plannerInputs = struct();
    plannerOptions = struct();
    independentValidation = obstacleAvoidance.validateTrajectory();
    plannerSuccess = false;
    terminationReason = "notRun";
end

% Keep raw strokes, simplified geometry, and protected obstacles. Compare
% these levels to find drawing simplification or safety-margin errors.
scene = struct( ...
    "StartPosition_deg", modeState.StartPosition_deg, ...
    "GoalPosition_deg", modeState.GoalPosition_deg, ...
    "RawObstacleStrokes_deg", {modeState.RawObstacleStrokes_deg}, ...
    "LineObstaclePositions_deg", ...
        {modeState.LineObstaclePositions_deg}, ...
    "PolygonObstaclePositions_deg", ...
        {modeState.PolygonObstaclePositions_deg}, ...
    "PolygonMotionVectors_deg", modeState.PolygonMotionVectors_deg, ...
    "PolygonMotionProfiles", modeState.PolygonMotionProfiles, ...
    "CanonicalObstacles", modeState.CanonicalObstacles, ...
    "ResolvedControls", modeState.ResolvedControls);
% Record the MATLAB environment. Geometry and optimization behavior can differ
% across MATLAB releases and operating systems.
environment = struct( ...
    "MATLABVersion", string(version), ...
    "MATLABRelease", string(version('-release')), ...
    "Computer", string(computer), ...
    "WorkingDirectory", string(pwd));
hasReplayableInputs = all(isfield(plannerInputs, ...
    {'obstacles', 'initialState', 'goalState', 'limits'}));
plannerCommand = "";
validationCommand = "";
if hasReplayableInputs
    % Store commands as guidance only. The exporter does not run the planner.
    % A developer can load the file and use these commands in a clean session.
    plannerCommand = ...
        "reproduced = obstacleAvoidance.planTrajectory(" + ...
        "diagnosisBundle.PlannerInputs.obstacles, " + ...
        "diagnosisBundle.PlannerInputs.initialState, " + ...
        "diagnosisBundle.PlannerInputs.goalState, " + ...
        "diagnosisBundle.PlannerInputs.limits, " + ...
        "diagnosisBundle.PlannerOptions);";
    validationCommand = ...
        "reproducedValidation = obstacleAvoidance.validateTrajectory(reproduced);";
end
reproduction = struct( ...
    "LoadCommand", ...
        "loaded = load(filePath, 'diagnosisBundle');", ...
    "PlannerCommand", plannerCommand, ...
    "ValidationCommand", validationCommand);
% Keep related data in named groups. First inspect PlanningState,
% Result.TerminationReason, IndependentValidation, and PlannerLog. Then use
% Scene and PlannerInputs to reproduce the exact request.
diagnosisBundle = struct( ...
    "Format", "obstacleAvoidanceSandboxDiagnosis-v2", ...
    "CreatedUTC", string(datetime( ...
        'now', 'TimeZone', 'UTC', ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSSXXX')), ...
    "Mode", modeName, ...
    "PlanningState", planningState, ...
    "HasPlannerResult", hasPlannerResult, ...
    "Environment", environment, ...
    "SandboxOptions", sandboxState.Options, ...
    "Scene", scene, ...
    "ExportRequest", exportRequest, ...
    "PlannerInputs", plannerInputs, ...
    "PlannerOptions", plannerOptions, ...
    "Result", result, ...
    "IndependentValidation", independentValidation, ...
    "Status", string(modeState.Status), ...
    "PlannerLog", string(modeState.PlannerLog), ...
    "Reproduction", reproduction);

%% Section 3: Save And Report The Export

% Use MAT-file version 7.3 because obstacle histories and diagnostics can be
% large. Verify both a nonempty file and the expected top-level variable. A
% successful return from save alone does not prove that useful data was written.

save(char(absoluteFilePath), 'diagnosisBundle', '-v7.3');
fileRecord = dir(char(absoluteFilePath));
if isempty(fileRecord) || fileRecord.bytes <= 0
    error("exportSandboxDiagnosis:SaveVerificationFailed", ...
        "MATLAB returned from save, but no nonempty bundle exists at %s.", ...
        absoluteFilePath);
end
savedVariables = whos('-file', char(absoluteFilePath));
hasDiagnosisBundle = any(string({savedVariables.name}) == "diagnosisBundle");
if ~hasDiagnosisBundle
    error("exportSandboxDiagnosis:SaveVerificationFailed", ...
        "The MAT file at %s does not contain diagnosisBundle.", ...
        absoluteFilePath);
end
exportInfo = struct( ...
    "FilePath", absoluteFilePath, ...
    "Bytes", double(fileRecord.bytes), ...
    "Mode", modeName, ...
    "HasPlannerResult", hasPlannerResult, ...
    "PlannerSuccess", plannerSuccess, ...
    "TerminationReason", terminationReason, ...
    "Format", diagnosisBundle.Format);
end
