function options = defaultOptions()
%% Section 0: Header & Readme
% SYNTAX
%   options = hs3Internal.defaultOptions()
%**************************************************************************
% PURPOSE
%   - Return the single source of argument-independent HS3 engine defaults.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - options (scalar struct)
%       Fixed/free-time mode, mesh, sampling, solver, and tolerance controls.
%**************************************************************************
% UNITS
%   - Time values use the caller's consistent time unit; coordinate
%     tolerances use the caller's consistent coordinate unit.
%**************************************************************************
options = struct( ...
    "TimeMode", "earliestArrival", ...
    "FinalTime", [], ...
    "SegmentCount", 10, ...
    "SampleTime", 0.05, ...
    "MaximumIterations", 300, ...
    "MaximumFunctionEvaluations", 30000, ...
    "MaximumSolveTime", 115, ...
    "ArrivalTimeTolerance", 1e-3, ...
    "ConstraintTolerance", 1e-7, ...
    "OptimalityTolerance", 1e-7, ...
    "StepTolerance", 1e-10, ...
    "Verbose", false);
end
