function search = buildAzElVisibilityRoutes( ...
        obstacleField, initialState, goalState, optionOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   search = buildAzElVisibilityRoutes( ...
%       obstacleField, initialState, goalState)
%   search = buildAzElVisibilityRoutes( ...
%       obstacleField, initialState, goalState, optionOverrides)
%**************************************************************************
% PURPOSE
%   - Build collision-checked visibility routes from a bounded candidate
%     set while retaining full protected polygons for collision validation.
%**************************************************************************
% INPUTS
%   - obstacleField (scalar packed obstacle field)
%       Output from buildAzElTimeObstacleField.
%   - initialState, goalState (scalar structs)
%       time_s and position_deg fields.
%   - optionOverrides (scalar struct, optional; default struct())
%       Internal search and reduction controls. UseParallel accepts
%       "auto", "on", "off", or a logical scalar and falls back to serial
%       execution when Parallel Computing Toolbox is unavailable.
%       RequiredSnapshotTimes_s adds only the source samples nearest the
%       requested adaptive-refinement times.
%       DetectSnapshotEvents promotes source slices when topology counts,
%       sampled edge rotation, or sampled edge motion crosses its threshold.
%       BuildFullVisibilityGraphs and BuildMergedVisibilityGraph are
%       internal stage controls used by the public planner's adaptive
%       dense-scene search.
%**************************************************************************
% OUTPUTS
%   - search (scalar struct)
%       VisibilityGraphs and CandidateReductionDiagnostics.
%**************************************************************************
% UNITS
%   - Position is degrees and time is seconds.
%**************************************************************************

%% Section 1: Resolve Options & Validate Inputs

if nargin < 4 || isempty(optionOverrides)
    optionOverrides = struct();
end
defaults = struct( ...
    "MaximumSnapshotsPerObstacle", Inf, ...
    "RequiredSnapshotTimes_s", zeros(0, 1), ...
    "DetectSnapshotEvents", true, ...
    "SnapshotProbeEdgeCount", 4, ...
    "SnapshotCountChangeThreshold", 0.10, ...
    "SnapshotEdgeRotationThreshold_deg", 5, ...
    "SnapshotBoundaryMotionThreshold_deg", 1, ...
    "CandidateClearance_deg", 0, ...
    "CornerAngleThreshold_deg", 15, ...
    "PolygonCandidateMode", "adaptive", ...
    "ExtremeDirectionCount", 16, ...
    "MaximumTangenciesPerReference", 2, ...
    "VisibilitySampleStep_deg", 0.10, ...
    "ConnectivityPathCostChangeThreshold", 0.05, ...
    "BuildFullVisibilityGraphs", true, ...
    "BuildMergedVisibilityGraph", true, ...
    "UseParallel", false, ...
    "Verbose", false);
if ~isstruct(optionOverrides) || ~isscalar(optionOverrides)
    error("buildAzElVisibilityRoutes:InvalidOptions", ...
        "optionOverrides must be a scalar struct.");
end
[options, unknownFields] = azElInternal.resolveOptions( ...
    defaults, optionOverrides);
if ~isempty(unknownFields)
    warning("buildAzElVisibilityRoutes:UnknownOptions", ...
        "Ignoring unknown option fields: %s. No behavior changed.", ...
        strjoin(unknownFields, ", "));
end
validateattributes(options.MaximumSnapshotsPerObstacle, {'numeric'}, ...
    {'real','scalar','positive'});
if isfinite(options.MaximumSnapshotsPerObstacle) && ...
        fix(options.MaximumSnapshotsPerObstacle) ~= ...
        options.MaximumSnapshotsPerObstacle
    error("buildAzElVisibilityRoutes:InvalidSnapshotLimit", ...
        "MaximumSnapshotsPerObstacle must be a positive integer or Inf.");
end
validateattributes(options.RequiredSnapshotTimes_s, {'numeric'}, ...
    {'real', 'finite', 'vector'});
options.RequiredSnapshotTimes_s = ...
    unique(double(options.RequiredSnapshotTimes_s(:)));
logicalOptionNames = ["DetectSnapshotEvents" ...
    "BuildFullVisibilityGraphs" "BuildMergedVisibilityGraph" "Verbose"];
for logicalOptionIndex = 1:numel(logicalOptionNames)
    optionName = logicalOptionNames(logicalOptionIndex);
    options.(optionName) = azElInternal.normalizeLogicalScalar( ...
        options.(optionName), optionName, ...
        "buildAzElVisibilityRoutes:InvalidLogicalOption");
end
validateattributes(options.SnapshotProbeEdgeCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'positive'});
validateattributes(options.SnapshotCountChangeThreshold, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'});
validateattributes(options.SnapshotEdgeRotationThreshold_deg, ...
    {'numeric'}, {'real', 'scalar', 'nonnegative'});
validateattributes(options.SnapshotBoundaryMotionThreshold_deg, ...
    {'numeric'}, {'real', 'scalar', 'nonnegative'});
validateattributes(options.CandidateClearance_deg, {'numeric'}, ...
    {'scalar','real','finite','nonnegative'});
polygonCandidateMode = lower(string(options.PolygonCandidateMode));
if ~isscalar(polygonCandidateMode) || ~any( ...
        polygonCandidateMode == ["adaptive" "allcorners" "extreme"])
    error("buildAzElVisibilityRoutes:InvalidPolygonCandidateMode", ...
        "PolygonCandidateMode must be adaptive, allCorners, or extreme.");
end
if polygonCandidateMode == "allcorners"
    options.PolygonCandidateMode = "allCorners";
else
    options.PolygonCandidateMode = polygonCandidateMode;
end
validateattributes(options.ExtremeDirectionCount, {'numeric'}, ...
    {'scalar','integer','>=',4});
validateattributes(options.MaximumTangenciesPerReference, {'numeric'}, ...
    {'scalar','integer','nonnegative'});
validateattributes(options.VisibilitySampleStep_deg, {'numeric'}, ...
    {'scalar','real','finite','positive'});
validateattributes(options.ConnectivityPathCostChangeThreshold, ...
    {'numeric'}, {'scalar', 'real', 'finite', '>=', 0, '<=', 1});
options.UseParallel = azElInternal.normalizeParallelMode( ...
    options.UseParallel, ...
    "buildAzElVisibilityRoutes:InvalidUseParallel");
fieldIsPacked = isstruct(obstacleField) && isscalar(obstacleField) && ...
    isfield(obstacleField, "Format") && ...
    string(obstacleField.Format) == "AzElTimeObstacleField";
if ~fieldIsPacked
    error("buildAzElVisibilityRoutes:InvalidObstacleField", ...
        "obstacleField must come from buildAzElTimeObstacleField.");
end

%% Section 2: Select Snapshots & Boundary Candidates

snapshotSelection = azElInternal.selectAzElVisibilitySnapshots( ...
    obstacleField, initialState, goalState, options);
candidatePoints = snapshotSelection.CandidatePointsAzElTime;
candidateObstacleIndex = snapshotSelection.CandidateObstacleIndex;
candidateSampleIndex = snapshotSelection.CandidateSampleIndex;
candidateRegionIndex = snapshotSelection.CandidateRegionIndex;
snapshotDiagnostics = snapshotSelection.SnapshotDiagnostics;
candidateReductionDiagnostics = ...
    snapshotSelection.CandidateReductionDiagnostics;

%% Section 3: Build Snapshot Visibility Graphs

[visibilityGraphs, mergedGraphCandidates, parallelExecution] = ...
    azElInternal.buildAzElSnapshotVisibilityGraphs( ...
    obstacleField, snapshotSelection, options);
[mergedVisibilityGraphs, obstacleMergeDiagnostics] = ...
    selectMergedObstacleGraph(mergedGraphCandidates);
[connectivityDiagnostics, connectivityChangeIntervals] = ...
    visibilityConnectivityDiagnostics(visibilityGraphs, ...
    options.ConnectivityPathCostChangeThreshold);
for graphIndex = 1:numel(visibilityGraphs)
    activeCandidate = visibilityGraphs(graphIndex).NodeCandidateIndex(3:end);
    activeCandidate = activeCandidate( ...
        visibilityGraphs(graphIndex).CandidateActiveMask);
    for diagnosticIndex = 1:numel(candidateReductionDiagnostics)
        diagnostic = candidateReductionDiagnostics(diagnosticIndex);
        belongs = candidateObstacleIndex == diagnostic.ObstacleIndex & ...
            candidateSampleIndex == diagnostic.SampleIndex & ...
            candidateRegionIndex == diagnostic.RegionIndex;
        activeCount = nnz(ismember(find(belongs), activeCandidate));
        candidateReductionDiagnostics(diagnosticIndex). ...
            GraphActiveCandidateCount = activeCount;
        if diagnostic.SelectedCandidateCount > 0
            candidateReductionDiagnostics(diagnosticIndex). ...
                RelevanceReductionPercent = 100 * ...
                (1 - activeCount / diagnostic.SelectedCandidateCount);
        end
    end
end

%% Section 4: Assemble Search Diagnostics

search = struct( ...
    "VisibilityGraphs", visibilityGraphs, ...
    "MergedVisibilityGraphs", mergedVisibilityGraphs, ...
    "ObstacleMergeDiagnostics", obstacleMergeDiagnostics, ...
    "ConnectivityDiagnostics", connectivityDiagnostics, ...
    "ConnectivityChangeIntervals", connectivityChangeIntervals, ...
    "SnapshotDiagnostics", snapshotDiagnostics, ...
    "CandidateReductionDiagnostics", candidateReductionDiagnostics, ...
    "CandidatePointsAzElTime", candidatePoints, ...
    "ParallelExecution", parallelExecution, ...
    "Options", options);
end

%% Section 5: Local Functions

function [selectedGraph, diagnostics] = ...
        selectMergedObstacleGraph(graphCandidates)
%% Section 0: Header & Readme
% SYNTAX
%   [selectedGraph, diagnostics] = ...
%       selectMergedObstacleGraph(graphCandidates)
%**************************************************************************
% PURPOSE
%   - Retain the shortest successful sparse merged graph so a dense
%     obstacle history adds one bounded planner contender.
%**************************************************************************
% INPUTS
%   - graphCandidates (structure array)
%       Dense-snapshot conservative merge attempts.
%**************************************************************************
% OUTPUTS
%   - selectedGraph (empty or scalar structure array)
%   - diagnostics (scalar struct)
%       Attempt, success, selection, and reduction counts.
%**************************************************************************
% UNITS
%   - Path cost is degrees and selected time is seconds.
%**************************************************************************
selectedGraph = graphCandidates([]);
successfulIndex = find([graphCandidates.Success] & ...
    [graphCandidates.ObstacleMergeComplete]);
selectedCandidateIndex = 0;
if ~isempty(successfulIndex)
    pathCost_deg = [graphCandidates(successfulIndex).PathCost_deg];
    [~, localIndex] = min(pathCost_deg);
    selectedCandidateIndex = successfulIndex(localIndex);
    selectedGraph = graphCandidates(selectedCandidateIndex);
end

selectedTime_s = NaN;
selectedSourceObstacleCount = 0;
selectedMaximumGraphObstacleCount = 0;
selectedMergedGroupCount = 0;
selectedGraphObstacleCount = 0;
if ~isempty(selectedGraph)
    selectedTime_s = selectedGraph.Time_s;
    selectedSourceObstacleCount = selectedGraph.SourceObstacleCount;
    selectedMaximumGraphObstacleCount = ...
        selectedGraph.MaximumGraphObstacleCount;
    selectedMergedGroupCount = selectedGraph.MergedGroupCount;
    selectedGraphObstacleCount = selectedGraph.GraphObstacleCount;
end
diagnostics = struct( ...
    "ThresholdObstacleCount", 4, ...
    "AttemptedGraphCount", numel(graphCandidates), ...
    "SuccessfulGraphCount", numel(successfulIndex), ...
    "SelectedCandidateIndex", selectedCandidateIndex, ...
    "SelectedTime_s", selectedTime_s, ...
    "SelectedSourceObstacleCount", selectedSourceObstacleCount, ...
    "SelectedMaximumGraphObstacleCount", ...
    selectedMaximumGraphObstacleCount, ...
    "SelectedMergedGroupCount", selectedMergedGroupCount, ...
    "SelectedGraphObstacleCount", selectedGraphObstacleCount, ...
    "Selected", ~isempty(selectedGraph));
end

function [diagnostics, changeIntervals] = ...
        visibilityConnectivityDiagnostics(visibilityGraphs, ...
        pathCostChangeThreshold)
%% Section 0: Header & Readme
% SYNTAX
%   [diagnostics, changeIntervals] = ...
%       visibilityConnectivityDiagnostics( ...
%       visibilityGraphs, pathCostChangeThreshold)
%**************************************************************************
% PURPOSE
%   - Detect graph splits, merges, and start-to-goal connectivity changes
%     that make an adjacent time interval valuable for refinement.
%**************************************************************************
% INPUTS
%   - visibilityGraphs (structure array)
%       Snapshot graphs with finite EdgeCost_deg entries for usable edges.
%   - pathCostChangeThreshold (scalar from zero through one)
%       Relative adjacent shortest-path change treated as significant.
%**************************************************************************
% OUTPUTS
%   - diagnostics (structure array)
%       Per-snapshot component count and endpoint connectivity.
%   - changeIntervals (structure array)
%       Adjacent time intervals whose connectivity signature changed.
%**************************************************************************
% UNITS
%   - Snapshot and interval times are seconds; graph counts are unitless.
%**************************************************************************
diagnosticTemplate = struct( ...
    "Time_s", NaN, ...
    "ConsideredNodeCount", 0, ...
    "ConnectedComponentCount", 0, ...
    "StartComponentSize", 0, ...
    "GoalComponentSize", 0, ...
    "StartGoalConnected", false, ...
    "DirectEdgeAvailable", false, ...
    "ShortestPathCost_deg", Inf);
diagnostics = repmat(diagnosticTemplate, numel(visibilityGraphs), 1);

for snapshotIndex = 1:numel(visibilityGraphs)
    visibilityGraph = visibilityGraphs(snapshotIndex);
    consideredNode = [true; true; ...
        visibilityGraph.CandidateActiveMask(:)];
    edgeAvailable = isfinite(visibilityGraph.EdgeCost_deg);
    edgeAvailable = edgeAvailable(consideredNode, consideredNode);
    edgeAvailable(1:size(edgeAvailable, 1) + 1:end) = false;
    componentGraph = graph(edgeAvailable, 'upper');
    componentIndex = conncomp(componentGraph).';
    componentCount = max(componentIndex);
    if isempty(componentCount)
        componentCount = 0;
    end

    diagnostic = diagnosticTemplate;
    diagnostic.Time_s = visibilityGraph.Time_s;
    diagnostic.ConsideredNodeCount = nnz(consideredNode);
    diagnostic.ConnectedComponentCount = componentCount;
    diagnostic.DirectEdgeAvailable = ...
        size(visibilityGraph.EdgeCost_deg, 1) >= 2 && ...
        isfinite(visibilityGraph.EdgeCost_deg(1, 2));
    diagnostic.ShortestPathCost_deg = visibilityGraph.PathCost_deg;
    if numel(componentIndex) >= 2
        startComponent = componentIndex(1);
        goalComponent = componentIndex(2);
        diagnostic.StartComponentSize = nnz( ...
            componentIndex == startComponent);
        diagnostic.GoalComponentSize = nnz( ...
            componentIndex == goalComponent);
        diagnostic.StartGoalConnected = ...
            startComponent == goalComponent;
    end
    diagnostics(snapshotIndex) = diagnostic;
end

intervalTemplate = struct( ...
    "EarlierTime_s", NaN, ...
    "LaterTime_s", NaN, ...
    "ComponentCountChanged", false, ...
    "StartGoalConnectivityChanged", false, ...
    "DirectEdgeAvailabilityChanged", false, ...
    "ShortestPathCostChangedSignificantly", false, ...
    "Significant", false);
changeIntervals = repmat(intervalTemplate, 0, 1);

for intervalIndex = 1:max(0, numel(diagnostics) - 1)
    earlier = diagnostics(intervalIndex);
    later = diagnostics(intervalIndex + 1);
    componentCountChanged = earlier.ConnectedComponentCount ~= ...
        later.ConnectedComponentCount;
    endpointConnectivityChanged = earlier.StartGoalConnected ~= ...
        later.StartGoalConnected;
    directEdgeChanged = earlier.DirectEdgeAvailable ~= ...
        later.DirectEdgeAvailable;
    finitePathPair = isfinite(earlier.ShortestPathCost_deg) && ...
        isfinite(later.ShortestPathCost_deg);
    pathCostChanged = finitePathPair && abs( ...
        later.ShortestPathCost_deg - earlier.ShortestPathCost_deg) > ...
        pathCostChangeThreshold * max( ...
        1, min(earlier.ShortestPathCost_deg, ...
        later.ShortestPathCost_deg));
    if ~(componentCountChanged || endpointConnectivityChanged || ...
            directEdgeChanged || pathCostChanged)
        continue;
    end
    interval = intervalTemplate;
    interval.EarlierTime_s = earlier.Time_s;
    interval.LaterTime_s = later.Time_s;
    interval.ComponentCountChanged = componentCountChanged;
    interval.StartGoalConnectivityChanged = ...
        endpointConnectivityChanged;
    interval.DirectEdgeAvailabilityChanged = directEdgeChanged;
    interval.ShortestPathCostChangedSignificantly = pathCostChanged;
    interval.Significant = true;
    changeIntervals(end + 1, 1) = interval; %#ok<AGROW>
end
end
