function result = planAzElMovingTargetIntercept( ...
        initialState, targetMotion, limits, optionOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   options = planAzElMovingTargetIntercept()
%   result = planAzElMovingTargetIntercept( ...
%       initialState, targetMotion, limits, options)
%**************************************************************************
% PURPOSE
%   - Resolve a linearly moving target into the earliest feasible or a
%     specified intercept state, then use planAzElMotion for the command.
%   - Support obstacle-free azimuth/elevation intercept demonstrations
%     without introducing a second retiming implementation.
%**************************************************************************
% INPUTS
%   - initialState (scalar struct)
%       time_s, position_deg, and optional velocity/acceleration fields.
%   - targetMotion (scalar struct)
%       referenceTime_s, referencePosition_deg, and velocity_deg_s.
%   - limits (scalar struct)
%       Limits accepted by planAzElMotion.
%   - options (scalar struct, optional)
%       .InterceptMode             "earliestArrival" or "specifiedTime"
%       .SpecifiedInterceptTime_s  required for specifiedTime
%       .MaximumSearchDuration_s   earliest-intercept horizon (60)
%       .InitialSearchStep_s       first bracket duration (0.5)
%       .SearchTimeTolerance_s     earliest-time tolerance (1e-4)
%       .MaximumSearchIterations   bisection limit (60)
%       .MatchTargetVelocity       match target angular rate (true)
%       .TargetTrackSampleCount    plot samples (121)
%       .PlannerOptions            planAzElMotion option overrides
%     Earliest mode requires a target that recedes on one straight ray
%     from the initial position so the first feasibility transition is
%     unique and the bisection certificate is meaningful. It also
%     requires a stationary initial state because the maintained fixed-
%     arrival retimers express schedule slack as an initial hold.
%     Velocity matching requires target velocity tangent to the direct
%     obstacle-free route; disable MatchTargetVelocity for position-only
%     interception of a general linear target.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Normal planner result augmented with target, search, intercept,
%       validation, and target-track plot diagnostics.
%**************************************************************************
% UNITS
%   - Angles are degrees; time is seconds; velocity is deg/s.

defaultOptions = struct( ...
    "InterceptMode", "earliestArrival", ...
    "SpecifiedInterceptTime_s", NaN, ...
    "MaximumSearchDuration_s", 60, ...
    "InitialSearchStep_s", 0.5, ...
    "SearchTimeTolerance_s", 1e-4, ...
    "MaximumSearchIterations", 60, ...
    "MatchTargetVelocity", true, ...
    "TargetTrackSampleCount", 121, ...
    "PlannerOptions", struct());
if nargin == 0
    result = defaultOptions;
    return;
end
if nargin < 4 || isempty(optionOverrides)
    optionOverrides = struct();
end
options = resolveInterceptOptions(defaultOptions, optionOverrides);
initialState = validateInterceptInitialState(initialState);
targetMotion = validateLinearTargetMotion(targetMotion);

%% Section 1: Resolve The Concrete Intercept State
interceptMode = lower(string(options.InterceptMode));
searchDiagnostics = emptyInterceptSearchDiagnostics();
if interceptMode == "specifiedtime"
    interceptTime_s = options.SpecifiedInterceptTime_s;
    validateattributes(interceptTime_s, {'numeric'}, ...
        {'real', 'finite', 'scalar', '>', initialState.time_s});
    searchDiagnostics.Message = ...
        "The caller supplied the intercept time; no search was required.";
else
    validateEarliestTargetGeometry(initialState, targetMotion);
    validateEarliestInitialVelocity(initialState);
    [interceptTime_s, searchDiagnostics] = ...
        searchEarliestInterceptTime(initialState, targetMotion, ...
        limits, options);
end
interceptPosition_deg = linearTargetPosition( ...
    targetMotion, interceptTime_s);
validateVelocityMatchGeometry(initialState, interceptPosition_deg, ...
    targetMotion, options.MatchTargetVelocity);
goalVelocity_deg_s = [0 0];
if options.MatchTargetVelocity
    goalVelocity_deg_s = targetMotion.velocity_deg_s;
end
goalState = struct( ...
    "time_s", interceptTime_s, ...
    "position_deg", interceptPosition_deg, ...
    "velocity_deg_s", goalVelocity_deg_s, ...
    "acceleration_deg_s2", [0 0]);

%% Section 2: Run The Maintained Obstacle-Free Planner
plannerOptions = options.PlannerOptions;
plannerDefaultOptions = planAzElMotion();
animationRequested = logical(plannerDisplayOption( ...
    plannerOptions, plannerDefaultOptions, "ShowAnimation"));
figureVisible = plannerDisplayOption( ...
    plannerOptions, plannerDefaultOptions, "FigureVisible");
animationFrameStride = plannerDisplayOption( ...
    plannerOptions, plannerDefaultOptions, "AnimationFrameStride");
animationPause_s = plannerDisplayOption( ...
    plannerOptions, plannerDefaultOptions, "AnimationPause_s");
showSweptSurfaces = plannerDisplayOption( ...
    plannerOptions, plannerDefaultOptions, "ShowSweptSurfaces");
maximumDisplayedSlices = plannerDisplayOption( ...
    plannerOptions, plannerDefaultOptions, ...
    "MaximumDisplayedSlicesPerObstacle");
plannerTitle = string(plannerDisplayOption( ...
    plannerOptions, plannerDefaultOptions, "Title"));
plannerOptions.GoalTimeMode = "fixedArrival";
% The wrapper supplies the final animation itself so the target and the
% pursuer advance on the same timeline.
plannerOptions.ShowAnimation = false;
result = planAzElMotion([], initialState, goalState, limits, ...
    plannerOptions);
plannerSucceeded = result.Success;

trackTime_s = linspace(initialState.time_s, interceptTime_s, ...
    options.TargetTrackSampleCount).';
trackPosition_deg = linearTargetPosition(targetMotion, trackTime_s);
if plannerSucceeded && animationRequested
    if lower(string(figureVisible)) == "off"
        animationPause_s = 0;
    end
    result.animation = animateAzElTimedSlopePath( ...
        result.timedSlopePath, result.obstacleField, struct( ...
        "FigureVisible", figureVisible, ...
        "FrameStride", animationFrameStride, ...
        "Pause_s", animationPause_s, ...
        "ShowSweptSurfaces", showSweptSurfaces, ...
        "MaximumDisplayedSlicesPerObstacle", ...
        maximumDisplayedSlices, ...
        "TargetTime_s", trackTime_s, ...
        "TargetPosition_deg", trackPosition_deg, ...
        "TargetLabel", "Moving target", ...
        "Title", plannerTitle + " animation"));
end
result.Options.ShowAnimation = animationRequested;

%% Section 3: Validate The Intercept Contract
targetPositionAtIntercept_deg = interceptPosition_deg;
positionError_deg = Inf;
targetVelocityError_deg_s = Inf;
requestedVelocityError_deg_s = Inf;
timeError_s = Inf;
positionMatched = false;
targetVelocityMatched = false;
requestedVelocityMatched = false;
timeMatched = false;
hasTimedEndpoint = plannerSucceeded && ...
    isfield(result, "timedSlopePath") && ...
    ~isempty(result.timedSlopePath.position_deg) && ...
    ~isempty(result.timedSlopePath.velocity_deg_s) && ...
    isfinite(result.goalLineInterceptTime_s);
if hasTimedEndpoint
    targetPositionAtIntercept_deg = linearTargetPosition( ...
        targetMotion, result.goalLineInterceptTime_s);
    actualTerminalPosition_deg = ...
        result.timedSlopePath.position_deg(end, :);
    actualTerminalVelocity_deg_s = ...
        result.timedSlopePath.velocity_deg_s(end, :);
    positionError_deg = norm( ...
        actualTerminalPosition_deg - targetPositionAtIntercept_deg);
    targetVelocityError_deg_s = norm( ...
        actualTerminalVelocity_deg_s - targetMotion.velocity_deg_s);
    requestedVelocityError_deg_s = norm( ...
        actualTerminalVelocity_deg_s - goalVelocity_deg_s);
    timeError_s = abs( ...
        result.goalLineInterceptTime_s - interceptTime_s);
    positionMatched = positionError_deg <= 1e-7;
    targetVelocityMatched = targetVelocityError_deg_s <= 1e-7;
    requestedVelocityMatched = requestedVelocityError_deg_s <= 1e-7;
    timeMatched = timeError_s <= ...
        max(1e-7, options.SearchTimeTolerance_s);
end
velocityRequirementSatisfied = requestedVelocityMatched;
earliestCertified = interceptMode == "specifiedtime" || ...
    searchDiagnostics.EarliestCertified;
interceptPassed = result.Success && positionMatched && ...
    velocityRequirementSatisfied && timeMatched && earliestCertified;
validationMessage = "Moving-target intercept validation passed.";
if ~interceptPassed
    validationMessage = "Moving-target intercept validation failed.";
end
interceptValidation = struct( ...
    "Passed", interceptPassed, ...
    "PlannerPassed", result.Success, ...
    "TargetPositionMatched", positionMatched, ...
    "VelocityMatchRequired", options.MatchTargetVelocity, ...
    "TargetVelocityMatched", targetVelocityMatched, ...
    "RequestedVelocityMatched", requestedVelocityMatched, ...
    "VelocityRequirementSatisfied", velocityRequirementSatisfied, ...
    "InterceptTimeMatched", timeMatched, ...
    "EarliestCertified", earliestCertified, ...
    "PositionError_deg", positionError_deg, ...
    "VelocityError_deg_s", targetVelocityError_deg_s, ...
    "RequestedVelocityError_deg_s", requestedVelocityError_deg_s, ...
    "TimeError_s", timeError_s, ...
    "Message", validationMessage);
result.Success = interceptPassed;
if ~interceptPassed
    result.Message = string(result.Message) + " " + validationMessage;
end

%% Section 4: Draw The Moving Target World Line
targetTrackHandles = struct( ...
    "TimeSpace", gobjects(0, 1), ...
    "Intercept", gobjects(0, 1), ...
    "Animation3D", gobjects(0, 1), ...
    "Animation2D", gobjects(0, 1));
if isfield(result, "spaceView") && ...
        isgraphics(result.spaceView.Axes)
    targetTrackHandles.TimeSpace = plot3(result.spaceView.Axes, ...
        trackPosition_deg(:, 1), trackPosition_deg(:, 2), trackTime_s, ...
        "-.", "Color", [0.72 0.10 0.72], "LineWidth", 2.3, ...
        "DisplayName", "Moving target");
    targetTrackHandles.Intercept = plot3(result.spaceView.Axes, ...
        interceptPosition_deg(1), interceptPosition_deg(2), ...
        interceptTime_s, "p", "MarkerSize", 13, ...
        "MarkerFaceColor", [0.95 0.30 0.82], ...
        "MarkerEdgeColor", "k", "DisplayName", "Intercept");
    legend(result.spaceView.Axes, "Location", "best");
end
if isfield(result, "animation") && isstruct(result.animation) && ...
        isfield(result.animation, "Axes3D") && ...
        isgraphics(result.animation.Axes3D)
    targetTrackHandles.Animation3D = ...
        result.animation.TargetWorldLine3D;
    targetTrackHandles.Animation2D = ...
        result.animation.TargetWorldLine2D;
end

result.InterceptMode = options.InterceptMode;
result.TargetMotion = targetMotion;
result.RequestedInterceptTime_s = options.SpecifiedInterceptTime_s;
result.InterceptTime_s = interceptTime_s;
result.InterceptPosition_deg = interceptPosition_deg;
result.TargetPositionAtIntercept_deg = targetPositionAtIntercept_deg;
result.TargetVelocityAtIntercept_deg_s = targetMotion.velocity_deg_s;
result.SearchDiagnostics = searchDiagnostics;
result.InterceptValidation = interceptValidation;
result.TargetTrackTime_s = trackTime_s;
result.TargetTrackPosition_deg = trackPosition_deg;
result.TargetTrackHandles = targetTrackHandles;
result.InterceptOptions = options;
end

function options = resolveInterceptOptions(defaultOptions, overrides)
%% Section 0: Header & Readme
% Resolve and validate public intercept controls.
if ~isstruct(overrides) || ~isscalar(overrides)
    error("planAzElMovingTargetIntercept:InvalidOptions", ...
        "options must be a scalar struct.");
end
unknownFields = setdiff( ...
    fieldnames(overrides), fieldnames(defaultOptions), "stable");
if ~isempty(unknownFields)
    warning("planAzElMovingTargetIntercept:UnknownOptions", ...
        "Ignoring unknown option fields: %s.", ...
        strjoin(string(unknownFields), ", "));
    overrides = rmfield(overrides, unknownFields);
end
options = defaultOptions;
overrideFields = fieldnames(overrides);
for fieldIndex = 1:numel(overrideFields)
    fieldName = overrideFields{fieldIndex};
    if ~isempty(overrides.(fieldName))
        options.(fieldName) = overrides.(fieldName);
    end
end
options.InterceptMode = lower(string(options.InterceptMode));
if ~isscalar(options.InterceptMode) || ~any( ...
        options.InterceptMode == ["earliestarrival" "specifiedtime"])
    error("planAzElMovingTargetIntercept:InvalidMode", ...
        "InterceptMode must be earliestArrival or specifiedTime.");
end
validateattributes(options.MaximumSearchDuration_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
validateattributes(options.InitialSearchStep_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
validateattributes(options.SearchTimeTolerance_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
if options.SearchTimeTolerance_s > options.MaximumSearchDuration_s
    error("planAzElMovingTargetIntercept:InvalidSearchTolerance", ...
        "SearchTimeTolerance_s cannot exceed MaximumSearchDuration_s.");
end
validateattributes(options.MaximumSearchIterations, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'positive'});
validateattributes(options.TargetTrackSampleCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 2});
validateattributes(options.MatchTargetVelocity, ...
    {'logical', 'numeric'}, {'scalar'});
options.MatchTargetVelocity = logical(options.MatchTargetVelocity);
if ~isstruct(options.PlannerOptions) || ~isscalar(options.PlannerOptions)
    error("planAzElMovingTargetIntercept:InvalidPlannerOptions", ...
        "PlannerOptions must be a scalar struct.");
end
end

function initialState = validateInterceptInitialState(initialState)
%% Section 0: Header & Readme
% Validate the state fields needed before the maintained planner runs.
if ~isstruct(initialState) || ~isscalar(initialState) || ...
        ~all(isfield(initialState, ["time_s" "position_deg"]))
    error("planAzElMovingTargetIntercept:InvalidInitialState", ...
        "initialState must contain time_s and position_deg.");
end
validateattributes(initialState.time_s, {'numeric'}, ...
    {'real', 'finite', 'scalar'});
validateattributes(initialState.position_deg, {'numeric'}, ...
    {'real', 'finite', 'vector', 'numel', 2});
initialState.time_s = double(initialState.time_s);
initialState.position_deg = reshape( ...
    double(initialState.position_deg), 1, 2);
end

function targetMotion = validateLinearTargetMotion(targetMotion)
%% Section 0: Header & Readme
% Validate and normalize one constant-angular-velocity target model.
requiredFields = ["referenceTime_s" ...
    "referencePosition_deg" "velocity_deg_s"];
if ~isstruct(targetMotion) || ~isscalar(targetMotion) || ...
        ~all(isfield(targetMotion, requiredFields))
    error("planAzElMovingTargetIntercept:InvalidTargetMotion", ...
        "targetMotion must contain referenceTime_s, " + ...
        "referencePosition_deg, and velocity_deg_s.");
end
validateattributes(targetMotion.referenceTime_s, {'numeric'}, ...
    {'real', 'finite', 'scalar'});
validateattributes(targetMotion.referencePosition_deg, {'numeric'}, ...
    {'real', 'finite', 'vector', 'numel', 2});
validateattributes(targetMotion.velocity_deg_s, {'numeric'}, ...
    {'real', 'finite', 'vector', 'numel', 2});
targetMotion.referenceTime_s = double(targetMotion.referenceTime_s);
targetMotion.referencePosition_deg = reshape( ...
    double(targetMotion.referencePosition_deg), 1, 2);
targetMotion.velocity_deg_s = reshape( ...
    double(targetMotion.velocity_deg_s), 1, 2);
end

function position_deg = linearTargetPosition(targetMotion, queryTime_s)
%% Section 0: Header & Readme
% Evaluate a constant-angular-velocity target at arbitrary times.
queryTime_s = double(queryTime_s(:));
position_deg = targetMotion.referencePosition_deg + ...
    (queryTime_s - targetMotion.referenceTime_s) .* ...
    targetMotion.velocity_deg_s;
end

function validateEarliestTargetGeometry(initialState, targetMotion)
%% Section 0: Header & Readme
% Require the monotone receding geometry certified by the root search.
targetAtStart_deg = linearTargetPosition( ...
    targetMotion, initialState.time_s);
lineOfSight_deg = targetAtStart_deg - initialState.position_deg;
lineOfSightLength_deg = norm(lineOfSight_deg);
if lineOfSightLength_deg <= 1e-10
    error("planAzElMovingTargetIntercept:InitialCoincidence", ...
        "The target is already at the initial position.");
end
targetSpeed_deg_s = norm(targetMotion.velocity_deg_s);
crossProduct_deg2_s = ...
    lineOfSight_deg(1) * targetMotion.velocity_deg_s(2) - ...
    lineOfSight_deg(2) * targetMotion.velocity_deg_s(1);
collinearityScale = max(1, ...
    lineOfSightLength_deg * max(1, targetSpeed_deg_s));
isCollinear = abs(crossProduct_deg2_s) <= 1e-10 * collinearityScale;
isReceding = dot(lineOfSight_deg, targetMotion.velocity_deg_s) >= -1e-10;
if ~isCollinear || ~isReceding
    error("planAzElMovingTargetIntercept:EarliestRequiresRecedingRay", ...
        "Earliest mode requires a target receding on a straight ray " + ...
        "from initialState.position_deg. For a general linear target, " + ...
        "use specifiedTime with MatchTargetVelocity=false.");
end
end

function validateEarliestInitialVelocity(initialState)
%% Section 0: Header & Readme
% Expose the current fixed-arrival retimer's scheduling limitation early.
initialVelocity_deg_s = [0 0];
if isfield(initialState, "velocity_deg_s") && ...
        ~isempty(initialState.velocity_deg_s)
    validateattributes(initialState.velocity_deg_s, {'numeric'}, ...
        {'real', 'finite', 'vector', 'numel', 2});
    initialVelocity_deg_s = reshape( ...
        double(initialState.velocity_deg_s), 1, 2);
end
if norm(initialVelocity_deg_s) > 1e-12
    error("planAzElMovingTargetIntercept:EarliestRequiresInitialRest", ...
        "Earliest intercept currently requires zero initial velocity " + ...
        "because final scheduling may use a short initial hold.");
end
end

function validateVelocityMatchGeometry( ...
        initialState, interceptPosition_deg, targetMotion, matchVelocity)
%% Section 0: Header & Readme
% A direct obstacle-free route can match only a tangent terminal velocity.
if ~matchVelocity || norm(targetMotion.velocity_deg_s) <= 1e-12
    return;
end
routeVector_deg = interceptPosition_deg - initialState.position_deg;
routeLength_deg = norm(routeVector_deg);
if routeLength_deg <= 1e-12
    error("planAzElMovingTargetIntercept:VelocityMatchNeedsRoute", ...
        "A zero-length intercept cannot match nonzero target velocity.");
end
crossProduct_deg2_s = ...
    routeVector_deg(1) * targetMotion.velocity_deg_s(2) - ...
    routeVector_deg(2) * targetMotion.velocity_deg_s(1);
alignmentScale = max(1, ...
    routeLength_deg * max(1, norm(targetMotion.velocity_deg_s)));
isTangent = abs(crossProduct_deg2_s) <= 1e-10 * alignmentScale;
isForward = dot(routeVector_deg, targetMotion.velocity_deg_s) >= -1e-12;
if ~isTangent || ~isForward
    error("planAzElMovingTargetIntercept:TargetVelocityNotTangent", ...
        "Target velocity must be forward-tangent to the direct route " + ...
        "when MatchTargetVelocity=true. Set MatchTargetVelocity=false " + ...
        "for a position-only intercept.");
end
end

function [interceptTime_s, diagnostics] = searchEarliestInterceptTime( ...
        initialState, targetMotion, limits, options)
%% Section 0: Header & Readme
% Bracket and bisect the first time at which the target is reachable.
searchStartTime_s = initialState.time_s;
searchEndTime_s = initialState.time_s + ...
    options.MaximumSearchDuration_s;
lowerTime_s = searchStartTime_s;
[lowerResidual_s, lowerArrivalTime_s] = interceptResidual( ...
    lowerTime_s, searchEndTime_s, initialState, targetMotion, ...
    limits, options);
upperTime_s = lowerTime_s;
upperResidual_s = lowerResidual_s;
upperArrivalTime_s = lowerArrivalTime_s;
bracketStep_s = options.InitialSearchStep_s;
bracketEvaluationCount = 1;
while upperResidual_s > 0 && upperTime_s < searchEndTime_s
    upperTime_s = min(searchEndTime_s, ...
        initialState.time_s + bracketStep_s);
    [upperResidual_s, upperArrivalTime_s] = interceptResidual( ...
        upperTime_s, searchEndTime_s, initialState, targetMotion, ...
        limits, options);
    bracketEvaluationCount = bracketEvaluationCount + 1;
    if upperResidual_s > 0
        lowerTime_s = upperTime_s;
        lowerResidual_s = upperResidual_s;
        lowerArrivalTime_s = upperArrivalTime_s;
        bracketStep_s = 2 * bracketStep_s;
    end
end
if upperResidual_s > 0
    error("planAzElMovingTargetIntercept:NoInterceptInHorizon", ...
        "No feasible intercept was found within %.6g seconds.", ...
        options.MaximumSearchDuration_s);
end

iterationCount = 0;
while upperTime_s - lowerTime_s > ...
        options.SearchTimeTolerance_s && ...
        iterationCount < options.MaximumSearchIterations
    iterationCount = iterationCount + 1;
    middleTime_s = 0.5 * (lowerTime_s + upperTime_s);
    [middleResidual_s, middleArrivalTime_s] = interceptResidual( ...
        middleTime_s, searchEndTime_s, initialState, targetMotion, ...
        limits, options);
    if middleResidual_s <= 0
        upperTime_s = middleTime_s;
        upperResidual_s = middleResidual_s;
        upperArrivalTime_s = middleArrivalTime_s;
    else
        lowerTime_s = middleTime_s;
        lowerResidual_s = middleResidual_s;
        lowerArrivalTime_s = middleArrivalTime_s;
    end
end
interceptTime_s = upperTime_s;
diagnostics = struct( ...
    "Success", lowerResidual_s > 0 && upperResidual_s <= 0 && ...
    upperTime_s - lowerTime_s <= options.SearchTimeTolerance_s, ...
    "Message", "Earliest feasible intercept was bracketed and bisected.", ...
    "LowerInfeasibleTime_s", lowerTime_s, ...
    "UpperFeasibleTime_s", upperTime_s, ...
    "LowerResidual_s", lowerResidual_s, ...
    "UpperResidual_s", upperResidual_s, ...
    "LowerMinimumArrivalTime_s", lowerArrivalTime_s, ...
    "UpperMinimumArrivalTime_s", upperArrivalTime_s, ...
    "BracketEvaluationCount", bracketEvaluationCount, ...
    "BisectionIterationCount", iterationCount, ...
    "EarliestCertified", lowerResidual_s > 0 && ...
    upperResidual_s <= 0 && upperTime_s - lowerTime_s <= ...
    options.SearchTimeTolerance_s);
end

function [residual_s, arrivalTime_s] = interceptResidual( ...
        candidateTime_s, searchEndTime_s, initialState, targetMotion, ...
        limits, options)
%% Section 0: Header & Readme
% Evaluate minimum planner arrival minus the candidate target time.
goalVelocity_deg_s = [0 0];
if options.MatchTargetVelocity
    goalVelocity_deg_s = targetMotion.velocity_deg_s;
end
goalState = struct( ...
    "time_s", searchEndTime_s + max(1000, ...
    100 * options.MaximumSearchDuration_s), ...
    "position_deg", linearTargetPosition(targetMotion, candidateTime_s), ...
    "velocity_deg_s", goalVelocity_deg_s, ...
    "acceleration_deg_s2", [0 0]);
plannerOptions = options.PlannerOptions;
plannerOptions.GoalTimeMode = "earliestArrival";
plannerOptions.FigureVisible = "off";
plannerOptions.ShowAnimation = false;
plannerOptions.ShowKinematicPlot = false;
plannerOptions.ShowSweptSurfaces = false;
plannerOptions.Verbose = false;
trialResult = planAzElMotion( ...
    [], initialState, goalState, limits, plannerOptions);
deletePlannerFigures(trialResult);
if ~trialResult.Success
    residual_s = Inf;
    arrivalTime_s = Inf;
    return;
end
arrivalTime_s = trialResult.goalLineInterceptTime_s;
residual_s = arrivalTime_s - candidateTime_s;
end

function value = plannerDisplayOption(overrides, defaults, fieldName)
%% Section 0: Header & Readme
% Resolve one planner display option without duplicating planner parsing.
value = defaults.(fieldName);
if isfield(overrides, fieldName) && ~isempty(overrides.(fieldName))
    value = overrides.(fieldName);
end
end

function deletePlannerFigures(plannerResult)
%% Section 0: Header & Readme
% Close every hidden figure produced by one feasibility trial.
containerNames = ["spaceView" "animation" "kinematicPlot"];
for containerIndex = 1:numel(containerNames)
    containerName = containerNames(containerIndex);
    if ~isfield(plannerResult, containerName)
        continue;
    end
    container = plannerResult.(containerName);
    if isstruct(container) && isfield(container, "Figure") && ...
            isgraphics(container.Figure)
        delete(container.Figure);
    end
end
end

function diagnostics = emptyInterceptSearchDiagnostics()
%% Section 0: Header & Readme
% Return the stable search schema for specified-time interception.
diagnostics = struct( ...
    "Success", true, ...
    "Message", "", ...
    "LowerInfeasibleTime_s", NaN, ...
    "UpperFeasibleTime_s", NaN, ...
    "LowerResidual_s", NaN, ...
    "UpperResidual_s", NaN, ...
    "LowerMinimumArrivalTime_s", NaN, ...
    "UpperMinimumArrivalTime_s", NaN, ...
    "BracketEvaluationCount", 0, ...
    "BisectionIterationCount", 0, ...
    "EarliestCertified", true);
end
