function result = planAzElMotion(obstacles, initialState, goalState, ...
        limits, optionOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   options = planAzElMotion()
%   result = planAzElMotion( ...
%       obstacles, initialState, goalState, limits)
%   result = planAzElMotion( ...
%       obstacles, initialState, goalState, limits, optionOverrides)
%**************************************************************************
% PURPOSE
%   - Plan one jerk-controlled azimuth/elevation motion with bounded seeds,
%     separated HS3 optimization, and independent continuous validation.
%**************************************************************************
% INPUTS
%   - obstacles (canonical protected obstacle array, nested cells, or [])
%       Construct safety margins with makeAzElObstacleData exactly once.
%   - initialState (scalar struct)
%       time_s and 1-by-2 position_deg are required. Velocity and
%       acceleration default to [0 0].
%   - goalState (scalar struct)
%       time_s is the fixed time or latest arrival. position_deg is 1-by-2.
%       Optional targetTime_s and targetPosition_deg define a moving goal.
%   - limits (scalar struct)
%       Positive 1-by-2 maxVelocity_deg_s, maxAcceleration_deg_s2, and
%       maxJerk_deg_s3 fields are required.
%   - optionOverrides (scalar struct, optional; default struct())
%       Partial options are accepted. Empty fields retain defaults.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Stable success-or-failure motion, seed, validation, and diagnostics.
%       Invalid contracts throw. Expected planning failure returns
%       Success=false and preserves every attempted seed summary.
%**************************************************************************
% UNITS
%   - Position is degrees; time is seconds; derivatives use deg/s, deg/s^2,
%     and deg/s^3. Histories are N-by-2 [azimuth elevation].
%**************************************************************************

%% Section 1: Validate Inputs And Apply Defaults

defaults = plannerDefaults();
if nargin == 0
    result = defaults;
    return;
end
if nargin < 4
    error("planAzElMotion:MissingInputs", ...
        "obstacles, initialState, goalState, and limits are required.");
end
if nargin < 5 || isempty(optionOverrides)
    optionOverrides = struct();
end
options = resolvePlannerOptions(defaults, optionOverrides);
obstacles = combineAzElObstacles(obstacles);
initialState = normalizeState(initialState, "initialState");
goalState = normalizeGoalState(goalState);
limits = normalizeLimits(limits);
if goalState.time_s <= initialState.time_s
    error("planAzElMotion:InvalidTimeWindow", ...
        "goalState.time_s must be greater than initialState.time_s.");
end
if options.AllowAzimuthWrapping
    turnCount = round((initialState.position_deg(1) - ...
        goalState.position_deg(1)) / 360);
    goalState.position_deg(1) = goalState.position_deg(1) + ...
        360 * turnCount;
    if isfield(goalState, "targetPosition_deg") && ...
            ~isempty(goalState.targetPosition_deg)
        goalState.targetPosition_deg(:, 1) = ...
            goalState.targetPosition_deg(:, 1) + 360 * turnCount;
    end
end
planningTimer = tic;
result = emptyResult(obstacles, initialState, goalState, limits, options);

%% Section 2: Validate Endpoint Feasibility

[endpointFeasible, endpointMessage, endpointReason] = ...
    validateEndpoints(obstacles, initialState, goalState, limits, options);
if ~endpointFeasible
    result.Message = endpointMessage;
    result.TerminationReason = endpointReason;
    result.ElapsedPlanningTime_s = toc(planningTimer);
    return;
end

%% Section 3: Generate The Bounded Deterministic Seed Set

[seeds, gridDiagnostics] = azElInternal.generateAzElTopologySeeds( ...
    obstacles, initialState, goalState, limits, options);
result.Seeds = seeds;
result.SearchDiagnostics.Grid = gridDiagnostics;
summaryTemplate = emptySeedSummary();
seedSummaries = repmat(summaryTemplate, numel(seeds), 1);
candidates = cell(numel(seeds), 1);

%% Section 4: Optimize And Independently Validate Every Seed

for seedIndex = 1:numel(seeds)
    elapsedTime_s = toc(planningTimer);
    remainingTime_s = options.MaximumPlanningTime_s - elapsedTime_s;
    if remainingTime_s <= 0
        seedSummaries(seedIndex) = summaryTemplate;
        seedSummaries(seedIndex).SeedIndex = seedIndex;
        seedSummaries(seedIndex).SeedSource = seeds(seedIndex).Source;
        seedSummaries(seedIndex).TerminationReason = "planningTimeLimit";
        seedSummaries(seedIndex).Message = ...
            "The planner time limit expired before this seed was solved.";
        continue;
    end
    remainingSeedCount = numel(seeds) - seedIndex + 1;
    seedBudget_s = max(0.1, remainingTime_s / remainingSeedCount);
    seedDeadline_s = elapsedTime_s + seedBudget_s;
    solverOptions = options;
    solverOptions.MaximumSolverTime_s = seedBudget_s;
    trialSeed = seeds(seedIndex);
    finalCandidate = azElInternal.solveAzElHs3( ...
        obstacles, initialState, goalState, limits, ...
        solverOptions, trialSeed);
    validation = validateCandidate( ...
        finalCandidate, obstacles, initialState, goalState, ...
        limits, options);
    relinearizationCount = 0;
    while ~validation.Passed && ~validation.CollisionFree && ...
            ~isempty(finalCandidate.time_s) && ...
            relinearizationCount < 2 && ...
            toc(planningTimer) < seedDeadline_s
        relinearizationCount = relinearizationCount + 1;
        trialSeed = candidateSeed(finalCandidate, seeds(seedIndex));
        remainingSeedTime_s = seedDeadline_s - toc(planningTimer);
        solverOptions.MaximumSolverTime_s = max(0.1, remainingSeedTime_s);
        finalCandidate = azElInternal.solveAzElHs3( ...
            obstacles, initialState, goalState, limits, ...
            solverOptions, trialSeed);
        validation = validateCandidate( ...
            finalCandidate, obstacles, initialState, goalState, ...
            limits, options);
    end
    finalCandidate.Validation = validation;
    candidates{seedIndex} = finalCandidate;
    seedSummaries(seedIndex) = candidateSummary( ...
        finalCandidate, relinearizationCount);
end

%% Section 5: Select And Assemble The Result

result.SeedSummaries = seedSummaries;
result.SearchDiagnostics.SeedSummaries = seedSummaries;
validatedIndices = find([seedSummaries.ValidationPassed]);
if isempty(validatedIndices)
    if toc(planningTimer) >= options.MaximumPlanningTime_s
        result.Message = ...
            "No validated seed was found before the planning time limit.";
        result.TerminationReason = "planningTimeLimit";
    else
        result.Message = ...
            "No attempted HS3 seed passed independent validation.";
        result.TerminationReason = "noValidatedSeed";
    end
    result.ElapsedPlanningTime_s = toc(planningTimer);
    result.SearchDiagnostics.TerminationReason = result.TerminationReason;
    result.SearchDiagnostics.BestPartialSeedIndex = ...
        bestPartialSeed(seedSummaries);
    return;
end
selectedSeedIndex = selectValidatedCandidate( ...
    seedSummaries, validatedIndices, options.ArrivalTimeTolerance_s);
selectedCandidate = candidates{selectedSeedIndex};
[selectedCandidate, meshRefinementPassCount] = refineCandidate( ...
    selectedCandidate, seeds(selectedSeedIndex), obstacles, ...
    initialState, goalState, limits, options, planningTimer);
result.SeedSummaries(selectedSeedIndex) = candidateSummary( ...
    selectedCandidate, result.SeedSummaries( ...
    selectedSeedIndex).RelinearizationCount);
result.SeedSummaries(selectedSeedIndex).MeshRefinementPassCount = ...
    meshRefinementPassCount;
result.SearchDiagnostics.SeedSummaries = result.SeedSummaries;
result.SearchDiagnostics.MeshRefinementPassCount = ...
    meshRefinementPassCount;
result.Success = true;
result.Message = ...
    "The earliest independently validated local HS3 solution was selected.";
result.TerminationReason = "goalReached";
result.SelectedSeedIndex = selectedSeedIndex;
result.SelectedSeed_deg = seeds(selectedSeedIndex).position_deg;
result.time_s = selectedCandidate.time_s;
result.position_deg = selectedCandidate.position_deg;
result.velocity_deg_s = selectedCandidate.velocity_deg_s;
result.acceleration_deg_s2 = selectedCandidate.acceleration_deg_s2;
result.jerk_deg_s3 = selectedCandidate.jerk_deg_s3;
result.Polynomial = selectedCandidate.Polynomial;
result.Validation = selectedCandidate.Validation;
result.ElapsedPlanningTime_s = toc(planningTimer);
result.SearchDiagnostics.TerminationReason = result.TerminationReason;
result.SearchDiagnostics.BestPartialSeedIndex = selectedSeedIndex;
if options.Verbose
    fprintf("[HS3] %s Seeds %d, validated %d, elapsed %.3f s.\n", ...
        result.Message, numel(seeds), numel(validatedIndices), ...
        result.ElapsedPlanningTime_s);
end
end

%% Section 6: Local Functions

function options = plannerDefaults()
% PURPOSE
%   - Define the complete public planner option source of truth.
options = struct( ...
    "GoalTimeMode", "earliestArrival", ...
    "SampleTime_s", 0.05, ...
    "AllowAzimuthWrapping", false, ...
    "AzimuthInterval_deg", [-180 180], ...
    "ElevationInterval_deg", [-90 90], ...
    "MaximumSeedCount", 5, ...
    "DirectSeedOnly", false, ...
    "CollocationSegmentCount", 10, ...
    "MaximumCollocationSegmentCount", 24, ...
    "MaximumMeshRefinementPasses", 0, ...
    "MaximumNlpIterations", 300, ...
    "MaximumNlpFunctionEvaluations", 30000, ...
    "MaximumPlanningTime_s", 60, ...
    "ArrivalTimeTolerance_s", 1e-3, ...
    "ConstraintTolerance", 1e-7, ...
    "OptimalityTolerance", 1e-7, ...
    "StepTolerance", 1e-10, ...
    "CollisionClearanceTolerance_deg", 1e-7, ...
    "CollisionMinimumTimeStep_s", 0.002, ...
    "Verbose", false, ...
    "RandomSeed", 0);
end

function options = resolvePlannerOptions(defaults, overrides)
% PURPOSE
%   - Merge, normalize, and validate all public options once.
if ~isstruct(overrides) || ~isscalar(overrides)
    error("planAzElMotion:InvalidOptions", ...
        "optionOverrides must be a scalar struct.");
end
[options, unknownNames] = azElInternal.resolveOptions(defaults, overrides);
if ~isempty(unknownNames)
    warning("planAzElMotion:UnknownOptions", ...
        "Ignoring unknown option fields: %s. No behavior changed.", ...
        strjoin(unknownNames, ", "));
end
options.GoalTimeMode = string(options.GoalTimeMode);
if ~isscalar(options.GoalTimeMode) || ...
        ~any(options.GoalTimeMode == ["earliestArrival", "fixedArrival"])
    error("planAzElMotion:InvalidGoalTimeMode", ...
        "GoalTimeMode must be 'earliestArrival' or 'fixedArrival'.");
end
logicalNames = ["AllowAzimuthWrapping", "DirectSeedOnly", "Verbose"];
for name = logicalNames
    options.(name) = azElInternal.normalizeLogicalScalar( ...
        options.(name), name, "planAzElMotion:InvalidLogicalOption");
end
validateattributes(options.SampleTime_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
validateattributes(options.MaximumSeedCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 1, '<=', 9});
validateattributes(options.CollocationSegmentCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 2, '<=', 40});
validateattributes(options.MaximumCollocationSegmentCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', ...
    '>=', options.CollocationSegmentCount, '<=', 40});
validateattributes(options.MaximumMeshRefinementPasses, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 0, '<=', 2});
positiveNames = [ ...
    "MaximumNlpIterations", "MaximumNlpFunctionEvaluations", ...
    "MaximumPlanningTime_s", "ArrivalTimeTolerance_s", ...
    "ConstraintTolerance", "OptimalityTolerance", "StepTolerance", ...
    "CollisionMinimumTimeStep_s"];
for name = positiveNames
    validateattributes(options.(name), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'positive'});
end
validateattributes(options.CollisionClearanceTolerance_deg, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'});
validateattributes(options.RandomSeed, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'nonnegative'});
options.AzimuthInterval_deg = normalizeInterval( ...
    options.AzimuthInterval_deg, "AzimuthInterval_deg");
options.ElevationInterval_deg = normalizeInterval( ...
    options.ElevationInterval_deg, "ElevationInterval_deg");
end

function interval = normalizeInterval(interval, fieldName)
% PURPOSE
%   - Normalize one finite increasing two-element position interval.
validateattributes(interval, {'numeric'}, ...
    {'real', 'finite', 'vector', 'numel', 2, 'increasing'}, ...
    "planAzElMotion", fieldName);
interval = double(interval(:).');
end

function state = normalizeState(state, label)
% PURPOSE
%   - Normalize one fixed endpoint state and derivative defaults.
if ~isstruct(state) || ~isscalar(state) || ...
        ~all(isfield(state, {'time_s', 'position_deg'}))
    error("planAzElMotion:InvalidState", ...
        "%s must be a scalar struct with time_s and position_deg.", label);
end
validateattributes(state.time_s, {'numeric'}, ...
    {'real', 'finite', 'scalar'});
validateattributes(state.position_deg, {'numeric'}, ...
    {'real', 'finite', 'vector', 'numel', 2});
state.time_s = double(state.time_s);
state.position_deg = double(state.position_deg(:).');
state = defaultDerivative(state, "velocity_deg_s");
state = defaultDerivative(state, "acceleration_deg_s2");
end

function goalState = normalizeGoalState(goalState)
% PURPOSE
%   - Normalize a fixed goal or sampled moving-goal history.
goalState = normalizeState(goalState, "goalState");
if isfield(goalState, "targetTime_s") || ...
        isfield(goalState, "targetPosition_deg")
    if ~all(isfield(goalState, ...
            {'targetTime_s', 'targetPosition_deg'}))
        error("planAzElMotion:IncompleteMovingGoal", ...
            "targetTime_s and targetPosition_deg must be supplied together.");
    end
    validateattributes(goalState.targetTime_s, {'numeric'}, ...
        {'real', 'finite', 'vector', 'increasing'});
    goalState.targetTime_s = double(goalState.targetTime_s(:));
    validateattributes(goalState.targetPosition_deg, {'numeric'}, ...
        {'real', 'finite', '2d', 'ncols', 2, ...
        'nrows', numel(goalState.targetTime_s)});
    goalState.targetPosition_deg = ...
        double(goalState.targetPosition_deg);
    if goalState.time_s < goalState.targetTime_s(1) || ...
            goalState.time_s > goalState.targetTime_s(end)
        error("planAzElMotion:MovingGoalHorizonOutsideHistory", ...
            "goalState.time_s must be inside targetTime_s.");
    end
    if ~isfield(goalState, "InterpolationMethod") || ...
            isempty(goalState.InterpolationMethod)
        goalState.InterpolationMethod = "linear";
    end
    goalState.InterpolationMethod = string(goalState.InterpolationMethod);
    if ~any(goalState.InterpolationMethod == ["linear", "pchip"])
        error("planAzElMotion:InvalidGoalInterpolation", ...
            "InterpolationMethod must be 'linear' or 'pchip'.");
    end
end
end

function state = defaultDerivative(state, fieldName)
% PURPOSE
%   - Apply one two-axis zero derivative default at the public boundary.
if ~isfield(state, fieldName) || isempty(state.(fieldName))
    state.(fieldName) = [0 0];
else
    validateattributes(state.(fieldName), {'numeric'}, ...
        {'real', 'finite', 'vector', 'numel', 2});
    state.(fieldName) = double(state.(fieldName)(:).');
end
end

function limits = normalizeLimits(limits)
% PURPOSE
%   - Validate and normalize the three required two-axis physical limits.
requiredFields = ["maxVelocity_deg_s", "maxAcceleration_deg_s2", ...
    "maxJerk_deg_s3"];
if ~isstruct(limits) || ~isscalar(limits) || ...
        ~all(isfield(limits, cellstr(requiredFields)))
    error("planAzElMotion:InvalidLimits", ...
        "limits must contain velocity, acceleration, and jerk limits.");
end
for name = requiredFields
    validateattributes(limits.(name), {'numeric'}, ...
        {'real', 'finite', 'positive', 'vector', 'numel', 2});
    limits.(name) = double(limits.(name)(:).');
end
end

function [feasible, message, reason] = validateEndpoints( ...
        obstacles, initialState, goalState, limits, options)
% PURPOSE
%   - Return expected endpoint infeasibility without invoking the optimizer.
goalPosition_deg = terminalPosition(goalState, goalState.time_s);
endpointPosition_deg = [initialState.position_deg; goalPosition_deg];
endpointTime_s = [initialState.time_s; goalState.time_s];
blocked = queryAzElTimeObstacle( ...
    obstacles, endpointPosition_deg(:, 1), ...
    endpointPosition_deg(:, 2), endpointTime_s);
if any(blocked)
    feasible = false;
    message = "The protected geometry contains the start or terminal point.";
    reason = "endpointBlocked";
    return;
end
derivativesWithinLimits = ...
    all(abs(initialState.velocity_deg_s) <= limits.maxVelocity_deg_s) && ...
    all(abs(goalState.velocity_deg_s) <= limits.maxVelocity_deg_s) && ...
    all(abs(initialState.acceleration_deg_s2) <= ...
    limits.maxAcceleration_deg_s2) && ...
    all(abs(goalState.acceleration_deg_s2) <= ...
    limits.maxAcceleration_deg_s2);
if ~derivativesWithinLimits
    feasible = false;
    message = "An endpoint derivative exceeds its physical limit.";
    reason = "dynamicEndpointInfeasible";
    return;
end
positionWithinBounds = ...
    all(endpointPosition_deg(:, 2) >= options.ElevationInterval_deg(1)) && ...
    all(endpointPosition_deg(:, 2) <= options.ElevationInterval_deg(2));
if ~options.AllowAzimuthWrapping
    positionWithinBounds = positionWithinBounds && ...
        all(endpointPosition_deg(:, 1) >= options.AzimuthInterval_deg(1)) && ...
        all(endpointPosition_deg(:, 1) <= options.AzimuthInterval_deg(2));
end
if ~positionWithinBounds
    feasible = false;
    message = "An endpoint is outside the configured workspace.";
    reason = "endpointOutsideWorkspace";
    return;
end
feasible = true;
message = "";
reason = "";
end

function validation = validateCandidate(candidate, obstacles, ...
        initialState, goalState, limits, options)
% PURPOSE
%   - Run the public independent validator on every nonempty solver outcome.
if isempty(candidate.time_s)
    validation = emptyValidation();
    validation.Message = "The solver returned no trajectory.";
    return;
end
validation = validateAzElTrajectory( ...
    candidate, obstacles, initialState, goalState, limits, options);
end

function seed = candidateSeed(candidate, originalSeed)
% PURPOSE
%   - Reassociate a failed collision corridor without adding a new topology.
seed = originalSeed;
sampleTau = (candidate.time_s - candidate.time_s(1)) / ...
    (candidate.time_s(end) - candidate.time_s(1));
seed.tau = candidate.ControlTau;
seed.position_deg = interp1( ...
    sampleTau, candidate.position_deg, seed.tau, "linear");
seed.EstimatedDuration_s = candidate.MotionDuration_s;
end

function [candidate, completedPassCount] = refineCandidate( ...
        candidate, originalSeed, obstacles, initialState, goalState, ...
        limits, options, planningTimer)
% PURPOSE
%   - Refine only the selected validated local solution on a denser HS3 mesh.
completedPassCount = 0;
segmentCount = candidate.Polynomial.SegmentCount;
for passIndex = 1:options.MaximumMeshRefinementPasses
    nextSegmentCount = min(2 * segmentCount, ...
        options.MaximumCollocationSegmentCount);
    remainingTime_s = options.MaximumPlanningTime_s - toc(planningTimer);
    if nextSegmentCount <= segmentCount || remainingTime_s <= 0.1
        break;
    end
    refinedOptions = options;
    refinedOptions.CollocationSegmentCount = nextSegmentCount;
    refinedOptions.MaximumSolverTime_s = remainingTime_s;
    refinedSeed = candidateSeed(candidate, originalSeed);
    trial = azElInternal.solveAzElHs3( ...
        obstacles, initialState, goalState, limits, ...
        refinedOptions, refinedSeed);
    trial.Validation = validateCandidate( ...
        trial, obstacles, initialState, goalState, limits, options);
    arrivalIsEquivalent = options.GoalTimeMode == "fixedArrival" || ...
        trial.FinalTime_s <= candidate.FinalTime_s + ...
        options.ArrivalTimeTolerance_s;
    if ~trial.Validation.Passed || ~arrivalIsEquivalent
        break;
    end
    candidate = trial;
    segmentCount = nextSegmentCount;
    completedPassCount = passIndex;
end
end

function summary = candidateSummary(candidate, relinearizationCount)
% PURPOSE
%   - Retain concise outcomes without duplicating full trajectories.
summary = emptySeedSummary();
summary.SeedIndex = candidate.SeedIndex;
summary.SeedSource = candidate.SeedSource;
summary.OptimizerFeasible = candidate.OptimizerFeasible;
summary.ValidationPassed = candidate.Validation.Passed;
summary.CollisionFree = candidate.Validation.CollisionFree;
summary.CollisionResolved = candidate.Validation.CollisionResolved;
summary.ArrivalTime_s = candidate.FinalTime_s;
summary.MotionDuration_s = candidate.MotionDuration_s;
summary.IntegratedSquaredJerk_deg2_s5 = ...
    candidate.IntegratedSquaredJerk_deg2_s5;
summary.MaximumConstraintViolation = candidate.MaximumConstraintViolation;
summary.RelinearizationCount = relinearizationCount;
summary.TerminationReason = candidate.TerminationReason;
summary.Message = candidate.Message + " " + candidate.Validation.Message;
summary.SolverDiagnostics = candidate.SolverDiagnostics;
end

function selectedIndex = selectValidatedCandidate( ...
        summaries, validatedIndices, arrivalTolerance_s)
% PURPOSE
%   - Apply time, jerk, and deterministic seed-index lexicographic order.
arrivalTimes_s = [summaries(validatedIndices).ArrivalTime_s].';
minimumArrival_s = min(arrivalTimes_s);
timeEquivalent = validatedIndices( ...
    arrivalTimes_s <= minimumArrival_s + arrivalTolerance_s);
jerkValues = [summaries(timeEquivalent).IntegratedSquaredJerk_deg2_s5].';
minimumJerk = min(jerkValues);
jerkEquivalent = timeEquivalent(jerkValues <= minimumJerk + 1e-12);
selectedIndex = min(jerkEquivalent);
end

function index = bestPartialSeed(summaries)
% PURPOSE
%   - Identify the finite least-violation seed for failure visualization.
violation = [summaries.MaximumConstraintViolation].';
violation(~isfinite(violation)) = Inf;
[minimumViolation, index] = min(violation);
if isinf(minimumViolation)
    index = 0;
end
end

function position_deg = terminalPosition(goalState, time_s)
% PURPOSE
%   - Evaluate fixed or sampled moving goal position at one time.
if isfield(goalState, "targetTime_s") && ~isempty(goalState.targetTime_s)
    position_deg = interp1( ...
        goalState.targetTime_s, goalState.targetPosition_deg, ...
        time_s, goalState.InterpolationMethod);
else
    position_deg = goalState.position_deg;
end
end

function result = emptyResult(obstacles, initialState, goalState, limits, options)
% PURPOSE
%   - Define one stable planner schema for every success and failure exit.
result = struct( ...
    "Success", false, ...
    "Message", "Planning was not completed.", ...
    "TerminationReason", "notRun", ...
    "Options", options, ...
    "Inputs", struct( ...
    "obstacles", obstacles, "initialState", initialState, ...
    "goalState", goalState, "limits", limits), ...
    "Seeds", repmat(emptySeed(), 0, 1), ...
    "SeedSummaries", repmat(emptySeedSummary(), 0, 1), ...
    "SelectedSeedIndex", 0, ...
    "SelectedSeed_deg", zeros(0, 2), ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2), ...
    "Polynomial", emptyPolynomial(), ...
    "Validation", emptyValidation(), ...
    "SearchDiagnostics", struct( ...
    "Grid", struct(), ...
    "SeedSummaries", repmat(emptySeedSummary(), 0, 1), ...
    "BestPartialSeedIndex", 0, ...
    "MeshRefinementPassCount", 0, ...
    "TerminationReason", "notRun"), ...
    "ElapsedPlanningTime_s", 0, ...
    "RandomSeed", options.RandomSeed, ...
    "OptimalityStatement", ...
    "Earliest independently validated local HS3 solution from the " + ...
    "finite deterministic seed set attempted; no global certificate.");
end

function seed = emptySeed()
% PURPOSE
%   - Match the topology-seed field order used by the generator.
seed = struct( ...
    "Index", 0, "Source", "", ...
    "position_deg", zeros(0, 2), "tau", zeros(0, 1), ...
    "EstimatedDuration_s", NaN, "Length_deg", NaN);
end

function summary = emptySeedSummary()
% PURPOSE
%   - Define one compact deterministic per-seed diagnostic record.
summary = struct( ...
    "SeedIndex", 0, "SeedSource", "", ...
    "OptimizerFeasible", false, "ValidationPassed", false, ...
    "CollisionFree", false, "CollisionResolved", false, ...
    "ArrivalTime_s", NaN, "MotionDuration_s", NaN, ...
    "IntegratedSquaredJerk_deg2_s5", Inf, ...
    "MaximumConstraintViolation", Inf, ...
    "RelinearizationCount", 0, ...
    "MeshRefinementPassCount", 0, ...
    "TerminationReason", "notRun", "Message", "", ...
    "SolverDiagnostics", struct());
end

function polynomial = emptyPolynomial()
% PURPOSE
%   - Define explicit empty coefficient shapes for a failed result.
polynomial = struct( ...
    "SegmentCount", 0, ...
    "SegmentStartTime_s", zeros(0, 1), ...
    "SegmentDuration_s", NaN, ...
    "FinalTime_s", NaN, ...
    "positionPower_deg", zeros(0, 2, 6), ...
    "velocityPower_deg_s", zeros(0, 2, 5), ...
    "accelerationPower_deg_s2", zeros(0, 2, 4), ...
    "jerkPower_deg_s3", zeros(0, 2, 3), ...
    "TerminalState", struct( ...
    "position_deg", [NaN NaN], ...
    "velocity_deg_s", [NaN NaN], ...
    "acceleration_deg_s2", [NaN NaN]));
end

function validation = emptyValidation()
% PURPOSE
%   - Match the independent validator schema on expected failures.
validation = struct( ...
    "Passed", false, "Message", "No trajectory was validated.", ...
    "HistorySizesMatch", false, "TimeIsFinite", false, ...
    "TimeIsStrictlyIncreasing", false, "HistoryIsFinite", false, ...
    "InitialStateMatched", false, "TerminalStateMatched", false, ...
    "GoalTimeSatisfied", false, "PositionWithinLimits", false, ...
    "VelocityWithinLimits", false, ...
    "AccelerationWithinLimits", false, "JerkWithinLimits", false, ...
    "DynamicsConsistent", false, "MaximumDynamicsResidual", NaN, ...
    "CollisionFree", false, "CollisionResolved", false, ...
    "MinimumClearance_deg", NaN, "CollisionCheckCount", 0, ...
    "UnresolvedIntervalCount", 0, ...
    "SafetyMarginPolicySatisfied", false, ...
    "AzimuthWrapPolicySatisfied", false, ...
    "PeakVelocity_deg_s", [NaN NaN], ...
    "PeakAcceleration_deg_s2", [NaN NaN], ...
    "PeakJerk_deg_s3", [NaN NaN], "Issues", strings(0, 1));
end
