function result = planAzElMotion(obstacles, initialState, goalState, ...
        limits, optionOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   options = planAzElMotion()
%   result = planAzElMotion(obstacles, initialState, goalState, limits)
%   result = planAzElMotion(obstacles, initialState, goalState, limits, ...
%       optionOverrides)
%**************************************************************************
% PURPOSE
%   - Find the earliest independently validated azimuth/elevation motion.
%   - Use the checked-in RL agent to round every topology seed.
%   - Optimize the RL seed geometry and timing together with jerk-controlled
%     Hermite--Simpson direct collocation.
%**************************************************************************
% INPUTS
%   - obstacles (canonical obstacle data, nested cell array, or [])
%       Static or time-varying already-protected polygon geometry.
%   - initialState, goalState (scalar structs)
%       time_s, position_deg, velocity_deg_s, and acceleration_deg_s2.
%       goalState.time_s is the horizon or fixed arrival time.
%   - limits (scalar struct)
%       Finite positive two-axis velocity, acceleration, and jerk limits.
%   - optionOverrides (scalar struct, optional; default struct())
%       Partial RL seed, direct-collocation, visibility, and validation
%       options. RpAgentFile selects the required checked-in policy.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Stable success/failure record with trajectory, topology seed,
%       independent validation, and diagnostics. Expected infeasibility
%       returns Success=false; invalid input throws.
%**************************************************************************
% UNITS
%   - Angles use degrees and time uses seconds. Histories are N-by-2
%     [azimuth elevation] with derivative units stated in field names.
%**************************************************************************

%% Section 1: Validate Inputs And Apply Defaults

defaults = plannerDefaults();
if nargin == 0
    result = defaults;
    return;
end
if nargin < 5 || isempty(optionOverrides)
    optionOverrides = struct();
end
planningTimer = tic;
options = resolveOptions(defaults, optionOverrides);
initialState = normalizeState(initialState, "initialState");
goalState = normalizeState(goalState, "goalState");
limits = normalizeLimits(limits);
if goalState.time_s <= initialState.time_s
    error("planAzElMotion:InvalidTimeWindow", ...
        "goalState.time_s must be greater than initialState.time_s.");
end

%% Section 2: Build Protected Geometry And Validate Endpoints

protectedAzElData = combineAzElObstacles(obstacles);
obstacleField = buildAzElTimeObstacleField(protectedAzElData, ...
    struct("Verbose", options.Verbose));
isObstacleGeometryTimeInvariant = ...
    packedGeometryIsTimeInvariant(obstacleField);
[originalObstacleField, obstacleSafetyMargins_deg] = ...
    recoverOriginalAzElObstacleField(obstacleField);
startBlocked = queryAzElTimeObstacle(obstacleField, ...
    initialState.position_deg(1), initialState.position_deg(2), ...
    initialState.time_s);
goalBlockedAtHorizon = queryAzElTimeObstacle(obstacleField, ...
    goalState.position_deg(1), goalState.position_deg(2), ...
    goalState.time_s);
goalBlocked = options.GoalTimeMode == "fixedarrival" && ...
    goalBlockedAtHorizon;
endpointBlocked = logical(startBlocked || goalBlocked);
[endpointDynamicsFeasible, endpointDynamicsMessage] = ...
    endpointDynamicsAreFeasible(initialState, goalState, limits, options);
[endpointWorkspaceFeasible, endpointWorkspaceMessage] = ...
    endpointWorkspaceIsFeasible(initialState, goalState, options);

directFraction = linspace(0, 1, 501).';
directPosition_deg = initialState.position_deg + directFraction .* ...
    (goalState.position_deg - initialState.position_deg);
directTime_s = initialState.time_s + directFraction .* ...
    (goalState.time_s - initialState.time_s);
directBlocked = queryAzElTimedPathCollision(obstacleField, ...
    directTime_s, directPosition_deg, struct( ...
    "TimePaddingSamples", options.CollisionTimePaddingSamples, ...
    "BoundaryIsOccupied", false));
[includeDirectSeed, directSeedRoute_deg, directSeedRouteTime_s] = ...
    directSeedIsPlausible(obstacleField, ...
    initialState, goalState, options, directBlocked, ...
    isObstacleGeometryTimeInvariant);

%% Section 3: Generate Direct And Visibility Topology Seeds

searchOptions = visibilitySearchOptions( ...
    options, limits, isObstacleGeometryTimeInvariant);
remainingPlanningTime_s = max(0, ...
    options.MaximumPlanningTime_s - toc(planningTimer));
if isfinite(remainingPlanningTime_s)
    reservedOptimizerTime_s = min( ...
        options.MinimumDirectCollocationSeedTime_s, ...
        0.75 * remainingPlanningTime_s);
    reservedSippTime_s = options.MaximumSippPlanningFraction * ...
        remainingPlanningTime_s;
    searchBudget_s = max( ...
        remainingPlanningTime_s - reservedOptimizerTime_s, ...
        reservedSippTime_s);
    searchOptions.MaximumPlanningTime_s = max(eps, min( ...
        remainingPlanningTime_s, searchBudget_s));
    searchOptions.MaximumSippWallTime_s = min( ...
        searchOptions.MaximumSippWallTime_s, ...
        max(eps, reservedSippTime_s));
end
search = emptyVisibilitySearch(searchOptions);
canSearch = ~endpointBlocked && endpointDynamicsFeasible && ...
    endpointWorkspaceFeasible;
if canSearch && obstacleField.ObstacleCount > 0
    search = buildAzElVisibilityRoutes( ...
        obstacleField, initialState, goalState, searchOptions);
end
[seeds, ~, seedReductionDiagnostics] = collectSeeds( ...
    initialState, goalState, search, options, includeDirectSeed, ...
    isObstacleGeometryTimeInvariant, directSeedRoute_deg, ...
    directSeedRouteTime_s);
topologySeedCount = numel(seeds);
[seeds, rpSeedDiagnostics, rpSeedReduction] = ...
    azElInternal.buildAzElRpHs3Seeds( ...
    seeds, limits, options);
seedReductionDiagnostics.CollectedCandidateSeedCount = ...
    seedReductionDiagnostics.CollectedCandidateSeedCount + ...
    rpSeedReduction.GeneratedWarmStartCount - topologySeedCount;
seedReductionDiagnostics.DeduplicatedCandidateSeedCount = ...
    seedReductionDiagnostics.DeduplicatedCandidateSeedCount + ...
    rpSeedReduction.GeneratedWarmStartCount - topologySeedCount;
seedReductionDiagnostics.SeedCapDroppedCount = ...
    seedReductionDiagnostics.SeedCapDroppedCount + ...
    rpSeedReduction.SeedCapDroppedWarmStartCount;
seedRoutes_deg = reshape({seeds.Route_deg}, [], 1);

%% Section 4: Optimize And Independently Validate Every Seed

[useParallelOptimization, parallelOptimizationExecution] = ...
    resolveOptimizationParallelExecution(options.UseParallel, numel(seeds));
candidateResults = repmat(emptyCandidateDiagnostic(), 0, 1);
rawCandidates = cell(0, 1);
if canSearch && useParallelOptimization
    seedCount = numel(seeds);
    candidateResults = repmat(emptyCandidateDiagnostic(), seedCount, 1);
    rawCandidates = cell(seedCount, 1);
    remainingPlanningTime_s = max(0, ...
        options.MaximumPlanningTime_s - toc(planningTimer));
    perSeedTime_s = fairCandidateTimeAllocation( ...
        remainingPlanningTime_s, seedCount);
    parfor seedIndex = 1:seedCount
        optimizerOptions = seedOptimizerOptions( ...
            options, seeds(seedIndex), initialState, ...
            isObstacleGeometryTimeInvariant);
        optimizerOptions.UseParallel = false;
        optimizerOptions.RemainingPlanningTime_s = perSeedTime_s;
        rawCandidate = azElInternal.optimizeAzElDirectCollocation( ...
            seeds(seedIndex).Route_deg, obstacleField, initialState, ...
            goalState, limits, optimizerOptions);
        rawCandidates{seedIndex} = rawCandidate;
        candidateResults(seedIndex) = candidateDiagnostic( ...
            seedIndex, seeds(seedIndex), rawCandidate);
    end
elseif canSearch
    for seedIndex = 1:numel(seeds)
        elapsedPlanningTime_s = toc(planningTimer);
        if elapsedPlanningTime_s >= options.MaximumPlanningTime_s
            break;
        end
        optimizerOptions = seedOptimizerOptions( ...
            options, seeds(seedIndex), initialState, ...
            isObstacleGeometryTimeInvariant);
        remainingSeedCount = numel(seeds) - seedIndex + 1;
        remainingPlanningTime_s = ...
            options.MaximumPlanningTime_s - elapsedPlanningTime_s;
        optimizerOptions.RemainingPlanningTime_s = ...
            fairCandidateTimeAllocation( ...
            remainingPlanningTime_s, remainingSeedCount);
        rawCandidate = azElInternal.optimizeAzElDirectCollocation( ...
            seeds(seedIndex).Route_deg, obstacleField, initialState, ...
            goalState, limits, optimizerOptions);
        rawCandidates{end + 1, 1} = rawCandidate; %#ok<AGROW>
        candidateResults(end + 1, 1) = candidateDiagnostic( ...
            seedIndex, seeds(seedIndex), rawCandidate); %#ok<AGROW>
    end
end
[selectedCandidateIndex, success] = selectCandidate( ...
    candidateResults, options.ArrivalTimeTieTolerance_s);
selectedRoute_deg = [initialState.position_deg; goalState.position_deg];
selectedRouteTime_s = zeros(0, 1);
selectedRawCandidate = [];
if selectedCandidateIndex > 0
    selectedRoute_deg = seeds(selectedCandidateIndex).Route_deg;
    selectedRouteTime_s = seeds(selectedCandidateIndex).RouteTime_s;
    selectedRawCandidate = rawCandidates{selectedCandidateIndex};
end

%% Section 5: Assemble Stable Trajectory And Result Schemas

timedSlopePath = emptyTimedPath();
validation = emptyValidation();
message = "No direct-collocation candidate was evaluated.";
terminationReason = "noFeasibleCandidate";
if endpointBlocked
    message = "The protected geometry contains the start or goal.";
    terminationReason = "endpointBlocked";
elseif ~endpointDynamicsFeasible
    message = endpointDynamicsMessage;
    terminationReason = "dynamicEndpointInfeasible";
elseif ~endpointWorkspaceFeasible
    message = endpointWorkspaceMessage;
    terminationReason = "endpointOutsideWorkspace";
elseif selectedCandidateIndex > 0
    timedSlopePath = compatibilityTimedPath( ...
        selectedRawCandidate, initialState);
    validation = selectedRawCandidate.Validation;
    message = selectedRawCandidate.Message;
    terminationReason = selectedRawCandidate.TerminationReason;
end
if success
    message = "Best RL-seeded HS-3 motion passed validation.";
    terminationReason = "goalReached";
end
candidateDiagnostics = candidateDiagnosticTable(candidateResults);
seedRouteTimes_s = reshape({seeds.RouteTime_s}, [], 1);
elapsedPlanningTime_s = toc(planningTimer);
searchDiagnostics = assembleSearchDiagnostics( ...
    search, seeds, candidateResults, selectedCandidateIndex, ...
    elapsedPlanningTime_s, options, terminationReason, ...
    parallelOptimizationExecution, ...
    isObstacleGeometryTimeInvariant, seedReductionDiagnostics);
searchDiagnostics.RpSeedDiagnostics = rpSeedDiagnostics;
searchDiagnostics.RpSeedReduction = rpSeedReduction;
searchDiagnostics.RpAgentFile = options.RpAgentFile;
searchDiagnostics.RpSeedMethod = "requiredRlCornerPolicy";
trajectory = trajectoryView(timedSlopePath);
goalLineInterceptTime_s = NaN;
if ~isempty(timedSlopePath.time_s)
    goalLineInterceptTime_s = timedSlopePath.time_s(end);
end
result = struct( ...
    "Success", success, ...
    "Message", message, ...
    "TerminationReason", terminationReason, ...
    "Options", options, ...
    "azElData", protectedAzElData, ...
    "originalAzElData", originalObstacleField.SourceAzElData, ...
    "obstacleField", obstacleField, ...
    "initialState", initialState, ...
    "goalState", goalState, ...
    "limits", limits, ...
    "obstacleSafetyMargins_deg", obstacleSafetyMargins_deg, ...
    "candidateReductionDiagnostics", ...
    search.CandidateReductionDiagnostics, ...
    "directPosition_deg", directPosition_deg, ...
    "directTime_s", directTime_s, ...
    "directBlocked", logical(directBlocked(:)), ...
    "candidateRoutes_deg", {seedRoutes_deg}, ...
    "candidateRouteTimes_s", {seedRouteTimes_s}, ...
    "candidateDiagnostics", candidateDiagnostics, ...
    "selectedCandidateIndex", selectedCandidateIndex, ...
    "selectedRoute_deg", selectedRoute_deg, ...
    "selectedRouteTime_s", selectedRouteTime_s, ...
    "smoothPath", [], ...
    "timedSlopePath", timedSlopePath, ...
    "time_s", trajectory.time_s, ...
    "position_deg", trajectory.position_deg, ...
    "velocity_deg_s", trajectory.velocity_deg_s, ...
    "acceleration_deg_s2", trajectory.acceleration_deg_s2, ...
    "jerk_deg_s3", trajectory.jerk_deg_s3, ...
    "goalLineInterceptTime_s", goalLineInterceptTime_s, ...
    "SearchDiagnostics", searchDiagnostics, ...
    "ElapsedPlanningTime_s", elapsedPlanningTime_s, ...
    "Validation", validation);
if options.Verbose
    fprintf("[AzEl RL-seeded HS-3] %s Seeds %d, feasible %d, " + ...
        "elapsed %.3f s.\n", message, numel(candidateResults), ...
        nnz([candidateResults.Success]), elapsedPlanningTime_s);
end
end

%% Section 6: Local Functions

function options = plannerDefaults()
% PURPOSE
%   - Return the single source of truth for public planner defaults.
repositoryRoot = fileparts(mfilename("fullpath"));
options = struct( ...
    "GoalTimeMode", "earliestArrival", ...
    "SampleTime_s", 0.05, ...
    "RpAgentFile", fullfile(repositoryRoot, "models", ...
        "azElRpRetimerAgent.mat"), ...
    "RpTurnRadius_deg", 1.0, ...
    "CollisionTimePaddingSamples", 0, ...
    "AllowAzimuthWrapping", false, ...
    "AzimuthInterval_deg", [-180 180], ...
    "ElevationInterval_deg", [-90 90], ...
    "VisibilitySampleStep_deg", 0.10, ...
    "MaximumVisibilitySnapshotsPerObstacle", 4, ...
    "DetectSnapshotEvents", true, ...
    "SnapshotProbeEdgeCount", 4, ...
    "SnapshotCountChangeThreshold", 0.10, ...
    "SnapshotEdgeRotationThreshold_deg", 5, ...
    "SnapshotBoundaryMotionThreshold_deg", 1, ...
    "VisibilityGraphCostChangeThreshold", 0.05, ...
    "TemporalSeedSampleTimes_s", zeros(0, 1), ...
    "UseSpaceTimeVisibilityGraph", true, ...
    "SpaceTimeLayerCount", 17, ...
    "MaximumSpaceTimeCandidateCount", 32, ...
    "MaximumSpaceTimeDiagnosticEdgeCount", 5000, ...
    "MaximumSafeIntervalRefinements", 4, ...
    "SafeIntervalTimeTolerance_s", 1e-3, ...
    "MaximumSippCandidates", 4, ...
    "MaximumSippExpansions", 5000, ...
    "MaximumSippWallTime_s", Inf, ...
    "MaximumSippPlanningFraction", 0.50, ...
    "SippKNearestNeighbors", 8, ...
    "SippMaximumEdgeLength_deg", Inf, ...
    "AllowSippWaiting", true, ...
    "SpaceTimeNodeMergeTolerance_deg", 1e-8, ...
    "MaximumDirectCollocationSeeds", 8, ...
    "MinimumDirectCollocationSeedTime_s", 60, ...
    "InitialCollocationSegmentCount", 8, ...
    "MaximumMeshRefinementPasses", 2, ...
    "CollocationErrorTolerance", 5e-3, ...
    "MaximumCollocationSegmentCount", 32, ...
    "MaximumCorridorRelinearizations", 4, ...
    "ObstacleConstraintTolerance_deg", 1e-4, ...
    "KinematicValidationTolerance", 1e-7, ...
    "NlpConstraintTolerance", 1e-8, ...
    "NlpOptimalityTolerance", 1e-6, ...
    "NlpStepTolerance", 1e-10, ...
    "MaximumNlpIterations", 300, ...
    "MaximumNlpFunctionEvaluations", 100000, ...
    "EnableJerkTieBreak", true, ...
    "ArrivalTimeTieTolerance_s", 0.01, ...
    "MaximumPlanningTime_s", Inf, ...
    "UseParallel", false, ...
    "Verbose", false);
end

function options = resolveOptions(defaults, overrides)
% PURPOSE
%   - Merge partial overrides, warn once, normalize, and validate.
if ~isstruct(overrides) || ~isscalar(overrides)
    error("planAzElMotion:InvalidOptions", ...
        "optionOverrides must be a scalar struct.");
end
movedMarginNames = intersect(fieldnames(overrides), ...
    {'SafetyMarginDeg', 'RoundingClearance_deg'}, "stable");
if ~isempty(movedMarginNames)
    error("planAzElMotion:SafetyMarginMoved", ...
        "Safety margins belong to obstacle data. Remove %s and use " + ...
        "makeAzElObstacleData.", ...
        strjoin(string(movedMarginNames), ", "));
end
[options, unknown] = azElInternal.resolveOptions(defaults, overrides);
if ~isempty(unknown)
    warning("planAzElMotion:UnknownOptions", ...
        "Ignored unknown option fields: %s. No behavior changed.", ...
        strjoin(unknown, ", "));
end
options.GoalTimeMode = lower(string(options.GoalTimeMode));
if ~isscalar(options.GoalTimeMode) || ~any( ...
        options.GoalTimeMode == ["earliestarrival" "fixedarrival"])
    error("planAzElMotion:InvalidGoalTimeMode", ...
        "GoalTimeMode must be earliestArrival or fixedArrival.");
end
options.RpAgentFile = string(options.RpAgentFile);
if ~isscalar(options.RpAgentFile) || strlength(options.RpAgentFile) == 0
    error("planAzElMotion:InvalidRpAgentFile", ...
        "RpAgentFile must be nonempty scalar text.");
end
validateattributes(options.RpTurnRadius_deg, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
options.UseParallel = azElInternal.normalizeParallelMode( ...
    options.UseParallel, "planAzElMotion:InvalidUseParallel");
logicalNames = ["AllowAzimuthWrapping" "DetectSnapshotEvents" ...
    "UseSpaceTimeVisibilityGraph" "AllowSippWaiting" ...
    "EnableJerkTieBreak" "Verbose"];
for optionIndex = 1:numel(logicalNames)
    name = logicalNames(optionIndex);
    options.(name) = azElInternal.normalizeLogicalScalar( ...
        options.(name), name, "planAzElMotion:InvalidLogicalOption");
end
positiveNames = ["SampleTime_s" "VisibilitySampleStep_deg" ...
    "SafeIntervalTimeTolerance_s" "MaximumSippWallTime_s" ...
    "SippMaximumEdgeLength_deg" ...
    "CollocationErrorTolerance" "KinematicValidationTolerance" ...
    "NlpConstraintTolerance" "NlpOptimalityTolerance" ...
    "NlpStepTolerance" "MaximumPlanningTime_s" ...
    "MaximumSippPlanningFraction" ...
    "MinimumDirectCollocationSeedTime_s"];
for optionIndex = 1:numel(positiveNames)
    validateattributes(options.(positiveNames(optionIndex)), ...
        {'numeric'}, {'real', 'scalar', 'positive'});
end
nonnegativeNames = ["SnapshotCountChangeThreshold" ...
    "SnapshotEdgeRotationThreshold_deg" ...
    "SnapshotBoundaryMotionThreshold_deg" ...
    "VisibilityGraphCostChangeThreshold" ...
    "SpaceTimeNodeMergeTolerance_deg" ...
    "ObstacleConstraintTolerance_deg" ...
    "ArrivalTimeTieTolerance_s"];
for optionIndex = 1:numel(nonnegativeNames)
    validateattributes(options.(nonnegativeNames(optionIndex)), ...
        {'numeric'}, {'real', 'finite', 'scalar', 'nonnegative'});
end
if options.MaximumSippPlanningFraction > 1
    error("planAzElMotion:InvalidSippPlanningFraction", ...
        "MaximumSippPlanningFraction must be in the interval (0, 1].");
end
integerNames = ["MaximumVisibilitySnapshotsPerObstacle" ...
    "SnapshotProbeEdgeCount" "MaximumDirectCollocationSeeds" ...
    "SpaceTimeLayerCount" "MaximumSpaceTimeCandidateCount" ...
    "MaximumSippCandidates" "MaximumSippExpansions" ...
    "SippKNearestNeighbors" ...
    "InitialCollocationSegmentCount" ...
    "MaximumCollocationSegmentCount" "MaximumNlpIterations" ...
    "MaximumNlpFunctionEvaluations"];
for optionIndex = 1:numel(integerNames)
    name = integerNames(optionIndex);
    validateattributes(options.(name), {'numeric'}, ...
        {'real', 'scalar', 'positive'});
    if isfinite(options.(name)) && fix(options.(name)) ~= options.(name)
        error("planAzElMotion:InvalidIntegerOption", ...
            "%s must be a positive integer or Inf.", name);
    end
end
if options.SpaceTimeLayerCount < 3
    error("planAzElMotion:InvalidSpaceTimeLayerCount", ...
        "SpaceTimeLayerCount must be at least 3.");
end
nonnegativeIntegerNames = ["CollisionTimePaddingSamples" ...
    "MaximumSafeIntervalRefinements" ...
    "MaximumMeshRefinementPasses" "MaximumCorridorRelinearizations" ...
    "MaximumSpaceTimeDiagnosticEdgeCount"];
for optionIndex = 1:numel(nonnegativeIntegerNames)
    validateattributes(options.(nonnegativeIntegerNames(optionIndex)), ...
        {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', 'nonnegative'});
end
if options.MaximumCollocationSegmentCount < ...
        options.InitialCollocationSegmentCount
    error("planAzElMotion:InvalidMeshLimits", ...
        "MaximumCollocationSegmentCount must not be smaller than " + ...
        "InitialCollocationSegmentCount.");
end
validateattributes(options.AzimuthInterval_deg, {'numeric'}, ...
    {'real', 'finite', 'vector', 'numel', 2, 'increasing'});
validateattributes(options.ElevationInterval_deg, {'numeric'}, ...
    {'real', 'finite', 'vector', 'numel', 2, 'increasing'});
validateattributes(options.TemporalSeedSampleTimes_s, {'numeric'}, ...
    {'real', 'finite', 'vector'});
options.AzimuthInterval_deg = ...
    reshape(double(options.AzimuthInterval_deg), 1, 2);
options.ElevationInterval_deg = ...
    reshape(double(options.ElevationInterval_deg), 1, 2);
options.TemporalSeedSampleTimes_s = unique(double( ...
    options.TemporalSeedSampleTimes_s(:)));
end

function state = normalizeState(state, label)
% PURPOSE
%   - Normalize one endpoint to scalar time and two-axis state rows.
if ~isstruct(state) || ~isscalar(state) || ...
        ~all(isfield(state, ["time_s" "position_deg"]))
    error("planAzElMotion:InvalidState", ...
        "%s must contain time_s and position_deg.", label);
end
if ~isfield(state, "velocity_deg_s") || isempty(state.velocity_deg_s)
    state.velocity_deg_s = [0 0];
end
if ~isfield(state, "acceleration_deg_s2") || ...
        isempty(state.acceleration_deg_s2)
    state.acceleration_deg_s2 = [0 0];
end
validateattributes(state.time_s, {'numeric'}, ...
    {'real', 'finite', 'scalar'});
names = ["position_deg" "velocity_deg_s" "acceleration_deg_s2"];
for fieldIndex = 1:numel(names)
    name = names(fieldIndex);
    validateattributes(state.(name), {'numeric'}, ...
        {'real', 'finite', 'vector', 'numel', 2});
    state.(name) = reshape(double(state.(name)), 1, 2);
end
state.time_s = double(state.time_s);
end

function limits = normalizeLimits(limits)
% PURPOSE
%   - Normalize finite positive per-axis motion limits.
names = ["maxVelocity_deg_s" "maxAcceleration_deg_s2" ...
    "maxJerk_deg_s3"];
if ~isstruct(limits) || ~isscalar(limits) || ...
        ~all(isfield(limits, names))
    error("planAzElMotion:InvalidLimits", ...
        "limits must contain velocity, acceleration, and jerk limits.");
end
for fieldIndex = 1:numel(names)
    name = names(fieldIndex);
    value = limits.(name);
    validateattributes(value, {'numeric'}, ...
        {'real', 'finite', 'vector', 'nonempty', 'positive'});
    if ~(isscalar(value) || numel(value) == 2)
        error("planAzElMotion:InvalidLimits", ...
            "%s must be scalar or two-element.", name);
    end
    value = reshape(double(value), 1, []);
    if isscalar(value)
        value = repmat(value, 1, 2);
    end
    limits.(name) = value;
end
end

function [feasible, message] = endpointDynamicsAreFeasible( ...
        initialState, goalState, limits, options)
% PURPOSE
%   - Return stable expected failure for endpoint limit violations.
tolerance = options.KinematicValidationTolerance;
velocityFeasible = all(abs([initialState.velocity_deg_s; ...
    goalState.velocity_deg_s]) <= limits.maxVelocity_deg_s + tolerance, ...
    "all");
accelerationFeasible = all(abs([initialState.acceleration_deg_s2; ...
    goalState.acceleration_deg_s2]) <= ...
    limits.maxAcceleration_deg_s2 + tolerance, "all");
feasible = velocityFeasible && accelerationFeasible;
message = "Endpoint motion states satisfy their limits.";
if ~feasible
    message = "An endpoint velocity or acceleration exceeds its limit.";
end
end

function [feasible, message] = endpointWorkspaceIsFeasible( ...
        initialState, goalState, options)
% PURPOSE
%   - Return stable expected failure for endpoint workspace violations.
positions_deg = [initialState.position_deg; goalState.position_deg];
elevationFeasible = all(positions_deg(:, 2) >= ...
    options.ElevationInterval_deg(1) & positions_deg(:, 2) <= ...
    options.ElevationInterval_deg(2));
azimuthFeasible = true;
if ~options.AllowAzimuthWrapping
    azimuthFeasible = all(positions_deg(:, 1) >= ...
        options.AzimuthInterval_deg(1) & positions_deg(:, 1) <= ...
        options.AzimuthInterval_deg(2));
end
feasible = elevationFeasible && azimuthFeasible;
message = "Endpoint positions satisfy the workspace policy.";
if ~feasible
    message = "An endpoint position lies outside the configured workspace.";
end
end

function searchOptions = visibilitySearchOptions( ...
        options, limits, isObstacleGeometryTimeInvariant)
% PURPOSE
%   - Map planner limits and options to collision-informed seed generation.
% One sampling step keeps a topology seed far enough from protected
% geometry for continuous smoothing. Independent validation still uses the
% original protected geometry and does not subtract this clearance.
searchOptions = struct( ...
    "CandidateClearance_deg", ...
    options.VisibilitySampleStep_deg, ...
    "MaximumSnapshotsPerObstacle", ...
    options.MaximumVisibilitySnapshotsPerObstacle, ...
    "RequiredSnapshotTimes_s", options.TemporalSeedSampleTimes_s, ...
    "DetectSnapshotEvents", options.DetectSnapshotEvents, ...
    "SnapshotProbeEdgeCount", options.SnapshotProbeEdgeCount, ...
    "SnapshotCountChangeThreshold", ...
    options.SnapshotCountChangeThreshold, ...
    "SnapshotEdgeRotationThreshold_deg", ...
    options.SnapshotEdgeRotationThreshold_deg, ...
    "SnapshotBoundaryMotionThreshold_deg", ...
    options.SnapshotBoundaryMotionThreshold_deg, ...
    "VisibilitySampleStep_deg", options.VisibilitySampleStep_deg, ...
    "ConnectivityPathCostChangeThreshold", ...
    options.VisibilityGraphCostChangeThreshold, ...
    "BuildFullVisibilityGraphs", true, ...
    "BuildMergedVisibilityGraph", true, ...
    "BuildAlternativeTopologyRoute", true, ...
    "BuildSpaceTimeVisibilityGraph", ...
    options.UseSpaceTimeVisibilityGraph && ...
    ~isObstacleGeometryTimeInvariant, ...
    "GoalTimeMode", options.GoalTimeMode, ...
    "MaximumVelocity_deg_s", limits.maxVelocity_deg_s, ...
    "MaximumAcceleration_deg_s2", limits.maxAcceleration_deg_s2, ...
    "MaximumJerk_deg_s3", limits.maxJerk_deg_s3, ...
    "SpaceTimeLayerCount", options.SpaceTimeLayerCount, ...
    "MaximumSpaceTimeCandidateCount", ...
    options.MaximumSpaceTimeCandidateCount, ...
    "MaximumSpaceTimeDiagnosticEdgeCount", ...
    options.MaximumSpaceTimeDiagnosticEdgeCount, ...
    "MaximumSafeIntervalRefinements", ...
    options.MaximumSafeIntervalRefinements, ...
    "SafeIntervalTimeTolerance_s", ...
    options.SafeIntervalTimeTolerance_s, ...
    "MaximumSippCandidates", options.MaximumSippCandidates, ...
    "MaximumSippExpansions", options.MaximumSippExpansions, ...
    "MaximumSippWallTime_s", options.MaximumSippWallTime_s, ...
    "SippKNearestNeighbors", options.SippKNearestNeighbors, ...
    "SippMaximumEdgeLength_deg", ...
    options.SippMaximumEdgeLength_deg, ...
    "AllowSippWaiting", options.AllowSippWaiting, ...
    "SpaceTimeNodeMergeTolerance_deg", ...
    options.SpaceTimeNodeMergeTolerance_deg, ...
    "CollisionTimePaddingSamples", ...
    options.CollisionTimePaddingSamples, ...
    "MaximumPlanningTime_s", Inf, ...
    "UseParallel", options.UseParallel, ...
    "Verbose", options.Verbose);
end

function search = emptyVisibilitySearch(searchOptions)
% PURPOSE
%   - Define stable empty visibility diagnostics for obstacle-free planning.
emptyGraph = repmat(struct("Success", false), 0, 1);
search = struct( ...
    "VisibilityGraphs", emptyGraph, ...
    "MergedVisibilityGraphs", emptyGraph, ...
    "SpaceTimeVisibilityGraph", ...
    azElInternal.buildAzElSpaceTimeVisibilityGraph(), ...
    "ObstacleMergeDiagnostics", struct(), ...
    "ConnectivityDiagnostics", struct(), ...
    "ConnectivityChangeIntervals", zeros(0, 2), ...
    "PairwiseEventTimes_s", zeros(0, 1), ...
    "PairwiseEventDiagnostics", repmat(struct(), 0, 1), ...
    "SnapshotDiagnostics", struct(), ...
    "CandidateReductionDiagnostics", repmat(struct(), 0, 1), ...
    "CandidatePointsAzElTime", zeros(0, 3), ...
    "ElapsedSearchTime_s", 0, ...
    "PlanningTimeLimitReached", false, ...
    "ParallelExecution", struct( ...
    "RequestedMode", searchOptions.UseParallel, ...
    "ToolboxAvailable", license("test", ...
    "Distrib_Computing_Toolbox"), ...
    "Enabled", false, "WorkerCount", 0, "TaskCount", 0, ...
    "CompletedTaskCount", 0, "ElapsedTime_s", 0, ...
    "PlanningTimeLimitReached", false, ...
    "Message", "No visibility tasks were available."), ...
    "Options", searchOptions);
end

function optimizerOptions = seedOptimizerOptions( ...
        options, seed, initialState, obstacleGeometryTimeInvariant)
% PURPOSE
%   - Pass one space-time route law to every optimizer stage.
optimizerOptions = options;
optimizerOptions.ObstacleGeometryTimeInvariant = ...
    logical(obstacleGeometryTimeInvariant);
optimizerOptions.SeedSnapshotTime_s = seed.SnapshotTime_s;
optimizerOptions.SeedRouteTimeFraction = zeros(0, 1);
optimizerOptions.SeedRouteProgress = zeros(0, 1);
optimizerOptions.SeedRouteDuration_s = NaN;
if isfield(seed, "RpSeedRouteTimeFraction") && ...
        isfield(seed, "RpSeedRouteProgress") && ...
        numel(seed.RpSeedRouteTimeFraction) >= 2
    optimizerOptions.SeedRouteTimeFraction = ...
        seed.RpSeedRouteTimeFraction;
    optimizerOptions.SeedRouteProgress = seed.RpSeedRouteProgress;
    optimizerOptions.SeedRouteDuration_s = seed.RpSeedRouteDuration_s;
    return;
end
routeTime_s = double(seed.RouteTime_s(:));
route_deg = double(seed.Route_deg);
hasTimedRoute = numel(routeTime_s) == size(route_deg, 1) && ...
    numel(routeTime_s) >= 2 && all(isfinite(routeTime_s)) && ...
    all(diff(routeTime_s) > 0) && ...
    routeTime_s(1) >= initialState.time_s && ...
    routeTime_s(end) > initialState.time_s;
if ~hasTimedRoute
    return;
end
routeStep_deg = diff(route_deg, 1, 1);
routeArc_deg = [0; cumsum(hypot( ...
    routeStep_deg(:, 1), routeStep_deg(:, 2)))];
if routeArc_deg(end) <= eps
    return;
end
% SIPP-IP arrival times define the collision-checked progress law. The
% collocation fit can smooth node stops, but it must not replace that law
% with uniform arc-length timing because doing so changes obstacle phase.
optimizerOptions.SeedRouteTimeFraction = ...
    (routeTime_s - initialState.time_s) / ...
    (routeTime_s(end) - initialState.time_s);
optimizerOptions.SeedRouteProgress = routeArc_deg / routeArc_deg(end);
optimizerOptions.SeedRouteDuration_s = ...
    routeTime_s(end) - initialState.time_s;
end

function allocatedTime_s = fairCandidateTimeAllocation( ...
        remainingTime_s, remainingCandidateCount)
% PURPOSE
%   - Prevent one candidate from consuming another candidate's finite share.
if ~isfinite(remainingTime_s)
    allocatedTime_s = Inf;
    return;
end
allocatedTime_s = max(0, remainingTime_s) / ...
    max(1, remainingCandidateCount);
end

function [useParallel, diagnostics] = ...
        resolveOptimizationParallelExecution(requestedMode, taskCount)
% PURPOSE
%   - Start or reuse a pool for independent direct-collocation seeds.
toolboxAvailable = license("test", "Distrib_Computing_Toolbox") && ...
    exist("parpool", "file") == 2 && exist("gcp", "file") == 2;
useParallel = false;
workerCount = 0;
if taskCount <= 1
    message = "One or fewer NLP seeds; serial execution selected.";
elseif requestedMode == "off"
    message = "UseParallel is off; serial NLP execution selected.";
elseif ~toolboxAvailable
    message = "Parallel Computing Toolbox is unavailable; serial fallback selected.";
    if requestedMode == "on"
        warning("planAzElMotion:ParallelUnavailable", "%s", message);
    end
else
    try
        pool = gcp("nocreate");
        if isempty(pool)
            pool = parpool;
        end
        workerCount = pool.NumWorkers;
        useParallel = workerCount > 0;
        message = sprintf( ...
            "Parallel direct collocation enabled with %d workers.", ...
            workerCount);
    catch parallelException
        message = "Parallel pool startup failed; serial fallback selected. " + ...
            string(parallelException.message);
        if requestedMode == "on"
            warning("planAzElMotion:ParallelUnavailable", "%s", message);
        end
    end
end
diagnostics = struct( ...
    "RequestedMode", requestedMode, ...
    "ToolboxAvailable", toolboxAvailable, ...
    "Enabled", useParallel, ...
    "WorkerCount", workerCount, ...
    "TaskCount", taskCount, ...
    "Message", string(message));
end

function [plausible, seedRoute_deg, seedRouteTime_s] = ...
        directSeedIsPlausible(obstacleField, ...
        initialState, goalState, options, horizonCollisionMask, ...
        isObstacleGeometryTimeInvariant)
% PURPOSE
%   - Retain a straight seed if a valid deterministic time law is clear.
seedRoute_deg = [initialState.position_deg; goalState.position_deg];
seedRouteTime_s = zeros(0, 1);
plausible = obstacleField.ObstacleCount == 0 || ...
    ~any(horizonCollisionMask);
preserveClearHorizonTimeLaw = plausible && ...
    obstacleField.ObstacleCount > 0 && ...
    ~isObstacleGeometryTimeInvariant;
if plausible && (options.GoalTimeMode == "fixedarrival" || ...
        preserveClearHorizonTimeLaw)
    seedRouteTime_s = [initialState.time_s; goalState.time_s];
end
if plausible || isObstacleGeometryTimeInvariant
    return;
end
pathFraction = linspace(0, 1, 201).';
position_deg = initialState.position_deg + pathFraction .* ...
    (goalState.position_deg - initialState.position_deg);
if options.GoalTimeMode == "fixedarrival"
    timeFraction = linspace(0, 1, 201).';
    exponent = [0.25; 0.5; 2; 4];
    progressLaw = zeros(numel(timeFraction), 0);
    for exponentIndex = 1:numel(exponent)
        progressLaw(:, end + 1) = ...
            timeFraction .^ exponent(exponentIndex); %#ok<AGROW>
    end
    waitFraction = [0.25; 0.5; 0.75];
    for waitIndex = 1:numel(waitFraction)
        wait = waitFraction(waitIndex);
        progressLaw(:, end + 1) = max(0, ...
            (timeFraction - wait) / (1 - wait)); %#ok<AGROW>
        progressLaw(:, end + 1) = min(1, ...
            timeFraction / (1 - wait)); %#ok<AGROW>
    end
    horizon_s = goalState.time_s - initialState.time_s;
    time_s = initialState.time_s + horizon_s * timeFraction;
    for lawIndex = 1:size(progressLaw, 2)
        lawPosition_deg = initialState.position_deg + ...
            progressLaw(:, lawIndex) .* ...
            (goalState.position_deg - initialState.position_deg);
        collisionMask = queryAzElTimedPathCollision(obstacleField, ...
            time_s, lawPosition_deg, struct( ...
            "TimePaddingSamples", options.CollisionTimePaddingSamples, ...
            "BoundaryIsOccupied", false, "StopAtFirstCollision", true));
        if ~any(collisionMask)
            plausible = true;
            anchorIndex = unique(round(linspace( ...
                1, numel(time_s), 9)));
            seedRoute_deg = lawPosition_deg(anchorIndex, :);
            seedRouteTime_s = time_s(anchorIndex);
            return;
        end
    end
    return;
end
horizon_s = goalState.time_s - initialState.time_s;
arrivalTime_s = initialState.time_s + horizon_s * ...
    linspace(0.1, 1, 10).';
obstacleSampleTime_s = zeros(0, 1);
for obstacleIndex = 1:numel(obstacleField.Obstacles)
    obstacleSampleTime_s = [obstacleSampleTime_s; ...
        obstacleField.Obstacles(obstacleIndex).TimeSeconds(:)]; %#ok<AGROW>
end
midpointAlignedArrival_s = initialState.time_s + 2 * ...
    (obstacleSampleTime_s - initialState.time_s);
arrivalTime_s = unique([arrivalTime_s; midpointAlignedArrival_s]);
arrivalTime_s = arrivalTime_s(arrivalTime_s > initialState.time_s & ...
    arrivalTime_s <= goalState.time_s);
for arrivalIndex = 1:numel(arrivalTime_s)
    time_s = initialState.time_s + pathFraction * ...
        (arrivalTime_s(arrivalIndex) - initialState.time_s);
    collisionMask = queryAzElTimedPathCollision(obstacleField, ...
        time_s, position_deg, struct( ...
        "TimePaddingSamples", options.CollisionTimePaddingSamples, ...
        "BoundaryIsOccupied", false, "StopAtFirstCollision", true));
    if ~any(collisionMask)
        plausible = true;
        seedRouteTime_s = [initialState.time_s; ...
            arrivalTime_s(arrivalIndex)];
        return;
    end
end
end

function [seeds, routes_deg, reduction] = collectSeeds( ...
        initialState, goalState, search, options, includeDirectSeed, ...
        isObstacleGeometryTimeInvariant, directSeedRoute_deg, ...
        directSeedRouteTime_s)
% PURPOSE
%   - Use a plausible direct seed, then deterministic topology/time seeds.
template = struct( ...
    "Source", "direct", ...
    "SnapshotTime_s", initialState.time_s, ...
    "GraphIndex", 0, ...
    "RouteCost_deg", 0, ...
    "Route_deg", zeros(0, 2), ...
    "RouteTime_s", zeros(0, 1), ...
    "RouteSignature", "");
directSeed = template;
directSeed.Route_deg = directSeedRoute_deg;
directSeed.RouteTime_s = directSeedRouteTime_s;
directSeed.RouteCost_deg = routeLength(directSeedRoute_deg);
seeds = repmat(template, 0, 1);
if includeDirectSeed
    seeds = directSeed;
end
graphSources = {search.VisibilityGraphs, search.MergedVisibilityGraphs};
sourceNames = ["visibilityGraph" "mergedObstacleGraph"];
collectedVisibilitySeeds = repmat(template, 0, 1);
spaceTimeGraph = search.SpaceTimeVisibilityGraph;
timedCandidates = repmat(struct( ...
    "Position_deg", zeros(0, 2), ...
    "Time_s", zeros(0, 1), ...
    "AngularLength_deg", Inf, ...
    "WaitDuration_s", 0, ...
    "RouteSignature", ""), 0, 1);
primaryTimedRouteAddsDecision = spaceTimeGraph.Success && ...
    timedRouteAddsDecision(spaceTimeGraph.PathPosition_deg, ...
    spaceTimeGraph.PathTime_s, goalState.position_deg);
if primaryTimedRouteAddsDecision && ...
        isfield(spaceTimeGraph, "DiverseCandidates")
    timedCandidates = spaceTimeGraph.DiverseCandidates;
elseif primaryTimedRouteAddsDecision
    timedCandidates = struct( ...
        "Position_deg", spaceTimeGraph.PathPosition_deg, ...
        "Time_s", spaceTimeGraph.PathTime_s, ...
        "AngularLength_deg", spaceTimeGraph.PathCost_deg, ...
        "WaitDuration_s", spaceTimeGraph.WaitDuration_s, ...
        "RouteSignature", "legacySpaceTimeRoute");
end
if ~isempty(timedCandidates) && primaryTimedRouteAddsDecision
    primaryTimedCandidateIndex = 0;
    for timedCandidateIndex = 1:numel(timedCandidates)
        candidatePosition_deg = ...
            timedCandidates(timedCandidateIndex).Position_deg;
        candidateTime_s = timedCandidates(timedCandidateIndex).Time_s;
        samePosition = routesHaveSameGeometry( ...
            candidatePosition_deg, spaceTimeGraph.PathPosition_deg);
        sameTime = isequal(size(candidateTime_s), ...
            size(spaceTimeGraph.PathTime_s)) && ...
            max(abs(candidateTime_s - ...
            spaceTimeGraph.PathTime_s), [], "all") <= 1e-10;
        if samePosition && sameTime
            primaryTimedCandidateIndex = timedCandidateIndex;
            break;
        end
    end
    if primaryTimedCandidateIndex > 1
        timedCandidateOrder = [primaryTimedCandidateIndex, ...
            1:primaryTimedCandidateIndex - 1, ...
            primaryTimedCandidateIndex + 1:numel(timedCandidates)];
        timedCandidates = timedCandidates(timedCandidateOrder);
    end
end
for timedCandidateIndex = 1:numel(timedCandidates)
    timedCandidate = timedCandidates(timedCandidateIndex);
    candidateAddsDecision = timedRouteAddsDecision( ...
        timedCandidate.Position_deg, timedCandidate.Time_s, ...
        goalState.position_deg);
    if ~candidateAddsDecision
        continue;
    end
    seed = template;
    seed.Source = "spaceTimeVisibilityGraph";
    seed.SnapshotTime_s = mean(timedCandidate.Time_s);
    seed.GraphIndex = timedCandidateIndex;
    seed.RouteCost_deg = timedCandidate.AngularLength_deg;
    seed.Route_deg = timedCandidate.Position_deg;
    seed.RouteTime_s = timedCandidate.Time_s;
    seed.RouteSignature = timedCandidate.RouteSignature;
    collectedVisibilitySeeds(end + 1, 1) = seed; %#ok<AGROW>
end
for sourceIndex = 1:numel(graphSources)
    graphs = graphSources{sourceIndex};
    for graphIndex = 1:numel(graphs)
        if ~graphs(graphIndex).Success || ...
                isempty(graphs(graphIndex).PathPosition_deg)
            continue;
        end
        seed = template;
        seed.Source = sourceNames(sourceIndex);
        seed.SnapshotTime_s = graphs(graphIndex).Time_s;
        seed.GraphIndex = graphIndex;
        seed.RouteCost_deg = graphs(graphIndex).PathCost_deg;
        seed.Route_deg = graphs(graphIndex).PathPosition_deg;
        % The visibility search retains few snapshots, so bounded growth
        % keeps the original stable insertion index for later tie breaks.
        collectedVisibilitySeeds(end + 1, 1) = seed; %#ok<AGROW>
        if ~isempty(graphs(graphIndex).AlternativePathPosition_deg)
            alternativeSeed = template;
            alternativeSeed.Source = sourceNames(sourceIndex) + ...
                "Alternative";
            alternativeSeed.SnapshotTime_s = graphs(graphIndex).Time_s;
            alternativeSeed.GraphIndex = graphIndex;
            alternativeSeed.RouteCost_deg = ...
                graphs(graphIndex).AlternativePathCost_deg;
            alternativeSeed.Route_deg = ...
                graphs(graphIndex).AlternativePathPosition_deg;
            collectedVisibilitySeeds(end + 1, 1) = ...
                alternativeSeed; %#ok<AGROW>
        end
    end
end
if ~isempty(collectedVisibilitySeeds)
    isSpaceTimeSeed = [collectedVisibilitySeeds.Source].' == ...
        "spaceTimeVisibilityGraph";
    hasDelayedDirectSeed = ~isempty(seeds) && ...
        any([seeds.Source] == "direct");
    % A successful primary SIPP-IP route contains collision-checked
    % temporal decisions that an untimed snapshot route does not preserve.
    % Retain one primary timed route, then prefer spatial fallback evidence
    % before extra SIPP diversity variants consume a bounded seed budget.
    isPrimarySpaceTimeSeed = isSpaceTimeSeed & ...
        [collectedVisibilitySeeds.GraphIndex].' == 1;
    timedSeedClass = ones(numel(collectedVisibilitySeeds), 1);
    availableVisibilitySeedSlotCount = max(0, ...
        options.MaximumDirectCollocationSeeds - numel(seeds));
    canReserveTimedEvidence = hasDelayedDirectSeed || ...
        availableVisibilitySeedSlotCount >= 2;
    if canReserveTimedEvidence
        timedSeedClass(isPrimarySpaceTimeSeed) = 0;
    end
    if hasDelayedDirectSeed
        timedSeedClass(isSpaceTimeSeed) = 0;
    end
    isReducedMergedSeed = contains( ...
        [collectedVisibilitySeeds.Source].', "mergedObstacleGraph");
    repeatsDirectGeometryWithoutTiming = false( ...
        numel(collectedVisibilitySeeds), 1);
    if hasDelayedDirectSeed
        directRoute_deg = seeds(find( ...
            [seeds.Source] == "direct", 1, "first")).Route_deg;
        for candidateIndex = 1:numel(collectedVisibilitySeeds)
            candidate = collectedVisibilitySeeds(candidateIndex);
            repeatsDirectGeometryWithoutTiming(candidateIndex) = ...
                ~isSpaceTimeSeed(candidateIndex) && ...
                routesHaveSameGeometry( ...
                candidate.Route_deg, directRoute_deg);
        end
    end
    % Full protected-field topology is stronger evidence than a route from
    % a reduced merged graph. Cost ranks only after this fidelity class.
    ranking = [isReducedMergedSeed, timedSeedClass, ...
        repeatsDirectGeometryWithoutTiming, ...
        [collectedVisibilitySeeds.RouteCost_deg].', ...
        [collectedVisibilitySeeds.SnapshotTime_s].', ...
        (1:numel(collectedVisibilitySeeds)).'];
    [~, order] = sortrows(ranking, 1:size(ranking, 2));
    collectedVisibilitySeeds = collectedVisibilitySeeds(order);
end
collectedCandidateSeedCount = ...
    numel(seeds) + numel(collectedVisibilitySeeds);

% Sort before deduplication so equal static routes keep the cheapest,
% earliest, and then earliest-inserted graph source deterministically.
visibilitySeeds = repmat(template, 0, 1);
for seedIndex = 1:numel(collectedVisibilitySeeds)
    seed = collectedVisibilitySeeds(seedIndex);
    if routeDuplicatesAny(seed.Route_deg, seed.SnapshotTime_s, ...
            [seeds; visibilitySeeds], ...
            isObstacleGeometryTimeInvariant)
        continue;
    end
    visibilitySeeds(end + 1, 1) = seed; %#ok<AGROW>
end
maximumVisibilitySeedCount = max(0, ...
    options.MaximumDirectCollocationSeeds - numel(seeds));
deduplicatedCandidateSeedCount = numel(seeds) + numel(visibilitySeeds);
visibilitySeeds = selectBoundedTemporalSeeds( ...
    visibilitySeeds, maximumVisibilitySeedCount, seeds);
seeds = [seeds; visibilitySeeds];
routes_deg = reshape({seeds.Route_deg}, [], 1);
reduction = struct( ...
    "CollectedCandidateSeedCount", collectedCandidateSeedCount, ...
    "DeduplicatedCandidateSeedCount", ...
    deduplicatedCandidateSeedCount, ...
    "SeedCapDroppedCount", ...
    deduplicatedCandidateSeedCount - numel(seeds));
end

function duplicates = routeDuplicatesAny( ...
        route_deg, snapshotTime_s, seeds, ...
        isObstacleGeometryTimeInvariant)
% PURPOSE
%   - Collapse cross-time route copies only for a fully static field.
duplicates = false;
for seedIndex = 1:numel(seeds)
    sameTemporalSeed = isObstacleGeometryTimeInvariant || ...
        abs(snapshotTime_s - seeds(seedIndex).SnapshotTime_s) <= 1e-10;
    if sameTemporalSeed && routesHaveSameGeometry( ...
            route_deg, seeds(seedIndex).Route_deg)
        duplicates = true;
        return;
    end
end
end

function matches = routesHaveSameGeometry(firstRoute_deg, secondRoute_deg)
% PURPOSE
%   - Compare route geometry without attaching snapshot-time meaning.
firstRoute_deg = removeConsecutiveRoutePoints(firstRoute_deg);
secondRoute_deg = removeConsecutiveRoutePoints(secondRoute_deg);
matches = isequal(size(firstRoute_deg), size(secondRoute_deg)) && ...
    max(abs(firstRoute_deg - secondRoute_deg), [], "all") <= 1e-10;
end

function route_deg = removeConsecutiveRoutePoints(route_deg)
% PURPOSE
%   - Compare spatial topology without treating waiting as new geometry.
if size(route_deg, 1) < 2
    return;
end
keepRow = [true; any(abs(diff(route_deg, 1, 1)) > 1e-10, 2)];
route_deg = route_deg(keepRow, :);
end

function addsDecision = timedRouteAddsDecision( ...
        route_deg, routeTime_s, goalPosition_deg)
% PURPOSE
%   - Ignore a direct route whose only wait is at the fixed-arrival goal.
addsDecision = false;
if size(route_deg, 1) < 2 || numel(routeTime_s) ~= size(route_deg, 1)
    return;
end
compressedRoute_deg = removeConsecutiveRoutePoints(route_deg);
if size(compressedRoute_deg, 1) > 2
    addsDecision = true;
    return;
end
routeStep_deg = diff(route_deg, 1, 1);
waitEdge = hypot(routeStep_deg(:, 1), routeStep_deg(:, 2)) <= 1e-10 & ...
    diff(routeTime_s(:)) > 1e-10;
waitPosition_deg = route_deg(1:end - 1, :);
waitGoalOffset_deg = waitPosition_deg - goalPosition_deg;
waitsAwayFromGoal = waitEdge & ...
    hypot(waitGoalOffset_deg(:, 1), waitGoalOffset_deg(:, 2)) > 1e-10;
addsDecision = any(waitsAwayFromGoal);
end

function selectedSeeds = selectBoundedTemporalSeeds( ...
        seeds, maximumCount, preselectedSeeds)
% PURPOSE
%   - Keep the cheapest topology seed, then spread retained seed times.
if maximumCount <= 0 || isempty(seeds)
    selectedSeeds = seeds([]);
    return;
end
maximumCount = min(maximumCount, numel(seeds));
if numel(seeds) <= maximumCount
    selectedSeeds = seeds;
    return;
end

selectedIndex = zeros(maximumCount, 1);
isSelected = false(numel(seeds), 1);
% Distinct geometry must survive before extra time laws for an already
% retained route. This prevents moving snapshots of one route from removing
% a valid alternative topology.
selectedCount = 0;
while selectedCount < maximumCount
    remainingIndex = find(~isSelected);
    selectedSeedPool = [preselectedSeeds; seeds(isSelected)];
    chosenIndex = 0;
    for remainingPosition = 1:numel(remainingIndex)
        seedIndex = remainingIndex(remainingPosition);
        geometryAlreadySelected = routeDuplicatesAny( ...
            seeds(seedIndex).Route_deg, ...
            seeds(seedIndex).SnapshotTime_s, selectedSeedPool, true);
        if ~geometryAlreadySelected
            chosenIndex = seedIndex;
            break;
        end
    end
    if chosenIndex == 0
        break;
    end
    selectedCount = selectedCount + 1;
    selectedIndex(selectedCount) = chosenIndex;
    isSelected(chosenIndex) = true;
end
if selectedCount == 0
    selectedCount = 1;
    selectedIndex(selectedCount) = 1;
    isSelected(1) = true;
end
snapshotTime_s = [seeds.SnapshotTime_s].';
routeCost_deg = [seeds.RouteCost_deg].';
distinctTimeTolerance_s = 1e-10;
preselectedTime_s = [preselectedSeeds.SnapshotTime_s].';
preselectedTime_s = preselectedTime_s(isfinite(preselectedTime_s));

while selectedCount < maximumCount
    remainingIndex = find(~isSelected);
    selectedTime_s = [preselectedTime_s; ...
        snapshotTime_s(isSelected & isfinite(snapshotTime_s))];
    if isempty(selectedTime_s)
        break;
    end
    minimumSeparation_s = -inf(numel(remainingIndex), 1);
    for remainingPosition = 1:numel(remainingIndex)
        seedIndex = remainingIndex(remainingPosition);
        if isfinite(snapshotTime_s(seedIndex))
            minimumSeparation_s(remainingPosition) = min(abs( ...
                snapshotTime_s(seedIndex) - selectedTime_s));
        end
    end
    distinctTime = minimumSeparation_s > distinctTimeTolerance_s;
    if ~any(distinctTime)
        break;
    end
    distinctIndex = remainingIndex(distinctTime);
    distinctSeparation_s = minimumSeparation_s(distinctTime);
    ranking = [-distinctSeparation_s, routeCost_deg(distinctIndex), ...
        snapshotTime_s(distinctIndex), distinctIndex];
    [~, order] = sortrows(ranking, [1 2 3 4]);
    selectedCount = selectedCount + 1;
    chosenIndex = distinctIndex(order(1));
    selectedIndex(selectedCount) = chosenIndex;
    isSelected(chosenIndex) = true;
end

% The remaining input order is already the stable cost ranking.
remainingSlotCount = maximumCount - selectedCount;
if remainingSlotCount > 0
    costFillIndex = find(~isSelected, remainingSlotCount, "first");
    selectedIndex(selectedCount + (1:remainingSlotCount)) = ...
        costFillIndex;
end
selectedSeeds = seeds(selectedIndex);
end

function isTimeInvariant = packedGeometryIsTimeInvariant(obstacleField)
% PURPOSE
%   - Prove exact equality of protected packed geometry at every slice.
isTimeInvariant = true;
for obstacleIndex = 1:numel(obstacleField.Obstacles)
    obstacle = obstacleField.Obstacles(obstacleIndex);
    if obstacle.SampleCount <= 1
        continue;
    end
    referenceVertexRows = packedRows(obstacle.SliceOffsets, 1);
    referenceEdgeRows = packedRows(obstacle.EdgeOffsets, 1);
    referenceAzimuth_deg = obstacle.AzimuthDeg(referenceVertexRows);
    referenceElevation_deg = obstacle.ElevationDeg(referenceVertexRows);
    referenceEdges_deg = [ ...
        obstacle.EdgeStartAzimuthDeg(referenceEdgeRows), ...
        obstacle.EdgeStartElevationDeg(referenceEdgeRows), ...
        obstacle.EdgeEndAzimuthDeg(referenceEdgeRows), ...
        obstacle.EdgeEndElevationDeg(referenceEdgeRows)];
    referenceBounds_deg = obstacle.BoundsDeg(1, :);
    for sampleIndex = 2:obstacle.SampleCount
        vertexRows = packedRows(obstacle.SliceOffsets, sampleIndex);
        edgeRows = packedRows(obstacle.EdgeOffsets, sampleIndex);
        edges_deg = [ ...
            obstacle.EdgeStartAzimuthDeg(edgeRows), ...
            obstacle.EdgeStartElevationDeg(edgeRows), ...
            obstacle.EdgeEndAzimuthDeg(edgeRows), ...
            obstacle.EdgeEndElevationDeg(edgeRows)];
        verticesMatch = isequaln( ...
            obstacle.AzimuthDeg(vertexRows), referenceAzimuth_deg) && ...
            isequaln(obstacle.ElevationDeg(vertexRows), ...
            referenceElevation_deg);
        edgesMatch = isequaln(edges_deg, referenceEdges_deg);
        boundsMatch = isequaln( ...
            obstacle.BoundsDeg(sampleIndex, :), referenceBounds_deg);
        if ~(verticesMatch && edgesMatch && boundsMatch)
            isTimeInvariant = false;
            return;
        end
    end
end
end

function rows = packedRows(offsets, sampleIndex)
% PURPOSE
%   - Convert one packed CSR slice to a valid row-index vector.
firstRow = double(offsets(sampleIndex));
finalRow = double(offsets(sampleIndex + 1)) - 1;
rows = firstRow:finalRow;
end

function diagnostic = emptyCandidateDiagnostic()
% PURPOSE
%   - Define planner-level diagnostics for one optimized seed.
diagnostic = struct( ...
    "Index", 0, "SeedIndex", 0, "SeedSource", "", ...
    "SeedSnapshotTime_s", NaN, "SeedGraphIndex", 0, ...
    "SeedRouteCost_deg", Inf, "SeedRoute_deg", zeros(0, 2), ...
    "SeedRouteTime_s", zeros(0, 1), ...
    "TimedSeedLawUsed", false, ...
    "SeedRouteTimeFraction", zeros(0, 1), ...
    "SeedRouteProgress", zeros(0, 1), ...
    "InitialGuessProjectionSucceeded", false, ...
    "InitialGuessMessage", "", ...
    "InitialGuessMaximumHs3Defect", Inf, ...
    "InitialGuessInitialStateError", inf(1, 6), ...
    "InitialGuessTerminalStateError", inf(1, 6), ...
    "InitialGuessMaximumBoundAdjustment", Inf, ...
    "InitialGuessCollisionFree", false, ...
    "InitialGuessValidationPassed", false, ...
    "SelectedSolutionSource", "", ...
    "Success", false, ...
    "TerminationReason", "notEvaluated", "SolverExitFlag", NaN, ...
    "SolverMessage", "", "ObjectiveArrivalTime_s", Inf, ...
    "SolverExitFlagHistory", zeros(0, 1), ...
    "SolverMessageHistory", strings(0, 1), ...
    "SolverTimeLimitReachedHistory", false(0, 1), ...
    "SolverMeshPassHistory", zeros(0, 1), ...
    "SolverCorridorPassHistory", zeros(0, 1), ...
    "SolverStageHistory", strings(0, 1), ...
    "StageOneMinimumArrivalTime_s", Inf, ...
    "FinalTieBreakArrivalTime_s", Inf, ...
    "AllowedTimeTieTolerance_s", NaN, ...
    "StageOneIntegratedSquaredJerk", Inf, ...
    "StageOneSolutionSource", "", ...
    "FixedArrivalFeasibilityStagePassed", false, ...
    "FixedArrivalFeasibilityIntegratedSquaredJerk", NaN, ...
    "FixedArrivalJerkRefinementAttempted", false, ...
    "FixedArrivalJerkRefinementAccepted", false, ...
    "FixedArrivalJerkRefinementExitFlag", NaN, ...
    "FixedArrivalJerkRefinementMessage", "", ...
    "FixedArrivalRefinedIntegratedSquaredJerk", NaN, ...
    "FixedArrivalJerkRefinementTimeLimitReached", false, ...
    "TieBreakAttempted", false, "TieBreakAccepted", false, ...
    "TieBreakExitFlag", NaN, "TieBreakMessage", "", ...
    "TieBreakIntegratedSquaredJerk", NaN, ...
    "SolverTimeLimitReached", false, ...
    "TimeBudgetReached", false, ...
    "MotionDuration_s", Inf, "IntegratedSquaredJerk", Inf, ...
    "MeshPassCount", 0, "SegmentCountHistory", zeros(0, 1), ...
    "MeshObjectiveHistory", zeros(0, 1), ...
    "MeshObjectiveChangeHistory", zeros(0, 1), ...
    "MeshRefinementConverged", false, ...
    "MeshRefinementConvergenceTolerance", NaN, ...
    "NlpIterationCount", 0, "NlpFunctionEvaluationCount", 0, ...
    "MaximumCollocationDefect", Inf, ...
    "MaximumNlpInequalityViolation", Inf, ...
    "MaximumDynamicsDefect", Inf, ...
    "MaximumVelocityViolation_deg_s", [Inf Inf], ...
    "MaximumAccelerationViolation_deg_s2", [Inf Inf], ...
    "MaximumJerkViolation_deg_s3", [Inf Inf], ...
    "MaximumVelocity_deg_s", [Inf Inf], ...
    "MaximumAcceleration_deg_s2", [Inf Inf], ...
    "MaximumJerk_deg_s3", [Inf Inf], ...
    "MinimumObstacleClearance_deg", NaN, ...
    "CorridorRelinearizationCount", 0, ...
    "CollisionValidationPerformed", false, ...
    "CollisionValidationPassed", false, ...
    "BufferedChordQueryClear", false, ...
    "CollisionSafetyProven", false, ...
    "CollisionClearanceDiagnostics", ...
    emptyCollisionClearanceDiagnostics(), ...
    "CollisionFree", false, ...
    "Validation", emptyValidation(), "ElapsedTime_s", 0, ...
    "Message", "");
end

function diagnostic = candidateDiagnostic(seedIndex, seed, candidate)
% PURPOSE
%   - Map internal solver output to stable public search diagnostics.
diagnostic = emptyCandidateDiagnostic();
diagnostic.Index = seedIndex;
diagnostic.SeedIndex = seedIndex;
diagnostic.SeedSource = seed.Source;
diagnostic.SeedSnapshotTime_s = seed.SnapshotTime_s;
diagnostic.SeedGraphIndex = seed.GraphIndex;
diagnostic.SeedRouteCost_deg = seed.RouteCost_deg;
diagnostic.SeedRoute_deg = seed.Route_deg;
diagnostic.SeedRouteTime_s = seed.RouteTime_s;
diagnostic.TimedSeedLawUsed = candidate.TimedSeedLawUsed;
diagnostic.SeedRouteTimeFraction = candidate.SeedRouteTimeFraction;
diagnostic.SeedRouteProgress = candidate.SeedRouteProgress;
diagnostic.InitialGuessProjectionSucceeded = ...
    candidate.InitialGuessProjectionSucceeded;
diagnostic.InitialGuessMessage = candidate.InitialGuessMessage;
diagnostic.InitialGuessMaximumHs3Defect = ...
    candidate.InitialGuessMaximumHs3Defect;
diagnostic.InitialGuessInitialStateError = ...
    candidate.InitialGuessInitialStateError;
diagnostic.InitialGuessTerminalStateError = ...
    candidate.InitialGuessTerminalStateError;
diagnostic.InitialGuessMaximumBoundAdjustment = ...
    candidate.InitialGuessMaximumBoundAdjustment;
diagnostic.InitialGuessCollisionFree = ...
    candidate.InitialGuessCollisionFree;
diagnostic.InitialGuessValidationPassed = ...
    candidate.InitialGuessValidationPassed;
diagnostic.SelectedSolutionSource = candidate.SelectedSolutionSource;
diagnostic.Success = candidate.Success;
diagnostic.TerminationReason = candidate.TerminationReason;
diagnostic.SolverExitFlag = candidate.SolverExitFlag;
diagnostic.SolverMessage = candidate.SolverMessage;
diagnostic.SolverExitFlagHistory = candidate.SolverExitFlagHistory;
diagnostic.SolverMessageHistory = candidate.SolverMessageHistory;
diagnostic.SolverTimeLimitReachedHistory = ...
    candidate.SolverTimeLimitReachedHistory;
diagnostic.SolverMeshPassHistory = candidate.SolverMeshPassHistory;
diagnostic.SolverCorridorPassHistory = ...
    candidate.SolverCorridorPassHistory;
diagnostic.SolverStageHistory = candidate.SolverStageHistory;
diagnostic.ObjectiveArrivalTime_s = candidate.ArrivalTime_s;
diagnostic.StageOneMinimumArrivalTime_s = ...
    candidate.StageOneMinimumArrivalTime_s;
diagnostic.FinalTieBreakArrivalTime_s = ...
    candidate.FinalTieBreakArrivalTime_s;
diagnostic.AllowedTimeTieTolerance_s = ...
    candidate.AllowedTimeTieTolerance_s;
diagnostic.StageOneIntegratedSquaredJerk = ...
    candidate.StageOneIntegratedSquaredJerk;
diagnostic.StageOneSolutionSource = candidate.StageOneSolutionSource;
diagnostic.FixedArrivalFeasibilityStagePassed = ...
    candidate.FixedArrivalFeasibilityStagePassed;
diagnostic.FixedArrivalFeasibilityIntegratedSquaredJerk = ...
    candidate.FixedArrivalFeasibilityIntegratedSquaredJerk;
diagnostic.FixedArrivalJerkRefinementAttempted = ...
    candidate.FixedArrivalJerkRefinementAttempted;
diagnostic.FixedArrivalJerkRefinementAccepted = ...
    candidate.FixedArrivalJerkRefinementAccepted;
diagnostic.FixedArrivalJerkRefinementExitFlag = ...
    candidate.FixedArrivalJerkRefinementExitFlag;
diagnostic.FixedArrivalJerkRefinementMessage = ...
    candidate.FixedArrivalJerkRefinementMessage;
diagnostic.FixedArrivalRefinedIntegratedSquaredJerk = ...
    candidate.FixedArrivalRefinedIntegratedSquaredJerk;
diagnostic.FixedArrivalJerkRefinementTimeLimitReached = ...
    candidate.FixedArrivalJerkRefinementTimeLimitReached;
diagnostic.TieBreakAttempted = candidate.TieBreakAttempted;
diagnostic.TieBreakAccepted = candidate.TieBreakAccepted;
diagnostic.TieBreakExitFlag = candidate.TieBreakExitFlag;
diagnostic.TieBreakMessage = candidate.TieBreakMessage;
diagnostic.TieBreakIntegratedSquaredJerk = ...
    candidate.TieBreakIntegratedSquaredJerk;
diagnostic.SolverTimeLimitReached = candidate.SolverTimeLimitReached;
diagnostic.TimeBudgetReached = candidate.TimeBudgetReached;
diagnostic.MotionDuration_s = candidate.MotionDuration_s;
diagnostic.IntegratedSquaredJerk = candidate.IntegratedSquaredJerk;
diagnostic.MeshPassCount = candidate.MeshPassCount;
diagnostic.SegmentCountHistory = candidate.SegmentCountHistory;
diagnostic.MeshObjectiveHistory = candidate.MeshObjectiveHistory;
diagnostic.MeshObjectiveChangeHistory = ...
    candidate.MeshObjectiveChangeHistory;
diagnostic.MeshRefinementConverged = ...
    candidate.MeshRefinementConverged;
diagnostic.MeshRefinementConvergenceTolerance = ...
    candidate.MeshRefinementConvergenceTolerance;
diagnostic.NlpIterationCount = candidate.SolverIterationCount;
diagnostic.NlpFunctionEvaluationCount = ...
    candidate.SolverFunctionEvaluationCount;
diagnostic.MaximumCollocationDefect = ...
    candidate.MaximumCollocationDefect;
diagnostic.MaximumNlpInequalityViolation = ...
    candidate.MaximumNlpInequalityViolation;
diagnostic.MaximumDynamicsDefect = candidate.MaximumDynamicsDefect;
diagnostic.MaximumVelocityViolation_deg_s = ...
    candidate.MaximumVelocityViolation_deg_s;
diagnostic.MaximumAccelerationViolation_deg_s2 = ...
    candidate.MaximumAccelerationViolation_deg_s2;
diagnostic.MaximumJerkViolation_deg_s3 = ...
    candidate.MaximumJerkViolation_deg_s3;
diagnostic.MaximumVelocity_deg_s = candidate.MaximumVelocity_deg_s;
diagnostic.MaximumAcceleration_deg_s2 = ...
    candidate.MaximumAcceleration_deg_s2;
diagnostic.MaximumJerk_deg_s3 = candidate.MaximumJerk_deg_s3;
diagnostic.MinimumObstacleClearance_deg = candidate.MinimumClearance_deg;
diagnostic.CorridorRelinearizationCount = ...
    candidate.CorridorRelinearizationCount;
diagnostic.CollisionValidationPerformed = ...
    candidate.CollisionValidationPerformed;
diagnostic.CollisionValidationPassed = candidate.CollisionValidationPassed;
diagnostic.BufferedChordQueryClear = ...
    candidate.BufferedChordQueryClear;
diagnostic.CollisionSafetyProven = candidate.CollisionSafetyProven;
diagnostic.CollisionClearanceDiagnostics = ...
    candidate.CollisionClearanceDiagnostics;
diagnostic.CollisionFree = candidate.CollisionFree;
diagnostic.Validation = candidate.Validation;
diagnostic.ElapsedTime_s = candidate.ElapsedTime_s;
diagnostic.Message = candidate.Message;
end

function [selectedIndex, success] = selectCandidate( ...
        diagnostics, timeTieTolerance_s)
% PURPOSE
%   - Select validated earliest arrival, then jerk, then stable seed index.
selectedIndex = 0;
success = false;
if isempty(diagnostics)
    return;
end
feasibleIndex = find([diagnostics.Success]);
if ~isempty(feasibleIndex)
    arrivalTime_s = [diagnostics(feasibleIndex).ObjectiveArrivalTime_s].';
    bestArrival_s = min(arrivalTime_s);
    nearBest = feasibleIndex(arrivalTime_s <= ...
        bestArrival_s + timeTieTolerance_s);
    ranking = [[diagnostics(nearBest).IntegratedSquaredJerk].', ...
        nearBest(:)];
    [~, order] = sortrows(ranking, [1 2]);
    selectedIndex = nearBest(order(1));
    success = true;
    return;
end
finiteIndex = find(isfinite([diagnostics.ObjectiveArrivalTime_s]));
if isempty(finiteIndex)
    selectedIndex = 1;
else
    ranking = [[diagnostics(finiteIndex).ObjectiveArrivalTime_s].', ...
        finiteIndex(:)];
    [~, order] = sortrows(ranking, [1 2]);
    selectedIndex = finiteIndex(order(1));
end
end

function timedPath = compatibilityTimedPath(candidate, initialState)
% PURPOSE
%   - Expose direct-collocation motion through the maintained timed schema.
trajectory = candidate.Trajectory;
continuousExtremaVerified = ...
    candidate.Validation.ContinuousPolynomialExtremaVerified;
constraintDiagnostics = struct( ...
    "FiniteJerkCertified", candidate.Validation.JerkWithinLimits, ...
    "FiniteJerkNumericallyVerified", ...
    candidate.Validation.JerkWithinLimits, ...
    "ContinuousPolynomialExtremaVerified", ...
    continuousExtremaVerified, ...
    "DynamicsDefectWithinTolerance", ...
    candidate.Validation.DynamicsDefectWithinTolerance, ...
    "CurveSubdivisionConverged", ...
    candidate.Validation.CurveSubdivisionConverged, ...
    "MaximumCurveDeviationBound_deg", ...
    candidate.Validation.MaximumCurveDeviationBound_deg, ...
    "MaximumDynamicsDefect", candidate.MaximumDynamicsDefect, ...
    "DynamicsConsistencyScope", ...
    candidate.Validation.DynamicsConsistencyScope, ...
    "MaximumVelocity_deg_s", candidate.MaximumVelocity_deg_s, ...
    "MaximumAcceleration_deg_s2", ...
    candidate.MaximumAcceleration_deg_s2, ...
    "MaximumJerk_deg_s3", candidate.MaximumJerk_deg_s3);
timedPath = struct( ...
    "Success", candidate.Success, "Message", candidate.Message, ...
    "MotionType", "directCollocation", ...
    "RetimerType", "rlSeededHs3", ...
    "time_s", trajectory.time_s, ...
    "position_deg", trajectory.position_deg, ...
    "velocity_deg_s", trajectory.velocity_deg_s, ...
    "acceleration_deg_s2", trajectory.acceleration_deg_s2, ...
    "jerk_deg_s3", trajectory.jerk_deg_s3, ...
    "MotionStartTime_s", initialState.time_s, ...
    "DepartureCandidateTime_s", initialState.time_s, ...
    "ArrivalTime_s", candidate.ArrivalTime_s, ...
    "GoalLineInterceptTime_s", candidate.ArrivalTime_s, ...
    "MotionDuration_s", candidate.MotionDuration_s, ...
    "MinimumMotionDuration_s", candidate.MotionDuration_s, ...
    "PathLength_deg", routeLength(trajectory.position_deg), ...
    "IntegratedSquaredJerk", candidate.IntegratedSquaredJerk, ...
    "ConstraintDiagnostics", constraintDiagnostics);
end

function timedPath = emptyTimedPath()
% PURPOSE
%   - Define the stable empty direct-collocation compatibility schema.
timedPath = struct( ...
    "Success", false, "Message", "No trajectory is available.", ...
    "MotionType", "directCollocation", ...
    "RetimerType", "rlSeededHs3", ...
    "time_s", zeros(0, 1), "position_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2), "MotionStartTime_s", NaN, ...
    "DepartureCandidateTime_s", NaN, "ArrivalTime_s", NaN, ...
    "GoalLineInterceptTime_s", NaN, "MotionDuration_s", NaN, ...
    "MinimumMotionDuration_s", NaN, "PathLength_deg", NaN, ...
    "IntegratedSquaredJerk", NaN, ...
    "ConstraintDiagnostics", struct( ...
    "FiniteJerkCertified", false, ...
    "FiniteJerkNumericallyVerified", false, ...
    "ContinuousPolynomialExtremaVerified", false, ...
    "DynamicsDefectWithinTolerance", false, ...
    "CurveSubdivisionConverged", false, ...
    "MaximumCurveDeviationBound_deg", Inf, ...
    "MaximumDynamicsDefect", Inf, ...
    "DynamicsConsistencyScope", ...
    "No HS-3 polynomial was available for a consistency check.", ...
    "MaximumVelocity_deg_s", [Inf Inf], ...
    "MaximumAcceleration_deg_s2", [Inf Inf], ...
    "MaximumJerk_deg_s3", [Inf Inf]));
end

function validation = emptyValidation()
% PURPOSE
%   - Define stable validation fields when no candidate was evaluated.
validation = struct( ...
    "Passed", false, ...
    "Message", "No trajectory was validated.", ...
    "TimeIsStrictlyIncreasing", false, ...
    "InitialStateMatched", false, ...
    "TerminalStateMatched", false, ...
    "GoalTimeSatisfied", false, ...
    "CollisionFree", false, ...
    "BufferedChordQueryClear", false, ...
    "CollisionSafetyProven", false, ...
    "CollisionValidationScope", ...
    "No trajectory was available for collision validation.", ...
    "CurveSubdivisionConverged", false, ...
    "MaximumCurveDeviationBound_deg", Inf, ...
    "VelocityWithinLimits", false, ...
    "AccelerationWithinLimits", false, ...
    "JerkWithinLimits", false, ...
    "PositionWithinBounds", false, ...
    "ContinuousPolynomialExtremaVerified", false, ...
    "DynamicsDefectWithinTolerance", false, ...
    "CollocationDefectWithinTolerance", false, ...
    "NlpInequalityWithinTolerance", false, ...
    "InitialStateError", inf(1, 6), ...
    "TerminalStateError", inf(1, 6), ...
    "MaximumDynamicsDefect", Inf, ...
    "DynamicsConsistencyScope", ...
    "No HS-3 polynomial was available for a consistency check.", ...
    "MaximumCollocationDefect", Inf, ...
    "MaximumNlpInequalityViolation", Inf, ...
    "MaximumVelocity_deg_s", [Inf Inf], ...
    "MaximumAcceleration_deg_s2", [Inf Inf], ...
    "MaximumJerk_deg_s3", [Inf Inf], ...
    "Issues", "notValidated");
end

function diagnostics = emptyCollisionClearanceDiagnostics()
% PURPOSE
%   - Define stable moving-edge clearance-proof diagnostics.
diagnostics = struct( ...
    "ProvenClear", false, ...
    "UnresolvedPathSegmentMask", false(0, 1), ...
    "UnresolvedPathSegmentCount", 0, ...
    "TopologyMismatchIntervalCount", 0, ...
    "EvaluatedEdgeIntervalCount", 0, ...
    "BroadPhaseRejectedEdgeIntervalCount", 0, ...
    "SubdivisionBoxCount", 0, ...
    "MaximumDepthReached", 0, ...
    "MaximumSubdivisionDepth", 18, ...
    "MaximumBoxesPerEdge", 20000, ...
    "MinimumProvenLowerBound_deg", NaN);
end

function trajectory = trajectoryView(timedPath)
% PURPOSE
%   - Provide direct top-level trajectory fields without duplicating logic.
trajectory = struct( ...
    "time_s", timedPath.time_s, ...
    "position_deg", timedPath.position_deg, ...
    "velocity_deg_s", timedPath.velocity_deg_s, ...
    "acceleration_deg_s2", timedPath.acceleration_deg_s2, ...
    "jerk_deg_s3", timedPath.jerk_deg_s3);
end

function tableOutput = candidateDiagnosticTable(diagnostics)
% PURPOSE
%   - Preserve familiar tabular candidate inspection for examples.
candidateCount = numel(diagnostics);
if candidateCount == 0
    tableOutput = table( ...
        zeros(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
        zeros(0, 1), false(0, 1), false(0, 1), false(0, 1), ...
        false(0, 1), false(0, 1), ...
        zeros(0, 1), zeros(0, 1), strings(0, 1), ...
        'VariableNames', {'Index', 'Source', 'SnapshotTime_s', ...
        'GraphIndex', 'PathLength_deg', 'Retimed', 'CollisionFree', ...
        'BufferedChordQueryClear', 'CollisionSafetyProven', ...
        'ContinuousCollisionChecked', ...
        'AttemptArrivalTime_s', 'ArrivalTime_s', 'Message'});
    return;
end
tableOutput = table( ...
    [diagnostics.Index].', [diagnostics.SeedSource].', ...
    [diagnostics.SeedSnapshotTime_s].', ...
    [diagnostics.SeedGraphIndex].', ...
    [diagnostics.SeedRouteCost_deg].', false(candidateCount, 1), ...
    [diagnostics.CollisionValidationPassed].', ...
    [diagnostics.BufferedChordQueryClear].', ...
    [diagnostics.CollisionSafetyProven].', ...
    [diagnostics.CollisionValidationPerformed].', ...
    [diagnostics.ObjectiveArrivalTime_s].', successArrival(diagnostics), ...
    [diagnostics.Message].', ...
    'VariableNames', {'Index', 'Source', 'SnapshotTime_s', ...
    'GraphIndex', 'PathLength_deg', 'Retimed', 'CollisionFree', ...
    'BufferedChordQueryClear', 'CollisionSafetyProven', ...
    'ContinuousCollisionChecked', ...
    'AttemptArrivalTime_s', 'ArrivalTime_s', 'Message'});
end

function arrivalTime_s = successArrival(diagnostics)
% PURPOSE
%   - Use Inf for failed candidate arrival in compatibility tables.
arrivalTime_s = [diagnostics.ObjectiveArrivalTime_s].';
arrivalTime_s(~[diagnostics.Success].') = Inf;
end

function searchDiagnostics = assembleSearchDiagnostics( ...
        search, seeds, candidates, selectedIndex, elapsedTime_s, ...
        options, terminationReason, parallelOptimizationExecution, ...
        isObstacleGeometryTimeInvariant, seedReductionDiagnostics)
% PURPOSE
%   - Assemble seed, NLP, validation, and optimality-scope evidence.
bestArrival_s = Inf;
if ~isempty(candidates) && any([candidates.Success])
    bestArrival_s = min([candidates([candidates.Success]). ...
        ObjectiveArrivalTime_s]);
end
visibilitySuccessCount = 0;
if ~isempty(search.VisibilityGraphs)
    visibilitySuccessCount = nnz([search.VisibilityGraphs.Success]);
end
mergedSuccessCount = 0;
if ~isempty(search.MergedVisibilityGraphs)
    mergedSuccessCount = nnz([search.MergedVisibilityGraphs.Success]);
end
% The repository certificate proves separation from the protected moving-edge
% interpolation that the collision query uses. A topology change uses the
% union of its endpoint polygons. This does not claim the more general Zhang
% et al. semi-infinite-program result. See citation.md.
optimalityScope = "Best independently validated minimum-time solution " + ...
    "found among the evaluated topology/time seeds.";
if options.GoalTimeMode == "fixedarrival"
    optimalityScope = "Best independently validated fixed-arrival " + ...
        "feasible solution found among the evaluated topology/time seeds; " + ...
        "minimum-jerk refinement is local when accepted.";
end
selectedUsesInitialGuessFallback = selectedIndex >= 1 && ...
    selectedIndex <= numel(candidates) && ...
    candidates(selectedIndex).SelectedSolutionSource == ...
    "validatedInitialGuess";
if selectedUsesInitialGuessFallback
    optimalityScope = "The selected result is an independently validated " + ...
        "HS-3 initial-guess fallback. No optimized minimum-time or " + ...
        "minimum-jerk claim is made for this result.";
end
continuousPolynomialCollisionProven = selectedIndex >= 1 && ...
    selectedIndex <= numel(candidates) && ...
    candidates(selectedIndex).CollisionSafetyProven;
searchDiagnostics = struct( ...
    "VisibilityGraphCount", numel(search.VisibilityGraphs), ...
    "SuccessfulVisibilityGraphCount", visibilitySuccessCount, ...
    "VisibilityGraphs", search.VisibilityGraphs, ...
    "MergedVisibilityGraphCount", numel(search.MergedVisibilityGraphs), ...
    "SuccessfulMergedVisibilityGraphCount", mergedSuccessCount, ...
    "MergedVisibilityGraphs", search.MergedVisibilityGraphs, ...
    "SpaceTimeVisibilityGraph", search.SpaceTimeVisibilityGraph, ...
    "SpaceTimeVisibilityGraphSucceeded", ...
    search.SpaceTimeVisibilityGraph.Success, ...
    "ObstacleMergeDiagnostics", search.ObstacleMergeDiagnostics, ...
    "ConnectivityDiagnostics", search.ConnectivityDiagnostics, ...
    "ConnectivityChangeIntervals", search.ConnectivityChangeIntervals, ...
    "PairwiseEventTimes_s", search.PairwiseEventTimes_s, ...
    "PairwiseEventDiagnostics", search.PairwiseEventDiagnostics, ...
    "SnapshotDiagnostics", search.SnapshotDiagnostics, ...
    "VisibilitySearchOptions", search.Options, ...
    "VisibilitySearchElapsedTime_s", search.ElapsedSearchTime_s, ...
    "VisibilitySearchTimeLimitReached", ...
    search.PlanningTimeLimitReached, ...
    "ObstacleGeometryTimeInvariant", ...
    isObstacleGeometryTimeInvariant, ...
    "CollectedCandidateSeedCount", ...
    seedReductionDiagnostics.CollectedCandidateSeedCount, ...
    "DeduplicatedCandidateSeedCount", ...
    seedReductionDiagnostics.DeduplicatedCandidateSeedCount, ...
    "SeedCapDroppedCount", ...
    seedReductionDiagnostics.SeedCapDroppedCount, ...
    "CandidateSeedCount", numel(seeds), ...
    "CandidateSeeds", seeds, ...
    "OptimizedCandidateCount", numel(candidates), ...
    "FeasibleCandidateCount", nnz([candidates.Success]), ...
    "CandidateRouteCount", numel(seeds), ...
    "SelectedCandidateIndex", selectedIndex, ...
    "CandidateOptimizations", candidates, ...
    "BestValidatedArrival_s", bestArrival_s, ...
    "OptimalityProven", false, ...
    "OptimalityScope", optimalityScope, ...
    "TimedRouteOptimalityCertified", false, ...
    "TimedRouteOptimalityScope", "Local multi-start direct collocation", ...
    "MotionType", "directCollocation", ...
    "RetimerType", "rlSeededHs3", ...
    "DirectCollocationTranscription", "reducedSeparatedGeneralizedHs3", ...
    "StateInterpolationMethod", ...
    "integratedQuadraticJerkCorrectedKellyEquation4_13", ...
    "DepartureTimeCandidates_s", zeros(0, 1), ...
    "DepartureTimeCandidateCount", 0, ...
    "WaitingIsOptimizedInTrajectory", true, ...
    "ContinuousCollisionRequiredForSuccess", true, ...
    "ContinuousPolynomialCollisionProven", ...
    continuousPolynomialCollisionProven, ...
    "CollisionValidationMethod", ...
    "Exact timed-chord intersection query plus conservative HS-3 " + ...
    "curve-tube clearance against linearly moving protected edges", ...
    "ParallelExecution", search.ParallelExecution, ...
    "DirectCollocationParallelExecution", ...
    parallelOptimizationExecution, ...
    "InitialCollocationSegmentCount", ...
    options.InitialCollocationSegmentCount, ...
    "MaximumMeshRefinementPasses", ...
    options.MaximumMeshRefinementPasses, ...
    "CollocationErrorTolerance", options.CollocationErrorTolerance, ...
    "MaximumSippPlanningFraction", ...
    options.MaximumSippPlanningFraction, ...
    "MinimumDirectCollocationSeedTime_s", ...
    options.MinimumDirectCollocationSeedTime_s, ...
    "PlanningTimeBudgetReached", isfinite(options.MaximumPlanningTime_s) && ...
    elapsedTime_s >= options.MaximumPlanningTime_s, ...
    "ElapsedPlanningTime_s", elapsedTime_s, ...
    "TerminationReason", terminationReason);
end

function length_deg = routeLength(route_deg)
% PURPOSE
%   - Compute polyline length for deterministic seed diagnostics.
if size(route_deg, 1) < 2
    length_deg = 0;
    return;
end
step_deg = diff(route_deg, 1, 1);
length_deg = sum(hypot(step_deg(:, 1), step_deg(:, 2)));
end
