function [isOccupied, collisionDetails] = queryAzElTimedPathCollision( ...
        obstacleField, time_s, position_deg, optionOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   optionDefaults = queryAzElTimedPathCollision()
%   isOccupied = queryAzElTimedPathCollision( ...
%       obstacleField, time_s, position_deg)
%   [isOccupied, collisionDetails] = queryAzElTimedPathCollision( ...
%       obstacleField, time_s, position_deg, optionOverrides)
%**************************************************************************
% PURPOSE
%   - Test both trajectory samples and every connecting line segment against
%     the complete packed polygon geometry.
%   - Preserve the nearest obstacle-slice and time-padding policy used by
%     queryAzElTimeObstacle without allowing clear endpoints to hide a
%     polygon crossing between samples.
%**************************************************************************
% INPUTS
%   - obstacleField (scalar packed obstacle field or canonical obstacle data)
%       Unpacked obstacle data is packed before the continuous query.
%   - time_s (numeric scalar or N-element vector)
%       A scalar applies one time to the complete spatial path. A vector must
%       be finite and nondecreasing, with one value per position row.
%   - position_deg (N-by-2 finite numeric array)
%       Ordered [azimuth elevation] trajectory samples. Connecting rows are
%       interpreted as line segments and checked continuously in space.
%   - optionOverrides (scalar struct, optional; default struct())
%       .TimePaddingSamples is a nonnegative integer (default 0).
%       .BoundaryIsOccupied controls exact polygon contact (default true).
%       .StopAtFirstCollision permits an incomplete segment scan after the
%       earliest collision is established (default false). This is useful
%       for rejecting candidates; complete trajectory validation keeps the
%       default false value.
%**************************************************************************
% OUTPUTS
%   - isOccupied (N-by-1 logical vector)
%       Row one reports its sample. Later rows report their sample or the
%       inbound segment, so any(isOccupied) validates the complete path.
%   - collisionDetails (scalar struct)
%       Stable sample/segment masks, blocking obstacle and source-slice
%       indices, evaluated-segment and obstacle-pair counts, broad-phase
%       rejects, scan-completion status, interpreted histories, and
%       resolved options.
%**************************************************************************
% UNITS
%   - Position is degrees and numeric time is seconds from ReferenceTime.
%**************************************************************************

%% Section 1: Validate Inputs & Apply Defaults

defaultOptions = struct( ...
    "TimePaddingSamples", 0, ...
    "BoundaryIsOccupied", true, ...
    "StopAtFirstCollision", false);
if nargin == 0
    isOccupied = defaultOptions;
    collisionDetails = struct();
    return;
end
if nargin < 4 || isempty(optionOverrides)
    optionOverrides = struct();
end
if ~isstruct(optionOverrides) || ~isscalar(optionOverrides)
    error("queryAzElTimedPathCollision:InvalidOptions", ...
        "optionOverrides must be a scalar struct.");
end
[resolvedOptions, unknownOptionFields] = ...
    azElInternal.resolveOptions(defaultOptions, optionOverrides);
if ~isempty(unknownOptionFields)
    warning("queryAzElTimedPathCollision:UnknownOptions", ...
        "Ignoring unknown option fields: %s. No behavior changed.", ...
        strjoin(unknownOptionFields, ", "));
end
validateattributes(resolvedOptions.TimePaddingSamples, {'numeric'}, ...
    {'scalar','integer','nonnegative'});
resolvedOptions.BoundaryIsOccupied = ...
    azElInternal.normalizeLogicalScalar( ...
    resolvedOptions.BoundaryIsOccupied, "BoundaryIsOccupied", ...
    "queryAzElTimedPathCollision:InvalidBoundaryPolicy");
resolvedOptions.StopAtFirstCollision = ...
    azElInternal.normalizeLogicalScalar( ...
    resolvedOptions.StopAtFirstCollision, "StopAtFirstCollision", ...
    "queryAzElTimedPathCollision:InvalidEarlyExitPolicy");

validateattributes(position_deg, {'numeric'}, ...
    {'real','finite','2d','ncols',2,'nonempty'});
position_deg = double(position_deg);
pathPointCount = size(position_deg, 1);
validateattributes(time_s, {'numeric'}, {'real','finite','nonempty'});
time_s = double(time_s(:));
if isscalar(time_s)
    time_s = repmat(time_s, pathPointCount, 1);
elseif numel(time_s) ~= pathPointCount
    error("queryAzElTimedPathCollision:TimeSizeMismatch", ...
        "time_s must be scalar or have %d values for position_deg.", ...
        pathPointCount);
end
if any(diff(time_s) < 0)
    error("queryAzElTimedPathCollision:TimeNotNondecreasing", ...
        "time_s must be nondecreasing along position_deg.");
end
isPackedInput = isstruct(obstacleField) && isscalar(obstacleField) && ...
    isfield(obstacleField, "Format") && any( ...
    string(obstacleField.Format) == [ ...
    "AzElTimeObstacleField", "AzElTimeObstacleWorkspace"]);
if ~isPackedInput
    obstacleField = buildAzElTimeObstacleField(obstacleField);
end

%% Section 2: Check Samples & Continuous Connecting Segments

pointOptions = struct( ...
    "CollisionMode", "polygon", ...
    "TimePaddingSamples", resolvedOptions.TimePaddingSamples, ...
    "BoundaryIsOccupied", resolvedOptions.BoundaryIsOccupied);
[sampleOccupied, sampleBlockingObstacleIndex] = ...
    queryAzElTimeObstacle(obstacleField, position_deg(:, 1), ...
    position_deg(:, 2), time_s, pointOptions);
sampleOccupied = logical(sampleOccupied(:));
sampleBlockingObstacleIndex = uint32( ...
    sampleBlockingObstacleIndex(:));
segmentOccupied = false(max(0, pathPointCount - 1), 1);
segmentBlockingObstacleIndex = zeros( ...
    size(segmentOccupied), "uint32");
segmentBlockingSliceIndex = zeros( ...
    size(segmentOccupied), "uint32");
segmentCount = numel(segmentOccupied);
evaluatedSegmentCount = 0;
stoppedAtFirstCollision = false;
evaluatedObstacleSegmentPairCount = 0;
candidateObstacleSegmentPairCount = 0;
broadPhaseRejectedObstacleSegmentPairCount = 0;

packedObstacles = obstacleField.Obstacles;
isSameTimePath = pathPointCount > 1 && all(time_s == time_s(1));
if isSameTimePath
    for obstacleIndex = 1:numel(packedObstacles)
        packedObstacle = packedObstacles(obstacleIndex);
        [obstacleSegmentOccupied, ~, obstacleBlockingSliceIndex] = ...
            azElInternal.queryPackedMovingObstacle( ...
            packedObstacle, time_s(1), position_deg, ...
            resolvedOptions.BoundaryIsOccupied, ...
            resolvedOptions.TimePaddingSamples);
        evaluatedObstacleSegmentPairCount = ...
            evaluatedObstacleSegmentPairCount + segmentCount;
        newlyBlocked = obstacleSegmentOccupied & ~segmentOccupied;
        segmentOccupied = segmentOccupied | obstacleSegmentOccupied;
        segmentBlockingObstacleIndex(newlyBlocked) = uint32(obstacleIndex);
        segmentBlockingSliceIndex(newlyBlocked) = uint32( ...
            obstacleBlockingSliceIndex(newlyBlocked));
    end
    evaluatedSegmentCount = segmentCount;
    candidateObstacleSegmentPairCount = ...
        numel(packedObstacles) * segmentCount;
else
    obstacleCount = numel(packedObstacles);
    obstacleIsActive = false(obstacleCount, 1);
    obstacleBounds_deg = zeros(obstacleCount, 4);
    for obstacleIndex = 1:obstacleCount
        [obstacleBounds_deg(obstacleIndex, :), ...
            obstacleIsActive(obstacleIndex)] = ...
            conservativeObstacleBoundsOverTimeWindow( ...
            packedObstacles(obstacleIndex), time_s(1), time_s(end), ...
            resolvedOptions.TimePaddingSamples);
    end
    finiteObstacleBounds_deg = obstacleBounds_deg(obstacleIsActive, :);
    coordinateScale_deg = max(1, max(abs([ ...
        position_deg(:); finiteObstacleBounds_deg(:)])));
    boundsTolerance_deg = 100 * eps(coordinateScale_deg);
    segmentEvaluationLimit = segmentCount;
    firstOccupiedSampleIndex = find(sampleOccupied, 1, "first");
    if resolvedOptions.StopAtFirstCollision && ...
            ~isempty(firstOccupiedSampleIndex)
        % Only inbound segments preceding the earliest occupied sample can
        % contain an earlier collision. Later segments cannot change the
        % first-collision result needed for candidate rejection.
        segmentEvaluationLimit = max(0, firstOccupiedSampleIndex - 1);
    end

    for segmentIndex = 1:segmentEvaluationLimit
        evaluatedSegmentCount = segmentIndex;
        segmentStartTime_s = time_s(segmentIndex);
        segmentEndTime_s = time_s(segmentIndex + 1);
        segmentStart_deg = position_deg(segmentIndex, :);
        segmentEnd_deg = position_deg(segmentIndex + 1, :);
        segmentBounds_deg = [ ...
            min(segmentStart_deg(1), segmentEnd_deg(1)), ...
            max(segmentStart_deg(1), segmentEnd_deg(1)), ...
            min(segmentStart_deg(2), segmentEnd_deg(2)), ...
            max(segmentStart_deg(2), segmentEnd_deg(2))];
        candidateObstacle = obstacleIsActive & ...
            obstacleBounds_deg(:, 2) >= ...
            segmentBounds_deg(1) - boundsTolerance_deg & ...
            obstacleBounds_deg(:, 1) <= ...
            segmentBounds_deg(2) + boundsTolerance_deg & ...
            obstacleBounds_deg(:, 4) >= ...
            segmentBounds_deg(3) - boundsTolerance_deg & ...
            obstacleBounds_deg(:, 3) <= ...
            segmentBounds_deg(4) + boundsTolerance_deg;
        candidateObstacleIndex = find(candidateObstacle);
        candidateObstacleSegmentPairCount = ...
            candidateObstacleSegmentPairCount + ...
            numel(candidateObstacleIndex);
        broadPhaseRejectedObstacleSegmentPairCount = ...
            broadPhaseRejectedObstacleSegmentPairCount + ...
            nnz(obstacleIsActive) - numel(candidateObstacleIndex);
        for obstacleIndex = reshape(candidateObstacleIndex, 1, [])
            packedObstacle = packedObstacles(obstacleIndex);
            evaluatedObstacleSegmentPairCount = ...
                evaluatedObstacleSegmentPairCount + 1;
            [segmentIsOccupied, ~, blockingSliceIndex] = ...
                azElInternal.queryPackedMovingObstacle( ...
                packedObstacle, [segmentStartTime_s; segmentEndTime_s], ...
                [segmentStart_deg; segmentEnd_deg], ...
                resolvedOptions.BoundaryIsOccupied, ...
                resolvedOptions.TimePaddingSamples);
            if segmentIsOccupied
                segmentOccupied(segmentIndex) = true;
                segmentBlockingObstacleIndex(segmentIndex) = ...
                    uint32(obstacleIndex);
                segmentBlockingSliceIndex(segmentIndex) = ...
                    uint32(blockingSliceIndex);
                break;
            end
        end
        if segmentOccupied(segmentIndex) && ...
                resolvedOptions.StopAtFirstCollision
            break;
        end
    end

    stoppedAtFirstCollision = ...
        resolvedOptions.StopAtFirstCollision && ...
        evaluatedSegmentCount < segmentCount && ...
        (~isempty(firstOccupiedSampleIndex) || ...
        any(segmentOccupied(1:evaluatedSegmentCount)));
end
segmentEvaluationComplete = evaluatedSegmentCount == segmentCount;

%% Section 3: Assemble Stable Diagnostics

isOccupied = sampleOccupied;
if pathPointCount > 1
    isOccupied(2:end) = isOccupied(2:end) | segmentOccupied;
end
blockingObstacleIndex = sampleBlockingObstacleIndex;
blockingSliceIndex = zeros(pathPointCount, 1, "uint32");
for pathPointIndex = 2:pathPointCount
    inboundSegmentIndex = pathPointIndex - 1;
    if ~sampleOccupied(pathPointIndex) && ...
            segmentOccupied(inboundSegmentIndex)
        blockingObstacleIndex(pathPointIndex) = ...
            segmentBlockingObstacleIndex(inboundSegmentIndex);
        blockingSliceIndex(pathPointIndex) = ...
            segmentBlockingSliceIndex(inboundSegmentIndex);
    end
end
collisionDetails = struct( ...
    "SampleOccupied", sampleOccupied, ...
    "SegmentOccupied", segmentOccupied, ...
    "BlockingObstacleIndex", blockingObstacleIndex, ...
    "BlockingSliceIndex", blockingSliceIndex, ...
    "SegmentBlockingObstacleIndex", segmentBlockingObstacleIndex, ...
    "SegmentBlockingSliceIndex", segmentBlockingSliceIndex, ...
    "EvaluatedSegmentCount", evaluatedSegmentCount, ...
    "EvaluatedObstacleSegmentPairCount", ...
    evaluatedObstacleSegmentPairCount, ...
    "CandidateObstacleSegmentPairCount", ...
    candidateObstacleSegmentPairCount, ...
    "BroadPhaseRejectedObstacleSegmentPairCount", ...
    broadPhaseRejectedObstacleSegmentPairCount, ...
    "SegmentEvaluationComplete", segmentEvaluationComplete, ...
    "StoppedAtFirstCollision", stoppedAtFirstCollision, ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "Options", resolvedOptions);
end

%% Section 4: Local Functions

function [bounds_deg, isActive] = ...
        conservativeObstacleBoundsOverTimeWindow( ...
        packedObstacle, firstTime_s, finalTime_s, timePaddingSamples)
% PURPOSE
%   - Bound all linearly interpolated obstacle geometry over one time window.
obstacleTime_s = double(packedObstacle.TimeSeconds(:));
isActive = ~isempty(obstacleTime_s) && ...
    finalTime_s >= obstacleTime_s(1) && ...
    firstTime_s <= obstacleTime_s(end);
bounds_deg = [Inf -Inf Inf -Inf];
if ~isActive
    return;
end
overlapStart_s = max(firstTime_s, obstacleTime_s(1));
overlapEnd_s = min(finalTime_s, obstacleTime_s(end));
firstSliceIndex = find( ...
    obstacleTime_s <= overlapStart_s, 1, "last");
lastSliceIndex = find( ...
    obstacleTime_s >= overlapEnd_s, 1, "first");
firstSliceIndex = max(1, firstSliceIndex - timePaddingSamples);
lastSliceIndex = min( ...
    numel(obstacleTime_s), lastSliceIndex + timePaddingSamples);
sliceBounds_deg = double(packedObstacle.BoundsDeg( ...
    firstSliceIndex:lastSliceIndex, :));
hasFiniteBounds = all(isfinite(sliceBounds_deg), 2);
if ~any(hasFiniteBounds)
    % Unknown bounds must retain every exact segment query.
    bounds_deg = [-Inf Inf -Inf Inf];
    return;
end
sliceBounds_deg = sliceBounds_deg(hasFiniteBounds, :);
bounds_deg = [min(sliceBounds_deg(:, 1)), ...
    max(sliceBounds_deg(:, 2)), ...
    min(sliceBounds_deg(:, 3)), ...
    max(sliceBounds_deg(:, 4))];
end
