function training = trainAzElRpRetimer(optionOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   defaults = trainAzElRpRetimer()
%   training = trainAzElRpRetimer(optionOverrides)
%**************************************************************************
% PURPOSE
%   - Train and save a reproducible deterministic RP corner-radius proposer.
%   - Record that deterministic search and certificates, not the policy,
%     control every production selection and acceptance decision.
%**************************************************************************
% INPUTS
%   - optionOverrides (scalar struct, optional; default struct())
%       MaximumEpisodes (5000), RandomSeed (41), TrainingCaseCount (384),
%       ValidationCaseCount (128), MinimumRelativeImprovement (0.05),
%       ModelFile, Verbose (true), and ShowTrainingPlot (false).
%**************************************************************************
% OUTPUTS
%   - training (scalar struct)
%       Agent, statistics, production-label validation, promotion status,
%       metadata, model path, resolved options, and policy specifications.
%       A policy that fails promotion is returned but does not replace the
%       saved model. Invalid options throw.
%**************************************************************************
% UNITS
%   - Policy observations, actions, scores, and rewards are dimensionless.
%**************************************************************************

%% Section 1: Resolve Reproducible Training Controls

repositoryRoot = fileparts(mfilename("fullpath"));
defaults = struct( ...
    "MaximumEpisodes", 5000, ...
    "RandomSeed", 41, ...
    "TrainingCaseCount", 384, ...
    "ValidationCaseCount", 128, ...
    "MinimumRelativeImprovement", 0.05, ...
    "ModelFile", fullfile(repositoryRoot, "models", ...
        "azElRpRetimerAgent.mat"), ...
    "Verbose", true, ...
    "ShowTrainingPlot", false);
if nargin == 0
    training = defaults;
    return;
end
if isempty(optionOverrides)
    optionOverrides = struct();
end
if ~isstruct(optionOverrides) || ~isscalar(optionOverrides)
    error("trainAzElRpRetimer:InvalidOptions", ...
        "optionOverrides must be a scalar struct.");
end
[options, unknown] = azElInternal.resolveOptions(defaults, optionOverrides);
if ~isempty(unknown)
    warning("trainAzElRpRetimer:UnknownOptions", ...
        "Ignoring unknown option fields: %s. No behavior changed.", ...
        strjoin(unknown, ", "));
end
validateattributes(options.MaximumEpisodes, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'positive'});
validateattributes(options.RandomSeed, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'nonnegative'});
validateattributes(options.TrainingCaseCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'positive'});
validateattributes(options.ValidationCaseCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'positive'});
validateattributes(options.MinimumRelativeImprovement, {'numeric'}, ...
    {'real', 'finite', 'scalar', '>=', 0, '<', 1});
options.ModelFile = string(options.ModelFile);
if ~isscalar(options.ModelFile) || strlength(options.ModelFile) == 0
    error("trainAzElRpRetimer:InvalidModelFile", ...
        "ModelFile must be nonempty scalar text.");
end
options.Verbose = azElInternal.normalizeLogicalScalar( ...
    options.Verbose, "Verbose", ...
    "trainAzElRpRetimer:InvalidVerbose");
options.ShowTrainingPlot = azElInternal.normalizeLogicalScalar( ...
    options.ShowTrainingPlot, "ShowTrainingPlot", ...
    "trainAzElRpRetimer:InvalidShowTrainingPlot");

%% Section 2: Create Production Labels & Train The Continuous Policy

rng(options.RandomSeed, "twister");
validationSeed = options.RandomSeed + 104729;
trainingData = azElInternal.createRpRetimerTrainingData( ...
    options.TrainingCaseCount, options.RandomSeed);
validationData = azElInternal.createRpRetimerTrainingData( ...
    options.ValidationCaseCount, validationSeed);
environment = createAzElRpRetimerEnvironment( ...
    options.RandomSeed, trainingData);
initializationOptions = rlAgentInitializationOptions( ...
    "NumHiddenUnit", 64, "Normalization", "none");
% The DDPG policy algorithm is identified in citation.md.
agentOptions = rlDDPGAgentOptions( ...
    "SampleTime", 1, ...
    "DiscountFactor", 0.95, ...
    "ExperienceBufferLength", 50000, ...
    "MiniBatchSize", 128, ...
    "NumWarmStartSteps", 256, ...
    "TargetSmoothFactor", 5e-3);
agent = rlDDPGAgent( ...
    getObservationInfo(environment), getActionInfo(environment), ...
    initializationOptions, agentOptions);
plotMode = "none";
if options.ShowTrainingPlot
    plotMode = "training-progress";
end
trainingOptions = rlTrainingOptions( ...
    "MaxEpisodes", options.MaximumEpisodes, ...
    "MaxStepsPerEpisode", 1, ...
    "ScoreAveragingWindowLength", 200, ...
    "StopTrainingCriteria", "EpisodeCount", ...
    "StopTrainingValue", options.MaximumEpisodes, ...
    "Verbose", options.Verbose, ...
    "Plots", plotMode, ...
    "UseParallel", false);
trainingStatistics = train(agent, environment, trainingOptions);
agent.UseExplorationPolicy = false;

%% Section 3: Validate The Policy & Control Model Promotion

validation = evaluatePolicy(agent, validationData);
fixedBaselineError = validation.BestFixedMeanAbsoluteError;
requiredError = (1 - options.MinimumRelativeImprovement) * ...
    fixedBaselineError;
existingPolicyError = evaluateExistingPolicy( ...
    options.ModelFile, validationData);
passesFixedBaseline = validation.MeanAbsoluteError <= requiredError;
passesExistingPolicy = ~isfinite(existingPolicyError) || ...
    validation.MeanAbsoluteError < existingPolicyError;
promoted = passesFixedBaseline && passesExistingPolicy;
validation.RequiredMeanAbsoluteError = requiredError;
validation.ExistingPolicyMeanAbsoluteError = existingPolicyError;
validation.PassesFixedBaseline = passesFixedBaseline;
validation.PassesExistingPolicy = passesExistingPolicy;
validation.Promoted = promoted;

%% Section 4: Save A Policy That Passes The Production Gate

modelDirectory = fileparts(options.ModelFile);
if promoted && strlength(modelDirectory) > 0 && ~isfolder(modelDirectory)
    mkdir(modelDirectory);
end
metadata = struct( ...
    "Format", "AzElRpRetimerAgent", ...
    "Version", 2, ...
    "Algorithm", "DDPG contextual radius proposer", ...
    "RandomSeed", options.RandomSeed, ...
    "MaximumEpisodes", options.MaximumEpisodes, ...
    "TrainingCaseCount", options.TrainingCaseCount, ...
    "ValidationCaseCount", options.ValidationCaseCount, ...
    "ValidationSeed", validationSeed, ...
    "TrainingTarget", trainingData.TargetSource, ...
    "ValidationMeanAbsoluteError", validation.MeanAbsoluteError, ...
    "BestFixedMeanAbsoluteError", fixedBaselineError, ...
    "ExistingPolicyMeanAbsoluteError", existingPolicyError, ...
    "MinimumRelativeImprovement", ...
        options.MinimumRelativeImprovement, ...
    "Promoted", promoted, ...
    "ObservationCount", 10, ...
    "ActionRange", [-1 1], ...
    "RadiusFractionRange", [0 1], ...
    "PolicyAuthority", "proposalOnly", ...
    "SelectionAuthority", ...
        "deterministic search plus kinematic and collision certificates", ...
    "ObstacleInputsUsedForTraining", false, ...
    "MATLABRelease", string(version("-release")), ...
    "Created", datetime("now", "TimeZone", "UTC"));
modelFile = char(options.ModelFile);
if promoted
    save(modelFile, "agent", "trainingStatistics", "metadata", "-v7.3");
else
    warning("trainAzElRpRetimer:PolicyNotPromoted", ...
        "The trained policy was not saved. Its mean absolute radius " + ...
        "error was %.6f. The required error was %.6f, and the existing " + ...
        "policy error was %.6f.", validation.MeanAbsoluteError, ...
        requiredError, existingPolicyError);
end
training = struct( ...
    "Agent", agent, ...
    "TrainingStatistics", trainingStatistics, ...
    "Validation", validation, ...
    "Promoted", promoted, ...
    "Metadata", metadata, ...
    "ModelFile", options.ModelFile, ...
    "Options", options, ...
    "ObservationInfo", getObservationInfo(environment), ...
    "ActionInfo", getActionInfo(environment));
end

%% Section 5: Local Functions

function validation = evaluatePolicy(agent, validationData)
% Measure policy radius error on production-retimer labels.
prediction = predictRadiusFraction(agent, validationData.Observation);
target = validationData.BestRadiusFraction;
absoluteError = abs(prediction - target);
fixedFraction = [0 0.5 1];
fixedMeanAbsoluteError = zeros(size(fixedFraction));
for fractionIndex = 1:numel(fixedFraction)
    fixedMeanAbsoluteError(fractionIndex) = mean( ...
        abs(fixedFraction(fractionIndex) - target));
end
validation = struct( ...
    "TargetSource", validationData.TargetSource, ...
    "Seed", validationData.Seed, ...
    "CaseCount", validationData.CaseCount, ...
    "Prediction", prediction, ...
    "Target", target, ...
    "MeanAbsoluteError", mean(absoluteError), ...
    "MedianAbsoluteError", median(absoluteError), ...
    "MaximumAbsoluteError", max(absoluteError), ...
    "FixedFraction", fixedFraction, ...
    "FixedMeanAbsoluteError", fixedMeanAbsoluteError, ...
    "BestFixedMeanAbsoluteError", min(fixedMeanAbsoluteError));
end

function meanAbsoluteError = evaluateExistingPolicy( ...
        modelFile, validationData)
% Compare the proposed model with the currently saved compatible policy.
meanAbsoluteError = NaN;
if ~isfile(modelFile)
    return;
end
try
    saved = load(modelFile, "agent", "metadata");
    if ~isfield(saved, "agent") || ~isfield(saved, "metadata") || ...
            string(saved.metadata.Format) ~= "AzElRpRetimerAgent"
        return;
    end
    saved.agent.UseExplorationPolicy = false;
    prediction = predictRadiusFraction( ...
        saved.agent, validationData.Observation);
    meanAbsoluteError = mean(abs( ...
        prediction - validationData.BestRadiusFraction));
catch
    meanAbsoluteError = NaN;
end
end

function radiusFraction = predictRadiusFraction(agent, observation)
% Evaluate deterministic actions and convert them to radius fractions.
caseCount = size(observation, 2);
radiusFraction = zeros(1, caseCount);
for caseIndex = 1:caseCount
    action = getAction(agent, {observation(:, caseIndex)});
    if iscell(action)
        action = action{1};
    end
    radiusFraction(caseIndex) = 0.5 * ...
        (min(1, max(-1, double(action))) + 1);
end
end
