function validation = validateAzElExampleResult( ...
        result, scenarioName, requirements)
%% Section 0: Header & Readme
% SYNTAX
%   validation = validateAzElExampleResult(result)
%   validation = validateAzElExampleResult(result, scenarioName)
%   validation = validateAzElExampleResult( ...
%       result, scenarioName, requirements)
%**************************************************************************
% PURPOSE
%   - Independently validate the timed trajectory returned by the public
%     planner without rerunning planning or trusting planner Success alone.
%**************************************************************************
% INPUTS
%   - result (scalar planner-result struct)
%       Must expose obstacleField, states, limits, options, and trajectory.
%   - scenarioName (scalar text, optional; default "az/el example")
%       Human-readable context used in the validation message.
%   - requirements (scalar struct, optional; default struct())
%       .RequireDirectBlocked is logical (default false).
%       .PositionTolerance_deg is nonnegative (default 1e-7).
%       .TimeTolerance_s is nonnegative (default 1e-8).
%       .KinematicTolerance is nonnegative (default 1e-7).
%**************************************************************************
% OUTPUTS
%   - validation (scalar struct)
%       Independent checks, observed peaks, collision mask, issues, Passed,
%       and Message. A normal planning failure returns Passed=false.
%**************************************************************************
% UNITS
%   - Position is degrees, time is seconds, velocity is degrees per second,
%     acceleration is degrees per second squared, and jerk is degrees per
%     second cubed.
%**************************************************************************

%% Section 1: Validate Inputs & Apply Defaults

if nargin < 2 || isempty(scenarioName)
    scenarioName = "az/el example";
end
if nargin < 3 || isempty(requirements)
    requirements = struct();
end
if ~isstruct(result) || ~isscalar(result) || ...
        ~isstruct(requirements) || ~isscalar(requirements)
    error("validateAzElExampleResult:InvalidInput", ...
        "result and requirements must be scalar structs.");
end
scenarioName = string(scenarioName);
if ~isscalar(scenarioName)
    error("validateAzElExampleResult:InvalidScenarioName", ...
        "scenarioName must be scalar text.");
end
requireDirectBlocked = logical(requirementValue( ...
    requirements, "RequireDirectBlocked", false));
positionTolerance_deg = requirementValue( ...
    requirements, "PositionTolerance_deg", 1e-7);
timeTolerance_s = requirementValue( ...
    requirements, "TimeTolerance_s", 1e-8);
kinematicTolerance = requirementValue( ...
    requirements, "KinematicTolerance", 1e-7);
validateattributes(positionTolerance_deg, {'numeric'}, ...
    {'real','finite','scalar','nonnegative'});
validateattributes(timeTolerance_s, {'numeric'}, ...
    {'real','finite','scalar','nonnegative'});
validateattributes(kinematicTolerance, {'numeric'}, ...
    {'real','finite','scalar','nonnegative'});

requiredFields = ["Success" "Message" "obstacleField" ...
    "initialState" "goalState" "limits" "Options" ...
    "timedSlopePath" "directBlocked"];
missingFields = requiredFields(~isfield(result, requiredFields));
if ~isempty(missingFields)
    error("validateAzElExampleResult:MissingResultFields", ...
        "result is missing required fields: %s.", ...
        strjoin(missingFields, ", "));
end

%% Section 2: Validate Timed State History

timedPath = result.timedSlopePath;
hasTrajectory = isstruct(timedPath) && isscalar(timedPath) && ...
    isfield(timedPath, "time_s") && ...
    isfield(timedPath, "position_deg") && ...
    ~isempty(timedPath.time_s) && ...
    size(timedPath.position_deg, 1) == numel(timedPath.time_s);
timeIsFinite = false;
timeIsNondecreasing = false;
timeIsStrictlyIncreasing = false;
initialStateMatched = false;
terminalStateMatched = false;
goalTimeSatisfied = false;
collisionMask = false(0, 1);
collisionFree = false;
peakVelocity_deg_s = [NaN NaN];
peakAcceleration_deg_s2 = [NaN NaN];
peakJerk_deg_s3 = [NaN NaN];
velocityWithinLimits = false;
accelerationWithinLimits = false;
jerkWithinLimits = false;
azimuthWrapPolicySatisfied = false;
if hasTrajectory
    time_s = double(timedPath.time_s(:));
    position_deg = double(timedPath.position_deg);
    timeIsFinite = all(isfinite(time_s));
    timeIsNondecreasing = timeIsFinite && all(diff(time_s) >= 0);
    timeIsStrictlyIncreasing = timeIsFinite && all(diff(time_s) > 0);
    initialStateMatched = ...
        abs(time_s(1) - result.initialState.time_s) <= timeTolerance_s && ...
        norm(position_deg(1, :) - ...
        result.initialState.position_deg) <= positionTolerance_deg;
    terminalStateMatched = norm(position_deg(end, :) - ...
        result.goalState.position_deg) <= positionTolerance_deg;
    if isfield(timedPath, "velocity_deg_s")
        initialStateMatched = initialStateMatched && norm( ...
            timedPath.velocity_deg_s(1, :) - ...
            result.initialState.velocity_deg_s) <= kinematicTolerance;
        terminalStateMatched = terminalStateMatched && norm( ...
            timedPath.velocity_deg_s(end, :) - ...
            result.goalState.velocity_deg_s) <= kinematicTolerance;
    else
        initialStateMatched = false;
        terminalStateMatched = false;
    end
    if isfield(timedPath, "acceleration_deg_s2")
        initialStateMatched = initialStateMatched && norm( ...
            timedPath.acceleration_deg_s2(1, :) - ...
            result.initialState.acceleration_deg_s2) <= ...
            kinematicTolerance;
        terminalStateMatched = terminalStateMatched && norm( ...
            timedPath.acceleration_deg_s2(end, :) - ...
            result.goalState.acceleration_deg_s2) <= ...
            kinematicTolerance;
    else
        initialStateMatched = false;
        terminalStateMatched = false;
    end
    if result.Options.GoalTimeMode == "fixedArrival"
        goalTimeSatisfied = abs(time_s(end) - ...
            result.goalState.time_s) <= timeTolerance_s;
    else
        goalTimeSatisfied = time_s(end) <= ...
            result.goalState.time_s + timeTolerance_s;
    end

    collisionTimePaddingSamples = 1;
    if isfield(result.Options, "CollisionTimePaddingSamples")
        collisionTimePaddingSamples = ...
            result.Options.CollisionTimePaddingSamples;
    end
    collisionMask = queryAzElTimedPathCollision( ...
        result.obstacleField, time_s, position_deg, struct( ...
        "TimePaddingSamples", collisionTimePaddingSamples, ...
        "BoundaryIsOccupied", false));
    collisionFree = ~any(collisionMask);
    [peakVelocity_deg_s, velocityWithinLimits] = checkKinematicHistory( ...
        timedPath, "velocity_deg_s", result.limits, ...
        "maxVelocity_deg_s", kinematicTolerance);
    [peakAcceleration_deg_s2, accelerationWithinLimits] = ...
        checkKinematicHistory(timedPath, "acceleration_deg_s2", ...
        result.limits, "maxAcceleration_deg_s2", kinematicTolerance);
    [peakJerk_deg_s3, jerkWithinLimits] = checkKinematicHistory( ...
        timedPath, "jerk_deg_s3", result.limits, ...
        "maxJerk_deg_s3", kinematicTolerance);

    if result.Options.AllowAzimuthWrapping
        azimuthWrapPolicySatisfied = true;
    else
        azimuthInterval_deg = double(result.Options.AzimuthInterval_deg);
        azimuthWrapPolicySatisfied = all( ...
            position_deg(:, 1) >= azimuthInterval_deg(1) - ...
            positionTolerance_deg & ...
            position_deg(:, 1) <= azimuthInterval_deg(2) + ...
            positionTolerance_deg);
    end
end

%% Section 3: Validate Scenario And Safety Metadata

directRouteRequirementSatisfied = ~requireDirectBlocked || ...
    any(result.directBlocked);
safetyMarginPolicySatisfied = ...
    isfield(result, "originalAzElData") && ...
    isfield(result, "azElData") && ...
    isfield(result, "obstacleSafetyMargins_deg") && ...
    all(isfinite(result.obstacleSafetyMargins_deg)) && ...
    all(result.obstacleSafetyMargins_deg >= 0);
plannerReportedSuccess = logical(result.Success);
checks = [ ...
    plannerReportedSuccess, hasTrajectory, timeIsFinite, ...
    timeIsStrictlyIncreasing, initialStateMatched, terminalStateMatched, ...
    goalTimeSatisfied, collisionFree, velocityWithinLimits, ...
    accelerationWithinLimits, jerkWithinLimits, ...
    azimuthWrapPolicySatisfied, directRouteRequirementSatisfied, ...
    safetyMarginPolicySatisfied];
checkNames = [ ...
    "plannerReportedSuccess" "hasTrajectory" "timeIsFinite" ...
    "timeIsStrictlyIncreasing" "initialStateMatched" ...
    "terminalStateMatched" "goalTimeSatisfied" "collisionFree" ...
    "velocityWithinLimits" "accelerationWithinLimits" ...
    "jerkWithinLimits" "azimuthWrapPolicySatisfied" ...
    "directRouteRequirementSatisfied" "safetyMarginPolicySatisfied"];
issues = checkNames(~checks);
passed = all(checks);
message = scenarioName + " passed independent example validation.";
if ~passed
    message = scenarioName + " failed independent checks: " + ...
        strjoin(issues, ", ") + ". " + string(result.Message);
end

%% Section 4: Assemble Stable Validation Output

validation = struct( ...
    "Passed", passed, ...
    "Message", message, ...
    "PlannerReportedSuccess", plannerReportedSuccess, ...
    "HasTrajectory", hasTrajectory, ...
    "TimeIsFinite", timeIsFinite, ...
    "TimeIsNondecreasing", timeIsNondecreasing, ...
    "TimeIsStrictlyIncreasing", timeIsStrictlyIncreasing, ...
    "InitialStateMatched", initialStateMatched, ...
    "TerminalStateMatched", terminalStateMatched, ...
    "GoalTimeSatisfied", goalTimeSatisfied, ...
    "CollisionFree", collisionFree, ...
    "VelocityWithinLimits", velocityWithinLimits, ...
    "AccelerationWithinLimits", accelerationWithinLimits, ...
    "JerkWithinLimits", jerkWithinLimits, ...
    "AzimuthWrapPolicySatisfied", azimuthWrapPolicySatisfied, ...
    "DirectRouteRequirementSatisfied", ...
    directRouteRequirementSatisfied, ...
    "SafetyMarginPolicySatisfied", safetyMarginPolicySatisfied, ...
    "PeakVelocity_deg_s", peakVelocity_deg_s, ...
    "PeakAcceleration_deg_s2", peakAcceleration_deg_s2, ...
    "PeakJerk_deg_s3", peakJerk_deg_s3, ...
    "CollisionMask", logical(collisionMask(:)), ...
    "Issues", issues);
end

%% Section 5: Local Functions

function value = requirementValue(requirements, fieldName, defaultValue)
%% Section 0: Header & Readme
% SYNTAX
%   value = requirementValue(requirements, fieldName, defaultValue)
%**************************************************************************
% PURPOSE
%   - Resolve one optional independent-validation requirement.
%**************************************************************************
% INPUTS
%   - requirements (scalar struct)
%   - fieldName (scalar text)
%   - defaultValue (value of any supported requirement type)
%**************************************************************************
% OUTPUTS
%   - value (resolved requirement value)
%**************************************************************************
% UNITS
%   - Units are inherited from the named requirement.
%**************************************************************************
value = defaultValue;
if isfield(requirements, fieldName) && ...
        ~isempty(requirements.(fieldName))
    value = requirements.(fieldName);
end
end

function [peakValue, withinLimits] = checkKinematicHistory( ...
        timedPath, historyField, limits, limitField, tolerance)
%% Section 0: Header & Readme
% SYNTAX
%   [peakValue, withinLimits] = checkKinematicHistory( ...
%       timedPath, historyField, limits, limitField, tolerance)
%**************************************************************************
% PURPOSE
%   - Independently compare one two-axis history with its limits.
%**************************************************************************
% INPUTS
%   - timedPath (scalar timed-path struct)
%   - historyField, limitField (scalar text)
%   - limits (scalar planner-limit struct)
%   - tolerance (nonnegative numeric scalar)
%**************************************************************************
% OUTPUTS
%   - peakValue (1-by-2 numeric row)
%   - withinLimits (logical scalar)
%**************************************************************************
% UNITS
%   - Units are inherited from historyField and limitField.
%**************************************************************************
limit = [Inf Inf];
if isfield(limits, limitField) && ~isempty(limits.(limitField))
    limit = reshape(double(limits.(limitField)), 1, []);
    if isscalar(limit)
        limit = repmat(limit, 1, 2);
    end
end
if ~isfield(timedPath, historyField) || ...
        isempty(timedPath.(historyField))
    peakValue = [NaN NaN];
    withinLimits = all(~isfinite(limit));
    return;
end
history = double(timedPath.(historyField));
peakValue = max(abs(history), [], 1);
finiteLimitAxis = isfinite(limit);
if ~any(finiteLimitAxis)
    withinLimits = true;
else
    withinLimits = size(history, 2) == 2 && ...
        all(isfinite(history(:, finiteLimitAxis)), "all") && ...
        all(peakValue(finiteLimitAxis) <= ...
        limit(finiteLimitAxis) + tolerance);
end
end
