function validation = validateAzElTrajectory(trajectory, obstacles, ...
        initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   validation = validateAzElTrajectory(result)
%   validation = validateAzElTrajectory( ...
%       trajectory, obstacles, initialState, goalState, limits, options)
%**************************************************************************
% PURPOSE
%   - Independently validate one complete HS3 motion and protected geometry.
%   - Fail unresolved continuous-collision intervals instead of accepting them.
%**************************************************************************
% INPUTS
%   - trajectory (scalar candidate or planner-result struct)
%       Must contain sampled histories and Polynomial segment coefficients.
%   - obstacles (canonical protected obstacle array, optional with result)
%   - initialState, goalState (normalized state structs, optional with result)
%   - limits (normalized physical limits struct, optional with result)
%   - options (resolved planner options, optional with result)
%**************************************************************************
% OUTPUTS
%   - validation (scalar struct)
%       Stable independent pass/fail checks, extrema, clearance, and message.
%**************************************************************************
% UNITS
%   - Position and clearance are degrees. Derivatives use deg/s, deg/s^2,
%     and deg/s^3. Time is seconds.
%**************************************************************************

%% Section 1: Resolve Inputs And Basic History Checks

if nargin == 1
    requiredResultFields = {'Inputs', 'Options', 'Polynomial'};
    if ~isstruct(trajectory) || ~isscalar(trajectory) || ...
            ~all(isfield(trajectory, requiredResultFields))
        error("validateAzElTrajectory:InvalidResult", ...
            "A one-input call requires a planner result with Inputs, " + ...
            "Options, and Polynomial fields.");
    end
    obstacles = trajectory.Inputs.obstacles;
    initialState = trajectory.Inputs.initialState;
    goalState = trajectory.Inputs.goalState;
    limits = trajectory.Inputs.limits;
    options = trajectory.Options;
elseif nargin ~= 6
    error("validateAzElTrajectory:InvalidCall", ...
        "Use one planner result or all six explicit validation inputs.");
end
obstacles = combineAzElObstacles(obstacles);
requiredFields = {'time_s', 'position_deg', 'velocity_deg_s', ...
    'acceleration_deg_s2', 'jerk_deg_s3', 'Polynomial'};
hasRequiredFields = isstruct(trajectory) && isscalar(trajectory) && ...
    all(isfield(trajectory, requiredFields));
if ~hasRequiredFields
    error("validateAzElTrajectory:InvalidTrajectory", ...
        "trajectory must contain sampled histories and Polynomial data.");
end
time_s = double(trajectory.time_s(:));
position_deg = double(trajectory.position_deg);
velocity_deg_s = double(trajectory.velocity_deg_s);
acceleration_deg_s2 = double(trajectory.acceleration_deg_s2);
jerk_deg_s3 = double(trajectory.jerk_deg_s3);
sampleCount = numel(time_s);
historySizesMatch = ...
    isequal(size(position_deg), [sampleCount 2]) && ...
    isequal(size(velocity_deg_s), [sampleCount 2]) && ...
    isequal(size(acceleration_deg_s2), [sampleCount 2]) && ...
    isequal(size(jerk_deg_s3), [sampleCount 2]);
timeIsFinite = ~isempty(time_s) && all(isfinite(time_s));
timeIsStrictlyIncreasing = timeIsFinite && all(diff(time_s) > 0);
historyIsFinite = sampleCount > 0 && historySizesMatch && ...
    all(isfinite(position_deg), "all") && ...
    all(isfinite(velocity_deg_s), "all") && ...
    all(isfinite(acceleration_deg_s2), "all") && ...
    all(isfinite(jerk_deg_s3), "all");

%% Section 2: Validate Endpoints And Continuous Polynomial Bounds

stateTolerance = max(10 * options.ConstraintTolerance, 1e-7);
initialStateMatched = historyIsFinite && ...
    max(abs(position_deg(1, :) - initialState.position_deg)) <= ...
    stateTolerance && ...
    max(abs(velocity_deg_s(1, :) - initialState.velocity_deg_s)) <= ...
    stateTolerance && ...
    max(abs(acceleration_deg_s2(1, :) - ...
    initialState.acceleration_deg_s2)) <= stateTolerance;
if timeIsFinite
    goalPosition_deg = goalPositionAtTime(goalState, time_s(end));
else
    goalPosition_deg = [NaN NaN];
end
terminalStateMatched = historyIsFinite && ...
    max(abs(position_deg(end, :) - goalPosition_deg)) <= stateTolerance && ...
    max(abs(velocity_deg_s(end, :) - goalState.velocity_deg_s)) <= ...
    stateTolerance && ...
    max(abs(acceleration_deg_s2(end, :) - ...
    goalState.acceleration_deg_s2)) <= stateTolerance;
if options.GoalTimeMode == "fixedArrival"
    goalTimeSatisfied = timeIsFinite && ...
        abs(time_s(end) - goalState.time_s) <= stateTolerance;
else
    goalTimeSatisfied = timeIsFinite && ...
        time_s(end) <= goalState.time_s + stateTolerance && ...
        time_s(end) > initialState.time_s;
end
[continuousBounds, dynamics] = validatePolynomial( ...
    trajectory.Polynomial, limits, options, stateTolerance);

%% Section 3: Certify Continuous Collision Freedom

if timeIsStrictlyIncreasing && historyIsFinite && continuousBounds.Valid
    [seedCorridorCertified, seedCorridorClearance_deg] = ...
        azElInternal.certifySeedCorridor( ...
        trajectory, obstacles, options.CollisionClearanceTolerance_deg);
    if seedCorridorCertified
        collisionFree = true;
        collisionResolved = true;
        minimumClearance_deg = seedCorridorClearance_deg;
        collisionCheckCount = 0;
        unresolvedIntervalCount = 0;
    else
        [collisionFree, collisionResolved, minimumClearance_deg, ...
            collisionCheckCount, unresolvedIntervalCount] = ...
            certifyCollision( ...
            trajectory.Polynomial, obstacles, limits, options);
    end
else
    seedCorridorCertified = false;
    collisionFree = false;
    collisionResolved = false;
    minimumClearance_deg = NaN;
    collisionCheckCount = 0;
    unresolvedIntervalCount = 0;
end
safetyMarginPolicySatisfied = true;
for obstacleIndex = 1:numel(obstacles)
    obstacle = obstacles(obstacleIndex);
    obstacleHasProvenance = isfield(obstacle, "originalAz_deg") && ...
        isfield(obstacle, "originalEl_deg") && ...
        isfinite(obstacle.safetyMargin_deg) && ...
        obstacle.safetyMargin_deg >= 0;
    safetyMarginPolicySatisfied = ...
        safetyMarginPolicySatisfied && obstacleHasProvenance;
end
azimuthWrapPolicySatisfied = options.AllowAzimuthWrapping || ...
    continuousBounds.PositionWithinLimits;

%% Section 4: Assemble The Stable Validation Record

passed = historySizesMatch && timeIsStrictlyIncreasing && ...
    historyIsFinite && initialStateMatched && terminalStateMatched && ...
    goalTimeSatisfied && continuousBounds.Valid && dynamics.Consistent && ...
    collisionFree && collisionResolved && ...
    safetyMarginPolicySatisfied && azimuthWrapPolicySatisfied;
issues = strings(0, 1);
checkNames = [ ...
    "history shape", "finite increasing time", "finite histories", ...
    "initial state", "terminal state", "goal time", ...
    "continuous limits", "HS3 dynamics", "collision freedom", ...
    "collision resolution", "safety-margin provenance", ...
    "azimuth-wrap policy"];
checkValues = [ ...
    historySizesMatch, timeIsStrictlyIncreasing, historyIsFinite, ...
    initialStateMatched, terminalStateMatched, goalTimeSatisfied, ...
    continuousBounds.Valid, dynamics.Consistent, collisionFree, ...
    collisionResolved, safetyMarginPolicySatisfied, ...
    azimuthWrapPolicySatisfied];
for checkIndex = 1:numel(checkNames)
    if ~checkValues(checkIndex)
        issues(end + 1, 1) = checkNames(checkIndex); %#ok<AGROW>
    end
end
if passed
    message = "Independent continuous validation passed.";
else
    message = "Independent validation failed: " + ...
        strjoin(issues, ", ") + ".";
end
validation = struct( ...
    "Passed", passed, ...
    "Message", message, ...
    "HistorySizesMatch", historySizesMatch, ...
    "TimeIsFinite", timeIsFinite, ...
    "TimeIsStrictlyIncreasing", timeIsStrictlyIncreasing, ...
    "HistoryIsFinite", historyIsFinite, ...
    "InitialStateMatched", initialStateMatched, ...
    "TerminalStateMatched", terminalStateMatched, ...
    "GoalTimeSatisfied", goalTimeSatisfied, ...
    "PositionWithinLimits", continuousBounds.PositionWithinLimits, ...
    "VelocityWithinLimits", continuousBounds.VelocityWithinLimits, ...
    "AccelerationWithinLimits", ...
    continuousBounds.AccelerationWithinLimits, ...
    "JerkWithinLimits", continuousBounds.JerkWithinLimits, ...
    "DynamicsConsistent", dynamics.Consistent, ...
    "MaximumDynamicsResidual", dynamics.MaximumResidual, ...
    "CollisionFree", collisionFree, ...
    "CollisionResolved", collisionResolved, ...
    "SeedCorridorCertified", seedCorridorCertified, ...
    "MinimumClearance_deg", minimumClearance_deg, ...
    "CollisionCheckCount", collisionCheckCount, ...
    "UnresolvedIntervalCount", unresolvedIntervalCount, ...
    "SafetyMarginPolicySatisfied", safetyMarginPolicySatisfied, ...
    "AzimuthWrapPolicySatisfied", azimuthWrapPolicySatisfied, ...
    "PeakVelocity_deg_s", maximumAbsolute(velocity_deg_s), ...
    "PeakAcceleration_deg_s2", maximumAbsolute(acceleration_deg_s2), ...
    "PeakJerk_deg_s3", maximumAbsolute(jerk_deg_s3), ...
    "Issues", issues);
end

%% Section 5: Local Functions

function [bounds, dynamics] = validatePolynomial( ...
        polynomial, limits, options, tolerance)
% PURPOSE
%   - Check Bernstein bounds and exact derivative relationships by segment.
requiredFields = {'SegmentCount', 'SegmentDuration_s', ...
    'positionPower_deg', 'velocityPower_deg_s', ...
    'accelerationPower_deg_s2', 'jerkPower_deg_s3'};
hasFields = isstruct(polynomial) && isscalar(polynomial) && ...
    all(isfield(polynomial, requiredFields));
positionWithinLimits = hasFields;
velocityWithinLimits = hasFields;
accelerationWithinLimits = hasFields;
jerkWithinLimits = hasFields;
if ~hasFields || polynomial.SegmentDuration_s <= 0
    bounds = boundsRecord(false, false, false, false);
    dynamics = struct("Consistent", false, "MaximumResidual", Inf);
    return;
end
maximumDynamicsResidual = 0;
positionLower_deg = [options.AzimuthInterval_deg(1), ...
    options.ElevationInterval_deg(1)];
positionUpper_deg = [options.AzimuthInterval_deg(2), ...
    options.ElevationInterval_deg(2)];
for segmentIndex = 1:polynomial.SegmentCount
    for axisIndex = 1:2
        positionPower = coefficients( ...
            polynomial.positionPower_deg, segmentIndex, axisIndex);
        velocityPower = coefficients( ...
            polynomial.velocityPower_deg_s, segmentIndex, axisIndex);
        accelerationPower = coefficients( ...
            polynomial.accelerationPower_deg_s2, segmentIndex, axisIndex);
        jerkPower = coefficients( ...
            polynomial.jerkPower_deg_s3, segmentIndex, axisIndex);
        if ~(axisIndex == 1 && options.AllowAzimuthWrapping)
            positionWithinLimits = positionWithinLimits && withinBounds( ...
                positionPower, positionLower_deg(axisIndex), ...
                positionUpper_deg(axisIndex), tolerance);
        end
        velocityWithinLimits = velocityWithinLimits && withinBounds( ...
            velocityPower, -limits.maxVelocity_deg_s(axisIndex), ...
            limits.maxVelocity_deg_s(axisIndex), tolerance);
        accelerationWithinLimits = accelerationWithinLimits && ...
            withinBounds(accelerationPower, ...
            -limits.maxAcceleration_deg_s2(axisIndex), ...
            limits.maxAcceleration_deg_s2(axisIndex), tolerance);
        jerkWithinLimits = jerkWithinLimits && withinBounds( ...
            jerkPower, -limits.maxJerk_deg_s3(axisIndex), ...
            limits.maxJerk_deg_s3(axisIndex), tolerance);
        duration_s = polynomial.SegmentDuration_s;
        positionDerivative = (1:numel(positionPower) - 1).' .* ...
            positionPower(2:end) / duration_s;
        velocityDerivative = (1:numel(velocityPower) - 1).' .* ...
            velocityPower(2:end) / duration_s;
        accelerationDerivative = ...
            (1:numel(accelerationPower) - 1).' .* ...
            accelerationPower(2:end) / duration_s;
        maximumDynamicsResidual = max(maximumDynamicsResidual, max([ ...
            abs(positionDerivative - velocityPower); ...
            abs(velocityDerivative - accelerationPower); ...
            abs(accelerationDerivative - jerkPower)]));
    end
end
bounds = boundsRecord(positionWithinLimits, velocityWithinLimits, ...
    accelerationWithinLimits, jerkWithinLimits);
dynamics = struct( ...
    "Consistent", maximumDynamicsResidual <= tolerance, ...
    "MaximumResidual", maximumDynamicsResidual);
end

function bounds = boundsRecord(position, velocity, acceleration, jerk)
% PURPOSE
%   - Assemble continuous-bound checks in stable order.
bounds = struct( ...
    "Valid", position && velocity && acceleration && jerk, ...
    "PositionWithinLimits", position, ...
    "VelocityWithinLimits", velocity, ...
    "AccelerationWithinLimits", acceleration, ...
    "JerkWithinLimits", jerk);
end

function value = coefficients(array, segmentIndex, axisIndex)
% PURPOSE
%   - Read one ascending polynomial coefficient column.
value = reshape(array(segmentIndex, axisIndex, :), [], 1);
end

function within = withinBounds(powerCoefficient, lower, upper, tolerance)
% PURPOSE
%   - Certify a polynomial range by its Bernstein convex hull.
bernstein = powerToBernstein(powerCoefficient);
within = all(bernstein >= lower - tolerance & ...
    bernstein <= upper + tolerance);
end

function coefficient = powerToBernstein(powerCoefficient)
% PURPOSE
%   - Convert ascending power coefficients to same-degree Bernstein form.
degree = numel(powerCoefficient) - 1;
coefficient = zeros(degree + 1, 1);
for bernsteinIndex = 0:degree
    for powerIndex = 0:bernsteinIndex
        coefficient(bernsteinIndex + 1) = ...
            coefficient(bernsteinIndex + 1) + ...
            nchoosek(bernsteinIndex, powerIndex) / ...
            nchoosek(degree, powerIndex) * ...
            powerCoefficient(powerIndex + 1);
    end
end
end

function [collisionFree, resolved, minimumClearance_deg, ...
        checkCount, unresolvedCount] = certifyCollision( ...
        polynomial, obstacles, limits, options)
% PURPOSE
%   - Certify moving-obstacle clearance with conservative adaptive intervals.
if isempty(obstacles)
    collisionFree = true;
    resolved = true;
    minimumClearance_deg = Inf;
    checkCount = 0;
    unresolvedCount = 0;
    return;
end
collisionFree = true;
resolved = true;
minimumClearance_deg = Inf;
checkCount = 0;
unresolvedCount = 0;
pathSpeedBound_deg_s = norm(limits.maxVelocity_deg_s);
for segmentIndex = 1:polynomial.SegmentCount
    segmentStart_s = polynomial.SegmentStartTime_s(segmentIndex);
    segmentEnd_s = segmentStart_s + polynomial.SegmentDuration_s;
    splitTimes_s = [segmentStart_s; segmentEnd_s];
    for obstacleIndex = 1:numel(obstacles)
        obstacleTimes_s = obstacles(obstacleIndex).time_s(:);
        splitTimes_s = [splitTimes_s; obstacleTimes_s( ...
            obstacleTimes_s > segmentStart_s & ...
            obstacleTimes_s < segmentEnd_s)]; %#ok<AGROW>
    end
    splitTimes_s = unique(splitTimes_s);
    stackStart_s = splitTimes_s(1:end - 1);
    stackEnd_s = splitTimes_s(2:end);
    while ~isempty(stackStart_s)
        intervalStart_s = stackStart_s(end);
        intervalEnd_s = stackEnd_s(end);
        stackStart_s(end) = [];
        stackEnd_s(end) = [];
        intervalMid_s = (intervalStart_s + intervalEnd_s) / 2;
        point_deg = evaluatePosition( ...
            polynomial, segmentIndex, intervalMid_s);
        intervalResolved = true;
        for obstacleIndex = 1:numel(obstacles)
            [shape, geometry] = azElInternal.obstacleShapeAtTime( ...
                obstacles(obstacleIndex), intervalMid_s);
            clearance_deg = azElInternal.pointPolygonClearance( ...
                shape, point_deg);
            checkCount = checkCount + 1;
            minimumClearance_deg = min(minimumClearance_deg, clearance_deg);
            if clearance_deg <= options.CollisionClearanceTolerance_deg
                collisionFree = false;
                resolved = true;
                return;
            end
            relativeSpeedBound_deg_s = pathSpeedBound_deg_s + ...
                geometry.VertexSpeedBound_deg_s;
            crossingBound_deg = relativeSpeedBound_deg_s * ...
                (intervalEnd_s - intervalStart_s) / 2;
            intervalResolved = intervalResolved && isfinite(crossingBound_deg) && ...
                clearance_deg > crossingBound_deg + ...
                options.CollisionClearanceTolerance_deg;
        end
        if intervalResolved
            continue;
        end
        intervalDuration_s = intervalEnd_s - intervalStart_s;
        if intervalDuration_s <= options.CollisionMinimumTimeStep_s
            resolved = false;
            collisionFree = false;
            unresolvedCount = unresolvedCount + 1;
            return;
        end
        stackStart_s = [stackStart_s; intervalStart_s; intervalMid_s]; ...
            %#ok<AGROW>
        stackEnd_s = [stackEnd_s; intervalMid_s; intervalEnd_s]; ...
            %#ok<AGROW>
    end
end
end

function position_deg = evaluatePosition(polynomial, segmentIndex, time_s)
% PURPOSE
%   - Evaluate one segment position polynomial at one absolute time.
localTau = (time_s - polynomial.SegmentStartTime_s(segmentIndex)) / ...
    polynomial.SegmentDuration_s;
power = localTau .^ (0:5);
coefficient = reshape( ...
    polynomial.positionPower_deg(segmentIndex, :, :), 2, []);
position_deg = (coefficient * power.').';
end

function goalPosition_deg = goalPositionAtTime(goalState, time_s)
% PURPOSE
%   - Evaluate a fixed or sampled moving terminal position.
if isfield(goalState, "targetTime_s") && ~isempty(goalState.targetTime_s)
    goalPosition_deg = interp1( ...
        goalState.targetTime_s, goalState.targetPosition_deg, ...
        time_s, goalState.InterpolationMethod);
else
    goalPosition_deg = goalState.position_deg;
end
end

function peak = maximumAbsolute(values)
% PURPOSE
%   - Return per-axis sampled peaks with stable NaNs for empty histories.
if isempty(values)
    peak = [NaN NaN];
else
    peak = max(abs(values), [], 1);
end
end
