function validation = validateAzElExampleResult( ...
        result, diagnostics, scenarioName, requirements)
%% Section 0: Header & Readme
% SYNTAX
%   validation = validateAzElExampleResult(result, diagnostics)
%   validation = validateAzElExampleResult( ...
%       result, diagnostics, scenarioName)
%   validation = validateAzElExampleResult( ...
%       result, diagnostics, scenarioName, requirements)
%**************************************************************************
% PURPOSE
%   - Independently validate the timed trajectory returned by the public
%     planner without rerunning planning or trusting planner Success alone.
%**************************************************************************
% INPUTS
%   - result (scalar planner-result struct)
%       Compact first output from the public planner.
%   - diagnostics (scalar planner-diagnostics struct)
%       Second planner output with collision and trajectory data.
%   - scenarioName (scalar text, optional; default "az/el example")
%       Human-readable context used in the validation message.
%   - requirements (scalar struct, optional; default struct())
%       .RequireDirectBlocked is logical (default false).
%       .PositionTolerance_deg is nonnegative (default 1e-7).
%       .TimeTolerance_s is nonnegative (default 1e-8).
%       .KinematicTolerance is nonnegative (default 1e-7).
%**************************************************************************
% OUTPUTS
%   - validation (scalar struct)
%       Independent checks, observed peaks, collision mask, issues, Passed,
%       and Message. A normal planning failure returns Passed=false.
%**************************************************************************
% UNITS
%   - Position is degrees, time is seconds, velocity is degrees per second,
%     acceleration is degrees per second squared, and jerk is degrees per
%     second cubed.
%**************************************************************************

%% Section 1: Validate Inputs & Apply Defaults

if nargin < 3 || isempty(scenarioName)
    scenarioName = "az/el example";
end
if nargin < 4 || isempty(requirements)
    requirements = struct();
end
if ~isstruct(result) || ~isscalar(result) || ...
        ~isstruct(diagnostics) || ~isscalar(diagnostics) || ...
        ~isstruct(requirements) || ~isscalar(requirements)
    error("validateAzElExampleResult:InvalidInput", ...
        "result, diagnostics, and requirements must be scalar structs.");
end
plannerDiagnostics = diagnostics;
if isfield(diagnostics, "Planner")
    plannerDiagnostics = diagnostics.Planner;
end
motionOptions = result.Options;
if isfield(diagnostics, "PlannerOptions")
    motionOptions = diagnostics.PlannerOptions;
end
scenarioName = string(scenarioName);
if ~isscalar(scenarioName)
    error("validateAzElExampleResult:InvalidScenarioName", ...
        "scenarioName must be scalar text.");
end
requireDirectBlocked = requirementValue( ...
    requirements, "RequireDirectBlocked", false);
requireDirectBlocked = azElInternal.normalizeLogicalScalar( ...
    requireDirectBlocked, "RequireDirectBlocked", ...
    "validateAzElExampleResult:InvalidRequireDirectBlocked");
positionTolerance_deg = requirementValue( ...
    requirements, "PositionTolerance_deg", 1e-7);
timeTolerance_s = requirementValue( ...
    requirements, "TimeTolerance_s", 1e-8);
kinematicTolerance = requirementValue( ...
    requirements, "KinematicTolerance", 1e-7);
validateattributes(positionTolerance_deg, {'numeric'}, ...
    {'real','finite','scalar','nonnegative'});
validateattributes(timeTolerance_s, {'numeric'}, ...
    {'real','finite','scalar','nonnegative'});
validateattributes(kinematicTolerance, {'numeric'}, ...
    {'real','finite','scalar','nonnegative'});

requiredFields = ["Success" "Message" "initialState" "goalState" ...
    "limits" "Options" "Validation"];
missingFields = requiredFields(~isfield(result, requiredFields));
if ~isempty(missingFields)
    error("validateAzElExampleResult:MissingResultFields", ...
        "result is missing required fields: %s.", ...
        strjoin(missingFields, ", "));
end
requiredDiagnosticFields = ["ObstacleField" "TimedPath" "DirectSeed" ...
    "OriginalObstacleData" "ProtectedObstacleData" ...
    "ObstacleSafetyMargins_deg"];
missingDiagnosticFields = requiredDiagnosticFields( ...
    ~isfield(plannerDiagnostics, requiredDiagnosticFields));
if ~isempty(missingDiagnosticFields)
    error("validateAzElExampleResult:MissingDiagnosticFields", ...
        "diagnostics is missing required fields: %s.", ...
        strjoin(missingDiagnosticFields, ", "));
end

%% Section 2: Validate Timed State History

timedPath = plannerDiagnostics.TimedPath;
hasTrajectory = isstruct(timedPath) && isscalar(timedPath) && ...
    isfield(timedPath, "time_s") && ...
    isfield(timedPath, "position_deg") && ...
    ~isempty(timedPath.time_s) && ...
    size(timedPath.position_deg, 1) == numel(timedPath.time_s);
timeIsFinite = false;
timeIsNondecreasing = false;
timeIsStrictlyIncreasing = false;
initialStateMatched = false;
terminalStateMatched = false;
goalTimeSatisfied = false;
collisionMask = false(0, 1);
collisionFree = false;
peakVelocity_deg_s = [NaN NaN];
peakAcceleration_deg_s2 = [NaN NaN];
peakJerk_deg_s3 = [NaN NaN];
velocityWithinLimits = false;
accelerationWithinLimits = false;
jerkWithinLimits = false;
azimuthWrapPolicySatisfied = false;
continuousPolynomialExtremaVerified = false;
dynamicsDefectWithinTolerance = false;
maximumDynamicsDefect = Inf;
collisionSafetyProven = false;
bufferedChordQueryClear = false;
collisionValidationScope = "No continuous collision validation was reported.";
curveSubdivisionConverged = false;
maximumCurveDeviationBound_deg = Inf;
if hasTrajectory
    time_s = double(timedPath.time_s(:));
    position_deg = double(timedPath.position_deg);
    timeIsFinite = all(isfinite(time_s));
    timeIsNondecreasing = timeIsFinite && all(diff(time_s) >= 0);
    timeIsStrictlyIncreasing = timeIsFinite && all(diff(time_s) > 0);
    initialStateMatched = ...
        abs(time_s(1) - result.initialState.time_s) <= timeTolerance_s && ...
        norm(position_deg(1, :) - ...
        result.initialState.position_deg) <= positionTolerance_deg;
    terminalStateMatched = norm(position_deg(end, :) - ...
        result.goalState.position_deg) <= positionTolerance_deg;
    if isfield(timedPath, "velocity_deg_s")
        initialStateMatched = initialStateMatched && norm( ...
            timedPath.velocity_deg_s(1, :) - ...
            result.initialState.velocity_deg_s) <= kinematicTolerance;
        terminalStateMatched = terminalStateMatched && norm( ...
            timedPath.velocity_deg_s(end, :) - ...
            result.goalState.velocity_deg_s) <= kinematicTolerance;
    else
        initialStateMatched = false;
        terminalStateMatched = false;
    end
    if isfield(timedPath, "acceleration_deg_s2")
        initialStateMatched = initialStateMatched && norm( ...
            timedPath.acceleration_deg_s2(1, :) - ...
            result.initialState.acceleration_deg_s2) <= ...
            kinematicTolerance;
        terminalStateMatched = terminalStateMatched && norm( ...
            timedPath.acceleration_deg_s2(end, :) - ...
            result.goalState.acceleration_deg_s2) <= ...
            kinematicTolerance;
    else
        initialStateMatched = false;
        terminalStateMatched = false;
    end
    goalTimeMode = lower(string(motionOptions.GoalTimeMode));
    if goalTimeMode == "fixedarrival"
        goalTimeSatisfied = abs(time_s(end) - ...
            result.goalState.time_s) <= timeTolerance_s;
    else
        goalTimeSatisfied = time_s(end) <= ...
            result.goalState.time_s + timeTolerance_s;
    end

    collisionTimePaddingSamples = 1;
    if isfield(motionOptions, "CollisionTimePaddingSamples")
        collisionTimePaddingSamples = ...
            motionOptions.CollisionTimePaddingSamples;
    end
    curveDeviation_deg = 0;
    if isfield(timedPath, "CurveDeviationBoundBySegment_deg") && ...
            ~isempty(timedPath.CurveDeviationBoundBySegment_deg)
        curveDeviation_deg = max( ...
            timedPath.CurveDeviationBoundBySegment_deg, [], "all");
    end
    collisionMask = queryAzElTimedPathCollision( ...
        plannerDiagnostics.ObstacleField, time_s, position_deg, struct( ...
        "TimePaddingSamples", collisionTimePaddingSamples, ...
        "BoundaryIsOccupied", true));
    bufferedChordQueryClear = ~any(collisionMask);
    collisionSafetyProven = false;
    if bufferedChordQueryClear
        clearanceBuffer_deg = repmat(curveDeviation_deg, ...
            max(0, numel(time_s) - 1), 1);
        collisionSafetyProven = ...
            azElInternal.certifyAzElTimedPathClearance( ...
            plannerDiagnostics.ObstacleField, time_s, position_deg, ...
            clearanceBuffer_deg);
    end
    collisionFree = bufferedChordQueryClear && collisionSafetyProven;
    [peakVelocity_deg_s, velocityWithinLimits] = checkKinematicHistory( ...
        timedPath, "velocity_deg_s", result.limits, ...
        "maxVelocity_deg_s", kinematicTolerance);
    [peakAcceleration_deg_s2, accelerationWithinLimits] = ...
        checkKinematicHistory(timedPath, "acceleration_deg_s2", ...
        result.limits, "maxAcceleration_deg_s2", kinematicTolerance);
    [peakJerk_deg_s3, jerkWithinLimits] = checkKinematicHistory( ...
        timedPath, "jerk_deg_s3", result.limits, ...
        "maxJerk_deg_s3", kinematicTolerance);

    if motionOptions.AllowAzimuthWrapping
        azimuthWrapPolicySatisfied = true;
    else
        azimuthInterval_deg = double(motionOptions.AzimuthInterval_deg);
        azimuthWrapPolicySatisfied = all( ...
            position_deg(:, 1) >= azimuthInterval_deg(1) - ...
            positionTolerance_deg & ...
            position_deg(:, 1) <= azimuthInterval_deg(2) + ...
            positionTolerance_deg);
    end
end

%% Section 3: Validate Scenario And Safety Metadata

plannerValidation = result.Validation;
if isstruct(plannerValidation) && isscalar(plannerValidation)
    if isfield(plannerValidation, ...
            "ContinuousPolynomialExtremaVerified")
        continuousPolynomialExtremaVerified = logical( ...
            plannerValidation.ContinuousPolynomialExtremaVerified);
    end
    if isfield(plannerValidation, "CollisionSafetyProven")
        collisionSafetyProven = collisionSafetyProven && logical( ...
            plannerValidation.CollisionSafetyProven);
    end
    if isfield(plannerValidation, "BufferedChordQueryClear")
        bufferedChordQueryClear = bufferedChordQueryClear && logical( ...
            plannerValidation.BufferedChordQueryClear);
    end
    if isfield(plannerValidation, "CollisionValidationScope")
        collisionValidationScope = string( ...
            plannerValidation.CollisionValidationScope);
    end
    if isfield(plannerValidation, "CurveSubdivisionConverged")
        curveSubdivisionConverged = logical( ...
            plannerValidation.CurveSubdivisionConverged);
    end
    if isfield(plannerValidation, "MaximumCurveDeviationBound_deg")
        maximumCurveDeviationBound_deg = double( ...
            plannerValidation.MaximumCurveDeviationBound_deg);
    end
    if isfield(plannerValidation, "MaximumDynamicsDefect")
        maximumDynamicsDefect = double( ...
            plannerValidation.MaximumDynamicsDefect);
    end
    if isfield(plannerValidation, "DynamicsDefectWithinTolerance")
        dynamicsDefectWithinTolerance = logical( ...
            plannerValidation.DynamicsDefectWithinTolerance) && ...
            isfinite(maximumDynamicsDefect) && ...
            maximumDynamicsDefect <= ...
            motionOptions.CollocationErrorTolerance;
    end
end
collisionFree = collisionFree && bufferedChordQueryClear && ...
    collisionSafetyProven;

directRouteRequirementSatisfied = ~requireDirectBlocked || ...
    any(plannerDiagnostics.DirectSeed.blocked);
safetyMarginPolicySatisfied = ...
    verifySafetyMarginPolicy(plannerDiagnostics);
plannerReportedSuccess = logical(result.Success);
checks = [ ...
    plannerReportedSuccess, hasTrajectory, timeIsFinite, ...
    timeIsStrictlyIncreasing, initialStateMatched, terminalStateMatched, ...
    goalTimeSatisfied, collisionFree, velocityWithinLimits, ...
    accelerationWithinLimits, jerkWithinLimits, ...
    continuousPolynomialExtremaVerified, ...
    curveSubdivisionConverged, ...
    dynamicsDefectWithinTolerance, ...
    azimuthWrapPolicySatisfied, directRouteRequirementSatisfied, ...
    safetyMarginPolicySatisfied];
checkNames = [ ...
    "plannerReportedSuccess" "hasTrajectory" "timeIsFinite" ...
    "timeIsStrictlyIncreasing" "initialStateMatched" ...
    "terminalStateMatched" "goalTimeSatisfied" "collisionFree" ...
    "velocityWithinLimits" "accelerationWithinLimits" ...
    "jerkWithinLimits" "continuousPolynomialExtremaVerified" ...
    "curveSubdivisionConverged" "dynamicsDefectWithinTolerance" ...
    "azimuthWrapPolicySatisfied" ...
    "directRouteRequirementSatisfied" "safetyMarginPolicySatisfied"];
issues = checkNames(~checks);
passed = all(checks);
message = scenarioName + " passed independent example validation.";
if ~passed
    message = scenarioName + " failed independent checks: " + ...
        strjoin(issues, ", ") + ". " + string(result.Message);
end

%% Section 4: Assemble Stable Validation Output

validation = struct( ...
    "Passed", passed, ...
    "Message", message, ...
    "PlannerReportedSuccess", plannerReportedSuccess, ...
    "HasTrajectory", hasTrajectory, ...
    "TimeIsFinite", timeIsFinite, ...
    "TimeIsNondecreasing", timeIsNondecreasing, ...
    "TimeIsStrictlyIncreasing", timeIsStrictlyIncreasing, ...
    "InitialStateMatched", initialStateMatched, ...
    "TerminalStateMatched", terminalStateMatched, ...
    "GoalTimeSatisfied", goalTimeSatisfied, ...
    "CollisionFree", collisionFree, ...
    "BufferedChordQueryClear", bufferedChordQueryClear, ...
    "CollisionSafetyProven", collisionSafetyProven, ...
    "CollisionValidationScope", collisionValidationScope, ...
    "CurveSubdivisionConverged", curveSubdivisionConverged, ...
    "MaximumCurveDeviationBound_deg", ...
    maximumCurveDeviationBound_deg, ...
    "VelocityWithinLimits", velocityWithinLimits, ...
    "AccelerationWithinLimits", accelerationWithinLimits, ...
    "JerkWithinLimits", jerkWithinLimits, ...
    "ContinuousPolynomialExtremaVerified", ...
    continuousPolynomialExtremaVerified, ...
    "DynamicsDefectWithinTolerance", ...
    dynamicsDefectWithinTolerance, ...
    "MaximumDynamicsDefect", maximumDynamicsDefect, ...
    "AzimuthWrapPolicySatisfied", azimuthWrapPolicySatisfied, ...
    "DirectRouteRequirementSatisfied", ...
    directRouteRequirementSatisfied, ...
    "DirectRouteRequirementScope", ...
    "Straight-line motion spread over the complete goal horizon.", ...
    "SafetyMarginPolicySatisfied", safetyMarginPolicySatisfied, ...
    "PeakVelocity_deg_s", peakVelocity_deg_s, ...
    "PeakAcceleration_deg_s2", peakAcceleration_deg_s2, ...
    "PeakJerk_deg_s3", peakJerk_deg_s3, ...
    "CollisionMask", logical(collisionMask(:)), ...
    "Issues", issues);
end

%% Section 5: Local Functions

function value = requirementValue(requirements, fieldName, defaultValue)
% PURPOSE
%   - Resolve one optional independent-validation requirement.
value = defaultValue;
if isfield(requirements, fieldName) && ...
        ~isempty(requirements.(fieldName))
    value = requirements.(fieldName);
end
end

function [peakValue, withinLimits] = checkKinematicHistory( ...
        timedPath, historyField, limits, limitField, tolerance)
% PURPOSE
%   - Independently compare one two-axis history with its limits.
limit = [Inf Inf];
if isfield(limits, limitField) && ~isempty(limits.(limitField))
    limit = reshape(double(limits.(limitField)), 1, []);
    if isscalar(limit)
        limit = repmat(limit, 1, 2);
    end
end
if ~isfield(timedPath, historyField) || ...
        isempty(timedPath.(historyField))
    peakValue = [NaN NaN];
    withinLimits = all(~isfinite(limit));
    return;
end
history = double(timedPath.(historyField));
peakValue = max(abs(history), [], 1);
finiteLimitAxis = isfinite(limit);
if ~any(finiteLimitAxis)
    withinLimits = true;
else
    withinLimits = size(history, 2) == 2 && ...
        all(isfinite(history(:, finiteLimitAxis)), "all") && ...
        all(peakValue(finiteLimitAxis) <= ...
        limit(finiteLimitAxis) + tolerance);
end
end

function policySatisfied = verifySafetyMarginPolicy(diagnostics)
% PURPOSE
%   - Rebuild each protected obstacle once from its stored original geometry.
requiredFields = ["OriginalObstacleData" "ProtectedObstacleData" ...
    "ObstacleSafetyMargins_deg"];
policySatisfied = all(isfield(diagnostics, requiredFields));
if ~policySatisfied
    return;
end
protectedData = diagnostics.ProtectedObstacleData;
originalData = diagnostics.OriginalObstacleData;
margins_deg = double(diagnostics.ObstacleSafetyMargins_deg(:));
policySatisfied = numel(protectedData) == numel(originalData) && ...
    numel(protectedData) == numel(margins_deg) && ...
    all(isfinite(margins_deg)) && all(margins_deg >= 0);
if ~policySatisfied
    return;
end
for obstacleIndex = 1:numel(protectedData)
    requiredGeometryFields = ["az_deg" "el_deg" ...
        "originalAz_deg" "originalEl_deg" "safetyMargin_deg"];
    if ~all(isfield(protectedData(obstacleIndex), ...
            requiredGeometryFields)) || ...
            ~all(isfield(originalData(obstacleIndex), ...
            requiredGeometryFields))
        policySatisfied = false;
        return;
    end
    rebuilt = inflateAzElObstacleData( ...
        protectedData(obstacleIndex), margins_deg(obstacleIndex));
    protectedMatchesOneInflation = isequaln( ...
        rebuilt.az_deg, protectedData(obstacleIndex).az_deg) && ...
        isequaln(rebuilt.el_deg, protectedData(obstacleIndex).el_deg);
    originalMatchesProvenance = isequaln( ...
        originalData(obstacleIndex).az_deg, ...
        protectedData(obstacleIndex).originalAz_deg) && ...
        isequaln(originalData(obstacleIndex).el_deg, ...
        protectedData(obstacleIndex).originalEl_deg);
    marginMatches = ...
        protectedData(obstacleIndex).safetyMargin_deg == ...
        margins_deg(obstacleIndex) && ...
        originalData(obstacleIndex).safetyMargin_deg == 0;
    if ~(protectedMatchesOneInflation && originalMatchesProvenance && ...
            marginMatches)
        policySatisfied = false;
        return;
    end
end
end
