function validation = validateAzElTrajectory(trajectory, obstacles, ...
        initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   validation = validateAzElTrajectory()
%   validation = validateAzElTrajectory(result)
%   validation = validateAzElTrajectory( ...
%       trajectory, obstacles, initialState, goalState, limits, options)
%**************************************************************************
% PURPOSE
%   - Independently validate one complete polynomial motion and geometry.
%   - Fail unresolved continuous-collision intervals instead of accepting them.
%**************************************************************************
% INPUTS
%   - trajectory (scalar candidate or planner-result struct)
%       Must contain sampled histories and Polynomial segment coefficients.
%   - obstacles (canonical protected obstacle array, optional with result)
%   - initialState, goalState (normalized state structs, optional with result)
%   - limits (normalized physical limits struct, optional with result)
%   - options (resolved planner options, optional with result)
%**************************************************************************
% OUTPUTS
%   - validation (scalar struct)
%       Stable independent pass/fail checks, extrema, clearance, and message.
%**************************************************************************
% UNITS
%   - Position and clearance are degrees. Derivatives use deg/s, deg/s^2,
%     and deg/s^3. Time is seconds.
%**************************************************************************
if nargin == 0
    validation = emptyValidation();
    return;
end
%% Section 1: Resolve Inputs And Basic History Checks
if nargin == 1
    requiredResultFields = {'Inputs', 'Options', 'Polynomial'};
    if ~isstruct(trajectory) || ~isscalar(trajectory) || ...
            ~all(isfield(trajectory, requiredResultFields))
        error("validateAzElTrajectory:InvalidResult", ...
            "A one-input call requires a planner result with Inputs, " + ...
            "Options, and Polynomial fields.");
    end
    obstacles = trajectory.Inputs.obstacles;
    initialState = trajectory.Inputs.initialState;
    goalState = trajectory.Inputs.goalState;
    limits = trajectory.Inputs.limits;
    options = trajectory.Options;
elseif nargin ~= 6
    error("validateAzElTrajectory:InvalidCall", ...
        "Use one planner result or all six explicit validation inputs.");
end
obstacles = combineAzElObstacles(obstacles);
hasMovingGoal = isfield(goalState, "targetTime_s") && ...
    ~isempty(goalState.targetTime_s);
if options.AllowAzimuthWrapping && ...
        (~isempty(obstacles) || hasMovingGoal)
    error("validateAzElTrajectory:UnsupportedWrappedGeometry", ...
        "Wrapped validation is supported only for obstacle-free " + ...
        "fixed-position goals.");
end
requiredFields = {'time_s', 'position_deg', 'velocity_deg_s', ...
    'acceleration_deg_s2', 'jerk_deg_s3', 'Polynomial'};
hasRequiredFields = isstruct(trajectory) && isscalar(trajectory) && ...
    all(isfield(trajectory, requiredFields));
if ~hasRequiredFields
    error("validateAzElTrajectory:InvalidTrajectory", ...
        "trajectory must contain sampled histories and Polynomial data.");
end
time_s = double(trajectory.time_s(:));
position_deg = double(trajectory.position_deg);
velocity_deg_s = double(trajectory.velocity_deg_s);
acceleration_deg_s2 = double(trajectory.acceleration_deg_s2);
jerk_deg_s3 = double(trajectory.jerk_deg_s3);
sampleCount = numel(time_s);
historySizesMatch = ...
    isequal(size(position_deg), [sampleCount 2]) && ...
    isequal(size(velocity_deg_s), [sampleCount 2]) && ...
    isequal(size(acceleration_deg_s2), [sampleCount 2]) && ...
    isequal(size(jerk_deg_s3), [sampleCount 2]);
timeIsFinite = ~isempty(time_s) && all(isfinite(time_s));
timeIsStrictlyIncreasing = timeIsFinite && all(diff(time_s) > 0);
historyIsFinite = sampleCount > 0 && historySizesMatch && ...
    all(isfinite(position_deg), "all") && ...
    all(isfinite(velocity_deg_s), "all") && ...
    all(isfinite(acceleration_deg_s2), "all") && ...
    all(isfinite(jerk_deg_s3), "all");
%% Section 2: Validate Endpoints And Continuous Polynomial Bounds
stateTolerance = max(10 * options.ConstraintTolerance, 1e-7);
initialStateMatched = historyIsFinite && ...
    max(abs(position_deg(1, :) - initialState.position_deg)) <= ...
    stateTolerance && ...
    max(abs(velocity_deg_s(1, :) - initialState.velocity_deg_s)) <= ...
    stateTolerance && ...
    max(abs(acceleration_deg_s2(1, :) - ...
    initialState.acceleration_deg_s2)) <= stateTolerance;
if timeIsFinite
    goalPosition_deg = azElInternal.goalPositionAtTime( ...
        goalState, time_s(end));
else
    goalPosition_deg = [NaN NaN];
end
terminalStateMatched = historyIsFinite && ...
    max(abs(position_deg(end, :) - goalPosition_deg)) <= stateTolerance && ...
    max(abs(velocity_deg_s(end, :) - goalState.velocity_deg_s)) <= ...
    stateTolerance && ...
    max(abs(acceleration_deg_s2(end, :) - ...
    goalState.acceleration_deg_s2)) <= stateTolerance;
if options.GoalTimeMode == "fixedArrival"
    goalTimeSatisfied = timeIsFinite && ...
        abs(time_s(end) - goalState.time_s) <= stateTolerance;
else
    goalTimeSatisfied = timeIsFinite && ...
        time_s(end) <= goalState.time_s + stateTolerance && ...
        time_s(end) > initialState.time_s;
end
[continuousBounds, dynamics, polynomialChecks] = validatePolynomial( ...
    trajectory.Polynomial, time_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, jerk_deg_s3, initialState, goalState, limits, ...
    options, stateTolerance);
%% Section 3: Certify Continuous Collision Freedom
if timeIsStrictlyIncreasing && historyIsFinite && continuousBounds.Valid
    validationDeadlineReached = internalDeadlineReached(options);
    if ~validationDeadlineReached
        [seedCorridorCertified, seedCorridorClearance_deg] = ...
            azElInternal.certifySeedCorridor( ...
            trajectory, obstacles, ...
            options.CollisionClearanceTolerance_deg);
        validationDeadlineReached = internalDeadlineReached(options);
    else
        seedCorridorCertified = false;
        seedCorridorClearance_deg = NaN;
    end
    if validationDeadlineReached
        seedCorridorCertified = false;
        collisionFree = false;
        collisionResolved = false;
        minimumClearance_deg = NaN;
        collisionCheckCount = 0;
        unresolvedIntervalCount = 1;
    elseif seedCorridorCertified
        collisionFree = true;
        collisionResolved = true;
        minimumClearance_deg = seedCorridorClearance_deg;
        collisionCheckCount = 0;
        unresolvedIntervalCount = 0;
    else
        [collisionFree, collisionResolved, minimumClearance_deg, ...
            collisionCheckCount, unresolvedIntervalCount, ...
            validationDeadlineReached] = ...
            certifyCollision( ...
            trajectory.Polynomial, obstacles, limits, options);
    end
else
    seedCorridorCertified = false;
    collisionFree = false;
    collisionResolved = false;
    minimumClearance_deg = NaN;
    collisionCheckCount = 0;
    unresolvedIntervalCount = 0;
    validationDeadlineReached = false;
end
safetyMarginPolicySatisfied = true;
for obstacleIndex = 1:numel(obstacles)
    obstacle = obstacles(obstacleIndex);
    obstacleHasProvenance = isfield(obstacle, "originalAz_deg") && ...
        isfield(obstacle, "originalEl_deg") && ...
        isfinite(obstacle.safetyMargin_deg) && ...
        obstacle.safetyMargin_deg >= 0;
    safetyMarginPolicySatisfied = ...
        safetyMarginPolicySatisfied && obstacleHasProvenance;
end
azimuthWrapPolicySatisfied = options.AllowAzimuthWrapping || ...
    continuousBounds.PositionWithinLimits;
%% Section 4: Assemble The Stable Validation Record
passed = historySizesMatch && timeIsStrictlyIncreasing && ...
    historyIsFinite && initialStateMatched && terminalStateMatched && ...
    goalTimeSatisfied && polynomialChecks.Valid && ...
    continuousBounds.Valid && dynamics.Consistent && ...
    collisionFree && collisionResolved && ...
    safetyMarginPolicySatisfied && azimuthWrapPolicySatisfied;
issues = strings(0, 1);
checkNames = [ ...
    "history shape", "finite increasing time", "finite histories", ...
    "initial state", "terminal state", "goal time", ...
    "polynomial schema", "polynomial initial time", ...
    "polynomial time base", ...
    "polynomial segment continuity", "polynomial endpoint states", ...
    "polynomial sampled histories", "continuous limits", ...
    "polynomial dynamics", "collision freedom", ...
    "collision resolution", "safety-margin provenance", ...
    "azimuth-wrap policy", "validation deadline"];
checkValues = [ ...
    historySizesMatch, timeIsStrictlyIncreasing, historyIsFinite, ...
    initialStateMatched, terminalStateMatched, goalTimeSatisfied, ...
    polynomialChecks.SchemaValid, polynomialChecks.InitialTimeMatched, ...
    polynomialChecks.TimeBaseConsistent, ...
    polynomialChecks.SegmentContinuity, ...
    polynomialChecks.EndpointStatesMatched, ...
    polynomialChecks.HistoryConsistent, continuousBounds.Valid, ...
    dynamics.Consistent, collisionFree, ...
    collisionResolved, safetyMarginPolicySatisfied, ...
    azimuthWrapPolicySatisfied, ~validationDeadlineReached];
for checkIndex = 1:numel(checkNames)
    if ~checkValues(checkIndex)
        issues(end + 1, 1) = checkNames(checkIndex); %#ok<AGROW>
    end
end
if passed
    message = "Independent continuous validation passed.";
else
    message = "Independent validation failed: " + ...
        strjoin(issues, ", ") + ".";
end
validation = struct( ...
    "Passed", passed, ...
    "Message", message, ...
    "HistorySizesMatch", historySizesMatch, ...
    "TimeIsFinite", timeIsFinite, ...
    "TimeIsStrictlyIncreasing", timeIsStrictlyIncreasing, ...
    "HistoryIsFinite", historyIsFinite, ...
    "InitialStateMatched", initialStateMatched, ...
    "TerminalStateMatched", terminalStateMatched, ...
    "GoalTimeSatisfied", goalTimeSatisfied, ...
    "PolynomialSchemaValid", polynomialChecks.SchemaValid, ...
    "PolynomialInitialTimeMatched", ...
    polynomialChecks.InitialTimeMatched, ...
    "PolynomialTimeBaseConsistent", ...
    polynomialChecks.TimeBaseConsistent, ...
    "PolynomialSegmentContinuity", ...
    polynomialChecks.SegmentContinuity, ...
    "PolynomialEndpointStatesMatched", ...
    polynomialChecks.EndpointStatesMatched, ...
    "PolynomialHistoryConsistent", ...
    polynomialChecks.HistoryConsistent, ...
    "MaximumSegmentContinuityResidual", ...
    polynomialChecks.MaximumSegmentContinuityResidual, ...
    "MaximumPolynomialHistoryResidual", ...
    polynomialChecks.MaximumHistoryResidual, ...
    "PositionWithinLimits", continuousBounds.PositionWithinLimits, ...
    "VelocityWithinLimits", continuousBounds.VelocityWithinLimits, ...
    "AccelerationWithinLimits", ...
    continuousBounds.AccelerationWithinLimits, ...
    "JerkWithinLimits", continuousBounds.JerkWithinLimits, ...
    "DynamicsConsistent", dynamics.Consistent, ...
    "MaximumDynamicsResidual", dynamics.MaximumResidual, ...
    "CollisionFree", collisionFree, ...
    "CollisionResolved", collisionResolved, ...
    "SeedCorridorCertified", seedCorridorCertified, ...
    "MinimumClearance_deg", minimumClearance_deg, ...
    "CollisionCheckCount", collisionCheckCount, ...
    "UnresolvedIntervalCount", unresolvedIntervalCount, ...
    "DeadlineReached", validationDeadlineReached, ...
    "SafetyMarginPolicySatisfied", safetyMarginPolicySatisfied, ...
    "AzimuthWrapPolicySatisfied", azimuthWrapPolicySatisfied, ...
    "PeakVelocity_deg_s", maximumAbsolute(velocity_deg_s), ...
    "PeakAcceleration_deg_s2", maximumAbsolute(acceleration_deg_s2), ...
    "PeakJerk_deg_s3", maximumAbsolute(jerk_deg_s3), ...
    "Issues", issues);
end
%% Section 5: Local Functions
function [bounds, dynamics, checks] = validatePolynomial( ...
        polynomial, time_s, position_deg, velocity_deg_s, ...
        acceleration_deg_s2, jerk_deg_s3, initialState, goalState, ...
        limits, options, tolerance)
% PURPOSE
%   - Check the complete polynomial schema, dynamics, and returned histories.
checks = emptyPolynomialChecks();
bounds = boundsRecord(false, false, false, false);
dynamics = struct("Consistent", false, "MaximumResidual", Inf);
requiredFields = {'SegmentCount', 'SegmentStartTime_s', ...
    'SegmentDuration_s', 'FinalTime_s', 'positionPower_deg', ...
    'velocityPower_deg_s', 'accelerationPower_deg_s2', ...
    'jerkPower_deg_s3'};
hasFields = isstruct(polynomial) && isscalar(polynomial) && ...
    all(isfield(polynomial, requiredFields));
if ~hasFields
    return;
end
segmentCount = polynomial.SegmentCount;
segmentDuration_s = polynomial.SegmentDuration_s;
countIsValid = isnumeric(segmentCount) && isscalar(segmentCount) && ...
    isfinite(segmentCount) && segmentCount >= 1 && ...
    segmentCount == fix(segmentCount);
durationIsValid = isnumeric(segmentDuration_s) && ...
    isscalar(segmentDuration_s) && isfinite(segmentDuration_s) && ...
    segmentDuration_s > 0;
finalTimeIsValid = isnumeric(polynomial.FinalTime_s) && ...
    isscalar(polynomial.FinalTime_s) && isfinite(polynomial.FinalTime_s);
if ~(countIsValid && durationIsValid && finalTimeIsValid)
    return;
end
segmentStartTime_s = double(polynomial.SegmentStartTime_s(:));
timeArrayIsValid = numel(segmentStartTime_s) == segmentCount && ...
    all(isfinite(segmentStartTime_s));
coefficientArrays = {polynomial.positionPower_deg, ...
    polynomial.velocityPower_deg_s, ...
    polynomial.accelerationPower_deg_s2, ...
    polynomial.jerkPower_deg_s3};
expectedSizes = {[segmentCount 2 6], [segmentCount 2 5], ...
    [segmentCount 2 4], [segmentCount 2 3]};
coefficientArraysAreValid = true;
for arrayIndex = 1:numel(coefficientArrays)
    array = coefficientArrays{arrayIndex};
    coefficientArraysAreValid = coefficientArraysAreValid && ...
        isnumeric(array) && isequal(size(array), expectedSizes{arrayIndex}) && ...
        all(isfinite(array), "all");
end
checks.SchemaValid = timeArrayIsValid && coefficientArraysAreValid;
if ~checks.SchemaValid
    return;
end
expectedStartTime_s = segmentStartTime_s(1) + ...
    (0:segmentCount - 1).' * segmentDuration_s;
expectedFinalTime_s = segmentStartTime_s(1) + ...
    segmentCount * segmentDuration_s;
timeTolerance_s = max(tolerance, ...
    100 * eps(max(1, max(abs([expectedStartTime_s; ...
    expectedFinalTime_s])))));
sampleTimeIsConsistent = ~isempty(time_s) && all(isfinite(time_s)) && ...
    abs(time_s(1) - segmentStartTime_s(1)) <= timeTolerance_s && ...
    abs(time_s(end) - expectedFinalTime_s) <= timeTolerance_s && ...
    all(time_s >= segmentStartTime_s(1) - timeTolerance_s) && ...
    all(time_s <= expectedFinalTime_s + timeTolerance_s);
checks.TimeBaseConsistent = sampleTimeIsConsistent && ...
    max(abs(segmentStartTime_s - expectedStartTime_s)) <= ...
    timeTolerance_s && ...
    abs(polynomial.FinalTime_s - expectedFinalTime_s) <= timeTolerance_s;
checks.InitialTimeMatched = abs( ...
    segmentStartTime_s(1) - initialState.time_s) <= timeTolerance_s;
positionWithinLimits = true;
velocityWithinLimits = true;
accelerationWithinLimits = true;
jerkWithinLimits = true;
maximumDynamicsResidual = 0;
maximumSegmentContinuityResidual = 0;
positionLower_deg = [options.AzimuthInterval_deg(1), ...
    options.ElevationInterval_deg(1)];
positionUpper_deg = [options.AzimuthInterval_deg(2), ...
    options.ElevationInterval_deg(2)];
for segmentIndex = 1:segmentCount
    for axisIndex = 1:2
        positionPower = coefficients( ...
            polynomial.positionPower_deg, segmentIndex, axisIndex);
        velocityPower = coefficients( ...
            polynomial.velocityPower_deg_s, segmentIndex, axisIndex);
        accelerationPower = coefficients( ...
            polynomial.accelerationPower_deg_s2, segmentIndex, axisIndex);
        jerkPower = coefficients( ...
            polynomial.jerkPower_deg_s3, segmentIndex, axisIndex);
        if ~(axisIndex == 1 && options.AllowAzimuthWrapping)
            positionWithinLimits = positionWithinLimits && withinBounds( ...
                positionPower, positionLower_deg(axisIndex), ...
                positionUpper_deg(axisIndex), tolerance);
        end
        velocityWithinLimits = velocityWithinLimits && withinBounds( ...
            velocityPower, -limits.maxVelocity_deg_s(axisIndex), ...
            limits.maxVelocity_deg_s(axisIndex), tolerance);
        accelerationWithinLimits = accelerationWithinLimits && ...
            withinBounds(accelerationPower, ...
            -limits.maxAcceleration_deg_s2(axisIndex), ...
            limits.maxAcceleration_deg_s2(axisIndex), tolerance);
        jerkWithinLimits = jerkWithinLimits && withinBounds( ...
            jerkPower, -limits.maxJerk_deg_s3(axisIndex), ...
            limits.maxJerk_deg_s3(axisIndex), tolerance);
        positionDerivative = (1:numel(positionPower) - 1).' .* ...
            positionPower(2:end) / segmentDuration_s;
        velocityDerivative = (1:numel(velocityPower) - 1).' .* ...
            velocityPower(2:end) / segmentDuration_s;
        accelerationDerivative = ...
            (1:numel(accelerationPower) - 1).' .* ...
            accelerationPower(2:end) / segmentDuration_s;
        maximumDynamicsResidual = max(maximumDynamicsResidual, max([ ...
            abs(positionDerivative - velocityPower); ...
            abs(velocityDerivative - accelerationPower); ...
            abs(accelerationDerivative - jerkPower)]));
        if segmentIndex < segmentCount
            nextPositionPower = coefficients( ...
                polynomial.positionPower_deg, segmentIndex + 1, axisIndex);
            nextVelocityPower = coefficients( ...
                polynomial.velocityPower_deg_s, segmentIndex + 1, axisIndex);
            nextAccelerationPower = coefficients( ...
                polynomial.accelerationPower_deg_s2, ...
                segmentIndex + 1, axisIndex);
            continuityResidual = [ ...
                sum(positionPower) - nextPositionPower(1); ...
                sum(velocityPower) - nextVelocityPower(1); ...
                sum(accelerationPower) - nextAccelerationPower(1)];
            maximumSegmentContinuityResidual = max( ...
                maximumSegmentContinuityResidual, ...
                max(abs(continuityResidual)));
        end
    end
end
bounds = boundsRecord(positionWithinLimits, velocityWithinLimits, ...
    accelerationWithinLimits, jerkWithinLimits);
dynamics = struct( ...
    "Consistent", maximumDynamicsResidual <= tolerance, ...
    "MaximumResidual", maximumDynamicsResidual);
checks.MaximumSegmentContinuityResidual = ...
    maximumSegmentContinuityResidual;
checks.SegmentContinuity = ...
    maximumSegmentContinuityResidual <= tolerance;
initialPolynomialState = [ ...
    reshape(polynomial.positionPower_deg(1, :, 1), 1, 2), ...
    reshape(polynomial.velocityPower_deg_s(1, :, 1), 1, 2), ...
    reshape(polynomial.accelerationPower_deg_s2(1, :, 1), 1, 2)];
terminalPosition_deg = sum(reshape( ...
    polynomial.positionPower_deg(end, :, :), 2, []), 2).';
terminalVelocity_deg_s = sum(reshape( ...
    polynomial.velocityPower_deg_s(end, :, :), 2, []), 2).';
terminalAcceleration_deg_s2 = sum(reshape( ...
    polynomial.accelerationPower_deg_s2(end, :, :), 2, []), 2).';
goalPosition_deg = azElInternal.goalPositionAtTime( ...
    goalState, polynomial.FinalTime_s);
expectedEndpointState = [initialState.position_deg, ...
    initialState.velocity_deg_s, initialState.acceleration_deg_s2, ...
    goalPosition_deg, goalState.velocity_deg_s, ...
    goalState.acceleration_deg_s2];
polynomialEndpointState = [initialPolynomialState, ...
    terminalPosition_deg, terminalVelocity_deg_s, ...
    terminalAcceleration_deg_s2];
checks.EndpointStatesMatched = max(abs( ...
    polynomialEndpointState - expectedEndpointState)) <= tolerance;
[~, polynomialPosition_deg, polynomialVelocity_deg_s, ...
    polynomialAcceleration_deg_s2, polynomialJerk_deg_s3] = ...
    azElInternal.evaluateAzElPolynomial(polynomial, time_s);
historySizesMatch = isequal(size(position_deg), ...
    size(polynomialPosition_deg)) && isequal(size(velocity_deg_s), ...
    size(polynomialVelocity_deg_s)) && ...
    isequal(size(acceleration_deg_s2), ...
    size(polynomialAcceleration_deg_s2)) && ...
    isequal(size(jerk_deg_s3), size(polynomialJerk_deg_s3));
if historySizesMatch
    checks.MaximumHistoryResidual = max(abs([ ...
        position_deg - polynomialPosition_deg, ...
        velocity_deg_s - polynomialVelocity_deg_s, ...
        acceleration_deg_s2 - polynomialAcceleration_deg_s2, ...
        jerk_deg_s3 - polynomialJerk_deg_s3]), [], "all");
    checks.HistoryConsistent = ...
        checks.MaximumHistoryResidual <= tolerance;
end
checks.Valid = checks.SchemaValid && checks.InitialTimeMatched && ...
    checks.TimeBaseConsistent && ...
    checks.SegmentContinuity && checks.EndpointStatesMatched && ...
    checks.HistoryConsistent;
end
function checks = emptyPolynomialChecks()
% PURPOSE
%   - Define stable polynomial-consistency checks for every invalid schema.
checks = struct( ...
    "Valid", false, "SchemaValid", false, ...
    "InitialTimeMatched", false, ...
    "TimeBaseConsistent", false, "SegmentContinuity", false, ...
    "EndpointStatesMatched", false, "HistoryConsistent", false, ...
    "MaximumSegmentContinuityResidual", Inf, ...
    "MaximumHistoryResidual", Inf);
end
function bounds = boundsRecord(position, velocity, acceleration, jerk)
% PURPOSE
%   - Assemble continuous-bound checks in stable order.
bounds = struct( ...
    "Valid", position && velocity && acceleration && jerk, ...
    "PositionWithinLimits", position, ...
    "VelocityWithinLimits", velocity, ...
    "AccelerationWithinLimits", acceleration, ...
    "JerkWithinLimits", jerk);
end
function value = coefficients(array, segmentIndex, axisIndex)
% PURPOSE
%   - Read one ascending polynomial coefficient column.
value = reshape(array(segmentIndex, axisIndex, :), [], 1);
end
function within = withinBounds(powerCoefficient, lower, upper, tolerance)
% PURPOSE
%   - Certify a polynomial range by its Bernstein convex hull.
bernstein = azElInternal.powerToBernstein(powerCoefficient);
within = all(bernstein >= lower - tolerance & ...
    bernstein <= upper + tolerance);
end
function [collisionFree, resolved, minimumClearance_deg, ...
        checkCount, unresolvedCount, deadlineReached] = certifyCollision( ...
        polynomial, obstacles, limits, options)
% PURPOSE
%   - Certify moving-obstacle clearance with conservative adaptive intervals.
if isempty(obstacles)
    collisionFree = true;
    resolved = true;
    minimumClearance_deg = Inf;
    checkCount = 0;
    unresolvedCount = 0;
    deadlineReached = false;
    return;
end
collisionFree = true;
resolved = true;
minimumClearance_deg = Inf;
checkCount = 0;
unresolvedCount = 0;
deadlineReached = false;
pathSpeedBound_deg_s = norm(limits.maxVelocity_deg_s);
for segmentIndex = 1:polynomial.SegmentCount
    segmentStart_s = polynomial.SegmentStartTime_s(segmentIndex);
    segmentEnd_s = segmentStart_s + polynomial.SegmentDuration_s;
    splitTimes_s = [segmentStart_s; segmentEnd_s];
    for obstacleIndex = 1:numel(obstacles)
        obstacleTimes_s = obstacles(obstacleIndex).time_s(:);
        splitTimes_s = [splitTimes_s; obstacleTimes_s( ...
            obstacleTimes_s > segmentStart_s & ...
            obstacleTimes_s < segmentEnd_s)]; %#ok<AGROW>
    end
    splitTimes_s = unique(splitTimes_s);
    for splitIndex = 1:numel(splitTimes_s)
        if internalDeadlineReached(options)
            collisionFree = false;
            resolved = false;
            unresolvedCount = unresolvedCount + 1;
            deadlineReached = true;
            return;
        end
        [~, splitPoint_deg] = azElInternal.evaluateAzElPolynomial( ...
            polynomial, splitTimes_s(splitIndex), segmentIndex);
        for obstacleIndex = 1:numel(obstacles)
            shape = azElInternal.obstacleShapeAtTime( ...
                obstacles(obstacleIndex), splitTimes_s(splitIndex));
            clearance_deg = azElInternal.pointPolygonClearance( ...
                shape, splitPoint_deg);
            checkCount = checkCount + 1;
            minimumClearance_deg = min( ...
                minimumClearance_deg, clearance_deg);
            if clearance_deg <= ...
                    options.CollisionClearanceTolerance_deg
                collisionFree = false;
                resolved = true;
                return;
            end
        end
    end
    stackStart_s = splitTimes_s(1:end - 1);
    stackEnd_s = splitTimes_s(2:end);
    while ~isempty(stackStart_s)
        if internalDeadlineReached(options)
            collisionFree = false;
            resolved = false;
            unresolvedCount = unresolvedCount + numel(stackStart_s);
            deadlineReached = true;
            return;
        end
        intervalStart_s = stackStart_s(end);
        intervalEnd_s = stackEnd_s(end);
        stackStart_s(end) = [];
        stackEnd_s(end) = [];
        intervalMid_s = (intervalStart_s + intervalEnd_s) / 2;
        [~, point_deg] = azElInternal.evaluateAzElPolynomial( ...
            polynomial, intervalMid_s, segmentIndex);
        intervalResolved = true;
        intervalClearanceLowerBound_deg = Inf;
        for obstacleIndex = 1:numel(obstacles)
            [shape, geometry] = azElInternal.obstacleShapeAtTime( ...
                obstacles(obstacleIndex), intervalMid_s);
            clearance_deg = azElInternal.pointPolygonClearance( ...
                shape, point_deg);
            checkCount = checkCount + 1;
            if clearance_deg <= options.CollisionClearanceTolerance_deg
                minimumClearance_deg = min( ...
                    minimumClearance_deg, clearance_deg);
                collisionFree = false;
                resolved = true;
                return;
            end
            relativeSpeedBound_deg_s = pathSpeedBound_deg_s + ...
                geometry.VertexSpeedBound_deg_s;
            crossingBound_deg = relativeSpeedBound_deg_s * ...
                (intervalEnd_s - intervalStart_s) / 2;
            intervalClearanceLowerBound_deg = min( ...
                intervalClearanceLowerBound_deg, ...
                clearance_deg - crossingBound_deg);
            intervalResolved = intervalResolved && isfinite(crossingBound_deg) && ...
                clearance_deg > crossingBound_deg + ...
                options.CollisionClearanceTolerance_deg;
        end
        if intervalResolved
            minimumClearance_deg = min( ...
                minimumClearance_deg, ...
                intervalClearanceLowerBound_deg);
            continue;
        end
        intervalDuration_s = intervalEnd_s - intervalStart_s;
        if intervalDuration_s <= options.CollisionMinimumTimeStep_s
            resolved = false;
            collisionFree = false;
            unresolvedCount = unresolvedCount + 1;
            return;
        end
        stackStart_s = [stackStart_s; intervalStart_s; intervalMid_s]; ...
            %#ok<AGROW>
        stackEnd_s = [stackEnd_s; intervalMid_s; intervalEnd_s]; ...
            %#ok<AGROW>
    end
end
end
function reached = internalDeadlineReached(options)
% PURPOSE
%   - Enforce the planner deadline when validation runs inside planning.
reached = false;
if isfield(options, "InternalPlanningTimer") && ...
        isfield(options, "InternalPlanningDeadline_s")
    reached = toc(options.InternalPlanningTimer) >= ...
        options.InternalPlanningDeadline_s;
end
end
function peak = maximumAbsolute(values)
% PURPOSE
%   - Return per-axis sampled peaks with stable NaNs for empty histories.
if isempty(values)
    peak = [NaN NaN];
else
    peak = max(abs(values), [], 1);
end
end
function validation = emptyValidation()
% PURPOSE
%   - Define the stable public validation schema for unavailable checks.
validation = struct( ...
    "Passed", false, "Message", "No trajectory was validated.", ...
    "HistorySizesMatch", false, "TimeIsFinite", false, ...
    "TimeIsStrictlyIncreasing", false, "HistoryIsFinite", false, ...
    "InitialStateMatched", false, "TerminalStateMatched", false, ...
    "GoalTimeSatisfied", false, "PolynomialSchemaValid", false, ...
    "PolynomialInitialTimeMatched", false, ...
    "PolynomialTimeBaseConsistent", false, ...
    "PolynomialSegmentContinuity", false, ...
    "PolynomialEndpointStatesMatched", false, ...
    "PolynomialHistoryConsistent", false, ...
    "MaximumSegmentContinuityResidual", NaN, ...
    "MaximumPolynomialHistoryResidual", NaN, ...
    "PositionWithinLimits", false, "VelocityWithinLimits", false, ...
    "AccelerationWithinLimits", false, "JerkWithinLimits", false, ...
    "DynamicsConsistent", false, "MaximumDynamicsResidual", NaN, ...
    "CollisionFree", false, "CollisionResolved", false, ...
    "SeedCorridorCertified", false, "MinimumClearance_deg", NaN, ...
    "CollisionCheckCount", 0, "UnresolvedIntervalCount", 0, ...
    "DeadlineReached", false, ...
    "SafetyMarginPolicySatisfied", false, ...
    "AzimuthWrapPolicySatisfied", false, ...
    "PeakVelocity_deg_s", [NaN NaN], ...
    "PeakAcceleration_deg_s2", [NaN NaN], ...
    "PeakJerk_deg_s3", [NaN NaN], "Issues", strings(0, 1));
end
