function validation = validatePreparedTrajectory( ...
        trajectory, obstacles, initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   validation = validatePreparedTrajectory( ...
%       trajectory, obstacles, initialState, goalState, limits, options)
% PURPOSE
%   Check the complete motion using already prepared obstacle histories.
% INPUTS
%   trajectory and normalized planning inputs; obstacles must be prepared.
% OUTPUTS
%   validation: endpoint, continuous constraint, collision, and timing checks.
% UNITS
%   Positions are degrees; time is seconds; derivatives retain physical units.

%% Section 1: Evaluate Prepared Inputs
if nargin == 0
    validation = createEmptyValidation();
    return;
end
validationTimer = tic;
hasMovingGoal = isfield(goalState, "targetTime_s") && ...
    ~isempty(goalState.targetTime_s);
if options.AllowAzimuthWrapping && (~isempty(obstacles) || hasMovingGoal)
    error("validateTrajectory:UnsupportedWrappedGeometry", ...
        "Wrapped validation is supported only for obstacle-free " + ...
        "fixed-position goals.");
end
[time_s, position_deg, velocity_deg_s, acceleration_deg_s2, ...
    jerk_deg_s3, historySizesMatch, timeIsFinite, ...
    timeIsStrictlyIncreasing, historyIsFinite] = ...
    readAndCheckMotionHistory(trajectory);

%% Section 2: Validate Endpoints And Continuous Polynomial Bounds

stateTolerance = max(10 * options.ConstraintTolerance, 1e-7);
[initialStateMatched, terminalStateMatched, goalTimeSatisfied] = ...
    checkEndpointStates(time_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, historyIsFinite, timeIsFinite, initialState, ...
    goalState, options, stateTolerance);
[continuousBounds, dynamics, polynomialChecks] = ...
        obstacleAvoidance.validation.validatePolynomialTrajectory( ...
    trajectory.Polynomial, time_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, jerk_deg_s3, initialState, goalState, limits, ...
    options, stateTolerance, ...
    @obstacleAvoidance.validation.certifyPolynomialRange);

%% Section 3: Certify Continuous Collision Freedom

collisionTimer = tic;
[collisionFree, collisionResolved, seedCorridorCertified, ...
    planeCertificateCertified, minimumClearance_deg, ...
    collisionCheckCount, unresolvedIntervalCount, certificateRejectionReason] = ...
    obstacleAvoidance.validation.checkObstacleClearance( ...
    trajectory, obstacles, limits, options, ...
    timeIsStrictlyIncreasing && historyIsFinite && continuousBounds.Valid);
collisionCheckingElapsedTime_s = toc(collisionTimer);
safetyMarginPolicySatisfied = safetyMarginProvenanceSatisfied(obstacles);
azimuthWrapPolicySatisfied = options.AllowAzimuthWrapping || ...
    continuousBounds.PositionWithinLimits;

%% Section 4: Assemble The Stable Validation Record

checkNames = ["history shape", "finite increasing time", ...
    "finite histories", "initial state", "terminal state", "goal time", ...
    "polynomial format", "polynomial initial time", ...
    "polynomial time base", "polynomial segment continuity", ...
    "polynomial endpoint states", "polynomial sampled histories", ...
    "continuous limits", "polynomial dynamics", "collision freedom", ...
    "collision resolution", "safety-margin provenance", ...
    "azimuth-wrap policy"];
checkValues = [historySizesMatch, timeIsStrictlyIncreasing, ...
    historyIsFinite, initialStateMatched, terminalStateMatched, ...
    goalTimeSatisfied, polynomialChecks.FormatValid, ...
    polynomialChecks.InitialTimeMatched, ...
    polynomialChecks.TimeBaseConsistent, ...
    polynomialChecks.SegmentContinuity, ...
    polynomialChecks.EndpointStatesMatched, ...
    polynomialChecks.HistoryConsistent, continuousBounds.Valid, ...
    dynamics.Consistent, collisionFree, collisionResolved, ...
    safetyMarginPolicySatisfied, azimuthWrapPolicySatisfied];
passed = all(checkValues);
issues = checkNames(~checkValues).';
if passed
    message = "Independent continuous validation passed.";
else
    message = "Independent validation failed: " + ...
        strjoin(issues, ", ") + ".";
end
values = {passed, message, historySizesMatch, timeIsFinite, ...
    timeIsStrictlyIncreasing, historyIsFinite, initialStateMatched, ...
    terminalStateMatched, goalTimeSatisfied, polynomialChecks.FormatValid, ...
    polynomialChecks.InitialTimeMatched, polynomialChecks.TimeBaseConsistent, ...
    polynomialChecks.SegmentContinuity, ...
    polynomialChecks.EndpointStatesMatched, ...
    polynomialChecks.HistoryConsistent, ...
    polynomialChecks.MaximumSegmentContinuityResidual, ...
    polynomialChecks.MaximumHistoryResidual, ...
    continuousBounds.PositionWithinLimits, ...
    continuousBounds.VelocityWithinLimits, ...
    continuousBounds.AccelerationWithinLimits, ...
    continuousBounds.JerkWithinLimits, dynamics.Consistent, ...
    dynamics.MaximumResidual, collisionFree, collisionResolved, ...
    seedCorridorCertified, planeCertificateCertified, minimumClearance_deg, ...
    collisionCheckCount, unresolvedIntervalCount, ...
    safetyMarginPolicySatisfied, azimuthWrapPolicySatisfied, ...
    maximumAbsolute(velocity_deg_s), maximumAbsolute(acceleration_deg_s2), ...
    maximumAbsolute(jerk_deg_s3), issues, collisionCheckingElapsedTime_s, ...
    toc(validationTimer)};
validation = createValidationRecord(values);
validation.CertificateRejectionReason = certificateRejectionReason;
end

%% Section 5: Local Functions

function [time_s, position_deg, velocity_deg_s, acceleration_deg_s2, ...
        jerk_deg_s3, historySizesMatch, timeIsFinite, ...
        timeIsStrictlyIncreasing, historyIsFinite] = ...
        readAndCheckMotionHistory(trajectory)
% Normalize sampled histories and check their shared shape and finiteness.
requiredFields = {'time_s', 'position_deg', 'velocity_deg_s', ...
    'acceleration_deg_s2', 'jerk_deg_s3', 'Polynomial'};
if ~isstruct(trajectory) || ~isscalar(trajectory) || ...
        ~all(isfield(trajectory, requiredFields))
    error("validateTrajectory:InvalidTrajectory", ...
        "trajectory must contain sampled histories and Polynomial data.");
end
time_s = double(trajectory.time_s(:));
position_deg = double(trajectory.position_deg);
velocity_deg_s = double(trajectory.velocity_deg_s);
acceleration_deg_s2 = double(trajectory.acceleration_deg_s2);
jerk_deg_s3 = double(trajectory.jerk_deg_s3);
sampleCount = numel(time_s);
historySizesMatch = isequal(size(position_deg), [sampleCount 2]) && ...
    isequal(size(velocity_deg_s), [sampleCount 2]) && ...
    isequal(size(acceleration_deg_s2), [sampleCount 2]) && ...
    isequal(size(jerk_deg_s3), [sampleCount 2]);
timeIsFinite = ~isempty(time_s) && all(isfinite(time_s));
timeIsStrictlyIncreasing = timeIsFinite && all(diff(time_s) > 0);
historyIsFinite = sampleCount > 0 && historySizesMatch && ...
    all(isfinite(position_deg), "all") && ...
    all(isfinite(velocity_deg_s), "all") && ...
    all(isfinite(acceleration_deg_s2), "all") && ...
    all(isfinite(jerk_deg_s3), "all");
end

function [initialStateMatched, terminalStateMatched, goalTimeSatisfied] = ...
        checkEndpointStates(time_s, position_deg, velocity_deg_s, ...
        acceleration_deg_s2, historyIsFinite, timeIsFinite, initialState, ...
        goalState, options, stateTolerance)
% Compare sampled endpoints with the requested states and arrival policy.
initialStateMatched = historyIsFinite && max(abs([ ...
    position_deg(1, :) - initialState.position_deg, ...
    velocity_deg_s(1, :) - initialState.velocity_deg_s, ...
    acceleration_deg_s2(1, :) - initialState.acceleration_deg_s2])) <= ...
    stateTolerance;
if timeIsFinite
    goalPosition_deg = obstacleAvoidance.input.goalPositionAtTime( ...
        goalState, time_s(end));
else
    goalPosition_deg = [NaN NaN];
end
terminalStateMatched = historyIsFinite && max(abs([ ...
    position_deg(end, :) - goalPosition_deg, ...
    velocity_deg_s(end, :) - goalState.velocity_deg_s, ...
    acceleration_deg_s2(end, :) - goalState.acceleration_deg_s2])) <= ...
    stateTolerance;
if options.GoalTimeMode == "fixedArrival"
    goalTimeSatisfied = timeIsFinite && ...
        abs(time_s(end) - goalState.time_s) <= stateTolerance;
else
    goalTimeSatisfied = timeIsFinite && ...
        time_s(end) <= goalState.time_s + stateTolerance && ...
        time_s(end) > initialState.time_s;
end
end

function satisfied = safetyMarginProvenanceSatisfied(obstacles)
% Require original geometry and a finite, nonnegative safety margin.
if isempty(obstacles)
    satisfied = true;
    return;
end
hasFields = all(isfield(obstacles, ...
    {'originalAz_deg', 'originalEl_deg', 'safetyMargin_deg'}));
satisfied = hasFields && all(isfinite([obstacles.safetyMargin_deg])) && ...
    all([obstacles.safetyMargin_deg] >= 0);
end

function peak = maximumAbsolute(values)
% Return per-coordinate sampled peaks or documented NaN values.
if isempty(values)
    peak = [NaN NaN];
else
    peak = max(abs(values), [], 1);
end
end

function validation = createEmptyValidation()
% Initialize all validation fields.
values = {false, "No trajectory was validated.", false, false, false, ...
    false, false, false, false, false, false, false, false, false, false, ...
    NaN, NaN, false, false, false, false, false, NaN, false, false, false, ...
    false, NaN, 0, 0, false, false, [NaN NaN], [NaN NaN], [NaN NaN], ...
    strings(0, 1), 0, 0};
validation = createValidationRecord(values);
end

function validation = createValidationRecord(values)
% Assemble validation results in public field order.
names = ["Passed", "Message", "HistorySizesMatch", "TimeIsFinite", ...
    "TimeIsStrictlyIncreasing", "HistoryIsFinite", "InitialStateMatched", ...
    "TerminalStateMatched", "GoalTimeSatisfied", "PolynomialFormatValid", ...
    "PolynomialInitialTimeMatched", "PolynomialTimeBaseConsistent", ...
    "PolynomialSegmentContinuity", "PolynomialEndpointStatesMatched", ...
    "PolynomialHistoryConsistent", "MaximumSegmentContinuityResidual", ...
    "MaximumPolynomialHistoryResidual", "PositionWithinLimits", ...
    "VelocityWithinLimits", "AccelerationWithinLimits", "JerkWithinLimits", ...
    "DynamicsConsistent", "MaximumDynamicsResidual", "CollisionFree", ...
    "CollisionResolved", "SeedCorridorCertified", ...
    "PlaneCertificateCertified", "MinimumClearance_deg", ...
    "CollisionCheckCount", "UnresolvedIntervalCount", ...
    "SafetyMarginPolicySatisfied", "AzimuthWrapPolicySatisfied", ...
    "PeakVelocity_deg_s", "PeakAcceleration_deg_s2", "PeakJerk_deg_s3", ...
    "Issues", "CollisionCheckingElapsedTime_s", "ElapsedTime_s"];
validation = cell2struct(values, cellstr(names), 2);
validation.CertificateRejectionReason = "";
end
