function tests = testMinimalAzElWorkflow
%% Section 0: Header & Readme
% SYNTAX
%   tests = testMinimalAzElWorkflow
%**************************************************************************
% PURPOSE
%   - Verify the minimal construct, reduce-search, plan, validate, and plot
%     workflow with finite and unlimited jerk.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - tests (MATLAB function-test array)
%       Deterministic tests for the retained public workflow.
%**************************************************************************
% UNITS
%   - Position is degrees and time is seconds.
%**************************************************************************

%% Section 1: Create The Function-Test Suite

root = fileparts(fileparts(mfilename("fullpath")));
addpath(root, fullfile(root, "examples"));
tests = functiontests(localfunctions);
end

%% Section 2: Local Test Cases

function testDenseObstacleIsReducedOnlyForSearch(testCase)
result = exampleAzElPlanning(struct("FigureVisible", "off", ...
    "PlotOutputs", false, "EnableJerkConstraint", true));
testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
diagnostics = result.candidateReductionDiagnostics;
inputVertexCount = sum([diagnostics.InputVertexCount]);
selectedCandidateCount = sum([diagnostics.SelectedCandidateCount]);
testCase.verifyGreaterThan(inputVertexCount, 1000);
testCase.verifyLessThan(selectedCandidateCount, 0.01 * inputVertexCount);
blocked = queryAzElTimedPathCollision(result.obstacleField, ...
    result.timedSlopePath.time_s, result.timedSlopePath.position_deg);
testCase.verifyFalse(any(blocked));
testCase.verifyTrue(result.timedSlopePath.ConstraintDiagnostics. ...
    FiniteJerkCertified);
end

function testUnlimitedJerkIsReportedHonestly(testCase)
result = exampleAzElPlanning(struct("FigureVisible", "off", ...
    "PlotOutputs", false, "EnableJerkConstraint", false));
testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
testCase.verifyFalse(result.timedSlopePath.ConstraintDiagnostics. ...
    FiniteJerkCertified);
testCase.verifyTrue(all(isinf(result.limits.maxJerk_deg_s3)));
testCase.verifyTrue(all(isnan(result.timedSlopePath. ...
    ConstraintDiagnostics.PeakJerk_deg_s3)));
end

function testUnlimitedJerkUShapeDoesNotInsertAccelerationZeros(testCase)
result = exampleUShapedAzElTimeSpace(struct("FigureVisible", "off", ...
    "PlotOutputs", false, "EnableJerkConstraint", false, ...
    "Verbose", false));
testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.ExampleValidation.Passed, ...
    result.ExampleValidation.Message);
timedPath = result.timedSlopePath;
tangentialAcceleration_deg_s2 = ...
    timedPath.SampleTangentialAcceleration_deg_s2;
artificialZero = abs(tangentialAcceleration_deg_s2(2:end - 1)) < 1e-12 & ...
    abs(tangentialAcceleration_deg_s2(1:end - 2)) > 1e-4 & ...
    abs(tangentialAcceleration_deg_s2(3:end)) > 1e-4;
testCase.verifyEqual(nnz(artificialZero), 0, ...
    "Spatial profile joins must not inject one-sample acceleration zeros.");
for profileIndex = 1:numel(timedPath.SegmentProfiles)
    profile = timedPath.SegmentProfiles(profileIndex);
    testCase.verifyEqual(profile.PhaseStartAcceleration_deg_s2(1), ...
        profile.TangentialAcceleration_deg_s2, "AbsTol", 1e-12);
end
testCase.verifyLessThan(timedPath.MinimumMotionDuration_s, 30);
testCase.verifyTrue(all(isnan(timedPath.jerk_deg_s3), "all"));
blocked = queryAzElTimedPathCollision(result.obstacleField, ...
    timedPath.time_s, timedPath.position_deg);
testCase.verifyFalse(any(blocked));
jerkConstrainedResult = exampleUShapedAzElTimeSpace(struct( ...
    "FigureVisible", "off", "PlotOutputs", false, ...
    "EnableJerkConstraint", true, "Verbose", false));
testCase.verifyTrue(jerkConstrainedResult.Success, ...
    jerkConstrainedResult.Message);
testCase.verifyEqual(jerkConstrainedResult.limits.maxJerk_deg_s3, ...
    [2.5 2.5]);
testCase.verifyTrue(jerkConstrainedResult.timedSlopePath. ...
    ConstraintDiagnostics.FiniteJerkCertified);
testCase.verifyGreaterThan( ...
    jerkConstrainedResult.timedSlopePath.MinimumMotionDuration_s, ...
    timedPath.MinimumMotionDuration_s);
end

function testOpeningUWaitsAndBeatsClosedDetour(testCase)
result = exampleOpeningUShapedAzElTimeSpace(struct( ...
    "FigureVisible", "off", ...
    "PlotOutputs", false, ...
    "EnableJerkConstraint", true, ...
    "UseParallel", "off", ...
    "Verbose", false));

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.ExampleValidation.Passed, ...
    result.ExampleValidation.Message);
testCase.verifyTrue(result.OpeningValidation.Passed, ...
    result.OpeningValidation.Message);
testCase.verifyTrue(result.OpeningValidation.DelayedDeparture);
testCase.verifyTrue(result.OpeningValidation.SelectedDirectGeometry);
testCase.verifyTrue(result.OpeningValidation.CrossedOpenGap);
testCase.verifyTrue( ...
    result.OpeningValidation.OpeningWasFasterThanDetour);
testCase.verifyGreaterThan(result.OpeningValidation.TimeSaved_s, 0);
testCase.verifyEqual(result.timedSlopePath.DepartureCandidateTime_s, ...
    result.timedSlopePath.MotionStartTime_s, "AbsTol", 1e-12);

holdMask = result.timedSlopePath.time_s <= ...
    result.timedSlopePath.MotionStartTime_s;
heldPosition_deg = result.timedSlopePath.position_deg(holdMask, :);
testCase.verifyEqual(heldPosition_deg, repmat( ...
    result.initialState.position_deg, size(heldPosition_deg, 1), 1), ...
    "AbsTol", 1e-12);
blocked = queryAzElTimedPathCollision(result.obstacleField, ...
    result.timedSlopePath.time_s, result.timedSlopePath.position_deg, ...
    struct("TimePaddingSamples", 0, "BoundaryIsOccupied", false));
testCase.verifyFalse(any(blocked));
end

function testTranslatedObstacleUsesGeneralTimeGrid(testCase)
initialAzimuth_deg = [-1; 1; 1; -1];
initialElevation_deg = [-12; -12; 12; 12];
clearedElevation_deg = initialElevation_deg + 15;
obstacle = makeAzElObstacleData( ...
    "translating rectangle", [0; 4; 30], ...
    {initialAzimuth_deg; initialAzimuth_deg; initialAzimuth_deg}, ...
    {initialElevation_deg; clearedElevation_deg; ...
    clearedElevation_deg}, 0.1);

initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-5 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 30, ...
    "position_deg", [5 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [Inf Inf]);
options = struct( ...
    "CollisionTimePaddingSamples", 0, ...
    "UseParallel", "off");

result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
testCase.verifyEqual( ...
    result.SearchDiagnostics.DepartureTimeCandidates_s, [0; 4; 30]);
testCase.verifyEqual(size(result.selectedRoute_deg, 1), 2);
testCase.verifyTrue(queryAzElTimeObstacle( ...
    result.obstacleField, 0, 0, 0));
testCase.verifyFalse(queryAzElTimeObstacle( ...
    result.obstacleField, 0, 0, 4));
testCase.verifyGreaterThan( ...
    result.timedSlopePath.DepartureCandidateTime_s, 0);
testCase.verifyLessThan( ...
    result.timedSlopePath.DepartureCandidateTime_s, 4);
blocked = queryAzElTimedPathCollision( ...
    result.obstacleField, result.timedSlopePath.time_s, ...
    result.timedSlopePath.position_deg, struct( ...
    "TimePaddingSamples", 0, "BoundaryIsOccupied", false));
testCase.verifyFalse(any(blocked));
end

function testHybridCollisionScreenStillRequiresContinuousValidation(testCase)
defaults = planAzElMotion();
testCase.verifyEqual(defaults.CollisionValidationMode, "hybrid");
testCase.verifyEqual(defaults.MaximumVisibilitySnapshotsPerObstacle, 10);
testCase.verifyEqual(defaults.MaximumCollisionPrefilterSamples, 80);
testCase.verifyEqual(defaults.MinimumContinuouslyValidatedCandidates, 2);
testCase.verifyFalse(defaults.RefineVisibilityAfterSuccess);
testCase.verifyEqual(defaults.VisibilitySuccessRefinementMode, ...
    "connectivity");
testCase.verifyEqual(defaults.VisibilityGraphCostChangeThreshold, 0.05);

obstacle = makeAzElObstacleData( ...
    "blocking rectangle", [0; 20], ...
    {[-0.25; 0.25; 0.25; -0.25]; ...
    [-0.25; 0.25; 0.25; -0.25]}, ...
    {[-1; -1; 1; 1]; [-1; -1; 1; 1]}, 0.05);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-1 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 20, ...
    "position_deg", [1 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [Inf Inf]);
options = struct( ...
    "CollisionValidationMode", "hybrid", ...
    "MaximumCollisionPrefilterSamples", 2, ...
    "UseParallel", "off");

result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
testCase.verifyEqual(result.Options.CollisionValidationMode, "hybrid");
testCase.verifyEqual( ...
    result.Options.MaximumCollisionPrefilterSamples, 2);
testCase.verifyTrue(result.SearchDiagnostics. ...
    ContinuousCollisionRequiredForSuccess);
testCase.verifyTrue(result.candidateDiagnostics. ...
    CollisionPrefilterApplied(1));
testCase.verifyTrue(result.candidateDiagnostics. ...
    CollisionPrefilterPassed(1));
testCase.verifyTrue(result.candidateDiagnostics. ...
    ContinuousCollisionChecked(1));
testCase.verifyEqual(result.candidateDiagnostics. ...
    CollisionValidationStatus(1), "continuousCollision");
testCase.verifyTrue(result.candidateDiagnostics. ...
    ContinuousCollisionChecked(result.selectedCandidateIndex));
testCase.verifyEqual(result.candidateDiagnostics. ...
    CollisionValidationStatus(result.selectedCandidateIndex), ...
    "continuousClear");
blocked = queryAzElTimedPathCollision( ...
    result.obstacleField, result.timedSlopePath.time_s, ...
    result.timedSlopePath.position_deg);
testCase.verifyFalse(any(blocked));

continuousResult = planAzElMotion( ...
    obstacle, initialState, goalState, limits, struct( ...
    "CollisionValidationMode", "continuous", ...
    "UseParallel", "off"));
testCase.verifyTrue(continuousResult.Success, continuousResult.Message);
testCase.verifyFalse(any(continuousResult.candidateDiagnostics. ...
    CollisionPrefilterApplied));
testCase.verifyTrue(continuousResult.candidateDiagnostics. ...
    ContinuousCollisionChecked(1));
end

function testVisibilityRefinementUsesGraphChangeAndRecoversFailure(testCase)
sampleTime_s = [0; 2; 4; 6; 8];
wallAzimuth_deg = repmat({[-0.4; 0.4; 0.4; -0.4]}, 5, 1);
blockingElevation_deg = [-8; -8; 8; 8];
clearElevation_deg = [10; 10; 26; 26];
wallElevation_deg = {blockingElevation_deg; blockingElevation_deg; ...
    clearElevation_deg; clearElevation_deg; blockingElevation_deg};
obstacle = makeAzElObstacleData( ...
    "temporary wall", sampleTime_s, wallAzimuth_deg, ...
    wallElevation_deg, 0.05);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-2 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 8, ...
    "position_deg", [2 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [2 2], ...
    "maxJerk_deg_s3", [Inf Inf]);

recoveredResult = planAzElMotion( ...
    obstacle, initialState, goalState, limits, struct( ...
    "MaximumVisibilitySnapshotsPerObstacle", 2, ...
    "RefineVisibilityAfterSuccess", false, ...
    "CollisionTimePaddingSamples", 0, ...
    "UseParallel", "off"));

history = recoveredResult.SearchDiagnostics. ...
    VisibilityRefinementHistory;
testCase.verifyTrue(recoveredResult.Success, recoveredResult.Message);
testCase.verifyGreaterThan(numel(history), 1);
testCase.verifyFalse(history(1).Success);
testCase.verifyTrue(history(end).Success);
testCase.verifyTrue(any( ...
    [history.Trigger] == "automaticAfterFailure"));
testCase.verifyGreaterThan( ...
    history(end).MaximumRetainedSnapshotCount, ...
    history(1).MaximumRetainedSnapshotCount);
testCase.verifyTrue(recoveredResult.SearchDiagnostics. ...
    AutomaticFailureRefinementPerformed);
blocked = queryAzElTimedPathCollision( ...
    recoveredResult.obstacleField, recoveredResult.timedSlopePath.time_s, ...
    recoveredResult.timedSlopePath.position_deg, struct( ...
    "TimePaddingSamples", 0, "BoundaryIsOccupied", false));
testCase.verifyFalse(any(blocked));

monotoneElevation_deg = {blockingElevation_deg; ...
    blockingElevation_deg + 4; blockingElevation_deg + 8; ...
    clearElevation_deg; clearElevation_deg};
changingObstacle = makeAzElObstacleData( ...
    "opening wall", sampleTime_s, wallAzimuth_deg, ...
    monotoneElevation_deg, 0.05);
optionalGoalState = goalState;
optionalGoalState.time_s = 20;
optionalResult = planAzElMotion( ...
    changingObstacle, initialState, optionalGoalState, limits, struct( ...
    "MaximumVisibilitySnapshotsPerObstacle", 2, ...
    "RefineVisibilityAfterSuccess", true, ...
    "VisibilitySuccessRefinementMode", "connectivity", ...
    "MaximumVisibilityRefinementPasses", 1, ...
    "CollisionTimePaddingSamples", 0, ...
    "UseParallel", "off"));

optionalHistory = optionalResult.SearchDiagnostics. ...
    VisibilityRefinementHistory;
testCase.verifyTrue(optionalResult.Success, optionalResult.Message);
testCase.verifyEqual(numel(optionalHistory), 2);
testCase.verifyGreaterThan( ...
    optionalHistory(1).ConnectivityChangeIntervalCount, 0);
testCase.verifyEqual(optionalHistory(2).Trigger, ...
    "optionalAfterConnectivityChange");
testCase.verifyTrue(optionalResult.SearchDiagnostics. ...
    OptionalSuccessRefinementPerformed);
end

function testPlotConsumesResultWithoutReplanning(testCase)
result = exampleAzElPlanning(struct("FigureVisible", "off", ...
    "PlotOutputs", false));
handles = plotAzElMotion(result, struct("FigureVisible", "off", ...
    "FrameStride", 1000, "Pause_s", 0));
cleanup = onCleanup(@() close([handles.WorkspaceFigure ...
    handles.VisibilityGraphs.Figure handles.KinematicsFigure ...
    handles.Animation.Figure]));
testCase.verifyTrue(isgraphics(handles.WorkspaceFigure));
testCase.verifyTrue(isgraphics(handles.VisibilityGraphs.Figure));
testCase.verifyTrue(isgraphics(handles.VisibilityGraphs.OverviewAxes));
testCase.verifyTrue(isgraphics(handles.VisibilityGraphs.SnapshotAxes));
testCase.verifyTrue(isgraphics(handles.KinematicsFigure));
testCase.verifyEqual(numel(handles.KinematicsAxes), 4);
testCase.verifyTrue(isgraphics(handles.Animation.Figure));
testCase.verifyTrue(isgraphics(handles.Animation.Axes3D));
testCase.verifyTrue(isgraphics(handles.Animation.Axes2D));

graphs = result.SearchDiagnostics.VisibilityGraphs;
testCase.verifyGreaterThan(numel(graphs), 1);
blockedTestWasRetained = false;
for graphIndex = 1:numel(graphs)
    graph = graphs(graphIndex);
    blockedTestWasRetained = blockedTestWasRetained || ...
        any(graph.VisibilityBlockedMask, "all");
    testCase.verifyEqual(graph.VisibilityTestedMask, ...
        graph.VisibilityTestedMask.');
    testCase.verifyEqual(graph.VisibilityBlockedMask, ...
        graph.VisibilityBlockedMask.');
    testCase.verifyFalse(any(graph.VisibilityBlockedMask & ...
        ~graph.VisibilityTestedMask, "all"));
end
testCase.verifyTrue(blockedTestWasRetained);

requestedTime_s = mean([graphs.Time_s]);
set(handles.VisibilityGraphs.TimeEdit, ...
    "String", sprintf("%.12g", requestedTime_s));
callback = get(handles.VisibilityGraphs.GoButton, "Callback");
callback(handles.VisibilityGraphs.GoButton, []);
[~, expectedSnapshotIndex] = min(abs([graphs.Time_s] - requestedTime_s));
testCase.verifyEqual(getappdata(handles.VisibilityGraphs.Figure, ...
    "SelectedSnapshotIndex"), expectedSnapshotIndex);
end

function testMovingPointHistoryUsesSameObstacleConstructor(testCase)
squareAzimuth_deg = {[-2; 0; 0; -2], [1; 3; 3; 1]};
squareElevation_deg = {[-1; -1; 1; 1], [-1; -1; 1; 1]};
obstacle = makeAzElObstacleData("moving obstacle", [0; 20], ...
    squareAzimuth_deg, squareElevation_deg, 0);
field = buildAzElTimeObstacleField(obstacle);
testCase.verifyTrue(queryAzElTimeObstacle(field, -1, 0, 0));
testCase.verifyTrue(queryAzElTimeObstacle(field, 2, 0, 20));
testCase.verifyFalse(queryAzElTimeObstacle(field, -1, 0, 20));
initialState = struct("time_s", 0, "position_deg", [-4 3]);
goalState = struct("time_s", 20, "position_deg", [4 3]);
limits = struct("maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], "maxJerk_deg_s3", [Inf Inf]);
result = planAzElMotion(obstacle, initialState, goalState, limits);
testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
end

function testContinuousMovingObstacleCollisionIsNotSliceAliased(testCase)
leftSquareAzimuth_deg = [-3; -1; -1; -3];
rightSquareAzimuth_deg = [1; 3; 3; 1];
squareElevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData( ...
    "crossing square", [0; 10], ...
    {leftSquareAzimuth_deg; rightSquareAzimuth_deg}, ...
    {squareElevation_deg; squareElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);

testCase.verifyTrue(queryAzElTimeObstacle( ...
    obstacleField, 0, 0, 5));
fullCrossing = queryAzElTimedPathCollision( ...
    obstacleField, [0; 10], [0 0; 0 0], struct( ...
    "TimePaddingSamples", 0));
earlyClear = queryAzElTimedPathCollision( ...
    obstacleField, [0; 2], [0 0; 0 0], struct( ...
    "TimePaddingSamples", 0));
testCase.verifyTrue(any(fullCrossing));
testCase.verifyFalse(any(earlyClear));
end

function testAsynchronousObstacleTimesShareVisibilityGraph(testCase)
firstObstacle = makeAzElObstacleData( ...
    "first", [0; 10], [-2; -1; -1; -2], ...
    [-1; -1; 1; 1], 0);
secondObstacle = makeAzElObstacleData( ...
    "second", [5; 15], [1; 2; 2; 1], ...
    [-1; -1; 1; 1], 0);
obstacleField = buildAzElTimeObstacleField( ...
    {firstObstacle, secondObstacle});
initialState = struct("time_s", 0, "position_deg", [-4 3]);
goalState = struct("time_s", 15, "position_deg", [4 3]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct("UseParallel", "off"));
testCase.verifyEqual([search.VisibilityGraphs.Time_s], [0 5 10 15]);
for graphIndex = [2 3]
    obstacleIndex = unique(search.VisibilityGraphs(graphIndex). ...
        NodeObstacleIndex(3:end));
    testCase.verifyEqual(obstacleIndex(:), [1; 2]);
end
end

function testVisibilitySnapshotsAreUncappedByDefault(testCase)
sampleTime_s = (0:20).';
squareAzimuth_deg = repmat({[-1; 1; 1; -1]}, numel(sampleTime_s), 1);
squareElevation_deg = repmat({[-1; -1; 1; 1]}, ...
    numel(sampleTime_s), 1);
obstacle = makeAzElObstacleData( ...
    "sampled square", sampleTime_s, ...
    squareAzimuth_deg, squareElevation_deg, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-3 2]);
goalState = struct("time_s", 20, "position_deg", [3 2]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct("UseParallel", "off"));
testCase.verifyEqual(numel(search.VisibilityGraphs), ...
    numel(sampleTime_s));
testCase.verifyEqual(search.Options.MaximumSnapshotsPerObstacle, Inf);
end

function testInfeasibleEndpointSpeedReturnsStableFailure(testCase)
initialState = struct( ...
    "time_s", 0, "position_deg", [0 0], ...
    "velocity_deg_s", [3 0]);
goalState = struct( ...
    "time_s", 10, "position_deg", [5 0], ...
    "velocity_deg_s", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2 2]);

result = planAzElMotion([], initialState, goalState, limits);
testCase.verifyFalse(result.Success);
testCase.verifyEqual(result.TerminationReason, "noFeasibleCandidate");
testCase.verifyTrue(contains(result.candidateDiagnostics.Message(1), ...
    "endpoint speed", "IgnoreCase", true));
end

function testParallelPolygonReductionMatchesSerial(testCase)
squareAzimuth_deg = {[-2; 0; 0; -2], [-1; 1; 1; -1], ...
    [1; 3; 3; 1]};
squareElevation_deg = {[-1; -1; 1; 1], [-1; -1; 1; 1], ...
    [-1; -1; 1; 1]};
obstacle = makeAzElObstacleData( ...
    "moving obstacle", [0; 10; 20], squareAzimuth_deg, ...
    squareElevation_deg, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-4 3]);
goalState = struct("time_s", 20, "position_deg", [4 3]);

serialSearch = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, ...
    struct("UseParallel", "off"));
parallelSearch = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, ...
    struct("UseParallel", "on"));

testCase.verifyEqual(serialSearch.ParallelExecution.RequestedMode, "off");
testCase.verifyEqual(parallelSearch.ParallelExecution.RequestedMode, "on");
testCase.verifyGreaterThan(parallelSearch.ParallelExecution.TaskCount, 1);
testCase.verifyEqual(numel(parallelSearch.VisibilityGraphs), ...
    numel(serialSearch.VisibilityGraphs));
testCase.verifyEqual(parallelSearch.CandidatePointsAzElTime, ...
    serialSearch.CandidatePointsAzElTime, "AbsTol", 1e-12);

for snapshotIndex = 1:numel(serialSearch.VisibilityGraphs)
    serialGraph = serialSearch.VisibilityGraphs(snapshotIndex);
    parallelGraph = parallelSearch.VisibilityGraphs(snapshotIndex);
    testCase.verifyEqual(parallelGraph.Success, serialGraph.Success);
    testCase.verifyEqual(parallelGraph.PathPosition_deg, ...
        serialGraph.PathPosition_deg, "AbsTol", 1e-12);
    testCase.verifyEqual(parallelGraph.PathCost_deg, ...
        serialGraph.PathCost_deg, "AbsTol", 1e-12);
    testCase.verifyEqual(parallelGraph.CandidateActiveMask, ...
        serialGraph.CandidateActiveMask);
end
end

function testTwoVertexRegionsWarnAndAreRemoved(testCase)
validAzimuth_deg = [-2; 0; 0; -2];
validElevation_deg = [-1; -1; 1; 1];
twoVertexAzimuth_deg = [5; 6];
twoVertexElevation_deg = [0; 0];
azimuth_deg = [validAzimuth_deg; NaN; twoVertexAzimuth_deg];
elevation_deg = [validElevation_deg; NaN; twoVertexElevation_deg];

lastwarn("");
obstacle = makeAzElObstacleData( ...
    "mixed regions", [0; 10], azimuth_deg, elevation_deg, 0);
[warningMessage, warningIdentifier] = lastwarn;
testCase.verifyEqual(string(warningIdentifier), ...
    "normalizeAzElTimeObstacleData:RemovedTwoVertexRegions");
testCase.verifyTrue(contains(warningMessage, "two-vertex regions"));
testCase.verifyEqual(nnz(isfinite(obstacle.az_deg{1})), 4);
testCase.verifyEqual(nnz(isfinite(obstacle.originalAz_deg{1})), 4);

obstacleField = buildAzElTimeObstacleField(obstacle);
testCase.verifyTrue(queryAzElTimeObstacle(obstacleField, -1, 0, 5));
testCase.verifyFalse(queryAzElTimeObstacle(obstacleField, 5.5, 0, 5));

lastwarn("");
emptyObstacle = makeAzElObstacleData( ...
    "only two vertices", [0; 10], ...
    twoVertexAzimuth_deg, twoVertexElevation_deg, 0);
[~, warningIdentifier] = lastwarn;
testCase.verifyEqual(string(warningIdentifier), ...
    "normalizeAzElTimeObstacleData:RemovedTwoVertexRegions");
testCase.verifyEmpty(emptyObstacle.az_deg{1});
testCase.verifyEmpty(emptyObstacle.el_deg{1});
end

function testFourCirclesAccelerateDecelerateAndTouch(testCase)
result = exampleFourAcceleratingCircles(struct( ...
    "FigureVisible", "off", ...
    "PlotOutputs", false, ...
    "EnableJerkConstraint", true, ...
    "Verbose", false));

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.ExampleValidation.Passed, ...
    result.ExampleValidation.Message);
testCase.verifyTrue(result.CircleMotionValidation.Passed);
testCase.verifyEqual(numel(result.originalAzElData), 4);

centerAzimuth_deg = result.circleCenterAzimuth_deg;
centerElevation_deg = result.circleCenterElevation_deg;
diameter_deg = 2 * result.circleRadius_deg;
testCase.verifyEqual(diff(centerAzimuth_deg([1 2])), ...
    diameter_deg, "AbsTol", 1e-12);
testCase.verifyEqual(diff(centerAzimuth_deg([3 4])), ...
    diameter_deg, "AbsTol", 1e-12);

[~, midpointIndex] = min(abs(result.obstacleTime_s - ...
    0.5 * result.obstacleMotionDuration_s));
midpointStep_deg = hypot(diff(centerAzimuth_deg), ...
    diff(centerElevation_deg(midpointIndex, :)));
testCase.verifyEqual(midpointStep_deg, ...
    repmat(diameter_deg, 1, 3), "AbsTol", 1e-12);

[~, motionEndIndex] = min(abs(result.obstacleTime_s - ...
    result.obstacleMotionDuration_s));
endpointRows = [1 motionEndIndex];
testCase.verifyEqual(result.circleCenterVelocity_deg_s( ...
    endpointRows, :), zeros(2, 4), "AbsTol", 1e-12);
testCase.verifyEqual(result.circleCenterAcceleration_deg_s2( ...
    endpointRows, :), zeros(2, 4), "AbsTol", 1e-12);
testCase.verifyGreaterThan(max( ...
    result.circleCenterVelocity_deg_s(:, 1:2), [], "all"), 0);
testCase.verifyLessThan(min( ...
    result.circleCenterVelocity_deg_s(:, 3:4), [], "all"), 0);

collision = queryAzElTimedPathCollision(result.obstacleField, ...
    result.timedSlopePath.time_s, result.timedSlopePath.position_deg);
testCase.verifyFalse(any(collision));
testCase.verifyTrue(result.timedSlopePath.ConstraintDiagnostics. ...
    FiniteJerkCertified);
end

function testBlockedEndpointReturnsStableFailure(testCase)
azimuth_deg = [-1; 1; 1; -1];
elevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData("obstacle", [0; 20], ...
    azimuth_deg, elevation_deg, 0);
initialState = struct("time_s", 0, "position_deg", [0 0]);
goalState = struct("time_s", 20, "position_deg", [4 0]);
limits = struct("maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], "maxJerk_deg_s3", [2 2]);
result = planAzElMotion(obstacle, initialState, goalState, limits);
testCase.verifyFalse(result.Success);
testCase.verifyEqual(result.TerminationReason, "endpointBlocked");
testCase.verifyFalse(isempty(result.SearchDiagnostics));
handles = plotAzElMotion(result, struct("FigureVisible", "off"));
cleanup = onCleanup(@() close([handles.WorkspaceFigure ...
    handles.VisibilityGraphs.Figure handles.KinematicsFigure]));
testCase.verifyTrue(isgraphics(handles.WorkspaceFigure));
testCase.verifyTrue(isgraphics(handles.VisibilityGraphs.Figure));
end
