function tests = testOfflineSandboxDiagnosisBundle
%% Section 0: Header & Readme
% SYNTAX
%   tests = testOfflineSandboxDiagnosisBundle
%**************************************************************************
% PURPOSE
%   - Verify that the HTML sandbox creates a replayable, handle-free MATLAB
%     diagnosis bundle and exposes a request-matched download workflow.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - tests (matlab.unittest.FunctionTestCase array)
%       Focused tests for bundle construction and HTML/server integration.
%**************************************************************************
% UNITS
%   - Positions and polygon vertices use degrees. Time uses seconds.
%**************************************************************************

tests = functiontests(localfunctions);
end

function setupOnce(testCase)
% Add only the repository and offline-sandbox public-function folders.
repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(repositoryRoot, fullfile(repositoryRoot, "offlinesandbox"));
testCase.TestData.RepositoryRoot = repositoryRoot;
end

function testBundlePreservesExactResultAndRemovesCallback(testCase)
% Preserve replay data while excluding the trusted transport callback.
request = createSyntheticRequest();
plannerInputs = struct( ...
    "obstacles", struct.empty(0, 1), ...
    "initialState", request.initialState, ...
    "goalState", request.goalState, ...
    "limits", request.limits);
plannerOptions = request.options;
plannerOptions.CancellationCheckFcn = @() false;
result = struct( ...
    "Success", false, ...
    "Message", "No feasible path found.", ...
    "TerminationReason", "openSetExhausted", ...
    "Inputs", plannerInputs, ...
    "Options", plannerOptions, ...
    "SearchDiagnostics", struct("ExpandedCount", 17));
validation = struct("Passed", false, "Message", "Expected failure.");

bundle = offlineSandbox.createDiagnosisBundle( ...
    request, result, validation);

verifyEqual(testCase, bundle.Format, ...
    "obstacleAvoidanceSandboxDiagnosis-v2");
verifyEqual(testCase, bundle.ExportRequest.RequestId, request.requestId);
verifyEqual(testCase, bundle.PlannerInputs, plannerInputs);
verifyEqual(testCase, bundle.Result.SearchDiagnostics.ExpandedCount, 17);
verifyEmpty(testCase, bundle.Result.Options.CancellationCheckFcn);
verifyEmpty(testCase, bundle.PlannerOptions.CancellationCheckFcn);
verifyEqual(testCase, bundle.Result.TerminationReason, ...
    "openSetExhausted");
verifyFalse(testCase, bundle.Result.Success);
end

function testPageAndServerExposeMatchedBundleDownload(testCase)
% Keep the user control and request-matched binary route wired together.
htmlPath = fullfile(testCase.TestData.RepositoryRoot, ...
    "offlinesandbox", "az_el_planner_sandbox.html");
serverPath = fullfile(testCase.TestData.RepositoryRoot, ...
    "offlinesandbox", "+offlineSandbox", "serveSandbox.m");
htmlText = string(fileread(htmlPath));
serverText = string(fileread(serverPath));

verifyTrue(testCase, contains(htmlText, 'id="downloadBundleButton"'));
verifyTrue(testCase, contains(htmlText, ...
    'fetch(`${state.serverOrigin}/bundle`'));
verifyTrue(testCase, contains(htmlText, ...
    'state.bundleRequestId = payload.requestId'));
verifyTrue(testCase, contains(serverText, 'path == "/bundle"'));
verifyTrue(testCase, contains(serverText, ...
    'cachedRequestId ~= requestId'));
verifyTrue(testCase, contains(serverText, ...
    '"application/vnd.matlab.mat-file"'));
end

function request = createSyntheticRequest()
% Create a complete browser request without invoking the planner.
request = struct( ...
    "schemaVersion", "offlineSandboxRequest/v1", ...
    "requestId", "bundle-test-request", ...
    "obstacles", struct.empty(0, 1), ...
    "initialState", struct( ...
        "time_s", 0, ...
        "position_deg", [0 0], ...
        "velocity_deg_s", [0 0], ...
        "acceleration_deg_s2", [0 0]), ...
    "goalState", struct( ...
        "time_s", 5, ...
        "position_deg", [1 0], ...
        "velocity_deg_s", [0 0], ...
        "acceleration_deg_s2", [0 0]), ...
    "limits", struct( ...
        "maxVelocity_deg_s", [2 2], ...
        "maxAcceleration_deg_s2", [2 2], ...
        "maxJerk_deg_s3", [5 5], ...
        "azimuthInterval_deg", [-10 10], ...
        "elevationInterval_deg", [-10 10]), ...
    "options", struct("GoalTimeMode", "earliestArrival"));
end
