function tests = testHs3Improver
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(repositoryRoot);
testCase.TestData.Fixtures = testSupport.plannerFixtures();
end

function testPolynomialJerkIntegralIsExact(testCase)
polynomial = struct( ...
    "SegmentCount", 2, "SegmentDuration_s", [2; 3], ...
    "jerkPower_deg_s3", zeros(2, 2, 3));
polynomial.jerkPower_deg_s3(1, :, 1) = [2 3];
polynomial.jerkPower_deg_s3(2, 1, 1:2) = [1 2];
expected = 2 * (2^2 + 3^2) + 3 * (1 + 2 + 4 / 3);
verifyEqual(testCase, ...
    azElInternal.integratedSquaredPolynomialJerk(polynomial), ...
    expected, "AbsTol", 1e-12);
end

function testComparatorRequiresMonotoneStrictImprovement(testCase)
valid = struct("Passed", true);
invalid = struct("Passed", false);
baseline = quality(valid, 10, 20);
[acceptedRecovery, recovery] = ...
    azElInternal.acceptsTrajectoryImprovement( ...
    quality(invalid, NaN, Inf), baseline);
verifyTrue(testCase, acceptedRecovery);
verifyFalse(testCase, recovery.BaselineValid);
verifyFalse(testCase, azElInternal.acceptsTrajectoryImprovement( ...
    baseline, quality(invalid, 9, 19)));
verifyFalse(testCase, azElInternal.acceptsTrajectoryImprovement( ...
    baseline, quality(valid, 10, 20)));
verifyTrue(testCase, azElInternal.acceptsTrajectoryImprovement( ...
    baseline, quality(valid, 10 - 1e-6, 20)));
verifyTrue(testCase, azElInternal.acceptsTrajectoryImprovement( ...
    baseline, quality(valid, 10, 20 - 1e-6)));
verifyFalse(testCase, azElInternal.acceptsTrajectoryImprovement( ...
    baseline, quality(valid, 10 + 1e-6, 19)));
end

function testImprovementOffPreservesImmutableBaseline(testCase)
baseline = syntheticBaseline();
options = azElPlannerMethods.hs3.resolvePlannerOptions();
verifyFalse(testCase, options.EnableHs3Improvement);
result = azElPlannerMethods.hs3.improve(baseline, options);
preservedFields = {'Inputs', 'Seeds', 'SelectedSeedIndex', ...
    'SelectedSeed_deg', 'time_s', 'position_deg', 'velocity_deg_s', ...
    'acceleration_deg_s2', 'jerk_deg_s3', 'Polynomial', ...
    'SeedCorridorBoundary_deg', 'SeedCorridor', 'Validation'};
for fieldIndex = 1:numel(preservedFields)
    field = preservedFields{fieldIndex};
    verifyEqual(testCase, result.(field), baseline.(field));
end
verifyEqual(testCase, result.Options, options);
verifyFalse(testCase, result.CompositionDiagnostics.Hs3.Attempted);
verifyFalse(testCase, result.SeedSummaries.Hs3Attempted);
verifyTrue(testCase, isfield(result.SeedSummaries, ...
    "Hs3SolverDiagnostics"));
end

function testEmptySeedSummaryRetainsGenericSchema(testCase)
baseline = syntheticBaseline();
genericTemplate = struct("SeedIndex", 0, "ValidationPassed", false, ...
    "Message", "");
baseline.Success = false;
baseline.Validation.Passed = false;
baseline.Seeds = baseline.Seeds([]);
baseline.SeedSummaries = repmat(genericTemplate, 0, 1);
baseline.SearchDiagnostics.SeedSummaries = baseline.SeedSummaries;
options = azElPlannerMethods.hs3.resolvePlannerOptions();
result = azElPlannerMethods.hs3.improve(baseline, options);
genericNames = fieldnames(genericTemplate);
resultNames = fieldnames(result.SeedSummaries);
verifyEqual(testCase, resultNames(1:numel(genericNames)), genericNames);
verifySize(testCase, result.SeedSummaries, [0 1]);
verifyTrue(testCase, isfield(result.SeedSummaries, "Hs3Attempted"));
end

function testRealOptInAttemptNeverLosesValidCompactBaseline(testCase)
fixtures = testCase.TestData.Fixtures;
initialState = fixtures.State(0, [0 0], [0 0], [0 0]);
goalState = fixtures.State(3, [1 0], [0 0], [0 0]);
limits = fixtures.PhysicalLimits([2 2], [2 2], [2 2]);
baseline = planAzElMotion( ...
    [], initialState, goalState, limits, struct( ...
    "PlannerMethod", "corridorQuintic", "DirectSeedOnly", true));
verifyTrue(testCase, baseline.Success, baseline.Message);
options = azElPlannerMethods.hs3.resolvePlannerOptions(struct( ...
    "EnableHs3Improvement", true, ...
    "MaximumHs3ImprovementTime_s", 0.25, ...
    "CollocationSegmentCount", 2, ...
    "MaximumCollocationSegmentCount", 2, ...
    "MaximumMeshRefinementPasses", 0));
result = azElPlannerMethods.hs3.improve(baseline, options);
verifyEqual(testCase, result.Inputs, baseline.Inputs);
verifyEqual(testCase, result.Seeds, baseline.Seeds);
verifyTrue(testCase, result.Success);
verifyTrue(testCase, result.Validation.Passed);
verifyGreaterThanOrEqual(testCase, ...
    numel(result.CompositionDiagnostics.Hs3.Attempts), 1);
exclusiveNames = ["TopologyElapsedTime_s", ...
    "CorridorConstructionElapsedTime_s", "MotionSolvingElapsedTime_s", ...
    "CollisionCheckingElapsedTime_s", "FinalValidationElapsedTime_s"];
for name = exclusiveNames
    verifyEqual(testCase, result.SearchDiagnostics.StageTiming.(name), ...
        baseline.SearchDiagnostics.StageTiming.(name));
end
verifyEqual(testCase, result.ElapsedPlanningTime_s, ...
    baseline.ElapsedPlanningTime_s + ...
    result.CompositionDiagnostics.Hs3.ElapsedTime_s, "AbsTol", 1e-12);
verifyEqual(testCase, ...
    result.SearchDiagnostics.StageTiming.TotalElapsedTime_s, ...
    result.ElapsedPlanningTime_s, "AbsTol", 1e-12);
if result.CompositionDiagnostics.Hs3.Accepted
    [accepted, ~] = azElInternal.acceptsTrajectoryImprovement( ...
        quality(baseline.Validation, baseline.ArrivalTime_s, ...
        azElInternal.integratedSquaredPolynomialJerk(baseline.Polynomial)), ...
        quality(result.Validation, result.ArrivalTime_s, ...
        azElInternal.integratedSquaredPolynomialJerk(result.Polynomial)));
    verifyTrue(testCase, accepted);
else
    verifyEqual(testCase, result.time_s, baseline.time_s);
    verifyEqual(testCase, result.Validation, baseline.Validation);
end
end

function testAcceptedRecoveryReconcilesPublicSearchDiagnostics(testCase)
% Promote a valid HS3 trial over a synthetic compact failure consistently.
fixtures = testCase.TestData.Fixtures;
initialState = fixtures.State(0, [0 0], [0 0], [0 0]);
goalState = fixtures.State(3, [1 0], [0 0], [0 0]);
limits = fixtures.PhysicalLimits([2 2], [2 2], [2 2]);
baseline = planAzElMotion( ...
    [], initialState, goalState, limits, struct( ...
    "PlannerMethod", "corridorQuintic", ...
    "GoalTimeMode", "fixedArrival", "DirectSeedOnly", true));
verifyTrue(testCase, baseline.Success, baseline.Message);

% Preserve real inputs and seeds while modeling a failed compact selection.
baseline.Success = false;
baseline.Message = "Synthetic compact failure.";
baseline.TerminationReason = "noValidatedSeed";
baseline.SelectedSeedIndex = 0;
baseline.SelectedMotionSource = "";
baseline.SelectedSeed_deg = zeros(0, 2);
baseline.Validation = validateAzElTrajectory();
baseline.ArrivalTime_s = NaN;
baseline.TrajectoryDuration_s = NaN;
baseline.FirstValidatedMotionTime_s = NaN;
baseline.SearchDiagnostics.TerminationReason = "noValidatedSeed";
baseline.SearchDiagnostics.ValidatedCandidateCount = 0;
baseline.SearchDiagnostics.BestPartialSeedIndex = 0;
baseline.SearchDiagnostics.FirstValidatedMotionTime_s = NaN;
for summaryIndex = 1:numel(baseline.SeedSummaries)
    baseline.SeedSummaries(summaryIndex).ValidationPassed = false;
end
baseline.SearchDiagnostics.SeedSummaries = baseline.SeedSummaries;

options = azElPlannerMethods.hs3.resolvePlannerOptions(struct( ...
    "GoalTimeMode", "fixedArrival", ...
    "EnableHs3Improvement", true, ...
    "MaximumHs3ImprovementTime_s", 2, ...
    "CollocationSegmentCount", 2, ...
    "MaximumCollocationSegmentCount", 2, ...
    "MaximumMeshRefinementPasses", 0));
result = azElPlannerMethods.hs3.improve(baseline, options);

verifyTrue(testCase, result.Success, result.Message);
verifyTrue(testCase, result.Validation.Passed, result.Validation.Message);
verifyTrue(testCase, result.CompositionDiagnostics.Hs3.Accepted);
verifyEqual(testCase, result.TerminationReason, "goalReached");
verifyEqual(testCase, result.SearchDiagnostics.TerminationReason, ...
    result.TerminationReason);
verifyEqual(testCase, ...
    result.SearchDiagnostics.ValidatedCandidateCount, 1);
verifyEqual(testCase, ...
    result.SearchDiagnostics.BestPartialSeedIndex, ...
    result.SelectedSeedIndex);
verifyEqual(testCase, ...
    result.SearchDiagnostics.FirstValidatedMotionTime_s, ...
    result.FirstValidatedMotionTime_s, "AbsTol", 1e-12);
verifyEqual(testCase, result.FirstValidatedMotionTime_s, ...
    result.ElapsedPlanningTime_s, "AbsTol", 1e-12);
end

function record = quality(validation, arrival_s, jerk)
record = struct( ...
    "Validation", validation, "ArrivalTime_s", arrival_s, ...
    "IntegratedSquaredJerk_deg2_s5", jerk);
end

function baseline = syntheticBaseline()
validation = validateAzElTrajectory();
validation.Passed = true;
polynomial = struct( ...
    "SegmentCount", 1, "SegmentDuration_s", 2, ...
    "jerkPower_deg_s3", zeros(1, 2, 3));
seed = struct( ...
    "Index", 1, "Source", "direct", ...
    "position_deg", [0 0; 1 0], "tau", [0; 1], ...
    "CorridorBoundary_deg", zeros(0, 2), ...
    "UsesReducedGeometry", false, ...
    "EstimatedDuration_s", 2, "Length_deg", 1);
summary = struct("SeedIndex", 1, "ValidationPassed", true);
baseline = struct( ...
    "Success", true, "Message", "baseline", ...
    "TerminationReason", "goalReached", "Options", struct("old", 1), ...
    "Inputs", struct("obstacles", struct([]), ...
    "initialState", struct(), "goalState", struct(), "limits", struct()), ...
    "Seeds", seed, "SeedSummaries", summary, ...
    "SelectedSeedIndex", 1, "SelectedMotionSource", "corridorQuintic", ...
    "SelectedSeed_deg", seed.position_deg, "time_s", [0; 2], ...
    "position_deg", [0 0; 1 0], "velocity_deg_s", zeros(2), ...
    "acceleration_deg_s2", zeros(2), "jerk_deg_s3", zeros(2), ...
    "Polynomial", polynomial, "SeedCorridorBoundary_deg", zeros(0, 2), ...
    "SeedCorridor", struct([]), "Validation", validation, ...
    "ArrivalTime_s", 2, "TrajectoryDuration_s", 2, ...
    "SearchDiagnostics", struct("SeedSummaries", summary), ...
    "ElapsedPlanningTime_s", 1);
end
