function tests = testHs3AffineSensitivity
%% Section 0: Header & Readme
% Prove the scalar-axis HS3 affine maps against direct state propagation.
tests = functiontests(localfunctions);
end

function setupOnce(~)
% Add the repository root for package-based test execution.
addpath(fileparts(fileparts(mfilename("fullpath"))));
end

function testRandomizedCoefficientAndTerminalParity(testCase)
% Cover requested mesh sizes, randomized jerk, and nonzero endpoint bases.
rng(325, "twister");
for segmentCount = [1 2 5 10]
    duration_s = 1.7 + 0.31 * segmentCount;
    evaluationTau = unique([linspace(0, 1, 47).'; ...
        (0:segmentCount).' / segmentCount]);
    model = azElPlannerMethods.hs3.internal.motion.hs3AffineSensitivity( ...
        segmentCount, duration_s, evaluationTau);
    initialState = struct( ...
        "position", -2.3 + rand(), ...
        "velocity", 0.7 + rand(), ...
        "acceleration", -0.4 + 0.8 * rand());
    jerk = 0.6 * randn(model.ControlCount, 1);
    zeroPolynomial = directReconstruction( ...
        zeros(model.ControlCount, 1), initialState, duration_s, segmentCount);
    jerkPolynomial = directReconstruction( ...
        jerk, initialState, duration_s, segmentCount);
    verifyCoefficientDelta(testCase, model, zeroPolynomial, jerkPolynomial, jerk);
    expectedTerminalDelta = model.terminalStateMap * jerk;
    actualTerminalDelta = jerkPolynomial.terminalState - ...
        zeroPolynomial.terminalState;
    verifyEqual(testCase, actualTerminalDelta, expectedTerminalDelta, ...
        "AbsTol", 2e-12, "RelTol", 2e-12);
    [zeroPosition, zeroVelocity] = evaluateDirect(zeroPolynomial, evaluationTau);
    [jerkPosition, jerkVelocity] = evaluateDirect(jerkPolynomial, evaluationTau);
    verifyEqual(testCase, jerkPosition - zeroPosition, ...
        model.positionAtTauMap * jerk, "AbsTol", 2e-12, "RelTol", 2e-12);
    verifyEqual(testCase, jerkVelocity - zeroVelocity, ...
        model.velocityAtTauMap * jerk, "AbsTol", 2e-12, "RelTol", 2e-12);
end
end

function testDirectionalFiniteDifferenceParity(testCase)
% Verify every coefficient and sampled map as a decision-space derivative.
rng(1325, "twister");
for segmentCount = [1 2 5 10]
    duration_s = 2.1 + 0.19 * segmentCount;
    evaluationTau = unique([linspace(0, 1, 53).'; ...
        ((0:segmentCount - 1).' + 0.5) / segmentCount]);
    model = azElPlannerMethods.hs3.internal.motion.hs3AffineSensitivity( ...
        segmentCount, duration_s, evaluationTau);
    initialState = struct("position", 1.4, "velocity", -0.8, ...
        "acceleration", 0.35);
    jerk = randn(model.ControlCount, 1);
    direction = randn(model.ControlCount, 1);
    direction = direction / norm(direction);
    differenceStep = 1e-5;
    lowerPolynomial = directReconstruction( ...
        jerk - differenceStep * direction, initialState, duration_s, segmentCount);
    upperPolynomial = directReconstruction( ...
        jerk + differenceStep * direction, initialState, duration_s, segmentCount);
    verifyDirectionalCoefficient(testCase, model, lowerPolynomial, ...
        upperPolynomial, direction, differenceStep);
    [lowerPosition, lowerVelocity] = evaluateDirect( ...
        lowerPolynomial, evaluationTau);
    [upperPosition, upperVelocity] = evaluateDirect( ...
        upperPolynomial, evaluationTau);
    verifyEqual(testCase, (upperPosition - lowerPosition) / ...
        (2 * differenceStep), model.positionAtTauMap * direction, ...
        "AbsTol", 2e-9, "RelTol", 2e-10);
    verifyEqual(testCase, (upperVelocity - lowerVelocity) / ...
        (2 * differenceStep), model.velocityAtTauMap * direction, ...
        "AbsTol", 2e-9, "RelTol", 2e-10);
    verifyEqual(testCase, (upperPolynomial.terminalState - ...
        lowerPolynomial.terminalState) / (2 * differenceStep), ...
        model.terminalStateMap * direction, ...
        "AbsTol", 2e-9, "RelTol", 2e-10);
end
end

function testFixedSolveUsesExactAffineConstraintMatrices(testCase)
% Exercise continuous, terminal, seed-free, and frozen obstacle Jacobian rows.
initialState = struct( ...
    "time_s", 0, "position_deg", [-4 3], ...
    "velocity_deg_s", [0.3 -0.1], ...
    "acceleration_deg_s2", [0.05 0]);
goalState = struct( ...
    "time_s", 8, "position_deg", [4 3], ...
    "velocity_deg_s", [-0.2 0.15], ...
    "acceleration_deg_s2", [0 -0.04]);
limits = struct( ...
    "maxVelocity_deg_s", [3 3], ...
    "maxAcceleration_deg_s2", [2 2], ...
    "maxJerk_deg_s3", [3 3], ...
    "azimuthInterval_deg", [-10 10], ...
    "elevationInterval_deg", [-10 10]);
vertices_deg = [-1 -1; 1 -1; 1 1; -1 1];
obstacle = makeAzElObstacleData( ...
    "static below route", [0; 8], ...
    {vertices_deg(:, 1); vertices_deg(:, 1)}, ...
    {vertices_deg(:, 2); vertices_deg(:, 2)}, 0);
seed = struct( ...
    "Index", 1, "Source", "visibilityGraph", ...
    "position_deg", [-4 3; 0 3; 4 3], ...
    "tau", [0; 0.5; 1], "EstimatedDuration_s", 8, ...
    "Length_deg", 8, "UsesReducedGeometry", false);
options = directFixedOptions();
solverTimer = tic;
candidate = azElPlannerMethods.hs3.internal.motion.solveHs3( ...
    obstacle, initialState, goalState, limits, options, seed);
elapsedTime_s = toc(solverTimer);
verifyTrue(testCase, candidate.OptimizerFeasible, candidate.Message);
verifyEqual(testCase, ...
    candidate.SolverDiagnostics.ConstraintRepresentation, "linearFixedTime");
verifyNotEmpty(testCase, candidate.Corridor);
verifyLessThanOrEqual(testCase, ...
    candidate.MaximumConstraintViolation, 1e-6);
verifyEqual(testCase, candidate.position_deg(end, :), ...
    goalState.position_deg, "AbsTol", 1e-7);
verifyEqual(testCase, candidate.velocity_deg_s(end, :), ...
    goalState.velocity_deg_s, "AbsTol", 1e-7);
verifyEqual(testCase, candidate.acceleration_deg_s2(end, :), ...
    goalState.acceleration_deg_s2, "AbsTol", 1e-7);
verifyLessThan(testCase, elapsedTime_s, options.MaximumSolverTime_s + 2);
end

function testFixedConstraintMatricesMatchDirectionalDifference(testCase)
% Prove the assembled raw constraint Jacobians in fmincon row order.
rng(2325, "twister");
segmentCount = 5;
controlCount = 2 * segmentCount + 1;
duration_s = 7.4;
corridorTau = unique([linspace(0, 1, 43).'; ...
    (0:segmentCount).' / segmentCount]);
seedTemplate = struct( ...
    "SegmentIndex", 0, "RegionIndex", 0, "Normal", [0 0], ...
    "BoundaryOffset_deg", 0, "Clearance_deg", 0);
seedCorridor = repmat(seedTemplate, 2, 1);
seedCorridor(1).SegmentIndex = 2;
seedCorridor(1).Normal = [0.6 0.8];
seedCorridor(2).SegmentIndex = 5;
seedCorridor(2).Normal = [-0.8 0.6];
corridorTemplate = struct( ...
    "ControlIndex", 0, "GeometryIsFixed", true, ...
    "FixedNormal", [0 0], "FixedBoundaryOffset_deg", 0, ...
    "Clearance_deg", 0);
corridor = repmat(corridorTemplate, 3, 1);
corridor(1).ControlIndex = 4;
corridor(1).FixedNormal = [1 0];
corridor(2).ControlIndex = 19;
corridor(2).FixedNormal = [0.3 -sqrt(0.91)];
corridor(3).ControlIndex = numel(corridorTau);
corridor(3).FixedNormal = [-0.4 sqrt(0.84)];
[inequalityMatrix, equalityMatrix] = ...
    azElPlannerMethods.hs3.internal.motion.buildFixedHs3ConstraintMatrices( ...
    segmentCount, duration_s, false, seedCorridor, corridor, corridorTau);
initialState = struct( ...
    "position", [-1.2 2.1], "velocity", [0.4 -0.3], ...
    "acceleration", [-0.1 0.2]);
decision = randn(2 * controlCount, 1);
direction = randn(2 * controlCount, 1);
direction = direction / norm(direction);
differenceStep = 1e-5;
[lowerInequality, lowerEquality] = directConstraintValues( ...
    decision - differenceStep * direction, initialState, duration_s, ...
    segmentCount, seedCorridor, corridor, corridorTau);
[upperInequality, upperEquality] = directConstraintValues( ...
    decision + differenceStep * direction, initialState, duration_s, ...
    segmentCount, seedCorridor, corridor, corridorTau);
verifyEqual(testCase, (upperInequality - lowerInequality) / ...
    (2 * differenceStep), inequalityMatrix * direction, ...
    "AbsTol", 5e-9, "RelTol", 5e-10);
verifyEqual(testCase, (upperEquality - lowerEquality) / ...
    (2 * differenceStep), equalityMatrix * direction, ...
    "AbsTol", 5e-9, "RelTol", 5e-10);
end


function testEarliestStaticHybridGradientDirectionalParity(testCase)
% Verify exact jerk columns and the smooth static final-time column.
rng(3325, "twister");
segmentCount = 5;
controlCount = 2 * segmentCount + 1;
initialState = plannerState(1.5, [-2 1], [0.4 -0.2], [0.1 0.05]);
goalState = plannerState(12, [3 -1], [-0.1 0.3], [0 -0.08]);
limits = directLimits();
options = directFixedOptions();
options.GoalTimeMode = "earliestArrival";
decision = [0.2 * randn(2 * controlCount, 1); 8.3];
reconstructFunction = @(jerk, finalTime_s) reconstructHs3Polynomial( ...
    jerk, initialState, finalTime_s, segmentCount);
[inequality, equality, inequalityGradient, equalityGradient] = ...
    azElPlannerMethods.hs3.internal.motion.evaluateHs3TrajectoryConstraints( ...
    decision, true, goalState.time_s, 4, goalState.time_s, segmentCount, ...
    initialState, goalState, limits, options, struct([]), struct([]), ...
    linspace(0, 1, 41).', struct([]), reconstructFunction);
verifySize(testCase, inequalityGradient, [numel(decision), numel(inequality)]);
verifySize(testCase, equalityGradient, [numel(decision), numel(equality)]);
jerkDirection = [randn(2 * controlCount, 1); 0];
jerkDirection = jerkDirection / norm(jerkDirection);
verifyConstraintDirection(testCase, decision, jerkDirection, 1e-5, ...
    inequality, equality, inequalityGradient, equalityGradient, ...
    initialState, goalState, limits, options, struct([]), struct([]), ...
    linspace(0, 1, 41).', struct([]), segmentCount, 4, reconstructFunction, ...
    "central", 2e-8);
timeDirection = zeros(size(decision));
timeDirection(end) = 1;
verifyConstraintDirection(testCase, decision, timeDirection, ...
    eps^(1 / 3) * decision(end), inequality, equality, ...
    inequalityGradient, equalityGradient, initialState, goalState, ...
    limits, options, struct([]), struct([]), linspace(0, 1, 41).', ...
    struct([]), segmentCount, 4, reconstructFunction, "forward", 2e-4);
end

function testEarliestDeformingEventHybridGradientParity(testCase)
% Exercise exact jerk columns and a nonzero one-sided derivative at a knot.
rng(4325, "twister");
segmentCount = 4;
controlCount = 2 * segmentCount + 1;
initialState = plannerState(0, [-3 3], [0.2 -0.1], [0.03 0]);
goalState = plannerState(12, [4 3], [-0.15 0.1], [0 -0.02]);
limits = directLimits();
options = directFixedOptions();
options.GoalTimeMode = "earliestArrival";
first_deg = [-1 -1; 1 -1; 1 1; -1 1];
middle_deg = [-1.5 -0.5; 1.5 -0.5; 1.5 1.5; -1.5 1.5];
last_deg = [-0.5 0; 2 0; 2 2; -0.5 2];
obstacle = makeAzElObstacleData( ...
    "deforming event", [0; 4; 10], ...
    {first_deg(:, 1); middle_deg(:, 1); last_deg(:, 1)}, ...
    {first_deg(:, 2); middle_deg(:, 2); last_deg(:, 2)}, 0);
corridorTau = [0.25; 0.5; 0.75];
corridor = dynamicSupportAssociation(2, 0.5, [0 1]);
decision = [0.15 * randn(2 * controlCount, 1); 8];
reconstructFunction = @(jerk, finalTime_s) reconstructHs3Polynomial( ...
    jerk, initialState, finalTime_s, segmentCount);
[inequality, equality, inequalityGradient, equalityGradient] = ...
    azElPlannerMethods.hs3.internal.motion.evaluateHs3TrajectoryConstraints( ...
    decision, true, goalState.time_s, 6, goalState.time_s, segmentCount, ...
    initialState, goalState, limits, options, obstacle, corridor, ...
    corridorTau, struct([]), reconstructFunction);
jerkDirection = [randn(2 * controlCount, 1); 0];
jerkDirection = jerkDirection / norm(jerkDirection);
verifyConstraintDirection(testCase, decision, jerkDirection, 1e-5, ...
    inequality, equality, inequalityGradient, equalityGradient, ...
    initialState, goalState, limits, options, obstacle, corridor, ...
    corridorTau, struct([]), segmentCount, 6, reconstructFunction, ...
    "central", 2e-8);
timeDirection = zeros(size(decision));
timeDirection(end) = 1;
differenceStep = eps^(1 / 3) * decision(end);
verifyConstraintDirection(testCase, decision, timeDirection, ...
    differenceStep, inequality, equality, inequalityGradient, ...
    equalityGradient, initialState, goalState, limits, options, ...
    obstacle, corridor, corridorTau, struct([]), segmentCount, 6, ...
    reconstructFunction, "forward", 2e-8);
verifyGreaterThan(testCase, norm(inequalityGradient(end, :)), 0);
end

function verifyConstraintDirection(testCase, decision, direction, step, ...
        inequality, equality, inequalityGradient, equalityGradient, ...
        initialState, goalState, limits, options, obstacles, corridor, ...
        corridorTau, seedCorridor, segmentCount, minimumFinalTime_s, ...
        reconstructFunction, differenceMode, tolerance)
% Compare the returned fmincon-oriented Jacobians with raw value differences.
upperDecision = decision + step * direction;
[upperInequality, upperEquality] = ...
    azElPlannerMethods.hs3.internal.motion.evaluateHs3TrajectoryConstraints( ...
    upperDecision, true, goalState.time_s, minimumFinalTime_s, ...
    goalState.time_s, segmentCount, initialState, goalState, limits, ...
    options, obstacles, corridor, corridorTau, seedCorridor, ...
    reconstructFunction);
if differenceMode == "central"
    lowerDecision = decision - step * direction;
    [lowerInequality, lowerEquality] = ...
        azElPlannerMethods.hs3.internal.motion.evaluateHs3TrajectoryConstraints( ...
        lowerDecision, true, goalState.time_s, minimumFinalTime_s, ...
        goalState.time_s, segmentCount, initialState, goalState, limits, ...
        options, obstacles, corridor, corridorTau, seedCorridor, ...
        reconstructFunction);
    inequalityDifference = (upperInequality - lowerInequality) / (2 * step);
    equalityDifference = (upperEquality - lowerEquality) / (2 * step);
else
    inequalityDifference = (upperInequality - inequality) / step;
    equalityDifference = (upperEquality - equality) / step;
end
verifyEqual(testCase, inequalityDifference, ...
    inequalityGradient.' * direction, "AbsTol", tolerance, ...
    "RelTol", tolerance);
verifyEqual(testCase, equalityDifference, ...
    equalityGradient.' * direction, "AbsTol", tolerance, ...
    "RelTol", tolerance);
end

function polynomial = reconstructHs3Polynomial( ...
        jerk_deg_s3, initialState, finalTime_s, segmentCount)
% Build the two-axis test polynomial through independent scalar propagation.
duration_s = finalTime_s - initialState.time_s;
azimuthInitial = struct( ...
    "position", initialState.position_deg(1), ...
    "velocity", initialState.velocity_deg_s(1), ...
    "acceleration", initialState.acceleration_deg_s2(1));
elevationInitial = struct( ...
    "position", initialState.position_deg(2), ...
    "velocity", initialState.velocity_deg_s(2), ...
    "acceleration", initialState.acceleration_deg_s2(2));
azimuth = directReconstruction( ...
    jerk_deg_s3(:, 1), azimuthInitial, duration_s, segmentCount);
elevation = directReconstruction( ...
    jerk_deg_s3(:, 2), elevationInitial, duration_s, segmentCount);
polynomial = combineScalarPolynomials(azimuth, elevation, segmentCount);
polynomial.SegmentStartTime_s = initialState.time_s + ...
    (0:segmentCount - 1).' * duration_s / segmentCount;
polynomial.SegmentDuration_s = duration_s / segmentCount;
polynomial.FinalTime_s = finalTime_s;
polynomial.TerminalState = struct( ...
    "position_deg", [azimuth.terminalState(1), elevation.terminalState(1)], ...
    "velocity_deg_s", [azimuth.terminalState(2), elevation.terminalState(2)], ...
    "acceleration_deg_s2", ...
    [azimuth.terminalState(3), elevation.terminalState(3)]);
end

function state = plannerState(time_s, position_deg, velocity_deg_s, ...
        acceleration_deg_s2)
% Construct one normalized test state with nonzero derivative support.
state = struct( ...
    "time_s", time_s, "position_deg", position_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2);
end

function limits = directLimits()
% Return broad two-axis limits for derivative proofs.
limits = struct( ...
    "maxVelocity_deg_s", [4 4], ...
    "maxAcceleration_deg_s2", [3 3], ...
    "maxJerk_deg_s3", [3 3], ...
    "azimuthInterval_deg", [-20 20], ...
    "elevationInterval_deg", [-20 20]);
end

function association = dynamicSupportAssociation(controlIndex, tau, normal)
% Define one frozen association whose support offset follows input geometry.
association = struct( ...
    "ControlIndex", controlIndex, "ObstacleIndex", 1, "EdgeIndex", 1, ...
    "Tau", tau, "OutwardSign", 1, "UseSupport", true, ...
    "SupportNormal", normal, "Clearance_deg", 1e-4, ...
    "GeometryIsFixed", false, "FixedNormal", [0 0], ...
    "FixedBoundaryOffset_deg", 0);
end

function options = directFixedOptions()
% Supply only the resolved fields consumed by the isolated HS3 solver.
options = struct( ...
    "GoalTimeMode", "fixedArrival", ...
    "SampleTime_s", 0.05, ...
    "AllowAzimuthWrapping", false, ...
    "CollocationSegmentCount", 5, ...
    "MaximumNlpIterations", 150, ...
    "MaximumNlpFunctionEvaluations", 15000, ...
    "MaximumSolverTime_s", 20, ...
    "ArrivalTimeTolerance_s", 1e-3, ...
    "ConstraintTolerance", 1e-7, ...
    "OptimalityTolerance", 1e-7, ...
    "StepTolerance", 1e-10, ...
    "CollisionClearanceTolerance_deg", 1e-7, ...
    "Verbose", false);
end

function [inequality, equality] = directConstraintValues( ...
        decision, initialState, duration_s, segmentCount, ...
        seedCorridor, corridor, corridorTau)
% Reconstruct raw fixed-time constraints independently of production maps.
controlCount = 2 * segmentCount + 1;
azimuthInitial = struct( ...
    "position", initialState.position(1), ...
    "velocity", initialState.velocity(1), ...
    "acceleration", initialState.acceleration(1));
elevationInitial = struct( ...
    "position", initialState.position(2), ...
    "velocity", initialState.velocity(2), ...
    "acceleration", initialState.acceleration(2));
azimuthPolynomial = directReconstruction( ...
    decision(1:controlCount), azimuthInitial, duration_s, segmentCount);
elevationPolynomial = directReconstruction( ...
    decision(controlCount + 1:end), elevationInitial, duration_s, segmentCount);
polynomial = combineScalarPolynomials( ...
    azimuthPolynomial, elevationPolynomial, segmentCount);
continuousInequality = directContinuousBounds(polynomial);
seedInequality = azElInternal.seedCorridorInequality( ...
    polynomial, seedCorridor);
[azimuthPosition, ~] = evaluateDirect(azimuthPolynomial, corridorTau);
[elevationPosition, ~] = evaluateDirect(elevationPolynomial, corridorTau);
position_deg = [azimuthPosition, elevationPosition];
controlIndex = [corridor.ControlIndex].';
normal = vertcat(corridor.FixedNormal);
offset_deg = [corridor.FixedBoundaryOffset_deg].' + ...
    [corridor.Clearance_deg].';
corridorInequality = offset_deg - sum( ...
    position_deg(controlIndex, :) .* normal, 2);
inequality = [continuousInequality; seedInequality; corridorInequality];
equality = [ ...
    azimuthPolynomial.terminalState(1); ...
    elevationPolynomial.terminalState(1); ...
    azimuthPolynomial.terminalState(2); ...
    elevationPolynomial.terminalState(2); ...
    azimuthPolynomial.terminalState(3); ...
    elevationPolynomial.terminalState(3)];
end

function polynomial = combineScalarPolynomials(azimuth, elevation, segmentCount)
% Assemble the two-axis coefficient shape consumed by shared constraints.
polynomial = struct( ...
    "SegmentCount", segmentCount, ...
    "positionPower_deg", cat(2, ...
    reshape(azimuth.positionPower, segmentCount, 1, 6), ...
    reshape(elevation.positionPower, segmentCount, 1, 6)), ...
    "velocityPower_deg_s", cat(2, ...
    reshape(azimuth.velocityPower, segmentCount, 1, 5), ...
    reshape(elevation.velocityPower, segmentCount, 1, 5)), ...
    "accelerationPower_deg_s2", cat(2, ...
    reshape(azimuth.accelerationPower, segmentCount, 1, 4), ...
    reshape(elevation.accelerationPower, segmentCount, 1, 4)), ...
    "jerkPower_deg_s3", cat(2, ...
    reshape(azimuth.jerkPower, segmentCount, 1, 3), ...
    reshape(elevation.jerkPower, segmentCount, 1, 3)));
end

function inequality = directContinuousBounds(polynomial)
% Reproduce the non-wrapped continuous Bernstein constraint value order.
positionViolation = directBernsteinViolations( ...
    polynomial.positionPower_deg, [-10 -10], [10 10]);
velocityViolation = directBernsteinViolations( ...
    polynomial.velocityPower_deg_s, [-3 -3], [3 3]);
accelerationViolation = directBernsteinViolations( ...
    polynomial.accelerationPower_deg_s2, [-2 -2], [2 2]);
jerkViolation = directBernsteinViolations( ...
    polynomial.jerkPower_deg_s3, [-3 -3], [3 3]);
firstAxis = [positionViolation(:, 1, :); velocityViolation(:, 1, :); ...
    accelerationViolation(:, 1, :); jerkViolation(:, 1, :)];
secondAxis = [positionViolation(:, 2, :); velocityViolation(:, 2, :); ...
    accelerationViolation(:, 2, :); jerkViolation(:, 2, :)];
segmentCount = polynomial.SegmentCount;
inequalityBySegment = [reshape(firstAxis, [], segmentCount); ...
    reshape(secondAxis, [], segmentCount)];
inequality = inequalityBySegment(:);
end

function violation = directBernsteinViolations( ...
        powerCoefficient, lowerBound, upperBound)
% Convert independent coefficient values through the shared exact basis.
segmentCount = size(powerCoefficient, 1);
coefficientCount = size(powerCoefficient, 3);
coefficientMatrix = reshape(permute( ...
    powerCoefficient, [3 1 2]), coefficientCount, []);
bernstein = azElInternal.powerToBernstein(coefficientMatrix);
bernstein = permute(reshape( ...
    bernstein, coefficientCount, segmentCount, 2), [1 3 2]);
violation = [bernstein - reshape(upperBound, 1, 2, 1); ...
    reshape(lowerBound, 1, 2, 1) - bernstein];
end

function verifyCoefficientDelta(testCase, model, zeroPolynomial, ...
        jerkPolynomial, jerk)
% Apply every coefficient tensor to one randomized control vector.
names = ["positionPower", "velocityPower", ...
    "accelerationPower", "jerkPower"];
for name = names
    coefficientMap = model.(name + "Map");
    predictedDelta = applyMap(coefficientMap, jerk);
    actualDelta = jerkPolynomial.(name) - zeroPolynomial.(name);
    verifyEqual(testCase, actualDelta, predictedDelta, ...
        "AbsTol", 2e-12, "RelTol", 2e-12);
end
end

function verifyDirectionalCoefficient(testCase, model, lowerPolynomial, ...
        upperPolynomial, direction, differenceStep)
% Compare centered directional differences for every polynomial field.
names = ["positionPower", "velocityPower", ...
    "accelerationPower", "jerkPower"];
for name = names
    actualDerivative = (upperPolynomial.(name) - ...
        lowerPolynomial.(name)) / (2 * differenceStep);
    expectedDerivative = applyMap(model.(name + "Map"), direction);
    verifyEqual(testCase, actualDerivative, expectedDerivative, ...
        "AbsTol", 2e-9, "RelTol", 2e-10);
end
end

function value = applyMap(coefficientMap, control)
% Contract a segment-by-power-by-control map with one control column.
value = reshape(sum(coefficientMap .* ...
    reshape(control, 1, 1, []), 3), ...
    size(coefficientMap, 1), size(coefficientMap, 2));
end

function polynomial = directReconstruction( ...
        jerk, initialState, duration_s, segmentCount)
% Independently propagate scalar states through exact local integrations.
segmentDuration_s = duration_s / segmentCount;
positionPower = zeros(segmentCount, 6);
velocityPower = zeros(segmentCount, 5);
accelerationPower = zeros(segmentCount, 4);
jerkPower = zeros(segmentCount, 3);
position = initialState.position;
velocity = initialState.velocity;
acceleration = initialState.acceleration;
for segmentIndex = 1:segmentCount
    startJerk = jerk(2 * segmentIndex - 1);
    midpointJerk = jerk(2 * segmentIndex);
    endJerk = jerk(2 * segmentIndex + 1);
    jerkLinear = -3 * startJerk + 4 * midpointJerk - endJerk;
    jerkQuadratic = 2 * startJerk - 4 * midpointJerk + 2 * endJerk;
    jerkPower(segmentIndex, :) = [startJerk, jerkLinear, jerkQuadratic];
    accelerationPower(segmentIndex, :) = [acceleration, ...
        segmentDuration_s * startJerk, ...
        segmentDuration_s * jerkLinear / 2, ...
        segmentDuration_s * jerkQuadratic / 3];
    velocityPower(segmentIndex, :) = [velocity, ...
        segmentDuration_s * acceleration, ...
        segmentDuration_s^2 * startJerk / 2, ...
        segmentDuration_s^2 * jerkLinear / 6, ...
        segmentDuration_s^2 * jerkQuadratic / 12];
    positionPower(segmentIndex, :) = [position, ...
        segmentDuration_s * velocity, ...
        segmentDuration_s^2 * acceleration / 2, ...
        segmentDuration_s^3 * startJerk / 6, ...
        segmentDuration_s^3 * jerkLinear / 24, ...
        segmentDuration_s^3 * jerkQuadratic / 60];
    position = sum(positionPower(segmentIndex, :));
    velocity = sum(velocityPower(segmentIndex, :));
    acceleration = sum(accelerationPower(segmentIndex, :));
end
polynomial = struct( ...
    "positionPower", positionPower, ...
    "velocityPower", velocityPower, ...
    "accelerationPower", accelerationPower, ...
    "jerkPower", jerkPower, ...
    "terminalState", [position; velocity; acceleration]);
end

function [position, velocity] = evaluateDirect(polynomial, evaluationTau)
% Evaluate ascending local powers using a test-owned Horner loop.
segmentCount = size(polynomial.positionPower, 1);
scaledTau = segmentCount * evaluationTau;
segmentIndex = min(segmentCount, floor(scaledTau) + 1);
localTau = scaledTau - segmentIndex + 1;
position = evaluatePower(polynomial.positionPower, segmentIndex, localTau);
velocity = evaluatePower(polynomial.velocityPower, segmentIndex, localTau);
end

function value = evaluatePower(coefficient, segmentIndex, localTau)
% Apply Horner evaluation independently of production polynomial helpers.
value = zeros(size(localTau));
for powerIndex = size(coefficient, 2):-1:1
    selectedCoefficient = coefficient(sub2ind( ...
        size(coefficient), segmentIndex, ...
        powerIndex * ones(size(segmentIndex))));
    selectedCoefficient = selectedCoefficient(:);
    value = selectedCoefficient + localTau .* value;
end
end
