function tests = testNonuniformHs3Mesh
%% Section 0: Header & Readme
% SYNTAX
%   results = runtests("tests/testNonuniformHs3Mesh.m")
%**************************************************************************
% PURPOSE
%   - Verify nonuniform HS3 propagation, sensitivities, objective gradients,
%     solver behavior, and path-interval ownership.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - tests (matlab.unittest.FunctionTestCase array)
%       Function-based tests discovered by MATLAB runtests.
%**************************************************************************
% UNITS
%   - Test coordinates and time use arbitrary consistent units.
%**************************************************************************
tests = functiontests(localfunctions);
end

function setupOnce(~)
% Add both package roots used by the standalone engine tests.
repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(repositoryRoot);
addpath(fullfile(repositoryRoot, "trajectory"));
end

function testExplicitUniformMeshPreservesPolynomial(testCase)
% Require bitwise equality across every kernel on the uniform dispatch.
segmentCount = 4;
duration = 5;
uniformBreakTau = (0:segmentCount).' / segmentCount;
controlJerk = reshape(linspace(-0.8, 0.9, 18), 9, 2);
initialState = struct("time", 1.2, "position", [2 -1], ...
    "velocity", [0.1 -0.2], "acceleration", [0.05 0.02]);
implicit = hs3Engine.polynomial.createTrajectoryPolynomial( ...
    controlJerk, initialState, 6.2, segmentCount);
explicit = hs3Engine.polynomial.createTrajectoryPolynomial( ...
    controlJerk, initialState, 6.2, segmentCount, ...
    uniformBreakTau);
evaluationTau = linspace(0, 1, 17).';
implicitSensitivity = ...
    hs3Engine.polynomial.createAffineSensitivityModel( ...
    segmentCount, duration, evaluationTau);
explicitSensitivity = ...
    hs3Engine.polynomial.createAffineSensitivityModel( ...
    segmentCount, duration, evaluationTau, uniformBreakTau);
decision = controlJerk(:);
[implicitObjective, implicitGradient, implicitHessian] = ...
    hs3Engine.polynomial.evaluateIntegratedSquaredJerk( ...
    decision, false, 6.2, segmentCount, 1.2, 2);
[explicitObjective, explicitGradient, explicitHessian] = ...
    hs3Engine.polynomial.evaluateIntegratedSquaredJerk( ...
    decision, false, 6.2, segmentCount, 1.2, 2, uniformBreakTau);
[implicitSegmentIndex, implicitHullMap] = ...
    hs3Engine.polynomial.createSubintervalBernsteinMap( ...
    [0.04; 0.54], [0.12; 0.63], segmentCount, 6);
[explicitSegmentIndex, explicitHullMap] = ...
    hs3Engine.polynomial.createSubintervalBernsteinMap( ...
    [0.04; 0.54], [0.12; 0.63], segmentCount, 6, uniformBreakTau);

verifyEqual(testCase, explicit.positionPower, implicit.positionPower);
verifyEqual(testCase, explicit.velocityPower, implicit.velocityPower);
verifyEqual(testCase, explicit.accelerationPower, implicit.accelerationPower);
verifyEqual(testCase, explicit.TerminalState, implicit.TerminalState);
verifyEqual(testCase, explicitSensitivity.positionAtTauMap, ...
    implicitSensitivity.positionAtTauMap);
verifyEqual(testCase, explicitSensitivity.velocityAtTauMap, ...
    implicitSensitivity.velocityAtTauMap);
verifyEqual(testCase, explicitSensitivity.terminalStateMap, ...
    implicitSensitivity.terminalStateMap);
verifyEqual(testCase, explicitObjective, implicitObjective);
verifyEqual(testCase, explicitGradient, implicitGradient);
verifyEqual(testCase, explicitHessian, implicitHessian);
verifyEqual(testCase, explicitSegmentIndex, implicitSegmentIndex);
verifyEqual(testCase, explicitHullMap, implicitHullMap);
end

function testNonuniformSensitivityMatchesReconstruction(testCase)
% Compare the affine map against an exact finite perturbation in jerk.
segmentCount = 3;
duration = 4.7;
breakTau = [0; 0.15; 0.62; 1];
evaluationTau = [0.07; 0.4; 0.91];
controlJerk = [0.2; -0.4; 0.7; 0.1; -0.6; 0.3; 0.5];
initialState = struct("time", 0, "position", 0, ...
    "velocity", 0, "acceleration", 0);
model = hs3Engine.polynomial.createAffineSensitivityModel( ...
    segmentCount, duration, evaluationTau, breakTau);
polynomial = hs3Engine.polynomial.createTrajectoryPolynomial( ...
    controlJerk, initialState, duration, segmentCount, breakTau);
time = duration * evaluationTau;
[~, position, velocity] = ...
    hs3Engine.polynomial.evaluateTrajectoryPolynomial(polynomial, time);

verifyEqual(testCase, model.positionAtTauMap * controlJerk, position, ...
    "AbsTol", 2e-13);
verifyEqual(testCase, model.velocityAtTauMap * controlJerk, velocity, ...
    "AbsTol", 2e-13);
verifyEqual(testCase, model.terminalStateMap * controlJerk, ...
    [polynomial.TerminalState.position; ...
    polynomial.TerminalState.velocity; ...
    polynomial.TerminalState.acceleration], "AbsTol", 2e-13);
end

function testNonuniformJerkGradient(testCase)
% Check the exact weighted objective gradient by directional differentiation.
segmentCount = 3;
dimensionCount = 2;
breakTau = [0; 0.1; 0.55; 1];
decision = linspace(-0.7, 0.9, ...
    dimensionCount * (2 * segmentCount + 1)).';
direction = cos((1:numel(decision)).');
[~, gradient] = hs3Engine.polynomial.evaluateIntegratedSquaredJerk( ...
    decision, false, 5, segmentCount, 0, dimensionCount, breakTau);
step = 1e-6;
plus = hs3Engine.polynomial.evaluateIntegratedSquaredJerk( ...
    decision + step * direction, false, 5, segmentCount, 0, ...
    dimensionCount, breakTau);
minus = hs3Engine.polynomial.evaluateIntegratedSquaredJerk( ...
    decision - step * direction, false, 5, segmentCount, 0, ...
    dimensionCount, breakTau);
finiteDifference = (plus - minus) / (2 * step);

verifyEqual(testCase, gradient.' * direction, finiteDifference, ...
    "RelTol", 2e-9, "AbsTol", 2e-10);
end

function testNonuniformFixedSolveValidates(testCase)
% Solve and independently validate one nonuniform fixed-time motion.
initialState = struct("time", 0, "position", 0, ...
    "velocity", 0, "acceleration", 0);
terminalState = struct("position", 1, "velocity", 0, ...
    "acceleration", 0, "maximumTime", 4);
limits = struct("maximumVelocity", 2, ...
    "maximumAcceleration", 2, "maximumJerk", 4);
options = struct("TimeMode", "fixed", "FinalTime", 4, ...
    "SegmentCount", 4, "SegmentBreakTau", [0; 0.1; 0.4; 0.75; 1], ...
    "Verbose", false);

trajectory = hs3Engine.solve( ...
    initialState, terminalState, limits, options);

verifyTrue(testCase, trajectory.Success, trajectory.Message);
verifyTrue(testCase, trajectory.Validation.Passed, ...
    trajectory.Validation.Message);
verifyEqual(testCase, trajectory.Polynomial.SegmentBreakTau, ...
    options.SegmentBreakTau);
end

function testRejectsCrossingNonuniformInterval(testCase)
% Ensure a continuous path certificate cannot silently cross a mesh boundary.
initialState = struct("time", 0, "position", 0, ...
    "velocity", 0, "acceleration", 0);
terminalState = struct("position", 1, "velocity", 0, ...
    "acceleration", 0, "maximumTime", 4);
limits = struct("maximumVelocity", 2, ...
    "maximumAcceleration", 2, "maximumJerk", 4);
options = struct("TimeMode", "fixed", "FinalTime", 4, ...
    "SegmentCount", 3, "SegmentBreakTau", [0; 0.2; 0.7; 1]);
pathConstraints = struct("Tau", 0.1, "TauEnd", 0.3, ...
    "Normal", 1, "LowerBound", -10);

verifyError(testCase, @() hs3Engine.solve( ...
    initialState, terminalState, limits, options, pathConstraints), ...
    "hs3Engine:CrossSegmentPathInterval");
end

function testObstaclePlannerUsesNonuniformSeedMesh(testCase)
% Exercise the obstacle planner's separate HS3 kernel and corridor mapping.
initialState = struct( ...
    "time_s", 0, "position_deg", [-4 3], ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 8, "position_deg", [4 3], ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [3 3], ...
    "maxAcceleration_deg_s2", [2 2], ...
    "maxJerk_deg_s3", [3 3], ...
    "azimuthInterval_deg", [-10 10], ...
    "elevationInterval_deg", [-10 10]);
vertices_deg = [-1 -1; 1 -1; 1 1; -1 1];
obstacle = obstacleAvoidance.obstacles.createObstacle( ...
    "static below route", [0; 8], ...
    {vertices_deg(:, 1); vertices_deg(:, 1)}, ...
    {vertices_deg(:, 2); vertices_deg(:, 2)}, 0);
segmentBreakTau = [0; 0.08; 0.3; 0.55; 0.82; 1];
seed = struct( ...
    "Index", 1, "Source", "visibilityGraph", ...
    "position_deg", [-4 3; 0 3; 4 3], ...
    "tau", [0; 0.5; 1], "EstimatedDuration_s", 8, ...
    "Length_deg", 8, "UsesReducedGeometry", false, ...
    "SegmentBreakTau", segmentBreakTau);
options = struct( ...
    "GoalTimeMode", "fixedArrival", "SampleTime_s", 0.05, ...
    "AllowAzimuthWrapping", false, "CollocationSegmentCount", 5, ...
    "MaximumNlpIterations", 150, ...
    "MaximumNlpFunctionEvaluations", 15000, ...
    "MaximumSolverTime_s", 20, "ArrivalTimeTolerance_s", 1e-3, ...
    "ConstraintTolerance", 1e-7, "OptimalityTolerance", 1e-7, ...
    "StepTolerance", 1e-10, ...
    "CollisionClearanceTolerance_deg", 1e-7, "Verbose", false);

candidate = obstacleAvoidance.planner.solveRouteCandidate( ...
    obstacle, initialState, goalState, limits, options, seed);

verifyTrue(testCase, candidate.OptimizerFeasible, candidate.Message);
verifyEqual(testCase, candidate.Polynomial.SegmentBreakTau, ...
    segmentBreakTau);
verifyLessThanOrEqual(testCase, ...
    candidate.MaximumConstraintViolation, 1e-6);
end
