function tests = testMinimalAzElWorkflow
%% Section 0: Header & Readme
% SYNTAX
%   tests = testMinimalAzElWorkflow
%**************************************************************************
% PURPOSE
%   - Verify the minimal construct, reduce-search, plan, validate, and plot
%     workflow with finite and unlimited jerk.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - tests (MATLAB function-test array)
%       Deterministic tests for the retained public workflow.
%**************************************************************************
% UNITS
%   - Position is degrees and time is seconds.
%**************************************************************************

%% Section 1: Create The Function-Test Suite

root = fileparts(fileparts(mfilename("fullpath")));
addpath(root, fullfile(root, "examples"));
tests = functiontests(localfunctions);
end

%% Section 2: Local Test Cases

function testDenseObstacleIsReducedOnlyForSearch(testCase)
result = exampleAzElPlanning(struct("FigureVisible", "off", ...
    "PlotOutputs", false, "EnableJerkConstraint", true));
testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
diagnostics = result.candidateReductionDiagnostics;
inputVertexCount = sum([diagnostics.InputVertexCount]);
selectedCandidateCount = sum([diagnostics.SelectedCandidateCount]);
testCase.verifyGreaterThan(inputVertexCount, 1000);
testCase.verifyLessThan(selectedCandidateCount, 0.01 * inputVertexCount);
blocked = queryAzElTimedPathCollision(result.obstacleField, ...
    result.timedSlopePath.time_s, result.timedSlopePath.position_deg);
testCase.verifyFalse(any(blocked));
testCase.verifyTrue(result.timedSlopePath.ConstraintDiagnostics. ...
    FiniteJerkCertified);
end

function testUnlimitedJerkIsReportedHonestly(testCase)
result = exampleAzElPlanning(struct("FigureVisible", "off", ...
    "PlotOutputs", false, "EnableJerkConstraint", false));
testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
testCase.verifyFalse(result.timedSlopePath.ConstraintDiagnostics. ...
    FiniteJerkCertified);
testCase.verifyTrue(all(isinf(result.limits.maxJerk_deg_s3)));
testCase.verifyTrue(all(isnan(result.timedSlopePath. ...
    ConstraintDiagnostics.PeakJerk_deg_s3)));
end

function testExampleOptionResolverRejectsStaleControls(testCase)
% Keep display controls local, forward only supported planner options, and
% make ignored names visible to the caller.
defaults = struct("GoalTimeMode", "earliestArrival", ...
    "FigureVisible", "off");
testCase.verifyWarning(@() resolveAzElExampleOptions( ...
    struct("StaleControl", true), defaults, [2.5 2.5]), ...
    "resolveAzElExampleOptions:UnknownOptions");
testCase.verifyError(@() resolveAzElExampleOptions( ...
    struct("PlotOutputs", 2), defaults, [2.5 2.5]), ...
    "resolveAzElExampleOptions:InvalidLogicalControl");

[plannerOptions, configuration] = resolveAzElExampleOptions( ...
    struct("EnableJerkConstraint", false, "Verbose", false), ...
    defaults, [2.5 2.5]);
testCase.verifyEqual(plannerOptions.GoalTimeMode, "earliestArrival");
testCase.verifyFalse(plannerOptions.Verbose);
testCase.verifyFalse(configuration.JerkConstraintEnabled);
testCase.verifyEqual(configuration.MaxJerk_deg_s3, [Inf Inf]);
testCase.verifyFalse(isfield(plannerOptions, "FigureVisible"));
end

function testUnlimitedJerkUShapeDoesNotInsertAccelerationZeros(testCase)
result = exampleUShapedAzElTimeSpace(struct("FigureVisible", "off", ...
    "PlotOutputs", false, "EnableJerkConstraint", false, ...
    "Verbose", false));
testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.ExampleValidation.Passed, ...
    result.ExampleValidation.Message);
timedPath = result.timedSlopePath;
tangentialAcceleration_deg_s2 = ...
    timedPath.SampleTangentialAcceleration_deg_s2;
artificialZero = abs(tangentialAcceleration_deg_s2(2:end - 1)) < 1e-12 & ...
    abs(tangentialAcceleration_deg_s2(1:end - 2)) > 1e-4 & ...
    abs(tangentialAcceleration_deg_s2(3:end)) > 1e-4;
testCase.verifyEqual(nnz(artificialZero), 0, ...
    "Spatial profile joins must not inject one-sample acceleration zeros.");
for profileIndex = 1:numel(timedPath.SegmentProfiles)
    profile = timedPath.SegmentProfiles(profileIndex);
    testCase.verifyEqual(profile.PhaseStartAcceleration_deg_s2(1), ...
        profile.TangentialAcceleration_deg_s2, "AbsTol", 1e-12);
end
testCase.verifyLessThan(timedPath.MinimumMotionDuration_s, 30);
testCase.verifyTrue(all(isnan(timedPath.jerk_deg_s3), "all"));
blocked = queryAzElTimedPathCollision(result.obstacleField, ...
    timedPath.time_s, timedPath.position_deg);
testCase.verifyFalse(any(blocked));
jerkConstrainedResult = exampleUShapedAzElTimeSpace(struct( ...
    "FigureVisible", "off", "PlotOutputs", false, ...
    "EnableJerkConstraint", true, "Verbose", false));
testCase.verifyTrue(jerkConstrainedResult.Success, ...
    jerkConstrainedResult.Message);
testCase.verifyEqual(jerkConstrainedResult.limits.maxJerk_deg_s3, ...
    [2.5 2.5]);
testCase.verifyTrue(jerkConstrainedResult.timedSlopePath. ...
    ConstraintDiagnostics.FiniteJerkCertified);
testCase.verifyGreaterThan( ...
    jerkConstrainedResult.timedSlopePath.MinimumMotionDuration_s, ...
    timedPath.MinimumMotionDuration_s);
end

function testOpeningUWaitsAndBeatsClosedDetour(testCase)
result = exampleOpeningUShapedAzElTimeSpace(struct( ...
    "FigureVisible", "off", ...
    "PlotOutputs", false, ...
    "EnableJerkConstraint", true, ...
    "UseParallel", "off", ...
    "Verbose", false));

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.ExampleValidation.Passed, ...
    result.ExampleValidation.Message);
testCase.verifyTrue(result.OpeningValidation.Passed, ...
    result.OpeningValidation.Message);
testCase.verifyTrue(result.OpeningValidation.DelayedDeparture);
testCase.verifyTrue(result.OpeningValidation.SelectedDirectGeometry);
testCase.verifyTrue(result.OpeningValidation.CrossedOpenGap);
testCase.verifyTrue( ...
    result.OpeningValidation.OpeningWasFasterThanDetour);
testCase.verifyGreaterThan(result.OpeningValidation.TimeSaved_s, 0);
testCase.verifyEqual(result.timedSlopePath.DepartureCandidateTime_s, ...
    result.timedSlopePath.MotionStartTime_s, "AbsTol", 1e-12);

holdMask = result.timedSlopePath.time_s <= ...
    result.timedSlopePath.MotionStartTime_s;
heldPosition_deg = result.timedSlopePath.position_deg(holdMask, :);
testCase.verifyEqual(heldPosition_deg, repmat( ...
    result.initialState.position_deg, size(heldPosition_deg, 1), 1), ...
    "AbsTol", 1e-12);
blocked = queryAzElTimedPathCollision(result.obstacleField, ...
    result.timedSlopePath.time_s, result.timedSlopePath.position_deg, ...
    struct("TimePaddingSamples", 0, "BoundaryIsOccupied", false));
testCase.verifyFalse(any(blocked));
end

function testTranslatedObstacleUsesGeneralTimeGrid(testCase)
initialAzimuth_deg = [-1; 1; 1; -1];
initialElevation_deg = [-12; -12; 12; 12];
clearedElevation_deg = initialElevation_deg + 15;
obstacle = makeAzElObstacleData( ...
    "translating rectangle", [0; 4; 30], ...
    {initialAzimuth_deg; initialAzimuth_deg; initialAzimuth_deg}, ...
    {initialElevation_deg; clearedElevation_deg; ...
    clearedElevation_deg}, 0.1);

initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-5 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 30, ...
    "position_deg", [5 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [Inf Inf]);
options = struct( ...
    "CollisionTimePaddingSamples", 0, ...
    "UseParallel", "off");

result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
testCase.verifyEqual( ...
    result.SearchDiagnostics.DepartureTimeCandidates_s, [0; 4; 30]);
testCase.verifyEqual(size(result.selectedRoute_deg, 1), 2);
testCase.verifyTrue(queryAzElTimeObstacle( ...
    result.obstacleField, 0, 0, 0));
testCase.verifyFalse(queryAzElTimeObstacle( ...
    result.obstacleField, 0, 0, 4));
testCase.verifyGreaterThan( ...
    result.timedSlopePath.DepartureCandidateTime_s, 0);
testCase.verifyLessThan( ...
    result.timedSlopePath.DepartureCandidateTime_s, 4);
blocked = queryAzElTimedPathCollision( ...
    result.obstacleField, result.timedSlopePath.time_s, ...
    result.timedSlopePath.position_deg, struct( ...
    "TimePaddingSamples", 0, "BoundaryIsOccupied", false));
testCase.verifyFalse(any(blocked));
end

function testHybridCollisionScreenStillRequiresContinuousValidation(testCase)
defaults = planAzElMotion();
testCase.verifyEqual(defaults.CollisionValidationMode, "hybrid");
testCase.verifyEqual(defaults.MaximumVisibilitySnapshotsPerObstacle, 4);
testCase.verifyTrue(defaults.DetectSnapshotEvents);
testCase.verifyEqual(defaults.SnapshotProbeEdgeCount, 4);
testCase.verifyEqual(defaults.SnapshotCountChangeThreshold, 0.10);
testCase.verifyEqual(defaults.SnapshotEdgeRotationThreshold_deg, 5);
testCase.verifyEqual(defaults.SnapshotBoundaryMotionThreshold_deg, 1);
testCase.verifyEqual(defaults.MaximumCollisionPrefilterSamples, 80);
testCase.verifyEqual(defaults.MinimumContinuouslyValidatedCandidates, 2);
testCase.verifyFalse(defaults.ContinueAfterFirstFeasible);
testCase.verifyEqual(defaults.MaximumTemporalRefinementSteps, Inf);
testCase.verifyEqual(defaults.MaximumPlanningTime_s, Inf);
testCase.verifyEqual(defaults.OptimalityTolerance_s, 0.05);
testCase.verifyEmpty(defaults.TemporalRefinementSampleTimes_s);
testCase.verifyEqual(defaults.VisibilityGraphCostChangeThreshold, 0.05);

obstacle = makeAzElObstacleData( ...
    "blocking rectangle", [0; 20], ...
    {[-0.25; 0.25; 0.25; -0.25]; ...
    [-0.25; 0.25; 0.25; -0.25]}, ...
    {[-1; -1; 1; 1]; [-1; -1; 1; 1]}, 0.05);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-1 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 20, ...
    "position_deg", [1 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [Inf Inf]);
options = struct( ...
    "CollisionValidationMode", "hybrid", ...
    "MaximumCollisionPrefilterSamples", 2, ...
    "UseParallel", "off");

result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
testCase.verifyEqual(result.Options.CollisionValidationMode, "hybrid");
testCase.verifyEqual( ...
    result.Options.MaximumCollisionPrefilterSamples, 2);
testCase.verifyTrue(result.SearchDiagnostics. ...
    ContinuousCollisionRequiredForSuccess);
testCase.verifyTrue(result.candidateDiagnostics. ...
    CollisionPrefilterApplied(1));
testCase.verifyTrue(result.candidateDiagnostics. ...
    CollisionPrefilterPassed(1));
testCase.verifyTrue(result.candidateDiagnostics. ...
    ContinuousCollisionChecked(1));
testCase.verifyEqual(result.candidateDiagnostics. ...
    CollisionValidationStatus(1), "continuousCollision");
testCase.verifyTrue(result.candidateDiagnostics. ...
    ContinuousCollisionChecked(result.selectedCandidateIndex));
testCase.verifyEqual(result.candidateDiagnostics. ...
    CollisionValidationStatus(result.selectedCandidateIndex), ...
    "continuousClear");
blocked = queryAzElTimedPathCollision( ...
    result.obstacleField, result.timedSlopePath.time_s, ...
    result.timedSlopePath.position_deg);
testCase.verifyFalse(any(blocked));

continuousResult = planAzElMotion( ...
    obstacle, initialState, goalState, limits, struct( ...
    "CollisionValidationMode", "continuous", ...
    "UseParallel", "off"));
testCase.verifyTrue(continuousResult.Success, continuousResult.Message);
testCase.verifyFalse(any(continuousResult.candidateDiagnostics. ...
    CollisionPrefilterApplied));
testCase.verifyTrue(continuousResult.candidateDiagnostics. ...
    ContinuousCollisionChecked(1));
end

function testAdaptiveTemporalRefinementRecoversFailure(testCase)
sampleTime_s = [0; 2; 4; 6; 8];
wallAzimuth_deg = repmat({[-0.4; 0.4; 0.4; -0.4]}, 5, 1);
blockingElevation_deg = [-8; -8; 8; 8];
clearElevation_deg = [10; 10; 26; 26];
wallElevation_deg = {blockingElevation_deg; blockingElevation_deg; ...
    clearElevation_deg; clearElevation_deg; blockingElevation_deg};
obstacle = makeAzElObstacleData( ...
    "temporary wall", sampleTime_s, wallAzimuth_deg, ...
    wallElevation_deg, 0.05);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-2 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 8, ...
    "position_deg", [2 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [2 2], ...
    "maxJerk_deg_s3", [Inf Inf]);

recoveredResult = planAzElMotion( ...
    obstacle, initialState, goalState, limits, struct( ...
    "MaximumVisibilitySnapshotsPerObstacle", 2, ...
    "DetectSnapshotEvents", false, ...
    "CollisionTimePaddingSamples", 0, ...
    "UseParallel", "off"));

history = recoveredResult.SearchDiagnostics. ...
    TemporalRefinementHistory;
testCase.verifyTrue(recoveredResult.Success, recoveredResult.Message);
testCase.verifyGreaterThan(numel(history), 1);
testCase.verifyFalse(history(1).Success);
testCase.verifyTrue(history(end).Success);
testCase.verifyTrue(any(ismember([history.Trigger], [ ...
    "automaticAfterFailure" "collisionDirected" ...
    "connectivityDirected"])));
testCase.verifyTrue(recoveredResult.SearchDiagnostics. ...
    TemporalRefinementPerformed);
testCase.verifyNotEmpty(recoveredResult.SearchDiagnostics. ...
    AdaptiveRefinementSampleTimes_s);
testCase.verifyTrue(all(ismember( ...
    recoveredResult.SearchDiagnostics.AdaptiveRefinementSampleTimes_s, ...
    sampleTime_s)));
blocked = queryAzElTimedPathCollision( ...
    recoveredResult.obstacleField, recoveredResult.timedSlopePath.time_s, ...
    recoveredResult.timedSlopePath.position_deg, struct( ...
    "TimePaddingSamples", 0, "BoundaryIsOccupied", false));
testCase.verifyFalse(any(blocked));

monotoneElevation_deg = {blockingElevation_deg; ...
    blockingElevation_deg + 4; blockingElevation_deg + 8; ...
    clearElevation_deg; clearElevation_deg};
changingObstacle = makeAzElObstacleData( ...
    "opening wall", sampleTime_s, wallAzimuth_deg, ...
    monotoneElevation_deg, 0.05);
optionalGoalState = goalState;
optionalGoalState.time_s = 20;
optionalResult = planAzElMotion( ...
    changingObstacle, initialState, optionalGoalState, limits, struct( ...
    "MaximumVisibilitySnapshotsPerObstacle", 2, ...
    "DetectSnapshotEvents", false, ...
    "ContinueAfterFirstFeasible", true, ...
    "MaximumTemporalRefinementSteps", 1, ...
    "CollisionTimePaddingSamples", 0, ...
    "UseParallel", "off"));

optionalHistory = optionalResult.SearchDiagnostics. ...
    TemporalRefinementHistory;
testCase.verifyTrue(optionalResult.Success, optionalResult.Message);
testCase.verifyEqual(numel(optionalHistory), 2);
testCase.verifyTrue(optionalResult.SearchDiagnostics. ...
    TemporalRefinementPerformed);
testCase.verifyEqual(optionalResult.SearchDiagnostics. ...
    TemporalRefinementStoppedBecause, "refinementStepLimit");
testCase.verifyFalse(optionalResult.SearchDiagnostics.OptimalityProven);
testCase.verifyGreaterThanOrEqual(optionalResult.SearchDiagnostics. ...
    UnresolvedTemporalIntervalCount, 1);
end

function testTemporalStepLimitReportsIncompleteMovingSearch(testCase)
sampleTime_s = (0:2:8).';
wallAzimuth_deg = repmat({[-0.4; 0.4; 0.4; -0.4]}, 5, 1);
blockingElevation_deg = [-8; -8; 8; 8];
wallElevation_deg = repmat({blockingElevation_deg}, 5, 1);
wallElevation_deg{3} = [10; 10; 26; 26];
obstacle = makeAzElObstacleData( ...
    "temporary wall", sampleTime_s, wallAzimuth_deg, ...
    wallElevation_deg, 0.05);
initialState = struct( ...
    "time_s", 0, "position_deg", [-2 0], ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 8, "position_deg", [2 0], ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [2 2], ...
    "maxJerk_deg_s3", [Inf Inf]);

result = planAzElMotion(obstacle, initialState, goalState, limits, struct( ...
    "MaximumVisibilitySnapshotsPerObstacle", 2, ...
    "DetectSnapshotEvents", false, ...
    "MaximumTemporalRefinementSteps", 0, ...
    "CollisionTimePaddingSamples", 0, ...
    "UseParallel", "off"));

testCase.verifyFalse(result.Success);
testCase.verifyEqual(result.TerminationReason, "temporalSearchIncomplete");
testCase.verifyEqual(result.SearchDiagnostics. ...
    TemporalRefinementStoppedBecause, "refinementStepLimit");
testCase.verifyGreaterThan(result.SearchDiagnostics. ...
    UnresolvedTemporalIntervalCount, 0);
testCase.verifyGreaterThan(result.SearchDiagnostics. ...
    OmittedSourceSampleCount, 0);
testCase.verifyFalse(result.SearchDiagnostics. ...
    ContinuousTemporalCoverageCertified);
end

function testPlotConsumesResultWithoutReplanning(testCase)
result = exampleAzElPlanning(struct("FigureVisible", "off", ...
    "PlotOutputs", false));
handles = plotAzElMotion(result, struct("FigureVisible", "off", ...
    "FrameStride", 1000, "Pause_s", 0));
cleanup = onCleanup(@() close([handles.WorkspaceFigure ...
    handles.VisibilityGraphs.Figure handles.KinematicsFigure ...
    handles.Animation.Figure]));
testCase.verifyTrue(isgraphics(handles.WorkspaceFigure));
testCase.verifyTrue(isgraphics(handles.VisibilityGraphs.Figure));
testCase.verifyTrue(isgraphics(handles.VisibilityGraphs.OverviewAxes));
testCase.verifyTrue(isgraphics(handles.VisibilityGraphs.SnapshotAxes));
testCase.verifyTrue(isgraphics(handles.KinematicsFigure));
testCase.verifyEqual(numel(handles.KinematicsAxes), 4);
testCase.verifyTrue(isgraphics(handles.Animation.Figure));
testCase.verifyTrue(isgraphics(handles.Animation.Axes3D));
testCase.verifyTrue(isgraphics(handles.Animation.Axes2D));

graphs = result.SearchDiagnostics.VisibilityGraphs;
testCase.verifyGreaterThan(numel(graphs), 1);
blockedTestWasRetained = false;
for graphIndex = 1:numel(graphs)
    graph = graphs(graphIndex);
    blockedTestWasRetained = blockedTestWasRetained || ...
        any(graph.VisibilityBlockedMask, "all");
    testCase.verifyEqual(graph.VisibilityTestedMask, ...
        graph.VisibilityTestedMask.');
    testCase.verifyEqual(graph.VisibilityBlockedMask, ...
        graph.VisibilityBlockedMask.');
    testCase.verifyFalse(any(graph.VisibilityBlockedMask & ...
        ~graph.VisibilityTestedMask, "all"));
end
testCase.verifyTrue(blockedTestWasRetained);

requestedTime_s = mean([graphs.Time_s]);
set(handles.VisibilityGraphs.TimeEdit, ...
    "String", sprintf("%.12g", requestedTime_s));
callback = get(handles.VisibilityGraphs.GoButton, "Callback");
callback(handles.VisibilityGraphs.GoButton, []);
[~, expectedSnapshotIndex] = min(abs([graphs.Time_s] - requestedTime_s));
testCase.verifyEqual(getappdata(handles.VisibilityGraphs.Figure, ...
    "SelectedSnapshotIndex"), expectedSnapshotIndex);

% Return to the first graph after visiting the second. Hidden graph
% artists must be replaced, not accumulated behind the new snapshot.
set(handles.VisibilityGraphs.TimeEdit, ...
    "String", sprintf("%.12g", graphs(1).Time_s));
callback(handles.VisibilityGraphs.GoButton, []);
firstSnapshotChildCount = numel(allchild( ...
    handles.VisibilityGraphs.SnapshotAxes));
nextCallback = get(handles.VisibilityGraphs.NextButton, "Callback");
previousCallback = get( ...
    handles.VisibilityGraphs.PreviousButton, "Callback");
nextCallback(handles.VisibilityGraphs.NextButton, []);
previousCallback(handles.VisibilityGraphs.PreviousButton, []);
testCase.verifyEqual(getappdata(handles.VisibilityGraphs.Figure, ...
    "SelectedSnapshotIndex"), 1);
testCase.verifyEqual(numel(allchild( ...
    handles.VisibilityGraphs.SnapshotAxes)), ...
    firstSnapshotChildCount, ...
    "Previous/Next must replace hidden graph artists instead of stacking them.");
end

function testMovingPointHistoryUsesSameObstacleConstructor(testCase)
squareAzimuth_deg = {[-2; 0; 0; -2], [1; 3; 3; 1]};
squareElevation_deg = {[-1; -1; 1; 1], [-1; -1; 1; 1]};
obstacle = makeAzElObstacleData("moving obstacle", [0; 20], ...
    squareAzimuth_deg, squareElevation_deg, 0);
field = buildAzElTimeObstacleField(obstacle);
testCase.verifyTrue(queryAzElTimeObstacle(field, -1, 0, 0));
testCase.verifyTrue(queryAzElTimeObstacle(field, 2, 0, 20));
testCase.verifyFalse(queryAzElTimeObstacle(field, -1, 0, 20));
initialState = struct("time_s", 0, "position_deg", [-4 3]);
goalState = struct("time_s", 20, "position_deg", [4 3]);
limits = struct("maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], "maxJerk_deg_s3", [Inf Inf]);
result = planAzElMotion(obstacle, initialState, goalState, limits);
testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
end

function testContinuousMovingObstacleCollisionIsNotSliceAliased(testCase)
leftSquareAzimuth_deg = [-3; -1; -1; -3];
rightSquareAzimuth_deg = [1; 3; 3; 1];
squareElevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData( ...
    "crossing square", [0; 10], ...
    {leftSquareAzimuth_deg; rightSquareAzimuth_deg}, ...
    {squareElevation_deg; squareElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);

testCase.verifyTrue(queryAzElTimeObstacle( ...
    obstacleField, 0, 0, 5));
fullCrossing = queryAzElTimedPathCollision( ...
    obstacleField, [0; 10], [0 0; 0 0], struct( ...
    "TimePaddingSamples", 0));
earlyClear = queryAzElTimedPathCollision( ...
    obstacleField, [0; 2], [0 0; 0 0], struct( ...
    "TimePaddingSamples", 0));
testCase.verifyTrue(any(fullCrossing));
testCase.verifyFalse(any(earlyClear));
end

function testSameTimePathBatchMatchesIndividualSegmentQueries(testCase)
squareAzimuth_deg = [-1; 1; 1; -1];
squareElevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData( ...
    "static square", [0; 10], ...
    {squareAzimuth_deg; squareAzimuth_deg}, ...
    {squareElevation_deg; squareElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
pathPosition_deg = [-3 2; -2 0; 0 0; 2 0; 3 2];

[~, batchedDetails] = queryAzElTimedPathCollision( ...
    obstacleField, 5, pathPosition_deg);
individualSegmentOccupied = false(size(pathPosition_deg, 1) - 1, 1);
for segmentIndex = 1:numel(individualSegmentOccupied)
    [~, individualDetails] = queryAzElTimedPathCollision( ...
        obstacleField, [5; 5], ...
        pathPosition_deg(segmentIndex:segmentIndex + 1, :));
    individualSegmentOccupied(segmentIndex) = ...
        individualDetails.SegmentOccupied;
end

testCase.verifyEqual( ...
    batchedDetails.SegmentOccupied, individualSegmentOccupied);
testCase.verifyEqual(batchedDetails.SegmentOccupied, ...
    [false; true; true; false]);
end

function testCachedTopologyMatchesLegacyCompleteTraversal(testCase)
outerAzimuth_deg = [-4; 4; 4; -4];
outerElevation_deg = [-3; -3; 3; 3];
innerAzimuth_deg = [-1; -1; 1; 1];
innerElevation_deg = [-1; 1; 1; -1];
firstAzimuth_deg = [outerAzimuth_deg; NaN; innerAzimuth_deg];
firstElevation_deg = [outerElevation_deg; NaN; innerElevation_deg];
lastAzimuth_deg = firstAzimuth_deg + 2;
lastElevation_deg = firstElevation_deg + 0.5;
obstacle = makeAzElObstacleData( ...
    "moving ring", [0; 10], ...
    {firstAzimuth_deg; lastAzimuth_deg}, ...
    {firstElevation_deg; lastElevation_deg}, 0);
blockedField = buildAzElTimeObstacleField(obstacle);

legacyField = blockedField;
legacyField.Obstacles = rmfield( ...
    legacyField.Obstacles, "TopologyMatchesNext");

queryTime_s = linspace(0, 10, 121).';
queryAzimuth_deg = linspace(-6, 8, 121).';
queryElevation_deg = 2.5 * sin(queryTime_s);
blockedQuery = queryAzElTimeObstacle( ...
    blockedField, queryAzimuth_deg, queryElevation_deg, queryTime_s);
legacyQuery = queryAzElTimeObstacle( ...
    legacyField, queryAzimuth_deg, queryElevation_deg, queryTime_s);
testCase.verifyEqual(blockedQuery, legacyQuery);

pathPosition_deg = [queryAzimuth_deg, queryElevation_deg];
blockedPath = queryAzElTimedPathCollision( ...
    blockedField, queryTime_s, pathPosition_deg);
legacyPath = queryAzElTimedPathCollision( ...
    legacyField, queryTime_s, pathPosition_deg);
testCase.verifyEqual(blockedPath, legacyPath);
testCase.verifyTrue(blockedField.Obstacles.TopologyMatchesNext(1));

firstDuplicateAzimuth_deg = [0; 0; 2; 2];
firstDuplicateElevation_deg = [0; 0; 0; 2];
lastDuplicateAzimuth_deg = [0; 2; 2; 2];
lastDuplicateElevation_deg = [0; 0; 2; 2];
changedDuplicate = makeAzElObstacleData( ...
    "changed duplicate", [0; 10], ...
    {firstDuplicateAzimuth_deg; lastDuplicateAzimuth_deg}, ...
    {firstDuplicateElevation_deg; lastDuplicateElevation_deg}, 0);
changedDuplicateField = buildAzElTimeObstacleField(changedDuplicate);
testCase.verifyFalse( ...
    changedDuplicateField.Obstacles.TopologyMatchesNext(1));
end

function testAsynchronousObstacleTimesShareVisibilityGraph(testCase)
firstObstacle = makeAzElObstacleData( ...
    "first", [0; 10], [-2; -1; -1; -2], ...
    [-1; -1; 1; 1], 0);
secondObstacle = makeAzElObstacleData( ...
    "second", [5; 15], [1; 2; 2; 1], ...
    [-1; -1; 1; 1], 0);
obstacleField = buildAzElTimeObstacleField( ...
    {firstObstacle, secondObstacle});
initialState = struct("time_s", 0, "position_deg", [-4 3]);
goalState = struct("time_s", 15, "position_deg", [4 3]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct("UseParallel", "off"));
testCase.verifyEqual([search.VisibilityGraphs.Time_s], [0 5 10 15]);
for graphIndex = [2 3]
    obstacleIndex = unique(search.VisibilityGraphs(graphIndex). ...
        NodeObstacleIndex(3:end));
    testCase.verifyEqual(obstacleIndex(:), [1; 2]);
end
end

function testVisibilitySnapshotsAreUncappedByDefault(testCase)
sampleTime_s = (0:20).';
squareAzimuth_deg = repmat({[-1; 1; 1; -1]}, numel(sampleTime_s), 1);
squareElevation_deg = repmat({[-1; -1; 1; 1]}, ...
    numel(sampleTime_s), 1);
obstacle = makeAzElObstacleData( ...
    "sampled square", sampleTime_s, ...
    squareAzimuth_deg, squareElevation_deg, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-3 2]);
goalState = struct("time_s", 20, "position_deg", [3 2]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct("UseParallel", "off"));
testCase.verifyEqual(numel(search.VisibilityGraphs), ...
    numel(sampleTime_s));
testCase.verifyEqual(search.Options.MaximumSnapshotsPerObstacle, Inf);
end

function testVisibilitySearchAddsOnlyRequestedLocalSnapshot(testCase)
sampleTime_s = (0:20).';
squareAzimuth_deg = repmat({[-1; 1; 1; -1]}, ...
    numel(sampleTime_s), 1);
squareElevation_deg = repmat({[-1; -1; 1; 1]}, ...
    numel(sampleTime_s), 1);
obstacle = makeAzElObstacleData( ...
    "sampled square", sampleTime_s, ...
    squareAzimuth_deg, squareElevation_deg, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-3 2]);
goalState = struct("time_s", 20, "position_deg", [3 2]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct( ...
    "MaximumSnapshotsPerObstacle", 2, ...
    "RequiredSnapshotTimes_s", 9, ...
    "UseParallel", "off"));

testCase.verifyEqual([search.VisibilityGraphs.Time_s], [0 9 20]);
testCase.verifyEqual(search.SnapshotDiagnostics.RetainedSampleIndex, ...
    [1; 10; 21]);
testCase.verifyEqual(search.SnapshotDiagnostics.RequiredSampleIndex, 10);
testCase.verifyEqual(search.SnapshotDiagnostics.RetainedSnapshotCount, 3);
end

function testSnapshotEventsPromoteRotatingBoundarySlices(testCase)
sampleTime_s = (0:5).';
basePosition_deg = [-1 -1; 1 -1; 1 1; -1 1];
rotation_deg = [0; 0; 20; 20; 20; 20];
azimuth_deg = cell(numel(sampleTime_s), 1);
elevation_deg = cell(numel(sampleTime_s), 1);
for sampleIndex = 1:numel(sampleTime_s)
    rotationMatrix = [cosd(rotation_deg(sampleIndex)), ...
        -sind(rotation_deg(sampleIndex)); ...
        sind(rotation_deg(sampleIndex)), ...
        cosd(rotation_deg(sampleIndex))];
    rotatedPosition_deg = basePosition_deg * rotationMatrix.';
    azimuth_deg{sampleIndex} = rotatedPosition_deg(:, 1);
    elevation_deg{sampleIndex} = rotatedPosition_deg(:, 2);
end
obstacle = makeAzElObstacleData( ...
    "rotating square", sampleTime_s, azimuth_deg, elevation_deg, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-3 2]);
goalState = struct("time_s", 5, "position_deg", [3 2]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct( ...
    "MaximumSnapshotsPerObstacle", 2, ...
    "DetectSnapshotEvents", true, ...
    "SnapshotProbeEdgeCount", 4, ...
    "SnapshotEdgeRotationThreshold_deg", 5, ...
    "SnapshotBoundaryMotionThreshold_deg", Inf, ...
    "UseParallel", "off"));

testCase.verifyEqual([search.VisibilityGraphs.Time_s], [0 1 2 5]);
testCase.verifyEqual(search.SnapshotDiagnostics.EventSampleIndex, [2; 3]);
eventDiagnostics = search.SnapshotDiagnostics.EventDiagnostics;
testCase.verifyGreaterThan(eventDiagnostics.MaximumEdgeRotation_deg(3), 5);
testCase.verifyTrue(eventDiagnostics.RotationThresholdCrossed(3));
testCase.verifyFalse(any(eventDiagnostics.TopologyChanged));
end

function testSnapshotEventsPromoteIslandSplit(testCase)
sampleTime_s = (0:3).';
singleAzimuth_deg = [-2; 2; 2; -2];
singleElevation_deg = [-1; -1; 1; 1];
splitAzimuth_deg = [-2; -0.5; -0.5; -2; NaN; 0.5; 2; 2; 0.5];
splitElevation_deg = [-1; -1; 1; 1; NaN; -1; -1; 1; 1];
obstacle = makeAzElObstacleData( ...
    "splitting obstacle", sampleTime_s, ...
    {singleAzimuth_deg; singleAzimuth_deg; ...
    splitAzimuth_deg; splitAzimuth_deg}, ...
    {singleElevation_deg; singleElevation_deg; ...
    splitElevation_deg; splitElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-3 2]);
goalState = struct("time_s", 3, "position_deg", [3 2]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct( ...
    "MaximumSnapshotsPerObstacle", 2, ...
    "SnapshotEdgeRotationThreshold_deg", Inf, ...
    "SnapshotBoundaryMotionThreshold_deg", Inf, ...
    "UseParallel", "off"));

eventDiagnostics = search.SnapshotDiagnostics.EventDiagnostics;
testCase.verifyEqual(eventDiagnostics.IslandCount, [1; 1; 2; 2]);
testCase.verifyTrue(eventDiagnostics.TopologyChanged(3));
testCase.verifyEqual(search.SnapshotDiagnostics.EventSampleIndex, [2; 3]);
testCase.verifyEqual([search.VisibilityGraphs.Time_s], [0 1 2 3]);
end

function testInfeasibleEndpointSpeedReturnsStableFailure(testCase)
initialState = struct( ...
    "time_s", 0, "position_deg", [0 0], ...
    "velocity_deg_s", [3 0]);
goalState = struct( ...
    "time_s", 10, "position_deg", [5 0], ...
    "velocity_deg_s", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2 2]);

result = planAzElMotion([], initialState, goalState, limits);
testCase.verifyFalse(result.Success);
testCase.verifyEqual(result.TerminationReason, "noFeasibleCandidate");
testCase.verifyTrue(contains(result.candidateDiagnostics.Message(1), ...
    "endpoint speed", "IgnoreCase", true));
end

function testParallelPolygonReductionMatchesSerial(testCase)
squareAzimuth_deg = {[-2; 0; 0; -2], [-1; 1; 1; -1], ...
    [1; 3; 3; 1]};
squareElevation_deg = {[-1; -1; 1; 1], [-1; -1; 1; 1], ...
    [-1; -1; 1; 1]};
obstacle = makeAzElObstacleData( ...
    "moving obstacle", [0; 10; 20], squareAzimuth_deg, ...
    squareElevation_deg, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-4 3]);
goalState = struct("time_s", 20, "position_deg", [4 3]);

serialSearch = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, ...
    struct("UseParallel", "off"));
parallelSearch = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, ...
    struct("UseParallel", "on"));

testCase.verifyEqual(serialSearch.ParallelExecution.RequestedMode, "off");
testCase.verifyEqual(parallelSearch.ParallelExecution.RequestedMode, "on");
testCase.verifyGreaterThan(parallelSearch.ParallelExecution.TaskCount, 1);
testCase.verifyEqual(numel(parallelSearch.VisibilityGraphs), ...
    numel(serialSearch.VisibilityGraphs));
testCase.verifyEqual(parallelSearch.CandidatePointsAzElTime, ...
    serialSearch.CandidatePointsAzElTime, "AbsTol", 1e-12);

for snapshotIndex = 1:numel(serialSearch.VisibilityGraphs)
    serialGraph = serialSearch.VisibilityGraphs(snapshotIndex);
    parallelGraph = parallelSearch.VisibilityGraphs(snapshotIndex);
    testCase.verifyEqual(parallelGraph.Success, serialGraph.Success);
    testCase.verifyEqual(parallelGraph.PathPosition_deg, ...
        serialGraph.PathPosition_deg, "AbsTol", 1e-12);
    testCase.verifyEqual(parallelGraph.PathCost_deg, ...
        serialGraph.PathCost_deg, "AbsTol", 1e-12);
    testCase.verifyEqual(parallelGraph.CandidateActiveMask, ...
        serialGraph.CandidateActiveMask);
end
end

function testTwoVertexRegionsWarnAndAreRemoved(testCase)
validAzimuth_deg = [-2; 0; 0; -2];
validElevation_deg = [-1; -1; 1; 1];
twoVertexAzimuth_deg = [5; 6];
twoVertexElevation_deg = [0; 0];
azimuth_deg = [validAzimuth_deg; NaN; twoVertexAzimuth_deg];
elevation_deg = [validElevation_deg; NaN; twoVertexElevation_deg];

lastwarn("");
obstacle = makeAzElObstacleData( ...
    "mixed regions", [0; 10], azimuth_deg, elevation_deg, 0);
[warningMessage, warningIdentifier] = lastwarn;
testCase.verifyEqual(string(warningIdentifier), ...
    "normalizeAzElTimeObstacleData:RemovedTwoVertexRegions");
testCase.verifyTrue(contains(warningMessage, "two-vertex regions"));
testCase.verifyEqual(nnz(isfinite(obstacle.az_deg{1})), 4);
testCase.verifyEqual(nnz(isfinite(obstacle.originalAz_deg{1})), 4);

obstacleField = buildAzElTimeObstacleField(obstacle);
testCase.verifyTrue(queryAzElTimeObstacle(obstacleField, -1, 0, 5));
testCase.verifyFalse(queryAzElTimeObstacle(obstacleField, 5.5, 0, 5));

lastwarn("");
emptyObstacle = makeAzElObstacleData( ...
    "only two vertices", [0; 10], ...
    twoVertexAzimuth_deg, twoVertexElevation_deg, 0);
[~, warningIdentifier] = lastwarn;
testCase.verifyEqual(string(warningIdentifier), ...
    "normalizeAzElTimeObstacleData:RemovedTwoVertexRegions");
testCase.verifyEmpty(emptyObstacle.az_deg{1});
testCase.verifyEmpty(emptyObstacle.el_deg{1});
end

function testFourCirclesAndMovingTargetAreValidated(testCase)
result = exampleFourAcceleratingCircles(struct( ...
    "FigureVisible", "off", ...
    "PlotOutputs", false, ...
    "EnableJerkConstraint", true, ...
    "Verbose", false));

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.ExampleValidation.Passed, ...
    result.ExampleValidation.Message);
testCase.verifyTrue(result.CircleMotionValidation.Passed);
testCase.verifyTrue(result.MovingTargetValidation.Passed);
testCase.verifyTrue(result.InterceptValidation.Passed);
testCase.verifyEqual(result.TargetMotion.ModelType, "sampledTrajectory");
testCase.verifyFalse(result.InterceptOptions.MatchTargetVelocity);
testCase.verifyEqual(numel(result.originalAzElData), 4);

testCase.verifyGreaterThan(result.MovingTargetValidation.TargetTravel_deg, 0);
testCase.verifyGreaterThan( ...
    result.MovingTargetValidation.TargetSpeedAtIntercept_deg_s, 0);
testCase.verifyEqual(result.TargetPositionAtIntercept_deg, ...
    result.targetPosition_deg(end, :), "AbsTol", 1e-10);
testCase.verifyEqual(result.timedSlopePath.position_deg(end, :), ...
    result.TargetPositionAtIntercept_deg, "AbsTol", 1e-7);

centerAzimuth_deg = result.circleCenterAzimuth_deg;
centerElevation_deg = result.circleCenterElevation_deg;
diameter_deg = 2 * result.circleRadius_deg;
testCase.verifyEqual(diff(centerAzimuth_deg([1 2])), ...
    diameter_deg, "AbsTol", 1e-12);
testCase.verifyEqual(diff(centerAzimuth_deg([3 4])), ...
    diameter_deg, "AbsTol", 1e-12);

[~, midpointIndex] = min(abs(result.obstacleTime_s - ...
    0.5 * result.obstacleMotionDuration_s));
midpointStep_deg = hypot(diff(centerAzimuth_deg), ...
    diff(centerElevation_deg(midpointIndex, :)));
testCase.verifyEqual(midpointStep_deg, ...
    repmat(diameter_deg, 1, 3), "AbsTol", 1e-12);

[~, motionEndIndex] = min(abs(result.obstacleTime_s - ...
    result.obstacleMotionDuration_s));
endpointRows = [1 motionEndIndex];
testCase.verifyEqual(result.circleCenterVelocity_deg_s( ...
    endpointRows, :), zeros(2, 4), "AbsTol", 1e-12);
testCase.verifyEqual(result.circleCenterAcceleration_deg_s2( ...
    endpointRows, :), zeros(2, 4), "AbsTol", 1e-12);
testCase.verifyGreaterThan(max( ...
    result.circleCenterVelocity_deg_s(:, 1:2), [], "all"), 0);
testCase.verifyLessThan(min( ...
    result.circleCenterVelocity_deg_s(:, 3:4), [], "all"), 0);

collision = queryAzElTimedPathCollision(result.obstacleField, ...
    result.timedSlopePath.time_s, result.timedSlopePath.position_deg);
testCase.verifyFalse(any(collision));
testCase.verifyTrue(result.timedSlopePath.ConstraintDiagnostics. ...
    FiniteJerkCertified);
end

function testTargetExitsObstacleExampleInBothJerkModes(testCase)
jerkModes = [true false];
referenceTargetPosition_deg = zeros(0, 2);
for modeIndex = 1:numel(jerkModes)
    jerkConstraintEnabled = jerkModes(modeIndex);
    result = exampleTargetExitsObstacle(struct( ...
        "FigureVisible", "off", ...
        "PlotOutputs", false, ...
        "EnableJerkConstraint", jerkConstraintEnabled, ...
        "Verbose", false));

    testCase.verifyTrue(result.Success, result.Message);
    testCase.verifyTrue(result.ExampleValidation.Passed, ...
        result.ExampleValidation.Message);
    testCase.verifyTrue(result.ScenarioValidation.Passed);
    testCase.verifyTrue(result.ScenarioValidation.TargetStartsInside);
    testCase.verifyTrue(result.ScenarioValidation.TargetWaitedInside);
    testCase.verifyTrue(result.ScenarioValidation.TargetEventuallyExits);
    testCase.verifyTrue(result.ScenarioValidation.TargetIsClearAtIntercept);
    testCase.verifyTrue(result.ScenarioValidation.TransitCircleIsBetween);
    testCase.verifyTrue(any(result.directBlocked));
    testCase.verifyEqual(numel(result.originalAzElData), 2);
    testCase.verifyEqual(result.randomSeed, 17);
    testCase.verifyGreaterThan(std(result.postWaitStep_deg(:, 1)), 0);
    testCase.verifyEqual(result.timedSlopePath.position_deg(end, :), ...
        result.TargetPositionAtIntercept_deg, "AbsTol", 1e-7);

    if modeIndex == 1
        referenceTargetPosition_deg = result.targetPosition_deg;
    else
        testCase.verifyEqual(result.targetPosition_deg, ...
            referenceTargetPosition_deg, "AbsTol", 0);
    end

    collision = queryAzElTimedPathCollision(result.obstacleField, ...
        result.timedSlopePath.time_s, result.timedSlopePath.position_deg);
    testCase.verifyFalse(any(collision));
    testCase.verifyEqual(result.timedSlopePath.ConstraintDiagnostics. ...
        FiniteJerkCertified, jerkConstraintEnabled);
end

frameExitResult = exampleTargetExitsObstacle(struct( ...
    "FigureVisible", "off", ...
    "PlotOutputs", false, ...
    "EnableJerkConstraint", false, ...
    "AzimuthInterval_deg", [-10 10], ...
    "Verbose", false));
testCase.verifyFalse(frameExitResult.Success);
testCase.verifyTrue(frameExitResult.ExampleValidation.Passed, ...
    frameExitResult.ExampleValidation.Message);
testCase.verifyEqual(frameExitResult.TerminationReason, ...
    "targetLeftAzElFrame");
testCase.verifyTrue(frameExitResult.TargetLeftFrameBeforeIntercept);
testCase.verifyTrue(isfinite(frameExitResult.TargetFrameExitTime_s));
testCase.verifyTrue(isnan(frameExitResult.InterceptTime_s));
testCase.verifyTrue(contains(frameExitResult.Message, "Cannot catch up"));
end

function testStraightTargetAlternatesAcrossFourShapes(testCase)
result = exampleStraightTargetAlternatingOcclusion(struct( ...
    "FigureVisible", "off", ...
    "PlotOutputs", false, ...
    "EnableJerkConstraint", true, ...
    "Verbose", false));

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.ExampleValidation.Passed, ...
    result.ExampleValidation.Message);
testCase.verifyTrue(result.ScenarioValidation.Passed);
testCase.verifyTrue(result.ScenarioValidation.TargetTrackIsStraight);
testCase.verifyTrue(result.ScenarioValidation.AlternationIsPresent);
testCase.verifyTrue(result.ScenarioValidation.ShapeProbesPassed);
testCase.verifyTrue(result.ScenarioValidation.BoresightIsFaster);
testCase.verifyTrue(result.ScenarioValidation.InterceptInInterShapeGap);
testCase.verifyTrue(result.ScenarioValidation.InterceptTargetIsClear);
testCase.verifyTrue(result.ScenarioValidation.CatchOccurredBeforeTrackEnd);
testCase.verifyLessThan(result.ScenarioValidation.TargetSpeed_deg_s, ...
    min(result.limits.maxVelocity_deg_s));
testCase.verifyEqual(result.ScenarioValidation.BlockedRunCount, 5);
testCase.verifyEqual(result.ScenarioValidation.ClearRunCount, 5);
testCase.verifyEqual(result.ScenarioValidation.OccupancyTransitionCount, 9);
testCase.verifyEqual(result.ScenarioValidation.ProbeOccupied, ...
    logical([1; 1; 1; 1; 0; 1; 0]));
testCase.verifyEqual(result.ScenarioValidation. ...
    ProbeBlockingObstacleIndex, uint32([1; 2; 3; 4; 0; 4; 0]));
testCase.verifyTrue(any(result.directBlocked));

collision = queryAzElTimedPathCollision(result.obstacleField, ...
    result.timedSlopePath.time_s, result.timedSlopePath.position_deg);
testCase.verifyFalse(any(collision));
testCase.verifyTrue(result.timedSlopePath.ConstraintDiagnostics. ...
    FiniteJerkCertified);
end

function testMovingObstacleInterceptUsesKinematicPrefilter(testCase)
obstacleTime_s = [0; 20];
obstacleAzimuth_deg = {[-1; 1; 1; -1]; [-1; 1; 1; -1]};
obstacleElevation_deg = { [8; 8; 10; 10]; [9; 9; 11; 11] };
obstacle = makeAzElObstacleData("moving distant square", ...
    obstacleTime_s, obstacleAzimuth_deg, obstacleElevation_deg, 0);

targetTime_s = (0:2:20).';
targetMotion = struct( ...
    "time_s", targetTime_s, ...
    "position_deg", [8 + 0.08 * targetTime_s, ...
        0.4 * sin(0.25 * targetTime_s)], ...
    "InterpolationMethod", "pchip");
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2 2]);
options = struct( ...
    "InterceptMode", "earliestArrival", ...
    "MaximumSearchDuration_s", 20, ...
    "InitialSearchStep_s", 1, ...
    "SearchTimeTolerance_s", 1e-3, ...
    "MatchTargetVelocity", false, ...
    "PlannerOptions", struct( ...
        "UseParallel", "off", "Verbose", false));

result = planAzElMovingTargetIntercept( ...
    obstacle, initialState, targetMotion, limits, options);

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.InterceptValidation.Passed, ...
    result.InterceptValidation.Message);
testCase.verifyTrue(result.SearchDiagnostics.KinematicPrefilterApplied);
testCase.verifyGreaterThan( ...
    result.SearchDiagnostics.KinematicPrunedCandidateCount, 0);
testCase.verifyLessThan( ...
    result.SearchDiagnostics.FullValidationCandidateCount, ...
    result.SearchDiagnostics.TargetCandidateCount);
testCase.verifyLessThan( ...
    result.SearchDiagnostics.FullPlannerEvaluationCount, ...
    result.SearchDiagnostics.TargetCandidateCount);
testCase.verifyTrue(isfinite( ...
    result.SearchDiagnostics.InterpolatedCandidateTime_s));
testCase.verifyEqual(result.SearchDiagnostics.SearchMethod, ...
    "interpolatedKinematicPrefilterAndValidatedScan");

blocked = queryAzElTimedPathCollision(result.obstacleField, ...
    result.timedSlopePath.time_s, result.timedSlopePath.position_deg);
testCase.verifyFalse(any(blocked));
end

function testBlockedEndpointReturnsStableFailure(testCase)
azimuth_deg = [-1; 1; 1; -1];
elevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData("obstacle", [0; 20], ...
    azimuth_deg, elevation_deg, 0);
initialState = struct("time_s", 0, "position_deg", [0 0]);
goalState = struct("time_s", 20, "position_deg", [4 0]);
limits = struct("maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], "maxJerk_deg_s3", [2 2]);
result = planAzElMotion(obstacle, initialState, goalState, limits);
testCase.verifyFalse(result.Success);
testCase.verifyEqual(result.TerminationReason, "endpointBlocked");
testCase.verifyFalse(isempty(result.SearchDiagnostics));
handles = plotAzElMotion(result, struct("FigureVisible", "off"));
cleanup = onCleanup(@() close([handles.WorkspaceFigure ...
    handles.VisibilityGraphs.Figure handles.KinematicsFigure]));
testCase.verifyTrue(isgraphics(handles.WorkspaceFigure));
testCase.verifyTrue(isgraphics(handles.VisibilityGraphs.Figure));
end
