function tests = testFixedDurationAffineModel
%% Section 0: Header & Readme
% Prove the shared fixed-duration affine model is a mechanical identity.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
% Add the repository root for package-based test execution.
repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(repositoryRoot);
testCase.TestData.RepositoryRoot = repositoryRoot;
end

function testSimpleKnotModelMatchesDirectConversion(testCase)
% Cover the route-sized quintic with simple interior knots.
spanDuration_s = [0.7; 1.1; 0.9];
controlPointCount = numel(spanDuration_s) + 5;
verifyModelIdentity( ...
    testCase, controlPointCount, 2.5, spanDuration_s);
end

function testDoubledKnotCompactModelMatchesDirectConversion(testCase)
% Cover the compact C3 eight-span, twenty-control representation.
spanDuration_s = ones(8, 1) / 8;
verifyModelIdentity(testCase, 20, 0, spanDuration_s);
end

function testEmptySamplesRetainControlCoordinateCount(testCase)
% Prevent empty affine models from falling back to a hard-coded two axes.
model = ...
    azElPlannerMethods.corridor.internal.motion.buildFixedDurationAffineModel( ...
    8, 1, [0.5; 0.75; 1.25], zeros(0, 1));
verifySize(testCase, model.PositionBasis, [0 8]);
verifySize(testCase, model.VelocityBasis, [0 8]);
verifySize(testCase, model.AccelerationBasis, [0 8]);
verifySize(testCase, model.JerkBasis, [0 8]);
end

function testCompactReferenceBasesScaleToPhysicalDuration(testCase)
% Prove the cached unit-duration Compact C3 bases obey the chain rule.
spanCount = 8;
controlPointCount = 20;
normalizedSampleTime = linspace(0, 1, 257).';
referenceModel = ...
    azElPlannerMethods.corridor.internal.motion.buildFixedDurationAffineModel( ...
    controlPointCount, 0, ones(spanCount, 1) / spanCount, ...
    normalizedSampleTime);
physicalDuration_s = 3.7;
initialTime_s = 4.2;
physicalSampleTime_s = initialTime_s + ...
    physicalDuration_s * normalizedSampleTime;
physicalModel = ...
    azElPlannerMethods.corridor.internal.motion.buildFixedDurationAffineModel( ...
    controlPointCount, initialTime_s, ...
    physicalDuration_s / spanCount * ones(spanCount, 1), ...
    physicalSampleTime_s);
durationScale = referenceModel.ReferenceDuration_s / physicalDuration_s;

verifyEqual(testCase, referenceModel.PositionBasis, ...
    physicalModel.PositionBasis, "AbsTol", 1e-10);
verifyEqual(testCase, referenceModel.VelocityBasis * durationScale, ...
    physicalModel.VelocityBasis, ...
    "AbsTol", 1e-9, "RelTol", 1e-11);
verifyEqual(testCase, ...
    referenceModel.AccelerationBasis * durationScale^2, ...
    physicalModel.AccelerationBasis, ...
    "AbsTol", 1e-9, "RelTol", 1e-11);
verifyEqual(testCase, referenceModel.JerkBasis * durationScale^3, ...
    physicalModel.JerkBasis, ...
    "AbsTol", 1e-9, "RelTol", 1e-11);
end

function verifyModelIdentity( ...
        testCase, controlPointCount, initialTime_s, spanDuration_s)
% Compare direct and shared coefficient, sample, and decision maps.
segmentBoundary_s = initialTime_s + [0; cumsum(spanDuration_s)];
sampleTime_s = unique([ ...
    linspace(initialTime_s, segmentBoundary_s(end), 113).'; ...
    segmentBoundary_s]);
model = ...
    azElPlannerMethods.corridor.internal.motion.buildFixedDurationAffineModel( ...
    controlPointCount, initialTime_s, spanDuration_s, sampleTime_s);
directUnitPolynomial = ...
    azElPlannerMethods.corridor.internal.motion.convertBsplineToPolynomial( ...
    eye(controlPointCount), 5, initialTime_s, spanDuration_s);

verifyEqual(testCase, model.Degree, 5);
verifyEqual(testCase, model.VariableControlIndex, ...
    4:controlPointCount - 3);
verifyEqual(testCase, model.FixedControlIndex, ...
    [1:3, controlPointCount - 2:controlPointCount]);
verifyEqual(testCase, model.VariableControlCount, controlPointCount - 6);
verifyEqual(testCase, model.ReferenceDuration_s, sum(spanDuration_s), ...
    "AbsTol", 1e-14);
verifyEqual(testCase, model.SampleTime_s, sampleTime_s);
verifyPolynomial(testCase, model.UnitControlPolynomial, directUnitPolynomial);

[~, directPositionBasis, directVelocityBasis, ...
    directAccelerationBasis, directJerkBasis] = ...
    azElPlannerMethods.corridor.internal.motion.evaluatePolynomial( ...
    directUnitPolynomial, sampleTime_s);
verifyEqual(testCase, model.PositionBasis, directPositionBasis, ...
    "AbsTol", 1e-10);
verifyEqual(testCase, model.VelocityBasis, directVelocityBasis, ...
    "AbsTol", 1e-9);
verifyEqual(testCase, model.AccelerationBasis, ...
    directAccelerationBasis, "AbsTol", 1e-9);
verifyEqual(testCase, model.JerkBasis, directJerkBasis, ...
    "AbsTol", 1e-9);

controlIndex = (1:controlPointCount).';
controlPoint_deg = [ ...
    0.2 * controlIndex + sin(controlIndex), ...
    -0.3 * controlIndex + cos(0.5 * controlIndex)];
directPolynomial = ...
    azElPlannerMethods.corridor.internal.motion.convertBsplineToPolynomial( ...
    controlPoint_deg, 5, initialTime_s, spanDuration_s);
[~, directPosition_deg, directVelocity_deg_s, ...
    directAcceleration_deg_s2, directJerk_deg_s3] = ...
    azElPlannerMethods.corridor.internal.motion.evaluatePolynomial( ...
    directPolynomial, sampleTime_s);
verifyEqual(testCase, model.PositionBasis * controlPoint_deg, ...
    directPosition_deg, "AbsTol", 1e-10);
verifyEqual(testCase, model.VelocityBasis * controlPoint_deg, ...
    directVelocity_deg_s, "AbsTol", 1e-9, "RelTol", 1e-11);
verifyEqual(testCase, model.AccelerationBasis * controlPoint_deg, ...
    directAcceleration_deg_s2, "AbsTol", 1e-9, "RelTol", 1e-11);
verifyEqual(testCase, model.JerkBasis * controlPoint_deg, ...
    directJerk_deg_s3, "AbsTol", 1e-9, "RelTol", 1e-11);

azimuthDecisionIndex = 1:model.VariableControlCount;
elevationDecisionIndex = ...
    model.VariableControlCount + azimuthDecisionIndex;
decision_deg = linspace( ...
    -0.2, 0.2, 2 * model.VariableControlCount).';
perturbedControlPoint_deg = controlPoint_deg;
perturbedControlPoint_deg(model.VariableControlIndex, 1) = ...
    perturbedControlPoint_deg(model.VariableControlIndex, 1) + ...
    decision_deg(azimuthDecisionIndex);
perturbedControlPoint_deg(model.VariableControlIndex, 2) = ...
    perturbedControlPoint_deg(model.VariableControlIndex, 2) + ...
    decision_deg(elevationDecisionIndex);
perturbedPosition_deg = model.PositionBasis * perturbedControlPoint_deg;
affinePosition_deg = model.PositionBasis * controlPoint_deg;
affinePosition_deg(:, 1) = affinePosition_deg(:, 1) + ...
    model.PositionBasis(:, model.VariableControlIndex) * ...
    decision_deg(azimuthDecisionIndex);
affinePosition_deg(:, 2) = affinePosition_deg(:, 2) + ...
    model.PositionBasis(:, model.VariableControlIndex) * ...
    decision_deg(elevationDecisionIndex);
verifyEqual(testCase, affinePosition_deg, perturbedPosition_deg, ...
    "AbsTol", 1e-10);
perturbedPolynomial = ...
    azElPlannerMethods.corridor.internal.motion.convertBsplineToPolynomial( ...
    perturbedControlPoint_deg, 5, initialTime_s, spanDuration_s);
deltaControlPoint_deg = perturbedControlPoint_deg - controlPoint_deg;
fieldNames = [ ...
    "positionPower_deg", "velocityPower_deg_s", ...
    "accelerationPower_deg_s2", "jerkPower_deg_s3"];

for fieldIndex = 1:numel(fieldNames)
    name = fieldNames(fieldIndex);
    affineCoefficient = directPolynomial.(name) + ...
        applyControlMap( ...
        model.UnitControlPolynomial.(name), deltaControlPoint_deg);
    if fieldIndex == 1
        verifyEqual(testCase, affineCoefficient, ...
            perturbedPolynomial.(name), "AbsTol", 1e-10);
    else
        verifyEqual(testCase, affineCoefficient, ...
            perturbedPolynomial.(name), ...
            "AbsTol", 1e-9, "RelTol", 1e-11);
    end
end
end

function coefficient = applyControlMap(unitCoefficient, controlPoint_deg)
% Apply an identity-control coefficient map to two physical coordinates.
segmentCount = size(unitCoefficient, 1);
coefficientCount = size(unitCoefficient, 3);
controlPointCount = size(unitCoefficient, 2);
coefficient = zeros(segmentCount, 2, coefficientCount);

for segmentIndex = 1:segmentCount
    basisCoefficient = reshape( ...
        unitCoefficient(segmentIndex, :, :), ...
        controlPointCount, coefficientCount);

    for axisIndex = 1:2
        coefficient(segmentIndex, axisIndex, :) = ...
            controlPoint_deg(:, axisIndex).' * basisCoefficient;
    end
end
end

function verifyPolynomial(testCase, actual, expected)
% Compare exact identity-control polynomial arrays and time metadata.
verifyEqual(testCase, actual.SegmentCount, expected.SegmentCount);
verifyEqual(testCase, ...
    actual.SegmentStartTime_s, expected.SegmentStartTime_s, ...
    "AbsTol", 1e-14);
verifyEqual(testCase, actual.SegmentDuration_s, ...
    expected.SegmentDuration_s, "AbsTol", 1e-14);
verifyEqual(testCase, actual.FinalTime_s, expected.FinalTime_s, ...
    "AbsTol", 1e-14);
verifyEqual(testCase, actual.positionPower_deg, ...
    expected.positionPower_deg, "AbsTol", 1e-10);
verifyEqual(testCase, actual.velocityPower_deg_s, ...
    expected.velocityPower_deg_s, "AbsTol", 1e-9);
verifyEqual(testCase, actual.accelerationPower_deg_s2, ...
    expected.accelerationPower_deg_s2, "AbsTol", 1e-9);
verifyEqual(testCase, actual.jerkPower_deg_s3, ...
    expected.jerkPower_deg_s3, "AbsTol", 1e-9);
end
