function tests = testStaticActivePairBmtp
%% Section 0: Header & Readme
% SYNTAX: results = runtests('tests/testStaticActivePairBmtp.m')
% PURPOSE: Regress collision-driven static BMTP on structurally different concave and multi-obstacle routes.
% INPUTS: MATLAB unit test framework.
% OUTPUTS: Independent validation and solver-representation checks.
% UNITS: Coordinate units and seconds.
tests=functiontests(localfunctions);
end

function setupOnce(~)
    root=fileparts(fileparts(mfilename('fullpath')));
    addpath(root,fullfile(root,'trajectory'));
end

function testConcaveCavityEscape(testCase)
    angle_rad=linspace(pi/3,5*pi/3,10).';
    vertices_units=[8*cos(angle_rad),8*sin(angle_rad); ...
        4*cos(flipud(angle_rad)),4*sin(flipud(angle_rad))];
    obstacle=obstacleAvoidance.obstacles.createObstacle( ...
        'C cavity',[0;260],vertices_units(:,1),vertices_units(:,2),0.1);
    limits=struct('xInterval_units',[-23,23],'yInterval_units',[-23,23], ...
        'maxVelocity_units_s',[2,2],'maxAcceleration_units_s2',[0.8,0.8], ...
        'maxJerk_units_s3',[3,3]);
    result=planner(obstacle,state([0,0],0),state([-13,0],260),limits,options());
    verifyValidatedStaticBmtp(testCase,result);
end

function testSeparatedSlalomBarriers(testCase)
    center_units=[-6,-2.5;0,2.5;6,-2.5];
    obstacleList=cell(3,1);
    for obstacleIndex=1:3
        vertices_units=center_units(obstacleIndex,:)+[-0.7,-3;0.7,-3;0.7,3;-0.7,3];
        obstacleList{obstacleIndex}=obstacleAvoidance.obstacles.createObstacle( ...
            "barrier "+obstacleIndex,[0;110],vertices_units(:,1),vertices_units(:,2),0.1);
    end
    obstacles=obstacleAvoidance.obstacles.combineObstacles(obstacleList{:});
    limits=struct('xInterval_units',[-17,17],'yInterval_units',[-10,10], ...
        'maxVelocity_units_s',[2,2],'maxAcceleration_units_s2',[1,1], ...
        'maxJerk_units_s3',[2,2]);
    result=planner(obstacles,state([-13,0],0),state([13,0],110),limits,options());
    verifyValidatedStaticBmtp(testCase,result);
    verifyTrue(testCase,result.Diagnostics.SolverDiagnostics.TravelRefinementAccepted);
end

function testAffinePlaneBlockConsolidation(testCase)
    limits=struct('xInterval_units',[-100,100],'yInterval_units',[-100,100]);
    source=plane([1,0;0.5,0.5],[-2,-2]);
    target=plane(0.5*source.Normal,[-1.1,-1.1]);
    reduced=bmtpEngine.separation.removeRedundantPlanes([source,target],limits,0.1,true);
    verifyTrue(testCase,reduced(1).Active);
    verifyFalse(testCase,reduced(2).Active);
end

function testAffinePlaneNeedsOneEndpointWeight(testCase)
    limits=struct('xInterval_units',[-10,10],'yInterval_units',[-10,10]);
    source=plane([1,0;1,0],[0,0]);
    differentEndpointScale=plane([0.5,0;0.75,0],[0,0]);
    reduced=bmtpEngine.separation.removeRedundantPlanes( ...
        [source,differentEndpointScale],limits,0,true);
    verifyTrue(testCase,all([reduced.Active]));
end

function testStaticMeshIgnoresCollinearSeedVertices(testCase)
    limits=struct('xInterval_units',[-10,10],'yInterval_units',[-10,10], ...
        'maxVelocity_units_s',[2,2],'maxAcceleration_units_s2',[1,1], ...
        'maxJerk_units_s3',[3,3]);
    initial=state([-6,4],0);
    goal=state([6,-1],100);
    normalized=planner([],initial,goal,limits,options());
    route=[initial.position_units;-2,1;goal.position_units];
    midpointRoute=[route(1,:);mean(route(1:2,:),1);route(2,:); ...
        mean(route(2:3,:),1);route(3,:)];
    coverage=struct('Passed',true,'ExactRegionCount',0);
    firstRequest=bmtpEngine.prepareRequest(seed(route), ...
        struct('regions_units', {cell(0,1)}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    secondRequest=bmtpEngine.prepareRequest(seed(midpointRoute), ...
        struct('regions_units', {cell(0,1)}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    firstWarm=bmtpEngine.createStartingCurve(firstRequest);
    secondWarm=bmtpEngine.createStartingCurve(secondRequest);
    verifyEqual(testCase,firstWarm.SegmentCount,12);
    verifyEqual(testCase,secondWarm.SegmentCount,firstWarm.SegmentCount);
    verifyEqual(testCase,secondWarm.Route_units,firstWarm.Route_units,'AbsTol',1e-12);
    verifyEqual(testCase,secondWarm.ControlPoint_units, ...
        firstWarm.ControlPoint_units,'AbsTol',1e-12);
    verifyEqual(testCase,secondWarm.SegmentTime_s, ...
        firstWarm.SegmentTime_s,'AbsTol',1e-12);
end

function testReturnedActivePlanesProveReturnedControls(testCase)
    [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createStaticAlternatingFixture("earliestArrival");
    [result, diagnostics] = bmtpEngine.optimization.solveActivePairTrajectory( ...
        request, warmStart, diagnostics, target_units, roundoffReserve_units);
    verifyTrue(testCase, result.Success, result.SolverMessage);
    verifyEqual(testCase, result.FailureStage, "");
    verifyEqual(testCase, result.FailureKind, "");
    verifyFalse(testCase, result.AlternativeGuideEligible);
    verifyLessThanOrEqual(testCase, diagnostics.IterationCount, ...
        request.MaximumAlternatingIterations);
    verifyEqual(testCase, size(result.Planes), size(result.TaggedPairs));
    activePairs = reshape([result.Planes.Active], size(result.Planes));
    verifyEqual(testCase, result.TaggedPairs, activePairs);
    for pairIndex = reshape(find(activePairs), 1, [])
        [segmentIndex, regionIndex] = ind2sub(size(result.TaggedPairs), pairIndex);
        checkedPlane = bmtpEngine.separation.verifySeparatingLine( ...
            result.Planes(segmentIndex, regionIndex), ...
            squeeze(result.ControlPoint_units(segmentIndex, :, :)), ...
            request.Regions_units{regionIndex}, roundoffReserve_units, target_units);
        verifyTrue(testCase, checkedPlane.Verified);
    end
    verifyEqual(testCase, diagnostics.ApplicablePairCount, nnz(result.TaggedPairs));
    verifyEqual(testCase, diagnostics.TaggedPairCount, nnz(result.TaggedPairs));
    verifyEqual(testCase, diagnostics.FinalCollisionPairCount, 0);
end

function testRowProofReturnsPlanesThatProveReturnedControls(testCase)
    % The constraint-row proof accepts a motion without per-pair verification;
    % every returned plane must still separate the returned controls exactly.
    [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createStaticAlternatingFixture("fixedArrival");
    [result, diagnostics] = bmtpEngine.optimization.solveAlternatingTrajectory( ...
        request, warmStart, diagnostics, target_units, roundoffReserve_units);
    verifyTrue(testCase, result.Success, result.SolverMessage);
    verifyTrue(testCase, isstruct(result.PreparedMotion));
    verifyTrue(testCase, isstruct(result.Proof));
    verifyEqual(testCase, numel(result.PreparedMotion.SegmentTime_s), ...
        size(result.Proof.RegionActiveBySegment, 1));
    verifyGreaterThan(testCase, diagnostics.ConstraintRowPairVerificationCount, 0);
    verifyEqual(testCase, diagnostics.ExistingPlanePairVerificationCount, 0);
    verifyEqual(testCase, diagnostics.FinalCollisionPairCount, 0);
    activePairs = reshape([result.Planes.Active], size(result.Planes));
    verifyEqual(testCase, result.TaggedPairs, activePairs);
    for pairIndex = reshape(find(activePairs), 1, [])
        [segmentIndex, regionIndex] = ind2sub(size(result.TaggedPairs), pairIndex);
        checkedPlane = bmtpEngine.separation.verifySeparatingLine( ...
            result.Planes(segmentIndex, regionIndex), ...
            squeeze(result.ControlPoint_units(segmentIndex, :, :)), ...
            request.Regions_units{regionIndex}, roundoffReserve_units, target_units);
        verifyTrue(testCase, checkedPlane.Verified);
    end
end

function testSolveRequestRejectsIncompleteCoverage(testCase)
    initial=state([-1,0],0);
    goal=state([1,0],10);
    normalized=planner([],initial,goal,[],struct('GoalTimeMode','fixedArrival'));
    routeSeed=seed([initial.position_units;goal.position_units]);
    verifyError(testCase,@()bmtpEngine.prepareRequest(routeSeed, ...
        struct('regions_units', {cell(0,1)}, 'coverage', struct('ExactRegionCount',1)), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options)), ...
        'bmtpEngine:InvalidExclusionRegions');
    verifyError(testCase,@()bmtpEngine.prepareRequest(routeSeed, ...
        struct('regions_units', {cell(0,1)}, ...
        'coverage', struct('Passed',false,'ExactRegionCount',0)), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options)), ...
        'bmtpEngine:InvalidCoverage');
    region_units=[-0.2,-0.2;0.2,-0.2;0.2,0.2;-0.2,0.2];
    verifyError(testCase,@()bmtpEngine.prepareRequest(routeSeed, ...
        struct('regions_units', {{region_units}}, ...
        'coverage', struct('ExactRegionCount',1, 'ActiveTimeInterval_s',[0,10])), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options)), ...
        'bmtpEngine:InvalidCoverage');
    verifyError(testCase,@()bmtpEngine.prepareRequest(routeSeed, ...
        struct('regions_units', {{region_units}}, ...
        'coverage', struct('ExactRegionCount',1, 'ActiveTimeInterval_s',[100,101], ...
        'EndRegions_units',{{region_units}})), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options)), ...
        'bmtpEngine:InvalidCoverage');
end

function [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createStaticAlternatingFixture(goalTimeMode)
    box_units = [-0.5, -0.5; 0.5, -0.5; 0.5, 0.5; -0.5, 0.5];
    initial   = state([-3, 0], 0);
    goal      = state([3, 0], 60);
    limits = struct( ...
        'xInterval_units',          [-5, 5], ...
        'yInterval_units',          [-5, 5], ...
        'maxVelocity_units_s',      [2, 2], ...
        'maxAcceleration_units_s2', [1, 1], ...
        'maxJerk_units_s3',         [3, 3]);
    normalized = planner([], initial, goal, limits, ...
        struct('GoalTimeMode', goalTimeMode));
    route_units = [initial.position_units; -1, 1.5; 1, 1.5; goal.position_units];
    coverage = struct('Passed', true, 'ExactRegionCount', 1);
    request = bmtpEngine.prepareRequest(seed(route_units), ...
        struct('regions_units', {{box_units}}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    warmStart = bmtpEngine.createStartingCurve(request);
    diagnostics = struct( ...
        'IterationCount',          0, ...
        'Converged',               false, ...
        'ApplicablePairCount',     nnz(warmStart.RegionActiveBySegment), ...
        'TrajectorySocpCount',     0, ...
        'FinalCollisionPairCount', 0, ...
        'PlaneSocpCount',          0, ...
        'SolverMessage',           "");
    roundoffReserve_units = normalized.Diagnostics.SeparationProof.RoundoffReserve_units;
    target_units  = normalized.Diagnostics.SeparationProof.RequiredGap_units - roundoffReserve_units;
end

function verifyValidatedStaticBmtp(testCase,result)
    verifyTrue(testCase,result.Success,result.Message);
    verifyTrue(testCase,obstacleAvoidance.validateTrajectory(result).Passed);
    verifyGreaterThan(testCase,result.Diagnostics.SolverDiagnostics.TaggedPairCount,0);
    verifyGreaterThanOrEqual(testCase, ...
        result.Diagnostics.SolverDiagnostics.TransientPlaneRemovalCount,0);
end

function value=state(position_units,time_s)
    value=struct('time_s',time_s,'position_units',position_units);
end

function value=options()
    value=struct('GoalTimeMode','earliestArrival','SampleTime_s',0.1);
end

function value=seed(route_units)
    edgeLength_units=vecnorm(diff(route_units),2,2);
    value=struct('position_units',route_units, ...
        'tau',[0;cumsum(edgeLength_units)]/sum(edgeLength_units));
end

function value=plane(normal,offset_units)
    value=struct('Active',true,'Verified',true,'ExitFlag',1, ...
        'Normal',normal,'Offset_units',offset_units,'SignedGap_units',1);
end
