function tests = testPassThroughWaypointWarmStart
%% Section 0: Header & Readme
% SYNTAX
%   tests = testPassThroughWaypointWarmStart
%**************************************************************************
% PURPOSE
%   - Verify the native MATLAB non-stopping waypoint-state warm start.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - tests (matlab.unittest function test array)
%**************************************************************************
% UNITS
%   - Position is degrees; derivatives use seconds and degree powers.
%**************************************************************************
tests = functiontests(localfunctions);
end

function setupOnce(~)
% Add the dimension-neutral trajectory engines used by the warm start.
repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(repositoryRoot);
addpath(fullfile(repositoryRoot, "trajectory"));
end

function testMonotoneAxisPassesThroughInteriorWaypoint(testCase)
% A monotone azimuth leg should retain nonzero interior velocity without
% pretending that an unavailable geometric corridor has been certified.
initialState = state(0, [0 0]);
goalState = state(20, [2 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2 2]);
options = obstacleAvoidance.input.resolvePlannerOptions();
seed = struct( ...
    "Index", 1, ...
    "Source", "unitTest", ...
    "position_deg", [0 0; 1 0.5; 2 0], ...
    "tau", [0; 0.5; 1], ...
    "CorridorBoundary_deg", zeros(0, 2), ...
    "EstimatedDuration_s", 2, ...
    "Length_deg", 2 * sqrt(1.25));

candidate = obstacleAvoidance.planner.solvePassThroughSeedCandidate( ...
    initialState, goalState, limits, options, seed, 1);

verifyNotEmpty(testCase, candidate.time_s);
verifyEqual(testCase, candidate.TerminationReason, "corridorUnavailable");
verifyGreaterThan(testCase, abs(candidate.WaypointVelocity_deg_s(2, 1)), 0);
verifyEqual(testCase, candidate.WaypointVelocity_deg_s(2, 2), 0, ...
    "AbsTol", 1e-12);
verifyEqual(testCase, candidate.position_deg(1, :), [0 0], ...
    "AbsTol", 1e-10);
verifyEqual(testCase, candidate.position_deg(end, :), [2 0], ...
    "AbsTol", 1e-10);
verifyGreaterThan(testCase, candidate.SolverDiagnostics.RuckigSolveCount, 0);
verifySize(testCase, candidate.SectionDuration_s, [2 1]);
verifySize(testCase, candidate.SectionTimeSaving_s, [2 1]);
verifyEqual(testCase, candidate.SectionTimeSaving_s, ...
    candidate.InitialSectionDuration_s - candidate.SectionDuration_s, ...
    "AbsTol", 1e-12);
verifyGreaterThan(testCase, sum(candidate.SectionTimeSaving_s), 0);
end

function testFullyReversingRouteUsesCoupledSearch(testCase)
% A route that reverses both axes should avoid redundant scalar probe ladders.
initialState = state(0, [0 0]);
goalState = state(30, [0 -1]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2 2]);
options = obstacleAvoidance.input.resolvePlannerOptions();
position_deg = [0 0; 1 1; -1 2; 0 -1];
edgeLength_deg = vecnorm(diff(position_deg, 1, 1), 2, 2);
seed = struct( ...
    "Index", 1, ...
    "Source", "unitTest", ...
    "position_deg", position_deg, ...
    "tau", [0; cumsum(edgeLength_deg)] / sum(edgeLength_deg), ...
    "CorridorBoundary_deg", zeros(0, 2), ...
    "EstimatedDuration_s", 10, ...
    "Length_deg", sum(edgeLength_deg));

candidate = obstacleAvoidance.planner.solvePassThroughSeedCandidate( ...
    initialState, goalState, limits, options, seed, 1);

verifyNotEmpty(testCase, candidate.time_s);
verifyEqual(testCase, ...
    candidate.SolverDiagnostics.WaypointStateSearchMode, ...
    "coupledReversing");
verifyLessThan(testCase, ...
    candidate.SolverDiagnostics.RuckigSolveCount, 100);
verifyEqual(testCase, candidate.position_deg([1 end], :), ...
    position_deg([1 end], :), "AbsTol", 1e-10);
end

function value = state(time_s, position_deg)
% Create one normalized rest boundary state for a focused engine test.
value = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end
