function tests = testBmtpOptimization
%% Section 0: Header & Readme
% SYNTAX: results = runtests('tests/testBmtpOptimization.m')
% PURPOSE: Preserve BMTP refinement, clock formulations, and solver contracts.
% INPUTS: MATLAB unit test framework.
% OUTPUTS: Function-based test results with independently named cases.
% UNITS: Coordinate units and seconds.

%% Section 1: Register Tests
tests = functiontests(localfunctions);
end

function setupOnce(~)
    root = fileparts(fileparts(mfilename('fullpath')));
    addpath(root, fullfile(root, 'trajectory'), fullfile(root, 'examples'));
end

function testStaticBmtpRefinementContracts(testCase)
    runCases(testCase, { ...
        @thinWallCrossingIsNotPromotedBySampling; @concaveCavityEscape; @separatedSlalomBarriers; ...
        @arrivalImprovementToleranceEndsRefinement; @alternationMayOutlastRequestBeforeShortening; ...
        @provenWallTravelExceedsAcceptedRequest; @returnedActivePlanesProveReturnedControls; ...
        @rowProofReturnsPlanesThatProveReturnedControls; @travelRefinementAddsNewCollisionPlanes});
end

function testTrajectoryStepContracts(testCase)
    [limits, solverOptions] = singleSpanStepFixture();
    runCases(testCase, { ...
        @usableConicIteratePolicy; @(testCase) differentTimeWindowsDoNotConflict(testCase, limits, solverOptions); ...
        @(testCase) singleSpanTimedInfeasibilityReturnsNoMotion(testCase, limits, solverOptions); ...
        @(testCase) singleSpanTimedMotionIsIndependentlyValid(testCase, limits, solverOptions); ...
        @timedTrajectoryStepRetainsSuppliedClock; @unequalSpanClockWithFullEndpointStates; ...
        @constraintGenerationWithTransformedFixedClock; @variationPassDoesNotConsumeFeasibilityBudget; ...
        @constraintGenerationClosesSeveralPairsInOneSpan});
end

function testTimedAlternatingSolverContracts(testCase)
    [fixture.Request, fixture.WarmStart, fixture.Diagnostics, fixture.Target_units, ...
        fixture.RoundoffReserve_units] = createMovingTimedSolveFixture(1);
    runCases(testCase, { ...
        @timedSolverHonorsRequestIterationLimit; @timedSolverReturnsCoherentEmptyRecord; ...
        @timedSolverUsesAvailableUnverifiedSeedLines; ...
        @(testCase) timedSolverRetainsAtomicRecordAfterLaterRejectedTrial(testCase, fixture); ...
        @(testCase) timedSolverRetainsAtomicRecordAfterLaterFailedTrial(testCase, fixture)});
end

function testWarmStartAndMeshContracts(testCase)
    normalized = meshNormalizationFixture();
    sparseRequest = createWaitRequest(1, normalized);
    runCases(testCase, { ...
        @staticMeshIgnoresCollinearSeedVertices; ...
        @(testCase) waitKnotsScaleWithArrivalClock(testCase, sparseRequest); ...
        @(testCase) motionSpanCountIgnoresCellCount(testCase, sparseRequest, normalized); ...
        @(testCase) solveRequestCarriesMinimumArrivalBound(testCase, normalized); ...
        @(testCase) variableClockWarmStartPreservesEventKnots(testCase, normalized); ...
        @variableClockUsesActualMovingCellOverlap});
end

function testSavedDetourArrivalModes(testCase)
    [request, obstacles] = savedDetourFixture();
    runCases(testCase, { ...
        @(testCase) savedDetourUsesGivenDeadline(testCase, request, obstacles); ...
        @(testCase) savedMovingDetourEarliestArrival(testCase, request, obstacles)});
end

function thinWallCrossingIsNotPromotedBySampling(testCase)
    % A wall 1e-5 wide lies between the fixed samples of the straight first
    % iterate, so the sampled overlap check reports it clear. Continuous
    % proof must decide the best plan so far and separate the pair.
    straightControls_units       = zeros(1, 9, 2);
    straightControls_units(1, :, 1) = (0:8) / 8;
    wall_units = [0.0004 -0.1; 0.0005 -0.1; 0.0005 0.1; 0.0004 0.1];
    sampledPairs = bmtpEngine.separation.findSampledObstacleOverlaps(straightControls_units, {wall_units}, ...
        min(wall_units, [], 1), max(wall_units, [], 1), true);
    verifyFalse(testCase, any(sampledPairs, 'all'));

    % The visibility route seeds the solver around the wall, but its first
    % unconstrained iterate is the straight chord through the wall.
    offset_units = 0.005;
    width_units  = 1e-5;
    wall_units   = [offset_units -0.5; offset_units + width_units -0.5; ...
        offset_units + width_units 0.5; offset_units 0.5];
    obstacle = obstacleAvoidance.obstacles.createObstacle('thin wall', 0, wall_units(:, 1), wall_units(:, 2), 0);
    initial  = struct('time_s', 0, 'position_units', [-4 0]);
    goal     = struct('time_s', 30, 'position_units', [4 0]);
    result   = planner(obstacle, initial, goal, thinWallLimits(), struct('GoalTimeMode', 'earliestArrival'));
    verifyTrue(testCase, result.Success, result.Message);
    verifyTrue(testCase, obstacleAvoidance.validateTrajectory(result).Passed);
    verifyEqual(testCase, result.Diagnostics.VisibilityGraph.SearchKind, "initialSpatialSnapshot");
    verifyGreaterThan(testCase, result.Diagnostics.SolverDiagnostics.TaggedPairCount, 0);
end

function concaveCavityEscape(testCase)
    angle_rad=linspace(pi/3,5*pi/3,10).';
    vertices_units=[8*cos(angle_rad),8*sin(angle_rad); ...
        4*cos(flipud(angle_rad)),4*sin(flipud(angle_rad))];
    obstacle=obstacleAvoidance.obstacles.createObstacle( ...
        'C cavity',[0;260],vertices_units(:,1),vertices_units(:,2),0.1);
    limits=struct('xInterval_units',[-23,23],'yInterval_units',[-23,23], ...
        'maxVelocity_units_s',[2,2],'maxAcceleration_units_s2',[0.8,0.8], ...
        'maxJerk_units_s3',[3,3]);
    result=planner(obstacle,state([0,0],0),state([-13,0],260),limits,options());
    verifyValidatedStaticBmtp(testCase,result);
end

function separatedSlalomBarriers(testCase)
    center_units=[-6,-2.5;0,2.5;6,-2.5];
    obstacleList=cell(3,1);
    for obstacleIndex=1:3
        vertices_units=center_units(obstacleIndex,:)+[-0.7,-3;0.7,-3;0.7,3;-0.7,3];
        obstacleList{obstacleIndex}=obstacleAvoidance.obstacles.createObstacle( ...
            "barrier "+obstacleIndex,[0;110],vertices_units(:,1),vertices_units(:,2),0.1);
    end
    obstacles=obstacleAvoidance.obstacles.combineObstacles(obstacleList{:});
    limits=struct('xInterval_units',[-17,17],'yInterval_units',[-10,10], ...
        'maxVelocity_units_s',[2,2],'maxAcceleration_units_s2',[1,1], ...
        'maxJerk_units_s3',[2,2]);
    result=planner(obstacles,state([-13,0],0),state([13,0],110),limits,options());
    verifyValidatedStaticBmtp(testCase,result);
    verifyTrue(testCase,result.Diagnostics.SolverDiagnostics.TravelRefinementAccepted);
end

function arrivalImprovementToleranceEndsRefinement(testCase)
    % An L-shaped wall with both endpoints outside it. The start is above the
    % tall side and the goal sits beside the foot, so the route wraps the top
    % outer corner and runs down the wall. Each rebuild of the separating
    % lines then gains a little less arrival time than the last: refining
    % until a pass gains nothing takes 19 passes here, the default stop 4.
    % Unlike the cavity escape, neither endpoint is enclosed.
    vertices_units=[-8,-6;2,-6;2,-4;0,-4;0,4;-8,4];
    obstacle=obstacleAvoidance.obstacles.createObstacle( ...
        'L wall',[0;120],vertices_units(:,1),vertices_units(:,2),0.1);
    limits=struct('xInterval_units',[-20,20],'yInterval_units',[-10,10], ...
        'maxVelocity_units_s',[2,2],'maxAcceleration_units_s2',[1,1], ...
        'maxJerk_units_s3',[2.5,2.5]);
    initial=state([-4,6],0);
    goal=state([4,-2],120);
    stopped=planner(obstacle,initial,goal,limits,options());
    verifyValidatedStaticBmtp(testCase,stopped);
    stoppedSolver=stopped.Diagnostics.SolverDiagnostics;
    verifyTrue(testCase,stoppedSolver.Converged);
    verifyLessThan(testCase,stoppedSolver.IterationCount, ...
        stoppedSolver.MaximumAlternatingIterations);
    % Refining until a pass gains nothing repeats the same passes and then
    % continues, so it can only arrive earlier, and only by the small gains
    % the default stop gave up. The shortening pass may move either arrival
    % by at most one millionth of its duration.
    exactOptions=options();
    exactOptions.ArrivalImprovementTolerance_s=0;
    exact=planner(obstacle,initial,goal,limits,exactOptions);
    verifyValidatedStaticBmtp(testCase,exact);
    verifyLessThanOrEqual(testCase,stoppedSolver.IterationCount, ...
        exact.Diagnostics.SolverDiagnostics.IterationCount);
    verifyGreaterThanOrEqual(testCase,stopped.ArrivalTime_s, ...
        exact.ArrivalTime_s-1e-4);
    verifyLessThanOrEqual(testCase,stopped.ArrivalTime_s-exact.ArrivalTime_s,0.05);
end

function alternationMayOutlastRequestBeforeShortening(testCase)
    % Five separate walls require turns around alternating ends. First find
    % and validate a motion with a generous request. A horizon at 1.04 x
    % that arrival is feasible because the witness exists; this is a test
    % scenario, not a bound on the alternation. At this horizon HEAD's third
    % SOCP is infeasible, while one relaxed step now finds a motion inside it.
    barrierCount      = 5;
    generousHorizon_s = 200;
    wallCenterX_units = 4 * ((1:barrierCount) - (barrierCount + 1) / 2);
    obstacleList      = cell(barrierCount, 1);
    for obstacleIndex = 1:barrierCount
        centerX_units = wallCenterX_units(obstacleIndex);
        if mod(obstacleIndex, 2) == 1
            lowerY_units = -6;
            upperY_units = 1.2;
        else
            lowerY_units = -1.2;
            upperY_units = 6;
        end
        vertices_units = [centerX_units - 0.5, lowerY_units; ...
            centerX_units + 0.5, lowerY_units; ...
            centerX_units + 0.5, upperY_units; ...
            centerX_units - 0.5, upperY_units];
        obstacleList{obstacleIndex} = obstacleAvoidance.obstacles.createObstacle( ...
            "wall " + obstacleIndex, [0; generousHorizon_s], ...
            vertices_units(:, 1), vertices_units(:, 2), 0.1);
    end
    obstacles = obstacleAvoidance.obstacles.combineObstacles(obstacleList{:});
    startX_units = wallCenterX_units(1) - 3;
    goalX_units  = wallCenterX_units(end) + 3;
    limits = struct( ...
        'xInterval_units',          [startX_units - 2, goalX_units + 2], ...
        'yInterval_units',          [-5, 5], ...
        'maxVelocity_units_s',      [1, 1], ...
        'maxAcceleration_units_s2', [0.75, 0.75], ...
        'maxJerk_units_s3',         [2.5, 2.5]);
    initialState = state([startX_units, 0], 0);
    generousGoal = state([goalX_units, 0], generousHorizon_s);
    generousResult = planner(obstacles, initialState, generousGoal, limits, options());
    verifyValidatedStaticBmtp(testCase, generousResult);

    requestHorizon_s = 1.04 * generousResult.ArrivalTime_s;
    for obstacleIndex = 1:numel(obstacles)
        obstacles(obstacleIndex).time_s(end) = requestHorizon_s;
    end
    tightGoal   = state([goalX_units, 0], requestHorizon_s);
    tightResult = planner(obstacles, initialState, tightGoal, limits, options());
    verifyValidatedStaticBmtp(testCase, tightResult);
    verifyLessThanOrEqual(testCase, tightResult.ArrivalTime_s, requestHorizon_s);
end

function provenWallTravelExceedsAcceptedRequest(testCase)
    % At x = 0, a clear path must reach |y| >= 5 + 0.1 = 5.1 units. It
    % starts and ends at y = 0, so y travel is at least 2 x 5.1 = 10.2
    % units. With |vy| <= 1 unit/s, every detour needs at least 10.2 s.
    % The straight rest-to-rest chord takes about 9.69 s, so a 10 s request
    % passes the free-space timing check and must fail at motion acceptance.
    vertices_units   = [-1, -5; 1, -5; 1, 5; -1, 5];
    requestHorizon_s = 10;
    obstacle = obstacleAvoidance.obstacles.createObstacle( ...
        'tall wall', [0; requestHorizon_s], vertices_units(:, 1), ...
        vertices_units(:, 2), 0.1);
    limits = struct( ...
        'xInterval_units',          [-6, 6], ...
        'yInterval_units',          [-7, 7], ...
        'maxVelocity_units_s',      [1, 1], ...
        'maxAcceleration_units_s2', [0.75, 0.75], ...
        'maxJerk_units_s3',         [2.5, 2.5]);
    initialState = state([-4, 0], 0);
    goalState    = state([4, 0], requestHorizon_s);
    [~, straightSegmentTime_s] = bmtpEngine.motion.createC3Chord( ...
        initialState.position_units, goalState.position_units, limits);
    verifyLessThan(testCase, sum(straightSegmentTime_s), requestHorizon_s);
    verifyLessThan(testCase, requestHorizon_s, 2 * (5 + 0.1) / limits.maxVelocity_units_s(2));

    result = planner(obstacle, initialState, goalState, limits, options());
    verifyFalse(testCase, result.Success);
    verifyEqual(testCase, result.TerminationReason, "timeWindowInfeasible");
    verifyEqual(testCase, result.Diagnostics.FailureStage, "optimization");
    verifyEqual(testCase, result.Diagnostics.FailureKind, "timeWindowInfeasible");
    verifyFalse(testCase, result.Diagnostics.AlternativeGuideEligible);
    verifyTrue(testCase, contains(result.Message, "The collision-free motion needs"));
    verifyTrue(testCase, contains(result.Message, "more than the 10.0 s horizon."));
end

function returnedActivePlanesProveReturnedControls(testCase)
    [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createStaticAlternatingFixture("earliestArrival");
    [result, diagnostics] = bmtpEngine.optimization.solveActivePairTrajectory( ...
        request, warmStart, diagnostics, target_units, roundoffReserve_units);
    verifyTrue(testCase, result.Success, result.SolverMessage);
    verifyEqual(testCase, result.FailureStage, "");
    verifyEqual(testCase, result.FailureKind, "");
    verifyFalse(testCase, result.AlternativeGuideEligible);
    verifyLessThanOrEqual(testCase, diagnostics.IterationCount, ...
        request.MaximumAlternatingIterations);
    verifyEqual(testCase, size(result.Planes), size(result.TaggedPairs));
    activePairs = reshape([result.Planes.Active], size(result.Planes));
    verifyEqual(testCase, result.TaggedPairs, activePairs);
    for pairIndex = reshape(find(activePairs), 1, [])
        [segmentIndex, regionIndex] = ind2sub(size(result.TaggedPairs), pairIndex);
        checkedPlane = bmtpEngine.separation.verifySeparatingLine( ...
            result.Planes(segmentIndex, regionIndex), ...
            squeeze(result.ControlPoint_units(segmentIndex, :, :)), ...
            request.Regions_units{regionIndex}, roundoffReserve_units, target_units);
        verifyTrue(testCase, checkedPlane.Verified);
    end
    verifyEqual(testCase, diagnostics.ApplicablePairCount, nnz(result.TaggedPairs));
    verifyEqual(testCase, diagnostics.TaggedPairCount, nnz(result.TaggedPairs));
    verifyEqual(testCase, diagnostics.FinalCollisionPairCount, 0);
end

function rowProofReturnsPlanesThatProveReturnedControls(testCase)
    % The constraint-row proof accepts a motion without per-pair verification;
    % every returned plane must still separate the returned controls exactly.
    [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createStaticAlternatingFixture("fixedArrival");
    [result, diagnostics] = bmtpEngine.optimization.solveAlternatingTrajectory( ...
        request, warmStart, diagnostics, target_units, roundoffReserve_units);
    verifyTrue(testCase, result.Success, result.SolverMessage);
    verifyTrue(testCase, isstruct(result.PreparedMotion));
    verifyTrue(testCase, isstruct(result.Proof));
    verifyEqual(testCase, numel(result.PreparedMotion.SegmentTime_s), ...
        size(result.Proof.RegionActiveBySegment, 1));
    verifyGreaterThan(testCase, diagnostics.ConstraintRowPairVerificationCount, 0);
    verifyEqual(testCase, diagnostics.ExistingPlanePairVerificationCount, 0);
    verifyEqual(testCase, diagnostics.FinalCollisionPairCount, 0);
    activePairs = reshape([result.Planes.Active], size(result.Planes));
    verifyEqual(testCase, result.TaggedPairs, activePairs);
    for pairIndex = reshape(find(activePairs), 1, [])
        [segmentIndex, regionIndex] = ind2sub(size(result.TaggedPairs), pairIndex);
        checkedPlane = bmtpEngine.separation.verifySeparatingLine( ...
            result.Planes(segmentIndex, regionIndex), ...
            squeeze(result.ControlPoint_units(segmentIndex, :, :)), ...
            request.Regions_units{regionIndex}, roundoffReserve_units, target_units);
        verifyTrue(testCase, checkedPlane.Verified);
    end
end

function travelRefinementAddsNewCollisionPlanes(testCase)
    box_units = [-0.5, -0.5; 0.5, -0.5; 0.5, 0.5; -0.5, 0.5];
    waypoints_units = [-3, 0; -3, 3; 3, 3; 3, 0];
    controls_units = zeros(3, 9, 2);
    for span = 1:3
        points_units = [repmat(waypoints_units(span, :), 4, 1); ...
            mean(waypoints_units(span:span + 1, :), 1); ...
            repmat(waypoints_units(span + 1, :), 4, 1)];
        controls_units(span, :, :) = reshape(points_units, 1, 9, 2);
    end
    plane = struct( ...
        'Active',          false, ...
        'Verified',        false, ...
        'ExitFlag',        NaN, ...
        'Normal',          zeros(2), ...
        'Offset_units',    zeros(1, 2), ...
        'SignedGap_units', NaN, ...
        'TimeFraction',    [0, 1]);
    initial = struct( ...
        'time_s',                0, ...
        'position_units',        waypoints_units(1, :), ...
        'velocity_units_s',      [0, 0], ...
        'acceleration_units_s2', [0, 0]);
    goal = struct( ...
        'time_s',                12, ...
        'position_units',        waypoints_units(end, :), ...
        'velocity_units_s',      [0, 0], ...
        'acceleration_units_s2', [0, 0]);
    limits = struct( ...
        'xInterval_units',          [-10, 10], ...
        'yInterval_units',          [-10, 10], ...
        'maxVelocity_units_s',      [5, 5], ...
        'maxAcceleration_units_s2', [10, 10], ...
        'maxJerk_units_s3',         [20, 20]);
    normalized = planner([], initial, goal, limits, ...
        struct('GoalTimeMode', "earliestArrival"));
    edgeLength_units = vecnorm(diff(waypoints_units), 2, 2);
    seed = struct( ...
        'position_units',    waypoints_units, ...
        'tau',               [0; cumsum(edgeLength_units)] / sum(edgeLength_units), ...
        'UsesVariableClock', true);
    request = bmtpEngine.prepareRequest(seed, ...
        struct('regions_units', {{box_units}}, ...
        'coverage', struct('Passed', true, 'ExactRegionCount', 1, ...
        'BreakTime_s', [initial.time_s; goal.time_s])), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    alternating = bmtpEngine.optimization.createOptimizationResult( ...
        "A complete time-scoped feasible iterate was retained.", "", "", false, ...
        controls_units, [4; 4; 4], repmat(plane, 3, 1), false(3, 1));
    diagnostics = struct('ConicSolver', bmtpEngine.optimization.accumulateConicDiagnostics());
    roundoffReserve_units = normalized.Diagnostics.SeparationProof.RoundoffReserve_units;
    target_units  = normalized.Diagnostics.SeparationProof.RequiredGap_units - roundoffReserve_units;
    [refined, diagnostics] = bmtpEngine.optimization.refineTravel( ...
        request, alternating, [], [], diagnostics, target_units, roundoffReserve_units);
    verifyTrue(testCase, diagnostics.TravelRefinementAccepted);
    verifyGreaterThan(testCase, diagnostics.TaggedPairCount, 0);
    verifyLessThan(testCase, diagnostics.TravelRefinementFinalLength_units, ...
        diagnostics.TravelRefinementInitialLength_units);
    prepared = struct('ControlPoint_units', refined.ControlPoint_units, ...
        'SegmentTime_s', refined.SegmentTime_s(:), ...
        'FinalTime_s', request.InitialState.time_s + sum(refined.SegmentTime_s));
    verifyTrue(testCase, bmtpEngine.validation.checkFinalMotion( ...
        request, prepared, roundoffReserve_units, target_units).Passed);
end

function usableConicIteratePolicy(testCase)
    verifyTrue(testCase,bmtpEngine.optimization.hasUsableConicIterate(0,1));
    verifyTrue(testCase,bmtpEngine.optimization.hasUsableConicIterate(0,-7));
    verifyFalse(testCase,bmtpEngine.optimization.hasUsableConicIterate([],1));
    verifyFalse(testCase,bmtpEngine.optimization.hasUsableConicIterate(NaN,1));
    verifyFalse(testCase,bmtpEngine.optimization.hasUsableConicIterate(0,0));
end

function differentTimeWindowsDoNotConflict(testCase, limits, options)
    initial = struct('time_s',0,'position_units',[-1,0],'velocity_units_s',[0,0],'acceleration_units_s2',[0,0]);
    goal = initial; goal.time_s = 6; goal.position_units = [1,0];
    planes = repmat(struct('Active',true,'Normal',[1,0;1,0],'Offset_units',[0.5,0.5], ...
        'TimeFraction',[0,0.1]),1,2);
    planes(2).Normal = -planes(1).Normal; planes(2).TimeFraction = [0.9,1];
    request = stepRequest(5,initial,goal,limits,options);
    [controls,durations,flag,output,constraintBase] = ...
        bmtpEngine.optimization.solveTrajectoryStep(request, ...
        trajectoryStep(1,planes,1e-8,6));
    verifyTrue(testCase,flag>0 || flag==-7);
    verifyEqual(testCase,durations,6);
    verifyLessThan(testCase,output.MaximumClearanceSlack_units,1e-6);
    first = bmtpEngine.motion.restrictBezier(squeeze(controls),[0,0.1]);
    last = bmtpEngine.motion.restrictBezier(squeeze(controls),[0.9,1]);
    verifyLessThan(testCase,max(first(:,1)),-0.5);
    verifyGreaterThan(testCase,min(last(:,1)),0.5);
    % The same two exclusions overlap in time and are genuinely incompatible.
    planes(1).TimeFraction = [0,1]; planes(2).TimeFraction = [0,1];
    [~,~,flag,output] = bmtpEngine.optimization.solveTrajectoryStep(request, ...
        trajectoryStep(1,planes,1e-8,6));
    verifyTrue(testCase,flag<=0 || output.MaximumClearanceSlack_units>0.4);
    verifyTrue(testCase,output.ConstraintGenerationApplied);
    verifyGreaterThan(testCase,output.SolveCount,1);
    verifyEqual(testCase,output.LoadedPlanePairCount,2);

    reducedStep = trajectoryStep(1,planes(1),1e-8,6);
    reducedStep.ConstraintBase = constraintBase;
    [~,~,~,~,reducedConstraintBase] = ...
        bmtpEngine.optimization.solveTrajectoryStep(request,reducedStep);
    verifyNotEqual(testCase,reducedConstraintBase.Key.VariableCount, ...
        constraintBase.Key.VariableCount);
    verifyEqual(testCase,size(reducedConstraintBase.A,2), ...
        reducedConstraintBase.Key.VariableCount);
end

function singleSpanTimedInfeasibilityReturnsNoMotion(testCase, limits, options)
    planes = repmat(struct('Active',false),1,0);
    % Two units in 0.1 s exceeds the two-units/s velocity bound alone.
    request = stepRequest(8,struct('position_units',[-1,0]),struct('position_units',[1,0.5]),limits,options);
    [controls,duration_s,flag] = bmtpEngine.optimization.solveTrajectoryStep( ...
        request,timedStep(1,planes,1e-8,0.1));
    verifyLessThanOrEqual(testCase,flag,0);
    verifyEmpty(testCase,controls);
    verifyTrue(testCase,isnan(duration_s));
end

function singleSpanTimedMotionIsIndependentlyValid(testCase, limits, options)
    planes = repmat(struct('Active',false),1,0);
    for degree = [5,8]
        for horizon_s = [5,6,8,10]
            request = stepRequest(degree,struct('position_units',[-1,0]), ...
                struct('position_units',[1,0.5]),limits,options);
            [controls,duration_s,flag,output] = bmtpEngine.optimization.solveTrajectoryStep( ...
                request,timedStep(1,planes,1e-8,horizon_s));
            assertNotEmpty(testCase,controls);
            verifyTrue(testCase,flag>0 || flag==-7);
            verifyEqual(testCase,output.OptimizationConverged,flag>0);
            verifyEqual(testCase,duration_s,horizon_s,'AbsTol',1e-12);
            initial = struct('time_s',0,'position_units',[-1,0]);
            goal = struct('time_s',horizon_s,'position_units',[1,0.5]);
            result = planner([],initial,goal,limits,struct('GoalTimeMode','fixedArrival'));
            seed = struct('position_units',[-1,0;1,0.5],'tau',[0;1]);
            request = bmtpEngine.prepareRequest(seed, ...
                struct('regions_units', {cell(0,1)}, ...
                'coverage', struct('Passed',true,'ExactRegionCount',0)), ...
                struct('initialState', result.Inputs.initialState, ...
                'goalState', result.Inputs.goalState, ...
                'limits', result.Diagnostics.Limits, ...
                'options', result.Options));
            prepared = bmtpEngine.motion.createMotion(request,controls,duration_s);
            [~,roundoffReserve_units] = bmtpEngine.validation.createCoordinateTolerances( ...
                controls,limits.xInterval_units,limits.yInterval_units);
            target_units = (1+2^20*eps)*result.Options.CollisionClearanceTolerance_units+roundoffReserve_units;
            motionOutput = bmtpEngine.createMotionOutput(struct(),request,prepared);
            result.time_s                = motionOutput.time_s;
            result.position_units        = motionOutput.position_units;
            result.velocity_units_s      = motionOutput.velocity_units_s;
            result.acceleration_units_s2 = motionOutput.acceleration_units_s2;
            result.jerk_units_s3         = motionOutput.jerk_units_s3;
            result.ArrivalTime_s         = motionOutput.ArrivalTime_s;
            result.MotionLength_units    = motionOutput.MotionLength_units;
            result.Diagnostics.Polynomial                      = motionOutput.Polynomial;
            result.Diagnostics.TrajectoryDuration_s            = motionOutput.TrajectoryDuration_s;
            result.Diagnostics.IntegratedSquaredJerk_units2_s5 = motionOutput.IntegratedSquaredJerk_units2_s5;
            result.Diagnostics.MaximumConstraintViolation      = motionOutput.MaximumConstraintViolation;
            result.Diagnostics.SeparationProof = bmtpEngine.validation.checkFinalMotion( ...
                request,prepared,roundoffReserve_units,target_units);
            result.Diagnostics.Validation = struct("Passed",false, ...
                "Message","Synthetic motion has not been validated.");
            assertTrue(testCase,obstacleAvoidance.validateTrajectory(result).Passed);
        end
    end
end

function timedTrajectoryStepRetainsSuppliedClock(testCase)
    limits=struct('xInterval_units',[-3,3],'yInterval_units',[-3,3], ...
        'maxVelocity_units_s',[2,2],'maxAcceleration_units_s2',[5,5], ...
        'maxJerk_units_s3',[10,10]);
    options=optimoptions('coneprog','Display','none', ...
        'ConstraintTolerance',1e-10,'OptimalityTolerance',1e-9);
    planes=repmat(struct('Active',false),2,0);
    request=stepRequest(5,struct('position_units',[-1,0]),struct('position_units',[1,0]),limits,options);
    [controls,duration_s,flag]=bmtpEngine.optimization.solveTrajectoryStep( ...
        request,timedStep(2,planes,1e-8,[2;6]));
    verifyTrue(testCase,flag>0 || flag==-7);
    verifyNotEmpty(testCase,controls);
    verifyEqual(testCase,duration_s,[2;6],'AbsTol',1e-12);
end

function unequalSpanClockWithFullEndpointStates(testCase)
    initial = struct('position_units',[-1,0],'velocity_units_s',[0.1,-0.1],'acceleration_units_s2',[0.02,0.01]);
    goal = struct('position_units',[1,0.4],'velocity_units_s',[0.2,0.05],'acceleration_units_s2',[-0.01,0.02]);
    limits = struct('xInterval_units',[-2,2],'yInterval_units',[-2,2], ...
        'maxVelocity_units_s',[2,2],'maxAcceleration_units_s2',[5,5],'maxJerk_units_s3',[10,10]);
    options = optimoptions('coneprog','Display','none','ConstraintTolerance',1e-10,'OptimalityTolerance',1e-9);
    planes = repmat(struct('Active',false),3,0);
    [controls,durations_s,flag] = bmtpEngine.optimization.solveTrajectoryStep( ...
        stepRequest(5,initial,goal,limits,options),trajectoryStep(3,planes,1e-8,[2;4;2]));
    assertTrue(testCase,flag>0 || flag==-7);
    verifyEqual(testCase,durations_s,[2;4;2]);
    endpointControls=bmtpEngine.motion.imposeEndpointControls(controls,durations_s,initial,goal);
    verifyEqual(testCase,controls(1,1:3,:),endpointControls(1,1:3,:));
    verifyEqual(testCase,controls(end,end-2:end,:),endpointControls(end,end-2:end,:));
    polynomial = bmtpEngine.motion.createPowerPolynomial(controls,durations_s,0);
    [~,position,velocity,acceleration] = bmtpEngine.motion.evaluatePolynomial(polynomial,[0;8]);
    verifyEqual(testCase,position,[initial.position_units;goal.position_units],'AbsTol',1e-8);
    verifyEqual(testCase,velocity,[initial.velocity_units_s;goal.velocity_units_s],'AbsTol',1e-8);
    verifyEqual(testCase,acceleration,[initial.acceleration_units_s2;goal.acceleration_units_s2],'AbsTol',1e-8);
    [~,~,~,~,leftJerk] = bmtpEngine.motion.evaluatePolynomial(polynomial,[2;6],[1;2]);
    [~,~,~,~,rightJerk] = bmtpEngine.motion.evaluatePolynomial(polynomial,[2;6],[2;3]);
    verifyEqual(testCase,leftJerk,rightJerk,'AbsTol',1e-8);
end

function constraintGenerationWithTransformedFixedClock(testCase)
    initial=struct('position_units',[-1,0],'velocity_units_s',[0,0], ...
        'acceleration_units_s2',[0,0]);
    goal=struct('position_units',[1,0],'velocity_units_s',[0,0], ...
        'acceleration_units_s2',[0,0]);
    limits=struct('xInterval_units',[-2,2],'yInterval_units',[-2,2], ...
        'maxVelocity_units_s',[2,2],'maxAcceleration_units_s2',[5,5], ...
        'maxJerk_units_s3',[10,10]);
    options=optimoptions('coneprog','Display','none', ...
        'ConstraintTolerance',1e-10,'OptimalityTolerance',1e-9);
    emptyPlane=struct('Active',false,'Normal',zeros(2), ...
        'Offset_units',zeros(1,2),'TimeFraction',[0,1]);
    planes=repmat(emptyPlane,9,1);
    planes(4)=struct('Active',true,'Normal',[0,1;0,1], ...
        'Offset_units',[0.1,0.1],'TimeFraction',[0.2,0.8]);
    planes(6)=struct('Active',true,'Normal',[0,-1;0,-1], ...
        'Offset_units',[0.1,0.1],'TimeFraction',[0,1]);
    [controls,durations_s,flag,output]=bmtpEngine.optimization.solveTrajectoryStep( ...
        stepRequest(5,initial,goal,limits,options),trajectoryStep(9,planes,1e-8,2 * ones(9,1)));
    assertTrue(testCase,flag>0 || flag==-7);
    verifyTrue(testCase,output.IntrinsicJerkVariation);
    verifyTrue(testCase,output.ConstraintGenerationComplete);
    verifyGreaterThanOrEqual(testCase,output.ConstraintGenerationRoundCount,1);
    verifyTrue(testCase,output.ConstraintGenerationApplied);
    verifyEqual(testCase,output.LoadedPlanePairCount,2);
    verifyEqual(testCase,durations_s,2*ones(9,1),'AbsTol',1e-12);
    fourth=bmtpEngine.motion.restrictBezier(squeeze(controls(4,:,:)),[0.2,0.8]);
    verifyLessThanOrEqual(testCase,max(fourth(:,2)),-0.1+1e-6);
    verifyGreaterThanOrEqual(testCase,min(controls(6,:,2)),0.1-1e-6);
end

function variationPassDoesNotConsumeFeasibilityBudget(testCase)
    % One allowed corridor iteration must still be followed by the mandatory
    % full integrated-snap pass on the selected fixed clock.
    options = planner();
    options.GoalTimeMode = 'fixedArrival';
    initial = struct( ...
        'time_s',0, ...
        'position_units',[-4,0], ...
        'velocity_units_s',[0,0], ...
        'acceleration_units_s2',[0,0]);
    goal = struct( ...
        'time_s',10, ...
        'position_units',[4,0], ...
        'velocity_units_s',[0,0], ...
        'acceleration_units_s2',[0,0]);
    limits = struct( ...
        'xInterval_units',[-10,10], ...
        'yInterval_units',[-10,10], ...
        'maxVelocity_units_s',[3,3], ...
        'maxAcceleration_units_s2',[3,3], ...
        'maxJerk_units_s3',[6,6]);
    region_units = [-0.5,-1;0.5,-1;0.5,1;-0.5,1];
    seed = struct( ...
        'position_units',[-4,0;0,2;4,0], ...
        'tau',[0;0.5;1], ...
        'UsesTimeScopedSolver',true, ...
        'MaximumAlternatingIterations',1);
    coverage = struct( ...
        'Passed',true, ...
        'ExactRegionCount',1, ...
        'ActiveTimeInterval_s',[0,10], ...
        'EndRegions_units',{{region_units}}, ...
        'BreakTime_s',[0;10]);

    [candidate,diagnostics] = bmtpEngine.solve(seed, ...
        struct('regions_units', {{region_units}}, 'coverage', coverage), ...
        struct('initialState', initial, ...
        'goalState', goal, ...
        'limits', limits, ...
        'options', options), struct());

    verifyTrue(testCase,candidate.Success,candidate.Message);
    verifyEqual(testCase,diagnostics.IterationCount,2);
    verifyTrue(testCase,diagnostics.IntrinsicJerkVariation);
end

function constraintGenerationClosesSeveralPairsInOneSpan(testCase)
    initial=struct('position_units',[-2,0],'velocity_units_s',[0,0], ...
        'acceleration_units_s2',[0,0]);
    goal=struct('position_units',[2,0],'velocity_units_s',[0,0], ...
        'acceleration_units_s2',[0,0]);
    limits=struct('xInterval_units',[-5,5],'yInterval_units',[-5,5], ...
        'maxVelocity_units_s',[10,10],'maxAcceleration_units_s2',[10,10], ...
        'maxJerk_units_s3',[10,10]);
    plane=struct('Active',true,'Verified',true,'ExitFlag',1, ...
        'Normal',repmat([0,1],2,1),'Offset_units',[0.5,0.5], ...
        'SignedGap_units',1,'TimeFraction',[0.2,0.3]);
    planes=repmat(plane,1,3);
    planes(2).Normal=repmat([0,-1],2,1);
    planes(2).TimeFraction=[0.45,0.55];
    planes(3).TimeFraction=[0.7,0.8];
    options=optimoptions('coneprog','Display','none', ...
        'ConstraintTolerance',1e-10,'OptimalityTolerance',1e-9);
    [controlPoint_units,~,exitFlag,output]= ...
        bmtpEngine.optimization.solveTrajectoryStep( ...
        stepRequest(8,initial,goal,limits,options),trajectoryStep(1,planes,0,20));
    verifyNotEmpty(testCase,controlPoint_units);
    verifyTrue(testCase,exitFlag>0 || exitFlag==-7);
    verifyTrue(testCase,output.ConstraintGenerationComplete);
    verifyEqual(testCase,output.LoadedPlanePairCount,3);
    verifyGreaterThanOrEqual(testCase,output.ConstraintGenerationRoundCount,3);
    verifyLessThanOrEqual(testCase, ...
        output.MaximumPlaneConstraintResidual,options.ConstraintTolerance);
end

function timedSolverHonorsRequestIterationLimit(testCase)
    [request, warmStart, diagnostics] = createEmptyTimedSolveFixture(1);
    [result, diagnostics] = bmtpEngine.optimization.solveTimedAlternatingTrajectory( ...
        request, warmStart, diagnostics, 0, 0);
    verifyTrue(testCase, result.Success, result.SolverMessage);
    verifyEqual(testCase, request.MaximumAlternatingIterations, 1);
    verifyLessThanOrEqual(testCase, diagnostics.IterationCount, 1);
end

function timedSolverReturnsCoherentEmptyRecord(testCase)
    [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createBlockedTimedSolveFixture();
    [result, diagnostics] = bmtpEngine.optimization.solveTimedAlternatingTrajectory( ...
        request, warmStart, diagnostics, target_units, roundoffReserve_units);
    activePairs = reshape([result.Planes.Active], size(result.Planes));
    verifyFalse(testCase, result.Success);
    verifyEmpty(testCase, result.ControlPoint_units);
    verifyFalse(testCase, any(activePairs, 'all'));
    verifyEqual(testCase, result.TaggedPairs, activePairs);
    verifyEqual(testCase, diagnostics.ApplicablePairCount, 0);
    verifyEqual(testCase, diagnostics.TaggedPairCount, 0);
    verifyEqual(testCase, diagnostics.FinalCollisionPairCount, 0);
    verifyEqual(testCase, result.FailureStage, "proposal");
    verifyEqual(testCase, result.FailureKind, ...
        "trajectorySubproblemInfeasible");
    verifyFalse(testCase, result.AlternativeGuideEligible);
end

function timedSolverUsesAvailableUnverifiedSeedLines(testCase)
    [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createCrossingTimedSolveFixture();

    % This straight seed crosses a small moving square. On HEAD, the line
    % exists but does not verify, so initialization wrongly returns
    % timedCorridorInitializationUnavailable before solving a trajectory.
    [~, seedActivePairs, allRequiredLinesVerified, lineReport] = ...
        bmtpEngine.separation.createTimeScopedPlanes(warmStart.ControlPoint_units, ...
        warmStart.SegmentTime_s, request, target_units, roundoffReserve_units);
    verifyGreaterThan(testCase, nnz(seedActivePairs), 0);
    verifyFalse(testCase, allRequiredLinesVerified);
    verifyEqual(testCase, lineReport.UnavailablePairCount, 0);

    [result, ~] = bmtpEngine.optimization.solveTimedAlternatingTrajectory( ...
        request, warmStart, diagnostics, target_units, roundoffReserve_units);
    verifyTrue(testCase, result.Success, result.SolverMessage);

    retainedBoundaryTime_s = request.InitialState.time_s + [0; cumsum(result.SegmentTime_s(:))];
    retainedActivePairs = bmtpEngine.separation.activePairsOnClock( ...
        retainedBoundaryTime_s, request.Coverage, numel(request.Regions_units));
    verifiedPairs = reshape([result.Planes.Verified], size(result.Planes));
    verifyTrue(testCase, all(verifiedPairs(retainedActivePairs), 'all'));

    [preparedMotion, motionCheck] = bmtpEngine.evaluateCandidate( ...
        request, result.ControlPoint_units, result.SegmentTime_s, ...
        roundoffReserve_units, target_units);
    verifyTrue(testCase, preparedMotion.Success);
    verifyTrue(testCase, motionCheck.Passed);
end

function timedSolverRetainsAtomicRecordAfterLaterRejectedTrial(testCase, fixture)
    request = fixture.Request;
    warmStart = fixture.WarmStart; diagnostics = fixture.Diagnostics;
    target_units = fixture.Target_units; roundoffReserve_units = fixture.RoundoffReserve_units;
    [retainedResult, retainedDiagnostics] = bmtpEngine.optimization.solveTimedAlternatingTrajectory( ...
        request, warmStart, diagnostics, target_units, roundoffReserve_units);
    [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createMovingTimedSolveFixture(2);
    [result, diagnostics] = bmtpEngine.optimization.solveTimedAlternatingTrajectory( ...
        request, warmStart, diagnostics, target_units, roundoffReserve_units);
    controlTolerance_units = request.Options.ConstraintTolerance;
    timeTolerance_s        = request.Options.ArrivalTimeTolerance_s;
    planeTolerance_units   = request.Options.ConstraintTolerance;
    verifyTrue(testCase, result.Success, result.SolverMessage);
    verifyEqual(testCase, diagnostics.IterationCount, 2);
    verifyEqual(testCase, result.ControlPoint_units, ...
        retainedResult.ControlPoint_units, 'AbsTol', controlTolerance_units);
    verifyEqual(testCase, result.SegmentTime_s, ...
        retainedResult.SegmentTime_s, 'AbsTol', timeTolerance_s);
    verifyEqual(testCase, result.Planes, retainedResult.Planes, ...
        'AbsTol', planeTolerance_units);
    verifyEqual(testCase, result.TaggedPairs, retainedResult.TaggedPairs);
    verifyEqual(testCase, result.SolverMessage, retainedResult.SolverMessage);
    verifyEqual(testCase, diagnostics.SolverMessage, result.SolverMessage);
    verifyEqual(testCase, diagnostics.ApplicablePairCount, ...
        retainedDiagnostics.ApplicablePairCount);
    verifyEqual(testCase, diagnostics.TaggedPairCount, ...
        retainedDiagnostics.TaggedPairCount);
    verifyEqual(testCase, diagnostics.FinalCollisionPairCount, ...
        retainedDiagnostics.FinalCollisionPairCount);
    verifyRetainedTimedDiagnostics(testCase, diagnostics, retainedDiagnostics);
    verifyGreaterThan(testCase, diagnostics.TaggedPairCount, 0);
end

function timedSolverRetainsAtomicRecordAfterLaterFailedTrial(testCase, fixture)
    failedTrialIterationLimit = 15;
    request = fixture.Request;
    warmStart = fixture.WarmStart; diagnostics = fixture.Diagnostics;
    target_units = fixture.Target_units; roundoffReserve_units = fixture.RoundoffReserve_units;
    request.TimedTrajectoryOptions = optimoptions( ...
        request.TimedTrajectoryOptions, 'MaxIterations', failedTrialIterationLimit);
    [retainedResult, retainedDiagnostics] = bmtpEngine.optimization.solveTimedAlternatingTrajectory( ...
        request, warmStart, diagnostics, target_units, roundoffReserve_units);

    [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createMovingTimedSolveFixture(2);
    request.TimedTrajectoryOptions = optimoptions( ...
        request.TimedTrajectoryOptions, 'MaxIterations', failedTrialIterationLimit);
    [result, diagnostics] = bmtpEngine.optimization.solveTimedAlternatingTrajectory( ...
        request, warmStart, diagnostics, target_units, roundoffReserve_units);

    controlTolerance_units = request.Options.ConstraintTolerance;
    timeTolerance_s        = request.Options.ArrivalTimeTolerance_s;
    planeTolerance_units   = request.Options.ConstraintTolerance;
    verifyTrue(testCase, retainedResult.Success, retainedResult.SolverMessage);
    verifyTrue(testCase, result.Success, result.SolverMessage);
    verifyEqual(testCase, diagnostics.IterationCount, 2);
    verifyEqual(testCase, result.ControlPoint_units, ...
        retainedResult.ControlPoint_units, 'AbsTol', controlTolerance_units);
    verifyEqual(testCase, result.SegmentTime_s, ...
        retainedResult.SegmentTime_s, 'AbsTol', timeTolerance_s);
    verifyEqual(testCase, result.Planes, retainedResult.Planes, ...
        'AbsTol', planeTolerance_units);
    verifyEqual(testCase, result.TaggedPairs, retainedResult.TaggedPairs);
    verifyEqual(testCase, result.SolverMessage, retainedResult.SolverMessage);
    verifyEqual(testCase, diagnostics.SolverMessage, retainedResult.SolverMessage);
    verifyEqual(testCase, diagnostics.TaggedPairCount, ...
        retainedDiagnostics.TaggedPairCount);
    verifyEqual(testCase, diagnostics.ApplicablePairCount, ...
        retainedDiagnostics.ApplicablePairCount);
    verifyEqual(testCase, diagnostics.FinalCollisionPairCount, ...
        retainedDiagnostics.FinalCollisionPairCount);
    verifyRetainedTimedDiagnostics(testCase, diagnostics, retainedDiagnostics);
    verifyGreaterThan(testCase, diagnostics.TaggedPairCount, 0);
    verifyEqual(testCase, diagnostics.FinalCollisionPairCount, 0);
end

function staticMeshIgnoresCollinearSeedVertices(testCase)
    limits=struct('xInterval_units',[-10,10],'yInterval_units',[-10,10], ...
        'maxVelocity_units_s',[2,2],'maxAcceleration_units_s2',[1,1], ...
        'maxJerk_units_s3',[3,3]);
    initial=state([-6,4],0);
    goal=state([6,-1],100);
    normalized=planner([],initial,goal,limits,options());
    route=[initial.position_units;-2,1;goal.position_units];
    midpointRoute=[route(1,:);mean(route(1:2,:),1);route(2,:); ...
        mean(route(2:3,:),1);route(3,:)];
    coverage=struct('Passed',true,'ExactRegionCount',0);
    firstRequest=bmtpEngine.prepareRequest(seed(route), ...
        struct('regions_units', {cell(0,1)}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    secondRequest=bmtpEngine.prepareRequest(seed(midpointRoute), ...
        struct('regions_units', {cell(0,1)}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    firstWarm=bmtpEngine.createStartingCurve(firstRequest);
    secondWarm=bmtpEngine.createStartingCurve(secondRequest);
    verifyEqual(testCase,firstWarm.SegmentCount,12);
    verifyEqual(testCase,secondWarm.SegmentCount,firstWarm.SegmentCount);
    verifyEqual(testCase,secondWarm.Route_units,firstWarm.Route_units,'AbsTol',1e-12);
    verifyEqual(testCase,secondWarm.ControlPoint_units, ...
        firstWarm.ControlPoint_units,'AbsTol',1e-12);
    verifyEqual(testCase,secondWarm.SegmentTime_s, ...
        firstWarm.SegmentTime_s,'AbsTol',1e-12);
end

function waitKnotsScaleWithArrivalClock(testCase, request)
    firstWarm = bmtpEngine.createStartingCurve(request);
    for duration_s = [6, 9]
        request.SeedMotionDuration_s = duration_s;
        warm = bmtpEngine.createStartingCurve(request);
        meshTau = [0; cumsum(warm.SegmentTime_s)] / duration_s;
        tolerance = 64 * eps;
        for knotIndex = 1:numel(request.Seed.tau)
            [error, meshIndex] = min(abs(meshTau - request.Seed.tau(knotIndex)));
            verifyLessThanOrEqual(testCase, error, tolerance);
            if meshIndex <= warm.SegmentCount
                position_units = reshape(warm.ControlPoint_units(meshIndex, 1, :), 1, 2);
            else
                position_units = reshape(warm.ControlPoint_units(end, end, :), 1, 2);
            end
            verifyEqual(testCase, position_units, request.Seed.position_units(knotIndex, :), ...
                'AbsTol', tolerance);
        end
        waitSpans = meshTau(1:end - 1) >= request.Seed.tau(2) - tolerance & ...
            meshTau(2:end) <= request.Seed.tau(3) + tolerance;
        verifyTrue(testCase, any(waitSpans));
        verifyEqual(testCase, warm.ControlPoint_units(waitSpans, 1, :), ...
            warm.ControlPoint_units(waitSpans, end, :), 'AbsTol', tolerance);
        verifyEqual(testCase, sum(warm.SegmentTime_s(waitSpans)), ...
            duration_s * (request.Seed.tau(3) - request.Seed.tau(2)), ...
            'AbsTol', 64 * eps(duration_s));
        verifyEqual(testCase, warm.ControlPoint_units, firstWarm.ControlPoint_units);
    end
end

function motionSpanCountIgnoresCellCount(testCase, sparseRequest, normalized)
    denseRequest  = createWaitRequest(920, normalized);
    sparseWarm = bmtpEngine.createStartingCurve(sparseRequest);
    denseWarm  = bmtpEngine.createStartingCurve(denseRequest);
    guideSegmentCount = size(denseRequest.Seed.position_units, 1) - 1;
    expectedSegmentCount = max(20, guideSegmentCount * denseRequest.SplitCount);
    verifyEqual(testCase, denseWarm.SegmentCount, expectedSegmentCount);
    verifyEqual(testCase, denseWarm.ControlPoint_units, sparseWarm.ControlPoint_units);
    verifyEqual(testCase, denseWarm.SegmentTime_s, sparseWarm.SegmentTime_s);
    verifyGreaterThan(testCase, nnz(denseWarm.RegionActiveBySegment), ...
        nnz(sparseWarm.RegionActiveBySegment));
end

function solveRequestCarriesMinimumArrivalBound(testCase, normalized)
    initial=struct('time_s',0,'position_units',[-1,0]);
    goal=struct('time_s',10,'position_units',[1,0.5]);
    seed=struct('position_units',[-1,0;1,0.5],'tau',[0;1], ...
        'UsesVariableClock',true);
    coverage=struct('Passed',true,'ExactRegionCount',0,'MinimumMotionDuration_s',4, ...
        'SeedMotionDuration_s',6, ...
        'BreakTime_s', [initial.time_s; goal.time_s], ...
        'ActiveTimeInterval_s',zeros(0,2));
    request=bmtpEngine.prepareRequest(seed, ...
        struct('regions_units', {cell(0,1)}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    verifyEqual(testCase,request.MinimumMotionDuration_s,4);
    verifyEqual(testCase,request.SeedMotionDuration_s,6);
    verifyTrue(testCase,request.UsesVariableClock);
    verifyEqual(testCase,request.Degree,5);
    warmStart=bmtpEngine.createStartingCurve(request);
    verifyEqual(testCase,warmStart.Duration_s,6,'AbsTol',1e-12);
end

function variableClockWarmStartPreservesEventKnots(testCase, normalized)
    initial = struct('time_s', 0, 'position_units', [-1, 0]);
    goal    = struct('time_s', 10, 'position_units', [1, 0.5]);
    seed = struct( ...
        'position_units',    [-1, 0; -0.5, 0; 1, 0.5], ...
        'tau',               [0; 0.25; 1], ...
        'UsesVariableClock', true);
    regions_units = {[-4, -4; -3, -4; -3, -3; -4, -3]; ...
        [3, 3; 4, 3; 4, 4; 3, 4]};
    coverage = struct( ...
        'Passed',                  true, ...
        'ExactRegionCount',        2, ...
        'MinimumMotionDuration_s', 4, ...
        'SeedMotionDuration_s',    6, ...
        'ActiveTimeInterval_s',    [0, 1.4; 1.6, 6], ...
        'EndRegions_units',        {regions_units}, ...
        'BreakTime_s',             [0; 2.5; 10]);
    request = bmtpEngine.prepareRequest(seed, ...
        struct('regions_units', {regions_units}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));

    warmStart = bmtpEngine.createStartingCurve(request);
    breaks_s  = request.InitialState.time_s + [0; cumsum(warmStart.SegmentTime_s)];
    expectedActivePairs = breaks_s(1:end - 1) < coverage.ActiveTimeInterval_s(:, 2).' & ...
        breaks_s(2:end) > coverage.ActiveTimeInterval_s(:, 1).';
    minimumEventSegmentCount = 20; % Keep enough spans to steer around timed cells.
    expectedSegmentCount = max(minimumEventSegmentCount, ...
        (size(seed.position_units, 1) - 1) * request.SplitCount);
    expectedEventTime_s = request.InitialState.time_s + ...
        coverage.SeedMotionDuration_s * seed.tau(2:end - 1);
    comparisonTolerance_s = 32 * eps(coverage.SeedMotionDuration_s);

    verifyEqual(testCase, warmStart.SegmentCount, expectedSegmentCount);
    verifyEqual(testCase, warmStart.Duration_s, coverage.SeedMotionDuration_s, ...
        'AbsTol', comparisonTolerance_s);
    for eventIndex = 1:numel(expectedEventTime_s)
        nearestBreakError_s = min(abs(breaks_s - expectedEventTime_s(eventIndex)));
        verifyLessThanOrEqual(testCase, nearestBreakError_s, comparisonTolerance_s);
    end
    verifyEqual(testCase, warmStart.ControlPoint_units(1, 1:3, :), ...
        reshape(repmat(initial.position_units, 3, 1), 1, 3, 2));
    verifyEqual(testCase, warmStart.ControlPoint_units(end, end - 2:end, :), ...
        reshape(repmat(goal.position_units, 3, 1), 1, 3, 2));
    verifyEqual(testCase, warmStart.RegionActiveBySegment, expectedActivePairs);
end

function variableClockUsesActualMovingCellOverlap(testCase)
    box=[-0.25,4.75;0.25,4.75;0.25,5.25;-0.25,5.25];
    controls=zeros(2,6,2);
    controls(1,:,1)=linspace(-2,-1,6);
    controls(2,:,1)=linspace(-1,0,6);
    coverage=struct('Passed',true,'ActiveTimeInterval_s',[0,5;5,10], ...
        'EndRegions_units',{{box;box}});
    request=struct('InitialState',struct('time_s',0), ...
        'Regions_units',{{box;box}},'Coverage',coverage);
    [planes,activePairs,complete,statistics]= ...
        bmtpEngine.separation.createTimeScopedPlanes(controls,[3;3],request,1e-6,1e-8);
    verifyTrue(testCase,complete);
    verifyEqual(testCase,activePairs,[true,false;true,true]);
    verifyEqual(testCase,statistics.ActivePairCount,3);
    verifyEqual(testCase,planes(2,1).TimeFraction,[0,2/3],'AbsTol',1e-12);
    verifyEqual(testCase,planes(2,2).TimeFraction,[2/3,1],'AbsTol',1e-12);
end

function savedDetourUsesGivenDeadline(testCase, request, obstacles)
    options=request.options;
    options.GoalTimeMode='fixedArrival';
    result=planner(obstacles, ...
        request.initialState,request.goalState,request.limits,options);
    assertTrue(testCase,result.Success,result.Message);
    verifyTrue(testCase,obstacleAvoidance.validateTrajectory(result).Passed);
    verifyEqual(testCase,result.ArrivalTime_s,180,'AbsTol',1e-8);
    % The unified spatial result stays within one percent of the former
    % explicitly selected timed motion (229.400575729 units).
    verifyLessThan(testCase,result.MotionLength_units,232);
    verifyGreaterThan(testCase,result.Diagnostics.SolverDiagnostics.OptimizerSpanCount,16);
end

function savedMovingDetourEarliestArrival(testCase, request, obstacles)
    options = request.options; options.GoalTimeMode = 'earliestArrival';
    result = planner(obstacles,request.initialState,request.goalState,request.limits,options);
    assertTrue(testCase,result.Success,result.Message);
    verifyTrue(testCase,obstacleAvoidance.validateTrajectory(result).Passed);
    verifyEqual(testCase,result.Diagnostics.GoalArrivalWindow_s(2),180,'AbsTol',1e-8);
    verifyGreaterThanOrEqual(testCase,result.ArrivalTime_s, ...
        result.Diagnostics.GoalArrivalWindow_s(1)-1e-8);
    verifyLessThanOrEqual(testCase,result.ArrivalTime_s, ...
        result.Diagnostics.GoalArrivalWindow_s(2)+1e-8);
    verifyEqual(testCase,result.Diagnostics.VisibilityGraph.SearchKind,"timeExpandedVisibilityGraph");
    verifyEqual(testCase,result.Diagnostics.SolverDiagnostics.TaggedPairCount, ...
        result.Diagnostics.SolverDiagnostics.ApplicablePairCount);
    verifyEqual(testCase,result.Diagnostics.SolverDiagnostics.FinalCollisionPairCount,0);
end

function [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createStaticAlternatingFixture(goalTimeMode)
    box_units = [-0.5, -0.5; 0.5, -0.5; 0.5, 0.5; -0.5, 0.5];
    initial   = state([-3, 0], 0);
    goal      = state([3, 0], 60);
    limits = struct( ...
        'xInterval_units',          [-5, 5], ...
        'yInterval_units',          [-5, 5], ...
        'maxVelocity_units_s',      [2, 2], ...
        'maxAcceleration_units_s2', [1, 1], ...
        'maxJerk_units_s3',         [3, 3]);
    normalized = planner([], initial, goal, limits, ...
        struct('GoalTimeMode', goalTimeMode));
    route_units = [initial.position_units; -1, 1.5; 1, 1.5; goal.position_units];
    coverage = struct('Passed', true, 'ExactRegionCount', 1);
    request = bmtpEngine.prepareRequest(seed(route_units), ...
        struct('regions_units', {{box_units}}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    warmStart = bmtpEngine.createStartingCurve(request);
    diagnostics = struct( ...
        'IterationCount',          0, ...
        'Converged',               false, ...
        'ApplicablePairCount',     nnz(warmStart.RegionActiveBySegment), ...
        'TrajectorySocpCount',     0, ...
        'FinalCollisionPairCount', 0, ...
        'PlaneSocpCount',          0, ...
        'SolverMessage',           "");
    roundoffReserve_units = normalized.Diagnostics.SeparationProof.RoundoffReserve_units;
    target_units  = normalized.Diagnostics.SeparationProof.RequiredGap_units - roundoffReserve_units;
end

function verifyValidatedStaticBmtp(testCase,result)
    verifyTrue(testCase,result.Success,result.Message);
    verifyTrue(testCase,obstacleAvoidance.validateTrajectory(result).Passed);
    verifyGreaterThan(testCase,result.Diagnostics.SolverDiagnostics.TaggedPairCount,0);
    verifyGreaterThanOrEqual(testCase, ...
        result.Diagnostics.SolverDiagnostics.TransientPlaneRemovalCount,0);
end

function value=state(position_units,time_s)
    value=struct('time_s',time_s,'position_units',position_units);
end

function value=options()
    value=struct('GoalTimeMode','earliestArrival','SampleTime_s',0.1);
end

function value=seed(route_units)
    edgeLength_units=vecnorm(diff(route_units),2,2);
    value=struct('position_units',route_units, ...
        'tau',[0;cumsum(edgeLength_units)]/sum(edgeLength_units));
end

function verifyRetainedTimedDiagnostics(testCase, actual, expected)
    % Every selected-candidate diagnostic remains atomic with its motion.
    verifyEqual(testCase, actual.Converged, expected.Converged);
    fieldNames = [ ...
        "LoadedPlanePairCount", ...
        "ConstraintGenerationRoundCount", ...
        "ConstraintGenerationComplete", ...
        "MaximumPlaneConstraintResidual", ...
        "ConstraintGenerationReturnedSolveIndex", ...
        "ConstraintGenerationLastAttemptExitFlag", ...
        "ConstraintGenerationTerminatedAfterRetainedIterate"];
    for fieldName = fieldNames
        verifyEqual(testCase, isfield(actual, fieldName), isfield(expected, fieldName));
        if isfield(expected, fieldName)
            verifyEqual(testCase, actual.(fieldName), expected.(fieldName));
        end
    end
end

function [request, warmStart, diagnostics] = createEmptyTimedSolveFixture(maximumIterationCount)
    initial = struct('time_s', 0, 'position_units', [-1, 0]);
    goal    = struct('time_s', 10, 'position_units', [1, 0.5]);
    normalized = planner([], initial, goal, [], struct('GoalTimeMode', "earliestArrival"));
    seed = struct( ...
        'position_units',              [initial.position_units; goal.position_units], ...
        'tau',                         [0; 1], ...
        'UsesVariableClock',           true, ...
        'MaximumAlternatingIterations', maximumIterationCount);
    coverage = struct( ...
        'Passed',                  true, ...
        'BreakTime_s',             [initial.time_s; goal.time_s], ...
        'ExactRegionCount',        0, ...
        'MinimumMotionDuration_s', 4, ...
        'SeedMotionDuration_s',    6, ...
        'ActiveTimeInterval_s',    zeros(0, 2));
    request = bmtpEngine.prepareRequest(seed, ...
        struct('regions_units', {cell(0, 1)}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    warmStart = bmtpEngine.createStartingCurve(request);
    diagnostics = struct( ...
        'IterationCount',          0, ...
        'Converged',               false, ...
        'ApplicablePairCount',     0, ...
        'TrajectorySocpCount',     0, ...
        'FinalCollisionPairCount', 0, ...
        'SolverMessage',           "", ...
        'ConicSolver',             bmtpEngine.optimization.accumulateConicDiagnostics());
end

function [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createBlockedTimedSolveFixture()
    initial = struct('time_s', 0, 'position_units', [-1, 0]);
    goal    = struct('time_s', 10, 'position_units', [1, 0]);
    normalized = planner([], initial, goal, [], struct('GoalTimeMode', "earliestArrival"));
    seed = struct( ...
        'position_units',    [initial.position_units; goal.position_units], ...
        'tau',               [0; 1], ...
        'UsesVariableClock', true);
    blockingRegion_units = [-2, -2; 2, -2; 2, 2; -2, 2];
    coverage = struct( ...
        'Passed',                  true, ...
        'BreakTime_s',             [initial.time_s; goal.time_s], ...
        'ExactRegionCount',        1, ...
        'MinimumMotionDuration_s', 0, ...
        'SeedMotionDuration_s',    6, ...
        'ActiveTimeInterval_s',    [0, 10], ...
        'EndRegions_units',        {{blockingRegion_units}});
    request = bmtpEngine.prepareRequest(seed, ...
        struct('regions_units', {{blockingRegion_units}}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    warmStart = bmtpEngine.createStartingCurve(request);
    diagnostics = struct( ...
        'IterationCount',          0, ...
        'Converged',               false, ...
        'ApplicablePairCount',     nnz(warmStart.RegionActiveBySegment), ...
        'TrajectorySocpCount',     0, ...
        'FinalCollisionPairCount', 0, ...
        'SolverMessage',           "", ...
        'ConicSolver',             bmtpEngine.optimization.accumulateConicDiagnostics());
    roundoffReserve_units = normalized.Diagnostics.SeparationProof.RoundoffReserve_units;
    target_units  = normalized.Diagnostics.SeparationProof.RequiredGap_units - roundoffReserve_units;
end

function [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createCrossingTimedSolveFixture()
    initial = struct('time_s', 0, 'position_units', [-4, 0]);
    goal    = struct('time_s', 20, 'position_units', [4, 0]);
    limits = struct( ...
        'xInterval_units',          [-6, 6], ...
        'yInterval_units',          [-6, 6], ...
        'maxVelocity_units_s',      [3, 3], ...
        'maxAcceleration_units_s2', [3, 3], ...
        'maxJerk_units_s3',         [6, 6]);
    normalized = planner([], initial, goal, limits, struct('GoalTimeMode', "earliestArrival"));

    route_units = [-4, 0; -1, 0; 1, 0; 4, 0];
    routeLength_units = vecnorm(diff(route_units), 2, 2);
    firstRegion_units = [-0.35, -0.35; 0.35, -0.35; 0.35, 0.35; -0.35, 0.35];
    lastRegion_units  = firstRegion_units + [0, 0.3];
    seed = struct( ...
        'position_units',               route_units, ...
        'tau',                          [0; cumsum(routeLength_units)] / sum(routeLength_units), ...
        'UsesVariableClock',            true, ...
        'MaximumAlternatingIterations', 8);
    coverage = struct( ...
        'Passed',                  true, ...
        'BreakTime_s',             [initial.time_s; goal.time_s], ...
        'ExactRegionCount',        1, ...
        'EndRegions_units',        {{lastRegion_units}}, ...
        'ActiveTimeInterval_s',    [0, 20], ...
        'MinimumMotionDuration_s', 0, ...
        'SeedMotionDuration_s',    12);
    request = bmtpEngine.prepareRequest(seed, ...
        struct('regions_units', {{firstRegion_units}}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    warmStart = bmtpEngine.createStartingCurve(request);
    diagnostics = struct( ...
        'IterationCount',          0, ...
        'Converged',               false, ...
        'ApplicablePairCount',     nnz(warmStart.RegionActiveBySegment), ...
        'TrajectorySocpCount',     0, ...
        'FinalCollisionPairCount', 0, ...
        'PlaneSocpCount',          0, ...
        'SolverMessage',           "");
    roundoffReserve_units = normalized.Diagnostics.SeparationProof.RoundoffReserve_units;
    target_units = normalized.Diagnostics.SeparationProof.RequiredGap_units - roundoffReserve_units;
end

function [request, warmStart, diagnostics, target_units, roundoffReserve_units] = ...
        createMovingTimedSolveFixture(maximumIterationCount)
    initial = struct('time_s', 0, 'position_units', [-4, 0]);
    goal    = struct('time_s', 20, 'position_units', [4, 0]);
    limits = struct( ...
        'xInterval_units',          [-6, 6], ...
        'yInterval_units',          [-6, 6], ...
        'maxVelocity_units_s',      [3, 3], ...
        'maxAcceleration_units_s2', [3, 3], ...
        'maxJerk_units_s3',         [6, 6]);
    normalized = planner([], initial, goal, limits, struct('GoalTimeMode', "earliestArrival"));
    route_units = [-4, 0; -1, 2; 1, 2; 4, 0];
    routeLength_units = vecnorm(diff(route_units), 2, 2);
    firstRegion_units = [-0.5, -1.5; 0.5, -1.5; 0.5, -0.5; -0.5, -0.5];
    lastRegion_units  = firstRegion_units + [0, 2];
    seed = struct( ...
        'position_units',               route_units, ...
        'tau',                          [0; cumsum(routeLength_units)] / sum(routeLength_units), ...
        'UsesVariableClock',            true, ...
        'MaximumAlternatingIterations', maximumIterationCount);
    coverage = struct( ...
        'Passed',                  true, ...
        'BreakTime_s',             [initial.time_s; goal.time_s], ...
        'ExactRegionCount',        1, ...
        'EndRegions_units',        {{lastRegion_units}}, ...
        'ActiveTimeInterval_s',    [0, 20], ...
        'MinimumMotionDuration_s', 0, ...
        'SeedMotionDuration_s',    12);
    request = bmtpEngine.prepareRequest(seed, ...
        struct('regions_units', {{firstRegion_units}}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
    % These atomic-retention tests need the same nine-span curve to exercise
    % their later rejected and failed trials. Build its controls through the
    % untimed route branch, then assign the supplied timed seed duration.
    curveRequest = request;
    curveRequest.UsesVariableClock = false;
    warmStart = bmtpEngine.createStartingCurve(curveRequest);
    commonSegmentTime_s = request.SeedMotionDuration_s / sum(warmStart.SegmentRatio);
    warmStart.SegmentTime_s = commonSegmentTime_s * warmStart.SegmentRatio;
    warmStart.Duration_s = sum(warmStart.SegmentTime_s);
    segmentBoundaryTime_s = request.InitialState.time_s + [0; cumsum(warmStart.SegmentTime_s)];
    warmStart.RegionActiveBySegment = bmtpEngine.separation.activePairsOnClock( ...
        segmentBoundaryTime_s, request.Coverage, numel(request.Regions_units));
    diagnostics = struct( ...
        'IterationCount',          0, ...
        'Converged',               false, ...
        'ApplicablePairCount',     nnz(warmStart.RegionActiveBySegment), ...
        'TrajectorySocpCount',     0, ...
        'FinalCollisionPairCount', 0, ...
        'PlaneSocpCount',          0, ...
        'SolverMessage',           "");
    roundoffReserve_units = normalized.Diagnostics.SeparationProof.RoundoffReserve_units;
    target_units  = normalized.Diagnostics.SeparationProof.RequiredGap_units - roundoffReserve_units;
end

function request = stepRequest(degree, initialState, goalState, limits, options)
    % The part of an engine solve request that a trajectory step reads.
    request = struct( ...
        'Degree',                 degree, ...
        'InitialState',           initialState, ...
        'GoalState',              goalState, ...
        'Limits',                 limits, ...
        'TrajectoryOptions',      options, ...
        'TimedTrajectoryOptions', options);
end

function step = trajectoryStep(segmentCount, planes, roundoffReserve_units, segmentTime_s)
    % One fixed physical clock, supplied directly rather than rebuilt from ratios.
    step = struct( ...
        'Formulation',               "physicalClock", ...
        'SegmentCount',              segmentCount, ...
        'Planes',                    planes, ...
        'RoundoffReserve_units',     roundoffReserve_units, ...
        'MaximumMotionDuration_s',   [], ...
        'MinimumMotionDuration_s',   0, ...
        'SegmentRatio',              [], ...
        'SegmentTime_s',             segmentTime_s(:), ...
        'FixedClock',                true, ...
        'IntrinsicVariationEnabled', true, ...
        'ConstraintBase',            struct());
end

function step = timedStep(segmentCount, planes, roundoffReserve_units, segmentTime_s)
    % One fixed scaled clock, supplied directly with no second duration source.
    step = struct( ...
        'Formulation',             "scaledClock", ...
        'SegmentCount',            segmentCount, ...
        'Planes',                  planes, ...
        'RoundoffReserve_units',   roundoffReserve_units, ...
        'MaximumMotionDuration_s', [], ...
        'FixedClock',              true, ...
        'MinimumMotionDuration_s', 0, ...
        'SegmentRatio',            [], ...
        'SegmentTime_s',           segmentTime_s(:), ...
        'IntrinsicVariationEnabled', false, ...
        'ConstraintBase',          struct());
end

function request = createWaitRequest(cellCount, normalized)
    % The same stationary remote obstacle has either one cell or many cells.
    % The guide has eleven edges (a wait at its second knot, then nine
    % straight edges) so that the guide-derived span count exceeds the
    % twenty-span floor and the assertion pins the guide rule, not the floor.
    tailTau    = linspace(0.4, 1, 9).';
    tail_units = [-0.4, 0.28] + (tailTau - 0.4) / 0.6 .* ([1, 0.5] - [-0.4, 0.28]);
    seed = struct( ...
        'position_units',    [-1, 0; -0.5, 0.25; -0.5, 0.25; tail_units], ...
        'tau',               [0; 0.2; 0.35; tailTau], ...
        'UsesVariableClock', true);
    breaks_s = linspace(0, 10, cellCount + 1).';
    regions_units = repmat({[3, 3; 4, 3; 4, 4; 3, 4]}, cellCount, 1);
    coverage = struct( ...
        'Passed',                  true, ...
        'ExactRegionCount',        cellCount, ...
        'MinimumMotionDuration_s', 4, ...
        'SeedMotionDuration_s',    6, ...
        'ActiveTimeInterval_s',    [breaks_s(1:end - 1), breaks_s(2:end)], ...
        'EndRegions_units',        {regions_units}, ...
        'BreakTime_s',             breaks_s);
    request = bmtpEngine.prepareRequest(seed, ...
        struct('regions_units', {regions_units}, 'coverage', coverage), ...
        struct('initialState', normalized.Inputs.initialState, ...
        'goalState', normalized.Inputs.goalState, ...
        'limits', normalized.Diagnostics.Limits, ...
        'options', normalized.Options));
end

function limits = thinWallLimits()
    limits = struct( ...
        'xInterval_units',          [-10 10], ...
        'yInterval_units',          [-10 10], ...
        'maxVelocity_units_s',      [2 2], ...
        'maxAcceleration_units_s2', [2 2], ...
        'maxJerk_units_s3',         [4 4]);
end

function normalized = meshNormalizationFixture()
    initial = struct('time_s', 0, 'position_units', [-1, 0]);
    goal = struct('time_s', 10, 'position_units', [1, 0.5]);
    normalized = planner([], initial, goal, [], struct('GoalTimeMode', "earliestArrival"));
end

function [request, obstacles] = savedDetourFixture()
    root=fileparts(mfilename('fullpath'));
    request=jsondecode(fileread(fullfile(root,'fixtures','savedMovingDetour.json')));
    sources=cell(numel(request.obstacles),1);
    for k=1:numel(sources)
        source=request.obstacles(k); frames=source.keyframes;
        sources{k}=obstacleAvoidance.obstacles.createObstacle(source.name,[frames.time_s].', ...
            arrayfun(@(f)f.vertices_units(:,1),frames,'UniformOutput',false), ...
            arrayfun(@(f)f.vertices_units(:,2),frames,'UniformOutput',false),source.safetyMargin_units);
    end
    obstacles = obstacleAvoidance.obstacles.combineObstacles(sources);
end

function [limits, solverOptions] = singleSpanStepFixture()
    limits = struct('xInterval_units', [-2, 2], 'yInterval_units', [-2, 2], ...
        'maxVelocity_units_s', [2, 2], 'maxAcceleration_units_s2', [5, 5], 'maxJerk_units_s3', [10, 10]);
    solverOptions = optimoptions('coneprog', 'Display', 'none', ...
        'ConstraintTolerance', 1e-10, 'OptimalityTolerance', 1e-9);
end
