function tests = testCoppRetimer
%% Section 0: Header & Readme
% SYNTAX
%   tests = testCoppRetimer
%**************************************************************************
% PURPOSE
%   - Verify the experimental COPP TOPP3 adapter on deterministic regular
%     paths without invoking visibility search or obstacle construction.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - tests (MATLAB function-test array)
%**************************************************************************
% UNITS
%   - Position is degrees and time derivatives use seconds.
%**************************************************************************

%% Section 1: Create The Function-Test Suite

root = fileparts(fileparts(mfilename("fullpath")));
addpath(root);
tests = functiontests(localfunctions);
end

%% Section 2: Local Test Cases

function testRestToRestLineSatisfiesFiniteLimits(testCase)
% A regular line isolates COPP timing from visibility and smoothing logic.
testCase.verifyNotEmpty(which("copp.version"), ...
    "COPP for MATLAB must be installed for this branch trial.");
start_deg = [0 0];
goal_deg = [4 2];
smoothPath = makeLinePath(start_deg, goal_deg, 101);
initialState = state(0, start_deg);
goalState = state(30, goal_deg);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2.5 2.5]);
options = struct( ...
    "GoalTimeMode", "earliestArrival", ...
    "SampleTime_s", 0.01);

trial = azElExperimental.retimeCoppSmoothPath( ...
    smoothPath, initialState, goalState, limits, options, 0);

testCase.verifyTrue(trial.Success, trial.Message);
testCase.verifyEqual(trial.position_deg(1, :), start_deg, ...
    "AbsTol", 1e-10);
testCase.verifyEqual(trial.position_deg(end, :), goal_deg, ...
    "AbsTol", 1e-10);
testCase.verifyTrue(trial.ConstraintDiagnostics.Satisfied);
testCase.verifyTrue( ...
    trial.ConstraintDiagnostics.FiniteJerkNumericallyVerified);
testCase.verifyFalse(trial.ConstraintDiagnostics.FiniteJerkCertified);
testCase.verifyFalse( ...
    trial.ConstraintDiagnostics.ContinuousJerkCertified);
testCase.verifyEqual(trial.ConstraintDiagnostics.VerificationMethod, ...
    "denseTimeSampling");
testCase.verifyLessThanOrEqual( ...
    trial.ConstraintDiagnostics.PeakVelocity_deg_s, ...
    limits.maxVelocity_deg_s .* (1 + 1e-7));
testCase.verifyLessThanOrEqual( ...
    trial.ConstraintDiagnostics.PeakAcceleration_deg_s2, ...
    limits.maxAcceleration_deg_s2 .* (1 + 1e-7));
testCase.verifyLessThanOrEqual( ...
    trial.ConstraintDiagnostics.PeakJerk_deg_s3, ...
    limits.maxJerk_deg_s3 .* (1 + 1e-7));
end

function testInteriorStopReturnsExplicitFailure(testCase)
% The current COPP profile schema supports stationary boundaries, not an
% arbitrary interior stop, so the adapter must expose that limitation.
smoothPath = makeLinePath([0 0], [1 0], 21);
smoothPath.MandatoryStopCount = 1;
initialState = state(0, [0 0]);
goalState = state(10, [1 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2.5 2.5]);
options = struct( ...
    "GoalTimeMode", "earliestArrival", ...
    "SampleTime_s", 0.01);

trial = azElExperimental.retimeCoppSmoothPath( ...
    smoothPath, initialState, goalState, limits, options, 0);

testCase.verifyFalse(trial.Success);
testCase.verifyEqual( ...
    trial.TerminationReason, "interiorStopUnsupported");
end

function stateRecord = state(time_s, position_deg)
% Create one rest boundary state for deterministic local tests.
stateRecord = struct( ...
    "time_s", time_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
end

function smoothPath = makeLinePath(start_deg, goal_deg, stationCount)
% Build the smallest regular maintained-path schema without a planner.
delta_deg = goal_deg - start_deg;
length_deg = norm(delta_deg);
direction = delta_deg / length_deg;
station_s_deg = linspace(0, length_deg, stationCount).';
position_deg = start_deg + station_s_deg .* direction;
primitive = struct( ...
    "Type", "line", ...
    "StartPosition_deg", start_deg, ...
    "EndPosition_deg", goal_deg, ...
    "Direction", direction, ...
    "Length_deg", length_deg, ...
    "StartArcLength_deg", 0, ...
    "EndArcLength_deg", length_deg, ...
    "ControlPoints_deg", zeros(6, 2), ...
    "ParameterGrid", zeros(0, 1), ...
    "ArcLengthGrid_deg", zeros(0, 1), ...
    "CornerPathPointIndex", 0);
smoothPath = struct( ...
    "Success", true, ...
    "TotalLength_deg", length_deg, ...
    "SampleArcLength_deg", station_s_deg, ...
    "position_deg", position_deg, ...
    "tangent", repmat(direction, stationCount, 1), ...
    "secondDerivative_deg_inv", zeros(stationCount, 2), ...
    "thirdDerivative_deg_inv2", zeros(stationCount, 2), ...
    "Primitives", primitive, ...
    "MandatoryStopCount", 0);
end
