function tests = testOfflineSandboxDiagnosisBundle
%% Section 0: Header & Readme
% SYNTAX
%   tests = testOfflineSandboxDiagnosisBundle
%**************************************************************************
% PURPOSE
%   - Verify that the HTML sandbox creates a replayable, handle-free MATLAB
%     diagnosis bundle and exposes a request-matched download workflow.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - tests (matlab.unittest.FunctionTestCase array)
%       Focused tests for bundle construction and HTML/server integration.
%**************************************************************************
% UNITS
%   - Positions and polygon vertices use degrees. Time uses seconds.
%**************************************************************************

tests = functiontests(localfunctions);
end

function setupOnce(testCase)
% Add only the repository and offline-sandbox public-function folders.
repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(repositoryRoot, fullfile(repositoryRoot, "offlinesandbox"));
testCase.TestData.RepositoryRoot = repositoryRoot;
end

function testBundlePreservesExactResultAndRemovesCallback(testCase)
% Preserve replay data while excluding the trusted transport callback.
request = createSyntheticRequest();
plannerInputs = struct( ...
    "obstacles", struct.empty(0, 1), ...
    "initialState", request.initialState, ...
    "goalState", request.goalState, ...
    "limits", request.limits);
plannerOptions = request.options;
plannerOptions.CancellationCheckFcn = @() false;
result = struct( ...
    "Success", false, ...
    "Message", "No feasible path found.", ...
    "TerminationReason", "openSetExhausted", ...
    "Inputs", plannerInputs, ...
    "Options", plannerOptions, ...
    "SearchDiagnostics", struct("ExpandedCount", 17));
validation = struct("Passed", false, "Message", "Expected failure.");

bundle = offlineSandbox.createDiagnosisBundle( ...
    request, result, validation);

verifyEqual(testCase, bundle.Format, ...
    "obstacleAvoidanceSandboxDiagnosis-v2");
verifyEqual(testCase, bundle.ExportRequest.RequestId, request.requestId);
verifyEqual(testCase, bundle.PlannerInputs, plannerInputs);
verifyEqual(testCase, bundle.Result.SearchDiagnostics.ExpandedCount, 17);
verifyEmpty(testCase, bundle.Result.Options.CancellationCheckFcn);
verifyEmpty(testCase, bundle.PlannerOptions.CancellationCheckFcn);
verifyEqual(testCase, bundle.Result.TerminationReason, ...
    "openSetExhausted");
verifyFalse(testCase, bundle.Result.Success);
end

function testPageAndServerExposeMatchedBundleDownload(testCase)
% Keep bundle download and fresh replay routes wired to the browser controls.
htmlPath = fullfile(testCase.TestData.RepositoryRoot, ...
    "offlinesandbox", "az_el_planner_sandbox.html");
serverPath = fullfile(testCase.TestData.RepositoryRoot, ...
    "offlinesandbox", "+offlineSandbox", "serveSandbox.m");
htmlText = string(fileread(htmlPath));
serverText = string(fileread(serverPath));

verifyTrue(testCase, contains(htmlText, 'id="downloadBundleButton"'));
verifyTrue(testCase, contains(htmlText, 'id="bundleFileInput"'));
verifyTrue(testCase, contains(htmlText, ...
    '`${state.serverOrigin}/run-bundle`'));
verifyTrue(testCase, contains(htmlText, 'id="setMotionButton"'));
verifyTrue(testCase, contains(htmlText, ...
    'motionVelocity_deg_s'));
verifyTrue(testCase, contains(htmlText, ...
    'Speed magnitude: ${speed_deg_s.toFixed(3)} deg/s'));
verifyTrue(testCase, contains(htmlText, ...
    'fetch(`${state.serverOrigin}/bundle`'));
verifyTrue(testCase, contains(htmlText, ...
    'state.bundleRequestId = payload.requestId'));
verifyTrue(testCase, contains(serverText, 'path == "/bundle"'));
verifyTrue(testCase, contains(serverText, 'path == "/run-bundle"'));
verifyTrue(testCase, contains(serverText, ...
    'offlineSandbox.replayDiagnosisBundle'));
verifyTrue(testCase, contains(serverText, ...
    'cachedRequestId ~= requestId'));
verifyTrue(testCase, contains(serverText, ...
    '"application/vnd.matlab.mat-file"'));
end

function testReplayDiagnosisBundleRunsStoredCanonicalRequest(testCase)
% Replay a moving-obstacle canonical request and write a fresh browser result.
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 10, ...
    "position_deg", [1 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [2 2], ...
    "maxJerk_deg_s3", [5 5], ...
    "azimuthInterval_deg", [-10 10], ...
    "elevationInterval_deg", [-10 10]);
time_s = [0; 10];
azimuthBySlice_deg = {[-6; -5; -5; -6]; [-5.5; -4.5; -4.5; -5.5]};
elevationBySlice_deg = {[5; 5; 6; 6]; [5; 5; 6; 6]};
movingObstacle = obstacleAvoidance.obstacles.createObstacle( ...
    "moving replay sentinel", time_s, azimuthBySlice_deg, ...
    elevationBySlice_deg, 0.1);
plannerInputs = struct( ...
    "obstacles", obstacleAvoidance.obstacles.combineObstacles( ...
        {movingObstacle}), ...
    "initialState", initialState, ...
    "goalState", goalState, ...
    "limits", limits);
plannerOptions = obstacleAvoidance.planTrajectory();
plannerOptions.GoalTimeMode = "earliestArrival";
plannerOptions.MaximumSeedCount = 1;
diagnosisBundle = struct( ...
    "Format", "obstacleAvoidanceSandboxDiagnosis-v2", ...
    "PlannerInputs", plannerInputs, ...
    "PlannerOptions", plannerOptions);

bundleFilePath = string(tempname) + ".mat";
resultFilePath = string(tempname) + ".json";
cleanup = onCleanup(@() deleteTestFiles( ...
    bundleFilePath, resultFilePath));
save(bundleFilePath, "diagnosisBundle", "-v7");

[response, reproducedBundle] = ...
    offlineSandbox.replayDiagnosisBundle( ...
    bundleFilePath, resultFilePath);

verifyTrue(testCase, response.result.Success, response.result.Message);
verifyEqual(testCase, response.schemaVersion, ...
    "offlineSandboxResult/v1");
verifyTrue(testCase, startsWith(string(response.requestId), ...
    "bundle-replay-"));
verifyTrue(testCase, isfile(resultFilePath));
verifyEqual(testCase, numel(response.obstacles), 1);
verifyEqual(testCase, reproducedBundle.Format, ...
    "obstacleAvoidanceSandboxDiagnosis-v2");
verifyEqual(testCase, ...
    reproducedBundle.PlannerInputs.initialState.position_deg, [0 0]);
verifyEqual(testCase, ...
    reproducedBundle.PlannerInputs.goalState.position_deg, [1 0]);
verifyEqual(testCase, ...
    reproducedBundle.PlannerInputs.obstacles(1).time_s, time_s);
verifyEqual(testCase, ...
    reproducedBundle.PlannerInputs.obstacles(1).originalAz_deg{2}, ...
    azimuthBySlice_deg{2});
clear cleanup;
end

function testSuppliedFailureBundleReplaysUnderEightySeconds(testCase)
% Keep the supplied historical false negative as an exact feasible regression.
bundleFilePath = fullfile(testCase.TestData.RepositoryRoot, ...
    "Rogue Examples", "failed.mat");
resultFilePath = string(tempname) + ".json";
cleanup = onCleanup(@() deleteTestFiles(resultFilePath));

verifyTrue(testCase, isfile(bundleFilePath), ...
    "The supplied failed.mat diagnosis bundle must remain in the suite.");
[response, reproducedBundle] = ...
    offlineSandbox.replayDiagnosisBundle( ...
    bundleFilePath, resultFilePath);

verifyTrue(testCase, response.result.Success, response.result.Message);
verifyEqual(testCase, response.result.TerminationReason, "goalReached");
verifyTrue(testCase, reproducedBundle.IndependentValidation.Passed, ...
    reproducedBundle.IndependentValidation.Message);
verifyLessThan(testCase, response.result.ArrivalTime_s, 80, ...
    "The known feasible motion must arrive in less than 80 seconds.");
selectedSummary = reproducedBundle.Result.SeedSummaries( ...
    reproducedBundle.Result.SelectedSeedIndex);
verifyLessThan(testCase, selectedSummary.TravelTimeTradeoffCost_deg, 217, ...
    "Runtime reductions must preserve the known balanced-objective quality.");
verifyLessThan(testCase, reproducedBundle.Result.SearchDiagnostics.Grid. ...
    RouteCleanupCandidateCount, 1000, ...
    "Same-class route cleanup must not restore the discarded candidate sweep.");
verifyTrue(testCase, reproducedBundle.Result.SearchDiagnostics.Grid. ...
    HomologySearchTruncated, ...
    "The bounded route-class search must report its completeness limit.");
clear cleanup;
end

function request = createSyntheticRequest()
% Create a complete browser request without invoking the planner.
request = struct( ...
    "schemaVersion", "offlineSandboxRequest/v1", ...
    "requestId", "bundle-test-request", ...
    "obstacles", struct.empty(0, 1), ...
    "initialState", struct( ...
        "time_s", 0, ...
        "position_deg", [0 0], ...
        "velocity_deg_s", [0 0], ...
        "acceleration_deg_s2", [0 0]), ...
    "goalState", struct( ...
        "time_s", 5, ...
        "position_deg", [1 0], ...
        "velocity_deg_s", [0 0], ...
        "acceleration_deg_s2", [0 0]), ...
    "limits", struct( ...
        "maxVelocity_deg_s", [2 2], ...
        "maxAcceleration_deg_s2", [2 2], ...
        "maxJerk_deg_s3", [5 5], ...
        "azimuthInterval_deg", [-10 10], ...
        "elevationInterval_deg", [-10 10]), ...
    "options", struct("GoalTimeMode", "earliestArrival"));
end

function deleteTestFiles(varargin)
% Delete only temporary files created by one focused replay test.
for fileIndex = 1:numel(varargin)
    if isfile(varargin{fileIndex})
        delete(varargin{fileIndex});
    end
end
end
