function tests = testMinimalAzElWorkflow
%% Section 0: Header & Readme
% SYNTAX
%   tests = testMinimalAzElWorkflow
%**************************************************************************
% PURPOSE
%   - Verify the maintained direct RL policy planner and public utilities.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - tests (MATLAB function-test array)
%**************************************************************************
% UNITS
%   - Position is degrees. Time is seconds. Derivative units are stated in
%     the tested public fields.
%**************************************************************************
root = fileparts(fileparts(mfilename("fullpath")));
addpath(root, fullfile(root, "examples"));
tests = functiontests(localfunctions);
end

function testDefaultsDescribeRlPolicyMotion(testCase)
% PURPOSE
%   - Verify the RL policy-motion and safe-interval planner defaults.
options = planAzElMotion();
testCase.verifyEqual(options.GoalTimeMode, "earliestArrival");
testCase.verifyEqual(options.RlDurationTrialCount, 12);
testCase.verifyEqual(options.RlDurationTolerance_s, 0.01);
testCase.verifyTrue(options.UseSpaceTimeVisibilityGraph);
testCase.verifyEqual(options.SpaceTimeLayerCount, 17);
testCase.verifyEqual(options.MaximumSpaceTimeCandidateCount, 32);
testCase.verifyEqual(options.MaximumSippCandidates, 4);
testCase.verifyEqual(options.MaximumSippExpansions, 5000);
testCase.verifyEqual(options.MaximumSippPlanningFraction, 0.50);
testCase.verifyEqual(options.MinimumRlPolicySeedTime_s, 5);
testCase.verifyTrue(options.AllowSippWaiting);
testCase.verifyTrue(isfile(options.RpAgentFile));
testCase.verifyGreaterThan(options.RpTurnRadius_deg, 0);
testCase.verifyFalse(isfield(options, "MaximumRetimedVisibilityRoutes"));
end

function testExampleOptionResolverValidatesDisplayControls(testCase)
% PURPOSE
%   - Verify separate example-display and planner-option controls.
defaults = struct( ...
    "GoalTimeMode", "earliestArrival", ...
    "FigureVisible", "off");
testCase.verifyWarning(@() resolveAzElExampleOptions( ...
    struct("StaleControl", true), defaults, [2.5 2.5]), ...
    "resolveAzElExampleOptions:UnknownOptions");
testCase.verifyError(@() resolveAzElExampleOptions( ...
    struct("PlotOutputs", 2), defaults, [2.5 2.5]), ...
    "resolveAzElExampleOptions:InvalidLogicalControl");

[plannerOptions, configuration] = resolveAzElExampleOptions( ...
    struct("Verbose", false), defaults, [2.5 2.5]);
testCase.verifyEqual(plannerOptions.GoalTimeMode, "earliestArrival");
testCase.verifyFalse(plannerOptions.Verbose);
testCase.verifyTrue(configuration.JerkConstraintEnabled);
testCase.verifyEqual(configuration.MaxJerk_deg_s3, [2.5 2.5]);
testCase.verifyEqual(configuration.FigureVisible, "off");
testCase.verifyFalse(isfield(plannerOptions, "FigureVisible"));
testCase.verifyError(@() resolveAzElExampleOptions( ...
    struct("EnableJerkConstraint", false), defaults, [2.5 2.5]), ...
    "resolveAzElExampleOptions:RemovedJerkToggle");
end

function testStaticBlockerProvidesOppositeTopologySeeds(testCase)
% PURPOSE
%   - Retain distinct upper and lower seeds around a symmetric blocker.
obstacle = makeAzElObstacleData("symmetric blocker", [0; 20], ...
    [-0.5; 0.5; 0.5; -0.5], [-1; -1; 1; 1], 0.1);
[initialState, goalState, limits] = standardRequest([-3 0], [3 0], 20);
options = fastOptions(2);
options.MaximumPlanningTime_s = 5;
result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

seeds = result.SearchDiagnostics.CandidateSeeds;
testCase.verifyGreaterThanOrEqual(numel(seeds), 2);
hasUpperRoute = false;
hasLowerRoute = false;
for seedIndex = 1:numel(seeds)
    routeElevation_deg = seeds(seedIndex).Route_deg(:, 2);
    hasUpperRoute = hasUpperRoute || max(routeElevation_deg) > 1;
    hasLowerRoute = hasLowerRoute || min(routeElevation_deg) < -1;
end
testCase.verifyTrue(hasUpperRoute);
testCase.verifyTrue(hasLowerRoute);
end

function testMovingBlockerPreservesOppositeTopologySeeds(testCase)
% PURPOSE
%   - Keep distinct route geometry before extra moving-snapshot time laws.
firstAzimuth_deg = [-0.6; 0.4; 0.4; -0.6];
lastAzimuth_deg = [-0.4; 0.6; 0.6; -0.4];
elevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData("moving symmetric blocker", [0; 20], ...
    {firstAzimuth_deg; lastAzimuth_deg}, ...
    {elevation_deg; elevation_deg}, 0.1);
[initialState, goalState, limits] = standardRequest([-3 0], [3 0], 20);
options = fastOptions(2);
options.MaximumPlanningTime_s = 5;
options.MaximumVisibilitySnapshotsPerObstacle = 2;
options.DetectSnapshotEvents = false;
result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

seeds = result.SearchDiagnostics.CandidateSeeds;
testCase.verifyEqual(numel(seeds), 2);
testCase.verifyFalse(result.SearchDiagnostics. ...
    ObstacleGeometryTimeInvariant);
hasUpperRoute = false;
hasLowerRoute = false;
for seedIndex = 1:numel(seeds)
    routeElevation_deg = seeds(seedIndex).Route_deg(:, 2);
    hasUpperRoute = hasUpperRoute || max(routeElevation_deg) > 1;
    hasLowerRoute = hasLowerRoute || min(routeElevation_deg) < -1;
end
testCase.verifyTrue(hasUpperRoute);
testCase.verifyTrue(hasLowerRoute);
end

function testStaticBlockerCarriesSpeedThroughTurn(testCase)
% PURPOSE
%   - Verify that the RL route carries speed through a certified turn.
obstacle = makeAzElObstacleData("static blocker", [0; 20], ...
    [-0.5; 0.5; 0.5; -0.5], [-1; -1; 1; 1], 0.1);
[initialState, goalState, limits] = standardRequest( ...
    [-3 0], [3 0], 20);
options = fastOptions(3);
options.UseParallel = "on";
result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);
testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(any(result.directBlocked));
testCase.verifyGreaterThan(size(result.selectedRoute_deg, 1), 2);
blocked = queryAzElTimedPathCollision(result.obstacleField, ...
    result.time_s, result.position_deg);
testCase.verifyFalse(any(blocked));

speed_deg_s = vecnorm(result.velocity_deg_s, 2, 2);
curvatureNumerator = abs(result.velocity_deg_s(:, 1) .* ...
    result.acceleration_deg_s2(:, 2) - ...
    result.velocity_deg_s(:, 2) .* ...
    result.acceleration_deg_s2(:, 1));
curvature = curvatureNumerator ./ max(speed_deg_s .^ 3, 1e-8);
turnMask = abs(result.position_deg(:, 1)) < 1.5 & ...
    result.time_s > result.time_s(1) + 0.1 * ...
    (result.time_s(end) - result.time_s(1)) & ...
    result.time_s < result.time_s(1) + 0.9 * ...
    (result.time_s(end) - result.time_s(1));
curvature(~turnMask) = -Inf;
[~, maximumCurvatureIndex] = max(curvature);
testCase.verifyGreaterThan(speed_deg_s(maximumCurvatureIndex), 0.05);
testCase.verifyGreaterThan(min(speed_deg_s(turnMask)), 1e-3);
interiorSeed_deg = result.selectedRoute_deg(2:end - 1, :);
minimumSeedDistance_deg = Inf;
for seedIndex = 1:size(interiorSeed_deg, 1)
    minimumSeedDistance_deg = min(minimumSeedDistance_deg, min(vecnorm( ...
        result.position_deg - interiorSeed_deg(seedIndex, :), 2, 2)));
end
testCase.verifyLessThanOrEqual(minimumSeedDistance_deg, 1e-7);
stopBaseline_s = deliberateStopBaseline( ...
    result.selectedRoute_deg, limits);
testCase.verifyLessThanOrEqual(result.time_s(end) - result.time_s(1), ...
    stopBaseline_s);
exampleValidation = validateAzElExampleResult( ...
    result, "static blocker regression");
testCase.verifyTrue(exampleValidation.SafetyMarginPolicySatisfied);
testCase.verifyTrue(exampleValidation.BufferedChordQueryClear);
tamperedResult = result;
tamperedResult.azElData(1).az_deg{1}(1) = ...
    tamperedResult.azElData(1).az_deg{1}(1) + 1e-4;
tamperedValidation = validateAzElExampleResult( ...
    tamperedResult, "tampered margin provenance");
testCase.verifyFalse(tamperedValidation.SafetyMarginPolicySatisfied);
selectedDiagnostic = result.SearchDiagnostics.CandidatePolicyMotions( ...
    result.selectedCandidateIndex);
testCase.verifyEqual(selectedDiagnostic.SeedRoute_deg, ...
    result.selectedRoute_deg);
testCase.verifyTrue(selectedDiagnostic.CollisionFree);
testCase.verifyTrue(selectedDiagnostic.BufferedChordQueryClear);
testCase.verifyTrue(selectedDiagnostic.CollisionSafetyProven);
testCase.verifyTrue(selectedDiagnostic.Validation.Passed);
testCase.verifyTrue(result.candidateDiagnostics. ...
    BufferedChordQueryClear(result.selectedCandidateIndex));
testCase.verifyTrue(contains(result.SearchDiagnostics. ...
    CollisionValidationMethod, "quintic curve tube"));
testCase.verifyEqual(selectedDiagnostic.MaximumVelocity_deg_s, ...
    result.Validation.MaximumVelocity_deg_s, "AbsTol", 1e-12);
testCase.verifyEqual(result.SearchDiagnostics. ...
    RlPolicyParallelExecution.RequestedMode, "on");
testCase.verifyGreaterThanOrEqual(result.SearchDiagnostics. ...
    RlPolicyParallelExecution.TaskCount, 2);
end

function testMovingObstacleUsesActualTime(testCase)
% PURPOSE
%   - Verify direct optimization against interpolated moving geometry.
wallAzimuth_deg = repmat({[-0.4; 0.4; 0.4; -0.4]}, 3, 1);
wallElevation_deg = {[-2; -2; 2; 2]; [3; 3; 7; 7]; [3; 3; 7; 7]};
obstacle = makeAzElObstacleData("moving wall", [0; 4; 15], ...
    wallAzimuth_deg, wallElevation_deg, 0.05);
[initialState, goalState, limits] = standardRequest( ...
    [-3 0], [3 0], 15);
result = planAzElMotion(obstacle, initialState, goalState, limits, ...
    fastOptions(3));
testCase.verifyTrue(result.Success, result.Message);
blocked = queryAzElTimedPathCollision(result.obstacleField, ...
    result.time_s, result.position_deg);
testCase.verifyFalse(any(blocked));
testCase.verifyTrue(result.SearchDiagnostics. ...
    WaitingIsPreservedFromTimedSeed);
testCase.verifyEmpty(result.SearchDiagnostics.DepartureTimeCandidates_s);
selectedDiagnostic = result.SearchDiagnostics.CandidatePolicyMotions( ...
    result.selectedCandidateIndex);
testCase.verifyTrue(selectedDiagnostic.CollisionFree);
testCase.verifyTrue(selectedDiagnostic.CollisionSafetyProven);
end

function testFixedArrivalEndsAtNormalizedGoalTime(testCase)
% PURPOSE
%   - Verify exact fixed arrival after mixed-case option normalization.
[initialState, goalState, limits] = standardRequest([0 0], [2 0], 8);
options = fastOptions(1);
options.GoalTimeMode = "FiXeDArRiVaL";
result = planAzElMotion([], initialState, goalState, limits, options);

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
testCase.verifyTrue(result.Validation.GoalTimeSatisfied);
testCase.verifyEqual(result.Options.GoalTimeMode, "fixedarrival");
testCase.verifyEqual(result.time_s(end), goalState.time_s, ...
    "AbsTol", result.Options.KinematicValidationTolerance);
testCase.verifyEqual(result.goalLineInterceptTime_s, goalState.time_s, ...
    "AbsTol", result.Options.KinematicValidationTolerance);
selectedDiagnostic = result.SearchDiagnostics.CandidatePolicyMotions( ...
    result.selectedCandidateIndex);
testCase.verifyTrue(selectedDiagnostic.Success);
testCase.verifyEqual(selectedDiagnostic.MotionDuration_s, ...
    goalState.time_s - initialState.time_s, ...
    "AbsTol", result.Options.KinematicValidationTolerance);
testCase.verifyEmpty(selectedDiagnostic.SolverExitFlagHistory);
end

function testFixedArrivalRejectsBlockedDirectSeed(testCase)
% PURPOSE
%   - Verify that alternate times cannot admit a fixed-time direct seed.
obstacle = makeAzElObstacleData("fixed blocker", [0; 10], ...
    [-0.5; 0.5; 0.5; -0.5], [-1; -1; 1; 1], 0.1);
[initialState, goalState, limits] = standardRequest([-3 0], [3 0], 10);
options = fastOptions(1);
options.GoalTimeMode = "fixedArrival";
options.MaximumPlanningTime_s = 5;
result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

testCase.verifyTrue(any(result.directBlocked));
testCase.verifyEqual(result.SearchDiagnostics.CandidateSeedCount, 1);
testCase.verifyGreaterThan(size(result.candidateRoutes_deg{1}, 1), 2);
end

function testFixedArrivalKeepsClearNonuniformDirectTimeLaw(testCase)
% PURPOSE
%   - Keep a moving-obstacle direct seed when nonuniform progress is clear.
blockedAzimuth_deg = [-0.5; 0.5; 0.5; -0.5];
clearAzimuth_deg = [5.5; 6.5; 6.5; 5.5];
elevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData("departing blocker", ...
    [0; 6; 6.1; 10], ...
    {blockedAzimuth_deg; blockedAzimuth_deg; ...
    clearAzimuth_deg; clearAzimuth_deg}, ...
    {elevation_deg; elevation_deg; elevation_deg; elevation_deg}, 0.1);
[initialState, goalState, limits] = standardRequest([-3 0], [3 0], 10);
options = fastOptions(1);
options.GoalTimeMode = "fixedArrival";
options.MaximumPlanningTime_s = 5;
result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

testCase.verifyTrue(any(result.directBlocked));
testCase.verifyEqual(result.SearchDiagnostics.CandidateSeedCount, 1);
seed = result.SearchDiagnostics.CandidateSeeds(1);
testCase.verifyEqual(seed.Source, "direct");
testCase.verifyGreaterThan(size(seed.Route_deg, 1), 2);
testCase.verifyEqual(numel(seed.RouteTime_s), size(seed.Route_deg, 1));
testCase.verifyEqual(seed.RouteTime_s([1 end]), [0; 10], ...
    "AbsTol", 1e-12);
end

function testEarliestArrivalKeepsClearDirectSeed(testCase)
% PURPOSE
%   - Keep an early direct seed when the goal is blocked only at horizon.
clearAzimuth_deg = [1.5; 2.5; 2.5; 1.5];
clearElevation_deg = [4; 4; 5; 5];
blockedElevation_deg = [-0.5; -0.5; 0.5; 0.5];
obstacle = makeAzElObstacleData( ...
    "late goal cover", [0; 8; 10], ...
    {clearAzimuth_deg; clearAzimuth_deg; clearAzimuth_deg}, ...
    {clearElevation_deg; clearElevation_deg; blockedElevation_deg}, 0);
[initialState, goalState, limits] = standardRequest([0 0], [2 0], 10);
options = fastOptions(1);
options.GoalTimeMode = "earliestArrival";
options.MaximumPlanningTime_s = 60;

result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

testCase.verifyTrue(queryAzElTimeObstacle( ...
    result.obstacleField, goalState.position_deg(1), ...
    goalState.position_deg(2), goalState.time_s));
testCase.verifyTrue(any(result.directBlocked));
testCase.verifyNotEqual(result.TerminationReason, "endpointBlocked");
testCase.verifyTrue(result.Success, result.Message);
testCase.verifyLessThan(result.time_s(end), 8);
seedSources = [result.SearchDiagnostics.CandidatePolicyMotions. ...
    SeedSource];
testCase.verifyTrue(any(seedSources == "direct"));
end

function testStaticSeedCopiesCollapseButMovingCopiesRemain(testCase)
% PURPOSE
%   - Remove static time copies while retaining moving-obstacle time laws.
squareAzimuth_deg = [-0.5; 0.5; 0.5; -0.5];
squareElevation_deg = [-3; -3; -2; -2];
staticObstacle = makeAzElObstacleData( ...
    "static seed field", [0; 10], ...
    {squareAzimuth_deg; squareAzimuth_deg}, ...
    {squareElevation_deg; squareElevation_deg}, 0);
movingTime_s = [0; 2.5; 5; 7.5; 10];
movingAzimuth_deg = cell(numel(movingTime_s), 1);
movingElevation_deg = repmat( ...
    {squareElevation_deg}, numel(movingTime_s), 1);
for sampleIndex = 1:numel(movingTime_s)
    movingAzimuth_deg{sampleIndex} = squareAzimuth_deg + ...
        5e-11 * (sampleIndex - 1) / (numel(movingTime_s) - 1);
end
movingObstacle = makeAzElObstacleData( ...
    "moving seed field", movingTime_s, movingAzimuth_deg, ...
    movingElevation_deg, 0);
[initialState, goalState, limits] = standardRequest( ...
    [-3 2], [3 2], 10);
options = fastOptions(8);
options.GoalTimeMode = "fixedArrival";
options.MaximumVisibilitySnapshotsPerObstacle = 2;
options.DetectSnapshotEvents = false;
options.TemporalSeedSampleTimes_s = [0; 10];
options.MaximumPlanningTime_s = 5;

staticResult = planAzElMotion( ...
    staticObstacle, initialState, goalState, limits, options);
movingResult = planAzElMotion( ...
    movingObstacle, initialState, goalState, limits, options);

testCase.verifyTrue(staticResult.SearchDiagnostics. ...
    ObstacleGeometryTimeInvariant);
testCase.verifyFalse(movingResult.SearchDiagnostics. ...
    ObstacleGeometryTimeInvariant);
testCase.verifyEqual(staticResult.SearchDiagnostics.CandidateSeedCount, 1);
movingSeeds = movingResult.SearchDiagnostics.CandidateSeeds;
testCase.verifyGreaterThanOrEqual(numel(movingSeeds), 2);
hasCrossTimeRouteCopy = false;
for firstSeedIndex = 1:numel(movingSeeds) - 1
    for secondSeedIndex = firstSeedIndex + 1:numel(movingSeeds)
        firstRoute_deg = movingSeeds(firstSeedIndex).Route_deg;
        secondRoute_deg = movingSeeds(secondSeedIndex).Route_deg;
        sameRoute = isequal(size(firstRoute_deg), size(secondRoute_deg)) && ...
            max(abs(firstRoute_deg - secondRoute_deg), [], "all") <= 1e-10;
        differentTime = abs(movingSeeds(firstSeedIndex).SnapshotTime_s - ...
            movingSeeds(secondSeedIndex).SnapshotTime_s) > 1e-10;
        hasCrossTimeRouteCopy = hasCrossTimeRouteCopy || ...
            (sameRoute && differentTime);
    end
end
testCase.verifyTrue(hasCrossTimeRouteCopy);

cappedOptions = options;
cappedOptions.MaximumVisibilitySnapshotsPerObstacle = 5;
cappedOptions.TemporalSeedSampleTimes_s = movingTime_s;
cappedOptions.MaximumRlPolicySeeds = 3;
cappedResult = planAzElMotion( ...
    movingObstacle, initialState, goalState, limits, cappedOptions);
cappedSeeds = cappedResult.SearchDiagnostics.CandidateSeeds;
cappedSnapshotTime_s = [cappedSeeds.SnapshotTime_s];
testCase.verifyEqual(numel(cappedSeeds), 3);
testCase.verifyEqual(cappedSnapshotTime_s, [0 2.5 10], ...
    "AbsTol", 1e-12);
testCase.verifyGreaterThan( ...
    cappedResult.SearchDiagnostics.SeedCapDroppedCount, 0);
testCase.verifyGreaterThan( ...
    cappedResult.SearchDiagnostics.DeduplicatedCandidateSeedCount, ...
    cappedResult.SearchDiagnostics.CandidateSeedCount);

uncappedTemporalOptions = cappedOptions;
uncappedTemporalOptions.MaximumRlPolicySeeds = 8;
uncappedTemporalResult = planAzElMotion( ...
    movingObstacle, initialState, goalState, limits, ...
    uncappedTemporalOptions);
uncappedTemporalSeeds = ...
    uncappedTemporalResult.SearchDiagnostics.CandidateSeeds;
testCase.verifyGreaterThanOrEqual(numel(uncappedTemporalSeeds), 2);
cheapestTopologyTime_s = uncappedTemporalSeeds(2).SnapshotTime_s;

twoSeedOptions = cappedOptions;
twoSeedOptions.MaximumRlPolicySeeds = 2;
twoSeedResult = planAzElMotion( ...
    movingObstacle, initialState, goalState, limits, twoSeedOptions);
twoSeedSnapshotTime_s = [twoSeedResult.SearchDiagnostics. ...
    CandidateSeeds.SnapshotTime_s];
testCase.verifyEqual(twoSeedSnapshotTime_s, ...
    [0 cheapestTopologyTime_s], ...
    "AbsTol", 1e-12);
end

function testNonzeroInitialMotionIsContinued(testCase)
% PURPOSE
%   - Verify exact nonzero endpoint motion without an artificial hold.
[initialState, goalState, limits] = standardRequest([0 0], [4 1], 12);
initialState.velocity_deg_s = [0.4 0.1];
initialState.acceleration_deg_s2 = [0.1 0];
result = planAzElMotion([], initialState, goalState, limits, ...
    fastOptions(1));
testCase.verifyTrue(result.Success, result.Message);
testCase.verifyEqual(result.velocity_deg_s(1, :), ...
    initialState.velocity_deg_s, "AbsTol", 1e-8);
testCase.verifyEqual(result.acceleration_deg_s2(1, :), ...
    initialState.acceleration_deg_s2, "AbsTol", 1e-8);
testCase.verifyGreaterThan(norm(result.position_deg(2, :) - ...
    result.position_deg(1, :)), 0);
end

function testInfeasibleHorizonReturnsStableFailure(testCase)
% PURPOSE
%   - Verify clean failure when the horizon violates a dynamic lower bound.
[initialState, goalState, limits] = standardRequest([0 0], [10 0], 1);
result = planAzElMotion([], initialState, goalState, limits, ...
    fastOptions(1));
testCase.verifyFalse(result.Success);
testCase.verifyEqual(result.TerminationReason, "goalTimeInfeasible");
testCase.verifyNotEmpty(result.SearchDiagnostics.CandidatePolicyMotions);
candidate = result.SearchDiagnostics.CandidatePolicyMotions(1);
testCase.verifyFalse(candidate.CollisionValidationPerformed);
testCase.verifyFalse(result.candidateDiagnostics. ...
    ContinuousCollisionChecked(1));
end

function testEndpointLimitViolationReturnsStableFailure(testCase)
% PURPOSE
%   - Verify clean failure for an impossible supplied endpoint state.
[initialState, goalState, limits] = standardRequest([0 0], [1 0], 10);
initialState.velocity_deg_s = [3 0];
result = planAzElMotion([], initialState, goalState, limits, ...
    fastOptions(1));
testCase.verifyFalse(result.Success);
testCase.verifyEqual(result.TerminationReason, ...
    "dynamicEndpointInfeasible");
testCase.verifyEmpty(result.time_s);
end

function testContinuousMovingCollisionQuery(testCase)
% PURPOSE
%   - Retain a focused regression for public time-continuous collision.
obstacle = makeAzElObstacleData("crossing square", [0; 2], ...
    {[-2; -1; -1; -2]; [1; 2; 2; 1]}, ...
    {[-0.5; -0.5; 0.5; 0.5]; [-0.5; -0.5; 0.5; 0.5]}, 0);
farObstacle = makeAzElObstacleData("far moving square", [0; 2], ...
    {[40; 41; 41; 40]; [42; 43; 43; 42]}, ...
    {[-0.5; -0.5; 0.5; 0.5]; [-0.5; -0.5; 0.5; 0.5]}, 0);
field = buildAzElTimeObstacleField( ...
    combineAzElObstacles(obstacle, farObstacle));
[blocked, details] = queryAzElTimedPathCollision( ...
    field, [0; 2], [0 0; 0 0]);
testCase.verifyTrue(any(blocked));
testCase.verifyGreaterThan( ...
    details.BroadPhaseRejectedObstacleSegmentPairCount, 0);
testCase.verifyLessThan( ...
    details.EvaluatedObstacleSegmentPairCount, ...
    field.ObstacleCount);
end

function testMovingPointHistoryUsesCanonicalObstacleConstructor(testCase)
% PURPOSE
%   - Verify moving obstacle interpolation through the public constructor.
squareAzimuth_deg = {[-2; 0; 0; -2], [1; 3; 3; 1]};
squareElevation_deg = {[-1; -1; 1; 1], [-1; -1; 1; 1]};
obstacle = makeAzElObstacleData( ...
    "moving obstacle", [0; 20], squareAzimuth_deg, ...
    squareElevation_deg, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);

testCase.verifyEqual(obstacleField.ObstacleCount, 1);
testCase.verifyTrue(queryAzElTimeObstacle( ...
    obstacleField, -1, 0, 0));
testCase.verifyTrue(queryAzElTimeObstacle( ...
    obstacleField, 2, 0, 20));
testCase.verifyFalse(queryAzElTimeObstacle( ...
    obstacleField, -1, 0, 20));
end

function testContinuousMovingCollisionIsNotSliceAliased(testCase)
% PURPOSE
%   - Detect an obstacle crossing between its supplied time slices.
leftSquareAzimuth_deg = [-3; -1; -1; -3];
rightSquareAzimuth_deg = [1; 3; 3; 1];
squareElevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData( ...
    "crossing square", [0; 10], ...
    {leftSquareAzimuth_deg; rightSquareAzimuth_deg}, ...
    {squareElevation_deg; squareElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);

testCase.verifyTrue(queryAzElTimeObstacle( ...
    obstacleField, 0, 0, 5));
fullCrossing = queryAzElTimedPathCollision( ...
    obstacleField, [0; 10], [0 0; 0 0], struct( ...
    "TimePaddingSamples", 0));
earlyClear = queryAzElTimedPathCollision( ...
    obstacleField, [0; 2], [0 0; 0 0], struct( ...
    "TimePaddingSamples", 0));
testCase.verifyTrue(any(fullCrossing));
testCase.verifyFalse(any(earlyClear));
end

function testSpaceTimeGraphUsesEarlyLowerDetour(testCase)
% PURPOSE
%   - Select an early lower route when one obstacle rises too slowly to wait.
squareAzimuth_deg = [-1; 1; 1; -1];
initialElevation_deg = [-1; -1; 1; 1];
finalElevation_deg = [3; 3; 5; 5];
obstacle = makeAzElObstacleData( ...
    "slowly rising square", [0; 20], ...
    {squareAzimuth_deg; squareAzimuth_deg}, ...
    {initialElevation_deg; finalElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-6 0]);
goalState = struct("time_s", 20, "position_deg", [6 0]);
search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct( ...
    "UseParallel", "off", ...
    "BuildSpaceTimeVisibilityGraph", true, ...
    "MaximumVelocity_deg_s", [2 2], ...
    "SpaceTimeLayerCount", 17, ...
    "MaximumSpaceTimeCandidateCount", 16, ...
    "MaximumSpaceTimeDiagnosticEdgeCount", 2000));
graph = search.SpaceTimeVisibilityGraph;

testCase.verifyTrue(graph.Success, graph.Message);
testCase.verifyEqual(graph.TerminationReason, "goalReached");
testCase.verifyLessThan(graph.ArrivalTime_s, 10);
testCase.verifyLessThanOrEqual(min(graph.PathPosition_deg(:, 2)), -1);
testCase.verifyEqual(graph.WaitDuration_s, 0, "AbsTol", 1e-12);
testCase.verifyGreaterThan(graph.CollisionRejectedEdgeCount, 0);
edgeVelocity_deg_s = abs(diff(graph.PathPosition_deg, 1, 1)) ./ ...
    diff(graph.PathTime_s);
testCase.verifyLessThanOrEqual(edgeVelocity_deg_s, ...
    repmat([2 2], size(edgeVelocity_deg_s, 1), 1) + 1e-10);
collisionMask = queryAzElTimedPathCollision( ...
    obstacleField, graph.PathTime_s, graph.PathPosition_deg, struct( ...
    "BoundaryIsOccupied", false));
testCase.verifyFalse(any(collisionMask));
end

function testSafeIntervalRoadmapProducesDiverseStaticRoutes(testCase)
% PURPOSE
%   - Retain two static route classes as distinct SIPP candidates.
squareAzimuth_deg = [-1; 1; 1; -1];
squareElevation_deg = [-2; -2; 2; 2];
obstacle = makeAzElObstacleData( ...
    "symmetric blocker", [0; 20], ...
    {squareAzimuth_deg; squareAzimuth_deg}, ...
    {squareElevation_deg; squareElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-6 0]);
goalState = struct("time_s", 20, "position_deg", [6 0]);
search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct( ...
    "UseParallel", "off", ...
    "BuildSpaceTimeVisibilityGraph", true, ...
    "MaximumVelocity_deg_s", [2 2], ...
    "MaximumAcceleration_deg_s2", [1 1], ...
    "MaximumJerk_deg_s3", [2 2], ...
    "MaximumSippCandidates", 4));
graph = search.SpaceTimeVisibilityGraph;

testCase.verifyTrue(graph.Success, graph.Message);
testCase.verifyEqual(graph.Representation, ...
    "safeIntervalVisibilityRoadmap");
testCase.verifyEqual(graph.SearchMethod, ...
    "safeIntervalPathPlanningWithIntervalProjection");
testCase.verifyGreaterThan(graph.ProjectedIntervalCount, 0);
testCase.verifyGreaterThan( ...
    graph.InvariantTraversalSampleSkipCount, 0);
testCase.verifyGreaterThan(graph.TraversalQueryCount, 0);
testCase.verifyGreaterThanOrEqual( ...
    graph.CollisionRejectedTransitionCount, ...
    graph.InvariantTraversalSampleSkipCount);
reachedState = isfinite(graph.EarliestArrival_s);
testCase.verifyGreaterThanOrEqual( ...
    graph.ReachableIntervalStop_s(reachedState), ...
    graph.EarliestArrival_s(reachedState));
testCase.verifyGreaterThanOrEqual(graph.DiverseCandidateCount, 2);
candidates = graph.DiverseCandidates;
hasLowerRoute = false;
hasUpperRoute = false;
for candidateIndex = 1:numel(candidates)
    testCase.verifyTrue(all(diff(candidates(candidateIndex).Time_s) > 0));
    edgeStep_deg = diff(candidates(candidateIndex).Position_deg, 1, 1);
    edgeDuration_s = diff(candidates(candidateIndex).Time_s);
    jerkLowerBound_s = max((32 * abs(edgeStep_deg) ./ [2 2]) .^ ...
        (1 / 3), [], 2);
    testCase.verifyGreaterThanOrEqual( ...
        edgeDuration_s, jerkLowerBound_s - 1e-10);
    hasLowerRoute = hasLowerRoute || ...
        min(candidates(candidateIndex).Position_deg(:, 2)) < -1;
    hasUpperRoute = hasUpperRoute || ...
        max(candidates(candidateIndex).Position_deg(:, 2)) > 1;
end
testCase.verifyTrue(hasLowerRoute);
testCase.verifyTrue(hasUpperRoute);
end

function testSippIntervalProjectionHonorsSharedWallTime(testCase)
% PURPOSE
%   - Stop all SIPP-IP diversity runs at one shared wall-time limit.
squareAzimuth_deg = [-1; 1; 1; -1];
squareElevation_deg = [-2; -2; 2; 2];
obstacle = makeAzElObstacleData( ...
    "shared-time blocker", [0; 20], ...
    {squareAzimuth_deg; squareAzimuth_deg}, ...
    {squareElevation_deg; squareElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-6 0]);
goalState = struct("time_s", 20, "position_deg", [6 0]);
search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct( ...
    "UseParallel", "off", ...
    "BuildSpaceTimeVisibilityGraph", true, ...
    "MaximumVelocity_deg_s", [2 2], ...
    "MaximumSippWallTime_s", eps));
graph = search.SpaceTimeVisibilityGraph;

testCase.verifyFalse(graph.Success);
testCase.verifyEqual(graph.TerminationReason, "searchTimeLimit");
testCase.verifyTrue( ...
    graph.CandidateGenerationDiagnostics.SharedTimeLimitReached);
testCase.verifyLessThan( ...
    graph.CandidateGenerationDiagnostics.ElapsedSearchTime_s, 1);
end

function testPlannerUsesEarliestTimeClearRoute(testCase)
% PURPOSE
%   - Select and validate the earliest route that clears the rising body.
squareAzimuth_deg = [-1; 1; 1; -1];
obstacle = makeAzElObstacleData( ...
    "slowly rising square", [0; 20], ...
    {squareAzimuth_deg; squareAzimuth_deg}, ...
    {[-1; -1; 1; 1]; [3; 3; 5; 5]}, 0);
[initialState, goalState, limits] = ...
    standardRequest([-6 0], [6 0], 20);
options = fastOptions(8);
options.MaximumVisibilitySnapshotsPerObstacle = 2;
options.DetectSnapshotEvents = false;
options.SpaceTimeLayerCount = 17;
options.MaximumSpaceTimeCandidateCount = 16;

result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.Validation.Passed, result.Validation.Message);
selected = result.SearchDiagnostics.CandidatePolicyMotions( ...
    result.selectedCandidateIndex);
candidateDiagnostics = ...
    result.SearchDiagnostics.CandidatePolicyMotions;
spaceTimeIndex = find([candidateDiagnostics.SeedSource] == ...
    "spaceTimeVisibilityGraph", 1);
testCase.verifyNotEmpty(spaceTimeIndex);
spaceTimeDiagnostic = candidateDiagnostics(spaceTimeIndex);
testCase.verifyTrue(spaceTimeDiagnostic.TimedSeedLawUsed);
spaceTimeGraph = result.SearchDiagnostics.SpaceTimeVisibilityGraph;
expectedTimeFraction = (spaceTimeGraph.PathTime_s - ...
    spaceTimeGraph.PathTime_s(1)) / ...
    (spaceTimeGraph.PathTime_s(end) - spaceTimeGraph.PathTime_s(1));
routeStep_deg = diff(spaceTimeGraph.PathPosition_deg, 1, 1);
routeArc_deg = [0; cumsum(vecnorm(routeStep_deg, 2, 2))];
expectedProgress = routeArc_deg / routeArc_deg(end);
testCase.verifyEqual(spaceTimeDiagnostic.SeedRouteTimeFraction, ...
    expectedTimeFraction, "AbsTol", 1e-12);
testCase.verifyEqual(spaceTimeDiagnostic.SeedRouteProgress, ...
    expectedProgress, "AbsTol", 1e-12);
crossingIndex = find(result.position_deg(:, 1) >= 0, 1, "first");
testCase.verifyNotEmpty(crossingIndex);
crossingBlocked = queryAzElTimeObstacle( ...
    result.obstacleField, result.position_deg(crossingIndex, 1), ...
    result.position_deg(crossingIndex, 2), ...
    result.time_s(crossingIndex));
testCase.verifyFalse(crossingBlocked);
testCase.verifyTrue(selected.CollisionSafetyProven);
movementStep_deg = vecnorm(diff(result.position_deg, 1, 1), 2, 2);
firstMovingSegmentIndex = find(movementStep_deg > 1e-6, 1, "first");
testCase.verifyEqual(firstMovingSegmentIndex, 1);
directIndex = find([result.SearchDiagnostics.CandidatePolicyMotions. ...
    SeedSource] == "direct", 1);
testCase.verifyNotEmpty(directIndex);
testCase.verifyTrue(result.SearchDiagnostics. ...
    CandidatePolicyMotions(directIndex).Success);
testCase.verifyLessThan(selected.ObjectiveArrivalTime_s, ...
    result.SearchDiagnostics.CandidatePolicyMotions( ...
    directIndex).ObjectiveArrivalTime_s);
end

function testSpaceTimeGraphWaitsForFastOpening(testCase)
% PURPOSE
%   - Select waiting when a tall barrier clears before its long detour.
barrierAzimuth_deg = [-1; 1; 1; -1];
closedElevation_deg = [-10; -10; 10; 10];
openElevation_deg = [1; 1; 21; 21];
obstacleTime_s = [0; 4.999; 5.001; 20];
obstacle = makeAzElObstacleData( ...
    "opening tall barrier", obstacleTime_s, ...
    {barrierAzimuth_deg; barrierAzimuth_deg; ...
    barrierAzimuth_deg; barrierAzimuth_deg}, ...
    {closedElevation_deg; closedElevation_deg; ...
    openElevation_deg; openElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-6 0]);
goalState = struct("time_s", 20, "position_deg", [6 0]);
search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct( ...
    "UseParallel", "off", ...
    "BuildSpaceTimeVisibilityGraph", true, ...
    "MaximumVelocity_deg_s", [2 2], ...
    "SpaceTimeLayerCount", 17, ...
    "MaximumSpaceTimeCandidateCount", 16, ...
    "MaximumSpaceTimeDiagnosticEdgeCount", 2000));
graph = search.SpaceTimeVisibilityGraph;

testCase.verifyTrue(graph.Success, graph.Message);
testCase.verifyGreaterThan(graph.WaitDuration_s, 0);
testCase.verifyEqual(graph.PathCost_deg, 12, "AbsTol", 1e-10);
testCase.verifyEqual(unique(graph.PathPosition_deg, "rows"), ...
    [-6 0; 6 0]);
testCase.verifyLessThan(graph.ArrivalTime_s, 10);
collisionMask = queryAzElTimedPathCollision( ...
    obstacleField, graph.PathTime_s, graph.PathPosition_deg, struct( ...
    "BoundaryIsOccupied", false));
testCase.verifyFalse(any(collisionMask));
end

function testPlannerRetainsTimedSpaceTimeSeed(testCase)
% PURPOSE
%   - Pass the selected space-time path and its time law to optimization.
squareAzimuth_deg = [-1; 1; 1; -1];
obstacle = makeAzElObstacleData( ...
    "timed seed square", [0; 20], ...
    {squareAzimuth_deg; squareAzimuth_deg}, ...
    {[-1; -1; 1; 1]; [3; 3; 5; 5]}, 0);
[initialState, goalState, limits] = standardRequest([-6 0], [6 0], 20);
options = fastOptions(8);
options.MaximumPlanningTime_s = 5;
options.MaximumSippPlanningFraction = 1;
options.MaximumVisibilitySnapshotsPerObstacle = 2;
options.DetectSnapshotEvents = false;
options.SpaceTimeLayerCount = 17;
options.MaximumSpaceTimeCandidateCount = 16;

result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);
seeds = result.SearchDiagnostics.CandidateSeeds;
spaceTimeSeedIndex = find( ...
    [seeds.Source] == "spaceTimeVisibilityGraph", 1);

testCase.verifyNotEmpty(spaceTimeSeedIndex);
spaceTimeSeed = seeds(spaceTimeSeedIndex);
spaceTimeGraph = result.SearchDiagnostics.SpaceTimeVisibilityGraph;
expectedTimeFraction = (spaceTimeGraph.PathTime_s - ...
    spaceTimeGraph.PathTime_s(1)) / ...
    (spaceTimeGraph.PathTime_s(end) - spaceTimeGraph.PathTime_s(1));
routeStep_deg = diff(spaceTimeGraph.PathPosition_deg, 1, 1);
routeArc_deg = [0; cumsum(vecnorm(routeStep_deg, 2, 2))];
expectedProgress = routeArc_deg / routeArc_deg(end);
testCase.verifyGreaterThan( ...
    numel(spaceTimeSeed.RpSeedRouteTimeFraction), 2);
testCase.verifyTrue(all(diff( ...
    spaceTimeSeed.RpSeedRouteTimeFraction) > 0));
testCase.verifyEqual(spaceTimeSeed.RpSeedRouteTimeFraction, ...
    expectedTimeFraction, "AbsTol", 1e-12);
testCase.verifyEqual(spaceTimeSeed.RpSeedRouteProgress, ...
    expectedProgress, "AbsTol", 1e-12);
end

function testSmallBudgetRetainsSpaceTimeDetour(testCase)
% PURPOSE
%   - Retain one timed moving-obstacle detour with a two-seed budget.
squareAzimuth_deg = [-1; 1; 1; -1];
obstacle = makeAzElObstacleData( ...
    "timed budget square", [0; 20], ...
    {squareAzimuth_deg; squareAzimuth_deg}, ...
    {[-1; -1; 1; 1]; [3; 3; 5; 5]}, 0);
[initialState, goalState, limits] = standardRequest([-6 0], [6 0], 20);
options = fastOptions(2);
options.MaximumPlanningTime_s = 5;
options.MaximumSippPlanningFraction = 1;
options.MaximumVisibilitySnapshotsPerObstacle = 2;
options.DetectSnapshotEvents = false;
options.SpaceTimeLayerCount = 17;
options.MaximumSpaceTimeCandidateCount = 16;

result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

seedSources = [result.SearchDiagnostics.CandidateSeeds.Source];
testCase.verifyEqual(numel(seedSources), 2);
testCase.verifyEqual(seedSources(1), "direct");
testCase.verifyEqual(seedSources(2), "spaceTimeVisibilityGraph");
testCase.verifyLessThan(min( ...
    result.SearchDiagnostics.CandidateSeeds(2).Route_deg(:, 2)), -1);
end

function testContinuousCollisionEarlyExitPreservesFirstCollision(testCase)
% PURPOSE
%   - Verify that early exit reports the same first collision as full scan.
squareAzimuth_deg = [-1; 1; 1; -1];
squareElevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData( ...
    "static square", [0; 10], ...
    {squareAzimuth_deg; squareAzimuth_deg}, ...
    {squareElevation_deg; squareElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
time_s = (0:6).';
position_deg = [-4 0; -2 0; 0 0; 2 0; 4 0; 5 0; 6 0];

[fullOccupied, fullDetails] = queryAzElTimedPathCollision( ...
    obstacleField, time_s, position_deg);
[earlyOccupied, earlyDetails] = queryAzElTimedPathCollision( ...
    obstacleField, time_s, position_deg, struct( ...
    "StopAtFirstCollision", true));

firstFullIndex = find(fullOccupied, 1, "first");
firstEarlyIndex = find(earlyOccupied, 1, "first");
testCase.verifyEqual(firstEarlyIndex, firstFullIndex);
testCase.verifyEqual( ...
    earlyDetails.BlockingObstacleIndex(firstEarlyIndex), ...
    fullDetails.BlockingObstacleIndex(firstFullIndex));
testCase.verifyFalse(earlyDetails.SegmentEvaluationComplete);
testCase.verifyTrue(earlyDetails.StoppedAtFirstCollision);
testCase.verifyLessThan(earlyDetails.EvaluatedSegmentCount, ...
    size(position_deg, 1) - 1);
testCase.verifyTrue(fullDetails.SegmentEvaluationComplete);
testCase.verifyFalse(fullDetails.StoppedAtFirstCollision);
end

function testCurveDeviationBufferRejectsThinGap(testCase)
% PURPOSE
%   - Reject a clear chord whose permitted curve tube reaches an obstacle.
obstacle = makeAzElObstacleData( ...
    "thin strip", [0; 1], [-0.1; 0.1; 0.1; -0.1], ...
    [0.04; 0.04; 0.06; 0.06], 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
time_s = [0; 1];
position_deg = [-1 0; 1 0];

unbufferedCollision = queryAzElTimedPathCollision( ...
    obstacleField, time_s, position_deg);
[clearanceProven, clearanceDiagnostics] = ...
    azElInternal.certifyAzElTimedPathClearance( ...
    obstacleField, time_s, position_deg, 0.05);

testCase.verifyFalse(any(unbufferedCollision));
testCase.verifyFalse(clearanceProven);
testCase.verifyEqual( ...
    clearanceDiagnostics.UnresolvedPathSegmentCount, 1);
end

function testMovingEdgeClearanceCertificate(testCase)
% PURPOSE
%   - Prove clearance from a translating and deforming polygon edge field.
firstAzimuth_deg = [-0.5; 0.5; 0.5; -0.5];
firstElevation_deg = [-0.5; -0.5; 0.5; 0.5];
lastAzimuth_deg = [-0.2; 0.9; 0.7; -0.4];
lastElevation_deg = [-0.6; -0.4; 0.7; 0.4];
obstacle = makeAzElObstacleData( ...
    "moving clearance", [0; 10], ...
    {firstAzimuth_deg; lastAzimuth_deg}, ...
    {firstElevation_deg; lastElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
time_s = [0; 10];
position_deg = [-2 2; 2 2];

collisionMask = queryAzElTimedPathCollision( ...
    obstacleField, time_s, position_deg);
[clearanceProven, diagnostics] = ...
    azElInternal.certifyAzElTimedPathClearance( ...
    obstacleField, time_s, position_deg, 0.05);

testCase.verifyFalse(any(collisionMask));
testCase.verifyTrue(clearanceProven);
testCase.verifyTrue(diagnostics.ProvenClear);
testCase.verifyEqual(diagnostics.UnresolvedPathSegmentCount, 0);
testCase.verifyGreaterThan( ...
    diagnostics.EvaluatedEdgeIntervalCount + ...
    diagnostics.BroadPhaseRejectedEdgeIntervalCount, 0);
testCase.verifyGreaterThan( ...
    diagnostics.BroadPhaseRejectedEdgeIntervalCount, 0);
end

function testSameTimePathBatchMatchesIndividualQueries(testCase)
% PURPOSE
%   - Verify same-time batched segments against individual segment queries.
squareAzimuth_deg = [-1; 1; 1; -1];
squareElevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData( ...
    "static square", [0; 10], ...
    {squareAzimuth_deg; squareAzimuth_deg}, ...
    {squareElevation_deg; squareElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
pathPosition_deg = [-3 2; -2 0; 0 0; 2 0; 3 2];

[~, batchedDetails] = queryAzElTimedPathCollision( ...
    obstacleField, 5, pathPosition_deg);
individualSegmentOccupied = false(size(pathPosition_deg, 1) - 1, 1);
for segmentIndex = 1:numel(individualSegmentOccupied)
    [~, individualDetails] = queryAzElTimedPathCollision( ...
        obstacleField, [5; 5], ...
        pathPosition_deg(segmentIndex:segmentIndex + 1, :));
    individualSegmentOccupied(segmentIndex) = ...
        individualDetails.SegmentOccupied;
end

testCase.verifyEqual( ...
    batchedDetails.SegmentOccupied, individualSegmentOccupied);
testCase.verifyEqual(batchedDetails.SegmentOccupied, ...
    [false; true; true; false]);

independentPairPosition_deg = [ ...
    -3 2; -2 0; ...
    0 0; 2 0; ...
    3 2; 4 2];
packedObstacle = obstacleField.Obstacles(1);
batchedIndependentOccupied = ...
    azElInternal.queryPackedMovingObstacle( ...
    packedObstacle, 5, independentPairPosition_deg, false, 0, true);
individualIndependentOccupied = false(3, 1);
for segmentIndex = 1:numel(individualIndependentOccupied)
    firstPositionIndex = 2 * segmentIndex - 1;
    individualIndependentOccupied(segmentIndex) = ...
        azElInternal.queryPackedMovingObstacle( ...
        packedObstacle, 5, independentPairPosition_deg( ...
        firstPositionIndex:firstPositionIndex + 1, :), false, 0);
end
testCase.verifyEqual( ...
    batchedIndependentOccupied, individualIndependentOccupied);
testCase.verifyEqual(batchedIndependentOccupied, [false; true; false]);
end

function testCachedTopologyMatchesCompleteTraversal(testCase)
% PURPOSE
%   - Verify cached polygon topology against uncached collision traversal.
outerAzimuth_deg = [-4; 4; 4; -4];
outerElevation_deg = [-3; -3; 3; 3];
innerAzimuth_deg = [-1; -1; 1; 1];
innerElevation_deg = [-1; 1; 1; -1];
firstAzimuth_deg = [outerAzimuth_deg; NaN; innerAzimuth_deg];
firstElevation_deg = [outerElevation_deg; NaN; innerElevation_deg];
lastAzimuth_deg = firstAzimuth_deg + 2;
lastElevation_deg = firstElevation_deg + 0.5;
obstacle = makeAzElObstacleData( ...
    "moving ring", [0; 10], ...
    {firstAzimuth_deg; lastAzimuth_deg}, ...
    {firstElevation_deg; lastElevation_deg}, 0);
cachedField = buildAzElTimeObstacleField(obstacle);

uncachedField = cachedField;
uncachedField.Obstacles = rmfield( ...
    uncachedField.Obstacles, "TopologyMatchesNext");
queryTime_s = linspace(0, 10, 121).';
queryAzimuth_deg = linspace(-6, 8, 121).';
queryElevation_deg = 2.5 * sin(queryTime_s);
cachedQuery = queryAzElTimeObstacle( ...
    cachedField, queryAzimuth_deg, queryElevation_deg, queryTime_s);
uncachedQuery = queryAzElTimeObstacle( ...
    uncachedField, queryAzimuth_deg, queryElevation_deg, queryTime_s);
testCase.verifyEqual(cachedQuery, uncachedQuery);

pathPosition_deg = [queryAzimuth_deg, queryElevation_deg];
cachedPath = queryAzElTimedPathCollision( ...
    cachedField, queryTime_s, pathPosition_deg);
uncachedPath = queryAzElTimedPathCollision( ...
    uncachedField, queryTime_s, pathPosition_deg);
testCase.verifyEqual(cachedPath, uncachedPath);
testCase.verifyTrue(cachedField.Obstacles.TopologyMatchesNext(1));

firstDuplicateAzimuth_deg = [0; 0; 2; 2];
firstDuplicateElevation_deg = [0; 0; 0; 2];
lastDuplicateAzimuth_deg = [0; 2; 2; 2];
lastDuplicateElevation_deg = [0; 0; 2; 2];
changedDuplicate = makeAzElObstacleData( ...
    "changed duplicate", [0; 10], ...
    {firstDuplicateAzimuth_deg; lastDuplicateAzimuth_deg}, ...
    {firstDuplicateElevation_deg; lastDuplicateElevation_deg}, 0);
changedDuplicateField = buildAzElTimeObstacleField(changedDuplicate);
testCase.verifyFalse( ...
    changedDuplicateField.Obstacles.TopologyMatchesNext(1));

firstShiftedAzimuth_deg = [0; 0; 2; 2; 0];
firstShiftedElevation_deg = [0; 0; 0; 2; 2];
lastShiftedAzimuth_deg = [10; 12; 12; 12; 10];
lastShiftedElevation_deg = [0; 0; 0; 2; 2];
shiftedDuplicate = makeAzElObstacleData( ...
    "shifted duplicate", [0; 10], ...
    {firstShiftedAzimuth_deg; lastShiftedAzimuth_deg}, ...
    {firstShiftedElevation_deg; lastShiftedElevation_deg}, 0);
shiftedDuplicateField = buildAzElTimeObstacleField(shiftedDuplicate);
testCase.verifyFalse( ...
    shiftedDuplicateField.Obstacles.TopologyMatchesNext(1));

% A midpoint topology change selects the later discrete source shape. It
% must not interpolate unrelated retained-edge rows.
midpointOccupied = queryAzElTimeObstacle( ...
    shiftedDuplicateField, [6; 11], [1; 1], [5; 5]);
testCase.verifyEqual(midpointOccupied, [false; true]);
end

function testAsynchronousObstacleTimesShareVisibilityGraph(testCase)
% PURPOSE
%   - Verify visibility graphs at the union of obstacle sample times.
firstObstacle = makeAzElObstacleData( ...
    "first", [0; 10], [-2; -1; -1; -2], ...
    [-1; -1; 1; 1], 0);
secondObstacle = makeAzElObstacleData( ...
    "second", [5; 15], [1; 2; 2; 1], ...
    [-1; -1; 1; 1], 0);
obstacleField = buildAzElTimeObstacleField( ...
    {firstObstacle, secondObstacle});
initialState = struct("time_s", 0, "position_deg", [-4 3]);
goalState = struct("time_s", 15, "position_deg", [4 3]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct("UseParallel", "off"));
testCase.verifyEqual([search.VisibilityGraphs.Time_s], [0 5 10 15]);
for graphIndex = [2 3]
    obstacleIndex = unique(search.VisibilityGraphs(graphIndex). ...
        NodeObstacleIndex(3:end));
    testCase.verifyEqual(obstacleIndex(:), [1; 2]);
end
end

function testVisibilitySnapshotsAreUncappedByDefault(testCase)
% PURPOSE
%   - Verify that default visibility search retains all source snapshots.
sampleTime_s = (0:20).';
squareAzimuth_deg = repmat( ...
    {[-1; 1; 1; -1]}, numel(sampleTime_s), 1);
squareElevation_deg = repmat( ...
    {[-1; -1; 1; 1]}, numel(sampleTime_s), 1);
obstacle = makeAzElObstacleData( ...
    "sampled square", sampleTime_s, ...
    squareAzimuth_deg, squareElevation_deg, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-3 2]);
goalState = struct("time_s", 20, "position_deg", [3 2]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct("UseParallel", "off"));
testCase.verifyEqual(numel(search.VisibilityGraphs), ...
    numel(sampleTime_s));
testCase.verifyEqual(search.Options.MaximumSnapshotsPerObstacle, Inf);
end

function testVisibilitySearchAddsOnlyRequestedSnapshot(testCase)
% PURPOSE
%   - Verify that one requested time adds only its nearest source snapshot.
sampleTime_s = (0:20).';
squareAzimuth_deg = repmat( ...
    {[-1; 1; 1; -1]}, numel(sampleTime_s), 1);
squareElevation_deg = repmat( ...
    {[-1; -1; 1; 1]}, numel(sampleTime_s), 1);
obstacle = makeAzElObstacleData( ...
    "sampled square", sampleTime_s, ...
    squareAzimuth_deg, squareElevation_deg, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-3 2]);
goalState = struct("time_s", 20, "position_deg", [3 2]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct( ...
    "MaximumSnapshotsPerObstacle", 2, ...
    "RequiredSnapshotTimes_s", 9, ...
    "UseParallel", "off"));

testCase.verifyEqual([search.VisibilityGraphs.Time_s], [0 9 20]);
testCase.verifyEqual(search.SnapshotDiagnostics.RetainedSampleIndex, ...
    [1; 10; 21]);
testCase.verifyEqual(search.SnapshotDiagnostics.RequiredSampleIndex, 10);
testCase.verifyEqual(search.SnapshotDiagnostics.RetainedSnapshotCount, 3);
end

function testSnapshotEventsPromoteRotatingBoundary(testCase)
% PURPOSE
%   - Verify event promotion when a polygon boundary rotates.
sampleTime_s = (0:5).';
basePosition_deg = [-1 -1; 1 -1; 1 1; -1 1];
rotation_deg = [0; 0; 20; 20; 20; 20];
azimuth_deg = cell(numel(sampleTime_s), 1);
elevation_deg = cell(numel(sampleTime_s), 1);
for sampleIndex = 1:numel(sampleTime_s)
    rotationMatrix = [ ...
        cosd(rotation_deg(sampleIndex)), ...
        -sind(rotation_deg(sampleIndex)); ...
        sind(rotation_deg(sampleIndex)), ...
        cosd(rotation_deg(sampleIndex))];
    rotatedPosition_deg = basePosition_deg * rotationMatrix.';
    azimuth_deg{sampleIndex} = rotatedPosition_deg(:, 1);
    elevation_deg{sampleIndex} = rotatedPosition_deg(:, 2);
end
obstacle = makeAzElObstacleData( ...
    "rotating square", sampleTime_s, azimuth_deg, elevation_deg, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-3 2]);
goalState = struct("time_s", 5, "position_deg", [3 2]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct( ...
    "MaximumSnapshotsPerObstacle", 2, ...
    "DetectSnapshotEvents", true, ...
    "SnapshotProbeEdgeCount", 4, ...
    "SnapshotEdgeRotationThreshold_deg", 5, ...
    "SnapshotBoundaryMotionThreshold_deg", Inf, ...
    "UseParallel", "off"));

testCase.verifyEqual([search.VisibilityGraphs.Time_s], [0 1 2 5]);
testCase.verifyEqual(search.SnapshotDiagnostics.EventSampleIndex, [2; 3]);
eventDiagnostics = search.SnapshotDiagnostics.EventDiagnostics;
testCase.verifyGreaterThan( ...
    eventDiagnostics.MaximumEdgeRotation_deg(3), 5);
testCase.verifyTrue(eventDiagnostics.RotationThresholdCrossed(3));
testCase.verifyFalse(any(eventDiagnostics.TopologyChanged));
end

function testPairwiseSnapshotEventsPromoteMergeAndSplit(testCase)
% PURPOSE
%   - Retain times around two protected-obstacle overlap transitions.
sampleTime_s = [0; 4; 5; 6; 10];
firstCenter_deg = [-3; -0.6; -0.3; -0.6; -3];
secondCenter_deg = -firstCenter_deg;
azimuthHalfWidth_deg = 0.4;
elevation_deg = [-0.4; -0.4; 0.4; 0.4];
firstAzimuth_deg = cell(numel(sampleTime_s), 1);
secondAzimuth_deg = cell(numel(sampleTime_s), 1);
elevationHistory_deg = cell(numel(sampleTime_s), 1);
for sampleIndex = 1:numel(sampleTime_s)
    firstAzimuth_deg{sampleIndex} = firstCenter_deg(sampleIndex) + ...
        azimuthHalfWidth_deg * [-1; 1; 1; -1];
    secondAzimuth_deg{sampleIndex} = secondCenter_deg(sampleIndex) + ...
        azimuthHalfWidth_deg * [-1; 1; 1; -1];
    elevationHistory_deg{sampleIndex} = elevation_deg;
end
firstObstacle = makeAzElObstacleData( ...
    "first merging obstacle", sampleTime_s, firstAzimuth_deg, ...
    elevationHistory_deg, 0);
secondObstacle = makeAzElObstacleData( ...
    "second merging obstacle", sampleTime_s, secondAzimuth_deg, ...
    elevationHistory_deg, 0);
obstacleField = buildAzElTimeObstacleField( ...
    [firstObstacle secondObstacle]);
[initialState, goalState] = standardRequest([-4 2], [4 2], 10);
options = struct( ...
    "MaximumSnapshotsPerObstacle", 2, ...
    "DetectSnapshotEvents", true, ...
    "SnapshotEdgeRotationThreshold_deg", Inf, ...
    "SnapshotBoundaryMotionThreshold_deg", Inf, ...
    "BuildFullVisibilityGraphs", false, ...
    "BuildMergedVisibilityGraph", false, ...
    "BuildSpaceTimeVisibilityGraph", false);
search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, options);

testCase.verifyEqual(search.PairwiseEventTimes_s, [4; 5; 6], ...
    "AbsTol", 1e-12);
testCase.verifyEqual(numel(search.PairwiseEventDiagnostics), 1);
diagnostic = search.PairwiseEventDiagnostics(1);
testCase.verifyEqual(diagnostic.TransitionCount, 2);
testCase.verifyEqual(diagnostic.MinimumBoundsGap_deg, 0, ...
    "AbsTol", 1e-12);
end

function testSnapshotEventsPromoteIslandSplit(testCase)
% PURPOSE
%   - Verify event promotion when one polygon becomes two polygon islands.
sampleTime_s = (0:3).';
singleAzimuth_deg = [-2; 2; 2; -2];
singleElevation_deg = [-1; -1; 1; 1];
splitAzimuth_deg = [-2; -0.5; -0.5; -2; NaN; 0.5; 2; 2; 0.5];
splitElevation_deg = [-1; -1; 1; 1; NaN; -1; -1; 1; 1];
obstacle = makeAzElObstacleData( ...
    "splitting obstacle", sampleTime_s, ...
    {singleAzimuth_deg; singleAzimuth_deg; ...
    splitAzimuth_deg; splitAzimuth_deg}, ...
    {singleElevation_deg; singleElevation_deg; ...
    splitElevation_deg; splitElevation_deg}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-3 2]);
goalState = struct("time_s", 3, "position_deg", [3 2]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct( ...
    "MaximumSnapshotsPerObstacle", 2, ...
    "SnapshotEdgeRotationThreshold_deg", Inf, ...
    "SnapshotBoundaryMotionThreshold_deg", Inf, ...
    "UseParallel", "off"));

eventDiagnostics = search.SnapshotDiagnostics.EventDiagnostics;
testCase.verifyEqual(eventDiagnostics.IslandCount, [1; 1; 2; 2]);
testCase.verifyTrue(eventDiagnostics.TopologyChanged(3));
testCase.verifyEqual(search.SnapshotDiagnostics.EventSampleIndex, [2; 3]);
testCase.verifyEqual([search.VisibilityGraphs.Time_s], [0 1 2 3]);
end

function testDenseSnapshotBuildsEndpointSafeMergedGraph(testCase)
% PURPOSE
%   - Verify merged visibility geometry for a dense obstacle snapshot.
centerAzimuth_deg = [-6 -3 0 3 6];
obstacles = cell(numel(centerAzimuth_deg), 1);
for obstacleIndex = 1:numel(centerAzimuth_deg)
    azimuth_deg = centerAzimuth_deg(obstacleIndex) + ...
        [-0.8; 0.8; 0.8; -0.8];
    elevation_deg = [-1.5; -1.5; 1.5; 1.5];
    obstacles{obstacleIndex} = makeAzElObstacleData( ...
        "dense square " + obstacleIndex, [0; 30], ...
        {azimuth_deg; azimuth_deg}, ...
        {elevation_deg; elevation_deg}, 0.1);
end
obstacleField = buildAzElTimeObstacleField( ...
    combineAzElObstacles(obstacles));
initialState = struct("time_s", 0, "position_deg", [-10 0]);
goalState = struct("time_s", 30, "position_deg", [10 0]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct("UseParallel", "off"));
testCase.verifyEqual(numel(search.MergedVisibilityGraphs), 1);
mergedGraph = search.MergedVisibilityGraphs;
testCase.verifyTrue(mergedGraph.Success, mergedGraph.Message);
testCase.verifyEqual(mergedGraph.Representation, ...
    "mergedObstacleGraph");
testCase.verifyTrue(mergedGraph.ObstacleMergeComplete);
testCase.verifyEqual(mergedGraph.SourceObstacleCount, 5);
testCase.verifyEqual(mergedGraph.MaximumGraphObstacleCount, 1);
testCase.verifyEqual(mergedGraph.MergedGroupCount, 1);
testCase.verifyEqual(mergedGraph.GraphObstacleCount, 1);
testCase.verifyEqual(sort([mergedGraph.MergedObstacleMembership{:}]), ...
    1:5);
testCase.verifyEmpty(mergedGraph.OmittedObstacleMembership);
testCase.verifyEqual( ...
    search.ObstacleMergeDiagnostics.SuccessfulGraphCount, 1);
testCase.verifyEqual( ...
    search.ObstacleMergeDiagnostics.AttemptedGraphCount, 1);

region_deg = mergedGraph.MergedObstacleGeometry_deg{1};
[startInside, startOnBoundary] = inpolygon( ...
    initialState.position_deg(1), initialState.position_deg(2), ...
    region_deg(:, 1), region_deg(:, 2));
[goalInside, goalOnBoundary] = inpolygon( ...
    goalState.position_deg(1), goalState.position_deg(2), ...
    region_deg(:, 1), region_deg(:, 2));
testCase.verifyFalse(startInside || startOnBoundary);
testCase.verifyFalse(goalInside || goalOnBoundary);

fourObstacleField = buildAzElTimeObstacleField( ...
    combineAzElObstacles(obstacles(1:4)));
fourObstacleSearch = buildAzElVisibilityRoutes( ...
    fourObstacleField, initialState, goalState, ...
    struct("UseParallel", "off"));
testCase.verifyEmpty(fourObstacleSearch.MergedVisibilityGraphs);
testCase.verifyEqual( ...
    fourObstacleSearch.ObstacleMergeDiagnostics.AttemptedGraphCount, 0);
end

function testSparseMergedGraphOmitsUnrelatedGroups(testCase)
% PURPOSE
%   - Verify bounded merged graphs and explicit omitted obstacle groups.
clusterCenter_deg = [0 0; 0 6; 0 -6; 8 6];
localOffset_deg = [-0.6 0; 0.6 0; 0 0.6; 0 -0.6; 0 0];
obstacles = cell(20, 1);
obstacleIndex = 0;
for clusterIndex = 1:size(clusterCenter_deg, 1)
    for localIndex = 1:size(localOffset_deg, 1)
        obstacleIndex = obstacleIndex + 1;
        center_deg = clusterCenter_deg(clusterIndex, :) + ...
            localOffset_deg(localIndex, :);
        azimuth_deg = center_deg(1) + ...
            [-0.15; 0.15; 0.15; -0.15];
        elevation_deg = center_deg(2) + ...
            [-0.15; -0.15; 0.15; 0.15];
        obstacles{obstacleIndex} = makeAzElObstacleData( ...
            "cluster square " + obstacleIndex, [0; 20], ...
            {azimuth_deg; azimuth_deg}, ...
            {elevation_deg; elevation_deg}, 0.05);
    end
end
obstacleField = buildAzElTimeObstacleField( ...
    combineAzElObstacles(obstacles));
initialState = struct("time_s", 0, "position_deg", [-15 0]);
goalState = struct("time_s", 20, "position_deg", [15 0]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct("UseParallel", "off"));
testCase.verifyEqual(numel(search.MergedVisibilityGraphs), 1);
mergedGraph = search.MergedVisibilityGraphs;
testCase.verifyTrue(mergedGraph.Success, mergedGraph.Message);
testCase.verifyEqual(mergedGraph.SourceObstacleCount, 20);
testCase.verifyEqual(mergedGraph.MaximumGraphObstacleCount, 4);
testCase.verifyEqual(mergedGraph.MergedGroupCount, 4);
testCase.verifyLessThan( ...
    mergedGraph.GraphObstacleCount, mergedGraph.MergedGroupCount);
testCase.verifyNotEmpty(mergedGraph.OmittedObstacleMembership);
representedObstacleIndex = sort([ ...
    mergedGraph.MergedObstacleMembership{:}, ...
    mergedGraph.OmittedObstacleMembership{:}]);
testCase.verifyEqual(representedObstacleIndex, 1:20);
testCase.verifyEqual( ...
    numel(mergedGraph.OmittedObstacleGeometry_deg), ...
    numel(mergedGraph.OmittedObstacleMembership));
end

function testMergedBoundaryContainsEverySourceVertex(testCase)
% PURPOSE
%   - Verify conservative reduction of a merged dense polygon boundary.
angle_rad = (0:63).' * (2 * pi / 64);
centerAzimuth_deg = linspace(-1.2, 1.2, 5);
obstacles = cell(5, 1);
sourceBoundary_deg = cell(5, 1);
for obstacleIndex = 1:numel(obstacles)
    boundary_deg = [ ...
        centerAzimuth_deg(obstacleIndex) + 0.45 * cos(angle_rad), ...
        0.45 * sin(angle_rad)];
    sourceBoundary_deg{obstacleIndex} = boundary_deg;
    obstacles{obstacleIndex} = makeAzElObstacleData( ...
        "dense circle " + obstacleIndex, [0; 10], ...
        {boundary_deg(:, 1); boundary_deg(:, 1)}, ...
        {boundary_deg(:, 2); boundary_deg(:, 2)}, 0);
end
obstacleField = buildAzElTimeObstacleField( ...
    combineAzElObstacles(obstacles));
initialState = struct("time_s", 0, "position_deg", [-5 0]);
goalState = struct("time_s", 10, "position_deg", [5 0]);

search = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, struct( ...
    "BuildFullVisibilityGraphs", false, ...
    "BuildMergedVisibilityGraph", true, ...
    "UseParallel", "off"));

testCase.verifyEqual(numel(search.MergedVisibilityGraphs), 1);
mergedGraph = search.MergedVisibilityGraphs;
testCase.verifyTrue(mergedGraph.Success, mergedGraph.Message);
testCase.verifyEqual(mergedGraph.MergedGroupCount, 1);
reducedBoundary_deg = mergedGraph.MergedObstacleGeometry_deg{1};
testCase.verifyLessThanOrEqual(size(reducedBoundary_deg, 1), 24);
for obstacleIndex = 1:numel(sourceBoundary_deg)
    boundary_deg = sourceBoundary_deg{obstacleIndex};
    [inside, onBoundary] = inpolygon( ...
        boundary_deg(:, 1), boundary_deg(:, 2), ...
        reducedBoundary_deg(:, 1), reducedBoundary_deg(:, 2));
    testCase.verifyTrue(all(inside | onBoundary));
end
end

function testVerboseMergedOnlySearchDoesNotIndexEmptyGraphs(testCase)
% PURPOSE
%   - Verify verbose merged-only search with no full snapshot graph array.
boundary_deg = [-1 -1; 1 -1; 1 1; -1 1];
obstacle = makeAzElObstacleData( ...
    "moving square", [0; 5; 10], ...
    {boundary_deg(:, 1); boundary_deg(:, 1); boundary_deg(:, 1)}, ...
    {boundary_deg(:, 2); boundary_deg(:, 2); boundary_deg(:, 2)}, 0);
obstacleField = buildAzElTimeObstacleField(obstacle); %#ok<NASGU>
initialState = struct( ...
    "time_s", 0, "position_deg", [-3 0]); %#ok<NASGU>
goalState = struct( ...
    "time_s", 10, "position_deg", [3 0]); %#ok<NASGU>

printedText = evalc("search = buildAzElVisibilityRoutes(" + ...
    "obstacleField, initialState, goalState, struct(" + ...
    "'BuildFullVisibilityGraphs', false, " + ...
    "'BuildMergedVisibilityGraph', true, " + ...
    "'UseParallel', 'off', 'Verbose', true));");

testCase.verifyEmpty(search.VisibilityGraphs);
testCase.verifyTrue(contains(printedText, ...
    "Full snapshot graph construction is disabled"));
end

function testParallelPolygonReductionMatchesSerial(testCase)
% PURPOSE
%   - Verify deterministic visibility results for serial and parallel modes.
squareAzimuth_deg = { ...
    [-2; 0; 0; -2], [-1; 1; 1; -1], [1; 3; 3; 1]};
squareElevation_deg = { ...
    [-1; -1; 1; 1], [-1; -1; 1; 1], [-1; -1; 1; 1]};
obstacle = makeAzElObstacleData( ...
    "moving obstacle", [0; 10; 20], ...
    squareAzimuth_deg, squareElevation_deg, 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
initialState = struct("time_s", 0, "position_deg", [-4 3]);
goalState = struct("time_s", 20, "position_deg", [4 3]);

serialSearch = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, ...
    struct("UseParallel", "off"));
parallelSearch = buildAzElVisibilityRoutes( ...
    obstacleField, initialState, goalState, ...
    struct("UseParallel", "on"));

testCase.verifyEqual( ...
    serialSearch.ParallelExecution.RequestedMode, "off");
testCase.verifyEqual( ...
    parallelSearch.ParallelExecution.RequestedMode, "on");
testCase.verifyGreaterThan( ...
    parallelSearch.ParallelExecution.TaskCount, 1);
testCase.verifyEqual(numel(parallelSearch.VisibilityGraphs), ...
    numel(serialSearch.VisibilityGraphs));
testCase.verifyEqual(parallelSearch.CandidatePointsAzElTime, ...
    serialSearch.CandidatePointsAzElTime, "AbsTol", 1e-12);

for snapshotIndex = 1:numel(serialSearch.VisibilityGraphs)
    serialGraph = serialSearch.VisibilityGraphs(snapshotIndex);
    parallelGraph = parallelSearch.VisibilityGraphs(snapshotIndex);
    testCase.verifyEqual(parallelGraph.Success, serialGraph.Success);
    testCase.verifyEqual(parallelGraph.PathPosition_deg, ...
        serialGraph.PathPosition_deg, "AbsTol", 1e-12);
    testCase.verifyEqual(parallelGraph.PathCost_deg, ...
        serialGraph.PathCost_deg, "AbsTol", 1e-12);
    testCase.verifyEqual(parallelGraph.CandidateActiveMask, ...
        serialGraph.CandidateActiveMask);
end
end

function testTwoVertexRegionsWarnAndAreRemoved(testCase)
% PURPOSE
%   - Verify explicit removal of invalid two-vertex obstacle regions.
validAzimuth_deg = [-2; 0; 0; -2];
validElevation_deg = [-1; -1; 1; 1];
twoVertexAzimuth_deg = [5; 6];
twoVertexElevation_deg = [0; 0];
azimuth_deg = [validAzimuth_deg; NaN; twoVertexAzimuth_deg];
elevation_deg = [validElevation_deg; NaN; twoVertexElevation_deg];

lastwarn("");
obstacle = makeAzElObstacleData( ...
    "mixed regions", [0; 10], azimuth_deg, elevation_deg, 0);
[warningMessage, warningIdentifier] = lastwarn;
testCase.verifyEqual(string(warningIdentifier), ...
    "normalizeAzElTimeObstacleData:RemovedTwoVertexRegions");
testCase.verifyTrue(contains(warningMessage, "two-vertex regions"));
testCase.verifyEqual(nnz(isfinite(obstacle.az_deg{1})), 4);
testCase.verifyEqual(nnz(isfinite(obstacle.originalAz_deg{1})), 4);

obstacleField = buildAzElTimeObstacleField(obstacle);
testCase.verifyTrue(queryAzElTimeObstacle( ...
    obstacleField, -1, 0, 5));
testCase.verifyFalse(queryAzElTimeObstacle( ...
    obstacleField, 5.5, 0, 5));

lastwarn("");
emptyObstacle = makeAzElObstacleData( ...
    "only two vertices", [0; 10], ...
    twoVertexAzimuth_deg, twoVertexElevation_deg, 0);
[~, warningIdentifier] = lastwarn;
testCase.verifyEqual(string(warningIdentifier), ...
    "normalizeAzElTimeObstacleData:RemovedTwoVertexRegions");
testCase.verifyEmpty(emptyObstacle.az_deg{1});
testCase.verifyEmpty(emptyObstacle.el_deg{1});
end

function testSpecifiedMovingTargetInterceptUsesMaintainedPlanner(testCase)
% PURPOSE
%   - Verify a specified-time intercept through the maintained planner.
targetMotion = struct( ...
    "time_s", [0; 8], ...
    "position_deg", [3 0; 3 0], ...
    "InterpolationMethod", "pchip");
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2 2]);
options = struct( ...
    "InterceptMode", "specifiedTime", ...
    "SpecifiedInterceptTime_s", 8, ...
    "MatchTargetVelocity", false, ...
    "PlannerOptions", fastOptions(1));

result = planAzElMovingTargetIntercept( ...
    [], initialState, targetMotion, limits, options);

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.InterceptValidation.Passed, ...
    result.InterceptValidation.Message);
testCase.verifyEqual(result.InterceptTime_s, 8, "AbsTol", 1e-10);
testCase.verifyEqual(result.position_deg(end, :), ...
    [3 0], "AbsTol", 1e-7);
testCase.verifyEqual(result.SearchDiagnostics.SearchMethod, ...
    "specifiedTime");
testCase.verifyEqual(result.SearchDiagnostics.TerminationReason, ...
    "goalReached");
testCase.verifyEqual(result.InterceptSearchDiagnostics.TerminationReason, ...
    "notRun");
testCase.verifyTrue(result.Validation.Passed);
testCase.verifyTrue(result.PlannerValidation.Passed);
testCase.verifyNotEmpty( ...
    result.SearchDiagnostics.CandidatePolicyMotions);
testCase.verifyEqual(result.PlannerSearchDiagnostics.MotionType, ...
    "piecewiseQuintic");
testCase.verifyGreaterThanOrEqual(result.ElapsedPlanningTime_s, ...
    result.FinalPlannerElapsedPlanningTime_s);
testCase.verifyGreaterThanOrEqual(result.ElapsedPlanningTime_s, ...
    result.InterceptSearchDiagnostics.ElapsedPlanningTime_s);
testCase.verifyTrue(isfinite( ...
    result.InterceptSearchDiagnostics.ElapsedPlanningTime_s));
testCase.verifyEqual(result.SearchDiagnostics.ElapsedPlanningTime_s, ...
    result.ElapsedPlanningTime_s);
testCase.verifyFalse(any(queryAzElTimedPathCollision( ...
    result.obstacleField, result.time_s, result.position_deg)));
end

function testEarliestInterceptTreatsInitialTimeAsLowerBound(testCase)
% PURPOSE
%   - Verify that the earliest search does not request a zero-duration plan.
targetMotion = struct( ...
    "time_s", [0; 5], ...
    "position_deg", [50 0; 50 0], ...
    "InterpolationMethod", "linear");
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2 2]);
plannerOptions = fastOptions(1);
plannerOptions.MaximumPlanningTime_s = 1;
options = struct( ...
    "InterceptMode", "earliestArrival", ...
    "MaximumSearchDuration_s", 5, ...
    "InitialSearchStep_s", 1, ...
    "SearchTimeTolerance_s", 0.25, ...
    "MatchTargetVelocity", false, ...
    "PlannerOptions", plannerOptions);

result = planAzElMovingTargetIntercept( ...
    [], initialState, targetMotion, limits, options);

testCase.verifyFalse(result.Success);
testCase.verifyEqual(result.TerminationReason, "noInterceptInHorizon");
testCase.verifyGreaterThan( ...
    result.SearchDiagnostics.BracketEvaluationCount, 0);
testCase.verifyEqual( ...
    result.SearchDiagnostics.FullPlannerEvaluationCount, 0);
testCase.verifyEqual(result.SearchDiagnostics. ...
    NumericallyUnknownEvaluationCount, 0);
testCase.verifyEqual(result.SearchDiagnostics. ...
    CandidatePlannerGoalTimeMode, "analyticresttorest");
end

function testReachableRestToRestInterceptUsesLinearJerkBoundary(testCase)
% PURPOSE
%   - Verify the analytic lower bound and continuous linear-jerk feasibility boundary.
targetMotion = struct( ...
    "time_s", [0; 5], ...
    "position_deg", [1 0; 1 0], ...
    "InterpolationMethod", "linear");
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [4 4], ...
    "maxAcceleration_deg_s2", [4 4], ...
    "maxJerk_deg_s3", [8 8]);
plannerOptions = fastOptions(1);
plannerOptions.MaximumPlanningTime_s = 20;
options = struct( ...
    "InterceptMode", "earliestArrival", ...
    "MaximumSearchDuration_s", 5, ...
    "InitialSearchStep_s", 1, ...
    "SearchTimeTolerance_s", 0.1, ...
    "MatchTargetVelocity", false, ...
    "PlannerOptions", plannerOptions);

result = planAzElMovingTargetIntercept( ...
    [], initialState, targetMotion, limits, options);

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyTrue(result.InterceptValidation.Passed, ...
    result.InterceptValidation.Message);
testCase.verifyTrue(result.SearchDiagnostics.EarliestNumericallyResolved);
testCase.verifyEqual(result.SearchDiagnostics. ...
    NumericallyUnknownEvaluationCount, 0);
testCase.verifyGreaterThan( ...
    result.SearchDiagnostics.FullPlannerEvaluationCount, 0);
testCase.verifyEqual(result.SearchDiagnostics. ...
    CandidatePlannerGoalTimeMode, ...
    "analyticresttorestthenfixedarrival");
end

function testMovingInterceptPrefilterReportsPrunedFailure(testCase)
% PURPOSE
%   - Verify prefilter counts when no intercept fits the search horizon.
obstacle = makeAzElObstacleData( ...
    "distant obstacle", [0; 5], ...
    [-1; 1; 1; -1], [8; 8; 10; 10], 0);
targetMotion = struct( ...
    "time_s", [0; 5], ...
    "position_deg", [50 0; 50 0], ...
    "InterpolationMethod", "linear");
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2 2]);
plannerOptions = fastOptions(1);
plannerOptions.MaximumPlanningTime_s = 1;
options = struct( ...
    "InterceptMode", "earliestArrival", ...
    "MaximumSearchDuration_s", 5, ...
    "InitialSearchStep_s", 1, ...
    "SearchTimeTolerance_s", 0.1, ...
    "MatchTargetVelocity", false, ...
    "PlannerOptions", plannerOptions);

result = planAzElMovingTargetIntercept( ...
    obstacle, initialState, targetMotion, limits, options);

testCase.verifyFalse(result.Success);
testCase.verifyEqual(result.TerminationReason, ...
    "noInterceptInHorizon");
testCase.verifyTrue(result.SearchDiagnostics.KinematicPrefilterApplied);
testCase.verifyGreaterThan( ...
    result.SearchDiagnostics.KinematicPrunedCandidateCount, 0);
testCase.verifyLessThanOrEqual( ...
    result.SearchDiagnostics.FullValidationCandidateCount, ...
    result.SearchDiagnostics.TargetCandidateCount);
testCase.verifyEqual(result.SearchDiagnostics.SearchMethod, ...
    "interpolatedKinematicPrefilterAndValidatedScan");
testCase.verifyEqual(result.SearchDiagnostics. ...
    CandidatePlannerGoalTimeMode, "fixedarrival");
testCase.verifyEqual(result.SearchDiagnostics. ...
    NumericallyUnknownEvaluationCount, 0);
testCase.verifyGreaterThanOrEqual(result.ElapsedPlanningTime_s, ...
    result.InterceptSearchDiagnostics.ElapsedPlanningTime_s);
testCase.verifyGreaterThanOrEqual(result.ElapsedPlanningTime_s, ...
    result.FinalPlannerElapsedPlanningTime_s);
testCase.verifyEqual(result.SearchDiagnostics.ElapsedPlanningTime_s, ...
    result.ElapsedPlanningTime_s);
end

function testPlotConsumesVisibilityDiagnosticsWithoutReplanning(testCase)
% PURPOSE
%   - Verify snapshot and space-time plots from a retained search trace.
squareAzimuth_deg = [-1; 1; 1; -1];
squareElevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData( ...
    "moving square", [0; 10], ...
    {squareAzimuth_deg; squareAzimuth_deg}, ...
    {squareElevation_deg; squareElevation_deg + 0.5}, 0);
initialState = struct( ...
    "time_s", 0, "position_deg", [-3 2], ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 10, "position_deg", [3 2], ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2 2]);
options = fastOptions(1);
options.MaximumPlanningTime_s = 5;
result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

graphs = result.SearchDiagnostics.VisibilityGraphs;
testCase.verifyGreaterThan(numel(graphs), 1);
testCase.verifyFalse(isempty(result.SearchDiagnostics. ...
    SpaceTimeVisibilityGraph.NodeAzElTime));
handles = plotAzElMotion(result, struct( ...
    "FigureVisible", "on", ...
    "ShowAnimation", false, ...
    "ShowKinematics", false, ...
    "ShowVisibilityGraphs", true));
cleanup = onCleanup(@() closeMotionFigures(handles));
drawnow;
testCase.verifyTrue(isgraphics(handles.WorkspaceFigure));
testCase.verifyTrue(isgraphics(handles.VisibilityGraphs.Figure));
testCase.verifyTrue(isgraphics( ...
    handles.VisibilityGraphs.OverviewAxes));
testCase.verifyTrue(isgraphics( ...
    handles.VisibilityGraphs.SnapshotAxes));

blockedTestWasRetained = false;
for graphIndex = 1:numel(graphs)
    graph = graphs(graphIndex);
    blockedTestWasRetained = blockedTestWasRetained || ...
        any(graph.VisibilityBlockedMask, "all");
    testCase.verifyEqual(graph.VisibilityTestedMask, ...
        graph.VisibilityTestedMask.');
    testCase.verifyEqual(graph.VisibilityBlockedMask, ...
        graph.VisibilityBlockedMask.');
    testCase.verifyFalse(any(graph.VisibilityBlockedMask & ...
        ~graph.VisibilityTestedMask, "all"));
end
testCase.verifyTrue(blockedTestWasRetained);

requestedTime_s = mean([graphs.Time_s]);
set(handles.VisibilityGraphs.TimeEdit, ...
    "String", sprintf("%.12g", requestedTime_s));
goCallback = get(handles.VisibilityGraphs.GoButton, "Callback");
goCallback(handles.VisibilityGraphs.GoButton, []);
[~, expectedSnapshotIndex] = min( ...
    abs([graphs.Time_s] - requestedTime_s));
testCase.verifyEqual(getappdata( ...
    handles.VisibilityGraphs.Figure, "SelectedSnapshotIndex"), ...
    expectedSnapshotIndex);

set(handles.VisibilityGraphs.TimeEdit, ...
    "String", sprintf("%.12g", graphs(1).Time_s));
goCallback(handles.VisibilityGraphs.GoButton, []);
firstSnapshotChildCount = numel(allchild( ...
    handles.VisibilityGraphs.SnapshotAxes));
nextCallback = get(handles.VisibilityGraphs.NextButton, "Callback");
previousCallback = get( ...
    handles.VisibilityGraphs.PreviousButton, "Callback");
nextCallback(handles.VisibilityGraphs.NextButton, []);
previousCallback(handles.VisibilityGraphs.PreviousButton, []);
testCase.verifyEqual(getappdata( ...
    handles.VisibilityGraphs.Figure, "SelectedSnapshotIndex"), 1);
testCase.verifyEqual(numel(allchild( ...
    handles.VisibilityGraphs.SnapshotAxes)), firstSnapshotChildCount);
end

function testBlockedEndpointReturnsStableFailureAndPlot(testCase)
% PURPOSE
%   - Verify blocked-endpoint schema and visible failure diagnostics.
azimuth_deg = [-1; 1; 1; -1];
elevation_deg = [-1; -1; 1; 1];
obstacle = makeAzElObstacleData( ...
    "obstacle", [0; 20], azimuth_deg, elevation_deg, 0);
initialState = struct("time_s", 0, "position_deg", [0 0]);
goalState = struct("time_s", 20, "position_deg", [4 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2 2]);

result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, fastOptions(1));
testCase.verifyFalse(result.Success);
testCase.verifyEqual(result.TerminationReason, "endpointBlocked");
testCase.verifyEmpty(result.time_s);
testCase.verifyEmpty(result.position_deg);
testCase.verifyFalse(result.Validation.Passed);
testCase.verifyEqual(result.SearchDiagnostics.TerminationReason, ...
    "endpointBlocked");

handles = plotAzElMotion(result, struct( ...
    "FigureVisible", "on", ...
    "ShowAnimation", false, ...
    "ShowKinematics", true, ...
    "ShowVisibilityGraphs", true));
cleanup = onCleanup(@() closeMotionFigures(handles));
drawnow;
testCase.verifyTrue(isgraphics(handles.WorkspaceFigure));
testCase.verifyTrue(isgraphics(handles.VisibilityGraphs.Figure));
testCase.verifyTrue(isgraphics(handles.KinematicsFigure));
testCase.verifyEqual(numel(handles.KinematicsAxes), 4);
end

function testFailureOutcomesShareCanonicalSchemas(testCase)
% PURPOSE
%   - Verify stable fields across success and normal planning failures.
[successInitial, successGoal, successLimits] = standardRequest( ...
    [0 0], [1 0], 8);
successOptions = fastOptions(1);
successOptions.GoalTimeMode = "fixedArrival";
successResult = planAzElMotion( ...
    [], successInitial, successGoal, successLimits, successOptions);
[initialState, goalState, limits] = standardRequest([0 0], [1 0], 10);
initialState.velocity_deg_s = [3 0];
dynamicFailure = planAzElMotion( ...
    [], initialState, goalState, limits, fastOptions(1));

obstacle = makeAzElObstacleData( ...
    "goal blocker", [0; 10], ...
    [0.5; 1.5; 1.5; 0.5], [-1; -1; 1; 1], 0);
[initialState, goalState, limits] = standardRequest([0 0], [1 0], 10);
blockedFailure = planAzElMotion( ...
    obstacle, initialState, goalState, limits, fastOptions(1));
[candidateFailureInitial, candidateFailureGoal, ...
    candidateFailureLimits] = standardRequest([0 0], [10 0], 1);
candidateFailure = planAzElMotion([], candidateFailureInitial, ...
    candidateFailureGoal, candidateFailureLimits, fastOptions(1));

testCase.verifyTrue(successResult.Success, successResult.Message);
testCase.verifyFalse(dynamicFailure.Success);
testCase.verifyFalse(blockedFailure.Success);
testCase.verifyEqual(fieldnames(successResult), ...
    fieldnames(dynamicFailure));
testCase.verifyEqual(fieldnames(dynamicFailure), ...
    fieldnames(blockedFailure));
testCase.verifyEqual(fieldnames(successResult.timedSlopePath), ...
    fieldnames(dynamicFailure.timedSlopePath));
testCase.verifyEqual(fieldnames(dynamicFailure.timedSlopePath), ...
    fieldnames(blockedFailure.timedSlopePath));
testCase.verifyEqual( ...
    fieldnames(successResult.timedSlopePath.ConstraintDiagnostics), ...
    fieldnames(dynamicFailure.timedSlopePath.ConstraintDiagnostics));
testCase.verifyEqual( ...
    fieldnames(dynamicFailure.timedSlopePath.ConstraintDiagnostics), ...
    fieldnames(blockedFailure.timedSlopePath.ConstraintDiagnostics));
testCase.verifyEqual(fieldnames(dynamicFailure.Validation), ...
    fieldnames(blockedFailure.Validation));
testCase.verifyEqual(fieldnames(successResult.Validation), ...
    fieldnames(dynamicFailure.Validation));
testCase.verifyEqual(fieldnames(successResult.SearchDiagnostics), ...
    fieldnames(dynamicFailure.SearchDiagnostics));
testCase.verifyEqual(fieldnames(dynamicFailure.SearchDiagnostics), ...
    fieldnames(blockedFailure.SearchDiagnostics));
successCandidate = successResult.SearchDiagnostics. ...
    CandidatePolicyMotions(successResult.selectedCandidateIndex);
failureCandidate = candidateFailure.SearchDiagnostics. ...
    CandidatePolicyMotions(1);
testCase.verifyEqual(fieldnames(successCandidate), ...
    fieldnames(failureCandidate));
testCase.verifyEqual(fieldnames(successCandidate.Validation), ...
    fieldnames(failureCandidate.Validation));
end

function [initialState, goalState, limits] = standardRequest( ...
        start_deg, goal_deg, horizon_s)
% PURPOSE
%   - Build neutral state and limit fixtures for planner tests.
initialState = struct( ...
    "time_s", 0, "position_deg", start_deg, ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", horizon_s, "position_deg", goal_deg, ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [1 1], ...
    "maxJerk_deg_s3", [2.5 2.5]);
end

function options = fastOptions(maximumSeedCount)
% PURPOSE
%   - Keep regression runtime bounded without changing physical inputs.
options = struct( ...
    "RlDurationTrialCount", 8, ...
    "MaximumRlPolicySeeds", maximumSeedCount, ...
    "MaximumPlanningTime_s", 120, ...
    "UseParallel", "off", ...
    "Verbose", false);
end

function duration_s = deliberateStopBaseline(route_deg, limits)
% PURPOSE
%   - Compute a conservative stop-at-each-vertex comparison duration.
step_deg = diff(route_deg, 1, 1);
distance_deg = vecnorm(step_deg, 2, 2);
velocity_deg_s = min(limits.maxVelocity_deg_s);
acceleration_deg_s2 = min(limits.maxAcceleration_deg_s2);
jerk_deg_s3 = min(limits.maxJerk_deg_s3);
duration_s = sum(distance_deg / velocity_deg_s + ...
    velocity_deg_s / acceleration_deg_s2 + ...
    2 * acceleration_deg_s2 / jerk_deg_s3);
end

function closeMotionFigures(handles)
% PURPOSE
%   - Close all figures made by one plotAzElMotion test call.
figureHandles = handles.WorkspaceFigure;
if isstruct(handles.VisibilityGraphs) && ...
        isfield(handles.VisibilityGraphs, "Figure")
    figureHandles(end + 1) = handles.VisibilityGraphs.Figure;
end
if ~isempty(handles.KinematicsFigure)
    figureHandles(end + 1) = handles.KinematicsFigure;
end
if isstruct(handles.Animation) && isfield(handles.Animation, "Figure")
    figureHandles(end + 1) = handles.Animation.Figure;
end
close(figureHandles(isgraphics(figureHandles)));
end
