function tests = testAzElRpRetimer
%% Section 0: Header & Readme
% SYNTAX
%   results = runtests("tests/testAzElRpRetimer.m")
%**************************************************************************
% PURPOSE
%   - Verify RP curve proposals, deterministic time selection, nonlinear
%     collision certificates, local repair, and honest repair exhaustion.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - tests (matlab.unittest.FunctionTestCase array)
%       Deterministic production-retimer regression cases.
%**************************************************************************
% UNITS
%   - Position is degrees. Time is seconds. Derivative suffixes state units.
%**************************************************************************

%% Section 1: Create The Function-Test Suite

tests = functiontests(localfunctions);
end

%% Section 2: Local Test Cases

function setupOnce(testCase)
% Put the repository API on the test path.
repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
testCase.TestData.OriginalPath = path;
addpath(repositoryRoot);
end

function teardownOnce(testCase)
% Restore the caller path.
path(testCase.TestData.OriginalPath);
end

function testNinetyDegreeCornerIsRoundedAndFaster(testCase)
% The selected equal-leg turn must beat the evaluated sharp-stop member.
route_deg = [0 0; 10 0; 10 10];
[initialState, goalState, limits, options] = requestForRoute(route_deg);
obstacleField = buildAzElTimeObstacleField([]);

[smoothPath, timedPath] = azElInternal.retimeAzElSpatialPath( ...
    route_deg, obstacleField, initialState, goalState, limits, ...
    options, initialState.time_s);

testCase.verifyTrue(timedPath.Success, timedPath.Message);
testCase.verifyEqual(smoothPath.RoundedCornerCount, 1);
testCase.verifyEqual(timedPath.TerminationReason, ...
    "certifiedUnconstrainedOptimum");
testCase.verifyGreaterThan( ...
    smoothPath.CornerDiagnostics. ...
    CertifiedMinimumCurvatureRadius_deg, 0);
candidates = smoothPath.GeometryOptimizationDiagnostics.Candidates;
sharpIndex = [];
for candidateIndex = 1:numel(candidates)
    if all(candidates(candidateIndex).RadiusScaleByCorner == 0)
        sharpIndex = candidateIndex;
        break;
    end
end
testCase.assertNotEmpty(sharpIndex);
testCase.verifyLessThan(timedPath.MinimumMotionDuration_s, ...
    candidates(sharpIndex).MinimumMotionDuration_s);
testCase.verifyTrue( ...
    timedPath.RetimerDiagnostics.FinalCollisionCertificate.Resolved);
testCase.verifyTrue(timedPath.RetimerDiagnostics.FinalCollisionFree);
end

function testStaticCollisionUsesNondecreasingRadiusRepair(testCase)
% A protected corner obstruction must produce an outward certified bulge.
route_deg = [0 0; 10 0; 10 10];
[initialState, goalState, limits, options] = requestForRoute(route_deg);
obstacle = makeAzElObstacleData( ...
    "protected region", [0; 100], ...
    [9.4; 9.7; 9.7; 9.4], [0.3; 0.3; 0.7; 0.7], 0.02);
obstacleField = buildAzElTimeObstacleField(obstacle);

[smoothPath, timedPath] = azElInternal.retimeAzElSpatialPath( ...
    route_deg, obstacleField, initialState, goalState, limits, ...
    options, initialState.time_s);

diagnostics = timedPath.RetimerDiagnostics;
testCase.verifyTrue(timedPath.Success, timedPath.Message);
testCase.verifyEqual(timedPath.TerminationReason, ...
    "certifiedAfterLocalRepair");
testCase.verifyFalse(diagnostics.UnconstrainedCollisionFree);
testCase.verifyTrue(diagnostics.FinalCollisionFree);
testCase.verifyGreaterThan(diagnostics.RepairAttemptCount, 0);
testCase.verifyTrue(diagnostics.SafetyMarginPreserved);
testCase.verifyEqual(diagnostics.OriginalSafetyMargins_deg, 0.02, ...
    "AbsTol", 1e-12);
testCase.verifyGreaterThanOrEqual(diagnostics.FinalRadius_deg, ...
    diagnostics.UnconstrainedRadius_deg - 1e-10);
testCase.verifyGreaterThan(norm( ...
    diagnostics.CornerRepairDiagnostics(1).Displacement_deg), 0);
blocked = queryAzElTimedCurveCollision( ...
    obstacleField, timedPath, struct( ...
        "MaximumNumericalEnvelope_deg", ...
            options.RpCollisionCurveTolerance_deg, ...
        "TimePaddingSamples", 0));
testCase.verifyFalse(any(blocked));
testCase.verifyEqual(smoothPath.OriginalPathPosition_deg, route_deg);
end

function testLineCollisionReturnsRepairExhaustion(testCase)
% A colliding line has no same-route curve repair and must fail honestly.
route_deg = [0 0; 10 0];
[initialState, goalState, limits, options] = requestForRoute(route_deg);
obstacle = makeAzElObstacleData( ...
    "line blocker", [0; 100], [4; 6; 6; 4], [-1; -1; 1; 1], 0.05);
obstacleField = buildAzElTimeObstacleField(obstacle);

[~, timedPath] = azElInternal.retimeAzElSpatialPath( ...
    route_deg, obstacleField, initialState, goalState, limits, ...
    options, initialState.time_s);

testCase.verifyFalse(timedPath.Success);
testCase.verifyTrue(timedPath.HasTimedAttempt);
testCase.verifyEqual(timedPath.TerminationReason, ...
    "collisionRepairExhausted");
testCase.verifyTrue(timedPath.RetimerDiagnostics.RepairExhausted);
testCase.verifyFalse(timedPath.RetimerDiagnostics.FinalCollisionFree);
testCase.verifyNotEmpty(timedPath.RetimerDiagnostics. ...
    InitialCollisionSegmentIndex);
end

function testStructurallyDifferentTurnsAreDeterministic(testCase)
% Unequal oblique turns exercise a different corner family and repeatability.
route_deg = [0 0; 6 0; 8 3; 12 4];
[initialState, goalState, limits, options] = requestForRoute(route_deg);
obstacleField = buildAzElTimeObstacleField([]);

[firstSmoothPath, firstTimedPath] = ...
    azElInternal.retimeAzElSpatialPath( ...
        route_deg, obstacleField, initialState, goalState, limits, ...
        options, initialState.time_s);
[secondSmoothPath, secondTimedPath] = ...
    azElInternal.retimeAzElSpatialPath( ...
        route_deg, obstacleField, initialState, goalState, limits, ...
        options, initialState.time_s);

testCase.verifyTrue(firstTimedPath.Success, firstTimedPath.Message);
testCase.verifyGreaterThanOrEqual(firstSmoothPath.RoundedCornerCount, 1);
testCase.verifyEqual(firstTimedPath.MinimumMotionDuration_s, ...
    secondTimedPath.MinimumMotionDuration_s, "AbsTol", 1e-12);
testCase.verifyEqual(firstSmoothPath.position_deg, ...
    secondSmoothPath.position_deg, "AbsTol", 1e-12);
testCase.verifyGreaterThan( ...
    firstSmoothPath.GeometryOptimizationDiagnostics.CandidateCount, 6);
end

function testCurveEnvelopeDetectsBetweenSampleHazard(testCase)
% Clear endpoints must not hide a parabolic mid-interval obstacle crossing.
obstacle = makeAzElObstacleData( ...
    "between samples", [0; 1], ...
    [0.45; 0.55; 0.55; 0.45], [0.9; 0.9; 1.1; 1.1], 0);
obstacleField = buildAzElTimeObstacleField(obstacle);
profile = struct( ...
    "StartTime_s", 0, ...
    "EndTime_s", 1, ...
    "Duration_s", 1, ...
    "PhaseStartTime_s", 0, ...
    "PhaseDuration_s", 1);
timedPath = struct( ...
    "Success", true, ...
    "time_s", [0; 1], ...
    "position_deg", [0 0; 1 0], ...
    "ConstraintDiagnostics", struct( ...
        "PeakAcceleration_deg_s2", [0 8]), ...
    "SegmentProfiles", profile);
sampleBlocked = queryAzElTimeObstacle( ...
    obstacleField, timedPath.position_deg(:, 1), ...
    timedPath.position_deg(:, 2), timedPath.time_s);

[blocked, certificate] = queryAzElTimedCurveCollision( ...
    obstacleField, timedPath, struct( ...
        "MaximumNumericalEnvelope_deg", 1.01, ...
        "TimePaddingSamples", 0));

testCase.verifyFalse(any(sampleBlocked));
testCase.verifyTrue(certificate.Resolved);
testCase.verifyEqual(certificate.MaximumEnvelope_deg, 1, ...
    "AbsTol", 1e-10);
testCase.verifyTrue(any(blocked));
testCase.verifyFalse(certificate.CollisionFree);
end

function testMovingLineCollisionIsLocalizedAfterRetiming(testCase)
% A moving protected region must be checked at the retimed crossing time.
route_deg = [0 0; 10 0];
[initialState, goalState, limits, options] = requestForRoute(route_deg);
azimuthBySlice_deg = { ...
    [4.8; 5.2; 5.2; 4.8]; ...
    [4.8; 5.2; 5.2; 4.8]};
elevationBySlice_deg = { ...
    [0.7; 0.7; 1.3; 1.3]; ...
    [-1.3; -1.3; -0.7; -0.7]};
obstacle = makeAzElObstacleData( ...
    "moving blocker", [0; 3.66], ...
    azimuthBySlice_deg, elevationBySlice_deg, 0.02);
obstacleField = buildAzElTimeObstacleField(obstacle);

[~, timedPath] = azElInternal.retimeAzElSpatialPath( ...
    route_deg, obstacleField, initialState, goalState, limits, ...
    options, initialState.time_s);

testCase.verifyFalse(timedPath.Success);
testCase.verifyEqual(timedPath.TerminationReason, ...
    "collisionRepairExhausted");
collisionTime_s = timedPath.RetimerDiagnostics.InitialCollisionTime_s;
testCase.verifyNotEmpty(collisionTime_s);
testCase.verifyGreaterThan(min(collisionTime_s), 1.7);
testCase.verifyLessThan(max(collisionTime_s), 2.0);
end

function testRepairPreservesUnrelatedCurveControls(testCase)
% Repair at the first turn must not alter the second turn control polygon.
route_deg = [0 0; 10 0; 10 10; 20 10];
[initialState, goalState, limits, options] = requestForRoute(route_deg);
obstacle = makeAzElObstacleData( ...
    "first turn blocker", [0; 100], ...
    [9.4; 9.7; 9.7; 9.4], [0.3; 0.3; 0.7; 0.7], 0.02);
obstacleField = buildAzElTimeObstacleField(obstacle);

[smoothPath, timedPath] = azElInternal.retimeAzElSpatialPath( ...
    route_deg, obstacleField, initialState, goalState, limits, ...
    options, initialState.time_s);

diagnostics = timedPath.RetimerDiagnostics;
testCase.verifyTrue(timedPath.Success, timedPath.Message);
testCase.verifyEqual(timedPath.TerminationReason, ...
    "certifiedAfterLocalRepair");
testCase.verifyGreaterThan(norm( ...
    diagnostics.CornerRepairDiagnostics(1).Displacement_deg), 0);
testCase.verifyEqual( ...
    diagnostics.CornerRepairDiagnostics(2).Displacement_deg, [0 0]);
testCase.verifyEqual( ...
    smoothPath.CornerDiagnostics(2).ControlPoints_deg, ...
    diagnostics.UnconstrainedControlPointsByCorner_deg{2}, ...
    "AbsTol", 0);
unrelatedCurvePrimitiveIndex = find( ...
    [smoothPath.Primitives.CornerPathPointIndex] == 3);
testCase.verifyFalse(any(ismember(unrelatedCurvePrimitiveIndex, ...
    diagnostics.ContinuityUpdatedPrimitiveIndex)));
end

function testEachCollidingCornerReceivesRepairBudget(testCase)
% Two blocked turns must each receive local proposals before exhaustion.
route_deg = [0 0; 10 0; 10 10; 20 10];
[initialState, goalState, limits, options] = requestForRoute(route_deg);
firstObstacle = makeAzElObstacleData( ...
    "first turn blocker", [0; 100], ...
    [9.4; 9.7; 9.7; 9.4], [0.3; 0.3; 0.7; 0.7], 0.02);
secondObstacle = makeAzElObstacleData( ...
    "second turn blocker", [0; 100], ...
    [10.3; 10.7; 10.7; 10.3], [9.4; 9.4; 9.7; 9.7], 0.02);
obstacleField = buildAzElTimeObstacleField( ...
    [firstObstacle; secondObstacle]);

[~, timedPath] = azElInternal.retimeAzElSpatialPath( ...
    route_deg, obstacleField, initialState, goalState, limits, ...
    options, initialState.time_s);

diagnostics = timedPath.RetimerDiagnostics;
testCase.verifyTrue(timedPath.Success, timedPath.Message);
testCase.verifyGreaterThan(diagnostics.RepairAttemptCountByCorner(1), 0);
testCase.verifyGreaterThan(diagnostics.RepairAttemptCountByCorner(2), 0);
testCase.verifyTrue(all(diagnostics.FinalRadius_deg + 1e-10 >= ...
    diagnostics.UnconstrainedRadius_deg));
testCase.verifyTrue(diagnostics.FinalCollisionFree);
end

function testExhaustedCornerDoesNotStopLaterCorner(testCase)
% A one-proposal corner budget must still be allocated to each collision.
route_deg = [0 0; 10 0; 10 10; 20 10];
[initialState, goalState, limits, options] = requestForRoute(route_deg);
options.RpMaximumRepairAttempts = 1;
firstObstacle = makeAzElObstacleData( ...
    "first turn blocker", [0; 100], ...
    [9.4; 9.7; 9.7; 9.4], [0.3; 0.3; 0.7; 0.7], 0.02);
secondObstacle = makeAzElObstacleData( ...
    "second turn blocker", [0; 100], ...
    [10.3; 10.7; 10.7; 10.3], [9.4; 9.4; 9.7; 9.7], 0.02);
obstacleField = buildAzElTimeObstacleField( ...
    [firstObstacle; secondObstacle]);

[~, timedPath] = azElInternal.retimeAzElSpatialPath( ...
    route_deg, obstacleField, initialState, goalState, limits, ...
    options, initialState.time_s);

diagnostics = timedPath.RetimerDiagnostics;
testCase.verifyEqual(diagnostics.RepairAttemptCountByCorner, [1; 1]);
testCase.verifyEqual(diagnostics.RepairAttemptCount, 2);
end

function testPlannerUsesAnotherRouteAfterDirectRepairExhaustion(testCase)
% A failed direct retimer candidate must not stop visibility-route search.
obstacle = makeAzElObstacleData( ...
    "central blocker", [0; 100], ...
    [-0.5; 0.5; 0.5; -0.5], [-0.5; -0.5; 0.5; 0.5], 0.1);
initialState = struct( ...
    "time_s", 0, "position_deg", [-3 0], ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 30, "position_deg", [3 0], ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [3 3], ...
    "maxAcceleration_deg_s2", [2 2], ...
    "maxJerk_deg_s3", [Inf Inf]);
options = planAzElMotion();
options.UseRpAgent = false;
options.CollisionTimePaddingSamples = 0;
options.MaximumTemporalRefinementSteps = 0;

result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);

testCase.verifyTrue(result.Success, result.Message);
testCase.verifyGreaterThan(result.selectedCandidateIndex, 1);
testCase.verifyFalse(result.candidateDiagnostics.Retimed(1));
testCase.verifyTrue(contains( ...
    result.candidateDiagnostics.Message(1), ...
    "equal-or-larger-radius", "IgnoreCase", true));
testCase.verifyTrue(result.timedSlopePath. ...
    RetimerDiagnostics.FinalCollisionFree);
end

function testFiniteJerkModeUsesRpProductionPath(testCase)
% Finite jerk must retain the analytic certificate under RP geometry search.
route_deg = [0 0; 10 0; 10 10];
[initialState, goalState, limits, options] = requestForRoute(route_deg);
limits.maxJerk_deg_s3 = [1000 1000];
obstacleField = buildAzElTimeObstacleField([]);

[smoothPath, timedPath] = azElInternal.retimeAzElSpatialPath( ...
    route_deg, obstacleField, initialState, goalState, limits, ...
    options, initialState.time_s);

testCase.verifyTrue(timedPath.Success, timedPath.Message);
testCase.verifyEqual(timedPath.RetimerType, ...
    "rpGeometryCertifiedSpatialRetimer");
testCase.verifyTrue( ...
    timedPath.ConstraintDiagnostics.FiniteJerkCertified);
testCase.verifyTrue(timedPath.RetimerDiagnostics.FinalCollisionFree);
testCase.verifyGreaterThan( ...
    smoothPath.GeometryOptimizationDiagnostics.CandidateCount, 1);
end

function testProductionTrainingLabelsAreReproducible(testCase)
% Policy targets must come from repeatable production-retimer selections.
firstData = azElInternal.createRpRetimerTrainingData(2, 8128);
secondData = azElInternal.createRpRetimerTrainingData(2, 8128);

testCase.verifyEqual(firstData.Format, ...
    "AzElRpRetimerTrainingData");
testCase.verifyEqual(firstData.TargetSource, ...
    "productionRetimerSelectedRadius");
testCase.verifyEqual(firstData.Observation, secondData.Observation, ...
    "AbsTol", 0);
testCase.verifyEqual(firstData.BestRadiusFraction, ...
    secondData.BestRadiusFraction, "AbsTol", 0);
for caseIndex = 1:firstData.CaseCount
    expectedObservation = azElInternal.rpRetimerObservation( ...
        firstData.Problems(caseIndex));
    testCase.verifyEqual(firstData.Observation(:, caseIndex), ...
        expectedObservation, "AbsTol", 0);
end
end

function testTrainingDefaultsUseProductionPromotionGate(testCase)
% Training defaults must retain extensive labels and held-out validation.
options = trainAzElRpRetimer();

testCase.verifyEqual(options.MaximumEpisodes, 5000);
testCase.verifyGreaterThanOrEqual(options.TrainingCaseCount, 256);
testCase.verifyGreaterThanOrEqual(options.ValidationCaseCount, 64);
testCase.verifyGreaterThan(options.MinimumRelativeImprovement, 0);
end

function testSavedAgentUsesProductionLabelMetadata(testCase)
% The deployed artifact must identify its production target and gate result.
repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
model = load(fullfile(repositoryRoot, "models", ...
    "azElRpRetimerAgent.mat"), "metadata");

testCase.verifyEqual(model.metadata.Format, ...
    "AzElRpRetimerAgent");
testCase.verifyEqual(model.metadata.Version, 2);
testCase.verifyEqual(model.metadata.TrainingTarget, ...
    "productionRetimerSelectedRadius");
testCase.verifyTrue(model.metadata.Promoted);
testCase.verifyLessThan( ...
    model.metadata.ValidationMeanAbsoluteError, ...
    model.metadata.BestFixedMeanAbsoluteError);
testCase.verifyLessThan( ...
    model.metadata.ValidationMeanAbsoluteError, ...
    model.metadata.ExistingPolicyMeanAbsoluteError);
end

function [initialState, goalState, limits, options] = ...
        requestForRoute(route_deg)
% Build one common acceleration-limited request with deterministic RP controls.
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", route_deg(1, :), ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", 100, ...
    "position_deg", route_deg(end, :), ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [5 5], ...
    "maxAcceleration_deg_s2", [3 3], ...
    "maxJerk_deg_s3", [Inf Inf]);
options = planAzElMotion();
options.UseRpAgent = false;
options.CollisionTimePaddingSamples = 0;
end
