function [result, emptySeedSummary] = emptyAzElPlannerResult(obstacles, initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   [result, emptySeedSummary] = azElPlannerMethods.corridor.internal.emptyAzElPlannerResult( ...
%       obstacles, initialState, goalState, limits, options)
%**************************************************************************
% PURPOSE
%   - Define the single source of truth for the planner result schema. Every
%     expected failure begins with this record and overwrites only known fields,
%     so callers never need a different parser for success and failure.
%**************************************************************************
% INPUTS
%   - obstacles (canonical protected obstacle struct array)
%   - initialState, goalState (normalized scalar state structs)
%   - limits, options (normalized scalar planner-input structs)
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Empty public planner result with stable motion and diagnostics fields.
%   - emptySeedSummary (scalar struct)
%       Stable internal record template shared with the planner.
%**************************************************************************
% UNITS
%   - Position is degrees. Time is seconds. Derivatives use deg/s, deg/s^2,
%     and deg/s^3.
%**************************************************************************

%% Section 1: Build The Stable Result

% Templates use explicit empty shapes and conservative failure values. Inf for
% cost/violation sorts unavailable candidates behind finite evidence; NaN marks
% physical values that were never produced.
emptySeed = struct( ...
    "Index", 0, "Source", "", ...
    "position_deg", zeros(0, 2), "tau", zeros(0, 1), ...
    "CorridorBoundary_deg", zeros(0, 2), "UsesReducedGeometry", false, "EstimatedDuration_s", NaN, "Length_deg", NaN);
emptySeedSummary = struct( ...
    "SeedIndex", 0, "SeedSource", "", "SelectedMotionSource", "", ...
    "OptimizerFeasible", false, "ValidationPassed", false, ...
    "CollisionFree", false, "CollisionResolved", false, ...
    "MinimumClearance_deg", NaN, "UnresolvedIntervalCount", 0, ...
    "ArrivalTime_s", NaN, "MotionDuration_s", NaN, ...
    "IntegratedSquaredJerk_deg2_s5", Inf, ...
    "MaximumConstraintViolation", Inf, ...
    "RelinearizationCount", 0, "MeshRefinementPassCount", 0, ...
    "FirstMotionAttempted", false, "FirstMotionValidationPassed", false, ...
    "FirstMotionTerminationReason", "notRun", "FirstMotionDiagnostics", struct(), ...
    "TerminationReason", "notRun", "Message", "", "SolverDiagnostics", struct());
emptyPolynomial = struct( ...
    "SegmentCount", 0, "SegmentStartTime_s", zeros(0, 1), ...
    "SegmentDuration_s", zeros(0, 1), "FinalTime_s", NaN, ...
    "positionPower_deg", zeros(0, 2, 6), ...
    "velocityPower_deg_s", zeros(0, 2, 5), ...
    "accelerationPower_deg_s2", zeros(0, 2, 4), ...
    "jerkPower_deg_s3", zeros(0, 2, 3), "TerminalState", struct( ...
    "position_deg", [NaN NaN], "velocity_deg_s", [NaN NaN], "acceleration_deg_s2", [NaN NaN]));
result = struct( ...
    "Success", false, ...
    "Message", "Planning was not completed.", ...
    "TerminationReason", "notRun", ...
    "Options", options, ...
    "Inputs", struct( ...
    "obstacles", obstacles, "initialState", initialState, ...
    "goalState", goalState, "limits", limits), ...
    "Seeds", repmat(emptySeed, 0, 1), ...
    "SeedSummaries", repmat(emptySeedSummary, 0, 1), ...
    "SelectedSeedIndex", 0, "SelectedMotionSource", "", ...
    "SelectedSeed_deg", zeros(0, 2), "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), "jerk_deg_s3", zeros(0, 2), ...
    "Polynomial", emptyPolynomial, ...
    "SeedCorridorBoundary_deg", zeros(0, 2), ...
    "SeedCorridor", struct([]), ...
    "Validation", azElPlannerMethods.corridor.validateTrajectory(), ...
    "ArrivalTime_s", NaN, "TrajectoryDuration_s", NaN, ...
    "GoalHorizon_s", goalState.time_s - initialState.time_s, ...
    "FirstValidatedMotionTime_s", NaN, ...
    "SearchDiagnostics", struct( ...
    "PlannerMethod", options.MotionMethod, ...
    "StageTiming", azElPlannerMethods.internal.stageTiming(), ...
    "Grid", struct(), ...
    "SeedSummaries", repmat(emptySeedSummary, 0, 1), ...
    "BestPartialSeedIndex", 0, "MeshRefinementPassCount", 0, ...
    "ValidatedCandidateCount", 0, ...
    "FirstValidatedMotionTime_s", NaN, ...
    "SeedGenerationElapsedTime_s", 0, ...
    "FirstMotionElapsedTime_s", 0, ...
    "CompactC3", struct(), ...
    "AttemptedSeedCount", 0, "TerminationReason", "notRun"), ...
    "ElapsedPlanningTime_s", 0, ...
    "RandomSeed", options.RandomSeed, ...
    "OptimalityStatement", "No motion was validated from the bounded candidate work.");
end
