function graph = buildAzElSafeIntervalRoadmap( ...
        obstacleField, snapshotGraphs, initialState, goalState, options)
%% Section 0: Header & Readme
% SYNTAX
%   graph = azElInternal.buildAzElSafeIntervalRoadmap()
%   graph = azElInternal.buildAzElSafeIntervalRoadmap( ...
%       obstacleField, snapshotGraphs, initialState, goalState, options)
%**************************************************************************
% PURPOSE
%   - Build a sparse spatial roadmap with safe node intervals.
%   - Find earliest-arrival and diverse timed routes with SIPP-IP.
%**************************************************************************
% INPUTS
%   - obstacleField (scalar packed obstacle field)
%       Protected static or time-varying polygons from the public packer.
%   - snapshotGraphs (structure array)
%       Collision-checked spatial visibility graphs used as roadmap seeds.
%   - initialState, goalState (scalar structs)
%       time_s and N-by-2 position_deg fields for the planning horizon.
%   - options (scalar struct)
%       Validated roadmap, interval, SIPP, collision, and limit controls.
%**************************************************************************
% OUTPUTS
%   - graph (scalar struct)
%       Stable success/failure record with safe intervals, search traces,
%       diverse timed candidates, and a compatibility primary path.
%**************************************************************************
% UNITS
%   - Position is [azimuth elevation] in degrees. Time is seconds.
%**************************************************************************

%% Section 1: Validate Inputs & Build The Spatial Roadmap

graph = emptySafeIntervalRoadmap();
if nargin == 0
    return;
end
validateRoadmapInputs(obstacleField, initialState, goalState);
options = safeIntervalOptions(options);
graph.Options = options;
sippTimer = tic;

[candidatePosition_deg, candidateDiagnostics] = ...
    collectSpatialCandidates(snapshotGraphs, initialState.position_deg, ...
    goalState.position_deg, options.MaximumSpaceTimeCandidateCount, ...
    options.SpaceTimeNodeMergeTolerance_deg);
spatialPosition_deg = [initialState.position_deg; ...
    goalState.position_deg; candidatePosition_deg];
[spatialEdgeSourceNodeIndex, spatialEdgeTargetNodeIndex, ...
    spatialEdgeLength_deg, preferredRouteNodeSequences] = ...
    buildPotentialSpatialEdges( ...
    spatialPosition_deg, snapshotGraphs, options);
spatialNodeCount = size(spatialPosition_deg, 1);
spatialEdgeCount = numel(spatialEdgeSourceNodeIndex);

graph.SpatialNodePosition_deg = spatialPosition_deg;
graph.SpatialEdgeSourceNodeIndex = spatialEdgeSourceNodeIndex;
graph.SpatialEdgeTargetNodeIndex = spatialEdgeTargetNodeIndex;
graph.SpatialEdgeLength_deg = spatialEdgeLength_deg;
graph.PotentialSpatialEdgeCount = spatialEdgeCount;
graph.CandidateReductionDiagnostics = candidateDiagnostics;
if spatialEdgeCount == 0
    graph.Message = "The spatial roadmap contains no potential edge.";
    graph.TerminationReason = "disconnectedRoadmap";
    return;
end

%% Section 2: Compute Safe Intervals At Every Spatial Node

[timeSample_s, eventTime_s] = safeIntervalTimeGrid( ...
    obstacleField, initialState.time_s, goalState.time_s, options);
[nodeSafeMask, safeIntervals, safeIntervalDiagnostics] = ...
    calculateSafeIntervals( ...
    obstacleField, spatialPosition_deg, timeSample_s, ...
    eventTime_s, options);
[stateNodeIndex, stateIntervalIndex, stateStartTime_s, ...
    stateStopTime_s, nodeStateIndex] = flattenSafeIntervals(safeIntervals);

graph.Representation = "safeIntervalVisibilityRoadmap";
graph.SearchMethod = "safeIntervalPathPlanningWithIntervalProjection";
graph.LayerTime_s = timeSample_s;
graph.NodeActiveMask = nodeSafeMask;
graph.SafeIntervals = safeIntervals;
graph.SafeIntervalStateNodeIndex = stateNodeIndex;
graph.SafeIntervalStateIntervalIndex = stateIntervalIndex;
graph.SafeIntervalStateStartTime_s = stateStartTime_s;
graph.SafeIntervalStateStopTime_s = stateStopTime_s;
graph.SafeIntervalCount = numel(stateNodeIndex);
graph.SafeIntervalDiagnostics = safeIntervalDiagnostics;
graph.NodeAzElTime = [spatialPosition_deg(stateNodeIndex, :), ...
    stateStartTime_s];

safeIntervalTimeLimitReached = ...
    isfinite(options.MaximumSippWallTime_s) && ...
    toc(sippTimer) >= options.MaximumSippWallTime_s;
if safeIntervalTimeLimitReached
    graph.Message = "SIPP-IP reached the configured wall-time limit " + ...
        "after safe-interval construction.";
    graph.TerminationReason = "searchTimeLimit";
    graph.CandidateGenerationDiagnostics = struct( ...
        "SearchRunCount", 0, ...
        "AlternativeSearchCount", 0, ...
        "SuccessfulSearchCount", 0, ...
        "DistinctCandidateCount", 0, ...
        "MaximumCandidateCount", options.MaximumSippCandidates, ...
        "SharedTimeLimitReached", true, ...
        "ElapsedSearchTime_s", toc(sippTimer), ...
        "SearchSummaries", searchSummary(repmat( ...
        emptySearchResult(numel(stateNodeIndex)), 0, 1)));
    return;
end

startStateIndex = findStateAtTime(nodeStateIndex{1}, ...
    stateStartTime_s, stateStopTime_s, initialState.time_s, ...
    options.SafeIntervalTimeTolerance_s);
if startStateIndex == 0
    graph.Message = "The start has no safe interval at its initial time.";
    graph.TerminationReason = "noStartSafeInterval";
    return;
end
if isempty(nodeStateIndex{2})
    graph.Message = "The goal has no safe interval in the time horizon.";
    graph.TerminationReason = "noGoalSafeInterval";
    return;
end

%% Section 3: Run SIPP And Generate Diverse Timed Candidates

adjacency = spatialAdjacency(spatialNodeCount, ...
    spatialEdgeSourceNodeIndex, spatialEdgeTargetNodeIndex);
searchData = struct( ...
    "ObstacleField", obstacleField, ...
    "SpatialPosition_deg", spatialPosition_deg, ...
    "SpatialEdgeSourceNodeIndex", spatialEdgeSourceNodeIndex, ...
    "SpatialEdgeTargetNodeIndex", spatialEdgeTargetNodeIndex, ...
    "SpatialEdgeLength_deg", spatialEdgeLength_deg, ...
    "Adjacency", {adjacency}, ...
    "PreferredRouteNodeSequences", {preferredRouteNodeSequences}, ...
    "StateNodeIndex", stateNodeIndex, ...
    "StateIntervalIndex", stateIntervalIndex, ...
    "StateStartTime_s", stateStartTime_s, ...
    "StateStopTime_s", stateStopTime_s, ...
    "NodeStateIndex", {nodeStateIndex}, ...
    "StartStateIndex", startStateIndex, ...
    "InitialState", initialState, ...
    "GoalState", goalState, ...
    "TimeSample_s", timeSample_s, ...
    "SharedSearchTimer", sippTimer, ...
    "SharedSearchWallTime_s", options.MaximumSippWallTime_s, ...
    "Options", options);

[candidates, primarySearch, candidateDiagnostics] = ...
    generateDiverseCandidates(searchData);
graph.DiverseCandidates = candidates;
graph.DiverseCandidateCount = numel(candidates);
graph.CandidateGenerationDiagnostics = candidateDiagnostics;
copyFields = [ ...
    "ParentStateIndex" "CostToCome_deg" "EarliestArrival_s" ...
    "ReachableIntervalStop_s" ...
    "HeuristicTime_s" "ExpandedStateIndex" "FrontierStateIndex" ...
    "BestPartialStateIndex" "BestPartialDistance_deg" ...
    "AcceptedEdgeSourceStateIndex" "AcceptedEdgeTargetStateIndex" ...
    "RejectedEdgeSourceStateIndex" "RejectedEdgeTargetStateIndex" ...
    "RejectedEdgeReason" "GeneratedTransitionCount" ...
    "AcceptedTransitionCount" "CollisionRejectedTransitionCount" ...
    "WindowRejectedTransitionCount" "ExpandedStateCount" ...
    "TraversalQueryCount" "InvariantTraversalSampleSkipCount" ...
    "ProjectedIntervalCount" ...
    "TerminationReason" "Message"];
for fieldIndex = 1:numel(copyFields)
    fieldName = copyFields(fieldIndex);
    graph.(fieldName) = primarySearch.(fieldName);
end
graph.ParentNodeIndex = primarySearch.ParentStateIndex;
graph.CostToCome_deg = primarySearch.CostToCome_deg;
graph.ExpandedNodeIndex = primarySearch.ExpandedStateIndex;
graph.FrontierNodeIndex = primarySearch.FrontierStateIndex;
graph.BestPartialNodeIndex = primarySearch.BestPartialStateIndex;
graph.BestPartialDistance_deg = primarySearch.BestPartialDistance_deg;
graph.AcceptedEdgeSourceNodeIndex = ...
    primarySearch.AcceptedEdgeSourceStateIndex;
graph.AcceptedEdgeTargetNodeIndex = ...
    primarySearch.AcceptedEdgeTargetStateIndex;
graph.RejectedEdgeSourceNodeIndex = ...
    primarySearch.RejectedEdgeSourceStateIndex;
graph.RejectedEdgeTargetNodeIndex = ...
    primarySearch.RejectedEdgeTargetStateIndex;
graph.GeneratedEdgeCount = primarySearch.GeneratedTransitionCount;
graph.AcceptedEdgeCount = primarySearch.AcceptedTransitionCount;
graph.CollisionRejectedEdgeCount = ...
    primarySearch.CollisionRejectedTransitionCount;
graph.DynamicsRejectedEdgeCount = 0;
graph.AcceptedDiagnosticEdgeCount = numel( ...
    graph.AcceptedEdgeSourceNodeIndex);
graph.RejectedDiagnosticEdgeCount = numel( ...
    graph.RejectedEdgeSourceNodeIndex);
graph.DiagnosticEdgeTraceWasLimited = ...
    primarySearch.DiagnosticEdgeTraceWasLimited;
graph.EvaluatedLayerCount = numel(timeSample_s);

reachedState = isfinite(primarySearch.EarliestArrival_s);
graph.NodeAzElTime(reachedState, 3) = ...
    primarySearch.EarliestArrival_s(reachedState);
if isempty(candidates)
    graph.Message = primarySearch.Message;
    graph.TerminationReason = primarySearch.TerminationReason;
    return;
end

%% Section 4: Assemble The Primary Compatibility Path

primaryCandidate = candidates(1);
graph.Success = true;
graph.Message = "SIPP-IP reached the goal.";
graph.TerminationReason = "goalReached";
graph.PathNodeIndex = primaryCandidate.StateIndex;
graph.PathSpatialNodeIndex = primaryCandidate.SpatialNodeIndex;
graph.PathSafeIntervalIndex = primaryCandidate.SafeIntervalIndex;
graph.PathPosition_deg = primaryCandidate.Position_deg;
graph.PathTime_s = primaryCandidate.Time_s;
graph.PathCost_deg = primaryCandidate.AngularLength_deg;
graph.ArrivalTime_s = primaryCandidate.ArrivalTime_s;
graph.PathEdgeCount = numel(primaryCandidate.EdgeIdSequence);
graph.WaitEdgeCount = primaryCandidate.WaitEventCount;
graph.WaitDuration_s = primaryCandidate.WaitDuration_s;
end

%% Section 5: Local Functions

function validateRoadmapInputs(obstacleField, initialState, goalState)
% PURPOSE
%   - Reject invalid public-boundary records before search allocation.
fieldIsPacked = isstruct(obstacleField) && isscalar(obstacleField) && ...
    isfield(obstacleField, "Format") && ...
    string(obstacleField.Format) == "AzElTimeObstacleField";
if ~fieldIsPacked
    error("buildAzElSafeIntervalRoadmap:InvalidObstacleField", ...
        "obstacleField must come from buildAzElTimeObstacleField.");
end
requiredStateFields = ["time_s" "position_deg"];
statesAreValid = isstruct(initialState) && isscalar(initialState) && ...
    all(isfield(initialState, requiredStateFields)) && ...
    isstruct(goalState) && isscalar(goalState) && ...
    all(isfield(goalState, requiredStateFields));
if ~statesAreValid
    error("buildAzElSafeIntervalRoadmap:InvalidState", ...
        "initialState and goalState need time_s and position_deg.");
end
validateattributes(initialState.time_s, {'numeric'}, ...
    {'real', 'finite', 'scalar'});
validateattributes(goalState.time_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', '>', initialState.time_s});
validateattributes(initialState.position_deg, {'numeric'}, ...
    {'real', 'finite', 'size', [1 2]});
validateattributes(goalState.position_deg, {'numeric'}, ...
    {'real', 'finite', 'size', [1 2]});
end

function options = safeIntervalOptions(options)
% PURPOSE
%   - Validate the complete internal safe-interval search contract.
requiredFields = [ ...
    "GoalTimeMode" "MaximumVelocity_deg_s" ...
    "MaximumAcceleration_deg_s2" "MaximumJerk_deg_s3" ...
    "SpaceTimeLayerCount" "MaximumSpaceTimeCandidateCount" ...
    "MaximumSpaceTimeDiagnosticEdgeCount" ...
    "CollisionTimePaddingSamples" ...
    "MaximumSafeIntervalRefinements" ...
    "SafeIntervalTimeTolerance_s" "MaximumSippCandidates" ...
    "MaximumSippExpansions" "MaximumSippWallTime_s" ...
    "SippKNearestNeighbors" "SippMaximumEdgeLength_deg" ...
    "AllowSippWaiting" ...
    "SpaceTimeNodeMergeTolerance_deg"];
if ~isstruct(options) || ~isscalar(options) || ...
        ~all(isfield(options, requiredFields))
    error("buildAzElSafeIntervalRoadmap:InvalidOptions", ...
        "options does not contain every safe-interval search control.");
end
options.GoalTimeMode = lower(string(options.GoalTimeMode));
if ~isscalar(options.GoalTimeMode) || ~any( ...
        options.GoalTimeMode == ["earliestarrival" "fixedarrival"])
    error("buildAzElSafeIntervalRoadmap:InvalidGoalTimeMode", ...
        "GoalTimeMode must be earliestArrival or fixedArrival.");
end
validateattributes(options.MaximumVelocity_deg_s, {'numeric'}, ...
    {'real', 'positive', 'vector', 'numel', 2});
options.MaximumVelocity_deg_s = reshape( ...
    double(options.MaximumVelocity_deg_s), 1, 2);
motionLimitNames = [ ...
    "MaximumAcceleration_deg_s2" "MaximumJerk_deg_s3"];
for motionLimitIndex = 1:numel(motionLimitNames)
    motionLimitName = motionLimitNames(motionLimitIndex);
    validateattributes(options.(motionLimitName), {'numeric'}, ...
        {'real', 'positive', 'vector', 'numel', 2});
    options.(motionLimitName) = reshape( ...
        double(options.(motionLimitName)), 1, 2);
end
positiveIntegerNames = ["SpaceTimeLayerCount" ...
    "MaximumSippCandidates" ...
    "MaximumSippExpansions" "SippKNearestNeighbors"];
for optionIndex = 1:numel(positiveIntegerNames)
    optionName = positiveIntegerNames(optionIndex);
    validateattributes(options.(optionName), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', 'positive'});
end
validateattributes(options.MaximumSpaceTimeCandidateCount, {'numeric'}, ...
    {'real', 'scalar', 'positive'});
if isfinite(options.MaximumSpaceTimeCandidateCount) && ...
        fix(options.MaximumSpaceTimeCandidateCount) ~= ...
        options.MaximumSpaceTimeCandidateCount
    error("buildAzElSafeIntervalRoadmap:InvalidCandidateLimit", ...
        "MaximumSpaceTimeCandidateCount must be an integer or Inf.");
end
if options.SpaceTimeLayerCount < 3
    error("buildAzElSafeIntervalRoadmap:InvalidTimeSampleCount", ...
        "SpaceTimeLayerCount must be at least 3.");
end
nonnegativeIntegerNames = ["MaximumSpaceTimeDiagnosticEdgeCount" ...
    "CollisionTimePaddingSamples" ...
    "MaximumSafeIntervalRefinements"];
for optionIndex = 1:numel(nonnegativeIntegerNames)
    optionName = nonnegativeIntegerNames(optionIndex);
    validateattributes(options.(optionName), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', 'nonnegative'});
end
validateattributes(options.SafeIntervalTimeTolerance_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
validateattributes(options.MaximumSippWallTime_s, {'numeric'}, ...
    {'real', 'scalar', 'positive'});
validateattributes(options.SippMaximumEdgeLength_deg, {'numeric'}, ...
    {'real', 'scalar', 'positive'});
validateattributes(options.SpaceTimeNodeMergeTolerance_deg, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'});
options.AllowSippWaiting = azElInternal.normalizeLogicalScalar( ...
    options.AllowSippWaiting, "AllowSippWaiting", ...
    "buildAzElSafeIntervalRoadmap:InvalidAllowWaiting");
end

function [candidatePosition_deg, diagnostics] = ...
        collectSpatialCandidates(snapshotGraphs, startPosition_deg, ...
        goalPosition_deg, maximumCount, mergeTolerance_deg)
% PURPOSE
%   - Prefer route nodes, then add other bounded visibility candidates.
routePosition_deg = zeros(0, 2);
otherPosition_deg = zeros(0, 2);
for graphIndex = 1:numel(snapshotGraphs)
    snapshotGraph = snapshotGraphs(graphIndex);
    if isfield(snapshotGraph, "Success") && snapshotGraph.Success
        routePosition_deg = appendGraphRoute( ...
            routePosition_deg, snapshotGraph, "PathPosition_deg");
        routePosition_deg = appendGraphRoute( ...
            routePosition_deg, snapshotGraph, ...
            "AlternativePathPosition_deg");
    end
    if isfield(snapshotGraph, "NodePosition_deg")
        activePosition_deg = snapshotGraph.NodePosition_deg;
        if isfield(snapshotGraph, "CandidateActiveMask") && ...
                size(activePosition_deg, 1) >= 2 + ...
                numel(snapshotGraph.CandidateActiveMask)
            activePosition_deg = activePosition_deg( ...
                [true; true; snapshotGraph.CandidateActiveMask(:)], :);
        end
        otherPosition_deg = [otherPosition_deg; ...
            activePosition_deg]; %#ok<AGROW>
    end
end
endpointPosition_deg = [startPosition_deg; goalPosition_deg];
routePosition_deg = retainUniqueRows(routePosition_deg, ...
    endpointPosition_deg, mergeTolerance_deg);
otherPosition_deg = retainUniqueRows(otherPosition_deg, ...
    [endpointPosition_deg; routePosition_deg], mergeTolerance_deg);
allPosition_deg = [routePosition_deg; otherPosition_deg];
inputCount = size(allPosition_deg, 1);
retainedCount = min(inputCount, maximumCount);
candidatePosition_deg = allPosition_deg(1:retainedCount, :);
if retainedCount < inputCount
    warning("buildAzElSafeIntervalRoadmap:CandidateReduction", ...
        "The roadmap retained %d of %d candidates. Increase " + ...
        "MaximumSpaceTimeCandidateCount to retain more nodes.", ...
        retainedCount, inputCount);
end
diagnostics = struct( ...
    "InputCandidateCount", inputCount, ...
    "RouteCandidateCount", size(routePosition_deg, 1), ...
    "OtherGraphCandidateCount", size(otherPosition_deg, 1), ...
    "RetainedCandidateCount", retainedCount, ...
    "DroppedCandidateCount", inputCount - retainedCount, ...
    "MaximumCandidateCount", maximumCount);
end

function positions_deg = appendGraphRoute( ...
        positions_deg, graph, fieldName)
% PURPOSE
%   - Append one optional visibility route without call-site branches.
if isfield(graph, fieldName) && ~isempty(graph.(fieldName))
    positions_deg = [positions_deg; graph.(fieldName)];
end
end

function retained_deg = retainUniqueRows( ...
        positions_deg, existing_deg, tolerance_deg)
% PURPOSE
%   - Deduplicate points with one documented angular tolerance.
retained_deg = zeros(0, 2);
for pointIndex = 1:size(positions_deg, 1)
    point_deg = positions_deg(pointIndex, :);
    comparison_deg = [existing_deg; retained_deg];
    isDuplicate = ~isempty(comparison_deg) && any(all( ...
        abs(comparison_deg - point_deg) <= tolerance_deg, 2));
    if ~isDuplicate
        retained_deg(end + 1, :) = point_deg; %#ok<AGROW>
    end
end
end

function [sourceNodeIndex, targetNodeIndex, edgeLength_deg, ...
        preferredRouteNodeSequences] = ...
        buildPotentialSpatialEdges(positions_deg, snapshotGraphs, options)
% PURPOSE
%   - Combine route adjacency with bounded nearest-neighbor connections.
nodeCount = size(positions_deg, 1);
pairMask = false(nodeCount, nodeCount);
preferredRouteNodeSequences = cell(0, 1);
if nodeCount >= 2
    pairMask(1, 2) = true;
end
routeFieldNames = ["PathPosition_deg" ...
    "AlternativePathPosition_deg"];
for graphIndex = 1:numel(snapshotGraphs)
    for fieldIndex = 1:numel(routeFieldNames)
        fieldName = routeFieldNames(fieldIndex);
        if ~isfield(snapshotGraphs(graphIndex), fieldName)
            continue;
        end
        route_deg = snapshotGraphs(graphIndex).(fieldName);
        routeNodeIndex = zeros(size(route_deg, 1), 1);
        for routeIndex = 1:size(route_deg, 1)
            routeNodeIndex(routeIndex) = nearestNode( ...
                route_deg(routeIndex, :), positions_deg, ...
                options.SpaceTimeNodeMergeTolerance_deg);
        end
        routeNodeIndex = routeNodeIndex(routeNodeIndex > 0);
        routeNodeIndex = removeConsecutiveNodeCopies(routeNodeIndex);
        if numel(routeNodeIndex) >= 2 && routeNodeIndex(1) == 1 && ...
                routeNodeIndex(end) == 2 && ...
                ~sequenceAlreadyStored( ...
                preferredRouteNodeSequences, routeNodeIndex)
            preferredRouteNodeSequences{end + 1, 1} = ...
                routeNodeIndex; %#ok<AGROW>
        end
        for routeIndex = 1:numel(routeNodeIndex) - 1
            firstIndex = min(routeNodeIndex(routeIndex:routeIndex + 1));
            secondIndex = max(routeNodeIndex(routeIndex:routeIndex + 1));
            if firstIndex ~= secondIndex
                pairMask(firstIndex, secondIndex) = true;
            end
        end
    end
end
for sourceIndex = 1:nodeCount
    delta_deg = positions_deg - positions_deg(sourceIndex, :);
    distance_deg = hypot(delta_deg(:, 1), delta_deg(:, 2));
    distance_deg(sourceIndex) = Inf;
    ranking = [distance_deg, (1:nodeCount).'];
    [~, order] = sortrows(ranking, [1 2]);
    neighborCount = min(options.SippKNearestNeighbors, nodeCount - 1);
    for neighborOrderIndex = 1:neighborCount
        targetIndex = order(neighborOrderIndex);
        if distance_deg(targetIndex) > options.SippMaximumEdgeLength_deg
            continue;
        end
        firstIndex = min(sourceIndex, targetIndex);
        secondIndex = max(sourceIndex, targetIndex);
        pairMask(firstIndex, secondIndex) = true;
    end
end
[sourceNodeIndex, targetNodeIndex] = find(triu(pairMask, 1));
delta_deg = positions_deg(targetNodeIndex, :) - ...
    positions_deg(sourceNodeIndex, :);
edgeLength_deg = hypot(delta_deg(:, 1), delta_deg(:, 2));
end

function nodeIndex = removeConsecutiveNodeCopies(nodeIndex)
% PURPOSE
%   - Preserve route order while removing zero-length node transitions.
if numel(nodeIndex) < 2
    return;
end
nodeIndex = nodeIndex([true; diff(nodeIndex) ~= 0]);
end

function isStored = sequenceAlreadyStored(sequences, candidateSequence)
% PURPOSE
%   - Avoid duplicate preferred routes from repeated snapshot times.
isStored = false;
for sequenceIndex = 1:numel(sequences)
    if isequal(sequences{sequenceIndex}, candidateSequence)
        isStored = true;
        return;
    end
end
end

function nodeIndex = nearestNode(point_deg, positions_deg, tolerance_deg)
% PURPOSE
%   - Map snapshot route points to the deduplicated spatial roadmap.
delta_deg = positions_deg - point_deg;
distance_deg = hypot(delta_deg(:, 1), delta_deg(:, 2));
[minimumDistance_deg, nodeIndex] = min(distance_deg);
if minimumDistance_deg > max(tolerance_deg, 1e-10)
    nodeIndex = 0;
end
end

function [timeSample_s, eventTime_s] = safeIntervalTimeGrid( ...
        obstacleField, initialTime_s, finalTime_s, options)
% PURPOSE
%   - Refine only source intervals in which packed geometry can change.
eventTime_s = [initialTime_s; finalTime_s];
for obstacleIndex = 1:obstacleField.ObstacleCount
    obstacleTime_s = obstacleField.Obstacles(obstacleIndex).TimeSeconds;
    obstacleTime_s = obstacleTime_s(obstacleTime_s >= initialTime_s & ...
        obstacleTime_s <= finalTime_s);
    eventTime_s = [eventTime_s; obstacleTime_s]; %#ok<AGROW>
end
eventTime_s = unique(eventTime_s);
baseTime_s = linspace(initialTime_s, finalTime_s, ...
    options.SpaceTimeLayerCount).';
retainedBaseTime_s = zeros(0, 1);
for baseIndex = 1:numel(baseTime_s)
    baseValue_s = baseTime_s(baseIndex);
    if any(eventTime_s == baseValue_s)
        retainedBaseTime_s(end + 1, 1) = baseValue_s; %#ok<AGROW>
        continue;
    end
    lowerEvent_s = eventTime_s(find( ...
        eventTime_s < baseValue_s, 1, "last"));
    upperEvent_s = eventTime_s(find( ...
        eventTime_s > baseValue_s, 1, "first"));
    geometryCanChange = ~packedGeometryIsInvariantOverWindow( ...
        obstacleField, lowerEvent_s, upperEvent_s, ...
        options.CollisionTimePaddingSamples);
    if geometryCanChange
        retainedBaseTime_s(end + 1, 1) = baseValue_s; %#ok<AGROW>
    end
end
timeSample_s = unique([eventTime_s; retainedBaseTime_s]);
baseIntervalCount = max(1, options.SpaceTimeLayerCount - 1);
baseRefinementDepth = floor(log2(baseIntervalCount));
additionalRefinementCount = max(0, ...
    options.MaximumSafeIntervalRefinements - baseRefinementDepth);
for refinementIndex = 1:additionalRefinementCount
    midpointTime_s = zeros(0, 1);
    for intervalIndex = 1:numel(timeSample_s) - 1
        lowerTime_s = timeSample_s(intervalIndex);
        upperTime_s = timeSample_s(intervalIndex + 1);
        geometryCanChange = ~packedGeometryIsInvariantOverWindow( ...
            obstacleField, lowerTime_s, upperTime_s, ...
            options.CollisionTimePaddingSamples);
        if geometryCanChange
            midpointTime_s(end + 1, 1) = ...
                0.5 * (lowerTime_s + upperTime_s); %#ok<AGROW>
        end
    end
    timeSample_s = unique([timeSample_s; midpointTime_s]);
end
end

function [nodeSafeMask, safeIntervals, diagnostics] = ...
        calculateSafeIntervals( ...
        obstacleField, positions_deg, timeSample_s, eventTime_s, options)
% PURPOSE
%   - Prove clear source intervals before querying unresolved time samples.
nodeCount = size(positions_deg, 1);
timeCount = numel(timeSample_s);
completeGridPointCount = timeCount * nodeCount;
adaptiveIntervalMinimumGridPointCount = 10000;
if completeGridPointCount <= adaptiveIntervalMinimumGridPointCount
    queryPosition_deg = repmat(positions_deg, timeCount, 1);
    queryTime_s = repelem(timeSample_s, nodeCount, 1);
    occupied = queryAzElTimeObstacle(obstacleField, ...
        queryPosition_deg(:, 1), queryPosition_deg(:, 2), ...
        queryTime_s, struct("CollisionMode", "polygon", ...
        "TimePaddingSamples", options.CollisionTimePaddingSamples, ...
        "BoundaryIsOccupied", false));
    nodeSafeMask = ~reshape( ...
        logical(occupied), nodeCount, timeCount).';
    diagnostics = struct( ...
        "EventPointQueryCount", 0, ...
        "AdaptivePointQueryCount", completeGridPointCount, ...
        "ContinuousIntervalQueryCount", 0, ...
        "ContinuouslyClearIntervalCount", 0, ...
        "AvoidedPointQueryCount", 0, ...
        "CompleteGridPointCount", completeGridPointCount);
else
    nodeSafeMask = false(timeCount, nodeCount);
    sampleWasResolved = false(timeCount, nodeCount);
    [eventIsSample, eventSampleIndex] = ismember(eventTime_s, timeSample_s);
    if ~all(eventIsSample)
        error("buildAzElSafeIntervalRoadmap:MissingEventTime", ...
            "Every obstacle event time must be in the safe-interval grid.");
    end
    eventPosition_deg = repmat(positions_deg, numel(eventTime_s), 1);
    eventQueryTime_s = repelem(eventTime_s, nodeCount, 1);
    eventOccupied = queryAzElTimeObstacle(obstacleField, ...
        eventPosition_deg(:, 1), eventPosition_deg(:, 2), ...
        eventQueryTime_s, struct("CollisionMode", "polygon", ...
        "TimePaddingSamples", options.CollisionTimePaddingSamples, ...
        "BoundaryIsOccupied", false));
    eventSafeMask = ~reshape( ...
        logical(eventOccupied), nodeCount, numel(eventTime_s)).';
    nodeSafeMask(eventSampleIndex, :) = eventSafeMask;
    sampleWasResolved(eventSampleIndex, :) = true;
    continuousIntervalQueryCount = 0;
    continuouslyClearIntervalCount = 0;
    for eventIntervalIndex = 1:numel(eventTime_s) - 1
        firstTime_s = eventTime_s(eventIntervalIndex);
        finalTime_s = eventTime_s(eventIntervalIndex + 1);
        interiorSampleIndex = find(timeSample_s > firstTime_s & ...
            timeSample_s < finalTime_s);
        if isempty(interiorSampleIndex)
            continue;
        end
        for nodeIndex = 1:nodeCount
            if ~eventSafeMask(eventIntervalIndex, nodeIndex) || ...
                    ~eventSafeMask(eventIntervalIndex + 1, nodeIndex)
                continue;
            end
            continuousIntervalQueryCount = ...
                continuousIntervalQueryCount + 1;
            stationaryPosition_deg = repmat( ...
                positions_deg(nodeIndex, :), 2, 1);
            intervalOccupied = queryAzElTimedPathCollision( ...
                obstacleField, [firstTime_s; finalTime_s], ...
                stationaryPosition_deg, struct( ...
                "TimePaddingSamples", ...
                options.CollisionTimePaddingSamples, ...
                "BoundaryIsOccupied", false, ...
                "StopAtFirstCollision", true));
            if ~any(intervalOccupied)
                continuouslyClearIntervalCount = ...
                    continuouslyClearIntervalCount + 1;
                nodeSafeMask(interiorSampleIndex, nodeIndex) = true;
                sampleWasResolved(interiorSampleIndex, nodeIndex) = true;
            end
        end
    end
    [unresolvedTimeIndex, unresolvedNodeIndex] = find(~sampleWasResolved);
    if ~isempty(unresolvedTimeIndex)
        unresolvedPosition_deg = positions_deg(unresolvedNodeIndex, :);
        unresolvedTime_s = timeSample_s(unresolvedTimeIndex);
        unresolvedOccupied = queryAzElTimeObstacle(obstacleField, ...
            unresolvedPosition_deg(:, 1), ...
            unresolvedPosition_deg(:, 2), unresolvedTime_s, struct( ...
            "CollisionMode", "polygon", ...
            "TimePaddingSamples", ...
            options.CollisionTimePaddingSamples, ...
            "BoundaryIsOccupied", false));
        unresolvedLinearIndex = sub2ind( ...
            size(nodeSafeMask), unresolvedTimeIndex, ...
            unresolvedNodeIndex);
        nodeSafeMask(unresolvedLinearIndex) = ...
            ~logical(unresolvedOccupied(:));
    end
    diagnostics = struct( ...
        "EventPointQueryCount", numel(eventQueryTime_s), ...
        "AdaptivePointQueryCount", numel(unresolvedTimeIndex), ...
        "ContinuousIntervalQueryCount", ...
            continuousIntervalQueryCount, ...
        "ContinuouslyClearIntervalCount", ...
            continuouslyClearIntervalCount, ...
        "AvoidedPointQueryCount", ...
            nnz(sampleWasResolved) - numel(eventQueryTime_s), ...
        "CompleteGridPointCount", completeGridPointCount);
end
template = struct( ...
    "NodeIndex", 0, ...
    "StartTime_s", zeros(0, 1), ...
    "StopTime_s", zeros(0, 1), ...
    "IntervalCount", 0);
safeIntervals = repmat(template, nodeCount, 1);
for nodeIndex = 1:nodeCount
    safeSample = nodeSafeMask(:, nodeIndex);
    runTransition = diff([false; safeSample; false]);
    firstSafeSample = find(runTransition == 1);
    lastSafeSample = find(runTransition == -1) - 1;
    intervalStart_s = zeros(numel(firstSafeSample), 1);
    intervalStop_s = zeros(numel(lastSafeSample), 1);
    for intervalIndex = 1:numel(firstSafeSample)
        firstIndex = firstSafeSample(intervalIndex);
        lastIndex = lastSafeSample(intervalIndex);
        intervalStart_s(intervalIndex) = timeSample_s(firstIndex);
        intervalStop_s(intervalIndex) = timeSample_s(lastIndex);
        if firstIndex > 1
            intervalStart_s(intervalIndex) = refineOccupancyTransition( ...
                obstacleField, positions_deg(nodeIndex, :), ...
                timeSample_s(firstIndex - 1), timeSample_s(firstIndex), ...
                false, true, options);
        end
        if lastIndex < timeCount
            intervalStop_s(intervalIndex) = refineOccupancyTransition( ...
                obstacleField, positions_deg(nodeIndex, :), ...
                timeSample_s(lastIndex), timeSample_s(lastIndex + 1), ...
                true, false, options);
        end
    end
    hasDuration = intervalStop_s - intervalStart_s >= ...
        options.SafeIntervalTimeTolerance_s;
    safeIntervals(nodeIndex).NodeIndex = nodeIndex;
    safeIntervals(nodeIndex).StartTime_s = intervalStart_s(hasDuration);
    safeIntervals(nodeIndex).StopTime_s = intervalStop_s(hasDuration);
    safeIntervals(nodeIndex).IntervalCount = nnz(hasDuration);
end
end

function transitionTime_s = refineOccupancyTransition( ...
        obstacleField, position_deg, lowerTime_s, upperTime_s, ...
        lowerIsSafe, upperIsSafe, options)
% PURPOSE
%   - Locate one sampled safe/occupied transition by deterministic bisection.
for refinementIndex = 1:64
    if upperTime_s - lowerTime_s <= ...
            options.SafeIntervalTimeTolerance_s
        break;
    end
    midpointTime_s = 0.5 * (lowerTime_s + upperTime_s);
    midpointIsSafe = ~queryAzElTimeObstacle(obstacleField, ...
        position_deg(1), position_deg(2), midpointTime_s, struct( ...
        "CollisionMode", "polygon", ...
        "TimePaddingSamples", options.CollisionTimePaddingSamples, ...
        "BoundaryIsOccupied", false));
    if midpointIsSafe == lowerIsSafe
        lowerTime_s = midpointTime_s;
    else
        upperTime_s = midpointTime_s;
    end
end
if ~lowerIsSafe && upperIsSafe
    transitionTime_s = upperTime_s;
else
    transitionTime_s = lowerTime_s;
end
end

function [stateNodeIndex, stateIntervalIndex, startTime_s, ...
        stopTime_s, nodeStateIndex] = flattenSafeIntervals(safeIntervals)
% PURPOSE
%   - Create one SIPP state for each node and maximal safe interval.
nodeCount = numel(safeIntervals);
stateCount = sum([safeIntervals.IntervalCount]);
stateNodeIndex = zeros(stateCount, 1);
stateIntervalIndex = zeros(stateCount, 1);
startTime_s = zeros(stateCount, 1);
stopTime_s = zeros(stateCount, 1);
nodeStateIndex = cell(nodeCount, 1);
nextStateIndex = 1;
for nodeIndex = 1:nodeCount
    intervalCount = safeIntervals(nodeIndex).IntervalCount;
    stateRows = nextStateIndex:nextStateIndex + intervalCount - 1;
    nodeStateIndex{nodeIndex} = reshape(stateRows, [], 1);
    for intervalIndex = 1:intervalCount
        stateIndex = nextStateIndex;
        stateNodeIndex(stateIndex) = nodeIndex;
        stateIntervalIndex(stateIndex) = intervalIndex;
        startTime_s(stateIndex) = ...
            safeIntervals(nodeIndex).StartTime_s(intervalIndex);
        stopTime_s(stateIndex) = ...
            safeIntervals(nodeIndex).StopTime_s(intervalIndex);
        nextStateIndex = nextStateIndex + 1;
    end
end
end

function stateIndex = findStateAtTime( ...
        candidateStateIndex, startTime_s, stopTime_s, time_s, tolerance_s)
% PURPOSE
%   - Find the stable safe-interval state that contains a time.
stateIndex = 0;
for candidateIndex = reshape(candidateStateIndex, 1, [])
    containsTime = time_s >= startTime_s(candidateIndex) - tolerance_s && ...
        time_s <= stopTime_s(candidateIndex) + tolerance_s;
    if containsTime
        stateIndex = candidateIndex;
        return;
    end
end
end

function adjacency = spatialAdjacency(nodeCount, sourceIndex, targetIndex)
% PURPOSE
%   - Store neighbor node and edge identity for bounded SIPP expansion.
adjacency = cell(nodeCount, 1);
for edgeIndex = 1:numel(sourceIndex)
    adjacency{sourceIndex(edgeIndex)}(end + 1, :) = ...
        [targetIndex(edgeIndex), edgeIndex];
    adjacency{targetIndex(edgeIndex)}(end + 1, :) = ...
        [sourceIndex(edgeIndex), edgeIndex];
end
for nodeIndex = 1:nodeCount
    if ~isempty(adjacency{nodeIndex})
        adjacency{nodeIndex} = sortrows(adjacency{nodeIndex}, [1 2]);
    end
end
end

function [candidates, primarySearch, diagnostics] = ...
        generateDiverseCandidates(searchData)
% PURPOSE
%   - Run nominal SIPP, then bounded edge-exclusion and delay alternatives.
if ~isfield(searchData, "SharedSearchTimer") || ...
        isempty(searchData.SharedSearchTimer)
    searchData.SharedSearchTimer = tic;
end
if ~isfield(searchData, "SharedSearchWallTime_s") || ...
        isempty(searchData.SharedSearchWallTime_s)
    searchData.SharedSearchWallTime_s = ...
        searchData.Options.MaximumSippWallTime_s;
end
edgeCount = numel(searchData.SpatialEdgeSourceNodeIndex);
noExclusions = false(edgeCount, 1);
primarySearch = searchSafeIntervalGraph( ...
    searchData, noExclusions, searchData.InitialState.time_s);
candidateTemplate = emptyTimedCandidate();
candidates = repmat(candidateTemplate, 0, 1);
searchResults = repmat(emptySearchResult( ...
    numel(searchData.StateNodeIndex)), 0, 1);
searchResults(end + 1, 1) = primarySearch;
if primarySearch.Success
    candidates(end + 1, 1) = primarySearch.Candidate;
end

maximumAlternativeSearchCount = max( ...
    searchData.Options.MaximumSippCandidates * 4, 4);
alternativeSearchCount = 0;
for routeIndex = 1:numel(searchData.PreferredRouteNodeSequences)
    if alternativeSearchCount >= maximumAlternativeSearchCount
        break;
    end
    if numel(candidates) >= searchData.Options.MaximumSippCandidates || ...
            sharedSearchTimeExpired(searchData)
        break;
    end
    [routeExclusions, routeIsConnected] = routeOnlyExclusions( ...
        searchData, searchData.PreferredRouteNodeSequences{routeIndex});
    if ~routeIsConnected
        continue;
    end
    routeSearch = searchSafeIntervalGraph( ...
        searchData, routeExclusions, searchData.InitialState.time_s);
    searchResults(end + 1, 1) = routeSearch; %#ok<AGROW>
    alternativeSearchCount = alternativeSearchCount + 1;
    candidates = appendDistinctCandidate(candidates, routeSearch);
end
if primarySearch.Success
    excludedEdgeCandidates = unique( ...
        primarySearch.Candidate.EdgeIdSequence, "stable");
    for edgeListIndex = 1:numel(excludedEdgeCandidates)
        if alternativeSearchCount >= maximumAlternativeSearchCount
            break;
        end
        if numel(candidates) >= ...
                searchData.Options.MaximumSippCandidates || ...
                sharedSearchTimeExpired(searchData)
            break;
        end
        excludedEdgeMask = false(edgeCount, 1);
        excludedEdgeMask(excludedEdgeCandidates(edgeListIndex)) = true;
        alternative = searchSafeIntervalGraph( ...
            searchData, excludedEdgeMask, ...
            searchData.InitialState.time_s);
        searchResults(end + 1, 1) = alternative; %#ok<AGROW>
        alternativeSearchCount = alternativeSearchCount + 1;
        candidates = appendDistinctCandidate(candidates, alternative);
    end
end

if ~isempty(candidates)
    ranking = [[candidates.ArrivalTime_s].', ...
        [candidates.AngularLength_deg].', (1:numel(candidates)).'];
    [~, order] = sortrows(ranking, [1 2 3]);
    candidates = candidates(order);
    candidates = candidates(1:min(numel(candidates), ...
        searchData.Options.MaximumSippCandidates));
end
diagnostics = struct( ...
    "SearchRunCount", numel(searchResults), ...
    "AlternativeSearchCount", alternativeSearchCount, ...
    "SuccessfulSearchCount", nnz([searchResults.Success]), ...
    "DistinctCandidateCount", numel(candidates), ...
    "MaximumCandidateCount", ...
    searchData.Options.MaximumSippCandidates, ...
    "SharedTimeLimitReached", sharedSearchTimeExpired(searchData), ...
    "ElapsedSearchTime_s", toc(searchData.SharedSearchTimer), ...
    "SearchSummaries", searchSummary(searchResults));
end

function [excludedEdgeMask, isConnected] = ...
        routeOnlyExclusions(searchData, nodeSequence)
% PURPOSE
%   - Restrict one SIPP run to a visibility route's spatial edge chain.
edgeCount = numel(searchData.SpatialEdgeSourceNodeIndex);
allowedEdgeMask = false(edgeCount, 1);
isConnected = true;
for routeIndex = 1:numel(nodeSequence) - 1
    firstNodeIndex = min(nodeSequence(routeIndex:routeIndex + 1));
    secondNodeIndex = max(nodeSequence(routeIndex:routeIndex + 1));
    edgeIndex = find( ...
        searchData.SpatialEdgeSourceNodeIndex == firstNodeIndex & ...
        searchData.SpatialEdgeTargetNodeIndex == secondNodeIndex, 1);
    if isempty(edgeIndex)
        isConnected = false;
        excludedEdgeMask = true(edgeCount, 1);
        return;
    end
    allowedEdgeMask(edgeIndex) = true;
end
excludedEdgeMask = ~allowedEdgeMask;
end

function candidates = appendDistinctCandidate(candidates, search)
% PURPOSE
%   - Reject failed or duplicate SIPP route-and-wait signatures.
if ~search.Success
    return;
end
signature = search.Candidate.RouteSignature;
if ~isempty(candidates) && any([candidates.RouteSignature] == signature)
    return;
end
candidates(end + 1, 1) = search.Candidate;
end

function summaries = searchSummary(searchResults)
% PURPOSE
%   - Retain bounded evidence for every diversity search run.
template = struct( ...
    "Success", false, ...
    "TerminationReason", "notEvaluated", ...
    "ArrivalTime_s", Inf, ...
    "ExpandedStateCount", 0, ...
    "GeneratedTransitionCount", 0, ...
    "RouteSignature", "");
summaries = repmat(template, numel(searchResults), 1);
for searchIndex = 1:numel(searchResults)
    summaries(searchIndex).Success = searchResults(searchIndex).Success;
    summaries(searchIndex).TerminationReason = ...
        searchResults(searchIndex).TerminationReason;
    summaries(searchIndex).ExpandedStateCount = ...
        searchResults(searchIndex).ExpandedStateCount;
    summaries(searchIndex).GeneratedTransitionCount = ...
        searchResults(searchIndex).GeneratedTransitionCount;
    if searchResults(searchIndex).Success
        summaries(searchIndex).ArrivalTime_s = ...
            searchResults(searchIndex).Candidate.ArrivalTime_s;
        summaries(searchIndex).RouteSignature = ...
            searchResults(searchIndex).Candidate.RouteSignature;
    end
end
end

function search = searchSafeIntervalGraph( ...
        data, excludedEdgeMask, minimumStartDeparture_s)
% PURPOSE
%   - Search safe states with projected reachable-time intervals.
% Ali and Yakovlev's SIPP-IP correction propagates the complete time range
% that comes from predecessor waiting. Roadmap edges are rest-to-rest
% motion primitives, so each reached roadmap node permits a physical wait.
% The continuous moving-polygon traversal query is repository-specific.
% See citation.md.
stateCount = numel(data.StateNodeIndex);
search = emptySearchResult(stateCount);
searchTimer = tic;
arrivalTime_s = inf(stateCount, 1);
reachableIntervalStop_s = -inf(stateCount, 1);
angularCost_deg = inf(stateCount, 1);
parentStateIndex = zeros(stateCount, 1);
parentEdgeId = zeros(stateCount, 1);
parentDepartureTime_s = nan(stateCount, 1);
heuristicTime_s = zeros(stateCount, 1);
for stateIndex = 1:stateCount
    nodeIndex = data.StateNodeIndex(stateIndex);
    heuristicTime_s(stateIndex) = minimumTravelDuration( ...
        data.SpatialPosition_deg(nodeIndex, :), ...
        data.GoalState.position_deg, ...
        data.Options.MaximumVelocity_deg_s, ...
        data.Options.MaximumAcceleration_deg_s2, ...
        data.Options.MaximumJerk_deg_s3, ...
        data.Options.SafeIntervalTimeTolerance_s);
end
startStateIndex = data.StartStateIndex;
arrivalTime_s(startStateIndex) = data.InitialState.time_s;
reachableIntervalStop_s(startStateIndex) = data.InitialState.time_s;
if startStateAllowsWaiting(data)
    reachableIntervalStop_s(startStateIndex) = ...
        data.StateStopTime_s(startStateIndex);
end
angularCost_deg(startStateIndex) = 0;
openState = false(stateCount, 1);
closedState = false(stateCount, 1);
openState(startStateIndex) = true;
terminalStateIndex = 0;
acceptedSourceStateIndex = zeros(0, 1);
acceptedTargetStateIndex = zeros(0, 1);
rejectedSourceStateIndex = zeros(0, 1);
rejectedTargetStateIndex = zeros(0, 1);
rejectedReason = strings(0, 1);
generatedTransitionCount = 0;
acceptedTransitionCount = 0;
collisionRejectedTransitionCount = 0;
windowRejectedTransitionCount = 0;
traversalQueryCount = 0;
invariantTraversalSampleSkipCount = 0;
projectedIntervalCount = 0;
expandedStateCount = 0;
terminationReason = "openSetExhausted";
searchTimeLimitReached = false;

while any(openState)
    if expandedStateCount >= data.Options.MaximumSippExpansions
        terminationReason = "searchExpansionLimit";
        break;
    end
    if toc(searchTimer) >= data.Options.MaximumSippWallTime_s || ...
            sharedSearchTimeExpired(data)
        terminationReason = "searchTimeLimit";
        break;
    end
    openIndex = find(openState);
    priority_s = arrivalTime_s(openIndex) + ...
        heuristicTime_s(openIndex);
    ranking = [priority_s, arrivalTime_s(openIndex), ...
        angularCost_deg(openIndex), openIndex];
    [~, order] = sortrows(ranking, [1 2 3 4]);
    currentStateIndex = openIndex(order(1));
    openState(currentStateIndex) = false;
    if closedState(currentStateIndex)
        continue;
    end
    closedState(currentStateIndex) = true;
    expandedStateCount = expandedStateCount + 1;
    currentNodeIndex = data.StateNodeIndex(currentStateIndex);
    if currentNodeIndex == 2 && goalStateAcceptsArrival( ...
            currentStateIndex, arrivalTime_s(currentStateIndex), ...
            reachableIntervalStop_s(currentStateIndex), data)
        terminalStateIndex = currentStateIndex;
        terminationReason = "goalReached";
        break;
    end
    neighbors = data.Adjacency{currentNodeIndex};
    for neighborIndex = 1:size(neighbors, 1)
        targetNodeIndex = neighbors(neighborIndex, 1);
        edgeId = neighbors(neighborIndex, 2);
        if excludedEdgeMask(edgeId)
            continue;
        end
        earliestDeparture_s = data.InitialState.time_s;
        if currentStateIndex == startStateIndex
            earliestDeparture_s = minimumStartDeparture_s;
        end
        [transitions, queryCount, collisionRejectCount, ...
            invariantSkipCount, ...
            failedTargetStateIndex, rejectionReason] = ...
            projectFeasibleTraversals(data, currentStateIndex, ...
            targetNodeIndex, arrivalTime_s(currentStateIndex), ...
            reachableIntervalStop_s(currentStateIndex), ...
            earliestDeparture_s);
        if sharedSearchTimeExpired(data)
            terminationReason = "searchTimeLimit";
            searchTimeLimitReached = true;
            break;
        end
        traversalQueryCount = traversalQueryCount + queryCount;
        invariantTraversalSampleSkipCount = ...
            invariantTraversalSampleSkipCount + invariantSkipCount;
        collisionRejectedTransitionCount = ...
            collisionRejectedTransitionCount + collisionRejectCount;
        generatedTransitionCount = generatedTransitionCount + ...
            max(1, numel(transitions));
        projectedIntervalCount = projectedIntervalCount + ...
            numel(transitions);
        if isempty(transitions)
            windowRejectedTransitionCount = ...
                windowRejectedTransitionCount + 1;
            [rejectedSourceStateIndex, rejectedTargetStateIndex, ...
                rejectedReason] = retainDiagnosticTransition( ...
                rejectedSourceStateIndex, rejectedTargetStateIndex, ...
                rejectedReason, currentStateIndex, ...
                failedTargetStateIndex, rejectionReason, ...
                data.Options.MaximumSpaceTimeDiagnosticEdgeCount);
            continue;
        end
        for transitionIndex = 1:numel(transitions)
            transition = transitions(transitionIndex);
            acceptedTransitionCount = acceptedTransitionCount + 1;
            [acceptedSourceStateIndex, acceptedTargetStateIndex, ~] = ...
                retainDiagnosticTransition(acceptedSourceStateIndex, ...
                acceptedTargetStateIndex, strings(0, 1), ...
                currentStateIndex, transition.TargetStateIndex, "", ...
                data.Options.MaximumSpaceTimeDiagnosticEdgeCount);
            targetStateIndex = transition.TargetStateIndex;
            candidateAngularCost_deg = ...
                angularCost_deg(currentStateIndex) + ...
                data.SpatialEdgeLength_deg(edgeId);
            improvesArrival = transition.ArrivalTime_s < ...
                arrivalTime_s(targetStateIndex) - ...
                data.Options.SafeIntervalTimeTolerance_s;
            tiesArrival = abs(transition.ArrivalTime_s - ...
                arrivalTime_s(targetStateIndex)) <= ...
                data.Options.SafeIntervalTimeTolerance_s;
            improvesTie = tiesArrival && candidateAngularCost_deg < ...
                angularCost_deg(targetStateIndex) - 1e-12;
            improvesInterval = transition.ArrivalIntervalStop_s > ...
                reachableIntervalStop_s(targetStateIndex) + ...
                data.Options.SafeIntervalTimeTolerance_s;
            if improvesArrival || improvesTie
                arrivalTime_s(targetStateIndex) = ...
                    transition.ArrivalTime_s;
                angularCost_deg(targetStateIndex) = ...
                    candidateAngularCost_deg;
                parentStateIndex(targetStateIndex) = currentStateIndex;
                parentEdgeId(targetStateIndex) = edgeId;
                parentDepartureTime_s(targetStateIndex) = ...
                    transition.DepartureTime_s;
            end
            if improvesArrival || improvesTie || improvesInterval
                reachableIntervalStop_s(targetStateIndex) = max( ...
                    reachableIntervalStop_s(targetStateIndex), ...
                    transition.ArrivalIntervalStop_s);
                openState(targetStateIndex) = true;
                closedState(targetStateIndex) = false;
            end
        end
    end
    if searchTimeLimitReached
        break;
    end
end

if terminalStateIndex == 0
    reachedGoalState = find( ...
        data.StateNodeIndex == 2 & isfinite(arrivalTime_s));
    goalStateIsAccepted = false(size(reachedGoalState));
    for goalIndex = 1:numel(reachedGoalState)
        stateIndex = reachedGoalState(goalIndex);
        goalStateIsAccepted(goalIndex) = goalStateAcceptsArrival( ...
            stateIndex, arrivalTime_s(stateIndex), ...
            reachableIntervalStop_s(stateIndex), data);
    end
    reachedGoalState = reachedGoalState(goalStateIsAccepted);
    if ~isempty(reachedGoalState)
        goalRanking = [arrivalTime_s(reachedGoalState), ...
            angularCost_deg(reachedGoalState), reachedGoalState];
        [~, goalOrder] = sortrows(goalRanking, [1 2 3]);
        terminalStateIndex = reachedGoalState(goalOrder(1));
        if terminationReason == "searchTimeLimit"
            terminationReason = "goalReachedAtSearchLimit";
        else
            terminationReason = "goalReachedFromFrontier";
        end
    end
end

search.ParentStateIndex = parentStateIndex;
search.CostToCome_deg = angularCost_deg;
search.EarliestArrival_s = arrivalTime_s;
search.ReachableIntervalStop_s = reachableIntervalStop_s;
search.HeuristicTime_s = heuristicTime_s;
search.ExpandedStateIndex = find(closedState);
search.FrontierStateIndex = find(openState & isfinite(arrivalTime_s));
[search.BestPartialStateIndex, search.BestPartialDistance_deg] = ...
    bestPartialState(arrivalTime_s, data);
search.AcceptedEdgeSourceStateIndex = acceptedSourceStateIndex;
search.AcceptedEdgeTargetStateIndex = acceptedTargetStateIndex;
search.RejectedEdgeSourceStateIndex = rejectedSourceStateIndex;
search.RejectedEdgeTargetStateIndex = rejectedTargetStateIndex;
search.RejectedEdgeReason = rejectedReason;
search.GeneratedTransitionCount = generatedTransitionCount;
search.AcceptedTransitionCount = acceptedTransitionCount;
search.CollisionRejectedTransitionCount = ...
    collisionRejectedTransitionCount;
search.WindowRejectedTransitionCount = windowRejectedTransitionCount;
search.ExpandedStateCount = expandedStateCount;
search.TraversalQueryCount = traversalQueryCount;
search.InvariantTraversalSampleSkipCount = ...
    invariantTraversalSampleSkipCount;
search.ProjectedIntervalCount = projectedIntervalCount;
search.DiagnosticEdgeTraceWasLimited = ...
    acceptedTransitionCount > numel(acceptedSourceStateIndex) || ...
    windowRejectedTransitionCount > numel(rejectedSourceStateIndex);
search.TerminationReason = terminationReason;
if terminalStateIndex == 0
    search.Message = searchFailureMessage(terminationReason);
    return;
end
search.Success = true;
search.Message = "SIPP-IP reached the goal with collision-checked " + ...
    "interval propagation.";
search.Candidate = reconstructTimedCandidate( ...
    terminalStateIndex, arrivalTime_s, parentStateIndex, ...
    parentEdgeId, parentDepartureTime_s, data);
end

function accepted = goalStateAcceptsArrival( ...
        stateIndex, arrivalTime_s, reachableIntervalStop_s, data)
% PURPOSE
%   - Apply earliest or fixed terminal-time policy to a goal interval.
if data.Options.GoalTimeMode == "earliestarrival"
    accepted = arrivalTime_s <= data.GoalState.time_s + ...
        data.Options.SafeIntervalTimeTolerance_s;
    return;
end
accepted = arrivalTime_s <= data.GoalState.time_s + ...
    data.Options.SafeIntervalTimeTolerance_s && ...
    reachableIntervalStop_s >= data.GoalState.time_s - ...
    data.Options.SafeIntervalTimeTolerance_s && ...
    data.StateStartTime_s(stateIndex) <= data.GoalState.time_s && ...
    data.StateStopTime_s(stateIndex) >= data.GoalState.time_s;
end

function [transitions, queryCount, collisionRejectCount, ...
        invariantSkipCount, ...
        rejectedTargetStateIndex, rejectionReason] = ...
        projectFeasibleTraversals(data, sourceStateIndex, ...
        targetNodeIndex, arrivalAtSource_s, ...
        reachableIntervalStop_s, earliestDeparture_s)
% PURPOSE
%   - Project one reachable source interval into every target safe interval.
transitionTemplate = struct( ...
    "TargetStateIndex", 0, ...
    "DepartureTime_s", NaN, ...
    "ArrivalTime_s", NaN, ...
    "ArrivalIntervalStop_s", NaN);
transitions = repmat(transitionTemplate, 0, 1);
queryCount = 0;
collisionRejectCount = 0;
invariantSkipCount = 0;
rejectedTargetStateIndex = 0;
rejectionReason = "noTraversalWindow";
sourceNodeIndex = data.StateNodeIndex(sourceStateIndex);
sourcePosition_deg = data.SpatialPosition_deg(sourceNodeIndex, :);
targetPosition_deg = data.SpatialPosition_deg(targetNodeIndex, :);
duration_s = minimumTravelDuration(sourcePosition_deg, ...
    targetPosition_deg, data.Options.MaximumVelocity_deg_s, ...
    data.Options.MaximumAcceleration_deg_s2, ...
    data.Options.MaximumJerk_deg_s3, ...
    data.Options.SafeIntervalTimeTolerance_s);
sourceStart_s = data.StateStartTime_s(sourceStateIndex);
sourceStop_s = min(data.StateStopTime_s(sourceStateIndex), ...
    reachableIntervalStop_s);
baseDeparture_s = max([arrivalAtSource_s, sourceStart_s, ...
    earliestDeparture_s]);
targetStates = data.NodeStateIndex{targetNodeIndex};
for targetStateIndex = reshape(targetStates, 1, [])
    if rejectedTargetStateIndex == 0
        rejectedTargetStateIndex = targetStateIndex;
    end
    departureLower_s = max(baseDeparture_s, ...
        data.StateStartTime_s(targetStateIndex) - duration_s);
    departureUpper_s = min(sourceStop_s, ...
        data.StateStopTime_s(targetStateIndex) - duration_s);
    if departureUpper_s < departureLower_s - ...
            data.Options.SafeIntervalTimeTolerance_s
        continue;
    end
    [departure_s, found, localQueryCount, localRejectCount, ...
        localInvariantSkipCount] = ...
        firstCollisionFreeDeparture(data, sourcePosition_deg, ...
        targetPosition_deg, departureLower_s, departureUpper_s, ...
        duration_s);
    queryCount = queryCount + localQueryCount;
    collisionRejectCount = collisionRejectCount + localRejectCount;
    invariantSkipCount = invariantSkipCount + ...
        localInvariantSkipCount;
    if found
        candidateArrival_s = departure_s + duration_s;
        arrivalIntervalStop_s = candidateArrival_s;
        if data.Options.AllowSippWaiting
            % Every roadmap edge is a rest-to-rest primitive. The target
            % configuration can therefore use the rest of its safe interval.
            arrivalIntervalStop_s = ...
                data.StateStopTime_s(targetStateIndex);
        end
        transition = transitionTemplate;
        transition.TargetStateIndex = targetStateIndex;
        transition.DepartureTime_s = departure_s;
        transition.ArrivalTime_s = candidateArrival_s;
        transition.ArrivalIntervalStop_s = arrivalIntervalStop_s;
        transitions(end + 1, 1) = transition; %#ok<AGROW>
    elseif localRejectCount > 0
        rejectionReason = "collision";
    end
end
if ~isempty(transitions)
    ranking = [[transitions.ArrivalTime_s].', ...
        [transitions.TargetStateIndex].'];
    [~, order] = sortrows(ranking, [1 2]);
    transitions = transitions(order);
end
end

function [departure_s, found, queryCount, collisionRejectCount, ...
        invariantSkipCount] = ...
        firstCollisionFreeDeparture(data, sourcePosition_deg, ...
        targetPosition_deg, lowerTime_s, upperTime_s, duration_s)
% PURPOSE
%   - Scan then bisect the first feasible departure in one time window.
if data.Options.AllowSippWaiting
    candidateTime_s = data.TimeSample_s( ...
        data.TimeSample_s > lowerTime_s & ...
        data.TimeSample_s < upperTime_s);
    candidateTime_s = unique([lowerTime_s; candidateTime_s; upperTime_s]);
else
    candidateTime_s = lowerTime_s;
end
departure_s = NaN;
found = false;
queryCount = 0;
collisionRejectCount = 0;
invariantSkipCount = 0;
previousTime_s = NaN;
previousWasBlocked = false;
candidateIndex = 1;
while candidateIndex <= numel(candidateTime_s)
    if sharedSearchTimeExpired(data)
        return;
    end
    queryCount = queryCount + 1;
    isBlocked = traversalIsBlocked(data, sourcePosition_deg, ...
        targetPosition_deg, candidateTime_s(candidateIndex), duration_s);
    if ~isBlocked
        departure_s = candidateTime_s(candidateIndex);
        found = true;
        if previousWasBlocked
            departure_s = refineDepartureBoundary(data, ...
                sourcePosition_deg, targetPosition_deg, previousTime_s, ...
                departure_s, duration_s);
        end
        return;
    end
    collisionRejectCount = collisionRejectCount + 1;
    lastBlockedIndex = candidateIndex;
    nextCandidateIndex = candidateIndex + 1;
    while nextCandidateIndex <= numel(candidateTime_s) && ...
            packedGeometryIsInvariantOverWindow( ...
            data.ObstacleField, candidateTime_s(candidateIndex), ...
            candidateTime_s(nextCandidateIndex) + duration_s, ...
            data.Options.CollisionTimePaddingSamples)
        lastBlockedIndex = nextCandidateIndex;
        nextCandidateIndex = nextCandidateIndex + 1;
        invariantSkipCount = invariantSkipCount + 1;
        collisionRejectCount = collisionRejectCount + 1;
    end
    previousTime_s = candidateTime_s(lastBlockedIndex);
    previousWasBlocked = true;
    candidateIndex = nextCandidateIndex;
end
end

function isInvariant = packedGeometryIsInvariantOverWindow( ...
        obstacleField, firstTime_s, finalTime_s, timePaddingSamples)
% PURPOSE
%   - Prove that absolute time cannot change a traversal collision result.
% A rest-to-rest roadmap edge follows the same spatial curve for every
% departure. If every packed edge used over the union time window is exact
% and unchanged, one blocked query proves that all skipped departures are
% blocked. A moving, appearing, disappearing, or uncertain shape disables
% this reduction.
isInvariant = true;
for obstacleIndex = 1:obstacleField.ObstacleCount
    obstacle = obstacleField.Obstacles(obstacleIndex);
    obstacleTime_s = double(obstacle.TimeSeconds(:));
    if isempty(obstacleTime_s) || finalTime_s < obstacleTime_s(1) || ...
            firstTime_s > obstacleTime_s(end)
        continue;
    end
    if firstTime_s < obstacleTime_s(1) || ...
            finalTime_s > obstacleTime_s(end)
        isInvariant = false;
        return;
    end
    firstLowerIndex = find( ...
        obstacleTime_s <= firstTime_s, 1, "last");
    firstUpperIndex = find( ...
        obstacleTime_s >= firstTime_s, 1, "first");
    finalLowerIndex = find( ...
        obstacleTime_s <= finalTime_s, 1, "last");
    finalUpperIndex = find( ...
        obstacleTime_s >= finalTime_s, 1, "first");
    firstSliceIndex = max(1, min([ ...
        firstLowerIndex, firstUpperIndex, ...
        finalLowerIndex, finalUpperIndex]) - timePaddingSamples);
    finalSliceIndex = min(obstacle.SampleCount, max([ ...
        firstLowerIndex, firstUpperIndex, ...
        finalLowerIndex, finalUpperIndex]) + timePaddingSamples);
    for sliceIndex = firstSliceIndex + 1:finalSliceIndex
        if ~packedSlicesHaveEqualEdges( ...
                obstacle, firstSliceIndex, sliceIndex)
            isInvariant = false;
            return;
        end
    end
end
end

function areEqual = packedSlicesHaveEqualEdges( ...
        obstacle, firstSliceIndex, secondSliceIndex)
% PURPOSE
%   - Compare two packed edge sets without reconstructing edge matrices.
firstStartIndex = double(obstacle.EdgeOffsets(firstSliceIndex));
firstStopIndex = double( ...
    obstacle.EdgeOffsets(firstSliceIndex + 1)) - 1;
secondStartIndex = double(obstacle.EdgeOffsets(secondSliceIndex));
secondStopIndex = double( ...
    obstacle.EdgeOffsets(secondSliceIndex + 1)) - 1;
firstCount = firstStopIndex - firstStartIndex + 1;
secondCount = secondStopIndex - secondStartIndex + 1;
if firstCount ~= secondCount
    areEqual = false;
    return;
end
if firstCount == 0
    areEqual = true;
    return;
end
firstRows = firstStartIndex:firstStopIndex;
secondRows = secondStartIndex:secondStopIndex;
areEqual = isequal( ...
    obstacle.EdgeStartAzimuthDeg(firstRows), ...
    obstacle.EdgeStartAzimuthDeg(secondRows)) && isequal( ...
    obstacle.EdgeStartElevationDeg(firstRows), ...
    obstacle.EdgeStartElevationDeg(secondRows)) && isequal( ...
    obstacle.EdgeEndAzimuthDeg(firstRows), ...
    obstacle.EdgeEndAzimuthDeg(secondRows)) && isequal( ...
    obstacle.EdgeEndElevationDeg(firstRows), ...
    obstacle.EdgeEndElevationDeg(secondRows));
end

function expired = sharedSearchTimeExpired(data)
% PURPOSE
%   - Apply one wall-time limit across primary and diversity SIPP-IP runs.
expired = isfield(data, "SharedSearchTimer") && ...
    isfield(data, "SharedSearchWallTime_s") && ...
    toc(data.SharedSearchTimer) >= data.SharedSearchWallTime_s;
end

function isBlocked = traversalIsBlocked(data, sourcePosition_deg, ...
        targetPosition_deg, departureTime_s, duration_s)
% PURPOSE
%   - Check the complete moving chord with the public collision query.
collisionMask = queryAzElTimedPathCollision( ...
    data.ObstacleField, ...
    [departureTime_s; departureTime_s + duration_s], ...
    [sourcePosition_deg; targetPosition_deg], struct( ...
    "TimePaddingSamples", ...
    data.Options.CollisionTimePaddingSamples, ...
    "BoundaryIsOccupied", false, ...
    "StopAtFirstCollision", true));
isBlocked = any(collisionMask);
end

function departureTime_s = refineDepartureBoundary(data, ...
        sourcePosition_deg, targetPosition_deg, blockedTime_s, ...
        clearTime_s, duration_s)
% PURPOSE
%   - Refine an infeasible-to-feasible departure transition.
for refinementIndex = 1:64
    if clearTime_s - blockedTime_s <= ...
            data.Options.SafeIntervalTimeTolerance_s
        break;
    end
    midpointTime_s = 0.5 * (blockedTime_s + clearTime_s);
    if traversalIsBlocked(data, sourcePosition_deg, ...
            targetPosition_deg, midpointTime_s, duration_s)
        blockedTime_s = midpointTime_s;
    else
        clearTime_s = midpointTime_s;
    end
end
departureTime_s = clearTime_s;
end

function duration_s = minimumTravelDuration( ...
        sourcePosition_deg, targetPosition_deg, maximumVelocity_deg_s, ...
        maximumAcceleration_deg_s2, maximumJerk_deg_s3, ...
        timeTolerance_s)
% PURPOSE
%   - Compute a synchronized rest-to-rest S-curve edge duration.
displacement_deg = abs(targetPosition_deg - sourcePosition_deg);
axisDuration_s = zeros(1, 2);
for axisIndex = 1:2
    axisDuration_s(axisIndex) = restToRestAxisDuration( ...
        displacement_deg(axisIndex), ...
        maximumVelocity_deg_s(axisIndex), ...
        maximumAcceleration_deg_s2(axisIndex), ...
        maximumJerk_deg_s3(axisIndex));
end
duration_s = max(axisDuration_s);
if ~isfinite(duration_s) || duration_s <= 0
    duration_s = timeTolerance_s;
end
end

function duration_s = restToRestAxisDuration( ...
        displacement_deg, maximumVelocity_deg_s, ...
        maximumAcceleration_deg_s2, maximumJerk_deg_s3)
% PURPOSE
%   - Solve one symmetric jerk-limited rest-to-rest timing profile.
if displacement_deg <= 0
    duration_s = 0;
    return;
end
hasAccelerationLimit = isfinite(maximumAcceleration_deg_s2);
hasJerkLimit = isfinite(maximumJerk_deg_s3);
if ~hasJerkLimit && ~hasAccelerationLimit
    duration_s = displacement_deg / maximumVelocity_deg_s;
    return;
end
if ~hasJerkLimit
    triangularPeakVelocity_deg_s = sqrt( ...
        displacement_deg * maximumAcceleration_deg_s2);
    if triangularPeakVelocity_deg_s <= maximumVelocity_deg_s
        duration_s = 2 * sqrt( ...
            displacement_deg / maximumAcceleration_deg_s2);
    else
        duration_s = displacement_deg / maximumVelocity_deg_s + ...
            maximumVelocity_deg_s / maximumAcceleration_deg_s2;
    end
    return;
end
if ~hasAccelerationLimit
    triangularJerkTime_s = (displacement_deg / ...
        (2 * maximumJerk_deg_s3)) ^ (1 / 3);
    triangularPeakVelocity_deg_s = maximumJerk_deg_s3 * ...
        triangularJerkTime_s ^ 2;
    if triangularPeakVelocity_deg_s <= maximumVelocity_deg_s
        duration_s = 4 * triangularJerkTime_s;
    else
        jerkTime_s = sqrt( ...
            maximumVelocity_deg_s / maximumJerk_deg_s3);
        accelerationDistance_deg = 2 * maximumJerk_deg_s3 * ...
            jerkTime_s ^ 3;
        cruiseTime_s = max(0, ...
            (displacement_deg - accelerationDistance_deg) / ...
            maximumVelocity_deg_s);
        duration_s = 4 * jerkTime_s + cruiseTime_s;
    end
    return;
end

triangularJerkTime_s = (displacement_deg / ...
    (2 * maximumJerk_deg_s3)) ^ (1 / 3);
triangularPeakAcceleration_deg_s2 = maximumJerk_deg_s3 * ...
    triangularJerkTime_s;
triangularPeakVelocity_deg_s = maximumJerk_deg_s3 * ...
    triangularJerkTime_s ^ 2;
if triangularPeakAcceleration_deg_s2 <= ...
        maximumAcceleration_deg_s2 && ...
        triangularPeakVelocity_deg_s <= maximumVelocity_deg_s
    duration_s = 4 * triangularJerkTime_s;
    return;
end

velocityBeforeAcceleration = maximumVelocity_deg_s <= ...
    maximumAcceleration_deg_s2 ^ 2 / maximumJerk_deg_s3;
if velocityBeforeAcceleration
    jerkTime_s = sqrt( ...
        maximumVelocity_deg_s / maximumJerk_deg_s3);
    accelerationDistance_deg = 2 * maximumJerk_deg_s3 * ...
        jerkTime_s ^ 3;
    cruiseTime_s = max(0, ...
        (displacement_deg - accelerationDistance_deg) / ...
        maximumVelocity_deg_s);
    duration_s = 4 * jerkTime_s + cruiseTime_s;
    return;
end

jerkTime_s = maximumAcceleration_deg_s2 / maximumJerk_deg_s3;
constantAccelerationTime_s = 0.5 * ( ...
    -3 * jerkTime_s + sqrt(jerkTime_s ^ 2 + ...
    4 * displacement_deg / maximumAcceleration_deg_s2));
constantAccelerationTime_s = max(0, constantAccelerationTime_s);
peakVelocity_deg_s = maximumAcceleration_deg_s2 * ...
    (jerkTime_s + constantAccelerationTime_s);
if peakVelocity_deg_s <= maximumVelocity_deg_s
    duration_s = 4 * jerkTime_s + ...
        2 * constantAccelerationTime_s;
    return;
end

constantAccelerationTime_s = ...
    maximumVelocity_deg_s / maximumAcceleration_deg_s2 - jerkTime_s;
constantAccelerationTime_s = max(0, constantAccelerationTime_s);
accelerationDistance_deg = 2 * maximumAcceleration_deg_s2 * ( ...
    jerkTime_s ^ 2 + 1.5 * jerkTime_s * ...
    constantAccelerationTime_s + ...
    0.5 * constantAccelerationTime_s ^ 2);
cruiseTime_s = max(0, ...
    (displacement_deg - accelerationDistance_deg) / ...
    maximumVelocity_deg_s);
duration_s = 4 * jerkTime_s + ...
    2 * constantAccelerationTime_s + cruiseTime_s;
end

function allowsWaiting = startStateAllowsWaiting(data)
% PURPOSE
%   - Allow a start wait only when the supplied motion state is at rest.
allowsWaiting = data.Options.AllowSippWaiting;
if ~allowsWaiting
    return;
end
tolerance = data.Options.SafeIntervalTimeTolerance_s;
if isfield(data.InitialState, "velocity_deg_s")
    allowsWaiting = allowsWaiting && all( ...
        abs(data.InitialState.velocity_deg_s) <= tolerance);
end
if isfield(data.InitialState, "acceleration_deg_s2")
    allowsWaiting = allowsWaiting && all( ...
        abs(data.InitialState.acceleration_deg_s2) <= tolerance);
end
end

function [sourceStateIndex, targetStateIndex, reason] = ...
        retainDiagnosticTransition(sourceStateIndex, targetStateIndex, ...
        reason, newSourceStateIndex, newTargetStateIndex, newReason, ...
        maximumCount)
% PURPOSE
%   - Retain a bounded trace without changing search decisions.
if numel(sourceStateIndex) >= maximumCount
    return;
end
sourceStateIndex(end + 1, 1) = newSourceStateIndex;
targetStateIndex(end + 1, 1) = newTargetStateIndex;
if ~isempty(reason)
    reason(end + 1, 1) = newReason;
end
end

function [stateIndex, distance_deg] = bestPartialState(arrivalTime_s, data)
% PURPOSE
%   - Identify the reached safe-interval state nearest to the goal.
reachedStateIndex = find(isfinite(arrivalTime_s));
if isempty(reachedStateIndex)
    stateIndex = 0;
    distance_deg = Inf;
    return;
end
nodeIndex = data.StateNodeIndex(reachedStateIndex);
delta_deg = data.SpatialPosition_deg(nodeIndex, :) - ...
    data.GoalState.position_deg;
candidateDistance_deg = hypot(delta_deg(:, 1), delta_deg(:, 2));
ranking = [candidateDistance_deg, arrivalTime_s(reachedStateIndex), ...
    reachedStateIndex];
[~, order] = sortrows(ranking, [1 2 3]);
stateIndex = reachedStateIndex(order(1));
distance_deg = candidateDistance_deg(order(1));
end

function candidate = reconstructTimedCandidate( ...
        terminalStateIndex, arrivalTime_s, parentStateIndex, ...
        parentEdgeId, parentDepartureTime_s, data)
% PURPOSE
%   - Expand implicit safe waiting into a strict timed polyline.
stateSequence = terminalStateIndex;
while stateSequence(1) ~= data.StartStateIndex
    parentIndex = parentStateIndex(stateSequence(1));
    if parentIndex == 0
        error("buildAzElSafeIntervalRoadmap:CorruptParentTrace", ...
            "The selected SIPP parent trace does not reach the start.");
    end
    stateSequence = [parentIndex; stateSequence]; %#ok<AGROW>
end
spatialNodeSequence = data.StateNodeIndex(stateSequence);
safeIntervalSequence = data.StateIntervalIndex(stateSequence);
position_deg = data.SpatialPosition_deg(spatialNodeSequence(1), :);
time_s = data.InitialState.time_s;
edgeIdSequence = zeros(numel(stateSequence) - 1, 1);
edgeDepartureTime_s = zeros(numel(stateSequence) - 1, 1);
edgeArrivalTime_s = zeros(numel(stateSequence) - 1, 1);
waitDuration_s = 0;
waitEventCount = 0;
for transitionIndex = 2:numel(stateSequence)
    targetStateIndex = stateSequence(transitionIndex);
    sourcePosition_deg = position_deg(end, :);
    departureTime_s = parentDepartureTime_s(targetStateIndex);
    targetArrivalTime_s = arrivalTime_s(targetStateIndex);
    if departureTime_s > time_s(end) + ...
            data.Options.SafeIntervalTimeTolerance_s
        position_deg(end + 1, :) = sourcePosition_deg; %#ok<AGROW>
        time_s(end + 1, 1) = departureTime_s; %#ok<AGROW>
        waitDuration_s = waitDuration_s + ...
            departureTime_s - time_s(end - 1);
        waitEventCount = waitEventCount + 1;
    end
    targetNodeIndex = data.StateNodeIndex(targetStateIndex);
    position_deg(end + 1, :) = ...
        data.SpatialPosition_deg(targetNodeIndex, :); %#ok<AGROW>
    time_s(end + 1, 1) = targetArrivalTime_s; %#ok<AGROW>
    edgeIdSequence(transitionIndex - 1) = ...
        parentEdgeId(targetStateIndex);
    edgeDepartureTime_s(transitionIndex - 1) = departureTime_s;
    edgeArrivalTime_s(transitionIndex - 1) = targetArrivalTime_s;
end
if data.Options.GoalTimeMode == "fixedarrival" && ...
        data.GoalState.time_s > time_s(end) + ...
        data.Options.SafeIntervalTimeTolerance_s
    position_deg(end + 1, :) = position_deg(end, :);
    time_s(end + 1, 1) = data.GoalState.time_s;
    waitDuration_s = waitDuration_s + ...
        data.GoalState.time_s - time_s(end - 1);
    waitEventCount = waitEventCount + 1;
end
candidate = emptyTimedCandidate();
candidate.Success = true;
candidate.Message = "The SIPP-IP candidate reached the goal.";
candidate.TerminationReason = "goalReached";
candidate.StateIndex = stateSequence;
candidate.SpatialNodeIndex = spatialNodeSequence;
candidate.SafeIntervalIndex = safeIntervalSequence;
candidate.Position_deg = position_deg;
candidate.Time_s = time_s;
candidate.EdgeIdSequence = edgeIdSequence;
candidate.EdgeDepartureTime_s = edgeDepartureTime_s;
candidate.EdgeArrivalTime_s = edgeArrivalTime_s;
candidate.ArrivalTime_s = time_s(end);
candidate.AngularLength_deg = sum( ...
    data.SpatialEdgeLength_deg(edgeIdSequence));
candidate.WaitDuration_s = waitDuration_s;
candidate.WaitEventCount = waitEventCount;
candidate.RouteSignature = routeSignature(candidate, data.Options);
end

function signature = routeSignature(candidate, options)
% PURPOSE
%   - Distinguish spatial route order and meaningful waiting decisions.
nodeText = strjoin(string(candidate.SpatialNodeIndex.'), "-");
waitBucket = round(candidate.WaitDuration_s / ...
    options.SafeIntervalTimeTolerance_s);
signature = nodeText + "|wait=" + string(waitBucket);
end

function message = searchFailureMessage(terminationReason)
% PURPOSE
%   - Return actionable messages for expected search outcomes.
switch terminationReason
    case "searchExpansionLimit"
        message = "SIPP-IP reached the configured expansion limit.";
    case "searchTimeLimit"
        message = "SIPP-IP reached the configured wall-time limit.";
    otherwise
        message = "SIPP-IP exhausted all reachable time intervals.";
end
end

function search = emptySearchResult(stateCount)
% PURPOSE
%   - Define one stable SIPP-IP search record.
search = struct( ...
    "Success", false, ...
    "Message", "SIPP-IP was not evaluated.", ...
    "TerminationReason", "notEvaluated", ...
    "ParentStateIndex", zeros(stateCount, 1), ...
    "CostToCome_deg", inf(stateCount, 1), ...
    "EarliestArrival_s", inf(stateCount, 1), ...
    "ReachableIntervalStop_s", -inf(stateCount, 1), ...
    "HeuristicTime_s", zeros(stateCount, 1), ...
    "ExpandedStateIndex", zeros(0, 1), ...
    "FrontierStateIndex", zeros(0, 1), ...
    "BestPartialStateIndex", 0, ...
    "BestPartialDistance_deg", Inf, ...
    "AcceptedEdgeSourceStateIndex", zeros(0, 1), ...
    "AcceptedEdgeTargetStateIndex", zeros(0, 1), ...
    "RejectedEdgeSourceStateIndex", zeros(0, 1), ...
    "RejectedEdgeTargetStateIndex", zeros(0, 1), ...
    "RejectedEdgeReason", strings(0, 1), ...
    "GeneratedTransitionCount", 0, ...
    "AcceptedTransitionCount", 0, ...
    "CollisionRejectedTransitionCount", 0, ...
    "WindowRejectedTransitionCount", 0, ...
    "ExpandedStateCount", 0, ...
    "TraversalQueryCount", 0, ...
    "InvariantTraversalSampleSkipCount", 0, ...
    "ProjectedIntervalCount", 0, ...
    "DiagnosticEdgeTraceWasLimited", false, ...
    "Candidate", emptyTimedCandidate());
end

function candidate = emptyTimedCandidate()
% PURPOSE
%   - Define one stable diverse timed-candidate record.
candidate = struct( ...
    "Success", false, ...
    "Message", "The candidate was not evaluated.", ...
    "TerminationReason", "notEvaluated", ...
    "StateIndex", zeros(0, 1), ...
    "SpatialNodeIndex", zeros(0, 1), ...
    "SafeIntervalIndex", zeros(0, 1), ...
    "Position_deg", zeros(0, 2), ...
    "Time_s", zeros(0, 1), ...
    "EdgeIdSequence", zeros(0, 1), ...
    "EdgeDepartureTime_s", zeros(0, 1), ...
    "EdgeArrivalTime_s", zeros(0, 1), ...
    "ArrivalTime_s", Inf, ...
    "AngularLength_deg", Inf, ...
    "WaitDuration_s", 0, ...
    "WaitEventCount", 0, ...
    "RouteSignature", "");
end

function graph = emptySafeIntervalRoadmap()
% PURPOSE
%   - Define the stable graph schema for success and expected failure.
graph = struct( ...
    "Success", false, ...
    "Message", "The safe-interval roadmap was not evaluated.", ...
    "TerminationReason", "notEvaluated", ...
    "Representation", "safeIntervalVisibilityRoadmap", ...
    "SearchMethod", ...
    "safeIntervalPathPlanningWithIntervalProjection", ...
    "LayerTime_s", zeros(0, 1), ...
    "SpatialNodePosition_deg", zeros(0, 2), ...
    "SpatialEdgeSourceNodeIndex", zeros(0, 1), ...
    "SpatialEdgeTargetNodeIndex", zeros(0, 1), ...
    "SpatialEdgeLength_deg", zeros(0, 1), ...
    "PotentialSpatialEdgeCount", 0, ...
    "NodeAzElTime", zeros(0, 3), ...
    "NodeActiveMask", false(0, 0), ...
    "SafeIntervals", repmat(struct( ...
        "NodeIndex", 0, "StartTime_s", zeros(0, 1), ...
        "StopTime_s", zeros(0, 1), "IntervalCount", 0), 0, 1), ...
    "SafeIntervalStateNodeIndex", zeros(0, 1), ...
    "SafeIntervalStateIntervalIndex", zeros(0, 1), ...
    "SafeIntervalStateStartTime_s", zeros(0, 1), ...
    "SafeIntervalStateStopTime_s", zeros(0, 1), ...
    "SafeIntervalCount", 0, ...
    "SafeIntervalDiagnostics", struct( ...
        "EventPointQueryCount", 0, ...
        "AdaptivePointQueryCount", 0, ...
        "ContinuousIntervalQueryCount", 0, ...
        "ContinuouslyClearIntervalCount", 0, ...
        "AvoidedPointQueryCount", 0, ...
        "CompleteGridPointCount", 0), ...
    "ParentStateIndex", zeros(0, 1), ...
    "ParentNodeIndex", zeros(0, 1), ...
    "CostToCome_deg", zeros(0, 1), ...
    "EarliestArrival_s", zeros(0, 1), ...
    "ReachableIntervalStop_s", zeros(0, 1), ...
    "HeuristicTime_s", zeros(0, 1), ...
    "ExpandedStateIndex", zeros(0, 1), ...
    "ExpandedNodeIndex", zeros(0, 1), ...
    "FrontierStateIndex", zeros(0, 1), ...
    "FrontierNodeIndex", zeros(0, 1), ...
    "BestPartialStateIndex", 0, ...
    "BestPartialNodeIndex", 0, ...
    "BestPartialDistance_deg", Inf, ...
    "AcceptedEdgeSourceStateIndex", zeros(0, 1), ...
    "AcceptedEdgeTargetStateIndex", zeros(0, 1), ...
    "RejectedEdgeSourceStateIndex", zeros(0, 1), ...
    "RejectedEdgeTargetStateIndex", zeros(0, 1), ...
    "AcceptedEdgeSourceNodeIndex", zeros(0, 1), ...
    "AcceptedEdgeTargetNodeIndex", zeros(0, 1), ...
    "RejectedEdgeSourceNodeIndex", zeros(0, 1), ...
    "RejectedEdgeTargetNodeIndex", zeros(0, 1), ...
    "RejectedEdgeReason", strings(0, 1), ...
    "GeneratedTransitionCount", 0, ...
    "AcceptedTransitionCount", 0, ...
    "CollisionRejectedTransitionCount", 0, ...
    "WindowRejectedTransitionCount", 0, ...
    "GeneratedEdgeCount", 0, ...
    "AcceptedEdgeCount", 0, ...
    "CollisionRejectedEdgeCount", 0, ...
    "DynamicsRejectedEdgeCount", 0, ...
    "ExpandedStateCount", 0, ...
    "TraversalQueryCount", 0, ...
    "InvariantTraversalSampleSkipCount", 0, ...
    "ProjectedIntervalCount", 0, ...
    "AcceptedDiagnosticEdgeCount", 0, ...
    "RejectedDiagnosticEdgeCount", 0, ...
    "DiagnosticEdgeTraceWasLimited", false, ...
    "EvaluatedLayerCount", 0, ...
    "PathNodeIndex", zeros(0, 1), ...
    "PathSpatialNodeIndex", zeros(0, 1), ...
    "PathSafeIntervalIndex", zeros(0, 1), ...
    "PathPosition_deg", zeros(0, 2), ...
    "PathTime_s", zeros(0, 1), ...
    "PathCost_deg", Inf, ...
    "ArrivalTime_s", Inf, ...
    "PathEdgeCount", 0, ...
    "WaitEdgeCount", 0, ...
    "WaitDuration_s", 0, ...
    "DiverseCandidates", repmat(emptyTimedCandidate(), 0, 1), ...
    "DiverseCandidateCount", 0, ...
    "CandidateGenerationDiagnostics", struct(), ...
    "CandidateReductionDiagnostics", struct(), ...
    "Options", struct());
end
