function candidate = buildAzElStopWaypointMotion( ...
        obstacles, initialState, goalState, limits, options, seed)
%% Section 0: Header & Readme
% SYNTAX
%   candidate = azElInternal.buildAzElStopWaypointMotion()
%   candidate = azElInternal.buildAzElStopWaypointMotion( ...
%       obstacles, initialState, goalState, limits, options, seed)
%**************************************************************************
% PURPOSE
%   - Construct one deterministic finite-jerk motion on a geometric seed.
%   - Stop at each waypoint and certify the complete motion independently.
%**************************************************************************
% INPUTS
%   - obstacles (canonical protected obstacle struct array or [])
%       The independent validator checks the complete time-varying history.
%   - initialState, goalState (normalized scalar state structs)
%       position_deg, velocity_deg_s, and acceleration_deg_s2 are 1-by-2.
%       Only zero endpoint velocity and acceleration are supported.
%   - limits (normalized scalar limits struct)
%       maxVelocity_deg_s, maxAcceleration_deg_s2, and maxJerk_deg_s3 are
%       positive 1-by-2 limits.
%   - options (resolved scalar planner-options struct)
%       GoalTimeMode, SampleTime_s, workspace, and validation fields are
%       required. earliestArrival minimizes this fixed profile family.
%   - seed (scalar geometric-seed struct)
%       Index, Source, and N-by-2 position_deg are required. Consecutive
%       duplicate positions, which can represent a timed wait, are not
%       supported by this geometric construction.
%**************************************************************************
% OUTPUTS
%   - candidate (scalar struct)
%       Stable construction, polynomial, sampled-history, validation, and
%       analytic-certificate fields. Success is true only after independent
%       collision and constraint validation. Unsupported states return
%       Success = false without throwing. Invalid input contracts throw.
%**************************************************************************
% UNITS
%   - Position is degrees; time is seconds; derivatives use deg/s, deg/s^2,
%     and deg/s^3. Integrated squared jerk uses deg^2/s^5.
%**************************************************************************
if nargin == 0
    seed = struct("Index", 0, "Source", "");
    candidate = emptyCandidate(seed);
    return;
end
%% Section 1: Validate Inputs & Initialize The Stable Result
constructionTimer = tic;
[obstacles, goalTimeMode] = validateInputs( ...
    obstacles, initialState, goalState, limits, options, seed);
candidate = emptyCandidate(seed);
candidate.SeedCorridorBoundary_deg = optionalCorridorBoundary(seed);
stateTolerance = max(10 * options.ConstraintTolerance, 1e-7);
%% Section 2: Check The Supported Geometric Contract
endpointDerivative = [initialState.velocity_deg_s, ...
    initialState.acceleration_deg_s2, goalState.velocity_deg_s, ...
    goalState.acceleration_deg_s2];
if any(abs(endpointDerivative) > stateTolerance)
    candidate.Message = "The analytic seed motion supports only zero " + ...
        "initial and terminal velocity and acceleration.";
    candidate.TerminationReason = "unsupportedEndpointDerivatives";
    candidate.SolverDiagnostics.ElapsedTime_s = toc(constructionTimer);
    return;
end
hasMovingGoal = isfield(goalState, "targetTime_s") && ...
    ~isempty(goalState.targetTime_s);
if hasMovingGoal && goalTimeMode == "earliestArrival"
    candidate.Message = "Earliest arrival to a moving goal is not " + ...
        "supported by the analytic seed motion.";
    candidate.TerminationReason = "unsupportedMovingGoal";
    candidate.SolverDiagnostics.ElapsedTime_s = toc(constructionTimer);
    return;
end
goalPosition_deg = azElInternal.goalPositionAtTime( ...
    goalState, goalState.time_s);
seedPosition_deg = double(seed.position_deg);
endpointError_deg = max(abs([ ...
    seedPosition_deg(1, :) - initialState.position_deg, ...
    seedPosition_deg(end, :) - goalPosition_deg]));
if endpointError_deg > stateTolerance
    candidate.Message = "The geometric seed endpoints do not match the " + ...
        "requested initial and goal positions.";
    candidate.TerminationReason = "seedEndpointMismatch";
    candidate.SolverDiagnostics.ElapsedTime_s = toc(constructionTimer);
    return;
end
edgeDelta_deg = diff(seedPosition_deg, 1, 1);
edgeLength_deg = vecnorm(edgeDelta_deg, 2, 2);
zeroLengthTolerance_deg = max(1e-12, ...
    100 * eps(max(1, max(abs(seedPosition_deg), [], "all"))));
if any(edgeLength_deg <= zeroLengthTolerance_deg)
    candidate.Message = "The geometric seed contains a stationary " + ...
        "segment. Timed waits require a separate construction.";
    candidate.TerminationReason = "unsupportedStationarySeedSegment";
    candidate.SolverDiagnostics.ElapsedTime_s = toc(constructionTimer);
    return;
end
%% Section 3: Select One Certified Uniform Edge Duration
% Four equal polynomial records per edge tighten the validator's Bernstein
% bounds. Their dimensionless coefficient bounds are exact rational values
% for velocity and acceleration and the exact jerk maximum.
velocityCoefficient = 15 / 8;
accelerationCoefficient = 25 / 4;
jerkCoefficient = 60;
velocityDuration_s = max( ...
    velocityCoefficient * abs(edgeDelta_deg) ./ ...
    limits.maxVelocity_deg_s, [], 2);
accelerationDuration_s = sqrt(max( ...
    accelerationCoefficient * abs(edgeDelta_deg) ./ ...
    limits.maxAcceleration_deg_s2, [], 2));
jerkDuration_s = nthroot(max( ...
    jerkCoefficient * abs(edgeDelta_deg) ./ ...
    limits.maxJerk_deg_s3, [], 2), 3);
edgeMinimumDuration_s = max([velocityDuration_s, ...
    accelerationDuration_s, jerkDuration_s], [], 2);
minimumUniformEdgeDuration_s = max(edgeMinimumDuration_s);
edgeCount = size(edgeDelta_deg, 1);
availableDuration_s = goalState.time_s - initialState.time_s;
if availableDuration_s <= 0
    candidate.Message = "The goal time must be after the initial time.";
    candidate.TerminationReason = "timeWindowInfeasible";
    candidate.SolverDiagnostics.ElapsedTime_s = toc(constructionTimer);
    return;
end
if goalTimeMode == "fixedArrival"
    uniformEdgeDuration_s = availableDuration_s / edgeCount;
    if uniformEdgeDuration_s < minimumUniformEdgeDuration_s
        candidate.Message = "The fixed-arrival time is too short for the " + ...
            "certified stop-at-waypoint profile.";
        candidate.TerminationReason = "fixedArrivalInfeasible";
        candidate.AnalyticDiagnostics = analyticDiagnostics( ...
            seedPosition_deg, edgeMinimumDuration_s, ...
            minimumUniformEdgeDuration_s, uniformEdgeDuration_s, ...
            limits);
        candidate.SolverDiagnostics.ElapsedTime_s = toc(constructionTimer);
        return;
    end
else
    % This small scale prevents a roundoff-only limit failure at equality.
    durationRoundoffScale = 1 + 32 * eps;
    uniformEdgeDuration_s = ...
        durationRoundoffScale * minimumUniformEdgeDuration_s;
    motionDuration_s = edgeCount * uniformEdgeDuration_s;
    if motionDuration_s > availableDuration_s + stateTolerance
        candidate.Message = "The certified stop-at-waypoint profile does " + ...
            "not fit in the goal-time window.";
        candidate.TerminationReason = "timeWindowInfeasible";
        candidate.AnalyticDiagnostics = analyticDiagnostics( ...
            seedPosition_deg, edgeMinimumDuration_s, ...
            minimumUniformEdgeDuration_s, uniformEdgeDuration_s, ...
            limits);
        candidate.SolverDiagnostics.ElapsedTime_s = toc(constructionTimer);
        return;
    end
end
%% Section 4: Build And Sample The Exact Quintic Motion
finalTime_s = initialState.time_s + edgeCount * uniformEdgeDuration_s;
polynomial = buildPolynomial( ...
    seedPosition_deg, initialState.time_s, uniformEdgeDuration_s);
[time_s, position_deg, velocity_deg_s, acceleration_deg_s2, ...
    jerk_deg_s3] = samplePolynomial(polynomial, options.SampleTime_s);
candidate.ConstructionFeasible = true;
candidate.FinalTime_s = finalTime_s;
candidate.MotionDuration_s = finalTime_s - initialState.time_s;
candidate.IntegratedSquaredJerk_deg2_s5 = 720 * ...
    sum(edgeDelta_deg.^2, "all") / uniformEdgeDuration_s^5;
candidate.MaximumConstraintViolation = 0;
candidate.time_s = time_s;
candidate.position_deg = position_deg;
candidate.velocity_deg_s = velocity_deg_s;
candidate.acceleration_deg_s2 = acceleration_deg_s2;
candidate.jerk_deg_s3 = jerk_deg_s3;
candidate.Polynomial = polynomial;
if ~isempty(candidate.SeedCorridorBoundary_deg)
    % Equal edge durations make a uniform waypoint time law exact for this
    % stop profile. The validator still verifies original-obstacle
    % containment and complete polynomial separation before acceptance.
    corridorSeed = seed;
    corridorSeed.tau = linspace(0, 1, edgeCount + 1).';
    candidate.SeedCorridor = azElInternal.buildSeedCorridor( ...
        corridorSeed, polynomial.SegmentCount);
end
candidate.AnalyticDiagnostics = analyticDiagnostics( ...
    seedPosition_deg, edgeMinimumDuration_s, ...
    minimumUniformEdgeDuration_s, uniformEdgeDuration_s, limits);
%% Section 5: Independently Validate The Complete Motion
validation = validateAzElTrajectory( ...
    candidate, obstacles, initialState, goalState, limits, options);
candidate.Validation = validation;
candidate.Success = validation.Passed;
candidate.MaximumConstraintViolation = validationViolation( ...
    validation, candidate.AnalyticDiagnostics);
if validation.Passed
    candidate.Message = "The analytic stop-at-waypoint seed motion " + ...
        "passed independent validation.";
    candidate.TerminationReason = "seedMotionValidated";
elseif validation.DeadlineReached
    candidate.Message = "The planning deadline expired during " + ...
        "independent validation of the analytic seed motion.";
    candidate.TerminationReason = "validationTimeLimit";
elseif ~validation.CollisionFree
    candidate.Message = "The analytic seed motion was constructed, but " + ...
        "it did not pass continuous collision validation.";
    candidate.TerminationReason = "seedMotionCollision";
elseif ~validation.PositionWithinLimits
    candidate.Message = "The analytic seed motion leaves the configured " + ...
        "workspace.";
    candidate.TerminationReason = "seedMotionWorkspaceViolation";
elseif ~validation.VelocityWithinLimits || ...
        ~validation.AccelerationWithinLimits || ...
        ~validation.JerkWithinLimits || ~validation.DynamicsConsistent
    candidate.Message = "The analytic seed motion did not pass its " + ...
        "continuous kinematic certificate.";
    candidate.TerminationReason = "seedMotionCertificateFailure";
else
    candidate.Message = "The analytic seed motion did not pass " + ...
        "independent validation.";
    candidate.TerminationReason = "seedMotionValidationFailed";
end
candidate.SolverDiagnostics.ElapsedTime_s = toc(constructionTimer);
end
%% Section 6: Local Functions
function [obstacles, goalTimeMode] = validateInputs( ...
        obstacles, initialState, goalState, limits, options, seed)
% PURPOSE
%   - Validate the normalized internal contract before any construction.
obstacles = combineAzElObstacles(obstacles);
scalarStructNames = ["initialState", "goalState", "limits", ...
    "options", "seed"];
scalarStructValues = {initialState, goalState, limits, options, seed};
for valueIndex = 1:numel(scalarStructValues)
    if ~isstruct(scalarStructValues{valueIndex}) || ...
            ~isscalar(scalarStructValues{valueIndex})
        error("azElInternal:buildAzElStopWaypointMotion:InvalidStruct", ...
            "%s must be a scalar struct.", ...
            scalarStructNames(valueIndex));
    end
end
requireFields(initialState, ["time_s", "position_deg", ...
    "velocity_deg_s", "acceleration_deg_s2"], "initialState");
requireFields(goalState, ["time_s", "position_deg", ...
    "velocity_deg_s", "acceleration_deg_s2"], "goalState");
requireFields(limits, ["maxVelocity_deg_s", ...
    "maxAcceleration_deg_s2", "maxJerk_deg_s3"], "limits");
requireFields(options, ["GoalTimeMode", "SampleTime_s", ...
    "ConstraintTolerance", "CollisionClearanceTolerance_deg", ...
    "CollisionMinimumTimeStep_s", "AllowAzimuthWrapping", ...
    "AzimuthInterval_deg", "ElevationInterval_deg"], "options");
requireFields(seed, ["Index", "Source", "position_deg"], "seed");
validateattributes(initialState.time_s, {'numeric'}, ...
    {'real', 'finite', 'scalar'});
validateattributes(goalState.time_s, {'numeric'}, ...
    {'real', 'finite', 'scalar'});
stateNames = ["position_deg", "velocity_deg_s", ...
    "acceleration_deg_s2"];
for stateName = stateNames
    validateattributes(initialState.(stateName), {'numeric'}, ...
        {'real', 'finite', 'size', [1 2]});
    validateattributes(goalState.(stateName), {'numeric'}, ...
        {'real', 'finite', 'size', [1 2]});
end
limitNames = ["maxVelocity_deg_s", "maxAcceleration_deg_s2", ...
    "maxJerk_deg_s3"];
for limitName = limitNames
    validateattributes(limits.(limitName), {'numeric'}, ...
        {'real', 'finite', 'positive', 'size', [1 2]});
end
validateattributes(seed.position_deg, {'numeric'}, ...
    {'real', 'finite', '2d', 'ncols', 2});
if size(seed.position_deg, 1) < 2
    error("azElInternal:buildAzElStopWaypointMotion:InvalidSeed", ...
        "seed.position_deg must contain at least two rows.");
end
validateattributes(seed.Index, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'nonnegative'});
seedSource = string(seed.Source);
if ~isscalar(seedSource)
    error("azElInternal:buildAzElStopWaypointMotion:InvalidSeedSource", ...
        "seed.Source must be scalar text.");
end
goalTimeMode = string(options.GoalTimeMode);
if ~isscalar(goalTimeMode) || ~any( ...
        goalTimeMode == ["earliestArrival", "fixedArrival"])
    error("azElInternal:buildAzElStopWaypointMotion:InvalidGoalTimeMode", ...
        "options.GoalTimeMode must be earliestArrival or fixedArrival.");
end
validateattributes(options.SampleTime_s, {'numeric'}, ...
    {'real', 'finite', 'positive', 'scalar'});
end
function requireFields(record, fieldNames, inputName)
% PURPOSE
%   - Report all missing normalized fields at one contract boundary.
missingNames = fieldNames(~isfield(record, fieldNames));
if ~isempty(missingNames)
    error("azElInternal:buildAzElStopWaypointMotion:MissingFields", ...
        "%s is missing required fields: %s.", inputName, ...
        strjoin(missingNames, ", "));
end
end
function boundary_deg = optionalCorridorBoundary(seed)
% PURPOSE
%   - Preserve seed geometry for optional independent corridor certification.
if isfield(seed, "CorridorBoundary_deg") && ...
        ~isempty(seed.CorridorBoundary_deg)
    boundary_deg = double(seed.CorridorBoundary_deg);
else
    boundary_deg = zeros(0, 2);
end
end
function polynomial = buildPolynomial( ...
        waypoint_deg, initialTime_s, uniformEdgeDuration_s)
% PURPOSE
%   - Expand each rest-to-rest quintic into four equal-duration records.
subsegmentCountPerEdge = 4;
edgeCount = size(waypoint_deg, 1) - 1;
segmentCount = subsegmentCountPerEdge * edgeCount;
segmentDuration_s = uniformEdgeDuration_s / subsegmentCountPerEdge;
positionPower_deg = zeros(segmentCount, 2, 6);
velocityPower_deg_s = zeros(segmentCount, 2, 5);
accelerationPower_deg_s2 = zeros(segmentCount, 2, 4);
jerkPower_deg_s3 = zeros(segmentCount, 2, 3);
segmentIndex = 0;
for edgeIndex = 1:edgeCount
    edgeStart_deg = waypoint_deg(edgeIndex, :);
    edgeDelta_deg = waypoint_deg(edgeIndex + 1, :) - edgeStart_deg;
    for subsegmentIndex = 1:subsegmentCountPerEdge
        segmentIndex = segmentIndex + 1;
        intervalStart = ...
            (subsegmentIndex - 1) / subsegmentCountPerEdge;
        intervalScale = 1 / subsegmentCountPerEdge;
        profilePower = restrictedSmoothstepPower( ...
            intervalStart, intervalScale);
        positionPower = edgeDelta_deg.' .* profilePower;
        positionPower(:, 1) = positionPower(:, 1) + edgeStart_deg.';
        velocityPower = positionPower(:, 2:end) .* (1:5) / ...
            segmentDuration_s;
        accelerationPower = velocityPower(:, 2:end) .* (1:4) / ...
            segmentDuration_s;
        jerkPower = accelerationPower(:, 2:end) .* (1:3) / ...
            segmentDuration_s;
        positionPower_deg(segmentIndex, :, :) = positionPower;
        velocityPower_deg_s(segmentIndex, :, :) = velocityPower;
        accelerationPower_deg_s2(segmentIndex, :, :) = ...
            accelerationPower;
        jerkPower_deg_s3(segmentIndex, :, :) = jerkPower;
    end
end
segmentStartTime_s = initialTime_s + ...
    (0:segmentCount - 1).' * segmentDuration_s;
finalTime_s = initialTime_s + edgeCount * uniformEdgeDuration_s;
terminalPosition_deg = sum(positionPower, 2).';
terminalVelocity_deg_s = sum(velocityPower, 2).';
terminalAcceleration_deg_s2 = sum(accelerationPower, 2).';
polynomial = struct( ...
    "SegmentCount", segmentCount, ...
    "SegmentStartTime_s", segmentStartTime_s, ...
    "SegmentDuration_s", segmentDuration_s, ...
    "FinalTime_s", finalTime_s, ...
    "positionPower_deg", positionPower_deg, ...
    "velocityPower_deg_s", velocityPower_deg_s, ...
    "accelerationPower_deg_s2", accelerationPower_deg_s2, ...
    "jerkPower_deg_s3", jerkPower_deg_s3, ...
    "TerminalState", struct( ...
    "position_deg", terminalPosition_deg, ...
    "velocity_deg_s", terminalVelocity_deg_s, ...
    "acceleration_deg_s2", terminalAcceleration_deg_s2));
end
function restrictedPower = restrictedSmoothstepPower(startFraction, scale)
% PURPOSE
%   - Express q(startFraction + scale*u) in ascending local powers.
%   - Use the quintic blend identified in citation.md.
basePower = [0 0 0 10 -15 6];
degree = numel(basePower) - 1;
restrictedPower = zeros(1, degree + 1);
for basePowerIndex = 0:degree
    for localPowerIndex = 0:basePowerIndex
        restrictedPower(localPowerIndex + 1) = ...
            restrictedPower(localPowerIndex + 1) + ...
            basePower(basePowerIndex + 1) * ...
            nchoosek(basePowerIndex, localPowerIndex) * ...
            startFraction^(basePowerIndex - localPowerIndex) * ...
            scale^localPowerIndex;
    end
end
end
function [time_s, position_deg, velocity_deg_s, ...
        acceleration_deg_s2, jerk_deg_s3] = ...
        samplePolynomial(polynomial, sampleTime_s)
% PURPOSE
%   - Sample every polynomial knot and the requested uniform time grid.
initialTime_s = polynomial.SegmentStartTime_s(1);
uniformTime_s = (initialTime_s:sampleTime_s:polynomial.FinalTime_s).';
time_s = unique([uniformTime_s; polynomial.SegmentStartTime_s; ...
    polynomial.FinalTime_s]);
[time_s, position_deg, velocity_deg_s, acceleration_deg_s2, ...
    jerk_deg_s3] = azElInternal.evaluateAzElPolynomial( ...
    polynomial, time_s);
end
function diagnostics = analyticDiagnostics(waypoint_deg, ...
        edgeMinimumDuration_s, minimumUniformEdgeDuration_s, ...
        uniformEdgeDuration_s, limits)
% PURPOSE
%   - Report exact peaks and conservative Bernstein certificate peaks.
edgeDelta_deg = diff(waypoint_deg, 1, 1);
maximumAxisDisplacement_deg = max(abs(edgeDelta_deg), [], 1);
if isfinite(uniformEdgeDuration_s) && uniformEdgeDuration_s > 0
    exactPeakVelocity_deg_s = (15 / 8) * ...
        maximumAxisDisplacement_deg / uniformEdgeDuration_s;
    exactPeakAcceleration_deg_s2 = (10 * sqrt(3) / 3) * ...
        maximumAxisDisplacement_deg / uniformEdgeDuration_s^2;
    exactPeakJerk_deg_s3 = 60 * maximumAxisDisplacement_deg / ...
        uniformEdgeDuration_s^3;
    certifiedPeakVelocity_deg_s = exactPeakVelocity_deg_s;
    certifiedPeakAcceleration_deg_s2 = (25 / 4) * ...
        maximumAxisDisplacement_deg / uniformEdgeDuration_s^2;
    certifiedPeakJerk_deg_s3 = exactPeakJerk_deg_s3;
    maximumLimitRatio = max([ ...
        certifiedPeakVelocity_deg_s ./ limits.maxVelocity_deg_s, ...
        certifiedPeakAcceleration_deg_s2 ./ ...
        limits.maxAcceleration_deg_s2, ...
        certifiedPeakJerk_deg_s3 ./ limits.maxJerk_deg_s3]);
else
    exactPeakVelocity_deg_s = [NaN NaN];
    exactPeakAcceleration_deg_s2 = [NaN NaN];
    exactPeakJerk_deg_s3 = [NaN NaN];
    certifiedPeakVelocity_deg_s = [NaN NaN];
    certifiedPeakAcceleration_deg_s2 = [NaN NaN];
    certifiedPeakJerk_deg_s3 = [NaN NaN];
    maximumLimitRatio = NaN;
end
diagnostics = struct( ...
    "Profile", "restToRestQuintic", ...
    "PolynomialSegmentsPerEdge", 4, ...
    "WaypointCount", size(waypoint_deg, 1), ...
    "EdgeCount", size(edgeDelta_deg, 1), ...
    "EdgeMinimumDuration_s", edgeMinimumDuration_s, ...
    "MinimumUniformEdgeDuration_s", minimumUniformEdgeDuration_s, ...
    "UniformEdgeDuration_s", uniformEdgeDuration_s, ...
    "ExactPeakVelocity_deg_s", exactPeakVelocity_deg_s, ...
    "ExactPeakAcceleration_deg_s2", exactPeakAcceleration_deg_s2, ...
    "ExactPeakJerk_deg_s3", exactPeakJerk_deg_s3, ...
    "CertifiedPeakVelocity_deg_s", certifiedPeakVelocity_deg_s, ...
    "CertifiedPeakAcceleration_deg_s2", ...
    certifiedPeakAcceleration_deg_s2, ...
    "CertifiedPeakJerk_deg_s3", certifiedPeakJerk_deg_s3, ...
    "MaximumLimitRatio", maximumLimitRatio, ...
    "StopsAtEveryWaypoint", true, ...
    "PositionVelocityAccelerationContinuous", true, ...
    "JerkIsPiecewiseFinite", true);
end
function candidate = emptyCandidate(seed)
% PURPOSE
%   - Define one stable schema for success, failure, and unsupported exits.
candidate = struct( ...
    "Success", false, ...
    "ConstructionFeasible", false, ...
    "OptimizerFeasible", false, ...
    "Message", "The analytic seed motion was not constructed.", ...
    "TerminationReason", "notRun", ...
    "SeedIndex", seed.Index, ...
    "SeedSource", string(seed.Source), ...
    "FinalTime_s", NaN, ...
    "MotionDuration_s", NaN, ...
    "IntegratedSquaredJerk_deg2_s5", Inf, ...
    "MaximumConstraintViolation", Inf, ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2), ...
    "Polynomial", emptyPolynomial(), ...
    "ControlTau", zeros(0, 1), ...
    "ControlJerk_deg_s3", zeros(0, 2), ...
    "Corridor", struct([]), ...
    "SeedCorridorBoundary_deg", zeros(0, 2), ...
    "SeedCorridor", struct([]), ...
    "Validation", validateAzElTrajectory(), ...
    "AnalyticDiagnostics", emptyAnalyticDiagnostics(), ...
    "SolverDiagnostics", struct( ...
    "Method", "analyticRestToRestQuintic", ...
    "UsedOptimizer", false, "ElapsedTime_s", 0));
end
function polynomial = emptyPolynomial()
% PURPOSE
%   - Match the complete polynomial schema on construction failures.
polynomial = struct( ...
    "SegmentCount", 0, ...
    "SegmentStartTime_s", zeros(0, 1), ...
    "SegmentDuration_s", NaN, ...
    "FinalTime_s", NaN, ...
    "positionPower_deg", zeros(0, 2, 6), ...
    "velocityPower_deg_s", zeros(0, 2, 5), ...
    "accelerationPower_deg_s2", zeros(0, 2, 4), ...
    "jerkPower_deg_s3", zeros(0, 2, 3), ...
    "TerminalState", struct( ...
    "position_deg", [NaN NaN], ...
    "velocity_deg_s", [NaN NaN], ...
    "acceleration_deg_s2", [NaN NaN]));
end
function diagnostics = emptyAnalyticDiagnostics()
% PURPOSE
%   - Match analytic certificate fields before timing is available.
diagnostics = struct( ...
    "Profile", "restToRestQuintic", ...
    "PolynomialSegmentsPerEdge", 4, ...
    "WaypointCount", 0, "EdgeCount", 0, ...
    "EdgeMinimumDuration_s", zeros(0, 1), ...
    "MinimumUniformEdgeDuration_s", NaN, ...
    "UniformEdgeDuration_s", NaN, ...
    "ExactPeakVelocity_deg_s", [NaN NaN], ...
    "ExactPeakAcceleration_deg_s2", [NaN NaN], ...
    "ExactPeakJerk_deg_s3", [NaN NaN], ...
    "CertifiedPeakVelocity_deg_s", [NaN NaN], ...
    "CertifiedPeakAcceleration_deg_s2", [NaN NaN], ...
    "CertifiedPeakJerk_deg_s3", [NaN NaN], ...
    "MaximumLimitRatio", NaN, ...
    "StopsAtEveryWaypoint", true, ...
    "PositionVelocityAccelerationContinuous", true, ...
    "JerkIsPiecewiseFinite", true);
end
function violation = validationViolation(validation, diagnostics)
% PURPOSE
%   - Give invalid analytic candidates an honest partial-result ranking.
if validation.Passed
    violation = 0;
elseif validation.DeadlineReached || ~validation.CollisionResolved
    violation = Inf;
elseif ~validation.CollisionFree
    violation = max(1e-12, -validation.MinimumClearance_deg);
elseif isfinite(diagnostics.MaximumLimitRatio)
    violation = max(1e-12, diagnostics.MaximumLimitRatio - 1);
else
    violation = Inf;
end
end
