function data = createRpRetimerTrainingData(caseCount, seed)
%% Section 0: Header & Readme
% SYNTAX
%   data = azElInternal.createRpRetimerTrainingData(caseCount, seed)
%**************************************************************************
% PURPOSE
%   - Create reproducible corner-policy labels with the production retimer.
%**************************************************************************
% INPUTS
%   - caseCount (positive integer scalar)
%       Number of independent one-corner production problems.
%   - seed (nonnegative integer scalar)
%       Seed for all problem draws. The production retimer is deterministic.
%**************************************************************************
% OUTPUTS
%   - data (scalar struct)
%       Observations, selected radius fractions, durations, and source
%       problems. Invalid inputs or failed production labels throw an error.
%**************************************************************************
% UNITS
%   - Geometry uses degrees. Time uses seconds. Observations and radius
%     fractions are dimensionless.
%**************************************************************************

%% Section 1: Validate Inputs & Allocate The Data Set

validateattributes(caseCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'positive'});
validateattributes(seed, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'nonnegative'});
caseCount = double(caseCount);
seed = double(seed);
stream = RandStream("Threefry", "Seed", seed);
observation = zeros(10, caseCount);
bestRadiusFraction = zeros(1, caseCount);
minimumMotionDuration_s = zeros(1, caseCount);
problemTemplate = struct( ...
    "DeflectionAngle_rad", 0, ...
    "IncomingLength_deg", 0, ...
    "OutgoingLength_deg", 0, ...
    "IncomingDirection", zeros(1, 2), ...
    "OutgoingDirection", zeros(1, 2), ...
    "TurnRadius_deg", 0, ...
    "MaxVelocity_deg_s", zeros(1, 2), ...
    "MaxAcceleration_deg_s2", zeros(1, 2), ...
    "MaxJerk_deg_s3", zeros(1, 2));
problems = repmat(problemTemplate, 1, caseCount);

%% Section 2: Label General Corner Problems With Production Code

obstacleField = buildAzElTimeObstacleField([]);
options = planAzElMotion();
options.UseRpAgent = false;
options.CollisionTimePaddingSamples = 0;
for caseIndex = 1:caseCount
    problem = drawProblem(stream);
    route_deg = [ ...
        0 0; ...
        problem.IncomingLength_deg * problem.IncomingDirection; ...
        problem.IncomingLength_deg * problem.IncomingDirection + ...
            problem.OutgoingLength_deg * problem.OutgoingDirection];
    initialState = struct( ...
        "time_s", 0, ...
        "position_deg", route_deg(1, :), ...
        "velocity_deg_s", [0 0], ...
        "acceleration_deg_s2", [0 0]);
    goalState = struct( ...
        "time_s", 1e6, ...
        "position_deg", route_deg(end, :), ...
        "velocity_deg_s", [0 0], ...
        "acceleration_deg_s2", [0 0]);
    limits = struct( ...
        "maxVelocity_deg_s", problem.MaxVelocity_deg_s, ...
        "maxAcceleration_deg_s2", problem.MaxAcceleration_deg_s2, ...
        "maxJerk_deg_s3", problem.MaxJerk_deg_s3);
    options.TurnRadius_deg = problem.TurnRadius_deg;
    [smoothPath, timedPath] = azElInternal.retimeAzElSpatialPath( ...
        route_deg, obstacleField, initialState, goalState, limits, ...
        options, initialState.time_s);
    if ~timedPath.Success || numel(smoothPath.CornerDiagnostics) ~= 1
        error("createRpRetimerTrainingData:ProductionLabelFailed", ...
            "Production retiming failed for training case %d: %s", ...
            caseIndex, timedPath.Message);
    end
    observation(:, caseIndex) = ...
        azElInternal.rpRetimerObservation(problem);
    bestRadiusFraction(caseIndex) = ...
        smoothPath.CornerDiagnostics.RadiusScale;
    minimumMotionDuration_s(caseIndex) = ...
        timedPath.MinimumMotionDuration_s;
    problems(caseIndex) = problem;
end

%% Section 3: Assemble Reproducible Training Data

data = struct( ...
    "Format", "AzElRpRetimerTrainingData", ...
    "Version", 1, ...
    "TargetSource", "productionRetimerSelectedRadius", ...
    "Seed", seed, ...
    "CaseCount", caseCount, ...
    "Observation", observation, ...
    "BestRadiusFraction", bestRadiusFraction, ...
    "MinimumMotionDuration_s", minimumMotionDuration_s, ...
    "Problems", problems);
end

%% Section 4: Local Functions

function problem = drawProblem(stream)
% Draw one broad corner and motion-limit combination.
incomingLength_deg = 10^(log10(0.5) + rand(stream) * log10(120));
outgoingLength_deg = 10^(log10(0.5) + rand(stream) * log10(120));
deflectionAngle_rad = 0.15 + rand(stream) * (pi - 0.3);
incomingHeading_rad = -pi + 2 * pi * rand(stream);
turnSign = 2 * (rand(stream) >= 0.5) - 1;
outgoingHeading_rad = incomingHeading_rad + ...
    turnSign * deflectionAngle_rad;
velocityLimit_deg_s = 10 .^ ( ...
    log10(0.4) + rand(stream, 1, 2) * log10(20));
accelerationLimit_deg_s2 = 10 .^ ( ...
    log10(0.2) + rand(stream, 1, 2) * log10(50));
if rand(stream) < 0.5
    jerkLimit_deg_s3 = [Inf Inf];
else
    jerkLimit_deg_s3 = 10 .^ ( ...
        log10(0.5) + rand(stream, 1, 2) * log10(200));
end
problem = struct( ...
    "DeflectionAngle_rad", deflectionAngle_rad, ...
    "IncomingLength_deg", incomingLength_deg, ...
    "OutgoingLength_deg", outgoingLength_deg, ...
    "IncomingDirection", ...
        [cos(incomingHeading_rad), sin(incomingHeading_rad)], ...
    "OutgoingDirection", ...
        [cos(outgoingHeading_rad), sin(outgoingHeading_rad)], ...
    "TurnRadius_deg", ...
        10^(log10(0.05) + rand(stream) * log10(100)), ...
    "MaxVelocity_deg_s", velocityLimit_deg_s, ...
    "MaxAcceleration_deg_s2", accelerationLimit_deg_s2, ...
    "MaxJerk_deg_s3", jerkLimit_deg_s3);
end
