function result = emptyAzElPlannerResult(obstacles, initialState, ...
        goalState, limits, options, emptySeed, emptySeedSummary)
%% Section 0: Header & Readme
% SYNTAX
%   result = azElInternal.emptyAzElPlannerResult( ...
%       obstacles, initialState, goalState, limits, options, ...
%       emptySeed, emptySeedSummary)
%**************************************************************************
% PURPOSE
%   - Define one stable planner result for all success and failure exits.
%**************************************************************************
% INPUTS
%   - obstacles (canonical protected obstacle struct array)
%   - initialState, goalState (normalized scalar state structs)
%   - limits, options (normalized scalar planner-input structs)
%   - emptySeed, emptySeedSummary (scalar stable record templates)
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Empty public planner result with stable motion and diagnostics fields.
%**************************************************************************
% UNITS
%   - Position is degrees. Time is seconds. Derivatives use deg/s, deg/s^2,
%     and deg/s^3.
%**************************************************************************
%% Section 1: Build The Stable Result
emptyMotion = azElInternal.buildAzElStopWaypointMotion();
result = struct( ...
    "Success", false, ...
    "Message", "Planning was not completed.", ...
    "TerminationReason", "notRun", ...
    "Options", options, ...
    "Inputs", struct( ...
    "obstacles", obstacles, "initialState", initialState, ...
    "goalState", goalState, "limits", limits), ...
    "Seeds", repmat(emptySeed, 0, 1), ...
    "SeedSummaries", repmat(emptySeedSummary, 0, 1), ...
    "SelectedSeedIndex", 0, "SelectedMotionSource", "", ...
    "SelectedSeed_deg", zeros(0, 2), "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), "jerk_deg_s3", zeros(0, 2), ...
    "Polynomial", emptyMotion.Polynomial, ...
    "SeedCorridorBoundary_deg", zeros(0, 2), ...
    "SeedCorridor", struct([]), ...
    "Validation", validateAzElTrajectory(), ...
    "ArrivalTime_s", NaN, "TrajectoryDuration_s", NaN, ...
    "GoalHorizon_s", goalState.time_s - initialState.time_s, ...
    "FirstValidatedMotionTime_s", NaN, ...
    "SearchDiagnostics", struct( ...
    "Grid", struct(), ...
    "SeedSummaries", repmat(emptySeedSummary, 0, 1), ...
    "BestPartialSeedIndex", 0, "MeshRefinementPassCount", 0, ...
    "ValidatedCandidateCount", 0, ...
    "FirstValidatedMotionTime_s", NaN, ...
    "SeedGenerationElapsedTime_s", 0, ...
    "FirstMotionElapsedTime_s", 0, "Hs3ElapsedTime_s", 0, ...
    "AttemptedSeedCount", 0, "TerminationReason", "notRun"), ...
    "ElapsedPlanningTime_s", 0, ...
    "RandomSeed", options.RandomSeed, ...
    "OptimalityStatement", ...
    "No motion was validated from the bounded candidate work.");
end
