function candidate = emptyAzElHs3Candidate()
% PURPOSE
%   - Define the stable result for one direct-collocation seed.
candidate = struct( ...
    "Success", false, ...
    "Message", "Direct collocation was not evaluated.", ...
    "TerminationReason", "notEvaluated", ...
    "ArrivalTime_s", Inf, ...
    "MotionDuration_s", Inf, ...
    "StageOneMinimumArrivalTime_s", Inf, ...
    "FinalTieBreakArrivalTime_s", Inf, ...
    "AllowedTimeTieTolerance_s", NaN, ...
    "StageOneIntegratedSquaredJerk", Inf, ...
    "StageOneSolutionSource", "", ...
    "IntegratedSquaredJerk", Inf, ...
    "SeedRoute_deg", zeros(0, 2), ...
    "SeedRouteCost_deg", Inf, ...
    "TimedSeedLawUsed", false, ...
    "SeedRouteTimeFraction", zeros(0, 1), ...
    "SeedRouteProgress", zeros(0, 1), ...
    "InitialGuessProjectionSucceeded", false, ...
    "InitialGuessMessage", "", ...
    "InitialGuessMaximumHs3Defect", Inf, ...
    "InitialGuessInitialStateError", inf(1, 6), ...
    "InitialGuessTerminalStateError", inf(1, 6), ...
    "InitialGuessMaximumBoundAdjustment", Inf, ...
    "InitialGuessCollisionFree", false, ...
    "InitialGuessValidationPassed", false, ...
    "SelectedSolutionSource", "", ...
    "MeshPassCount", 0, ...
    "SegmentCountHistory", zeros(0, 1), ...
    "MeshObjectiveHistory", zeros(0, 1), ...
    "MeshObjectiveChangeHistory", zeros(0, 1), ...
    "MeshRefinementConverged", false, ...
    "MeshRefinementConvergenceTolerance", NaN, ...
    "SolverExitFlag", NaN, ...
    "SolverMessage", "", ...
    "SolverExitFlagHistory", zeros(0, 1), ...
    "SolverMessageHistory", strings(0, 1), ...
    "SolverTimeLimitReached", false, ...
    "SolverTimeLimitReachedHistory", false(0, 1), ...
    "SolverMeshPassHistory", zeros(0, 1), ...
    "SolverCorridorPassHistory", zeros(0, 1), ...
    "SolverStageHistory", strings(0, 1), ...
    "SolverIterationCount", 0, ...
    "SolverFunctionEvaluationCount", 0, ...
    "MaximumCollocationDefect", Inf, ...
    "MaximumNlpInequalityViolation", Inf, ...
    "MaximumDynamicsDefect", Inf, ...
    "MaximumVelocity_deg_s", [Inf Inf], ...
    "MaximumAcceleration_deg_s2", [Inf Inf], ...
    "MaximumJerk_deg_s3", [Inf Inf], ...
    "MaximumVelocityViolation_deg_s", [Inf Inf], ...
    "MaximumAccelerationViolation_deg_s2", [Inf Inf], ...
    "MaximumJerkViolation_deg_s3", [Inf Inf], ...
    "MinimumClearance_deg", NaN, ...
    "ClearanceSampleCount", 0, ...
    "CorridorRelinearizationCount", 0, ...
    "CollisionValidationPerformed", false, ...
    "CollisionFree", false, ...
    "CollisionValidationPassed", false, ...
    "BufferedChordQueryClear", false, ...
    "CollisionSafetyProven", false, ...
    "CollisionClearanceDiagnostics", ...
    azElInternal.emptyCollisionClearanceDiagnostics(), ...
    "Trajectory", azElInternal.reconstructAzElHs3Trajectory(), ...
    "Validation", azElInternal.emptyTrajectoryValidation(), ...
    "MeshTau", zeros(0, 1), ...
    "MaximumDefectHistory", zeros(0, 1), ...
    "FixedArrivalFeasibilityStagePassed", false, ...
    "FixedArrivalFeasibilityIntegratedSquaredJerk", NaN, ...
    "FixedArrivalJerkRefinementAttempted", false, ...
    "FixedArrivalJerkRefinementAccepted", false, ...
    "FixedArrivalJerkRefinementExitFlag", NaN, ...
    "FixedArrivalJerkRefinementMessage", "", ...
    "FixedArrivalRefinedIntegratedSquaredJerk", NaN, ...
    "FixedArrivalJerkRefinementTimeLimitReached", false, ...
    "TieBreakAttempted", false, ...
    "TieBreakAccepted", false, ...
    "TieBreakExitFlag", NaN, ...
    "TieBreakMessage", "", ...
    "TieBreakIntegratedSquaredJerk", NaN, ...
    "TimeBudgetReached", false, ...
    "ElapsedTime_s", 0);
end
