function diagnostics = emptyCollisionClearanceDiagnostics()
%% Section 0: Header & Readme
% SYNTAX
%   diagnostics = azElInternal.emptyCollisionClearanceDiagnostics()
%**************************************************************************
% PURPOSE
%   - Define the stable empty schema for conservative clearance proofs.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - diagnostics (scalar struct)
%       Stable proof fields used before a timed trajectory is available.
%**************************************************************************
% UNITS
%   - MinimumProvenLowerBound_deg is degrees. Counts are dimensionless.
%**************************************************************************

%% Section 1: Assemble Stable Diagnostics

diagnostics = struct( ...
    "ProvenClear", false, ...
    "UnresolvedPathSegmentMask", false(0, 1), ...
    "UnresolvedPathSegmentCount", 0, ...
    "TopologyMismatchIntervalCount", 0, ...
    "EvaluatedEdgeIntervalCount", 0, ...
    "BroadPhaseRejectedEdgeIntervalCount", 0, ...
    "SubdivisionBoxCount", 0, ...
    "MaximumDepthReached", 0, ...
    "MaximumSubdivisionDepth", 18, ...
    "MaximumBoxesPerEdge", 20000, ...
    "MinimumProvenLowerBound_deg", NaN);
end
