function [position_deg, firstDerivative, secondDerivative, ...
        thirdDerivative] = evaluateAzElQuintic( ...
        controlPoints_deg, parameter)
%% Section 0: Header & Readme
% SYNTAX
%   [position_deg, firstDerivative, secondDerivative, thirdDerivative] = ...
%       azElInternal.evaluateAzElQuintic( ...
%       controlPoints_deg, parameter)
%**************************************************************************
% PURPOSE
%   - Evaluate one quintic Bezier curve and its first three parameter
%     derivatives from a single maintained implementation.
%**************************************************************************
% INPUTS
%   - controlPoints_deg (6-by-2 finite numeric)
%       Ordered quintic Bezier control points.
%   - parameter (numeric vector)
%       Dimensionless values in the closed interval [0, 1].
%**************************************************************************
% OUTPUTS
%   - position_deg, firstDerivative, secondDerivative, thirdDerivative
%       N-by-2 degree-based parameter derivatives.
%**************************************************************************
% UNITS
%   - Parameter is dimensionless and all outputs are degree-based.
%**************************************************************************

%% Section 1: Validate Inputs

validateattributes(controlPoints_deg, {'numeric'}, ...
    {'real', 'finite', 'size', [6 2]});
validateattributes(parameter, {'numeric'}, ...
    {'real', 'finite', 'vector', '>=', 0, '<=', 1});

%% Section 2: Evaluate Bernstein Derivatives

parameter = double(parameter(:));
oneMinus = 1 - parameter;
position_deg = [ ...
    oneMinus.^5, ...
    5 * oneMinus.^4 .* parameter, ...
    10 * oneMinus.^3 .* parameter.^2, ...
    10 * oneMinus.^2 .* parameter.^3, ...
    5 * oneMinus .* parameter.^4, ...
    parameter.^5] * controlPoints_deg;
firstDerivative = [ ...
    oneMinus.^4, ...
    4 * oneMinus.^3 .* parameter, ...
    6 * oneMinus.^2 .* parameter.^2, ...
    4 * oneMinus .* parameter.^3, ...
    parameter.^4] * (5 * diff(controlPoints_deg, 1, 1));
secondDerivative = [ ...
    oneMinus.^3, ...
    3 * oneMinus.^2 .* parameter, ...
    3 * oneMinus .* parameter.^2, ...
    parameter.^3] * (20 * diff(controlPoints_deg, 2, 1));
thirdDerivative = [ ...
    oneMinus.^2, ...
    2 * oneMinus .* parameter, ...
    parameter.^2] * (60 * diff(controlPoints_deg, 3, 1));
end
