function [control, isFeasible, message, timeBudgetReached, ...
        failureReason] = fitAzElHs3InitialControl( ...
        stateResponse, fitPositionResponse, continuousStateResponse, ...
        continuousJerkResponse, freeSampleState, freeContinuousState, ...
        freeFitPosition_deg, targetFitPosition_deg, goalState, ...
        baseControl, limits, options, corridor, obstacleField, ...
        initialTime_s, finalTime_s, candidateTimer, remainingTime_s)
%% Section 0: Header & Readme
% SYNTAX
%   [control, isFeasible, message, timeBudgetReached, ...
%       failureReason] = azElInternal.fitAzElHs3InitialControl( ...
%       stateResponse, fitPositionResponse, continuousStateResponse, ...
%       continuousJerkResponse, freeSampleState, freeContinuousState, ...
%       freeFitPosition_deg, targetFitPosition_deg, goalState, ...
%       baseControl, limits, options, corridor, obstacleField, ...
%       initialTime_s, finalTime_s, candidateTimer, remainingTime_s)
%**************************************************************************
% PURPOSE
%   - Fit both HS-3 jerk axes to a route with shared obstacle separators.
%   - Verify the linear solver result before it becomes a warm start.
%**************************************************************************
% INPUTS
%   - stateResponse (P-by-C numeric matrix)
%       Affine sampled-state response for one unit jerk axis.
%   - fitPositionResponse (Q-by-C numeric matrix)
%       Affine route-fit position response for one unit jerk axis.
%   - continuousStateResponse (R-by-C numeric matrix)
%       Affine interior Bernstein-state response.
%   - continuousJerkResponse (S-by-C numeric matrix)
%       Affine interior jerk response.
%   - freeSampleState (T-by-6 numeric matrix)
%       Sampled two-axis state without control.
%   - freeContinuousState (U-by-6 numeric matrix)
%       Interior two-axis Bernstein state without control.
%   - freeFitPosition_deg, targetFitPosition_deg (Q-by-2 matrices)
%       Free and requested route-fit positions.
%   - goalState (1-by-6 numeric row)
%       Terminal position, velocity, and acceleration state.
%   - baseControl (C-by-2 numeric matrix)
%       Endpoint-feasible control used as the solver start.
%   - limits, options, corridor, obstacleField (scalar structs)
%       Resolved physical limits, planner controls, frozen separators, and
%       canonical obstacle geometry.
%   - initialTime_s, finalTime_s (finite numeric scalars)
%       Absolute motion interval.
%   - candidateTimer (tic timer token)
%       Timer shared with the candidate solve.
%   - remainingTime_s (nonnegative numeric scalar)
%       Candidate time budget.
%**************************************************************************
% OUTPUTS
%   - control (C-by-2 numeric matrix)
%       Time-ordered azimuth and elevation jerk ordinates.
%   - isFeasible, timeBudgetReached (logical scalars)
%       Verified feasibility and time-limit status.
%   - message, failureReason (string scalars)
%       Actionable status and machine-readable failure reason.
%**************************************************************************
% UNITS
%   - Position is degrees. Time is seconds. Velocity, acceleration, and
%     jerk use degrees per second, second squared, and second cubed.
%**************************************************************************

%% Section 1: Assemble The Two-Axis Linear Model

failureReason = "initialGuessInfeasible";
controlCount = size(stateResponse, 2);
axisModel = cell(2, 1);
for axisIndex = 1:2
    stateColumn = [axisIndex, axisIndex + 2, axisIndex + 4];
    positionBounds_deg = options.ElevationInterval_deg;
    if axisIndex == 1 && options.AllowAzimuthWrapping
        positionBounds_deg = [-Inf Inf];
    elseif axisIndex == 1
        positionBounds_deg = options.AzimuthInterval_deg;
    end
    axisModel{axisIndex} = axisSeedLinearModel( ...
        stateResponse, fitPositionResponse, continuousStateResponse, ...
        continuousJerkResponse, freeSampleState(:, stateColumn), ...
        freeContinuousState(:, stateColumn), ...
        freeFitPosition_deg(:, axisIndex), ...
        targetFitPosition_deg(:, axisIndex), goalState(stateColumn), ...
        baseControl(:, axisIndex), limits.maxJerk_deg_s3(axisIndex), ...
        limits.maxVelocity_deg_s(axisIndex), ...
        limits.maxAcceleration_deg_s2(axisIndex), positionBounds_deg);
end
objectiveMatrix = blkdiag( ...
    axisModel{1}.ObjectiveMatrix, axisModel{2}.ObjectiveMatrix);
objectiveTarget = [axisModel{1}.ObjectiveTarget; ...
    axisModel{2}.ObjectiveTarget];
inequalityMatrix = blkdiag( ...
    axisModel{1}.InequalityMatrix, axisModel{2}.InequalityMatrix);
inequalityTarget = [axisModel{1}.InequalityTarget; ...
    axisModel{2}.InequalityTarget];
equalityMatrix = blkdiag( ...
    axisModel{1}.EqualityMatrix, axisModel{2}.EqualityMatrix);
equalityTarget = [axisModel{1}.EqualityTarget; ...
    axisModel{2}.EqualityTarget];
motionInequalityMatrix = inequalityMatrix;
motionInequalityTarget = inequalityTarget;
continuousPositionCount = size(freeContinuousState, 1);
continuousPositionResponse = continuousStateResponse( ...
    1:continuousPositionCount, :);
[corridorMatrix, corridorTarget] = linearSeedCorridorConstraints( ...
    corridor, obstacleField, initialTime_s, finalTime_s, ...
    freeFitPosition_deg, fitPositionResponse, ...
    freeContinuousState(:, 1:2), continuousPositionResponse, ...
    limits.maxJerk_deg_s3, options.ObstacleConstraintTolerance_deg);
inequalityMatrix = [inequalityMatrix; corridorMatrix];
inequalityTarget = [inequalityTarget; corridorTarget];
initialControl = [axisModel{1}.InitialControl; ...
    axisModel{2}.InitialControl];
variableCount = 2 * controlCount;
lowerBound = -ones(variableCount, 1);
upperBound = ones(variableCount, 1);
verificationTolerance = max(1e-8, ...
    0.1 * options.NlpConstraintTolerance);
[motionPointIsFinite, motionEqualityResidual, ...
    motionInequalityResidual, motionControlViolation] = ...
    verifyLinearSeedPoint(initialControl, variableCount, ...
    equalityMatrix, equalityTarget, motionInequalityMatrix, ...
    motionInequalityTarget);
motionOnlyPointIsFeasible = motionPointIsFinite && ...
    motionEqualityResidual <= verificationTolerance && ...
    motionInequalityResidual <= verificationTolerance && ...
    motionControlViolation <= verificationTolerance;
isFeasible = false;
control = zeros(controlCount, 2);

%% Section 2: Solve The Bounded Least-Squares Projection

try
    linearOptions = optimoptions("lsqlin", ...
        "Algorithm", "active-set", "Display", "none", ...
        "ConstraintTolerance", 1e-12, ...
        "OptimalityTolerance", 1e-10, ...
        "StepTolerance", 1e-12);
    [normalizedControl, ~, ~, linearExitFlag, linearOutput] = lsqlin( ...
        objectiveMatrix, objectiveTarget, inequalityMatrix, ...
        inequalityTarget, equalityMatrix, equalityTarget, lowerBound, ...
        upperBound, initialControl, linearOptions);
    linearMessage = string(linearOutput.message);
catch fitError
    timeBudgetReached = candidateTimeBudgetReached( ...
        candidateTimer, remainingTime_s);
    if timeBudgetReached
        message = "The joint HS-3 projection time budget expired.";
        return;
    end
    message = "The joint HS-3 least-squares solver failed: " + ...
        string(fitError.identifier) + ".";
    return;
end
timeBudgetReached = candidateTimeBudgetReached( ...
    candidateTimer, remainingTime_s);
if timeBudgetReached
    message = "The joint HS-3 projection time budget expired.";
    return;
end

%% Section 3: Verify Or Recover A Feasible Point

[isFeasible, maximumEqualityResidual, ...
    maximumInequalityResidual, maximumControlViolation] = ...
    verifyLinearSeedPoint(normalizedControl, variableCount, ...
    equalityMatrix, equalityTarget, inequalityMatrix, inequalityTarget);
isFeasible = isFeasible && ...
    maximumEqualityResidual <= verificationTolerance && ...
    maximumInequalityResidual <= verificationTolerance && ...
    maximumControlViolation <= verificationTolerance;
if ~isFeasible && exist("linprog", "file") == 2
    try
        feasibilityOptions = optimoptions("linprog", "Display", "none", ...
            "ConstraintTolerance", 1e-10, ...
            "OptimalityTolerance", 1e-10);
        [feasibleControl, ~, feasibilityExitFlag, feasibilityOutput] = ...
            linprog(zeros(variableCount, 1), inequalityMatrix, ...
            inequalityTarget, equalityMatrix, equalityTarget, ...
            lowerBound, upperBound, feasibilityOptions);
    catch feasibilityError
        timeBudgetReached = candidateTimeBudgetReached( ...
            candidateTimer, remainingTime_s);
        if timeBudgetReached
            message = "The joint HS-3 feasibility time budget expired.";
            return;
        end
        message = "The joint HS-3 feasibility solver failed: " + ...
            string(feasibilityError.identifier) + ".";
        return;
    end
    timeBudgetReached = candidateTimeBudgetReached( ...
        candidateTimer, remainingTime_s);
    if timeBudgetReached
        message = "The joint HS-3 feasibility time budget expired.";
        return;
    end
    if feasibilityExitFlag == -2
        if ~motionOnlyPointIsFeasible || isempty(corridorMatrix)
            message = "The joint bounded HS-3 route and corridor are " + ...
                "infeasible. Exit flag: -2. " + ...
                string(feasibilityOutput.message);
            return;
        end
    elseif isempty(feasibleControl) || feasibilityExitFlag <= 0
        message = "The joint HS-3 feasibility solver returned no " + ...
            "proved point. Exit flag: " + ...
            string(feasibilityExitFlag) + ".";
        return;
    else
        normalizedControl = feasibleControl;
        [isFeasible, maximumEqualityResidual, ...
            maximumInequalityResidual, maximumControlViolation] = ...
            verifyLinearSeedPoint(normalizedControl, variableCount, ...
            equalityMatrix, equalityTarget, inequalityMatrix, ...
            inequalityTarget);
        isFeasible = isFeasible && ...
            maximumEqualityResidual <= verificationTolerance && ...
            maximumInequalityResidual <= verificationTolerance && ...
            maximumControlViolation <= verificationTolerance;
    end
end
if ~isFeasible && motionOnlyPointIsFeasible && ~isempty(corridorMatrix)
    normalizedControl = initialControl;
    [isFeasible, maximumEqualityResidual, ...
        maximumInequalityResidual, maximumControlViolation] = ...
        verifyLinearSeedPoint(normalizedControl, variableCount, ...
        equalityMatrix, equalityTarget, motionInequalityMatrix, ...
        motionInequalityTarget);
    isFeasible = isFeasible && ...
        maximumEqualityResidual <= verificationTolerance && ...
        maximumInequalityResidual <= verificationTolerance && ...
        maximumControlViolation <= verificationTolerance;
    linearMessage = "The motion-feasible HS-3 seed was retained because " + ...
        "the local linear corridor was infeasible.";
end
if ~isFeasible
    if motionOnlyPointIsFeasible && ~isempty(corridorMatrix)
        failureReason = "collisionValidationFailed";
    end
    message = "The joint HS-3 point failed residual verification. " + ...
        "Least-squares exit flag: " + string(linearExitFlag) + ". " + ...
        linearMessage;
    return;
end
control(:, 1) = limits.maxJerk_deg_s3(1) * ...
    normalizedControl(1:controlCount);
control(:, 2) = limits.maxJerk_deg_s3(2) * ...
    normalizedControl(controlCount + (1:controlCount));
failureReason = "";
message = "The joint bounded HS-3 route projection passed linear " + ...
    "feasibility verification. " + linearMessage;
end

%% Section 4: Local Functions

function model = axisSeedLinearModel( ...
        stateResponse, fitPositionResponse, continuousStateResponse, ...
        continuousJerkResponse, freeSampleState, freeContinuousState, ...
        freeFitPosition, targetFitPosition, goalState, baseControl, ...
        jerkLimit, velocityLimit, accelerationLimit, positionBounds)
% PURPOSE
%   - Build one axis of the scaled HS-3 linear projection.
sampleCount = size(freeSampleState, 1);
controlCount = size(stateResponse, 2);
knotCount = (sampleCount + 1) / 2;
positionScale = max([1; max(targetFitPosition) - ...
    min(targetFitPosition); abs(goalState(1) - freeSampleState(1, 1))]);
stateScale = repmat([positionScale, max(1, velocityLimit), ...
    max(1, accelerationLimit)], sampleCount, 1);
stateScale = stateScale(:);
normalizedStateResponse = (jerkLimit * stateResponse) ./ stateScale;
terminalRow = [knotCount, sampleCount + knotCount, ...
    2 * sampleCount + knotCount];
equalityMatrix = normalizedStateResponse(terminalRow, :);
equalityTarget = (goalState(:) - ...
    freeSampleState(knotCount, :).') ./ stateScale(terminalRow);

stateLower = repmat([positionBounds(1), -velocityLimit, ...
    -accelerationLimit], sampleCount, 1);
stateUpper = repmat([positionBounds(2), velocityLimit, ...
    accelerationLimit], sampleCount, 1);
upperAllowance = (stateUpper(:) - freeSampleState(:)) ./ stateScale;
lowerAllowance = (freeSampleState(:) - stateLower(:)) ./ stateScale;
hasFiniteUpper = isfinite(upperAllowance);
hasFiniteLower = isfinite(lowerAllowance);
inequalityMatrix = [ ...
    normalizedStateResponse(hasFiniteUpper, :); ...
    -normalizedStateResponse(hasFiniteLower, :)];
inequalityTarget = [upperAllowance(hasFiniteUpper); ...
    lowerAllowance(hasFiniteLower)];

continuousPointCount = size(freeContinuousState, 1);
continuousScale = repmat([positionScale, max(1, velocityLimit), ...
    max(1, accelerationLimit)], continuousPointCount, 1);
continuousScale = continuousScale(:);
normalizedContinuousStateResponse = ...
    (jerkLimit * continuousStateResponse) ./ continuousScale;
continuousLower = repmat([positionBounds(1), -velocityLimit, ...
    -accelerationLimit], continuousPointCount, 1);
continuousUpper = repmat([positionBounds(2), velocityLimit, ...
    accelerationLimit], continuousPointCount, 1);
continuousUpperAllowance = (continuousUpper(:) - ...
    freeContinuousState(:)) ./ continuousScale;
continuousLowerAllowance = (freeContinuousState(:) - ...
    continuousLower(:)) ./ continuousScale;
hasFiniteContinuousUpper = isfinite(continuousUpperAllowance);
hasFiniteContinuousLower = isfinite(continuousLowerAllowance);
inequalityMatrix = [inequalityMatrix; ...
    normalizedContinuousStateResponse(hasFiniteContinuousUpper, :); ...
    -normalizedContinuousStateResponse(hasFiniteContinuousLower, :); ...
    continuousJerkResponse; -continuousJerkResponse];
inequalityTarget = [inequalityTarget; ...
    continuousUpperAllowance(hasFiniteContinuousUpper); ...
    continuousLowerAllowance(hasFiniteContinuousLower); ...
    ones(2 * size(continuousJerkResponse, 1), 1)];

normalizedPositionResponse = ...
    jerkLimit * fitPositionResponse / positionScale;
normalizedPositionTarget = ...
    (targetFitPosition - freeFitPosition) / positionScale;
firstDifference = diff(eye(controlCount), 1, 1);
objectiveMatrix = [normalizedPositionResponse; ...
    1e-3 * firstDifference; 1e-6 * eye(controlCount)];
objectiveTarget = [normalizedPositionTarget; ...
    zeros(size(firstDifference, 1) + controlCount, 1)];
model = struct( ...
    "ObjectiveMatrix", objectiveMatrix, ...
    "ObjectiveTarget", objectiveTarget, ...
    "InequalityMatrix", inequalityMatrix, ...
    "InequalityTarget", inequalityTarget, ...
    "EqualityMatrix", equalityMatrix, ...
    "EqualityTarget", equalityTarget, ...
    "InitialControl", min(1, max(-1, baseControl / jerkLimit)));
end

function [inequalityMatrix, inequalityTarget] = ...
        linearSeedCorridorConstraints( ...
        corridor, obstacleField, initialTime_s, finalTime_s, ...
        freePosition_deg, positionResponse, ...
        freeContinuousPosition_deg, continuousPositionResponse, ...
        jerkLimits_deg_s3, clearance_deg)
% PURPOSE
%   - Express frozen two-axis obstacle separators in jerk coordinates.
pointCount = numel(corridor.PointTau);
controlCount = size(positionResponse, 2);
if size(freePosition_deg, 1) ~= pointCount || ...
        size(positionResponse, 1) ~= pointCount
    error("fitAzElHs3InitialControl:SeedCorridorSizeMismatch", ...
        "The joint seed response does not match the corridor points.");
end
activeCount = nnz(corridor.Active);
pointsPerSegment = 5;
segmentCount = size(freeContinuousPosition_deg, 1) / 4;
hasStaticSegmentRows = isfield(corridor, "GeometryTimeInvariant") && ...
    corridor.GeometryTimeInvariant && segmentCount == fix(segmentCount) && ...
    pointCount == pointsPerSegment * segmentCount;
maximumStaticRowCount = 0;
if hasStaticSegmentRows
    midpointRow = 3:pointsPerSegment:pointCount;
    maximumStaticRowCount = 6 * nnz(corridor.Active(midpointRow, :));
end
inequalityMatrix = zeros( ...
    activeCount + maximumStaticRowCount, 2 * controlCount);
inequalityTarget = ones(activeCount + maximumStaticRowCount, 1);
pointTime_s = initialTime_s + ...
    (finalTime_s - initialTime_s) * corridor.PointTau;
edgeSets_deg = azElInternal.interpolateAzElObstacleEdges( ...
    obstacleField, pointTime_s);
constraintIndex = 0;
for pointIndex = 1:pointCount
    for obstacleIndex = 1:numel(obstacleField.Obstacles)
        if ~corridor.Active(pointIndex, obstacleIndex)
            continue;
        end
        constraintIndex = constraintIndex + 1;
        edges_deg = edgeSets_deg{pointIndex, obstacleIndex};
        if isempty(edges_deg)
            continue;
        end
        selectedEdgeIndex = min(size(edges_deg, 1), max(1, ...
            corridor.EdgeIndex(pointIndex, obstacleIndex)));
        edge_deg = edges_deg(selectedEdgeIndex, :);
        tangent_deg = edge_deg(3:4) - edge_deg(1:2);
        leftNormal = [-tangent_deg(2), tangent_deg(1)];
        normalLength = norm(leftNormal);
        if normalLength <= eps
            inequalityTarget(constraintIndex) = -clearance_deg;
            continue;
        end
        normal = corridor.SideSign(pointIndex, obstacleIndex) * ...
            leftNormal / normalLength;
        responseRow = positionResponse(pointIndex, :);
        inequalityMatrix(constraintIndex, 1:controlCount) = ...
            -normal(1) * jerkLimits_deg_s3(1) * responseRow;
        inequalityMatrix(constraintIndex, ...
            controlCount + (1:controlCount)) = ...
            -normal(2) * jerkLimits_deg_s3(2) * responseRow;
        inequalityTarget(constraintIndex) = dot( ...
            freePosition_deg(pointIndex, :) - edge_deg(1:2), normal) - ...
            clearance_deg;
    end
end
if hasStaticSegmentRows
    for segmentIndex = 1:segmentCount
        firstPointRow = pointsPerSegment * (segmentIndex - 1) + 1;
        midpointRow = pointsPerSegment * (segmentIndex - 1) + 3;
        lastPointRow = pointsPerSegment * segmentIndex;
        continuousRow = 4 * (segmentIndex - 1) + (1:4);
        staticFreePosition_deg = [ ...
            freePosition_deg(firstPointRow, :); ...
            freeContinuousPosition_deg(continuousRow, :); ...
            freePosition_deg(lastPointRow, :)];
        staticPositionResponse = [ ...
            positionResponse(firstPointRow, :); ...
            continuousPositionResponse(continuousRow, :); ...
            positionResponse(lastPointRow, :)];
        for obstacleIndex = 1:numel(obstacleField.Obstacles)
            if ~corridor.Active(midpointRow, obstacleIndex)
                continue;
            end
            edges_deg = edgeSets_deg{midpointRow, obstacleIndex};
            if isempty(edges_deg)
                continue;
            end
            selectedEdgeIndex = min(size(edges_deg, 1), max(1, ...
                corridor.EdgeIndex(midpointRow, obstacleIndex)));
            edge_deg = edges_deg(selectedEdgeIndex, :);
            tangent_deg = edge_deg(3:4) - edge_deg(1:2);
            leftNormal = [-tangent_deg(2), tangent_deg(1)];
            normalLength = norm(leftNormal);
            if normalLength <= eps
                continue;
            end
            normal = corridor.SideSign(midpointRow, obstacleIndex) * ...
                leftNormal / normalLength;
            for staticRowIndex = 1:6
                constraintIndex = constraintIndex + 1;
                responseRow = staticPositionResponse(staticRowIndex, :);
                inequalityMatrix(constraintIndex, 1:controlCount) = ...
                    -normal(1) * jerkLimits_deg_s3(1) * responseRow;
                inequalityMatrix(constraintIndex, ...
                    controlCount + (1:controlCount)) = ...
                    -normal(2) * jerkLimits_deg_s3(2) * responseRow;
                inequalityTarget(constraintIndex) = dot( ...
                    staticFreePosition_deg(staticRowIndex, :) - ...
                    edge_deg(1:2), normal) - clearance_deg;
            end
        end
    end
end
inequalityMatrix = inequalityMatrix(1:constraintIndex, :);
inequalityTarget = inequalityTarget(1:constraintIndex);
end

function [isFinitePoint, maximumEqualityResidual, ...
        maximumInequalityResidual, maximumControlViolation] = ...
        verifyLinearSeedPoint(point, variableCount, equalityMatrix, ...
        equalityTarget, inequalityMatrix, inequalityTarget)
% PURPOSE
%   - Measure one linear seed without trusting the solver exit flag.
isFinitePoint = ~isempty(point) && numel(point) == variableCount && ...
    all(isfinite(point));
if ~isFinitePoint
    maximumEqualityResidual = Inf;
    maximumInequalityResidual = Inf;
    maximumControlViolation = Inf;
    return;
end
maximumEqualityResidual = maximumAbsoluteOrZero( ...
    equalityMatrix * point - equalityTarget);
maximumInequalityResidual = maximumOrZero( ...
    inequalityMatrix * point - inequalityTarget);
maximumControlViolation = max([0; abs(point) - 1]);
end

function reached = candidateTimeBudgetReached( ...
        candidateTimer, remainingTime_s)
% PURPOSE
%   - Check the candidate timer only when its limit is finite.
reached = isfinite(remainingTime_s) && ...
    toc(candidateTimer) >= remainingTime_s;
end

function value = maximumOrZero(vector)
% PURPOSE
%   - Return the positive violation of an optional vector.
if isempty(vector)
    value = 0;
else
    value = max(0, max(vector));
end
end

function value = maximumAbsoluteOrZero(vector)
% PURPOSE
%   - Return the maximum magnitude of an optional vector.
if isempty(vector)
    value = 0;
else
    value = max(abs(vector));
end
end
