function candidate = generateAzElRlMotion(route_deg, obstacleField, ...
        initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   candidate = azElInternal.generateAzElRlMotion( ...
%       route_deg, obstacleField, initialState, goalState, limits, options)
%**************************************************************************
% PURPOSE
%   - Convert one RL-shaped route directly into a continuous-acceleration
%     quintic motion without a numerical motion optimizer.
%   - Reject policy motion that fails an independent physical or collision
%     certificate.
%**************************************************************************
% INPUTS
%   - route_deg (N-by-2 finite numeric matrix)
%       RL-shaped [azimuth elevation] route with at least two points.
%   - obstacleField (scalar packed-obstacle struct)
%       Protected static or time-varying obstacle geometry.
%   - initialState, goalState (scalar structs)
%       Endpoint time, position, velocity, and acceleration states.
%   - limits (scalar struct)
%       Positive two-axis velocity, acceleration, and jerk limits.
%   - options (scalar struct)
%       Resolved timing, workspace, sampling, and validation controls.
%**************************************************************************
% OUTPUTS
%   - candidate (scalar struct)
%       Stable success-or-failure policy-motion record with trajectory,
%       duration trials, validation, and collision-certificate evidence.
%**************************************************************************
% UNITS
%   - Position is degrees. Time is seconds. Derivative units are stated in
%     field names. Histories are N-by-2 [azimuth elevation].
%**************************************************************************

%% Section 1: Validate Inputs And Build The Policy Route Law

candidateTimer = tic;
validateattributes(route_deg, {'numeric'}, ...
    {'real', 'finite', '2d', 'ncols', 2, 'nonempty'});
if size(route_deg, 1) < 2
    error("generateAzElRlMotion:InvalidRoute", ...
        "route_deg must contain two distinct positions.");
end
requiredOptionNames = ["GoalTimeMode" "SampleTime_s" ...
    "RlDurationTolerance_s" "RlDurationTrialCount" ...
    "CollisionTimePaddingSamples" "KinematicValidationTolerance" ...
    "RemainingPlanningTime_s" "AllowAzimuthWrapping" ...
    "ObstacleGeometryTimeInvariant" ...
    "SeedSnapshotTime_s" ...
    "AzimuthInterval_deg" "ElevationInterval_deg" ...
    "SeedRouteTimeFraction" "SeedRouteProgress" ...
    "SeedRouteDuration_s"];
if ~isstruct(options) || ~isscalar(options) || ...
        ~all(isfield(options, requiredOptionNames))
    error("generateAzElRlMotion:InvalidOptions", ...
        "options is missing a required RL motion field.");
end
route_deg = conditionPolicyRoute( ...
    route_deg, obstacleField, options, initialState.time_s);
candidate = emptyCandidate();
candidate.SeedRouteTimeFraction = ...
    double(options.SeedRouteTimeFraction(:));
candidate.SeedRouteProgress = double(options.SeedRouteProgress(:));
candidate.TimedSeedLawUsed = validTimedSeedLaw( ...
    candidate.SeedRouteTimeFraction, candidate.SeedRouteProgress, ...
    options.SeedRouteDuration_s);
horizonDuration_s = goalState.time_s - initialState.time_s;
[knotPosition_deg, ~] = policyKnotLaw( ...
    route_deg, candidate, limits, 1, horizonDuration_s, ...
    initialState, goalState, options);
routeStep_deg = diff(knotPosition_deg, 1, 1);
routeWork_s = sum(max(abs(routeStep_deg) ./ ...
    limits.maxVelocity_deg_s, [], 2));
endpointVelocityTime_s = max(abs(goalState.velocity_deg_s - ...
    initialState.velocity_deg_s) ./ limits.maxAcceleration_deg_s2);
endpointAccelerationTime_s = max(abs( ...
    goalState.acceleration_deg_s2 - initialState.acceleration_deg_s2) ./ ...
    limits.maxJerk_deg_s3);
necessaryDuration_s = max([routeWork_s, endpointVelocityTime_s, ...
    endpointAccelerationTime_s]);
if horizonDuration_s + options.RlDurationTolerance_s < ...
        necessaryDuration_s
    candidate.Message = "The goal horizon violates a necessary route " + ...
        "velocity, acceleration, or jerk duration bound.";
    candidate.TerminationReason = "goalTimeInfeasible";
    candidate.ElapsedTime_s = toc(candidateTimer);
    return;
end

%% Section 2: Generate And Validate Direct Policy Motions

durationTrials_s = buildDurationTrials( ...
    knotPosition_deg, initialState, goalState, limits, ...
    options, horizonDuration_s);
tangentScales = [1.75; 2; 2.25; 1.25; 1.5; 1; 0.75; 0.5; 0.25; 0];
if options.GoalTimeMode == "fixedarrival"
    tangentScales = [tangentScales; 0.975; 1.025; 0.95; 1.05];
end
timeLawBlends = ones(size(tangentScales));
if candidate.TimedSeedLawUsed
    % Test the SIPP phase first. Then progressively regularize it toward
    % the analytic physical response law. Each variant uses the same RL
    % route and the same direct quintic reconstruction.
    tangentScales = [tangentScales; ...
        0.5; 0; 0.5; 0; 0.5; 0; 0.5; 0];
    timeLawBlends = [timeLawBlends; ...
        0.75; 0.75; 0.5; 0.5; 0.25; 0.25; 0; 0];
else
    tangentScales = [tangentScales; 1; 0.75; 0.5; 0.25; 0];
    timeLawBlends = [timeLawBlends; zeros(5, 1)];
end
trialResults = repmat(emptyTrial(), 0, 1);
selectedTrialIndex = 0;
endpointStatesAreRest = max(abs([initialState.velocity_deg_s, ...
    initialState.acceleration_deg_s2, goalState.velocity_deg_s, ...
    goalState.acceleration_deg_s2])) <= ...
    options.KinematicValidationTolerance;
durationIndex = 1;
while durationIndex <= numel(durationTrials_s)
    if toc(candidateTimer) >= options.RemainingPlanningTime_s
        break;
    end
    firstTrialIndex = numel(trialResults) + 1;
    for tangentIndex = 1:numel(tangentScales)
        [trialKnotPosition_deg, trialKnotFraction, ...
            velocityOverride_deg_s, accelerationOverride_deg_s2] = ...
            policyKnotLaw( ...
            route_deg, candidate, limits, ...
            timeLawBlends(tangentIndex), ...
            durationTrials_s(durationIndex), initialState, goalState, ...
            options);
        trial = buildAndValidateTrial( ...
            trialKnotPosition_deg, trialKnotFraction, ...
            durationTrials_s(durationIndex), tangentScales(tangentIndex), ...
            timeLawBlends(tangentIndex), velocityOverride_deg_s, ...
            accelerationOverride_deg_s2, obstacleField, initialState, ...
            goalState, limits, options);
        trialResults(end + 1, 1) = trial; %#ok<AGROW>
        if trial.Success
            selectedTrialIndex = numel(trialResults);
            break;
        end
    end
    if selectedTrialIndex > 0
        break;
    end
    currentTrials = trialResults(firstTrialIndex:end);
    requiredScale = Inf;
    for trialIndex = 1:numel(currentTrials)
        requiredScale = min(requiredScale, ...
            requiredKinematicDurationScale( ...
            currentTrials(trialIndex), limits));
    end
    currentDuration_s = durationTrials_s(durationIndex);
    fixedWaitDuration_s = 0;
    if ~candidate.TimedSeedLawUsed && ...
            ~options.ObstacleGeometryTimeInvariant
        fixedWaitDuration_s = max(0, ...
            options.SeedSnapshotTime_s - initialState.time_s);
    end
    movingDuration_s = max(options.RlDurationTolerance_s, ...
        currentDuration_s - fixedWaitDuration_s);
    requiredDuration_s = fixedWaitDuration_s + ...
        movingDuration_s * requiredScale * 1.001;
    canJumpToKinematicDuration = isfinite(requiredDuration_s) && ...
        requiredScale > 1 + options.KinematicValidationTolerance && ...
        currentDuration_s < horizonDuration_s && ~endpointStatesAreRest;
    if canJumpToKinematicDuration
        requiredDuration_s = min(horizonDuration_s, requiredDuration_s);
        completedDuration_s = durationTrials_s(1:durationIndex);
        futureDuration_s = durationTrials_s(durationIndex + 1:end);
        futureDuration_s = futureDuration_s(futureDuration_s >= ...
            requiredDuration_s - options.RlDurationTolerance_s);
        durationTrials_s = unique([completedDuration_s; ...
            requiredDuration_s; futureDuration_s]);
    end
    durationIndex = durationIndex + 1;
end
canRefineStaticDuration = selectedTrialIndex > 0 && ...
    options.GoalTimeMode == "earliestarrival" && ...
    options.ObstacleGeometryTimeInvariant && durationIndex > 1;
if canRefineStaticDuration
    lowerDuration_s = durationTrials_s(durationIndex - 1);
    upperDuration_s = trialResults(selectedTrialIndex).MotionDuration_s;
    while upperDuration_s - lowerDuration_s > ...
            options.RlDurationTolerance_s && ...
            toc(candidateTimer) < options.RemainingPlanningTime_s
        middleDuration_s = 0.5 * (lowerDuration_s + upperDuration_s);
        middleSuccess = false;
        for tangentIndex = 1:numel(tangentScales)
            [trialKnotPosition_deg, trialKnotFraction, ...
                velocityOverride_deg_s, ...
                accelerationOverride_deg_s2] = ...
                policyKnotLaw(route_deg, candidate, limits, ...
                timeLawBlends(tangentIndex), middleDuration_s, ...
                initialState, goalState, options);
            trial = buildAndValidateTrial( ...
                trialKnotPosition_deg, trialKnotFraction, middleDuration_s, ...
                tangentScales(tangentIndex), ...
                timeLawBlends(tangentIndex), velocityOverride_deg_s, ...
                accelerationOverride_deg_s2, obstacleField, initialState, ...
                goalState, limits, options);
            trialResults(end + 1, 1) = trial; %#ok<AGROW>
            if trial.Success
                selectedTrialIndex = numel(trialResults);
                upperDuration_s = middleDuration_s;
                middleSuccess = true;
                break;
            end
        end
        if ~middleSuccess
            lowerDuration_s = middleDuration_s;
        end
    end
end

%% Section 3: Assemble The Stable Candidate Record

trialCount = numel(trialResults);
candidate.DurationTrial_s = zeros(trialCount, 1);
candidate.DurationFeasibleHistory = false(trialCount, 1);
candidate.DurationIntegratedSquaredJerk = inf(trialCount, 1);
candidate.DurationMaximumVelocity_deg_s = inf(trialCount, 2);
candidate.DurationMaximumAcceleration_deg_s2 = inf(trialCount, 2);
candidate.DurationMaximumJerk_deg_s3 = inf(trialCount, 2);
candidate.DurationTangentScale = nan(trialCount, 1);
candidate.DurationTimeLawBlend = nan(trialCount, 1);
candidate.DurationIssueSummary = strings(trialCount, 1);
candidate.PolicyEvaluationCount = trialCount;
for trialIndex = 1:trialCount
    trial = trialResults(trialIndex);
    candidate.DurationTrial_s(trialIndex) = trial.MotionDuration_s;
    candidate.DurationFeasibleHistory(trialIndex) = trial.Success;
    candidate.DurationIntegratedSquaredJerk(trialIndex) = ...
        trial.IntegratedSquaredJerk;
    candidate.DurationMaximumVelocity_deg_s(trialIndex, :) = ...
        trial.MaximumVelocity_deg_s;
    candidate.DurationMaximumAcceleration_deg_s2(trialIndex, :) = ...
        trial.MaximumAcceleration_deg_s2;
    candidate.DurationMaximumJerk_deg_s3(trialIndex, :) = ...
        trial.MaximumJerk_deg_s3;
    candidate.DurationTangentScale(trialIndex) = trial.TangentScale;
    candidate.DurationTimeLawBlend(trialIndex) = trial.TimeLawBlend;
    candidate.DurationIssueSummary(trialIndex) = ...
        strjoin(string(trial.Validation.Issues), ",");
end
if selectedTrialIndex > 0
    candidate = copySuccessfulTrial(candidate, ...
        trialResults(selectedTrialIndex));
elseif trialCount > 0
    lastTrial = trialResults(end);
    candidate.Message = lastTrial.Message;
    candidate.TerminationReason = lastTrial.TerminationReason;
    candidate.ArrivalTime_s = lastTrial.ArrivalTime_s;
    candidate.MotionDuration_s = lastTrial.MotionDuration_s;
    candidate.MaximumVelocity_deg_s = lastTrial.MaximumVelocity_deg_s;
    candidate.MaximumAcceleration_deg_s2 = ...
        lastTrial.MaximumAcceleration_deg_s2;
    candidate.MaximumJerk_deg_s3 = lastTrial.MaximumJerk_deg_s3;
    candidate.Trajectory = lastTrial.Trajectory;
    candidate.Validation = lastTrial.Validation;
    candidate.CollisionFree = lastTrial.CollisionFree;
    candidate.BufferedChordQueryClear = ...
        lastTrial.BufferedChordQueryClear;
    candidate.CollisionSafetyProven = ...
        lastTrial.CollisionSafetyProven;
    candidate.ReferencePosition_deg = lastTrial.ReferencePosition_deg;
    candidate.ReferenceTimeFraction = lastTrial.ReferenceTimeFraction;
    candidate.SelectedTangentScale = lastTrial.TangentScale;
    candidate.SelectedTimeLawBlend = lastTrial.TimeLawBlend;
    candidate.CollisionClearanceDiagnostics = ...
        lastTrial.CollisionClearanceDiagnostics;
else
    candidate.Message = ...
        "The RL motion time budget expired before policy evaluation.";
    candidate.TerminationReason = "planningTimeLimit";
end
candidate.ElapsedTime_s = toc(candidateTimer);
end

%% Section 4: Local Functions

function route_deg = conditionPolicyRoute( ...
        route_deg, obstacleField, options, initialTime_s)
% PURPOSE
%   - Remove short route edges only when the replacement chord is clear.
route_deg = double(route_deg);
if size(route_deg, 1) < 3
    return;
end
edgeLength_deg = vecnorm(diff(route_deg, 1, 1), 2, 2);
routeLength_deg = sum(edgeLength_deg);
routeProgress = [0; cumsum(edgeLength_deg)] / routeLength_deg;
hasTimedLaw = validTimedSeedLaw(options.SeedRouteTimeFraction, ...
    options.SeedRouteProgress, options.SeedRouteDuration_s);
if hasTimedLaw
    [uniqueSeedProgress, lastSeedIndex] = unique( ...
        options.SeedRouteProgress, "last");
    uniqueSeedTimeFraction = options.SeedRouteTimeFraction( ...
        lastSeedIndex);
end
keepRow = false(size(route_deg, 1), 1);
keepRow(1) = true;
retainedIndex = 1;
for routeIndex = 2:size(route_deg, 1) - 1
    canSkip = true;
    if canSkip && obstacleField.ObstacleCount > 0
        replacementChord_deg = [route_deg(retainedIndex, :); ...
            route_deg(routeIndex + 1, :)];
        if hasTimedLaw
            chordTimeFraction = interp1(uniqueSeedProgress, ...
                uniqueSeedTimeFraction, ...
                routeProgress([retainedIndex, routeIndex + 1]), ...
                "linear", "extrap");
            collisionTime_s = initialTime_s + ...
                options.SeedRouteDuration_s * chordTimeFraction;
        else
            collisionTime_s = options.SeedSnapshotTime_s;
        end
        chordBlocked = queryAzElTimedPathCollision( ...
            obstacleField, collisionTime_s, ...
            replacementChord_deg, struct("BoundaryIsOccupied", ...
            ~options.ObstacleGeometryTimeInvariant, ...
            "StopAtFirstCollision", true));
        canSkip = ~any(chordBlocked);
    end
    if ~canSkip
        keepRow(routeIndex) = true;
        retainedIndex = routeIndex;
    end
end
keepRow(end) = true;
route_deg = route_deg(keepRow, :);
end

function isValid = validTimedSeedLaw(timeFraction, progress, duration_s)
% PURPOSE
%   - Check one normalized SIPP progress law.
isValid = numel(timeFraction) >= 2 && ...
    numel(timeFraction) == numel(progress) && ...
    all(isfinite(timeFraction)) && all(isfinite(progress)) && ...
    all(diff(timeFraction) > 0) && all(diff(progress) >= 0) && ...
    timeFraction(1) >= -1e-10 && timeFraction(end) <= 1 + 1e-10 && ...
    isfinite(duration_s) && duration_s > 0;
end

function [position_deg, fraction, velocityOverride_deg_s, ...
        accelerationOverride_deg_s2] = policyKnotLaw( ...
        route_deg, candidate, limits, timeLawBlend, duration_s, ...
        initialState, goalState, options)
% PURPOSE
%   - Combine RL route knots with the optional SIPP wait law.
initialTime_s = initialState.time_s;
waitDuration_s = 0;
if ~candidate.TimedSeedLawUsed && ...
        ~options.ObstacleGeometryTimeInvariant
    waitDuration_s = max(0, ...
        options.SeedSnapshotTime_s - initialTime_s);
elseif candidate.TimedSeedLawUsed && timeLawBlend <= 1e-12
    leadingWaitMask = candidate.SeedRouteProgress <= 1e-10;
    if any(leadingWaitMask)
        leadingWaitFraction = max( ...
            candidate.SeedRouteTimeFraction(leadingWaitMask));
        waitDuration_s = options.SeedRouteDuration_s * ...
            leadingWaitFraction;
    end
end
motionLawDuration_s = max(options.RlDurationTolerance_s, ...
    duration_s - waitDuration_s);
routeStep_deg = diff(route_deg, 1, 1);
routeArc_deg = [0; cumsum(hypot( ...
    routeStep_deg(:, 1), routeStep_deg(:, 2)))];
routeProgress = routeArc_deg / routeArc_deg(end);
endpointStatesAreRest = max(abs([initialState.velocity_deg_s, ...
    initialState.acceleration_deg_s2, goalState.velocity_deg_s, ...
    goalState.acceleration_deg_s2])) <= ...
    options.KinematicValidationTolerance;
if ~endpointStatesAreRest
    position_deg = route_deg;
    velocityOverride_deg_s = nan(size(route_deg));
    accelerationOverride_deg_s2 = nan(size(route_deg));
    fraction = routeProgress;
    if candidate.TimedSeedLawUsed
        [uniqueProgress, lastIndex] = unique( ...
            candidate.SeedRouteProgress, "last");
        fraction = interp1(uniqueProgress, ...
            candidate.SeedRouteTimeFraction(lastIndex), ...
            routeProgress, "linear", "extrap");
    end
    return;
end
% Dedicated endpoint intervals let the physical polynomial accelerate and
% brake near the endpoints. Directional path limits use both axes without
% exceeding either axis limit.
initialDirection = routeStep_deg(1, :) / norm(routeStep_deg(1, :));
finalDirection = routeStep_deg(end, :) / norm(routeStep_deg(end, :));
maximumTransitionDistance_deg = 0.15 * routeArc_deg(end);
meanPathSpeed_deg_s = routeArc_deg(end) / motionLawDuration_s;
maximumEndpointSpeed_deg_s = 1.25 * meanPathSpeed_deg_s;
routeVelocityBound_s = sum(max(abs(routeStep_deg) ./ ...
    limits.maxVelocity_deg_s, [], 2));
displacement_deg = abs(route_deg(end, :) - route_deg(1, :));
routeAccelerationBound_s = max(2 * sqrt(displacement_deg ./ ...
    limits.maxAcceleration_deg_s2));
routeJerkBound_s = max((32 * displacement_deg ./ ...
    limits.maxJerk_deg_s3) .^ (1 / 3));
restToRestLowerBound_s = max([routeVelocityBound_s, ...
    routeAccelerationBound_s, routeJerkBound_s]);
endpointSpeedThresholdFactor = 1.25;
if options.ObstacleGeometryTimeInvariant
    endpointSpeedThresholdFactor = 2.25;
end
if motionLawDuration_s <= ...
        endpointSpeedThresholdFactor * restToRestLowerBound_s
    maximumEndpointSpeed_deg_s = Inf;
end
initialProfile = endpointTransition( ...
    initialDirection, limits, maximumTransitionDistance_deg, ...
    maximumEndpointSpeed_deg_s);
finalProfile = endpointTransition( ...
    finalDirection, limits, maximumTransitionDistance_deg, ...
    maximumEndpointSpeed_deg_s);
initialTransitionProgress = initialProfile.Distance_deg / ...
    routeArc_deg(end);
finalTransitionProgress = 1 - flip(finalProfile.Distance_deg) / ...
    routeArc_deg(end);
endpointTransitionProgress = [initialTransitionProgress; ...
    finalTransitionProgress];
policyProgress = unique([routeProgress; endpointTransitionProgress]);
route_deg = interp1(routeProgress, route_deg, ...
    policyProgress, "linear");
routeProgress = policyProgress;
velocityOverride_deg_s = nan(size(route_deg));
accelerationOverride_deg_s2 = nan(size(route_deg));
if endpointStatesAreRest
    for phaseIndex = 1:numel(initialProfile.Time_s)
        [~, knotIndex] = min(abs(routeProgress - ...
            initialTransitionProgress(phaseIndex)));
        velocityOverride_deg_s(knotIndex, :) = ...
            initialProfile.Velocity_deg_s(phaseIndex) * ...
            initialDirection;
        accelerationOverride_deg_s2(knotIndex, :) = ...
            initialProfile.Acceleration_deg_s2(phaseIndex) * ...
            initialDirection;
    end
    finalVelocity_deg_s = flip(finalProfile.Velocity_deg_s);
    finalAcceleration_deg_s2 = -flip( ...
        finalProfile.Acceleration_deg_s2);
    for phaseIndex = 1:numel(finalProfile.Time_s)
        [~, knotIndex] = min(abs(routeProgress - ...
            finalTransitionProgress(phaseIndex)));
        velocityOverride_deg_s(knotIndex, :) = ...
            finalVelocity_deg_s(phaseIndex) * finalDirection;
        accelerationOverride_deg_s2(knotIndex, :) = ...
            finalAcceleration_deg_s2(phaseIndex) * finalDirection;
    end
end
routeStep_deg = diff(route_deg, 1, 1);
edgeDisplacement_deg = abs(routeStep_deg);
velocityWork_s = max(edgeDisplacement_deg ./ ...
    limits.maxVelocity_deg_s, [], 2);
minimumResponseTime_s = 0.5 * min( ...
    limits.maxAcceleration_deg_s2 ./ limits.maxJerk_deg_s3);
velocityEdgeWork_s = max(velocityWork_s, minimumResponseTime_s);
edgeDirection = routeStep_deg ./ vecnorm(routeStep_deg, 2, 2);
edgeTurnFactor = ones(size(velocityEdgeWork_s));
turnPenaltyCoefficient = 2;
if options.ObstacleGeometryTimeInvariant
    turnPenaltyCoefficient = 1.4;
end
for knotIndex = 2:size(route_deg, 1) - 1
    directionDot = dot(edgeDirection(knotIndex - 1, :), ...
        edgeDirection(knotIndex, :));
    turnAngle_rad = acos(min(1, max(-1, directionDot)));
    turnFactor = 1 + turnPenaltyCoefficient * turnAngle_rad / pi;
    edgeTurnFactor(knotIndex - 1:knotIndex) = max( ...
        edgeTurnFactor(knotIndex - 1:knotIndex), turnFactor);
end
velocityEdgeWork_s = velocityEdgeWork_s .* edgeTurnFactor;
accelerationWork_s = max(sqrt(6 * edgeDisplacement_deg ./ ...
    limits.maxAcceleration_deg_s2), [], 2);
jerkWork_s = max((12 * edgeDisplacement_deg ./ ...
    limits.maxJerk_deg_s3) .^ (1 / 3), [], 2);
responseEdgeWork_s = max([velocityWork_s, accelerationWork_s, ...
    jerkWork_s], [], 2);
if candidate.TimedSeedLawUsed
    edgeWork_s = velocityEdgeWork_s;
else
    edgeWork_s = timeLawBlend * velocityEdgeWork_s + ...
        (1 - timeLawBlend) * responseEdgeWork_s;
end
if sum(edgeWork_s) <= eps
    baseFraction = linspace(0, 1, size(route_deg, 1)).';
else
    baseFraction = [0; cumsum(edgeWork_s)] / sum(edgeWork_s);
    transitionIndex = zeros(numel(endpointTransitionProgress), 1);
    for phaseIndex = 1:numel(endpointTransitionProgress)
        [~, transitionIndex(phaseIndex)] = min(abs(routeProgress - ...
            endpointTransitionProgress(phaseIndex)));
    end
    sourceBreak = [0; baseFraction(transitionIndex); 1];
    initialTargetFraction = initialProfile.Time_s / motionLawDuration_s;
    finalTargetFraction = 1 - flip(finalProfile.Time_s) / ...
        motionLawDuration_s;
    targetBreak = [0; initialTargetFraction; ...
        finalTargetFraction; 1];
    if all(diff(sourceBreak) > 1e-10)
        baseFraction = interp1(sourceBreak, targetBreak, ...
            baseFraction, "linear");
    end
end
if ~candidate.TimedSeedLawUsed
    fraction = baseFraction;
    position_deg = route_deg;
    if ~options.ObstacleGeometryTimeInvariant && ...
            waitDuration_s > options.RlDurationTolerance_s && ...
            waitDuration_s < duration_s
        waitFraction = waitDuration_s / duration_s;
        fraction = waitFraction + (1 - waitFraction) * fraction;
        fraction = [0; fraction];
        position_deg = [route_deg(1, :); route_deg];
        velocityOverride_deg_s = [nan(1, 2); ...
            velocityOverride_deg_s];
        accelerationOverride_deg_s2 = [nan(1, 2); ...
            accelerationOverride_deg_s2];
    end
    return;
end
seedProgress = candidate.SeedRouteProgress;
seedTimeFraction = candidate.SeedRouteTimeFraction;
[uniqueProgress, lastIndex] = unique(seedProgress, "last");
timedFraction = interp1(uniqueProgress, seedTimeFraction(lastIndex), ...
    routeProgress, "linear", "extrap");
fraction = timeLawBlend * timedFraction + ...
    (1 - timeLawBlend) * baseFraction;
position_deg = route_deg;
if timeLawBlend > 1e-12
    velocityOverride_deg_s(:) = NaN;
    accelerationOverride_deg_s2(:) = NaN;
end
if timeLawBlend <= 1e-12 && ...
        waitDuration_s > options.RlDurationTolerance_s && ...
        waitDuration_s < duration_s
    waitFraction = waitDuration_s / duration_s;
    fraction = waitFraction + (1 - waitFraction) * fraction;
    fraction = [0; fraction];
    position_deg = [route_deg(1, :); position_deg];
    velocityOverride_deg_s = [nan(1, 2); ...
        velocityOverride_deg_s];
    accelerationOverride_deg_s2 = [nan(1, 2); ...
        accelerationOverride_deg_s2];
end
% Duplicate SIPP progress values describe a discontinuous wait. Selecting
% the last time at that progress spreads the delay over the incoming RL
% curve interval. This preserves the safe late phase without asking a
% continuous-acceleration motion to stop over a near-zero interval.
[fraction, order] = sort(fraction);
position_deg = position_deg(order, :);
velocityOverride_deg_s = velocityOverride_deg_s(order, :);
accelerationOverride_deg_s2 = accelerationOverride_deg_s2(order, :);
[fraction, uniqueIndex] = unique(fraction, "last");
position_deg = position_deg(uniqueIndex, :);
velocityOverride_deg_s = velocityOverride_deg_s(uniqueIndex, :);
accelerationOverride_deg_s2 = ...
    accelerationOverride_deg_s2(uniqueIndex, :);
fraction(1) = 0;
fraction(end) = 1;
minimumGap = 1e-8;
for knotIndex = 2:numel(fraction)
    fraction(knotIndex) = max(fraction(knotIndex), ...
        fraction(knotIndex - 1) + minimumGap);
end
fraction = fraction / fraction(end);
end

function profile = endpointTransition( ...
        direction, limits, maximumDistance_deg, maximumPathSpeed_deg_s)
% PURPOSE
%   - Compute a monotonic jerk-limited endpoint transition.
directionMagnitude = abs(direction);
activeAxis = directionMagnitude > 1e-12;
pathVelocity_deg_s = min(limits.maxVelocity_deg_s(activeAxis) ./ ...
    directionMagnitude(activeAxis));
pathVelocity_deg_s = min(pathVelocity_deg_s, maximumPathSpeed_deg_s);
pathAcceleration_deg_s2 = min( ...
    limits.maxAcceleration_deg_s2(activeAxis) ./ ...
    directionMagnitude(activeAxis));
pathJerk_deg_s3 = min(limits.maxJerk_deg_s3(activeAxis) ./ ...
    directionMagnitude(activeAxis));
profile = transitionProfile(pathVelocity_deg_s, ...
    pathAcceleration_deg_s2, pathJerk_deg_s3);
if profile.Distance_deg(end) <= maximumDistance_deg
    return;
end
lowerVelocity_deg_s = 0;
upperVelocity_deg_s = pathVelocity_deg_s;
for iterationIndex = 1:40
    middleVelocity_deg_s = 0.5 * ( ...
        lowerVelocity_deg_s + upperVelocity_deg_s);
    middleProfile = transitionProfile(middleVelocity_deg_s, ...
        pathAcceleration_deg_s2, pathJerk_deg_s3);
    if middleProfile.Distance_deg(end) <= maximumDistance_deg
        lowerVelocity_deg_s = middleVelocity_deg_s;
        profile = middleProfile;
    else
        upperVelocity_deg_s = middleVelocity_deg_s;
    end
end
end

function profile = transitionProfile( ...
        pathVelocity_deg_s, maximumAcceleration_deg_s2, ...
        maximumJerk_deg_s3)
% PURPOSE
%   - Build exact constant-jerk and constant-acceleration phase states.
peakAcceleration_deg_s2 = min(maximumAcceleration_deg_s2, ...
    sqrt(pathVelocity_deg_s * maximumJerk_deg_s3));
rampTime_s = peakAcceleration_deg_s2 / maximumJerk_deg_s3;
constantAccelerationTime_s = max(0, pathVelocity_deg_s / ...
    peakAcceleration_deg_s2 - rampTime_s);
firstVelocity_deg_s = 0.5 * maximumJerk_deg_s3 * rampTime_s^2;
firstDistance_deg = maximumJerk_deg_s3 * rampTime_s^3 / 6;
secondVelocity_deg_s = firstVelocity_deg_s + ...
    peakAcceleration_deg_s2 * constantAccelerationTime_s;
secondDistance_deg = firstDistance_deg + ...
    firstVelocity_deg_s * constantAccelerationTime_s + ...
    0.5 * peakAcceleration_deg_s2 * ...
    constantAccelerationTime_s^2;
totalTime_s = 2 * rampTime_s + constantAccelerationTime_s;
totalDistance_deg = 0.5 * pathVelocity_deg_s * totalTime_s;
time_s = [rampTime_s; ...
    rampTime_s + constantAccelerationTime_s; totalTime_s];
distance_deg = [firstDistance_deg; secondDistance_deg; ...
    totalDistance_deg];
velocity_deg_s = [firstVelocity_deg_s; secondVelocity_deg_s; ...
    pathVelocity_deg_s];
acceleration_deg_s2 = [peakAcceleration_deg_s2; ...
    peakAcceleration_deg_s2; 0];
[time_s, uniqueIndex] = unique(time_s, "last");
profile = struct( ...
    "Time_s", time_s, ...
    "Distance_deg", distance_deg(uniqueIndex), ...
    "Velocity_deg_s", velocity_deg_s(uniqueIndex), ...
    "Acceleration_deg_s2", acceleration_deg_s2(uniqueIndex));
end

function durationTrials_s = buildDurationTrials( ...
        knotPosition_deg, initialState, goalState, limits, ...
        options, horizonDuration_s)
% PURPOSE
%   - Build bounded analytic duration trials without a motion optimizer.
edge_deg = diff(knotPosition_deg, 1, 1);
routeWork_s = sum(max(abs(edge_deg) ./ ...
    limits.maxVelocity_deg_s, [], 2));
endpointVelocityTime_s = max(abs(goalState.velocity_deg_s - ...
    initialState.velocity_deg_s) ./ limits.maxAcceleration_deg_s2);
endpointAccelerationTime_s = max(abs( ...
    goalState.acceleration_deg_s2 - initialState.acceleration_deg_s2) ./ ...
    limits.maxJerk_deg_s3);
minimumDuration_s = max([options.RlDurationTolerance_s, routeWork_s, ...
    endpointVelocityTime_s, endpointAccelerationTime_s]);
endpointStatesAreRest = max(abs([initialState.velocity_deg_s, ...
    initialState.acceleration_deg_s2, goalState.velocity_deg_s, ...
    goalState.acceleration_deg_s2])) <= ...
    options.KinematicValidationTolerance;
if endpointStatesAreRest
    displacement_deg = abs(goalState.position_deg - ...
        initialState.position_deg);
    velocityBound_s = displacement_deg ./ limits.maxVelocity_deg_s;
    accelerationBound_s = 2 * sqrt(displacement_deg ./ ...
        limits.maxAcceleration_deg_s2);
    jerkBound_s = (32 * displacement_deg ./ ...
        limits.maxJerk_deg_s3) .^ (1 / 3);
    minimumDuration_s = max(minimumDuration_s, max([ ...
        velocityBound_s, accelerationBound_s, jerkBound_s], [], "all"));
end
if ~options.ObstacleGeometryTimeInvariant && ...
        ~validTimedSeedLaw(options.SeedRouteTimeFraction, ...
        options.SeedRouteProgress, options.SeedRouteDuration_s)
    snapshotWait_s = max(0, ...
        options.SeedSnapshotTime_s - initialState.time_s);
    minimumDuration_s = max(minimumDuration_s, ...
        snapshotWait_s + routeWork_s);
end
if options.GoalTimeMode == "fixedarrival"
    durationTrials_s = horizonDuration_s;
    return;
end
if validTimedSeedLaw(options.SeedRouteTimeFraction, ...
        options.SeedRouteProgress, options.SeedRouteDuration_s)
    minimumDuration_s = max(minimumDuration_s, ...
        options.SeedRouteDuration_s);
end
if minimumDuration_s > horizonDuration_s
    durationTrials_s = horizonDuration_s;
    return;
end
trialCount = options.RlDurationTrialCount;
if trialCount == 1 || ...
        horizonDuration_s - minimumDuration_s <= ...
        options.RlDurationTolerance_s
    durationTrials_s = minimumDuration_s;
    return;
end
% A quadratic spacing gives more evidence near the earliest possible time.
scanFraction = linspace(0, 1, trialCount).'.^2;
durationTrials_s = minimumDuration_s + scanFraction * ...
    (horizonDuration_s - minimumDuration_s);
durationTrials_s = unique(durationTrials_s);
end

function trial = buildAndValidateTrial( ...
        knotPosition_deg, knotFraction, duration_s, tangentScale, ...
        timeLawBlend, velocityOverride_deg_s, ...
        accelerationOverride_deg_s2, obstacleField, initialState, ...
        goalState, limits, options)
% PURPOSE
%   - Construct and certify one direct quintic policy motion.
trial = emptyTrial();
trial.MotionDuration_s = duration_s;
trial.ArrivalTime_s = initialState.time_s + duration_s;
trial.TangentScale = tangentScale;
trial.TimeLawBlend = timeLawBlend;
trial.ReferencePosition_deg = knotPosition_deg;
trial.ReferenceTimeFraction = knotFraction;
segmentDuration_s = duration_s * diff(knotFraction);
if any(segmentDuration_s <= 0)
    trial.Message = "The RL route law contains a nonpositive interval.";
    trial.TerminationReason = "invalidPolicyRouteLaw";
    return;
end
knotVelocity_deg_s = interiorKnotVelocity( ...
    knotPosition_deg, segmentDuration_s, tangentScale, ...
    initialState.velocity_deg_s, goalState.velocity_deg_s);
knotAcceleration_deg_s2 = interiorKnotAcceleration( ...
    knotPosition_deg, segmentDuration_s, tangentScale, ...
    initialState.acceleration_deg_s2, goalState.acceleration_deg_s2);
velocityOverrideMask = isfinite(velocityOverride_deg_s);
accelerationOverrideMask = isfinite(accelerationOverride_deg_s2);
knotVelocity_deg_s(velocityOverrideMask) = ...
    velocityOverride_deg_s(velocityOverrideMask);
knotAcceleration_deg_s2(accelerationOverrideMask) = ...
    accelerationOverride_deg_s2(accelerationOverrideMask);
coefficient = quinticCoefficients( ...
    knotPosition_deg, knotVelocity_deg_s, ...
    knotAcceleration_deg_s2, segmentDuration_s);
[trajectory, extrema] = sampleQuinticMotion( ...
    coefficient, segmentDuration_s, initialState.time_s, ...
    options.SampleTime_s);
[validation, clearanceDiagnostics] = validateTrajectory( ...
    trajectory, extrema, obstacleField, initialState, goalState, ...
    limits, options);
trial.Success = validation.Passed;
trial.Message = validation.Message;
trial.TerminationReason = "policyMotionValidationFailed";
if trial.Success
    trial.Message = "The direct RL policy motion passed validation.";
    trial.TerminationReason = "goalReached";
end
trial.Trajectory = trajectory;
trial.Validation = validation;
trial.CollisionFree = validation.CollisionFree;
trial.BufferedChordQueryClear = validation.BufferedChordQueryClear;
trial.CollisionSafetyProven = validation.CollisionSafetyProven;
trial.CollisionClearanceDiagnostics = clearanceDiagnostics;
trial.MaximumVelocity_deg_s = extrema.MaximumVelocity_deg_s;
trial.MaximumAcceleration_deg_s2 = extrema.MaximumAcceleration_deg_s2;
trial.MaximumJerk_deg_s3 = extrema.MaximumJerk_deg_s3;
trial.IntegratedSquaredJerk = trapz(trajectory.time_s, ...
    sum(trajectory.jerk_deg_s3 .^ 2, 2));
end

function scale = requiredKinematicDurationScale(trial, limits)
% PURPOSE
%   - Compute the exact global duration scale needed by one fixed law.
velocityScale = max(trial.MaximumVelocity_deg_s ./ ...
    limits.maxVelocity_deg_s);
accelerationScale = sqrt(max(trial.MaximumAcceleration_deg_s2 ./ ...
    limits.maxAcceleration_deg_s2));
jerkScale = max(trial.MaximumJerk_deg_s3 ./ ...
    limits.maxJerk_deg_s3) ^ (1 / 3);
scale = max([velocityScale, accelerationScale, jerkScale]);
end

function acceleration_deg_s2 = interiorKnotAcceleration( ...
        position_deg, segmentDuration_s, tangentScale, ...
        initialAcceleration_deg_s2, goalAcceleration_deg_s2)
% PURPOSE
%   - Preserve the RL curve curvature with continuous knot acceleration.
knotCount = size(position_deg, 1);
acceleration_deg_s2 = zeros(knotCount, 2);
acceleration_deg_s2(1, :) = initialAcceleration_deg_s2;
acceleration_deg_s2(end, :) = goalAcceleration_deg_s2;
secant_deg_s = diff(position_deg, 1, 1) ./ segmentDuration_s;
for knotIndex = 2:knotCount - 1
    if knotIndex == 2 || knotIndex == knotCount - 1
        continue;
    end
    beforeDuration_s = segmentDuration_s(knotIndex - 1);
    afterDuration_s = segmentDuration_s(knotIndex);
    if norm(secant_deg_s(knotIndex - 1, :)) <= 1e-12 || ...
            norm(secant_deg_s(knotIndex, :)) <= 1e-12
        continue;
    end
    acceleration_deg_s2(knotIndex, :) = tangentScale * 2 * ...
        (secant_deg_s(knotIndex, :) - ...
        secant_deg_s(knotIndex - 1, :)) / ...
        (beforeDuration_s + afterDuration_s);
end
end

function velocity_deg_s = interiorKnotVelocity( ...
        position_deg, segmentDuration_s, tangentScale, ...
        initialVelocity_deg_s, goalVelocity_deg_s)
% PURPOSE
%   - Form continuous monotone knot velocities from the RL route.
knotCount = size(position_deg, 1);
velocity_deg_s = zeros(knotCount, 2);
velocity_deg_s(1, :) = initialVelocity_deg_s;
velocity_deg_s(end, :) = goalVelocity_deg_s;
secant_deg_s = diff(position_deg, 1, 1) ./ segmentDuration_s;
for knotIndex = 2:knotCount - 1
    beforeDuration_s = segmentDuration_s(knotIndex - 1);
    afterDuration_s = segmentDuration_s(knotIndex);
    if knotIndex == 2
        velocity_deg_s(knotIndex, :) = ...
            2 * secant_deg_s(knotIndex - 1, :) - ...
            initialVelocity_deg_s;
        continue;
    elseif knotIndex == knotCount - 1
        velocity_deg_s(knotIndex, :) = ...
            2 * secant_deg_s(knotIndex, :) - goalVelocity_deg_s;
        continue;
    end
    beforeWeight_s = 2 * afterDuration_s + beforeDuration_s;
    afterWeight_s = afterDuration_s + 2 * beforeDuration_s;
    for axisIndex = 1:2
        before_deg_s = secant_deg_s(knotIndex - 1, axisIndex);
        after_deg_s = secant_deg_s(knotIndex, axisIndex);
        if before_deg_s * after_deg_s <= 0
            continue;
        end
        monotoneVelocity_deg_s = ...
            (beforeWeight_s + afterWeight_s) / ...
            (beforeWeight_s / before_deg_s + ...
            afterWeight_s / after_deg_s);
        velocity_deg_s(knotIndex, axisIndex) = ...
            tangentScale * monotoneVelocity_deg_s;
    end
end
end

function coefficient = quinticCoefficients( ...
        position_deg, velocity_deg_s, acceleration_deg_s2, ...
        segmentDuration_s)
% PURPOSE
%   - Build exact quintic Hermite coefficients for all route intervals.
segmentCount = numel(segmentDuration_s);
coefficient = zeros(6, 2, segmentCount);
for segmentIndex = 1:segmentCount
    duration_s = segmentDuration_s(segmentIndex);
    firstPosition = position_deg(segmentIndex, :);
    firstVelocity = velocity_deg_s(segmentIndex, :) * duration_s;
    firstAcceleration = ...
        acceleration_deg_s2(segmentIndex, :) * duration_s^2;
    finalVelocity = velocity_deg_s(segmentIndex + 1, :) * duration_s;
    finalAcceleration = ...
        acceleration_deg_s2(segmentIndex + 1, :) * duration_s^2;
    coefficient(1, :, segmentIndex) = firstPosition;
    coefficient(2, :, segmentIndex) = firstVelocity;
    coefficient(3, :, segmentIndex) = 0.5 * firstAcceleration;
    positionResidual = position_deg(segmentIndex + 1, :) - ...
        firstPosition - firstVelocity - 0.5 * firstAcceleration;
    velocityResidual = finalVelocity - firstVelocity - firstAcceleration;
    accelerationResidual = finalAcceleration - firstAcceleration;
    coefficient(4, :, segmentIndex) = ...
        10 * positionResidual - 4 * velocityResidual + ...
        0.5 * accelerationResidual;
    coefficient(5, :, segmentIndex) = ...
        -15 * positionResidual + 7 * velocityResidual - ...
        accelerationResidual;
    coefficient(6, :, segmentIndex) = ...
        6 * positionResidual - 3 * velocityResidual + ...
        0.5 * accelerationResidual;
end
end

function [trajectory, extrema] = sampleQuinticMotion( ...
        coefficient, segmentDuration_s, initialTime_s, sampleTime_s)
% PURPOSE
%   - Sample the exact quintic state and certify polynomial extrema.
time_s = initialTime_s;
position_deg = reshape(coefficient(1, :, 1), 1, 2);
velocity_deg_s = zeros(1, 2);
acceleration_deg_s2 = zeros(1, 2);
jerk_deg_s3 = zeros(1, 2);
maximumVelocity_deg_s = zeros(1, 2);
maximumAcceleration_deg_s2 = zeros(1, 2);
maximumJerk_deg_s3 = zeros(1, 2);
positionBounds_deg = [position_deg; position_deg];
elapsed_s = 0;
for segmentIndex = 1:numel(segmentDuration_s)
    duration_s = segmentDuration_s(segmentIndex);
    sampleCount = max(1, ceil(duration_s / sampleTime_s));
    localTime_s = linspace(0, duration_s, sampleCount + 1).';
    if segmentIndex > 1
        localTime_s = localTime_s(2:end);
    end
    normalizedTime = localTime_s / duration_s;
    [position, velocity, acceleration, jerk] = evaluateQuintic( ...
        coefficient(:, :, segmentIndex), normalizedTime, duration_s);
    if segmentIndex == 1
        position_deg = position;
        velocity_deg_s = velocity;
        acceleration_deg_s2 = acceleration;
        jerk_deg_s3 = jerk;
        time_s = initialTime_s + localTime_s;
    else
        position_deg = [position_deg; position]; %#ok<AGROW>
        velocity_deg_s = [velocity_deg_s; velocity]; %#ok<AGROW>
        acceleration_deg_s2 = [acceleration_deg_s2; ...
            acceleration]; %#ok<AGROW>
        jerk_deg_s3 = [jerk_deg_s3; jerk]; %#ok<AGROW>
        time_s = [time_s; initialTime_s + elapsed_s + ...
            localTime_s]; %#ok<AGROW>
    end
    segmentExtrema = exactSegmentExtrema( ...
        coefficient(:, :, segmentIndex), duration_s);
    maximumVelocity_deg_s = max(maximumVelocity_deg_s, ...
        segmentExtrema.MaximumVelocity_deg_s);
    maximumAcceleration_deg_s2 = max(maximumAcceleration_deg_s2, ...
        segmentExtrema.MaximumAcceleration_deg_s2);
    maximumJerk_deg_s3 = max(maximumJerk_deg_s3, ...
        segmentExtrema.MaximumJerk_deg_s3);
    positionBounds_deg(1, :) = min(positionBounds_deg(1, :), ...
        segmentExtrema.PositionBounds_deg(1, :));
    positionBounds_deg(2, :) = max(positionBounds_deg(2, :), ...
        segmentExtrema.PositionBounds_deg(2, :));
    elapsed_s = elapsed_s + duration_s;
end
trajectory = struct("time_s", time_s, "position_deg", position_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2, ...
    "jerk_deg_s3", jerk_deg_s3);
extrema = struct( ...
    "MaximumVelocity_deg_s", maximumVelocity_deg_s, ...
    "MaximumAcceleration_deg_s2", maximumAcceleration_deg_s2, ...
    "MaximumJerk_deg_s3", maximumJerk_deg_s3, ...
    "PositionBounds_deg", positionBounds_deg);
end

function [position, velocity, acceleration, jerk] = ...
        evaluateQuintic(coefficient, normalizedTime, duration_s)
% PURPOSE
%   - Evaluate one two-axis quintic and its physical derivatives.
u = normalizedTime;
position = coefficient(1, :) + u .* coefficient(2, :) + ...
    u.^2 .* coefficient(3, :) + u.^3 .* coefficient(4, :) + ...
    u.^4 .* coefficient(5, :) + u.^5 .* coefficient(6, :);
velocity = (coefficient(2, :) + 2 * u .* coefficient(3, :) + ...
    3 * u.^2 .* coefficient(4, :) + ...
    4 * u.^3 .* coefficient(5, :) + ...
    5 * u.^4 .* coefficient(6, :)) / duration_s;
acceleration = (2 * coefficient(3, :) + ...
    6 * u .* coefficient(4, :) + ...
    12 * u.^2 .* coefficient(5, :) + ...
    20 * u.^3 .* coefficient(6, :)) / duration_s^2;
jerk = (6 * coefficient(4, :) + ...
    24 * u .* coefficient(5, :) + ...
    60 * u.^2 .* coefficient(6, :)) / duration_s^3;
end

function extrema = exactSegmentExtrema(coefficient, duration_s)
% PURPOSE
%   - Evaluate every bounded real stationary point of one quintic segment.
maximumVelocity_deg_s = zeros(1, 2);
maximumAcceleration_deg_s2 = zeros(1, 2);
maximumJerk_deg_s3 = zeros(1, 2);
positionBounds_deg = zeros(2, 2);
for axisIndex = 1:2
    positionPolynomial = flip(coefficient(:, axisIndex).');
    velocityPolynomial = polyder(positionPolynomial);
    accelerationPolynomial = polyder(velocityPolynomial);
    jerkPolynomial = polyder(accelerationPolynomial);
    snapPolynomial = polyder(jerkPolynomial);
    positionTimes = unique([0; 1; boundedRoots( ...
        velocityPolynomial)]);
    velocityTimes = unique([0; 1; boundedRoots( ...
        accelerationPolynomial)]);
    accelerationTimes = unique([0; 1; boundedRoots( ...
        jerkPolynomial)]);
    jerkTimes = unique([0; 1; boundedRoots(snapPolynomial)]);
    positionValues = polyval(positionPolynomial, positionTimes);
    velocityValues = polyval(velocityPolynomial, velocityTimes) / ...
        duration_s;
    accelerationValues = polyval( ...
        accelerationPolynomial, accelerationTimes) / duration_s^2;
    jerkValues = polyval(jerkPolynomial, jerkTimes) / duration_s^3;
    positionBounds_deg(:, axisIndex) = ...
        [min(positionValues); max(positionValues)];
    maximumVelocity_deg_s(axisIndex) = max(abs(velocityValues));
    maximumAcceleration_deg_s2(axisIndex) = ...
        max(abs(accelerationValues));
    maximumJerk_deg_s3(axisIndex) = max(abs(jerkValues));
end
extrema = struct( ...
    "MaximumVelocity_deg_s", maximumVelocity_deg_s, ...
    "MaximumAcceleration_deg_s2", maximumAcceleration_deg_s2, ...
    "MaximumJerk_deg_s3", maximumJerk_deg_s3, ...
    "PositionBounds_deg", positionBounds_deg);
end

function values = boundedRoots(coefficients)
% PURPOSE
%   - Return real polynomial roots in the closed unit interval.
firstNonzero = find(abs(coefficients) > 1e-14, 1, "first");
if isempty(firstNonzero) || firstNonzero == numel(coefficients)
    values = zeros(0, 1);
    return;
end
values = roots(coefficients(firstNonzero:end));
values = real(values(abs(imag(values)) <= 1e-10 & ...
    real(values) >= 0 & real(values) <= 1));
end

function [validation, clearanceDiagnostics] = validateTrajectory( ...
        trajectory, extrema, obstacleField, initialState, goalState, ...
        limits, options)
% PURPOSE
%   - Independently validate exact polynomial limits and moving clearance.
tolerance = options.KinematicValidationTolerance;
velocityWithinLimits = all(extrema.MaximumVelocity_deg_s <= ...
    limits.maxVelocity_deg_s + tolerance);
accelerationWithinLimits = all(extrema.MaximumAcceleration_deg_s2 <= ...
    limits.maxAcceleration_deg_s2 + tolerance);
jerkWithinLimits = all(extrema.MaximumJerk_deg_s3 <= ...
    limits.maxJerk_deg_s3 + tolerance);
positionWithinBounds = ...
    extrema.PositionBounds_deg(1, 2) >= ...
        options.ElevationInterval_deg(1) - tolerance && ...
    extrema.PositionBounds_deg(2, 2) <= ...
        options.ElevationInterval_deg(2) + tolerance;
if ~options.AllowAzimuthWrapping
    positionWithinBounds = positionWithinBounds && ...
        extrema.PositionBounds_deg(1, 1) >= ...
            options.AzimuthInterval_deg(1) - tolerance && ...
        extrema.PositionBounds_deg(2, 1) <= ...
            options.AzimuthInterval_deg(2) + tolerance;
end
bufferedChordQueryClear = false;
collisionSafetyProven = false;
collisionFree = false;
curveDeviationBound_deg = Inf;
clearanceDiagnostics = emptyClearanceDiagnostics();
initialError = [trajectory.position_deg(1, :) - ...
    initialState.position_deg, trajectory.velocity_deg_s(1, :) - ...
    initialState.velocity_deg_s, trajectory.acceleration_deg_s2(1, :) - ...
    initialState.acceleration_deg_s2];
terminalError = [trajectory.position_deg(end, :) - ...
    goalState.position_deg, trajectory.velocity_deg_s(end, :) - ...
    goalState.velocity_deg_s, trajectory.acceleration_deg_s2(end, :) - ...
    goalState.acceleration_deg_s2];
initialStateMatched = max(abs(initialError)) <= tolerance;
terminalStateMatched = max(abs(terminalError)) <= tolerance;
goalTimeSatisfied = trajectory.time_s(end) <= ...
    goalState.time_s + tolerance;
if options.GoalTimeMode == "fixedarrival"
    goalTimeSatisfied = abs(trajectory.time_s(end) - ...
        goalState.time_s) <= tolerance;
end
canCheckCollision = velocityWithinLimits && accelerationWithinLimits && ...
    jerkWithinLimits && positionWithinBounds && initialStateMatched && ...
    terminalStateMatched && goalTimeSatisfied;
if canCheckCollision
    collisionMask = queryAzElTimedPathCollision( ...
        obstacleField, trajectory.time_s, trajectory.position_deg, ...
        struct("BoundaryIsOccupied", true, "TimePaddingSamples", ...
        options.CollisionTimePaddingSamples, ...
        "StopAtFirstCollision", true));
    bufferedChordQueryClear = ~any(collisionMask);
    maximumStep_s = max(diff(trajectory.time_s));
    maximumAccelerationNorm_deg_s2 = norm( ...
        extrema.MaximumAcceleration_deg_s2);
    curveDeviationBound_deg = maximumAccelerationNorm_deg_s2 * ...
        maximumStep_s^2 / 8;
    if bufferedChordQueryClear
        [collisionSafetyProven, clearanceDiagnostics] = ...
            azElInternal.certifyAzElTimedPathClearance( ...
            obstacleField, trajectory.time_s, trajectory.position_deg, ...
            curveDeviationBound_deg);
    end
    collisionFree = bufferedChordQueryClear && collisionSafetyProven;
end
checks = [all(isfinite(trajectory.time_s)), ...
    all(diff(trajectory.time_s) > 0), initialStateMatched, ...
    terminalStateMatched, goalTimeSatisfied, collisionFree, ...
    velocityWithinLimits, accelerationWithinLimits, jerkWithinLimits, ...
    positionWithinBounds];
issueNames = ["finiteTime" "strictTime" "initialState" ...
    "terminalState" "goalTime" "collision" "velocity" ...
    "acceleration" "jerk" "workspace"];
issues = issueNames(~checks);
passed = all(checks);
message = "The direct RL policy motion passed all checks.";
if ~passed
    message = "The direct RL policy motion failed: " + ...
        strjoin(issues, ", ") + ".";
end
validation = struct("Passed", passed, "Message", message, ...
    "TimeIsStrictlyIncreasing", checks(2), ...
    "InitialStateMatched", initialStateMatched, ...
    "TerminalStateMatched", terminalStateMatched, ...
    "GoalTimeSatisfied", goalTimeSatisfied, ...
    "CollisionFree", collisionFree, ...
    "BufferedChordQueryClear", bufferedChordQueryClear, ...
    "CollisionSafetyProven", collisionSafetyProven, ...
    "CollisionValidationScope", ...
    "Timed chords plus a conservative quintic-curve clearance tube.", ...
    "CurveSubdivisionConverged", collisionSafetyProven, ...
    "MaximumCurveDeviationBound_deg", curveDeviationBound_deg, ...
    "VelocityWithinLimits", velocityWithinLimits, ...
    "AccelerationWithinLimits", accelerationWithinLimits, ...
    "JerkWithinLimits", jerkWithinLimits, ...
    "PositionWithinBounds", positionWithinBounds, ...
    "ContinuousPolynomialExtremaVerified", true, ...
    "DynamicsDefectWithinTolerance", true, ...
    "InitialStateError", initialError, ...
    "TerminalStateError", terminalError, ...
    "MaximumDynamicsDefect", 0, ...
    "DynamicsConsistencyScope", ...
    "Exact analytic derivatives of piecewise-quintic policy motion.", ...
    "MaximumVelocity_deg_s", extrema.MaximumVelocity_deg_s, ...
    "MaximumAcceleration_deg_s2", ...
        extrema.MaximumAcceleration_deg_s2, ...
    "MaximumJerk_deg_s3", extrema.MaximumJerk_deg_s3, ...
    "Issues", issues);
end

function candidate = copySuccessfulTrial(candidate, trial)
% PURPOSE
%   - Copy one validated direct policy motion into the candidate schema.
candidate.Success = true;
candidate.Message = trial.Message;
candidate.TerminationReason = trial.TerminationReason;
candidate.ArrivalTime_s = trial.ArrivalTime_s;
candidate.MotionDuration_s = trial.MotionDuration_s;
candidate.IntegratedSquaredJerk = trial.IntegratedSquaredJerk;
candidate.MaximumVelocity_deg_s = trial.MaximumVelocity_deg_s;
candidate.MaximumAcceleration_deg_s2 = ...
    trial.MaximumAcceleration_deg_s2;
candidate.MaximumJerk_deg_s3 = trial.MaximumJerk_deg_s3;
candidate.CollisionFree = trial.CollisionFree;
candidate.BufferedChordQueryClear = trial.BufferedChordQueryClear;
candidate.CollisionSafetyProven = trial.CollisionSafetyProven;
candidate.CollisionClearanceDiagnostics = ...
    trial.CollisionClearanceDiagnostics;
candidate.ReferencePosition_deg = trial.ReferencePosition_deg;
candidate.ReferenceTimeFraction = trial.ReferenceTimeFraction;
candidate.Trajectory = trial.Trajectory;
candidate.Validation = trial.Validation;
candidate.SelectedTangentScale = trial.TangentScale;
candidate.SelectedTimeLawBlend = trial.TimeLawBlend;
end

function candidate = emptyCandidate()
% PURPOSE
%   - Define the stable result for one direct RL policy route.
candidate = struct("Success", false, ...
    "Message", "The direct RL motion was not evaluated.", ...
    "TerminationReason", "notEvaluated", ...
    "TimedSeedLawUsed", false, ...
    "SeedRouteTimeFraction", zeros(0, 1), ...
    "SeedRouteProgress", zeros(0, 1), ...
    "DurationTrial_s", zeros(0, 1), ...
    "DurationFeasibleHistory", false(0, 1), ...
    "DurationIntegratedSquaredJerk", zeros(0, 1), ...
    "DurationMaximumVelocity_deg_s", zeros(0, 2), ...
    "DurationMaximumAcceleration_deg_s2", zeros(0, 2), ...
    "DurationMaximumJerk_deg_s3", zeros(0, 2), ...
    "DurationTangentScale", zeros(0, 1), ...
    "DurationTimeLawBlend", zeros(0, 1), ...
    "DurationIssueSummary", strings(0, 1), ...
    "PolicyEvaluationCount", 0, "SelectedTangentScale", NaN, ...
    "SelectedTimeLawBlend", NaN, ...
    "SolverExitFlag", NaN, "SolverMessage", "No solver is used.", ...
    "SolverExitFlagHistory", zeros(0, 1), ...
    "SolverMessageHistory", strings(0, 1), ...
    "SolverIterationCount", 0, "ArrivalTime_s", Inf, ...
    "MotionDuration_s", Inf, "IntegratedSquaredJerk", Inf, ...
    "MaximumVelocity_deg_s", [Inf Inf], ...
    "MaximumAcceleration_deg_s2", [Inf Inf], ...
    "MaximumJerk_deg_s3", [Inf Inf], "CollisionFree", false, ...
    "BufferedChordQueryClear", false, ...
    "CollisionSafetyProven", false, ...
    "CollisionClearanceDiagnostics", emptyClearanceDiagnostics(), ...
    "ReferencePosition_deg", zeros(0, 2), ...
    "ReferenceTimeFraction", zeros(0, 1), ...
    "Trajectory", emptyTrajectory(), "Validation", emptyValidation(), ...
    "ElapsedTime_s", 0);
end

function trial = emptyTrial()
% PURPOSE
%   - Define one direct policy-motion trial.
trial = struct("Success", false, "Message", "Not evaluated.", ...
    "TerminationReason", "notEvaluated", "ArrivalTime_s", Inf, ...
    "MotionDuration_s", Inf, "IntegratedSquaredJerk", Inf, ...
    "TangentScale", NaN, "TimeLawBlend", NaN, ...
    "MaximumVelocity_deg_s", [Inf Inf], ...
    "MaximumAcceleration_deg_s2", [Inf Inf], ...
    "MaximumJerk_deg_s3", [Inf Inf], "CollisionFree", false, ...
    "BufferedChordQueryClear", false, ...
    "CollisionSafetyProven", false, ...
    "CollisionClearanceDiagnostics", emptyClearanceDiagnostics(), ...
    "ReferencePosition_deg", zeros(0, 2), ...
    "ReferenceTimeFraction", zeros(0, 1), ...
    "Trajectory", emptyTrajectory(), "Validation", emptyValidation());
end

function trajectory = emptyTrajectory()
% PURPOSE
%   - Define empty two-axis trajectory histories.
trajectory = struct("time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2));
end

function validation = emptyValidation()
% PURPOSE
%   - Define validation fields before a policy motion is available.
validation = struct("Passed", false, "Message", "Not validated.", ...
    "TimeIsStrictlyIncreasing", false, ...
    "InitialStateMatched", false, "TerminalStateMatched", false, ...
    "GoalTimeSatisfied", false, "CollisionFree", false, ...
    "BufferedChordQueryClear", false, ...
    "CollisionSafetyProven", false, "CollisionValidationScope", "", ...
    "CurveSubdivisionConverged", false, ...
    "MaximumCurveDeviationBound_deg", Inf, ...
    "VelocityWithinLimits", false, ...
    "AccelerationWithinLimits", false, "JerkWithinLimits", false, ...
    "PositionWithinBounds", false, ...
    "ContinuousPolynomialExtremaVerified", false, ...
    "DynamicsDefectWithinTolerance", false, ...
    "InitialStateError", inf(1, 6), ...
    "TerminalStateError", inf(1, 6), ...
    "MaximumDynamicsDefect", Inf, "DynamicsConsistencyScope", "", ...
    "MaximumVelocity_deg_s", [Inf Inf], ...
    "MaximumAcceleration_deg_s2", [Inf Inf], ...
    "MaximumJerk_deg_s3", [Inf Inf], "Issues", "notValidated");
end

function diagnostics = emptyClearanceDiagnostics()
% PURPOSE
%   - Define the stable moving-clearance certificate fields.
diagnostics = struct("ProvenClear", false, ...
    "UnresolvedPathSegmentMask", false(0, 1), ...
    "UnresolvedPathSegmentCount", 0, ...
    "TopologyMismatchIntervalCount", 0, ...
    "EvaluatedEdgeIntervalCount", 0, ...
    "BroadPhaseRejectedEdgeIntervalCount", 0, ...
    "SubdivisionBoxCount", 0, "MaximumDepthReached", 0, ...
    "MaximumSubdivisionDepth", 18, "MaximumBoxesPerEdge", 20000, ...
    "MinimumProvenLowerBound_deg", NaN);
end
