function candidate = projectAzElRlMotion(route_deg, obstacleField, ...
        initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   candidate = azElInternal.projectAzElRlMotion( ...
%       route_deg, obstacleField, initialState, goalState, limits, options)
%**************************************************************************
% PURPOSE
%   - Project one RL-shaped route to a continuous-jerk motion with a convex
%     quadratic program.
%   - Validate the complete timed motion against moving protected geometry.
%**************************************************************************
% INPUTS
%   - route_deg (N-by-2 finite numeric matrix)
%       RL-shaped [azimuth elevation] route with at least two points.
%   - obstacleField (scalar packed-obstacle struct)
%       Protected static or time-varying obstacle geometry.
%   - initialState, goalState (scalar structs)
%       Endpoint time, position, velocity, and acceleration states.
%   - limits (scalar struct)
%       Positive two-axis velocity, acceleration, and jerk limits.
%   - options (scalar struct)
%       Resolved projection, timing, workspace, and validation controls.
%**************************************************************************
% OUTPUTS
%   - candidate (scalar struct)
%       Stable success-or-failure record with trajectory, validation,
%       solver history, collision proof, and elapsed time.
%**************************************************************************
% UNITS
%   - Position is degrees. Time is seconds. Derivative units are stated in
%     field names. Histories are N-by-2 [azimuth elevation].
%**************************************************************************

%% Section 1: Validate Inputs And Build The Route Law

candidateTimer = tic;
route_deg = removeDuplicateRoutePoints(route_deg);
validateattributes(route_deg, {'numeric'}, ...
    {'real', 'finite', '2d', 'ncols', 2, 'nonempty'});
if size(route_deg, 1) < 2
    error("projectAzElRlMotion:InvalidRoute", ...
        "route_deg must contain two distinct positions.");
end
requiredOptionNames = ["GoalTimeMode" "SampleTime_s" ...
    "ProjectionSegmentCount" "ProjectionRouteTube_deg" ...
    "ProjectionDurationTolerance_s" ...
    "ObstacleConstraintTolerance_deg" ...
    "KinematicValidationTolerance" "CollisionTimePaddingSamples" ...
    "EnableJerkTieBreak" "ArrivalTimeTieTolerance_s" ...
    "RemainingPlanningTime_s" ...
    "AllowAzimuthWrapping" "AzimuthInterval_deg" ...
    "ElevationInterval_deg" "SeedRouteTimeFraction" ...
    "SeedRouteProgress" "SeedRouteDuration_s"];
if ~isstruct(options) || ~isscalar(options) || ...
        ~all(isfield(options, requiredOptionNames))
    error("projectAzElRlMotion:InvalidOptions", ...
        "options is missing a required RL projection field.");
end
candidate = emptyCandidate();
candidate.SeedRouteTimeFraction = ...
    double(options.SeedRouteTimeFraction(:));
candidate.SeedRouteProgress = double(options.SeedRouteProgress(:));
candidate.TimedSeedLawUsed = ...
    validTimedSeedLaw(candidate.SeedRouteTimeFraction, ...
    candidate.SeedRouteProgress, options.SeedRouteDuration_s);
routeLaw = buildRouteLaw(route_deg, candidate, limits);

%% Section 2: Scan And Refine Bounded Duration Trials

horizonDuration_s = goalState.time_s - initialState.time_s;
[durationTrials_s, durationLowerBound_s] = durationTrials( ...
    route_deg, routeLaw, initialState, goalState, limits, ...
    options, horizonDuration_s);
trialResults = cell(0, 1);
successfulIndex = 0;
for trialIndex = 1:numel(durationTrials_s)
    if toc(candidateTimer) >= options.RemainingPlanningTime_s
        break;
    end
    trialResults{end + 1, 1} = solveDuration( ...
        route_deg, routeLaw, durationTrials_s(trialIndex), ...
        obstacleField, initialState, goalState, limits, ...
        options); %#ok<AGROW>
    if trialResults{end}.Success
        successfulIndex = numel(trialResults);
        break;
    end
end

if successfulIndex > 0 && options.GoalTimeMode == "earliestarrival"
    upperDuration_s = trialResults{successfulIndex}.MotionDuration_s;
    if successfulIndex > 1
        lowerDuration_s = ...
            trialResults{successfulIndex - 1}.MotionDuration_s;
    else
        lowerDuration_s = durationLowerBound_s;
    end
    while upperDuration_s - lowerDuration_s > ...
            options.ProjectionDurationTolerance_s && ...
            toc(candidateTimer) < options.RemainingPlanningTime_s
        middleDuration_s = 0.5 * ...
            (lowerDuration_s + upperDuration_s);
        middleTrial = solveDuration( ...
            route_deg, routeLaw, middleDuration_s, obstacleField, ...
            initialState, goalState, limits, options);
        trialResults{end + 1, 1} = middleTrial; %#ok<AGROW>
        if middleTrial.Success
            upperDuration_s = middleDuration_s;
            successfulIndex = numel(trialResults);
        else
            lowerDuration_s = middleDuration_s;
        end
    end
end

if successfulIndex > 0 && options.GoalTimeMode == "earliestarrival" && ...
        options.EnableJerkTieBreak && ...
        options.ArrivalTimeTieTolerance_s > ...
        options.ProjectionDurationTolerance_s && ...
        toc(candidateTimer) < options.RemainingPlanningTime_s
    earliestDuration_s = trialResults{successfulIndex}.MotionDuration_s;
    smoothDuration_s = min(horizonDuration_s, earliestDuration_s + ...
        options.ArrivalTimeTieTolerance_s);
    if smoothDuration_s > earliestDuration_s + ...
            options.ProjectionDurationTolerance_s
        trialResults{end + 1, 1} = solveDuration( ...
            route_deg, routeLaw, smoothDuration_s, obstacleField, ...
            initialState, goalState, limits, options);
    end
    feasibleIndex = find(cellfun(@(trial) trial.Success, trialResults));
    if ~isempty(feasibleIndex)
        ranking = zeros(numel(feasibleIndex), 3);
        for rankIndex = 1:numel(feasibleIndex)
            trial = trialResults{feasibleIndex(rankIndex)};
            ranking(rankIndex, :) = [trial.IntegratedSquaredJerk, ...
                trial.MotionDuration_s, feasibleIndex(rankIndex)];
        end
        [~, bestOrder] = sortrows(ranking, [1 2 3]);
        successfulIndex = feasibleIndex(bestOrder(1));
    end
end

%% Section 3: Select The Earliest Validated Trial

evaluatedCount = numel(trialResults);
candidate.DurationTrial_s = zeros(evaluatedCount, 1);
candidate.SolverExitFlagHistory = zeros(evaluatedCount, 1);
candidate.SolverMessageHistory = strings(evaluatedCount, 1);
candidate.DurationFeasibleHistory = false(evaluatedCount, 1);
candidate.DurationIntegratedSquaredJerk = inf(evaluatedCount, 1);
candidate.DurationMaximumVelocity_deg_s = inf(evaluatedCount, 2);
candidate.DurationMaximumAcceleration_deg_s2 = inf(evaluatedCount, 2);
candidate.DurationIssueSummary = strings(evaluatedCount, 1);
for trialIndex = 1:evaluatedCount
    trial = trialResults{trialIndex};
    candidate.DurationTrial_s(trialIndex) = trial.MotionDuration_s;
    candidate.SolverExitFlagHistory(trialIndex) = trial.SolverExitFlag;
    candidate.SolverMessageHistory(trialIndex) = trial.SolverMessage;
    candidate.DurationFeasibleHistory(trialIndex) = trial.Success;
    candidate.DurationIntegratedSquaredJerk(trialIndex) = ...
        trial.IntegratedSquaredJerk;
    candidate.DurationMaximumVelocity_deg_s(trialIndex, :) = ...
        trial.MaximumVelocity_deg_s;
    candidate.DurationMaximumAcceleration_deg_s2(trialIndex, :) = ...
        trial.MaximumAcceleration_deg_s2;
    candidate.DurationIssueSummary(trialIndex) = ...
        strjoin(string(trial.Validation.Issues), ",");
end
if successfulIndex > 0
    candidate = copySuccessfulTrial(candidate, ...
        trialResults{successfulIndex});
else
    candidate.Message = "No RL projection duration passed validation.";
    candidate.TerminationReason = "convexProjectionInfeasible";
    if evaluatedCount > 0
        lastTrial = trialResults{evaluatedCount};
        candidate.SolverExitFlag = lastTrial.SolverExitFlag;
        candidate.SolverMessage = lastTrial.SolverMessage;
        candidate.Message = lastTrial.Message;
        candidate.Trajectory = lastTrial.Trajectory;
        candidate.Validation = lastTrial.Validation;
        candidate.MaximumVelocity_deg_s = ...
            lastTrial.MaximumVelocity_deg_s;
        candidate.MaximumAcceleration_deg_s2 = ...
            lastTrial.MaximumAcceleration_deg_s2;
        candidate.MaximumJerk_deg_s3 = lastTrial.MaximumJerk_deg_s3;
        candidate.CollisionFree = lastTrial.CollisionFree;
        candidate.BufferedChordQueryClear = ...
            lastTrial.BufferedChordQueryClear;
        candidate.CollisionSafetyProven = ...
            lastTrial.CollisionSafetyProven;
        candidate.CollisionClearanceDiagnostics = ...
            lastTrial.CollisionClearanceDiagnostics;
        if lastTrial.TerminationReason == "goalTimeInfeasible"
            candidate.TerminationReason = "goalTimeInfeasible";
        end
    end
end
candidate.ElapsedTime_s = toc(candidateTimer);
end

%% Section 4: Local Functions

function route = removeDuplicateRoutePoints(route)
% PURPOSE
%   - Remove consecutive zero-length route edges.
route = double(route);
if size(route, 1) < 2
    return;
end
route = route([true; any(abs(diff(route, 1, 1)) > 1e-12, 2)], :);
end

function isValid = validTimedSeedLaw(timeFraction, progress, duration_s)
% PURPOSE
%   - Check the normalized SIPP route law used by the projection.
isValid = numel(timeFraction) >= 2 && ...
    numel(timeFraction) == numel(progress) && ...
    all(isfinite(timeFraction)) && all(isfinite(progress)) && ...
    all(diff(timeFraction) > 0) && all(diff(progress) >= 0) && ...
    timeFraction(1) >= -1e-10 && timeFraction(end) <= 1 + 1e-10 && ...
    isfinite(duration_s) && duration_s > 0;
end

function routeLaw = buildRouteLaw(route_deg, candidate, limits)
% PURPOSE
%   - Create a normalized progress law from SIPP time or route work.
if candidate.TimedSeedLawUsed
    routeLaw = struct( ...
        "timeFraction", candidate.SeedRouteTimeFraction, ...
        "progress", candidate.SeedRouteProgress);
    return;
end
routeStep_deg = diff(route_deg, 1, 1);
routeWork_s = max(abs(routeStep_deg) ./ ...
    limits.maxVelocity_deg_s, [], 2);
if sum(routeWork_s) <= eps
    progress = linspace(0, 1, size(route_deg, 1)).';
else
    progress = [0; cumsum(routeWork_s)] / sum(routeWork_s);
end
routeLaw = struct("timeFraction", progress, "progress", progress);
end

function [trials_s, lowerBound_s] = durationTrials( ...
        route_deg, routeLaw, initialState, goalState, limits, ...
        options, horizonDuration_s)
% PURPOSE
%   - Build an input-scaled feasibility scan for duration refinement.
tolerance_s = options.ProjectionDurationTolerance_s;
if options.GoalTimeMode == "fixedarrival"
    trials_s = horizonDuration_s;
    lowerBound_s = horizonDuration_s;
    return;
end
routeStep_deg = diff(route_deg, 1, 1);
routeWork_s = sum(max(abs(routeStep_deg) ./ ...
    limits.maxVelocity_deg_s, [], 2));
lowerBound_s = max(tolerance_s, necessaryDurationLowerBound( ...
    initialState, goalState, limits));
motionResponse_s = max(limits.maxVelocity_deg_s ./ ...
    limits.maxAcceleration_deg_s2 + limits.maxAcceleration_deg_s2 ./ ...
    limits.maxJerk_deg_s3);
nominalDuration_s = max(lowerBound_s, routeWork_s + motionResponse_s);
initialTrials_s = [lowerBound_s; nominalDuration_s];
if validTimedSeedLaw(routeLaw.timeFraction, routeLaw.progress, ...
        options.SeedRouteDuration_s)
    seedDuration_s = min(horizonDuration_s, ...
        double(options.SeedRouteDuration_s));
    initialTrials_s = [initialTrials_s; ...
        max(lowerBound_s, seedDuration_s - tolerance_s); ...
        max(lowerBound_s, seedDuration_s)];
end
initialTrials_s = unique(sort(initialTrials_s));
initialTrials_s = initialTrials_s( ...
    initialTrials_s <= horizonDuration_s + 1e-12);

fineStep_s = max(4 * tolerance_s, 0.025 * motionResponse_s);
fineEnd_s = min(horizonDuration_s, ...
    nominalDuration_s + 0.25 * motionResponse_s);
fineTrials_s = (nominalDuration_s + fineStep_s:fineStep_s: ...
    fineEnd_s).';
scanStart_s = max([fineTrials_s; initialTrials_s; lowerBound_s]);
scanStep_s = max(motionResponse_s, fineStep_s);
coarseTrials_s = zeros(0, 1);
while scanStart_s < horizonDuration_s - 1e-12
    scanStart_s = min(horizonDuration_s, scanStart_s + scanStep_s);
    coarseTrials_s(end + 1, 1) = scanStart_s; %#ok<AGROW>
    scanStep_s = 2 * scanStep_s;
end
trials_s = unique(sort([initialTrials_s; fineTrials_s; ...
    coarseTrials_s; horizonDuration_s]));
end

function trial = solveDuration(route_deg, routeLaw, duration_s, ...
        obstacleField, initialState, goalState, limits, options)
% PURPOSE
%   - Solve and validate one fixed-duration convex jerk projection.
trial = emptyTrial();
trial.MotionDuration_s = duration_s;
trial.ArrivalTime_s = initialState.time_s + duration_s;
necessaryDuration_s = necessaryDurationLowerBound( ...
    initialState, goalState, limits);
if duration_s + options.ProjectionDurationTolerance_s < ...
        necessaryDuration_s
    trial.Message = "The goal time violates a necessary velocity, " + ...
        "acceleration, or jerk duration bound.";
    trial.TerminationReason = "goalTimeInfeasible";
    return;
end
segmentCount = options.ProjectionSegmentCount;
jerkKnotCount = segmentCount + 1;
step_s = duration_s / segmentCount;
[positionMap, velocityMap, accelerationMap, stateBase] = ...
    responseMap(segmentCount, step_s, initialState);
knotFraction = linspace(0, 1, jerkKnotCount).';
progress = interp1(routeLaw.timeFraction, routeLaw.progress, ...
    knotFraction, "linear", "extrap");
progress = min(1, max(0, progress));
reference_deg = interpolateRoute(route_deg, progress);

[hessian, linearTerm] = jerkObjective(jerkKnotCount, step_s);
[inequalityMatrix, inequalityBound] = projectionConstraints( ...
    positionMap, velocityMap, accelerationMap, stateBase, ...
    reference_deg, obstacleField, initialState.time_s + ...
    duration_s * knotFraction, limits, options);
[equalityMatrix, equalityValue] = endpointEqualities( ...
    positionMap, velocityMap, accelerationMap, stateBase, goalState);
[inequalityMatrix, inequalityBound] = normalizeLinearRows( ...
    inequalityMatrix, inequalityBound);
[equalityMatrix, equalityValue] = normalizeLinearRows( ...
    equalityMatrix, equalityValue);
hessian = sparse(hessian);
inequalityMatrix = sparse(inequalityMatrix);
equalityMatrix = sparse(equalityMatrix);
kinematicGuard = max(options.KinematicValidationTolerance, ...
    10 * options.ProjectionConstraintTolerance);
guardedJerkLimit_deg_s3 = max(0, ...
    limits.maxJerk_deg_s3 - kinematicGuard);
lowerBound = [-guardedJerkLimit_deg_s3(1) * ...
    ones(jerkKnotCount, 1); -guardedJerkLimit_deg_s3(2) * ...
    ones(jerkKnotCount, 1)];
upperBound = -lowerBound;
solverOptions = optimoptions("quadprog", "Display", "off", ...
    "Algorithm", "interior-point-convex", ...
    "MaxIterations", 500, ...
    "ConstraintTolerance", options.ProjectionConstraintTolerance, ...
    "OptimalityTolerance", options.ProjectionOptimalityTolerance);
maximumCorrectionPassCount = 6;
for correctionPassIndex = 1:maximumCorrectionPassCount
    [trialJerkVector, trialObjectiveValue, exitFlag, output] = quadprog( ...
        hessian, linearTerm, inequalityMatrix, inequalityBound, ...
        equalityMatrix, equalityValue, lowerBound, upperBound, [], ...
        solverOptions);
    trial.SolverExitFlag = exitFlag;
    trial.SolverMessage = string(output.message);
    trial.SolverIterationCount = trial.SolverIterationCount + ...
        output.iterations;
    if exitFlag <= 0 || isempty(trialJerkVector)
        trial.Message = "The convex RL projection was infeasible: " + ...
            trial.SolverMessage;
        trial.TerminationReason = "convexProjectionInfeasible";
        if correctionPassIndex == 1
            return;
        end
        break;
    end
    jerkVector = trialJerkVector;
    objectiveValue = trialObjectiveValue;
    jerkKnot_deg_s3 = [jerkVector(1:jerkKnotCount), ...
        jerkVector(jerkKnotCount + 1:end)];
    trajectory = reconstructTrajectory(jerkKnot_deg_s3, step_s, ...
        initialState, options.SampleTime_s);
    trajectory.time_s = trajectory.time_s + initialState.time_s;
    [validation, clearanceDiagnostics] = validateTrajectory( ...
        trajectory, jerkKnot_deg_s3, step_s, obstacleField, ...
        initialState, goalState, limits, options);
    if validation.Passed
        break;
    end
    correctableIssues = all(ismember(validation.Issues, ...
        ["velocity" "acceleration" "collision" "terminalState"]));
    if ~correctableIssues
        break;
    end
    correctionMatrix = zeros(0, 2 * jerkKnotCount);
    correctionBound = zeros(0, 1);
    if any(ismember(validation.Issues, ["velocity" "acceleration"]))
        [extremaMatrix, extremaBound] = kinematicExtremaConstraints( ...
            jerkKnot_deg_s3, velocityMap, accelerationMap, ...
            stateBase, step_s, limits, options);
        correctionMatrix = [correctionMatrix; extremaMatrix]; %#ok<AGROW>
        correctionBound = [correctionBound; extremaBound]; %#ok<AGROW>
    end
    if any(validation.Issues == "collision")
        [collisionMatrix, collisionBound] = ...
            collisionCorrectionConstraints( ...
            trajectory, clearanceDiagnostics, route_deg, routeLaw, ...
            positionMap, velocityMap, accelerationMap, stateBase, ...
            step_s, obstacleField, initialState.time_s, options);
        correctionMatrix = [correctionMatrix; collisionMatrix]; %#ok<AGROW>
        correctionBound = [correctionBound; collisionBound]; %#ok<AGROW>
    end
    if isempty(correctionBound)
        break;
    end
    [correctionMatrix, correctionBound] = normalizeLinearRows( ...
        correctionMatrix, correctionBound);
    % Each pass adds only extrema from one bounded projection solution.
    inequalityMatrix = [inequalityMatrix; correctionMatrix]; %#ok<AGROW>
    inequalityBound = [inequalityBound; correctionBound]; %#ok<AGROW>
end
trial.Success = validation.Passed;
trial.Message = validation.Message;
trial.TerminationReason = "trajectoryValidationFailed";
if trial.Success
    trial.Message = "The RL convex projection passed validation.";
    trial.TerminationReason = "goalReached";
end
trial.Trajectory = trajectory;
trial.Validation = validation;
trial.CollisionFree = validation.CollisionFree;
trial.BufferedChordQueryClear = validation.BufferedChordQueryClear;
trial.CollisionSafetyProven = validation.CollisionSafetyProven;
trial.CollisionClearanceDiagnostics = clearanceDiagnostics;
trial.IntegratedSquaredJerk = objectiveValue;
trial.MaximumVelocity_deg_s = validation.MaximumVelocity_deg_s;
trial.MaximumAcceleration_deg_s2 = ...
    validation.MaximumAcceleration_deg_s2;
trial.MaximumJerk_deg_s3 = validation.MaximumJerk_deg_s3;
trial.ReferencePosition_deg = reference_deg;
end

function duration_s = necessaryDurationLowerBound( ...
        initialState, goalState, limits)
% PURPOSE
%   - Compute necessary endpoint and displacement duration bounds.
displacementDuration_s = max(abs(goalState.position_deg - ...
    initialState.position_deg) ./ limits.maxVelocity_deg_s);
velocityDuration_s = max(abs(goalState.velocity_deg_s - ...
    initialState.velocity_deg_s) ./ limits.maxAcceleration_deg_s2);
accelerationDuration_s = max(abs(goalState.acceleration_deg_s2 - ...
    initialState.acceleration_deg_s2) ./ limits.maxJerk_deg_s3);
duration_s = max([displacementDuration_s, velocityDuration_s, ...
    accelerationDuration_s]);
end

function [matrix, bound] = collisionCorrectionConstraints( ...
        trajectory, clearanceDiagnostics, route_deg, routeLaw, ...
        positionMap, velocityMap, accelerationMap, stateBase, step_s, ...
        obstacleField, initialTime_s, options)
% PURPOSE
%   - Add obstacle half-spaces at measured colliding curve intervals.
collisionMask = queryAzElTimedPathCollision( ...
    obstacleField, trajectory.time_s, trajectory.position_deg, struct( ...
    "TimePaddingSamples", options.CollisionTimePaddingSamples, ...
    "BoundaryIsOccupied", false));
segmentEndIndex = find(collisionMask);
if isfield(clearanceDiagnostics, "UnresolvedPathSegmentMask")
    unresolvedIndex = find( ...
        clearanceDiagnostics.UnresolvedPathSegmentMask) + 1;
    segmentEndIndex = unique([segmentEndIndex; unresolvedIndex]);
end
segmentEndIndex = segmentEndIndex(segmentEndIndex >= 2 & ...
    segmentEndIndex <= numel(trajectory.time_s));
if isempty(segmentEndIndex)
    matrix = zeros(0, 2 * size(positionMap, 2));
    bound = zeros(0, 1);
    return;
end
maximumCorrectionTimeCount = 64;
if numel(segmentEndIndex) > maximumCorrectionTimeCount
    keepIndex = unique(round(linspace(1, numel(segmentEndIndex), ...
        maximumCorrectionTimeCount)));
    segmentEndIndex = segmentEndIndex(keepIndex);
end
correctionTime_s = unique([ ...
    trajectory.time_s(segmentEndIndex); ...
    0.5 * (trajectory.time_s(segmentEndIndex - 1) + ...
    trajectory.time_s(segmentEndIndex))]);
relativeTime_s = correctionTime_s - initialTime_s;
[samplePositionMap, samplePositionBase_deg] = positionResponseAtTimes( ...
    relativeTime_s, positionMap, velocityMap, accelerationMap, ...
    stateBase, step_s);
duration_s = step_s * (size(positionMap, 1) - 1);
timeFraction = min(1, max(0, relativeTime_s / duration_s));
progress = interp1(routeLaw.timeFraction, routeLaw.progress, ...
    timeFraction, "linear", "extrap");
reference_deg = interpolateRoute(route_deg, min(1, max(0, progress)));
[matrix, bound] = obstacleCorridor( ...
    obstacleField, reference_deg, correctionTime_s, ...
    samplePositionBase_deg, samplePositionMap, options);
end

function [sampleMap, sampleBase_deg] = positionResponseAtTimes( ...
        relativeTime_s, positionMap, velocityMap, accelerationMap, ...
        stateBase, step_s)
% PURPOSE
%   - Evaluate the affine exact-position response at arbitrary times.
segmentCount = size(positionMap, 1) - 1;
knotCount = size(positionMap, 2);
sampleCount = numel(relativeTime_s);
sampleMap = zeros(sampleCount, knotCount);
sampleBase_deg = zeros(sampleCount, 2);
for sampleIndex = 1:sampleCount
    segmentIndex = min(segmentCount, ...
        floor(relativeTime_s(sampleIndex) / step_s) + 1);
    segmentIndex = max(1, segmentIndex);
    segmentStart_s = (segmentIndex - 1) * step_s;
    localTime_s = min(step_s, max(0, ...
        relativeTime_s(sampleIndex) - segmentStart_s));
    sampleMap(sampleIndex, :) = positionMap(segmentIndex, :) + ...
        localTime_s * velocityMap(segmentIndex, :) + ...
        0.5 * localTime_s ^ 2 * accelerationMap(segmentIndex, :);
    sampleMap(sampleIndex, segmentIndex) = ...
        sampleMap(sampleIndex, segmentIndex) + ...
        localTime_s ^ 3 / 6 - localTime_s ^ 4 / (24 * step_s);
    sampleMap(sampleIndex, segmentIndex + 1) = ...
        sampleMap(sampleIndex, segmentIndex + 1) + ...
        localTime_s ^ 4 / (24 * step_s);
    sampleBase_deg(sampleIndex, :) = ...
        stateBase.position_deg(segmentIndex, :) + ...
        localTime_s * stateBase.velocity_deg_s(segmentIndex, :) + ...
        0.5 * localTime_s ^ 2 * ...
        stateBase.acceleration_deg_s2(segmentIndex, :);
end
end

function [matrix, value] = normalizeLinearRows(matrix, value)
% PURPOSE
%   - Scale linear rows without changing their physical feasible set.
if isempty(matrix)
    return;
end
rowScale = max(abs(matrix), [], 2);
rowScale(rowScale < eps) = 1;
matrix = matrix ./ rowScale;
value = value ./ rowScale;
end

function [matrix, bound] = kinematicExtremaConstraints( ...
        jerkKnot_deg_s3, velocityMap, accelerationMap, ...
        stateBase, step_s, limits, options)
% PURPOSE
%   - Add affine bounds at exact extrema found in the last convex solution.
jerkKnotCount = size(jerkKnot_deg_s3, 1);
zeroRow = zeros(1, jerkKnotCount);
matrix = zeros(0, 2 * jerkKnotCount);
bound = zeros(0, 1);
guard = max(options.KinematicValidationTolerance, ...
    10 * options.ProjectionConstraintTolerance);
for axisIndex = 1:2
    axisJerk = jerkKnot_deg_s3(:, axisIndex);
    for segmentIndex = 1:jerkKnotCount - 1
        firstJerk = axisJerk(segmentIndex);
        lastJerk = axisJerk(segmentIndex + 1);
        jerkDifference = lastJerk - firstJerk;
        acceleration0 = ...
            stateBase.acceleration_deg_s2(segmentIndex, axisIndex) + ...
            accelerationMap(segmentIndex, :) * axisJerk;
        accelerationExtremaTime_s = zeros(0, 1);
        if abs(jerkDifference) > 1e-12
            candidateTime_s = -firstJerk * step_s / jerkDifference;
            if candidateTime_s > 0 && candidateTime_s < step_s
                accelerationExtremaTime_s = candidateTime_s;
            end
        end
        velocityExtremaTime_s = boundedRealRoots( ...
            [0.5 * jerkDifference / step_s, firstJerk, ...
            acceleration0], step_s);
        velocityExtremaTime_s = velocityExtremaTime_s( ...
            velocityExtremaTime_s > 0 & ...
            velocityExtremaTime_s < step_s);
        for localTime_s = accelerationExtremaTime_s.'
            axisMap = accelerationMap(segmentIndex, :);
            axisMap(segmentIndex) = axisMap(segmentIndex) + ...
                localTime_s - localTime_s ^ 2 / (2 * step_s);
            axisMap(segmentIndex + 1) = ...
                axisMap(segmentIndex + 1) + ...
                localTime_s ^ 2 / (2 * step_s);
            baseValue = ...
                stateBase.acceleration_deg_s2(segmentIndex, axisIndex);
            [matrix, bound] = appendTwoSidedAxisBound( ...
                matrix, bound, axisMap, zeroRow, axisIndex, ...
                limits.maxAcceleration_deg_s2(axisIndex) - max(guard, ...
                0.001 * limits.maxAcceleration_deg_s2(axisIndex)), ...
                baseValue);
        end
        for localTime_s = velocityExtremaTime_s.'
            axisMap = velocityMap(segmentIndex, :) + ...
                localTime_s * accelerationMap(segmentIndex, :);
            axisMap(segmentIndex) = axisMap(segmentIndex) + ...
                0.5 * localTime_s ^ 2 - ...
                localTime_s ^ 3 / (6 * step_s);
            axisMap(segmentIndex + 1) = ...
                axisMap(segmentIndex + 1) + ...
                localTime_s ^ 3 / (6 * step_s);
            baseValue = stateBase.velocity_deg_s( ...
                segmentIndex, axisIndex) + localTime_s * ...
                stateBase.acceleration_deg_s2(segmentIndex, axisIndex);
            [matrix, bound] = appendTwoSidedAxisBound( ...
                matrix, bound, axisMap, zeroRow, axisIndex, ...
                limits.maxVelocity_deg_s(axisIndex) - max(guard, ...
                0.001 * limits.maxVelocity_deg_s(axisIndex)), baseValue);
        end
    end
end
end

function [matrix, bound] = appendTwoSidedAxisBound( ...
        matrix, bound, axisMap, zeroRow, axisIndex, limit, baseValue)
% PURPOSE
%   - Append one signed affine state bound for one motion axis.
if axisIndex == 1
    fullRow = [axisMap, zeroRow];
else
    fullRow = [zeroRow, axisMap];
end
matrix = [matrix; fullRow; -fullRow];
bound = [bound; limit - baseValue; limit + baseValue];
end

function [hessian, linearTerm] = jerkObjective(knotCount, step_s)
% PURPOSE
%   - Build the exact integrated squared linear-jerk objective.
jerkCost = zeros(knotCount);
for segmentIndex = 1:knotCount - 1
    rows = segmentIndex:segmentIndex + 1;
    jerkCost(rows, rows) = jerkCost(rows, rows) + ...
        step_s / 6 * [2 1; 1 2];
end
hessian = blkdiag(2 * jerkCost, 2 * jerkCost);
linearTerm = zeros(2 * knotCount, 1);
end

function [matrix, bound] = projectionConstraints( ...
        positionMap, velocityMap, accelerationMap, stateBase, ...
        reference_deg, obstacleField, knotTime_s, limits, options)
% PURPOSE
%   - Assemble tube, workspace, kinematic, and obstacle half-spaces.
knotCount = size(positionMap, 1);
zeroMap = zeros(size(positionMap));
matrix = zeros(0, 2 * knotCount);
bound = zeros(0, 1);
for axisIndex = 1:2
    if axisIndex == 1
        positionAxisMap = [positionMap, zeroMap];
        velocityAxisMap = [velocityMap, zeroMap];
        accelerationAxisMap = [accelerationMap, zeroMap];
        workspaceInterval_deg = options.AzimuthInterval_deg;
    else
        positionAxisMap = [zeroMap, positionMap];
        velocityAxisMap = [zeroMap, velocityMap];
        accelerationAxisMap = [zeroMap, accelerationMap];
        workspaceInterval_deg = options.ElevationInterval_deg;
    end
    positionBase_deg = stateBase.position_deg(:, axisIndex);
    velocityBase_deg_s = stateBase.velocity_deg_s(:, axisIndex);
    accelerationBase_deg_s2 = ...
        stateBase.acceleration_deg_s2(:, axisIndex);
    tube_deg = options.ProjectionRouteTube_deg;
    matrix = [matrix; positionAxisMap; -positionAxisMap; ...
        velocityAxisMap; -velocityAxisMap; accelerationAxisMap; ...
        -accelerationAxisMap]; %#ok<AGROW>
    velocityGuard_deg_s = max(options.KinematicValidationTolerance, ...
        10 * options.ProjectionConstraintTolerance);
    accelerationGuard_deg_s2 = max( ...
        options.KinematicValidationTolerance, ...
        10 * options.ProjectionConstraintTolerance);
    bound = [bound; reference_deg(:, axisIndex) + tube_deg - ...
        positionBase_deg; -reference_deg(:, axisIndex) + tube_deg + ...
        positionBase_deg; limits.maxVelocity_deg_s(axisIndex) - ...
        velocityGuard_deg_s - velocityBase_deg_s; ...
        limits.maxVelocity_deg_s(axisIndex) - velocityGuard_deg_s + ...
        velocityBase_deg_s; limits.maxAcceleration_deg_s2(axisIndex) - ...
        accelerationGuard_deg_s2 - accelerationBase_deg_s2; ...
        limits.maxAcceleration_deg_s2(axisIndex) - ...
        accelerationGuard_deg_s2 + ...
        accelerationBase_deg_s2]; %#ok<AGROW>
    if axisIndex == 2 || ~options.AllowAzimuthWrapping
        matrix = [matrix; positionAxisMap; -positionAxisMap]; %#ok<AGROW>
        bound = [bound; workspaceInterval_deg(2) - positionBase_deg; ...
            -workspaceInterval_deg(1) + positionBase_deg]; %#ok<AGROW>
    end
end
[corridorMatrix, corridorBound] = obstacleCorridor( ...
    obstacleField, reference_deg, knotTime_s, ...
    stateBase.position_deg, positionMap, options);
matrix = [matrix; corridorMatrix];
bound = [bound; corridorBound];
end

function [matrix, bound] = obstacleCorridor(obstacleField, ...
        reference_deg, knotTime_s, positionBase_deg, positionMap, options)
% PURPOSE
%   - Keep each knot on the RL reference side of nearby moving edges.
sampleCount = size(positionMap, 1);
jerkKnotCount = size(positionMap, 2);
matrix = zeros(0, 2 * jerkKnotCount);
bound = zeros(0, 1);
for sampleIndex = 1:sampleCount
    reference = reference_deg(sampleIndex, :);
    for obstacleIndex = 1:numel(obstacleField.Obstacles)
        edgeSet_deg = packedEdgesAtTime( ...
            obstacleField.Obstacles(obstacleIndex), ...
            knotTime_s(sampleIndex));
        if isempty(edgeSet_deg)
            continue;
        end
        [distance_deg, closest_deg] = nearestEdge(reference, edgeSet_deg);
        if ~isfinite(distance_deg) || distance_deg <= 1e-12
            continue;
        end
        normal = (reference - closest_deg) / distance_deg;
        row = -[normal(1) * positionMap(sampleIndex, :), ...
            normal(2) * positionMap(sampleIndex, :)];
        value = dot(normal, positionBase_deg(sampleIndex, :) - ...
            closest_deg) - options.ObstacleConstraintTolerance_deg;
        matrix(end + 1, :) = row; %#ok<AGROW>
        bound(end + 1, 1) = value; %#ok<AGROW>
    end
end
end

function [matrix, value] = endpointEqualities(positionMap, velocityMap, ...
        accelerationMap, stateBase, goalState)
% PURPOSE
%   - Enforce exact two-axis terminal position, velocity, and acceleration.
knotCount = size(positionMap, 2);
zeroRow = zeros(1, knotCount);
matrix = [positionMap(end, :), zeroRow; ...
    velocityMap(end, :), zeroRow; accelerationMap(end, :), zeroRow; ...
    zeroRow, positionMap(end, :); zeroRow, velocityMap(end, :); ...
    zeroRow, accelerationMap(end, :)];
value = [goalState.position_deg(1) - stateBase.position_deg(end, 1); ...
    goalState.velocity_deg_s(1) - stateBase.velocity_deg_s(end, 1); ...
    goalState.acceleration_deg_s2(1) - ...
    stateBase.acceleration_deg_s2(end, 1); ...
    goalState.position_deg(2) - stateBase.position_deg(end, 2); ...
    goalState.velocity_deg_s(2) - stateBase.velocity_deg_s(end, 2); ...
    goalState.acceleration_deg_s2(2) - ...
    stateBase.acceleration_deg_s2(end, 2)];
end

function [positionMap, velocityMap, accelerationMap, stateBase] = ...
        responseMap(segmentCount, step_s, initialState)
% PURPOSE
%   - Integrate the affine knot-state response to linear jerk ordinates.
knotCount = segmentCount + 1;
positionMap = zeros(knotCount);
velocityMap = zeros(knotCount);
accelerationMap = zeros(knotCount);
positionBase_deg = repmat(initialState.position_deg, knotCount, 1);
velocityBase_deg_s = repmat(initialState.velocity_deg_s, knotCount, 1);
accelerationBase_deg_s2 = repmat( ...
    initialState.acceleration_deg_s2, knotCount, 1);
for segmentIndex = 1:segmentCount
    positionMap(segmentIndex + 1, :) = positionMap(segmentIndex, :) + ...
        step_s * velocityMap(segmentIndex, :) + ...
        0.5 * step_s ^ 2 * accelerationMap(segmentIndex, :);
    positionMap(segmentIndex + 1, segmentIndex) = ...
        positionMap(segmentIndex + 1, segmentIndex) + step_s ^ 3 / 8;
    positionMap(segmentIndex + 1, segmentIndex + 1) = ...
        positionMap(segmentIndex + 1, segmentIndex + 1) + step_s ^ 3 / 24;
    velocityMap(segmentIndex + 1, :) = velocityMap(segmentIndex, :) + ...
        step_s * accelerationMap(segmentIndex, :);
    velocityMap(segmentIndex + 1, segmentIndex) = ...
        velocityMap(segmentIndex + 1, segmentIndex) + step_s ^ 2 / 3;
    velocityMap(segmentIndex + 1, segmentIndex + 1) = ...
        velocityMap(segmentIndex + 1, segmentIndex + 1) + step_s ^ 2 / 6;
    accelerationMap(segmentIndex + 1, :) = ...
        accelerationMap(segmentIndex, :);
    accelerationMap(segmentIndex + 1, segmentIndex) = ...
        accelerationMap(segmentIndex + 1, segmentIndex) + step_s / 2;
    accelerationMap(segmentIndex + 1, segmentIndex + 1) = ...
        accelerationMap(segmentIndex + 1, segmentIndex + 1) + step_s / 2;
    positionBase_deg(segmentIndex + 1, :) = ...
        positionBase_deg(segmentIndex, :) + ...
        step_s * velocityBase_deg_s(segmentIndex, :) + ...
        0.5 * step_s ^ 2 * accelerationBase_deg_s2(segmentIndex, :);
    velocityBase_deg_s(segmentIndex + 1, :) = ...
        velocityBase_deg_s(segmentIndex, :) + ...
        step_s * accelerationBase_deg_s2(segmentIndex, :);
end
stateBase = struct("position_deg", positionBase_deg, ...
    "velocity_deg_s", velocityBase_deg_s, ...
    "acceleration_deg_s2", accelerationBase_deg_s2);
end

function reference_deg = interpolateRoute(route_deg, progress)
% PURPOSE
%   - Interpolate a polyline by normalized arc length.
step_deg = diff(route_deg, 1, 1);
arcLength_deg = [0; cumsum(hypot(step_deg(:, 1), step_deg(:, 2)))];
arcProgress = arcLength_deg / arcLength_deg(end);
[arcProgress, uniqueIndex] = unique(arcProgress, "stable");
reference_deg = interp1(arcProgress, route_deg(uniqueIndex, :), ...
    progress, "linear");
end

function trajectory = reconstructTrajectory( ...
        jerkKnot_deg_s3, step_s, initialState, sampleTime_s)
% PURPOSE
%   - Reconstruct the exact quartic position from continuous linear jerk.
segmentCount = size(jerkKnot_deg_s3, 1) - 1;
time_s = 0;
position_deg = initialState.position_deg;
velocity_deg_s = initialState.velocity_deg_s;
acceleration_deg_s2 = initialState.acceleration_deg_s2;
jerk_deg_s3 = jerkKnot_deg_s3(1, :);
state = [initialState.position_deg, initialState.velocity_deg_s, ...
    initialState.acceleration_deg_s2];
for segmentIndex = 1:segmentCount
    localTime_s = (sampleTime_s:sampleTime_s:step_s).';
    if isempty(localTime_s) || localTime_s(end) < step_s - 1e-12
        % Each segment adds at most one endpoint to the bounded sample set.
        localTime_s(end + 1, 1) = step_s; %#ok<AGROW>
    end
    firstJerk = jerkKnot_deg_s3(segmentIndex, :);
    jerkRate = (jerkKnot_deg_s3(segmentIndex + 1, :) - ...
        firstJerk) / step_s;
    position = state(1:2) + localTime_s .* state(3:4) + ...
        0.5 * localTime_s .^ 2 .* state(5:6) + ...
        localTime_s .^ 3 / 6 .* firstJerk + ...
        localTime_s .^ 4 / 24 .* jerkRate;
    velocity = state(3:4) + localTime_s .* state(5:6) + ...
        0.5 * localTime_s .^ 2 .* firstJerk + ...
        localTime_s .^ 3 / 6 .* jerkRate;
    acceleration = state(5:6) + localTime_s .* firstJerk + ...
        0.5 * localTime_s .^ 2 .* jerkRate;
    jerk = firstJerk + localTime_s .* jerkRate;
    time_s = [time_s; time_s(end) + localTime_s]; %#ok<AGROW>
    position_deg = [position_deg; position]; %#ok<AGROW>
    velocity_deg_s = [velocity_deg_s; velocity]; %#ok<AGROW>
    acceleration_deg_s2 = [acceleration_deg_s2; ...
        acceleration]; %#ok<AGROW>
    jerk_deg_s3 = [jerk_deg_s3; jerk]; %#ok<AGROW>
    state = [position(end, :), velocity(end, :), acceleration(end, :)];
end
trajectory = struct("time_s", time_s, "position_deg", position_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2, ...
    "jerk_deg_s3", jerk_deg_s3);
end

function [validation, clearanceDiagnostics] = validateTrajectory( ...
        trajectory, jerkKnot_deg_s3, step_s, obstacleField, ...
        initialState, goalState, limits, options)
% PURPOSE
%   - Validate exact state extrema and conservative continuous clearance.
tolerance = options.KinematicValidationTolerance;
[maximumVelocity_deg_s, maximumAcceleration_deg_s2, ...
    maximumJerk_deg_s3, positionBounds_deg] = exactExtrema( ...
    initialState, jerkKnot_deg_s3, step_s);
velocityWithinLimits = all(maximumVelocity_deg_s <= ...
    limits.maxVelocity_deg_s + tolerance);
accelerationWithinLimits = all(maximumAcceleration_deg_s2 <= ...
    limits.maxAcceleration_deg_s2 + tolerance);
jerkWithinLimits = all(maximumJerk_deg_s3 <= ...
    limits.maxJerk_deg_s3 + tolerance);
positionWithinBounds = positionBounds_deg(2, 2) <= ...
    options.ElevationInterval_deg(2) + tolerance && ...
    positionBounds_deg(1, 2) >= ...
    options.ElevationInterval_deg(1) - tolerance;
if ~options.AllowAzimuthWrapping
    positionWithinBounds = positionWithinBounds && ...
        positionBounds_deg(2, 1) <= ...
        options.AzimuthInterval_deg(2) + tolerance && ...
        positionBounds_deg(1, 1) >= ...
        options.AzimuthInterval_deg(1) - tolerance;
end
collisionMask = queryAzElTimedPathCollision(obstacleField, ...
    trajectory.time_s, trajectory.position_deg, struct( ...
    "BoundaryIsOccupied", true, "TimePaddingSamples", ...
    options.CollisionTimePaddingSamples));
bufferedChordQueryClear = ~any(collisionMask);
curveBuffer_deg = norm(maximumAcceleration_deg_s2) * ...
    max(diff(trajectory.time_s)) ^ 2 / 8;
[collisionSafetyProven, clearanceDiagnostics] = ...
    azElInternal.certifyAzElTimedPathClearance(obstacleField, ...
    trajectory.time_s, trajectory.position_deg, curveBuffer_deg);
collisionFree = bufferedChordQueryClear && collisionSafetyProven;
initialError = [trajectory.position_deg(1, :) - ...
    initialState.position_deg, trajectory.velocity_deg_s(1, :) - ...
    initialState.velocity_deg_s, trajectory.acceleration_deg_s2(1, :) - ...
    initialState.acceleration_deg_s2];
terminalError = [trajectory.position_deg(end, :) - ...
    goalState.position_deg, trajectory.velocity_deg_s(end, :) - ...
    goalState.velocity_deg_s, trajectory.acceleration_deg_s2(end, :) - ...
    goalState.acceleration_deg_s2];
initialStateMatched = max(abs(initialError)) <= tolerance;
terminalStateMatched = max(abs(terminalError)) <= tolerance;
goalTimeSatisfied = trajectory.time_s(end) <= ...
    goalState.time_s + tolerance;
if options.GoalTimeMode == "fixedarrival"
    goalTimeSatisfied = abs(trajectory.time_s(end) - ...
        goalState.time_s) <= tolerance;
end
checks = [all(isfinite(trajectory.time_s)), ...
    all(diff(trajectory.time_s) > 0), initialStateMatched, ...
    terminalStateMatched, goalTimeSatisfied, collisionFree, ...
    velocityWithinLimits, accelerationWithinLimits, jerkWithinLimits, ...
    positionWithinBounds];
issueNames = ["finiteTime" "strictTime" "initialState" ...
    "terminalState" "goalTime" "collision" "velocity" ...
    "acceleration" "jerk" "workspace"];
issues = issueNames(~checks);
passed = all(checks);
message = "The RL convex trajectory passed all checks.";
if ~passed
    message = "The RL convex trajectory failed: " + ...
        strjoin(issues, ", ") + ".";
end
validation = struct("Passed", passed, "Message", message, ...
    "TimeIsStrictlyIncreasing", checks(2), ...
    "InitialStateMatched", initialStateMatched, ...
    "TerminalStateMatched", terminalStateMatched, ...
    "GoalTimeSatisfied", goalTimeSatisfied, ...
    "CollisionFree", collisionFree, ...
    "BufferedChordQueryClear", bufferedChordQueryClear, ...
    "CollisionSafetyProven", collisionSafetyProven, ...
    "CollisionValidationScope", ...
    "Timed chords plus a conservative quartic-curve clearance tube.", ...
    "CurveSubdivisionConverged", collisionSafetyProven, ...
    "MaximumCurveDeviationBound_deg", curveBuffer_deg, ...
    "VelocityWithinLimits", velocityWithinLimits, ...
    "AccelerationWithinLimits", accelerationWithinLimits, ...
    "JerkWithinLimits", jerkWithinLimits, ...
    "PositionWithinBounds", positionWithinBounds, ...
    "ContinuousPolynomialExtremaVerified", true, ...
    "DynamicsDefectWithinTolerance", true, ...
    "InitialStateError", initialError, ...
    "TerminalStateError", terminalError, ...
    "MaximumDynamicsDefect", 0, ...
    "DynamicsConsistencyScope", ...
    "Exact integration of piecewise-linear continuous jerk.", ...
    "MaximumVelocity_deg_s", maximumVelocity_deg_s, ...
    "MaximumAcceleration_deg_s2", maximumAcceleration_deg_s2, ...
    "MaximumJerk_deg_s3", maximumJerk_deg_s3, "Issues", issues);
end

function [maximumVelocity, maximumAcceleration, maximumJerk, ...
        positionBounds] = exactExtrema(initialState, jerkKnot, step_s)
% PURPOSE
%   - Evaluate all real stationary points of each segment polynomial.
maximumVelocity = zeros(1, 2);
maximumAcceleration = zeros(1, 2);
maximumJerk = max(abs(jerkKnot), [], 1);
positionBounds = [initialState.position_deg; initialState.position_deg];
positionState = initialState.position_deg;
velocityState = initialState.velocity_deg_s;
accelerationState = initialState.acceleration_deg_s2;
for segmentIndex = 1:size(jerkKnot, 1) - 1
    for axisIndex = 1:2
        position0 = positionState(axisIndex);
        velocity0 = velocityState(axisIndex);
        acceleration0 = accelerationState(axisIndex);
        jerk0 = jerkKnot(segmentIndex, axisIndex);
        jerkRate = (jerkKnot(segmentIndex + 1, axisIndex) - ...
            jerk0) / step_s;
        jerkTimes = boundedRealRoots([jerkRate, jerk0], step_s);
        accelerationTimes = boundedRealRoots([0.5 * jerkRate, ...
            jerk0, acceleration0], step_s);
        velocityTimes = boundedRealRoots([jerkRate / 6, ...
            jerk0 / 2, acceleration0, velocity0], step_s);
        sampleTimes = unique([0; step_s; jerkTimes; ...
            accelerationTimes; velocityTimes]);
        acceleration = acceleration0 + jerk0 * sampleTimes + ...
            0.5 * jerkRate * sampleTimes .^ 2;
        velocity = velocity0 + acceleration0 * sampleTimes + ...
            0.5 * jerk0 * sampleTimes .^ 2 + ...
            jerkRate / 6 * sampleTimes .^ 3;
        position = position0 + velocity0 * sampleTimes + ...
            0.5 * acceleration0 * sampleTimes .^ 2 + ...
            jerk0 / 6 * sampleTimes .^ 3 + ...
            jerkRate / 24 * sampleTimes .^ 4;
        maximumAcceleration(axisIndex) = max( ...
            maximumAcceleration(axisIndex), max(abs(acceleration)));
        maximumVelocity(axisIndex) = max( ...
            maximumVelocity(axisIndex), max(abs(velocity)));
        positionBounds(1, axisIndex) = min( ...
            positionBounds(1, axisIndex), min(position));
        positionBounds(2, axisIndex) = max( ...
            positionBounds(2, axisIndex), max(position));
        positionState(axisIndex) = position(end);
        velocityState(axisIndex) = velocity(end);
        accelerationState(axisIndex) = acceleration(end);
    end
end
end

function values = boundedRealRoots(coefficients, upperBound)
% PURPOSE
%   - Return real polynomial roots in one closed segment.
firstNonzero = find(abs(coefficients) > 1e-14, 1, "first");
if isempty(firstNonzero) || firstNonzero == numel(coefficients)
    values = zeros(0, 1);
    return;
end
values = roots(coefficients(firstNonzero:end));
values = real(values(abs(imag(values)) <= 1e-10 & ...
    real(values) >= 0 & real(values) <= upperBound));
end

function edgeSet = packedEdgesAtTime(obstacle, queryTime_s)
% PURPOSE
%   - Use cached packed topology to obtain one moving edge set.
obstacleTime_s = double(obstacle.TimeSeconds(:));
if queryTime_s < obstacleTime_s(1) || queryTime_s > obstacleTime_s(end)
    edgeSet = zeros(0, 4);
    return;
end
upperIndex = find(obstacleTime_s >= queryTime_s, 1, "first");
lowerIndex = find(obstacleTime_s <= queryTime_s, 1, "last");
if lowerIndex == upperIndex
    edgeSet = sliceEdges(obstacle, lowerIndex);
    return;
end
fraction = (queryTime_s - obstacleTime_s(lowerIndex)) / ...
    (obstacleTime_s(upperIndex) - obstacleTime_s(lowerIndex));
hasMatch = isfield(obstacle, "TopologyMatchesNext") && ...
    numel(obstacle.TopologyMatchesNext) >= lowerIndex && ...
    obstacle.TopologyMatchesNext(lowerIndex);
if hasMatch
    edgeSet = (1 - fraction) * sliceEdges(obstacle, lowerIndex) + ...
        fraction * sliceEdges(obstacle, upperIndex);
elseif fraction < 0.5
    edgeSet = sliceEdges(obstacle, lowerIndex);
else
    edgeSet = sliceEdges(obstacle, upperIndex);
end
end

function edgeSet = sliceEdges(obstacle, sliceIndex)
% PURPOSE
%   - Read one CSR-like packed edge slice.
firstRow = double(obstacle.EdgeOffsets(sliceIndex));
lastRow = double(obstacle.EdgeOffsets(sliceIndex + 1)) - 1;
if lastRow < firstRow
    edgeSet = zeros(0, 4);
    return;
end
rows = firstRow:lastRow;
edgeSet = double([obstacle.EdgeStartAzimuthDeg(rows), ...
    obstacle.EdgeStartElevationDeg(rows), ...
    obstacle.EdgeEndAzimuthDeg(rows), ...
    obstacle.EdgeEndElevationDeg(rows)]);
end

function [distance_deg, closest_deg] = nearestEdge(point_deg, edges_deg)
% PURPOSE
%   - Return the closest point on a packed edge set.
edgeStart_deg = edges_deg(:, 1:2);
edgeVector_deg = edges_deg(:, 3:4) - edgeStart_deg;
lengthSquared_deg2 = sum(edgeVector_deg .^ 2, 2);
validEdge = lengthSquared_deg2 > eps;
projection = zeros(size(lengthSquared_deg2));
projection(validEdge) = sum((point_deg - edgeStart_deg(validEdge, :)) .* ...
    edgeVector_deg(validEdge, :), 2) ./ lengthSquared_deg2(validEdge);
projection = min(1, max(0, projection));
points_deg = edgeStart_deg + projection .* edgeVector_deg;
distance = vecnorm(point_deg - points_deg, 2, 2);
[distance_deg, edgeIndex] = min(distance);
closest_deg = points_deg(edgeIndex, :);
end

function candidate = copySuccessfulTrial(candidate, trial)
% PURPOSE
%   - Copy a validated trial into the stable candidate schema.
candidate.Success = true;
candidate.Message = trial.Message;
candidate.TerminationReason = trial.TerminationReason;
candidate.SolverExitFlag = trial.SolverExitFlag;
candidate.SolverMessage = trial.SolverMessage;
candidate.SolverIterationCount = trial.SolverIterationCount;
candidate.ArrivalTime_s = trial.ArrivalTime_s;
candidate.MotionDuration_s = trial.MotionDuration_s;
candidate.IntegratedSquaredJerk = trial.IntegratedSquaredJerk;
candidate.MaximumVelocity_deg_s = trial.MaximumVelocity_deg_s;
candidate.MaximumAcceleration_deg_s2 = ...
    trial.MaximumAcceleration_deg_s2;
candidate.MaximumJerk_deg_s3 = trial.MaximumJerk_deg_s3;
candidate.CollisionFree = trial.CollisionFree;
candidate.BufferedChordQueryClear = trial.BufferedChordQueryClear;
candidate.CollisionSafetyProven = trial.CollisionSafetyProven;
candidate.CollisionClearanceDiagnostics = ...
    trial.CollisionClearanceDiagnostics;
candidate.Trajectory = trial.Trajectory;
candidate.Validation = trial.Validation;
candidate.ReferencePosition_deg = trial.ReferencePosition_deg;
end

function candidate = emptyCandidate()
% PURPOSE
%   - Define the stable result for one RL route projection.
candidate = struct("Success", false, ...
    "Message", "The RL projection was not evaluated.", ...
    "TerminationReason", "notEvaluated", ...
    "TimedSeedLawUsed", false, ...
    "SeedRouteTimeFraction", zeros(0, 1), ...
    "SeedRouteProgress", zeros(0, 1), ...
    "DurationTrial_s", zeros(0, 1), ...
    "DurationFeasibleHistory", false(0, 1), ...
    "DurationIntegratedSquaredJerk", zeros(0, 1), ...
    "DurationMaximumVelocity_deg_s", zeros(0, 2), ...
    "DurationMaximumAcceleration_deg_s2", zeros(0, 2), ...
    "DurationIssueSummary", strings(0, 1), ...
    "SolverExitFlag", NaN, "SolverMessage", "", ...
    "SolverExitFlagHistory", zeros(0, 1), ...
    "SolverMessageHistory", strings(0, 1), ...
    "SolverIterationCount", 0, "ArrivalTime_s", Inf, ...
    "MotionDuration_s", Inf, "IntegratedSquaredJerk", Inf, ...
    "MaximumVelocity_deg_s", [Inf Inf], ...
    "MaximumAcceleration_deg_s2", [Inf Inf], ...
    "MaximumJerk_deg_s3", [Inf Inf], "CollisionFree", false, ...
    "BufferedChordQueryClear", false, ...
    "CollisionSafetyProven", false, ...
    "CollisionClearanceDiagnostics", emptyClearanceDiagnostics(), ...
    "ReferencePosition_deg", zeros(0, 2), ...
    "Trajectory", emptyTrajectory(), "Validation", emptyValidation(), ...
    "ElapsedTime_s", 0);
end

function trial = emptyTrial()
% PURPOSE
%   - Define one fixed-duration trial record.
trial = struct("Success", false, "Message", "Not evaluated.", ...
    "TerminationReason", "notEvaluated", "SolverExitFlag", NaN, ...
    "SolverMessage", "", "SolverIterationCount", 0, ...
    "ArrivalTime_s", Inf, "MotionDuration_s", Inf, ...
    "IntegratedSquaredJerk", Inf, ...
    "MaximumVelocity_deg_s", [Inf Inf], ...
    "MaximumAcceleration_deg_s2", [Inf Inf], ...
    "MaximumJerk_deg_s3", [Inf Inf], "CollisionFree", false, ...
    "BufferedChordQueryClear", false, ...
    "CollisionSafetyProven", false, ...
    "CollisionClearanceDiagnostics", emptyClearanceDiagnostics(), ...
    "ReferencePosition_deg", zeros(0, 2), ...
    "Trajectory", emptyTrajectory(), "Validation", emptyValidation());
end

function trajectory = emptyTrajectory()
% PURPOSE
%   - Define empty two-axis trajectory arrays.
trajectory = struct("time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2));
end

function validation = emptyValidation()
% PURPOSE
%   - Define validation fields before a trajectory is available.
validation = struct("Passed", false, "Message", "Not validated.", ...
    "TimeIsStrictlyIncreasing", false, ...
    "InitialStateMatched", false, "TerminalStateMatched", false, ...
    "GoalTimeSatisfied", false, "CollisionFree", false, ...
    "BufferedChordQueryClear", false, ...
    "CollisionSafetyProven", false, "CollisionValidationScope", "", ...
    "CurveSubdivisionConverged", false, ...
    "MaximumCurveDeviationBound_deg", Inf, ...
    "VelocityWithinLimits", false, ...
    "AccelerationWithinLimits", false, "JerkWithinLimits", false, ...
    "PositionWithinBounds", false, ...
    "ContinuousPolynomialExtremaVerified", false, ...
    "DynamicsDefectWithinTolerance", false, ...
    "InitialStateError", inf(1, 6), ...
    "TerminalStateError", inf(1, 6), ...
    "MaximumDynamicsDefect", Inf, "DynamicsConsistencyScope", "", ...
    "MaximumVelocity_deg_s", [Inf Inf], ...
    "MaximumAcceleration_deg_s2", [Inf Inf], ...
    "MaximumJerk_deg_s3", [Inf Inf], "Issues", "notValidated");
end

function diagnostics = emptyClearanceDiagnostics()
% PURPOSE
%   - Define the stable clearance certificate fields.
diagnostics = struct("ProvenClear", false, ...
    "UnresolvedPathSegmentMask", false(0, 1), ...
    "UnresolvedPathSegmentCount", 0, ...
    "TopologyMismatchIntervalCount", 0, ...
    "EvaluatedEdgeIntervalCount", 0, ...
    "BroadPhaseRejectedEdgeIntervalCount", 0, ...
    "SubdivisionBoxCount", 0, "MaximumDepthReached", 0, ...
    "MaximumSubdivisionDepth", 18, "MaximumBoxesPerEdge", 20000, ...
    "MinimumProvenLowerBound_deg", NaN);
end
