function [isOccupied, isInsideBounds, handled] = ...
        queryPackedMovingPoints(packedObstacle, time_s, position_deg, ...
        boundaryIsOccupied)
%% Section 0: Header & Readme
% SYNTAX
%   [isOccupied, isInsideBounds, handled] = ...
%       azElInternal.queryPackedMovingPoints( ...
%       packedObstacle, time_s, position_deg, boundaryIsOccupied)
%**************************************************************************
% PURPOSE
%   - Batch point queries against linearly interpolated corresponding edges.
%   - Leave topology-changing rows unhandled for the maintained conservative
%     scalar fallback.
%**************************************************************************
% INPUTS
%   - packedObstacle (scalar packed-obstacle struct)
%       Edge arrays, slice offsets, times, and topology correspondence.
%   - time_s (N-by-1 finite numeric)
%       Interpolated query times inside the obstacle time span.
%   - position_deg (N-by-2 finite numeric)
%       Matching [azimuth elevation] query points.
%   - boundaryIsOccupied (logical scalar)
%       Whether exact polygon contact is occupied.
%**************************************************************************
% OUTPUTS
%   - isOccupied, isInsideBounds, handled (N-by-1 logical)
%       Polygon result, broad-phase result, and rows safely evaluated by
%       corresponding-edge interpolation. Unhandled rows are false.
%**************************************************************************
% UNITS
%   - Position is degrees and time is seconds.
%**************************************************************************

%% Section 1: Validate Inputs & Locate Source Intervals

time_s = double(time_s(:));
position_deg = double(position_deg);
if isempty(time_s) && isempty(position_deg)
    position_deg = zeros(0, 2);
end
validateattributes(time_s, {'numeric'}, ...
    {'real', 'finite', 'column'});
validateattributes(position_deg, {'numeric'}, ...
    {'real', 'finite', '2d', 'ncols', 2});
if size(position_deg, 1) ~= numel(time_s)
    error("queryPackedMovingPoints:SizeMismatch", ...
        "time_s and position_deg must have the same row count.");
end
boundaryIsOccupied = azElInternal.normalizeLogicalScalar( ...
    boundaryIsOccupied, "boundaryIsOccupied", ...
    "queryPackedMovingPoints:InvalidBoundaryPolicy");
queryCount = numel(time_s);
isOccupied = false(queryCount, 1);
isInsideBounds = false(queryCount, 1);
handled = false(queryCount, 1);
if queryCount == 0 || packedObstacle.SampleCount < 2
    return;
end

obstacleTime_s = double(packedObstacle.TimeSeconds(:));
lowerSliceIndex = discretize(time_s, obstacleTime_s);
isLastSourceTime = time_s == obstacleTime_s(end);
lowerSliceIndex(isLastSourceTime) = packedObstacle.SampleCount - 1;
isInsideTimeSpan = time_s >= obstacleTime_s(1) & ...
    time_s <= obstacleTime_s(end) & ~isnan(lowerSliceIndex);
if ~any(isInsideTimeSpan)
    return;
end

hasTopologyCache = isfield(packedObstacle, "TopologyMatchesNext") && ...
    numel(packedObstacle.TopologyMatchesNext) >= ...
    packedObstacle.SampleCount - 1;
if ~hasTopologyCache
    return;
end

%% Section 2: Batch Queries By Corresponding Source Interval

activeIntervals = unique(lowerSliceIndex(isInsideTimeSpan));
edgeOffsets = double(packedObstacle.EdgeOffsets(:));
for intervalListIndex = 1:numel(activeIntervals)
    sourceIndex = activeIntervals(intervalListIndex);
    if ~packedObstacle.TopologyMatchesNext(sourceIndex)
        continue;
    end
    queryRows = find(isInsideTimeSpan & ...
        lowerSliceIndex == sourceIndex);
    firstEdgeRows = edgeOffsets(sourceIndex): ...
        edgeOffsets(sourceIndex + 1) - 1;
    lastEdgeRows = edgeOffsets(sourceIndex + 1): ...
        edgeOffsets(sourceIndex + 2) - 1;
    if numel(firstEdgeRows) ~= numel(lastEdgeRows) || ...
            isempty(firstEdgeRows)
        continue;
    end

    firstEdges_deg = [ ...
        double(packedObstacle.EdgeStartAzimuthDeg(firstEdgeRows)), ...
        double(packedObstacle.EdgeStartElevationDeg(firstEdgeRows)), ...
        double(packedObstacle.EdgeEndAzimuthDeg(firstEdgeRows)), ...
        double(packedObstacle.EdgeEndElevationDeg(firstEdgeRows))];
    lastEdges_deg = [ ...
        double(packedObstacle.EdgeStartAzimuthDeg(lastEdgeRows)), ...
        double(packedObstacle.EdgeStartElevationDeg(lastEdgeRows)), ...
        double(packedObstacle.EdgeEndAzimuthDeg(lastEdgeRows)), ...
        double(packedObstacle.EdgeEndElevationDeg(lastEdgeRows))];
    intervalDuration_s = obstacleTime_s(sourceIndex + 1) - ...
        obstacleTime_s(sourceIndex);
    fraction = (time_s(queryRows) - obstacleTime_s(sourceIndex)) ./ ...
        intervalDuration_s;

    % Vectorized equivalent of interpolating every polygon separately:
    %
    %   for queryIndex = 1:numel(queryRows)
    %       edges = (1 - fraction(queryIndex)) * firstEdges_deg + ...
    %           fraction(queryIndex) * lastEdges_deg;
    %       occupancy(queryIndex) = pointInEdges(point(queryIndex), edges);
    %   end
    %
    % Rows are queries and columns are corresponding polygon edges. This
    % removes thousands of helper calls while retaining the same odd-even
    % and scale-aware boundary tests.
    firstWeight = 1 - fraction;
    edgeStartAzimuth_deg = firstWeight .* firstEdges_deg(:, 1).' + ...
        fraction .* lastEdges_deg(:, 1).';
    edgeStartElevation_deg = firstWeight .* firstEdges_deg(:, 2).' + ...
        fraction .* lastEdges_deg(:, 2).';
    edgeEndAzimuth_deg = firstWeight .* firstEdges_deg(:, 3).' + ...
        fraction .* lastEdges_deg(:, 3).';
    edgeEndElevation_deg = firstWeight .* firstEdges_deg(:, 4).' + ...
        fraction .* lastEdges_deg(:, 4).';

    queryAzimuth_deg = position_deg(queryRows, 1);
    queryElevation_deg = position_deg(queryRows, 2);
    minimumAzimuth_deg = min( ...
        [edgeStartAzimuth_deg, edgeEndAzimuth_deg], [], 2);
    maximumAzimuth_deg = max( ...
        [edgeStartAzimuth_deg, edgeEndAzimuth_deg], [], 2);
    minimumElevation_deg = min( ...
        [edgeStartElevation_deg, edgeEndElevation_deg], [], 2);
    maximumElevation_deg = max( ...
        [edgeStartElevation_deg, edgeEndElevation_deg], [], 2);
    boundsScale_deg = max(1, max(abs([ ...
        minimumAzimuth_deg, maximumAzimuth_deg, ...
        minimumElevation_deg, maximumElevation_deg]), [], 2));
    boundsTolerance_deg = 1e-12 .* boundsScale_deg;
    insideBounds = ...
        queryAzimuth_deg >= minimumAzimuth_deg - boundsTolerance_deg & ...
        queryAzimuth_deg <= maximumAzimuth_deg + boundsTolerance_deg & ...
        queryElevation_deg >= minimumElevation_deg - boundsTolerance_deg & ...
        queryElevation_deg <= maximumElevation_deg + boundsTolerance_deg;
    isInsideBounds(queryRows) = insideBounds;

    edgeAzimuthDelta_deg = ...
        edgeEndAzimuth_deg - edgeStartAzimuth_deg;
    edgeElevationDelta_deg = ...
        edgeEndElevation_deg - edgeStartElevation_deg;
    startsAbove = edgeStartElevation_deg > queryElevation_deg;
    endsAbove = edgeEndElevation_deg > queryElevation_deg;
    verticalStraddle = startsAbove ~= endsAbove;
    rayIntersectionAzimuth_deg = edgeStartAzimuth_deg + ( ...
        queryElevation_deg - edgeStartElevation_deg) .* ...
        edgeAzimuthDelta_deg ./ edgeElevationDelta_deg;
    rayCrosses = verticalStraddle & ...
        queryAzimuth_deg < rayIntersectionAzimuth_deg;
    insidePolygon = mod(sum(rayCrosses, 2), 2) == 1;

    edgeLength_deg = hypot( ...
        edgeAzimuthDelta_deg, edgeElevationDelta_deg);
    coordinateTolerance_deg = 1e-10 .* max(1, edgeLength_deg);
    crossProduct_deg2 = ...
        (queryAzimuth_deg - edgeStartAzimuth_deg) .* ...
        edgeElevationDelta_deg - ...
        (queryElevation_deg - edgeStartElevation_deg) .* ...
        edgeAzimuthDelta_deg;
    onBoundary = any( ...
        abs(crossProduct_deg2) <= ...
        coordinateTolerance_deg .* max(1, edgeLength_deg) & ...
        queryAzimuth_deg >= min( ...
        edgeStartAzimuth_deg, edgeEndAzimuth_deg) - ...
        coordinateTolerance_deg & ...
        queryAzimuth_deg <= max( ...
        edgeStartAzimuth_deg, edgeEndAzimuth_deg) + ...
        coordinateTolerance_deg & ...
        queryElevation_deg >= min( ...
        edgeStartElevation_deg, edgeEndElevation_deg) - ...
        coordinateTolerance_deg & ...
        queryElevation_deg <= max( ...
        edgeStartElevation_deg, edgeEndElevation_deg) + ...
        coordinateTolerance_deg, 2);
    if boundaryIsOccupied
        isOccupied(queryRows) = insidePolygon | onBoundary;
    else
        isOccupied(queryRows) = insidePolygon & ~onBoundary;
    end
    handled(queryRows) = true;
end
end
