function candidate = solveAzElHs3(obstacles, initialState, goalState, ...
        limits, options, seed)
%% Section 0: Header & Readme
% SYNTAX
%   candidate = azElInternal.solveAzElHs3( ...
%       obstacles, initialState, goalState, limits, options, seed)
%**************************************************************************
% PURPOSE
%   - Solve one separated third-order Hermite-Simpson trajectory problem.
%   - Reconstruct one position, velocity, and acceleration chain from jerk.
%**************************************************************************
% INPUTS
%   - obstacles (canonical protected obstacle struct array)
%   - initialState, goalState (normalized scalar state structs)
%   - limits (normalized scalar limits struct)
%   - options (resolved planner options)
%   - seed (scalar topology-seed struct)
%       position_deg is N-by-2 and tau is a strictly increasing N-vector.
%**************************************************************************
% OUTPUTS
%   - candidate (scalar struct)
%       Solver outcome, polynomial trajectory, samples, and diagnostics.
%**************************************************************************
% UNITS
%   - Position is degrees; time is seconds; derivatives use deg/s, deg/s^2,
%     and deg/s^3.
%**************************************************************************

%% Section 1: Build The Decision Layout And Initial Guess

segmentCount = options.CollocationSegmentCount;
controlCount = 2 * segmentCount + 1;
isEarliestArrival = options.GoalTimeMode == "earliestArrival";
startTime_s = initialState.time_s;
latestFinalTime_s = goalState.time_s;
minimumDuration_s = durationLowerBound( ...
    initialState, goalState, limits, latestFinalTime_s);
minimumFinalTime_s = startTime_s + minimumDuration_s;
candidate = emptyCandidate(seed, segmentCount);
if minimumFinalTime_s > latestFinalTime_s + options.ConstraintTolerance
    candidate.Message = "The goal time is below a physical duration bound.";
    candidate.TerminationReason = "timeWindowInfeasible";
    return;
end
if isEarliestArrival
    seedDuration_s = max( ...
        minimumDuration_s, seed.EstimatedDuration_s);
    finalTimeGuess_s = min(latestFinalTime_s, ...
        startTime_s + max(1.05 * minimumDuration_s, seedDuration_s));
else
    finalTimeGuess_s = latestFinalTime_s;
end
controlTau = linspace(0, 1, controlCount).';
initialJerk_deg_s3 = initialJerkGuess( ...
    initialState, goalState, limits, seed, finalTimeGuess_s, ...
    segmentCount, controlTau);
% Static geometry uses seven checks between each HS3 knot or midpoint.
% Moving geometry uses three plus an obstacle-motion clearance.
corridorSubdivisionCount = 8;
if obstacleHistoriesAreStatic(obstacles)
    corridorSubdivisionCount = 16;
end
corridorTau = linspace( ...
    0, 1, corridorSubdivisionCount * segmentCount + 1).';
corridor = buildCorridor( ...
    obstacles, seed, startTime_s, finalTimeGuess_s, corridorTau, limits, ...
    options.CollisionClearanceTolerance_deg);
decision0 = initialJerk_deg_s3(:);
lowerBound = repmat(-limits.maxJerk_deg_s3(:), controlCount, 1);
upperBound = repmat(limits.maxJerk_deg_s3(:), controlCount, 1);
if isEarliestArrival
    decision0(end + 1, 1) = finalTimeGuess_s;
    lowerBound(end + 1, 1) = minimumFinalTime_s;
    upperBound(end + 1, 1) = latestFinalTime_s;
end

%% Section 2: Minimize Arrival Time Or Fixed-Time Jerk

solverTimer = tic;
solverOptions = optimoptions("fmincon", ...
    "Algorithm", "sqp", ...
    "Display", solverDisplay(options.Verbose), ...
    "MaxIterations", options.MaximumNlpIterations, ...
    "MaxFunctionEvaluations", options.MaximumNlpFunctionEvaluations, ...
    "ConstraintTolerance", options.ConstraintTolerance, ...
    "OptimalityTolerance", options.OptimalityTolerance, ...
    "StepTolerance", options.StepTolerance, ...
    "OutputFcn", @(decision, solverValues, state) ...
    stopForTime(decision, solverValues, state, solverTimer, ...
    options.MaximumSolverTime_s));
constraintFunction = @(decision) trajectoryConstraints( ...
    decision, isEarliestArrival, latestFinalTime_s, segmentCount, ...
    initialState, goalState, limits, options, obstacles, corridor);
if isEarliestArrival
    stageOneObjective = @(decision) decision(end);
else
    stageOneObjective = @(decision) integratedSquaredJerk( ...
        decision, false, latestFinalTime_s, segmentCount, startTime_s);
end
try
    [stageOneDecision, stageOneObjectiveValue, stageOneExitFlag, ...
        stageOneOutput] = fmincon( ...
        stageOneObjective, decision0, [], [], [], [], ...
        lowerBound, upperBound, constraintFunction, solverOptions);
catch exception
    candidate.Message = "HS3 solve failed: " + string(exception.message);
    candidate.TerminationReason = "solverError";
    candidate.SolverDiagnostics = struct( ...
        "Identifier", string(exception.identifier), ...
        "StageOneExitFlag", NaN, "StageTwoExitFlag", NaN, ...
        "StageOneOutput", struct(), "StageTwoOutput", struct());
    return;
end

%% Section 3: Apply The Lexicographic Jerk Tie-Break

selectedDecision = stageOneDecision;
stageTwoExitFlag = NaN;
stageTwoOutput = struct();
stageTwoObjectiveValue = NaN;
if isEarliestArrival && ...
        toc(solverTimer) < options.MaximumSolverTime_s
    stageTwoUpperBound = upperBound;
    stageTwoUpperBound(end) = min( ...
        latestFinalTime_s, stageOneDecision(end) + ...
        options.ArrivalTimeTolerance_s);
    stageTwoObjective = @(decision) integratedSquaredJerk( ...
        decision, true, latestFinalTime_s, segmentCount, startTime_s);
    [trialDecision, stageTwoObjectiveValue, stageTwoExitFlag, ...
        stageTwoOutput] = fmincon( ...
        stageTwoObjective, stageOneDecision, [], [], [], [], ...
        lowerBound, stageTwoUpperBound, constraintFunction, solverOptions);
    trialViolation = maximumConstraintViolation( ...
        trialDecision, constraintFunction);
    stageOneViolation = maximumConstraintViolation( ...
        stageOneDecision, constraintFunction);
    if trialViolation <= max(options.ConstraintTolerance, ...
            stageOneViolation)
        selectedDecision = trialDecision;
    end
end

%% Section 4: Reconstruct The Candidate

[jerk_deg_s3, finalTime_s] = unpackDecision( ...
    selectedDecision, isEarliestArrival, latestFinalTime_s, controlCount);
polynomial = reconstructPolynomial( ...
    jerk_deg_s3, initialState, finalTime_s, segmentCount);
[sampleTime_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, sampledJerk_deg_s3] = ...
    samplePolynomial(polynomial, options.SampleTime_s);
maximumViolation = maximumConstraintViolation( ...
    selectedDecision, constraintFunction);
optimizerFeasible = maximumViolation <= ...
    max(10 * options.ConstraintTolerance, 1e-7);
timeLimitReached = toc(solverTimer) >= options.MaximumSolverTime_s;
if optimizerFeasible
    message = "HS3 returned a constraint-feasible local solution.";
    terminationReason = "optimizerFeasible";
elseif timeLimitReached
    message = "HS3 reached its solver time limit before feasibility.";
    terminationReason = "solverTimeLimit";
else
    message = "HS3 did not satisfy all optimization constraints.";
    terminationReason = "optimizerInfeasible";
end
candidate = struct( ...
    "OptimizerFeasible", optimizerFeasible, ...
    "Message", message, ...
    "TerminationReason", terminationReason, ...
    "SeedIndex", seed.Index, ...
    "SeedSource", seed.Source, ...
    "FinalTime_s", finalTime_s, ...
    "MotionDuration_s", finalTime_s - startTime_s, ...
    "IntegratedSquaredJerk_deg2_s5", integratedSquaredJerk( ...
    selectedDecision, isEarliestArrival, latestFinalTime_s, ...
    segmentCount, startTime_s), ...
    "MaximumConstraintViolation", maximumViolation, ...
    "time_s", sampleTime_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2, ...
    "jerk_deg_s3", sampledJerk_deg_s3, ...
    "Polynomial", polynomial, ...
    "ControlTau", controlTau, ...
    "ControlJerk_deg_s3", jerk_deg_s3, ...
    "Corridor", corridor, ...
    "SolverDiagnostics", struct( ...
    "StageOneExitFlag", stageOneExitFlag, ...
    "StageTwoExitFlag", stageTwoExitFlag, ...
    "StageOneObjective", stageOneObjectiveValue, ...
    "StageTwoObjective", stageTwoObjectiveValue, ...
    "StageOneOutput", stageOneOutput, ...
    "StageTwoOutput", stageTwoOutput, ...
    "ElapsedTime_s", toc(solverTimer)));
end

%% Section 5: Local Functions

function areStatic = obstacleHistoriesAreStatic(obstacles)
% PURPOSE
%   - Select corridor density from geometry history, not scenario identity.
areStatic = true;
for obstacleIndex = 1:numel(obstacles)
    azimuthHistory_deg = obstacles(obstacleIndex).az_deg;
    elevationHistory_deg = obstacles(obstacleIndex).el_deg;
    for sampleIndex = 2:numel(azimuthHistory_deg)
        if ~isequaln(azimuthHistory_deg{sampleIndex}, ...
                azimuthHistory_deg{1}) || ...
                ~isequaln(elevationHistory_deg{sampleIndex}, ...
                elevationHistory_deg{1})
            areStatic = false;
            return;
        end
    end
end
end

function stop = stopForTime(~, ~, ~, solverTimer, maximumTime_s)
% PURPOSE
%   - Stop one fmincon stage at its assigned wall-time limit.
stop = toc(solverTimer) >= maximumTime_s;
end

function displayMode = solverDisplay(verbose)
% PURPOSE
%   - Keep solver output under the public Verbose control.
if verbose
    displayMode = "iter";
else
    displayMode = "none";
end
end

function jerkGuess_deg_s3 = initialJerkGuess(initialState, goalState, ...
        limits, seed, finalTime_s, segmentCount, controlTau)
% PURPOSE
%   - Fit a bounded jerk-chain initialization to the supplied topology seed.
controlCount = numel(controlTau);
desiredPosition_deg = interp1(seed.tau, seed.position_deg, ...
    controlTau, "linear");
zeroJerk_deg_s3 = zeros(controlCount, 2);
basePolynomial = reconstructPolynomial( ...
    zeroJerk_deg_s3, initialState, finalTime_s, segmentCount);
[~, basePosition_deg, baseVelocity_deg_s, ...
    baseAcceleration_deg_s2] = evaluatePolynomial( ...
    basePolynomial, initialState.time_s + ...
    controlTau * (finalTime_s - initialState.time_s));
terminalPosition_deg = goalPositionAtTime(goalState, finalTime_s);
jerkGuess_deg_s3 = zeros(controlCount, 2);
for axisIndex = 1:2
    positionMap = zeros(controlCount - 1, controlCount);
    terminalVelocityMap = zeros(1, controlCount);
    terminalAccelerationMap = zeros(1, controlCount);
    for controlIndex = 1:controlCount
        basisJerk_deg_s3 = zeros(controlCount, 2);
        basisJerk_deg_s3(controlIndex, axisIndex) = 1;
        basisPolynomial = reconstructPolynomial( ...
            basisJerk_deg_s3, initialState, finalTime_s, segmentCount);
        [~, basisPosition_deg, basisVelocity_deg_s, ...
            basisAcceleration_deg_s2] = evaluatePolynomial( ...
            basisPolynomial, initialState.time_s + ...
            controlTau * (finalTime_s - initialState.time_s));
        positionMap(:, controlIndex) = ...
            basisPosition_deg(2:end, axisIndex) - ...
            basePosition_deg(2:end, axisIndex);
        terminalVelocityMap(controlIndex) = ...
            basisVelocity_deg_s(end, axisIndex) - ...
            baseVelocity_deg_s(end, axisIndex);
        terminalAccelerationMap(controlIndex) = ...
            basisAcceleration_deg_s2(end, axisIndex) - ...
            baseAcceleration_deg_s2(end, axisIndex);
    end
    desiredPosition_deg(end, axisIndex) = terminalPosition_deg(axisIndex);
    fitMatrix = [positionMap; ...
        5 * terminalVelocityMap; 5 * terminalAccelerationMap];
    fitOffset = [ ...
        desiredPosition_deg(2:end, axisIndex) - ...
        basePosition_deg(2:end, axisIndex); ...
        5 * (goalState.velocity_deg_s(axisIndex) - ...
        baseVelocity_deg_s(end, axisIndex)); ...
        5 * (goalState.acceleration_deg_s2(axisIndex) - ...
        baseAcceleration_deg_s2(end, axisIndex))];
    regularization = 1e-8 * eye(controlCount);
    jerkGuess_deg_s3(:, axisIndex) = ...
        (fitMatrix.' * fitMatrix + regularization) \ ...
        (fitMatrix.' * fitOffset);
end
jerkGuess_deg_s3 = min(limits.maxJerk_deg_s3, ...
    max(-limits.maxJerk_deg_s3, jerkGuess_deg_s3));
end

function [inequality, equality] = trajectoryConstraints(decision, ...
        isEarliestArrival, fixedFinalTime_s, segmentCount, ...
        initialState, goalState, limits, options, obstacles, corridor)
% PURPOSE
%   - Enforce endpoint, continuous kinematic, and frozen-corridor constraints.
controlCount = 2 * segmentCount + 1;
[jerk_deg_s3, finalTime_s] = unpackDecision( ...
    decision, isEarliestArrival, fixedFinalTime_s, controlCount);
polynomial = reconstructPolynomial( ...
    jerk_deg_s3, initialState, finalTime_s, segmentCount);
inequality = continuousBoundConstraints( ...
    polynomial, limits, options);
corridorTau = unique([corridor.Tau].', "stable");
controlTime_s = initialState.time_s + corridorTau * ...
    (finalTime_s - initialState.time_s);
[~, controlPosition_deg] = evaluatePolynomial(polynomial, controlTime_s);
corridorInequality = corridorConstraints( ...
    corridor, obstacles, controlTime_s, controlPosition_deg);
inequality = [inequality; corridorInequality];
terminalPosition_deg = polynomial.TerminalState.position_deg;
terminalVelocity_deg_s = polynomial.TerminalState.velocity_deg_s;
terminalAcceleration_deg_s2 = ...
    polynomial.TerminalState.acceleration_deg_s2;
goalPosition_deg = goalPositionAtTime(goalState, finalTime_s);
equality = [ ...
    terminalPosition_deg - goalPosition_deg, ...
    terminalVelocity_deg_s - goalState.velocity_deg_s, ...
    terminalAcceleration_deg_s2 - goalState.acceleration_deg_s2].';
end

function inequality = continuousBoundConstraints(polynomial, limits, options)
% PURPOSE
%   - Use Bernstein convex-hull bounds over every complete HS3 segment.
inequality = zeros(0, 1);
positionLower_deg = [options.AzimuthInterval_deg(1), ...
    options.ElevationInterval_deg(1)];
positionUpper_deg = [options.AzimuthInterval_deg(2), ...
    options.ElevationInterval_deg(2)];
for segmentIndex = 1:polynomial.SegmentCount
    for axisIndex = 1:2
        if ~(axisIndex == 1 && options.AllowAzimuthWrapping)
            positionPower = reshape( ...
                polynomial.positionPower_deg(segmentIndex, axisIndex, :), ...
                [], 1);
            inequality = appendBounds(inequality, positionPower, ...
                positionLower_deg(axisIndex), ...
                positionUpper_deg(axisIndex));
        end
        velocityPower = reshape( ...
            polynomial.velocityPower_deg_s(segmentIndex, axisIndex, :), ...
            [], 1);
        accelerationPower = reshape( ...
            polynomial.accelerationPower_deg_s2( ...
            segmentIndex, axisIndex, :), [], 1);
        jerkPower = reshape( ...
            polynomial.jerkPower_deg_s3(segmentIndex, axisIndex, :), ...
            [], 1);
        inequality = appendBounds(inequality, velocityPower, ...
            -limits.maxVelocity_deg_s(axisIndex), ...
            limits.maxVelocity_deg_s(axisIndex));
        inequality = appendBounds(inequality, accelerationPower, ...
            -limits.maxAcceleration_deg_s2(axisIndex), ...
            limits.maxAcceleration_deg_s2(axisIndex));
        inequality = appendBounds(inequality, jerkPower, ...
            -limits.maxJerk_deg_s3(axisIndex), ...
            limits.maxJerk_deg_s3(axisIndex));
    end
end
end

function inequality = appendBounds(inequality, powerCoefficient, ...
        lowerBound, upperBound)
% PURPOSE
%   - Append continuous polynomial limits through Bernstein coefficients.
bernsteinCoefficient = powerToBernstein(powerCoefficient);
inequality = [inequality; ...
    bernsteinCoefficient - upperBound; ...
    lowerBound - bernsteinCoefficient];
end

function corridor = buildCorridor( ...
        obstacles, seed, startTime_s, finalTime_s, controlTau, limits, ...
        clearanceTolerance_deg)
% PURPOSE
%   - Freeze obstacle edges with local motion clearance between points.
template = struct( ...
    "ControlIndex", 0, "ObstacleIndex", 0, "EdgeIndex", 0, ...
    "Tau", 0, ...
    "OutwardSign", 1, "UseSupport", false, ...
    "SupportNormal", [0 0], "Clearance_deg", 0);
corridor = repmat(template, 0, 1);
seedPosition_deg = interp1(seed.tau, seed.position_deg, ...
    controlTau, "linear");
motionDuration_s = finalTime_s - startTime_s;
controlTime_s = startTime_s + controlTau * motionDuration_s;
maximumTimeStep_s = max(diff(controlTau)) * motionDuration_s;
baseClearance_deg = max(1e-4, clearanceTolerance_deg);
seedSegmentDuration_s = diff(seed.tau) * motionDuration_s;
seedSegmentSpeed_deg_s = vecnorm( ...
    diff(seed.position_deg, 1, 1), 2, 2) ./ seedSegmentDuration_s;
seedSpeedGuard_deg_s = min( ...
    norm(limits.maxVelocity_deg_s), ...
    2 * max(seedSegmentSpeed_deg_s));
for controlIndex = 1:numel(controlTau)
    for obstacleIndex = 1:numel(obstacles)
        [shape, geometry] = azElInternal.obstacleShapeAtTime( ...
            obstacles(obstacleIndex), controlTime_s(controlIndex));
        if ~geometry.Active
            continue;
        end
        [edgeStart_deg, edgeEnd_deg] = geometryEdges(geometry);
        [edgeIndex, nearestPoint_deg] = nearestEdge( ...
            seedPosition_deg(controlIndex, :), ...
            edgeStart_deg, edgeEnd_deg);
        edgeDelta_deg = edgeEnd_deg(edgeIndex, :) - ...
            edgeStart_deg(edgeIndex, :);
        leftNormal = [-edgeDelta_deg(2), edgeDelta_deg(1)];
        leftNormal = leftNormal / norm(leftNormal);
        probeScale_deg = max(1e-7, 1e-7 * norm(edgeDelta_deg));
        probe_deg = nearestPoint_deg + probeScale_deg * leftNormal;
        if isinterior(shape, probe_deg(1), probe_deg(2))
            outwardSign = -1;
        else
            outwardSign = 1;
        end
        association = template;
        association.ControlIndex = controlIndex;
        association.ObstacleIndex = obstacleIndex;
        association.EdgeIndex = edgeIndex;
        association.Tau = controlTau(controlIndex);
        association.OutwardSign = outwardSign;
        hasUnboundedObstacleSpeed = ...
            ~isfinite(geometry.VertexSpeedBound_deg_s);
        obstacleSpeedBound_deg_s = geometry.VertexSpeedBound_deg_s;
        if ~isfinite(obstacleSpeedBound_deg_s)
            % A conservative endpoint union is fixed within a topology-change
            % interval. Only trajectory motion remains between checks.
            obstacleSpeedBound_deg_s = 0;
        end
        association.Clearance_deg = baseClearance_deg + ...
            0.5 * maximumTimeStep_s * ...
            (seedSpeedGuard_deg_s + obstacleSpeedBound_deg_s);
        if ~geometry.TopologyIsInterpolated || hasUnboundedObstacleSpeed
            outwardNormal = outwardSign * leftNormal;
            association.UseSupport = true;
            association.SupportNormal = outwardNormal;
        end
        corridor(end + 1, 1) = association; %#ok<AGROW>
    end
end
end

function inequality = corridorConstraints( ...
        corridor, obstacles, controlTime_s, controlPosition_deg)
% PURPOSE
%   - Evaluate frozen edge associations on geometry at the decision time.
inequality = zeros(numel(corridor), 1);
for associationIndex = 1:numel(corridor)
    association = corridor(associationIndex);
    controlIndex = association.ControlIndex;
    [~, geometry] = azElInternal.obstacleShapeAtTime( ...
        obstacles(association.ObstacleIndex), ...
        controlTime_s(controlIndex));
    if ~geometry.Active
        inequality(associationIndex) = -1;
        continue;
    end
    finiteVertices = isfinite(geometry.azimuth_deg) & ...
        isfinite(geometry.elevation_deg);
    vertices_deg = [geometry.azimuth_deg(finiteVertices), ...
        geometry.elevation_deg(finiteVertices)];
    if association.UseSupport
        outwardNormal = association.SupportNormal;
        boundaryOffset_deg = max(vertices_deg * outwardNormal.');
    else
        [edgeStart_deg, edgeEnd_deg] = geometryEdges(geometry);
        if association.EdgeIndex > size(edgeStart_deg, 1)
            inequality(associationIndex) = 1e3;
            continue;
        end
        edgeDelta_deg = ...
            edgeEnd_deg(association.EdgeIndex, :) - ...
            edgeStart_deg(association.EdgeIndex, :);
        if norm(edgeDelta_deg) <= eps
            inequality(associationIndex) = 1e3;
            continue;
        end
        leftNormal = [-edgeDelta_deg(2), edgeDelta_deg(1)] / ...
            norm(edgeDelta_deg);
        outwardNormal = association.OutwardSign * leftNormal;
        boundaryOffset_deg = ...
            edgeStart_deg(association.EdgeIndex, :) * ...
            outwardNormal.';
    end
    pointProjection_deg = ...
        controlPosition_deg(controlIndex, :) * outwardNormal.';
    inequality(associationIndex) = boundaryOffset_deg + ...
        association.Clearance_deg - pointProjection_deg;
end
end

function [edgeStart_deg, edgeEnd_deg] = geometryEdges(geometry)
% PURPOSE
%   - Convert a NaN-separated canonical boundary to deterministic edges.
position_deg = [geometry.azimuth_deg, geometry.elevation_deg];
finiteRows = all(isfinite(position_deg), 2);
regionChanges = diff([false; finiteRows; false]);
regionStarts = find(regionChanges == 1);
regionStops = find(regionChanges == -1) - 1;
edgeStart_deg = zeros(0, 2);
edgeEnd_deg = zeros(0, 2);
for regionIndex = 1:numel(regionStarts)
    vertices_deg = position_deg( ...
        regionStarts(regionIndex):regionStops(regionIndex), :);
    if size(vertices_deg, 1) < 2
        continue;
    end
    if all(vertices_deg(1, :) == vertices_deg(end, :))
        vertices_deg(end, :) = [];
    end
    edgeStart_deg = [edgeStart_deg; vertices_deg]; %#ok<AGROW>
    edgeEnd_deg = [edgeEnd_deg; ...
        vertices_deg([2:end 1], :)]; %#ok<AGROW>
end
end

function [edgeIndex, nearestPoint_deg] = nearestEdge( ...
        point_deg, edgeStart_deg, edgeEnd_deg)
% PURPOSE
%   - Select the closest edge and boundary point for a frozen association.
edgeDelta_deg = edgeEnd_deg - edgeStart_deg;
edgeLengthSquared_deg2 = sum(edgeDelta_deg.^2, 2);
projection = zeros(size(edgeLengthSquared_deg2));
validEdges = edgeLengthSquared_deg2 > 0;
projection(validEdges) = sum( ...
    (point_deg - edgeStart_deg(validEdges, :)) .* ...
    edgeDelta_deg(validEdges, :), 2) ./ ...
    edgeLengthSquared_deg2(validEdges);
projection = min(1, max(0, projection));
projectedPoint_deg = edgeStart_deg + projection .* edgeDelta_deg;
[~, edgeIndex] = min(sum((point_deg - projectedPoint_deg).^2, 2));
nearestPoint_deg = projectedPoint_deg(edgeIndex, :);
end

function polynomial = reconstructPolynomial( ...
        jerk_deg_s3, initialState, finalTime_s, segmentCount)
% PURPOSE
%   - Integrate one quadratic-jerk HS3 chain exactly on every segment.
%   - Follow the separated higher-order construction cited in citation.md.
duration_s = finalTime_s - initialState.time_s;
segmentDuration_s = duration_s / segmentCount;
positionPower_deg = zeros(segmentCount, 2, 6);
velocityPower_deg_s = zeros(segmentCount, 2, 5);
accelerationPower_deg_s2 = zeros(segmentCount, 2, 4);
jerkPower_deg_s3 = zeros(segmentCount, 2, 3);
position_deg = initialState.position_deg;
velocity_deg_s = initialState.velocity_deg_s;
acceleration_deg_s2 = initialState.acceleration_deg_s2;
for segmentIndex = 1:segmentCount
    startControlIndex = 2 * segmentIndex - 1;
    startJerk_deg_s3 = jerk_deg_s3(startControlIndex, :);
    midpointJerk_deg_s3 = jerk_deg_s3(startControlIndex + 1, :);
    endJerk_deg_s3 = jerk_deg_s3(startControlIndex + 2, :);
    jerkLinear_deg_s3 = -3 * startJerk_deg_s3 + ...
        4 * midpointJerk_deg_s3 - endJerk_deg_s3;
    jerkQuadratic_deg_s3 = 2 * startJerk_deg_s3 - ...
        4 * midpointJerk_deg_s3 + 2 * endJerk_deg_s3;
    jerkPower = [startJerk_deg_s3; jerkLinear_deg_s3; ...
        jerkQuadratic_deg_s3].';
    accelerationPower = [acceleration_deg_s2; ...
        segmentDuration_s * startJerk_deg_s3; ...
        segmentDuration_s * jerkLinear_deg_s3 / 2; ...
        segmentDuration_s * jerkQuadratic_deg_s3 / 3].';
    velocityPower = [velocity_deg_s; ...
        segmentDuration_s * acceleration_deg_s2; ...
        segmentDuration_s^2 * startJerk_deg_s3 / 2; ...
        segmentDuration_s^2 * jerkLinear_deg_s3 / 6; ...
        segmentDuration_s^2 * jerkQuadratic_deg_s3 / 12].';
    positionPower = [position_deg; ...
        segmentDuration_s * velocity_deg_s; ...
        segmentDuration_s^2 * acceleration_deg_s2 / 2; ...
        segmentDuration_s^3 * startJerk_deg_s3 / 6; ...
        segmentDuration_s^3 * jerkLinear_deg_s3 / 24; ...
        segmentDuration_s^3 * jerkQuadratic_deg_s3 / 60].';
    positionPower_deg(segmentIndex, :, :) = positionPower;
    velocityPower_deg_s(segmentIndex, :, :) = velocityPower;
    accelerationPower_deg_s2(segmentIndex, :, :) = accelerationPower;
    jerkPower_deg_s3(segmentIndex, :, :) = jerkPower;
    position_deg = sum(positionPower, 2).';
    velocity_deg_s = sum(velocityPower, 2).';
    acceleration_deg_s2 = sum(accelerationPower, 2).';
end
segmentStartTime_s = initialState.time_s + ...
    (0:segmentCount - 1).' * segmentDuration_s;
polynomial = struct( ...
    "SegmentCount", segmentCount, ...
    "SegmentStartTime_s", segmentStartTime_s, ...
    "SegmentDuration_s", segmentDuration_s, ...
    "FinalTime_s", finalTime_s, ...
    "positionPower_deg", positionPower_deg, ...
    "velocityPower_deg_s", velocityPower_deg_s, ...
    "accelerationPower_deg_s2", accelerationPower_deg_s2, ...
    "jerkPower_deg_s3", jerkPower_deg_s3, ...
    "TerminalState", struct( ...
    "position_deg", position_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2));
end

function [time_s, position_deg, velocity_deg_s, ...
        acceleration_deg_s2, jerk_deg_s3] = ...
        samplePolynomial(polynomial, sampleTime_s)
% PURPOSE
%   - Sample the exact segment polynomials without losing knot times.
startTime_s = polynomial.SegmentStartTime_s(1);
uniformTime_s = (startTime_s:sampleTime_s:polynomial.FinalTime_s).';
time_s = unique([uniformTime_s; polynomial.SegmentStartTime_s; ...
    polynomial.FinalTime_s]);
[time_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, jerk_deg_s3] = ...
    evaluatePolynomial(polynomial, time_s);
end

function [time_s, position_deg, velocity_deg_s, ...
        acceleration_deg_s2, jerk_deg_s3] = ...
        evaluatePolynomial(polynomial, time_s)
% PURPOSE
%   - Evaluate the exact HS3 state and jerk polynomials at requested times.
time_s = double(time_s(:));
sampleCount = numel(time_s);
position_deg = zeros(sampleCount, 2);
velocity_deg_s = zeros(sampleCount, 2);
acceleration_deg_s2 = zeros(sampleCount, 2);
jerk_deg_s3 = zeros(sampleCount, 2);
for sampleIndex = 1:sampleCount
    segmentIndex = floor((time_s(sampleIndex) - ...
        polynomial.SegmentStartTime_s(1)) / ...
        polynomial.SegmentDuration_s) + 1;
    segmentIndex = min(polynomial.SegmentCount, max(1, segmentIndex));
    localTau = (time_s(sampleIndex) - ...
        polynomial.SegmentStartTime_s(segmentIndex)) / ...
        polynomial.SegmentDuration_s;
    localTau = min(1, max(0, localTau));
    position_deg(sampleIndex, :) = evaluatePower(reshape( ...
        polynomial.positionPower_deg(segmentIndex, :, :), 2, []), ...
        localTau);
    velocity_deg_s(sampleIndex, :) = evaluatePower(reshape( ...
        polynomial.velocityPower_deg_s(segmentIndex, :, :), 2, []), ...
        localTau);
    acceleration_deg_s2(sampleIndex, :) = evaluatePower(reshape( ...
        polynomial.accelerationPower_deg_s2( ...
        segmentIndex, :, :), 2, []), localTau);
    jerk_deg_s3(sampleIndex, :) = evaluatePower(reshape( ...
        polynomial.jerkPower_deg_s3(segmentIndex, :, :), 2, []), ...
        localTau);
end
end

function value = evaluatePower(powerCoefficient, localTau)
% PURPOSE
%   - Evaluate row-oriented ascending power coefficients at one scalar.
powers = localTau .^ (0:size(powerCoefficient, 2) - 1);
value = (powerCoefficient * powers.').';
end

function coefficient = powerToBernstein(powerCoefficient)
% PURPOSE
%   - Convert ascending power coefficients to same-degree Bernstein form.
powerCoefficient = double(powerCoefficient(:));
degree = numel(powerCoefficient) - 1;
coefficient = zeros(degree + 1, 1);
for bernsteinIndex = 0:degree
    for powerIndex = 0:bernsteinIndex
        coefficient(bernsteinIndex + 1) = ...
            coefficient(bernsteinIndex + 1) + ...
            nchoosek(bernsteinIndex, powerIndex) / ...
            nchoosek(degree, powerIndex) * ...
            powerCoefficient(powerIndex + 1);
    end
end
end

function value = integratedSquaredJerk(decision, isEarliestArrival, ...
        fixedFinalTime_s, segmentCount, startTime_s)
% PURPOSE
%   - Integrate squared quadratic jerk exactly by Simpson quadrature.
controlCount = 2 * segmentCount + 1;
[jerk_deg_s3, finalTime_s] = unpackDecision( ...
    decision, isEarliestArrival, fixedFinalTime_s, controlCount);
segmentDuration_s = (finalTime_s - startTime_s) / segmentCount;
value = 0;
for segmentIndex = 1:segmentCount
    startIndex = 2 * segmentIndex - 1;
    value = value + segmentDuration_s / 6 * sum( ...
        jerk_deg_s3(startIndex, :).^2 + ...
        4 * jerk_deg_s3(startIndex + 1, :).^2 + ...
        jerk_deg_s3(startIndex + 2, :).^2);
end
end

function [jerk_deg_s3, finalTime_s] = unpackDecision( ...
        decision, isEarliestArrival, fixedFinalTime_s, controlCount)
% PURPOSE
%   - Recover jerk ordinates and final time from the compact decision vector.
jerkValueCount = 2 * controlCount;
jerk_deg_s3 = reshape(decision(1:jerkValueCount), controlCount, 2);
if isEarliestArrival
    finalTime_s = decision(end);
else
    finalTime_s = fixedFinalTime_s;
end
end

function goalPosition_deg = goalPositionAtTime(goalState, finalTime_s)
% PURPOSE
%   - Evaluate a fixed or sampled moving terminal position.
if isfield(goalState, "targetTime_s") && ...
        ~isempty(goalState.targetTime_s)
    goalPosition_deg = interp1( ...
        goalState.targetTime_s, goalState.targetPosition_deg, ...
        finalTime_s, goalState.InterpolationMethod);
else
    goalPosition_deg = goalState.position_deg;
end
end

function violation = maximumConstraintViolation(decision, constraintFunction)
% PURPOSE
%   - Reduce nonlinear inequality and equality residuals to one diagnostic.
[inequality, equality] = constraintFunction(decision);
violation = max([0; inequality(:); abs(equality(:))]);
end

function duration_s = durationLowerBound( ...
        initialState, goalState, limits, latestFinalTime_s)
% PURPOSE
%   - Compute an input-driven lower bound without claiming exact optimality.
goalPosition_deg = goalPositionAtTime(goalState, latestFinalTime_s);
displacement_deg = abs(goalPosition_deg - initialState.position_deg);
velocityBound_s = displacement_deg ./ limits.maxVelocity_deg_s;
accelerationBound_s = sqrt( ...
    2 * displacement_deg ./ limits.maxAcceleration_deg_s2);
jerkBound_s = nthroot( ...
    6 * displacement_deg ./ limits.maxJerk_deg_s3, 3);
duration_s = max([1e-3, velocityBound_s, ...
    accelerationBound_s, jerkBound_s]);
end

function candidate = emptyCandidate(seed, segmentCount)
% PURPOSE
%   - Define the same candidate schema for early solver failures.
candidate = struct( ...
    "OptimizerFeasible", false, ...
    "Message", "HS3 was not run.", ...
    "TerminationReason", "notRun", ...
    "SeedIndex", seed.Index, ...
    "SeedSource", seed.Source, ...
    "FinalTime_s", NaN, ...
    "MotionDuration_s", NaN, ...
    "IntegratedSquaredJerk_deg2_s5", Inf, ...
    "MaximumConstraintViolation", Inf, ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2), ...
    "Polynomial", struct("SegmentCount", segmentCount), ...
    "ControlTau", zeros(0, 1), ...
    "ControlJerk_deg_s3", zeros(0, 2), ...
    "Corridor", struct([]), ...
    "SolverDiagnostics", struct( ...
    "StageOneExitFlag", NaN, "StageTwoExitFlag", NaN, ...
    "StageOneOutput", struct(), "StageTwoOutput", struct()));
end
