function [decision, exitFlag, solverOutput, timeLimitReached] = ...
        solveAzElHs3Nlp( ...
        initialDecision, lowerBound, upperBound, layout, meshTau, ...
        corridor, obstacleField, initialState, goalState, limits, ...
        options, objectiveMode, timeBudget_s)
%% Section 0: Header & Readme
% SYNTAX
%   [decision, exitFlag, solverOutput, timeLimitReached] = ...
%       azElInternal.solveAzElHs3Nlp( ...
%       initialDecision, lowerBound, upperBound, layout, meshTau, ...
%       corridor, obstacleField, initialState, goalState, limits, ...
%       options, objectiveMode, timeBudget_s)
%**************************************************************************
% PURPOSE
%   - Solve one reduced HS-3 feasibility, minimum-time, or minimum-jerk
%     problem.
%   - Use fixed-duration affine subproblems when the model permits them.
%**************************************************************************
% INPUTS
%   - initialDecision, lowerBound, upperBound (N-by-1 numeric vectors)
%       Initial reduced decision and its element bounds.
%   - layout (scalar struct)
%       Reduced HS-3 decision indices.
%   - meshTau (M-by-1 numeric vector)
%       Strictly increasing normalized knot times.
%   - corridor, obstacleField (scalar structs)
%       Frozen obstacle separators and canonical obstacle geometry.
%   - initialState, goalState, limits, options (scalar structs)
%       Resolved endpoint states, physical limits, and planner controls.
%   - objectiveMode (string scalar)
%       feasibility, minimumTime, or minimumJerk.
%   - timeBudget_s (nonnegative numeric scalar)
%       Local wall-time budget. Inf disables the local limit.
%**************************************************************************
% OUTPUTS
%   - decision (N-by-1 numeric vector)
%       Best solver decision returned by the selected method.
%   - exitFlag (numeric scalar)
%       Solver status. Positive values indicate solver convergence.
%   - solverOutput (scalar struct)
%       Iteration, evaluation, message, and optional corridor diagnostics.
%   - timeLimitReached (logical scalar)
%       True when the local wall-time budget stopped or followed the solve.
%**************************************************************************
% UNITS
%   - Position is degrees. Time is seconds. Derivative units follow order.
%**************************************************************************

%% Section 1: Select And Run The Solver

solveTimer = tic;
timeLimitReached = false;
minimumAffineEvaluationCount = 2;
usesConvexAffineSolve = ~layout.HasFinalTimeVariable || ...
    objectiveMode == "feasibility" || objectiveMode == "minimumTime";
if usesConvexAffineSolve && ...
        options.MaximumNlpFunctionEvaluations < ...
        minimumAffineEvaluationCount
    decision = initialDecision;
    exitFlag = -1;
    solverOutput = struct( ...
        "iterations", 0, ...
        "funcCount", 0, ...
        "message", "The affine HS-3 subproblem needs at least " + ...
        string(minimumAffineEvaluationCount) + ...
        " constraint-map evaluations, but " + ...
        string(options.MaximumNlpFunctionEvaluations) + ...
        " were allowed.");
    return;
end
if ~layout.HasFinalTimeVariable
    [decision, exitFlag, solverOutput] = ...
        solveFixedArrivalConvexSubproblem( ...
        initialDecision, lowerBound, upperBound, layout, meshTau, ...
        corridor, obstacleField, initialState, goalState, limits, ...
        options, objectiveMode, true);
    timeLimitReached = isfinite(timeBudget_s) && ...
        toc(solveTimer) >= timeBudget_s;
    return;
end
if objectiveMode == "minimumTime"
    [decision, exitFlag, solverOutput, timeLimitReached] = ...
        solveMinimumTimeByConvexContinuation( ...
        initialDecision, lowerBound, upperBound, layout, meshTau, ...
        corridor, obstacleField, initialState, goalState, limits, ...
        options, timeBudget_s, solveTimer);
    return;
end
if objectiveMode == "feasibility"
    fixedLayout = azElInternal.azElHs3DecisionLayout(layout.SegmentCount, false);
    initialSolution = azElInternal.unpackAzElHs3Decision( ...
        initialDecision, layout, meshTau, initialState, goalState);
    trialFinalTime_s = ascendingFeasibilityTimes( ...
        initialState.time_s, initialSolution.FinalTime_s, ...
        goalState.time_s);
    fixedExitFlag = -2;
    fixedOutput = struct( ...
        "iterations", 0, "funcCount", 0, ...
        "message", "No fixed-arrival duration was evaluated.");
    totalFixedIterationCount = 0;
    totalFixedFunctionEvaluationCount = 0;
    initialDuration_s = max(eps, ...
        initialSolution.FinalTime_s - initialState.time_s);
    for trialIndex = 1:numel(trialFinalTime_s)
        if isfinite(timeBudget_s) && toc(solveTimer) >= timeBudget_s
            timeLimitReached = true;
            break;
        end
        fixedGoalState = goalState;
        fixedGoalState.time_s = trialFinalTime_s(trialIndex);
        trialDuration_s = ...
            fixedGoalState.time_s - initialState.time_s;
        controlScale = (initialDuration_s / trialDuration_s) ^ 3;
        fixedInitialSolution = initialSolution;
        fixedInitialSolution.FinalTime_s = fixedGoalState.time_s;
        fixedInitialSolution.KnotControl = ...
            controlScale * initialSolution.KnotControl;
        fixedInitialSolution.MidpointControl = ...
            controlScale * initialSolution.MidpointControl;
        fixedInitialDecision = azElInternal.packAzElHs3Decision( ...
            fixedInitialSolution, fixedLayout);
        [fixedLowerBound, fixedUpperBound] = ...
            azElInternal.boundAzElHs3Decision( ...
            fixedLayout, initialState, fixedGoalState, limits, 0, Inf);
        [fixedDecision, fixedExitFlag, fixedOutput] = ...
            solveFixedArrivalConvexSubproblem( ...
            fixedInitialDecision, fixedLowerBound, fixedUpperBound, ...
            fixedLayout, meshTau, corridor, obstacleField, ...
            initialState, fixedGoalState, limits, options, ...
            objectiveMode, trialIndex == 1);
        totalFixedIterationCount = totalFixedIterationCount + ...
            outputValue(fixedOutput, "iterations");
        totalFixedFunctionEvaluationCount = ...
            totalFixedFunctionEvaluationCount + ...
            outputValue(fixedOutput, "funcCount");
        if fixedExitFlag <= 0
            continue;
        end
        fixedSolution = azElInternal.unpackAzElHs3Decision( ...
            fixedDecision, fixedLayout, meshTau, initialState, ...
            fixedGoalState);
        decision = azElInternal.packAzElHs3Decision(fixedSolution, layout);
        exitFlag = fixedExitFlag;
        solverOutput = fixedOutput;
        solverOutput.iterations = totalFixedIterationCount;
        solverOutput.funcCount = totalFixedFunctionEvaluationCount;
        solverOutput.message = ...
            "An ascending fixed-arrival convex trial established a " + ...
            "feasible point at " + string(fixedGoalState.time_s) + ...
            " seconds. " + string(fixedOutput.message);
        timeLimitReached = isfinite(timeBudget_s) && ...
            toc(solveTimer) >= timeBudget_s;
        return;
    end
    decision = initialDecision;
    exitFlag = fixedExitFlag;
    solverOutput = fixedOutput;
    solverOutput.iterations = totalFixedIterationCount;
    solverOutput.funcCount = totalFixedFunctionEvaluationCount;
    solverOutput.message = ...
        "No ascending fixed-arrival convex trial satisfied the " + ...
        "collision corridor on this mesh. Mesh or corridor refinement " + ...
        "is required. " + string(fixedOutput.message);
    timeLimitReached = isfinite(timeBudget_s) && ...
        toc(solveTimer) >= timeBudget_s;
    return;
end
objectiveFunction = @(decision) nlpObjective( ...
    decision, layout, meshTau, initialState, goalState, limits, ...
    objectiveMode, initialDecision);
constraintFunction = @(decision) azElInternal.evaluateAzElHs3NlpConstraints( ...
    decision, layout, meshTau, corridor, obstacleField, initialState, ...
    goalState, limits, options);
solverOptions = optimoptions("fmincon", ...
    "Algorithm", "interior-point", ...
    "Display", "none", ...
    "MaxIterations", options.MaximumNlpIterations, ...
    "MaxFunctionEvaluations", options.MaximumNlpFunctionEvaluations, ...
    "ConstraintTolerance", options.NlpConstraintTolerance, ...
    "OptimalityTolerance", options.NlpOptimalityTolerance, ...
    "StepTolerance", options.NlpStepTolerance, ...
    "FiniteDifferenceType", "forward", ...
    "ScaleProblem", true, ...
    "TypicalX", max(1, abs(initialDecision)), ...
    "OutputFcn", @stopForTimeBudget);
try
    [decision, ~, exitFlag, solverOutput] = fmincon( ...
        objectiveFunction, initialDecision, [], [], [], [], ...
        lowerBound, upperBound, constraintFunction, solverOptions);
catch exception
    decision = initialDecision;
    exitFlag = -99;
    solverOutput = struct( ...
        "iterations", 0, ...
        "funcCount", 0, ...
        "message", "fmincon failed: " + string(exception.message));
end

%% Section 2: Local Functions

function trialFinalTime_s = ascendingFeasibilityTimes( ...
        initialTime_s, currentFinalTime_s, horizonTime_s)
% PURPOSE
%   - Cover short and long durations without assuming one obstacle event.
horizonDuration_s = horizonTime_s - initialTime_s;
currentDuration_s = min(horizonDuration_s, max(eps, ...
    currentFinalTime_s - initialTime_s));
durationMultiplier = [1; 1.25; 1.5; 2; 3; 4];
geometricDuration_s = currentDuration_s * durationMultiplier;
uniformDuration_s = linspace( ...
    currentDuration_s, horizonDuration_s, 4).';
trialDuration_s = unique([ ...
    geometricDuration_s; uniformDuration_s; horizonDuration_s]);
trialDuration_s = trialDuration_s( ...
    trialDuration_s >= currentDuration_s & ...
    trialDuration_s <= horizonDuration_s);
trialFinalTime_s = initialTime_s + trialDuration_s;
end

function [decision, exitFlag, solverOutput, timeLimitReached] = ...
        solveMinimumTimeByConvexContinuation( ...
        initialDecision, lowerBound, upperBound, layout, meshTau, ...
        corridor, obstacleField, initialState, goalState, limits, ...
        options, timeBudget_s, solveTimer)
% PURPOSE
%   - Reduce arrival time with verified fixed-duration convex subproblems.
% The reduced HS-3 state is affine in jerk for a fixed duration. A local
% time continuation therefore changes only one scalar between exact convex
% subproblems. This avoids a dense finite-difference Jacobian while keeping
% every accepted point subject to the complete collocation constraints.
fixedLayout = azElInternal.azElHs3DecisionLayout(layout.SegmentCount, false);
bestSolution = azElInternal.unpackAzElHs3Decision( ...
    initialDecision, layout, meshTau, initialState, goalState);
minimumFinalTime_s = lowerBound(layout.FinalTimeIndex);
maximumFinalTime_s = upperBound(layout.FinalTimeIndex);
bestSolution.FinalTime_s = min(maximumFinalTime_s, max( ...
    minimumFinalTime_s, bestSolution.FinalTime_s));
trialCount = 0;
[bestFixedDecision, bestExitFlag, bestOutput, bestIsFeasible, ...
    bestCorridor] = ...
    solveFixedTimeTrial( ...
    bestSolution, bestSolution.FinalTime_s, "feasibility");
totalIterationCount = outputValue(bestOutput, "iterations");
totalFunctionEvaluationCount = outputValue(bestOutput, "funcCount");
trialCount = 1;
if ~bestIsFeasible
    decision = initialDecision;
    exitFlag = bestExitFlag;
    solverOutput = bestOutput;
    solverOutput.iterations = totalIterationCount;
    solverOutput.funcCount = totalFunctionEvaluationCount;
    solverOutput.message = ...
        "The initial fixed-duration convex subproblem was infeasible. " + ...
        string(bestOutput.message);
    timeLimitReached = isfinite(timeBudget_s) && ...
        toc(solveTimer) >= timeBudget_s;
    return;
end
bestGoalState = goalState;
bestGoalState.time_s = bestSolution.FinalTime_s;
bestSolution = azElInternal.unpackAzElHs3Decision( ...
    bestFixedDecision, fixedLayout, meshTau, initialState, ...
    bestGoalState);
bestFinalTime_s = bestSolution.FinalTime_s;
% Two independent scalar searches can each stop within half of the public
% arrival-time tie tolerance without changing candidate ordering. The
% one-millisecond floor prevents mesh noise from driving extra map builds.
arrivalTolerance_s = max([options.NlpConstraintTolerance, 1e-3, ...
    0.5 * options.ArrivalTimeTieTolerance_s]);
continuationCount = 0;
maximumTimeContinuationTrialCount = 32;
maximumContinuationCount = min( ...
    maximumTimeContinuationTrialCount, ...
    max(0, options.MaximumNlpIterations));
lastOutput = bestOutput;
boundaryDerivativeTolerance = max( ...
    options.NlpConstraintTolerance, 1e-10);
initialEndpoint = endpointState(initialState);
goalEndpoint = endpointState(goalState);
hasZeroBoundaryDerivatives = max(abs([ ...
    initialEndpoint(3:6), goalEndpoint(3:6)])) <= ...
    boundaryDerivativeTolerance;
geometryIsTimeInvariant = isfield(corridor, "GeometryTimeInvariant") && ...
    corridor.GeometryTimeInvariant;
usesMonotoneStaticBisection = geometryIsTimeInvariant && ...
    hasZeroBoundaryDerivatives;
if usesMonotoneStaticBisection
    infeasibleFinalTime_s = minimumFinalTime_s;
    feasibleFinalTime_s = bestFinalTime_s;
    while feasibleFinalTime_s - infeasibleFinalTime_s > ...
            arrivalTolerance_s && ...
            continuationCount < maximumContinuationCount && ...
            totalFunctionEvaluationCount < ...
            options.MaximumNlpFunctionEvaluations
        if timeLimitReachedForContinuation()
            break;
        end
        trialFinalTime_s = 0.5 * ...
            (infeasibleFinalTime_s + feasibleFinalTime_s);
        [trialDecision, trialExitFlag, trialOutput, trialIsFeasible, ...
            trialCorridor] = solveFixedTimeTrial( ...
            bestSolution, trialFinalTime_s, "feasibility");
        continuationCount = continuationCount + 1;
        trialCount = trialCount + 1;
        totalIterationCount = totalIterationCount + ...
            outputValue(trialOutput, "iterations");
        totalFunctionEvaluationCount = ...
            totalFunctionEvaluationCount + ...
            outputValue(trialOutput, "funcCount");
        lastOutput = trialOutput;
        if trialIsFeasible
            trialGoalState = goalState;
            trialGoalState.time_s = trialFinalTime_s;
            bestExitFlag = trialExitFlag;
            bestSolution = azElInternal.unpackAzElHs3Decision( ...
                trialDecision, fixedLayout, meshTau, initialState, ...
                trialGoalState);
            feasibleFinalTime_s = trialFinalTime_s;
            bestCorridor = trialCorridor;
        else
            infeasibleFinalTime_s = trialFinalTime_s;
        end
    end
else
    timeStep_s = 0.5 * (bestFinalTime_s - minimumFinalTime_s);
    while timeStep_s > arrivalTolerance_s && ...
            bestFinalTime_s - minimumFinalTime_s > arrivalTolerance_s && ...
            continuationCount < maximumContinuationCount && ...
            totalFunctionEvaluationCount < ...
            options.MaximumNlpFunctionEvaluations
        if timeLimitReachedForContinuation()
            break;
        end
        trialFinalTime_s = max( ...
            minimumFinalTime_s, bestFinalTime_s - timeStep_s);
        [trialDecision, trialExitFlag, trialOutput, trialIsFeasible, ...
            trialCorridor] = solveFixedTimeTrial( ...
            bestSolution, trialFinalTime_s, "feasibility");
        continuationCount = continuationCount + 1;
        trialCount = trialCount + 1;
        totalIterationCount = totalIterationCount + ...
            outputValue(trialOutput, "iterations");
        totalFunctionEvaluationCount = ...
            totalFunctionEvaluationCount + ...
            outputValue(trialOutput, "funcCount");
        lastOutput = trialOutput;
        if trialIsFeasible
            trialGoalState = goalState;
            trialGoalState.time_s = trialFinalTime_s;
            bestExitFlag = trialExitFlag;
            bestSolution = azElInternal.unpackAzElHs3Decision( ...
                trialDecision, fixedLayout, meshTau, initialState, ...
                trialGoalState);
            bestFinalTime_s = trialFinalTime_s;
            bestCorridor = trialCorridor;
            timeStep_s = min(bestFinalTime_s - minimumFinalTime_s, ...
                1.5 * timeStep_s);
        else
            timeStep_s = 0.5 * timeStep_s;
        end
    end
end
decision = azElInternal.packAzElHs3Decision(bestSolution, layout);
exitFlag = bestExitFlag;
solverOutput = lastOutput;
solverOutput.iterations = totalIterationCount;
solverOutput.funcCount = totalFunctionEvaluationCount;
solverOutput.Corridor = bestCorridor;
continuationMessage = "Local arrival-time continuation";
if usesMonotoneStaticBisection
    continuationMessage = "Monotone static arrival-time bisection";
end
solverOutput.message = ...
    continuationMessage + " retained a verified convex " + ...
    "subproblem after " + string(trialCount) + " duration trials. " + ...
    string(lastOutput.message);
timeLimitReached = isfinite(timeBudget_s) && ...
    toc(solveTimer) >= timeBudget_s;

    function [fixedDecision, fixedExitFlag, fixedOutput, isFeasible, ...
            trialCorridor] = ...
            solveFixedTimeTrial( ...
            referenceSolution, trialFinalTime_s, trialObjectiveMode)
        % PURPOSE
        %   - Solve and verify one fixed-duration continuation point.
        referenceDuration_s = max(eps, ...
            referenceSolution.FinalTime_s - initialState.time_s);
        trialDuration_s = max(eps, ...
            trialFinalTime_s - initialState.time_s);
        controlScale = (referenceDuration_s / trialDuration_s) ^ 3;
        trialSolution = referenceSolution;
        trialSolution.FinalTime_s = trialFinalTime_s;
        trialSolution.KnotControl = ...
            controlScale * referenceSolution.KnotControl;
        trialSolution.MidpointControl = ...
            controlScale * referenceSolution.MidpointControl;
        trialCorridor = corridor;
        geometryIsTimeInvariant = isfield( ...
            corridor, "GeometryTimeInvariant") && ...
            corridor.GeometryTimeInvariant;
        if ~geometryIsTimeInvariant
            trialCorridor = azElInternal.buildAzElHs3OptimizationCorridor( ...
                trialSolution, meshTau, obstacleField, ...
                initialState.time_s, zeros(0, 2), ...
                corridor.PointTau);
            if isfield(corridor, "PointClearance_deg") && ...
                    numel(corridor.PointClearance_deg) == ...
                    numel(trialCorridor.PointTau)
                trialCorridor.PointClearance_deg = ...
                    corridor.PointClearance_deg;
            end
            trialCorridor.GeometryTimeInvariant = false;
        end
        fixedInitialDecision = azElInternal.packAzElHs3Decision( ...
            trialSolution, fixedLayout);
        trialGoalState = goalState;
        trialGoalState.time_s = trialFinalTime_s;
        [fixedLowerBound, fixedUpperBound] = ...
            azElInternal.boundAzElHs3Decision( ...
            fixedLayout, initialState, trialGoalState, limits, 0, Inf);
        [fixedDecision, fixedExitFlag, fixedOutput] = ...
            solveFixedArrivalConvexSubproblem( ...
            fixedInitialDecision, fixedLowerBound, fixedUpperBound, ...
            fixedLayout, meshTau, trialCorridor, obstacleField, ...
            initialState, trialGoalState, limits, options, ...
            trialObjectiveMode, trialCount == 0);
        [trialInequality, trialEquality] = azElInternal.evaluateAzElHs3NlpConstraints( ...
            fixedDecision, fixedLayout, meshTau, trialCorridor, ...
            obstacleField, initialState, trialGoalState, limits, ...
            options);
        verificationTolerance = max( ...
            options.NlpConstraintTolerance, 1e-10);
        isFeasible = fixedExitFlag > 0 && ...
            maximumOrZero(trialInequality) <= verificationTolerance && ...
            maximumAbsoluteOrZero(trialEquality) <= ...
            verificationTolerance;
    end

    function reached = timeLimitReachedForContinuation()
        % PURPOSE
        %   - Apply the local wall-time limit between convex subproblems.
        reached = isfinite(timeBudget_s) && ...
            toc(solveTimer) >= timeBudget_s;
    end
end

function [decision, exitFlag, solverOutput] = ...
        solveFixedArrivalConvexSubproblem( ...
        initialDecision, lowerBound, upperBound, layout, meshTau, ...
        corridor, obstacleField, initialState, goalState, limits, ...
        options, objectiveMode, verifyAffineMap)
% PURPOSE
%   - Solve the fixed-duration affine HS-3 subproblem without finite
%     differences.
% With fixed duration and frozen obstacle half-spaces, reduced HS-3 states
% and every enforced constraint are affine functions of the jerk ordinates.
% Direct dynamics propagation constructs that affine map once. This
% prevents an NLP tolerance from hiding an exact terminal-state constraint.
[inequalityMatrix, baseInequality, equalityMatrix, baseEquality] = ...
    fixedArrivalAffineConstraintMap( ...
    layout, meshTau, corridor, obstacleField, initialState, goalState, ...
    limits, options);
inequalityTarget = -baseInequality;
equalityTarget = -baseEquality;

if verifyAffineMap
    % Verify one map for each continuation. Duration changes only analytic
    % coefficients. Repeating this implementation check at every trial
    % previously rebuilt the full constraints twice per scalar time step.
    [initialInequality, initialEquality] = azElInternal.evaluateAzElHs3NlpConstraints( ...
        initialDecision, layout, meshTau, corridor, obstacleField, ...
        initialState, goalState, limits, options);
    probeDecision = 0.37 * lowerBound + 0.63 * upperBound;
    [probeInequality, probeEquality] = azElInternal.evaluateAzElHs3NlpConstraints( ...
        probeDecision, layout, meshTau, corridor, obstacleField, ...
        initialState, goalState, limits, options);
    affineResidual = max([0; abs(initialInequality - ...
        (inequalityMatrix * initialDecision + baseInequality)); ...
        abs(initialEquality - ...
        (equalityMatrix * initialDecision + baseEquality)); ...
        abs(probeInequality - ...
        (inequalityMatrix * probeDecision + baseInequality)); ...
        abs(probeEquality - ...
        (equalityMatrix * probeDecision + baseEquality))]);
    affineTolerance = max(1e-10, 10 * eps(max(1, ...
        max(abs([initialInequality; initialEquality; ...
        probeInequality; probeEquality])))));
    if affineResidual > affineTolerance
        decision = initialDecision;
        exitFlag = -99;
        solverOutput = struct( ...
            "iterations", 0, ...
            "funcCount", minimumAffineEvaluationCount, ...
            "message", "The fixed-arrival constraint map was not " + ...
            "affine. The convex solve was not used.");
        return;
    end
end

if objectiveMode == "minimumJerk"
    objectiveMatrix = fixedArrivalJerkObjectiveMatrix( ...
        layout, meshTau, goalState.time_s - initialState.time_s);
    objectiveTarget = zeros(size(objectiveMatrix, 1), 1);
else
    decisionScale = max(1, abs(initialDecision));
    objectiveMatrix = diag(1 ./ decisionScale);
    objectiveTarget = objectiveMatrix * initialDecision;
end
constraintMagnitude = max([1; abs(inequalityMatrix(:)); ...
    abs(equalityMatrix(:)); abs(inequalityTarget(:)); ...
    abs(equalityTarget(:))]);
linearConstraintTolerance = max(100 * eps, ...
    options.NlpConstraintTolerance / constraintMagnitude);
try
    linearOptions = optimoptions("lsqlin", ...
        "Algorithm", "active-set", ...
        "Display", "none", ...
        "ConstraintTolerance", linearConstraintTolerance, ...
        "OptimalityTolerance", options.NlpOptimalityTolerance, ...
        "StepTolerance", options.NlpStepTolerance);
    [decision, ~, ~, exitFlag, solverOutput] = lsqlin( ...
        objectiveMatrix, objectiveTarget, inequalityMatrix, ...
        inequalityTarget, equalityMatrix, equalityTarget, ...
        lowerBound, upperBound, initialDecision, linearOptions);
    solverOutput.funcCount = minimumAffineEvaluationCount;
catch exception
    decision = initialDecision;
    exitFlag = -99;
    solverOutput = struct( ...
        "iterations", 0, ...
        "funcCount", minimumAffineEvaluationCount, ...
        "message", "The fixed-arrival convex solver failed: " + ...
        string(exception.message));
end
end

function objectiveMatrix = fixedArrivalJerkObjectiveMatrix( ...
        layout, meshTau, duration_s)
% PURPOSE
%   - Factor the exact integral of squared quadratic jerk on the mesh.
% The three local jerk ordinates occur at normalized times 0, 1/2, and 1.
% Their Lagrange-basis Gram matrix is exact for quadratic jerk.
localGram = [4, 2, -1; 2, 16, 2; -1, 2, 4] / 30;
quadraticMatrix = zeros(layout.DecisionCount);
segmentCount = numel(meshTau) - 1;
for axisIndex = 1:2
    knotOffset = (axisIndex - 1) * (segmentCount + 1);
    midpointOffset = (axisIndex - 1) * segmentCount;
    for segmentIndex = 1:segmentCount
        localIndex = [ ...
            layout.KnotControlIndex(knotOffset + segmentIndex), ...
            layout.MidpointControlIndex( ...
            midpointOffset + segmentIndex), ...
            layout.KnotControlIndex(knotOffset + segmentIndex + 1)];
        segmentDuration_s = duration_s * ...
            (meshTau(segmentIndex + 1) - meshTau(segmentIndex));
        quadraticMatrix(localIndex, localIndex) = ...
            quadraticMatrix(localIndex, localIndex) + ...
            segmentDuration_s * localGram;
    end
end
quadraticMatrix = 0.5 * (quadraticMatrix + quadraticMatrix.');
[objectiveMatrix, factorFlag] = chol(quadraticMatrix, "upper");
if factorFlag ~= 0
    [eigenvector, eigenvalue] = eig(quadraticMatrix, "vector");
    eigenvalue = max(0, real(eigenvalue));
    objectiveMatrix = diag(sqrt(eigenvalue)) * eigenvector.';
end
end

function [inequalityMatrix, inequalityOffset, equalityMatrix, ...
        equalityOffset] = fixedArrivalAffineConstraintMap( ...
        layout, meshTau, corridor, obstacleField, initialState, ...
        goalState, limits, options)
% PURPOSE
%   - Assemble the exact fixed-duration HS-3 constraint map once.
if layout.HasFinalTimeVariable
    error("solveAzElHs3Nlp:AffineMapHasTimeVariable", ...
        "A fixed-arrival affine map cannot contain a final-time variable.");
end
duration_s = goalState.time_s - initialState.time_s;
initialEndpoint = endpointState(initialState);
goalEndpoint = endpointState(goalState);
axisResponse = cell(2, 1);
axisDecisionIndex = cell(2, 1);
for axisIndex = 1:2
    stateIndex = [axisIndex, axisIndex + 2, axisIndex + 4];
    axisResponse{axisIndex} = fixedArrivalAxisResponse( ...
        meshTau, duration_s, initialEndpoint(stateIndex), ...
        corridor.PointTau);
    axisDecisionIndex{axisIndex} = ...
        timeOrderedAxisDecisionIndex(layout, axisIndex);
end

equalityMatrix = zeros(6, layout.DecisionCount);
equalityOffset = zeros(6, 1);
for axisIndex = 1:2
    stateIndex = [axisIndex, axisIndex + 2, axisIndex + 4];
    equalityMatrix(stateIndex, axisDecisionIndex{axisIndex}) = ...
        axisResponse{axisIndex}.FinalStateMatrix;
    equalityOffset(stateIndex) = ...
        axisResponse{axisIndex}.FinalStateBase(:) - ...
        goalEndpoint(stateIndex).';
end
[corridorMatrix, corridorOffset] = fixedArrivalCorridorConstraintMap( ...
    layout, meshTau, corridor, obstacleField, initialState.time_s, ...
    duration_s, options.ObstacleConstraintTolerance_deg, ...
    axisResponse, axisDecisionIndex);
[kinematicMatrix, kinematicOffset] = ...
    fixedArrivalKinematicConstraintMap( ...
    layout, limits, options, axisResponse, axisDecisionIndex);
inequalityMatrix = [corridorMatrix; kinematicMatrix];
inequalityOffset = [corridorOffset; kinematicOffset];
end

function response = fixedArrivalAxisResponse( ...
        meshTau, duration_s, initialAxisState, pointTau)
% PURPOSE
%   - Propagate all one-axis jerk basis vectors in one mesh pass.
segmentCount = numel(meshTau) - 1;
controlCount = 2 * segmentCount + 1;
pointTau = pointTau(:);
pointPositionBase = zeros(numel(pointTau), 1);
pointPositionMatrix = zeros(numel(pointTau), controlCount);
stateBernsteinBase = zeros(segmentCount, 6, 3);
stateBernsteinMatrix = zeros(segmentCount, 6, 3, controlCount);
interiorControlMatrix = zeros(segmentCount, controlCount);
startStateBase = reshape(initialAxisState, 1, 3);
startStateMatrix = zeros(3, controlCount);
bernsteinTransform = azElInternal.powerToBernstein(eye(6));
for segmentIndex = 1:segmentCount
    firstControlIndex = 2 * segmentIndex - 1;
    midpointControlIndex = firstControlIndex + 1;
    lastControlIndex = firstControlIndex + 2;
    firstControlRow = zeros(1, controlCount);
    midpointControlRow = zeros(1, controlCount);
    lastControlRow = zeros(1, controlCount);
    firstControlRow(firstControlIndex) = 1;
    midpointControlRow(midpointControlIndex) = 1;
    lastControlRow(lastControlIndex) = 1;
    controlPowerMatrix = [firstControlRow; ...
        -3 * firstControlRow + 4 * midpointControlRow - ...
        lastControlRow; ...
        2 * firstControlRow - 4 * midpointControlRow + ...
        2 * lastControlRow];
    interiorControlMatrix(segmentIndex, :) = ...
        -0.5 * firstControlRow + 2 * midpointControlRow - ...
        0.5 * lastControlRow;

    segmentDuration_s = duration_s * ...
        (meshTau(segmentIndex + 1) - meshTau(segmentIndex));
    h = segmentDuration_s;
    statePowerBase = zeros(6, 3);
    statePowerBase(1, :) = startStateBase;
    statePowerBase(2, 1) = h * startStateBase(2);
    statePowerBase(3, 1) = h ^ 2 * startStateBase(3) / 2;
    statePowerBase(2, 2) = h * startStateBase(3);
    statePowerMatrix = zeros(6, 3, controlCount);
    statePowerMatrix(1, :, :) = reshape( ...
        startStateMatrix, 1, 3, controlCount);
    statePowerMatrix(2, 1, :) = reshape( ...
        h * startStateMatrix(2, :), 1, 1, controlCount);
    statePowerMatrix(3, 1, :) = reshape( ...
        h ^ 2 * startStateMatrix(3, :) / 2, 1, 1, controlCount);
    statePowerMatrix(4, 1, :) = reshape( ...
        h ^ 3 * controlPowerMatrix(1, :) / 6, ...
        1, 1, controlCount);
    statePowerMatrix(5, 1, :) = reshape( ...
        h ^ 3 * controlPowerMatrix(2, :) / 24, ...
        1, 1, controlCount);
    statePowerMatrix(6, 1, :) = reshape( ...
        h ^ 3 * controlPowerMatrix(3, :) / 60, ...
        1, 1, controlCount);
    statePowerMatrix(2, 2, :) = reshape( ...
        h * startStateMatrix(3, :), 1, 1, controlCount);
    statePowerMatrix(3, 2, :) = reshape( ...
        h ^ 2 * controlPowerMatrix(1, :) / 2, ...
        1, 1, controlCount);
    statePowerMatrix(4, 2, :) = reshape( ...
        h ^ 2 * controlPowerMatrix(2, :) / 6, ...
        1, 1, controlCount);
    statePowerMatrix(5, 2, :) = reshape( ...
        h ^ 2 * controlPowerMatrix(3, :) / 12, ...
        1, 1, controlCount);
    statePowerMatrix(2, 3, :) = reshape( ...
        h * controlPowerMatrix(1, :), 1, 1, controlCount);
    statePowerMatrix(3, 3, :) = reshape( ...
        h * controlPowerMatrix(2, :) / 2, ...
        1, 1, controlCount);
    statePowerMatrix(4, 3, :) = reshape( ...
        h * controlPowerMatrix(3, :) / 3, ...
        1, 1, controlCount);

    stateBernsteinBase(segmentIndex, :, :) = ...
        bernsteinTransform * statePowerBase;
    flatPowerMatrix = reshape( ...
        statePowerMatrix, 6, 3 * controlCount);
    stateBernsteinMatrix(segmentIndex, :, :, :) = reshape( ...
        bernsteinTransform * flatPowerMatrix, ...
        1, 6, 3, controlCount);
    if segmentIndex < segmentCount
        pointIsInSegment = pointTau >= meshTau(segmentIndex) & ...
            pointTau < meshTau(segmentIndex + 1);
    else
        pointIsInSegment = pointTau >= meshTau(segmentIndex) & ...
            pointTau <= meshTau(segmentIndex + 1);
    end
    if segmentIndex == 1
        pointIsInSegment = pointIsInSegment | pointTau < meshTau(1);
    elseif segmentIndex == segmentCount
        pointIsInSegment = pointIsInSegment | pointTau > meshTau(end);
    end
    pointIndex = find(pointIsInSegment);
    if ~isempty(pointIndex)
        segmentWidth = meshTau(segmentIndex + 1) - ...
            meshTau(segmentIndex);
        localTau = (pointTau(pointIndex) - meshTau(segmentIndex)) / ...
            segmentWidth;
        localTau = min(1, max(0, localTau));
        localPower = localTau .^ (0:5);
        pointPositionBase(pointIndex) = ...
            localPower * statePowerBase(:, 1);
        pointPositionMatrix(pointIndex, :) = ...
            localPower * reshape( ...
            statePowerMatrix(:, 1, :), 6, controlCount);
    end
    startStateBase = sum(statePowerBase, 1);
    startStateMatrix = reshape( ...
        sum(statePowerMatrix, 1), 3, controlCount);
end
response = struct( ...
    "PointPositionBase", pointPositionBase, ...
    "PointPositionMatrix", pointPositionMatrix, ...
    "StateBernsteinBase", stateBernsteinBase, ...
    "StateBernsteinMatrix", stateBernsteinMatrix, ...
    "InteriorControlMatrix", interiorControlMatrix, ...
    "FinalStateBase", startStateBase, ...
    "FinalStateMatrix", startStateMatrix);
end

function decisionIndex = timeOrderedAxisDecisionIndex(layout, axisIndex)
% PURPOSE
%   - Map one axis of time-ordered jerk to the packed decision columns.
segmentCount = layout.SegmentCount;
knotIndex = reshape( ...
    layout.KnotControlIndex, segmentCount + 1, 2);
midpointIndex = reshape( ...
    layout.MidpointControlIndex, segmentCount, 2);
decisionIndex = zeros(2 * segmentCount + 1, 1);
decisionIndex(1:2:end) = knotIndex(:, axisIndex);
decisionIndex(2:2:end) = midpointIndex(:, axisIndex);
end

function [inequalityMatrix, inequalityOffset] = ...
        fixedArrivalCorridorConstraintMap( ...
        layout, meshTau, corridor, obstacleField, initialTime_s, ...
        duration_s, clearance_deg, axisResponse, axisDecisionIndex)
% PURPOSE
%   - Assemble point and static polynomial half-space constraints.
pointCount = numel(corridor.PointTau);
obstacleCount = numel(obstacleField.Obstacles);
pointClearance_deg = clearance_deg * ones(pointCount, 1);
if isfield(corridor, "PointClearance_deg") && ...
        numel(corridor.PointClearance_deg) == pointCount
    pointClearance_deg = max( ...
        pointClearance_deg, corridor.PointClearance_deg(:));
end
isStaticCorridor = isfield(corridor, "GeometryTimeInvariant") && ...
    corridor.GeometryTimeInvariant && ...
    isfield(corridor, "SelectedEdgeStart_deg");
polynomialConstraintRow = staticPolynomialConstraintRows( ...
    meshTau, corridor, isStaticCorridor);
maximumRowCount = nnz(corridor.Active) + ...
    6 * nnz(corridor.Active(polynomialConstraintRow, :));
inequalityMatrix = zeros(maximumRowCount, layout.DecisionCount);
inequalityOffset = -ones(maximumRowCount, 1);
pointTime_s = initialTime_s + duration_s * corridor.PointTau;
if isStaticCorridor
    edgeSets_deg = cell(0, 0);
else
    edgeSets_deg = azElInternal.interpolateAzElObstacleEdges( ...
        obstacleField, pointTime_s);
end
constraintIndex = 0;
for pointIndex = 1:pointCount
    for obstacleIndex = 1:obstacleCount
        if ~corridor.Active(pointIndex, obstacleIndex)
            continue;
        end
        constraintIndex = constraintIndex + 1;
        if isStaticCorridor
            edgeStart_deg = reshape(corridor.SelectedEdgeStart_deg( ...
                pointIndex, obstacleIndex, :), 1, 2);
            normal = reshape(corridor.SelectedNormal( ...
                pointIndex, obstacleIndex, :), 1, 2);
        else
            edges_deg = edgeSets_deg{pointIndex, obstacleIndex};
            if isempty(edges_deg)
                inequalityOffset(constraintIndex) = -1;
                continue;
            end
            selectedEdgeIndex = min(size(edges_deg, 1), max(1, ...
                corridor.EdgeIndex(pointIndex, obstacleIndex)));
            edge_deg = edges_deg(selectedEdgeIndex, :);
            tangent_deg = edge_deg(3:4) - edge_deg(1:2);
            leftNormal = [-tangent_deg(2), tangent_deg(1)];
            normalLength = norm(leftNormal);
            if normalLength <= eps
                inequalityOffset(constraintIndex) = clearance_deg;
                continue;
            end
            normal = corridor.SideSign(pointIndex, obstacleIndex) * ...
                leftNormal / normalLength;
            edgeStart_deg = edge_deg(1:2);
        end
        basePosition_deg = [ ...
            axisResponse{1}.PointPositionBase(pointIndex), ...
            axisResponse{2}.PointPositionBase(pointIndex)];
        inequalityOffset(constraintIndex) = ...
            pointClearance_deg(pointIndex) - dot( ...
            basePosition_deg - edgeStart_deg, normal);
        for axisIndex = 1:2
            inequalityMatrix(constraintIndex, ...
                axisDecisionIndex{axisIndex}) = -normal(axisIndex) * ...
                axisResponse{axisIndex}.PointPositionMatrix( ...
                pointIndex, :);
        end
    end
end
if isStaticCorridor
    tauTolerance = 64 * eps(max(1, max(abs(meshTau))));
    for segmentIndex = 1:numel(meshTau) - 1
        if segmentIndex < numel(meshTau) - 1
            rowIsInSegment = corridor.PointTau >= ...
                meshTau(segmentIndex) - tauTolerance & ...
                corridor.PointTau < ...
                meshTau(segmentIndex + 1) - tauTolerance;
        else
            rowIsInSegment = corridor.PointTau >= ...
                meshTau(segmentIndex) - tauTolerance & ...
                corridor.PointTau <= ...
                meshTau(segmentIndex + 1) + tauTolerance;
        end
        corridorRows = find(polynomialConstraintRow & rowIsInSegment);
        for corridorRow = reshape(corridorRows, 1, [])
            for obstacleIndex = 1:obstacleCount
                if ~corridor.Active(corridorRow, obstacleIndex)
                    continue;
                end
                edgeStart_deg = reshape( ...
                    corridor.SelectedEdgeStart_deg( ...
                    corridorRow, obstacleIndex, :), 1, 2);
                normal = reshape(corridor.SelectedNormal( ...
                    corridorRow, obstacleIndex, :), 1, 2);
                polynomialClearance_deg = max( ...
                    clearance_deg, pointClearance_deg(corridorRow));
                for bernsteinIndex = 1:6
                    constraintIndex = constraintIndex + 1;
                    basePosition_deg = [ ...
                        axisResponse{1}.StateBernsteinBase( ...
                        segmentIndex, bernsteinIndex, 1), ...
                        axisResponse{2}.StateBernsteinBase( ...
                        segmentIndex, bernsteinIndex, 1)];
                    inequalityOffset(constraintIndex) = ...
                        polynomialClearance_deg - dot( ...
                        basePosition_deg - edgeStart_deg, normal);
                    for axisIndex = 1:2
                        responseRow = reshape( ...
                            axisResponse{axisIndex}. ...
                            StateBernsteinMatrix( ...
                            segmentIndex, bernsteinIndex, 1, :), ...
                            1, []);
                        inequalityMatrix(constraintIndex, ...
                            axisDecisionIndex{axisIndex}) = ...
                            -normal(axisIndex) * responseRow;
                    end
                end
            end
        end
    end
end
inequalityMatrix = inequalityMatrix(1:constraintIndex, :);
inequalityOffset = inequalityOffset(1:constraintIndex);
end

function polynomialConstraintRow = staticPolynomialConstraintRows( ...
        meshTau, corridor, isStaticCorridor)
% PURPOSE
%   - Select the midpoint corridor row for each static HS-3 segment.
polynomialConstraintRow = false(numel(corridor.PointTau), 1);
if ~isStaticCorridor
    return;
end
tauTolerance = 64 * eps(max(1, max(abs(meshTau))));
for segmentIndex = 1:numel(meshTau) - 1
    midpointTau = 0.5 * ...
        (meshTau(segmentIndex) + meshTau(segmentIndex + 1));
    [midpointDistance, midpointRow] = min(abs( ...
        corridor.PointTau - midpointTau));
    if midpointDistance <= tauTolerance
        polynomialConstraintRow(midpointRow) = true;
    end
end
end

function [inequalityMatrix, inequalityOffset] = ...
        fixedArrivalKinematicConstraintMap( ...
        layout, limits, options, axisResponse, axisDecisionIndex)
% PURPOSE
%   - Assemble continuous state and jerk Bernstein bounds.
azimuthBounds_deg = [-Inf Inf];
if ~options.AllowAzimuthWrapping
    azimuthBounds_deg = options.AzimuthInterval_deg;
end
stateLower = [azimuthBounds_deg(1), ...
    options.ElevationInterval_deg(1), ...
    -limits.maxVelocity_deg_s, -limits.maxAcceleration_deg_s2];
stateUpper = [azimuthBounds_deg(2), ...
    options.ElevationInterval_deg(2), ...
    limits.maxVelocity_deg_s, limits.maxAcceleration_deg_s2];
finiteStateIndex = find(isfinite(stateLower) & isfinite(stateUpper));
rowsPerSegment = 12 * numel(finiteStateIndex) + 4;
inequalityMatrix = zeros( ...
    layout.SegmentCount * rowsPerSegment, layout.DecisionCount);
inequalityOffset = zeros(layout.SegmentCount * rowsPerSegment, 1);
writeIndex = 0;
for segmentIndex = 1:layout.SegmentCount
    for componentIndex = reshape(finiteStateIndex, 1, [])
        axisIndex = mod(componentIndex - 1, 2) + 1;
        stateIndex = ceil(componentIndex / 2);
        baseValue = reshape(axisResponse{axisIndex}. ...
            StateBernsteinBase(segmentIndex, :, stateIndex), 6, 1);
        responseMatrix = reshape(axisResponse{axisIndex}. ...
            StateBernsteinMatrix(segmentIndex, :, stateIndex, :), ...
            6, []);
        row = writeIndex + (1:6);
        inequalityMatrix(row, axisDecisionIndex{axisIndex}) = ...
            -responseMatrix;
        inequalityOffset(row) = stateLower(componentIndex) - baseValue;
        writeIndex = writeIndex + 6;
    end
    for componentIndex = reshape(finiteStateIndex, 1, [])
        axisIndex = mod(componentIndex - 1, 2) + 1;
        stateIndex = ceil(componentIndex / 2);
        baseValue = reshape(axisResponse{axisIndex}. ...
            StateBernsteinBase(segmentIndex, :, stateIndex), 6, 1);
        responseMatrix = reshape(axisResponse{axisIndex}. ...
            StateBernsteinMatrix(segmentIndex, :, stateIndex, :), ...
            6, []);
        row = writeIndex + (1:6);
        inequalityMatrix(row, axisDecisionIndex{axisIndex}) = ...
            responseMatrix;
        inequalityOffset(row) = baseValue - stateUpper(componentIndex);
        writeIndex = writeIndex + 6;
    end
    for axisIndex = 1:2
        responseRow = axisResponse{axisIndex}. ...
            InteriorControlMatrix(segmentIndex, :);
        writeIndex = writeIndex + 1;
        inequalityMatrix(writeIndex, ...
            axisDecisionIndex{axisIndex}) = -responseRow;
        inequalityOffset(writeIndex) = -limits.maxJerk_deg_s3(axisIndex);
        writeIndex = writeIndex + 1;
        inequalityMatrix(writeIndex, ...
            axisDecisionIndex{axisIndex}) = responseRow;
        inequalityOffset(writeIndex) = -limits.maxJerk_deg_s3(axisIndex);
    end
end
end

    function stop = stopForTimeBudget(~, ~, ~)
        % PURPOSE
        %   - Stop one solver call at its assigned local time limit.
        stop = isfinite(timeBudget_s) && toc(solveTimer) >= timeBudget_s;
        timeLimitReached = timeLimitReached || stop;
    end

    function objective = nlpObjective( ...
            decisionValue, decisionLayoutValue, meshTauValue, ...
            initialStateValue, goalStateValue, limitsValue, ...
            objectiveModeValue, referenceDecision)
        % PURPOSE
        %   - Select feasibility, minimum-time, or jerk objectives.
        if objectiveModeValue == "feasibility"
            decisionScale = max(1, abs(referenceDecision));
            normalizedChange = ...
                (decisionValue - referenceDecision) ./ decisionScale;
            objective = mean(normalizedChange .^ 2);
            return;
        end
        solutionValue = azElInternal.unpackAzElHs3Decision( ...
            decisionValue, decisionLayoutValue, meshTauValue, ...
            initialStateValue, goalStateValue);
        horizon_s = goalStateValue.time_s - initialStateValue.time_s;
        if objectiveModeValue == "minimumTime"
            objective = (solutionValue.FinalTime_s - ...
                initialStateValue.time_s) / max(horizon_s, eps);
        else
            jerkScale = max(1, horizon_s * ...
                sum(limitsValue.maxJerk_deg_s3 .^ 2));
            objective = azElInternal.azElHs3IntegratedSquaredJerk( ...
                solutionValue, meshTauValue) / jerkScale;
        end
    end

    function state = endpointState(endpoint)
        % PURPOSE
        %   - Assemble one exact six-component endpoint row.
        state = [endpoint.position_deg, endpoint.velocity_deg_s, ...
            endpoint.acceleration_deg_s2];
    end

    function value = maximumOrZero(vector)
        % PURPOSE
        %   - Return the positive violation of an optional vector.
        if isempty(vector)
            value = 0;
        else
            value = max(0, max(vector));
        end
    end

    function value = maximumAbsoluteOrZero(vector)
        % PURPOSE
        %   - Return the maximum magnitude of an optional vector.
        if isempty(vector)
            value = 0;
        else
            value = max(abs(vector));
        end
    end

    function value = outputValue(output, fieldName)
        % PURPOSE
        %   - Read an optional numeric solver-output field.
        value = 0;
        if isstruct(output) && isfield(output, fieldName) && ...
                isfinite(output.(fieldName))
            value = output.(fieldName);
        end
    end

end
