function candidate = solveAzElHs3(obstacles, initialState, goalState, limits, options, seed)
%% Section 0: Header & Readme
% SYNTAX
%   candidate = azElInternal.solveAzElHs3(obstacles, initialState, ...
%       goalState, limits, options, seed)
%**************************************************************************
% PURPOSE
%   - Solve and reconstruct one separated third-order Hermite-Simpson motion.
%**************************************************************************
% INPUTS
%   - obstacles (canonical protected obstacle struct array)
%   - initialState, goalState (normalized scalar state structs)
%   - limits (normalized scalar limits struct)
%   - options (resolved planner options)
%   - seed (scalar topology-seed struct)
%       position_deg is N-by-2 and tau is a strictly increasing N-vector.
%**************************************************************************
% OUTPUTS
%   - candidate (scalar struct)
%       Solver outcome, polynomial trajectory, samples, and diagnostics.
%**************************************************************************
% UNITS
%   - Position is degrees; derivatives use deg/s, deg/s^2, and deg/s^3.
%**************************************************************************
%% Section 1: Build The Decision Layout And Initial Guess
solverTimer = tic;
maximumSolverTime_s = options.MaximumSolverTime_s;
if isempty(obstacles) && ~isstruct(obstacles)
    obstacles = combineAzElObstacles(obstacles);
end
obstacles = azElInternal.prepareDynamicObstacles(obstacles);
segmentCount = options.CollocationSegmentCount;
if ~isfield(seed, "CorridorBoundary_deg")
    seed.CorridorBoundary_deg = zeros(0, 2);
end
controlCount = 2 * segmentCount + 1;
isEarliestArrival = options.GoalTimeMode == "earliestArrival";
startTime_s = initialState.time_s;
latestFinalTime_s = goalState.time_s;
minimumDuration_s = durationLowerBound(initialState, goalState, limits, latestFinalTime_s);
isTimedSeed = any(seed.Source == ["directWait", "timeExpandedVisibilityGraph"]);
minimumFinalTime_s = startTime_s + minimumDuration_s;
if isEarliestArrival && isfield(goalState, "targetTime_s") && ~isempty(goalState.targetTime_s)
    minimumFinalTime_s = max( ...
        minimumFinalTime_s, goalState.targetTime_s(1));
end
candidate = emptyCandidate(seed, segmentCount);
if maximumSolverTime_s <= 0
    candidate.Message = "HS3 reached its solver time limit before setup.";
    candidate.TerminationReason = "solverTimeLimit";
    candidate.SolverDiagnostics.ElapsedTime_s = toc(solverTimer);
    return;
end
if minimumFinalTime_s > latestFinalTime_s + options.ConstraintTolerance
    candidate.Message = "The goal time is below a physical duration bound.";
    candidate.TerminationReason = "timeWindowInfeasible";
    candidate.SolverDiagnostics.ElapsedTime_s = toc(solverTimer);
    return;
end
if isEarliestArrival && isTimedSeed
    finalTimeGuess_s = min(latestFinalTime_s, max( ...
        minimumFinalTime_s, startTime_s + seed.EstimatedDuration_s));
elseif isEarliestArrival
    seedDuration_s = max(minimumDuration_s, seed.EstimatedDuration_s);
    finalTimeGuess_s = min(latestFinalTime_s, ...
        startTime_s + max(1.05 * minimumDuration_s, seedDuration_s));
else
    finalTimeGuess_s = latestFinalTime_s;
end
controlTau = linspace(0, 1, controlCount).';
[initialJerk_deg_s3, initialJerkLimitRatio] = initialJerkGuess( ...
    initialState, goalState, limits, seed, finalTimeGuess_s, ...
    segmentCount, controlTau);
if isEarliestArrival && ~isTimedSeed && initialJerkLimitRatio > 1
    durationScale = initialJerkLimitRatio^(1 / 3);
    durationSafetyFactor = 1.05;
    if isfield(seed, "UsesReducedGeometry") && ...
            seed.UsesReducedGeometry
        % A seed that actually uses reduced geometry can contain sharper
        % turns. An unused public clustering option must not change timing.
        durationSafetyFactor = 1.5;
    end
    scaledDuration_s = ...
        (finalTimeGuess_s - startTime_s) * durationScale * ...
        durationSafetyFactor;
    finalTimeGuess_s = min(latestFinalTime_s, startTime_s + scaledDuration_s);
    [initialJerk_deg_s3, ~] = initialJerkGuess( ...
        initialState, goalState, limits, seed, finalTimeGuess_s, ...
        segmentCount, controlTau);
end
% Detailed boundaries need more checks; independent validation remains final.
corridorCheckCount = corridorChecksPerSegment( ...
    obstacles, startTime_s, finalTimeGuess_s, segmentCount);
corridorTau = linspace(0, 1, corridorCheckCount * segmentCount + 1).';
eventTau = (vertcat(obstacles.time_s) - startTime_s) / ...
    (finalTimeGuess_s - startTime_s);
eventTau = eventTau(eventTau > 0 & eventTau < 1);
corridorTau = unique([corridorTau; eventTau]);
corridor = buildCorridor( ...
    obstacles, seed, startTime_s, finalTimeGuess_s, corridorTau, ...
    options.CollisionClearanceTolerance_deg, ...
    ~isEarliestArrival, limits.maxVelocity_deg_s);
seedCorridor = azElInternal.buildSeedCorridor(seed, segmentCount);
if toc(solverTimer) >= maximumSolverTime_s
    candidate.Message = "HS3 reached its solver time limit during setup.";
    candidate.TerminationReason = "solverTimeLimit";
    candidate.Corridor = corridor;
    candidate.SeedCorridor = seedCorridor;
    candidate.SolverDiagnostics.ElapsedTime_s = toc(solverTimer);
    return;
end
decision0 = initialJerk_deg_s3(:);
jerkScale_deg_s3 = repmat(limits.maxJerk_deg_s3, controlCount, 1);
jerkScale_deg_s3 = jerkScale_deg_s3(:);
lowerBound = -jerkScale_deg_s3;
upperBound = jerkScale_deg_s3;
typicalDecision = max(jerkScale_deg_s3, 1e-3);
if isEarliestArrival
    decision0(end + 1, 1) = finalTimeGuess_s;
    lowerBound(end + 1, 1) = minimumFinalTime_s;
    upperBound(end + 1, 1) = latestFinalTime_s;
    typicalDecision(end + 1, 1) = max([1, ...
        abs(minimumFinalTime_s), abs(latestFinalTime_s)]);
end
%% Section 2: Minimize Arrival Time Or Fixed-Time Jerk
solverOptions = optimoptions("fmincon", ...
    "Algorithm", "interior-point", ...
    "Display", "none", ...
    "MaxIterations", options.MaximumNlpIterations, ...
    "MaxFunctionEvaluations", options.MaximumNlpFunctionEvaluations, ...
    "ConstraintTolerance", options.ConstraintTolerance, ...
    "OptimalityTolerance", options.OptimalityTolerance, ...
    "StepTolerance", options.StepTolerance, ...
    "ScaleProblem", true, ...
    "TypicalX", typicalDecision, ...
    "OutputFcn", @(decision, solverValues, state) ...
    hs3Progress(decision, solverValues, state, solverTimer, ...
    maximumSolverTime_s, options.Verbose, seed.Index));
constraintFunction = @(decision) trajectoryConstraints( ...
    decision, isEarliestArrival, latestFinalTime_s, segmentCount, ...
    initialState, goalState, limits, options, obstacles, corridor, ...
    seedCorridor);
if isEarliestArrival
    stageOneObjective = @(decision) decision(end);
else
    stageOneObjective = @(decision) integratedSquaredJerk( ...
        decision, false, latestFinalTime_s, segmentCount, startTime_s);
end
try
    [stageOneDecision, stageOneObjectiveValue, stageOneExitFlag, ...
        stageOneOutput] = fmincon( ...
        stageOneObjective, decision0, [], [], [], [], ...
        lowerBound, upperBound, constraintFunction, solverOptions);
catch exception
    candidate.Message = "HS3 solve failed: " + string(exception.message);
    candidate.TerminationReason = "solverError";
    candidate.SolverDiagnostics.Identifier = ...
        string(exception.identifier);
    candidate.SolverDiagnostics.ElapsedTime_s = toc(solverTimer);
    return;
end
%% Section 3: Apply The Lexicographic Jerk Tie-Break
selectedDecision = stageOneDecision;
stageTwoExitFlag = NaN;
stageTwoOutput = struct();
stageTwoObjectiveValue = NaN;
stageTwoErrorIdentifier = "";
stageTwoErrorMessage = "";
if isEarliestArrival && ...
        toc(solverTimer) < maximumSolverTime_s
    stageTwoUpperBound = upperBound;
    stageTwoUpperBound(end) = min( ...
        latestFinalTime_s, stageOneDecision(end) + ...
        options.ArrivalTimeTolerance_s);
    stageTwoObjective = @(decision) integratedSquaredJerk( ...
        decision, true, latestFinalTime_s, segmentCount, startTime_s);
    try
        [trialDecision, stageTwoObjectiveValue, stageTwoExitFlag, ...
            stageTwoOutput] = fmincon( ...
            stageTwoObjective, stageOneDecision, [], [], [], [], ...
            lowerBound, stageTwoUpperBound, constraintFunction, ...
            solverOptions);
        trialViolation = maximumConstraintViolation( ...
            trialDecision, constraintFunction);
        stageOneViolation = maximumConstraintViolation( ...
            stageOneDecision, constraintFunction);
        trialJerkCost = integratedSquaredJerk( ...
            trialDecision, true, latestFinalTime_s, ...
            segmentCount, startTime_s);
        stageOneJerkCost = integratedSquaredJerk( ...
            stageOneDecision, true, latestFinalTime_s, ...
            segmentCount, startTime_s);
        jerkCostTolerance = max(1e-12, ...
            options.OptimalityTolerance * max(1, stageOneJerkCost));
        if trialViolation <= max(options.ConstraintTolerance, ...
                stageOneViolation) && ...
                trialJerkCost <= stageOneJerkCost + jerkCostTolerance
            selectedDecision = trialDecision;
        end
    catch exception
        % Stage one remains a valid candidate when the optional tie-break
        % stage fails. The diagnostic preserves the error without changing
        % an expected planning outcome into an uncaught exception.
        stageTwoErrorIdentifier = string(exception.identifier);
        stageTwoErrorMessage = string(exception.message);
    end
end
%% Section 4: Reconstruct The Candidate
[jerk_deg_s3, finalTime_s] = unpackDecision( ...
    selectedDecision, isEarliestArrival, latestFinalTime_s, controlCount);
polynomial = reconstructPolynomial( ...
    jerk_deg_s3, initialState, finalTime_s, segmentCount);
[sampleTime_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, sampledJerk_deg_s3] = ...
    samplePolynomial(polynomial, options.SampleTime_s);
[finalInequality, finalEquality] = constraintFunction(selectedDecision);
maximumInequalityViolation = max([0; finalInequality(:)]);
maximumEqualityViolation = max([0; abs(finalEquality(:))]);
maximumViolation = max( ...
    maximumInequalityViolation, maximumEqualityViolation);
optimizerFeasible = maximumViolation <= ...
    max(10 * options.ConstraintTolerance, 1e-7);
timeLimitReached = toc(solverTimer) >= maximumSolverTime_s;
if optimizerFeasible
    message = "HS3 returned a constraint-feasible local solution.";
    terminationReason = "optimizerFeasible";
elseif timeLimitReached
    message = "HS3 reached its solver time limit before feasibility.";
    terminationReason = "solverTimeLimit";
else
    message = "HS3 did not satisfy all optimization constraints.";
    terminationReason = "optimizerInfeasible";
end
candidate = struct( ...
    "OptimizerFeasible", optimizerFeasible, ...
    "Message", message, ...
    "TerminationReason", terminationReason, ...
    "SeedIndex", seed.Index, ...
    "SeedSource", seed.Source, ...
    "FinalTime_s", finalTime_s, ...
    "MotionDuration_s", finalTime_s - startTime_s, ...
    "IntegratedSquaredJerk_deg2_s5", integratedSquaredJerk( ...
    selectedDecision, isEarliestArrival, latestFinalTime_s, ...
    segmentCount, startTime_s), ...
    "MaximumConstraintViolation", maximumViolation, ...
    "time_s", sampleTime_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2, ...
    "jerk_deg_s3", sampledJerk_deg_s3, ...
    "Polynomial", polynomial, ...
    "ControlTau", controlTau, ...
    "ControlJerk_deg_s3", jerk_deg_s3, ...
    "Corridor", corridor, ...
    "SeedCorridorBoundary_deg", seed.CorridorBoundary_deg, ...
    "SeedCorridor", seedCorridor, ...
    "SolverDiagnostics", struct( ...
    "Identifier", "", ...
    "StageOneExitFlag", stageOneExitFlag, ...
    "StageTwoExitFlag", stageTwoExitFlag, ...
    "StageOneObjective", stageOneObjectiveValue, ...
    "StageTwoObjective", stageTwoObjectiveValue, ...
    "StageOneOutput", stageOneOutput, ...
    "StageTwoOutput", stageTwoOutput, ...
    "StageTwoErrorIdentifier", stageTwoErrorIdentifier, ...
    "StageTwoErrorMessage", stageTwoErrorMessage, ...
    "MaximumInequalityViolation", maximumInequalityViolation, ...
    "MaximumEqualityViolation", maximumEqualityViolation, ...
    "ElapsedTime_s", toc(solverTimer)));
end
%% Section 5: Local Functions
function stop = hs3Progress(~, solverValues, state, solverTimer, ...
        maximumTime_s, verbose, seedIndex)
% PURPOSE
%   - Stop optional solver work and report deterministic progress intervals.
stop = toc(solverTimer) >= maximumTime_s;
if ~verbose
    return;
end
iteration = outputValue(solverValues, "iteration");
if state == "init" || state == "done" || ...
        (state == "iter" && mod(iteration, 10) == 0)
    fprintf("[AzEl][HS3][seed %d] state=%s, iteration=%g, " + ...
        "evaluations=%g, objective=%.6g, violation=%.3g.\n", ...
        seedIndex, state, iteration, ...
        outputValue(solverValues, "funccount"), ...
        outputValue(solverValues, "fval"), ...
        outputValue(solverValues, "constrviolation"));
end
end
function value = outputValue(output, fieldName)
% PURPOSE
%   - Read one optional fmincon output value for stable verbose messages.
if isstruct(output) && isfield(output, fieldName)
    value = output.(fieldName);
else
    value = NaN;
end
end
function checkCount = corridorChecksPerSegment( ...
        obstacles, startTime_s, finalTime_s, segmentCount)
% PURPOSE
%   - Scale density with boundary detail and obstacle-history time spacing.
maximumVertexCount = 0;
minimumInterval_s = Inf;
for obstacleIndex = 1:numel(obstacles)
    obstacle = obstacles(obstacleIndex);
    if numel(obstacle.time_s) > 1
        minimumInterval_s = min( ...
            minimumInterval_s, min(diff(obstacle.time_s)));
    end
    for sampleIndex = 1:numel(obstacle.az_deg)
        finiteVertexCount = nnz(isfinite(obstacle.az_deg{sampleIndex}) & ...
            isfinite(obstacle.el_deg{sampleIndex}));
        maximumVertexCount = max(maximumVertexCount, finiteVertexCount);
    end
end
boundaryCheckCount = ceil(maximumVertexCount / 5);
motionCheckCount = 8;
if isfinite(minimumInterval_s) && minimumInterval_s > 0
    samplesPerObstacleInterval = 4;
    duration_s = finalTime_s - startTime_s;
    motionCheckCount = ceil(samplesPerObstacleInterval * duration_s / ...
        (segmentCount * minimumInterval_s));
end
maximumChecksPerSegment = 16;
checkCount = min(maximumChecksPerSegment, ...
    max([8, boundaryCheckCount, motionCheckCount]));
end
function [jerkGuess_deg_s3, jerkLimitRatio] = initialJerkGuess( ...
        initialState, goalState, limits, seed, finalTime_s, segmentCount, controlTau)
% PURPOSE
%   - Fit a bounded jerk-chain initialization to the supplied topology seed.
controlCount = numel(controlTau);
desiredPosition_deg = interp1(seed.tau, seed.position_deg, controlTau, "linear");
evaluationTime_s = initialState.time_s + controlTau * (finalTime_s - initialState.time_s);
zeroJerk_deg_s3 = zeros(controlCount, 2);
basePolynomial = reconstructPolynomial(zeroJerk_deg_s3, initialState, finalTime_s, segmentCount);
[~, basePosition_deg, baseVelocity_deg_s, baseAcceleration_deg_s2] = ...
    azElInternal.evaluateAzElPolynomial( ...
    basePolynomial, evaluationTime_s);
desiredPosition_deg(end, :) = azElInternal.goalPositionAtTime(goalState, finalTime_s);
routeTangent_deg = desiredPosition_deg([2:end end], :) - desiredPosition_deg([1 1:end-1], :);
routeDirection = routeTangent_deg ./ max(vecnorm(routeTangent_deg, 2, 2), eps);
routeSpeed_deg_s = min(limits.maxVelocity_deg_s ./ max(abs(routeDirection), eps), [], 2);
desiredVelocity_deg_s = routeDirection .* routeSpeed_deg_s;
desiredVelocity_deg_s([1 end], :) = [initialState.velocity_deg_s; goalState.velocity_deg_s];
velocityFitWeight_s = (finalTime_s - initialState.time_s) / segmentCount;
positionMap = zeros(controlCount - 1, controlCount);
velocityMap = zeros(controlCount - 2, controlCount);
terminalVelocityMap = zeros(1, controlCount);
terminalAccelerationMap = zeros(1, controlCount);
for controlIndex = 1:controlCount
    basisJerk_deg_s3 = zeros(controlCount, 2);
    basisJerk_deg_s3(controlIndex, 1) = 1;
    basisPolynomial = reconstructPolynomial( ...
        basisJerk_deg_s3, initialState, finalTime_s, segmentCount);
    [~, basisPosition_deg, basisVelocity_deg_s, basisAcceleration_deg_s2] = ...
        azElInternal.evaluateAzElPolynomial(basisPolynomial, evaluationTime_s);
    positionMap(:, controlIndex) = basisPosition_deg(2:end, 1) - basePosition_deg(2:end, 1);
    velocityMap(:, controlIndex) = ...
        basisVelocity_deg_s(2:end-1, 1) - baseVelocity_deg_s(2:end-1, 1);
    terminalVelocityMap(controlIndex) = basisVelocity_deg_s(end, 1) - baseVelocity_deg_s(end, 1);
    terminalAccelerationMap(controlIndex) = basisAcceleration_deg_s2(end, 1) - ...
        baseAcceleration_deg_s2(end, 1);
end
fitMatrix = [positionMap; velocityFitWeight_s * velocityMap; 5 * terminalVelocityMap; ...
    5 * terminalAccelerationMap];
fitOffset = [desiredPosition_deg(2:end, :) - basePosition_deg(2:end, :); ...
    velocityFitWeight_s * (desiredVelocity_deg_s(2:end-1, :) - ...
    baseVelocity_deg_s(2:end-1, :)); ...
    5 * (goalState.velocity_deg_s - baseVelocity_deg_s(end, :)); ...
    5 * (goalState.acceleration_deg_s2 - baseAcceleration_deg_s2(end, :))];
regularization = 1e-8 * eye(controlCount);
jerkGuess_deg_s3 = (fitMatrix.' * fitMatrix + regularization) \ ...
    (fitMatrix.' * fitOffset);
jerkLimitRatio = max(abs(jerkGuess_deg_s3) ./ limits.maxJerk_deg_s3, [], "all");
jerkGuess_deg_s3 = min(limits.maxJerk_deg_s3, max(-limits.maxJerk_deg_s3, jerkGuess_deg_s3));
end
function [inequality, equality] = trajectoryConstraints(decision, ...
        isEarliestArrival, fixedFinalTime_s, segmentCount, ...
        initialState, goalState, limits, options, obstacles, corridor, ...
        seedCorridor)
% PURPOSE
%   - Enforce endpoint, continuous kinematic, and frozen-corridor constraints.
controlCount = 2 * segmentCount + 1;
[jerk_deg_s3, finalTime_s] = unpackDecision( ...
    decision, isEarliestArrival, fixedFinalTime_s, controlCount);
polynomial = reconstructPolynomial( ...
    jerk_deg_s3, initialState, finalTime_s, segmentCount);
inequality = continuousBoundConstraints( ...
    polynomial, limits, options);
inequality = [inequality; ...
    azElInternal.seedCorridorInequality(polynomial, seedCorridor)];
corridorTau = unique([corridor.Tau].', "stable");
controlTime_s = initialState.time_s + corridorTau * ...
    (finalTime_s - initialState.time_s);
[~, controlPosition_deg] = azElInternal.evaluateAzElPolynomial( ...
    polynomial, controlTime_s);
corridorInequality = corridorConstraints( ...
    corridor, obstacles, controlTime_s, controlPosition_deg);
inequality = [inequality; corridorInequality];
terminalPosition_deg = polynomial.TerminalState.position_deg;
terminalVelocity_deg_s = polynomial.TerminalState.velocity_deg_s;
terminalAcceleration_deg_s2 = ...
    polynomial.TerminalState.acceleration_deg_s2;
goalPosition_deg = azElInternal.goalPositionAtTime(goalState, finalTime_s);
equality = [ ...
    terminalPosition_deg - goalPosition_deg, ...
    terminalVelocity_deg_s - goalState.velocity_deg_s, ...
    terminalAcceleration_deg_s2 - goalState.acceleration_deg_s2].';
end
function inequality = continuousBoundConstraints(polynomial, limits, options)
% PURPOSE
%   - Use Bernstein convex-hull bounds over every complete HS3 segment.
inequality = zeros(0, 1);
positionLower_deg = [limits.azimuthInterval_deg(1), ...
    limits.elevationInterval_deg(1)];
positionUpper_deg = [limits.azimuthInterval_deg(2), ...
    limits.elevationInterval_deg(2)];
for segmentIndex = 1:polynomial.SegmentCount
    for axisIndex = 1:2
        if ~(axisIndex == 1 && options.AllowAzimuthWrapping)
            positionPower = reshape( ...
                polynomial.positionPower_deg(segmentIndex, axisIndex, :), ...
                [], 1);
            inequality = appendBounds(inequality, positionPower, ...
                positionLower_deg(axisIndex), ...
                positionUpper_deg(axisIndex));
        end
        velocityPower = reshape( ...
            polynomial.velocityPower_deg_s(segmentIndex, axisIndex, :), ...
            [], 1);
        accelerationPower = reshape( ...
            polynomial.accelerationPower_deg_s2( ...
            segmentIndex, axisIndex, :), [], 1);
        jerkPower = reshape( ...
            polynomial.jerkPower_deg_s3(segmentIndex, axisIndex, :), ...
            [], 1);
        inequality = appendBounds(inequality, velocityPower, ...
            -limits.maxVelocity_deg_s(axisIndex), ...
            limits.maxVelocity_deg_s(axisIndex));
        inequality = appendBounds(inequality, accelerationPower, ...
            -limits.maxAcceleration_deg_s2(axisIndex), ...
            limits.maxAcceleration_deg_s2(axisIndex));
        inequality = appendBounds(inequality, jerkPower, ...
            -limits.maxJerk_deg_s3(axisIndex), ...
            limits.maxJerk_deg_s3(axisIndex));
    end
end
end
function inequality = appendBounds(inequality, powerCoefficient, ...
        lowerBound, upperBound)
% PURPOSE
%   - Append continuous polynomial limits through Bernstein coefficients.
bernsteinCoefficient = azElInternal.powerToBernstein(powerCoefficient);
inequality = [inequality; ...
    bernsteinCoefficient - upperBound; ...
    lowerBound - bernsteinCoefficient];
end
function corridor = buildCorridor( ...
        obstacles, seed, startTime_s, finalTime_s, controlTau, ...
        clearanceTolerance_deg, geometryIsFixed, maxVelocity_deg_s)
% PURPOSE
%   - Freeze obstacle edges at dense optimization constraint points.
template = struct( ...
    "ControlIndex", 0, "ObstacleIndex", 0, "EdgeIndex", 0, ...
    "Tau", 0, ...
    "OutwardSign", 1, "UseSupport", false, ...
    "SupportNormal", [0 0], "Clearance_deg", 0, ...
    "GeometryIsFixed", false, "FixedNormal", [0 0], ...
    "FixedBoundaryOffset_deg", 0);
corridor = repmat(template, 0, 1);
if azElInternal.seedEnvelopeContainsObstacles( ...
        seed.CorridorBoundary_deg, obstacles, clearanceTolerance_deg)
    return;
end
lockedAssociation = repmat(template, numel(obstacles), 1);
hasLockedAssociation = false(numel(obstacles), 1);
seedPosition_deg = interp1(seed.tau, seed.position_deg, ...
    controlTau, "linear");
controlTime_s = startTime_s + controlTau * (finalTime_s - startTime_s);
vehicleSpeedBound_deg_s = norm(maxVelocity_deg_s);
for controlIndex = 1:numel(controlTau)
    for obstacleIndex = 1:numel(obstacles)
        [shape, geometry] = azElInternal.obstacleShapeAtTime( ...
            obstacles(obstacleIndex), controlTime_s(controlIndex));
        if ~geometry.Active
            hasLockedAssociation(obstacleIndex) = false;
            continue;
        end
        [edgeStart_deg, edgeEnd_deg] = geometryEdges(geometry);
        finiteVertices = isfinite(geometry.azimuth_deg) & ...
            isfinite(geometry.elevation_deg);
        vertices_deg = [geometry.azimuth_deg(finiteVertices), ...
            geometry.elevation_deg(finiteVertices)];
        hullIndex = convhull(vertices_deg(:, 1), vertices_deg(:, 2));
        hullShape = polyshape( ...
            vertices_deg(hullIndex(1:end - 1), :), "Simplify", false);
        geometryIsConvex = shape.NumRegions == 1 && ...
            abs(area(hullShape) - area(shape)) <= ...
            1e-9 * max(1, area(hullShape));
        [edgeIndex, nearestPoint_deg] = nearestEdge( ...
            seedPosition_deg(controlIndex, :), ...
            edgeStart_deg, edgeEnd_deg);
        edgeDelta_deg = edgeEnd_deg(edgeIndex, :) - ...
            edgeStart_deg(edgeIndex, :);
        leftNormal = [-edgeDelta_deg(2), edgeDelta_deg(1)];
        leftNormal = leftNormal / norm(leftNormal);
        probeScale_deg = max(1e-7, 1e-7 * norm(edgeDelta_deg));
        probe_deg = nearestPoint_deg + probeScale_deg * leftNormal;
        if isinterior(shape, probe_deg(1), probe_deg(2))
            outwardSign = -1;
        else
            outwardSign = 1;
        end
        association = template;
        association.ControlIndex = controlIndex;
        association.ObstacleIndex = obstacleIndex;
        association.EdgeIndex = edgeIndex;
        association.Tau = controlTau(controlIndex);
        association.OutwardSign = outwardSign;
        % A small separation prevents tolerance-level boundary contact.
        % Adaptive validation certifies motion between constraint points.
        association.Clearance_deg = max(1e-4, clearanceTolerance_deg);
        stationarySpeedTolerance_deg_s = 1e-12;
        geometryIsStationary = geometry.VertexSpeedBound_deg_s <= ...
            stationarySpeedTolerance_deg_s;
        if (~geometry.TopologyIsInterpolated || geometryIsStationary) && ...
                geometryIsConvex
            outwardNormal = outwardSign * leftNormal;
            association.UseSupport = true;
            association.SupportNormal = outwardNormal;
        end
        if geometryIsFixed || geometryIsStationary
            if association.UseSupport
                outwardNormal = association.SupportNormal;
                boundaryOffset_deg = max(vertices_deg * outwardNormal.');
            else
                outwardNormal = outwardSign * leftNormal;
                boundaryOffset_deg = edgeStart_deg(edgeIndex, :) * ...
                    outwardNormal.';
            end
            association.GeometryIsFixed = true;
            association.FixedNormal = outwardNormal;
            association.FixedBoundaryOffset_deg = boundaryOffset_deg;
        end
        usedLockedAssociation = false;
        geometryRequiresLock = geometry.VertexSpeedBound_deg_s > ...
            vehicleSpeedBound_deg_s;
        if geometryRequiresLock && hasLockedAssociation(obstacleIndex)
            [trialAssociation, lockIsSatisfied] = moveAssociation( ...
                lockedAssociation(obstacleIndex), geometry, ...
                edgeStart_deg, edgeEnd_deg, controlIndex, ...
                controlTau(controlIndex), geometryIsFixed, ...
                seedPosition_deg(controlIndex, :));
            if lockIsSatisfied
                association = trialAssociation;
                usedLockedAssociation = true;
            end
        end
        if geometryRequiresLock && ~usedLockedAssociation
            [association, ~] = moveAssociation( ...
                association, geometry, edgeStart_deg, edgeEnd_deg, ...
                controlIndex, controlTau(controlIndex), ...
                geometryIsFixed, seedPosition_deg(controlIndex, :));
        end
        if geometryRequiresLock
            lockedAssociation(obstacleIndex) = association;
            hasLockedAssociation(obstacleIndex) = true;
        else
            hasLockedAssociation(obstacleIndex) = false;
        end
        corridor(end + 1, 1) = association; %#ok<AGROW>
    end
end
end
function [association, isSatisfied] = moveAssociation( ...
        association, geometry, edgeStart_deg, edgeEnd_deg, ...
        controlIndex, controlTau, geometryIsFixed, point_deg)
% PURPOSE
%   - Keep a seed half-space until the seed no longer satisfies it.
finiteVertices = isfinite(geometry.azimuth_deg) & ...
    isfinite(geometry.elevation_deg);
vertices_deg = [geometry.azimuth_deg(finiteVertices), ...
    geometry.elevation_deg(finiteVertices)];
isSatisfied = false;
if association.UseSupport
    outwardNormal = association.SupportNormal;
    boundaryOffset_deg = max(vertices_deg * outwardNormal.');
elseif association.EdgeIndex <= size(edgeStart_deg, 1)
    edgeDelta_deg = edgeEnd_deg(association.EdgeIndex, :) - ...
        edgeStart_deg(association.EdgeIndex, :);
    if norm(edgeDelta_deg) <= eps
        return;
    end
    leftNormal = [-edgeDelta_deg(2), edgeDelta_deg(1)] / ...
        norm(edgeDelta_deg);
    outwardNormal = association.OutwardSign * leftNormal;
    boundaryOffset_deg = edgeStart_deg(association.EdgeIndex, :) * ...
        outwardNormal.';
else
    return;
end
pointProjection_deg = point_deg * outwardNormal.';
seedClearance_deg = pointProjection_deg - boundaryOffset_deg;
isSatisfied = seedClearance_deg >= association.Clearance_deg;
if ~isSatisfied
    return;
end
seedClearanceRetention = 0.25;
association.Clearance_deg = max(association.Clearance_deg, ...
    seedClearanceRetention * seedClearance_deg);
association.ControlIndex = controlIndex;
association.Tau = controlTau;
association.GeometryIsFixed = geometryIsFixed;
if geometryIsFixed
    association.FixedNormal = outwardNormal;
    association.FixedBoundaryOffset_deg = boundaryOffset_deg;
end
end
function inequality = corridorConstraints( ...
        corridor, obstacles, controlTime_s, controlPosition_deg)
% PURPOSE
%   - Evaluate frozen edge associations on geometry at the decision time.
inequality = zeros(numel(corridor), 1);
for associationIndex = 1:numel(corridor)
    association = corridor(associationIndex);
    controlIndex = association.ControlIndex;
    if association.GeometryIsFixed
        outwardNormal = association.FixedNormal;
        boundaryOffset_deg = association.FixedBoundaryOffset_deg;
        pointProjection_deg = ...
            controlPosition_deg(controlIndex, :) * outwardNormal.';
        inequality(associationIndex) = boundaryOffset_deg + ...
            association.Clearance_deg - pointProjection_deg;
        continue;
    end
    [~, geometry] = azElInternal.obstacleShapeAtTime( ...
        obstacles(association.ObstacleIndex), ...
        controlTime_s(controlIndex), true);
    if ~geometry.Active
        inequality(associationIndex) = -1;
        continue;
    end
    finiteVertices = isfinite(geometry.azimuth_deg) & ...
        isfinite(geometry.elevation_deg);
    vertices_deg = [geometry.azimuth_deg(finiteVertices), ...
        geometry.elevation_deg(finiteVertices)];
    if association.UseSupport
        outwardNormal = association.SupportNormal;
        boundaryOffset_deg = max(vertices_deg * outwardNormal.');
    else
        [edgeStart_deg, edgeEnd_deg] = geometryEdges(geometry);
        if association.EdgeIndex > size(edgeStart_deg, 1)
            inequality(associationIndex) = 1e3;
            continue;
        end
        edgeDelta_deg = ...
            edgeEnd_deg(association.EdgeIndex, :) - ...
            edgeStart_deg(association.EdgeIndex, :);
        if norm(edgeDelta_deg) <= eps
            inequality(associationIndex) = 1e3;
            continue;
        end
        leftNormal = [-edgeDelta_deg(2), edgeDelta_deg(1)] / ...
            norm(edgeDelta_deg);
        outwardNormal = association.OutwardSign * leftNormal;
        boundaryOffset_deg = ...
            edgeStart_deg(association.EdgeIndex, :) * ...
            outwardNormal.';
    end
    pointProjection_deg = ...
        controlPosition_deg(controlIndex, :) * outwardNormal.';
    inequality(associationIndex) = boundaryOffset_deg + ...
        association.Clearance_deg - pointProjection_deg;
end
end
function [edgeStart_deg, edgeEnd_deg] = geometryEdges(geometry)
% PURPOSE
%   - Convert a NaN-separated canonical boundary to deterministic edges.
position_deg = [geometry.azimuth_deg, geometry.elevation_deg];
finiteRows = all(isfinite(position_deg), 2);
regionChanges = diff([false; finiteRows; false]);
regionStarts = find(regionChanges == 1);
regionStops = find(regionChanges == -1) - 1;
edgeStart_deg = zeros(0, 2);
edgeEnd_deg = zeros(0, 2);
for regionIndex = 1:numel(regionStarts)
    vertices_deg = position_deg( ...
        regionStarts(regionIndex):regionStops(regionIndex), :);
    if size(vertices_deg, 1) < 2
        continue;
    end
    if all(vertices_deg(1, :) == vertices_deg(end, :))
        vertices_deg(end, :) = [];
    end
    edgeStart_deg = [edgeStart_deg; vertices_deg]; %#ok<AGROW>
    edgeEnd_deg = [edgeEnd_deg; ...
        vertices_deg([2:end 1], :)]; %#ok<AGROW>
end
end
function [edgeIndex, nearestPoint_deg] = nearestEdge( ...
        point_deg, edgeStart_deg, edgeEnd_deg)
% PURPOSE
%   - Select the closest edge and boundary point for a frozen association.
edgeDelta_deg = edgeEnd_deg - edgeStart_deg;
edgeLengthSquared_deg2 = sum(edgeDelta_deg.^2, 2);
projection = zeros(size(edgeLengthSquared_deg2));
validEdges = edgeLengthSquared_deg2 > 0;
projection(validEdges) = sum( ...
    (point_deg - edgeStart_deg(validEdges, :)) .* ...
    edgeDelta_deg(validEdges, :), 2) ./ ...
    edgeLengthSquared_deg2(validEdges);
projection = min(1, max(0, projection));
projectedPoint_deg = edgeStart_deg + projection .* edgeDelta_deg;
[~, edgeIndex] = min(sum((point_deg - projectedPoint_deg).^2, 2));
nearestPoint_deg = projectedPoint_deg(edgeIndex, :);
end
function polynomial = reconstructPolynomial( ...
        jerk_deg_s3, initialState, finalTime_s, segmentCount)
% PURPOSE
%   - Integrate one quadratic-jerk HS3 chain exactly on every segment.
%   - Follow the separated higher-order construction cited in citation.md.
duration_s = finalTime_s - initialState.time_s;
segmentDuration_s = duration_s / segmentCount;
positionPower_deg = zeros(segmentCount, 2, 6);
velocityPower_deg_s = zeros(segmentCount, 2, 5);
accelerationPower_deg_s2 = zeros(segmentCount, 2, 4);
jerkPower_deg_s3 = zeros(segmentCount, 2, 3);
position_deg = initialState.position_deg;
velocity_deg_s = initialState.velocity_deg_s;
acceleration_deg_s2 = initialState.acceleration_deg_s2;
for segmentIndex = 1:segmentCount
    startControlIndex = 2 * segmentIndex - 1;
    startJerk_deg_s3 = jerk_deg_s3(startControlIndex, :);
    midpointJerk_deg_s3 = jerk_deg_s3(startControlIndex + 1, :);
    endJerk_deg_s3 = jerk_deg_s3(startControlIndex + 2, :);
    jerkLinear_deg_s3 = -3 * startJerk_deg_s3 + ...
        4 * midpointJerk_deg_s3 - endJerk_deg_s3;
    jerkQuadratic_deg_s3 = 2 * startJerk_deg_s3 - ...
        4 * midpointJerk_deg_s3 + 2 * endJerk_deg_s3;
    jerkPower = [startJerk_deg_s3; jerkLinear_deg_s3; ...
        jerkQuadratic_deg_s3].';
    accelerationPower = [acceleration_deg_s2; ...
        segmentDuration_s * startJerk_deg_s3; ...
        segmentDuration_s * jerkLinear_deg_s3 / 2; ...
        segmentDuration_s * jerkQuadratic_deg_s3 / 3].';
    velocityPower = [velocity_deg_s; ...
        segmentDuration_s * acceleration_deg_s2; ...
        segmentDuration_s^2 * startJerk_deg_s3 / 2; ...
        segmentDuration_s^2 * jerkLinear_deg_s3 / 6; ...
        segmentDuration_s^2 * jerkQuadratic_deg_s3 / 12].';
    positionPower = [position_deg; ...
        segmentDuration_s * velocity_deg_s; ...
        segmentDuration_s^2 * acceleration_deg_s2 / 2; ...
        segmentDuration_s^3 * startJerk_deg_s3 / 6; ...
        segmentDuration_s^3 * jerkLinear_deg_s3 / 24; ...
        segmentDuration_s^3 * jerkQuadratic_deg_s3 / 60].';
    positionPower_deg(segmentIndex, :, :) = positionPower;
    velocityPower_deg_s(segmentIndex, :, :) = velocityPower;
    accelerationPower_deg_s2(segmentIndex, :, :) = accelerationPower;
    jerkPower_deg_s3(segmentIndex, :, :) = jerkPower;
    position_deg = sum(positionPower, 2).';
    velocity_deg_s = sum(velocityPower, 2).';
    acceleration_deg_s2 = sum(accelerationPower, 2).';
end
segmentStartTime_s = initialState.time_s + ...
    (0:segmentCount - 1).' * segmentDuration_s;
polynomial = struct( ...
    "SegmentCount", segmentCount, ...
    "SegmentStartTime_s", segmentStartTime_s, ...
    "SegmentDuration_s", segmentDuration_s, ...
    "FinalTime_s", finalTime_s, ...
    "positionPower_deg", positionPower_deg, ...
    "velocityPower_deg_s", velocityPower_deg_s, ...
    "accelerationPower_deg_s2", accelerationPower_deg_s2, ...
    "jerkPower_deg_s3", jerkPower_deg_s3, ...
    "TerminalState", struct( ...
    "position_deg", position_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2));
end
function [time_s, position_deg, velocity_deg_s, ...
        acceleration_deg_s2, jerk_deg_s3] = ...
        samplePolynomial(polynomial, sampleTime_s)
% PURPOSE
%   - Sample the exact segment polynomials without losing knot times.
startTime_s = polynomial.SegmentStartTime_s(1);
uniformTime_s = (startTime_s:sampleTime_s:polynomial.FinalTime_s).';
time_s = unique([uniformTime_s; polynomial.SegmentStartTime_s; ...
    polynomial.FinalTime_s]);
[time_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, jerk_deg_s3] = ...
    azElInternal.evaluateAzElPolynomial(polynomial, time_s);
end
function value = integratedSquaredJerk(decision, isEarliestArrival, ...
        fixedFinalTime_s, segmentCount, startTime_s)
% PURPOSE
%   - Integrate each squared quadratic jerk polynomial exactly.
controlCount = 2 * segmentCount + 1;
[jerk_deg_s3, finalTime_s] = unpackDecision( ...
    decision, isEarliestArrival, fixedFinalTime_s, controlCount);
segmentDuration_s = (finalTime_s - startTime_s) / segmentCount;
startJerk_deg_s3 = jerk_deg_s3(1:2:end - 2, :);
midpointJerk_deg_s3 = jerk_deg_s3(2:2:end - 1, :);
endJerk_deg_s3 = jerk_deg_s3(3:2:end, :);
normalizedIntegral = (4 * startJerk_deg_s3.^2 + ...
    16 * midpointJerk_deg_s3.^2 + 4 * endJerk_deg_s3.^2 + ...
    4 * startJerk_deg_s3 .* midpointJerk_deg_s3 - ...
    2 * startJerk_deg_s3 .* endJerk_deg_s3 + ...
    4 * midpointJerk_deg_s3 .* endJerk_deg_s3) / 30;
value = segmentDuration_s * sum(normalizedIntegral, "all");
end
function [jerk_deg_s3, finalTime_s] = unpackDecision( ...
        decision, isEarliestArrival, fixedFinalTime_s, controlCount)
% PURPOSE
%   - Recover jerk ordinates and final time from the compact decision vector.
jerkValueCount = 2 * controlCount;
jerk_deg_s3 = reshape(decision(1:jerkValueCount), controlCount, 2);
if isEarliestArrival
    finalTime_s = decision(end);
else
    finalTime_s = fixedFinalTime_s;
end
end
function violation = maximumConstraintViolation(decision, constraintFunction)
% PURPOSE
%   - Reduce nonlinear inequality and equality residuals to one diagnostic.
[inequality, equality] = constraintFunction(decision);
violation = max([0; inequality(:); abs(equality(:))]);
end
function duration_s = durationLowerBound( ...
        initialState, goalState, limits, latestFinalTime_s)
% PURPOSE
%   - Compute an input-driven lower bound without claiming exact optimality.
if isfield(goalState, "targetTime_s") && ...
        ~isempty(goalState.targetTime_s)
    duration_s = movingTargetDurationLowerBound( ...
        initialState, goalState, limits);
    return;
end
goalPosition_deg = azElInternal.goalPositionAtTime( ...
    goalState, latestFinalTime_s);
displacement_deg = abs(goalPosition_deg - initialState.position_deg);
velocityBound_s = displacement_deg ./ limits.maxVelocity_deg_s;
duration_s = max([1e-3, velocityBound_s]);
end
function duration_s = movingTargetDurationLowerBound( ...
        initialState, goalState, limits)
% PURPOSE
%   - Bound linear-target interception without using a future snapshot.
duration_s = 1e-3;
if goalState.InterpolationMethod ~= "linear" || ...
        initialState.time_s < goalState.targetTime_s(1) || ...
        initialState.time_s > goalState.targetTime_s(end)
    return;
end
targetStart_deg = interp1( ...
    goalState.targetTime_s, goalState.targetPosition_deg, ...
    initialState.time_s, "linear");
targetVelocity_deg_s = diff(goalState.targetPosition_deg, 1, 1) ./ diff(goalState.targetTime_s);
targetSpeedBound_deg_s = max(abs(targetVelocity_deg_s), [], 1);
initialDistance_deg = abs(targetStart_deg - initialState.position_deg);
closingSpeedBound_deg_s = limits.maxVelocity_deg_s + ...
    targetSpeedBound_deg_s;
duration_s = max([duration_s, initialDistance_deg ./ closingSpeedBound_deg_s]);
end
function candidate = emptyCandidate(seed, segmentCount)
% PURPOSE
%   - Define the same candidate schema for early solver failures.
candidate = struct( ...
    "OptimizerFeasible", false, ...
    "Message", "HS3 was not run.", ...
    "TerminationReason", "notRun", ...
    "SeedIndex", seed.Index, ...
    "SeedSource", seed.Source, ...
    "FinalTime_s", NaN, ...
    "MotionDuration_s", NaN, ...
    "IntegratedSquaredJerk_deg2_s5", Inf, ...
    "MaximumConstraintViolation", Inf, ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2), ...
    "Polynomial", struct("SegmentCount", segmentCount), ...
    "ControlTau", zeros(0, 1), ...
    "ControlJerk_deg_s3", zeros(0, 2), ...
    "Corridor", struct([]), ...
    "SeedCorridorBoundary_deg", seed.CorridorBoundary_deg, ...
    "SeedCorridor", struct([]), ...
    "SolverDiagnostics", struct( ...
    "Identifier", "", "StageOneExitFlag", NaN, "StageTwoExitFlag", NaN, ...
    "StageOneObjective", NaN, "StageTwoObjective", NaN, ...
    "StageOneOutput", struct(), "StageTwoOutput", struct(), ...
    "StageTwoErrorIdentifier", "", "StageTwoErrorMessage", "", ...
    "MaximumInequalityViolation", Inf, ...
    "MaximumEqualityViolation", Inf, "ElapsedTime_s", 0));
end
