function validation = validateAzElHs3Solution(solution, trajectory, certificate, ...
        collisionAssessment, maximumCollocationDefect, ...
        maximumNlpInequalityViolation, initialState, goalState, ~, options)
%% Section 0: Header & Readme
% SYNTAX
%   validation = azElInternal.validateAzElHs3Solution( ...
%       solution, trajectory, certificate, collisionAssessment, ...
%       maximumCollocationDefect, maximumNlpInequalityViolation, ...
%       initialState, goalState, limits, options)
%**************************************************************************
% PURPOSE
%   - Independently gate HS-3 success on all continuous requirements.
%**************************************************************************
% INPUTS
%   - solution, trajectory, certificate, collisionAssessment (scalar structs)
%       HS-3 motion and independent continuous validation evidence.
%   - maximumCollocationDefect, maximumNlpInequalityViolation (scalars)
%       Measured reduced equality and inequality residuals.
%   - initialState, goalState, limits, options (scalar structs)
%       Resolved endpoint states, physical limits, and planner controls.
%**************************************************************************
% OUTPUTS
%   - validation (scalar struct)
%       Stable pass/fail record with checks, extrema, defects, and issues.
%**************************************************************************
% UNITS
%   - Field names state position, time, and derivative units.
%**************************************************************************

%% Section 1: Evaluate Independent Requirements
tolerance = options.KinematicValidationTolerance;
bufferedChordQueryClear = ...
    collisionAssessment.BufferedChordQueryClear;
collisionSafetyProven = collisionAssessment.CollisionSafetyProven;
collisionFree = bufferedChordQueryClear && collisionSafetyProven;
timeIsStrictlyIncreasing = all(isfinite(trajectory.time_s)) && ...
    all(diff(trajectory.time_s) > 0);
initialTrajectoryState = [trajectory.position_deg(1, :), ...
    trajectory.velocity_deg_s(1, :), ...
    trajectory.acceleration_deg_s2(1, :)];
terminalTrajectoryState = [trajectory.position_deg(end, :), ...
    trajectory.velocity_deg_s(end, :), ...
    trajectory.acceleration_deg_s2(end, :)];
requestedInitialState = [initialState.position_deg, ...
    initialState.velocity_deg_s, initialState.acceleration_deg_s2];
requestedTerminalState = [goalState.position_deg, ...
    goalState.velocity_deg_s, goalState.acceleration_deg_s2];
initialStateError = abs(initialTrajectoryState - requestedInitialState);
terminalStateError = abs(terminalTrajectoryState - requestedTerminalState);
initialStateMatched = all(initialStateError <= tolerance);
terminalStateMatched = all(terminalStateError <= tolerance);
goalTimeSatisfied = solution.FinalTime_s <= ...
    goalState.time_s + options.NlpConstraintTolerance;
if options.GoalTimeMode == "fixedarrival"
    goalTimeSatisfied = abs(solution.FinalTime_s - goalState.time_s) <= ...
        options.NlpConstraintTolerance;
end
velocityWithinLimits = all( ...
    certificate.MaximumVelocityViolation_deg_s <= tolerance);
accelerationWithinLimits = all( ...
    certificate.MaximumAccelerationViolation_deg_s2 <= tolerance);
jerkWithinLimits = all( ...
    certificate.MaximumJerkViolation_deg_s3 <= tolerance);
positionWithinBounds = all( ...
    certificate.MaximumPositionViolation_deg <= tolerance);
curveSubdivisionConverged = ...
    ~isempty(trajectory.CurveSubdivisionConvergedBySegment) && ...
    all(trajectory.CurveSubdivisionConvergedBySegment);
dynamicsDefectWithinTolerance = ...
    certificate.MaximumDynamicsDefect <= ...
    options.CollocationErrorTolerance;
collocationDefectWithinTolerance = maximumCollocationDefect <= ...
    options.NlpConstraintTolerance;
nlpInequalityWithinTolerance = maximumNlpInequalityViolation <= ...
    options.NlpConstraintTolerance;
continuousPolynomialExtremaVerified = velocityWithinLimits && ...
    accelerationWithinLimits && jerkWithinLimits && positionWithinBounds;
checks = [timeIsStrictlyIncreasing, initialStateMatched, ...
    terminalStateMatched, goalTimeSatisfied, collisionFree, ...
    velocityWithinLimits, accelerationWithinLimits, jerkWithinLimits, ...
    positionWithinBounds, curveSubdivisionConverged, ...
    dynamicsDefectWithinTolerance, ...
    collocationDefectWithinTolerance, nlpInequalityWithinTolerance];
names = ["strictTime" "initialState" "terminalState" "goalTime" ...
    "collision" "velocity" "acceleration" "jerk" "workspace" ...
    "curveSubdivision" "dynamicsDefect" "collocationDefect" ...
    "nlpInequality"];
issues = names(~checks);
passed = all(checks);
message = "Direct-collocation trajectory passed independent validation.";
if ~passed
    message = "Independent validation failed: " + ...
        strjoin(issues, ", ") + ".";
end
validation = struct( ...
    "Passed", passed, ...
    "Message", message, ...
    "TimeIsStrictlyIncreasing", timeIsStrictlyIncreasing, ...
    "InitialStateMatched", initialStateMatched, ...
    "TerminalStateMatched", terminalStateMatched, ...
    "GoalTimeSatisfied", goalTimeSatisfied, ...
    "CollisionFree", collisionFree, ...
    "BufferedChordQueryClear", bufferedChordQueryClear, ...
    "CollisionSafetyProven", collisionSafetyProven, ...
    "CollisionValidationScope", ...
    "Adaptive HS-3 chords passed an intersection query and a " + ...
    "conservative timed moving-edge clearance proof. A topology-changing " + ...
    "interval uses the union of both endpoint polygons.", ...
    "CurveSubdivisionConverged", curveSubdivisionConverged, ...
    "MaximumCurveDeviationBound_deg", max( ...
    trajectory.CurveDeviationBoundBySegment_deg), ...
    "VelocityWithinLimits", velocityWithinLimits, ...
    "AccelerationWithinLimits", accelerationWithinLimits, ...
    "JerkWithinLimits", jerkWithinLimits, ...
    "PositionWithinBounds", positionWithinBounds, ...
    "ContinuousPolynomialExtremaVerified", ...
    continuousPolynomialExtremaVerified, ...
    "DynamicsDefectWithinTolerance", dynamicsDefectWithinTolerance, ...
    "CollocationDefectWithinTolerance", ...
    collocationDefectWithinTolerance, ...
    "NlpInequalityWithinTolerance", nlpInequalityWithinTolerance, ...
    "InitialStateError", initialStateError, ...
    "TerminalStateError", terminalStateError, ...
    "MaximumDynamicsDefect", certificate.MaximumDynamicsDefect, ...
    "DynamicsConsistencyScope", ...
    "Internal consistency is certified because states are integrated " + ...
    "from shared HS-3 jerk ordinates. " + ...
    "MaximumCollocationDefect is a compatibility field that includes " + ...
    "the reduced terminal-state equality residual.", ...
    "MaximumCollocationDefect", maximumCollocationDefect, ...
    "MaximumNlpInequalityViolation", ...
    maximumNlpInequalityViolation, ...
    "MaximumVelocity_deg_s", certificate.MaximumVelocity_deg_s, ...
    "MaximumAcceleration_deg_s2", ...
    certificate.MaximumAcceleration_deg_s2, ...
    "MaximumJerk_deg_s3", certificate.MaximumJerk_deg_s3, ...
    "Issues", issues);
end
