function [result, emptySeedSummary] = createEmptyResult( ...
        obstacles, initialState, goalState, limits, options, ...
        validationTemplate)
%% Section 0: Header & Readme
% SYNTAX
%   [result, emptySeedSummary] = obstacleAvoidance.planner.createEmptyResult( ...
%       obstacles, initialState, goalState, limits, options, ...
%       validationTemplate)
%**************************************************************************
% PURPOSE
%   - Define the stable obstacle-planner result and candidate-summary formats.
%**************************************************************************
% INPUTS
%   - obstacles (canonical protected obstacle struct array)
%   - initialState, goalState (normalized scalar state structs)
%   - limits, options (normalized scalar planner-input structs)
%   - validationTemplate (scalar struct)
%       Empty canonical validation record.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Empty public planner result with stable motion and diagnostics fields.
%   - emptySeedSummary (scalar struct)
%       Stable candidate-summary template with engine-specific evidence.
%**************************************************************************
% UNITS
%   - Position is degrees. Time is seconds. Derivatives use deg/s, deg/s^2,
%     and deg/s^3.
%**************************************************************************

%% Section 1: Create Planner Templates

% Create every nested record before planning begins so success, expected
% no-path results, and early failures all return the same fields. Empty
% arrays retain meaningful column counts for plotting and validation.

emptySeed = struct( ...
    "Index", 0, "Source", "", ...
    "position_deg", zeros(0, 2), "tau", zeros(0, 1), ...
    "CorridorBoundary_deg", zeros(0, 2), ...
    "UsesReducedGeometry", false, ...
    "EstimatedDuration_s", NaN, "Length_deg", NaN);

emptySeedSummary = struct( ...
    "SeedIndex", 0, "SeedSource", "", ...
    "OptimizerFeasible", false, "ValidationPassed", false, ...
    "CollisionFree", false, "CollisionResolved", false, ...
    "MinimumClearance_deg", NaN, "UnresolvedIntervalCount", 0, ...
    "ArrivalTime_s", NaN, "MotionDuration_s", NaN, ...
    "MotionLength_deg", Inf, ...
    "IntegratedSquaredJerk_deg2_s5", Inf, ...
    "MaximumConstraintViolation", Inf, ...
    "SeedPlanningElapsedTime_s", 0, ...
    "TerminationReason", "notRun", ...
    "Message", "", ...
    "SolverDiagnostics", struct());

emptyPolynomial = struct( ...
    "SegmentCount", 0, "SegmentStartTime_s", zeros(0, 1), ...
    "SegmentDuration_s", NaN, ...
    "SegmentBreakTau", zeros(0, 1), ...
    "FinalTime_s", NaN, ...
    "positionPower_deg", zeros(0, 2, 6), ...
    "velocityPower_deg_s", zeros(0, 2, 5), ...
    "accelerationPower_deg_s2", zeros(0, 2, 4), ...
    "jerkPower_deg_s3", zeros(0, 2, 3), ...
    "TerminalState", struct( ...
    "position_deg", [NaN NaN], "velocity_deg_s", [NaN NaN], ...
    "acceleration_deg_s2", [NaN NaN]));

emptyPlane = struct("Active", false, "Normal", zeros(2, 2), ...
    "Offset_deg", zeros(1, 2), "SignedGap_deg", NaN, ...
    "Verified", false, "ExitFlag", NaN);
emptyPlaneCertificate = struct( ...
    "Kind", "", "Passed", false, "ExactRegionCount", 0, ...
    "SolverRegionCount", 0, "Regions_deg", {cell(0, 1)}, ...
    "Planes", repmat(emptyPlane, 0, 0), "RequiredGap_deg", NaN, ...
    "RoundoffReserve_deg", NaN, ...
    "MinimumSignedGap_deg", NaN, "CoveragePassed", false, ...
    "Coverage", struct(), "AllPairCount", 0, ...
    "VerifiedPairCount", 0, "ReusedPairCount", 0, ...
    "AnalyticPairCount", 0, "ConicPairCount", 0);

searchDiagnostics = struct( ...
    "Grid", struct(), ...
    "SeedSummaries", repmat(emptySeedSummary, 0, 1), ...
    "BestPartialSeedIndex", 0, ...
    "ValidatedCandidateCount", 0, "FirstValidatedMotionTime_s", NaN, ...
    "SeedGenerationElapsedTime_s", 0, ...
    "AttemptedSeedCount", 0, "TerminationReason", "notRun", ...
    "StageTiming", obstacleAvoidance.planner.stageTiming());

%% Section 2: Assemble The Stable Result

% Keep the request, planning geometry, solver evidence, and independent
% validation together so a failure can be explained without rerunning it.

result = struct( ...
    "Success", false, "Message", "Planning was not completed.", ...
    "TerminationReason", "notRun", ...
    "Options", options, ...
    "Inputs", struct( ...
    "obstacles", obstacles, ...
    "initialState", initialState, ...
    "goalState", goalState, ...
    "limits", limits), ...
    "Seeds", repmat(emptySeed, 0, 1), ...
    "SeedSummaries", repmat(emptySeedSummary, 0, 1), ...
    "SelectedSeedIndex", 0, ...
    "SelectedSeed_deg", zeros(0, 2), ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2), ...
    "Polynomial", emptyPolynomial, ...
    "SeedCorridorBoundary_deg", zeros(0, 2), ...
    "SeedCorridor", struct([]), ...
    "PlaneCertificate", emptyPlaneCertificate, ...
    "Validation", validationTemplate, ...
    "ArrivalTime_s", NaN, "TrajectoryDuration_s", NaN, ...
    "GoalHorizon_s", goalState.time_s - initialState.time_s, ...
    "FirstValidatedMotionTime_s", NaN, ...
    "SearchDiagnostics", searchDiagnostics, ...
    "ElapsedPlanningTime_s", 0);
end
