function result = plan(obstacles, initialState, goalState, limits, optionOverrides)
%% Section 0: Obstacle-Avoidance Planner
% Use exact state-to-state switching motion when geometry does not constrain
% the path. Otherwise search spatial topology and solve it with HS3.

if nargin == 0
    result = obstacleAvoidance.input.resolvePlannerOptions();
    return;
end
if nargin < 4
    error("planTrajectory:MissingInputs", ...
        "obstacles, initialState, goalState, and limits are required.");
end
if nargin < 5 || isempty(optionOverrides)
    optionOverrides = struct();
end
planningTimer = tic;
options = obstacleAvoidance.input.resolvePlannerOptions(optionOverrides);
[obstacles, initialState, goalState, limits] = ...
    obstacleAvoidance.input.normalizePlannerRequest( ...
    obstacles, initialState, goalState, limits, options);
[result, summaryTemplate] = obstacleAvoidance.planner.createEmptyResult( ...
    obstacles, initialState, goalState, limits, options, ...
    obstacleAvoidance.validateTrajectory());
obstacles = obstacleAvoidance.obstacles.prepareDynamic(obstacles);
stageTiming = result.SearchDiagnostics.StageTiming;
ruckigElapsedTime_s = result.SearchDiagnostics.RuckigElapsedTime_s;

%% Section 1: Reject Physically Invalid Endpoints

% Validate the request before spending time on graph search or nonlinear
% optimization. Endpoint checks include workspace limits, obstacle occupancy,
% and terminal motion. A blocked endpoint is an expected planning failure and
% returns a populated result with diagnostics.

[endpointFeasible, endpointMessage, endpointReason] = ...
    obstacleAvoidance.input.validatePlannerEndpoints( ...
    obstacles, initialState, goalState, limits, options);
if ~endpointFeasible
    result.Message = endpointMessage;
    result.TerminationReason = endpointReason;
    result.SearchDiagnostics.TerminationReason = endpointReason;
    result = obstacleAvoidance.planner.stageTiming( ...
        result, planningTimer, stageTiming);
    printPlannerProgress(options.Verbose, 1, 1, "endpoint rejected");
    return;
end

%% Section 2: Try Direct Motion With Ruckig

% Let the exact switching engine propose every fixed-position direct motion.
% Independent validation against the actual obstacles decides whether that
% motion is usable; invalid direct motions continue to topology search.

[result, stageTiming, ruckigHandled] = tryDirectRuckig( ...
    result, summaryTemplate, obstacles, initialState, goalState, limits, ...
    options, stageTiming);
if ruckigHandled
    if result.Success
        result.FirstValidatedMotionTime_s = toc(planningTimer);
        result.SearchDiagnostics.FirstValidatedMotionTime_s = ...
            result.FirstValidatedMotionTime_s;
    end
    result.SearchDiagnostics.StageTiming = stageTiming;
    result = obstacleAvoidance.planner.stageTiming( ...
        result, planningTimer, stageTiming);
    printPlannerProgress(options.Verbose, 1, 1, "planning complete");
    return;
end

%% Section 3: Create Input-Driven Topology Proposals

% Search protected obstacle geometry for several geometrically distinct ways
% to connect start and goal. These polylines are starting suggestions: they
% identify which side of obstacles to use, while HS3 later produces a
% continuous motion satisfying the physical limits.

printPlannerProgress(options.Verbose, 0, 1, "creating route candidates");
topologyTimer = tic;
[seeds, gridDiagnostics] = obstacleAvoidance.search.createRouteCandidates( ...
    obstacles, initialState, goalState, limits, options);
gridDiagnostics.ElapsedTime_s = toc(topologyTimer);
stageTiming.TopologyElapsedTime_s = gridDiagnostics.ElapsedTime_s;
result.Seeds = seeds;
result.SearchDiagnostics.Grid = gridDiagnostics;
result.SearchDiagnostics.SeedGenerationElapsedTime_s = gridDiagnostics.ElapsedTime_s;
printPlannerProgress(options.Verbose, 1, 1, "route candidates ready");
seedSummaries = repmat(summaryTemplate, numel(seeds), 1);
candidates = cell(numel(seeds), 1);

% Prefer a direct route only when the conservative swept-geometry graph
% certified its endpoint edge. Otherwise try input-derived detours first and
% retain direct proposals for dynamic cases where timing may make them viable.
routePointCount = reshape(arrayfun(@(seed) size(seed.position_deg, 1), seeds), [], 1);
isTimedTopology = any(string({seeds.Source}).' == ["directWait", "timeExpandedVisibilityGraph"], 2);
timedIndices = find(isTimedTopology);
detourIndices = find(routePointCount > 2 & ~isTimedTopology);
directIndices = find(routePointCount <= 2 & ~isTimedTopology);
hasChangingObstacles = obstacleAvoidance.obstacles.hasChangingHistory( ...
    obstacles, initialState.time_s, goalState.time_s);
staticDurationContinuationSeedIndex = 0;
if numel(detourIndices) > 1
    % Prefer shorter proposals but preserve deterministic order for ties.
    % Earliest-arrival work starts with the shortest geometric proposal.
    % Per-seed work budgets already account for route complexity.
    topologyEffort = [seeds(detourIndices).Length_deg];
    [~, effortOrder] = sort(topologyEffort, "ascend");
    detourIndices = detourIndices(effortOrder);
end
if conservativeDirectEdgeAccepted(gridDiagnostics)
    % Put a certified direct route first because it has a strong length lower
    % bound and normally requires the least nonlinear work.
    spatialOrder = [directIndices(:); detourIndices(:)];
else
    spatialOrder = [detourIndices(:); directIndices(:)];
    if ~hasChangingObstacles && ~options.CollectAllSeedCandidates && ...
            ~isempty(detourIndices) && ~isempty(directIndices)
        directLength_deg = min([seeds(directIndices).Length_deg]);
        shortestDetourLength_deg = min([seeds(detourIndices).Length_deg]);
        relativeDetourExcess = ...
            shortestDetourLength_deg / directLength_deg - 1;
        smallDeformationThreshold = 0.02;
        if relativeDetourExcess <= smallDeformationThreshold
            % A near-direct certified detour indicates that obstacle
            % avoidance requires only a small shape deformation. An
            % axis-aligned route with repeated lateral reversals also has a
            % certified endpoint-axis timing floor, so hybrid mode can try
            % that one topology before the blocked direct NLP.
            eligibleDetourIndices = zeros(0, 1);
            for detourIndex = reshape(detourIndices, 1, [])
                if supportsStaticDurationContinuation( ...
                        seeds(detourIndex), initialState, goalState, ...
                        options.ConstraintTolerance)
                    eligibleDetourIndices(end + 1, 1) = ...
                        detourIndex; %#ok<AGROW>
                end
            end
            useCertifiedContinuation = ...
                options.WaypointWarmStartMode == "passThrough" && ...
                options.GoalTimeMode == "earliestArrival" && ...
                ~isempty(eligibleDetourIndices);
            if useCertifiedContinuation
                staticDurationContinuationSeedIndex = ...
                    eligibleDetourIndices(1);
                remainingDetourIndices = detourIndices( ...
                    detourIndices ~= staticDurationContinuationSeedIndex);
                spatialOrder = [ ...
                    staticDurationContinuationSeedIndex; ...
                    directIndices(:); remainingDetourIndices(:)];
            else
                spatialOrder = [directIndices(:); detourIndices(:)];
            end
        end
    end
end
exactSpatialGraphUsed = gridDiagnostics.Coverage.ExactSpatialProposalUsed && ...
    gridDiagnostics.ExhaustiveVisibilityUsed;
staticNoPathCertified = ~hasChangingObstacles && exactSpatialGraphUsed && ...
    ~gridDiagnostics.HomologySearchTruncated && isempty(detourIndices) && ...
    ~conservativeDirectEdgeAccepted(gridDiagnostics);
gridDiagnostics.StaticNoPathCertified = staticNoPathCertified;
result.SearchDiagnostics.Grid = gridDiagnostics;
if hasChangingObstacles
    % Temporal search proposals already carry a causal obstacle-time law.
    % Exercise that information before free-time spatial local minima.
    seedOrder = [timedIndices(:); spatialOrder(:)];
else
    seedOrder = spatialOrder;
end
if hasChangingObstacles && options.GoalTimeMode == "fixedArrival" && ...
        ~isempty(seedOrder)
    % Fixed arrival ranks valid motions by spatial length. Trying the
    % shortest input-derived proposals first can prove the geometric lower
    % bound before spending work on longer topologies.
    orderedLength_deg = reshape( ...
        [seeds(seedOrder).Length_deg], [], 1);
    [~, lengthOrder] = sort(orderedLength_deg, "ascend");
    seedOrder = seedOrder(lengthOrder);
end
if staticNoPathCertified
    % A topology-preserving motion solve cannot repair an exact static graph
    % that exhausted every route and rejected its only direct edge.
    seedOrder = zeros(0, 1);
end
firstValidatedMotionTime_s = NaN;
bestValidatedFinalTime_s = Inf;
straightLineLowerBound_deg = norm( ...
    goalState.position_deg - initialState.position_deg);
lengthLowerBoundTolerance_deg = max( ...
    1e-10, 1e-10 * max(1, straightLineLowerBound_deg));

%% Section 4: Solve, Validate, And Boundedly Repair HS3 Motions

% Each seed is solved independently. A failed coarse mesh may be refined or
% relinearized within explicit limits, but every success must pass independent
% continuous-motion validation. Retain both the best valid candidate and the
% most informative failed partial candidate.

hs3Defaults = hs3Engine.defaultOptions();
maximumSolverTimePerAttempt_s = hs3Defaults.MaximumSolveTime;
minimumUsefulArrivalGain_s = 0.5;
ruckigArrivalLowerBound_s = NaN;
canCreateMovingArrivalLowerBound = hasChangingObstacles && ...
    options.GoalTimeMode == "earliestArrival" && ...
    ~(isfield(goalState, "targetTime_s") && ...
    ~isempty(goalState.targetTime_s));
if canCreateMovingArrivalLowerBound
    directLowerBoundSeed = createDirectSeed( ...
        initialState, goalState, goalState.time_s - initialState.time_s);
    [lowerBoundProfile, stageTiming, ruckigElapsedTime_s] = ...
        runPassThroughTimingProbe( ...
        initialState, goalState, limits, options, directLowerBoundSeed, 0, ...
        stageTiming, ruckigElapsedTime_s);
    hasExactDirectSection = isfield(lowerBoundProfile, ...
        "SectionDuration_s") && ...
        isscalar(lowerBoundProfile.SectionDuration_s) && ...
        isfinite(lowerBoundProfile.SectionDuration_s);
    if hasExactDirectSection
        % A direct one-section Ruckig profile is an exact obstacle-free
        % minimum-time relaxation. Its missing static corridor certificate is
        % irrelevant to the lower-bound role used here.
        ruckigArrivalLowerBound_s = initialState.time_s + ...
            lowerBoundProfile.SectionDuration_s;
    end
end
result.SearchDiagnostics.RuckigArrivalLowerBound_s = ...
    ruckigArrivalLowerBound_s;
staticDirectTimingProfile = [];
staticDurationContinuationAttempted = false;
useStaticHybridTiming = ...
    options.WaypointWarmStartMode == "passThrough" && ...
    options.GoalTimeMode == "earliestArrival" && ...
    ~hasChangingObstacles && ~isempty(obstacles) && ...
    staticDurationContinuationSeedIndex > 0 && ...
    ~(isfield(goalState, "targetTime_s") && ...
    ~isempty(goalState.targetTime_s));
if useStaticHybridTiming
    directTimingSeed = createDirectSeed( ...
        initialState, goalState, goalState.time_s - initialState.time_s);
    [staticDirectTimingProfile, stageTiming, ruckigElapsedTime_s] = ...
        runPassThroughTimingProbe( ...
        initialState, goalState, limits, options, directTimingSeed, 0, ...
        stageTiming, ruckigElapsedTime_s);
end
for orderIndex = 1:numel(seedOrder)
    % Order affects runtime, not the acceptance rules. Valid candidates are
    % compared under the same goal-time policy after validation.
    seedIndex = seedOrder(orderIndex);
    seedPlanningTimer = tic;
    seedPlanningTimeLimit_s = Inf;
    if options.CollectAllSeedCandidates
        seedPlanningTimeLimit_s = 30 + 15 * numel(obstacles);
    end
    printPlannerProgress(options.Verbose, orderIndex - 1, ...
        numel(seedOrder), "solving candidate " + seedIndex);
    originalSeed = seeds(seedIndex);
    equivalentTimedSeedIndex = 0;
    canReuseCompletedTimedTopology = hasChangingObstacles && ...
        options.GoalTimeMode == "earliestArrival" && ...
        ~options.CollectAllSeedCandidates && ...
        ~isTimedTopology(seedIndex) && ...
        ~(isfield(goalState, "targetTime_s") && ...
        ~isempty(goalState.targetTime_s));
    if canReuseCompletedTimedTopology
        equivalentTimedSeedIndex = equivalentCompletedTimedSeed( ...
            originalSeed, seeds, isTimedTopology, seedSummaries, ...
            straightLineLowerBound_deg, lengthLowerBoundTolerance_deg, ...
            bestValidatedFinalTime_s, options.ArrivalTimeTolerance_s);
    end
    if equivalentTimedSeedIndex > 0
        % The prior timed HS3 search already converged on this exact spatial
        % topology and attained the global Euclidean length floor. A second
        % free-time solve can only repeat its timing search through a less
        % reliable nonlinear formulation.
        seedSummaries(seedIndex).SeedIndex = seedIndex;
        seedSummaries(seedIndex).SeedSource = originalSeed.Source;
        seedSummaries(seedIndex).EquivalentTimedSeedIndex = ...
            equivalentTimedSeedIndex;
        seedSummaries(seedIndex).TerminationReason = ...
            "equivalentTimedTopologySolved";
        seedSummaries(seedIndex).Message = ...
            "A converged timed HS3 seed already solved this minimum-length " + ...
            "spatial topology.";
        printPlannerProgress(options.Verbose, orderIndex, ...
            numel(seedOrder), "candidate reused converged timed topology");
        continue;
    end
    axisTravel_deg = sum(abs(diff( ...
        originalSeed.position_deg, 1, 1)), 1);
    velocityDurationBound_s = max([1e-3, ...
        axisTravel_deg ./ limits.maxVelocity_deg_s]);
    spatialArrivalLowerBound_s = initialState.time_s + ...
        velocityDurationBound_s;
    isSpatialBoundDominated = ~options.CollectAllSeedCandidates && ...
        ~isTimedTopology(seedIndex) && ...
        spatialArrivalLowerBound_s >= bestValidatedFinalTime_s - ...
        options.ArrivalTimeTolerance_s;
    if isSpatialBoundDominated
        seedSummaries(seedIndex).SeedIndex = seedIndex;
        seedSummaries(seedIndex).SeedSource = originalSeed.Source;
        seedSummaries(seedIndex).TerminationReason = ...
            "arrivalBoundDominated";
        seedSummaries(seedIndex).Message = ...
            "A validated topology already meets this route's arrival bound.";
        printPlannerProgress(options.Verbose, orderIndex, ...
            numel(seedOrder), "candidate skipped by arrival bound");
        continue;
    end
    trialSeed = originalSeed;
    solverGoalState = goalState;
    if options.GoalTimeMode == "earliestArrival" && ...
            ~isTimedTopology(seedIndex) && isfinite(bestValidatedFinalTime_s)
        % A later solution cannot win candidate ranking. Tightening only the
        % free-time horizon preserves every potentially earlier motion.
        solverGoalState.time_s = min( ...
            solverGoalState.time_s, bestValidatedFinalTime_s);
    end
    seedGoalTimeMode = options.GoalTimeMode;
    if options.GoalTimeMode == "earliestArrival" && ( ...
            isempty(obstacles) || any( ...
            originalSeed.Source == ["directWait", ...
            "timeExpandedVisibilityGraph"]))
        % Timed topologies own an arrival proposal, while obstacle-free
        % motion has a convex fixed-time representation. Both avoid the
        % corresponding free-time local minimum through bounded bisection.
        solverGoalState.time_s = goalState.time_s;
        if ~isempty(obstacles)
            solverGoalState.time_s = min(goalState.time_s, ...
                initialState.time_s + originalSeed.EstimatedDuration_s);
        end
        seedGoalTimeMode = "fixedArrival";
    end
    segmentCount = min(options.MaximumCollocationSegmentCount, max( ...
        (1 + (isempty(obstacles) && ...
        options.GoalTimeMode == "earliestArrival")) * ...
        options.CollocationSegmentCount, max(2, size(originalSeed.position_deg, 1) - 1)));
    % Skip the midpoint solve when base segments span acceleration cycles.
    meshGrowthFactor = 2 + 2 * (size(originalSeed.position_deg, 1) > 3 && ...
        originalSeed.EstimatedDuration_s > 2 * options.CollocationSegmentCount * ...
        max(limits.maxVelocity_deg_s ./ limits.maxAcceleration_deg_s2) && ...
        ~isTimedTopology(seedIndex));
    totalRelinearizationCount = 0;
    meshRelinearizationCount = 0;
    meshRefinementCount = 0;
    validRelinearizationCount = 0;
    spatialTimingTarget_s = NaN;
    timedArrivalSearchActive = false;
    timedInfeasibleTime_s = NaN;
    timedFeasibleTime_s = NaN;
    timedArrivalTrialCount = 0;
    hs3SolveAttemptCount = 0;
    shapePolishAttempted = false;
    shapePolishAccepted = false;
    prePolishMotionLength_deg = NaN;
    ruckigAttempted = false;
    ruckigValidationPassed = false;
    ruckigTerminationReason = "notRun";
    ruckigDiagnostics = struct();
    directTimingProfile = struct();
    warmProfile = struct();
    warmCandidate = [];
    passThroughHs3Deferred = false;
    passThroughHs3Attempted = false;
    clusteredHs3RefinementAttempted = false;
    activityRefinementAttemptedSegmentCount = 0;
    arrivalLowerBoundGap_s = NaN;
    qualityMeshSuppressedByArrivalBound = false;
    maximumTimedArrivalTrialCount = 14;
    validatedCandidate = [];
    useWaypointHybrid = ...
        options.WaypointWarmStartMode == "passThrough" && ...
        options.GoalTimeMode == "earliestArrival" && ...
        ~hasChangingObstacles && ...
        ~isTimedTopology(seedIndex) && ...
        size(originalSeed.position_deg, 1) > 2;
    passThroughSearch = struct("Mode", "notRun");
    if useWaypointHybrid
        passThroughSearch = ...
            obstacleAvoidance.planner.classifyPassThroughSearch( ...
            originalSeed.position_deg, options.ConstraintTolerance);
    end
    hasClusteredSeedWaypoints = useWaypointHybrid && ...
        passThroughSearch.Mode == "oneDimensionalScalar" && ...
        seedHasClusteredWaypoints(originalSeed);
    usePassThroughWarmStart = useWaypointHybrid && ...
        ~hasClusteredSeedWaypoints;
    useClusteredHs3WarmStart = useWaypointHybrid && ...
        hasClusteredSeedWaypoints;
    useRuckigActivitySignature = ...
        options.WaypointWarmStartMode == "passThrough" && ...
        options.GoalTimeMode == "earliestArrival" && ...
        ~hasChangingObstacles && ...
        ~isTimedTopology(seedIndex) && ...
        size(originalSeed.position_deg, 1) == 2;
    useStaticDurationContinuation = ...
        ~staticDurationContinuationAttempted && ...
        useStaticHybridTiming && ...
        timingProfileIsUsable(staticDirectTimingProfile) && ...
        seedIndex == staticDurationContinuationSeedIndex;
    staticDurationContinuationSucceeded = false;
    if useStaticDurationContinuation
        staticDurationContinuationAttempted = true;
        [continuationCandidate, continuationDiagnostics, stageTiming] = ...
            runStaticDurationContinuation( ...
            staticDirectTimingProfile, originalSeed, obstacles, ...
            initialState, goalState, limits, options, stageTiming);
        ruckigAttempted = true;
        ruckigValidationPassed = ...
            staticDirectTimingProfile.OptimizerFeasible;
        ruckigTerminationReason = ...
            staticDirectTimingProfile.TerminationReason;
        ruckigDiagnostics = ...
            staticDirectTimingProfile.SolverDiagnostics;
        ruckigDiagnostics.UsedAsTimingSignatureOnly = true;
        ruckigDiagnostics.DurationContinuation = ...
            continuationDiagnostics;
        if ~isempty(continuationCandidate) && ...
                continuationCandidate.OptimizerFeasible && ...
                continuationCandidate.Validation.Passed
            validatedCandidate = continuationCandidate;
            staticDurationContinuationSucceeded = true;
            if isnan(firstValidatedMotionTime_s)
                firstValidatedMotionTime_s = toc(planningTimer);
            end
        end
    elseif usePassThroughWarmStart
        % A zero-sweep profile is a cheap measured timing probe. Scalar-axis
        % routes defer the much larger waypoint search and HS3 repair until
        % an ordinary coarse motion shows enough realizable arrival headroom.
        preliminarySweepCount = double( ...
            passThroughSearch.Mode ~= "oneDimensionalScalar");
        [preliminaryProfile, stageTiming, ruckigElapsedTime_s, ...
            preliminaryRuckigElapsedTime_s] = ...
            runPassThroughTimingProbe( ...
            initialState, goalState, limits, options, originalSeed, ...
            preliminarySweepCount, stageTiming, ruckigElapsedTime_s);
        warmProfile = preliminaryProfile;
        passThroughHs3Deferred = ~isempty(warmProfile.time_s) && ...
            passThroughSearch.Mode == "oneDimensionalScalar";
        if ~passThroughHs3Deferred
            % Coupled routes retain the established refined waypoint search;
            % their local state choices cannot be ranked by one scalar timing
            % probe, so they perform the established one refinement sweep.
            [warmCandidate, warmProfile, stageTiming] = ...
                runPassThroughHs3WarmStart( ...
                warmProfile, originalSeed, obstacles, initialState, ...
                goalState, limits, options, stageTiming);
            passThroughHs3Attempted = true;
        end
        ruckigAttempted = true;
        ruckigValidationPassed = warmProfile.OptimizerFeasible;
        ruckigTerminationReason = warmProfile.TerminationReason;
        ruckigDiagnostics = passThroughDiagnostics( ...
            warmProfile, warmCandidate);
        ruckigDiagnostics.PreliminaryElapsedTime_s = ...
            preliminaryRuckigElapsedTime_s;
        ruckigDiagnostics.PreliminaryFinalTime_s = ...
            preliminaryProfile.FinalTime_s;
        ruckigDiagnostics.PreliminaryRuckigSolveCount = ...
            preliminaryProfile.SolverDiagnostics.RuckigSolveCount;
        ruckigDiagnostics.Hs3DeferredForMeasuredPotential = ...
            passThroughHs3Deferred;
        ruckigDiagnostics.MeasuredArrivalPotential_s = NaN;
        if ~isempty(warmCandidate) && warmCandidate.Validation.Passed
            validatedCandidate = warmCandidate;
            if isnan(firstValidatedMotionTime_s)
                firstValidatedMotionTime_s = toc(planningTimer);
            end
        end
    elseif useRuckigActivitySignature
        % A two-point Ruckig profile is a dynamics lower bound and switching
        % signature only. The straight profile may cross an obstacle, so only
        % a later HS3 result can become a validated planner candidate.
        if isempty(staticDirectTimingProfile)
            [directTimingProfile, stageTiming, ruckigElapsedTime_s] = ...
                runPassThroughTimingProbe( ...
                initialState, goalState, limits, options, originalSeed, 0, ...
                stageTiming, ruckigElapsedTime_s);
        else
            directTimingProfile = staticDirectTimingProfile;
        end
        ruckigAttempted = true;
        ruckigValidationPassed = directTimingProfile.OptimizerFeasible;
        ruckigTerminationReason = directTimingProfile.TerminationReason;
        ruckigDiagnostics = directTimingProfile.SolverDiagnostics;
        ruckigDiagnostics.UsedAsTimingSignatureOnly = true;
        ruckigDiagnostics.ActivityRefinementMesh = struct();
    end
    previousSolve = struct("FinalTime_s", NaN, "MinimumClearance_deg", NaN);
    % Count-based caps below make planning decisions independent of machine
    % speed. The engine retains its own per-solve safety stop.
    while true
        if staticDurationContinuationSucceeded
            finalCandidate = validatedCandidate;
            break;
        end
        if useStaticDurationContinuation
            % An incomplete ladder has not reached its declared quality
            % target. Preserve its diagnostics, then try the ordinary direct
            % basin next instead of accepting an intermediate duration.
            finalCandidate = [];
            break;
        end
        hybridReplacesOrdinarySolve = usePassThroughWarmStart && ...
            ~hasChangingObstacles && ...
            ~isempty(validatedCandidate) && ...
            isfield(warmProfile.SolverDiagnostics, ...
            "MayReplaceOrdinarySolve") && ...
            warmProfile.SolverDiagnostics.MayReplaceOrdinarySolve;
        if hybridReplacesOrdinarySolve
            % The hybrid already performed fixed-time corridor repair and a
            % dense free-time HS3 solve on a measured high-leverage topology.
            % Low-leverage profiles retain ordinary HS3 as a competing basin.
            finalCandidate = validatedCandidate;
            break;
        end
        % One pass solves the current mesh and frozen corridor. Later passes
        % may update obstacle associations or add segments where continuous
        % validation found a violation.
        solverOptions = options;
        solverOptions.GoalTimeMode = seedGoalTimeMode;
        solverOptions.CollocationSegmentCount = segmentCount;
        remainingSeedTime_s = seedPlanningTimeLimit_s - ...
            toc(seedPlanningTimer);
        % Reserve two seconds for independent continuous validation and result
        % assembly so the complete per-seed mode stays inside its wall budget.
        seedFinalizationReserve_s = 2;
        solverOptions.MaximumSolverTime_s = min( ...
            maximumSolverTimePerAttempt_s, max( ...
            0, remainingSeedTime_s - seedFinalizationReserve_s));
        hs3SolveAttemptCount = hs3SolveAttemptCount + 1;
        finalCandidate = ...
            obstacleAvoidance.planner.solveRouteCandidate( ...
            obstacles, initialState, solverGoalState, limits, ...
            solverOptions, trialSeed);
        finalCandidate.Validation = validateCandidate( ...
            finalCandidate, obstacles, initialState, goalState, ...
            limits, options);
        stageTiming = addCandidateTiming(stageTiming, finalCandidate);
        if options.Verbose
            fprintf("[Planner][seed %d][attempt %d] segments=%d, " + ...
                "mode=%s, target=%.9g s, solver=%.6g s, validation=%.6g s, " + ...
                "optimizerFeasible=%d, validationPassed=%d, reason=%s.\n", ...
                seedIndex, hs3SolveAttemptCount, segmentCount, ...
                seedGoalTimeMode, solverGoalState.time_s, ...
                finalCandidate.SolverDiagnostics.ElapsedTime_s, ...
                finalCandidate.Validation.ElapsedTime_s, ...
                finalCandidate.OptimizerFeasible, ...
                finalCandidate.Validation.Passed, ...
                finalCandidate.TerminationReason);
        end
        seedTimeLimitReached = ...
            toc(seedPlanningTimer) >= seedPlanningTimeLimit_s;
        if finalCandidate.Validation.Passed
            if isnan(firstValidatedMotionTime_s)
                firstValidatedMotionTime_s = toc(planningTimer);
            end
            if passThroughHs3Deferred && ~passThroughHs3Attempted
                % Compare the cheap profile with an actual collision-free
                % HS3 basin. This measured gap is more predictive than the
                % sum of isolated edge savings, which can be unrealizable
                % after obstacle-constrained smoothing.
                passThroughHs3Attempted = true;
                passThroughHs3Deferred = false;
                measuredArrivalPotential_s = finalCandidate.FinalTime_s - ...
                    preliminaryProfile.FinalTime_s;
                ruckigDiagnostics.MeasuredArrivalPotential_s = ...
                    measuredArrivalPotential_s;
                ruckigDiagnostics.Hs3DeferredForMeasuredPotential = false;
                hasUsefulMeasuredPotential = ...
                    isfinite(measuredArrivalPotential_s) && ...
                    measuredArrivalPotential_s >= ...
                    minimumUsefulArrivalGain_s;
                if hasUsefulMeasuredPotential
                    [refinedProfile, stageTiming, ruckigElapsedTime_s] = ...
                        runPassThroughTimingProbe( ...
                        initialState, goalState, limits, options, ...
                        originalSeed, 1, stageTiming, ...
                        ruckigElapsedTime_s);
                    [deferredCandidate, warmProfile, stageTiming] = ...
                        runPassThroughHs3WarmStart( ...
                        refinedProfile, originalSeed, obstacles, ...
                        initialState, goalState, limits, options, ...
                        stageTiming);
                    warmCandidate = deferredCandidate;
                    ruckigValidationPassed = ...
                        warmProfile.OptimizerFeasible;
                    ruckigTerminationReason = ...
                        warmProfile.TerminationReason;
                    measuredDiagnostics = passThroughDiagnostics( ...
                        warmProfile, warmCandidate);
                    measuredDiagnostics.PreliminaryElapsedTime_s = ...
                        preliminaryRuckigElapsedTime_s;
                    measuredDiagnostics.PreliminaryFinalTime_s = ...
                        preliminaryProfile.FinalTime_s;
                    measuredDiagnostics.PreliminaryRuckigSolveCount = ...
                        preliminaryProfile.SolverDiagnostics. ...
                        RuckigSolveCount;
                    measuredDiagnostics. ...
                        Hs3DeferredForMeasuredPotential = false;
                    measuredDiagnostics.MeasuredArrivalPotential_s = ...
                        measuredArrivalPotential_s;
                    ruckigDiagnostics = measuredDiagnostics;
                    if ~isempty(deferredCandidate) && ...
                            deferredCandidate.Validation.Passed && ...
                            candidateImproves(deferredCandidate, ...
                            finalCandidate, options.GoalTimeMode)
                        finalCandidate = deferredCandidate;
                    end
                else
                    ruckigDiagnostics.HybridSkippedReason = ...
                        "measuredPotentialBelowHalfSecond";
                end
            end
            clusteredTargetSegmentCount = min( ...
                options.MaximumCollocationSegmentCount, max(20, ...
                2 * segmentCount));
            canRefineClusteredSeed = useClusteredHs3WarmStart && ...
                ~clusteredHs3RefinementAttempted && ...
                segmentCount < clusteredTargetSegmentCount && ...
                ~seedTimeLimitReached && meshRefinementCount < ...
                options.MaximumMeshRefinementPasses;
            if canRefineClusteredSeed
                % A sub-percent seed edge is geometry-resolution evidence,
                % not a useful standalone motion section. Reuse the valid
                % coarse HS3 polynomial on a denser mesh instead of paying
                % for hundreds of exact waypoint-state probes.
                validatedCandidate = finalCandidate;
                clusteredHs3RefinementAttempted = true;
                meshRefinementCount = meshRefinementCount + 1;
                totalRelinearizationCount = ...
                    totalRelinearizationCount + 1;
                segmentCount = clusteredTargetSegmentCount;
                trialSeed = seedFromCandidate( ...
                    finalCandidate, originalSeed);
                trialSeed.MotionWarmStart = finalCandidate;
                validRelinearizationCount = 1;
                continue;
            end
            relativeLengthExcess = coarseMotionLengthExcess( ...
                finalCandidate, originalSeed);
            % A five-percent spatial excess is large enough to be visible and
            % materially affect route quality. Hold arrival fixed and spend
            % one bounded convex cleanup rather than accepting an NLP loop.
            shapePolishThreshold = 0.05;
            shouldPolishShape = ~options.CollectAllSeedCandidates && ...
                ~shapePolishAttempted && ...
                seedGoalTimeMode == "earliestArrival" && ...
                relativeLengthExcess > shapePolishThreshold;
            if shouldPolishShape
                shapePolishAttempted = true;
                prePolishMotionLength_deg = finalCandidate.MotionLength_deg;
                [polishedCandidate, stageTiming] = polishEarliestMotionShape( ...
                    finalCandidate, originalSeed, obstacles, initialState, ...
                    goalState, limits, options, stageTiming);
                if candidateImproves( ...
                        polishedCandidate, finalCandidate, "fixedArrival")
                    finalCandidate = polishedCandidate;
                    shapePolishAccepted = true;
                end
            end
            if isempty(validatedCandidate) || candidateImproves( ...
                    finalCandidate, validatedCandidate, ...
                    options.GoalTimeMode)
                validatedCandidate = finalCandidate;
            end
            canRefineActivityMesh = useRuckigActivitySignature && ...
                activityRefinementAttemptedSegmentCount ~= ...
                segmentCount && ...
                ~seedTimeLimitReached && ...
                meshRefinementCount < ...
                options.MaximumMeshRefinementPasses;
            if canRefineActivityMesh
                activityRefinementAttemptedSegmentCount = segmentCount;
                activityMesh = ...
                    obstacleAvoidance.planner.createHybridActivityMesh( ...
                    finalCandidate, directTimingProfile, limits, ...
                    options.MaximumCollocationSegmentCount);
                ruckigDiagnostics.ActivityRefinementMesh = activityMesh;
                if activityMesh.Applied
                    meshRefinementCount = meshRefinementCount + 1;
                    totalRelinearizationCount = ...
                        totalRelinearizationCount + 1;
                    segmentCount = activityMesh.SegmentCount;
                    trialSeed = seedFromCandidate( ...
                        finalCandidate, originalSeed);
                    trialSeed.MotionWarmStart = finalCandidate;
                    trialSeed.SegmentBreakTau = ...
                        activityMesh.SegmentBreakTau;
                    % The adaptive solve already rebuilds the frozen
                    % corridor around the validated coarse motion.
                    validRelinearizationCount = 1;
                    continue;
                end
            end
            if seedTimeLimitReached
                finalCandidate = validatedCandidate;
                break;
            end
            relativeLengthExcess = coarseMotionLengthExcess( ...
                finalCandidate, originalSeed);
            % A 25% derivative reserve distinguishes velocity-dominated
            % coarse timing from motions already pressing higher derivatives.
            hasDerivativeSlack = all([ ...
                finalCandidate.Validation.PeakAcceleration_deg_s2 ./ ...
                limits.maxAcceleration_deg_s2, ...
                finalCandidate.Validation.PeakJerk_deg_s3 ./ ...
                limits.maxJerk_deg_s3] < 0.75);
            useFixedQualitySearch = meshRefinementCount < 1 && ~hasChangingObstacles && ...
                relativeLengthExcess > 2.5 / segmentCount;
            if seedGoalTimeMode == "fixedArrival" && ...
                    options.GoalTimeMode == "earliestArrival"
                if ~timedArrivalSearchActive
                    timedInfeasibleTime_s = initialState.time_s + velocityDurationBound_s;
                    timedArrivalSearchActive = true;
                end
                timedFeasibleTime_s = min( ...
                    timedFeasibleTime_s, finalCandidate.FinalTime_s, ...
                    "omitmissing");
                proposedSpatialTimingTarget_s = initialState.time_s + ...
                    2 * velocityDurationBound_s;
                hasSpatialTimingTrial = ~isfinite(spatialTimingTarget_s) && ...
                    originalSeed.Source == "timeExpandedVisibilityGraph" && ...
                    proposedSpatialTimingTarget_s < ...
                    validatedCandidate.FinalTime_s - ...
                    options.ArrivalTimeTolerance_s;
                if hasSpatialTimingTrial
                    spatialTimingTarget_s = proposedSpatialTimingTarget_s;
                    totalRelinearizationCount = totalRelinearizationCount + 1;
                    solverGoalState.time_s = spatialTimingTarget_s;
                    trialSeed = spatialTimingSeed(originalSeed);
                    continue;
                end
                hasTimedTrial = timedArrivalTrialCount < ...
                    maximumTimedArrivalTrialCount && ...
                    timedFeasibleTime_s - timedInfeasibleTime_s > ...
                    options.ArrivalTimeTolerance_s;
                if hasTimedTrial
                    timedArrivalTrialCount = timedArrivalTrialCount + 1;
                    totalRelinearizationCount = totalRelinearizationCount + 1;
                    solverGoalState.time_s = 0.5 * ...
                        (timedInfeasibleTime_s + timedFeasibleTime_s);
                    trialSeed = seedFromCandidate( ...
                        finalCandidate, originalSeed, ...
                        solverGoalState.time_s);
                    continue;
                end
            elseif hasChangingObstacles && ...
                    options.GoalTimeMode == "earliestArrival" && ...
                    ~isTimedTopology(seedIndex) && ...
                    isfinite(ruckigArrivalLowerBound_s) && ...
                    finalCandidate.FinalTime_s - ...
                    ruckigArrivalLowerBound_s < minimumUsefulArrivalGain_s
                % The obstacle-free switching time is a certified lower
                % bound. A denser moving-obstacle mesh cannot recover enough
                % arrival time to meet the declared runtime-for-gain budget.
                arrivalLowerBoundGap_s = max(0, ...
                    finalCandidate.FinalTime_s - ...
                    ruckigArrivalLowerBound_s);
                qualityMeshSuppressedByArrivalBound = true;
                finalCandidate = validatedCandidate;
                break;
            elseif options.GoalTimeMode == "earliestArrival" && ...
                    ~isTimedTopology(seedIndex) && ...
                    meshRefinementCount < options.MaximumMeshRefinementPasses && ...
                    ((validRelinearizationCount < 1 && ...
                    relativeLengthExcess > 1 / segmentCount) || ...
                    (validRelinearizationCount == 1 && hasDerivativeSlack) || ...
                    useFixedQualitySearch)
                nextSegmentCount = min(options.MaximumCollocationSegmentCount, ...
                    meshGrowthFactor * segmentCount + useFixedQualitySearch * ...
                    options.MaximumCollocationSegmentCount);
                if nextSegmentCount > segmentCount
                    meshRefinementCount = meshRefinementCount + 1;
                    totalRelinearizationCount = totalRelinearizationCount + 1;
                    segmentCount = nextSegmentCount;
                    trialSeed = originalSeed;
                    if validRelinearizationCount == 1
                        trialSeed = seedFromCandidate(finalCandidate, originalSeed);
                    end
                    if useFixedQualitySearch
                        seedGoalTimeMode = "fixedArrival";
                        solverGoalState.time_s = finalCandidate.FinalTime_s;
                    end
                    validRelinearizationCount = 2;
                    continue;
                end
            elseif validRelinearizationCount < 1
                validRelinearizationCount = validRelinearizationCount + 1;
                totalRelinearizationCount = totalRelinearizationCount + 1;
                trialSeed = seedFromCandidate(finalCandidate, originalSeed);
                continue;
            end
            finalCandidate = validatedCandidate;
            break;
        end

        if seedTimeLimitReached
            break;
        end

        if timedArrivalSearchActive && ~isempty(validatedCandidate)
            isSpatialTimingFailure = isfinite(spatialTimingTarget_s) && ...
                matchesWithin(solverGoalState.time_s, ...
                spatialTimingTarget_s, options.ArrivalTimeTolerance_s);
            if ~isSpatialTimingFailure
                timedInfeasibleTime_s = max( ...
                    timedInfeasibleTime_s, solverGoalState.time_s);
            end
            hasTimedTrial = timedArrivalTrialCount < ...
                maximumTimedArrivalTrialCount && ...
                timedFeasibleTime_s - timedInfeasibleTime_s > ...
                options.ArrivalTimeTolerance_s;
            if hasTimedTrial
                timedArrivalTrialCount = timedArrivalTrialCount + 1;
                totalRelinearizationCount = totalRelinearizationCount + 1;
                solverGoalState.time_s = 0.5 * ...
                    (timedInfeasibleTime_s + timedFeasibleTime_s);
                trialSeed = seedFromCandidate( ...
                    validatedCandidate, originalSeed, ...
                    solverGoalState.time_s);
                continue;
            end
        end
        if ~isempty(validatedCandidate)
            finalCandidate = validatedCandidate;
            break;
        end

        % Relinearizing around a motion that reproduced its predecessor only
        % re-derives the same rejected answer, so refine the mesh instead.
        repeatsPreviousSolve = reproducesSolve( ...
            finalCandidate, previousSolve, options);
        previousSolve.FinalTime_s = finalCandidate.FinalTime_s;
        previousSolve.MinimumClearance_deg = ...
            finalCandidate.Validation.MinimumClearance_deg;
        collisionOnly = ~isempty(finalCandidate.time_s) && ...
            ~finalCandidate.Validation.CollisionFree && ...
            finalCandidate.OptimizerFeasible;
        if collisionOnly && ~repeatsPreviousSolve && meshRelinearizationCount < 2
            % A collision-only failure can mean locally linear obstacle
            % supports are stale. Rebuild them around the new motion before
            % increasing mesh size, with a cap that prevents cycling.
            meshRelinearizationCount = meshRelinearizationCount + 1;
            totalRelinearizationCount = totalRelinearizationCount + 1;
            trialSeed = seedFromCandidate(finalCandidate, originalSeed);
            continue;
        end
        nextSegmentCount = min(options.MaximumCollocationSegmentCount, ...
            max(segmentCount + 1, 2 * segmentCount));
        if meshRefinementCount >= options.MaximumMeshRefinementPasses || ...
                nextSegmentCount <= segmentCount
            break;
        end
        meshRefinementCount = meshRefinementCount + 1;
        segmentCount = nextSegmentCount;
        meshRelinearizationCount = 0;
        if ~isempty(finalCandidate.time_s)
            trialSeed = seedFromCandidate(finalCandidate, originalSeed);
        end
    end
    if isempty(finalCandidate)
        if useStaticDurationContinuation
            seedSummaries(seedIndex).SeedIndex = seedIndex;
            seedSummaries(seedIndex).SeedSource = originalSeed.Source;
            seedSummaries(seedIndex).Hs3Attempted = true;
            seedSummaries(seedIndex).RuckigAttempted = ruckigAttempted;
            seedSummaries(seedIndex).RuckigValidationPassed = ...
                ruckigValidationPassed;
            seedSummaries(seedIndex).RuckigTerminationReason = ...
                ruckigTerminationReason;
            seedSummaries(seedIndex).RuckigDiagnostics = ...
                ruckigDiagnostics;
            seedSummaries(seedIndex).TerminationReason = ...
                "durationContinuationIncomplete";
            seedSummaries(seedIndex).Message = ...
                "The bounded continuation did not reach its final target.";
            seedSummaries(seedIndex).SeedPlanningElapsedTime_s = ...
                toc(seedPlanningTimer);
            seedSummaries(seedIndex).SeedPlanningTimeLimit_s = ...
                seedPlanningTimeLimit_s;
        end
        printPlannerProgress(options.Verbose, orderIndex, ...
            numel(seedOrder), "candidate work complete");
        continue;
    end
    candidates{seedIndex} = finalCandidate;
    seedSummaries(seedIndex) = candidateSummary( ...
        finalCandidate, totalRelinearizationCount, meshRefinementCount, ...
        shapePolishAttempted, shapePolishAccepted, ...
        prePolishMotionLength_deg, summaryTemplate);
    seedSummaries(seedIndex).SeedPlanningElapsedTime_s = ...
        toc(seedPlanningTimer);
    seedSummaries(seedIndex).SeedPlanningTimeLimit_s = ...
        seedPlanningTimeLimit_s;
    seedSummaries(seedIndex).Hs3SolveAttemptCount = hs3SolveAttemptCount;
    seedSummaries(seedIndex).RuckigArrivalLowerBound_s = ...
        ruckigArrivalLowerBound_s;
    seedSummaries(seedIndex).ArrivalLowerBoundGap_s = ...
        arrivalLowerBoundGap_s;
    seedSummaries(seedIndex).QualityMeshSuppressedByArrivalBound = ...
        qualityMeshSuppressedByArrivalBound;
    seedSummaries(seedIndex).TimedArrivalTrialCount = ...
        timedArrivalTrialCount;
    if timedArrivalSearchActive && isfinite(timedFeasibleTime_s) && ...
            isfinite(timedInfeasibleTime_s)
        timedArrivalBracketWidth_s = max( ...
            0, timedFeasibleTime_s - timedInfeasibleTime_s);
        seedSummaries(seedIndex).TimedArrivalBracketWidth_s = ...
            timedArrivalBracketWidth_s;
        seedSummaries(seedIndex).TimedArrivalSearchConverged = ...
            timedArrivalBracketWidth_s <= options.ArrivalTimeTolerance_s;
    end
    seedSummaries(seedIndex).RuckigAttempted = ruckigAttempted;
    seedSummaries(seedIndex).RuckigValidationPassed = ...
        ruckigValidationPassed;
    seedSummaries(seedIndex).RuckigTerminationReason = ...
        ruckigTerminationReason;
    seedSummaries(seedIndex).RuckigDiagnostics = ruckigDiagnostics;
    if finalCandidate.Validation.Passed
        bestValidatedFinalTime_s = min( ...
            bestValidatedFinalTime_s, finalCandidate.FinalTime_s);
    end
    fixedLengthLowerBoundReached = ...
        options.GoalTimeMode == "fixedArrival" && ...
        finalCandidate.Validation.Passed && ...
        finalCandidate.MotionLength_deg <= ...
        straightLineLowerBound_deg + lengthLowerBoundTolerance_deg;
    if fixedLengthLowerBoundReached && ~options.CollectAllSeedCandidates
        % Euclidean displacement is a global spatial lower bound. Once an
        % independently valid motion attains it, no later seed can be shorter.
        break;
    end
    % A motion pinned to the goal horizon is a fallback, not an earliest
    % arrival, so keep proposing topologies while budget remains.
    if ~options.CollectAllSeedCandidates && ...
            finalCandidate.Validation.Passed && ~hasChangingObstacles && ...
            ~finalCandidate.ArrivalAtHorizon && ...
            options.GoalTimeMode == "earliestArrival"
        break;
    end
    printPlannerProgress(options.Verbose, orderIndex, ...
        numel(seedOrder), "candidate work complete");
end
result.SearchDiagnostics.RuckigElapsedTime_s = ruckigElapsedTime_s;

%% Section 5: Select Or Return Diagnosable Failure

% Selection never trusts solver exit status alone. Only independently
% validated candidates are eligible. If none qualify, retain search and solve
% evidence and choose a specific reason so callers can see what stopped work.

result.SeedSummaries = seedSummaries;
if options.CollectAllSeedCandidates
    candidatePaths = repmat(result.CandidatePaths, 0, 1);
    for seedIndex = 1:numel(candidates)
        candidate = candidates{seedIndex};
        if isempty(candidate)
            continue;
        end
        path = struct( ...
            "SeedIndex", seedIndex, ...
            "SeedSource", seeds(seedIndex).Source, ...
            "ValidationPassed", candidate.Validation.Passed, ...
            "time_s", candidate.time_s, ...
            "position_deg", candidate.position_deg, ...
            "ArrivalTime_s", candidate.FinalTime_s, ...
            "MotionLength_deg", candidate.MotionLength_deg, ...
            "TerminationReason", candidate.TerminationReason);
        candidatePaths(end + 1, 1) = path; %#ok<AGROW>
    end
    result.CandidatePaths = candidatePaths;
end
result.SearchDiagnostics.SeedSummaries = seedSummaries;
result.SearchDiagnostics.AttemptedSeedCount = nnz([seedSummaries.Hs3Attempted]);
result.SearchDiagnostics.FirstValidatedMotionTime_s = firstValidatedMotionTime_s;
result.FirstValidatedMotionTime_s = firstValidatedMotionTime_s;
validatedIndices = find([seedSummaries.ValidationPassed]).';
result.SearchDiagnostics.ValidatedCandidateCount = numel(validatedIndices);
result.SearchDiagnostics.Hs3ElapsedTime_s = max(0, ...
    stageTiming.MotionSolvingElapsedTime_s - ...
    result.SearchDiagnostics.RuckigElapsedTime_s);
if isempty(validatedIndices)
    if gridDiagnostics.StaticNoPathCertified
        result.Message = "The exact static visibility graph exhausted all " + ...
            "routes, so no topology-preserving HS3 solve was attempted.";
    else
        result.Message = ...
            "No attempted HS3 motion passed independent validation.";
    end
    result.TerminationReason = "noValidatedSeed";
    result.SearchDiagnostics.TerminationReason = result.TerminationReason;
    result.SearchDiagnostics.BestPartialSeedIndex = ...
        bestPartialSeed(seedSummaries);
    result.SearchDiagnostics.StageTiming = stageTiming;
    result = obstacleAvoidance.planner.stageTiming( ...
        result, planningTimer, stageTiming);
    printPlannerProgress(options.Verbose, 1, 1, "planning complete");
    return;
end

selectedSeedIndex = selectValidatedCandidate( ...
    seedSummaries, validatedIndices, options.GoalTimeMode, ...
    options.ArrivalTimeTolerance_s);
selectedCandidate = candidates{selectedSeedIndex};
result.Success = true;
result.Message = "A kinematically constrained, collision-free path was found.";
result.TerminationReason = "goalReached";
result.SelectedSeedIndex = selectedSeedIndex;
result.SelectedSeed_deg = seeds(selectedSeedIndex).position_deg;
for fieldName = ["time_s", "position_deg", "velocity_deg_s", ...
        "acceleration_deg_s2", "jerk_deg_s3", "Polynomial", ...
        "SeedCorridorBoundary_deg", "SeedCorridor", "Validation"]
    result.(fieldName) = selectedCandidate.(fieldName);
end
result.ArrivalTime_s = selectedCandidate.FinalTime_s;
result.TrajectoryDuration_s = selectedCandidate.MotionDuration_s;
result.SearchDiagnostics.TerminationReason = result.TerminationReason;
result.SearchDiagnostics.BestPartialSeedIndex = selectedSeedIndex;
result.SearchDiagnostics.MeshRefinementPassCount = ...
    seedSummaries(selectedSeedIndex).MeshRefinementPassCount;
result.SearchDiagnostics.StageTiming = stageTiming;
result = obstacleAvoidance.planner.stageTiming( ...
    result, planningTimer, stageTiming);
printPlannerProgress(options.Verbose, 1, 1, "planning complete");
end

%% Section 6: Local Functions

function [result, stageTiming, handled] = tryDirectRuckig( ...
        result, summaryTemplate, obstacles, initialState, goalState, ...
        limits, options, stageTiming)
% Try exact direct motion first and accept it only after obstacle validation.

handled = false;
hasMovingGoal = isfield(goalState, "targetTime_s") && ...
    ~isempty(goalState.targetTime_s);
hasChangingObstacles = obstacleAvoidance.obstacles.hasChangingHistory( ...
    obstacles, initialState.time_s, goalState.time_s);
if hasMovingGoal || hasChangingObstacles
    return;
end
emptyResult = result;

engineInitialState = struct( ...
    "time", initialState.time_s, ...
    "position", initialState.position_deg, ...
    "velocity", initialState.velocity_deg_s, ...
    "acceleration", initialState.acceleration_deg_s2);
engineTerminalState = struct( ...
    "position", goalState.position_deg, ...
    "velocity", goalState.velocity_deg_s, ...
    "acceleration", goalState.acceleration_deg_s2, ...
    "maximumTime", goalState.time_s);
positionLower_deg = [limits.azimuthInterval_deg(1), ...
    limits.elevationInterval_deg(1)];
positionUpper_deg = [limits.azimuthInterval_deg(2), ...
    limits.elevationInterval_deg(2)];
if options.AllowAzimuthWrapping
    % The normalized goal may lie one turn outside the numeric interval. The
    % canonical planner validator owns this explicit periodic-axis exception.
    positionLower_deg(1) = -Inf;
    positionUpper_deg(1) = Inf;
end
engineLimits = struct( ...
    "maximumVelocity", limits.maxVelocity_deg_s, ...
    "maximumAcceleration", limits.maxAcceleration_deg_s2, ...
    "maximumJerk", limits.maxJerk_deg_s3, ...
    "positionLower", positionLower_deg, ...
    "positionUpper", positionUpper_deg);
engineOptions = struct( ...
    "TimeMode", options.GoalTimeMode, ...
    "FinalTime", [], ...
    "SampleTime", options.SampleTime_s, ...
    "ConstraintTolerance", options.ConstraintTolerance, ...
    "ArrivalTimeTolerance", options.ArrivalTimeTolerance_s, ...
    "Verbose", options.Verbose);
if options.GoalTimeMode == "fixedArrival"
    engineOptions.TimeMode = "fixed";
    engineOptions.FinalTime = goalState.time_s;
end

solveTimer = tic;
    engineResult = planTrajRuckig( ...
    engineInitialState, engineTerminalState, engineLimits, engineOptions);
ruckigElapsedTime_s = toc(solveTimer);
stageTiming.MotionSolvingElapsedTime_s = ...
    stageTiming.MotionSolvingElapsedTime_s + ruckigElapsedTime_s;
result.SearchDiagnostics.RuckigElapsedTime_s = ruckigElapsedTime_s;

if engineResult.TerminationReason == "unsupportedSwitchingFamily"
    return;
end

handled = true;
result.SearchDiagnostics.AttemptedSeedCount = 1;
result.SearchDiagnostics.ValidatedCandidateCount = 0;
result.SearchDiagnostics.TerminationReason = engineResult.TerminationReason;
seed = createDirectSeed(initialState, goalState, engineResult.Duration);
result.Seeds = seed;
summary = summaryTemplate;
summary.SeedIndex = 1;
summary.SeedSource = seed.Source;
summary.RuckigAttempted = true;
summary.RuckigValidationPassed = false;
summary.RuckigTerminationReason = engineResult.TerminationReason;
summary.RuckigDiagnostics = engineResult.Diagnostics;
summary.TerminationReason = engineResult.TerminationReason;
summary.Message = engineResult.Message;
summary.SolverDiagnostics = engineResult.Diagnostics;
summary.MaximumConstraintViolation = ...
    engineResult.MaximumConstraintViolation;

if ~engineResult.Success
    result.Message = engineResult.Message;
    result.TerminationReason = engineResult.TerminationReason;
    result.SeedSummaries = summary;
    result.SearchDiagnostics.SeedSummaries = summary;
    result.SearchDiagnostics.BestPartialSeedIndex = 1;
    return;
end

result.time_s = engineResult.time;
result.position_deg = engineResult.position;
result.velocity_deg_s = engineResult.velocity;
result.acceleration_deg_s2 = engineResult.acceleration;
result.jerk_deg_s3 = engineResult.jerk;
result.Polynomial = convertRuckigPolynomial(engineResult.Polynomial);
validationTimer = tic;
result.Validation = obstacleAvoidance.validateTrajectory( ...
    result, obstacles, initialState, goalState, limits, options);
validationElapsedTime_s = toc(validationTimer);
stageTiming.CollisionCheckingElapsedTime_s = ...
    result.Validation.CollisionCheckingElapsedTime_s;
stageTiming.FinalValidationElapsedTime_s = max(0, ...
    validationElapsedTime_s - ...
    result.Validation.CollisionCheckingElapsedTime_s);
motionLength_deg = sum(vecnorm(diff(result.position_deg, 1, 1), 2, 2));
summary.OptimizerFeasible = true;
summary.ValidationPassed = result.Validation.Passed;
summary.CollisionFree = result.Validation.CollisionFree;
summary.CollisionResolved = result.Validation.CollisionResolved;
summary.MinimumClearance_deg = result.Validation.MinimumClearance_deg;
summary.UnresolvedIntervalCount = ...
    result.Validation.UnresolvedIntervalCount;
summary.ArrivalTime_s = engineResult.FinalTime;
summary.MotionDuration_s = engineResult.Duration;
summary.MotionLength_deg = motionLength_deg;
summary.IntegratedSquaredJerk_deg2_s5 = ...
    engineResult.IntegratedSquaredJerk;
summary.RuckigValidationPassed = result.Validation.Passed;

if result.Validation.Passed
    result.Success = true;
    result.Message = ...
        "A kinematically constrained, collision-free path was found.";
    result.TerminationReason = "goalReached";
    result.ArrivalTime_s = engineResult.FinalTime;
    result.TrajectoryDuration_s = engineResult.Duration;
    result.SelectedSeedIndex = 1;
    result.SelectedSeed_deg = seed.position_deg;
    result.SearchDiagnostics.ValidatedCandidateCount = 1;
    result.SearchDiagnostics.BestPartialSeedIndex = 1;
else
    if ~isempty(obstacles)
        % A direct collision is a topology-search input, not a planning
        % failure. Discard the trial payload and continue through HS3.
        result = emptyResult;
        result.SearchDiagnostics.RuckigElapsedTime_s = ...
            ruckigElapsedTime_s;
        handled = false;
        return;
    end
    result.Message = "The exact obstacle-free motion failed independent " + ...
        "planner validation. " + result.Validation.Message;
    result.TerminationReason = "ruckigValidationFailed";
    summary.TerminationReason = result.TerminationReason;
    summary.Message = result.Message;
    result.SearchDiagnostics.BestPartialSeedIndex = 1;
end
summary.RuckigTerminationReason = result.TerminationReason;
summary.TerminationReason = result.TerminationReason;
result.SeedSummaries = summary;
result.SearchDiagnostics.SeedSummaries = summary;
result.SearchDiagnostics.TerminationReason = result.TerminationReason;
end

function seed = createDirectSeed(initialState, goalState, duration_s)
% Create the obstacle planner's ordinary two-endpoint route record.
position_deg = [initialState.position_deg; goalState.position_deg];
seed = struct( ...
    "Index", 1, ...
    "Source", "ruckigDirect", ...
    "position_deg", position_deg, ...
    "tau", [0; 1], ...
    "CorridorBoundary_deg", zeros(0, 2), ...
    "UsesReducedGeometry", false, ...
    "EstimatedDuration_s", duration_s, ...
    "Length_deg", norm(diff(position_deg, 1, 1)));
end

function polynomial = convertRuckigPolynomial(enginePolynomial)
% Translate exact-engine coefficient names at the obstacle-planner boundary.
terminalState = enginePolynomial.TerminalState;
polynomial = struct( ...
    "SegmentCount", enginePolynomial.SegmentCount, ...
    "SegmentStartTime_s", enginePolynomial.SegmentStartTime, ...
    "SegmentDuration_s", enginePolynomial.SegmentDuration, ...
    "FinalTime_s", enginePolynomial.FinalTime, ...
    "positionPower_deg", enginePolynomial.positionPower, ...
    "velocityPower_deg_s", enginePolynomial.velocityPower, ...
    "accelerationPower_deg_s2", ...
    enginePolynomial.accelerationPower, ...
    "jerkPower_deg_s3", enginePolynomial.jerkPower, ...
    "TerminalState", struct( ...
    "position_deg", terminalState.position, ...
    "velocity_deg_s", terminalState.velocity, ...
    "acceleration_deg_s2", terminalState.acceleration));
end

function accepted = conservativeDirectEdgeAccepted(gridDiagnostics)
% Read the search-owned swept-envelope certificate without repeating geometry.
accepted = false;
edges_deg = gridDiagnostics.AcceptedEdges_deg;
if isempty(edges_deg)
    return;
end
start_deg = gridDiagnostics.Start_deg;
goal_deg = gridDiagnostics.Goal_deg;
tolerance_deg = 1e-9;
forward = max(abs(edges_deg(:, 1:2) - start_deg), [], 2) <= tolerance_deg & ...
    max(abs(edges_deg(:, 3:4) - goal_deg), [], 2) <= tolerance_deg;
reverse = max(abs(edges_deg(:, 1:2) - goal_deg), [], 2) <= tolerance_deg & ...
    max(abs(edges_deg(:, 3:4) - start_deg), [], 2) <= tolerance_deg;
accepted = any(forward | reverse);
end

function printPlannerProgress(verbose, completedCount, totalCount, label)
% Print a truthful Unicode bar for completed bounded planner work.
if ~verbose
    return;
end
barWidth = 12;
fraction = min(1, max(0, completedCount / max(1, totalCount)));
filledCount = floor(barWidth * fraction);
barCells = repmat("░", 1, barWidth);
barCells(1:filledCount) = "█";
scaledWidth = barWidth * fraction;
hasPartialCell = filledCount < barWidth && ...
    scaledWidth - filledCount > 10 * eps(max(1, scaledWidth));
if hasPartialCell
    barCells(filledCount + 1) = "▒";
end
bar = join(barCells, "");
fprintf("[Planner] [%s] %3.0f%% %s\n", ...
    char(bar), 100 * fraction, char(label));
end

function validation = validateCandidate( ...
        candidate, obstacles, initialState, goalState, limits, options)
% Canonical validation is authoritative even when the optimizer is feasible.
if isempty(candidate.time_s)
    validation = obstacleAvoidance.validateTrajectory();
    validation.Message = "The HS3 solver returned no trajectory.";
else
    validation = obstacleAvoidance.validateTrajectory( ...
        candidate, obstacles, initialState, goalState, limits, options);
end
end

function isSupported = supportsStaticDurationContinuation( ...
        seed, initialState, goalState, constraintTolerance_deg)
% Certify an axis-aligned monotone slalom with repeated lateral reversals.
isSupported = false;
position_deg = seed.position_deg;
displacement_deg = goalState.position_deg - initialState.position_deg;
scale_deg = max(1, max(abs(displacement_deg)));
geometryTolerance_deg = max(1e-10, ...
    constraintTolerance_deg * scale_deg);
activeAxis = find(abs(displacement_deg) > geometryTolerance_deg);
if numel(activeAxis) ~= 1 || size(position_deg, 1) < 4
    return;
end
primaryAxis = activeAxis(1);
lateralAxis = 3 - primaryAxis;
primaryIncrement_deg = diff(position_deg(:, primaryAxis));
progressDirection = sign(displacement_deg(primaryAxis));
if any(progressDirection * primaryIncrement_deg < ...
        -geometryTolerance_deg)
    return;
end
primaryTravel_deg = sum(abs(primaryIncrement_deg));
if abs(primaryTravel_deg - abs(displacement_deg(primaryAxis))) > ...
        geometryTolerance_deg
    return;
end
nearDirectLengthThreshold = 0.02;
directLength_deg = abs(displacement_deg(primaryAxis));
if seed.Length_deg / directLength_deg - 1 > ...
        nearDirectLengthThreshold
    return;
end
lateralOffset_deg = position_deg(:, lateralAxis) - ...
    initialState.position_deg(lateralAxis);
lateralSign = sign(lateralOffset_deg( ...
    abs(lateralOffset_deg) > geometryTolerance_deg));
if numel(lateralSign) < 3
    return;
end
retainedSign = [true; diff(lateralSign) ~= 0];
lateralSign = lateralSign(retainedSign);
minimumLateralReversalCount = 2;
isSupported = nnz(diff(lateralSign) ~= 0) >= ...
    minimumLateralReversalCount;
end

function isUsable = timingProfileIsUsable(profile)
% A direct exact motion can bound time even when no obstacle corridor exists.
isUsable = ~isempty(profile) && isstruct(profile) && ...
    isscalar(profile) && isfield(profile, "FinalTime_s") && ...
    isfield(profile, "time_s") && ~isempty(profile.time_s) && ...
    isfinite(profile.FinalTime_s);
end

function [candidate, diagnostics, stageTiming] = ...
        runStaticDurationContinuation( ...
        timingProfile, seed, obstacles, initialState, goalState, limits, ...
        options, stageTiming)
% Descend a fixed static route through a bounded normalized-time schedule.
% Only optimizer-feasible and independently valid trials become warm starts.
candidate = [];
floorDuration_s = timingProfile.FinalTime_s - initialState.time_s;
durationMultipliers = [1.25, 1.20, 1.15, 1.10, 1.05, 1.025];
targetTime_s = initialState.time_s + ...
    durationMultipliers * floorDuration_s;
withinHorizon = targetTime_s <= ...
    goalState.time_s + options.ArrivalTimeTolerance_s;
targetTime_s = targetTime_s(withinHorizon);
durationMultipliers = durationMultipliers(withinHorizon);
edgeCount = size(seed.position_deg, 1) - 1;
minimumContinuationSegmentCount = 14;
segmentsPerEdge = 2;
segmentCount = min(options.MaximumCollocationSegmentCount, max([ ...
    options.CollocationSegmentCount, minimumContinuationSegmentCount, ...
    segmentsPerEdge * edgeCount]));
trialTemplate = struct( ...
    "TargetTime_s", NaN, ...
    "OptimizerFeasible", false, ...
    "ValidationPassed", false, ...
    "MotionLength_deg", NaN, ...
    "MaximumConstraintViolation", Inf, ...
    "ElapsedTime_s", NaN, ...
    "TerminationReason", "notRun");
trials = repmat(trialTemplate, numel(targetTime_s), 1);
acceptedCandidate = [];
attemptCount = 0;
for targetIndex = 1:numel(targetTime_s)
    attemptCount = attemptCount + 1;
    trialGoalState = goalState;
    trialGoalState.time_s = targetTime_s(targetIndex);
    trialOptions = options;
    trialOptions.GoalTimeMode = "fixedArrival";
    trialOptions.CollocationSegmentCount = segmentCount;
    trialOptions.MaximumSolverTime_s = ...
        hs3Engine.defaultOptions().MaximumSolveTime;
    trialSeed = seed;
    trialSeed.EstimatedDuration_s = ...
        targetTime_s(targetIndex) - initialState.time_s;
    if ~isempty(acceptedCandidate)
        trialSeed.MotionWarmStart = createDurationScaledWarmStart( ...
            acceptedCandidate, initialState, targetTime_s(targetIndex));
    end
    trial = obstacleAvoidance.planner.solveRouteCandidate( ...
        obstacles, initialState, trialGoalState, limits, trialOptions, ...
        trialSeed);
    trial.Validation = validateCandidate( ...
        trial, obstacles, initialState, trialGoalState, limits, ...
        trialOptions);
    stageTiming = addCandidateTiming(stageTiming, trial);
    trials(targetIndex) = struct( ...
        "TargetTime_s", targetTime_s(targetIndex), ...
        "OptimizerFeasible", trial.OptimizerFeasible, ...
        "ValidationPassed", trial.Validation.Passed, ...
        "MotionLength_deg", trial.MotionLength_deg, ...
        "MaximumConstraintViolation", ...
        trial.MaximumConstraintViolation, ...
        "ElapsedTime_s", trial.SolverDiagnostics.ElapsedTime_s + ...
        trial.Validation.ElapsedTime_s, ...
        "TerminationReason", trial.TerminationReason);
    if ~trial.OptimizerFeasible || ~trial.Validation.Passed
        break;
    end
    acceptedCandidate = trial;
end
trials = trials(1:attemptCount);
targetReached = ~isempty(targetTime_s) && ...
    attemptCount == numel(targetTime_s) && ...
    ~isempty(acceptedCandidate) && ...
    matchesWithin(acceptedCandidate.FinalTime_s, targetTime_s(end), ...
    options.ArrivalTimeTolerance_s);
if targetReached
    acceptedCandidate.Validation = validateCandidate( ...
        acceptedCandidate, obstacles, initialState, goalState, limits, ...
        options);
    acceptedCandidate.ArrivalAtHorizon = matchesWithin( ...
        acceptedCandidate.FinalTime_s, goalState.time_s, ...
        options.ArrivalTimeTolerance_s);
    if acceptedCandidate.OptimizerFeasible && ...
            acceptedCandidate.Validation.Passed
        candidate = acceptedCandidate;
    end
end
diagnostics = struct( ...
    "Applied", attemptCount > 0, ...
    "TimingFloor_s", timingProfile.FinalTime_s, ...
    "DurationMultipliers", durationMultipliers(:), ...
    "SegmentCount", segmentCount, ...
    "AttemptCount", attemptCount, ...
    "Trial", trials, ...
    "TargetReached", targetReached, ...
    "Accepted", ~isempty(candidate), ...
    "AcceptedFinalTime_s", NaN);
if ~isempty(candidate)
    diagnostics.AcceptedFinalTime_s = candidate.FinalTime_s;
end
end

function warmStart = createDurationScaledWarmStart( ...
        candidate, initialState, finalTime_s)
% Preserve one valid spatial curve while scaling all time derivatives.
polynomial = candidate.Polynomial;
segmentBreakTau = polynomial.SegmentBreakTau;
segmentCount = polynomial.SegmentCount;
controlTau = zeros(2 * segmentCount + 1, 1);
controlTau(1:2:end) = segmentBreakTau;
controlTau(2:2:end - 1) = ...
    (segmentBreakTau(1:end - 1) + segmentBreakTau(2:end)) / 2;
oldDuration_s = candidate.FinalTime_s - initialState.time_s;
oldControlTime_s = initialState.time_s + controlTau * oldDuration_s;
[~, ~, ~, ~, oldJerk_deg_s3] = ...
    obstacleAvoidance.planner.evaluatePlannerPolynomial( ...
    polynomial, oldControlTime_s);
newDuration_s = finalTime_s - initialState.time_s;
newJerk_deg_s3 = oldJerk_deg_s3 * ...
    (oldDuration_s / newDuration_s)^3;
engineInitialState = struct( ...
    "time", initialState.time_s, ...
    "position", initialState.position_deg, ...
    "velocity", initialState.velocity_deg_s, ...
    "acceleration", initialState.acceleration_deg_s2);
uniformBreakTau = (0:segmentCount).' / segmentCount;
if isempty(segmentBreakTau) || isequal(segmentBreakTau, uniformBreakTau)
    enginePolynomial = hs3Engine.polynomial.createTrajectoryPolynomial( ...
        newJerk_deg_s3, engineInitialState, finalTime_s, segmentCount);
else
    enginePolynomial = hs3Engine.polynomial.createTrajectoryPolynomial( ...
        newJerk_deg_s3, engineInitialState, finalTime_s, segmentCount, ...
        segmentBreakTau);
end
if isfield(enginePolynomial, "SegmentBreakTau")
    resolvedSegmentBreakTau = enginePolynomial.SegmentBreakTau;
else
    resolvedSegmentBreakTau = uniformBreakTau;
end
warmPolynomial = struct( ...
    "SegmentCount", enginePolynomial.SegmentCount, ...
    "SegmentStartTime_s", enginePolynomial.SegmentStartTime, ...
    "SegmentDuration_s", enginePolynomial.SegmentDuration, ...
    "SegmentBreakTau", resolvedSegmentBreakTau, ...
    "FinalTime_s", enginePolynomial.FinalTime, ...
    "positionPower_deg", enginePolynomial.positionPower, ...
    "velocityPower_deg_s", enginePolynomial.velocityPower, ...
    "accelerationPower_deg_s2", enginePolynomial.accelerationPower, ...
    "jerkPower_deg_s3", enginePolynomial.jerkPower, ...
    "TerminalState", struct( ...
    "position_deg", enginePolynomial.TerminalState.position, ...
    "velocity_deg_s", enginePolynomial.TerminalState.velocity, ...
    "acceleration_deg_s2", ...
    enginePolynomial.TerminalState.acceleration));
sampleTau = (candidate.time_s - candidate.time_s(1)) / oldDuration_s;
warmStart = struct( ...
    "FinalTime_s", finalTime_s, ...
    "Polynomial", warmPolynomial, ...
    "time_s", initialState.time_s + sampleTau * newDuration_s, ...
    "position_deg", candidate.position_deg);
end

function [candidate, profile, stageTiming] = ...
        runPassThroughHs3WarmStart( ...
        profile, seed, obstacles, initialState, goalState, limits, ...
        options, stageTiming)
% Repair one precomputed rsruckig-style profile with two bounded HS3 solves.
% Both outputs undergo canonical validation; an invalid repair never replaces
% the original exact profile as the free-time warm start.
candidate = [];
if isempty(profile.time_s)
    return;
end

repairGoalState = goalState;
repairGoalState.time_s = profile.FinalTime_s;
repairOptions = options;
repairOptions.GoalTimeMode = "fixedArrival";
repairOptions.MaximumSolverTime_s = ...
    hs3Engine.defaultOptions().MaximumSolveTime;
[repairSegmentCount, polishSegmentCount, hybridSignature, ...
    mayReplaceOrdinarySolve] = ...
    hybridSegmentCounts(profile, options);
repairOptions.CollocationSegmentCount = repairSegmentCount;
repairSeed = seed;
repairSeed.MotionWarmStart = profile;
repaired = obstacleAvoidance.planner.solveRouteCandidate( ...
    obstacles, initialState, repairGoalState, limits, repairOptions, ...
    repairSeed);
repaired.Validation = validateCandidate( ...
    repaired, obstacles, initialState, repairGoalState, limits, ...
    repairOptions);
stageTiming = addCandidateTiming(stageTiming, repaired);
if repaired.Validation.Passed
    candidate = repaired;
end

polishOptions = options;
polishOptions.GoalTimeMode = "earliestArrival";
polishOptions.MaximumSolverTime_s = ...
    hs3Engine.defaultOptions().MaximumSolveTime;
polishOptions.CollocationSegmentCount = polishSegmentCount;
polishSeed = seed;
if repaired.Validation.Passed
    % An optimizer can return sampled motion after an infeasible exit. Only
    % a canonically validated repair may replace the original Ruckig warm
    % start; otherwise its residual can push the free-time solve into a
    % slower or worse basin.
    polishSeed.MotionWarmStart = repaired;
else
    polishSeed.MotionWarmStart = profile;
end
polished = obstacleAvoidance.planner.solveRouteCandidate( ...
    obstacles, initialState, goalState, limits, polishOptions, polishSeed);
polished.Validation = validateCandidate( ...
    polished, obstacles, initialState, goalState, limits, polishOptions);
stageTiming = addCandidateTiming(stageTiming, polished);
if polished.Validation.Passed && (isempty(candidate) || ...
        candidateImproves(polished, candidate, "earliestArrival"))
    candidate = polished;
end
profile.SolverDiagnostics.SectionSignature = hybridSignature;
profile.SolverDiagnostics.RepairSegmentCount = repairSegmentCount;
profile.SolverDiagnostics.PolishSegmentCount = polishSegmentCount;
profile.SolverDiagnostics.MayReplaceOrdinarySolve = ...
    mayReplaceOrdinarySolve;
end

function diagnostics = passThroughDiagnostics(profile, warmCandidate)
% Preserve comparable Ruckig and repaired-candidate evidence on every exit.
diagnostics = profile.SolverDiagnostics;
diagnostics.WarmCandidateValidationPassed = ...
    ~isempty(warmCandidate) && warmCandidate.Validation.Passed;
diagnostics.WarmCandidateArrivalTime_s = NaN;
if ~isempty(warmCandidate)
    diagnostics.WarmCandidateArrivalTime_s = ...
        warmCandidate.FinalTime_s;
end
diagnostics.MaximumCorridorViolation_deg = ...
    profile.MaximumCorridorViolation_deg;
diagnostics.WaypointVelocity_deg_s = ...
    profile.WaypointVelocity_deg_s;
diagnostics.WaypointAcceleration_deg_s2 = ...
    profile.WaypointAcceleration_deg_s2;
diagnostics.InitialSectionDuration_s = ...
    profile.InitialSectionDuration_s;
diagnostics.SectionDuration_s = profile.SectionDuration_s;
diagnostics.SectionTimeSaving_s = profile.SectionTimeSaving_s;
diagnostics.TimeSensitiveEdgeIndex = profile.TimeSensitiveEdgeIndex;
end

function [repairSegmentCount, polishSegmentCount, signature, ...
        mayReplaceOrdinarySolve] = ...
        hybridSegmentCounts(profile, options)
% Scale repair work by route size and reserve dense polish for measured gain.
initialDuration_s = profile.InitialSectionDuration_s(:);
sectionDuration_s = profile.SectionDuration_s(:);
positiveTimeSaving_s = max(0, initialDuration_s - sectionDuration_s);
relativePositiveTimeSaving = sum(positiveTimeSaving_s) / ...
    sum(initialDuration_s);
edgeCount = numel(sectionDuration_s);
signature = struct( ...
    "EdgeCount", edgeCount, ...
    "TotalPositiveTimeSaving_s", sum(positiveTimeSaving_s), ...
    "RelativePositiveTimeSaving", relativePositiveTimeSaving);
minimumRepairSegmentCount = 12;
segmentsPerEdge = 1.75;
repairSegmentCount = min(options.MaximumCollocationSegmentCount, max( ...
    minimumRepairSegmentCount, ceil(segmentsPerEdge * edgeCount)));

% A two-percent pass-through saving is materially above solver tolerances and
% identifies routes where waypoint-state propagation changes the timing basin.
% Low-gain routes retain the cheaper established 14-segment finish.
meaningfulRelativeSaving = 0.02;
lowGainPolishSegmentCount = 14;
highGainPolishSegmentCount = 20;
hasFullyReversingRoute = ...
    profile.SolverDiagnostics.WaypointStateSearchMode == ...
    "coupledReversing";
hasHighGainSignature = ...
    relativePositiveTimeSaving >= meaningfulRelativeSaving || ...
    hasFullyReversingRoute;
if hasHighGainSignature
    requestedPolishSegmentCount = highGainPolishSegmentCount;
else
    requestedPolishSegmentCount = lowGainPolishSegmentCount;
end
polishSegmentCount = min( ...
    options.MaximumCollocationSegmentCount, requestedPolishSegmentCount);
mayReplaceOrdinarySolve = hasHighGainSignature && ...
    options.MaximumCollocationSegmentCount >= highGainPolishSegmentCount;
end

function stageTiming = addCandidateTiming(stageTiming, candidate)
% Add exclusive solver/corridor and independent-validation timings.
diagnostics = candidate.SolverDiagnostics;
stageTiming.CorridorConstructionElapsedTime_s = ...
    stageTiming.CorridorConstructionElapsedTime_s + ...
    diagnostics.CorridorConstructionElapsedTime_s;
stageTiming.MotionSolvingElapsedTime_s = ...
    stageTiming.MotionSolvingElapsedTime_s + ...
    diagnostics.MotionSolvingElapsedTime_s;
validation = candidate.Validation;
stageTiming.CollisionCheckingElapsedTime_s = ...
    stageTiming.CollisionCheckingElapsedTime_s + ...
    validation.CollisionCheckingElapsedTime_s;
stageTiming.FinalValidationElapsedTime_s = ...
    stageTiming.FinalValidationElapsedTime_s + max(0, ...
    validation.ElapsedTime_s - validation.CollisionCheckingElapsedTime_s);
end

function repeats = reproducesSolve(candidate, previousSolve, options)
% Compare arrival and clearance so a stalled relinearization is not repaid.
repeats = ~isempty(candidate.time_s) && ...
    matchesWithin(candidate.FinalTime_s, previousSolve.FinalTime_s, ...
    options.ArrivalTimeTolerance_s) && ...
    matchesWithin(candidate.Validation.MinimumClearance_deg, ...
    previousSolve.MinimumClearance_deg, ...
    max(options.CollisionClearanceTolerance_deg, 1e-9));
end

function relativeLengthExcess = coarseMotionLengthExcess(candidate, seed)
% Measure route inflation so the caller can scale one bounded quality pass.
if isempty(candidate.position_deg) || ~isfinite(seed.Length_deg) || ...
        seed.Length_deg <= 0
    relativeLengthExcess = 0;
    return;
end
motionLength_deg = sum(vecnorm(diff( ...
    candidate.position_deg, 1, 1), 2, 2));
relativeLengthExcess = motionLength_deg / seed.Length_deg - 1;
end

function [profile, stageTiming, totalElapsedTime_s, elapsedTime_s] = ...
        runPassThroughTimingProbe( ...
        initialState, goalState, limits, options, seed, sweepCount, ...
        stageTiming, totalElapsedTime_s)
% Run one Ruckig-derived timing probe and centralize elapsed-time accounting.
profile = obstacleAvoidance.planner.solvePassThroughSeedCandidate( ...
    initialState, goalState, limits, options, seed, sweepCount);
elapsedTime_s = profile.SolverDiagnostics.ElapsedTime_s;
stageTiming.MotionSolvingElapsedTime_s = ...
    stageTiming.MotionSolvingElapsedTime_s + elapsedTime_s;
totalElapsedTime_s = totalElapsedTime_s + elapsedTime_s;
end

function hasCluster = seedHasClusteredWaypoints(seed)
% Detect route sections too short to represent independent motion phases.
edgeLength_deg = vecnorm(diff(seed.position_deg, 1, 1), 2, 2);
totalLength_deg = sum(edgeLength_deg);
if numel(edgeLength_deg) < 2 || totalLength_deg <= 0
    hasCluster = false;
    return;
end
% Below one percent of the full route, an interior edge represents a local
% geometry cluster rather than a meaningful duration allocation. This is
% far below one interval of the maintained ten-segment coarse HS3 mesh.
clusterLengthFraction = 0.01;
interiorEdgeLength_deg = edgeLength_deg;
hasCluster = min(interiorEdgeLength_deg) <= ...
    clusterLengthFraction * totalLength_deg;
end

function seed = spatialTimingSeed(seed)
% Remove waits and distribute a timed topology by geometric arc length.
edgeLength_deg = vecnorm(diff(seed.position_deg, 1, 1), 2, 2);
retainedPoint = [true; edgeLength_deg > 1e-12];
seed.position_deg = seed.position_deg(retainedPoint, :);
cumulativeLength_deg = [0; cumsum(vecnorm( ...
    diff(seed.position_deg, 1, 1), 2, 2))];
seed.tau = cumulativeLength_deg / cumulativeLength_deg(end);
end

function matches = matchesWithin(current, previous, tolerance)
% Treat equal nonfinite evidence as unchanged without comparing NaN to NaN.
matches = (isinf(current) && isequal(current, previous)) || abs(current - previous) <= tolerance;
end

function [polishedCandidate, stageTiming] = polishEarliestMotionShape( ...
        candidate, seed, obstacles, initialState, goalState, limits, ...
        options, stageTiming)
% Hold an independently valid earliest arrival fixed and minimize integrated
% squared jerk on the same input-derived topology. Accepting this candidate is
% owned by the caller, which also requires a strictly shorter valid motion.
polishGoalState = goalState;
polishGoalState.time_s = candidate.FinalTime_s;
polishOptions = options;
polishOptions.GoalTimeMode = "fixedArrival";
polishOptions.MaximumSolverTime_s = ...
    hs3Engine.defaultOptions().MaximumSolveTime;
polishSeed = seed;
polishSeed.EstimatedDuration_s = ...
    candidate.FinalTime_s - initialState.time_s;
polishedCandidate = obstacleAvoidance.planner.solveRouteCandidate( ...
    obstacles, initialState, polishGoalState, limits, ...
    polishOptions, polishSeed);
polishedCandidate.Validation = validateCandidate( ...
    polishedCandidate, obstacles, initialState, polishGoalState, ...
    limits, polishOptions);
stageTiming = addCandidateTiming(stageTiming, polishedCandidate);
if ~polishedCandidate.Validation.Passed || ~matchesWithin( ...
        polishedCandidate.FinalTime_s, candidate.FinalTime_s, ...
        options.ArrivalTimeTolerance_s)
    polishedCandidate = candidate;
end
end

function seed = seedFromCandidate( ...
        candidate, originalSeed, targetFinalTime_s)
% Reassociate frozen corridors around HS3 motion without changing topology.
seed = originalSeed;
isTimedSeed = any(originalSeed.Source == ["directWait", "timeExpandedVisibilityGraph"]);
if nargin >= 3 && targetFinalTime_s < candidate.FinalTime_s && ~isTimedSeed
    return;
end
if nargin < 3 || targetFinalTime_s >= candidate.FinalTime_s
    sampleTau = (candidate.time_s - candidate.time_s(1)) / ...
        candidate.MotionDuration_s;
    [sampleTau, retainedIndex] = unique(sampleTau, "stable");
    seed.tau = candidate.ControlTau;
    seed.position_deg = interp1(sampleTau, ...
        candidate.position_deg(retainedIndex, :), seed.tau, "linear");
    seed.EstimatedDuration_s = candidate.MotionDuration_s;
    return;
end

% Shortening a timed motion must preserve absolute event timing. Rescaling
% its normalized wait would move an already validated crossing earlier.
controlTime_s = candidate.time_s(1) + ...
    candidate.ControlTau * candidate.MotionDuration_s;
retainedControl = controlTime_s < targetFinalTime_s;
retainedTime_s = controlTime_s(retainedControl);
retainedPosition_deg = interp1(candidate.time_s, ...
    candidate.position_deg, retainedTime_s, "linear");
trialDuration_s = targetFinalTime_s - candidate.time_s(1);
seed.tau = [(retainedTime_s - candidate.time_s(1)) / ...
    trialDuration_s; 1];
seed.position_deg = [retainedPosition_deg; originalSeed.position_deg(end, :)];
seed.EstimatedDuration_s = trialDuration_s;
end

function seedIndex = equivalentCompletedTimedSeed( ...
        seed, seeds, isTimedTopology, summaries, directLength_deg, ...
        lengthTolerance_deg, bestFinalTime_s, arrivalTolerance_s)
% Find a prior timed HS3 result that exhausted the same minimum-length route.
seedIndex = 0;
seedLengthMatchesFloor = abs(seed.Length_deg - directLength_deg) <= ...
    lengthTolerance_deg;
if ~seedLengthMatchesFloor
    return;
end
candidateIndex = find(isTimedTopology & ...
    [summaries.ValidationPassed].' & ...
    [summaries.TimedArrivalSearchConverged].');
for timedIndex = reshape(candidateIndex, 1, [])
    isCurrentBestArrival = abs( ...
        summaries(timedIndex).ArrivalTime_s - bestFinalTime_s) <= ...
        arrivalTolerance_s;
    summaryLengthMatchesFloor = abs( ...
        summaries(timedIndex).MotionLength_deg - directLength_deg) <= ...
        lengthTolerance_deg;
    if isCurrentBestArrival && summaryLengthMatchesFloor && ...
            seedSpatialGeometryMatches( ...
            seed, seeds(timedIndex), lengthTolerance_deg)
        seedIndex = timedIndex;
        return;
    end
end
end

function matches = seedSpatialGeometryMatches( ...
        firstSeed, secondSeed, positionTolerance_deg)
% Compare ordered spatial curves independently of waits and time parameterization.
sampleFraction = linspace(0, 1, 101).';
firstPosition_deg = sampleSeedByArcLength(firstSeed, sampleFraction, ...
    positionTolerance_deg);
secondPosition_deg = sampleSeedByArcLength(secondSeed, sampleFraction, ...
    positionTolerance_deg);
matches = max(vecnorm( ...
    firstPosition_deg - secondPosition_deg, 2, 2)) <= ...
    positionTolerance_deg;
end

function sampledPosition_deg = sampleSeedByArcLength( ...
        seed, sampleFraction, positionTolerance_deg)
% Remove waits, then sample the ordered spatial curve by cumulative length.
position_deg = seed.position_deg;
retainedPosition = [true; vecnorm(diff(position_deg, 1, 1), 2, 2) > ...
    positionTolerance_deg];
position_deg = position_deg(retainedPosition, :);
if size(position_deg, 1) == 1
    sampledPosition_deg = repmat(position_deg, numel(sampleFraction), 1);
    return;
end
cumulativeLength_deg = [0; cumsum(vecnorm( ...
    diff(position_deg, 1, 1), 2, 2))];
arcFraction = cumulativeLength_deg / cumulativeLength_deg(end);
sampledPosition_deg = interp1( ...
    arcFraction, position_deg, sampleFraction, "linear");
end

function summary = candidateSummary(candidate, relinearizationCount, ...
        meshRefinementCount, shapePolishAttempted, shapePolishAccepted, ...
        prePolishMotionLength_deg, template)
% Retain full failure evidence without duplicating trajectory arrays.
summary = template;
summary.SeedIndex = candidate.SeedIndex;
summary.SeedSource = candidate.SeedSource;
summary.OptimizerFeasible = candidate.OptimizerFeasible;
summary.ValidationPassed = candidate.Validation.Passed;
summary.CollisionFree = candidate.Validation.CollisionFree;
summary.CollisionResolved = candidate.Validation.CollisionResolved;
summary.MinimumClearance_deg = candidate.Validation.MinimumClearance_deg;
summary.UnresolvedIntervalCount = candidate.Validation.UnresolvedIntervalCount;
summary.ArrivalTime_s = candidate.FinalTime_s;
summary.MotionDuration_s = candidate.MotionDuration_s;
summary.MotionLength_deg = candidate.MotionLength_deg;
summary.IntegratedSquaredJerk_deg2_s5 = ...
    candidate.IntegratedSquaredJerk_deg2_s5;
summary.MaximumConstraintViolation = candidate.MaximumConstraintViolation;
summary.RelinearizationCount = relinearizationCount;
summary.MeshRefinementPassCount = meshRefinementCount;
summary.ShapePolishAttempted = shapePolishAttempted;
summary.ShapePolishAccepted = shapePolishAccepted;
summary.PrePolishMotionLength_deg = prePolishMotionLength_deg;
summary.Hs3Attempted = true;
summary.Hs3OptimizerFeasible = candidate.OptimizerFeasible;
summary.Hs3ValidationPassed = candidate.Validation.Passed;
summary.Hs3TerminationReason = candidate.TerminationReason;
summary.Hs3SolverDiagnostics = candidate.SolverDiagnostics;
summary.TerminationReason = candidate.TerminationReason;
summary.Message = candidate.Message + " " + candidate.Validation.Message;
summary.SolverDiagnostics = candidate.SolverDiagnostics;
end

function index = bestPartialSeed(summaries)
% Prefer resolved collision evidence, then NLP residual and clearance.
violation = [summaries.MaximumConstraintViolation].';
violation(~isfinite(violation)) = Inf;
collisionRank = 2 * ~[summaries.CollisionResolved].' + ...
    ~[summaries.CollisionFree].';
clearance = [summaries.MinimumClearance_deg].';
clearance(~isfinite(clearance)) = -Inf;
[~, order] = sortrows([collisionRank, violation, -clearance], [1 2 3]);
if isempty(order) || isinf(violation(order(1)))
    index = 0;
else
    index = order(1);
end
end

function selectedIndex = selectValidatedCandidate( ...
        summaries, validatedIndices, goalTimeMode, arrivalTolerance_s)
% Rank fixed arrivals by motion length and free arrivals by time.
if goalTimeMode == "fixedArrival"
    motionLength_deg = ...
        [summaries(validatedIndices).MotionLength_deg].';
    lengthTolerance_deg = max(1e-10, ...
        1e-10 * max(1, min(motionLength_deg)));
    lengthEquivalent = validatedIndices( ...
        motionLength_deg <= min(motionLength_deg) + lengthTolerance_deg);
    jerk = ...
        [summaries(lengthEquivalent).IntegratedSquaredJerk_deg2_s5].';
    selectedIndex = min( ...
        lengthEquivalent(jerk <= min(jerk) + 1e-12));
    return;
end
arrival = [summaries(validatedIndices).ArrivalTime_s].';
timeEquivalent = validatedIndices( ...
    arrival <= min(arrival) + arrivalTolerance_s);
jerk = [summaries(timeEquivalent).IntegratedSquaredJerk_deg2_s5].';
selectedIndex = min(timeEquivalent(jerk <= min(jerk) + 1e-12));
end

function improves = candidateImproves( ...
        candidate, incumbent, goalTimeMode)
% Compare independently valid candidates using the public time policy.
if goalTimeMode == "fixedArrival"
    lengthTolerance_deg = max(1e-10, ...
        1e-10 * max(1, incumbent.MotionLength_deg));
    lengthImproves = candidate.MotionLength_deg < ...
        incumbent.MotionLength_deg - lengthTolerance_deg;
    lengthEquivalent = abs(candidate.MotionLength_deg - ...
        incumbent.MotionLength_deg) <= lengthTolerance_deg;
    jerkImproves = candidate.IntegratedSquaredJerk_deg2_s5 < ...
        incumbent.IntegratedSquaredJerk_deg2_s5 - 1e-12;
    improves = lengthImproves || (lengthEquivalent && jerkImproves);
    return;
end
% Preserve the established earliest-arrival refinement rule exactly.
improves = candidate.FinalTime_s < incumbent.FinalTime_s;
end
