function candidate = solvePassThroughSeedCandidate( ...
        initialState, goalState, limits, options, seed, refinementSweepCount)
%% Section 0: Header & Readme
% SYNTAX
%   candidate = obstacleAvoidance.planner.solvePassThroughSeedCandidate( ...
%       initialState, goalState, limits, options, seed)
%   candidate = obstacleAvoidance.planner.solvePassThroughSeedCandidate( ...
%       initialState, goalState, limits, options, seed, refinementSweepCount)
%**************************************************************************
% PURPOSE
%   - Create a non-stopping multi-waypoint motion by optimizing shared
%     waypoint velocities and accelerations between exact Ruckig sections.
%   - Adapt the MIT-licensed rsruckig local waypoint search documented in
%     citation.md; the implementation here is native MATLAB.
%**************************************************************************
% INPUTS
%   - initialState, goalState (normalized scalar state structs)
%       Boundary position, velocity, and acceleration use Az/El row vectors.
%   - limits (normalized scalar limits struct)
%       Positive velocity, acceleration, and jerk limits use Az/El rows.
%   - options (resolved scalar planner options)
%       SampleTime_s and ConstraintTolerance control output and acceptance.
%   - seed (scalar topology-seed struct)
%       position_deg is N-by-2 and includes both request endpoints.
%   - refinementSweepCount (integer scalar, optional; default 4)
%       Bounded rsruckig-style waypoint-state refinement passes.
%**************************************************************************
% OUTPUTS
%   - candidate (scalar struct)
%       Stable motion record. OptimizerFeasible is true only when the exact
%       profile also passes the planner-owned static corridor certificate.
%**************************************************************************
% UNITS
%   - Position is degrees; time is seconds; derivatives use deg/s powers.
%**************************************************************************

%% Section 1: Estimate Pass-Through Waypoint States

position_deg = double(seed.position_deg);
if nargin < 6 || isempty(refinementSweepCount)
    refinementSweepCount = 4;
end
validateattributes(refinementSweepCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'nonnegative', '<=', 4});
pointCount = size(position_deg, 1);
edgeCount = pointCount - 1;
candidate = createEmptyCandidate(seed);
if edgeCount < 1
    candidate.Message = "The topology seed contains no route edge.";
    candidate.TerminationReason = "emptySeed";
    return;
end
velocity_deg_s = zeros(pointCount, 2);
acceleration_deg_s2 = zeros(pointCount, 2);
velocity_deg_s(1, :) = initialState.velocity_deg_s;
acceleration_deg_s2(1, :) = initialState.acceleration_deg_s2;
velocity_deg_s(end, :) = goalState.velocity_deg_s;
acceleration_deg_s2(end, :) = goalState.acceleration_deg_s2;
heuristicSafetyFactor = 0.9;
for pointIndex = 2:pointCount - 1
    previousDelta_deg = position_deg(pointIndex, :) - ...
        position_deg(pointIndex - 1, :);
    nextDelta_deg = position_deg(pointIndex + 1, :) - ...
        position_deg(pointIndex, :);
    monotoneAxis = previousDelta_deg .* nextDelta_deg > 0;
    direction = sign(nextDelta_deg);
    reachableVelocity_deg_s = sqrt(2 * limits.maxAcceleration_deg_s2 .* ...
        abs(previousDelta_deg));
    stoppableVelocity_deg_s = sqrt(2 * limits.maxAcceleration_deg_s2 .* ...
        abs(nextDelta_deg));
    previousJerkVelocity_deg_s = nthroot( ...
        limits.maxJerk_deg_s3 .* previousDelta_deg.^2, 3);
    nextJerkVelocity_deg_s = nthroot( ...
        limits.maxJerk_deg_s3 .* nextDelta_deg.^2, 3);
    velocityMagnitude_deg_s = heuristicSafetyFactor * min([ ...
        limits.maxVelocity_deg_s; reachableVelocity_deg_s; ...
        stoppableVelocity_deg_s; previousJerkVelocity_deg_s; ...
        nextJerkVelocity_deg_s], [], 1);
    velocity_deg_s(pointIndex, monotoneAxis) = ...
        direction(monotoneAxis) .* velocityMagnitude_deg_s(monotoneAxis);
end

%% Section 2: Create And Degrade The Initial Feasible Chain

engineLimits = struct( ...
    "maximumVelocity", limits.maxVelocity_deg_s, ...
    "maximumAcceleration", limits.maxAcceleration_deg_s2, ...
    "maximumJerk", limits.maxJerk_deg_s3);
engineOptions = struct( ...
    "TimeMode", "earliestArrival", ...
    "SampleTime", options.SampleTime_s, ...
    "ConstraintTolerance", options.ConstraintTolerance, ...
    "ArrivalTimeTolerance", options.ArrivalTimeTolerance_s, ...
    "Verbose", false);
solveTimer = tic;
solveCount = 0;
sectionDuration_s = NaN(edgeCount, 1);
heuristicVelocity_deg_s = velocity_deg_s;
chainScales = [1, 0.5, 0.25, 0];
chainIsFeasible = false;
selectedChainScale = NaN;
for scaleIndex = 1:numel(chainScales)
    velocity_deg_s(2:end - 1, :) = chainScales(scaleIndex) * ...
        heuristicVelocity_deg_s(2:end - 1, :);
    chainIsFeasible = true;
    for edgeIndex = 1:edgeCount
        sectionResult = solveSection(edgeIndex, 0, position_deg, ...
            velocity_deg_s, acceleration_deg_s2, goalState, ...
            engineLimits, engineOptions);
        solveCount = solveCount + 1;
        if ~sectionResult.Success
            chainIsFeasible = false;
            break;
        end
        sectionDuration_s(edgeIndex) = sectionResult.FinalTime;
    end
    if chainIsFeasible
        selectedChainScale = chainScales(scaleIndex);
        break;
    end
end
if ~chainIsFeasible
    candidate.Message = "The pass-through Ruckig chain remained unsupported " + ...
        "after all interior waypoint velocities were degraded to zero. " + ...
        sectionResult.Message;
    candidate.TerminationReason = sectionResult.TerminationReason;
    candidate.SolverDiagnostics.ElapsedTime_s = toc(solveTimer);
    candidate.SolverDiagnostics.RuckigSolveCount = solveCount;
    return;
end
initialSectionDuration_s = sectionDuration_s;

%% Section 3: Refine Shared Waypoint States

velocityScales = [0.5, 0.8, 0.95, 1.1, 1.25];
accelerationScales = [0, 0.5, 1];
additiveSteps = [0.2, 0.08, 0.03, 0.01];
searchClassification = ...
    obstacleAvoidance.planner.classifyPassThroughSearch( ...
    position_deg, options.ConstraintTolerance);
activeAxisIndex = searchClassification.ActiveAxisIndex;
useScalarAxisSearch = ...
    searchClassification.Mode == "oneDimensionalScalar";
vectorCandidateCount = numel(velocityScales) + 1;
candidateAxisGroups = {[1 2]};
candidateCounts = vectorCandidateCount;
if useScalarAxisSearch
    scalarCandidateCount = vectorCandidateCount + ...
        numel(accelerationScales) + 4;
    candidateAxisGroups = [candidateAxisGroups, ...
        num2cell(activeAxisIndex)];
    candidateCounts = [candidateCounts, repmat( ...
        scalarCandidateCount, 1, numel(activeAxisIndex))];
end
completedSweepCount = 0;
for sweepIndex = 1:refinementSweepCount
    for pointIndex = 2:pointCount - 1
        pairDuration_s = max(1e-9, ...
            sectionDuration_s(pointIndex - 1) + ...
            sectionDuration_s(pointIndex));
        % Ruckig synchronizes both axes to one section duration. Coupled
        % waypoint probes preserve that invariant and avoid re-solving both
        % adjacent sections for scalar-axis states that immediately become a
        % different synchronized vector problem.
        for groupIndex = 1:numel(candidateAxisGroups)
            for candidateIndex = 1:candidateCounts(groupIndex)
                trialVelocity_deg_s = velocity_deg_s(pointIndex, :);
                trialAcceleration_deg_s2 = acceleration_deg_s2(pointIndex, :);
                for axisIndex = candidateAxisGroups{groupIndex}
                    [trialVelocity_deg_s(axisIndex), ...
                        trialAcceleration_deg_s2(axisIndex)] = ...
                        candidateState( ...
                        candidateIndex, trialVelocity_deg_s(axisIndex), ...
                        trialAcceleration_deg_s2(axisIndex), position_deg, ...
                        pointIndex, axisIndex, pairDuration_s, limits, ...
                        velocityScales, accelerationScales, ...
                        additiveSteps(sweepIndex));
                end
                [accepted, sectionDuration_s, solveCount] = ...
                    tryWaypointState( ...
                    pointIndex, trialVelocity_deg_s, ...
                    trialAcceleration_deg_s2, position_deg, velocity_deg_s, ...
                    acceleration_deg_s2, sectionDuration_s, goalState, ...
                    engineLimits, engineOptions, solveCount);
                if accepted
                    velocity_deg_s(pointIndex, :) = trialVelocity_deg_s;
                    acceleration_deg_s2(pointIndex, :) = ...
                        trialAcceleration_deg_s2;
                end
            end
        end
    end
    completedSweepCount = sweepIndex;
end

%% Section 4: Assemble And Certify The Exact Motion

sectionCorridors = cell(edgeCount, 1);
currentTime_s = initialState.time_s;
segmentOffset = 0;
enginePolynomial = struct();
time_s = zeros(0, 1);
sampledPosition_deg = zeros(0, 2);
sampledVelocity_deg_s = zeros(0, 2);
sampledAcceleration_deg_s2 = zeros(0, 2);
jerk_deg_s3 = zeros(0, 2);
polynomialFieldNames = ["SegmentStartTime", "SegmentDuration", ...
    "positionPower", "velocityPower", "accelerationPower", "jerkPower"];
for edgeIndex = 1:edgeCount
    sectionResult = solveSection(edgeIndex, currentTime_s, ...
        position_deg, velocity_deg_s, acceleration_deg_s2, goalState, ...
        engineLimits, engineOptions);
    solveCount = solveCount + 1;
    if ~sectionResult.Success
        candidate.Message = "Final pass-through Ruckig section " + ...
            edgeIndex + " failed: " + sectionResult.Message;
        candidate.TerminationReason = sectionResult.TerminationReason;
        candidate.SolverDiagnostics.ElapsedTime_s = toc(solveTimer);
        candidate.SolverDiagnostics.RuckigSolveCount = solveCount;
        return;
    end
    edgeSeed = seed;
    edgeSeed.position_deg = position_deg(edgeIndex:edgeIndex + 1, :);
    edgeSeed.tau = [0; 1];
    corridor = obstacleAvoidance.search.createSeedCorridor( ...
        edgeSeed, sectionResult.Polynomial.SegmentCount);
    for recordIndex = 1:numel(corridor)
        corridor(recordIndex).Clearance_deg = 0;
        corridor(recordIndex).SegmentIndex = ...
            corridor(recordIndex).SegmentIndex + segmentOffset;
    end
    sectionCorridors{edgeIndex} = corridor;
    segmentOffset = segmentOffset + ...
        sectionResult.Polynomial.SegmentCount;
    sectionPolynomial = sectionResult.Polynomial;
    if edgeIndex == 1
        enginePolynomial = sectionPolynomial;
    else
        for fieldName = polynomialFieldNames
            enginePolynomial.(fieldName) = cat(1, ...
                enginePolynomial.(fieldName), sectionPolynomial.(fieldName));
        end
    end
    retainedIndex = 1:numel(sectionResult.time);
    if edgeIndex < edgeCount
        retainedIndex = retainedIndex(1:end - 1);
    end
    time_s = [time_s; sectionResult.time(retainedIndex)]; %#ok<AGROW>
    sampledPosition_deg = [sampledPosition_deg; ...
        sectionResult.position(retainedIndex, :)]; %#ok<AGROW>
    sampledVelocity_deg_s = [sampledVelocity_deg_s; ...
        sectionResult.velocity(retainedIndex, :)]; %#ok<AGROW>
    sampledAcceleration_deg_s2 = [sampledAcceleration_deg_s2; ...
        sectionResult.acceleration(retainedIndex, :)]; %#ok<AGROW>
    jerk_deg_s3 = [jerk_deg_s3; ...
        sectionResult.jerk(retainedIndex, :)]; %#ok<AGROW>
    currentTime_s = sectionResult.FinalTime;
end
enginePolynomial.SegmentCount = numel(enginePolynomial.SegmentStartTime);
enginePolynomial.FinalTime = currentTime_s;
enginePolynomial.TerminalState = sectionPolynomial.TerminalState;
terminalState = enginePolynomial.TerminalState;
polynomial = struct( ...
    "SegmentCount", enginePolynomial.SegmentCount, ...
    "SegmentStartTime_s", enginePolynomial.SegmentStartTime, ...
    "SegmentDuration_s", enginePolynomial.SegmentDuration, ...
    "FinalTime_s", enginePolynomial.FinalTime, ...
    "positionPower_deg", enginePolynomial.positionPower, ...
    "velocityPower_deg_s", enginePolynomial.velocityPower, ...
    "accelerationPower_deg_s2", enginePolynomial.accelerationPower, ...
    "jerkPower_deg_s3", enginePolynomial.jerkPower, ...
    "TerminalState", struct( ...
        "position_deg", terminalState.position, ...
        "velocity_deg_s", terminalState.velocity, ...
        "acceleration_deg_s2", terminalState.acceleration));
seedCorridor = vertcat(sectionCorridors{:});
inequality_deg = obstacleAvoidance.search.seedCorridorInequality( ...
    polynomial, seedCorridor);
maximumCorridorViolation_deg = max([0; inequality_deg]);
corridorCertified = ~isempty(seedCorridor) && ...
    maximumCorridorViolation_deg <= options.ConstraintTolerance;
candidate.OptimizerFeasible = corridorCertified;
if corridorCertified
    candidate.Message = ...
        "A corridor-certified non-stopping Ruckig motion was found.";
    candidate.TerminationReason = "optimizerFeasible";
elseif isempty(seedCorridor)
    candidate.Message = "The non-stopping Ruckig motion is dynamically " + ...
        "feasible, but this seed provides no standalone corridor " + ...
        "certificate. HS3 repair and independent obstacle validation are " + ...
        "required before acceptance.";
    candidate.TerminationReason = "corridorUnavailable";
else
    candidate.Message = "The non-stopping Ruckig motion is dynamically " + ...
        "feasible but violates its static seed corridor by " + ...
        maximumCorridorViolation_deg + " deg.";
    candidate.TerminationReason = "pathConstraintViolation";
end
candidate.FinalTime_s = time_s(end);
candidate.MotionDuration_s = time_s(end) - initialState.time_s;
candidate.MotionLength_deg = sum(vecnorm(diff( ...
    sampledPosition_deg, 1, 1), 2, 2));
candidate.time_s = time_s;
candidate.position_deg = sampledPosition_deg;
candidate.velocity_deg_s = sampledVelocity_deg_s;
candidate.acceleration_deg_s2 = sampledAcceleration_deg_s2;
candidate.jerk_deg_s3 = jerk_deg_s3;
candidate.Polynomial = polynomial;
candidate.SeedCorridor = seedCorridor;
candidate.WaypointVelocity_deg_s = velocity_deg_s;
candidate.WaypointAcceleration_deg_s2 = acceleration_deg_s2;
candidate.InitialSectionDuration_s = initialSectionDuration_s;
candidate.SectionDuration_s = sectionDuration_s;
candidate.SectionTimeSaving_s = ...
    initialSectionDuration_s - sectionDuration_s;
candidate.TimeSensitiveEdgeIndex = find( ...
    candidate.SectionTimeSaving_s > 1e-9);
candidate.MaximumCorridorViolation_deg = maximumCorridorViolation_deg;
candidate.SolverDiagnostics.ElapsedTime_s = toc(solveTimer);
candidate.SolverDiagnostics.SectionCount = edgeCount;
candidate.SolverDiagnostics.RuckigSolveCount = solveCount;
candidate.SolverDiagnostics.RefinementSweepCount = completedSweepCount;
candidate.SolverDiagnostics.InitialWaypointVelocityScale = selectedChainScale;
candidate.SolverDiagnostics.WaypointStateSearchMode = ...
    searchClassification.Mode;
end

%% Section 5: Local Functions

function result = solveSection(edgeIndex, startTime_s, position_deg, ...
        velocity_deg_s, acceleration_deg_s2, goalState, limits, options)
% Solve one synchronized section for the supplied shared boundary states.
initialState = struct( ...
    "time", startTime_s, ...
    "position", position_deg(edgeIndex, :), ...
    "velocity", velocity_deg_s(edgeIndex, :), ...
    "acceleration", acceleration_deg_s2(edgeIndex, :));
terminalState = struct( ...
    "position", position_deg(edgeIndex + 1, :), ...
    "velocity", velocity_deg_s(edgeIndex + 1, :), ...
    "acceleration", acceleration_deg_s2(edgeIndex + 1, :), ...
    "maximumTime", goalState.time_s);
result = planTrajRuckig(initialState, terminalState, limits, options);
end

function [accepted, durations_s, solveCount] = tryWaypointState( ...
        pointIndex, trialVelocity_deg_s, trialAcceleration_deg_s2, ...
        position_deg, velocity_deg_s, acceleration_deg_s2, durations_s, ...
        goalState, limits, options, solveCount)
% Accept a waypoint state only when both adjacent exact solves reduce time.
trialVelocity = velocity_deg_s;
trialAcceleration = acceleration_deg_s2;
trialVelocity(pointIndex, :) = trialVelocity_deg_s;
trialAcceleration(pointIndex, :) = trialAcceleration_deg_s2;
previousResult = solveSection(pointIndex - 1, 0, position_deg, ...
    trialVelocity, trialAcceleration, goalState, limits, options);
solveCount = solveCount + 1;
accepted = false;
if ~previousResult.Success
    return;
end
nextResult = solveSection(pointIndex, 0, position_deg, ...
    trialVelocity, trialAcceleration, goalState, limits, options);
solveCount = solveCount + 1;
if ~nextResult.Success
    return;
end
baseDuration_s = durations_s(pointIndex - 1) + durations_s(pointIndex);
trialDuration_s = previousResult.FinalTime + nextResult.FinalTime;
if trialDuration_s < baseDuration_s - 1e-9
    durations_s(pointIndex - 1) = previousResult.FinalTime;
    durations_s(pointIndex) = nextResult.FinalTime;
    accepted = true;
end
end

function [velocity_deg_s, acceleration_deg_s2] = candidateState( ...
        candidateIndex, currentVelocity_deg_s, currentAcceleration_deg_s2, ...
        position_deg, pointIndex, axisIndex, pairDuration_s, limits, ...
        velocityScales, accelerationScales, additiveStep)
% Reproduce the bounded rsruckig waypoint pattern-search candidate ladder.
maximumVelocity_deg_s = limits.maxVelocity_deg_s(axisIndex);
maximumAcceleration_deg_s2 = limits.maxAcceleration_deg_s2(axisIndex);
maximumJerk_deg_s3 = limits.maxJerk_deg_s3(axisIndex);
previousDelta_deg = position_deg(pointIndex, axisIndex) - ...
    position_deg(pointIndex - 1, axisIndex);
nextDelta_deg = position_deg(pointIndex + 1, axisIndex) - ...
    position_deg(pointIndex, axisIndex);
direction = 0;
if previousDelta_deg * nextDelta_deg > 0
    direction = sign(nextDelta_deg);
end
velocityScaleCount = numel(velocityScales);
accelerationScaleCount = numel(accelerationScales);
velocity_deg_s = currentVelocity_deg_s;
acceleration_deg_s2 = currentAcceleration_deg_s2;
if candidateIndex <= velocityScaleCount
    velocity_deg_s = currentVelocity_deg_s * ...
        velocityScales(candidateIndex);
elseif candidateIndex == velocityScaleCount + 1
    velocity_deg_s = direction * maximumVelocity_deg_s;
elseif candidateIndex <= velocityScaleCount + 1 + accelerationScaleCount
    scaleIndex = candidateIndex - velocityScaleCount - 1;
    secondDifference_deg = position_deg(pointIndex + 1, axisIndex) - ...
        2 * position_deg(pointIndex, axisIndex) + ...
        position_deg(pointIndex - 1, axisIndex);
    acceleration_deg_s2 = accelerationScales(scaleIndex) * 4 * ...
        secondDifference_deg / pairDuration_s^2;
else
    probeIndex = candidateIndex - velocityScaleCount - 1 - ...
        accelerationScaleCount;
    if probeIndex <= 2
        velocity_deg_s = currentVelocity_deg_s + ...
            (3 - 2 * probeIndex) * additiveStep * maximumVelocity_deg_s;
    else
        acceleration_deg_s2 = currentAcceleration_deg_s2 + ...
            (7 - 2 * probeIndex) * additiveStep * ...
            maximumAcceleration_deg_s2;
    end
end
velocity_deg_s = min(maximumVelocity_deg_s, ...
    max(-maximumVelocity_deg_s, velocity_deg_s));
acceleration_deg_s2 = min(maximumAcceleration_deg_s2, ...
    max(-maximumAcceleration_deg_s2, acceleration_deg_s2));
guard = 0.999;
if acceleration_deg_s2 ~= 0
    accelerationDirection = sign(acceleration_deg_s2);
    headroom_deg_s = max(0, maximumVelocity_deg_s - ...
        accelerationDirection * velocity_deg_s);
    acceleration_deg_s2 = accelerationDirection * min( ...
        abs(acceleration_deg_s2), guard * sqrt( ...
        2 * maximumJerk_deg_s3 * headroom_deg_s));
end
end

function candidate = createEmptyCandidate(seed)
% Return the same field topology on every expected outcome.
candidate = struct( ...
    "OptimizerFeasible", false, ...
    "Message", "The pass-through seed motion was not solved.", ...
    "TerminationReason", "notRun", ...
    "SeedIndex", seed.Index, ...
    "SeedSource", seed.Source, ...
    "FinalTime_s", NaN, ...
    "MotionDuration_s", NaN, ...
    "MotionLength_deg", NaN, ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2), ...
    "Polynomial", struct(), ...
    "SeedCorridorBoundary_deg", seed.CorridorBoundary_deg, ...
    "SeedCorridor", struct([]), ...
    "WaypointVelocity_deg_s", zeros(0, 2), ...
    "WaypointAcceleration_deg_s2", zeros(0, 2), ...
    "InitialSectionDuration_s", zeros(0, 1), ...
    "SectionDuration_s", zeros(0, 1), ...
    "SectionTimeSaving_s", zeros(0, 1), ...
    "TimeSensitiveEdgeIndex", zeros(0, 1), ...
    "MaximumCorridorViolation_deg", Inf, ...
    "SolverDiagnostics", struct( ...
        "ElapsedTime_s", 0, ...
        "SectionCount", 0, ...
        "RuckigSolveCount", 0, ...
        "RefinementSweepCount", 0, ...
        "InitialWaypointVelocityScale", NaN, ...
        "WaypointStateSearchMode", "notRun"));
end
