function candidate = solveRouteCandidate( ...
        obstacles, initialState, goalState, limits, options, seed)
%% Section 0: Header & Readme
% SYNTAX
%   candidate = obstacleAvoidance.planner.solveRouteCandidate( ...
%       obstacles, initialState, ...
%       goalState, limits, options, seed)
%**************************************************************************
% PURPOSE
%   - Solve and reconstruct one separated third-order Hermite-Simpson motion.
%**************************************************************************
% INPUTS
%   - obstacles (canonical protected obstacle struct array)
%   - initialState, goalState (normalized scalar state structs)
%   - limits (normalized scalar limits struct)
%   - options (resolved planner options)
%   - seed (scalar topology-seed struct)
%       position_deg is N-by-2 and tau is a strictly increasing N-vector.
%**************************************************************************
% OUTPUTS
%   - candidate (scalar struct)
%       Solver outcome, polynomial trajectory, samples, and diagnostics.
%**************************************************************************
% UNITS
%   - Position is degrees; derivatives use deg/s, deg/s^2, and deg/s^3.
%**************************************************************************
%% Section 1: Build The Decision Layout And Initial Guess

% HS3 represents each axis by jerk values at knot and midpoint controls.
% Integrating those controls from the initial state determines position,
% velocity, and acceleration. Earliest-arrival mode appends final time to the
% decision vector; fixed-arrival mode leaves duration constant.
solverTimer = tic;
corridorConstructionElapsedTime_s = 0;
maximumSolverTime_s = options.MaximumSolverTime_s;
if isempty(obstacles) && ~isstruct(obstacles)
    obstacles = obstacleAvoidance.obstacles.combineObstacles(obstacles);
end
obstacles = obstacleAvoidance.obstacles.prepareDynamic(obstacles);
segmentCount = options.CollocationSegmentCount;
segmentBreakTau = resolveSegmentBreakTau(seed, segmentCount);
collinearityDirection = zeros(0, 2);
if isfield(seed, "CollinearityDirection")
    collinearityDirection = seed.CollinearityDirection;
end
if ~isfield(seed, "CorridorBoundary_deg")
    seed.CorridorBoundary_deg = zeros(0, 2);
end
controlCount = 2 * segmentCount + 1;
isEarliestArrival = options.GoalTimeMode == "earliestArrival";
constraintRepresentations = ["linearFixedTime", "nonlinearTimeDecision"];
constraintRepresentation = constraintRepresentations(1 + isEarliestArrival);
startTime_s = initialState.time_s;
latestFinalTime_s = goalState.time_s;
minimumDuration_s = durationLowerBound(initialState, goalState, limits, latestFinalTime_s);
isTimedSeed = any(seed.Source == ["directWait", "timeExpandedVisibilityGraph"]);
minimumFinalTime_s = startTime_s + minimumDuration_s;
if isEarliestArrival && isfield(goalState, "targetTime_s") && ~isempty(goalState.targetTime_s)
    minimumFinalTime_s = max(minimumFinalTime_s, goalState.targetTime_s(1));
end
candidate = createEmptyCandidate(seed, segmentCount);
if maximumSolverTime_s <= 0
    candidate.Message = "HS3 reached its solver time limit before setup.";
    candidate.TerminationReason = "solverTimeLimit";
    candidate.SolverDiagnostics = ...
        obstacleAvoidance.planner.createEmptySolverDiagnostics( ...
        candidate.SolverDiagnostics, toc(solverTimer), ...
        corridorConstructionElapsedTime_s);
    return;
end
if minimumFinalTime_s > latestFinalTime_s + options.ConstraintTolerance
    % Even the optimistic lower bound misses the allowed arrival window, so
    % no nonlinear iterate can make this seed feasible.
    candidate.Message = "The goal time is below a physical duration bound.";
    candidate.TerminationReason = "timeWindowInfeasible";
    candidate.SolverDiagnostics = ...
        obstacleAvoidance.planner.createEmptySolverDiagnostics( ...
        candidate.SolverDiagnostics, toc(solverTimer), ...
        corridorConstructionElapsedTime_s);
    return;
end
if isEarliestArrival && isTimedSeed
    finalTimeGuess_s = min(latestFinalTime_s, max( ...
        minimumFinalTime_s, startTime_s + seed.EstimatedDuration_s));
elseif isEarliestArrival
    seedDuration_s = max(minimumDuration_s, seed.EstimatedDuration_s);
    finalTimeGuess_s = min(latestFinalTime_s, ...
        startTime_s + max(1.05 * minimumDuration_s, seedDuration_s));
else
    finalTimeGuess_s = latestFinalTime_s;
end
if isEarliestArrival && hasMotionWarmStart(seed, startTime_s, ...
        minimumFinalTime_s, latestFinalTime_s)
    finalTimeGuess_s = seed.MotionWarmStart.FinalTime_s;
end
controlTau = createControlTau(segmentBreakTau);
[initialJerk_deg_s3, initialJerkLimitRatio] = initialJerkGuess(isEarliestArrival, ...
    initialState, goalState, limits, seed, finalTimeGuess_s, ...
    segmentCount, controlTau, segmentBreakTau);
if isEarliestArrival && ~isTimedSeed && initialJerkLimitRatio > 1
    % Stretch an untimed guess enough to bring initial jerk near the physical
    % limit. The stretched motion is a starting point, not a claimed solution.
    durationScale = initialJerkLimitRatio^(1 / 3);
    durationSafetyFactor = 1.05;
    if isfield(seed, "UsesReducedGeometry") && seed.UsesReducedGeometry
        % Reduced geometry sharpens turns; an unused option must not change timing.
        durationSafetyFactor = 1.5;
    end
    scaledDuration_s = (finalTimeGuess_s - startTime_s) * durationScale * ...
        durationSafetyFactor;
    finalTimeGuess_s = min(latestFinalTime_s, startTime_s + scaledDuration_s);
    [initialJerk_deg_s3, ~] = initialJerkGuess(isEarliestArrival, ...
        initialState, goalState, limits, seed, finalTimeGuess_s, ...
        segmentCount, controlTau, segmentBreakTau);
end
corridorConstructionTimer = tic;
% Detailed boundaries need more checks; independent validation remains final.
corridorCheckCount = corridorChecksPerSegment( ...
    obstacles, startTime_s, finalTimeGuess_s, segmentCount);
corridorTau = createCorridorTau(segmentBreakTau, corridorCheckCount);
eventTau = (vertcat(obstacles.time_s) - startTime_s) / ...
    (finalTimeGuess_s - startTime_s);
eventTau = eventTau(eventTau > 0 & eventTau < 1);
corridorTau = unique([corridorTau; eventTau]);
constraintSeed = seed;
if isfield(seed, "MotionWarmStart") && ...
        ~isempty(seed.MotionWarmStart.time_s)
    warmStartDuration_s = seed.MotionWarmStart.FinalTime_s - startTime_s;
    warmStartTau = (seed.MotionWarmStart.time_s - startTime_s) / ...
        warmStartDuration_s;
    [constraintSeed.tau, retainedWarmStartIndex] = unique( ...
        warmStartTau, "stable");
    constraintSeed.position_deg = ...
        seed.MotionWarmStart.position_deg(retainedWarmStartIndex, :);
    % Use exact prepared obstacles for repair associations. The visibility
    % envelope remains provenance, not a mismatched uniform-time certificate.
    constraintSeed.CorridorBoundary_deg = zeros(0, 2);
end
corridor = createCorridor( ...
    obstacles, constraintSeed, startTime_s, finalTimeGuess_s, segmentCount, ...
    corridorTau, segmentBreakTau, ...
    options.CollisionClearanceTolerance_deg, ...
    ~isEarliestArrival, limits.maxVelocity_deg_s);
corridorTau = unique([corridor.Tau].', "stable");
seedCorridor = obstacleAvoidance.search.createSeedCorridor( ...
    constraintSeed, segmentCount, segmentBreakTau);
constraintLayout = createConstraintLayout( ...
    segmentCount, initialState.time_s, minimumFinalTime_s, ...
    latestFinalTime_s, goalState, obstacles, corridor, segmentBreakTau);
constraintLayout.MonotonicityDirection = monotonicityDirection( ...
    collinearityDirection, initialState, goalState);
corridorConstructionElapsedTime_s = toc(corridorConstructionTimer);
if toc(solverTimer) >= maximumSolverTime_s
    candidate.Message = "HS3 reached its solver time limit during setup.";
    candidate.TerminationReason = "solverTimeLimit";
    candidate.Corridor = corridor;
    candidate.SeedCorridor = seedCorridor;
    candidate.SolverDiagnostics = ...
        obstacleAvoidance.planner.createEmptySolverDiagnostics( ...
        candidate.SolverDiagnostics, toc(solverTimer), ...
        corridorConstructionElapsedTime_s);
    return;
end
decision0 = initialJerk_deg_s3(:);
jerkScale_deg_s3 = repmat(limits.maxJerk_deg_s3, controlCount, 1);
jerkScale_deg_s3 = jerkScale_deg_s3(:);
lowerBound = -jerkScale_deg_s3;
upperBound = jerkScale_deg_s3;
typicalDecision = max(jerkScale_deg_s3, 1e-3);
if isEarliestArrival
    decision0(end + 1, 1) = finalTimeGuess_s;
    lowerBound(end + 1, 1) = minimumFinalTime_s;
    upperBound(end + 1, 1) = latestFinalTime_s;
    % Scale the arrival decision by the physical duration this solve expects.
    % Taking the mission horizon instead would let an unrelated deadline
    % rescale every interior-point step and change the reported motion.
    typicalDecision(end + 1, 1) = max([1, ...
        abs(minimumFinalTime_s), abs(finalTimeGuess_s)]);
end
%% Section 2: Minimize Arrival Time Or Fixed-Time Jerk

% Nonlinear constraints cover continuous kinematic bounds, terminal state,
% and obstacle separation. Earliest-arrival minimizes final time. At fixed
% arrival, integrated squared jerk chooses a smoother feasible motion.
% Timed and exact multi-obstacle systems converge faster when factorized.
useFactorization = isEarliestArrival && (isTimedSeed || ...
    (numel(obstacles) > 1 && ~seed.UsesReducedGeometry));
subproblemAlgorithms = ["cg", "factorization"];
subproblemAlgorithm = subproblemAlgorithms(1 + useFactorization);
reconstructFunction = @(jerk_deg_s3, finalTime_s) createPlannerPolynomial( ...
    jerk_deg_s3, initialState, finalTime_s, segmentCount, segmentBreakTau);
constraintFunction = @(decision) ...
    obstacleAvoidance.planner.evaluateTrajectoryConstraints( ...
    decision, isEarliestArrival, latestFinalTime_s, minimumFinalTime_s, ...
    latestFinalTime_s, segmentCount, initialState, goalState, limits, ...
    options, obstacles, corridor, corridorTau, seedCorridor, ...
    reconstructFunction, collinearityDirection, constraintLayout);
linearInequalityMatrix = zeros(0, numel(decision0));
linearInequalityBound = zeros(0, 1);
linearEqualityMatrix = zeros(0, numel(decision0));
linearEqualityBound = zeros(0, 1);
if ~isEarliestArrival
    % Fixed-time integration makes every raw constraint affine in jerk.
    [zeroInequality, zeroEquality] = constraintFunction(zeros(size(decision0)));
    [linearInequalityMatrix, linearEqualityMatrix] = ...
        obstacleAvoidance.planner.createConstraintMatrices( ...
        segmentCount, latestFinalTime_s - startTime_s, ...
        options.AllowAzimuthWrapping, seedCorridor, corridor, corridorTau, ...
        [], collinearityDirection, constraintLayout, segmentBreakTau);
    if size(linearInequalityMatrix, 1) ~= numel(zeroInequality) || ...
            size(linearEqualityMatrix, 1) ~= numel(zeroEquality)
        error("solveRouteCandidate:ConstraintGradientSizeMismatch", ...
            "The exact fixed-time HS3 constraint maps have inconsistent sizes.");
    end
    linearInequalityBound = -zeroInequality;
    linearEqualityBound = -zeroEquality;
end
if isEarliestArrival
    stageOneObjective = @arrivalTimeObjective;
else
    stageOneObjective = @(decision) ...
        hs3Engine.polynomial.evaluateIntegratedSquaredJerk(decision, false, latestFinalTime_s, ...
        segmentCount, startTime_s, 2, segmentBreakTau);
end
coreOptions = struct( ...
    "MaximumIterations", options.MaximumNlpIterations, ...
    "MaximumFunctionEvaluations", options.MaximumNlpFunctionEvaluations, ...
    "MaximumSolveTime", maximumSolverTime_s, ...
    "ArrivalTimeTolerance", options.ArrivalTimeTolerance_s, ...
    "ConstraintTolerance", options.ConstraintTolerance, ...
    "OptimalityTolerance", options.OptimalityTolerance, ...
    "StepTolerance", options.StepTolerance, ...
    "Verbose", options.Verbose);
problem = struct( ...
    "Decision0", decision0, ...
    "LowerBound", lowerBound, ...
    "UpperBound", upperBound, ...
    "TypicalDecision", typicalDecision, ...
    "IsFreeTime", isEarliestArrival, ...
    "ConstraintFunction", constraintFunction, ...
    "ObjectiveFunction", stageOneObjective, ...
    "ProgressFunction", @(decision, solverValues, state) ...
    hs3Progress(decision, solverValues, state, solverTimer, ...
    maximumSolverTime_s, options.MaximumNlpIterations, ...
    options.Verbose, seed.Index), ...
    "SubproblemAlgorithm", subproblemAlgorithm, ...
    "MaximumFinalTime", latestFinalTime_s, ...
    "InequalityMatrix", linearInequalityMatrix, ...
    "InequalityBound", linearInequalityBound, ...
    "EqualityMatrix", linearEqualityMatrix, ...
    "EqualityBound", linearEqualityBound, ...
    "SolverTimer", solverTimer);
if ~isEarliestArrival
    [~, ~, problem.Hessian] = hs3Engine.polynomial.evaluateIntegratedSquaredJerk( ...
        decision0, false, latestFinalTime_s, segmentCount, startTime_s, 2, ...
        segmentBreakTau);
end
core = hs3Engine.optimize(problem, coreOptions);
if strlength(core.StageOneErrorIdentifier) > 0
    candidate.Message = "HS3 solve failed: " + core.StageOneErrorMessage;
    candidate.TerminationReason = "solverError";
    candidate.SolverDiagnostics.Identifier = core.StageOneErrorIdentifier;
    candidate.SolverDiagnostics = ...
        obstacleAvoidance.planner.createEmptySolverDiagnostics( ...
        candidate.SolverDiagnostics, toc(solverTimer), ...
        corridorConstructionElapsedTime_s);
    return;
end
if ~isEarliestArrival && options.Verbose
        fprintf("[ObstacleAvoidance][HS3][seed %d] state=done, solver=quadprog, " + ...
        "iterations=%g, objective=%.6g.\n", ...
        seed.Index, outputValue(core.StageOneOutput, "iterations"), ...
        core.StageOneObjective);
end
selectedDecision = core.Decision;
stageOneObjectiveValue = core.StageOneObjective;
stageOneExitFlag = core.StageOneExitFlag;
stageOneOutput = core.StageOneOutput;
stageTwoExitFlag = core.StageTwoExitFlag;
stageTwoOutput = core.StageTwoOutput;
stageTwoObjectiveValue = core.StageTwoObjective;
stageTwoErrorIdentifier = core.StageTwoErrorIdentifier;
stageTwoErrorMessage = core.StageTwoErrorMessage;
finalInequality = core.MaximumInequalityViolation;
finalEquality = core.MaximumEqualityViolation;
feasibilityTolerance = max(10 * options.ConstraintTolerance, 1e-7);
%% Section 4: Reconstruct The Candidate

% Solver output is only a proposal. Reconstruct the complete polynomial and
% preserve raw solver evidence; the caller independently validates collision
% and kinematic limits before accepting the candidate.
[jerk_deg_s3, finalTime_s] = unpackDecision( ...
    selectedDecision, isEarliestArrival, latestFinalTime_s, controlCount);
polynomial = createPlannerPolynomial( ...
    jerk_deg_s3, initialState, finalTime_s, segmentCount, segmentBreakTau);
[sampleTime_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, sampledJerk_deg_s3] = samplePolynomial( ...
    polynomial, options.SampleTime_s);
maximumInequalityViolation = max([0; finalInequality(:)]);
maximumEqualityViolation = max([0; abs(finalEquality(:))]);
maximumViolation = max( ...
    maximumInequalityViolation, maximumEqualityViolation);
optimizerFeasible = maximumViolation <= feasibilityTolerance;
timeLimitReached = toc(solverTimer) >= maximumSolverTime_s;
% A free-time solve that stops on its upper bound never descended, so its
% arrival is the deadline rather than an earliest arrival.
arrivalAtHorizon = isEarliestArrival && optimizerFeasible && ...
    finalTime_s >= latestFinalTime_s - options.ArrivalTimeTolerance_s;
if arrivalAtHorizon
    message = "HS3 returned a constraint-feasible motion pinned to the " + ...
        "goal horizon rather than an earliest arrival.";
    terminationReason = "arrivalAtHorizon";
elseif optimizerFeasible
    message = "HS3 returned a constraint-feasible local solution.";
    terminationReason = "optimizerFeasible";
elseif timeLimitReached
    message = "HS3 reached its solver time limit before feasibility.";
    terminationReason = "solverTimeLimit";
else
    message = "HS3 did not satisfy all optimization constraints.";
    terminationReason = "optimizerInfeasible";
end
solverDiagnostics = ...
    obstacleAvoidance.planner.createEmptySolverDiagnostics();
solverDiagnostics.ConstraintRepresentation = constraintRepresentation;
solverDiagnostics.StageOneExitFlag = stageOneExitFlag;
solverDiagnostics.StageTwoExitFlag = stageTwoExitFlag;
solverDiagnostics.StageOneObjective = stageOneObjectiveValue;
solverDiagnostics.StageTwoObjective = stageTwoObjectiveValue;
solverDiagnostics.StageOneOutput = stageOneOutput;
solverDiagnostics.StageTwoOutput = stageTwoOutput;
solverDiagnostics.StageTwoErrorIdentifier = stageTwoErrorIdentifier;
solverDiagnostics.StageTwoErrorMessage = stageTwoErrorMessage;
solverDiagnostics.MaximumInequalityViolation = maximumInequalityViolation;
solverDiagnostics.MaximumEqualityViolation = maximumEqualityViolation;
candidate = struct( ...
    "OptimizerFeasible", optimizerFeasible, ...
    "ArrivalAtHorizon", arrivalAtHorizon, ...
    "Message", message, ...
    "TerminationReason", terminationReason, ...
    "SeedIndex", seed.Index, ...
    "SeedSource", seed.Source, ...
    "FinalTime_s", finalTime_s, ...
    "MotionDuration_s", finalTime_s - startTime_s, ...
    "MotionLength_deg", sum(vecnorm(diff(position_deg, 1, 1), 2, 2)), ...
    "IntegratedSquaredJerk_deg2_s5", ...
    hs3Engine.polynomial.evaluateIntegratedSquaredJerk( ...
    selectedDecision, isEarliestArrival, latestFinalTime_s, ...
    segmentCount, startTime_s, 2, segmentBreakTau), ...
    "MaximumConstraintViolation", maximumViolation, ...
    "time_s", sampleTime_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2, ...
    "jerk_deg_s3", sampledJerk_deg_s3, ...
    "Polynomial", polynomial, ...
    "ControlTau", controlTau, ...
    "ControlJerk_deg_s3", jerk_deg_s3, ...
    "Corridor", corridor, ...
    "SeedCorridorBoundary_deg", seed.CorridorBoundary_deg, ...
    "SeedCorridor", seedCorridor, ...
    "SolverDiagnostics", solverDiagnostics);
candidate.SolverDiagnostics = ...
    obstacleAvoidance.planner.createEmptySolverDiagnostics( ...
    candidate.SolverDiagnostics, toc(solverTimer), ...
    corridorConstructionElapsedTime_s);
end
function stop = hs3Progress(~, solverValues, state, solverTimer, ...
        maximumTime_s, maximumIterationCount, verbose, seedIndex)
% Stop optional work and report only sparse, durable progress checkpoints.
stop = toc(solverTimer) >= maximumTime_s;
if ~verbose
    return;
end
iteration = outputValue(solverValues, "iteration");
reportCheckpoint = state == "iter" && iteration > 0 && ...
    mod(iteration, 100) == 0;
if state == "done" || reportCheckpoint
    barWidth = 12;
    fraction = min(1, max(0, iteration / maximumIterationCount));
    bar = progressBarText(fraction, barWidth);
    fprintf( ...
        "[Planner][candidate %d] [%s] %3.0f%% work cap; " + ...
        "state=%s, iteration=%g, evaluations=%g, objective=%.6g, " + ...
        "violation=%.3g.\n", seedIndex, char(bar), 100 * fraction, ...
        state, iteration, ...
        outputValue(solverValues, "funccount"), ...
        outputValue(solverValues, "fval"), ...
        outputValue(solverValues, "constrviolation"));
end
end

function bar = progressBarText(fraction, barWidth)
% Create a fixed-width Unicode bar with a partial leading cell.
scaledWidth = barWidth * fraction;
filledCount = floor(scaledWidth);
hasPartialCell = filledCount < barWidth && ...
    scaledWidth - filledCount > 10 * eps(max(1, scaledWidth));
barCells = repmat("░", 1, barWidth);
barCells(1:filledCount) = "█";
if hasPartialCell
    barCells(filledCount + 1) = "▒";
end
bar = join(barCells, "");
end

function value = outputValue(output, fieldName)
% Read one optional fmincon output value for stable verbose messages.
if isstruct(output) && isfield(output, fieldName)
    value = output.(fieldName);
else
    value = NaN;
end
end

function direction = monotonicityDirection( ...
        collinearityDirection, initialState, goalState)
% Restrict certified direct motion only for rest-to-rest endpoint states.
% Nonzero endpoint derivatives can physically require a reversal, so those
% requests retain the original unrestricted collinear solve.
direction = zeros(0, 2);
if isempty(collinearityDirection)
    return;
end
velocity_deg_s = [initialState.velocity_deg_s; goalState.velocity_deg_s];
acceleration_deg_s2 = [initialState.acceleration_deg_s2; goalState.acceleration_deg_s2];
velocityTolerance_deg_s = 64 * eps(max( ...
    1, max(abs(velocity_deg_s), [], "all")));
accelerationTolerance_deg_s2 = 64 * eps(max( ...
    1, max(abs(acceleration_deg_s2), [], "all")));
if all(abs(velocity_deg_s) <= velocityTolerance_deg_s, "all") && ...
        all(abs(acceleration_deg_s2) <= ...
        accelerationTolerance_deg_s2, "all")
    direction = collinearityDirection(:).';
end
end
function layout = createConstraintLayout(segmentCount, startTime_s, ...
        minimumFinalTime_s, maximumFinalTime_s, goalState, obstacles, ...
        corridor, segmentBreakTau)
% Freeze corridor row topology and final-time events for one solver attempt.
% Geometry values remain dynamic; only maps and event locations are reused.
positionCoefficientCount = 6;
recordCount = numel(corridor);
if recordCount == 0
    segmentIndex = zeros(0, 1);
    hullMap = zeros(positionCoefficientCount, positionCoefficientCount, 0);
    rowOffset = 0;
else
    useIntervalHull = [corridor.UseIntervalHull].';
    effectiveTauEnd = [corridor.TauEnd];
    effectiveTauEnd(~useIntervalHull.') = ...
        [corridor(~useIntervalHull).Tau];
    [segmentIndex, hullMap] = ...
        hs3Engine.polynomial.createSubintervalBernsteinMap( ...
        [corridor.Tau], effectiveTauEnd, segmentCount, ...
        positionCoefficientCount, segmentBreakTau);
    rowOffset = [0; cumsum(1 + ...
        (positionCoefficientCount - 1) * useIntervalHull)];
end

eventFinalTime_s = zeros(0, 1);
if isfield(goalState, "targetTime_s") && ~isempty(goalState.targetTime_s)
    eventFinalTime_s = double(goalState.targetTime_s(:));
end
for associationIndex = 1:recordCount
    tau = corridor(associationIndex).Tau;
    if tau <= 0
        continue;
    end
    obstacleTime_s = double( ...
        obstacles(corridor(associationIndex).ObstacleIndex).time_s(:));
    eventFinalTime_s = [eventFinalTime_s; ...
        startTime_s + (obstacleTime_s - startTime_s) / tau]; %#ok<AGROW>
end
eventFinalTime_s = unique(eventFinalTime_s( ...
    isfinite(eventFinalTime_s) & ...
    eventFinalTime_s >= minimumFinalTime_s & ...
    eventFinalTime_s <= maximumFinalTime_s));
layout = struct( ...
    "PositionCoefficientCount", positionCoefficientCount, ...
    "CorridorSegmentIndex", segmentIndex, ...
    "CorridorHullMap", hullMap, ...
    "CorridorRowOffset", rowOffset, ...
    "SegmentBreakTau", segmentBreakTau, ...
    "FinalTimeEvent_s", eventFinalTime_s);
end

function segmentBreakTau = resolveSegmentBreakTau(seed, segmentCount)
% Resolve an internal nonuniform mesh or construct the established uniform one.
segmentBreakTau = (0:segmentCount).' / segmentCount;
if ~isfield(seed, "SegmentBreakTau") || isempty(seed.SegmentBreakTau)
    return;
end
validateattributes(seed.SegmentBreakTau, {'numeric'}, ...
    {'real', 'finite', 'vector', 'numel', segmentCount + 1});
segmentBreakTau = double(seed.SegmentBreakTau(:));
endpointTolerance = 32 * eps;
if abs(segmentBreakTau(1)) > endpointTolerance || ...
        abs(segmentBreakTau(end) - 1) > endpointTolerance || ...
        any(diff(segmentBreakTau) <= 0)
    error("solveRouteCandidate:InvalidSegmentBreakTau", ...
        "seed.SegmentBreakTau must strictly increase from zero to one.");
end
segmentBreakTau(1) = 0;
segmentBreakTau(end) = 1;
end

function controlTau = createControlTau(segmentBreakTau)
% Interleave each segment boundary with its normalized-time midpoint.
segmentCount = numel(segmentBreakTau) - 1;
controlTau = zeros(2 * segmentCount + 1, 1);
controlTau(1:2:end) = segmentBreakTau;
controlTau(2:2:end - 1) = ...
    (segmentBreakTau(1:end - 1) + segmentBreakTau(2:end)) / 2;
end

function corridorTau = createCorridorTau(segmentBreakTau, checkCount)
% Subdivide every nonuniform segment without allowing certificate intervals
% to cross a polynomial boundary.
segmentCount = numel(segmentBreakTau) - 1;
corridorTau = zeros(segmentCount * checkCount + 1, 1);
nextIndex = 1;
for segmentIndex = 1:segmentCount
    localFraction = (0:checkCount - 1).' / checkCount;
    destination = nextIndex:nextIndex + checkCount - 1;
    corridorTau(destination) = segmentBreakTau(segmentIndex) + ...
        diff(segmentBreakTau(segmentIndex:segmentIndex + 1)) * localFraction;
    nextIndex = nextIndex + checkCount;
end
corridorTau(end) = 1;
end

function segmentIndex = segmentAtTau(tau, segmentBreakTau, segmentCount)
% Locate one normalized coordinate and assign the final endpoint to segment N.
segmentIndex = discretize(tau, segmentBreakTau);
if tau == 1
    segmentIndex = segmentCount;
end
end

function checkCount = corridorChecksPerSegment( ...
        obstacles, startTime_s, finalTime_s, segmentCount)
% Scale density with boundary detail and obstacle-history time spacing.
maximumVertexCount = 0;
minimumInterval_s = Inf;

% Scan every obstacle to find the densest boundary and shortest history
% interval that the frozen corridor must resolve.
for obstacleIndex = 1:numel(obstacles)
    obstacle = obstacles(obstacleIndex);
    if numel(obstacle.time_s) > 1
        minimumInterval_s = min( ...
            minimumInterval_s, min(diff(obstacle.time_s)));
    end

    % Inspect every source slice because a later slice may contain more detail
    % than the first.
    for sampleIndex = 1:numel(obstacle.az_deg)
        finiteVertexCount = nnz(isfinite(obstacle.az_deg{sampleIndex}) & ...
            isfinite(obstacle.el_deg{sampleIndex}));
        maximumVertexCount = max(maximumVertexCount, finiteVertexCount);
    end
end
boundaryCheckCount = ceil(maximumVertexCount / 5);
motionCheckCount = 8;
if isfinite(minimumInterval_s) && minimumInterval_s > 0
    samplesPerObstacleInterval = 4;
    duration_s = finalTime_s - startTime_s;
    motionCheckCount = ceil(samplesPerObstacleInterval * duration_s / ...
        (segmentCount * minimumInterval_s));
end
maximumChecksPerSegment = 16;
checkCount = min(maximumChecksPerSegment, ...
    max([8, boundaryCheckCount, motionCheckCount]));
end
function [jerkGuess_deg_s3, jerkLimitRatio] = initialJerkGuess(isEarliestArrival, ...
        initialState, goalState, limits, seed, finalTime_s, segmentCount, ...
        controlTau, segmentBreakTau)
% Fit a bounded jerk-chain initialization to the supplied topology seed.
controlCount = numel(controlTau);
desiredPosition_deg = interp1(seed.tau, seed.position_deg, controlTau, "linear");
evaluationTime_s = initialState.time_s + controlTau * (finalTime_s - initialState.time_s);
zeroJerk_deg_s3 = zeros(controlCount, 2);
basePolynomial = createPlannerPolynomial( ...
    zeroJerk_deg_s3, initialState, finalTime_s, segmentCount, ...
    segmentBreakTau);
[~, basePosition_deg, baseVelocity_deg_s, baseAcceleration_deg_s2] = ...
    obstacleAvoidance.planner.evaluatePlannerPolynomial( ...
        basePolynomial, evaluationTime_s);
desiredPosition_deg(end, :) = obstacleAvoidance.input.goalPositionAtTime( ...
    goalState, finalTime_s);
if hasMotionWarmStart(seed, initialState.time_s, ...
        initialState.time_s, finalTime_s)
    warmStartDuration_s = seed.MotionWarmStart.FinalTime_s - ...
        initialState.time_s;
    warmEvaluationTime_s = initialState.time_s + ...
        controlTau * warmStartDuration_s;
    [~, desiredPosition_deg, desiredVelocity_deg_s] = ...
        obstacleAvoidance.planner.evaluatePlannerPolynomial( ...
        seed.MotionWarmStart.Polynomial, warmEvaluationTime_s);
    desiredVelocity_deg_s = desiredVelocity_deg_s * ...
        warmStartDuration_s / (finalTime_s - initialState.time_s);
else
    routeTangent_deg = desiredPosition_deg([2:end end], :) - ...
        desiredPosition_deg([1 1:end-1], :);
    routeDirection = routeTangent_deg ./ ...
        max(vecnorm(routeTangent_deg, 2, 2), eps);
    routeSpeed_deg_s = min(limits.maxVelocity_deg_s ./ ...
        max(abs(routeDirection), eps), [], 2);
    routeSpeed_deg_s = min(routeSpeed_deg_s, max(seed.Length_deg / ...
        (finalTime_s - initialState.time_s), ...
        isEarliestArrival * norm(limits.maxVelocity_deg_s)));
    desiredVelocity_deg_s = routeDirection .* routeSpeed_deg_s;
    desiredVelocity_deg_s([1 end], :) = ...
        [initialState.velocity_deg_s; goalState.velocity_deg_s];
end
velocityFitWeight_s = (finalTime_s - initialState.time_s) / segmentCount;
sensitivity = hs3Engine.polynomial.createAffineSensitivityModel( ...
    segmentCount, finalTime_s - initialState.time_s, controlTau, ...
    segmentBreakTau);
positionMap = sensitivity.positionAtTauMap(2:end, :);
velocityMap = sensitivity.velocityAtTauMap(2:end - 1, :);
terminalVelocityMap = sensitivity.terminalStateMap(2, :);
terminalAccelerationMap = sensitivity.terminalStateMap(3, :);
fitMatrix = [positionMap; velocityFitWeight_s * velocityMap; 5 * terminalVelocityMap; ...
    5 * terminalAccelerationMap];
fitOffset = [desiredPosition_deg(2:end, :) - basePosition_deg(2:end, :); ...
    velocityFitWeight_s * (desiredVelocity_deg_s(2:end-1, :) - ...
    baseVelocity_deg_s(2:end-1, :)); ...
    5 * (goalState.velocity_deg_s - baseVelocity_deg_s(end, :)); ...
    5 * (goalState.acceleration_deg_s2 - baseAcceleration_deg_s2(end, :))];
regularization = 1e-8 * eye(controlCount);
jerkGuess_deg_s3 = (fitMatrix.' * fitMatrix + regularization) \ ...
    (fitMatrix.' * fitOffset);
jerkLimitRatio = max(abs(jerkGuess_deg_s3) ./ limits.maxJerk_deg_s3, [], "all");
jerkGuess_deg_s3 = min(limits.maxJerk_deg_s3, max(-limits.maxJerk_deg_s3, jerkGuess_deg_s3));
end
function available = hasMotionWarmStart( ...
        seed, startTime_s, minimumFinalTime_s, maximumFinalTime_s)
% Accept only a complete polynomial whose time range matches this request.
available = isfield(seed, "MotionWarmStart") && ...
    isstruct(seed.MotionWarmStart) && isscalar(seed.MotionWarmStart) && ...
    all(isfield(seed.MotionWarmStart, ["Polynomial", "FinalTime_s"])) && ...
    isstruct(seed.MotionWarmStart.Polynomial) && ...
    isfield(seed.MotionWarmStart.Polynomial, "SegmentStartTime_s") && ...
    ~isempty(seed.MotionWarmStart.Polynomial.SegmentStartTime_s) && ...
    abs(seed.MotionWarmStart.Polynomial.SegmentStartTime_s(1) - ...
    startTime_s) <= 1e-9 && ...
    isfinite(seed.MotionWarmStart.FinalTime_s) && ...
    seed.MotionWarmStart.FinalTime_s >= minimumFinalTime_s - 1e-9 && ...
    seed.MotionWarmStart.FinalTime_s <= maximumFinalTime_s + 1e-9;
end
function [value, gradient] = arrivalTimeObjective(decision)
% Return the exact linear arrival objective and axis-major decision gradient.
value = decision(end);
if ~isfinite(value)
    % Keep the line search alive long enough to reject a corrupt trial.
    value = 1e12;
end
if nargout > 1
    gradient = zeros(size(decision));
    gradient(end) = 1;
end
end
function corridor = createCorridor( ...
        obstacles, seed, startTime_s, finalTime_s, segmentCount, ...
        controlTau, segmentBreakTau, ...
        clearanceTolerance_deg, geometryIsFixed, maxVelocity_deg_s)
% Freeze obstacle edges at dense optimization constraint points.
template = struct( ...
    "ControlIndex", 0, "ObstacleIndex", 0, "EdgeIndex", 0, ...
    "Tau", 0, "TauEnd", 0, ...
    "OutwardSign", 1, "UseSupport", false, ...
    "UseIntervalHull", false, ...
    "SupportNormal", [0 0], "Clearance_deg", 0, ...
    "GeometryIsFixed", false, "FixedNormal", [0 0], ...
    "FixedBoundaryOffset_deg", 0);
corridor = repmat(template, 0, 1);
if obstacleAvoidance.search.seedEnvelopeContainsObstacles( ...
        seed.CorridorBoundary_deg, obstacles, clearanceTolerance_deg)
    return;
end
lockedAssociation = repmat(template, numel(obstacles), 1);
hasLockedAssociation = false(numel(obstacles), 1);
seedPosition_deg = interp1(seed.tau, seed.position_deg, ...
    controlTau, "linear");
controlTime_s = startTime_s + controlTau * (finalTime_s - startTime_s);
vehicleSpeedBound_deg_s = norm(maxVelocity_deg_s);

% Visit every dense control time so moving obstacle associations remain ordered
% along the candidate trajectory.
for controlIndex = 1:numel(controlTau)
    % Associate every active obstacle with one supporting edge at this time.
    for obstacleIndex = 1:numel(obstacles)
        [~, geometry] = obstacleAvoidance.obstacles.shapeAtTime( ...
            obstacles(obstacleIndex), controlTime_s(controlIndex), true);
        if ~geometry.Active
            hasLockedAssociation(obstacleIndex) = false;
            continue;
        end
        [edgeStart_deg, edgeEnd_deg] = ...
            obstacleAvoidance.geometry.canonicalBoundaryToEdges(geometry);
        finiteVertices = isfinite(geometry.azimuth_deg) & ...
            isfinite(geometry.elevation_deg);
        vertices_deg = [geometry.azimuth_deg(finiteVertices), ...
            geometry.elevation_deg(finiteVertices)];
        geometryIsConvex = geometry.IsConvex;
        [edgeIndex, nearestPoint_deg] = nearestEdge( ...
            seedPosition_deg(controlIndex, :), ...
            edgeStart_deg, edgeEnd_deg);
        edgeDelta_deg = edgeEnd_deg(edgeIndex, :) - ...
            edgeStart_deg(edgeIndex, :);
        leftNormal = [-edgeDelta_deg(2), edgeDelta_deg(1)];
        leftNormal = leftNormal / norm(leftNormal);
        if geometry.HasOrderedSingleRegion
            outwardSign = geometry.OutwardSign;
        else
            shape = obstacleAvoidance.geometry.boundaryToShape( ...
                geometry.azimuth_deg, geometry.elevation_deg);
            probeScale_deg = max(1e-7, 1e-7 * norm(edgeDelta_deg));
            probe_deg = nearestPoint_deg + probeScale_deg * leftNormal;
            outwardSign = 1 - 2 * isinterior( ...
                shape, probe_deg(1), probe_deg(2));
        end
        association = template;
        association.ControlIndex = controlIndex;
        association.ObstacleIndex = obstacleIndex;
        association.EdgeIndex = edgeIndex;
        association.Tau = controlTau(controlIndex);
        association.OutwardSign = outwardSign;
        % A small separation prevents tolerance-level boundary contact. The
        % association bounds its whole sub-interval, so this separation holds
        % continuously rather than only at the association time.
        association.Clearance_deg = max(1e-4, clearanceTolerance_deg);
        stationarySpeedTolerance_deg_s = 1e-12;
        geometryIsStationary = geometry.VertexSpeedBound_deg_s <= ...
            stationarySpeedTolerance_deg_s;
        association.UseIntervalHull = geometryIsStationary;
        if (~geometry.TopologyIsInterpolated || geometryIsStationary) && ...
                geometryIsConvex
            outwardNormal = outwardSign * leftNormal;
            association.UseSupport = true;
            association.SupportNormal = outwardNormal;
        end
        if geometryIsFixed || geometryIsStationary
            if association.UseSupport
                outwardNormal = association.SupportNormal;
                boundaryOffset_deg = max(vertices_deg * outwardNormal.');
            else
                outwardNormal = outwardSign * leftNormal;
                boundaryOffset_deg = edgeStart_deg(edgeIndex, :) * ...
                    outwardNormal.';
            end
            association.GeometryIsFixed = true;
            association.FixedNormal = outwardNormal;
            association.FixedBoundaryOffset_deg = boundaryOffset_deg;
        end
        usedLockedAssociation = false;
        geometryRequiresLock = geometry.VertexSpeedBound_deg_s > ...
            vehicleSpeedBound_deg_s;
        if geometryRequiresLock && hasLockedAssociation(obstacleIndex)
            [trialAssociation, lockIsSatisfied] = moveAssociation( ...
                lockedAssociation(obstacleIndex), geometry, ...
                edgeStart_deg, edgeEnd_deg, controlIndex, ...
                controlTau(controlIndex), geometryIsFixed, ...
                seedPosition_deg(controlIndex, :));
            if lockIsSatisfied
                association = trialAssociation;
                usedLockedAssociation = true;
            end
        end
        if geometryRequiresLock && ~usedLockedAssociation
            [association, ~] = moveAssociation( ...
                association, geometry, edgeStart_deg, edgeEnd_deg, ...
                controlIndex, controlTau(controlIndex), ...
                geometryIsFixed, seedPosition_deg(controlIndex, :));
        end
        if geometryRequiresLock
            lockedAssociation(obstacleIndex) = association;
            hasLockedAssociation(obstacleIndex) = true;
        else
            hasLockedAssociation(obstacleIndex) = false;
        end
        % Own the span up to the next constraint time so the frozen
        % half-space bounds a whole arc instead of one instant.
        association.TauEnd = controlTau( ...
            min(numel(controlTau), controlIndex + 1));
        corridor(end + 1, 1) = association; %#ok<AGROW>
    end
end
corridor = mergeFixedCorridorIntervals( ...
    corridor, segmentCount, segmentBreakTau);
end

function merged = mergeFixedCorridorIntervals( ...
        corridor, segmentCount, segmentBreakTau)
% Merge contiguous identical fixed half-spaces inside one polynomial
% segment so one exact hull replaces redundant sub-interval hulls.

if isempty(corridor)
    merged = corridor;
    return;
end
merged = repmat(corridor(1), 0, 1);
lastIndexByObstacle = zeros(max([corridor.ObstacleIndex]), 1);
halfspaceTolerance_deg = 1e-12;
tauTolerance = 64 * eps;

for associationIndex = 1:numel(corridor)
    current = corridor(associationIndex);
    previousIndex = lastIndexByObstacle(current.ObstacleIndex);
    canMerge = false;
    if current.GeometryIsFixed && previousIndex > 0
        previous = merged(previousIndex);
        previousSegment = segmentAtTau( ...
            previous.Tau, segmentBreakTau, segmentCount);
        currentSegment = segmentAtTau( ...
            current.Tau, segmentBreakTau, segmentCount);
        canMerge = previous.GeometryIsFixed && ...
            previous.UseIntervalHull && current.UseIntervalHull && ...
            previousSegment == currentSegment && ...
            abs(previous.TauEnd - current.Tau) <= tauTolerance && ...
            norm(previous.FixedNormal - current.FixedNormal) <= ...
            halfspaceTolerance_deg && ...
            abs(previous.FixedBoundaryOffset_deg - ...
            current.FixedBoundaryOffset_deg) <= halfspaceTolerance_deg && ...
            abs(previous.Clearance_deg - current.Clearance_deg) <= ...
            halfspaceTolerance_deg;
    end
    if canMerge
        merged(previousIndex).TauEnd = current.TauEnd;
    else
        merged(end + 1, 1) = current; %#ok<AGROW>
        lastIndexByObstacle(current.ObstacleIndex) = numel(merged);
    end
end
end

function [association, isSatisfied] = moveAssociation( ...
        association, geometry, edgeStart_deg, edgeEnd_deg, ...
        controlIndex, controlTau, geometryIsFixed, point_deg)
% Keep a seed half-space until the seed no longer satisfies it.
finiteVertices = isfinite(geometry.azimuth_deg) & ...
    isfinite(geometry.elevation_deg);
vertices_deg = [geometry.azimuth_deg(finiteVertices), ...
    geometry.elevation_deg(finiteVertices)];
isSatisfied = false;
if association.UseSupport
    outwardNormal = association.SupportNormal;
    boundaryOffset_deg = max(vertices_deg * outwardNormal.');
elseif association.EdgeIndex <= size(edgeStart_deg, 1)
    edgeDelta_deg = edgeEnd_deg(association.EdgeIndex, :) - ...
        edgeStart_deg(association.EdgeIndex, :);
    if norm(edgeDelta_deg) <= eps
        return;
    end
    leftNormal = [-edgeDelta_deg(2), edgeDelta_deg(1)] / ...
        norm(edgeDelta_deg);
    outwardNormal = association.OutwardSign * leftNormal;
    boundaryOffset_deg = edgeStart_deg(association.EdgeIndex, :) * ...
        outwardNormal.';
else
    return;
end
pointProjection_deg = point_deg * outwardNormal.';
seedClearance_deg = pointProjection_deg - boundaryOffset_deg;
isSatisfied = seedClearance_deg >= association.Clearance_deg;
if ~isSatisfied
    return;
end
seedClearanceRetention = 0.25;
association.Clearance_deg = max(association.Clearance_deg, ...
    seedClearanceRetention * seedClearance_deg);
association.ControlIndex = controlIndex;
association.Tau = controlTau;
association.GeometryIsFixed = geometryIsFixed;
if geometryIsFixed
    association.FixedNormal = outwardNormal;
    association.FixedBoundaryOffset_deg = boundaryOffset_deg;
end
end
function [edgeIndex, nearestPoint_deg] = nearestEdge( ...
        point_deg, edgeStart_deg, edgeEnd_deg)
% Select the closest edge and boundary point for a frozen association.
edgeDelta_deg = edgeEnd_deg - edgeStart_deg;
edgeLengthSquared_deg2 = sum(edgeDelta_deg.^2, 2);
projection = zeros(size(edgeLengthSquared_deg2));
validEdges = edgeLengthSquared_deg2 > 0;
projection(validEdges) = sum( ...
    (point_deg - edgeStart_deg(validEdges, :)) .* ...
    edgeDelta_deg(validEdges, :), 2) ./ ...
    edgeLengthSquared_deg2(validEdges);
projection = min(1, max(0, projection));
projectedPoint_deg = edgeStart_deg + projection .* edgeDelta_deg;
[~, edgeIndex] = min(sum((point_deg - projectedPoint_deg).^2, 2));
nearestPoint_deg = projectedPoint_deg(edgeIndex, :);
end

function polynomial = createPlannerPolynomial( ...
        jerk_deg_s3, initialState, finalTime_s, segmentCount, segmentBreakTau)
% Adapt unit-bearing Az/El state fields to the dimension-neutral HS3
% required reconstruction fields and restore the planner's public format.
engineInitialState = struct( ...
    "time", initialState.time_s, ...
    "position", initialState.position_deg, ...
    "velocity", initialState.velocity_deg_s, ...
    "acceleration", initialState.acceleration_deg_s2);
enginePolynomial = hs3Engine.polynomial.createTrajectoryPolynomial( ...
    jerk_deg_s3, engineInitialState, finalTime_s, segmentCount, ...
    segmentBreakTau);
polynomial = struct( ...
    "SegmentCount", enginePolynomial.SegmentCount, ...
    "SegmentStartTime_s", enginePolynomial.SegmentStartTime, ...
    "SegmentDuration_s", enginePolynomial.SegmentDuration, ...
    "SegmentBreakTau", enginePolynomial.SegmentBreakTau, ...
    "FinalTime_s", enginePolynomial.FinalTime, ...
    "positionPower_deg", enginePolynomial.positionPower, ...
    "velocityPower_deg_s", enginePolynomial.velocityPower, ...
    "accelerationPower_deg_s2", enginePolynomial.accelerationPower, ...
    "jerkPower_deg_s3", enginePolynomial.jerkPower, ...
    "TerminalState", struct( ...
    "position_deg", enginePolynomial.TerminalState.position, ...
    "velocity_deg_s", enginePolynomial.TerminalState.velocity, ...
    "acceleration_deg_s2", enginePolynomial.TerminalState.acceleration));
end

function [time_s, position_deg, velocity_deg_s, ...
        acceleration_deg_s2, jerk_deg_s3] = samplePolynomial( ...
        polynomial, sampleTime_s)
% Sample the exact segment polynomials without losing knot times.
startTime_s = polynomial.SegmentStartTime_s(1);
uniformTime_s = (startTime_s:sampleTime_s:polynomial.FinalTime_s).';
time_s = unique([uniformTime_s; polynomial.SegmentStartTime_s; ...
    polynomial.FinalTime_s]);
[time_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, jerk_deg_s3] = obstacleAvoidance.planner.evaluatePlannerPolynomial( ...
    polynomial, time_s);
end

function [jerk_deg_s3, finalTime_s] = unpackDecision( ...
        decision, isEarliestArrival, fixedFinalTime_s, controlCount)
% Recover jerk ordinates and final time from the HS3 decision vector.
jerkValueCount = 2 * controlCount;
jerk_deg_s3 = reshape(decision(1:jerkValueCount), controlCount, 2);
if isEarliestArrival
    finalTime_s = decision(end);
else
    finalTime_s = fixedFinalTime_s;
end
end

function duration_s = durationLowerBound( ...
        initialState, goalState, limits, latestFinalTime_s)
% Compute an input-driven lower bound without claiming exact optimality.
if isfield(goalState, "targetTime_s") && ...
        ~isempty(goalState.targetTime_s)
    duration_s = movingTargetDurationLowerBound( ...
        initialState, goalState, limits);
    return;
end
goalPosition_deg = obstacleAvoidance.input.goalPositionAtTime( ...
    goalState, latestFinalTime_s);
displacement_deg = abs(goalPosition_deg - initialState.position_deg);
velocityBound_s = displacement_deg ./ limits.maxVelocity_deg_s;
duration_s = max([1e-3, velocityBound_s]);
end

function duration_s = movingTargetDurationLowerBound( ...
        initialState, goalState, limits)
% Bound linear-target interception without using a future snapshot.
duration_s = 1e-3;
if goalState.InterpolationMethod ~= "linear" || ...
        initialState.time_s < goalState.targetTime_s(1) || ...
        initialState.time_s > goalState.targetTime_s(end)
    return;
end
targetStart_deg = interp1( ...
    goalState.targetTime_s, goalState.targetPosition_deg, ...
    initialState.time_s, "linear");
targetVelocity_deg_s = diff(goalState.targetPosition_deg, 1, 1) ./ diff(goalState.targetTime_s);
targetSpeedBound_deg_s = max(abs(targetVelocity_deg_s), [], 1);
initialDistance_deg = abs(targetStart_deg - initialState.position_deg);
closingSpeedBound_deg_s = limits.maxVelocity_deg_s + ...
    targetSpeedBound_deg_s;
duration_s = max([duration_s, initialDistance_deg ./ closingSpeedBound_deg_s]);
end

function candidate = createEmptyCandidate(seed, segmentCount)
% Define the same candidate fields for early solver failures.
candidate = struct( ...
    "OptimizerFeasible", false, ...
    "ArrivalAtHorizon", false, ...
    "Message", "HS3 was not run.", ...
    "TerminationReason", "notRun", ...
    "SeedIndex", seed.Index, ...
    "SeedSource", seed.Source, ...
    "FinalTime_s", NaN, ...
    "MotionDuration_s", NaN, ...
    "MotionLength_deg", Inf, ...
    "IntegratedSquaredJerk_deg2_s5", Inf, ...
    "MaximumConstraintViolation", Inf, ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2), ...
    "Polynomial", struct("SegmentCount", segmentCount), ...
    "ControlTau", zeros(0, 1), ...
    "ControlJerk_deg_s3", zeros(0, 2), ...
    "Corridor", struct([]), ...
    "SeedCorridorBoundary_deg", seed.CorridorBoundary_deg, ...
    "SeedCorridor", struct([]), ...
    "SolverDiagnostics", ...
    obstacleAvoidance.planner.createEmptySolverDiagnostics());
end
