function [bounds, dynamics, checks] = validatePolynomialTrajectory( ...
        polynomial, time_s, position_deg, velocity_deg_s, ...
        acceleration_deg_s2, jerk_deg_s3, initialState, goalState, limits, ...
        options, tolerance, rangeCheck)
%% Section 0: Header & Readme
% SYNTAX
%   [bounds, dynamics, checks] = ...
%       obstacleAvoidance.planner.validatePolynomialTrajectory( ...
%       polynomial, time_s, position_deg, velocity_deg_s, ...
%       acceleration_deg_s2, jerk_deg_s3, initialState, goalState, limits, ...
%       options, tolerance, rangeCheck)
%**************************************************************************
% PURPOSE
%   - Validate the shared polynomial fields, time base, derivative dynamics,
%     segment continuity, endpoints, sampled histories, and continuous bounds.
%**************************************************************************
% INPUTS
%   - polynomial (scalar planner polynomial struct)
%       Complete piecewise-polynomial representation.
%   - time_s and sampled histories (numeric arrays)
%       Returned trajectory samples in their documented physical units.
%   - initialState, goalState, limits, options (scalar structs)
%       Resolved inputs governing endpoints, bounds, and coordinate wrapping.
%   - tolerance (nonnegative finite scalar)
%       Absolute state and polynomial consistency tolerance.
%   - rangeCheck (function handle)
%       Method-specific continuous polynomial range certificate.
%**************************************************************************
% OUTPUTS
%   - bounds, dynamics, checks (scalar structs)
%       Stable continuous-bound, derivative, field, and history checks.
%**************************************************************************
% UNITS
%   - Position is degrees. Derivatives use deg/s, deg/s^2, and deg/s^3.
%     Time is seconds.
%**************************************************************************

%% Section 1: Validate Polynomial Motion

% Work from the continuous polynomial rather than the displayed samples.
% Bernstein bounds cover each full segment for position and derivatives,
% while adaptive collision checking examines motion between samples against
% time-varying geometry. Reject a solver success if any independent check
% exceeds its named tolerance.
checks = createEmptyPolynomialChecks();
bounds = boundsRecord(false, false, false, false);
dynamics = struct("Consistent", false, "MaximumResidual", Inf);
requiredFields = {'SegmentCount', 'SegmentStartTime_s', ...
    'SegmentDuration_s', 'FinalTime_s', 'positionPower_deg', ...
    'velocityPower_deg_s', 'accelerationPower_deg_s2', 'jerkPower_deg_s3'};
hasFields = isstruct(polynomial) && isscalar(polynomial) && ...
    all(isfield(polynomial, requiredFields));
if ~hasFields
    return;
end
segmentCount = polynomial.SegmentCount;
segmentDuration_s = double(polynomial.SegmentDuration_s(:));
countIsValid = isnumeric(segmentCount) && isscalar(segmentCount) && ...
    isfinite(segmentCount) && segmentCount >= 1 && segmentCount == fix(segmentCount);
durationIsValid = isnumeric(polynomial.SegmentDuration_s) && ...
    any(numel(segmentDuration_s) == [1 segmentCount]) && ...
    all(isfinite(segmentDuration_s)) && all(segmentDuration_s > 0);
finalTimeIsValid = isnumeric(polynomial.FinalTime_s) && ...
    isscalar(polynomial.FinalTime_s) && isfinite(polynomial.FinalTime_s);
if ~(countIsValid && durationIsValid && finalTimeIsValid)
    return;
end
if isscalar(segmentDuration_s)
    segmentDuration_s = repmat(segmentDuration_s, segmentCount, 1);
end
segmentStartTime_s = double(polynomial.SegmentStartTime_s(:));
timeArrayIsValid = numel(segmentStartTime_s) == segmentCount && all(isfinite(segmentStartTime_s));
coefficientArrays = {polynomial.positionPower_deg, ...
    polynomial.velocityPower_deg_s, ...
    polynomial.accelerationPower_deg_s2, ...
    polynomial.jerkPower_deg_s3};
expectedSizes = {[segmentCount 2 6], [segmentCount 2 5], [segmentCount 2 4], [segmentCount 2 3]};
coefficientArraysAreValid = true;

% Confirm every derivative-order coefficient array has the required finite dimensions.
for arrayIndex = 1:numel(coefficientArrays)
    array = coefficientArrays{arrayIndex};
    coefficientArraysAreValid = coefficientArraysAreValid && ...
        isnumeric(array) && ...
        isequal(size(array), expectedSizes{arrayIndex}) && ...
        all(isfinite(array), "all");
end
checks.SchemaValid = timeArrayIsValid && coefficientArraysAreValid;
if ~checks.SchemaValid
    return;
end
expectedStartTime_s = segmentStartTime_s(1) + [0; cumsum(segmentDuration_s(1:end - 1))];
expectedFinalTime_s = segmentStartTime_s(1) + sum(segmentDuration_s);
timeTolerance_s = max(tolerance, ...
    100 * eps(max(1, ...
    max(abs([expectedStartTime_s; expectedFinalTime_s])))));
sampleTimeIsConsistent = ~isempty(time_s) && all(isfinite(time_s)) && ...
    abs(time_s(1) - segmentStartTime_s(1)) <= timeTolerance_s && ...
    abs(time_s(end) - expectedFinalTime_s) <= timeTolerance_s && ...
    all(time_s >= segmentStartTime_s(1) - timeTolerance_s) && ...
    all(time_s <= expectedFinalTime_s + timeTolerance_s);
checks.TimeBaseConsistent = sampleTimeIsConsistent && ...
    max(abs(segmentStartTime_s - expectedStartTime_s)) <= ...
    timeTolerance_s && abs(polynomial.FinalTime_s - expectedFinalTime_s) <= timeTolerance_s;
checks.InitialTimeMatched = abs( segmentStartTime_s(1) - initialState.time_s) <= timeTolerance_s;
positionWithinLimits = true;
velocityWithinLimits = true;
accelerationWithinLimits = true;
jerkWithinLimits = true;
maximumDynamicsResidual = 0;
maximumSegmentContinuityResidual = 0;
positionLower_deg = [limits.azimuthInterval_deg(1), limits.elevationInterval_deg(1)];
positionUpper_deg = [limits.azimuthInterval_deg(2), limits.elevationInterval_deg(2)];

% Validate continuous bounds, dynamics, and knot continuity for every segment.
for segmentIndex = 1:segmentCount

    % Check azimuth and elevation polynomials independently within this segment.
    for axisIndex = 1:2
        positionPower = coefficients( polynomial.positionPower_deg, segmentIndex, axisIndex);
        velocityPower = coefficients( polynomial.velocityPower_deg_s, segmentIndex, axisIndex);
        accelerationPower = coefficients( ...
            polynomial.accelerationPower_deg_s2, segmentIndex, axisIndex);
        jerkPower = coefficients( polynomial.jerkPower_deg_s3, segmentIndex, axisIndex);
        if ~(axisIndex == 1 && options.AllowAzimuthWrapping)
            positionWithinLimits = positionWithinLimits && rangeCheck( ...
                positionPower, positionLower_deg(axisIndex), ...
                positionUpper_deg(axisIndex), tolerance);
        end
        velocityWithinLimits = velocityWithinLimits && rangeCheck( ...
            velocityPower, -limits.maxVelocity_deg_s(axisIndex), ...
            limits.maxVelocity_deg_s(axisIndex), tolerance);
        accelerationWithinLimits = accelerationWithinLimits && ...
            rangeCheck(accelerationPower, ...
            -limits.maxAcceleration_deg_s2(axisIndex), ...
            limits.maxAcceleration_deg_s2(axisIndex), tolerance);
        jerkWithinLimits = jerkWithinLimits && rangeCheck( ...
            jerkPower, -limits.maxJerk_deg_s3(axisIndex), ...
            limits.maxJerk_deg_s3(axisIndex), tolerance);
        positionDerivative = (1:numel(positionPower) - 1).' .* ...
            positionPower(2:end) / segmentDuration_s(segmentIndex);
        velocityDerivative = (1:numel(velocityPower) - 1).' .* ...
            velocityPower(2:end) / segmentDuration_s(segmentIndex);
        accelerationDerivative = (1:numel(accelerationPower) - 1).' .* ...
            accelerationPower(2:end) / segmentDuration_s(segmentIndex);
        maximumDynamicsResidual = max(maximumDynamicsResidual, max([ ...
            abs(positionDerivative - velocityPower); ...
            abs(velocityDerivative - accelerationPower); abs(accelerationDerivative - jerkPower)]));
        if segmentIndex < segmentCount
            nextPositionPower = coefficients( ...
                polynomial.positionPower_deg, segmentIndex + 1, axisIndex);
            nextVelocityPower = coefficients( ...
                polynomial.velocityPower_deg_s, ...
                segmentIndex + 1, axisIndex);
            nextAccelerationPower = coefficients( ...
                polynomial.accelerationPower_deg_s2, ...
                segmentIndex + 1, axisIndex);
            continuityResidual = [ ...
                sum(positionPower) - nextPositionPower(1); ...
                sum(velocityPower) - nextVelocityPower(1); ...
                sum(accelerationPower) - nextAccelerationPower(1)];
            maximumSegmentContinuityResidual = max( ...
                maximumSegmentContinuityResidual, ...
                max(abs(continuityResidual)));
        end
    end
end
bounds = boundsRecord(positionWithinLimits, velocityWithinLimits, ...
    accelerationWithinLimits, jerkWithinLimits);
dynamics = struct( ...
    "Consistent", maximumDynamicsResidual <= tolerance, ...
    "MaximumResidual", maximumDynamicsResidual);
checks.MaximumSegmentContinuityResidual = maximumSegmentContinuityResidual;
checks.SegmentContinuity = maximumSegmentContinuityResidual <= tolerance;
initialPolynomialState = [ ...
    reshape(polynomial.positionPower_deg(1, :, 1), 1, 2), ...
    reshape(polynomial.velocityPower_deg_s(1, :, 1), 1, 2), ...
    reshape(polynomial.accelerationPower_deg_s2(1, :, 1), 1, 2)];
terminalPosition_deg = sum(reshape( polynomial.positionPower_deg(end, :, :), 2, []), 2).';
terminalVelocity_deg_s = sum(reshape( polynomial.velocityPower_deg_s(end, :, :), 2, []), 2).';
terminalAcceleration_deg_s2 = sum(reshape( ...
    polynomial.accelerationPower_deg_s2(end, :, :), 2, []), 2).';
goalPosition_deg = obstacleAvoidance.input.goalPositionAtTime( ...
    goalState, polynomial.FinalTime_s);
expectedEndpointState = [initialState.position_deg, ...
    initialState.velocity_deg_s, initialState.acceleration_deg_s2, ...
    goalPosition_deg, goalState.velocity_deg_s, goalState.acceleration_deg_s2];
polynomialEndpointState = [initialPolynomialState, ...
    terminalPosition_deg, terminalVelocity_deg_s, terminalAcceleration_deg_s2];
checks.EndpointStatesMatched = max(abs( ...
    polynomialEndpointState - expectedEndpointState)) <= tolerance;
[~, polynomialPosition_deg, polynomialVelocity_deg_s, ...
    polynomialAcceleration_deg_s2, polynomialJerk_deg_s3] = ...
    obstacleAvoidance.planner.evaluatePlannerPolynomial(polynomial, time_s);
historySizesMatch = isequal(size(position_deg), ...
    size(polynomialPosition_deg)) && isequal(size(velocity_deg_s), ...
    size(polynomialVelocity_deg_s)) && ...
    isequal(size(acceleration_deg_s2), ...
    size(polynomialAcceleration_deg_s2)) && isequal(size(jerk_deg_s3), size(polynomialJerk_deg_s3));
if historySizesMatch
    checks.MaximumHistoryResidual = max(abs([ ...
        position_deg - polynomialPosition_deg, ...
        velocity_deg_s - polynomialVelocity_deg_s, ...
        acceleration_deg_s2 - polynomialAcceleration_deg_s2, ...
        jerk_deg_s3 - polynomialJerk_deg_s3]), [], "all");
    checks.HistoryConsistent = checks.MaximumHistoryResidual <= tolerance;
end
checks.Valid = checks.SchemaValid && checks.InitialTimeMatched && ...
    checks.TimeBaseConsistent && checks.SegmentContinuity && ...
    checks.EndpointStatesMatched && checks.HistoryConsistent;
end

%% Section 2: Local Functions

function checks = createEmptyPolynomialChecks()
% Define stable polynomial checks for every invalid data format.
checks = struct( ...
    "Valid", false, "SchemaValid", false, ...
    "InitialTimeMatched", false, ...
    "TimeBaseConsistent", false, "SegmentContinuity", false, ...
    "EndpointStatesMatched", false, "HistoryConsistent", false, ...
    "MaximumSegmentContinuityResidual", Inf, "MaximumHistoryResidual", Inf);
end

function bounds = boundsRecord(position, velocity, acceleration, jerk)
% Assemble continuous-bound checks in stable order.
bounds = struct( ...
    "Valid", position && velocity && acceleration && jerk, ...
    "PositionWithinLimits", position, ...
    "VelocityWithinLimits", velocity, ...
    "AccelerationWithinLimits", acceleration, ...
    "JerkWithinLimits", jerk);
end

function value = coefficients(array, segmentIndex, axisIndex)
% Read one ascending polynomial coefficient column.
value = reshape(array(segmentIndex, axisIndex, :), [], 1);
end
