function validation = validateAzElTrajectory(trajectory, obstacles, initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   validation = validateAzElTrajectory()
%   validation = validateAzElTrajectory(result)
%   validation = validateAzElTrajectory( ...
%       trajectory, obstacles, initialState, goalState, limits, options)
%**************************************************************************
% PURPOSE
%   - Independently validate one complete polynomial motion and geometry.
%   - Fail unresolved continuous-collision intervals instead of accepting them.
%**************************************************************************
% INPUTS
%   - trajectory (scalar candidate or planner-result struct)
%       Must contain sampled histories and Polynomial segment coefficients.
%   - obstacles (canonical protected obstacle array, optional with result)
%   - initialState, goalState (normalized state structs, optional with result)
%   - limits (normalized physical limits struct, optional with result)
%   - options (resolved planner options, optional with result)
%**************************************************************************
% OUTPUTS
%   - validation (scalar struct)
%       Stable checks, clearance, message, collision time, and total time.
%**************************************************************************
% UNITS
%   - Position and clearance are degrees. Derivatives use deg/s, deg/s^2,
%     and deg/s^3. Time is seconds.
%**************************************************************************
if nargin == 0
    validation = emptyValidation();
    return;
end
validationTimer = tic;

%% Section 1: Resolve Inputs And Basic History Checks

if nargin == 1
    requiredResultFields = {'Inputs', 'Options', 'Polynomial'};
    if ~isstruct(trajectory) || ~isscalar(trajectory) || ~all(isfield(trajectory, requiredResultFields))
        error("validateAzElTrajectory:InvalidResult", ...
            "A one-input call requires a planner result with Inputs, " + "Options, and Polynomial fields.");
    end
    obstacles = trajectory.Inputs.obstacles;
    initialState = trajectory.Inputs.initialState;
    goalState = trajectory.Inputs.goalState;
    limits = trajectory.Inputs.limits;
    options = trajectory.Options;
elseif nargin ~= 6
    error("validateAzElTrajectory:InvalidCall", "Use one planner result or all six explicit validation inputs.");
end
if isempty(obstacles) || ~isfield(obstacles, "InternalPreparation")
    obstacles = azElObstacles.combineAzElObstacles(obstacles);
    obstacles = azElObstacles.prepareDynamic(obstacles);
end
hasMovingGoal = isfield(goalState, "targetTime_s") && ~isempty(goalState.targetTime_s);
if options.AllowAzimuthWrapping && (~isempty(obstacles) || hasMovingGoal)
    error("validateAzElTrajectory:UnsupportedWrappedGeometry", ...
        "Wrapped validation is supported only for obstacle-free " + "fixed-position goals.");
end
requiredFields = {'time_s', 'position_deg', 'velocity_deg_s', 'acceleration_deg_s2', 'jerk_deg_s3', 'Polynomial'};
hasRequiredFields = isstruct(trajectory) && isscalar(trajectory) && all(isfield(trajectory, requiredFields));
if ~hasRequiredFields
    error("validateAzElTrajectory:InvalidTrajectory", "trajectory must contain sampled histories and Polynomial data.");
end
time_s = double(trajectory.time_s(:));
position_deg = double(trajectory.position_deg);
velocity_deg_s = double(trajectory.velocity_deg_s);
acceleration_deg_s2 = double(trajectory.acceleration_deg_s2);
jerk_deg_s3 = double(trajectory.jerk_deg_s3);
sampleCount = numel(time_s);
historySizesMatch = isequal(size(position_deg), [sampleCount 2]) && ...
    isequal(size(velocity_deg_s), [sampleCount 2]) && ...
    isequal(size(acceleration_deg_s2), [sampleCount 2]) && isequal(size(jerk_deg_s3), [sampleCount 2]);
timeIsFinite = ~isempty(time_s) && all(isfinite(time_s));
timeIsStrictlyIncreasing = timeIsFinite && all(diff(time_s) > 0);
historyIsFinite = sampleCount > 0 && historySizesMatch && ...
    all(isfinite(position_deg), "all") && ...
    all(isfinite(velocity_deg_s), "all") && ...
    all(isfinite(acceleration_deg_s2), "all") && all(isfinite(jerk_deg_s3), "all");

%% Section 2: Validate Endpoints And Continuous Polynomial Bounds

stateTolerance = max(10 * options.ConstraintTolerance, 1e-7);
initialStateMatched = historyIsFinite && ...
    max(abs(position_deg(1, :) - initialState.position_deg)) <= ...
    stateTolerance && ...
    max(abs(velocity_deg_s(1, :) - initialState.velocity_deg_s)) <= ...
    stateTolerance && max(abs(acceleration_deg_s2(1, :) - initialState.acceleration_deg_s2)) <= stateTolerance;
if timeIsFinite
goalPosition_deg = azElInput.goalPositionAtTime( ...
        goalState, time_s(end));
else
    goalPosition_deg = [NaN NaN];
end
terminalStateMatched = historyIsFinite && ...
    max(abs(position_deg(end, :) - goalPosition_deg)) <= stateTolerance && ...
    max(abs(velocity_deg_s(end, :) - goalState.velocity_deg_s)) <= ...
    stateTolerance && max(abs(acceleration_deg_s2(end, :) - goalState.acceleration_deg_s2)) <= stateTolerance;
if options.GoalTimeMode == "fixedArrival"
    goalTimeSatisfied = timeIsFinite && abs(time_s(end) - goalState.time_s) <= stateTolerance;
else
    goalTimeSatisfied = timeIsFinite && ...
        time_s(end) <= goalState.time_s + stateTolerance && time_s(end) > initialState.time_s;
end
[continuousBounds, dynamics, polynomialChecks] = ...
    azElPlanner.validatePolynomialTrajectory( ...
    trajectory.Polynomial, time_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, jerk_deg_s3, initialState, goalState, limits, ...
    options, stateTolerance, @withinBounds);

%% Section 3: Certify Continuous Collision Freedom

collisionTimer = tic;
if timeIsStrictlyIncreasing && historyIsFinite && continuousBounds.Valid
    [seedCorridorCertified, seedCorridorClearance_deg] = azElSearch.certifySeedCorridor( ...
        trajectory, obstacles, options.CollisionClearanceTolerance_deg);
    if seedCorridorCertified
        collisionFree = true;
        collisionResolved = true;
        minimumClearance_deg = seedCorridorClearance_deg;
        collisionCheckCount = 0;
        unresolvedIntervalCount = 0;
    else
        [collisionFree, collisionResolved, minimumClearance_deg, ...
            collisionCheckCount, unresolvedIntervalCount] = certifyCollision( ...
            trajectory.Polynomial, obstacles, limits, options);
    end
else
    seedCorridorCertified = false;
    collisionFree = false;
    collisionResolved = false;
    minimumClearance_deg = NaN;
    collisionCheckCount = 0;
    unresolvedIntervalCount = 0;
end
collisionCheckingElapsedTime_s = toc(collisionTimer);
safetyMarginPolicySatisfied = true;

% Verify every protected obstacle retains original-boundary and margin provenance.
for obstacleIndex = 1:numel(obstacles)
    obstacle = obstacles(obstacleIndex);
    obstacleHasProvenance = isfield(obstacle, "originalAz_deg") && ...
        isfield(obstacle, "originalEl_deg") && isfinite(obstacle.safetyMargin_deg) && obstacle.safetyMargin_deg >= 0;
    safetyMarginPolicySatisfied = safetyMarginPolicySatisfied && obstacleHasProvenance;
end
azimuthWrapPolicySatisfied = options.AllowAzimuthWrapping || continuousBounds.PositionWithinLimits;

%% Section 4: Assemble The Stable Validation Record

passed = historySizesMatch && timeIsStrictlyIncreasing && ...
    historyIsFinite && initialStateMatched && terminalStateMatched && ...
    goalTimeSatisfied && polynomialChecks.Valid && ...
    continuousBounds.Valid && dynamics.Consistent && ...
    collisionFree && collisionResolved && safetyMarginPolicySatisfied && azimuthWrapPolicySatisfied;
issues = strings(0, 1);
checkNames = [ ...
    "history shape", "finite increasing time", "finite histories", ...
    "initial state", "terminal state", "goal time", ...
    "polynomial schema", "polynomial initial time", ...
    "polynomial time base", ...
    "polynomial segment continuity", "polynomial endpoint states", ...
    "polynomial sampled histories", "continuous limits", ...
    "polynomial dynamics", "collision freedom", ...
    "collision resolution", "safety-margin provenance", "azimuth-wrap policy"];
checkValues = [ ...
    historySizesMatch, timeIsStrictlyIncreasing, historyIsFinite, ...
    initialStateMatched, terminalStateMatched, goalTimeSatisfied, ...
    polynomialChecks.SchemaValid, polynomialChecks.InitialTimeMatched, ...
    polynomialChecks.TimeBaseConsistent, ...
    polynomialChecks.SegmentContinuity, ...
    polynomialChecks.EndpointStatesMatched, ...
    polynomialChecks.HistoryConsistent, continuousBounds.Valid, ...
    dynamics.Consistent, collisionFree, collisionResolved, safetyMarginPolicySatisfied, azimuthWrapPolicySatisfied];

% Collect every failed check name for the public validation message.
for checkIndex = 1:numel(checkNames)
    if ~checkValues(checkIndex)
        issues(end + 1, 1) = checkNames(checkIndex); %#ok<AGROW>
    end
end
if passed
    message = "Independent continuous validation passed.";
else
    message = "Independent validation failed: " + strjoin(issues, ", ") + ".";
end
validation = struct( ...
    "Passed", passed, ...
    "Message", message, ...
    "HistorySizesMatch", historySizesMatch, ...
    "TimeIsFinite", timeIsFinite, ...
    "TimeIsStrictlyIncreasing", timeIsStrictlyIncreasing, ...
    "HistoryIsFinite", historyIsFinite, ...
    "InitialStateMatched", initialStateMatched, ...
    "TerminalStateMatched", terminalStateMatched, ...
    "GoalTimeSatisfied", goalTimeSatisfied, ...
    "PolynomialSchemaValid", polynomialChecks.SchemaValid, ...
    "PolynomialInitialTimeMatched", ...
    polynomialChecks.InitialTimeMatched, ...
    "PolynomialTimeBaseConsistent", ...
    polynomialChecks.TimeBaseConsistent, ...
    "PolynomialSegmentContinuity", ...
    polynomialChecks.SegmentContinuity, ...
    "PolynomialEndpointStatesMatched", ...
    polynomialChecks.EndpointStatesMatched, ...
    "PolynomialHistoryConsistent", ...
    polynomialChecks.HistoryConsistent, ...
    "MaximumSegmentContinuityResidual", ...
    polynomialChecks.MaximumSegmentContinuityResidual, ...
    "MaximumPolynomialHistoryResidual", ...
    polynomialChecks.MaximumHistoryResidual, ...
    "PositionWithinLimits", continuousBounds.PositionWithinLimits, ...
    "VelocityWithinLimits", continuousBounds.VelocityWithinLimits, ...
    "AccelerationWithinLimits", ...
    continuousBounds.AccelerationWithinLimits, ...
    "JerkWithinLimits", continuousBounds.JerkWithinLimits, ...
    "DynamicsConsistent", dynamics.Consistent, ...
    "MaximumDynamicsResidual", dynamics.MaximumResidual, ...
    "CollisionFree", collisionFree, ...
    "CollisionResolved", collisionResolved, ...
    "SeedCorridorCertified", seedCorridorCertified, ...
    "MinimumClearance_deg", minimumClearance_deg, ...
    "CollisionCheckCount", collisionCheckCount, ...
    "UnresolvedIntervalCount", unresolvedIntervalCount, ...
    "SafetyMarginPolicySatisfied", safetyMarginPolicySatisfied, ...
    "AzimuthWrapPolicySatisfied", azimuthWrapPolicySatisfied, ...
    "PeakVelocity_deg_s", maximumAbsolute(velocity_deg_s), ...
    "PeakAcceleration_deg_s2", maximumAbsolute(acceleration_deg_s2), ...
    "PeakJerk_deg_s3", maximumAbsolute(jerk_deg_s3), "Issues", issues, ...
    "CollisionCheckingElapsedTime_s", 0, "ElapsedTime_s", 0);
totalElapsedTime_s = toc(validationTimer);
validation.CollisionCheckingElapsedTime_s = ...
    collisionCheckingElapsedTime_s;
validation.ElapsedTime_s = totalElapsedTime_s;
end


function within = withinBounds(powerCoefficient, lower, upper, tolerance)
% Check the exact low-degree polynomial range on normalized [0, 1].
derivativeCoefficient = (1:numel(powerCoefficient) - 1).' .* powerCoefficient(2:end);
lastDerivativeIndex = find(derivativeCoefficient ~= 0, 1, "last");
candidateTau = [0; 1];
if ~isempty(lastDerivativeIndex)
    stationaryRoot = roots(flip( derivativeCoefficient(1:lastDerivativeIndex)));
    rootTolerance = 1e-9;
    stationaryTau = real(stationaryRoot);
    stationaryTau = stationaryTau( stationaryTau >= -rootTolerance & stationaryTau <= 1 + rootTolerance);
    candidateTau = [candidateTau; min(max(stationaryTau, 0), 1)];
end
candidateValue = polyval(flip(powerCoefficient), candidateTau);
within = all(candidateValue >= lower - tolerance & candidateValue <= upper + tolerance);
end

function [collisionFree, resolved, minimumClearance_deg, ...
        checkCount, unresolvedCount] = certifyCollision( polynomial, obstacles, limits, options)
% Certify moving-obstacle clearance with conservative adaptive intervals.
if isempty(obstacles)
    collisionFree = true;
    resolved = true;
    minimumClearance_deg = Inf;
    checkCount = 0;
    unresolvedCount = 0;
    return;
end
collisionFree = true;
resolved = true;
minimumClearance_deg = Inf;
checkCount = 0;
unresolvedCount = 0;
pathSpeedBound_deg_s = norm(limits.maxVelocity_deg_s);
obstacleHistoryBounds_deg = zeros(numel(obstacles), 4);

% Hoist input-derived complete-history boxes used by every adaptive interval.
for obstacleIndex = 1:numel(obstacles)
    obstacleHistoryBounds_deg(obstacleIndex, :) = ...
        obstacles(obstacleIndex).InternalPreparation.HistoryBounds_deg;
end

% Certify collision freedom independently over every polynomial segment.
for segmentIndex = 1:polynomial.SegmentCount
    segmentStart_s = polynomial.SegmentStartTime_s(segmentIndex);
    if isscalar(polynomial.SegmentDuration_s)
        segmentEnd_s = segmentStart_s + polynomial.SegmentDuration_s;
    else
        segmentEnd_s = segmentStart_s + polynomial.SegmentDuration_s(segmentIndex);
    end
    splitTimes_s = [segmentStart_s; segmentEnd_s];

    % Insert every obstacle history time that falls inside the current segment.
    for obstacleIndex = 1:numel(obstacles)
        obstacleTimes_s = obstacles(obstacleIndex).time_s(:);
        splitTimes_s = [splitTimes_s; obstacleTimes_s( ...
            obstacleTimes_s > segmentStart_s & obstacleTimes_s < segmentEnd_s)]; %#ok<AGROW>
    end
    splitTimes_s = unique(splitTimes_s);

    % Check each segment or obstacle-history breakpoint explicitly.
    for splitIndex = 1:numel(splitTimes_s)
        [~, splitPoint_deg] = azElPlanner.evaluateAzElPolynomial( ...
            polynomial, splitTimes_s(splitIndex), segmentIndex);

        % Measure the breakpoint position against every obstacle at that exact time.
        for obstacleIndex = 1:numel(obstacles)
            historyBounds_deg = obstacleHistoryBounds_deg(obstacleIndex, :);
            axisDistance_deg = max([ ...
                historyBounds_deg([1 3]) - splitPoint_deg; ...
                zeros(1, 2); ...
                splitPoint_deg - historyBounds_deg([2 4])], [], 1);
            historyClearanceLowerBound_deg = norm(axisDistance_deg);
            if historyClearanceLowerBound_deg > ...
                    options.CollisionClearanceTolerance_deg
                minimumClearance_deg = min(minimumClearance_deg, ...
                    historyClearanceLowerBound_deg);
                continue;
            end
            shape = azElObstacles.shapeAtTime( ...
                obstacles(obstacleIndex), splitTimes_s(splitIndex));
            clearance_deg = azElGeometry.pointPolygonClearance( shape, splitPoint_deg);
            checkCount = checkCount + 1;
            minimumClearance_deg = min( minimumClearance_deg, clearance_deg);
            if clearance_deg <= options.CollisionClearanceTolerance_deg
                collisionFree = false;
                resolved = true;
                return;
            end
        end
    end
    stackStart_s = splitTimes_s(1:end - 1);
    stackEnd_s = splitTimes_s(2:end);

    % Bisect unresolved intervals until clearance is certified or resolution is exhausted.
    while ~isempty(stackStart_s)
        intervalStart_s = stackStart_s(end);
        intervalEnd_s = stackEnd_s(end);
        stackStart_s(end) = [];
        stackEnd_s(end) = [];
        intervalMid_s = (intervalStart_s + intervalEnd_s) / 2;
        [~, point_deg] = azElPlanner.evaluateAzElPolynomial( ...
            polynomial, intervalMid_s, segmentIndex);
        intervalResolved = true;
        intervalClearanceLowerBound_deg = Inf;

        % Bound relative motion against every obstacle over the current interval.
        for obstacleIndex = 1:numel(obstacles)
            historyBounds_deg = obstacleHistoryBounds_deg(obstacleIndex, :);
            axisDistance_deg = max([ ...
                historyBounds_deg([1 3]) - point_deg; ...
                zeros(1, 2); ...
                point_deg - historyBounds_deg([2 4])], [], 1);
            maximumPathDisplacement_deg = pathSpeedBound_deg_s * ...
                (intervalEnd_s - intervalStart_s) / 2;
            historyClearanceLowerBound_deg = ...
                norm(axisDistance_deg) - maximumPathDisplacement_deg;
            if historyClearanceLowerBound_deg > ...
                    options.CollisionClearanceTolerance_deg
                intervalClearanceLowerBound_deg = min( ...
                    intervalClearanceLowerBound_deg, ...
                    historyClearanceLowerBound_deg);
                continue;
            end
            [shape, geometry] = azElObstacles.shapeAtTime( ...
                obstacles(obstacleIndex), intervalMid_s);
            clearance_deg = azElGeometry.pointPolygonClearance( shape, point_deg);
            checkCount = checkCount + 1;
            if clearance_deg <= options.CollisionClearanceTolerance_deg
                minimumClearance_deg = min( minimumClearance_deg, clearance_deg);
                collisionFree = false;
                resolved = true;
                return;
            end
            relativeSpeedBound_deg_s = pathSpeedBound_deg_s + geometry.VertexSpeedBound_deg_s;
            crossingBound_deg = relativeSpeedBound_deg_s * (intervalEnd_s - intervalStart_s) / 2;
            intervalClearanceLowerBound_deg = min( intervalClearanceLowerBound_deg, clearance_deg - crossingBound_deg);
            intervalResolved = intervalResolved && isfinite(crossingBound_deg) && ...
                clearance_deg > crossingBound_deg + options.CollisionClearanceTolerance_deg;
        end
        if intervalResolved
            minimumClearance_deg = min( minimumClearance_deg, intervalClearanceLowerBound_deg);
            continue;
        end
        intervalDuration_s = intervalEnd_s - intervalStart_s;
        if intervalDuration_s <= options.CollisionMinimumTimeStep_s
            resolved = false;
            collisionFree = false;
            unresolvedCount = unresolvedCount + 1;
            return;
        end
        stackStart_s = [stackStart_s; intervalStart_s; intervalMid_s]; %#ok<AGROW>
        stackEnd_s = [stackEnd_s; intervalMid_s; intervalEnd_s]; %#ok<AGROW>
    end
end
end

function peak = maximumAbsolute(values)
% Return per-axis sampled peaks with stable NaNs for empty histories.
if isempty(values)
    peak = [NaN NaN];
else
    peak = max(abs(values), [], 1);
end
end

function validation = emptyValidation()
% Define the stable public validation schema for unavailable checks.
validation = struct( ...
    "Passed", false, "Message", "No trajectory was validated.", ...
    "HistorySizesMatch", false, "TimeIsFinite", false, ...
    "TimeIsStrictlyIncreasing", false, "HistoryIsFinite", false, ...
    "InitialStateMatched", false, "TerminalStateMatched", false, ...
    "GoalTimeSatisfied", false, "PolynomialSchemaValid", false, ...
    "PolynomialInitialTimeMatched", false, ...
    "PolynomialTimeBaseConsistent", false, ...
    "PolynomialSegmentContinuity", false, ...
    "PolynomialEndpointStatesMatched", false, ...
    "PolynomialHistoryConsistent", false, ...
    "MaximumSegmentContinuityResidual", NaN, ...
    "MaximumPolynomialHistoryResidual", NaN, ...
    "PositionWithinLimits", false, "VelocityWithinLimits", false, ...
    "AccelerationWithinLimits", false, "JerkWithinLimits", false, ...
    "DynamicsConsistent", false, "MaximumDynamicsResidual", NaN, ...
    "CollisionFree", false, "CollisionResolved", false, ...
    "SeedCorridorCertified", false, "MinimumClearance_deg", NaN, ...
    "CollisionCheckCount", 0, "UnresolvedIntervalCount", 0, ...
    "SafetyMarginPolicySatisfied", false, ...
    "AzimuthWrapPolicySatisfied", false, ...
    "PeakVelocity_deg_s", [NaN NaN], ...
    "PeakAcceleration_deg_s2", [NaN NaN], ...
    "PeakJerk_deg_s3", [NaN NaN], "Issues", strings(0, 1), ...
    "CollisionCheckingElapsedTime_s", 0, "ElapsedTime_s", 0);
end
