function model = buildFixedDurationAffineModel( ...
        controlPointCount, initialTime_s, spanDuration_s, sampleTime_s)
%% Section 0: Header & Readme
% SYNTAX
%   model = azElPlannerMethods.corridor.internal.motion.buildFixedDurationAffineModel( ...
%       controlPointCount, initialTime_s, spanDuration_s, sampleTime_s)
%**************************************************************************
% PURPOSE
%   - Build the exact fixed-duration affine map shared by corridor motion
%     paths. The helper owns identity-control conversion, sampled bases, and
%     the common endpoint-fixed decision ordering; callers retain policies,
%     objectives, bounds, and solver choices.
%**************************************************************************
% INPUTS
%   - controlPointCount (integer scalar), number of quintic controls.
%   - initialTime_s (finite scalar), first physical segment time.
%   - spanDuration_s (positive vector), fixed physical span durations.
%   - sampleTime_s (finite vector), absolute basis-evaluation times.
%**************************************************************************
% OUTPUTS
%   - model (scalar struct), exact polynomial and sampled affine bases.
%**************************************************************************

degree = 5;
validateattributes(controlPointCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', degree + 1});
validateattributes(initialTime_s, {'numeric'}, {'real', 'finite', 'scalar'});
validateattributes(spanDuration_s, {'numeric'}, ...
    {'real', 'finite', 'vector', 'positive'});
if isempty(sampleTime_s)
    sampleTime_s = zeros(0, 1);
else
    validateattributes(sampleTime_s, {'numeric'}, {'real', 'finite', 'vector'});
end
spanDuration_s = double(spanDuration_s(:));
sampleTime_s = double(sampleTime_s(:));
variableControlIndex = 4:controlPointCount - 3;
fixedControlIndex = [1:3, controlPointCount - 2:controlPointCount];
% "Unit control" denotes identity control coordinates; durations stay physical.
unitControlPolynomial = ...
    azElPlannerMethods.corridor.internal.motion.convertBsplineToPolynomial( ...
    eye(controlPointCount), degree, initialTime_s, spanDuration_s);
[~, positionBasis, velocityBasis, accelerationBasis, jerkBasis] = ...
    azElInternal.evaluatePolynomial( ...
    unitControlPolynomial, sampleTime_s);
model = struct( ...
    "Degree", degree, ...
    "VariableControlIndex", variableControlIndex, ...
    "FixedControlIndex", fixedControlIndex, ...
    "VariableControlCount", numel(variableControlIndex), ...
    "ReferenceDuration_s", sum(spanDuration_s), ...
    "SampleTime_s", sampleTime_s, ...
    "UnitControlPolynomial", unitControlPolynomial, ...
    "PositionBasis", positionBasis, ...
    "VelocityBasis", velocityBasis, ...
    "AccelerationBasis", accelerationBasis, ...
    "JerkBasis", jerkBasis);
end
