function visibilityGraph = createVisibilityGraph(proposal, request)
%% Section 0: Header & Readme
% SYNTAX
%   visibilityGraph = ...
%       obstacleAvoidance.search.createVisibilityGraph(proposal, request)
%**************************************************************************
% PURPOSE
%   - Retry offset visibility attempts until endpoints connect or bounds end.
%   - Return all attempts and the final graph used by route search.
%**************************************************************************
% INPUTS
%   - proposal (scalar proposal-geometry struct)
%       Spatial shape, endpoints, and reusable boundary edges.
%   - request (scalar planning-request struct)
%       Normalized limits and resolved planner options.
%**************************************************************************
% OUTPUTS
%   - visibilityGraph (scalar struct)
%       Final nodes and costs, all offset attempts, and the legacy graph
%       record consumed by existing search diagnostics.
%**************************************************************************
% UNITS
%   - Positions, graph costs, bounds, and offsets are degrees.
%**************************************************************************

%% Section 1: Create The Offset Schedule Inputs

% Visibility nodes must sit outside proposal obstacles, but a small offset can
% leave components disconnected near narrow geometry. Derive the initial
% numerical offset and maximum physical retry from the supplied geometry and
% workspace rather than a scenario-specific schedule.

shape = proposal.shape;
start_deg = proposal.start_deg;
goal_deg = proposal.goal_deg;
limits = request.limits;
allPositions_deg = [start_deg; goal_deg; shape.Vertices];
coordinateScale_deg = ...
    bmtpEngine.createCoordinateTolerances(allPositions_deg);
baseOffset_deg = max(1e-3, 256 * eps(coordinateScale_deg));
maximumOffset_deg = max([diff(limits.azimuthInterval_deg), ...
    diff(limits.elevationInterval_deg)]);
workBudget = 1e6;

%% Section 2: Retry Visibility Attempts

% Each attempt owns node selection, pair construction, segment checks, and
% bounded connectivity recovery. Only its graph connectivity determines
% whether a wider offset is needed; none of these spatial checks can approve
% the eventual timed motion.

attempts = repmat(createEmptyAttempt(), 0, 1);
candidateOffset_deg = baseOffset_deg;
offsetRetryCount = 0;
anyExhaustiveUsed = false;
anyExhaustiveFallbackUsed = false;
while true
    obstacleAvoidance.input.throwIfCancellationRequested(request.options);
    attempt = obstacleAvoidance.search.createVisibilityAttempt( ...
        shape, start_deg, goal_deg, limits, candidateOffset_deg, ...
        offsetRetryCount, workBudget);
    attempts(end + 1, 1) = attempt; %#ok<AGROW>
    anyExhaustiveUsed = anyExhaustiveUsed || ...
        attempt.ExhaustiveVisibilityUsed;
    anyExhaustiveFallbackUsed = anyExhaustiveFallbackUsed || ...
        attempt.ExhaustiveVisibilityFallbackUsed;
    if attempt.IsConnected || candidateOffset_deg >= maximumOffset_deg
        break;
    end
    candidateOffset_deg = min( ...
        4 * candidateOffset_deg, maximumOffset_deg);
    offsetRetryCount = offsetRetryCount + 1;
end

%% Section 3: Create The Final Graph Record

% Existing route diagnostics consume the final attempt while two exhaustive
% flags historically summarize every retry. Preserve that contract and keep
% the complete attempts beside it for direct stage inspection.

finalAttempt = attempts(end);
minimum_deg = min(allPositions_deg, [], 1);
maximum_deg = max(allPositions_deg, [], 1);
record = struct( ...
    "Bounds_deg", [minimum_deg(1), maximum_deg(1), ...
    minimum_deg(2), maximum_deg(2)], ...
    "CandidateOffset_deg", finalAttempt.CandidateOffset_deg, ...
    "CandidateOffsetRetryCount", finalAttempt.OffsetRetryCount, ...
    "VisibilityWorkBudget", workBudget, ...
    "EstimatedExhaustiveVisibilityWork", ...
    finalAttempt.EstimatedExhaustiveVisibilityWork, ...
    "ExhaustiveVisibilityUsed", anyExhaustiveUsed, ...
    "ExhaustiveVisibilityFallbackUsed", ...
    anyExhaustiveFallbackUsed, ...
    "VisibilityCandidatePairCount", ...
    finalAttempt.VisibilityCandidatePairCount, ...
    "VisibilityEdgeCount", finalAttempt.VisibilityEdgeCount, ...
    "AcceptedEdges_deg", finalAttempt.AcceptedEdges_deg, ...
    "RejectedEdges_deg", finalAttempt.RejectedEdges_deg, ...
    "RejectedTransitionCount", ...
    finalAttempt.RejectedTransitionCount);
visibilityGraph = struct( ...
    "NodePosition_deg", finalAttempt.Nodes.Positions_deg, ...
    "EdgeCost_deg", finalAttempt.Cost_deg, ...
    "Attempts", attempts, ...
    "FinalAttemptIndex", numel(attempts), ...
    "IsConnected", finalAttempt.IsConnected, ...
    "Record", record);
end

%% Section 4: Local Functions

function attempt = createEmptyAttempt()
% Define stable field order for the dynamically sized attempt collection.
attempt = struct( ...
    "OffsetRetryCount", 0, ...
    "CandidateOffset_deg", NaN, ...
    "Nodes", struct(), ...
    "InitialPairSet", struct(), ...
    "FinalCandidatePairs", zeros(0, 2), ...
    "AcceptedEdges_deg", zeros(0, 4), ...
    "RejectedEdges_deg", zeros(0, 4), ...
    "EdgeRejectionReasons", strings(0, 1), ...
    "GraphComponents", zeros(1, 0), ...
    "RecoverySteps", strings(0, 1), ...
    "ExhaustiveVisibilityUsed", false, ...
    "ExhaustiveVisibilityFallbackUsed", false, ...
    "IsConnected", false, ...
    "Cost_deg", zeros(0), ...
    "VisibilityEdgeCount", 0, ...
    "RejectedTransitionCount", 0, ...
    "VisibilityCandidatePairCount", 0, ...
    "EstimatedExhaustiveVisibilityWork", 0);
end
