function diagnostics = createSearchDiagnostics( ...
        proposal, visibilityGraph, routeSet, seeds)
%% Section 0: Header & Readme
% SYNTAX
%   diagnostics = obstacleAvoidance.search.createSearchDiagnostics( ...
%       proposal, visibilityGraph, routeSet, seeds)
%**************************************************************************
% PURPOSE
%   - Assemble stable search diagnostics from completed production stages
%     without recomputing proposal, graph, route, or seed decisions.
%**************************************************************************
% INPUTS
%   - proposal, visibilityGraph, routeSet (scalar structs)
%       Completed stage records, or empty structs when graph work was skipped.
%   - seeds (nonempty route-seed struct array)
%       Final deterministic seed order.
%**************************************************************************
% OUTPUTS
%   - diagnostics (scalar struct)
%       Stable graph, route, rejection, coverage, and bounded-search evidence.
%**************************************************************************
% UNITS
%   - Position and path length are degrees; time is seconds.
%**************************************************************************

%% Section 1: Create Stable Direct-Only Diagnostics

start_deg = seeds(1).position_deg(1, :);
goal_deg = seeds(1).position_deg(end, :);
diagnostics = emptyDiagnostics(start_deg, goal_deg);
diagnostics.GeneratedSeedCount = numel(seeds);
if isempty(fieldnames(proposal))
    return;
end

%% Section 2: Copy Proposal And Visibility Evidence

diagnostics.SeedCluster.SourceRegionCount = ...
    numel(regions(proposal.shape));
diagnostics.SampleTimes_s = proposal.sampleTimes_s;
diagnostics.SampledShapeCount = proposal.sampledShapeCount;
diagnostics.DenseSeedEnvelopeUsed = proposal.usedDenseEnvelope;
diagnostics.NodeCount = size(visibilityGraph.NodePosition_deg, 1);
diagnostics.NodePosition_deg = visibilityGraph.NodePosition_deg;
if proposal.usedDenseEnvelope
    diagnostics.DenseSeedEnvelope_deg = proposal.shape.Vertices;
end
graphRecord = visibilityGraph.Record;
graphFields = ["Bounds_deg", "CandidateOffset_deg", ...
    "CandidateOffsetRetryCount", "VisibilityWorkBudget", ...
    "EstimatedExhaustiveVisibilityWork", "ExhaustiveVisibilityUsed", ...
    "ExhaustiveVisibilityFallbackUsed", ...
    "VisibilityCandidatePairCount", "VisibilityEdgeCount", ...
    "AcceptedEdges_deg", "RejectedEdges_deg", ...
    "RejectedTransitionCount"];
for fieldIndex = 1:numel(graphFields)
    fieldName = graphFields(fieldIndex);
    diagnostics.(fieldName) = graphRecord.(fieldName);
end
diagnostics.HomologyRepresentative_deg = ...
    visibilityGraph.ObstacleReferencePoints_deg;
diagnostics.Coverage.ExactSpatialProposalUsed = ...
    ~proposal.usedDenseEnvelope;
diagnostics.Coverage.ReducedSpatialProposalUsed = ...
    proposal.usedDenseEnvelope;
diagnostics.Coverage.TimedSearchSuppressionReason = ...
    "staticObstacleHistory";

%% Section 3: Copy Timed And Spatial Search Evidence

if routeSet.TimedSearchAttempted
    diagnostics.Coverage.TimedSearchAttempted = true;
    diagnostics.Coverage.ExtendedTimedSearchAttempted = true;
    diagnostics.Coverage.TimedSearchUsesExactObstacles = true;
    diagnostics.Coverage.TimedSearchSuppressionReason = "";
    timedRecord = routeSet.TimedSearchRecord;
    diagnostics.TemporalLayerTimes_s = timedRecord.LayerTimes_s;
    diagnostics.TemporalLayerCount = numel(timedRecord.LayerTimes_s);
    diagnostics.TemporalCandidateLayerCount = timedRecord.CandidateLayerCount;
    diagnostics.TemporalLayerLimitApplied = timedRecord.LayerLimitApplied;
    diagnostics.TemporalNodeCount = timedRecord.NodeCount;
    diagnostics.WaitEdgeCount = timedRecord.WaitEdgeCount;
    diagnostics.MotionEdgeCount = timedRecord.MotionEdgeCount;
    diagnostics.TimedSearchGoalTimeMode = ...
        routeSet.TimedSearchOptions.GoalTimeMode;
    diagnostics = appendSearchDiagnostics(diagnostics, timedRecord);
else
    diagnostics.Coverage.TimedSearchSuppressionReason = ...
        routeSet.TimedSearchSuppressionReason;
end
searchRecord = routeSet.SpatialSearchRecord;
diagnostics = appendSearchDiagnostics(diagnostics, searchRecord);
diagnostics.HomologySearchAttempted = ...
    routeSet.MaximumSpatialClassCount > 0;
diagnostics.HomologyClassSignatures = routeSet.RouteClassPattern;
diagnostics.HomologyClassCount = size(routeSet.RouteClassPattern, 1);
diagnostics.HomologyStateCount = searchRecord.StateCount;
diagnostics.HomologySearchTruncated = searchRecord.Truncated;
diagnostics.HomologyWindingComponentLimit = ...
    searchRecord.WindingComponentLimit;
diagnostics.HomologyWindingLimitRejectedCount = ...
    searchRecord.WindingLimitRejectedCount;
diagnostics.HomologyStoppedAtClassLimit = ...
    searchRecord.StoppedAtClassLimit;
cleanupFields = ["RouteCleanupAttemptedCount", ...
    "RouteCleanupCandidateCount", "RouteCleanupVisibilityRejectedCount", ...
    "RouteCleanupHomologyRejectedCount", "RouteCleanupAcceptedCount", ...
    "RouteCleanupLengthReduction_deg"];
for fieldIndex = 1:numel(cleanupFields)
    fieldName = cleanupFields(fieldIndex);
    diagnostics.(fieldName) = searchRecord.(fieldName);
end
if proposal.usedDenseEnvelope
    diagnostics.Coverage.CompletenessLossReason = ...
        "reducedSpatialProposalAndBoundedSearch";
else
    diagnostics.Coverage.CompletenessLossReason = ...
        "boundedSeedNodeAndTimeSearch";
end
end

%% Section 4: Local Functions

function diagnostics = appendSearchDiagnostics(diagnostics, record)
% Append returned search traces and full counts without recreating decisions.
diagnostics.ExpandedCount = diagnostics.ExpandedCount + record.ExpandedCount;
diagnostics.RejectedTransitionCount = ...
    diagnostics.RejectedTransitionCount + record.RejectedTransitionCount;
diagnostics.ExploredNodes_deg = [diagnostics.ExploredNodes_deg; ...
    record.ExploredNodes_deg];
diagnostics.FrontierNodes_deg = [diagnostics.FrontierNodes_deg; ...
    record.FrontierNodes_deg];
if ~isempty(record.BestPartialRoute_deg)
    diagnostics.BestPartialRoute_deg = record.BestPartialRoute_deg;
end
end

function diagnostics = emptyDiagnostics(start_deg, goal_deg)
% Initialize every stable field before direct-only and no-path exits.
coverage = struct("ExactSpatialProposalUsed", false, ...
    "ReducedSpatialProposalUsed", false, "TimedSearchAttempted", false, ...
    "ExtendedTimedSearchAttempted", false, ...
    "TimedSearchUsesExactObstacles", false, ...
    "TimedSearchSuppressionReason", "graphNotBuilt", ...
    "CompletenessLost", true, ...
    "CompletenessLossReason", "graphNotBuilt");
cluster = struct("Distance_deg", 0, ...
    "SourceRegionCount", 0, "ClusterGroupCount", 0, ...
    "ClusteredRegionCount", 0, ...
    "ClusterBoundary_deg", zeros(0, 2));
diagnostics = struct("GraphType", "timeExpandedVisibilityGraph", ...
    "Bounds_deg", [NaN NaN NaN NaN], "Resolution_deg", NaN, ...
    "CandidateOffset_deg", NaN, "CandidateOffsetRetryCount", 0, ...
    "SampleTimes_s", zeros(0, 1), "SampledShapeCount", 0, ...
    "DenseSeedEnvelopeUsed", false, ...
    "DenseSeedEnvelope_deg", zeros(0, 2), "Coverage", coverage, ...
    "SeedCluster", cluster, "NodeCount", 0, ...
    "NodePosition_deg", zeros(0, 2), "VisibilityWorkBudget", 1e6, ...
    "EstimatedExhaustiveVisibilityWork", 0, ...
    "ExhaustiveVisibilityUsed", false, ...
    "ExhaustiveVisibilityFallbackUsed", false, ...
    "VisibilityCandidatePairCount", 0, "VisibilityEdgeCount", 0, ...
    "AcceptedEdges_deg", zeros(0, 4), ...
    "RejectedEdges_deg", zeros(0, 4), ...
    "TemporalLayerTimes_s", zeros(0, 1), "TemporalLayerCount", 0, ...
    "TemporalCandidateLayerCount", 0, "TemporalLayerLimitApplied", false, ...
    "TemporalNodeCount", 0, "WaitEdgeCount", 0, "MotionEdgeCount", 0, ...
    "HomologySearchAttempted", false, ...
    "HomologyRepresentative_deg", zeros(0, 2), ...
    "HomologyClassSignatures", zeros(0, 0, "int8"), ...
    "HomologyClassCount", 0, "HomologyStateCount", 0, ...
    "HomologySearchTruncated", false, ...
    "HomologyWindingComponentLimit", 1, ...
    "HomologyWindingLimitRejectedCount", 0, ...
    "HomologyStoppedAtClassLimit", false, ...
    "RouteCleanupAttemptedCount", 0, ...
    "RouteCleanupCandidateCount", 0, ...
    "RouteCleanupVisibilityRejectedCount", 0, ...
    "RouteCleanupHomologyRejectedCount", 0, ...
    "RouteCleanupAcceptedCount", 0, ...
    "RouteCleanupLengthReduction_deg", 0, "ExpandedCount", 0, ...
    "RejectedTransitionCount", 0, "GeneratedSeedCount", 1, ...
    "ExploredNodes_deg", zeros(0, 2), ...
    "FrontierNodes_deg", zeros(0, 2), ...
    "BestPartialRoute_deg", zeros(0, 2), "Start_deg", start_deg, ...
    "Goal_deg", goal_deg, "TraceDownsampleRule", ...
    "Temporal/explored states are complete; static edge traces retain " + ...
    "the first 2000 accepted and rejected decisions");
end
