function attempt = createVisibilityAttempt( ...
        shape, start_deg, goal_deg, limits, candidateOffset_deg, ...
        offsetRetryCount, workBudget)
%% Section 0: Header & Readme
% SYNTAX
%   attempt = obstacleAvoidance.search.createVisibilityAttempt( ...
%       shape, start_deg, goal_deg, limits, candidateOffset_deg, ...
%       offsetRetryCount, workBudget)
%**************************************************************************
% PURPOSE
%   - Create, check, and recover one offset visibility-graph attempt.
%   - Return every representation needed to inspect its decisions.
%**************************************************************************
% INPUTS
%   - shape (scalar polyshape)
%       Spatial obstacle representation used only for route proposals.
%   - start_deg, goal_deg (1-by-2 finite numeric rows)
%       Required endpoint positions in [azimuth elevation] order.
%   - limits (scalar struct)
%       Workspace intervals in degrees.
%   - candidateOffset_deg (positive finite scalar)
%       Outward obstacle-boundary offset for this attempt.
%   - offsetRetryCount (nonnegative integer scalar)
%       Zero-based index of this attempt in the offset schedule.
%   - workBudget (positive finite scalar)
%       Pair-edge work cap governing node count and exhaustive recovery.
%**************************************************************************
% OUTPUTS
%   - attempt (scalar struct)
%       Raw and retained nodes, candidate pairs, accepted and rejected
%       edges, components, recovery steps, costs, and connectivity state.
%**************************************************************************
% UNITS
%   - Positions, offsets, bounds, and graph costs are degrees.
%**************************************************************************

%% Section 1: Bound The Candidate Nodes

% Segment checks scale with both candidate pairs and obstacle edges. Convert
% the fixed work budget into a node limit before constructing the offset
% nodes so later pair creation cannot silently exceed the intended bound.

[edgeStart_deg, edgeEnd_deg] = ...
    obstacleAvoidance.geometry.boundaryToEdges(shape, 1e-12);
candidateLimit = max(2, floor(sqrt( ...
    2 * workBudget / max(1, size(edgeStart_deg, 1)))) - 2);
nodes = obstacleAvoidance.search.createVisibilityNodes( ...
    shape, start_deg, goal_deg, limits, candidateOffset_deg, ...
    candidateLimit);

%% Section 2: Create And Check Candidate Pairs

% Sparse pairs are route suggestions, not safety certificates. Check each
% offered segment against the proposal geometry and retain both outcomes so
% recovery and plotting consume the same decisions.

pairSet = obstacleAvoidance.search.createVisibilityPairs( ...
    nodes.Positions_deg, size(edgeStart_deg, 1), workBudget);
edgeCheck = obstacleAvoidance.search.evaluateVisibilityPairs( ...
    nodes.Positions_deg, pairSet.PairMask, shape, ...
    edgeStart_deg, edgeEnd_deg);

%% Section 3: Recover Missing Connectivity

% A sparse graph may be disconnected even when useful visible edges exist.
% Add only the established boundary and affordable exhaustive candidates,
% then return the final components instead of hiding the recovery path.

recovery = obstacleAvoidance.search.recoverVisibilityConnectivity( ...
    nodes, pairSet, edgeCheck, shape, edgeStart_deg, edgeEnd_deg);

%% Section 4: Assemble The Attempt

attempt = struct( ...
    "OffsetRetryCount", offsetRetryCount, ...
    "CandidateOffset_deg", candidateOffset_deg, ...
    "Nodes", nodes, ...
    "InitialPairSet", pairSet, ...
    "FinalCandidatePairs", recovery.EdgeCheck.CandidatePairs, ...
    "AcceptedEdges_deg", recovery.EdgeCheck.AcceptedEdges_deg, ...
    "RejectedEdges_deg", recovery.EdgeCheck.RejectedEdges_deg, ...
    "EdgeRejectionReasons", recovery.EdgeCheck.RejectionReasons, ...
    "GraphComponents", recovery.Components, ...
    "RecoverySteps", recovery.RecoverySteps, ...
    "ExhaustiveVisibilityUsed", recovery.UsedExhaustive, ...
    "ExhaustiveVisibilityFallbackUsed", ...
    recovery.UsedExhaustiveFallback, ...
    "IsConnected", recovery.IsConnected, ...
    "Cost_deg", recovery.EdgeCheck.Cost_deg, ...
    "VisibilityEdgeCount", recovery.EdgeCheck.AcceptedCount, ...
    "RejectedTransitionCount", recovery.EdgeCheck.RejectedCount, ...
    "VisibilityCandidatePairCount", nnz(recovery.PairMask), ...
    "EstimatedExhaustiveVisibilityWork", ...
    pairSet.EstimatedExhaustiveWork);
end
