function validation = validateTrajectory( ...
        trajectory, obstacles, initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   validation = obstacleAvoidance.validateTrajectory()
%   validation = obstacleAvoidance.validateTrajectory(result)
%   validation = obstacleAvoidance.validateTrajectory( ...
%       trajectory, obstacles, initialState, goalState, limits, options)
%**************************************************************************
% PURPOSE
%   - Validate one complete polynomial motion independently of planner status.
%   - Fail closed when a continuous collision interval cannot be resolved.
%**************************************************************************
% INPUTS
%   - trajectory (scalar candidate or planner-result struct)
%       Must contain sampled histories and Polynomial segment coefficients.
%   - obstacles (canonical protected obstacle array, optional with result)
%   - initialState, goalState (normalized state structs, optional with result)
%   - limits (normalized physical limits struct, optional with result)
%   - options (resolved planner options, optional with result)
%**************************************************************************
% OUTPUTS
%   - validation (scalar struct)
%       Stable checks, clearance, message, collision counts, and timings.
%**************************************************************************
% UNITS
%   - Position and clearance are degrees. Derivatives use deg/s, deg/s^2,
%     and deg/s^3. Time is seconds.
%**************************************************************************
if nargin == 0
    validation = createEmptyValidation();
    return;
end
validationTimer = tic;

%% Section 1: Resolve Inputs And Validate Histories

if nargin == 1
    requiredFields = {'Inputs', 'Options', 'Polynomial'};
    if ~isstruct(trajectory) || ~isscalar(trajectory) || ...
            ~all(isfield(trajectory, requiredFields))
        error("validateTrajectory:InvalidResult", ...
            "A one-input call requires a planner result with Inputs, " + ...
            "Options, and Polynomial fields.");
    end
    obstacles = trajectory.Inputs.obstacles;
    initialState = trajectory.Inputs.initialState;
    goalState = trajectory.Inputs.goalState;
    limits = trajectory.Inputs.limits;
    options = trajectory.Options;
elseif nargin ~= 6
    error("validateTrajectory:InvalidCall", ...
        "Use one planner result or all six explicit validation inputs.");
end
if isempty(obstacles) || ~isfield(obstacles, "InternalPreparation")
    obstacles = obstacleAvoidance.obstacles.combineObstacles(obstacles);
end
obstacles = obstacleAvoidance.obstacles.prepareDynamic(obstacles);
hasMovingGoal = isfield(goalState, "targetTime_s") && ...
    ~isempty(goalState.targetTime_s);
if options.AllowAzimuthWrapping && (~isempty(obstacles) || hasMovingGoal)
    error("validateTrajectory:UnsupportedWrappedGeometry", ...
        "Wrapped validation is supported only for obstacle-free " + ...
        "fixed-position goals.");
end
[time_s, position_deg, velocity_deg_s, acceleration_deg_s2, ...
    jerk_deg_s3, historySizesMatch, timeIsFinite, ...
    timeIsStrictlyIncreasing, historyIsFinite] = ...
    readAndCheckMotionHistory(trajectory);

%% Section 2: Validate Endpoints And Continuous Polynomial Bounds

stateTolerance = max(10 * options.ConstraintTolerance, 1e-7);
[initialStateMatched, terminalStateMatched, goalTimeSatisfied] = ...
    checkEndpointStates(time_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, historyIsFinite, timeIsFinite, initialState, ...
    goalState, options, stateTolerance);
[continuousBounds, dynamics, polynomialChecks] = ...
        obstacleAvoidance.validation.validatePolynomialTrajectory( ...
    trajectory.Polynomial, time_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, jerk_deg_s3, initialState, goalState, limits, ...
    options, stateTolerance, ...
    @obstacleAvoidance.validation.certifyPolynomialRange);

%% Section 3: Certify Continuous Collision Freedom

collisionTimer = tic;
[collisionFree, collisionResolved, seedCorridorCertified, ...
    planeCertificateCertified, minimumClearance_deg, ...
    collisionCheckCount, unresolvedIntervalCount] = ...
    obstacleAvoidance.validation.checkObstacleClearance( ...
    trajectory, obstacles, limits, options, ...
    timeIsStrictlyIncreasing && historyIsFinite && continuousBounds.Valid);
collisionCheckingElapsedTime_s = toc(collisionTimer);
safetyMarginPolicySatisfied = safetyMarginProvenanceSatisfied(obstacles);
azimuthWrapPolicySatisfied = options.AllowAzimuthWrapping || ...
    continuousBounds.PositionWithinLimits;

%% Section 4: Assemble The Stable Validation Record

checkNames = ["history shape", "finite increasing time", ...
    "finite histories", "initial state", "terminal state", "goal time", ...
    "polynomial format", "polynomial initial time", ...
    "polynomial time base", "polynomial segment continuity", ...
    "polynomial endpoint states", "polynomial sampled histories", ...
    "continuous limits", "polynomial dynamics", "collision freedom", ...
    "collision resolution", "safety-margin provenance", ...
    "azimuth-wrap policy"];
checkValues = [historySizesMatch, timeIsStrictlyIncreasing, ...
    historyIsFinite, initialStateMatched, terminalStateMatched, ...
    goalTimeSatisfied, polynomialChecks.FormatValid, ...
    polynomialChecks.InitialTimeMatched, ...
    polynomialChecks.TimeBaseConsistent, ...
    polynomialChecks.SegmentContinuity, ...
    polynomialChecks.EndpointStatesMatched, ...
    polynomialChecks.HistoryConsistent, continuousBounds.Valid, ...
    dynamics.Consistent, collisionFree, collisionResolved, ...
    safetyMarginPolicySatisfied, azimuthWrapPolicySatisfied];
passed = all(checkValues);
issues = checkNames(~checkValues).';
if passed
    message = "Independent continuous validation passed.";
else
    message = "Independent validation failed: " + ...
        strjoin(issues, ", ") + ".";
end
values = {passed, message, historySizesMatch, timeIsFinite, ...
    timeIsStrictlyIncreasing, historyIsFinite, initialStateMatched, ...
    terminalStateMatched, goalTimeSatisfied, polynomialChecks.FormatValid, ...
    polynomialChecks.InitialTimeMatched, polynomialChecks.TimeBaseConsistent, ...
    polynomialChecks.SegmentContinuity, ...
    polynomialChecks.EndpointStatesMatched, ...
    polynomialChecks.HistoryConsistent, ...
    polynomialChecks.MaximumSegmentContinuityResidual, ...
    polynomialChecks.MaximumHistoryResidual, ...
    continuousBounds.PositionWithinLimits, ...
    continuousBounds.VelocityWithinLimits, ...
    continuousBounds.AccelerationWithinLimits, ...
    continuousBounds.JerkWithinLimits, dynamics.Consistent, ...
    dynamics.MaximumResidual, collisionFree, collisionResolved, ...
    seedCorridorCertified, planeCertificateCertified, minimumClearance_deg, ...
    collisionCheckCount, unresolvedIntervalCount, ...
    safetyMarginPolicySatisfied, azimuthWrapPolicySatisfied, ...
    maximumAbsolute(velocity_deg_s), maximumAbsolute(acceleration_deg_s2), ...
    maximumAbsolute(jerk_deg_s3), issues, collisionCheckingElapsedTime_s, ...
    toc(validationTimer)};
validation = createValidationRecord(values);
end

%% Section 5: Local Functions

function [time_s, position_deg, velocity_deg_s, acceleration_deg_s2, ...
        jerk_deg_s3, historySizesMatch, timeIsFinite, ...
        timeIsStrictlyIncreasing, historyIsFinite] = ...
        readAndCheckMotionHistory(trajectory)
% Normalize sampled histories and check their shared shape and finiteness.
requiredFields = {'time_s', 'position_deg', 'velocity_deg_s', ...
    'acceleration_deg_s2', 'jerk_deg_s3', 'Polynomial'};
if ~isstruct(trajectory) || ~isscalar(trajectory) || ...
        ~all(isfield(trajectory, requiredFields))
    error("validateTrajectory:InvalidTrajectory", ...
        "trajectory must contain sampled histories and Polynomial data.");
end
time_s = double(trajectory.time_s(:));
position_deg = double(trajectory.position_deg);
velocity_deg_s = double(trajectory.velocity_deg_s);
acceleration_deg_s2 = double(trajectory.acceleration_deg_s2);
jerk_deg_s3 = double(trajectory.jerk_deg_s3);
sampleCount = numel(time_s);
historySizesMatch = isequal(size(position_deg), [sampleCount 2]) && ...
    isequal(size(velocity_deg_s), [sampleCount 2]) && ...
    isequal(size(acceleration_deg_s2), [sampleCount 2]) && ...
    isequal(size(jerk_deg_s3), [sampleCount 2]);
timeIsFinite = ~isempty(time_s) && all(isfinite(time_s));
timeIsStrictlyIncreasing = timeIsFinite && all(diff(time_s) > 0);
historyIsFinite = sampleCount > 0 && historySizesMatch && ...
    all(isfinite(position_deg), "all") && ...
    all(isfinite(velocity_deg_s), "all") && ...
    all(isfinite(acceleration_deg_s2), "all") && ...
    all(isfinite(jerk_deg_s3), "all");
end

function [initialStateMatched, terminalStateMatched, goalTimeSatisfied] = ...
        checkEndpointStates(time_s, position_deg, velocity_deg_s, ...
        acceleration_deg_s2, historyIsFinite, timeIsFinite, initialState, ...
        goalState, options, stateTolerance)
% Compare sampled endpoints with the requested states and arrival policy.
initialStateMatched = historyIsFinite && max(abs([ ...
    position_deg(1, :) - initialState.position_deg, ...
    velocity_deg_s(1, :) - initialState.velocity_deg_s, ...
    acceleration_deg_s2(1, :) - initialState.acceleration_deg_s2])) <= ...
    stateTolerance;
if timeIsFinite
    goalPosition_deg = obstacleAvoidance.input.goalPositionAtTime( ...
        goalState, time_s(end));
else
    goalPosition_deg = [NaN NaN];
end
terminalStateMatched = historyIsFinite && max(abs([ ...
    position_deg(end, :) - goalPosition_deg, ...
    velocity_deg_s(end, :) - goalState.velocity_deg_s, ...
    acceleration_deg_s2(end, :) - goalState.acceleration_deg_s2])) <= ...
    stateTolerance;
if options.GoalTimeMode == "fixedArrival"
    goalTimeSatisfied = timeIsFinite && ...
        abs(time_s(end) - goalState.time_s) <= stateTolerance;
else
    goalTimeSatisfied = timeIsFinite && ...
        time_s(end) <= goalState.time_s + stateTolerance && ...
        time_s(end) > initialState.time_s;
end
end

function satisfied = safetyMarginProvenanceSatisfied(obstacles)
% Require original geometry and one finite nonnegative applied margin.
if isempty(obstacles)
    satisfied = true;
    return;
end
hasFields = all(isfield(obstacles, ...
    {'originalAz_deg', 'originalEl_deg', 'safetyMargin_deg'}));
satisfied = hasFields && all(isfinite([obstacles.safetyMargin_deg])) && ...
    all([obstacles.safetyMargin_deg] >= 0);
end

function peak = maximumAbsolute(values)
% Return per-coordinate sampled peaks or documented NaN values.
if isempty(values)
    peak = [NaN NaN];
else
    peak = max(abs(values), [], 1);
end
end

function validation = createEmptyValidation()
% Define every stable validation field before checks are available.
values = {false, "No trajectory was validated.", false, false, false, ...
    false, false, false, false, false, false, false, false, false, false, ...
    NaN, NaN, false, false, false, false, false, NaN, false, false, false, ...
    false, NaN, 0, 0, false, false, [NaN NaN], [NaN NaN], [NaN NaN], ...
    strings(0, 1), 0, 0};
validation = createValidationRecord(values);
end

function validation = createValidationRecord(values)
% Assemble values once in stable public field order.
names = ["Passed", "Message", "HistorySizesMatch", "TimeIsFinite", ...
    "TimeIsStrictlyIncreasing", "HistoryIsFinite", "InitialStateMatched", ...
    "TerminalStateMatched", "GoalTimeSatisfied", "PolynomialFormatValid", ...
    "PolynomialInitialTimeMatched", "PolynomialTimeBaseConsistent", ...
    "PolynomialSegmentContinuity", "PolynomialEndpointStatesMatched", ...
    "PolynomialHistoryConsistent", "MaximumSegmentContinuityResidual", ...
    "MaximumPolynomialHistoryResidual", "PositionWithinLimits", ...
    "VelocityWithinLimits", "AccelerationWithinLimits", "JerkWithinLimits", ...
    "DynamicsConsistent", "MaximumDynamicsResidual", "CollisionFree", ...
    "CollisionResolved", "SeedCorridorCertified", ...
    "PlaneCertificateCertified", "MinimumClearance_deg", ...
    "CollisionCheckCount", "UnresolvedIntervalCount", ...
    "SafetyMarginPolicySatisfied", "AzimuthWrapPolicySatisfied", ...
    "PeakVelocity_deg_s", "PeakAcceleration_deg_s2", "PeakJerk_deg_s3", ...
    "Issues", "CollisionCheckingElapsedTime_s", "ElapsedTime_s"];
validation = cell2struct(values, cellstr(names), 2);
end
