function exportInfo = exportDiagnosisBundle(filePath, scene)
%% Section 0: Header & Readme
% SYNTAX
%   exportInfo = webSandbox.bundle.exportDiagnosisBundle(filePath, scene)
%**************************************************************************
% PURPOSE
%   - Save a web scene as the MATLAB sandbox diagnosis-v2 bundle format.
%**************************************************************************
% INPUTS
%   - filePath (scalar text)
%       Destination .mat file controlled by the local web protocol.
%   - scene (scalar struct)
%       JSON-safe trajectory scene accepted by the web bridge.
%**************************************************************************
% OUTPUTS
%   - exportInfo (scalar struct)
%       Format, path, and byte count for the verified MATLAB bundle.
%**************************************************************************
% UNITS
%   - Positions are degrees and time is seconds.
%**************************************************************************

%% Section 1: Convert The Browser Scene Through The Public Inputs

if ~isstruct(scene) || ~isscalar(scene)
    error("webSandbox:exportDiagnosisBundle:InvalidScene", ...
        "scene must be one JSON-safe scalar struct.");
end
scene.mode = "trajectory";
inputs = webSandbox.fileProtocol.createRequestInputs(scene);
if inputs.Mode ~= "trajectory"
    error("webSandbox:exportDiagnosisBundle:UnsupportedMode", ...
        "Only trajectory scenes can be exported as sandbox bundles.");
end

%% Section 2: Assemble The Established Diagnosis Bundle

sceneRecord = createSceneRecord(scene, inputs.obstacles);
plannerInputs = struct( ...
    "obstacles", inputs.obstacles, ...
    "initialState", inputs.initialState, ...
    "goalState", inputs.goalState, ...
    "limits", inputs.limits);
exportRequest = struct( ...
    "HasCompleteScene", true, ...
    "PlannerInputs", plannerInputs, ...
    "PlannerOptions", inputs.plannerOptions, ...
    "RequestedStart_deg", inputs.initialState.position_deg, ...
    "RequestedGoal_deg", inputs.goalState.position_deg);
diagnosisBundle = struct( ...
    "Format", "obstacleAvoidanceSandboxDiagnosis-v2", ...
    "CreatedUTC", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX")), ...
    "Mode", "goal", ...
    "PlanningState", "notRun", ...
    "HasPlannerResult", false, ...
    "Environment", struct( ...
        "MATLABVersion", string(version), ...
        "MATLABRelease", string(version("-release")), ...
        "Computer", string(computer), ...
        "WorkingDirectory", string(pwd)), ...
    "SandboxOptions", struct(), ...
    "Scene", sceneRecord, ...
    "ExportRequest", exportRequest, ...
    "PlannerInputs", plannerInputs, ...
    "PlannerOptions", inputs.plannerOptions, ...
    "Result", struct(), ...
    "IndependentValidation", obstacleAvoidance.validateTrajectory(), ...
    "Status", "Exported by Web Sandbox before planning.", ...
    "PlannerLog", "[Web Sandbox]", ...
    "Reproduction", struct( ...
        "LoadCommand", "loaded = load(filePath, 'diagnosisBundle');", ...
        "PlannerCommand", "", "ValidationCommand", ""));

%% Section 3: Save And Verify The Interchange File

filePath = string(filePath);
save(char(filePath), "diagnosisBundle", "-v7.3");
record = dir(char(filePath));
if isempty(record) || record.bytes <= 0
    error("webSandbox:exportDiagnosisBundle:SaveFailed", ...
        "No nonempty diagnosis bundle was written to %s.", filePath);
end
exportInfo = struct( ...
    "Format", diagnosisBundle.Format, ...
    "FilePath", filePath, ...
    "Bytes", double(record.bytes));
end

function sceneRecord = createSceneRecord(scene, obstacles)
% Retain web polygons as raw/protected scene provenance while canonical data rules planning.
polygonPositions_deg = cell(numel(scene.obstacles), 1);
rawStrokes_deg = cell(numel(scene.obstacles), 1);
for obstacleIndex = 1:numel(scene.obstacles)
    vertices_deg = double(scene.obstacles(obstacleIndex).slices(1).vertices_deg);
    polygonPositions_deg{obstacleIndex} = vertices_deg;
    rawStrokes_deg{obstacleIndex} = vertices_deg;
end
sceneRecord = struct( ...
    "StartPosition_deg", scene.initialState.position_deg, ...
    "GoalPosition_deg", scene.goalState.position_deg, ...
    "RawObstacleStrokes_deg", {rawStrokes_deg}, ...
    "LineObstaclePositions_deg", {cell(0, 1)}, ...
    "PolygonObstaclePositions_deg", {polygonPositions_deg}, ...
    "PolygonMotionVectors_deg", zeros(numel(scene.obstacles), 2), ...
    "PolygonMotionProfiles", repmat("stationary", numel(scene.obstacles), 1), ...
    "CanonicalObstacles", obstacles, ...
    "ResolvedControls", struct());
end
