function options = resolvePlannerOptions(optionOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   options = obstacleAvoidance.input.resolvePlannerOptions()
%   options = obstacleAvoidance.input.resolvePlannerOptions(optionOverrides)
%**************************************************************************
% PURPOSE
%   - Resolve and validate obstacle-planner search and motion options.
%**************************************************************************
% INPUTS
%   - optionOverrides (scalar struct, optional; default struct())
%       Partial overrides; empty fields use defaults and unknown fields are
%       warned about once and ignored.
%       GoalTimeMode is "balancedArrival" (default), "earliestArrival", or
%       "fixedArrival". Balanced arrival minimizes travel plus the explicit
%       arrival-time exchange rate MinimumTravelSavingsRate_deg_s. A later
%       motion wins only when its travel saving exceeds that rate times its
%       delay. Jerk remains a hard constraint and is never a ranking cost.
%       MaximumTimeLayerCount is an integer from 2 through 65535 and bounds
%       BMTP timed-motion segments plus one. Default is 17.
%       MaximumWaitRefinementIterations is an integer from 0 through 64 and
%       bounds validated direct-wait bisection trials. Default is 16.
%       UnsupportedTimedTopologyPolicy is "fail" (default) or
%       "ruckigStopAtWaypoints". The latter explicitly permits rest-to-rest
%       composition after the smooth timed kernel rejects a route topology,
%       but only when the normalized route contains at most two segments.
%**************************************************************************
% OUTPUTS
%   - options (scalar struct)
%       Fully populated, normalized, and validated planner options.
%**************************************************************************
% UNITS
%   - Time fields use seconds and angular clearance fields use degrees.
%**************************************************************************

%% Section 1: Resolve Defaults

defaults = struct( ...
    "GoalTimeMode", "balancedArrival", ...
    "MinimumTravelSavingsRate_deg_s", 1, "SampleTime_s", 0.05, ...
    "TrajectoryMethod", "bmtp", ...
    "UnsupportedTimedTopologyPolicy", "fail", ...
    "AllowAzimuthWrapping", false, ...
    "MaximumSeedCount", 5, ...
    "MaximumTimeLayerCount", 17, ...
    "MaximumWaitRefinementIterations", 16, ...
    "ArrivalTimeTolerance_s", 1e-3, "ConstraintTolerance", 1e-7, ...
    "CollisionClearanceTolerance_deg", 1e-7, ...
    "CollisionMinimumTimeStep_s", 0.00025, ...
    "CancellationCheckFcn", []);
if nargin == 0 || isempty(optionOverrides)
    optionOverrides = struct();
end
if ~isstruct(optionOverrides) || ~isscalar(optionOverrides)
    error("planTrajectory:InvalidOptions", ...
        "optionOverrides must be a scalar struct.");
end
for fieldName = ["AzimuthInterval_deg", "ElevationInterval_deg"]
    if isfield(optionOverrides, fieldName)
        replacementName = lower(extractBefore(fieldName, "Interval")) + ...
            "Interval_deg";
        error("planTrajectory:WorkspaceLimitMoved", ...
            "%s has moved from options to limits.%s.", ...
            fieldName, replacementName);
    end
end
[options, unknownNames] = obstacleAvoidance.input.resolveOptions( ...
    defaults, optionOverrides);
if ~isempty(unknownNames)
    warning("planTrajectory:UnknownOptions", ...
        "Ignoring unknown option fields: %s. No behavior changed.", ...
        strjoin(unknownNames, ", "));
end

%% Section 2: Normalize Public Values

textRules = {"GoalTimeMode", ...
    ["balancedArrival", "earliestArrival", "fixedArrival"], ...
    "planTrajectory:InvalidGoalTimeMode", ...
    "GoalTimeMode must be 'balancedArrival', 'earliestArrival', or " + ...
    "'fixedArrival'."; ...
    "TrajectoryMethod", ["bmtp", "ruckigWaypoint"], ...
    "planTrajectory:InvalidTrajectoryMethod", ...
    "TrajectoryMethod must be 'bmtp' or 'ruckigWaypoint'."; ...
    "UnsupportedTimedTopologyPolicy", ...
    ["fail", "ruckigStopAtWaypoints"], ...
    "planTrajectory:InvalidUnsupportedTimedTopologyPolicy", ...
    "UnsupportedTimedTopologyPolicy must be 'fail' or " + ...
    "'ruckigStopAtWaypoints'."};
for ruleIndex = 1:size(textRules, 1)
    fieldName = textRules{ruleIndex, 1};
    options.(fieldName) = string(options.(fieldName));
    if ~isscalar(options.(fieldName)) || ...
            ~any(options.(fieldName) == textRules{ruleIndex, 2})
        error(textRules{ruleIndex, 3}, textRules{ruleIndex, 4});
    end
end
for fieldName = "AllowAzimuthWrapping"
    options.(fieldName) = obstacleAvoidance.input.normalizeLogicalScalar( ...
        options.(fieldName), fieldName, ...
        "planTrajectory:InvalidLogicalOption");
end
if ~isempty(options.CancellationCheckFcn) && ...
        ~(isa(options.CancellationCheckFcn, "function_handle") && ...
        isscalar(options.CancellationCheckFcn))
    error("planTrajectory:InvalidCancellationCheckFcn", ...
        "CancellationCheckFcn must be empty or a scalar function handle.");
end

validateattributes(options.SampleTime_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
integerRules = {"MaximumSeedCount", 1, 9; ...
    "MaximumTimeLayerCount", 2, 65535; ...
    "MaximumWaitRefinementIterations", 0, 64};
for ruleIndex = 1:size(integerRules, 1)
    validateattributes(options.(integerRules{ruleIndex, 1}), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', ...
        '>=', integerRules{ruleIndex, 2}, '<=', integerRules{ruleIndex, 3}});
end
for fieldName = ["MinimumTravelSavingsRate_deg_s", ...
        "ArrivalTimeTolerance_s", "ConstraintTolerance", ...
        "CollisionMinimumTimeStep_s"]
    validateattributes(options.(fieldName), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'positive'});
end
validateattributes(options.CollisionClearanceTolerance_deg, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'});
end
