function options = resolvePlannerOptions(optionOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   options = obstacleAvoidance.input.resolvePlannerOptions()
%   options = obstacleAvoidance.input.resolvePlannerOptions(optionOverrides)
%**************************************************************************
% PURPOSE
%   - Resolve and validate obstacle-planner search and motion options.
%**************************************************************************
% INPUTS
%   - optionOverrides (scalar struct, optional; default struct())
%       Partial overrides; empty fields use defaults and unknown fields are
%       warned about once and ignored.
%**************************************************************************
% OUTPUTS
%   - options (scalar struct)
%       Fully populated, normalized, and validated planner options.
%**************************************************************************
% UNITS
%   - Time fields use seconds and angular clearance fields use degrees.
%**************************************************************************

%% Section 1: Resolve Defaults

defaults = struct( ...
    "GoalTimeMode", "earliestArrival", "SampleTime_s", 0.05, ...
    "TrajectoryMethod", "bmtp", ...
    "AllowAzimuthWrapping", false, "WaypointWarmStartMode", "none", ...
    "MaximumSeedCount", 5, "SeedClusterDistance_deg", 0, ...
    "CollocationSegmentCount", 10, ...
    "MaximumCollocationSegmentCount", 64, ...
    "MaximumMeshRefinementPasses", 2, "MaximumNlpIterations", 300, ...
    "MaximumNlpFunctionEvaluations", 30000, ...
    "ArrivalTimeTolerance_s", 1e-3, "ConstraintTolerance", 1e-7, ...
    "OptimalityTolerance", 1e-7, "StepTolerance", 1e-10, ...
    "CollisionClearanceTolerance_deg", 1e-7, ...
    "CollisionMinimumTimeStep_s", 0.00025, "Verbose", false);
if nargin == 0 || isempty(optionOverrides)
    optionOverrides = struct();
end
if ~isstruct(optionOverrides) || ~isscalar(optionOverrides)
    error("planTrajectory:InvalidOptions", ...
        "optionOverrides must be a scalar struct.");
end
for fieldName = ["AzimuthInterval_deg", "ElevationInterval_deg"]
    if isfield(optionOverrides, fieldName)
        replacementName = lower(extractBefore(fieldName, "Interval")) + ...
            "Interval_deg";
        error("planTrajectory:WorkspaceLimitMoved", ...
            "%s has moved from options to limits.%s.", ...
            fieldName, replacementName);
    end
end
[options, unknownNames] = obstacleAvoidance.input.resolveOptions( ...
    defaults, optionOverrides);
if ~isempty(unknownNames)
    warning("planTrajectory:UnknownOptions", ...
        "Ignoring unknown option fields: %s. No behavior changed.", ...
        strjoin(unknownNames, ", "));
end

%% Section 2: Normalize Public Values

textRules = {"GoalTimeMode", ["earliestArrival", "fixedArrival"], ...
    "planTrajectory:InvalidGoalTimeMode", ...
    "GoalTimeMode must be 'earliestArrival' or 'fixedArrival'."; ...
    "TrajectoryMethod", ["bmtp", "ruckigWaypoint"], ...
    "planTrajectory:InvalidTrajectoryMethod", ...
    "TrajectoryMethod must be 'bmtp' or 'ruckigWaypoint'."; ...
    "WaypointWarmStartMode", ["none", "passThrough"], ...
    "planTrajectory:InvalidWaypointWarmStartMode", ...
    "WaypointWarmStartMode must be 'none' or 'passThrough'."};
for ruleIndex = 1:size(textRules, 1)
    fieldName = textRules{ruleIndex, 1};
    options.(fieldName) = string(options.(fieldName));
    if ~isscalar(options.(fieldName)) || ...
            ~any(options.(fieldName) == textRules{ruleIndex, 2})
        error(textRules{ruleIndex, 3}, textRules{ruleIndex, 4});
    end
end
warmStartRequested = isfield(optionOverrides, "WaypointWarmStartMode") && ...
    ~isempty(optionOverrides.WaypointWarmStartMode);
packageRoot = fileparts(fileparts(mfilename("fullpath")));
warmStartFile = fullfile(packageRoot, "+planner", "ruckigWarmStart.m");
if options.WaypointWarmStartMode == "passThrough" && ~isfile(warmStartFile)
    options.WaypointWarmStartMode = "none";
    if warmStartRequested
        warning("planTrajectory:RuckigWarmStartUnavailable", ...
            "WaypointWarmStartMode='passThrough' was requested, but the " + ...
            "optional ruckigWarmStart.m file is not installed. Continuing " + ...
            "with WaypointWarmStartMode='none'.");
    end
end
for fieldName = ["AllowAzimuthWrapping", "Verbose"]
    options.(fieldName) = obstacleAvoidance.input.normalizeLogicalScalar( ...
        options.(fieldName), fieldName, ...
        "planTrajectory:InvalidLogicalOption");
end

validateattributes(options.SampleTime_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
integerRules = {"MaximumSeedCount", 1, 9; ...
    "CollocationSegmentCount", 2, 80; ...
    "MaximumCollocationSegmentCount", options.CollocationSegmentCount, 80; ...
    "MaximumMeshRefinementPasses", 0, 2};
for ruleIndex = 1:size(integerRules, 1)
    validateattributes(options.(integerRules{ruleIndex, 1}), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', ...
        '>=', integerRules{ruleIndex, 2}, '<=', integerRules{ruleIndex, 3}});
end
for fieldName = ["MaximumNlpIterations", "MaximumNlpFunctionEvaluations"]
    validateattributes(options.(fieldName), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', 'positive'});
end
for fieldName = ["ArrivalTimeTolerance_s", "ConstraintTolerance", ...
        "OptimalityTolerance", "StepTolerance", ...
        "CollisionMinimumTimeStep_s"]
    validateattributes(options.(fieldName), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'positive'});
end
for fieldName = ["SeedClusterDistance_deg", ...
        "CollisionClearanceTolerance_deg"]
    validateattributes(options.(fieldName), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'nonnegative'});
end
end
