import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import * as THREE from 'three';
import './styles.css';

const initialScene = { obstacles: [], initialState: { time_s: 0, position_deg: [-8, -5], velocity_deg_s: [0, 0], acceleration_deg_s2: [0, 0] }, goalState: { time_s: 20, position_deg: [8, 5], velocity_deg_s: [0, 0], acceleration_deg_s2: [0, 0] }, limits: { maxVelocity_deg_s: [2, 2], maxAcceleration_deg_s2: [0.75, 0.75], maxJerk_deg_s3: [2.5, 2.5], azimuthInterval_deg: [-20, 20], elevationInterval_deg: [-10, 10] }, plannerOptions: { GoalTimeMode: 'fixedArrival', MaximumSeedCount: 3 } };
const sceneBounds = (scene) => ({ left: scene.limits.azimuthInterval_deg[0], right: scene.limits.azimuthInterval_deg[1], bottom: scene.limits.elevationInterval_deg[0], top: scene.limits.elevationInterval_deg[1] });

function Plane({ scene, result, time, mode, onPoint, onVertexMove }) {
  const mount = useRef();
  useEffect(() => {
    const bounds = sceneBounds(scene); const renderer = new THREE.WebGLRenderer({ antialias: true });
    const camera = new THREE.OrthographicCamera(bounds.left, bounds.right, bounds.top, bounds.bottom, 0.1, 100); camera.position.z = 10;
    const world = new THREE.Scene(); world.background = new THREE.Color('#101827');
    const drawLine = (points, color, closed = false) => { if (!points?.length) return; const geometry = new THREE.BufferGeometry().setFromPoints((closed ? [...points, points[0]] : points).map(([x, y]) => new THREE.Vector3(x, y, 0))); world.add(new THREE.Line(geometry, new THREE.LineBasicMaterial({ color }))); };
    const drawVertices = (points, color) => { if (!points?.length) return; const geometry = new THREE.BufferGeometry().setFromPoints(points.map(([x, y]) => new THREE.Vector3(x, y, 0.1))); world.add(new THREE.Points(geometry, new THREE.PointsMaterial({ color, size: 8, sizeAttenuation: false }))); };
    const activeSlices = scene.obstacles.map((obstacle) => { const index = Math.max(0, obstacle.slices.findLastIndex((_, sliceIndex) => (obstacle.time_s?.[sliceIndex] ?? 0) <= time)); const vertices = obstacle.slices[index]?.vertices_deg ?? []; drawLine(vertices, 0xee7d72, true); if (mode === 'edit') drawVertices(vertices, 0xfbbf24); return index; });
    drawVertices([scene.initialState.position_deg], 0x4ade80); drawVertices([scene.goalState.position_deg], 0xf87171); if (result?.position_deg?.length) drawLine(result.position_deg, 0x60a5fa);
    renderer.setSize(mount.current.clientWidth, mount.current.clientHeight); mount.current.appendChild(renderer.domElement); renderer.render(world, camera);
    const toPosition = (event) => { const box = renderer.domElement.getBoundingClientRect(); return [bounds.left + (event.clientX - box.left) / box.width * (bounds.right - bounds.left), bounds.top - (event.clientY - box.top) / box.height * (bounds.top - bounds.bottom)]; };
    let drag = null;
    const findVertex = (event) => { const position = toPosition(event); const box = renderer.domElement.getBoundingClientRect(); const threshold_deg = 12 / box.width * (bounds.right - bounds.left); let nearest = null; scene.obstacles.forEach((obstacle, obstacleIndex) => obstacle.slices[activeSlices[obstacleIndex]]?.vertices_deg.forEach((vertex, vertexIndex) => { const distance = Math.hypot(vertex[0] - position[0], vertex[1] - position[1]); if (distance <= threshold_deg && (!nearest || distance < nearest.distance)) nearest = { obstacleIndex, vertexIndex, distance }; })); return nearest; };
    const pointerDown = (event) => { if (mode === 'edit') drag = findVertex(event); }; const pointerMove = (event) => { if (drag) onVertexMove(drag, toPosition(event)); }; const pointerUp = (event) => { if (drag) { drag = null; return; } if (mode !== 'edit') onPoint(toPosition(event)); };
    renderer.domElement.addEventListener('pointerdown', pointerDown); renderer.domElement.addEventListener('pointermove', pointerMove); renderer.domElement.addEventListener('pointerup', pointerUp);
    return () => { renderer.domElement.removeEventListener('pointerdown', pointerDown); renderer.domElement.removeEventListener('pointermove', pointerMove); renderer.domElement.removeEventListener('pointerup', pointerUp); renderer.dispose(); mount.current?.replaceChildren(); };
  }, [scene, result, time, mode, onPoint, onVertexMove]);
  return <div className="plane" ref={mount} />;
}

function App() {
  const [scene, setScene] = useState(initialScene); const [mode, setMode] = useState('polygon'); const [draft, setDraft] = useState([]); const [job, setJob] = useState(null); const [response, setResponse] = useState(); const [time, setTime] = useState(0); const [latency, setLatency] = useState();
  const point = (position_deg) => { if (mode === 'start') setScene((current) => ({ ...current, initialState: { ...current.initialState, position_deg } })); else if (mode === 'goal') setScene((current) => ({ ...current, goalState: { ...current.goalState, position_deg } })); else if (mode === 'polygon') setDraft((current) => [...current, position_deg]); };
  const moveVertex = ({ obstacleIndex, vertexIndex }, position_deg) => setScene((current) => ({ ...current, obstacles: current.obstacles.map((obstacle, index) => index !== obstacleIndex ? obstacle : { ...obstacle, slices: obstacle.slices.map((slice) => slice.vertices_deg.length > vertexIndex ? { ...slice, vertices_deg: slice.vertices_deg.map((vertex, index) => index === vertexIndex ? position_deg : vertex) } : slice) }) }));
  const finishPolygon = () => { if (draft.length >= 3) setScene((current) => ({ ...current, obstacles: [...current.obstacles, { name: `polygon ${current.obstacles.length + 1}`, time_s: [current.initialState.time_s, current.goalState.time_s], safetyMargin_deg: 0, slices: [{ vertices_deg: draft }, { vertices_deg: draft }] }] })); setDraft([]); };
  const queue = async (url, options, type) => { setResponse(); setLatency(); const startedAt_ms = performance.now(); const result = await fetch(url, options); const payload = await result.json(); if (!payload.Success) throw new Error(payload.Error?.Message || 'The bridge rejected the request.'); setJob({ id: payload.JobId, type, startedAt_ms }); };
  const run = () => queue('/api/plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...scene, mode: 'trajectory' }) }, 'plan');
  const importBundle = async (event) => { const [bundle] = event.target.files; if (!bundle) return; await queue('/api/bundles/import', { method: 'POST', headers: { 'Content-Type': 'application/octet-stream', 'X-Bundle-Name': bundle.name }, body: bundle }, 'import'); event.target.value = ''; };
  const exportBundle = () => queue('/api/bundles/export', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...scene, bundleFileName: 'az_el_web_sandbox.mat' }) }, 'export');
  useEffect(() => { if (!job) return undefined; const timer = setInterval(async () => { const poll = await fetch(`/api/jobs/${job.id}`); const payload = await poll.json(); if (payload.Status !== 'completed') return; clearInterval(timer); if (job.type === 'import' && payload.Response.Scene) setScene(payload.Response.Scene); setResponse(payload.Response); requestAnimationFrame(() => setLatency({ clickToRender_s: (performance.now() - job.startedAt_ms) / 1000, planner_s: payload.Response.ElapsedWallTime_s })); }, 100); return () => clearInterval(timer); }, [job]);
  const cancel = () => fetch(`/api/jobs/${job.id}/cancel`, { method: 'POST' }); const duration = response?.Result?.TrajectoryDuration_s || scene.goalState.time_s; const busy = job && !response; const transport_s = latency ? Math.max(0, latency.clickToRender_s - (latency.planner_s || 0)) : undefined;
  return <main><header><h1>Az/El Planner Sandbox</h1><span>{response?.Result?.TerminationReason || response?.Error?.Identifier || (busy ? 'planning' : 'ready')}</span></header><section className="workspace"><Plane scene={scene} result={response?.Result} time={time} mode={mode} onPoint={point} onVertexMove={moveVertex} /><aside><button onClick={() => setMode('polygon')}>Draw polygon</button><button onClick={finishPolygon}>Finish polygon ({draft.length})</button><button onClick={() => setMode('edit')}>Edit vertices</button><button onClick={() => setMode('start')}>Place start</button><button onClick={() => setMode('goal')}>Place goal</button><button disabled={busy} onClick={run}>Run planner</button><button disabled={!busy || job.type !== 'plan'} onClick={cancel}>Cancel</button><label>Load sandbox bundle <input aria-label="Load sandbox bundle" type="file" accept=".mat" disabled={busy} onChange={importBundle} /></label><button disabled={busy} onClick={exportBundle}>Save sandbox bundle</button><label>Mission time <input value={scene.goalState.time_s} type="number" onChange={(event) => setScene((current) => ({ ...current, goalState: { ...current.goalState, time_s: +event.target.value } }))} /></label><label>Velocity az/el <input value={scene.limits.maxVelocity_deg_s.join(',')} onChange={(event) => setScene((current) => ({ ...current, limits: { ...current.limits, maxVelocity_deg_s: event.target.value.split(',').map(Number) } }))} /></label>{latency && <output>Click to render: {latency.clickToRender_s.toFixed(3)} s; planner: {latency.planner_s.toFixed(3)} s; transport/UI: {transport_s.toFixed(3)} s</output>}{response?.DownloadUrl && <a href={response.DownloadUrl}>Download saved MATLAB bundle</a>}<pre>{JSON.stringify(response?.Diagnostics || response?.Error || { draftVertices: draft.length, obstacleCount: scene.obstacles.length, editMode: mode === 'edit' }, null, 2)}</pre></aside></section><input aria-label="Trajectory time" className="scrub" type="range" min={scene.initialState.time_s} max={duration} step="0.01" value={Math.min(time, duration)} onChange={(event) => setTime(+event.target.value)} /></main>;
}
createRoot(document.getElementById('root')).render(<App />);
