function [result, emptySeedSummary] = emptyPlannerResult( ...
        obstacles, initialState, goalState, limits, options, ...
        validationTemplate)
%% Section 0: Header & Readme
% SYNTAX
%   [result, emptySeedSummary] = azElPlanner.emptyPlannerResult( ...
%       obstacles, initialState, goalState, limits, options, ...
%       validationTemplate)
%**************************************************************************
% PURPOSE
%   - Define the stable HS3 success-or-failure result and candidate-summary
%     schemas used by the maintained planner.
%**************************************************************************
% INPUTS
%   - obstacles (canonical protected obstacle struct array)
%   - initialState, goalState (normalized scalar state structs)
%   - limits, options (normalized scalar planner-input structs)
%   - validationTemplate (scalar struct)
%       Empty canonical validation record.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Empty public planner result with stable motion and diagnostics fields.
%   - emptySeedSummary (scalar struct)
%       Stable HS3 candidate-summary template.
%**************************************************************************
% UNITS
%   - Position is degrees. Time is seconds. Derivatives use deg/s, deg/s^2,
%     and deg/s^3.
%**************************************************************************

%% Section 1: Build HS3 Templates

emptySeed = struct( ...
    "Index", 0, "Source", "", ...
    "position_deg", zeros(0, 2), "tau", zeros(0, 1), ...
    "CorridorBoundary_deg", zeros(0, 2), ...
    "UsesReducedGeometry", false, ...
    "EstimatedDuration_s", NaN, "Length_deg", NaN);

emptySeedSummary = struct( ...
    "SeedIndex", 0, "SeedSource", "", "SelectedMotionSource", "", ...
    "OptimizerFeasible", false, "ValidationPassed", false, ...
    "CollisionFree", false, "CollisionResolved", false, ...
    "MinimumClearance_deg", NaN, "UnresolvedIntervalCount", 0, ...
    "ArrivalTime_s", NaN, "MotionDuration_s", NaN, ...
    "IntegratedSquaredJerk_deg2_s5", Inf, ...
    "MaximumConstraintViolation", Inf, ...
    "RelinearizationCount", 0, "MeshRefinementPassCount", 0, ...
    "FirstMotionAttempted", false, ...
    "FirstMotionValidationPassed", false, ...
    "FirstMotionTerminationReason", "notRun", ...
    "FirstMotionDiagnostics", struct(), ...
    "Hs3Attempted", false, ...
    "Hs3OptimizerFeasible", false, ...
    "Hs3ValidationPassed", false, ...
    "Hs3TerminationReason", "notRun", ...
    "Hs3SolverDiagnostics", struct(), ...
    "TerminationReason", "notRun", ...
    "Message", "", ...
    "SolverDiagnostics", struct());

emptyPolynomial = struct( ...
    "SegmentCount", 0, "SegmentStartTime_s", zeros(0, 1), ...
    "SegmentDuration_s", NaN, "FinalTime_s", NaN, ...
    "positionPower_deg", zeros(0, 2, 6), ...
    "velocityPower_deg_s", zeros(0, 2, 5), ...
    "accelerationPower_deg_s2", zeros(0, 2, 4), ...
    "jerkPower_deg_s3", zeros(0, 2, 3), ...
    "TerminalState", struct( ...
    "position_deg", [NaN NaN], "velocity_deg_s", [NaN NaN], ...
    "acceleration_deg_s2", [NaN NaN]));

searchDiagnostics = struct( ...
    "PlannerMethod", "hs3", ...
    "Grid", struct(), ...
    "SeedSummaries", repmat(emptySeedSummary, 0, 1), ...
    "BestPartialSeedIndex", 0, "MeshRefinementPassCount", 0, ...
    "ValidatedCandidateCount", 0, "FirstValidatedMotionTime_s", NaN, ...
    "SeedGenerationElapsedTime_s", 0, ...
    "FirstMotionElapsedTime_s", 0, "Hs3ElapsedTime_s", 0, ...
    "AttemptedSeedCount", 0, "TerminationReason", "notRun", ...
    "StageTiming", azElPlanner.stageTiming());

%% Section 2: Assemble The Stable Result

result = struct( ...
    "Success", false, "Message", "Planning was not completed.", ...
    "TerminationReason", "notRun", ...
    "Options", options, ...
    "Inputs", struct( ...
    "obstacles", obstacles, ...
    "initialState", initialState, ...
    "goalState", goalState, ...
    "limits", limits), ...
    "Seeds", repmat(emptySeed, 0, 1), ...
    "SeedSummaries", repmat(emptySeedSummary, 0, 1), ...
    "SelectedSeedIndex", 0, "SelectedMotionSource", "", ...
    "SelectedSeed_deg", zeros(0, 2), ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2), ...
    "Polynomial", emptyPolynomial, ...
    "SeedCorridorBoundary_deg", zeros(0, 2), ...
    "SeedCorridor", struct([]), ...
    "Validation", validationTemplate, ...
    "ArrivalTime_s", NaN, "TrajectoryDuration_s", NaN, ...
    "GoalHorizon_s", goalState.time_s - initialState.time_s, ...
    "FirstValidatedMotionTime_s", NaN, ...
    "SearchDiagnostics", searchDiagnostics, ...
    "ElapsedPlanningTime_s", 0, "RandomSeed", options.RandomSeed, ...
    "OptimalityStatement", ...
    "No motion was validated from the bounded candidate work.");
end
