function [options, compactOverrides] = resolvePlannerOptions(optionOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   [options, compactOverrides] = ...
%       azElPlannerMethods.hs3.resolvePlannerOptions()
%   [options, compactOverrides] = ...
%       azElPlannerMethods.hs3.resolvePlannerOptions(optionOverrides)
%**************************************************************************
% PURPOSE
%   - Own, resolve, and validate HS3 options once while projecting only
%     options shared with the compact corridor baseline.
%**************************************************************************
% INPUTS
%   - optionOverrides (scalar struct, optional; default struct())
%       Partial HS3 overrides. Empty fields retain their defaults.
%       PlannerMethod and MotionMethod remain public-dispatcher concerns.
%**************************************************************************
% OUTPUTS
%   - options (scalar struct)
%       Fully resolved and validated HS3 options in stable field order.
%   - compactOverrides (scalar struct)
%       Resolved options accepted by both HS3 and corridor, with no method
%       selector, compatibility field, or HS3-only solver control.
%**************************************************************************
% UNITS
%   - Times are seconds, angles are degrees, and tolerances retain the units
%     documented by planAzElMotion.
%**************************************************************************

%% Section 1: Resolve The Complete HS3 Option Record

defaults = struct( ...
    "GoalTimeMode", "earliestArrival", ...
    "SampleTime_s", 0.05, ...
    "AllowAzimuthWrapping", false, ...
    "MaximumSeedCount", 5, ...
    "DirectSeedOnly", false, ...
    "SeedClusterDistance_deg", 0, ...
    "CollocationSegmentCount", 10, ...
    "MaximumCollocationSegmentCount", 24, ...
    "MaximumMeshRefinementPasses", 0, ...
    "MaximumNlpIterations", 300, ...
    "MaximumNlpFunctionEvaluations", 30000, ...
    "EnableHs3Improvement", false, ...
    "MaximumHs3ImprovementTime_s", 15, ...
    "ArrivalTimeTolerance_s", 1e-3, ...
    "ConstraintTolerance", 1e-7, ...
    "OptimalityTolerance", 1e-7, ...
    "StepTolerance", 1e-10, ...
    "CollisionClearanceTolerance_deg", 1e-7, ...
    "CollisionMinimumTimeStep_s", 0.00025, ...
    "Verbose", false, ...
    "RandomSeed", 0);
if nargin == 0 || isempty(optionOverrides)
    optionOverrides = struct();
end
if ~isstruct(optionOverrides) || ~isscalar(optionOverrides)
    error("planAzElMotion:InvalidOptions", ...
        "optionOverrides must be a scalar struct.");
end
removedNames = ["MaximumPlanningTime_s", "AzimuthInterval_deg", "ElevationInterval_deg"];
for removedName = removedNames
    if isfield(optionOverrides, removedName)
        if removedName == "MaximumPlanningTime_s"
            error("planAzElMotion:RemovedMaximumPlanningTime", ...
                "MaximumPlanningTime_s has been removed. Use finite " + ...
                "algorithmic work limits and Verbose progress instead.");
        end
        replacementName = lower(extractBefore( ...
            removedName, "Interval")) + "Interval_deg";
        error("planAzElMotion:WorkspaceLimitMoved", ...
            "%s has moved from options to limits.%s.", ...
            removedName, replacementName);
    end
end
[options, unknownNames] = azElInternal.resolveOptions(defaults, optionOverrides);
if ~isempty(unknownNames)
    warning("planAzElMotion:UnknownOptions", ...
        "Ignoring unknown option fields: %s. No behavior changed.", ...
        strjoin(unknownNames, ", "));
end

%% Section 2: Normalize And Validate Every Public Value

options.GoalTimeMode = string(options.GoalTimeMode);
if ~isscalar(options.GoalTimeMode) || ~any( ...
        options.GoalTimeMode == ["earliestArrival", "fixedArrival"])
    error("planAzElMotion:InvalidGoalTimeMode", ...
        "GoalTimeMode must be 'earliestArrival' or 'fixedArrival'.");
end
logicalNames = ["AllowAzimuthWrapping", "DirectSeedOnly", ...
    "EnableHs3Improvement", "Verbose"];
for name = logicalNames
    options.(name) = azElInternal.normalizeLogicalScalar( ...
        options.(name), name, "planAzElMotion:InvalidLogicalOption");
end
validateattributes(options.SampleTime_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
validateattributes(options.MaximumSeedCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 1, '<=', 9});
validateattributes(options.SeedClusterDistance_deg, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'});
validateattributes(options.CollocationSegmentCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 2, '<=', 40});
validateattributes(options.MaximumCollocationSegmentCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', ...
    '>=', options.CollocationSegmentCount, '<=', 40});
validateattributes(options.MaximumMeshRefinementPasses, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 0, '<=', 2});
integerNames = ["MaximumNlpIterations", "MaximumNlpFunctionEvaluations"];
for name = integerNames
    validateattributes(options.(name), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', 'positive'});
end
positiveNames = ["ArrivalTimeTolerance_s", "ConstraintTolerance", ...
    "OptimalityTolerance", "StepTolerance", ...
    "CollisionMinimumTimeStep_s"];
for name = positiveNames
    validateattributes(options.(name), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'positive'});
end
validateattributes(options.CollisionClearanceTolerance_deg, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'});
validateattributes(options.MaximumHs3ImprovementTime_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'});
validateattributes(options.RandomSeed, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'nonnegative'});

%% Section 3: Project Only Compact-Baseline Controls

commonNames = ["GoalTimeMode", "SampleTime_s", ...
    "AllowAzimuthWrapping", "MaximumSeedCount", "DirectSeedOnly", ...
    "SeedClusterDistance_deg", "ArrivalTimeTolerance_s", ...
    "ConstraintTolerance", "CollisionClearanceTolerance_deg", ...
    "CollisionMinimumTimeStep_s", "Verbose", "RandomSeed"];
compactOverrides = struct();
for name = commonNames
    compactOverrides.(name) = options.(name);
end
end
