function scenario = createRandomInterceptionScenario(caseIndex, obstacleFamily, randomSeed)
%% Section 0: Header & Readme
% SYNTAX
%   scenario = createRandomInterceptionScenario(caseIndex, obstacleFamily)
%   scenario = createRandomInterceptionScenario(caseIndex, obstacleFamily, randomSeed)
%**************************************************************************
% PURPOSE
%   - Create deterministic moving-target interception requests with either
%     a static exclusion zone or translating obstacles.
%   - Include successful detours, target entry/exit, and stable blocked-goal
%     outcomes without changing the caller's global random stream.
%**************************************************************************
% INPUTS
%   - caseIndex (positive integer scalar)
%       Selects one independent substream from the seeded random stream.
%   - obstacleFamily (scalar text)
%       "staticZone" or "movingObstacles".
%   - randomSeed (integer scalar in [0, 2^32-1], optional; default 941207)
%       Seed for the local random stream.
%**************************************************************************
% OUTPUTS
%   - scenario (scalar struct)
%       Public planner arguments and deterministic expectations used by the
%       randomized interception regression suite.
%**************************************************************************
% UNITS
%   - Positions are coordinate units. Time is seconds; velocity,
%     acceleration, and jerk use units/s, units/s^2, and units/s^3.
%**************************************************************************

%% Section 1: Validate Inputs And Draw One Independent Case

if nargin < 3
    randomSeed = 941207;
end
validateattributes(caseIndex, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'});
validateattributes(randomSeed, {'numeric'}, ...
    {'scalar', 'integer', '>=', 0, '<=', 2^32 - 1});
obstacleFamily = string(obstacleFamily);
if ~isscalar(obstacleFamily) || ...
        ~any(obstacleFamily == ["staticZone", "movingObstacles"])
    error('createRandomInterceptionScenario:InvalidFamily', ...
        'obstacleFamily must be staticZone or movingObstacles.');
end

stream           = RandStream('mrg32k3a', 'Seed', randomSeed);
stream.Substream = caseIndex;
randomDraw       = rand(stream, 1, 19);

missionEndTime_s = 12 + 2 * randomDraw(1);
center_units     = [-1.5 + 3 * randomDraw(2), -1.5 + 3 * randomDraw(3)];
angle_rad        = 2 * pi * randomDraw(4);
alongDirection   = [cos(angle_rad), sin(angle_rad)];
crossDirection   = [-alongDirection(2), alongDirection(1)];

limits = struct( ...
    'xInterval_units',          [-20, 20], ...
    'yInterval_units',          [-20, 20], ...
    'maxVelocity_units_s',      [2.5, 2.5], ...
    'maxAcceleration_units_s2', [1.2, 1.2], ...
    'maxJerk_units_s3',         [2.5, 2.5]);
options = struct( ...
    'GoalTimeMode',       'fixedArrival', ...
    'SampleTime_s',       0.1, ...
    'TemporalResolution_s', 1, ...
    'MaxArrivalTrials',   16);

%% Section 2: Construct The Requested Obstacle Family

if obstacleFamily == "staticZone"
    [obstacles, initialPosition_units, targetPosition_units, options, ...
        expectedSuccess, expectedReason, occupancyPattern] = createStaticZoneCase( ...
        caseIndex, randomDraw, center_units, ...
        alongDirection, crossDirection, options);
    directRouteShouldBeBlocked = false;
else
    [obstacles, initialPosition_units, targetPosition_units, ...
        expectedSuccess, expectedReason, directRouteShouldBeBlocked, ...
        occupancyPattern] = createMovingObstacleCase( ...
        caseIndex, randomDraw, missionEndTime_s, center_units, ...
        alongDirection, crossDirection);
end

targetTime_s = [0; missionEndTime_s];
targetMotion = struct( ...
    'time_s',              targetTime_s, ...
    'position_units',      targetPosition_units, ...
    'InterpolationMethod', 'linear');
initialState = struct( ...
    'time_s',                0, ...
    'position_units',        initialPosition_units, ...
    'velocity_units_s',      [0, 0], ...
    'acceleration_units_s2', [0, 0]);
goalState = struct( ...
    'time_s',       missionEndTime_s, ...
    'targetMotion', targetMotion);

%% Section 3: Return Planner Inputs And Reproduction Metadata

scenario = struct( ...
    'Obstacles',                  obstacles, ...
    'InitialState',               initialState, ...
    'GoalState',                  goalState, ...
    'Limits',                     limits, ...
    'Options',                    options, ...
    'CaseIndex',                  caseIndex, ...
    'ObstacleFamily',             obstacleFamily, ...
    'RandomSeed',                 randomSeed, ...
    'ExpectedSuccess',            expectedSuccess, ...
    'ExpectedTerminationReason',  expectedReason, ...
    'TargetOccupancyPattern',     occupancyPattern, ...
    'DirectRouteShouldBeBlocked', directRouteShouldBeBlocked);
end

%% Section 4: Local Functions

function [obstacles, initialPosition_units, targetPosition_units, options, ...
        expectedSuccess, expectedReason, occupancyPattern] = createStaticZoneCase( ...
        caseIndex, randomDraw, center_units, ...
        alongDirection, crossDirection, options)
    % Make the target cross, leave, or finish inside one rotated static zone.
    halfSize_units = [1.0 + 0.45 * randomDraw(5), ...
        0.85 + 0.35 * randomDraw(6)];
    zoneVertices_units = rectangleVertices( ...
        center_units, alongDirection, crossDirection, halfSize_units);
    obstacles = obstacleAvoidance.obstacles.createObstacle( ...
        "Random static target zone " + caseIndex, 0, ...
        zoneVertices_units(:, 1), zoneVertices_units(:, 2), 0.08);

    lateralOffset_units = (-0.35 + 0.7 * randomDraw(7)) * halfSize_units(2);
    lateral_units       = lateralOffset_units * crossDirection;
    patternIndex        = mod(caseIndex - 1, 3) + 1;
    expectedSuccess     = true;
    expectedReason      = "goalReached";

    if patternIndex == 1
        occupancyPattern     = "outsideInsideOutside";
        targetStart_units    = center_units - ...
            (4.5 + randomDraw(8)) * alongDirection + lateral_units;
        targetEnd_units      = center_units + ...
            (4.5 + randomDraw(9)) * alongDirection + lateral_units;
        initialPosition_units = targetStart_units - ...
            (1.2 + randomDraw(10)) * alongDirection + ...
            directionSign(randomDraw(11)) * (2.4 + 0.5 * randomDraw(12)) * crossDirection;
    elseif patternIndex == 2
        occupancyPattern      = "insideOutside";
        targetStart_units     = center_units + lateral_units;
        targetEnd_units       = center_units + ...
            (5.5 + randomDraw(8)) * alongDirection + lateral_units;
        initialPosition_units = center_units - ...
            (5.0 + randomDraw(9)) * alongDirection + ...
            directionSign(randomDraw(10)) * (2.5 + 0.5 * randomDraw(11)) * crossDirection;
        options.GoalTimeMode = 'earliestArrival';
    else
        occupancyPattern      = "outsideInside";
        targetStart_units     = center_units - ...
            (5.0 + randomDraw(8)) * alongDirection + lateral_units;
        targetEnd_units       = center_units + lateral_units;
        initialPosition_units = targetStart_units - ...
            (1.5 + randomDraw(9)) * alongDirection + ...
            directionSign(randomDraw(10)) * (2.2 + 0.5 * randomDraw(11)) * crossDirection;
        expectedSuccess = false;
        expectedReason  = "endpointBlocked";
    end
    targetPosition_units = [targetStart_units; targetEnd_units];
end

function [obstacles, initialPosition_units, targetPosition_units, ...
        expectedSuccess, expectedReason, directRouteShouldBeBlocked, ...
        occupancyPattern] = createMovingObstacleCase( ...
        caseIndex, randomDraw, missionEndTime_s, center_units, ...
        alongDirection, crossDirection)
    % Place translating rectangles on the fixed-arrival direct chord.
    initialPosition_units = center_units - ...
        (6.0 + randomDraw(5)) * alongDirection + ...
        (-0.4 + 0.8 * randomDraw(6)) * crossDirection;
    targetStart_units = center_units + ...
        (3.0 + randomDraw(7)) * alongDirection + ...
        (-0.5 + randomDraw(8)) * crossDirection;
    targetEnd_units = targetStart_units + ...
        (2.0 + randomDraw(9)) * alongDirection + ...
        (-0.5 + randomDraw(10)) * crossDirection;
    targetPosition_units = [targetStart_units; targetEnd_units];

    patternIndex = mod(caseIndex - 1, 3) + 1;
    if patternIndex == 3
        % The target is covered only at the declared intercept. This is a
        % moving-obstacle endpoint failure, not a malformed input.
        halfSize_units = [0.9 + 0.2 * randomDraw(11), ...
            0.9 + 0.2 * randomDraw(12)];
        travel_units = (4.0 + randomDraw(13)) * ...
            directionSign(randomDraw(14)) * crossDirection;
        centerAtStart_units = targetEnd_units - travel_units;
        centerAtEnd_units   = targetEnd_units;
        obstacles = translatingRectangle( ...
            "Random moving endpoint cover " + caseIndex, missionEndTime_s, ...
            centerAtStart_units, centerAtEnd_units, alongDirection, ...
            crossDirection, halfSize_units);
        expectedSuccess            = false;
        expectedReason             = "endpointBlocked";
        directRouteShouldBeBlocked = false;
        occupancyPattern           = "outsideInside";
        return
    end

    blockFraction = 0.42 + 0.14 * randomDraw(11);
    blockPoint_units = initialPosition_units + blockFraction * ...
        (targetEnd_units - initialPosition_units);
    travel_units = directionSign(randomDraw(12)) * ...
        (4.5 + randomDraw(13)) * crossDirection;
    centerAtStart_units = blockPoint_units - blockFraction * travel_units;
    centerAtEnd_units   = blockPoint_units + (1 - blockFraction) * travel_units;
    halfSize_units      = [0.65 + 0.2 * randomDraw(14), ...
        0.85 + 0.25 * randomDraw(15)];
    primaryObstacle = translatingRectangle( ...
        "Random moving blocker A " + caseIndex, missionEndTime_s, ...
        centerAtStart_units, centerAtEnd_units, alongDirection, ...
        crossDirection, halfSize_units);
    obstacles = primaryObstacle;

    if patternIndex == 2
        secondFraction = 0.68 + 0.08 * randomDraw(16);
        secondPoint_units = initialPosition_units + secondFraction * ...
            (targetEnd_units - initialPosition_units);
        secondTravel_units = -directionSign(randomDraw(12)) * ...
            (4.0 + randomDraw(17)) * crossDirection;
        secondStart_units = secondPoint_units - secondFraction * secondTravel_units;
        secondEnd_units   = secondPoint_units + (1 - secondFraction) * secondTravel_units;
        secondHalf_units  = [0.55 + 0.2 * randomDraw(18), ...
            0.75 + 0.2 * randomDraw(19)];
        secondaryObstacle = translatingRectangle( ...
            "Random moving blocker B " + caseIndex, missionEndTime_s, ...
            secondStart_units, secondEnd_units, alongDirection, ...
            crossDirection, secondHalf_units);
        obstacles = obstacleAvoidance.obstacles.combineObstacles( ...
            primaryObstacle, secondaryObstacle);
    end

    expectedSuccess            = true;
    expectedReason             = "goalReached";
    directRouteShouldBeBlocked = true;
    occupancyPattern           = "outsideOutside";
end

function obstacle = translatingRectangle(name, missionEndTime_s, ...
        centerAtStart_units, centerAtEnd_units, alongDirection, ...
        crossDirection, halfSize_units)
    % Represent exact constant translation with corresponding rectangle vertices.
    startVertices_units = rectangleVertices( ...
        centerAtStart_units, alongDirection, crossDirection, halfSize_units);
    endVertices_units = rectangleVertices( ...
        centerAtEnd_units, alongDirection, crossDirection, halfSize_units);
    constructionOptions = struct('vertexCorrespondence', 'sourceIndex');
    obstacle = obstacleAvoidance.obstacles.createObstacle( ...
        name, [0; missionEndTime_s], ...
        {startVertices_units(:, 1); endVertices_units(:, 1)}, ...
        {startVertices_units(:, 2); endVertices_units(:, 2)}, ...
        0.06, constructionOptions);
end

function vertices_units = rectangleVertices(center_units, alongDirection, ...
        crossDirection, halfSize_units)
    % Return one consistently ordered rectangle in the supplied local frame.
    cornerSign = [-1, -1; 1, -1; 1, 1; -1, 1];
    vertices_units = center_units + ...
        cornerSign(:, 1) .* (halfSize_units(1) * alongDirection) + ...
        cornerSign(:, 2) .* (halfSize_units(2) * crossDirection);
end

function signValue = directionSign(randomValue)
    % Convert a continuous draw into a deterministic nonzero sign.
    signValue = 2 * (randomValue >= 0.5) - 1;
end
