function diagnostic = diagnoseUShapeInflation(safetyMargin_deg)
%% Section 0: Header & Readme
% SYNTAX
%   diagnostic = diagnoseUShapeInflation()
%   diagnostic = diagnoseUShapeInflation(safetyMargin_deg)
%**************************************************************************
% PURPOSE
%   - Isolate U-shaped safety-margin inflation from visibility planning.
%   - Compare a pre-inflated polygon against the original polygon queried
%     with the same Euclidean SafetyMarginDeg.
%   - Print inflated vertices, packed edges, ray crossings, mismatches, and
%     possible self-intersections that can explain a triangular artifact.
%**************************************************************************
% OUTPUTS
%   - diagnostic (scalar struct)
%       Geometry, occupancy masks, mismatch locations, edge diagnostics,
%       and figure handles.
%**************************************************************************
% UNITS
%   - Azimuth/elevation and safetyMargin_deg are degrees.

if nargin < 1 || isempty(safetyMargin_deg)
    safetyMargin_deg = 1.5;
end
validateattributes(safetyMargin_deg, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'});

%% Section 1: Rebuild Only The U & Its Two Collision Representations
missionEndTime_s = 35;
time_s = [0; missionEndTime_s];
uBoundary_deg = [ ...
    -8,  7; ...
    -5,  7; ...
    -5, -4; ...
     5, -4; ...
     5,  7; ...
     8,  7; ...
     8, -7; ...
    -8, -7];
azElData = makeAzElObstacleData( ...
    "Static U-shaped obstacle", time_s, ...
    uBoundary_deg(:, 1), uBoundary_deg(:, 2));
originalField = buildAzElTimeObstacleField(azElData, struct( ...
    "MaximumVerticesPerRegion", Inf));
inflatedAzElData = makeAzElObstacleData( ...
    "Static U-shaped obstacle", time_s, ...
    uBoundary_deg(:, 1), uBoundary_deg(:, 2), safetyMargin_deg);
inflatedField = buildAzElTimeObstacleField(inflatedAzElData, struct( ...
    "MaximumVerticesPerRegion", Inf));
inflatedFieldDefaultCap = buildAzElTimeObstacleField(inflatedAzElData);

%% Section 2: Compare The Same Margin On One Dense Grid
gridStep_deg = 0.10;
azimuthGrid_deg = -11:gridStep_deg:11;
elevationGrid_deg = -12:gridStep_deg:9;
[azimuthMesh_deg, elevationMesh_deg] = meshgrid( ...
    azimuthGrid_deg, elevationGrid_deg);
queryAzimuth_deg = azimuthMesh_deg(:);
queryElevation_deg = elevationMesh_deg(:);
queryTime_s = zeros(size(queryAzimuth_deg));
baseQueryOptions = struct( ...
    "CollisionMode", "polygon", ...
    "TimePaddingSamples", 0, ...
    "SafetyMarginDeg", 0);
referenceQueryOptions = baseQueryOptions;
referenceQueryOptions.SafetyMarginDeg = safetyMargin_deg;

referenceBlocked = queryAzElTimeObstacle(originalField, ...
    queryAzimuth_deg, queryElevation_deg, queryTime_s, ...
    referenceQueryOptions);
inflatedBlocked = queryAzElTimeObstacle(inflatedField, ...
    queryAzimuth_deg, queryElevation_deg, queryTime_s, ...
    baseQueryOptions);
defaultCapBlocked = queryAzElTimeObstacle(inflatedFieldDefaultCap, ...
    queryAzimuth_deg, queryElevation_deg, queryTime_s, ...
    baseQueryOptions);
referenceBlocked = reshape(logical(referenceBlocked), size(azimuthMesh_deg));
inflatedBlocked = reshape(logical(inflatedBlocked), size(azimuthMesh_deg));
defaultCapBlocked = reshape(logical(defaultCapBlocked), ...
    size(azimuthMesh_deg));
falsePositiveMask = inflatedBlocked & ~referenceBlocked;
falseNegativeMask = ~inflatedBlocked & referenceBlocked;
vertexCapMismatchMask = defaultCapBlocked ~= inflatedBlocked;

%% Section 3: Extract Exactly What Inflation & Packing Produced
inflatedAzimuth_deg = double(inflatedAzElData.az_deg{1}(:));
inflatedElevation_deg = double(inflatedAzElData.el_deg{1}(:));
inflatedBoundary_deg = [inflatedAzimuth_deg, inflatedElevation_deg];
finiteInflatedVertex = all(isfinite(inflatedBoundary_deg), 2);
inflatedBoundary_deg = inflatedBoundary_deg(finiteInflatedVertex, :);

packedObstacle = inflatedField.Obstacles(1);
firstVertex = double(packedObstacle.SliceOffsets(1));
lastVertex = double(packedObstacle.SliceOffsets(2) - 1);
packedBoundary_deg = double([ ...
    packedObstacle.AzimuthDeg(firstVertex:lastVertex), ...
    packedObstacle.ElevationDeg(firstVertex:lastVertex)]);
packedBoundary_deg = packedBoundary_deg( ...
    all(isfinite(packedBoundary_deg), 2), :);
firstEdge = double(packedObstacle.EdgeOffsets(1));
lastEdge = double(packedObstacle.EdgeOffsets(2) - 1);
packedEdges_deg = double([ ...
    packedObstacle.EdgeStartAzimuthDeg(firstEdge:lastEdge), ...
    packedObstacle.EdgeStartElevationDeg(firstEdge:lastEdge), ...
    packedObstacle.EdgeEndAzimuthDeg(firstEdge:lastEdge), ...
    packedObstacle.EdgeEndElevationDeg(firstEdge:lastEdge)]);
edgeLength_deg = hypot( ...
    packedEdges_deg(:, 3) - packedEdges_deg(:, 1), ...
    packedEdges_deg(:, 4) - packedEdges_deg(:, 2));
[sortedEdgeLength_deg, sortedEdgeIndex] = sort(edgeLength_deg, "descend");
longestEdgeCount = min(12, numel(sortedEdgeIndex));
longestEdgeIndex = sortedEdgeIndex(1:longestEdgeCount);
selfIntersectionPairs = findProperSelfIntersections(packedEdges_deg);

startPoint_deg = [0 0];
goalPoint_deg = [0 -10];
[startCrossingIndex, startCrossingAzimuth_deg] = ...
    horizontalRayCrossings(packedEdges_deg, startPoint_deg);
startBlockedByInflated = queryAzElTimeObstacle(inflatedField, ...
    startPoint_deg(1), startPoint_deg(2), 0, baseQueryOptions);
startBlockedByReference = queryAzElTimeObstacle(originalField, ...
    startPoint_deg(1), startPoint_deg(2), 0, referenceQueryOptions);
goalBlockedByInflated = queryAzElTimeObstacle(inflatedField, ...
    goalPoint_deg(1), goalPoint_deg(2), missionEndTime_s, ...
    baseQueryOptions);
goalBlockedByReference = queryAzElTimeObstacle(originalField, ...
    goalPoint_deg(1), goalPoint_deg(2), missionEndTime_s, ...
    referenceQueryOptions);

falsePositiveBounds_deg = maskBounds(falsePositiveMask, ...
    azimuthMesh_deg, elevationMesh_deg);
falseNegativeBounds_deg = maskBounds(falseNegativeMask, ...
    azimuthMesh_deg, elevationMesh_deg);
representativeFalsePositive_deg = [NaN NaN];
falsePositiveCrossingIndex = zeros(0, 1);
falsePositiveCrossingAzimuth_deg = zeros(0, 1);
if any(falsePositiveMask, "all")
    falsePositiveAzimuth_deg = azimuthMesh_deg(falsePositiveMask);
    falsePositiveElevation_deg = elevationMesh_deg(falsePositiveMask);
    falsePositiveCenter_deg = [ ...
        mean(falsePositiveAzimuth_deg), mean(falsePositiveElevation_deg)];
    distanceToCenter_deg2 = (falsePositiveAzimuth_deg - ...
        falsePositiveCenter_deg(1)).^2 + ...
        (falsePositiveElevation_deg - falsePositiveCenter_deg(2)).^2;
    [~, representativeIndex] = min(distanceToCenter_deg2);
    representativeFalsePositive_deg = [ ...
        falsePositiveAzimuth_deg(representativeIndex), ...
        falsePositiveElevation_deg(representativeIndex)];
    [falsePositiveCrossingIndex, falsePositiveCrossingAzimuth_deg] = ...
        horizontalRayCrossings( ...
        packedEdges_deg, representativeFalsePositive_deg);
end

%% Section 4: Print A Copy/Paste Diagnostic Report
fprintf('\n============================================================\n');
fprintf('U-SHAPE INFLATION DIAGNOSTIC\n');
fprintf('Safety margin: %.9g deg\n', safetyMargin_deg);
fprintf('Grid: %d x %d at %.3f deg\n', ...
    numel(azimuthGrid_deg), numel(elevationGrid_deg), gridStep_deg);
fprintf('Original vertices: %d\n', size(uBoundary_deg, 1));
fprintf('Inflated finite vertices: %d\n', size(inflatedBoundary_deg, 1));
fprintf('Packed finite vertices: %d\n', size(packedBoundary_deg, 1));
fprintf('Packed edges: %d\n', size(packedEdges_deg, 1));
fprintf('Self-intersection pairs: %d\n', ...
    size(selfIntersectionPairs, 1));
fprintf('Reference blocked cells: %d\n', nnz(referenceBlocked));
fprintf('Pre-inflated blocked cells: %d\n', nnz(inflatedBlocked));
fprintf('False-positive cells: %d\n', nnz(falsePositiveMask));
fprintf('False-negative cells: %d\n', nnz(falseNegativeMask));
fprintf('Default-cap/full-field disagreement cells: %d\n', ...
    nnz(vertexCapMismatchMask));
fprintf('Start [0 0]: inflated=%d, reference=%d, ray crossings=%d\n', ...
    startBlockedByInflated, startBlockedByReference, ...
    numel(startCrossingIndex));
fprintf('Goal [0 -10]: inflated=%d, reference=%d\n', ...
    goalBlockedByInflated, goalBlockedByReference);
fprintf('False-positive bounds [minAz maxAz minEl maxEl]: ');
fprintf('%.9g ', falsePositiveBounds_deg);
fprintf('\nFalse-negative bounds [minAz maxAz minEl maxEl]: ');
fprintf('%.9g ', falseNegativeBounds_deg);
fprintf('\nRepresentative false positive [az el]: %.9g %.9g\n', ...
    representativeFalsePositive_deg);

fprintf('\nSTART HORIZONTAL-RAY CROSSINGS\n');
fprintf(' edgeIndex  crossingAz_deg\n');
for crossingIndex = 1:numel(startCrossingIndex)
    fprintf(' %9d  %14.9g\n', startCrossingIndex(crossingIndex), ...
        startCrossingAzimuth_deg(crossingIndex));
end
fprintf('\nFALSE-POSITIVE HORIZONTAL-RAY CROSSINGS\n');
fprintf(' edgeIndex  crossingAz_deg\n');
for crossingIndex = 1:numel(falsePositiveCrossingIndex)
    fprintf(' %9d  %14.9g\n', ...
        falsePositiveCrossingIndex(crossingIndex), ...
        falsePositiveCrossingAzimuth_deg(crossingIndex));
end

fprintf('\nLONGEST PACKED EDGES\n');
fprintf(' edgeIndex  length_deg      startAz      startEl        endAz        endEl\n');
for rankIndex = 1:longestEdgeCount
    edgeIndex = longestEdgeIndex(rankIndex);
    fprintf(' %9d  %10.6f  %11.6f  %11.6f  %11.6f  %11.6f\n', ...
        edgeIndex, sortedEdgeLength_deg(rankIndex), ...
        packedEdges_deg(edgeIndex, 1), packedEdges_deg(edgeIndex, 2), ...
        packedEdges_deg(edgeIndex, 3), packedEdges_deg(edgeIndex, 4));
end

fprintf('\nINFLATED VERTICES IN SERIALIZED ORDER\n');
fprintf(' vertexIndex       azimuth_deg     elevation_deg\n');
for vertexIndex = 1:size(inflatedBoundary_deg, 1)
    fprintf(' %11d  %16.10f  %16.10f\n', vertexIndex, ...
        inflatedBoundary_deg(vertexIndex, 1), ...
        inflatedBoundary_deg(vertexIndex, 2));
end
if ~isempty(selfIntersectionPairs)
    fprintf('\nSELF-INTERSECTING EDGE PAIRS\n');
    fprintf(' edgeOne  edgeTwo\n');
    fprintf(' %7d  %7d\n', selfIntersectionPairs.');
end
fprintf('============================================================\n\n');

%% Section 5: Plot Reference, Pre-Inflated & Disagreement Masks
figureHandle = figure( ...
    "Name", "U-shape inflation diagnostic", ...
    "Color", "w", "Visible", "on");
layout = tiledlayout(figureHandle, 1, 3, ...
    "TileSpacing", "compact", "Padding", "compact");
referenceAxes = nexttile(layout);
drawOccupancy(referenceAxes, azimuthGrid_deg, elevationGrid_deg, ...
    referenceBlocked, uBoundary_deg, inflatedBoundary_deg, ...
    "Reference: original query + margin");
inflatedAxes = nexttile(layout);
drawOccupancy(inflatedAxes, azimuthGrid_deg, elevationGrid_deg, ...
    inflatedBlocked, uBoundary_deg, inflatedBoundary_deg, ...
    "Pre-inflated polygon query");
mismatchAxes = nexttile(layout);
mismatchCode = double(falsePositiveMask) + ...
    2 * double(falseNegativeMask);
imagesc(mismatchAxes, azimuthGrid_deg, elevationGrid_deg, mismatchCode);
set(mismatchAxes, "YDir", "normal");
hold(mismatchAxes, "on");
plotClosedBoundary(mismatchAxes, uBoundary_deg, "k-", 1.5);
plotClosedBoundary(mismatchAxes, inflatedBoundary_deg, "r:", 2.0);
scatter(mismatchAxes, startPoint_deg(1), startPoint_deg(2), ...
    70, "b", "filled");
scatter(mismatchAxes, goalPoint_deg(1), goalPoint_deg(2), ...
    90, [0.95 0.65 0], "p", "filled");
if all(isfinite(representativeFalsePositive_deg))
    scatter(mismatchAxes, representativeFalsePositive_deg(1), ...
        representativeFalsePositive_deg(2), 80, "m", "x", ...
        "LineWidth", 2);
end
colormap(mismatchAxes, [0.88 0.88 0.88; 0.90 0.25 0.85; ...
    0.20 0.65 0.95; 0.20 0.20 0.20]);
clim(mismatchAxes, [-0.5 3.5]);
colorbar(mismatchAxes, "Ticks", [0 1 2], ...
    "TickLabels", ["Agree" "False positive" "False negative"]);
title(mismatchAxes, sprintf( ...
    "Mismatch: FP=%d, FN=%d", ...
    nnz(falsePositiveMask), nnz(falseNegativeMask)));
formatAxes(mismatchAxes);
title(layout, sprintf( ...
    "U-shape safety-margin diagnosis | margin = %.3f deg", ...
    safetyMargin_deg));
drawnow;

diagnostic = struct( ...
    "SafetyMargin_deg", safetyMargin_deg, ...
    "AzElData", azElData, ...
    "InflatedAzElData", inflatedAzElData, ...
    "OriginalField", originalField, ...
    "InflatedField", inflatedField, ...
    "InflatedFieldDefaultCap", inflatedFieldDefaultCap, ...
    "AzimuthGrid_deg", azimuthGrid_deg, ...
    "ElevationGrid_deg", elevationGrid_deg, ...
    "ReferenceBlocked", referenceBlocked, ...
    "InflatedBlocked", inflatedBlocked, ...
    "FalsePositiveMask", falsePositiveMask, ...
    "FalseNegativeMask", falseNegativeMask, ...
    "VertexCapMismatchMask", vertexCapMismatchMask, ...
    "FalsePositiveBounds_deg", falsePositiveBounds_deg, ...
    "FalseNegativeBounds_deg", falseNegativeBounds_deg, ...
    "RepresentativeFalsePositive_deg", ...
    representativeFalsePositive_deg, ...
    "InflatedBoundary_deg", inflatedBoundary_deg, ...
    "PackedBoundary_deg", packedBoundary_deg, ...
    "PackedEdges_deg", packedEdges_deg, ...
    "EdgeLength_deg", edgeLength_deg, ...
    "SelfIntersectionPairs", selfIntersectionPairs, ...
    "StartCrossingEdgeIndex", startCrossingIndex, ...
    "StartCrossingAzimuth_deg", startCrossingAzimuth_deg, ...
    "StartBlockedByInflated", logical(startBlockedByInflated), ...
    "StartBlockedByReference", logical(startBlockedByReference), ...
    "GoalBlockedByInflated", logical(goalBlockedByInflated), ...
    "GoalBlockedByReference", logical(goalBlockedByReference), ...
    "Figure", figureHandle, ...
    "ReferenceAxes", referenceAxes, ...
    "InflatedAxes", inflatedAxes, ...
    "MismatchAxes", mismatchAxes);
end

function bounds_deg = maskBounds(mask, azimuthMesh_deg, elevationMesh_deg)
if ~any(mask, "all")
    bounds_deg = [NaN NaN NaN NaN];
    return;
end
azimuth_deg = azimuthMesh_deg(mask);
elevation_deg = elevationMesh_deg(mask);
bounds_deg = [min(azimuth_deg), max(azimuth_deg), ...
    min(elevation_deg), max(elevation_deg)];
end

function pairs = findProperSelfIntersections(edges_deg)
edgeCount = size(edges_deg, 1);
pairs = zeros(0, 2);
for firstEdgeIndex = 1:edgeCount
    firstStart = edges_deg(firstEdgeIndex, 1:2);
    firstEnd = edges_deg(firstEdgeIndex, 3:4);
    for secondEdgeIndex = firstEdgeIndex + 1:edgeCount
        edgesAreAdjacent = secondEdgeIndex == firstEdgeIndex + 1 || ...
            (firstEdgeIndex == 1 && secondEdgeIndex == edgeCount);
        if edgesAreAdjacent
            continue;
        end
        secondStart = edges_deg(secondEdgeIndex, 1:2);
        secondEnd = edges_deg(secondEdgeIndex, 3:4);
        firstSide = [cross2(firstStart, firstEnd, secondStart), ...
            cross2(firstStart, firstEnd, secondEnd)];
        secondSide = [cross2(secondStart, secondEnd, firstStart), ...
            cross2(secondStart, secondEnd, firstEnd)];
        properlyIntersects = prod(signWithTolerance(firstSide)) < 0 && ...
            prod(signWithTolerance(secondSide)) < 0;
        if properlyIntersects
            pairs(end + 1, :) = [ ...
                firstEdgeIndex secondEdgeIndex]; %#ok<AGROW>
        end
    end
end
end

function value = cross2(firstPoint, secondPoint, queryPoint)
value = (secondPoint(1) - firstPoint(1)) * ...
    (queryPoint(2) - firstPoint(2)) - ...
    (secondPoint(2) - firstPoint(2)) * ...
    (queryPoint(1) - firstPoint(1));
end

function result = signWithTolerance(value)
result = zeros(size(value));
result(value > 1e-10) = 1;
result(value < -1e-10) = -1;
end

function [edgeIndex, crossingAzimuth_deg] = ...
        horizontalRayCrossings(edges_deg, queryPoint_deg)
startAbove = edges_deg(:, 2) > queryPoint_deg(2);
endAbove = edges_deg(:, 4) > queryPoint_deg(2);
straddles = startAbove ~= endAbove;
candidateIndex = find(straddles);
candidateCrossingAzimuth_deg = edges_deg(candidateIndex, 1) + ...
    (queryPoint_deg(2) - edges_deg(candidateIndex, 2)) .* ...
    (edges_deg(candidateIndex, 3) - edges_deg(candidateIndex, 1)) ./ ...
    (edges_deg(candidateIndex, 4) - edges_deg(candidateIndex, 2));
isRightOfPoint = candidateCrossingAzimuth_deg > queryPoint_deg(1);
edgeIndex = candidateIndex(isRightOfPoint);
crossingAzimuth_deg = candidateCrossingAzimuth_deg(isRightOfPoint);
end

function drawOccupancy(axesHandle, azimuthGrid_deg, elevationGrid_deg, ...
        blocked, originalBoundary_deg, inflatedBoundary_deg, titleText)
imagesc(axesHandle, azimuthGrid_deg, elevationGrid_deg, double(blocked));
set(axesHandle, "YDir", "normal");
hold(axesHandle, "on");
plotClosedBoundary(axesHandle, originalBoundary_deg, "k-", 1.5);
plotClosedBoundary(axesHandle, inflatedBoundary_deg, "r:", 2.0);
scatter(axesHandle, 0, 0, 70, "b", "filled");
scatter(axesHandle, 0, -10, 90, [0.95 0.65 0], "p", "filled");
colormap(axesHandle, [0.82 0.94 0.84; 1.00 0.72 0.72]);
clim(axesHandle, [-0.5 1.5]);
colorbar(axesHandle, "Ticks", [0 1], ...
    "TickLabels", ["Free" "Blocked"]);
title(axesHandle, titleText);
formatAxes(axesHandle);
end

function plotClosedBoundary(axesHandle, boundary_deg, lineStyle, lineWidth)
if isempty(boundary_deg)
    return;
end
plot(axesHandle, [boundary_deg(:, 1); boundary_deg(1, 1)], ...
    [boundary_deg(:, 2); boundary_deg(1, 2)], lineStyle, ...
    "LineWidth", lineWidth);
end

function formatAxes(axesHandle)
xlabel(axesHandle, "Azimuth (deg)");
ylabel(axesHandle, "Elevation (deg)");
axis(axesHandle, "equal");
xlim(axesHandle, [-11 11]);
ylim(axesHandle, [-12 9]);
grid(axesHandle, "on");
box(axesHandle, "on");
end
