function result = exampleAlternatingTwoSlotGatesAzElTimeSpace( ...
        numberOfArrangements, options)
%% Section 0: Header & Readme
% SYNTAX
%   result = exampleAlternatingTwoSlotGatesAzElTimeSpace()
%   result = exampleAlternatingTwoSlotGatesAzElTimeSpace( ...
%       numberOfArrangements)
%   result = exampleAlternatingTwoSlotGatesAzElTimeSpace(options)
%   result = exampleAlternatingTwoSlotGatesAzElTimeSpace( ...
%       numberOfArrangements, options)
%**************************************************************************
% PURPOSE
%   - Construct 1 to 5 two-slot gates with continuously moving blockers.
%   - Offset the blocker cycles by gate index and let the maintained
%     planner choose the complete route without supplied waypoints.
%   - Leave the standard time-space, animation, and kinematic figures open
%     on success or diagnostic figures open on failure.
%**************************************************************************
% INPUTS
%   - numberOfArrangements (integer scalar from 1 through 5, optional;
%       default 3)
%   - options (scalar struct, optional)
%       Planner option overrides.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Planner result augmented with gate geometry, blocker histories,
%       and scenario-specific validation diagnostics.
%**************************************************************************
% UNITS
%   - Angles are degrees, time is seconds, velocity is deg/s,
%     acceleration is deg/s^2, and jerk is deg/s^3.

if nargin < 1 || isempty(numberOfArrangements)
    numberOfArrangements = 3;
    options = struct();
elseif isstruct(numberOfArrangements)
    options = numberOfArrangements;
    numberOfArrangements = 3;
elseif nargin < 2 || isempty(options)
    options = struct();
end
validateattributes(numberOfArrangements, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 1, '<=', 5});
stageCount = double(numberOfArrangements);
if ~isstruct(options) || ~isscalar(options)
    error("exampleAlternatingTwoSlotGatesAzElTimeSpace:InvalidOptions", ...
        "options must be a scalar struct.");
end
options = exampleOptions(options, struct( ...
    "MotionType", "velocityCarrying", ...
    "GoalTimeMode", "fixedArrival", ...
    "SampleTime_s", 0.05, ...
    "TurnRadius_deg", 5.0, ...
    "AllowAzimuthWrapping", false, ...
    "AzimuthInterval_deg", [-180 180], ...
    "FigureVisible", "on", ...
    "ShowAnimation", true, ...
    "ShowKinematicPlot", true, ...
    "AnimationFrameStride", 5, ...
    "AnimationPause_s", 0.002, ...
    "ShowSweptSurfaces", true, ...
    "MaximumDisplayedSlicesPerObstacle", 3, ...
    "VisibilitySampleStep_deg", 0.10, ...
    "CornerAngleThreshold_deg", 60, ...
    "Verbose", true, ...
    "Title", sprintf( ...
    "Alternating two-slot gates (%d stages)", stageCount)));

%% Section 1: Define The Gate And Blocker Geometry
safetyMargin_deg = 0.12;
gateSpacing_deg = 7;
stageAzimuth_deg = gateSpacing_deg * (1:stageCount).';
startPosition_deg = [0 0];
goalPosition_deg = [gateSpacing_deg * (stageCount + 1), 0];
corridorHalfHeight_deg = 5;
corridorWallThickness_deg = 1.5;
stageHalfWidth_deg = 0.65;
middleBarHalfHeight_deg = 0.35;
slotCenterElevation_deg = [-2.5 2.5];
% With the canonical 0.12-degree margin this overlaps both rails that bound
% the selected slot, so there is no residual passage around a "closed"
% blocker at either dwell position.
blockerHalfHeight_deg = 2.30;

% One acceleration-limited cycle dwells in the lower slot, moves to the
% upper slot with symmetric acceleration/deceleration, dwells there, then
% returns in the same way. The obstacle data contains one complete cycle;
% the requested arrival is at the end of the opposite-slot dwell.
blockerDwellTime_s = 64.0;
blockerMoveTime_s = 4.0;
blockerTravel_deg = diff(slotCenterElevation_deg);
blockerAccelerationLimit_deg_s2 = ...
    4 * blockerTravel_deg / blockerMoveTime_s^2;
blockerCycleTime_s = 2 * (blockerDwellTime_s + blockerMoveTime_s);
% The goal time is the end of the second dwell. Fixed-arrival retiming then
% holds at the start while the blockers exchange slots and performs the
% complete traverse during the stable second arrangement. The obstacle
% record continues through the return move so the full cycle is visible.
missionEndTime_s = 2 * blockerDwellTime_s + blockerMoveTime_s;
obstacleEndTime_s = blockerCycleTime_s;
blockerSampleTime_s = (0:0.25:obstacleEndTime_s).';
% A half-cycle offset puts adjacent stages in opposite slots and preserves
% that alternating arrangement throughout each dwell interval.
blockerPhaseStep_s = blockerDwellTime_s + blockerMoveTime_s;

% The two long horizontal corridor rails prevent a route from escaping
% above or below the gates. One short horizontal separator at every stage
% divides that bounded corridor into a lower and upper slot.
% All static rectangles share one canonical NaN-separated obstacle record.
corridorAzimuthBounds_deg = [-3, goalPosition_deg(1) + 3];
staticTime_s = [0; obstacleEndTime_s];
staticBoundary_deg = zeros(0, 2);
staticBoundary_deg = appendBoundaryRing(staticBoundary_deg, ...
    rectangleBoundary(corridorAzimuthBounds_deg, ...
    [-corridorHalfHeight_deg - corridorWallThickness_deg, ...
    -corridorHalfHeight_deg]));
staticBoundary_deg = appendBoundaryRing(staticBoundary_deg, ...
    rectangleBoundary(corridorAzimuthBounds_deg, ...
    [corridorHalfHeight_deg, ...
    corridorHalfHeight_deg + corridorWallThickness_deg]));
blockerProfiles = repmat(struct( ...
    "StageIndex", 0, ...
    "PhaseOffset_s", 0, ...
    "time_s", zeros(0, 1), ...
    "centerElevation_deg", zeros(0, 1), ...
    "velocity_deg_s", zeros(0, 1), ...
    "acceleration_deg_s2", zeros(0, 1)), stageCount, 1);
stageStaticBoundaries_deg = cell(stageCount, 1);
movingBoundary_deg = repmat( ...
    {zeros(0, 2)}, numel(blockerSampleTime_s), 1);
for stageIndex = 1:stageCount
    centerAzimuth_deg = stageAzimuth_deg(stageIndex);
    azimuthBounds_deg = centerAzimuth_deg + ...
        [-stageHalfWidth_deg, stageHalfWidth_deg];
    boundary_deg = rectangleBoundary(azimuthBounds_deg, ...
        [-middleBarHalfHeight_deg, middleBarHalfHeight_deg]);
    stageStaticBoundaries_deg{stageIndex} = boundary_deg;
    staticBoundary_deg = appendBoundaryRing( ...
        staticBoundary_deg, boundary_deg);

    phaseOffset_s = mod( ...
        (stageIndex - 1) * blockerPhaseStep_s, blockerCycleTime_s);
    [centerElevation_deg, blockerVelocity_deg_s, ...
        blockerAcceleration_deg_s2] = blockerMotionProfile( ...
        blockerSampleTime_s + phaseOffset_s, ...
        slotCenterElevation_deg, blockerDwellTime_s, ...
        blockerMoveTime_s);
    for sampleIndex = 1:numel(blockerSampleTime_s)
        boundary_deg = rectangleBoundary(azimuthBounds_deg, ...
            centerElevation_deg(sampleIndex) + ...
            blockerHalfHeight_deg * [-1 1]);
        movingBoundary_deg{sampleIndex} = appendBoundaryRing( ...
            movingBoundary_deg{sampleIndex}, boundary_deg);
    end
    blockerProfiles(stageIndex) = struct( ...
        "StageIndex", stageIndex, ...
        "PhaseOffset_s", phaseOffset_s, ...
        "time_s", blockerSampleTime_s, ...
        "centerElevation_deg", centerElevation_deg, ...
        "velocity_deg_s", blockerVelocity_deg_s, ...
        "acceleration_deg_s2", blockerAcceleration_deg_s2);
end
blockerAzimuth_deg = cellfun( ...
    @(boundary) boundary(:, 1), movingBoundary_deg, ...
    "UniformOutput", false);
blockerElevation_deg = cellfun( ...
    @(boundary) boundary(:, 2), movingBoundary_deg, ...
    "UniformOutput", false);
staticObstacle = makeAzElObstacleData( ...
    "Static two-slot gate bars", staticTime_s, ...
    staticBoundary_deg(:, 1), staticBoundary_deg(:, 2), ...
    safetyMargin_deg);
movingObstacle = makeAzElObstacleData( ...
    "Acceleration-limited moving gate blockers", ...
    blockerSampleTime_s, blockerAzimuth_deg, ...
    blockerElevation_deg, safetyMargin_deg);
obstacles = {staticObstacle; movingObstacle};

%% Section 2: Define And Run One Unified Planning Request
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", startPosition_deg, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", missionEndTime_s, ...
    "position_deg", goalPosition_deg, ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [0.75 0.75], ...
    "maxJerk_deg_s3", [2.5 2.5]);

% This is deliberately the only planner call. No gate side, waypoint,
% directed route, or preferred passage is supplied by the example.
result = planAzElMotion( ...
    obstacles, initialState, goalState, limits, options);

%% Section 3: Publish Scenario Geometry And Diagnostics
profileDiagnostics = validateBlockerProfiles( ...
    blockerProfiles, slotCenterElevation_deg, ...
    blockerDwellTime_s, blockerMoveTime_s, ...
    blockerAccelerationLimit_deg_s2);
slotDiagnostics = validateGateSlotClosure( ...
    result.obstacleField, stageAzimuth_deg, blockerProfiles, ...
    slotCenterElevation_deg, corridorHalfHeight_deg, ...
    middleBarHalfHeight_deg, safetyMargin_deg, blockerPhaseStep_s);
constraintDiagnostics = result.timedSlopePath.ConstraintDiagnostics;
finiteJerkNumericallyVerified = isfield( ...
    constraintDiagnostics, "FiniteJerkNumericallyVerified") && ...
    constraintDiagnostics.FiniteJerkNumericallyVerified;
scenarioValidation = struct( ...
    "RequestedStageCountValid", ...
    stageCount >= 1 && stageCount <= 5, ...
    "ObstacleCountCorrect", ...
    result.obstacleField.ObstacleCount == 2, ...
    "SafetyMarginOwnedByCanonicalData", all(abs( ...
    result.obstacleSafetyMargins_deg - safetyMargin_deg) <= 1e-12), ...
    "DirectRouteBlocked", any(result.directBlocked), ...
    "BlockerPositionContinuous", ...
    profileDiagnostics.PositionContinuous, ...
    "BlockerVelocityContinuous", ...
    profileDiagnostics.VelocityContinuous, ...
    "BlockerAccelerationLimited", ...
    profileDiagnostics.AccelerationLimited, ...
    "BlockersAccelerateAndDecelerate", ...
    profileDiagnostics.HasAccelerationAndDeceleration, ...
    "NeighboringSlotsAlternateInitially", ...
    profileDiagnostics.NeighboringSlotsAlternateInitially, ...
    "HalfCyclePhaseOffsetsCorrect", ...
    profileDiagnostics.HalfCyclePhaseOffsetsCorrect, ...
    "SelectedSlotFullyClosed", ...
    slotDiagnostics.SelectedSlotFullyClosed, ...
    "OppositeSlotRemainsOpen", ...
    slotDiagnostics.OppositeSlotRemainsOpen, ...
    "PlannerPassed", result.Success && result.Validation.Passed, ...
    "ProtectedGeometryClear", ...
    result.Validation.ProtectedGeometryClear, ...
    "KinematicLimitsPassed", ...
    result.Validation.VelocityWithinLimits && ...
    result.Validation.AccelerationWithinLimits && ...
    result.Validation.JerkWithinLimits, ...
    "JerkConstraintNumericallyVerified", ...
    finiteJerkNumericallyVerified);
scenarioValidation.Passed = all(cell2mat( ...
    struct2cell(scenarioValidation)));
scenarioDiagnostics = struct( ...
    "ArrangementCount", stageCount, ...
    "StageCount", stageCount, ...
    "Success", result.Success && scenarioValidation.Passed, ...
    "Message", string(result.Message), ...
    "ArrivalTime_s", result.goalLineInterceptTime_s, ...
    "PathLength_deg", sum(vecnorm(diff( ...
    result.bestAttemptPosition_deg, 1, 1), 2, 2)), ...
    "CollisionFree", result.Validation.ProtectedGeometryClear, ...
    "PeakVelocity_deg_s", ...
    constraintDiagnostics.PeakVelocity_deg_s, ...
    "PeakAcceleration_deg_s2", ...
    constraintDiagnostics.PeakAcceleration_deg_s2, ...
    "PeakJerk_deg_s3", constraintDiagnostics.PeakJerk_deg_s3, ...
    "JerkSatisfied", constraintDiagnostics.JerkSatisfied, ...
    "FiniteJerkCertified", constraintDiagnostics.FiniteJerkCertified, ...
    "FiniteJerkNumericallyVerified", finiteJerkNumericallyVerified, ...
    "ContinuousJerkCertified", ...
    constraintDiagnostics.ContinuousJerkCertified);
if ~scenarioDiagnostics.Success
    scenarioDiagnostics.Message = ...
        scenarioDiagnostics.Message + " Scenario validation: " + ...
        string(scenarioValidation.Passed) + ".";
end

result.numberOfArrangements = stageCount;
result.stageCount = stageCount;
result.stageAzimuth_deg = stageAzimuth_deg;
result.slotCenterElevation_deg = slotCenterElevation_deg;
result.stageStaticBoundaries_deg = stageStaticBoundaries_deg;
result.blockerProfiles = blockerProfiles;
result.blockerCycleTime_s = blockerCycleTime_s;
result.blockerPhaseStep_s = blockerPhaseStep_s;
result.blockerAccelerationLimit_deg_s2 = ...
    blockerAccelerationLimit_deg_s2;
result.safetyMargin_deg = safetyMargin_deg;
result.ProfileDiagnostics = profileDiagnostics;
result.SlotDiagnostics = slotDiagnostics;
result.ScenarioValidation = scenarioValidation;
result.ScenarioDiagnostics = scenarioDiagnostics;

%% Section 4: Fail With The Maintained Diagnostic Figures Intact
if ~result.Success || ~result.Validation.Passed
    if nargout == 0
        error("exampleAlternatingTwoSlotGatesAzElTimeSpace:PlanningFailed", ...
            "Two-slot gate planning failed for %d stages. " + ...
            "Diagnostic plots show the environment and best attempt. %s", ...
            stageCount, result.Message);
    end
    return;
end
if ~scenarioValidation.Passed
    failedNames = string(fieldnames(scenarioValidation));
    failedValues = cell2mat(struct2cell(scenarioValidation));
    failedNames = failedNames(~failedValues);
    error("exampleAlternatingTwoSlotGatesAzElTimeSpace:" + ...
        "ScenarioValidationFailed", ...
        "Scenario checks failed: %s. Diagnostic plots remain open.", ...
        strjoin(failedNames, ", "));
end
end

function combinedBoundary_deg = appendBoundaryRing( ...
        combinedBoundary_deg, boundary_deg)
%% Section 0: Header & Readme
% Join independent solid rings with the canonical paired-NaN separator.
if isempty(combinedBoundary_deg)
    combinedBoundary_deg = boundary_deg;
else
    combinedBoundary_deg = [combinedBoundary_deg; ...
        NaN NaN; boundary_deg];
end
end

function boundary_deg = rectangleBoundary( ...
        azimuthBounds_deg, elevationBounds_deg)
%% Section 0: Header & Readme
boundary_deg = [ ...
    azimuthBounds_deg(1), elevationBounds_deg(1); ...
    azimuthBounds_deg(2), elevationBounds_deg(1); ...
    azimuthBounds_deg(2), elevationBounds_deg(2); ...
    azimuthBounds_deg(1), elevationBounds_deg(2)];
end

function [position_deg, velocity_deg_s, acceleration_deg_s2] = ...
        blockerMotionProfile(time_s, slotCenters_deg, dwellTime_s, ...
        moveTime_s)
%% Section 0: Header & Readme
% Evaluate one periodic dwell/bang-bang/dwell/bang-bang motion cycle.
time_s = double(time_s(:));
lowerPosition_deg = slotCenters_deg(1);
upperPosition_deg = slotCenters_deg(2);
travel_deg = upperPosition_deg - lowerPosition_deg;
accelerationMagnitude_deg_s2 = 4 * travel_deg / moveTime_s^2;
halfMoveTime_s = moveTime_s / 2;
cycleTime_s = 2 * (dwellTime_s + moveTime_s);
phaseTime_s = mod(time_s, cycleTime_s);
position_deg = zeros(size(time_s));
velocity_deg_s = zeros(size(time_s));
acceleration_deg_s2 = zeros(size(time_s));

lowerDwell = phaseTime_s < dwellTime_s;
upwardMove = phaseTime_s >= dwellTime_s & ...
    phaseTime_s < dwellTime_s + moveTime_s;
upperDwell = phaseTime_s >= dwellTime_s + moveTime_s & ...
    phaseTime_s < 2 * dwellTime_s + moveTime_s;
downwardMove = ~(lowerDwell | upwardMove | upperDwell);
position_deg(lowerDwell) = lowerPosition_deg;
position_deg(upperDwell) = upperPosition_deg;

upwardTime_s = phaseTime_s(upwardMove) - dwellTime_s;
upwardAcceleration = upwardTime_s <= halfMoveTime_s;
upwardPosition_deg = zeros(size(upwardTime_s));
upwardVelocity_deg_s = zeros(size(upwardTime_s));
upwardPosition_deg(upwardAcceleration) = lowerPosition_deg + ...
    0.5 * accelerationMagnitude_deg_s2 * ...
    upwardTime_s(upwardAcceleration).^2;
upwardVelocity_deg_s(upwardAcceleration) = ...
    accelerationMagnitude_deg_s2 * ...
    upwardTime_s(upwardAcceleration);
remainingTime_s = moveTime_s - upwardTime_s(~upwardAcceleration);
upwardPosition_deg(~upwardAcceleration) = upperPosition_deg - ...
    0.5 * accelerationMagnitude_deg_s2 * remainingTime_s.^2;
upwardVelocity_deg_s(~upwardAcceleration) = ...
    accelerationMagnitude_deg_s2 * remainingTime_s;
position_deg(upwardMove) = upwardPosition_deg;
velocity_deg_s(upwardMove) = upwardVelocity_deg_s;
upwardAcceleration_deg_s2 = ...
    accelerationMagnitude_deg_s2 * ones(size(upwardTime_s));
upwardAcceleration_deg_s2(~upwardAcceleration) = ...
    -accelerationMagnitude_deg_s2;
acceleration_deg_s2(upwardMove) = upwardAcceleration_deg_s2;

downwardTime_s = phaseTime_s(downwardMove) - ...
    (2 * dwellTime_s + moveTime_s);
downwardAcceleration = downwardTime_s <= halfMoveTime_s;
downwardPosition_deg = zeros(size(downwardTime_s));
downwardVelocity_deg_s = zeros(size(downwardTime_s));
downwardPosition_deg(downwardAcceleration) = upperPosition_deg - ...
    0.5 * accelerationMagnitude_deg_s2 * ...
    downwardTime_s(downwardAcceleration).^2;
downwardVelocity_deg_s(downwardAcceleration) = ...
    -accelerationMagnitude_deg_s2 * ...
    downwardTime_s(downwardAcceleration);
remainingTime_s = moveTime_s - ...
    downwardTime_s(~downwardAcceleration);
downwardPosition_deg(~downwardAcceleration) = lowerPosition_deg + ...
    0.5 * accelerationMagnitude_deg_s2 * remainingTime_s.^2;
downwardVelocity_deg_s(~downwardAcceleration) = ...
    -accelerationMagnitude_deg_s2 * remainingTime_s;
position_deg(downwardMove) = downwardPosition_deg;
velocity_deg_s(downwardMove) = downwardVelocity_deg_s;
downwardAcceleration_deg_s2 = ...
    -accelerationMagnitude_deg_s2 * ones(size(downwardTime_s));
downwardAcceleration_deg_s2(~downwardAcceleration) = ...
    accelerationMagnitude_deg_s2;
acceleration_deg_s2(downwardMove) = downwardAcceleration_deg_s2;
end

function diagnostics = validateBlockerProfiles( ...
        profiles, slotCenters_deg, dwellTime_s, moveTime_s, ...
        accelerationLimit_deg_s2)
%% Section 0: Header & Readme
% Check the analytic cycle on both sides of all motion-phase transitions.
cycleTime_s = 2 * (dwellTime_s + moveTime_s);
transitionTime_s = [0; dwellTime_s; ...
    dwellTime_s + moveTime_s; ...
    2 * dwellTime_s + moveTime_s; cycleTime_s];
epsilon_s = 1e-7;
[leftPosition_deg, leftVelocity_deg_s] = blockerMotionProfile( ...
    transitionTime_s - epsilon_s, slotCenters_deg, ...
    dwellTime_s, moveTime_s);
[rightPosition_deg, rightVelocity_deg_s] = blockerMotionProfile( ...
    transitionTime_s + epsilon_s, slotCenters_deg, ...
    dwellTime_s, moveTime_s);
maximumPositionJump_deg = max(abs( ...
    rightPosition_deg - leftPosition_deg));
maximumVelocityJump_deg_s = max(abs( ...
    rightVelocity_deg_s - leftVelocity_deg_s));
allAcceleration_deg_s2 = vertcat(profiles.acceleration_deg_s2);
accelerationTolerance_deg_s2 = 1e-10;
initialPosition_deg = arrayfun( ...
    @(profile) profile.centerElevation_deg(1), profiles).';
expectedInitialPosition_deg = slotCenters_deg( ...
    1 + mod((1:numel(profiles)).' - 1, 2));
phaseOffset_s = reshape([profiles.PhaseOffset_s], [], 1);
expectedPhaseOffset_s = mod((0:numel(profiles) - 1).' * ...
    (dwellTime_s + moveTime_s), cycleTime_s);
diagnostics = struct( ...
    "PositionContinuous", maximumPositionJump_deg <= 1e-6, ...
    "VelocityContinuous", maximumVelocityJump_deg_s <= 1e-6, ...
    "MaximumPositionJump_deg", maximumPositionJump_deg, ...
    "MaximumVelocityJump_deg_s", maximumVelocityJump_deg_s, ...
    "AccelerationLimited", max(abs(allAcceleration_deg_s2)) <= ...
    accelerationLimit_deg_s2 + accelerationTolerance_deg_s2, ...
    "MaximumAcceleration_deg_s2", ...
    max(abs(allAcceleration_deg_s2)), ...
    "HasAccelerationAndDeceleration", ...
    any(allAcceleration_deg_s2 > accelerationTolerance_deg_s2) && ...
    any(allAcceleration_deg_s2 < -accelerationTolerance_deg_s2), ...
    "InitialPosition_deg", initialPosition_deg, ...
    "NeighboringSlotsAlternateInitially", all(abs( ...
    initialPosition_deg - expectedInitialPosition_deg) <= 1e-12), ...
    "PhaseOffset_s", phaseOffset_s, ...
    "HalfCyclePhaseOffsetsCorrect", all(abs( ...
    phaseOffset_s - expectedPhaseOffset_s) <= 1e-12));
end

function diagnostics = validateGateSlotClosure( ...
        obstacleField, stageAzimuth_deg, profiles, slotCenters_deg, ...
        corridorHalfHeight_deg, middleBarHalfHeight_deg, ...
        safetyMargin_deg, halfCycleTime_s)
%% Section 0: Header & Readme
% Query protected geometry across every gate at both dwell arrangements.
% The selected slot must be completely occupied at the gate cross-section,
% while the opposite slot must retain a completely clear interior channel.
sampleSpacing_deg = 0.02;
edgeInset_deg = safetyMargin_deg + 0.04;
lowerSlotElevation_deg = ( ...
    -corridorHalfHeight_deg + edgeInset_deg:sampleSpacing_deg: ...
    -middleBarHalfHeight_deg - edgeInset_deg).';
upperSlotElevation_deg = ( ...
    middleBarHalfHeight_deg + edgeInset_deg:sampleSpacing_deg: ...
    corridorHalfHeight_deg - edgeInset_deg).';
arrangementTime_s = [0; halfCycleTime_s];
stageCount = numel(stageAzimuth_deg);
selectedSlotClosed = false(stageCount, numel(arrangementTime_s));
oppositeSlotOpen = false(stageCount, numel(arrangementTime_s));
blockedSlotIndex = zeros(stageCount, numel(arrangementTime_s));
for stageIndex = 1:stageCount
    for arrangementIndex = 1:numel(arrangementTime_s)
        queryTime_s = arrangementTime_s(arrangementIndex);
        % Use the stored profile sample at the exact dwell time. All sample
        % grids include 0 and halfCycleTime_s by construction.
        [~, profileIndex] = min(abs( ...
            profiles(stageIndex).time_s - queryTime_s));
        blockerCenter_deg = ...
            profiles(stageIndex).centerElevation_deg(profileIndex);
        [~, selectedSlot] = min(abs(slotCenters_deg - blockerCenter_deg));
        blockedSlotIndex(stageIndex, arrangementIndex) = selectedSlot;
        lowerOccupied = queryAzElTimeObstacle( ...
            obstacleField, repmat(stageAzimuth_deg(stageIndex), ...
            size(lowerSlotElevation_deg)), lowerSlotElevation_deg, ...
            queryTime_s);
        upperOccupied = queryAzElTimeObstacle( ...
            obstacleField, repmat(stageAzimuth_deg(stageIndex), ...
            size(upperSlotElevation_deg)), upperSlotElevation_deg, ...
            queryTime_s);
        slotOccupied = {lowerOccupied; upperOccupied};
        selectedSlotClosed(stageIndex, arrangementIndex) = ...
            all(slotOccupied{selectedSlot});
        openSlot = 3 - selectedSlot;
        oppositeSlotOpen(stageIndex, arrangementIndex) = ...
            all(~slotOccupied{openSlot});
    end
end
diagnostics = struct( ...
    "ArrangementTime_s", arrangementTime_s, ...
    "BlockedSlotIndex", blockedSlotIndex, ...
    "SelectedSlotClosedByStage", selectedSlotClosed, ...
    "OppositeSlotOpenByStage", oppositeSlotOpen, ...
    "SelectedSlotFullyClosed", all(selectedSlotClosed, "all"), ...
    "OppositeSlotRemainsOpen", all(oppositeSlotOpen, "all"), ...
    "CrossSectionSampleSpacing_deg", sampleSpacing_deg);
end

function options = exampleOptions(options, defaults)
%% Section 0: Header & Readme
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(options, names{index}) || isempty(options.(names{index}))
        options.(names{index}) = defaults.(names{index});
    end
end
end
