function result = exampleMovingDeformingUSOutlineVisibility(options)
%% Section 0: Header & Readme
% SYNTAX
%   result = exampleMovingDeformingUSOutlineVisibility()
%   result = exampleMovingDeformingUSOutlineVisibility(options)
%**************************************************************************
% PURPOSE
%   - Plan around a dense U.S. outline that starts at 8 percent scale,
%     grows, deforms, completes a 180-degree rotation, and disappears.
%   - Include a starburst sun that moves across the bottom of the scene.
%**************************************************************************
% INPUTS
%   - options (scalar struct, optional; default struct())
%       Planner/display overrides plus the finite MaxJerk_deg_s3 limit.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Unmodified public planner result.
%**************************************************************************
% UNITS
%   - Position is degrees, time is seconds, velocity is degrees per second,
%     acceleration is degrees per second squared, and jerk is degrees per
%     second cubed.
%**************************************************************************

%% Section 1: Resolve Example Controls

% Set display and planner options before loading the large outline. A finite
% jerk limit requires smooth physical motion.

if nargin < 1 || isempty(options)
    options = struct();
end
[options, jerkConfiguration] = resolveExampleOptions( ...
    options, struct( ...
    "GoalTimeMode", "earliestArrival", ...
    "MaximumDisplayedSlicesPerObstacle", 10, ...
    "MaximumSeedCount", 3, ...
    "ShowSweptSurfaces", true, ...
        "FigureVisible", "on", ...
        "Title", "Extreme growing/rotating U.S. with moving sun"), [12 12]);

%% Section 2: Create Obstacles

% Build two dynamic obstacles. The U.S. outline changes scale, shape, angle, and
% position. A star-shaped sun moves across the lower area.

missionEndTime_s = 5 * 60;
obstacleTimeStep_s = 5;
uSDisappearTime_s = 4 * 60;
uSTime_s = (0:obstacleTimeStep_s:uSDisappearTime_s).';
% The private helper loads and joins more than 14,000 outline vertices. Keeping
% this work in the helper makes the scenario sequence easier to read.
[uSObstacle, uSHistory] = createContiguousUSObstacle( ...
    uSTime_s, 0.10, struct( ...
    "MotionMode", "movingDeforming", "Verbose", options.Verbose));

sunTime_s = (0:obstacleTimeStep_s:missionEndTime_s).';
sunRayCount = 16;
sunAngle_rad = (0:2 * sunRayCount - 1).' * ...
    (pi / sunRayCount);
sunRadius_deg = repmat([2.6; 1.8], sunRayCount, 1);
sunSource_deg = sunRadius_deg .* ...
    [cos(sunAngle_rad), sin(sunAngle_rad)];
sunStartCenter_deg = [uSHistory.centroid_deg(1, 1) - 16, 12];
sunEndCenter_deg = [uSHistory.centroid_deg(1, 1) + 16, 12];
sunTransform = @(sourcePosition_deg, sampleTime_s, sampleIndex) ...
    moveSunSlice(sourcePosition_deg, sampleTime_s, sampleIndex, ...
    missionEndTime_s, sunStartCenter_deg, sunEndCenter_deg);
[sunObstacle, sunHistory] = obstacleAvoidance.obstacles.createMovingObstacle( ...
    "Moving sun", sunTime_s, sunSource_deg(:, 1), ...
    sunSource_deg(:, 2), sunTransform, 0.10, ...
    struct("Verbose", options.Verbose));
obstacles = obstacleAvoidance.obstacles.combineObstacles(uSObstacle, sunObstacle);

%% Section 3: Create Planner Inputs

% Put the start and goal across the moving shapes. This request tests visibility
% candidates while dense geometry deforms and disappears.

routeAzimuth_deg = uSHistory.centroid_deg(1, 1);
initialState = struct( ...
    "time_s", 0, "position_deg", [routeAzimuth_deg 18]);
goalState = struct( ...
    "time_s", missionEndTime_s, ...
    "position_deg", [routeAzimuth_deg 58]);
limits = struct( ...
    "maxVelocity_deg_s", [8 8], "maxAcceleration_deg_s2", [3 3], "maxJerk_deg_s3", jerkConfiguration.MaxJerk_deg_s3);

%% Section 4: Run Planner

% Run the public planner with both obstacle histories.

result = obstacleAvoidance.planTrajectory( ...
    obstacles, initialState, goalState, limits, options);

%% Section 5: Validate Result

% Check the full trajectory and the outline history. For a failure, inspect
% topology-change diagnostics and collision subdivisions.

exampleValidation = validateExampleResult( ...
    result, "extreme moving/deforming U.S. with moving sun", ...
    struct("RequireDirectBlocked", true));

initialUS_deg = [ ...
    uSHistory.azimuthBySlice_deg{1}, ...
    uSHistory.elevationBySlice_deg{1}];
finalUS_deg = [ ...
    uSHistory.azimuthBySlice_deg{end}, ...
    uSHistory.elevationBySlice_deg{end}];
initialCenteredUS_deg = initialUS_deg - mean(initialUS_deg, 1);
finalCenteredUS_deg = finalUS_deg - mean(finalUS_deg, 1);
rotationCosine = sum( ...
    initialCenteredUS_deg .* finalCenteredUS_deg, "all") / ...
    (norm(initialCenteredUS_deg, "fro") * ...
    norm(finalCenteredUS_deg, "fro"));
initialAreaFraction = uSHistory.area_deg2(1) / ...
    max(uSHistory.area_deg2);
[~, inactiveUSGeometry] = obstacleAvoidance.obstacles.shapeAtTime( ...
    uSObstacle, missionEndTime_s, true);
uSHistoryValidation = struct( ...
    "Passed", initialAreaFraction <= 0.01 && ...
        max(uSHistory.scaleFactor) >= 1.35 - 1e-12 && ...
        rotationCosine <= -0.999 && ~inactiveUSGeometry.Active, ...
    "InitialAreaFraction", initialAreaFraction, ...
    "MaximumScaleFactor", max(uSHistory.scaleFactor), ...
    "CompletedRotation_deg", uSHistory.rotation_deg(end), ...
    "EndpointRotationCosine", rotationCosine, ...
    "DisappearTime_s", uSDisappearTime_s, ...
    "InactiveAtMissionEnd", ~inactiveUSGeometry.Active);

sunCentroidTravel_deg = sum(vecnorm( ...
    diff(sunHistory.centroid_deg, 1, 1), 2, 2));
sunStayedAtBottom = max(sunHistory.bounds_deg(:, 4)) < ...
    initialState.position_deg(2);
sunMotionValidation = struct( ...
    "Passed", sunCentroidTravel_deg >= 32 && sunStayedAtBottom, ...
    "CentroidTravel_deg", sunCentroidTravel_deg, ...
    "StayedBelowInitialElevation", sunStayedAtBottom, ...
    "MaximumBoundaryElevation_deg", ...
        max(sunHistory.bounds_deg(:, 4)));
if ~uSHistoryValidation.Passed || ~sunMotionValidation.Passed
    exampleValidation.Passed = false;
    exampleValidation.Message = exampleValidation.Message + ...
        " Extreme obstacle-history validation failed.";
end
if ~exampleValidation.Passed
    warning("exampleMovingDeformingUSOutlineVisibility:ValidationFailed", ...
        "%s", exampleValidation.Message);
end

%% Section 6: Plot Diagnostics And Motion

% Plot and animate the returned result with the supplied obstacle histories.

if jerkConfiguration.PlotOutputs
    obstacleAvoidance.plotting.plotTrajectory( ...
        result, jerkConfiguration.PlotOptions);
end

end

%% Section 8: Local Functions

function transformed_deg = moveSunSlice( ...
        sourcePosition_deg, sampleTime_s, ~, missionEndTime_s, ...
        startCenter_deg, endCenter_deg)
% Move one sun outline smoothly across the lower part of the scene.
missionProgress = min(max(sampleTime_s / missionEndTime_s, 0), 1);
travelFraction = 10 * missionProgress^3 - ...
    15 * missionProgress^4 + 6 * missionProgress^5;
center_deg = startCenter_deg + ...
    travelFraction * (endCenter_deg - startCenter_deg);
center_deg(2) = center_deg(2) + 2 * sin(2 * pi * missionProgress);
transformed_deg = sourcePosition_deg + center_deg;
end
