function result = example03TimedWallWait(showFigure)
%% Section 0: Header & Readme
% SYNTAX
%   result = example03TimedWallWait()
%   result = example03TimedWallWait(showFigure)
%**************************************************************************
% PURPOSE
%   - Demonstrate an explicit feasible wait for a delayed-opening scene.
%**************************************************************************
% INPUTS
%   - showFigure (optional logical scalar, default false)
%       Affects display only and is never passed into planning.
%**************************************************************************
% OUTPUTS
%   - result (scalar planner result)
%**************************************************************************
% UNITS
%   - Angles are degrees and time is seconds.

if nargin < 1
    showFigure = false;
end

%% Section 1: Build Canonical Obstacle Data
wallAzimuth_deg = [-2; 2; 2; -2];
blockingElevation_deg = [-30; -30; 30; 30];
clearElevation_deg = [35; 35; 55; 55];
azElData = makeAzElObstacleData( ...
    "delayed opening", [0; 8; 8.2], ...
    {wallAzimuth_deg; wallAzimuth_deg; wallAzimuth_deg}, ...
    {blockingElevation_deg; blockingElevation_deg; clearElevation_deg});
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-20, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
goal = struct( ...
    "type", "fixed", ...
    "time_s", NaN, ...
    "position_deg", [20, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-60, 60], ...
    "elevation_deg", [-20, 20], ...
    "maxVelocity_deg_s", [12, 12], ...
    "maxAcceleration_deg_s2", [8, 8]);
missionOptions = struct( ...
    "safetyMargin_deg", 1, ...
    "deadline_s", 20);
request = struct( ...
    "obstacles", azElData, ...
    "initialState", initialState, ...
    "goal", goal, ...
    "limits", limits, ...
    "options", missionOptions);

%% Section 2: Plan & Independently Validate
result = planAzElAvoidance(request);
assert(result.success, result.message);
validation = validateAzElCommand( ...
    result.command, request, result.arrivalTime_s);
assert(validation.isValid, validation.message);
assert(validation.totalWaitDuration_s > 0, ...
    "This mission requires an explicit stationary wait.");

%% Section 3: Report & Optionally Display
fprintf("Timed-wall arrival: %.6f s; wait: %.6f s\n", ...
    result.arrivalTime_s, validation.totalWaitDuration_s);
if showFigure
    visualizeAzElPlan(request, result);
end
end
