function result = exampleTargetExitsObstacle(exampleOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   result = exampleTargetExitsObstacle()
%   result = exampleTargetExitsObstacle(exampleOverrides)
%**************************************************************************
% PURPOSE
%   - Intercept a sampled target that begins inside an obstacle and later
%     moves into free space.
%   - Route around a separate circular obstacle between the initial state
%     and the target's containing obstacle.
%**************************************************************************
% INPUTS
%   - exampleOverrides (scalar struct, optional; default struct())
%       Planner overrides plus the shared FigureVisible, PlotOutputs,
%       ShowAnimation, ShowKinematicPlot, and MaxJerk_deg_s3 controls.
%       RandomSeed selects the deterministic
%       post-wait target path (default 17).
%**************************************************************************
% OUTPUTS
%   - result (scalar planner-result struct)
%       Validated specified-time intercept, target-occupancy history,
%       scenario inputs, and optional plot handles.
%**************************************************************************
% UNITS
%   - Position is degrees; time is seconds; derivatives use deg/s,
%     deg/s^2, and deg/s^3.
%**************************************************************************

%% Section 1: Resolve Example Controls

if nargin < 1 || isempty(exampleOverrides)
    exampleOverrides = struct();
end

randomSeed = 17;
if isfield(exampleOverrides, "RandomSeed") && ...
        ~isempty(exampleOverrides.RandomSeed)
    randomSeed = exampleOverrides.RandomSeed;
end
validateattributes(randomSeed, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'nonnegative'});
plannerOverrides = exampleOverrides;
if isfield(plannerOverrides, "RandomSeed")
    plannerOverrides = rmfield(plannerOverrides, "RandomSeed");
end

[options, jerkConfiguration] = resolveAzElExampleOptions( ...
    plannerOverrides, struct( ...
        "GoalTimeMode", "fixedArrival", ...
        "SampleTime_s", 0.05, ...
        "AllowAzimuthWrapping", false, ...
        "FigureVisible", "on", ...
        "Title", "Target exits a containing obstacle"), ...
    [2.5 2.5]);

options.AllowAzimuthWrapping = false;

%% Section 2: Create Obstacles

missionEndTime_s = 24;
obstacleTime_s = [0; missionEndTime_s];
circleVertexCount = 72;
circleAngle_rad = (0:circleVertexCount - 1).' * ...
    (2 * pi / circleVertexCount);
unitCircle = [cos(circleAngle_rad), sin(circleAngle_rad)];
safetyMargin_deg = 0.15;

transitCircleCenter_deg = [0 0];
transitCircleRadius_deg = 2.0;
transitCirclePosition_deg = transitCircleCenter_deg + ...
    transitCircleRadius_deg * unitCircle;
transitCircle = makeAzElObstacleData( ...
    "Transit circle", obstacleTime_s, ...
    {transitCirclePosition_deg(:, 1); ...
        transitCirclePosition_deg(:, 1)}, ...
    {transitCirclePosition_deg(:, 2); ...
        transitCirclePosition_deg(:, 2)}, ...
    safetyMargin_deg);

containingCircleCenter_deg = [8 0];
containingCircleRadius_deg = 2.0;
containingCirclePosition_deg = containingCircleCenter_deg + ...
    containingCircleRadius_deg * unitCircle;
containingCircle = makeAzElObstacleData( ...
    "Target containment circle", obstacleTime_s, ...
    {containingCirclePosition_deg(:, 1); ...
        containingCirclePosition_deg(:, 1)}, ...
    {containingCirclePosition_deg(:, 2); ...
        containingCirclePosition_deg(:, 2)}, ...
    safetyMargin_deg);

obstacles = combineAzElObstacles(transitCircle, containingCircle);

%% Section 3: Create Planner Inputs

initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-8 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);

targetTime_s = (0:4:missionEndTime_s).';
targetWaitSampleCount = 3;
postWaitSampleCount = numel(targetTime_s) - targetWaitSampleCount;
previousRandomState = rng;
restoreRandomState = onCleanup(@() rng(previousRandomState));
rng(randomSeed, "twister");

% The target waits at the containing circle's center, then takes seeded
% outward steps with randomized progress and elevation. Positive azimuth
% progress guarantees that every seed eventually leaves the obstacle while
% retaining a different reproducible path.
postWaitAzimuthStep_deg = 0.85 + 0.35 * ...
    rand(postWaitSampleCount, 1);
postWaitElevationStep_deg = 0.20 + 0.20 * ...
    rand(postWaitSampleCount, 1);
postWaitStep_deg = [postWaitAzimuthStep_deg, ...
    postWaitElevationStep_deg];
postWaitPosition_deg = containingCircleCenter_deg + ...
    cumsum(postWaitStep_deg, 1);
targetPosition_deg = [ ...
    repmat(containingCircleCenter_deg, targetWaitSampleCount, 1); ...
    postWaitPosition_deg];
targetMotion = struct( ...
    "time_s", targetTime_s, ...
    "position_deg", targetPosition_deg, ...
    "InterpolationMethod", "linear");

limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [0.8 0.8], ...
    "maxJerk_deg_s3", jerkConfiguration.MaxJerk_deg_s3);
interceptOptions = struct( ...
    "InterceptMode", "specifiedTime", ...
    "SpecifiedInterceptTime_s", missionEndTime_s, ...
    "MatchTargetVelocity", false, ...
    "PlannerOptions", options);

%% Section 4: Run Planner

result = planAzElMovingTargetIntercept( ...
    obstacles, initialState, targetMotion, limits, interceptOptions);

%% Section 5: Validate Result

exampleValidation = validateAzElExampleResult( ...
    result, "target exits a containing obstacle", ...
    struct("RequireDirectBlocked", true));

targetOccupied = queryAzElTimeObstacle( ...
    result.Inputs.obstacles, targetPosition_deg(:, 1), ...
    targetPosition_deg(:, 2), targetTime_s);
firstClearSampleIndex = find(~targetOccupied, 1, "first");
targetStartsInside = targetOccupied(1);
targetEventuallyExits = ~isempty(firstClearSampleIndex) && ...
    all(~targetOccupied(firstClearSampleIndex:end));
targetWaitedInside = all(targetOccupied(1:targetWaitSampleCount)) && ...
    all(targetPosition_deg(1:targetWaitSampleCount, :) == ...
    containingCircleCenter_deg, "all");

targetIsClearAtIntercept = false;
if result.Success && all(isfinite(result.Intercept.TargetPosition_deg))
    targetIsClearAtIntercept = ~queryAzElTimeObstacle( ...
        result.Inputs.obstacles, result.Intercept.TargetPosition_deg(1), ...
        result.Intercept.TargetPosition_deg(2), result.Intercept.Time_s);
end

transitCircleIsBetween = ...
    initialState.position_deg(1) < transitCircleCenter_deg(1) && ...
    transitCircleCenter_deg(1) < containingCircleCenter_deg(1);
targetTravel_deg = sum(vecnorm(diff(targetPosition_deg, 1, 1), 2, 2));
successfulInterceptValidated = result.Success && targetIsClearAtIntercept;
scenarioValidation = struct( ...
    "Passed", targetStartsInside && targetWaitedInside && ...
        targetEventuallyExits && transitCircleIsBetween && ...
        targetTravel_deg > 0 && successfulInterceptValidated, ...
    "TargetStartsInside", targetStartsInside, ...
    "TargetWaitedInside", targetWaitedInside, ...
    "TargetEventuallyExits", targetEventuallyExits, ...
    "TargetIsClearAtIntercept", targetIsClearAtIntercept, ...
    "TargetFrameFailureReported", false, ...
    "TransitCircleIsBetween", transitCircleIsBetween, ...
    "TargetOccupiedAtInputSamples", targetOccupied, ...
    "FirstClearTargetSampleIndex", firstClearSampleIndex, ...
    "TargetTravel_deg", targetTravel_deg);

if ~scenarioValidation.Passed
    exampleValidation.Passed = false;
    exampleValidation.Message = ...
        "Target containment or obstacle-placement validation failed.";
end

%% Section 6: Plot Diagnostics And Motion

result.PlotHandles = struct();
if jerkConfiguration.PlotOutputs
    result.PlotHandles = plotAzElMotion( ...
        result, jerkConfiguration.PlotOptions);
end

%% Section 7: Return Example Metadata

result.ExampleValidation = exampleValidation;
result.ScenarioValidation = scenarioValidation;
result.ExampleConfiguration = jerkConfiguration;
result.ExampleInputs = struct( ...
    "obstacles", obstacles, ...
    "initialState", initialState, ...
    "targetMotion", targetMotion, ...
    "limits", limits, ...
    "interceptOptions", interceptOptions);
result.targetTime_s = targetTime_s;
result.targetPosition_deg = targetPosition_deg;
result.randomSeed = randomSeed;
result.postWaitStep_deg = postWaitStep_deg;
result.transitCircleCenter_deg = transitCircleCenter_deg;
result.transitCircleRadius_deg = transitCircleRadius_deg;
result.containingCircleCenter_deg = containingCircleCenter_deg;
result.containingCircleRadius_deg = containingCircleRadius_deg;
result.safetyMargin_deg = safetyMargin_deg;
result.ExampleMetrics = computeAzElExampleMetrics(result);
end
