function result = example05RlStaticDetour(showFigure)
%% Section 0: Header & Readme
% SYNTAX
%   result = example05RlStaticDetour()
%   result = example05RlStaticDetour(showFigure)
%**************************************************************************
% PURPOSE
%   - Replay the RL branch's rate- and acceleration-limited central blocker.
%**************************************************************************
% INPUTS
%   - showFigure (optional logical scalar, default false)
%**************************************************************************
% OUTPUTS
%   - result (scalar planner result)
%**************************************************************************
% UNITS
%   - Angles are degrees and time is seconds.

if nargin < 1
    showFigure = false;
end

%% Section 1: Build The Imported Mission
time_s = (0:40).';
azElData = makeAzElObstacleData( ...
    "Central blocker", time_s, ...
    [-1; 1; 1; -1; -1], [43; 43; 47; 47; 43]);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-6, 45], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
goal = struct( ...
    "type", "fixed", ...
    "time_s", 40, ...
    "position_deg", [6, 45], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [40, 50], ...
    "maxVelocity_deg_s", [2, 2], ...
    "maxAcceleration_deg_s2", [1, 1]);
request = struct( ...
    "obstacles", azElData, ...
    "initialState", initialState, ...
    "goal", goal, ...
    "limits", limits, ...
    "options", struct("safetyMargin_deg", 0.1, "deadline_s", 40));

%% Section 2: Plan & Independently Validate
result = planAzElAvoidance(request);
assert(result.success, "%s", char(join(result.message)));
validation = validateAzElCommand( ...
    result.command, request, result.arrivalTime_s);
assert(validation.isValid, "%s", char(join(validation.message)));
assert(validation.collision.minimumClearance_deg > 0.1, ...
    "The static detour did not clear its required margin.");

%% Section 3: Report & Optionally Display
fprintf("RL static detour: %.6f s; clearance %.6f deg.\n", ...
    result.arrivalTime_s, validation.collision.minimumClearance_deg);
if showFigure
    visualizeAzElPlan(request, result);
end
end
