function result = exampleUShapedAzElTimeSpace(viewOptions)
%% Section 0: Header & Readme
% SYNTAX
%   result = exampleUShapedAzElTimeSpace()
%   result = exampleUShapedAzElTimeSpace(viewOptions)
%**************************************************************************
% PURPOSE
%   - Extrude one static U-shaped obstacle through az/el/time space.
%   - Place the start inside the open cavity and the goal below the U.
%   - Show why the direct vector fails and select a minimum-edge boundary
%     connection between start-visible and goal-visible corner candidates.
%**************************************************************************
% INPUTS
%   - viewOptions (scalar struct, optional)
%       Overrides accepted by visualizeAzElTimeSpace.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Scenario data, packed field, selected path, static 3-D view, and
%       synchronized 3-D/2-D animation, and kinematic-profile plot.
%**************************************************************************
% UNITS
%   - Azimuth/elevation are degrees and time is seconds.

%% Section 1: Draw One Static U-Shaped Obstacle
if nargin < 1
    viewOptions = struct();
end
if ~isfield(viewOptions, "SafetyMarginDeg") || ...
        isempty(viewOptions.SafetyMarginDeg)
    viewOptions.SafetyMarginDeg = 1.5;
end
appliedSafetyMargin_deg = viewOptions.SafetyMarginDeg;
if ~isfield(viewOptions, "FigureVisible") || ...
        isempty(viewOptions.FigureVisible)
    viewOptions.FigureVisible = "on";
end
missionEndTime_s = 35;
time_s = [0; missionEndTime_s];

% Traverse the U boundary without closing the final edge explicitly. The
% solid obstacle consists of the left wall, right wall, and bottom wall.
% The cavity between the inner walls remains free and opens at the top.
uBoundary_deg = [ ...
    -8,  7; ... % outer top-left
    -5,  7; ... % inner top-left
    -5, -4; ... % inner bottom-left
     5, -4; ... % inner bottom-right
     5,  7; ... % inner top-right
     8,  7; ... % outer top-right
     8, -7; ... % outer bottom-right
    -8, -7];    % outer bottom-left
azElData = makeAzElObstacleData( ...
    "Static U-shaped obstacle", time_s, ...
    uBoundary_deg(:, 1), uBoundary_deg(:, 2), ...
    appliedSafetyMargin_deg);

%% Section 2: Put The Start In The Cavity & The Goal Below The U
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", missionEndTime_s, ...
    "position_deg", [0 -10], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);

%% Section 3: Pack The Final Az/El Geometry Without Another Margin
% makeAzElObstacleData already produced the safety-inflated planning data.
% Packing and collision queries now treat it as ordinary final geometry.
obstacleField = buildAzElTimeObstacleField(azElData);
[originalObstacleField, ~, ~] = ...
    recoverOriginalAzElObstacleField(obstacleField);
originalAzElData = originalObstacleField.SourceAzElData;
directFraction = linspace(0, 1, 501).';
directPosition_deg = initialState.position_deg + directFraction .* ...
    (goalState.position_deg - initialState.position_deg);
directTime_s = initialState.time_s + directFraction .* ...
    (goalState.time_s - initialState.time_s);
directBlocked = queryAzElTimeObstacle(obstacleField, ...
    directPosition_deg(:, 1), directPosition_deg(:, 2), directTime_s, ...
    struct( ...
    "CollisionMode", "polygon", ...
    "TimePaddingSamples", 0));
% Always draw the occupancy diagnosis before enforcing the scenario
% assertions. If inflation or packing accidentally fills the cavity, this
% figure remains open and shows the exact blocked grid, both boundaries,
% and which direct-line samples caused the failure.
occupancyDiagnostic = plotAzElObstacleOccupancyGrid( ...
    obstacleField, initialState, goalState, struct( ...
    "GridStep_deg", 0.25, ...
    "Time_s", initialState.time_s, ...
    "OriginalObstacleField", originalObstacleField, ...
    "DirectPosition_deg", directPosition_deg, ...
    "DirectTime_s", directTime_s, ...
    "FigureVisible", viewOptions.FigureVisible, ...
    "Title", "U-shaped packed-field occupancy"));
if directBlocked(1)
    error("exampleUShapedAzElTimeSpace:BlockedStart", ...
        "The start must lie in the free U-shaped cavity.");
end
if directBlocked(end)
    error("exampleUShapedAzElTimeSpace:BlockedGoal", ...
        "The goal must lie outside the obstacle material.");
end
if ~any(directBlocked)
    error("exampleUShapedAzElTimeSpace:DirectLineIsFree", ...
        "The direct reference vector should cross the U's bottom wall.");
end

%% Section 4: Show The Extruded U & Its Corner Candidates
if ~isfield(viewOptions, "Title") || isempty(viewOptions.Title)
    viewOptions.Title = ...
        "U-shaped obstacle: start trapped in cavity, goal below";
end
if ~isfield(viewOptions, "CandidateClearance_deg") || ...
        isempty(viewOptions.CandidateClearance_deg)
    viewOptions.CandidateClearance_deg = 0;
end
% makeAzElObstacleData already applied the margin. From here onward the
% planning polygon is ordinary final geometry: no display/query margin and
% no secondary original-versus-inflated behavior.
displayOptions = rmfield(viewOptions, "SafetyMarginDeg");
if isfield(displayOptions, "OriginalObstacleField")
    displayOptions = rmfield(displayOptions, "OriginalObstacleField");
end
spaceView = visualizeAzElTimeSpace( ...
    obstacleField, initialState, goalState, displayOptions);
if lower(string(viewOptions.FigureVisible)) == "on"
    set(spaceView.Figure, "Visible", "on");
    figure(spaceView.Figure);
    drawnow;
end
selectedBoundaryConnection = spaceView.SelectedBoundaryConnection;
if ~selectedBoundaryConnection.Success
    error("exampleUShapedAzElTimeSpace:NoBoundaryConnection", ...
        "No start-visible to goal-visible boundary chain was selected.");
end
minimumBoundaryEdgeCount = ...
    selectedBoundaryConnection.BoundaryEdgeCount;
limits = struct("maxVelocity_deg_s", [2 2]);
timedSlopePath = retimeAzElVisibilityPath( ...
    spaceView.SelectedVisibilityPath.PathPosition_deg, ...
    initialState, goalState, limits, struct( ...
    "GoalTimeMode", "earliestArrival"));
if ~timedSlopePath.Success
    error("exampleUShapedAzElTimeSpace:SlopeRetimingFailed", ...
        "%s", timedSlopePath.Message);
end
timedSlopeHandle = plot3(spaceView.Axes, ...
    timedSlopePath.position_deg(:, 1), ...
    timedSlopePath.position_deg(:, 2), ...
    timedSlopePath.time_s, "-", ...
    "Color", [0.05 0.70 0.82], ...
    "LineWidth", 4.0, ...
    "DisplayName", "Velocity-limited timed slope path");
drawnow;

%% Section 5: Animate The Timed Slope In 3-D & 2-D By Default
animationOptions = struct( ...
    "FigureVisible", viewOptions.FigureVisible, ...
    "Title", "U-shaped timed slope path");
if lower(string(viewOptions.FigureVisible)) == "off"
    % Hidden validation runs should still build every animation object but
    % should not spend wall time emulating human playback.
    animationOptions.Pause_s = 0;
end
animation = animateAzElTimedSlopePath( ...
    timedSlopePath, obstacleField, animationOptions);
kinematicPlot = plotAzElTimedSlopeKinematics(timedSlopePath, struct( ...
    "FigureVisible", viewOptions.FigureVisible, ...
    "Title", "U-shaped timed slope kinematics"));

result = struct( ...
    "azElData", azElData, ...
    "originalAzElData", originalAzElData, ...
    "inflatedAzElData", azElData, ... % compatibility alias
    "originalObstacleField", originalObstacleField, ...
    "obstacleField", obstacleField, ...
    "initialState", initialState, ...
    "goalState", goalState, ...
    "uBoundary_deg", uBoundary_deg, ...
    "directPosition_deg", directPosition_deg, ...
    "directTime_s", directTime_s, ...
    "directBlocked", directBlocked, ...
    "blockedDirectSampleCount", nnz(directBlocked), ...
    "occupancyDiagnostic", occupancyDiagnostic, ...
    "candidatePointsAzElTime", ...
    spaceView.CandidatePointsAzElTime, ...
    "candidateTypes", spaceView.CandidateTypes, ...
    "selectedBoundaryConnection", selectedBoundaryConnection, ...
    "minimumBoundaryEdgeCount", minimumBoundaryEdgeCount, ...
    "selectedVisibilityPath", spaceView.SelectedVisibilityPath, ...
    "safetyMargin_deg", appliedSafetyMargin_deg, ...
    "safetyMarginDiagnostics", spaceView.SafetyMarginDiagnostics, ...
    "limits", limits, ...
    "timedSlopePath", timedSlopePath, ...
    "goalLineInterceptTime_s", ...
    timedSlopePath.GoalLineInterceptTime_s, ...
    "timedSlopeHandle", timedSlopeHandle, ...
    "animation", animation, ...
    "kinematicPlot", kinematicPlot, ...
    "spaceView", spaceView);
fprintf([ ...
    "U-shaped az/el/time example: direct vector blocked at %d/%d " + ...
    "samples; %d boundary candidates displayed; selected boundary " + ...
    "chain uses %d edges; applied safety margin is %.2f deg; " + ...
    "earliest goal-line intercept is %.3f s.\n"], ...
    nnz(directBlocked), numel(directBlocked), ...
    size(spaceView.CandidatePointsAzElTime, 1), ...
    minimumBoundaryEdgeCount, result.safetyMargin_deg, ...
    timedSlopePath.GoalLineInterceptTime_s);
end
