function result = exampleInterceptMovingTargetEarliest(options)
%% Section 0: Header & Readme
% SYNTAX
%   result = exampleInterceptMovingTargetEarliest()
%   result = exampleInterceptMovingTargetEarliest(options)
%**************************************************************************
% PURPOSE
%   - Intercept a curved target track supplied as time-indexed Az/El points
%     at the earliest numerically resolved feasible time.
%   - Demonstrate position-only interception when the target tangent is not
%     constrained to align with the pursuer's direct route.
%**************************************************************************
% INPUTS
%   - options (scalar struct, optional)
%       Planner option overrides plus EnableJerkConstraint and
%       MaxJerk_deg_s3 example controls.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Validated intercept plan, search bracket, target track, plots, and
%       kinematic diagnostics.
%**************************************************************************
% UNITS
%   - Angles are degrees and time is seconds.
%**************************************************************************

%% Section 1: Resolve Example Controls
if nargin < 1 || isempty(options)
    options = struct();
end
[options, jerkConfiguration] = resolveAzElExampleOptions( ...
    options, struct( ...
    "MotionType", "velocityCarrying", ...
    "Verbose", true, ...
    "FigureVisible", "on", ...
    "Title", "Earliest moving-target intercept"), [2.5 2.5]);

%% Section 2: Create Obstacles
obstacles = [];

%% Section 3: Create Planner Inputs
targetMotion = struct( ...
    "time_s", (0:5:30).', ...
    "position_deg", [ ...
        8.0 -3.0; 8.8 -3.0; 9.6 -2.6; 10.2 -1.8; ...
        10.5 -0.7; 10.2 0.6; 9.5 2.0], ...
    "InterpolationMethod", "pchip");
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [0.8 0.8], ...
    "maxJerk_deg_s3", jerkConfiguration.MaxJerk_deg_s3);
interceptOptions = struct( ...
    "InterceptMode", "earliestArrival", ...
    "MaximumSearchDuration_s", 30, ...
    "InitialSearchStep_s", 0.5, ...
    "SearchTimeTolerance_s", 1e-5, ...
    "PlannerOptions", options);

%% Section 4: Run Planner
result = planAzElMovingTargetIntercept( ...
    initialState, targetMotion, limits, interceptOptions);

%% Section 5: Validate Result
exampleValidation = validateAzElExampleResult( ...
    result, "earliest moving-target intercept");
earliestSearchSatisfied = result.obstacleField.ObstacleCount == 0 && ...
    result.InterceptValidation.Passed && ...
    result.SearchDiagnostics.EarliestNumericallyResolved && ...
    ~result.SearchDiagnostics.EarliestCertified && ...
    result.SearchDiagnostics.UpperResidual_s <= 1e-7 && ...
    result.SearchDiagnostics.UpperFeasibleTime_s - ...
    result.SearchDiagnostics.LowerInfeasibleTime_s <= ...
    interceptOptions.SearchTimeTolerance_s + eps;
exampleValidation.EarliestSearchSatisfied = earliestSearchSatisfied;
exampleValidation.Passed = exampleValidation.Passed && ...
    earliestSearchSatisfied;

%% Section 6: Plot Diagnostics And Motion
% planAzElMovingTargetIntercept created all requested plots from result data.

%% Section 7: Return Example Metadata
result.ExampleValidation = exampleValidation;
result.obstacles = obstacles;
result.ExampleConfiguration = jerkConfiguration;
end
