function result = exampleInterceptMovingTargetEarliest(options)
%% Section 0: Header & Readme
% SYNTAX
%   result = exampleInterceptMovingTargetEarliest()
%   result = exampleInterceptMovingTargetEarliest(options)
%**************************************************************************
% PURPOSE
%   - Intercept a constant-velocity moving target at the earliest feasible
%     time in an obstacle-free azimuth/elevation environment.
%   - Match both target position and angular velocity at rendezvous.
%**************************************************************************
% INPUTS
%   - options (scalar struct, optional)
%       Planner option overrides plus EnableJerkConstraint and
%       MaxJerk_deg_s3 example controls.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Validated intercept plan, search bracket, target track, plots, and
%       kinematic diagnostics.
%**************************************************************************
% UNITS
%   - Angles are degrees and time is seconds.
if nargin < 1 || isempty(options)
    options = struct();
end
[options, jerkConfiguration] = resolveAzElExampleOptions( ...
    options, struct( ...
    "MotionType", "velocityCarrying", ...
    "Verbose", true, ...
    "FigureVisible", "on", ...
    "Title", "Earliest moving-target intercept"), [2.5 2.5]);

%% Section 1: Construct The Obstacle-Free Target Scenario
obstacles = [];
targetMotion = struct( ...
    "referenceTime_s", 0, ...
    "referencePosition_deg", [8 -3], ...
    "velocity_deg_s", [0.25 -0.09375]);

%% Section 2: Define The Planning Request
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [0.8 0.8], ...
    "maxJerk_deg_s3", jerkConfiguration.MaxJerk_deg_s3);
interceptOptions = struct( ...
    "InterceptMode", "earliestArrival", ...
    "MaximumSearchDuration_s", 30, ...
    "InitialSearchStep_s", 0.5, ...
    "SearchTimeTolerance_s", 1e-5, ...
    "MatchTargetVelocity", true, ...
    "PlannerOptions", options);

%% Section 3: Run The Maintained Intercept Planner
result = planAzElMovingTargetIntercept( ...
    initialState, targetMotion, limits, interceptOptions);
result.obstacles = obstacles;
result.ExampleConfiguration = jerkConfiguration;

%% Section 4: Validate The Intercept
if ~result.Success || ~result.Validation.Passed || ...
        ~result.InterceptValidation.Passed
    error("exampleInterceptMovingTargetEarliest:PlanningFailed", ...
        "Earliest intercept validation failed. Diagnostic plots remain " + ...
        "open. %s", result.Message);
end
if result.obstacleField.ObstacleCount ~= 0 || ...
        ~result.SearchDiagnostics.EarliestCertified || ...
        result.SearchDiagnostics.UpperResidual_s > 1e-7 || ...
        result.SearchDiagnostics.UpperFeasibleTime_s - ...
        result.SearchDiagnostics.LowerInfeasibleTime_s > ...
        interceptOptions.SearchTimeTolerance_s + eps
    error("exampleInterceptMovingTargetEarliest:SearchValidationFailed", ...
        "The first feasible intercept was not certified by the search.");
end
end
