function result = exampleFortyMovingCircleGrid(exampleOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   result = exampleFortyMovingCircleGrid()
%   result = exampleFortyMovingCircleGrid(exampleOverrides)
%**************************************************************************
% PURPOSE
%   - Plan diagonally through 40 large circles on an equal 8-by-5 grid.
%   - Show the full visibility planner while every circle moves vertically.
%   - Exercise bounded failure diagnostics without claiming no path exists.
%**************************************************************************
% INPUTS
%   - exampleOverrides (scalar struct, optional; default struct())
%       Planner overrides plus the shared FigureVisible, PlotOutputs,
%       ShowAnimation, ShowKinematicPlot, and MaxJerk_deg_s3 controls.
%**************************************************************************
% OUTPUTS
%   - result (scalar planner-result struct)
%       Expected bounded failure, moving-grid history, diagnostics, and
%       optional plot handles. A failure is not a no-path certificate.
%**************************************************************************
% UNITS
%   - Position is degrees; time is seconds; derivatives use deg/s,
%     deg/s^2, and deg/s^3.
%**************************************************************************

%% Section 1: Resolve Example Controls

if nargin < 1 || isempty(exampleOverrides)
    exampleOverrides = struct();
end

[options, jerkConfiguration] = resolveAzElExampleOptions( ...
    exampleOverrides, struct( ...
        "GoalTimeMode", "earliestArrival", ...
        "SampleTime_s", 0.05, ...
        "AllowAzimuthWrapping", false, ...
        "AzimuthInterval_deg", [-180 180], ...
        "MaximumSeedCount", 2, ...
        "CollocationSegmentCount", 6, ...
        "MaximumPlanningTime_s", 30, ...
        "Verbose", true, ...
        "FigureVisible", "on", ...
        "Title", "Diagonal motion through 40 moving circles"), ...
    [2.5 2.5]);

options.AllowAzimuthWrapping = false;

%% Section 2: Create Obstacles

missionEndTime_s = 200;
obstacleTime_s = [0; 30; missionEndTime_s];
gridSpacing_deg = 8.0;
columnAzimuth_deg = (-3.5:3.5) * gridSpacing_deg;
rowElevation_deg = (-2:2).' * gridSpacing_deg;
circleRadius_deg = 3.0;
safetyMargin_deg = 0.10;
circleVertexCount = 8;
circleAngle_rad = (0:circleVertexCount - 1).' * ...
    (2 * pi / circleVertexCount);
unitCircle = [cos(circleAngle_rad), sin(circleAngle_rad)];
polygonRadius_deg = circleRadius_deg / cos(pi / circleVertexCount);

obstacleCount = numel(columnAzimuth_deg) * numel(rowElevation_deg);
centerAzimuth_deg = zeros(obstacleCount, 1);
baseCenterElevation_deg = zeros(obstacleCount, 1);
obstacleIndex = 0;
for rowIndex = 1:numel(rowElevation_deg)
    for columnIndex = 1:numel(columnAzimuth_deg)
        obstacleIndex = obstacleIndex + 1;
        centerAzimuth_deg(obstacleIndex) = ...
            columnAzimuth_deg(columnIndex);
        baseCenterElevation_deg(obstacleIndex) = ...
            rowElevation_deg(rowIndex);
    end
end
directLineSlope = (24 - (-24)) / (36 - (-36));
directLineElevation_deg = directLineSlope * centerAzimuth_deg;
signedLineOffset_deg = ...
    baseCenterElevation_deg - directLineElevation_deg;
moveDirection = sign(signedLineOffset_deg);
zeroOffsetIndices = find(moveDirection == 0);
for zeroIndex = reshape(zeroOffsetIndices, 1, [])
    moveDirection(zeroIndex) = 2 * mod(zeroIndex, 2) - 1;
end
requiredVerticalOffset_deg = ...
    (polygonRadius_deg + safetyMargin_deg + 0.25) * ...
    sqrt(1 + directLineSlope^2);
openLineOffset_deg = moveDirection .* max( ...
    abs(signedLineOffset_deg) + 0.25, requiredVerticalOffset_deg);
openCenterElevation_deg = ...
    directLineElevation_deg + openLineOffset_deg;
centerElevation_deg = [ ...
    baseCenterElevation_deg.'; ...
    openCenterElevation_deg.'; ...
    openCenterElevation_deg.'];
verticalTranslation_deg = centerElevation_deg - ...
    baseCenterElevation_deg.';

% One NaN-separated canonical obstacle preserves all 40 occupied regions.
% It prevents seed generation from repeating a polygon union for each
% region at each sampled time.
obstacleAzimuthByTime_deg = cell(numel(obstacleTime_s), 1);
obstacleElevationByTime_deg = cell(numel(obstacleTime_s), 1);
for sampleIndex = 1:numel(obstacleTime_s)
    combinedCircleShape = polyshape();
    for obstacleIndex = 1:obstacleCount
        center_deg = [centerAzimuth_deg(obstacleIndex), ...
            centerElevation_deg(sampleIndex, obstacleIndex)];
        circlePosition_deg = center_deg + polygonRadius_deg * unitCircle;
        circleShape = polyshape( ...
            circlePosition_deg(:, 1), circlePosition_deg(:, 2), ...
            "Simplify", false, "KeepCollinearPoints", true);
        combinedCircleShape = union(combinedCircleShape, circleShape);
    end
    [obstacleAzimuthByTime_deg{sampleIndex}, ...
        obstacleElevationByTime_deg{sampleIndex}] = ...
        boundary(combinedCircleShape);
end
obstacles = makeAzElObstacleData( ...
    "40 moving grid circles", obstacleTime_s, ...
    obstacleAzimuthByTime_deg, obstacleElevationByTime_deg, ...
    safetyMargin_deg);

%% Section 3: Create Planner Inputs

initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-36 -24], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", missionEndTime_s, ...
    "position_deg", [36 24], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [0.8 0.8], ...
    "maxJerk_deg_s3", jerkConfiguration.MaxJerk_deg_s3);

%% Section 4: Run Planner

result = planAzElMotion(obstacles, initialState, goalState, limits, options);

%% Section 5: Validate Result

exampleValidation = validateAzElExampleResult( ...
    result, "40-circle moving grid", ...
    struct("ExpectedSuccess", false));

spacingTolerance_deg = 1e-12;
equalColumnSpacing = all(abs(diff(columnAzimuth_deg) - ...
    gridSpacing_deg) <= spacingTolerance_deg);
equalRowSpacing = all(abs(diff(rowElevation_deg) - ...
    gridSpacing_deg) <= spacingTolerance_deg);
startAndGoalSpanGridDiagonal = ...
    initialState.position_deg(1) < min(columnAzimuth_deg) && ...
    initialState.position_deg(2) < min(rowElevation_deg) && ...
    goalState.position_deg(1) > max(columnAzimuth_deg) && ...
    goalState.position_deg(2) > max(rowElevation_deg);
allObstaclesMoved = all(max(centerElevation_deg, [], 1) - ...
    min(centerElevation_deg, [], 1) > 0);
directProbeFraction = linspace(0, 1, 801).';
directProbePosition_deg = initialState.position_deg + ...
    directProbeFraction .* ...
    (goalState.position_deg - initialState.position_deg);
directBlockedInitially = any(queryAzElTimeObstacle( ...
    obstacles, directProbePosition_deg(:, 1), ...
    directProbePosition_deg(:, 2), ...
    repmat(obstacleTime_s(1), size(directProbeFraction))));
directClearAfterMotion = ~any(queryAzElTimeObstacle( ...
    obstacles, directProbePosition_deg(:, 1), ...
    directProbePosition_deg(:, 2), ...
    repmat(obstacleTime_s(2), size(directProbeFraction))));

gridValidation = struct( ...
    "Passed", obstacleCount == 40 && equalColumnSpacing && ...
        equalRowSpacing && startAndGoalSpanGridDiagonal && ...
        allObstaclesMoved && directBlockedInitially && ...
        directClearAfterMotion, ...
    "ObstacleCount", obstacleCount, ...
    "EqualColumnSpacing", equalColumnSpacing, ...
    "EqualRowSpacing", equalRowSpacing, ...
    "StartAndGoalSpanGridDiagonal", startAndGoalSpanGridDiagonal, ...
    "AllObstaclesMoved", allObstaclesMoved, ...
    "DirectBlockedInitially", directBlockedInitially, ...
    "DirectClearAfterMotion", directClearAfterMotion);

if ~gridValidation.Passed
    exampleValidation.Passed = false;
    exampleValidation.Message = ...
        "The 40-circle grid geometry or motion validation failed.";
end

%% Section 6: Plot Diagnostics And Motion

result.PlotHandles = struct();
if jerkConfiguration.PlotOutputs
    result.PlotHandles = plotAzElMotion( ...
        result, jerkConfiguration.PlotOptions);
end

%% Section 7: Return Example Metadata

result.ExampleValidation = exampleValidation;
result.GridValidation = gridValidation;
result.ExampleConfiguration = jerkConfiguration;
result.ExampleInputs = struct( ...
    "obstacles", obstacles, ...
    "initialState", initialState, ...
    "goalState", goalState, ...
    "limits", limits, ...
    "options", options);
result.obstacleTime_s = obstacleTime_s;
result.centerAzimuth_deg = centerAzimuth_deg;
result.centerElevation_deg = centerElevation_deg;
result.verticalTranslation_deg = verticalTranslation_deg;
result.gridSpacing_deg = gridSpacing_deg;
result.circleRadius_deg = circleRadius_deg;
result.safetyMargin_deg = safetyMargin_deg;
result.ExampleMetrics = computeAzElExampleMetrics(result);
end
