function result = example01Unobstructed(showFigure)
%% Section 0: Header & Readme
% SYNTAX
%   result = example01Unobstructed()
%   result = example01Unobstructed(showFigure)
%**************************************************************************
% PURPOSE
%   - Demonstrate a complete-state unobstructed az/el mission.
%**************************************************************************
% INPUTS
%   - showFigure (optional logical scalar, default false)
%       Affects display only and is never passed into planning.
%**************************************************************************
% OUTPUTS
%   - result (scalar planner result)
%**************************************************************************
% UNITS
%   - Angles are degrees and time is seconds.

if nargin < 1
    showFigure = false;
end

%% Section 1: Define Canonical Mission Inputs
azElData = [];
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
goal = struct( ...
    "type", "fixed", ...
    "time_s", NaN, ...
    "position_deg", [20, 10], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-180, 180], ...
    "elevation_deg", [-90, 90], ...
    "maxVelocity_deg_s", [10, 10], ...
    "maxAcceleration_deg_s2", [5, 5]);
missionOptions = struct();
request = struct( ...
    "obstacles", azElData, ...
    "initialState", initialState, ...
    "goal", goal, ...
    "limits", limits, ...
    "options", missionOptions);

%% Section 2: Plan & Independently Validate
result = planAzElAvoidance(request);
assert(result.success, result.message);
validation = validateAzElCommand( ...
    result.command, request, result.arrivalTime_s);
assert(validation.isValid, validation.message);

%% Section 3: Report & Optionally Display
fprintf("Unobstructed arrival: %.6f s (%s)\n", ...
    result.arrivalTime_s, result.guarantee.optimality);
if showFigure
    visualizeAzElPlan(request, result);
end
end
