function result = exampleUShapedAzElTimeSpace(options)
%EXAMPLEUSHAPEDAZELTIMESPACE Define one U and call planAzElMotion.
if nargin < 1 || isempty(options)
    options = struct();
end
options = exampleOptions(options, struct( ...
    "SafetyMarginDeg", 0.20, ...
    "MotionType", "velocityCarrying", ...
    "FigureVisible", "on", ...
    "Title", "U-shaped az/el obstacle"));
missionEndTime_s = 35;
uBoundary_deg = [ ...
    -8,  7; -5,  7; -5, -4; 5, -4; ...
     5,  7;  8,  7;  8, -7; -8, -7];
obstacle = makeAzElObstacleData( ...
    "Static U-shaped obstacle", [0; missionEndTime_s], ...
    uBoundary_deg(:, 1), uBoundary_deg(:, 2));
initialState = stateAt(0, [0 0]);
goalState = stateAt(missionEndTime_s, [0 -10]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [0.75 0.75]);

result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);
result.uBoundary_deg = uBoundary_deg;
end

function state = stateAt(time_s, position_deg)
state = struct( ...
    "time_s", time_s, "position_deg", position_deg, ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
end

function options = exampleOptions(options, defaults)
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(options, names{index}) || isempty(options.(names{index}))
        options.(names{index}) = defaults.(names{index});
    end
end
end
