function result = exampleOpeningUShapedAzElTimeSpace(exampleOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   result = exampleOpeningUShapedAzElTimeSpace()
%   result = exampleOpeningUShapedAzElTimeSpace(exampleOverrides)
%**************************************************************************
% PURPOSE
%   - Demonstrate waiting for a timed opening in one U-shaped obstacle.
%**************************************************************************
% INPUTS
%   - exampleOverrides (scalar struct, optional; default struct())
%       Public planner and uniform display controls.
%**************************************************************************
% OUTPUTS
%   - result (scalar planAzElMotion result)
%       Includes independent opening-use validation and example metadata.
%**************************************************************************
% UNITS
%   - Position is degrees; time is seconds; derivatives use deg/s,
%     deg/s^2, and deg/s^3.
%**************************************************************************

%% Section 1: Resolve Example Controls

if nargin < 1 || isempty(exampleOverrides)
    exampleOverrides = struct();
end
[options, displayOptions] = resolveAzElExampleOptions( ...
    exampleOverrides, struct( ...
    "GoalTimeMode", "fixedArrival", ...
    "MaximumSeedCount", 2, ...
    "MaximumPlanningTime_s", 120, ...
    "Verbose", true, ...
    "FigureVisible", "on", ...
    "Title", "U-shaped gate opening from 7 to 12 seconds"), [2.5 2.5]);

%% Section 2: Create Obstacles

missionEndTime_s = 18;
openingStartTime_s = 7;
openingTime_s = 12;
safetyMargin_deg = 0.20;
gapHalfWidth_deg = 1.5;
leftOpenBoundary_deg = [ ...
    -8 7; -5 7; -5 -4; -gapHalfWidth_deg -4; ...
    -gapHalfWidth_deg -7; -8 -7];
rightOpenBoundary_deg = [ ...
    5 7; 8 7; 8 -7; gapHalfWidth_deg -7; ...
    gapHalfWidth_deg -4; 5 -4];
closedGate_deg = [ ...
    -gapHalfWidth_deg -4; gapHalfWidth_deg -4; ...
    gapHalfWidth_deg -7; -gapHalfWidth_deg -7];
gateDrop_deg = [0 -13];
openGate_deg = closedGate_deg + gateDrop_deg;
staticBoundary_deg = [ ...
    leftOpenBoundary_deg; NaN NaN; rightOpenBoundary_deg];
closedBoundary_deg = [ ...
    staticBoundary_deg; NaN NaN; closedGate_deg];
openBoundary_deg = [ ...
    staticBoundary_deg; NaN NaN; openGate_deg];
obstacleTime_s = [0; openingStartTime_s; openingTime_s; missionEndTime_s];
staticObstacle = makeAzElObstacleData( ...
    "Open U boundary", obstacleTime_s, ...
    staticBoundary_deg(:, 1), staticBoundary_deg(:, 2), ...
    safetyMargin_deg);
gateAzimuthByTime_deg = { ...
    closedGate_deg(:, 1); closedGate_deg(:, 1); ...
    openGate_deg(:, 1); openGate_deg(:, 1)};
gateElevationByTime_deg = { ...
    closedGate_deg(:, 2); closedGate_deg(:, 2); ...
    openGate_deg(:, 2); openGate_deg(:, 2)};
gateObstacle = makeAzElObstacleData( ...
    "Moving U gate", obstacleTime_s, ...
    gateAzimuthByTime_deg, gateElevationByTime_deg, safetyMargin_deg);
obstacles = combineAzElObstacles(staticObstacle, gateObstacle);

%% Section 3: Create Planner Inputs

initialState = struct( ...
    "time_s", 0, "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", missionEndTime_s, "position_deg", [0 -10], ...
    "velocity_deg_s", [0 0], "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [0.75 0.75], ...
    "maxJerk_deg_s3", displayOptions.MaxJerk_deg_s3);

%% Section 4: Run Planner

result = planAzElMotion( ...
    obstacles, initialState, goalState, limits, options);

%% Section 5: Validate Result

exampleValidation = validateAzElExampleResult( ...
    result, "opening U-shaped obstacle");
openingValidation = validateOpeningUse( ...
    result, openingStartTime_s, openingTime_s, ...
    gapHalfWidth_deg, safetyMargin_deg);
exampleValidation.Passed = exampleValidation.Passed && ...
    openingValidation.Passed;
if ~openingValidation.Passed
    exampleValidation.Message = exampleValidation.Message + " " + ...
        openingValidation.Message;
end
result.ExampleValidation = exampleValidation;
result.OpeningValidation = openingValidation;

%% Section 6: Plot Diagnostics And Motion

result.PlotHandles = struct();
if displayOptions.PlotOutputs
    result.PlotHandles = plotAzElMotion( ...
        result, displayOptions.PlotOptions);
end

%% Section 7: Return Example Metadata

result.ExampleConfiguration = displayOptions;
result.ExampleInputs = struct( ...
    "obstacles", obstacles, "initialState", initialState, ...
    "goalState", goalState, "limits", limits, "options", options);
result.ExampleMetrics = computeAzElExampleMetrics(result);
result.openingTime_s = openingTime_s;
result.openingStartTime_s = openingStartTime_s;
result.obstacleTime_s = obstacleTime_s;
result.closedUBoundary_deg = closedBoundary_deg;
result.openUBoundary_deg = openBoundary_deg;
result.gapHalfWidth_deg = gapHalfWidth_deg;
end

%% Section 8: Local Functions

function validation = validateOpeningUse( ...
        result, openingStartTime_s, openingTime_s, ...
        gapHalfWidth_deg, safetyMargin_deg)
% PURPOSE
%   - Verify that returned timing delays crossing until the gap is open.
waitSeedSelected = false;
stayedBeforeClosedBarrier = false;
crossedOpenGap = false;
directTimingRequiresDelay = false;
directEntryTime_s = NaN;
selectedArrivalTime_s = NaN;
comparisonArrivalTime_s = NaN;
if result.Success
    selectedSeed = result.Seeds(result.SelectedSeedIndex);
    repeatedPosition = vecnorm( ...
        diff(selectedSeed.position_deg, 1, 1), 2, 2) <= 1e-10;
    waitSeedSelected = any(repeatedPosition) || ...
        selectedSeed.Source == "directWait";
    beforeOpening = result.time_s <= openingStartTime_s;
    stayedBeforeClosedBarrier = any(beforeOpening) && all( ...
        result.position_deg(beforeOpening, 2) >= ...
        -4 + safetyMargin_deg - 1e-6);
    crossesBottomBar = result.position_deg(:, 2) <= ...
        -4 + safetyMargin_deg & result.position_deg(:, 2) >= ...
        -7 - safetyMargin_deg;
    protectedGapHalfWidth_deg = gapHalfWidth_deg - safetyMargin_deg;
    crossedOpenGap = any(crossesBottomBar & ...
        abs(result.position_deg(:, 1)) < protectedGapHalfWidth_deg & ...
        result.time_s > openingStartTime_s);
    directTime_s = linspace( ...
        result.Inputs.initialState.time_s, ...
        result.Inputs.goalState.time_s, 401).';
    directFraction = linspace(0, 1, 401).';
    directPosition_deg = result.Inputs.initialState.position_deg + ...
        directFraction .* (result.Inputs.goalState.position_deg - ...
        result.Inputs.initialState.position_deg);
    directOccupied = queryAzElTimeObstacle( ...
        result.Inputs.obstacles, directPosition_deg(:, 1), ...
        directPosition_deg(:, 2), directTime_s);
    directTimingRequiresDelay = any(directOccupied);
    firstDirectCollisionIndex = find(directOccupied, 1, "first");
    if ~isempty(firstDirectCollisionIndex)
        directEntryTime_s = directTime_s(firstDirectCollisionIndex);
    end
    selectedArrivalTime_s = result.time_s(end);
    otherValidated = find([result.SeedSummaries.ValidationPassed]);
    otherValidated(otherValidated == result.SelectedSeedIndex) = [];
    if ~isempty(otherValidated)
        comparisonArrivalTime_s = min( ...
            [result.SeedSummaries(otherValidated).ArrivalTime_s]);
    end
end
passed = result.Success && directTimingRequiresDelay && ...
    stayedBeforeClosedBarrier && crossedOpenGap;
if passed
    message = "The returned motion delayed crossing until the gap opened.";
else
    message = sprintf( ...
        "Opening use failed: success=%d, delay=%d, stayed=%d, crossed=%d.", ...
        result.Success, directTimingRequiresDelay, ...
        stayedBeforeClosedBarrier, crossedOpenGap);
end
validation = struct( ...
    "Passed", passed, ...
    "Message", string(message), ...
    "WaitSeedSelected", waitSeedSelected, ...
    "DirectTimingRequiresDelay", directTimingRequiresDelay, ...
    "DirectEntryTime_s", directEntryTime_s, ...
    "StayedBeforeClosedBarrier", stayedBeforeClosedBarrier, ...
    "CrossedOpenGap", crossedOpenGap, ...
    "OpeningStartTime_s", openingStartTime_s, ...
    "OpeningTime_s", openingTime_s, ...
    "SelectedArrivalTime_s", selectedArrivalTime_s, ...
    "ComparisonArrivalTime_s", comparisonArrivalTime_s);
end
