function result = exampleInterceptMovingTargetAtSetTime( ...
        interceptTime_s, options)
%% Section 0: Header & Readme
% SYNTAX
%   result = exampleInterceptMovingTargetAtSetTime()
%   result = exampleInterceptMovingTargetAtSetTime(interceptTime_s)
%   result = exampleInterceptMovingTargetAtSetTime(options)
%   result = exampleInterceptMovingTargetAtSetTime( ...
%       interceptTime_s, options)
%**************************************************************************
% PURPOSE
%   - Intercept a constant-velocity moving target at a specified time in an
%     obstacle-free azimuth/elevation environment.
%   - Match both target position and angular velocity at rendezvous.
%**************************************************************************
% INPUTS
%   - interceptTime_s (positive scalar, optional; default 12)
%   - options (scalar struct, optional)
%       Planner option overrides plus EnableJerkConstraint and
%       MaxJerk_deg_s3 example controls.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Validated fixed-time intercept, target track, plots, and kinematic
%       diagnostics.
%**************************************************************************
% UNITS
%   - Angles are degrees and time is seconds.
%**************************************************************************

%% Section 1: Resolve Example Controls
if nargin < 1 || isempty(interceptTime_s)
    interceptTime_s = 12;
    options = struct();
elseif isstruct(interceptTime_s)
    options = interceptTime_s;
    interceptTime_s = 12;
elseif nargin < 2 || isempty(options)
    options = struct();
end
validateattributes(interceptTime_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
[options, jerkConfiguration] = resolveAzElExampleOptions( ...
    options, struct( ...
    "MotionType", "velocityCarrying", ...
    "Verbose", true, ...
    "FigureVisible", "on", ...
    "Title", sprintf( ...
    "Moving-target intercept at t = %.3f s", interceptTime_s)), ...
    [2.5 2.5]);

%% Section 2: Create Obstacles
obstacles = [];
targetMotion = struct( ...
    "referenceTime_s", 0, ...
    "referencePosition_deg", [8 -3], ...
    "velocity_deg_s", [0.25 -0.09375]);

%% Section 3: Create Planner Inputs
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [0.8 0.8], ...
    "maxJerk_deg_s3", jerkConfiguration.MaxJerk_deg_s3);
interceptOptions = struct( ...
    "InterceptMode", "specifiedTime", ...
    "SpecifiedInterceptTime_s", interceptTime_s, ...
    "MatchTargetVelocity", true, ...
    "PlannerOptions", options);

%% Section 4: Run Planner
result = planAzElMovingTargetIntercept( ...
    initialState, targetMotion, limits, interceptOptions);

%% Section 5: Validate Result
exampleValidation = validateAzElExampleResult( ...
    result, "specified-time moving-target intercept");
specifiedTimeSatisfied = result.obstacleField.ObstacleCount == 0 && ...
    result.InterceptValidation.Passed && ...
    abs(result.InterceptTime_s - interceptTime_s) <= 1e-8 && ...
    abs(result.goalLineInterceptTime_s - interceptTime_s) <= 1e-7;
exampleValidation.SpecifiedTimeSatisfied = specifiedTimeSatisfied;
exampleValidation.Passed = exampleValidation.Passed && ...
    specifiedTimeSatisfied;

%% Section 6: Plot Diagnostics And Motion
% planAzElMovingTargetIntercept created all requested plots from result data.

%% Section 7: Return Example Metadata
result.ExampleValidation = exampleValidation;
result.obstacles = obstacles;
result.ExampleConfiguration = jerkConfiguration;
end
