function result = exampleMovingDeformingUSOutlineVisibility(options)
%% Section 0: Header & Readme
% SYNTAX
%   result = exampleMovingDeformingUSOutlineVisibility()
%   result = exampleMovingDeformingUSOutlineVisibility(options)
%**************************************************************************
% PURPOSE
%   - Move and continuously deform a full-resolution contiguous-U.S.
%     outline through az/el space.
%   - Recompute bounded silhouette/tangency candidates independently for
%     every displayed time slice; no rigid-shape or shared-index assumption
%     is used by the visibility graph.
%   - Retain the full-resolution source outline as canonical provenance and
%     use the complete conservative protected slice for collision checks,
%     while reducing graph nodes and validated boundary command points.
%**************************************************************************
% INPUTS
%   - options (scalar struct, optional)
%       Planner overrides plus EnableJerkConstraint and MaxJerk_deg_s3.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%       Validated plan, moving outline history, per-slice candidate metrics,
%       visibility-edge counts, and boundary-route reduction diagnostics.
%**************************************************************************
% UNITS
%   - Longitude/latitude are interpreted as azimuth/elevation degrees.
%   - Time is seconds.
if nargin < 1 || isempty(options)
    options = struct();
end
[options, jerkConfiguration] = resolveAzElExampleOptions( ...
    options, struct( ...
    "MotionType", "velocityCarrying", ...
    "GoalTimeMode", "earliestArrival", ...
    "TurnRadius_deg", 0.50, ...
    "PolygonCandidateMode", "extreme", ...
    "ExtremeDirectionCount", 16, ...
    "MaximumTangenciesPerReference", 2, ...
    "BoundaryRouteReductionTolerance_deg", 0.25, ...
    "MaximumDisplayedSlicesPerObstacle", 5, ...
    "ShowSweptSurfaces", true, ...
    "Verbose", true, ...
    "FigureVisible", "on", ...
    "Title", "Moving/deforming U.S.: slice-local visibility reduction"), ...
    [12 12]);

%% Section 1: Read One Full-Resolution Mainland Outline
boundaryFile = which("usastatehi.shp");
if isempty(boundaryFile)
    error("exampleMovingDeformingUSOutlineVisibility:" + ...
        "MappingToolboxRequired", ...
        "Mapping Toolbox file usastatehi.shp was not found.");
end
stateBoundary = shaperead(boundaryFile, "UseGeoCoords", true);
stateName = string({stateBoundary.Name});
stateBoundary = stateBoundary(~ismember(stateName, ["Alaska" "Hawaii"]));
mainlandUS = polyshape( ...
    stateBoundary(1).Lon, stateBoundary(1).Lat, ...
    "Simplify", false, "KeepCollinearPoints", true);
for stateIndex = 2:numel(stateBoundary)
    statePolygon = polyshape( ...
        stateBoundary(stateIndex).Lon, stateBoundary(stateIndex).Lat, ...
        "Simplify", false, "KeepCollinearPoints", true);
    mainlandUS = union(mainlandUS, statePolygon);
end
[allLongitude_deg, allLatitude_deg] = boundary(mainlandUS);
[baseLongitude_deg, baseLatitude_deg] = largestFiniteRing( ...
    allLongitude_deg, allLatitude_deg);

%% Section 2: Create Independently Deformed Az/El Slices
missionEndTime_s = 240;
obstacleTime_s = linspace(0, missionEndTime_s, 5).';
sliceCount = numel(obstacleTime_s);
baseCenter_deg = [mean(baseLongitude_deg), mean(baseLatitude_deg)];
baseLocal_deg = [baseLongitude_deg - baseCenter_deg(1), ...
    baseLatitude_deg - baseCenter_deg(2)];
localRange_deg = max(baseLocal_deg, [], 1) - ...
    min(baseLocal_deg, [], 1);
sliceAzimuth_deg = cell(sliceCount, 1);
sliceElevation_deg = cell(sliceCount, 1);
sliceArea_deg2 = zeros(sliceCount, 1);
sliceAspectRatio = zeros(sliceCount, 1);
sliceCentroid_deg = zeros(sliceCount, 2);
for sampleIndex = 1:sliceCount
    phase_rad = 2 * pi * (sampleIndex - 1) / sliceCount;
    deformedLocal_deg = baseLocal_deg;
    % Smooth nonlinear warps make the projected shape genuinely different
    % at each slice; this is not a rigid translation or shared affine copy.
    deformedLocal_deg(:, 1) = deformedLocal_deg(:, 1) + ...
        0.04 * sin(2 * pi * baseLocal_deg(:, 2) / ...
        localRange_deg(2) + phase_rad);
    deformedLocal_deg(:, 2) = deformedLocal_deg(:, 2) + ...
        0.03 * sin(2 * pi * baseLocal_deg(:, 1) / ...
        localRange_deg(1) - 0.7 * phase_rad);
    scaleAzimuth = 0.998 + 0.004 * sin(phase_rad + 0.4);
    scaleElevation = 0.998 + 0.004 * cos(phase_rad - 0.2);
    shear = 0.003 * sin(2 * phase_rad);
    rotation_rad = deg2rad(0.35 * sin(phase_rad + 0.3));
    deformationMatrix = [scaleAzimuth shear; 0 scaleElevation];
    rotationMatrix = [cos(rotation_rad) -sin(rotation_rad); ...
        sin(rotation_rad) cos(rotation_rad)];
    transformedLocal_deg = deformedLocal_deg * ...
        deformationMatrix.' * rotationMatrix.';
    translation_deg = [ ...
        0.35 * sin(phase_rad), 0.25 * cos(phase_rad + 0.5)];
    transformed_deg = transformedLocal_deg + ...
        baseCenter_deg + translation_deg;
    sliceAzimuth_deg{sampleIndex} = transformed_deg(:, 1);
    sliceElevation_deg{sampleIndex} = transformed_deg(:, 2);
    sliceArea_deg2(sampleIndex) = abs(polyarea( ...
        transformed_deg(:, 1), transformed_deg(:, 2)));
    sliceBounds_deg = [min(transformed_deg, [], 1); ...
        max(transformed_deg, [], 1)];
    sliceSize_deg = diff(sliceBounds_deg, 1, 1);
    sliceAspectRatio(sampleIndex) = ...
        sliceSize_deg(1) / sliceSize_deg(2);
    sliceCentroid_deg(sampleIndex, :) = mean(transformed_deg, 1);
end

safetyMargin_deg = 0.10;
obstacle = makeAzElObstacleData( ...
    "Moving and deforming contiguous United States", obstacleTime_s, ...
    sliceAzimuth_deg, sliceElevation_deg, safetyMargin_deg);

%% Section 3: Define One Automatic Planning Request
initialState = struct("time_s", 0, "position_deg", [-102 20]);
goalState = struct( ...
    "time_s", missionEndTime_s, "position_deg", [-102 55]);
limits = struct( ...
    "maxVelocity_deg_s", [8 8], ...
    "maxAcceleration_deg_s2", [3 3], ...
    "maxJerk_deg_s3", jerkConfiguration.MaxJerk_deg_s3);

%% Section 4: Run The Maintained Planner Once
result = planAzElMotion( ...
    obstacle, initialState, goalState, limits, options);
result.ExampleConfiguration = jerkConfiguration;
result.ObstacleTime_s = obstacleTime_s;
result.USoutlineAzimuthBySlice_deg = sliceAzimuth_deg;
result.USoutlineElevationBySlice_deg = sliceElevation_deg;
result.RawVertexCountPerSlice = cellfun(@numel, sliceAzimuth_deg);
result.SliceArea_deg2 = sliceArea_deg2;
result.SliceAspectRatio = sliceAspectRatio;
result.SliceCentroid_deg = sliceCentroid_deg;

%% Section 5: Assemble Per-Slice Reduction Diagnostics
candidateDiagnostic = result.spaceView.CandidateReductionDiagnostics;
displayedSampleIndex = unique([candidateDiagnostic.SampleIndex], "stable");
displayedSliceCount = numel(displayedSampleIndex);
inputVertexCount = zeros(displayedSliceCount, 1);
geometricCandidateCount = zeros(displayedSliceCount, 1);
activeCandidateCount = zeros(displayedSliceCount, 1);
regionCount = zeros(displayedSliceCount, 1);
candidateReductionPercent = zeros(displayedSliceCount, 1);
relevanceReductionPercent = zeros(displayedSliceCount, 1);
for displayedIndex = 1:displayedSliceCount
    onSlice = [candidateDiagnostic.SampleIndex] == ...
        displayedSampleIndex(displayedIndex);
    inputVertexCount(displayedIndex) = sum( ...
        [candidateDiagnostic(onSlice).InputVertexCount]);
    geometricCandidateCount(displayedIndex) = sum( ...
        [candidateDiagnostic(onSlice).SelectedCandidateCount]);
    activeCandidateCount(displayedIndex) = sum( ...
        [candidateDiagnostic(onSlice).GraphActiveCandidateCount]);
    regionCount(displayedIndex) = nnz(onSlice);
    candidateReductionPercent(displayedIndex) = 100 * max(0, ...
        1 - geometricCandidateCount(displayedIndex) / ...
        inputVertexCount(displayedIndex));
    if geometricCandidateCount(displayedIndex) > 0
        relevanceReductionPercent(displayedIndex) = 100 * max(0, ...
            1 - activeCandidateCount(displayedIndex) / ...
            geometricCandidateCount(displayedIndex));
    end
end
visibilityGraph = result.spaceView.VisibilityGraphs;
result.SliceReductionDiagnostics = table( ...
    displayedSampleIndex(:), obstacleTime_s(displayedSampleIndex), ...
    inputVertexCount, geometricCandidateCount, activeCandidateCount, ...
    regionCount, candidateReductionPercent, relevanceReductionPercent, ...
    reshape([visibilityGraph.GeneratedVisibilityEdgeCount], [], 1), ...
    reshape([visibilityGraph.GeneratedBoundaryEdgeCount], [], 1), ...
    reshape([visibilityGraph.BoundaryRouteInputVertexCount], [], 1), ...
    reshape([visibilityGraph.BoundaryRouteRetainedVertexCount], [], 1), ...
    reshape([visibilityGraph.BoundaryRouteVertexReductionPercent], [], 1), ...
    'VariableNames', { ...
    'SampleIndex','Time_s','InputVertexCount','GeometricCandidateCount', ...
    'ActiveCandidateCount','RegionCount','CandidateReductionPercent', ...
    'RelevanceReductionPercent', ...
    'VisibilityEdgeCount','BoundaryEdgeCount', ...
    'BoundaryRouteInputVertexCount','BoundaryRouteRetainedVertexCount', ...
    'BoundaryRouteReductionPercent'});

%% Section 6: Validate Shape Independence, Bounds & The Plan
if ~result.Success || ~result.Validation.Passed
    error("exampleMovingDeformingUSOutlineVisibility:PlanningFailed", ...
        "Moving-U.S. validation failed. Plots remain open. %s", ...
        result.Message);
end
if ~any(result.directBlocked)
    error("exampleMovingDeformingUSOutlineVisibility:" + ...
        "DirectRouteNotBlocked", ...
        "The direct route should be blocked during the moving scenario.");
end
candidateBoundPerRegion = options.ExtremeDirectionCount + ...
    2 * options.MaximumTangenciesPerReference;
if any(geometricCandidateCount > regionCount * candidateBoundPerRegion)
    error("exampleMovingDeformingUSOutlineVisibility:" + ...
        "CandidateBoundExceeded", ...
        "A slice exceeded its region-scaled candidate bound.");
end
shapeActuallyChanges = range(sliceArea_deg2) > 1e-3 && ...
    range(sliceAspectRatio) > 1e-4;
centroidActuallyMoves = any(range(sliceCentroid_deg, 1) > 1e-3);
if ~shapeActuallyChanges || ~centroidActuallyMoves
    error("exampleMovingDeformingUSOutlineVisibility:" + ...
        "ScenarioDidNotDeform", ...
        "The example must change both slice shape and position.");
end
fprintf( ...
    "Moving U.S. slices: %d, raw vertices/slice: %d\n" + ...
    "Geometric candidates/slice: %s\n" + ...
    "Route-relevant candidates/slice: %s\n" + ...
    "Candidate reduction/slice (%%): %s\n" + ...
    "Boundary command vertices raw/retained: %d/%d\n", ...
    sliceCount, result.RawVertexCountPerSlice(1), ...
    mat2str(geometricCandidateCount.'), ...
    mat2str(activeCandidateCount.'), ...
    mat2str(candidateReductionPercent.', 4), ...
    sum(result.SliceReductionDiagnostics.BoundaryRouteInputVertexCount), ...
    sum(result.SliceReductionDiagnostics.BoundaryRouteRetainedVertexCount));
end

function [largestX, largestY] = largestFiniteRing(x, y)
%% Section 0: Header & Readme
% Extract the largest finite boundary ring and discard holes/islands.
x = double(x(:));
y = double(y(:));
finiteRows = isfinite(x) & isfinite(y);
changes = diff([false; finiteRows; false]);
ringStart = find(changes == 1);
ringStop = find(changes == -1) - 1;
if isempty(ringStart)
    error("exampleMovingDeformingUSOutlineVisibility:EmptyOutline", ...
        "The state union did not produce a finite exterior boundary.");
end
ringArea = zeros(numel(ringStart), 1);
for ringIndex = 1:numel(ringStart)
    rows = ringStart(ringIndex):ringStop(ringIndex);
    ringArea(ringIndex) = abs(polyarea(x(rows), y(rows)));
end
[~, largestRingIndex] = max(ringArea);
rows = ringStart(largestRingIndex):ringStop(largestRingIndex);
largestX = x(rows);
largestY = y(rows);
if largestX(1) == largestX(end) && largestY(1) == largestY(end)
    largestX(end) = [];
    largestY(end) = [];
end
end
