function result = example06RlDynamicSafeIntervals(showFigure)
%% Section 0: Header & Readme
% SYNTAX
%   result = example06RlDynamicSafeIntervals()
%   result = example06RlDynamicSafeIntervals(showFigure)
%**************************************************************************
% PURPOSE
%   - Replay the RL branch's two independently moving wall volumes.
%**************************************************************************
% INPUTS
%   - showFigure (optional logical scalar, default false)
%**************************************************************************
% OUTPUTS
%   - result (scalar planner result)
%**************************************************************************
% UNITS
%   - Angles are degrees and time is seconds.

if nargin < 1
    showFigure = false;
end

%% Section 1: Sample The Imported Moving Obstacles
time_s = (0:30).';
wallAzimuth_deg = cell(numel(time_s), 1);
wallElevation_deg = cell(numel(time_s), 1);
lowerAzimuth_deg = cell(numel(time_s), 1);
lowerElevation_deg = cell(numel(time_s), 1);
for sampleIndex = 1:numel(time_s)
    wallAzimuth_deg{sampleIndex} = [-1; 1; 1; -1; -1];
    wallElevation_deg{sampleIndex} = ...
        0.45 .* sin(time_s(sampleIndex) ./ 4) + ...
        [-2; -2; 2; 2; -2];
    lowerAzimuth_deg{sampleIndex} = [2; 4; 4; 2; 2];
    lowerElevation_deg{sampleIndex} = ...
        -3.2 + 0.35 .* cos(time_s(sampleIndex) ./ 5) + ...
        [-1; -1; 1; 1; -1];
end
azElData = { ...
    makeAzElObstacleData("Oscillating center wall", time_s, ...
        wallAzimuth_deg, wallElevation_deg)
    makeAzElObstacleData("Moving lower wall", time_s, ...
        lowerAzimuth_deg, lowerElevation_deg)};

%% Section 2: Define The Imported Mission
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-6, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
goal = struct( ...
    "type", "fixed", ...
    "time_s", 30, ...
    "position_deg", [6, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-12, 12], ...
    "elevation_deg", [-6, 6], ...
    "maxVelocity_deg_s", [2, 2], ...
    "maxAcceleration_deg_s2", [1, 1]);
request = struct( ...
    "obstacles", {azElData}, ...
    "initialState", initialState, ...
    "goal", goal, ...
    "limits", limits, ...
    "options", struct("safetyMargin_deg", 0.15, "deadline_s", 30));

%% Section 3: Plan & Independently Validate
result = planAzElAvoidance(request);
assert(result.success, "%s", char(join(result.message)));
validation = validateAzElCommand( ...
    result.command, request, result.arrivalTime_s);
assert(validation.isValid, "%s", char(join(validation.message)));
assert(validation.collision.minimumClearance_deg > 0.15, ...
    "The moving-wall command did not clear its required margin.");

%% Section 4: Report & Optionally Display
fprintf("RL moving walls: %.6f s; clearance %.6f deg.\n", ...
    result.arrivalTime_s, validation.collision.minimumClearance_deg);
if showFigure
    visualizeAzElPlan(request, result);
end
end
