function result = exampleOpeningUShapedAzElTimeSpace(options)
%% Section 0: Header & Readme
% SYNTAX
%   result = exampleOpeningUShapedAzElTimeSpace()
%   result = exampleOpeningUShapedAzElTimeSpace(options)
%**************************************************************************
% PURPOSE
%   - Demonstrate that the maintained planner can wait for a timed opening
%     through one U-shaped obstacle instead of taking a slower detour.
%**************************************************************************
% INPUTS
%   - options (scalar struct, optional; default struct())
%       Planner/display overrides plus the finite MaxJerk_deg_s3 limit.
%**************************************************************************
% OUTPUTS
%   - result (scalar planner-result struct)
%       Validated motion plus opening geometry, timing, and comparison
%       against the feasible closed-U route considered in the same call.
%**************************************************************************
% UNITS
%   - Position is degrees; time is seconds; derivatives use deg/s,
%     deg/s^2, and deg/s^3.
%**************************************************************************

%% Section 1: Resolve Example Controls

if nargin < 1 || isempty(options)
    options = struct();
end
[options, jerkConfiguration] = resolveAzElExampleOptions( ...
    options, struct( ...
    "CollisionTimePaddingSamples", 0, ...
    "Verbose", true, ...
    "FigureVisible", "on", ...
    "Title", "U-shaped obstacle opening after 7 seconds"), ...
    [2.5 2.5]);

%% Section 2: Create Obstacles

missionEndTime_s = 120;
openingTime_s = 7;
transitionHalfWidth_s = 1e-3;
safetyMargin_deg = 0.20;
gapHalfWidth_deg = 1.5;

closedBoundary_deg = [ ...
    -8,  7; -5,  7; -5, -4; 5, -4; ...
     5,  7;  8,  7;  8, -7; -8, -7];
leftOpenBoundary_deg = [ ...
    -8, 7; -5, 7; -5, -4; -gapHalfWidth_deg, -4; ...
    -gapHalfWidth_deg, -7; -8, -7];
rightOpenBoundary_deg = [ ...
     5, 7; 8, 7; 8, -7; gapHalfWidth_deg, -7; ...
     gapHalfWidth_deg, -4; 5, -4];
openBoundary_deg = [ ...
    leftOpenBoundary_deg; NaN NaN; rightOpenBoundary_deg];
obstacleTime_s = [ ...
    0; openingTime_s - transitionHalfWidth_s; ...
    openingTime_s + transitionHalfWidth_s; missionEndTime_s];
% These paired samples place the nearest-slice transition exactly at
% openingTime_s. CollisionTimePaddingSamples is zero because this is a
% known discrete event, not uncertain sampled obstacle motion.
azimuthByTime_deg = { ...
    closedBoundary_deg(:, 1); closedBoundary_deg(:, 1); ...
    openBoundary_deg(:, 1); openBoundary_deg(:, 1)};
elevationByTime_deg = { ...
    closedBoundary_deg(:, 2); closedBoundary_deg(:, 2); ...
    openBoundary_deg(:, 2); openBoundary_deg(:, 2)};
obstacles = makeAzElObstacleData( ...
    "U-shaped obstacle with timed gap", obstacleTime_s, ...
    azimuthByTime_deg, elevationByTime_deg, safetyMargin_deg, ...
    struct("Verbose", options.Verbose));

%% Section 3: Create Planner Inputs

initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [0 0], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
goalState = struct( ...
    "time_s", missionEndTime_s, ...
    "position_deg", [0 -10], ...
    "velocity_deg_s", [0 0], ...
    "acceleration_deg_s2", [0 0]);
limits = struct( ...
    "maxVelocity_deg_s", [2 2], ...
    "maxAcceleration_deg_s2", [0.75 0.75], ...
    "maxJerk_deg_s3", jerkConfiguration.MaxJerk_deg_s3);

%% Section 4: Run Planner

result = planAzElMotion( ...
    obstacles, initialState, goalState, limits, options);

%% Section 5: Validate Result

exampleValidation = validateAzElExampleResult( ...
    result, "opening U", struct());
openingValidation = validateOpeningChoice( ...
    result, openingTime_s, gapHalfWidth_deg, safetyMargin_deg);
exampleValidation.Passed = ...
    exampleValidation.Passed && openingValidation.Passed;
if ~openingValidation.Passed
    exampleValidation.Message = exampleValidation.Message + " " + ...
        openingValidation.Message;
end

%% Section 6: Plot Diagnostics And Motion

result.PlotHandles = struct();
if jerkConfiguration.PlotOutputs
    result.PlotHandles = plotAzElMotion( ...
        result, jerkConfiguration.PlotOptions);
end

%% Section 7: Return Example Metadata

result.ExampleValidation = exampleValidation;
result.OpeningValidation = openingValidation;
result.openingTime_s = openingTime_s;
result.obstacleTime_s = obstacleTime_s;
result.closedUBoundary_deg = closedBoundary_deg;
result.openUBoundary_deg = openBoundary_deg;
result.gapHalfWidth_deg = gapHalfWidth_deg;
result.ExampleConfiguration = jerkConfiguration;
end

%% Section 8: Local Functions

function validation = validateOpeningChoice( ...
        result, openingTime_s, gapHalfWidth_deg, safetyMargin_deg)
% PURPOSE
%   - Verify integrated waiting, timed-gap use, and the detour comparison.
selectedRouteLength_deg = NaN;
directRouteLength_deg = norm( ...
    result.goalState.position_deg - result.initialState.position_deg);
openingArrivalTime_s = NaN;
aroundArrivalTime_s = NaN;
waitedUntilOpening = false;
delayedDeparture = false;
selectedDirectGeometry = false;
crossedOpenGap = false;
openingWasFaster = false;

if result.Success
    selectedStep_deg = diff(result.selectedRoute_deg, 1, 1);
    selectedRouteLength_deg = sum(hypot( ...
        selectedStep_deg(:, 1), selectedStep_deg(:, 2)));
    openingArrivalTime_s = result.goalLineInterceptTime_s;
    selectedDirectGeometry = abs( ...
        selectedRouteLength_deg - directRouteLength_deg) <= 1e-8;

    position_deg = result.timedSlopePath.position_deg;
    time_s = result.timedSlopePath.time_s;
    beforeOpening = time_s <= openingTime_s;
    stayedBeforeClosedBarrier = any(beforeOpening) && all( ...
        position_deg(beforeOpening, 2) >= ...
        -4 + safetyMargin_deg - 1e-7);
    waitedUntilOpening = stayedBeforeClosedBarrier;
    crossesBottomBar = position_deg(:, 2) <= -4 + safetyMargin_deg & ...
        position_deg(:, 2) >= -7 - safetyMargin_deg;
    protectedGapHalfWidth_deg = gapHalfWidth_deg - safetyMargin_deg;
    crossedOpenGap = any(crossesBottomBar & ...
        abs(position_deg(:, 1)) < protectedGapHalfWidth_deg & ...
        time_s > openingTime_s);
end

candidate = result.SearchDiagnostics.CandidateOptimizations;
isClosedDetour = false(numel(candidate), 1);
uncertifiedDetourCount = 0;
for candidateIndex = 1:numel(candidate)
    route_deg = candidate(candidateIndex).SeedRoute_deg;
    isLongerThanDirect = candidate(candidateIndex).SeedRouteCost_deg > ...
        directRouteLength_deg + 1e-8;
    hasFiniteArrival = isfinite( ...
        candidate(candidateIndex).ObjectiveArrivalTime_s);
    isCertifiedFeasible = candidate(candidateIndex).Success && ...
        candidate(candidateIndex).Validation.Passed && ...
        candidate(candidateIndex).CollisionFree && ...
        candidate(candidateIndex).CollisionSafetyProven;
    routeBlockedWhenClosed = true;
    if size(route_deg, 1) >= 2
        routeCollision = queryAzElTimedPathCollision( ...
            result.obstacleField, result.initialState.time_s, ...
            route_deg, struct("BoundaryIsOccupied", false));
        routeBlockedWhenClosed = any(routeCollision);
    end
    isDetourComparator = isLongerThanDirect && hasFiniteArrival && ...
        ~routeBlockedWhenClosed;
    uncertifiedDetourCount = uncertifiedDetourCount + ...
        double(isDetourComparator && ~isCertifiedFeasible);
    isClosedDetour(candidateIndex) = isDetourComparator && ...
        isCertifiedFeasible;
end
if any(isClosedDetour)
    aroundArrivalTime_s = min( ...
        [candidate(isClosedDetour).ObjectiveArrivalTime_s]);
    openingWasFaster = openingArrivalTime_s < aroundArrivalTime_s;
end

passed = result.Success && waitedUntilOpening && ...
    selectedDirectGeometry && crossedOpenGap && openingWasFaster;
if passed
    message = sprintf( ...
        "Integrated waiting stayed above the closed barrier until " + ...
        "%.3f s and arrived %.3f s before detouring. Excluded %d " + ...
        "uncertified detour candidates.", openingTime_s, ...
        aroundArrivalTime_s - openingArrivalTime_s, ...
        uncertifiedDetourCount);
else
    message = sprintf( ...
        "Opening choice failed: waited=%d, direct=%d, gap=%d, " + ...
        "faster=%d, opening arrival=%.6g s, detour arrival=%.6g s.", ...
        waitedUntilOpening, selectedDirectGeometry, crossedOpenGap, ...
        openingWasFaster, openingArrivalTime_s, aroundArrivalTime_s);
end
validation = struct( ...
    "Passed", passed, ...
    "Message", string(message), ...
    "WaitedUntilOpening", waitedUntilOpening, ...
    "DelayedDeparture", delayedDeparture, ...
    "StayedBeforeClosedBarrier", waitedUntilOpening, ...
    "SelectedDirectGeometry", selectedDirectGeometry, ...
    "CrossedOpenGap", crossedOpenGap, ...
    "OpeningWasFasterThanDetour", openingWasFaster, ...
    "OpeningTime_s", openingTime_s, ...
    "MotionStartTime_s", result.timedSlopePath.MotionStartTime_s, ...
    "OpeningArrivalTime_s", openingArrivalTime_s, ...
    "ClosedUDetourArrivalTime_s", aroundArrivalTime_s, ...
    "CertifiedClosedUDetourCount", nnz(isClosedDetour), ...
    "UncertifiedDetourCount", uncertifiedDetourCount, ...
    "TimeSaved_s", aroundArrivalTime_s - openingArrivalTime_s, ...
    "SelectedRouteLength_deg", selectedRouteLength_deg, ...
    "DirectRouteLength_deg", directRouteLength_deg);
end
