function result = example02StaticDetour(showFigure)
%% Section 0: Header & Readme
% SYNTAX
%   result = example02StaticDetour()
%   result = example02StaticDetour(showFigure)
%**************************************************************************
% PURPOSE
%   - Demonstrate a smooth validated detour around a static exclusion region.
%**************************************************************************
% INPUTS
%   - showFigure (optional logical scalar, default false)
%       Affects display only and is never passed into planning.
%**************************************************************************
% OUTPUTS
%   - result (scalar planner result)
%**************************************************************************
% UNITS
%   - Angles are degrees and time is seconds.

if nargin < 1
    showFigure = false;
end

%% Section 1: Build Canonical Obstacle Data
azElData = makeAzElObstacleData( ...
    "central exclusion", [0; 30], [-5; 5; 5; -5], ...
    [-5; -5; 5; 5]);
initialState = struct( ...
    "time_s", 0, ...
    "position_deg", [-20, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
goal = struct( ...
    "type", "fixed", ...
    "time_s", NaN, ...
    "position_deg", [20, 0], ...
    "velocity_deg_s", [0, 0], ...
    "acceleration_deg_s2", [0, 0]);
limits = struct( ...
    "azimuth_deg", [-60, 60], ...
    "elevation_deg", [-30, 30], ...
    "maxVelocity_deg_s", [12, 12], ...
    "maxAcceleration_deg_s2", [8, 8]);
missionOptions = struct( ...
    "safetyMargin_deg", 1, ...
    "deadline_s", 30);
request = struct( ...
    "obstacles", azElData, ...
    "initialState", initialState, ...
    "goal", goal, ...
    "limits", limits, ...
    "options", missionOptions);

%% Section 2: Plan & Independently Validate
result = planAzElAvoidance(request);
assert(result.success, result.message);
validation = validateAzElCommand( ...
    result.command, request, result.arrivalTime_s);
assert(validation.isValid, validation.message);
assert(validation.motion.minimumInteriorSpeed_deg_s > 0, ...
    "The safe interior turn must carry positive velocity.");

%% Section 3: Report & Optionally Display
fprintf("Static-scene arrival: %.6f s; clearance: %.6f deg\n", ...
    result.arrivalTime_s, validation.collision.minimumClearance_deg);
if showFigure
    visualizeAzElPlan(request, result);
end
end
