function [plannerOptions, jerkConfiguration] = ...
        resolveAzElExampleOptions(optionOverrides, plannerDefaults, ...
        defaultMaxJerk_deg_s3)
%% Section 0: Header & Readme
% SYNTAX
%   [plannerOptions, jerkConfiguration] = ...
%       resolveAzElExampleOptions(overrides, plannerDefaults, defaultJerk)
%**************************************************************************
% PURPOSE
%   - Give every maintained example one uniform jerk on/off interface.
%   - Keep example-only controls out of planAzElMotion options because jerk
%     is a physical limit, not a display or search option.
%   - Default every example to visible az/el planning, animation, and
%     kinematic figures while preserving explicit headless overrides.
%**************************************************************************
% EXAMPLE-ONLY OPTION FIELDS
%   - EnableJerkConstraint (logical scalar; default true)
%   - MaxJerk_deg_s3 (positive finite scalar or two-element vector)
%   - FigureVisible ("on" or "off"; default "on")
%   - PlotOutputs (logical scalar; default true)
%   - Title (scalar text)
%   - ShowAnimation and ShowKinematicPlot (logical scalars)
%**************************************************************************
% OUTPUTS
%   - plannerOptions (scalar struct)
%       Options safe to pass directly to planAzElMotion.
%   - jerkConfiguration (scalar struct)
%       JerkConstraintEnabled and MaxJerk_deg_s3 resolved for limits.
%**************************************************************************
% UNITS
%   - Jerk is degrees per second cubed.
if nargin < 1 || isempty(optionOverrides)
    optionOverrides = struct();
end
if nargin < 2 || isempty(plannerDefaults)
    plannerDefaults = struct();
end
if nargin < 3 || isempty(defaultMaxJerk_deg_s3)
    defaultMaxJerk_deg_s3 = [2.5 2.5];
end
if ~isstruct(optionOverrides) || ~isscalar(optionOverrides) || ...
        ~isstruct(plannerDefaults) || ~isscalar(plannerDefaults)
    error("resolveAzElExampleOptions:InvalidOptions", ...
        "Overrides and plannerDefaults must be scalar structs.");
end

enableJerkConstraint = true;
if isfield(optionOverrides, "EnableJerkConstraint") && ...
        ~isempty(optionOverrides.EnableJerkConstraint)
    enableValue = optionOverrides.EnableJerkConstraint;
    validateattributes(enableValue, {'logical','numeric'}, ...
        {'real','finite','scalar'});
    if isnumeric(enableValue) && enableValue ~= 0 && enableValue ~= 1
        error("resolveAzElExampleOptions:InvalidEnableJerkConstraint", ...
            "EnableJerkConstraint must be logical or numeric 0 or 1.");
    end
    enableJerkConstraint = logical( ...
        enableValue);
end
maxJerk_deg_s3 = defaultMaxJerk_deg_s3;
if isfield(optionOverrides, "MaxJerk_deg_s3") && ...
        ~isempty(optionOverrides.MaxJerk_deg_s3)
    maxJerk_deg_s3 = optionOverrides.MaxJerk_deg_s3;
end
validateattributes(maxJerk_deg_s3, {'numeric'}, ...
    {'real','finite','positive','nonempty'});
if ~isscalar(maxJerk_deg_s3) && numel(maxJerk_deg_s3) ~= 2
    error("resolveAzElExampleOptions:InvalidMaxJerk", ...
        "MaxJerk_deg_s3 must be scalar or two-element.");
end
maxJerk_deg_s3 = reshape(double(maxJerk_deg_s3), 1, []);
if isscalar(maxJerk_deg_s3)
    maxJerk_deg_s3 = repmat(maxJerk_deg_s3, 1, 2);
end

figureVisible = fieldValue(optionOverrides, plannerDefaults, ...
    "FigureVisible", "on");
figureVisible = lower(string(figureVisible));
if ~isscalar(figureVisible) || ~any(figureVisible == ["on" "off"])
    error("resolveAzElExampleOptions:InvalidFigureVisible", ...
        "FigureVisible must be on or off.");
end
plotOutputs = fieldValue(optionOverrides, plannerDefaults, ...
    "PlotOutputs", true);
validateattributes(plotOutputs, {'logical','numeric'}, ...
    {'real','finite','scalar'});
plotOutputs = logical(plotOutputs);
titleText = string(fieldValue(optionOverrides, plannerDefaults, ...
    "Title", "Azimuth/elevation motion plan"));
if ~isscalar(titleText)
    error("resolveAzElExampleOptions:InvalidTitle", ...
        "Title must be scalar text.");
end
showAnimation = logicalExampleControl(fieldValue( ...
    optionOverrides, plannerDefaults, "ShowAnimation", true), ...
    "ShowAnimation");
showKinematics = logicalExampleControl(fieldValue( ...
    optionOverrides, plannerDefaults, "ShowKinematicPlot", true), ...
    "ShowKinematicPlot");
showSweptSurfaces = logicalExampleControl(fieldValue( ...
    optionOverrides, plannerDefaults, "ShowSweptSurfaces", true), ...
    "ShowSweptSurfaces");
plotOptions = struct( ...
    "FigureVisible", figureVisible, "Title", titleText, ...
    "ShowAnimation", showAnimation, ...
    "ShowKinematics", showKinematics, ...
    "FrameStride", fieldValue(optionOverrides, plannerDefaults, ...
        "AnimationFrameStride", 10), ...
    "Pause_s", fieldValue(optionOverrides, plannerDefaults, ...
        "AnimationPause_s", 0.001), ...
    "ShowSweptSurfaces", showSweptSurfaces, ...
    "MaximumDisplayedSlicesPerObstacle", fieldValue( ...
        optionOverrides, plannerDefaults, ...
        "MaximumDisplayedSlicesPerObstacle", 30));

plannerSupported = string(fieldnames(planAzElMotion()));
plannerOptions = struct();
defaultNames = intersect(string(fieldnames(plannerDefaults)), ...
    plannerSupported, "stable");
for index = 1:numel(defaultNames)
    name = defaultNames(index);
    plannerOptions.(name) = plannerDefaults.(name);
end
exampleOnlyNames = ["EnableJerkConstraint" "MaxJerk_deg_s3" ...
    "FigureVisible" "PlotOutputs" "Title" "ShowAnimation" ...
    "ShowKinematicPlot" "ShowSweptSurfaces" ...
    "AnimationFrameStride" "AnimationPause_s" ...
    "MaximumDisplayedSlicesPerObstacle" "MotionType" "UseParallel"];
overrideNames = setdiff(string(fieldnames(optionOverrides)), ...
    exampleOnlyNames, "stable");
for index = 1:numel(overrideNames)
    name = overrideNames(index);
    if any(name == plannerSupported) && ~isempty(optionOverrides.(name))
        plannerOptions.(name) = optionOverrides.(name);
    end
end
resolvedJerk_deg_s3 = [Inf Inf];
if enableJerkConstraint
    resolvedJerk_deg_s3 = maxJerk_deg_s3;
end
jerkConfiguration = struct( ...
    "JerkConstraintEnabled", enableJerkConstraint, ...
    "MaxJerk_deg_s3", resolvedJerk_deg_s3, ...
    "ConfiguredFiniteMaxJerk_deg_s3", maxJerk_deg_s3, ...
    "FigureVisible", figureVisible, ...
    "PlotOutputs", plotOutputs, ...
    "Title", titleText, ...
    "ShowAnimation", showAnimation, ...
    "ShowKinematicPlot", showKinematics, ...
    "PlotOptions", plotOptions);
end

function value = fieldValue(overrides, defaults, name, fallback)
%% Section 0: Header & Readme
% Resolve one example-only control without passing it to the planner.
value = fallback;
if isfield(defaults, name) && ~isempty(defaults.(name))
    value = defaults.(name);
end
if isfield(overrides, name) && ~isempty(overrides.(name))
    value = overrides.(name);
end
end

function value = logicalExampleControl(value, name)
%% Section 0: Header & Readme
% Validate one example-only logical display control.
if ~(islogical(value) && isscalar(value)) && ...
        ~(isnumeric(value) && isscalar(value) && ...
        isfinite(value) && any(value == [0 1]))
    error("resolveAzElExampleOptions:InvalidLogicalControl", ...
        "%s must be scalar logical or binary numeric.", name);
end
value = logical(value);
end
