function [plannerOptions, jerkConfiguration] = ...
        resolveAzElExampleOptions(optionOverrides, plannerDefaults, ...
        defaultMaxJerk_deg_s3)
%% Section 0: Header & Readme
% SYNTAX
%   [plannerOptions, jerkConfiguration] = ...
%       resolveAzElExampleOptions(overrides, plannerDefaults, defaultJerk)
%**************************************************************************
% PURPOSE
%   - Give every maintained example one finite-jerk interface.
%   - Keep the example-only jerk value out of planAzElMotion options because
%     jerk is a physical limit, not a display or search option.
%   - Default every example to visible motion and kinematic figures while
%     keeping deep graph and swept-surface diagnostics optional.
%   - Give maintained examples a finite planning budget while preserving an
%     explicit user override and the planner library's unlimited default.
%**************************************************************************
% INPUTS
%   - optionOverrides (scalar struct, optional; default struct())
%       Example-only controls include MaxJerk_deg_s3, FigureVisible,
%       PlotOutputs, Title, ShowAnimation, ShowKinematicPlot, diagnostic
%       plot controls, and display budgets. Planner controls are forwarded
%       when known.
%   - plannerDefaults (scalar struct, optional; default struct())
%       Scenario defaults for planner and display controls.
%   - defaultMaxJerk_deg_s3 (positive scalar or two-element vector)
%       Finite jerk used when the constraint is enabled; default [2.5 2.5].
%**************************************************************************
% OUTPUTS
%   - plannerOptions (scalar struct)
%       Options safe to pass directly to planAzElMotion.
%   - jerkConfiguration (scalar struct)
%       The required finite MaxJerk_deg_s3 plus display controls.
%**************************************************************************
% UNITS
%   - Jerk is degrees per second cubed.
%**************************************************************************

%% Section 1: Resolve Example Controls

if nargin < 1 || isempty(optionOverrides)
    optionOverrides = struct();
end
if nargin < 2 || isempty(plannerDefaults)
    plannerDefaults = struct();
end
if nargin < 3 || isempty(defaultMaxJerk_deg_s3)
    defaultMaxJerk_deg_s3 = [2.5 2.5];
end
if ~isstruct(optionOverrides) || ~isscalar(optionOverrides) || ...
        ~isstruct(plannerDefaults) || ~isscalar(plannerDefaults)
    error("resolveAzElExampleOptions:InvalidOptions", ...
        "Overrides and plannerDefaults must be scalar structs.");
end

if isfield(optionOverrides, "EnableJerkConstraint")
    error("resolveAzElExampleOptions:RemovedJerkToggle", ...
        "EnableJerkConstraint was removed on this finite-jerk-only " + ...
        "branch. Use MaxJerk_deg_s3 to set the required finite limit.");
end
maxJerk_deg_s3 = defaultMaxJerk_deg_s3;
if isfield(optionOverrides, "MaxJerk_deg_s3") && ...
        ~isempty(optionOverrides.MaxJerk_deg_s3)
    maxJerk_deg_s3 = optionOverrides.MaxJerk_deg_s3;
end
validateattributes(maxJerk_deg_s3, {'numeric'}, ...
    {'real','finite','positive','nonempty'});
if ~isscalar(maxJerk_deg_s3) && numel(maxJerk_deg_s3) ~= 2
    error("resolveAzElExampleOptions:InvalidMaxJerk", ...
        "MaxJerk_deg_s3 must be scalar or two-element.");
end
maxJerk_deg_s3 = reshape(double(maxJerk_deg_s3), 1, []);
if isscalar(maxJerk_deg_s3)
    maxJerk_deg_s3 = repmat(maxJerk_deg_s3, 1, 2);
end

figureVisible = fieldValue(optionOverrides, plannerDefaults, ...
    "FigureVisible", "on");
figureVisible = lower(string(figureVisible));
if ~isscalar(figureVisible) || ~any(figureVisible == ["on" "off"])
    error("resolveAzElExampleOptions:InvalidFigureVisible", ...
        "FigureVisible must be on or off.");
end
plotOutputs = azElInternal.normalizeLogicalScalar(fieldValue( ...
    optionOverrides, plannerDefaults, "PlotOutputs", true), ...
    "PlotOutputs", ...
    "resolveAzElExampleOptions:InvalidLogicalControl");
titleText = string(fieldValue(optionOverrides, plannerDefaults, ...
    "Title", "Azimuth/elevation motion plan"));
if ~isscalar(titleText)
    error("resolveAzElExampleOptions:InvalidTitle", ...
        "Title must be scalar text.");
end
showAnimation = azElInternal.normalizeLogicalScalar(fieldValue( ...
    optionOverrides, plannerDefaults, "ShowAnimation", true), ...
    "ShowAnimation", ...
    "resolveAzElExampleOptions:InvalidLogicalControl");
showKinematics = azElInternal.normalizeLogicalScalar(fieldValue( ...
    optionOverrides, plannerDefaults, "ShowKinematicPlot", true), ...
    "ShowKinematicPlot", ...
    "resolveAzElExampleOptions:InvalidLogicalControl");
showVisibilityGraphs = azElInternal.normalizeLogicalScalar(fieldValue( ...
    optionOverrides, plannerDefaults, "ShowVisibilityGraphs", false), ...
    "ShowVisibilityGraphs", ...
    "resolveAzElExampleOptions:InvalidLogicalControl");
showSweptSurfaces = azElInternal.normalizeLogicalScalar(fieldValue( ...
    optionOverrides, plannerDefaults, "ShowSweptSurfaces", false), ...
    "ShowSweptSurfaces", ...
    "resolveAzElExampleOptions:InvalidLogicalControl");
plotOptions = struct( ...
    "FigureVisible", figureVisible, "Title", titleText, ...
    "ShowAnimation", showAnimation, ...
    "ShowKinematics", showKinematics, ...
    "ShowVisibilityGraphs", showVisibilityGraphs, ...
    "FrameStride", fieldValue(optionOverrides, plannerDefaults, ...
    "AnimationFrameStride", 10), ...
    "MaximumAnimationFrameCount", fieldValue( ...
    optionOverrides, plannerDefaults, "MaximumAnimationFrameCount", 60), ...
    "Pause_s", fieldValue(optionOverrides, plannerDefaults, ...
        "AnimationPause_s", 0.001), ...
    "ShowSweptSurfaces", showSweptSurfaces, ...
    "MaximumDisplayedSlicesPerObstacle", fieldValue( ...
    optionOverrides, plannerDefaults, ...
    "MaximumDisplayedSlicesPerObstacle", 30), ...
    "MaximumDisplayedTotalSlices", fieldValue( ...
    optionOverrides, plannerDefaults, ...
    "MaximumDisplayedTotalSlices", 120), ...
    "MaximumDisplayedVisibilitySnapshots", fieldValue( ...
        optionOverrides, plannerDefaults, ...
        "MaximumDisplayedVisibilitySnapshots", 30));

%% Section 2: Forward Supported Planner Options

plannerSupported = string(fieldnames(planAzElMotion()));
plannerOptions = struct( ...
    "MaximumPlanningTime_s", fieldValue( ...
    optionOverrides, plannerDefaults, "MaximumPlanningTime_s", 90));
defaultNames = intersect(string(fieldnames(plannerDefaults)), ...
    plannerSupported, "stable");
for defaultNameIndex = 1:numel(defaultNames)
    name = defaultNames(defaultNameIndex);
    plannerOptions.(name) = plannerDefaults.(name);
end
exampleOnlyNames = ["MaxJerk_deg_s3" ...
    "FigureVisible" "PlotOutputs" "Title" "ShowAnimation" ...
    "ShowKinematicPlot" "ShowVisibilityGraphs" "ShowSweptSurfaces" ...
    "AnimationFrameStride" "AnimationPause_s" ...
    "MaximumAnimationFrameCount" ...
    "MaximumDisplayedSlicesPerObstacle" ...
    "MaximumDisplayedTotalSlices" ...
    "MaximumDisplayedVisibilitySnapshots"];
recognizedNames = [plannerSupported; exampleOnlyNames(:)];
unknownDefaultNames = setdiff(string(fieldnames(plannerDefaults)), ...
    recognizedNames, "stable");
unknownOverrideNames = setdiff(string(fieldnames(optionOverrides)), ...
    recognizedNames, "stable");
unknownNames = unique([ ...
    unknownDefaultNames(:); unknownOverrideNames(:)], "stable");
if ~isempty(unknownNames)
    warning("resolveAzElExampleOptions:UnknownOptions", ...
        "Ignoring unknown example option fields: %s. No behavior changed.", ...
        strjoin(unknownNames, ", "));
end
overrideNames = intersect(string(fieldnames(optionOverrides)), ...
    plannerSupported, "stable");
for overrideNameIndex = 1:numel(overrideNames)
    name = overrideNames(overrideNameIndex);
    if ~isempty(optionOverrides.(name))
        plannerOptions.(name) = optionOverrides.(name);
    end
end

%% Section 3: Assemble Example Configuration

jerkConfiguration = struct( ...
    "JerkConstraintEnabled", true, ...
    "MaxJerk_deg_s3", maxJerk_deg_s3, ...
    "ConfiguredFiniteMaxJerk_deg_s3", maxJerk_deg_s3, ...
    "FigureVisible", figureVisible, ...
    "PlotOutputs", plotOutputs, ...
    "Title", titleText, ...
    "ShowAnimation", showAnimation, ...
    "ShowKinematicPlot", showKinematics, ...
    "ShowVisibilityGraphs", showVisibilityGraphs, ...
    "PlotOptions", plotOptions);
end

%% Section 4: Local Functions

function value = fieldValue(overrides, defaults, name, fallback)
% PURPOSE
%   - Resolve one example-only control without forwarding it.
value = fallback;
if isfield(defaults, name) && ~isempty(defaults.(name))
    value = defaults.(name);
end
if isfield(overrides, name) && ~isempty(overrides.(name))
    value = overrides.(name);
end
end
