function key = createEndpointValidationKey(preparedObstacles, initialState, goalState, limits, options)
%% Section 0: Header & Readme
% SYNTAX
%   key = obstacleAvoidance.planning.createEndpointValidationKey( ...
%       preparedObstacles, initialState, goalState, limits, options)
%**************************************************************************
% PURPOSE
%   - Record the inputs whose exact match permits endpoint-check reuse.
%**************************************************************************
% INPUTS
%   - preparedObstacles, initialState, goalState, limits, options
%       Prepared geometry and normalized endpoint-check inputs.
%**************************************************************************
% OUTPUTS
%   - key (scalar struct): input record; this does not check feasibility.
%**************************************************************************
% UNITS
%   - Position is coordinate units and time is seconds.
%**************************************************************************

%% Section 1: Record The Endpoint-Check Inputs

key = struct();
key.PreparedObstacles = preparedObstacles;
key.RequestHorizon_s  = [initialState.time_s, goalState.time_s];
key.InitialState = struct( ...
    'time_s',                initialState.time_s, ...
    'position_units',        initialState.position_units, ...
    'velocity_units_s',      initialState.velocity_units_s, ...
    'acceleration_units_s2', initialState.acceleration_units_s2);
key.GoalState = struct( ...
    'time_s',                goalState.time_s, ...
    'position_units',        goalState.position_units, ...
    'velocity_units_s',      goalState.velocity_units_s, ...
    'acceleration_units_s2', goalState.acceleration_units_s2);
key.Limits = limits;
key.Options = struct( ...
    'GoalTimeMode',           options.GoalTimeMode, ...
    'WrapX',                  options.WrapX, ...
    'WrapY',                  options.WrapY, ...
    'ArrivalTimeTolerance_s', options.ArrivalTimeTolerance_s);
end
