function attempt = createAttemptRecord(attemptIndex, methodName)
%% Section 0: Header & Readme
% SYNTAX
%   attempt = obstacleAvoidance.planning.createAttemptRecord(attemptIndex, methodName)
%**************************************************************************
% PURPOSE
%   - Create the standard record for one planning method or arrival trial.
%**************************************************************************
% INPUTS
%   - attemptIndex (nonnegative integer scalar)
%       Position in the attempt history, starting at 1. Use 0 when creating
%       a template for an empty attempt history.
%   - methodName (text scalar)
%       Planning method, such as "spatialVisibility" or "arrivalTimeTrial".
%**************************************************************************
% OUTPUTS
%   - attempt (scalar struct)
%       Standard fields for one attempt, ready for the planner to fill in.
%       CandidateSuccess records BMTP success; Success also requires
%       independent validation. Selected marks the attempt used in the result.
%       ChildAttempts holds the methods run within an arrival-time trial.
%**************************************************************************
% UNITS
%   - Time is seconds and position is coordinate units.
%**************************************************************************

%% Section 1: Create The Attempt Record

% Use the same fields for every attempt so the caller can compare them.
% The planner fills in measurements as each stage runs; values left as NaN
% mean that measurement was not recorded for the attempt.
attempt = struct( ...
    "Index",                       attemptIndex, ...
    "Kind",                        string(methodName), ...
    "IsShortcut",                  false, ...
    "IterationLimit",              NaN, ...
    "GraphSnapshotTime_s",         NaN, ...
    "TrialTime_s",                 NaN, ...
    "CandidateArrival_s",          NaN, ...
    "EarliestPossibleArrival_s",   NaN, ...
    "BestSoFarArrival_s",          NaN, ...
    "GraphConnected",              false, ...
    "GraphIsFullyEnumerated",      false, ...
    "RouteNodeCount",              0, ...
    "RouteLength_units",           Inf, ...
    "ExpandedCount",               0, ...
    "SolverAttempted",             false, ...
    "IterationCount",              0, ...
    "CandidateSuccess",            false, ...
    "OptimizerFeasible",           false, ...
    "OptimizerIterateUnavailable", false, ...
    "AlternativeGuideEligible",    false, ...
    "FailureStage",                "", ...
    "FailureKind",                 "", ...
    "Message",                     "", ...
    "SolverExitFlag",              NaN, ...
    "NextAttemptAllowed",          false, ...
    "NextMethodAllowed",           false, ...
    "NextMethodReason",            "", ...
    "Success",                     false, ...
    "Selected",                    false, ...
    "ElapsedTime_s",               0, ...
    "ChildAttempts",               {repmat(struct(), 0, 1)});
end
