function attempt = createAttemptRecord(index, kind)
%% Section 0: Header & Readme
% SYNTAX
%   attempt = obstacleAvoidance.planning.createAttemptRecord(index, kind)
%**************************************************************************
% PURPOSE
%   - Create one stable planner-level attempt record for a guide proposal.
%**************************************************************************
% INPUTS
%   - index (nonnegative integer scalar)
%       Position of the attempt in the planner attempt history.
%   - kind (text scalar)
%       Declared proposal kind for the attempt.
%**************************************************************************
% OUTPUTS
%   - attempt (scalar struct)
%       Planner-level attempt record initialized to the stable defaults.
%**************************************************************************
% UNITS
%   - Time is seconds and position is coordinate units.
%**************************************************************************

%% Section 1: Create The Attempt Record

% Keep one compact, stable record for every guide proposal.
% Only a retained ineligible timed challenger fills its failure message
% and solver exit flag; every other attempt keeps the declared defaults.
attempt = struct( ...
    "Index",                        index, ...
    "Kind",                         string(kind), ...
    "IsHeuristic",                  false, ...
    "IterationLimit",               NaN, ...
    "GraphSnapshotTime_s",          NaN, ...
    "TrialTime_s",                  NaN, ...
    "CandidateArrival_s",           NaN, ...
    "NecessaryArrivalBound_s",      NaN, ...
    "IncumbentArrival_s",           NaN, ...
    "GraphConnected",               false, ...
    "GraphIsFullyEnumerated",       false, ...
    "RouteNodeCount",               0, ...
    "RouteLength_units",            Inf, ...
    "ExpandedCount",                0, ...
    "SolverAttempted",              false, ...
    "IterationCount",               0, ...
    "CandidateSuccess",             false, ...
    "OptimizerFeasible",            false, ...
    "OptimizerIterateUnavailable",  false, ...
    "AlternativeGuideEligible",     false, ...
    "FailureStage",                 "", ...
    "FailureKind",                  "", ...
    "Message",                      "", ...
    "SolverExitFlag",               NaN, ...
    "FallbackEligible",             false, ...
    "MethodFallbackEligible",       false, ...
    "MethodFallbackReason",         "", ...
    "Success",                      false, ...
    "Selected",                     false, ...
    "ElapsedTime_s",                0, ...
    "ChildAttempts",                {repmat(struct(), 0, 1)});
end
