function solution = optimize(problem, options)
%% Section 0: Header & Readme
% SYNTAX
%   solution = hs3.optimize(problem, options)
%**************************************************************************
% PURPOSE
%   - Execute the shared fixed-time QP or free-time NLP and feasibility
%     recovery without assigning meaning to coordinates or constraints.
%**************************************************************************
% INPUTS
%   - problem (scalar struct)
%       Decision0, LowerBound, UpperBound, TypicalDecision, IsFreeTime,
%       ConstraintFunction, ObjectiveFunction, and ProgressFunction are
%       required. Fixed time also supplies linear matrices, bounds, and
%       Hessian. Free time supplies MaximumFinalTime and may select its
%       interior-point SubproblemAlgorithm.
%   - options (scalar struct)
%       MaximumIterations, MaximumFunctionEvaluations, MaximumSolveTime,
%       ArrivalTimeTolerance, ConstraintTolerance, OptimalityTolerance,
%       StepTolerance, and Verbose are resolved numerical controls.
%**************************************************************************
% OUTPUTS
%   - solution (scalar struct)
%       Stable stage outcomes, selected decision, constraint violations,
%       feasibility state, termination reason, messages, and elapsed time.
%**************************************************************************
% UNITS
%   - Decision, objective, constraint, and time units are caller-defined.
%**************************************************************************

%% Section 1: Validate The Numerical Contract

requiredProblemFields = [ ...
    "Decision0", "LowerBound", "UpperBound", "TypicalDecision", ...
    "IsFreeTime", "ConstraintFunction", "ObjectiveFunction", ...
    "ProgressFunction"];
if ~isstruct(problem) || ~isscalar(problem) || ...
        ~all(isfield(problem, requiredProblemFields))
    error("optimize:InvalidProblem", ...
        "problem must be scalar and contain every documented core field.");
end
requiredOptionFields = [ ...
    "MaximumIterations", "MaximumFunctionEvaluations", ...
    "MaximumSolveTime", "ArrivalTimeTolerance", ...
    "ConstraintTolerance", "OptimalityTolerance", ...
    "StepTolerance", "Verbose"];
if ~isstruct(options) || ~isscalar(options) || ...
        ~all(isfield(options, requiredOptionFields))
    error("optimize:InvalidOptions", ...
        "options must be scalar and contain every documented core field.");
end
decision0 = double(problem.Decision0(:));
lowerBound = double(problem.LowerBound(:));
upperBound = double(problem.UpperBound(:));
typicalDecision = double(problem.TypicalDecision(:));
decisionCount = numel(decision0);
if numel(lowerBound) ~= decisionCount || ...
        numel(upperBound) ~= decisionCount || ...
        numel(typicalDecision) ~= decisionCount || ...
        any(isnan(decision0)) || any(isnan(lowerBound)) || ...
        any(isnan(upperBound)) || any(~isfinite(typicalDecision)) || ...
        any(lowerBound > upperBound)
    error("optimize:InvalidDecisionLayout", ...
        "Decision, bound, and scale columns must have equal valid lengths.");
end
isFreeTime = logical(problem.IsFreeTime);
if ~isscalar(isFreeTime) || ...
        ~isa(problem.ConstraintFunction, "function_handle") || ...
        ~isa(problem.ObjectiveFunction, "function_handle") || ...
        ~isa(problem.ProgressFunction, "function_handle")
    error("optimize:InvalidFunctions", ...
        "IsFreeTime must be scalar and all supplied functions must be handles.");
end
fixedFields = [ ...
    "InequalityMatrix", "InequalityBound", ...
    "EqualityMatrix", "EqualityBound", "Hessian"];
if isFreeTime && ~isfield(problem, "MaximumFinalTime")
    error("optimize:MissingMaximumFinalTime", ...
        "A free-time problem requires MaximumFinalTime.");
elseif ~isFreeTime && ~all(isfield(problem, fixedFields))
    error("optimize:MissingFixedMatrices", ...
        "A fixed-time problem requires matrices, bounds, and Hessian.");
end
solverTimer = tic;
if isfield(problem, "SolverTimer") && ~isempty(problem.SolverTimer)
    solverTimer = problem.SolverTimer;
end

%% Section 2: Execute The Primary Solve

subproblemAlgorithm = "cg";
if isfield(problem, "SubproblemAlgorithm") && ...
        ~isempty(problem.SubproblemAlgorithm)
    subproblemAlgorithm = string(problem.SubproblemAlgorithm);
end
solverOptions = [];
stageOneErrorIdentifier = "";
stageOneErrorMessage = "";
try
    if isFreeTime
        solverOptions = optimoptions("fmincon", ...
            "Algorithm", "interior-point", ...
            "SubproblemAlgorithm", subproblemAlgorithm, ...
            "Display", "none", ...
            "MaxIterations", options.MaximumIterations, ...
            "MaxFunctionEvaluations", ...
            options.MaximumFunctionEvaluations, ...
            "ConstraintTolerance", options.ConstraintTolerance, ...
            "OptimalityTolerance", options.OptimalityTolerance, ...
            "StepTolerance", options.StepTolerance, ...
            "ScaleProblem", true, ...
            "SpecifyObjectiveGradient", true, ...
            "SpecifyConstraintGradient", true, ...
            "TypicalX", typicalDecision, ...
            "OutputFcn", problem.ProgressFunction);
        [stageOneDecision, stageOneObjective, stageOneExitFlag, ...
            stageOneOutput] = fmincon( ...
            problem.ObjectiveFunction, decision0, [], [], [], [], ...
            lowerBound, upperBound, problem.ConstraintFunction, ...
            solverOptions);
    else
        quadraticOptions = optimoptions("quadprog", ...
            "Algorithm", "active-set", ...
            "Display", "none", ...
            "MaxIterations", options.MaximumIterations, ...
            "ConstraintTolerance", options.ConstraintTolerance, ...
            "OptimalityTolerance", options.OptimalityTolerance);
        [stageOneDecision, stageOneObjective, stageOneExitFlag, ...
            stageOneOutput] = quadprog( ...
            problem.Hessian, zeros(decisionCount, 1), ...
            problem.InequalityMatrix, problem.InequalityBound, ...
            problem.EqualityMatrix, problem.EqualityBound, ...
            lowerBound, upperBound, decision0, quadraticOptions);
    end
catch exception
    stageOneDecision = decision0;
    stageOneObjective = Inf;
    stageOneExitFlag = NaN;
    stageOneOutput = struct();
    stageOneErrorIdentifier = string(exception.identifier);
    stageOneErrorMessage = string(exception.message);
end

%% Section 3: Recover Feasibility When Requested

selectedDecision = stageOneDecision;
stageTwoExitFlag = NaN;
stageTwoOutput = struct();
stageTwoObjective = NaN;
stageTwoErrorIdentifier = "";
stageTwoErrorMessage = "";
[finalInequality, finalEquality] = ...
    problem.ConstraintFunction(stageOneDecision);
stageOneViolation = max( ...
    [0; finalInequality(:); abs(finalEquality(:))]);
feasibilityTolerance = max(10 * options.ConstraintTolerance, 1e-7);
if isFreeTime && stageOneViolation > feasibilityTolerance && ...
        toc(solverTimer) < options.MaximumSolveTime
    stageTwoUpperBound = upperBound;
    stageTwoUpperBound(end) = min(problem.MaximumFinalTime, ...
        stageOneDecision(end) + options.ArrivalTimeTolerance);
    recoveryObjective = @zeroObjective;
    if isfield(problem, "RecoveryObjectiveFunction") && ...
            ~isempty(problem.RecoveryObjectiveFunction)
        recoveryObjective = problem.RecoveryObjectiveFunction;
    end
    try
        [trialDecision, stageTwoObjective, stageTwoExitFlag, ...
            stageTwoOutput] = fmincon( ...
            recoveryObjective, stageOneDecision, [], [], [], [], ...
            lowerBound, stageTwoUpperBound, ...
            problem.ConstraintFunction, solverOptions);
        [trialInequality, trialEquality] = ...
            problem.ConstraintFunction(trialDecision);
        trialViolation = max( ...
            [0; trialInequality(:); abs(trialEquality(:))]);
        if trialViolation <= max(options.ConstraintTolerance, stageOneViolation)
            selectedDecision = trialDecision;
            finalInequality = trialInequality;
            finalEquality = trialEquality;
        end
    catch exception
        stageTwoErrorIdentifier = string(exception.identifier);
        stageTwoErrorMessage = string(exception.message);
    end
end

%% Section 4: Assemble The Stable Outcome

maximumInequalityViolation = max([0; finalInequality(:)]);
maximumEqualityViolation = max([0; abs(finalEquality(:))]);
maximumViolation = max( ...
    maximumInequalityViolation, maximumEqualityViolation);
isFeasible = maximumViolation <= feasibilityTolerance;
arrivalAtHorizon = false;
if isFreeTime
    arrivalAtHorizon = isFeasible && selectedDecision(end) >= ...
        problem.MaximumFinalTime - options.ArrivalTimeTolerance;
end
timeLimitReached = toc(solverTimer) >= options.MaximumSolveTime;
if strlength(stageOneErrorIdentifier) > 0
    terminationReason = "solverError";
    message = "HS3 numerical solve failed: " + stageOneErrorMessage;
elseif arrivalAtHorizon
    terminationReason = "arrivalAtHorizon";
    message = "HS3 returned a feasible decision at the time horizon.";
elseif isFeasible
    terminationReason = "optimizerFeasible";
    message = "HS3 returned a constraint-feasible local solution.";
elseif timeLimitReached
    terminationReason = "solverTimeLimit";
    message = "HS3 reached its solve-time limit before feasibility.";
else
    terminationReason = "optimizerInfeasible";
    message = "HS3 did not satisfy all optimization constraints.";
end
solution = struct( ...
    "Success", isFeasible && ~arrivalAtHorizon, ...
    "OptimizerFeasible", isFeasible, ...
    "ArrivalAtHorizon", arrivalAtHorizon, ...
    "Message", message, ...
    "TerminationReason", terminationReason, ...
    "Decision", selectedDecision, ...
    "StageOneObjective", stageOneObjective, ...
    "StageTwoObjective", stageTwoObjective, ...
    "StageOneExitFlag", stageOneExitFlag, ...
    "StageTwoExitFlag", stageTwoExitFlag, ...
    "StageOneOutput", stageOneOutput, ...
    "StageTwoOutput", stageTwoOutput, ...
    "StageOneErrorIdentifier", stageOneErrorIdentifier, ...
    "StageOneErrorMessage", stageOneErrorMessage, ...
    "StageTwoErrorIdentifier", stageTwoErrorIdentifier, ...
    "StageTwoErrorMessage", stageTwoErrorMessage, ...
    "MaximumInequalityViolation", maximumInequalityViolation, ...
    "MaximumEqualityViolation", maximumEqualityViolation, ...
    "MaximumConstraintViolation", maximumViolation, ...
    "ElapsedTime", toc(solverTimer));
end

%% Section 5: Local Functions

function [value, gradient] = zeroObjective(decision)
%% Section 0: Header & Readme
% SYNTAX
%   [value, gradient] = zeroObjective(decision)
%**************************************************************************
% PURPOSE
%   - Request pure feasibility with an exact zero gradient.
%**************************************************************************
% INPUTS
%   - decision (numeric column), current decision.
%**************************************************************************
% OUTPUTS
%   - value (scalar zero), gradient (zero column).
%**************************************************************************
% UNITS
%   - Not applicable.
%**************************************************************************
value = 0;
gradient = zeros(size(decision));
end
