function validation = validate(trajectory)
%% Section 0: Header & Readme
% SYNTAX
%   validation = hs3.validate(trajectory)
%**************************************************************************
% PURPOSE
%   - Independently validate standalone HS3 endpoints and complete
%     continuous kinematic and affine path constraints.
%**************************************************************************
% INPUTS
%   - trajectory (scalar hs3.solve result)
%       Must contain reconstructed motion, polynomial, inputs, and options.
%**************************************************************************
% OUTPUTS
%   - validation (scalar struct)
%       Stable pass state, message, endpoint errors, constraint violations,
%       finiteness, and strictly increasing time evidence.
%**************************************************************************
% UNITS
%   - Values retain caller-defined consistent coordinate and time units.
%**************************************************************************

%% Section 1: Validate Histories And Endpoints

requiredFields = [ ...
    "time", "position", "velocity", "acceleration", "jerk", ...
    "ControlJerk", "Polynomial", "Inputs", "Options", "FinalTime"];
if ~isstruct(trajectory) || ~isscalar(trajectory) || ...
        ~all(isfield(trajectory, requiredFields))
    error("validate:InvalidTrajectory", ...
        "trajectory must be a scalar hs3.solve result.");
end
initialState = trajectory.Inputs.initialState;
terminalState = trajectory.Inputs.terminalState;
limits = trajectory.Inputs.limits;
pathConstraints = trajectory.Inputs.pathConstraints;
options = trajectory.Options;
historyIsFinite = ~isempty(trajectory.time) && ...
    all(isfinite(trajectory.time)) && ...
    all(isfinite(trajectory.position), "all") && ...
    all(isfinite(trajectory.velocity), "all") && ...
    all(isfinite(trajectory.acceleration), "all") && ...
    all(isfinite(trajectory.jerk), "all");
timeIsStrictlyIncreasing = numel(trajectory.time) >= 2 && ...
    all(diff(trajectory.time) > 0);
if historyIsFinite
    initialPositionError = max(abs( ...
        trajectory.position(1, :) - initialState.position));
    initialVelocityError = max(abs( ...
        trajectory.velocity(1, :) - initialState.velocity));
    initialAccelerationError = max(abs( ...
        trajectory.acceleration(1, :) - initialState.acceleration));
    terminalPositionError = max(abs( ...
        trajectory.position(end, :) - terminalState.position));
    terminalVelocityError = max(abs( ...
        trajectory.velocity(end, :) - terminalState.velocity));
    terminalAccelerationError = max(abs( ...
        trajectory.acceleration(end, :) - terminalState.acceleration));
else
    initialPositionError = Inf;
    initialVelocityError = Inf;
    initialAccelerationError = Inf;
    terminalPositionError = Inf;
    terminalVelocityError = Inf;
    terminalAccelerationError = Inf;
end

%% Section 2: Reevaluate Complete Continuous Constraints

decision = trajectory.ControlJerk(:);
[inequality, equality] = hs3.evaluateConstraints( ...
    decision, false, trajectory.FinalTime, trajectory.FinalTime, ...
    trajectory.FinalTime, options.SegmentCount, initialState, ...
    terminalState, limits, pathConstraints);
maximumInequalityViolation = max([0; inequality(:)]);
maximumEqualityViolation = max([0; abs(equality(:))]);
tolerance = max(10 * options.ConstraintTolerance, 1e-7);
endpointErrors = [ ...
    initialPositionError, initialVelocityError, initialAccelerationError, ...
    terminalPositionError, terminalVelocityError, ...
    terminalAccelerationError];
endpointPassed = all(endpointErrors <= tolerance);
constraintPassed = maximumInequalityViolation <= tolerance && ...
    maximumEqualityViolation <= tolerance;
passed = historyIsFinite && timeIsStrictlyIncreasing && ...
    endpointPassed && constraintPassed;
if passed
    message = "Trajectory satisfies endpoint and continuous constraints.";
elseif ~historyIsFinite
    message = "Trajectory histories are empty or nonfinite.";
elseif ~timeIsStrictlyIncreasing
    message = "Trajectory time must be finite and strictly increasing.";
elseif ~endpointPassed
    message = sprintf( ...
        "Endpoint error %.9g exceeds tolerance %.9g.", ...
        max(endpointErrors), tolerance);
else
    message = sprintf( ...
        "Constraint violation %.9g exceeds tolerance %.9g.", ...
        max(maximumInequalityViolation, maximumEqualityViolation), tolerance);
end
validation = struct( ...
    "Passed", passed, ...
    "Message", message, ...
    "HistoryIsFinite", historyIsFinite, ...
    "TimeIsStrictlyIncreasing", timeIsStrictlyIncreasing, ...
    "EndpointPassed", endpointPassed, ...
    "ConstraintPassed", constraintPassed, ...
    "InitialPositionError", initialPositionError, ...
    "InitialVelocityError", initialVelocityError, ...
    "InitialAccelerationError", initialAccelerationError, ...
    "TerminalPositionError", terminalPositionError, ...
    "TerminalVelocityError", terminalVelocityError, ...
    "TerminalAccelerationError", terminalAccelerationError, ...
    "MaximumInequalityViolation", maximumInequalityViolation, ...
    "MaximumEqualityViolation", maximumEqualityViolation, ...
    "Tolerance", tolerance);
end
