function diagnostics = emptySolverDiagnostics( ...
        diagnostics, totalElapsedTime_s, corridorElapsedTime_s)
%% Section 0: Header & Readme
% SYNTAX
%   diagnostics = azElPlanner.emptySolverDiagnostics()
%   diagnostics = azElPlanner.emptySolverDiagnostics( ...
%       diagnostics, totalElapsedTime_s, corridorElapsedTime_s)
%**************************************************************************
% PURPOSE
%   - Define the stable HS3 solver diagnostics and finalize the two elapsed
%     values needed for aggregate planner-stage attribution.
%**************************************************************************
% INPUTS
%   - diagnostics (scalar struct)
%       Existing solver diagnostics to finalize.
%   - totalElapsedTime_s (nonnegative scalar)
%       Complete solver-call elapsed time.
%   - corridorElapsedTime_s (nonnegative scalar)
%       Time spent constructing the frozen collision corridor.
%**************************************************************************
% OUTPUTS
%   - diagnostics (scalar struct)
%       Stable solver evidence with exclusive corridor and motion time.
%**************************************************************************
% UNITS
%   - Timing values are seconds.
%**************************************************************************

if nargin == 0
    diagnostics = struct( ...
        "Identifier", "", ...
        "ConstraintRepresentation", "notBuilt", ...
        "StageOneExitFlag", NaN, ...
        "StageTwoExitFlag", NaN, ...
        "StageOneObjective", NaN, ...
        "StageTwoObjective", NaN, ...
        "StageOneOutput", struct(), ...
        "StageTwoOutput", struct(), ...
        "StageTwoErrorIdentifier", "", ...
        "StageTwoErrorMessage", "", ...
        "MaximumInequalityViolation", Inf, ...
        "MaximumEqualityViolation", Inf, ...
        "CorridorConstructionElapsedTime_s", 0, ...
        "MotionSolvingElapsedTime_s", 0, ...
        "ElapsedTime_s", 0);
    return;
end

diagnostics.CorridorConstructionElapsedTime_s = corridorElapsedTime_s;
diagnostics.MotionSolvingElapsedTime_s = max( ...
    0, totalElapsedTime_s - corridorElapsedTime_s);
diagnostics.ElapsedTime_s = totalElapsedTime_s;
end
