function polynomial = createTrajectoryPolynomial( ...
        controlJerk, initialState, finalTime, segmentCount)
%% Section 0: Header & Readme
% SYNTAX
%   polynomial = hs3Internal.polynomial.createTrajectoryPolynomial( ...
%       controlJerk, initialState, finalTime, segmentCount)
%**************************************************************************
% PURPOSE
%   - Integrate a dimension-neutral quadratic-jerk HS3 chain exactly.
%**************************************************************************
% INPUTS
%   - controlJerk ((2N+1)-by-D numeric), start/mid/end jerk ordinates.
%   - initialState (scalar struct)
%       Fields time, position, velocity, and acceleration use 1-by-D rows.
%   - finalTime (finite scalar), absolute terminal time.
%   - segmentCount (positive integer scalar), equal-duration segments.
%**************************************************************************
% OUTPUTS
%   - polynomial (scalar struct)
%       Segment-by-coordinate-by-power coefficients and terminal state.
%**************************************************************************
% UNITS
%   - Time and coordinate units are caller-defined and must be consistent.
%**************************************************************************

%% Section 1: Integrate Every Segment

% HS3 uses start, midpoint, and end jerk values on each equal-duration
% segment. The unique quadratic through those values is written in ascending
% powers of local tau. The linear and quadratic coefficient formulas below are
% the three-point interpolation formula at tau=0, 1/2, and 1.

dimensionCount = size(controlJerk, 2);
duration = finalTime - initialState.time;
segmentDuration = duration / segmentCount;
startJerk = controlJerk(1:2:end - 2, :);
midpointJerk = controlJerk(2:2:end - 1, :);
endJerk = controlJerk(3:2:end, :);
jerkLinear = -3 * startJerk + 4 * midpointJerk - endJerk;
jerkQuadratic = 2 * startJerk - 4 * midpointJerk + 2 * endJerk;
accelerationContribution = reshape(permute(cat(3, ...
    segmentDuration * startJerk, segmentDuration * jerkLinear / 2, ...
    segmentDuration * jerkQuadratic / 3), [3 1 2]), [], dimensionCount);
accelerationHistory = cumsum( ...
    [initialState.acceleration; accelerationContribution], 1);
acceleration = accelerationHistory(1:3:end - 2, :);
% Exact integration produces one contribution per polynomial power. Flattening
% those contributions and taking a cumulative sum advances the segment start
% state without a numerical integrator. Selecting every third entry recovers
% acceleration at each segment start. Velocity uses four integrated terms.
% Position uses five integrated terms.
velocityContribution = reshape(permute(cat(3, ...
    segmentDuration * acceleration, ...
    segmentDuration^2 * startJerk / 2, ...
    segmentDuration^2 * jerkLinear / 6, ...
    segmentDuration^2 * jerkQuadratic / 12), ...
    [3 1 2]), [], dimensionCount);
velocityHistory = cumsum( ...
    [initialState.velocity; velocityContribution], 1);
velocity = velocityHistory(1:4:end - 3, :);
positionContribution = reshape(permute(cat(3, ...
    segmentDuration * velocity, ...
    segmentDuration^2 * acceleration / 2, ...
    segmentDuration^3 * startJerk / 6, ...
    segmentDuration^3 * jerkLinear / 24, ...
    segmentDuration^3 * jerkQuadratic / 60), ...
    [3 1 2]), [], dimensionCount);
positionHistory = cumsum( ...
    [initialState.position; positionContribution], 1);
position = positionHistory(1:5:end - 4, :);
jerkPower = cat(3, startJerk, jerkLinear, jerkQuadratic);
% Arrays are segment-by-coordinate-by-ascending-power. Coefficients already
% include the required powers of segment duration, so evaluation uses local
% tau directly and returns derivatives in the caller's physical units.
accelerationPower = cat(3, acceleration, permute(reshape( ...
    accelerationContribution, 3, segmentCount, dimensionCount), [2 3 1]));
velocityPower = cat(3, velocity, permute(reshape( ...
    velocityContribution, 4, segmentCount, dimensionCount), [2 3 1]));
positionPower = cat(3, position, permute(reshape( ...
    positionContribution, 5, segmentCount, dimensionCount), [2 3 1]));
segmentStartTime = initialState.time + ...
    (0:segmentCount - 1).' * segmentDuration;
    % TerminalState comes from the final cumulative sums. It does not come from
    % sampled evaluation. Thus, it keeps the exact endpoint used by the solver.
polynomial = struct( ...
    "SegmentCount", segmentCount, ...
    "SegmentStartTime", segmentStartTime, ...
    "SegmentDuration", segmentDuration, ...
    "FinalTime", finalTime, ...
    "positionPower", positionPower, ...
    "velocityPower", velocityPower, ...
    "accelerationPower", accelerationPower, ...
    "jerkPower", jerkPower, ...
    "TerminalState", struct( ...
    "position", positionHistory(end, :), ...
    "velocity", velocityHistory(end, :), ...
    "acceleration", accelerationHistory(end, :)));
end
