function model = createAffineSensitivityModel(segmentCount, duration, evaluationTau)
%% Section 0: Header & Readme
% SYNTAX
%   model = hs3Internal.polynomial.createAffineSensitivityModel( ...
%       segmentCount, duration, evaluationTau)
%**************************************************************************
% PURPOSE
%   - Build exact scalar-coordinate HS3 coefficient, terminal-state, and
%     evaluation sensitivities for quadratic jerk controls.
%**************************************************************************
% INPUTS
%   - segmentCount (positive integer scalar), equal-duration segments.
%   - duration (positive finite scalar), complete trajectory duration.
%   - evaluationTau (numeric vector), normalized coordinates in [0, 1].
%**************************************************************************
% OUTPUTS
%   - model (scalar struct)
%       Power maps are segment-by-power-by-control. TerminalStateMap has
%       position, velocity, and acceleration rows.
%**************************************************************************
% UNITS
%   - Time and coordinate units are caller-defined and must be consistent.
%**************************************************************************

%% Section 1: Propagate Exact Segment Sensitivities

% This function creates the linear maps for one coordinate. Each map gives the
% change in one coefficient for a change in one jerk control. The maps do not
% include initial position, velocity, or acceleration. These values are constant
% offsets and do not change with the jerk controls.

validateattributes(segmentCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'positive'});
validateattributes(duration, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
validateattributes(evaluationTau, {'numeric'}, ...
    {'real', 'finite', 'vector', '>=', 0, '<=', 1});
evaluationTau = double(evaluationTau(:));
controlCount = 2 * segmentCount + 1;
segmentDuration = double(duration) / segmentCount;
persistent cachedSegmentCount cachedJerkConstantMap ...
    cachedJerkLinearMap cachedJerkQuadraticMap cachedPriorSegmentSum
if isempty(cachedSegmentCount) || cachedSegmentCount ~= segmentCount
    segmentIndex = (1:segmentCount).';
    startSelection = sparse(segmentIndex, 2 * segmentIndex - 1, 1, ...
        segmentCount, controlCount);
    midpointSelection = sparse(segmentIndex, 2 * segmentIndex, 1, ...
        segmentCount, controlCount);
    endSelection = sparse(segmentIndex, 2 * segmentIndex + 1, 1, ...
        segmentCount, controlCount);
    % Consecutive segments select the same shared boundary control. The
    % three selection matrices expose each segment's start, midpoint, and
    % end jerk.
    % Mesh incidence and integration ordering do not depend on duration or
    % evaluation coordinates. Reuse them across optimizer iterations.
    cachedJerkConstantMap = startSelection;
    cachedJerkLinearMap = ...
        -3 * startSelection + 4 * midpointSelection - endSelection;
    cachedJerkQuadraticMap = ...
        2 * startSelection - 4 * midpointSelection + 2 * endSelection;
    cachedPriorSegmentSum = sparse(tril(ones(segmentCount), -1));
    % Publish the key last so an interrupted rebuild cannot validate
    % partially replaced cache values.
    cachedSegmentCount = segmentCount;
end
jerkConstantMap = cachedJerkConstantMap;
jerkLinearMap = cachedJerkLinearMap;
jerkQuadraticMap = cachedJerkQuadraticMap;
priorSegmentSum = cachedPriorSegmentSum;
% Integrating within a segment gives its state increment. Multiplication by
% the strict lower-triangular matrix adds all earlier increments. This operation
% propagates continuous acceleration, velocity, and position to each start.
accelerationIncrementMap = segmentDuration * ( ...
    jerkConstantMap + jerkLinearMap / 2 + jerkQuadraticMap / 3);
accelerationStartMap = priorSegmentSum * accelerationIncrementMap;
velocityIncrementMap = segmentDuration * accelerationStartMap + ...
    segmentDuration^2 * (jerkConstantMap / 2 + ...
    jerkLinearMap / 6 + jerkQuadraticMap / 12);
velocityStartMap = priorSegmentSum * velocityIncrementMap;
positionIncrementMap = segmentDuration * velocityStartMap + ...
    segmentDuration^2 * accelerationStartMap / 2 + ...
    segmentDuration^3 * (jerkConstantMap / 6 + ...
    jerkLinearMap / 24 + jerkQuadraticMap / 60);
positionStartMap = priorSegmentSum * positionIncrementMap;
asCoefficientMap = @(value) reshape( ...
    full(value), segmentCount, 1, controlCount);
jerkPowerMap = cat(2, asCoefficientMap(jerkConstantMap), ...
    asCoefficientMap(jerkLinearMap), asCoefficientMap(jerkQuadraticMap));
accelerationPowerMap = cat(2, asCoefficientMap(accelerationStartMap), ...
    asCoefficientMap(segmentDuration * jerkConstantMap), ...
    asCoefficientMap(segmentDuration * jerkLinearMap / 2), ...
    asCoefficientMap(segmentDuration * jerkQuadraticMap / 3));
velocityPowerMap = cat(2, asCoefficientMap(velocityStartMap), ...
    asCoefficientMap(segmentDuration * accelerationStartMap), ...
    asCoefficientMap(segmentDuration^2 * jerkConstantMap / 2), ...
    asCoefficientMap(segmentDuration^2 * jerkLinearMap / 6), ...
    asCoefficientMap(segmentDuration^2 * jerkQuadraticMap / 12));
positionPowerMap = cat(2, asCoefficientMap(positionStartMap), ...
    asCoefficientMap(segmentDuration * velocityStartMap), ...
    asCoefficientMap(segmentDuration^2 * accelerationStartMap / 2), ...
    asCoefficientMap(segmentDuration^3 * jerkConstantMap / 6), ...
    asCoefficientMap(segmentDuration^3 * jerkLinearMap / 24), ...
    asCoefficientMap(segmentDuration^3 * jerkQuadraticMap / 60));
terminalStateMap = full([sum(positionIncrementMap, 1); ...
    sum(velocityIncrementMap, 1); sum(accelerationIncrementMap, 1)]);

%% Section 2: Evaluate Requested Global Coordinates

% Global tau spans the whole trajectory. Convert it to an owning segment and
% local tau in [0,1], then evaluate the same integrated powers used to create
% position and velocity. These maps support point and path calculations while
% preserving exact affine dependence on jerk at fixed duration.

scaledTau = segmentCount * evaluationTau;
evaluationSegmentIndex = min(segmentCount, floor(scaledTau) + 1);
localTau = scaledTau - evaluationSegmentIndex + 1;
selectedPositionStartMap = full( ...
    positionStartMap(evaluationSegmentIndex, :));
selectedVelocityStartMap = full( ...
    velocityStartMap(evaluationSegmentIndex, :));
selectedAccelerationStartMap = full( ...
    accelerationStartMap(evaluationSegmentIndex, :));
selectedJerkConstantMap = full( ...
    jerkConstantMap(evaluationSegmentIndex, :));
selectedJerkLinearMap = full(jerkLinearMap(evaluationSegmentIndex, :));
selectedJerkQuadraticMap = full( ...
    jerkQuadraticMap(evaluationSegmentIndex, :));
positionAtTauMap = selectedPositionStartMap + ...
    segmentDuration * localTau .* selectedVelocityStartMap + ...
    segmentDuration^2 * localTau.^2 / 2 .* ...
    selectedAccelerationStartMap + segmentDuration^3 * ( ...
    localTau.^3 / 6 .* selectedJerkConstantMap + ...
    localTau.^4 / 24 .* selectedJerkLinearMap + ...
    localTau.^5 / 60 .* selectedJerkQuadraticMap);
velocityAtTauMap = selectedVelocityStartMap + ...
    segmentDuration * localTau .* selectedAccelerationStartMap + ...
    segmentDuration^2 * ( ...
    localTau.^2 / 2 .* selectedJerkConstantMap + ...
    localTau.^3 / 6 .* selectedJerkLinearMap + ...
    localTau.^4 / 12 .* selectedJerkQuadraticMap);
model = struct( ...
    "ControlCount", controlCount, ...
    "SegmentDuration", segmentDuration, ...
    "positionPowerMap", positionPowerMap, ...
    "velocityPowerMap", velocityPowerMap, ...
    "accelerationPowerMap", accelerationPowerMap, ...
    "jerkPowerMap", jerkPowerMap, ...
    "terminalStateMap", terminalStateMap, ...
    "positionAtTauMap", full(positionAtTauMap), ...
    "velocityAtTauMap", full(velocityAtTauMap));
end
