function options = azElPlannerDefaults()
%% Section 0: Header & Readme
% SYNTAX
%   options = azElPlannerDefaults()
%**************************************************************************
% PURPOSE
%   - Own the complete caller-facing mission-option defaults.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - options (scalar struct)
%       Physical mission choices, validation tolerances, and one global
%       planning wall-time bound.
%**************************************************************************
% UNITS
%   - Field names state their units.

options = struct( ...
    "safetyMargin_deg", 0.5, ...
    "azimuthWrap", false, ...
    "temporalPadding_s", 0, ...
    "deadline_s", NaN, ...
    "trailingDuration_s", 0, ...
    "planningWallTime_s", 20, ...
    "positionTolerance_deg", 1e-6, ...
    "velocityTolerance_deg_s", 1e-6, ...
    "accelerationTolerance_deg_s2", 1e-6, ...
    "clearanceTolerance_deg", 1e-7, ...
    "arrivalTolerance_s", 1e-6);
end
