function result = makeAzElPlannerResult()
%% Section 0: Header & Readme
% SYNTAX
%   result = makeAzElPlannerResult()
%**************************************************************************
% PURPOSE
%   - Return the stable result schema used by every planner exit.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - result (scalar struct)
%**************************************************************************
% UNITS
%   - Field names state their units.

emptyCommand = struct( ...
    "interpolation", "quinticHermite", ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "unwrappedPosition_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "azimuthWrap", false, ...
    "azimuthDisplayRange_deg", [-180, 180]);
emptyWait = struct( ...
    "startTime_s", 0, ...
    "endTime_s", 0, ...
    "position_deg", [0, 0]);
emptyLevel = struct( ...
    "level", 0, ...
    "spatialResolution_deg", NaN, ...
    "temporalResolution_s", NaN, ...
    "nodeCount", 0, ...
    "edgeCount", 0, ...
    "routeCount", 0, ...
    "candidateCount", 0, ...
    "validationFailureCount", 0, ...
    "incumbentArrivalTime_s", NaN, ...
    "planningElapsed_s", 0);

result = struct( ...
    "success", false, ...
    "status", "unknown", ...
    "reasonCode", "NotStarted", ...
    "message", "Planning has not started.", ...
    "command", emptyCommand, ...
    "arrivalTime_s", NaN, ...
    "waits", repmat(emptyWait, 0, 1), ...
    "options", struct(), ...
    "limits", struct(), ...
    "validation", struct(), ...
    "planningElapsed_s", 0, ...
    "executionDuration_s", NaN, ...
    "operationalArrivalDelay_s", NaN, ...
    "guarantee", struct( ...
        "feasibility", "Unvalidated", ...
        "optimality", "Unknown", ...
        "model", "", ...
        "tolerance_s", NaN, ...
        "lowerBoundDuration_s", NaN, ...
        "arrivalGap_s", NaN), ...
    "diagnostics", struct( ...
        "deterministic", true, ...
        "levels", repmat(emptyLevel, 0, 1), ...
        "incumbentChanges", zeros(0, 2), ...
        "validationFailures", strings(0, 1), ...
        "stoppingReason", "NotStarted"));
end
