function options = resolveHs3Options(optionOverrides)
%% Section 0: Header & Readme
% SYNTAX
%   options = resolveHs3Options()
%   options = resolveHs3Options(optionOverrides)
%**************************************************************************
% PURPOSE
%   - Resolve and validate options shared by HS3 planning entry points.
%**************************************************************************
% INPUTS
%   - optionOverrides (scalar struct, optional; default struct())
%       Partial HS3 option overrides. Empty fields use defaults; unknown
%       fields are warned about once and ignored.
%**************************************************************************
% OUTPUTS
%   - options (scalar struct)
%       Fully populated, normalized, and validated HS3 options.
%**************************************************************************
% UNITS
%   - Time fields use seconds and angular clearance fields use degrees.
%**************************************************************************

%% Section 1: Resolve Defaults

defaults = struct( ...
    "GoalTimeMode", "earliestArrival", ...
    "SampleTime_s", 0.05, ...
    "AllowAzimuthWrapping", false, ...
    "MaximumSeedCount", 5, ...
    "DirectSeedOnly", false, ...
    "SeedClusterDistance_deg", 0, ...
    "CollocationSegmentCount", 10, ...
    "MaximumCollocationSegmentCount", 64, ...
    "MaximumMeshRefinementPasses", 2, ...
    "MaximumNlpIterations", 300, ...
    "MaximumNlpFunctionEvaluations", 30000, ...
    "MaximumPlanningTime_s", 115, ...
    "DeterministicWorkBudget", false, ...
    "ArrivalTimeTolerance_s", 1e-3, ...
    "ConstraintTolerance", 1e-7, ...
    "OptimalityTolerance", 1e-7, ...
    "StepTolerance", 1e-10, ...
    "CollisionClearanceTolerance_deg", 1e-7, ...
    "CollisionMinimumTimeStep_s", 0.00025, ...
    "Verbose", false, ...
    "RandomSeed", 0);
if nargin == 0 || isempty(optionOverrides)
    optionOverrides = struct();
end
if ~isstruct(optionOverrides) || ~isscalar(optionOverrides)
    error("planAzElMotion:InvalidOptions", ...
        "optionOverrides must be a scalar struct.");
end
for movedName = ["AzimuthInterval_deg", "ElevationInterval_deg"]
    if isfield(optionOverrides, movedName)
        replacementName = lower(extractBefore(movedName, "Interval")) + ...
            "Interval_deg";
        error("planAzElMotion:WorkspaceLimitMoved", ...
            "%s has moved from options to limits.%s.", ...
            movedName, replacementName);
    end
end
[options, unknownNames] = azElInput.resolveOptions(defaults, optionOverrides);
if ~isempty(unknownNames)
    warning("planAzElMotion:UnknownOptions", ...
        "Ignoring unknown option fields: %s. No behavior changed.", ...
        strjoin(unknownNames, ", "));
end

%% Section 2: Normalize Public Values

options.GoalTimeMode = string(options.GoalTimeMode);
if ~isscalar(options.GoalTimeMode) || ~any( ...
        options.GoalTimeMode == ["earliestArrival", "fixedArrival"])
    error("planAzElMotion:InvalidGoalTimeMode", ...
        "GoalTimeMode must be 'earliestArrival' or 'fixedArrival'.");
end
for name = ["AllowAzimuthWrapping", "DeterministicWorkBudget", ...
        "DirectSeedOnly", "Verbose"]
    options.(name) = azElInput.normalizeLogicalScalar( ...
        options.(name), name, "planAzElMotion:InvalidLogicalOption");
end
validateattributes(options.SampleTime_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
validateattributes(options.MaximumSeedCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 1, '<=', 9});
validateattributes(options.SeedClusterDistance_deg, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'});
validateattributes(options.CollocationSegmentCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 2, '<=', 80});
validateattributes(options.MaximumCollocationSegmentCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', ...
    '>=', options.CollocationSegmentCount, '<=', 80});
validateattributes(options.MaximumMeshRefinementPasses, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', '>=', 0, '<=', 2});
for name = ["MaximumNlpIterations", "MaximumNlpFunctionEvaluations"]
    validateattributes(options.(name), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', 'positive'});
end
for name = ["MaximumPlanningTime_s", "ArrivalTimeTolerance_s", ...
        "ConstraintTolerance", "OptimalityTolerance", "StepTolerance", ...
        "CollisionMinimumTimeStep_s"]
    validateattributes(options.(name), {'numeric'}, ...
        {'real', 'finite', 'scalar', 'positive'});
end
validateattributes(options.CollisionClearanceTolerance_deg, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'});
validateattributes(options.RandomSeed, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'nonnegative'});
end
