function model = hs3AffineSensitivity(segmentCount, duration_s, evaluationTau)
%% Section 0: Header & Readme
% SYNTAX
%   model = azElPlannerMethods.hs3.internal.motion.hs3AffineSensitivity( ...
%       segmentCount, duration_s, evaluationTau)
%**************************************************************************
% PURPOSE
%   - Build exact scalar-axis coefficient, terminal-state, and evaluation
%     sensitivities for the quadratic-jerk Hermite-Simpson chain.
%**************************************************************************
% INPUTS
%   - segmentCount (positive integer scalar)
%       Number of equal-duration Hermite-Simpson segments.
%   - duration_s (positive finite scalar)
%       Complete physical trajectory duration.
%   - evaluationTau (numeric vector)
%       Global normalized trajectory coordinates in the closed interval [0,1].
%**************************************************************************
% OUTPUTS
%   - model (scalar struct)
%       PowerCoefficient maps have shape segment-by-power-by-control.
%       terminalStateMap has P/V/A rows. positionAtTauMap and
%       velocityAtTauMap have one row per requested evaluation coordinate.
%**************************************************************************
% UNITS
%   - Maps multiply jerk in deg/s^3. Position, velocity, acceleration, and
%     jerk maps therefore have sensitivity units s^3, s^2, s, and 1.
%**************************************************************************

%% Section 1: Propagate Exact Segment Sensitivities

validateattributes(segmentCount, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'positive'});
validateattributes(duration_s, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'});
validateattributes(evaluationTau, {'numeric'}, ...
    {'real', 'finite', 'vector', '>=', 0, '<=', 1});
evaluationTau = double(evaluationTau(:));
controlCount = 2 * segmentCount + 1;
segmentDuration_s = double(duration_s) / segmentCount;
segmentIndex = (1:segmentCount).';
startSelection = sparse(segmentIndex, 2 * segmentIndex - 1, 1, ...
    segmentCount, controlCount);
midpointSelection = sparse(segmentIndex, 2 * segmentIndex, 1, ...
    segmentCount, controlCount);
endSelection = sparse(segmentIndex, 2 * segmentIndex + 1, 1, ...
    segmentCount, controlCount);
jerkConstantMap = startSelection;
jerkLinearMap = -3 * startSelection + 4 * midpointSelection - endSelection;
jerkQuadraticMap = 2 * startSelection - 4 * midpointSelection + 2 * endSelection;
priorSegmentSum = sparse(tril(ones(segmentCount), -1));
accelerationIncrementMap = segmentDuration_s * ( ...
    jerkConstantMap + jerkLinearMap / 2 + jerkQuadraticMap / 3);
accelerationStartMap = priorSegmentSum * accelerationIncrementMap;
velocityIncrementMap = segmentDuration_s * accelerationStartMap + ...
    segmentDuration_s^2 * (jerkConstantMap / 2 + ...
    jerkLinearMap / 6 + jerkQuadraticMap / 12);
velocityStartMap = priorSegmentSum * velocityIncrementMap;
positionIncrementMap = segmentDuration_s * velocityStartMap + ...
    segmentDuration_s^2 * accelerationStartMap / 2 + ...
    segmentDuration_s^3 * (jerkConstantMap / 6 + ...
    jerkLinearMap / 24 + jerkQuadraticMap / 60);
positionStartMap = priorSegmentSum * positionIncrementMap;
asCoefficientMap = @(value) reshape( ...
    full(value), segmentCount, 1, controlCount);
jerkPowerMap = cat(2, asCoefficientMap(jerkConstantMap), ...
    asCoefficientMap(jerkLinearMap), asCoefficientMap(jerkQuadraticMap));
accelerationPowerMap = cat(2, asCoefficientMap(accelerationStartMap), ...
    asCoefficientMap(segmentDuration_s * jerkConstantMap), ...
    asCoefficientMap(segmentDuration_s * jerkLinearMap / 2), ...
    asCoefficientMap(segmentDuration_s * jerkQuadraticMap / 3));
velocityPowerMap = cat(2, asCoefficientMap(velocityStartMap), ...
    asCoefficientMap(segmentDuration_s * accelerationStartMap), ...
    asCoefficientMap(segmentDuration_s^2 * jerkConstantMap / 2), ...
    asCoefficientMap(segmentDuration_s^2 * jerkLinearMap / 6), ...
    asCoefficientMap(segmentDuration_s^2 * jerkQuadraticMap / 12));
positionPowerMap = cat(2, asCoefficientMap(positionStartMap), ...
    asCoefficientMap(segmentDuration_s * velocityStartMap), ...
    asCoefficientMap(segmentDuration_s^2 * accelerationStartMap / 2), ...
    asCoefficientMap(segmentDuration_s^3 * jerkConstantMap / 6), ...
    asCoefficientMap(segmentDuration_s^3 * jerkLinearMap / 24), ...
    asCoefficientMap(segmentDuration_s^3 * jerkQuadraticMap / 60));
terminalStateMap = full([sum(positionIncrementMap, 1); ...
    sum(velocityIncrementMap, 1); sum(accelerationIncrementMap, 1)]);

%% Section 2: Evaluate Requested Global Coordinates

scaledTau = segmentCount * evaluationTau;
evaluationSegmentIndex = min(segmentCount, floor(scaledTau) + 1);
localTau = scaledTau - evaluationSegmentIndex + 1;
selectedPositionStartMap = full(positionStartMap(evaluationSegmentIndex, :));
selectedVelocityStartMap = full(velocityStartMap(evaluationSegmentIndex, :));
selectedAccelerationStartMap = full(accelerationStartMap(evaluationSegmentIndex, :));
selectedJerkConstantMap = full(jerkConstantMap(evaluationSegmentIndex, :));
selectedJerkLinearMap = full(jerkLinearMap(evaluationSegmentIndex, :));
selectedJerkQuadraticMap = full(jerkQuadraticMap(evaluationSegmentIndex, :));
positionAtTauMap = selectedPositionStartMap + ...
    segmentDuration_s * localTau .* selectedVelocityStartMap + ...
    segmentDuration_s^2 * localTau.^2 / 2 .* selectedAccelerationStartMap + ...
    segmentDuration_s^3 * (localTau.^3 / 6 .* selectedJerkConstantMap + ...
    localTau.^4 / 24 .* selectedJerkLinearMap + ...
    localTau.^5 / 60 .* selectedJerkQuadraticMap);
velocityAtTauMap = selectedVelocityStartMap + ...
    segmentDuration_s * localTau .* selectedAccelerationStartMap + ...
    segmentDuration_s^2 * (localTau.^2 / 2 .* selectedJerkConstantMap + ...
    localTau.^3 / 6 .* selectedJerkLinearMap + ...
    localTau.^4 / 12 .* selectedJerkQuadraticMap);
model = struct( ...
    "ControlCount", controlCount, ...
    "SegmentDuration_s", segmentDuration_s, ...
    "positionPowerMap", positionPowerMap, ...
    "velocityPowerMap", velocityPowerMap, ...
    "accelerationPowerMap", accelerationPowerMap, ...
    "jerkPowerMap", jerkPowerMap, ...
    "terminalStateMap", terminalStateMap, ...
    "positionAtTauMap", full(positionAtTauMap), ...
    "velocityAtTauMap", full(velocityAtTauMap));
end
