function varargout = integratedSquaredHs3Jerk( ...
        decision, isEarliestArrival, fixedFinalTime_s, ...
        segmentCount, startTime_s)
%% Section 0: Header & Readme
% SYNTAX
%   value = ...
%       azElPlannerMethods.hs3.internal.motion.integratedSquaredHs3Jerk( ...
%       decision, isEarliestArrival, fixedFinalTime_s, ...
%       segmentCount, startTime_s)
%   [value, gradient, hessian] = ...
%       azElPlannerMethods.hs3.internal.motion.integratedSquaredHs3Jerk( ...
%       decision, isEarliestArrival, fixedFinalTime_s, ...
%       segmentCount, startTime_s)
%**************************************************************************
% PURPOSE
%   - Provide a deprecated two-axis alias to hs3.integratedSquaredJerk.
%**************************************************************************
% INPUTS
%   - decision, isEarliestArrival, fixedFinalTime_s, segmentCount,
%       startTime_s (numeric), existing objective inputs.
%**************************************************************************
% OUTPUTS
%   - varargout (numeric), objective value and requested derivatives.
%**************************************************************************
% UNITS
%   - Time uses seconds and jerk uses degrees per second cubed.
%**************************************************************************
[varargout{1:nargout}] = hs3.integratedSquaredJerk( ...
    decision, isEarliestArrival, fixedFinalTime_s, ...
    segmentCount, startTime_s, 2);
end
