function candidate = solveHs3(obstacles, initialState, goalState, limits, options, seed)
%% Section 0: Header & Readme
% SYNTAX
%   candidate = azElPlannerMethods.hs3.internal.motion.solveHs3(obstacles, initialState, ...
%       goalState, limits, options, seed)
%**************************************************************************
% PURPOSE
%   - Solve and reconstruct one separated third-order Hermite-Simpson motion.
%**************************************************************************
% INPUTS
%   - obstacles (canonical protected obstacle struct array)
%   - initialState, goalState (normalized scalar state structs)
%   - limits (normalized scalar limits struct)
%   - options (resolved planner options)
%   - seed (scalar topology-seed struct)
%       position_deg is N-by-2 and tau is a strictly increasing N-vector.
%**************************************************************************
% OUTPUTS
%   - candidate (scalar struct)
%       Solver outcome, polynomial trajectory, samples, and diagnostics.
%**************************************************************************
% UNITS
%   - Position is degrees; derivatives use deg/s, deg/s^2, and deg/s^3.
%**************************************************************************
%% Section 1: Build The Decision Layout And Initial Guess
solverTimer = tic;
corridorConstructionElapsedTime_s = 0;
maximumSolverTime_s = options.MaximumSolverTime_s;
if isempty(obstacles) && ~isstruct(obstacles)
    obstacles = combineAzElObstacles(obstacles);
end
obstacles = azElInternal.obstacles.prepareDynamic(obstacles);
segmentCount = options.CollocationSegmentCount;
if ~isfield(seed, "CorridorBoundary_deg")
    seed.CorridorBoundary_deg = zeros(0, 2);
end
controlCount = 2 * segmentCount + 1;
isEarliestArrival = options.GoalTimeMode == "earliestArrival";
constraintRepresentations = ["linearFixedTime", "nonlinearTimeDecision"];
constraintRepresentation = constraintRepresentations(1 + isEarliestArrival);
startTime_s = initialState.time_s;
latestFinalTime_s = goalState.time_s;
minimumDuration_s = durationLowerBound(initialState, goalState, limits, latestFinalTime_s);
isTimedSeed = any(seed.Source == ["directWait", "timeExpandedVisibilityGraph"]);
minimumFinalTime_s = startTime_s + minimumDuration_s;
if isEarliestArrival && isfield(goalState, "targetTime_s") && ~isempty(goalState.targetTime_s)
    minimumFinalTime_s = max(minimumFinalTime_s, goalState.targetTime_s(1));
end
candidate = emptyCandidate(seed, segmentCount);
if maximumSolverTime_s <= 0
    candidate.Message = "HS3 reached its solver time limit before setup.";
    candidate.TerminationReason = "solverTimeLimit";
    candidate.SolverDiagnostics = ...
        azElPlannerMethods.hs3.internal.motion.emptyHs3SolverDiagnostics( ...
        candidate.SolverDiagnostics, toc(solverTimer), ...
        corridorConstructionElapsedTime_s);
    return;
end
if minimumFinalTime_s > latestFinalTime_s + options.ConstraintTolerance
    candidate.Message = "The goal time is below a physical duration bound.";
    candidate.TerminationReason = "timeWindowInfeasible";
    candidate.SolverDiagnostics = ...
        azElPlannerMethods.hs3.internal.motion.emptyHs3SolverDiagnostics( ...
        candidate.SolverDiagnostics, toc(solverTimer), ...
        corridorConstructionElapsedTime_s);
    return;
end
if isEarliestArrival && isTimedSeed
    finalTimeGuess_s = min(latestFinalTime_s, max( ...
        minimumFinalTime_s, startTime_s + seed.EstimatedDuration_s));
elseif isEarliestArrival
    seedDuration_s = max(minimumDuration_s, seed.EstimatedDuration_s);
    finalTimeGuess_s = min(latestFinalTime_s, ...
        startTime_s + max(1.05 * minimumDuration_s, seedDuration_s));
else
    finalTimeGuess_s = latestFinalTime_s;
end
controlTau = linspace(0, 1, controlCount).';
[initialJerk_deg_s3, initialJerkLimitRatio] = initialJerkGuess(isEarliestArrival, ...
    initialState, goalState, limits, seed, finalTimeGuess_s, ...
    segmentCount, controlTau);
if isEarliestArrival && ~isTimedSeed && initialJerkLimitRatio > 1
    durationScale = initialJerkLimitRatio^(1 / 3);
    durationSafetyFactor = 1.05;
    if isfield(seed, "UsesReducedGeometry") && seed.UsesReducedGeometry
        % Reduced geometry sharpens turns; an unused option must not change timing.
        durationSafetyFactor = 1.5;
    end
    scaledDuration_s = (finalTimeGuess_s - startTime_s) * durationScale * ...
        durationSafetyFactor;
    finalTimeGuess_s = min(latestFinalTime_s, startTime_s + scaledDuration_s);
    [initialJerk_deg_s3, ~] = initialJerkGuess(isEarliestArrival, ...
        initialState, goalState, limits, seed, finalTimeGuess_s, ...
        segmentCount, controlTau);
end
corridorConstructionTimer = tic;
% Detailed boundaries need more checks; independent validation remains final.
corridorCheckCount = corridorChecksPerSegment( ...
    obstacles, startTime_s, finalTimeGuess_s, segmentCount);
corridorTau = linspace(0, 1, corridorCheckCount * segmentCount + 1).';
eventTau = (vertcat(obstacles.time_s) - startTime_s) / ...
    (finalTimeGuess_s - startTime_s);
eventTau = eventTau(eventTau > 0 & eventTau < 1);
corridorTau = unique([corridorTau; eventTau]);
corridor = buildCorridor( ...
    obstacles, seed, startTime_s, finalTimeGuess_s, corridorTau, ...
    options.CollisionClearanceTolerance_deg, ...
    ~isEarliestArrival, limits.maxVelocity_deg_s);
corridorTau = unique([corridor.Tau].', "stable");
seedCorridor = azElInternal.buildSeedCorridor(seed, segmentCount);
corridorConstructionElapsedTime_s = toc(corridorConstructionTimer);
if toc(solverTimer) >= maximumSolverTime_s
    candidate.Message = "HS3 reached its solver time limit during setup.";
    candidate.TerminationReason = "solverTimeLimit";
    candidate.Corridor = corridor;
    candidate.SeedCorridor = seedCorridor;
    candidate.SolverDiagnostics = ...
        azElPlannerMethods.hs3.internal.motion.emptyHs3SolverDiagnostics( ...
        candidate.SolverDiagnostics, toc(solverTimer), ...
        corridorConstructionElapsedTime_s);
    return;
end
decision0 = initialJerk_deg_s3(:);
jerkScale_deg_s3 = repmat(limits.maxJerk_deg_s3, controlCount, 1);
jerkScale_deg_s3 = jerkScale_deg_s3(:);
lowerBound = -jerkScale_deg_s3;
upperBound = jerkScale_deg_s3;
typicalDecision = max(jerkScale_deg_s3, 1e-3);
if isEarliestArrival
    decision0(end + 1, 1) = finalTimeGuess_s;
    lowerBound(end + 1, 1) = minimumFinalTime_s;
    upperBound(end + 1, 1) = latestFinalTime_s;
    typicalDecision(end + 1, 1) = max([1, ...
        abs(minimumFinalTime_s), abs(latestFinalTime_s)]);
end
%% Section 2: Minimize Arrival Time Or Fixed-Time Jerk
% Timed and exact multi-obstacle systems converge faster when factorized.
useFactorization = isEarliestArrival && (isTimedSeed || ...
    (numel(obstacles) > 1 && ~seed.UsesReducedGeometry));
subproblemAlgorithms = ["cg", "factorization"];
subproblemAlgorithm = subproblemAlgorithms(1 + useFactorization);
solverOptions = optimoptions("fmincon", ...
    "Algorithm", "interior-point", "SubproblemAlgorithm", subproblemAlgorithm, ...
    "Display", "none", ...
    "MaxIterations", options.MaximumNlpIterations, ...
    "MaxFunctionEvaluations", options.MaximumNlpFunctionEvaluations, ...
    "ConstraintTolerance", options.ConstraintTolerance, ...
    "OptimalityTolerance", options.OptimalityTolerance, ...
    "StepTolerance", options.StepTolerance, ...
    "ScaleProblem", true, ...
    "SpecifyObjectiveGradient", true, ...
    "SpecifyConstraintGradient", isEarliestArrival, ...
    "TypicalX", typicalDecision, ...
    "OutputFcn", @(decision, solverValues, state) ...
    hs3Progress(decision, solverValues, state, solverTimer, ...
    maximumSolverTime_s, options.Verbose, seed.Index));
reconstructFunction = @(jerk_deg_s3, finalTime_s) reconstructPolynomial( ...
    jerk_deg_s3, initialState, finalTime_s, segmentCount);
constraintFunction = @(decision) ...
    azElPlannerMethods.hs3.internal.motion.evaluateHs3TrajectoryConstraints( ...
    decision, isEarliestArrival, latestFinalTime_s, minimumFinalTime_s, ...
    latestFinalTime_s, segmentCount, initialState, goalState, limits, ...
    options, obstacles, corridor, corridorTau, seedCorridor, ...
    reconstructFunction);
linearInequalityMatrix = zeros(0, numel(decision0));
linearInequalityBound = zeros(0, 1);
linearEqualityMatrix = zeros(0, numel(decision0));
linearEqualityBound = zeros(0, 1);
nonlinearConstraintFunction = constraintFunction;
if ~isEarliestArrival
    % Fixed-time integration makes every raw constraint affine in jerk.
    [zeroInequality, zeroEquality] = constraintFunction(zeros(size(decision0)));
    [linearInequalityMatrix, linearEqualityMatrix] = ...
        azElPlannerMethods.hs3.internal.motion.buildFixedHs3ConstraintMatrices( ...
        segmentCount, latestFinalTime_s - startTime_s, ...
        options.AllowAzimuthWrapping, seedCorridor, corridor, corridorTau);
    if size(linearInequalityMatrix, 1) ~= numel(zeroInequality) || ...
            size(linearEqualityMatrix, 1) ~= numel(zeroEquality)
        error("solveHs3:ConstraintGradientSizeMismatch", ...
            "The exact fixed-time HS3 constraint maps have inconsistent sizes.");
    end
    linearInequalityBound = -zeroInequality;
    linearEqualityBound = -zeroEquality;
    nonlinearConstraintFunction = [];
end
if isEarliestArrival
    stageOneObjective = @arrivalTimeObjective;
else
    stageOneObjective = @(decision) ...
        azElPlannerMethods.hs3.internal.motion.integratedSquaredHs3Jerk( ...
        decision, false, latestFinalTime_s, segmentCount, startTime_s);
end
try
    [stageOneDecision, stageOneObjectiveValue, stageOneExitFlag, ...
        stageOneOutput] = fmincon( ...
        stageOneObjective, decision0, linearInequalityMatrix, ...
        linearInequalityBound, linearEqualityMatrix, ...
        linearEqualityBound, lowerBound, upperBound, ...
        nonlinearConstraintFunction, solverOptions);
catch exception
    candidate.Message = "HS3 solve failed: " + string(exception.message);
    candidate.TerminationReason = "solverError";
    candidate.SolverDiagnostics.Identifier = string(exception.identifier);
    candidate.SolverDiagnostics = ...
        azElPlannerMethods.hs3.internal.motion.emptyHs3SolverDiagnostics( ...
        candidate.SolverDiagnostics, toc(solverTimer), ...
        corridorConstructionElapsedTime_s);
    return;
end
%% Section 3: Recover An Infeasible Primary Solver Result
selectedDecision = stageOneDecision;
stageTwoExitFlag = NaN;
stageTwoOutput = struct();
stageTwoObjectiveValue = NaN;
stageTwoErrorIdentifier = "";
stageTwoErrorMessage = "";
[finalInequality, finalEquality] = constraintFunction(stageOneDecision);
stageOneViolation = max([0; finalInequality(:); abs(finalEquality(:))]);
feasibilityTolerance = max(10 * options.ConstraintTolerance, 1e-7);
if isEarliestArrival && ...
        stageOneViolation > feasibilityTolerance && ...
        toc(solverTimer) < maximumSolverTime_s
    stageTwoUpperBound = upperBound;
    stageTwoUpperBound(end) = min( ...
        latestFinalTime_s, stageOneDecision(end) + ...
        options.ArrivalTimeTolerance_s);
    stageTwoObjective = @(~) 0;
    try
        [trialDecision, stageTwoObjectiveValue, stageTwoExitFlag, ...
            stageTwoOutput] = fmincon( ...
            stageTwoObjective, stageOneDecision, [], [], [], [], ...
            lowerBound, stageTwoUpperBound, constraintFunction, ...
            solverOptions);
        [trialInequality, trialEquality] = constraintFunction(trialDecision);
        trialViolation = max([0; trialInequality(:); abs(trialEquality(:))]);
        if trialViolation <= max(options.ConstraintTolerance, stageOneViolation)
            selectedDecision = trialDecision;
            finalInequality = trialInequality;
            finalEquality = trialEquality;
        end
    catch exception
        stageTwoErrorIdentifier = string(exception.identifier);
        stageTwoErrorMessage = string(exception.message);
    end
end
%% Section 4: Reconstruct The Candidate
[jerk_deg_s3, finalTime_s] = unpackDecision( ...
    selectedDecision, isEarliestArrival, latestFinalTime_s, controlCount);
polynomial = reconstructPolynomial( ...
    jerk_deg_s3, initialState, finalTime_s, segmentCount);
[sampleTime_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, sampledJerk_deg_s3] = samplePolynomial( ...
    polynomial, options.SampleTime_s);
maximumInequalityViolation = max([0; finalInequality(:)]);
maximumEqualityViolation = max([0; abs(finalEquality(:))]);
maximumViolation = max( ...
    maximumInequalityViolation, maximumEqualityViolation);
optimizerFeasible = maximumViolation <= feasibilityTolerance;
timeLimitReached = toc(solverTimer) >= maximumSolverTime_s;
if optimizerFeasible
    message = "HS3 returned a constraint-feasible local solution.";
    terminationReason = "optimizerFeasible";
elseif timeLimitReached
    message = "HS3 reached its solver time limit before feasibility.";
    terminationReason = "solverTimeLimit";
else
    message = "HS3 did not satisfy all optimization constraints.";
    terminationReason = "optimizerInfeasible";
end
solverDiagnostics = azElPlannerMethods.hs3.internal.motion.emptyHs3SolverDiagnostics();
solverDiagnostics.ConstraintRepresentation = constraintRepresentation;
solverDiagnostics.StageOneExitFlag = stageOneExitFlag;
solverDiagnostics.StageTwoExitFlag = stageTwoExitFlag;
solverDiagnostics.StageOneObjective = stageOneObjectiveValue;
solverDiagnostics.StageTwoObjective = stageTwoObjectiveValue;
solverDiagnostics.StageOneOutput = stageOneOutput;
solverDiagnostics.StageTwoOutput = stageTwoOutput;
solverDiagnostics.StageTwoErrorIdentifier = stageTwoErrorIdentifier;
solverDiagnostics.StageTwoErrorMessage = stageTwoErrorMessage;
solverDiagnostics.MaximumInequalityViolation = maximumInequalityViolation;
solverDiagnostics.MaximumEqualityViolation = maximumEqualityViolation;
candidate = struct( ...
    "OptimizerFeasible", optimizerFeasible, ...
    "Message", message, ...
    "TerminationReason", terminationReason, ...
    "SeedIndex", seed.Index, ...
    "SeedSource", seed.Source, ...
    "FinalTime_s", finalTime_s, ...
    "MotionDuration_s", finalTime_s - startTime_s, ...
    "IntegratedSquaredJerk_deg2_s5", ...
    azElPlannerMethods.hs3.internal.motion.integratedSquaredHs3Jerk( ...
    selectedDecision, isEarliestArrival, latestFinalTime_s, ...
    segmentCount, startTime_s), ...
    "MaximumConstraintViolation", maximumViolation, ...
    "time_s", sampleTime_s, ...
    "position_deg", position_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2, ...
    "jerk_deg_s3", sampledJerk_deg_s3, ...
    "Polynomial", polynomial, ...
    "ControlTau", controlTau, ...
    "ControlJerk_deg_s3", jerk_deg_s3, ...
    "Corridor", corridor, ...
    "SeedCorridorBoundary_deg", seed.CorridorBoundary_deg, ...
    "SeedCorridor", seedCorridor, ...
    "SolverDiagnostics", solverDiagnostics);
candidate.SolverDiagnostics = ...
    azElPlannerMethods.hs3.internal.motion.emptyHs3SolverDiagnostics( ...
    candidate.SolverDiagnostics, toc(solverTimer), ...
    corridorConstructionElapsedTime_s);
end
function stop = hs3Progress(~, solverValues, state, solverTimer, ...
        maximumTime_s, verbose, seedIndex)
% Stop optional solver work and report deterministic progress intervals.
stop = toc(solverTimer) >= maximumTime_s;
if ~verbose
    return;
end
iteration = outputValue(solverValues, "iteration");
if state == "init" || state == "done" || ...
        (state == "iter" && mod(iteration, 10) == 0)
    fprintf("[AzEl][HS3][seed %d] state=%s, iteration=%g, " + ...
        "evaluations=%g, objective=%.6g, violation=%.3g.\n", ...
        seedIndex, state, iteration, ...
        outputValue(solverValues, "funccount"), ...
        outputValue(solverValues, "fval"), ...
        outputValue(solverValues, "constrviolation"));
end
end
function value = outputValue(output, fieldName)
% Read one optional fmincon output value for stable verbose messages.
if isstruct(output) && isfield(output, fieldName)
    value = output.(fieldName);
else
    value = NaN;
end
end
function checkCount = corridorChecksPerSegment( ...
        obstacles, startTime_s, finalTime_s, segmentCount)
% Scale density with boundary detail and obstacle-history time spacing.
maximumVertexCount = 0;
minimumInterval_s = Inf;

% Scan every obstacle to find the densest boundary and shortest history
% interval that the frozen corridor must resolve.
for obstacleIndex = 1:numel(obstacles)
    obstacle = obstacles(obstacleIndex);
    if numel(obstacle.time_s) > 1
        minimumInterval_s = min( ...
            minimumInterval_s, min(diff(obstacle.time_s)));
    end

    % Inspect every source slice because a later slice may contain more detail
    % than the first.
    for sampleIndex = 1:numel(obstacle.az_deg)
        finiteVertexCount = nnz(isfinite(obstacle.az_deg{sampleIndex}) & ...
            isfinite(obstacle.el_deg{sampleIndex}));
        maximumVertexCount = max(maximumVertexCount, finiteVertexCount);
    end
end
boundaryCheckCount = ceil(maximumVertexCount / 5);
motionCheckCount = 8;
if isfinite(minimumInterval_s) && minimumInterval_s > 0
    samplesPerObstacleInterval = 4;
    duration_s = finalTime_s - startTime_s;
    motionCheckCount = ceil(samplesPerObstacleInterval * duration_s / ...
        (segmentCount * minimumInterval_s));
end
maximumChecksPerSegment = 16;
checkCount = min(maximumChecksPerSegment, ...
    max([8, boundaryCheckCount, motionCheckCount]));
end
function [jerkGuess_deg_s3, jerkLimitRatio] = initialJerkGuess(isEarliestArrival, ...
        initialState, goalState, limits, seed, finalTime_s, segmentCount, controlTau)
% Fit a bounded jerk-chain initialization to the supplied topology seed.
controlCount = numel(controlTau);
desiredPosition_deg = interp1(seed.tau, seed.position_deg, controlTau, "linear");
evaluationTime_s = initialState.time_s + controlTau * (finalTime_s - initialState.time_s);
zeroJerk_deg_s3 = zeros(controlCount, 2);
basePolynomial = reconstructPolynomial(zeroJerk_deg_s3, initialState, finalTime_s, segmentCount);
[~, basePosition_deg, baseVelocity_deg_s, baseAcceleration_deg_s2] = ...
    azElInternal.evaluatePolynomial( ...
        basePolynomial, evaluationTime_s);
desiredPosition_deg(end, :) = azElInternal.goalPositionAtTime( ...
    goalState, finalTime_s);
routeTangent_deg = desiredPosition_deg([2:end end], :) - desiredPosition_deg([1 1:end-1], :);
routeDirection = routeTangent_deg ./ max(vecnorm(routeTangent_deg, 2, 2), eps);
routeSpeed_deg_s = min(limits.maxVelocity_deg_s ./ max(abs(routeDirection), eps), [], 2);
routeSpeed_deg_s = min(routeSpeed_deg_s, max(seed.Length_deg / ...
    (finalTime_s - initialState.time_s), isEarliestArrival * norm(limits.maxVelocity_deg_s)));
desiredVelocity_deg_s = routeDirection .* routeSpeed_deg_s;
desiredVelocity_deg_s([1 end], :) = [initialState.velocity_deg_s; goalState.velocity_deg_s];
velocityFitWeight_s = (finalTime_s - initialState.time_s) / segmentCount;
sensitivity = azElPlannerMethods.hs3.internal.motion.hs3AffineSensitivity( ...
    segmentCount, finalTime_s - initialState.time_s, controlTau);
positionMap = sensitivity.positionAtTauMap(2:end, :);
velocityMap = sensitivity.velocityAtTauMap(2:end - 1, :);
terminalVelocityMap = sensitivity.terminalStateMap(2, :);
terminalAccelerationMap = sensitivity.terminalStateMap(3, :);
fitMatrix = [positionMap; velocityFitWeight_s * velocityMap; 5 * terminalVelocityMap; ...
    5 * terminalAccelerationMap];
fitOffset = [desiredPosition_deg(2:end, :) - basePosition_deg(2:end, :); ...
    velocityFitWeight_s * (desiredVelocity_deg_s(2:end-1, :) - ...
    baseVelocity_deg_s(2:end-1, :)); ...
    5 * (goalState.velocity_deg_s - baseVelocity_deg_s(end, :)); ...
    5 * (goalState.acceleration_deg_s2 - baseAcceleration_deg_s2(end, :))];
regularization = 1e-8 * eye(controlCount);
jerkGuess_deg_s3 = (fitMatrix.' * fitMatrix + regularization) \ ...
    (fitMatrix.' * fitOffset);
jerkLimitRatio = max(abs(jerkGuess_deg_s3) ./ limits.maxJerk_deg_s3, [], "all");
jerkGuess_deg_s3 = min(limits.maxJerk_deg_s3, max(-limits.maxJerk_deg_s3, jerkGuess_deg_s3));
end
function [value, gradient] = arrivalTimeObjective(decision)
% Return the exact linear arrival objective and axis-major decision gradient.
value = decision(end);
if nargout > 1
    gradient = zeros(size(decision));
    gradient(end) = 1;
end
end
function corridor = buildCorridor( ...
        obstacles, seed, startTime_s, finalTime_s, controlTau, ...
        clearanceTolerance_deg, geometryIsFixed, maxVelocity_deg_s)
% Freeze obstacle edges at dense optimization constraint points.
template = struct( ...
    "ControlIndex", 0, "ObstacleIndex", 0, "EdgeIndex", 0, ...
    "Tau", 0, ...
    "OutwardSign", 1, "UseSupport", false, ...
    "SupportNormal", [0 0], "Clearance_deg", 0, ...
    "GeometryIsFixed", false, "FixedNormal", [0 0], ...
    "FixedBoundaryOffset_deg", 0);
corridor = repmat(template, 0, 1);
if azElInternal.seedEnvelopeContainsObstacles( ...
        seed.CorridorBoundary_deg, obstacles, clearanceTolerance_deg)
    return;
end
lockedAssociation = repmat(template, numel(obstacles), 1);
hasLockedAssociation = false(numel(obstacles), 1);
seedPosition_deg = interp1(seed.tau, seed.position_deg, ...
    controlTau, "linear");
controlTime_s = startTime_s + controlTau * (finalTime_s - startTime_s);
vehicleSpeedBound_deg_s = norm(maxVelocity_deg_s);

% Visit every dense control time so moving obstacle associations remain ordered
% along the candidate trajectory.
for controlIndex = 1:numel(controlTau)
    % Associate every active obstacle with one supporting edge at this time.
    for obstacleIndex = 1:numel(obstacles)
        [shape, geometry] = azElInternal.obstacles.shapeAtTime( ...
            obstacles(obstacleIndex), controlTime_s(controlIndex));
        if ~geometry.Active
            hasLockedAssociation(obstacleIndex) = false;
            continue;
        end
        [edgeStart_deg, edgeEnd_deg] = geometryEdges(geometry);
        finiteVertices = isfinite(geometry.azimuth_deg) & ...
            isfinite(geometry.elevation_deg);
        vertices_deg = [geometry.azimuth_deg(finiteVertices), ...
            geometry.elevation_deg(finiteVertices)];
        hullIndex = convhull(vertices_deg(:, 1), vertices_deg(:, 2));
        hullShape = polyshape( ...
            vertices_deg(hullIndex(1:end - 1), :), "Simplify", false);
        geometryIsConvex = shape.NumRegions == 1 && ...
            abs(area(hullShape) - area(shape)) <= ...
            1e-9 * max(1, area(hullShape));
        [edgeIndex, nearestPoint_deg] = nearestEdge( ...
            seedPosition_deg(controlIndex, :), ...
            edgeStart_deg, edgeEnd_deg);
        edgeDelta_deg = edgeEnd_deg(edgeIndex, :) - ...
            edgeStart_deg(edgeIndex, :);
        leftNormal = [-edgeDelta_deg(2), edgeDelta_deg(1)];
        leftNormal = leftNormal / norm(leftNormal);
        probeScale_deg = max(1e-7, 1e-7 * norm(edgeDelta_deg));
        probe_deg = nearestPoint_deg + probeScale_deg * leftNormal;
        if isinterior(shape, probe_deg(1), probe_deg(2))
            outwardSign = -1;
        else
            outwardSign = 1;
        end
        association = template;
        association.ControlIndex = controlIndex;
        association.ObstacleIndex = obstacleIndex;
        association.EdgeIndex = edgeIndex;
        association.Tau = controlTau(controlIndex);
        association.OutwardSign = outwardSign;
        % A small separation prevents tolerance-level boundary contact.
        % Adaptive validation certifies motion between constraint points.
        association.Clearance_deg = max(1e-4, clearanceTolerance_deg);
        stationarySpeedTolerance_deg_s = 1e-12;
        geometryIsStationary = geometry.VertexSpeedBound_deg_s <= ...
            stationarySpeedTolerance_deg_s;
        if (~geometry.TopologyIsInterpolated || geometryIsStationary) && ...
                geometryIsConvex
            outwardNormal = outwardSign * leftNormal;
            association.UseSupport = true;
            association.SupportNormal = outwardNormal;
        end
        if geometryIsFixed || geometryIsStationary
            if association.UseSupport
                outwardNormal = association.SupportNormal;
                boundaryOffset_deg = max(vertices_deg * outwardNormal.');
            else
                outwardNormal = outwardSign * leftNormal;
                boundaryOffset_deg = edgeStart_deg(edgeIndex, :) * ...
                    outwardNormal.';
            end
            association.GeometryIsFixed = true;
            association.FixedNormal = outwardNormal;
            association.FixedBoundaryOffset_deg = boundaryOffset_deg;
        end
        usedLockedAssociation = false;
        geometryRequiresLock = geometry.VertexSpeedBound_deg_s > ...
            vehicleSpeedBound_deg_s;
        if geometryRequiresLock && hasLockedAssociation(obstacleIndex)
            [trialAssociation, lockIsSatisfied] = moveAssociation( ...
                lockedAssociation(obstacleIndex), geometry, ...
                edgeStart_deg, edgeEnd_deg, controlIndex, ...
                controlTau(controlIndex), geometryIsFixed, ...
                seedPosition_deg(controlIndex, :));
            if lockIsSatisfied
                association = trialAssociation;
                usedLockedAssociation = true;
            end
        end
        if geometryRequiresLock && ~usedLockedAssociation
            [association, ~] = moveAssociation( ...
                association, geometry, edgeStart_deg, edgeEnd_deg, ...
                controlIndex, controlTau(controlIndex), ...
                geometryIsFixed, seedPosition_deg(controlIndex, :));
        end
        if geometryRequiresLock
            lockedAssociation(obstacleIndex) = association;
            hasLockedAssociation(obstacleIndex) = true;
        else
            hasLockedAssociation(obstacleIndex) = false;
        end
        corridor(end + 1, 1) = association; %#ok<AGROW>
    end
end
end
function [association, isSatisfied] = moveAssociation( ...
        association, geometry, edgeStart_deg, edgeEnd_deg, ...
        controlIndex, controlTau, geometryIsFixed, point_deg)
% Keep a seed half-space until the seed no longer satisfies it.
finiteVertices = isfinite(geometry.azimuth_deg) & ...
    isfinite(geometry.elevation_deg);
vertices_deg = [geometry.azimuth_deg(finiteVertices), ...
    geometry.elevation_deg(finiteVertices)];
isSatisfied = false;
if association.UseSupport
    outwardNormal = association.SupportNormal;
    boundaryOffset_deg = max(vertices_deg * outwardNormal.');
elseif association.EdgeIndex <= size(edgeStart_deg, 1)
    edgeDelta_deg = edgeEnd_deg(association.EdgeIndex, :) - ...
        edgeStart_deg(association.EdgeIndex, :);
    if norm(edgeDelta_deg) <= eps
        return;
    end
    leftNormal = [-edgeDelta_deg(2), edgeDelta_deg(1)] / ...
        norm(edgeDelta_deg);
    outwardNormal = association.OutwardSign * leftNormal;
    boundaryOffset_deg = edgeStart_deg(association.EdgeIndex, :) * ...
        outwardNormal.';
else
    return;
end
pointProjection_deg = point_deg * outwardNormal.';
seedClearance_deg = pointProjection_deg - boundaryOffset_deg;
isSatisfied = seedClearance_deg >= association.Clearance_deg;
if ~isSatisfied
    return;
end
seedClearanceRetention = 0.25;
association.Clearance_deg = max(association.Clearance_deg, ...
    seedClearanceRetention * seedClearance_deg);
association.ControlIndex = controlIndex;
association.Tau = controlTau;
association.GeometryIsFixed = geometryIsFixed;
if geometryIsFixed
    association.FixedNormal = outwardNormal;
    association.FixedBoundaryOffset_deg = boundaryOffset_deg;
end
end
function [edgeStart_deg, edgeEnd_deg] = geometryEdges(geometry)
% Convert a NaN-separated canonical boundary to deterministic edges.
position_deg = [geometry.azimuth_deg, geometry.elevation_deg];
finiteRows = all(isfinite(position_deg), 2);
regionChanges = diff([false; finiteRows; false]);
regionStarts = find(regionChanges == 1);
regionStops = find(regionChanges == -1) - 1;
edgeStart_deg = zeros(0, 2);
edgeEnd_deg = zeros(0, 2);

% Convert every finite boundary region into closed directed edge pairs.
for regionIndex = 1:numel(regionStarts)
    vertices_deg = position_deg( ...
        regionStarts(regionIndex):regionStops(regionIndex), :);
    if size(vertices_deg, 1) < 2
        continue;
    end
    if all(vertices_deg(1, :) == vertices_deg(end, :))
        vertices_deg(end, :) = [];
    end
    edgeStart_deg = [edgeStart_deg; vertices_deg]; %#ok<AGROW>
    edgeEnd_deg = [edgeEnd_deg; ...
        vertices_deg([2:end 1], :)]; %#ok<AGROW>
end
end

function [edgeIndex, nearestPoint_deg] = nearestEdge( ...
        point_deg, edgeStart_deg, edgeEnd_deg)
% Select the closest edge and boundary point for a frozen association.
edgeDelta_deg = edgeEnd_deg - edgeStart_deg;
edgeLengthSquared_deg2 = sum(edgeDelta_deg.^2, 2);
projection = zeros(size(edgeLengthSquared_deg2));
validEdges = edgeLengthSquared_deg2 > 0;
projection(validEdges) = sum( ...
    (point_deg - edgeStart_deg(validEdges, :)) .* ...
    edgeDelta_deg(validEdges, :), 2) ./ ...
    edgeLengthSquared_deg2(validEdges);
projection = min(1, max(0, projection));
projectedPoint_deg = edgeStart_deg + projection .* edgeDelta_deg;
[~, edgeIndex] = min(sum((point_deg - projectedPoint_deg).^2, 2));
nearestPoint_deg = projectedPoint_deg(edgeIndex, :);
end

function polynomial = reconstructPolynomial(jerk_deg_s3, initialState, finalTime_s, segmentCount)
% Integrate the cited quadratic-jerk HS3 chain exactly on every segment.
duration_s = finalTime_s - initialState.time_s;
segmentDuration_s = duration_s / segmentCount;
startJerk_deg_s3 = jerk_deg_s3(1:2:end - 2, :);
midpointJerk_deg_s3 = jerk_deg_s3(2:2:end - 1, :);
endJerk_deg_s3 = jerk_deg_s3(3:2:end, :);
jerkLinear_deg_s3 = -3 * startJerk_deg_s3 + ...
    4 * midpointJerk_deg_s3 - endJerk_deg_s3;
jerkQuadratic_deg_s3 = 2 * startJerk_deg_s3 - ...
    4 * midpointJerk_deg_s3 + 2 * endJerk_deg_s3;
accelerationContribution = reshape(permute(cat(3, ...
    segmentDuration_s * startJerk_deg_s3, ...
    segmentDuration_s * jerkLinear_deg_s3 / 2, ...
    segmentDuration_s * jerkQuadratic_deg_s3 / 3), [3 1 2]), [], 2);
accelerationHistory = cumsum( ...
    [initialState.acceleration_deg_s2; accelerationContribution], 1);
acceleration_deg_s2 = accelerationHistory(1:3:end - 2, :);
velocityContribution = reshape(permute(cat(3, ...
    segmentDuration_s * acceleration_deg_s2, ...
    segmentDuration_s^2 * startJerk_deg_s3 / 2, ...
    segmentDuration_s^2 * jerkLinear_deg_s3 / 6, ...
    segmentDuration_s^2 * jerkQuadratic_deg_s3 / 12), [3 1 2]), [], 2);
velocityHistory = cumsum( ...
    [initialState.velocity_deg_s; velocityContribution], 1);
velocity_deg_s = velocityHistory(1:4:end - 3, :);
positionContribution = reshape(permute(cat(3, ...
    segmentDuration_s * velocity_deg_s, ...
    segmentDuration_s^2 * acceleration_deg_s2 / 2, ...
    segmentDuration_s^3 * startJerk_deg_s3 / 6, ...
    segmentDuration_s^3 * jerkLinear_deg_s3 / 24, ...
    segmentDuration_s^3 * jerkQuadratic_deg_s3 / 60), [3 1 2]), [], 2);
positionHistory = cumsum( ...
    [initialState.position_deg; positionContribution], 1);
position_deg = positionHistory(1:5:end - 4, :);
jerkPower_deg_s3 = cat(3, startJerk_deg_s3, ...
    jerkLinear_deg_s3, jerkQuadratic_deg_s3);
accelerationPower_deg_s2 = cat(3, acceleration_deg_s2, ...
    permute(reshape(accelerationContribution, 3, segmentCount, 2), [2 3 1]));
velocityPower_deg_s = cat(3, velocity_deg_s, ...
    permute(reshape(velocityContribution, 4, segmentCount, 2), [2 3 1]));
positionPower_deg = cat(3, position_deg, ...
    permute(reshape(positionContribution, 5, segmentCount, 2), [2 3 1]));
position_deg = positionHistory(end, :);
velocity_deg_s = velocityHistory(end, :);
acceleration_deg_s2 = accelerationHistory(end, :);
segmentStartTime_s = initialState.time_s + ...
    (0:segmentCount - 1).' * segmentDuration_s;
polynomial = struct( ...
    "SegmentCount", segmentCount, ...
    "SegmentStartTime_s", segmentStartTime_s, ...
    "SegmentDuration_s", segmentDuration_s, ...
    "FinalTime_s", finalTime_s, ...
    "positionPower_deg", positionPower_deg, ...
    "velocityPower_deg_s", velocityPower_deg_s, ...
    "accelerationPower_deg_s2", accelerationPower_deg_s2, ...
    "jerkPower_deg_s3", jerkPower_deg_s3, ...
    "TerminalState", struct( ...
    "position_deg", position_deg, ...
    "velocity_deg_s", velocity_deg_s, ...
    "acceleration_deg_s2", acceleration_deg_s2));
end

function [time_s, position_deg, velocity_deg_s, ...
        acceleration_deg_s2, jerk_deg_s3] = samplePolynomial( ...
        polynomial, sampleTime_s)
% Sample the exact segment polynomials without losing knot times.
startTime_s = polynomial.SegmentStartTime_s(1);
uniformTime_s = (startTime_s:sampleTime_s:polynomial.FinalTime_s).';
time_s = unique([uniformTime_s; polynomial.SegmentStartTime_s; ...
    polynomial.FinalTime_s]);
[time_s, position_deg, velocity_deg_s, ...
    acceleration_deg_s2, jerk_deg_s3] = azElInternal.evaluatePolynomial( ...
    polynomial, time_s);
end

function [jerk_deg_s3, finalTime_s] = unpackDecision( ...
        decision, isEarliestArrival, fixedFinalTime_s, controlCount)
% Recover jerk ordinates and final time from the HS3 decision vector.
jerkValueCount = 2 * controlCount;
jerk_deg_s3 = reshape(decision(1:jerkValueCount), controlCount, 2);
if isEarliestArrival
    finalTime_s = decision(end);
else
    finalTime_s = fixedFinalTime_s;
end
end

function duration_s = durationLowerBound( ...
        initialState, goalState, limits, latestFinalTime_s)
% Compute an input-driven lower bound without claiming exact optimality.
if isfield(goalState, "targetTime_s") && ...
        ~isempty(goalState.targetTime_s)
    duration_s = movingTargetDurationLowerBound( ...
        initialState, goalState, limits);
    return;
end
goalPosition_deg = azElInternal.goalPositionAtTime( ...
    goalState, latestFinalTime_s);
displacement_deg = abs(goalPosition_deg - initialState.position_deg);
velocityBound_s = displacement_deg ./ limits.maxVelocity_deg_s;
duration_s = max([1e-3, velocityBound_s]);
end

function duration_s = movingTargetDurationLowerBound( ...
        initialState, goalState, limits)
% Bound linear-target interception without using a future snapshot.
duration_s = 1e-3;
if goalState.InterpolationMethod ~= "linear" || ...
        initialState.time_s < goalState.targetTime_s(1) || ...
        initialState.time_s > goalState.targetTime_s(end)
    return;
end
targetStart_deg = interp1( ...
    goalState.targetTime_s, goalState.targetPosition_deg, ...
    initialState.time_s, "linear");
targetVelocity_deg_s = diff(goalState.targetPosition_deg, 1, 1) ./ diff(goalState.targetTime_s);
targetSpeedBound_deg_s = max(abs(targetVelocity_deg_s), [], 1);
initialDistance_deg = abs(targetStart_deg - initialState.position_deg);
closingSpeedBound_deg_s = limits.maxVelocity_deg_s + ...
    targetSpeedBound_deg_s;
duration_s = max([duration_s, initialDistance_deg ./ closingSpeedBound_deg_s]);
end

function candidate = emptyCandidate(seed, segmentCount)
% Define the same candidate schema for early solver failures.
candidate = struct( ...
    "OptimizerFeasible", false, ...
    "Message", "HS3 was not run.", ...
    "TerminationReason", "notRun", ...
    "SeedIndex", seed.Index, ...
    "SeedSource", seed.Source, ...
    "FinalTime_s", NaN, ...
    "MotionDuration_s", NaN, ...
    "IntegratedSquaredJerk_deg2_s5", Inf, ...
    "MaximumConstraintViolation", Inf, ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2), ...
    "Polynomial", struct("SegmentCount", segmentCount), ...
    "ControlTau", zeros(0, 1), ...
    "ControlJerk_deg_s3", zeros(0, 2), ...
    "Corridor", struct([]), ...
    "SeedCorridorBoundary_deg", seed.CorridorBoundary_deg, ...
    "SeedCorridor", struct([]), ...
    "SolverDiagnostics", ...
    azElPlannerMethods.hs3.internal.motion.emptyHs3SolverDiagnostics());
end
