function trial = retimeCoppSmoothPath( ...
        smoothPath, initialState, goalState, limits, options, ...
        departureTime_s, failureMessage)
%% Section 0: Header & Readme
% SYNTAX
%   trial = azElExperimental.retimeCoppSmoothPath( ...
%       smoothPath, initialState, goalState, limits, options, ...
%       departureTime_s)
%   trial = azElExperimental.retimeCoppSmoothPath( ...
%       smoothPath, initialState, goalState, limits, options, ...
%       departureTime_s, failureMessage)
%**************************************************************************
% PURPOSE
%   - Retime one fixed, regular azimuth/elevation curve with COPP's TOPP3
%     SOCP solver while preserving the supplied geometry exactly.
%   - Return sampled kinematics plus an independent dense numerical check of
%     the composed trajectory between COPP stations.
%**************************************************************************
% INPUTS
%   - smoothPath (scalar struct)
%       Regular fixed path with arc-length samples, derivatives through
%       third order, and line/quintic primitives.
%   - initialState, goalState (scalar structs)
%       time_s, position_deg, velocity_deg_s, and acceleration_deg_s2.
%   - limits (scalar struct)
%       Finite positive maxVelocity_deg_s, maxAcceleration_deg_s2, and
%       maxJerk_deg_s3 values, each scalar or two-element.
%   - options (scalar struct)
%       GoalTimeMode and SampleTime_s are required.
%   - departureTime_s (finite numeric scalar)
%       Earliest permitted motion-start time.
%   - failureMessage (scalar text, optional; default "")
%       A nonempty upstream failure returns the stable timed-path schema
%       without attempting a COPP solve.
%**************************************************************************
% OUTPUTS
%   - trial (scalar struct)
%       Stable success-or-failure COPP trial record. Expected solver or
%       timing infeasibility returns Success=false; invalid contracts throw.
%**************************************************************************
% UNITS
%   - Position and arc length are degrees. Time derivatives use seconds.
%**************************************************************************

%% Section 1: Validate Inputs & Initialize The Trial

if nargin < 7
    failureMessage = "";
end
failureMessage = string(failureMessage);
if ~isscalar(failureMessage)
    error("retimeCoppSmoothPath:InvalidFailureMessage", ...
        "failureMessage must be scalar text.");
end
trial = emptyTrial();
trial.Limits = limits;
trial.Options = options;
trial.DepartureCandidateTime_s = departureTime_s;
if strlength(failureMessage) > 0
    trial.Message = failureMessage;
    trial.TerminationReason = "upstreamFailure";
    return;
end
requiredPathFields = [ ...
    "Success", "TotalLength_deg", "SampleArcLength_deg", ...
    "position_deg", "tangent", "secondDerivative_deg_inv", ...
    "thirdDerivative_deg_inv2", "Primitives", ...
    "MandatoryStopCount"];
if ~isstruct(smoothPath) || ~isscalar(smoothPath) || ...
        ~all(isfield(smoothPath, requiredPathFields))
    error("retimeCoppSmoothPath:InvalidSmoothPath", ...
        "smoothPath must contain the maintained fixed-path schema.");
end
if ~smoothPath.Success
    trial.Message = "The supplied smooth path is not valid.";
    trial.TerminationReason = "invalidSmoothPath";
    return;
end
if smoothPath.MandatoryStopCount > 0
    trial.Message = ...
        "COPP TOPP3 does not represent stationary interior path nodes.";
    trial.TerminationReason = "interiorStopUnsupported";
    return;
end
if isempty(which("copp.version"))
    trial.Message = ...
        "COPP for MATLAB is not installed or is not on the MATLAB path.";
    trial.TerminationReason = "missingDependency";
    return;
end

validateState(initialState, "initialState");
validateState(goalState, "goalState");
validateattributes(departureTime_s, {'numeric'}, ...
    {'real', 'finite', 'scalar'});
if ~isstruct(options) || ~isscalar(options) || ...
        ~all(isfield(options, ["GoalTimeMode", "SampleTime_s"]))
    error("retimeCoppSmoothPath:InvalidOptions", ...
        "options must contain GoalTimeMode and SampleTime_s.");
end
validateattributes(options.SampleTime_s, {'numeric'}, ...
    {'real', 'finite', 'positive', 'scalar'});
limits = normalizeLimits(limits);
endpointTolerance = 1e-10;
initialSpeedExceedsLimit = any(abs(initialState.velocity_deg_s) > ...
    limits.maxVelocity_deg_s .* (1 + endpointTolerance));
goalSpeedExceedsLimit = any(abs(goalState.velocity_deg_s) > ...
    limits.maxVelocity_deg_s .* (1 + endpointTolerance));
if initialSpeedExceedsLimit || goalSpeedExceedsLimit
    trial.Message = ...
        "An endpoint speed exceeds the configured per-axis velocity limit.";
    trial.TerminationReason = "endpointConstraintInfeasible";
    return;
end
initialAccelerationExceedsLimit = any( ...
    abs(initialState.acceleration_deg_s2) > ...
    limits.maxAcceleration_deg_s2 .* (1 + endpointTolerance));
goalAccelerationExceedsLimit = any( ...
    abs(goalState.acceleration_deg_s2) > ...
    limits.maxAcceleration_deg_s2 .* (1 + endpointTolerance));
if initialAccelerationExceedsLimit || goalAccelerationExceedsLimit
    trial.Message = "An endpoint acceleration exceeds the configured " + ...
        "per-axis acceleration limit.";
    trial.TerminationReason = "endpointConstraintInfeasible";
    return;
end

sourceStation_s_deg = double(smoothPath.SampleArcLength_deg(:));
sourceStationCount = numel(sourceStation_s_deg);
sampleShapesAgree = sourceStationCount >= 3 && ...
    size(smoothPath.position_deg, 1) == sourceStationCount && ...
    size(smoothPath.tangent, 1) == sourceStationCount && ...
    size(smoothPath.secondDerivative_deg_inv, 1) == sourceStationCount && ...
    size(smoothPath.thirdDerivative_deg_inv2, 1) == sourceStationCount;
if ~sampleShapesAgree || any(diff(sourceStation_s_deg) <= 0)
    error("retimeCoppSmoothPath:InvalidPathSamples", ...
        "Path samples must have matching rows and strictly increasing arc length.");
end
if abs(sourceStation_s_deg(1)) > 1e-10 || ...
        abs(sourceStation_s_deg(end) - smoothPath.TotalLength_deg) > 1e-8
    error("retimeCoppSmoothPath:InvalidArcLengthRange", ...
        "Path samples must cover [0, smoothPath.TotalLength_deg].");
end
if any(abs(vecnorm(smoothPath.tangent, 2, 2) - 1) > 1e-7)
    error("retimeCoppSmoothPath:IrregularPath", ...
        "Every arc-length tangent must have unit norm.");
end

endpoint = azElInternal.sampleAzElSmoothPath(smoothPath, ...
    [sourceStation_s_deg(1); sourceStation_s_deg(end)]);
positionTolerance_deg = 1e-8;
if norm(endpoint.position_deg(1, :) - initialState.position_deg) > ...
        positionTolerance_deg || ...
        norm(endpoint.position_deg(2, :) - goalState.position_deg) > ...
        positionTolerance_deg
    error("retimeCoppSmoothPath:EndpointMismatch", ...
        "smoothPath endpoints must match initialState and goalState positions.");
end
[initialA_deg2_s2, initialB_deg_s2] = ...
    boundaryPathState(initialState, endpoint, 1);
[goalA_deg2_s2, goalB_deg_s2] = ...
    boundaryPathState(goalState, endpoint, 2);

% Plot samples and optimization stations serve different purposes. Feeding
% the 0.05-degree plotting grid to SOCP made problem size grow unnecessarily
% with route length. Exact primitives let COPP sample its own smaller grid:
% straight pieces need only resolve the timing law, while curved blends use
% finer stations for changing geometry. The interval certificate below
% remains authoritative between all optimization stations.
nominalLineStationSpacing_deg = 0.012;
maximumTotalLineIntervalCount = 800;
maximumCurvedStationSpacing_deg = 0.002;
primitiveTypes = string({smoothPath.Primitives.Type});
primitiveLengths_deg = [smoothPath.Primitives.Length_deg];
totalLineLength_deg = sum( ...
    primitiveLengths_deg(primitiveTypes == "line"));
lineStationSpacing_deg = max( ...
    nominalLineStationSpacing_deg, ...
    totalLineLength_deg / maximumTotalLineIntervalCount);
station_s_deg = smoothPath.Primitives(1).StartArcLength_deg;
for primitiveIndex = 1:numel(smoothPath.Primitives)
    primitive = smoothPath.Primitives(primitiveIndex);
    if primitive.Type == "quintic"
        maximumSpacing_deg = maximumCurvedStationSpacing_deg;
    else
        % Short routes retain the resolution needed for accurate stationary
        % boundary timing. Long straight geometry shares one global interval
        % budget so extra route vertices cannot multiply SOCP size.
        maximumSpacing_deg = lineStationSpacing_deg;
    end
    intervalCount = max(1, ...
        ceil(primitive.Length_deg / maximumSpacing_deg));
    primitiveStation_s_deg = linspace( ...
        primitive.StartArcLength_deg, primitive.EndArcLength_deg, ...
        intervalCount + 1).';
    station_s_deg = [station_s_deg; ...
        primitiveStation_s_deg(2:end)]; %#ok<AGROW>
end
station_s_deg = unique(station_s_deg);
stationPath = azElInternal.sampleAzElSmoothPath( ...
    smoothPath, station_s_deg);
stationCount = numel(station_s_deg);

%% Section 2: Solve TOPP2 Seed & Iterated TOPP3 Problems

robot = copp.Robot(2, Capacity=stationCount);
robotCleanup = onCleanup(@() robot.release());
robot.append_s(station_s_deg);
robot.set_q_3rd( ...
    double(stationPath.position_deg.'), ...
    double(stationPath.tangent.'), ...
    double(stationPath.secondDerivative_deg_inv.'), ...
    double(stationPath.thirdDerivative_deg_inv2.'));
% Curved geometry needs room for between-station derivative variation.
% Exact lines have constant path derivatives, so only a small numerical
% reserve is needed. The continuous certificate below remains authoritative
% in both cases and rejects any reserve that proves insufficient.
hasCurvedPrimitive = any( ...
    string({smoothPath.Primitives.Type}) == "quintic");
if hasCurvedPrimitive
    solverLimitScale = 0.85;
else
    solverLimitScale = 0.999;
end
robot.add_velocity_limits( ...
    solverLimitScale * limits.maxVelocity_deg_s(:), ...
    -solverLimitScale * limits.maxVelocity_deg_s(:));
robot.add_acceleration_limits( ...
    solverLimitScale * limits.maxAcceleration_deg_s2(:), ...
    -solverLimitScale * limits.maxAcceleration_deg_s2(:));
robot.add_jerk_limits( ...
    solverLimitScale * limits.maxJerk_deg_s3(:), ...
    -solverLimitScale * limits.maxJerk_deg_s3(:));

aBoundary_deg2_s2 = [initialA_deg2_s2, goalA_deg2_s2];
bBoundary_deg_s2 = [initialB_deg_s2, goalB_deg_s2];
solverTimer = tic;
try
    seedProblem = copp.solver.topp2_ra.Problem( ...
        robot, ...
        idx_s_interval=[1, stationCount], ...
        a_boundary=aBoundary_deg2_s2);
    aLinearization_deg2_s2 = copp.solver.topp2_ra.solve(seedProblem);

    % TOPP3 linearizes jerk constraints around a path-speed profile. The
    % official example performs repeated solves; convergence, rather than a
    % scenario name or path shape, determines when this loop stops.
    maximumPassCount = 2;
    relativeDurationTolerance = 1e-7;
    passDuration_s = NaN(maximumPassCount, 1);
    bestDuration_s = Inf;
    bestProfile = [];
    previousDuration_s = Inf;
    solverOptions = copp.solver.topp3_socp.Options();
    for passIndex = 1:maximumPassCount
        problem = copp.solver.topp3_socp.Problem( ...
            robot, aLinearization_deg2_s2, ...
            idx_s_start=1, ...
            a_boundary=aBoundary_deg2_s2, ...
            b_boundary=bBoundary_deg_s2, ...
            num_stationary_max=1);
        profile = copp.solver.topp3_socp.solve(problem, solverOptions);
        [duration_s, ~] = copp.interpolation.s_to_t_topp3( ...
            station_s_deg, profile);
        passDuration_s(passIndex) = duration_s;
        if duration_s < bestDuration_s
            bestDuration_s = duration_s;
            bestProfile = profile;
        end
        relativeImprovement = ...
            (previousDuration_s - duration_s) / max(duration_s, 1);
        aLinearization_deg2_s2 = profile.a;
        previousDuration_s = duration_s;
        if passIndex >= 2 && relativeImprovement >= 0 && ...
                relativeImprovement < relativeDurationTolerance
            break;
        end
    end
catch solverError
    trial.Message = "COPP TOPP3 failed: " + string(solverError.message);
    trial.TerminationReason = "coppSolverFailure";
    trial.SolverElapsedTime_s = toc(solverTimer);
    return;
end
solverElapsedTime_s = toc(solverTimer);
passDuration_s = passDuration_s(1:passIndex);
profile = bestProfile;
[minimumMotionDuration_s, stationTime_s] = ...
    copp.interpolation.s_to_t_topp3(station_s_deg, profile);

%% Section 3: Resolve Departure, Arrival & Optional Initial Hold

minimumWaitDuration_s = max(0, departureTime_s - initialState.time_s);
goalTimeMode = lower(string(options.GoalTimeMode));
availableDuration_s = goalState.time_s - initialState.time_s;
timeTolerance_s = 1e-10 * max(1, abs(goalState.time_s));
if goalTimeMode == "fixedarrival"
    waitDuration_s = availableDuration_s - minimumMotionDuration_s;
    if waitDuration_s + timeTolerance_s < minimumWaitDuration_s
        trial.Message = sprintf( ...
            "COPP motion and departure need %.9g s; only %.9g s are available.", ...
            minimumWaitDuration_s + minimumMotionDuration_s, ...
            availableDuration_s);
        trial.TerminationReason = "goalTimeInfeasible";
        return;
    end
    waitDuration_s = max(waitDuration_s, 0);
    arrivalTime_s = goalState.time_s;
elseif goalTimeMode == "earliestarrival"
    waitDuration_s = minimumWaitDuration_s;
    arrivalTime_s = initialState.time_s + waitDuration_s + ...
        minimumMotionDuration_s;
    if arrivalTime_s > goalState.time_s + timeTolerance_s
        trial.Message = sprintf( ...
            "COPP earliest arrival %.9g s exceeds the goal horizon %.9g s.", ...
            arrivalTime_s, goalState.time_s);
        trial.TerminationReason = "goalTimeInfeasible";
        return;
    end
else
    error("retimeCoppSmoothPath:InvalidGoalTimeMode", ...
        "options.GoalTimeMode must be earliestArrival or fixedArrival.");
end
initialStateIsMoving = norm(initialState.velocity_deg_s) > 1e-10 || ...
    norm(initialState.acceleration_deg_s2) > 1e-10;
if waitDuration_s > timeTolerance_s && initialStateIsMoving
    trial.Message = ...
        "An initial hold is incompatible with the moving initial state.";
    trial.TerminationReason = "movingHoldUnsupported";
    return;
end

motionStartTime_s = initialState.time_s + waitDuration_s;

%% Section 4: Sample The Exact Geometry & COPP Timing Law

relativeMotionTime_s = unique([ ...
    (0:options.SampleTime_s:minimumMotionDuration_s).'; ...
    stationTime_s; minimumMotionDuration_s]);
motionArcLength_deg = copp.interpolation.t_to_s_topp3( ...
    station_s_deg, profile, stationTime_s, ...
    t_sample=relativeMotionTime_s);
motionPath = azElInternal.sampleAzElSmoothPath( ...
    smoothPath, motionArcLength_deg);
[pathSpeed_deg_s, pathAcceleration_deg_s2, pathJerk_deg_s3] = ...
    sampleCoppProfile(station_s_deg, profile, stationTime_s, ...
    relativeMotionTime_s, motionArcLength_deg);
[motionVelocity_deg_s, motionAcceleration_deg_s2, motionJerk_deg_s3] = ...
    composeKinematics(motionPath, pathSpeed_deg_s, ...
    pathAcceleration_deg_s2, pathJerk_deg_s3);

if waitDuration_s > timeTolerance_s
    holdTime_s = unique([ ...
        (initialState.time_s:options.SampleTime_s:motionStartTime_s).'; ...
        motionStartTime_s]);
    holdTime_s(end) = [];
else
    holdTime_s = zeros(0, 1);
end
holdCount = numel(holdTime_s);
time_s = [holdTime_s; motionStartTime_s + relativeMotionTime_s];
position_deg = [ ...
    repmat(initialState.position_deg, holdCount, 1); ...
    motionPath.position_deg];
velocity_deg_s = [zeros(holdCount, 2); motionVelocity_deg_s];
acceleration_deg_s2 = [ ...
    zeros(holdCount, 2); motionAcceleration_deg_s2];
jerk_deg_s3 = [zeros(holdCount, 2); motionJerk_deg_s3];

%% Section 5: Densely Verify The Returned Kinematics

% COPP enforces constraints on its station grid but the v0.2.2 MATLAB API
% does not return a continuous interval certificate. A separate dense pass
% therefore checks the actual composed trajectory and is reported honestly
% as numerical verification, not as continuous certification.
verificationStep_s = min(options.SampleTime_s, 0.005);
verificationTime_s = unique([ ...
    (0:verificationStep_s:minimumMotionDuration_s).'; ...
    stationTime_s; minimumMotionDuration_s]);
verificationArcLength_deg = copp.interpolation.t_to_s_topp3( ...
    station_s_deg, profile, stationTime_s, ...
    t_sample=verificationTime_s);
verificationPath = azElInternal.sampleAzElSmoothPath( ...
    smoothPath, verificationArcLength_deg);
[verificationSpeed_deg_s, verificationAcceleration_deg_s2, ...
    verificationJerk_deg_s3] = sampleCoppProfile( ...
    station_s_deg, profile, stationTime_s, verificationTime_s, ...
    verificationArcLength_deg);
[verificationVelocity_deg_s, verificationAccelerationVector_deg_s2, ...
    verificationJerkVector_deg_s3] = composeKinematics( ...
    verificationPath, verificationSpeed_deg_s, ...
    verificationAcceleration_deg_s2, verificationJerk_deg_s3);

peakVelocity_deg_s = max(abs(verificationVelocity_deg_s), [], 1);
peakAcceleration_deg_s2 = max( ...
    abs(verificationAccelerationVector_deg_s2), [], 1);
peakJerk_deg_s3 = max(abs(verificationJerkVector_deg_s3), [], 1);
relativeLimitTolerance = 1e-7;
velocitySatisfied = all(peakVelocity_deg_s <= ...
    limits.maxVelocity_deg_s .* (1 + relativeLimitTolerance));
accelerationSatisfied = all(peakAcceleration_deg_s2 <= ...
    limits.maxAcceleration_deg_s2 .* (1 + relativeLimitTolerance));
jerkSatisfied = all(peakJerk_deg_s3 <= ...
    limits.maxJerk_deg_s3 .* (1 + relativeLimitTolerance));
finiteJerkNumericallyVerified = velocitySatisfied && ...
    accelerationSatisfied && jerkSatisfied;

%% Section 6: Assemble The Trial Record

trial.Success = finiteJerkNumericallyVerified;
trial.Message = ...
    "COPP TOPP3 retiming and dense numerical verification succeeded.";
trial.TerminationReason = "goalReached";
if ~trial.Success
    trial.Message = ...
        "COPP returned a profile that failed dense numerical verification.";
    trial.TerminationReason = "denseVerificationFailed";
end
trial.time_s = time_s;
trial.position_deg = position_deg;
trial.velocity_deg_s = velocity_deg_s;
trial.acceleration_deg_s2 = acceleration_deg_s2;
trial.jerk_deg_s3 = jerk_deg_s3;
trial.PathPosition_deg = smoothPath.position_deg;
trial.WaypointTime_s = motionStartTime_s + stationTime_s;
trial.DepartureCandidateTime_s = departureTime_s;
trial.MotionStartTime_s = motionStartTime_s;
trial.WaitDuration_s = waitDuration_s;
trial.MinimumMotionDuration_s = minimumMotionDuration_s;
trial.ArrivalTime_s = arrivalTime_s;
trial.GoalLineInterceptTime_s = arrivalTime_s;
trial.SolverElapsedTime_s = solverElapsedTime_s;
trial.StationCount = stationCount;
trial.CoppVersion = string(copp.version());
trial.LinearizationPassCount = passIndex;
trial.PassDuration_s = passDuration_s;
trial.SolverLimitScale = solverLimitScale;
trial.ProfileA_deg2_s2 = profile.a;
trial.ProfileB_deg_s2 = profile.b;
trial.SmoothPath = smoothPath;
trial.RetimerType = "coppTopp3Socp";
trial.MotionType = "velocityCarrying";
trial.Limits = limits;
trial.Options = struct( ...
    "GoalTimeMode", options.GoalTimeMode, ...
    "SampleTime_s", options.SampleTime_s);
trial.CurveArcLength_deg = station_s_deg;
trial.CurveNodeTime_s = motionStartTime_s + stationTime_s;
trial.CurveSpeedSquared_deg2_s2 = profile.a;
trial.CurveSpeed_deg_s = sqrt(max(profile.a, 0));
trial.CurveTangentialAcceleration_deg_s2 = profile.b;
[~, ~, stationJerk_deg_s3] = sampleCoppProfile( ...
    station_s_deg, profile, stationTime_s, stationTime_s, station_s_deg);
trial.CurveTangentialJerk_deg_s3 = stationJerk_deg_s3;
trial.SampleArcLength_deg = [zeros(holdCount, 1); motionArcLength_deg];
trial.SampleSpeed_deg_s = [zeros(holdCount, 1); pathSpeed_deg_s];
trial.SampleTangentialAcceleration_deg_s2 = [ ...
    zeros(holdCount, 1); pathAcceleration_deg_s2];
trial.SampleTangentialJerk_deg_s3 = [ ...
    zeros(holdCount, 1); pathJerk_deg_s3];
mandatoryStopArcLength_deg = zeros(0, 1);
if isfield(smoothPath, "MandatoryStopArcLength_deg")
    mandatoryStopArcLength_deg = ...
        smoothPath.MandatoryStopArcLength_deg;
end
trial.ConstraintDiagnostics = struct( ...
    "PeakVelocity_deg_s", peakVelocity_deg_s, ...
    "PeakAcceleration_deg_s2", peakAcceleration_deg_s2, ...
    "PeakJerk_deg_s3", peakJerk_deg_s3, ...
    "VelocitySatisfied", velocitySatisfied, ...
    "AccelerationSatisfied", accelerationSatisfied, ...
    "JerkSatisfied", jerkSatisfied, ...
    "Satisfied", trial.Success, ...
    "VelocityMargin_deg_s", ...
        limits.maxVelocity_deg_s - peakVelocity_deg_s, ...
    "AccelerationMargin_deg_s2", ...
        limits.maxAcceleration_deg_s2 - peakAcceleration_deg_s2, ...
    "JerkMargin_deg_s3", ...
        limits.maxJerk_deg_s3 - peakJerk_deg_s3, ...
    "JerkConstrained", true, ...
    "FiniteJerkCertified", false, ...
    "FiniteJerkNumericallyVerified", ...
        finiteJerkNumericallyVerified, ...
    "ContinuousJerkCertified", false, ...
    "VerificationMethod", "denseTimeSampling", ...
    "VerificationSampleTime_s", verificationStep_s, ...
    "VerificationSampleCount", numel(verificationTime_s), ...
    "MandatoryStopCount", smoothPath.MandatoryStopCount, ...
    "MandatoryStopArcLength_deg", mandatoryStopArcLength_deg, ...
    "ContinuousCertificate", struct());
end

%% Section 7: Local Functions

function trial = emptyTrial()
%% Section 0: Header & Readme
% SYNTAX
%   trial = emptyTrial()
%**************************************************************************
% PURPOSE
%   - Define one stable COPP trial schema for every exit path.
%**************************************************************************
% INPUTS
%   - None.
%**************************************************************************
% OUTPUTS
%   - trial (scalar struct)
%**************************************************************************
% UNITS
%   - Field suffixes state physical units.
%**************************************************************************
diagnostics = struct( ...
    "PeakVelocity_deg_s", [NaN NaN], ...
    "PeakAcceleration_deg_s2", [NaN NaN], ...
    "PeakJerk_deg_s3", [NaN NaN], ...
    "VelocitySatisfied", false, ...
    "AccelerationSatisfied", false, ...
    "JerkSatisfied", false, ...
    "Satisfied", false, ...
    "VelocityMargin_deg_s", [NaN NaN], ...
    "AccelerationMargin_deg_s2", [NaN NaN], ...
    "JerkMargin_deg_s3", [NaN NaN], ...
    "JerkConstrained", true, ...
    "FiniteJerkCertified", false, ...
    "FiniteJerkNumericallyVerified", false, ...
    "ContinuousJerkCertified", false, ...
    "VerificationMethod", "notPerformed", ...
    "VerificationSampleTime_s", NaN, ...
    "VerificationSampleCount", 0, ...
    "MandatoryStopCount", 0, ...
    "MandatoryStopArcLength_deg", zeros(0, 1), ...
    "ContinuousCertificate", struct());
trial = struct( ...
    "Success", false, ...
    "Message", "COPP retiming was not attempted.", ...
    "TerminationReason", "notAttempted", ...
    "time_s", zeros(0, 1), ...
    "position_deg", zeros(0, 2), ...
    "velocity_deg_s", zeros(0, 2), ...
    "acceleration_deg_s2", zeros(0, 2), ...
    "jerk_deg_s3", zeros(0, 2), ...
    "PathPosition_deg", zeros(0, 2), ...
    "WaypointTime_s", zeros(0, 1), ...
    "DepartureCandidateTime_s", NaN, ...
    "MotionStartTime_s", NaN, ...
    "WaitDuration_s", NaN, ...
    "MinimumMotionDuration_s", NaN, ...
    "ArrivalTime_s", NaN, ...
    "GoalLineInterceptTime_s", NaN, ...
    "SegmentProfiles", struct([]), ...
    "SolverElapsedTime_s", NaN, ...
    "StationCount", 0, ...
    "CoppVersion", "", ...
    "LinearizationPassCount", 0, ...
    "PassDuration_s", zeros(0, 1), ...
    "SolverLimitScale", NaN, ...
    "ProfileA_deg2_s2", zeros(0, 1), ...
    "ProfileB_deg_s2", zeros(0, 1), ...
    "SmoothPath", struct(), ...
    "RetimerType", "coppTopp3Socp", ...
    "MotionType", "velocityCarrying", ...
    "Limits", struct(), ...
    "Options", struct(), ...
    "CurveArcLength_deg", zeros(0, 1), ...
    "CurveNodeTime_s", zeros(0, 1), ...
    "CurveSpeed_deg_s", zeros(0, 1), ...
    "CurveSpeedSquared_deg2_s2", zeros(0, 1), ...
    "CurveTangentialAcceleration_deg_s2", zeros(0, 1), ...
    "CurveTangentialJerk_deg_s3", zeros(0, 1), ...
    "SampleArcLength_deg", zeros(0, 1), ...
    "SampleSpeed_deg_s", zeros(0, 1), ...
    "SampleTangentialAcceleration_deg_s2", zeros(0, 1), ...
    "SampleTangentialJerk_deg_s3", zeros(0, 1), ...
    "CurvatureDiscontinuityStopCount", 0, ...
    "ConstraintDiagnostics", diagnostics);
end

function validateState(state, argumentName)
%% Section 0: Header & Readme
% SYNTAX
%   validateState(state, argumentName)
%**************************************************************************
% PURPOSE
%   - Validate one normalized planner boundary state.
%**************************************************************************
% INPUTS
%   - state (scalar struct), argumentName (scalar text)
%**************************************************************************
% OUTPUTS
%   - None. Invalid state data throws an identified error.
%**************************************************************************
% UNITS
%   - Position is degrees and time derivatives use seconds.
%**************************************************************************
required = ["time_s", "position_deg", "velocity_deg_s", ...
    "acceleration_deg_s2"];
if ~isstruct(state) || ~isscalar(state) || ~all(isfield(state, required))
    error("retimeCoppSmoothPath:InvalidState", ...
        "%s must contain time, position, velocity, and acceleration.", ...
        argumentName);
end
validateattributes(state.time_s, {'numeric'}, ...
    {'real', 'finite', 'scalar'});
validateattributes(state.position_deg, {'numeric'}, ...
    {'real', 'finite', 'numel', 2});
validateattributes(state.velocity_deg_s, {'numeric'}, ...
    {'real', 'finite', 'numel', 2});
validateattributes(state.acceleration_deg_s2, {'numeric'}, ...
    {'real', 'finite', 'numel', 2});
end

function limits = normalizeLimits(limits)
%% Section 0: Header & Readme
% SYNTAX
%   limits = normalizeLimits(limits)
%**************************************************************************
% PURPOSE
%   - Normalize three required finite per-axis limit vectors.
%**************************************************************************
% INPUTS
%   - limits (scalar struct)
%**************************************************************************
% OUTPUTS
%   - limits (scalar struct with 1-by-2 double fields)
%**************************************************************************
% UNITS
%   - Limits use deg/s, deg/s^2, and deg/s^3.
%**************************************************************************
names = ["maxVelocity_deg_s", "maxAcceleration_deg_s2", ...
    "maxJerk_deg_s3"];
if ~isstruct(limits) || ~isscalar(limits) || ~all(isfield(limits, names))
    error("retimeCoppSmoothPath:InvalidLimits", ...
        "limits must contain finite velocity, acceleration, and jerk fields.");
end
for nameIndex = 1:numel(names)
    name = names(nameIndex);
    value = limits.(name);
    validateattributes(value, {'numeric'}, ...
        {'real', 'finite', 'positive', 'nonempty', 'vector'});
    if ~(isscalar(value) || numel(value) == 2)
        error("retimeCoppSmoothPath:InvalidLimits", ...
            "%s must be scalar or two-element.", name);
    end
    value = reshape(double(value), 1, []);
    if isscalar(value)
        value = repmat(value, 1, 2);
    end
    limits.(name) = value;
end
end

function [a_deg2_s2, b_deg_s2] = ...
        boundaryPathState(state, endpoint, endpointIndex)
%% Section 0: Header & Readme
% SYNTAX
%   [a_deg2_s2, b_deg_s2] = ...
%       boundaryPathState(state, endpoint, endpointIndex)
%**************************************************************************
% PURPOSE
%   - Convert Cartesian endpoint derivatives into COPP path-domain state.
%**************************************************************************
% INPUTS
%   - state (scalar struct), endpoint (path sample struct)
%   - endpointIndex (1 or 2)
%**************************************************************************
% OUTPUTS
%   - a_deg2_s2 (squared path speed), b_deg_s2 (path acceleration)
%**************************************************************************
% UNITS
%   - a is deg^2/s^2 and b is deg/s^2.
%**************************************************************************
tangent = endpoint.tangent(endpointIndex, :);
second = endpoint.secondDerivative_deg_inv(endpointIndex, :);
velocity_deg_s = double(state.velocity_deg_s(:).');
acceleration_deg_s2 = double(state.acceleration_deg_s2(:).');
tolerance = 1e-8;
pathSpeed_deg_s = dot(velocity_deg_s, tangent);
if pathSpeed_deg_s < -tolerance || ...
        norm(velocity_deg_s - pathSpeed_deg_s * tangent) > tolerance
    error("retimeCoppSmoothPath:BoundaryVelocityMismatch", ...
        "Boundary velocity must point forward along the fixed path tangent.");
end
pathSpeed_deg_s = max(pathSpeed_deg_s, 0);
a_deg2_s2 = pathSpeed_deg_s^2;
normalAcceleration_deg_s2 = second * a_deg2_s2;
b_deg_s2 = dot( ...
    acceleration_deg_s2 - normalAcceleration_deg_s2, tangent);
reconstructedAcceleration_deg_s2 = ...
    normalAcceleration_deg_s2 + tangent * b_deg_s2;
if norm(acceleration_deg_s2 - reconstructedAcceleration_deg_s2) > ...
        tolerance
    error("retimeCoppSmoothPath:BoundaryAccelerationMismatch", ...
        "Boundary acceleration is incompatible with the fixed path.");
end
end

function [pathSpeed_deg_s, pathAcceleration_deg_s2, pathJerk_deg_s3] = ...
        sampleCoppProfile(station_s_deg, profile, stationTime_s, ...
        sampleTime_s, sample_s_deg)
%% Section 0: Header & Readme
% SYNTAX
%   [pathSpeed_deg_s, pathAcceleration_deg_s2, pathJerk_deg_s3] = ...
%       sampleCoppProfile(station_s_deg, profile, stationTime_s, ...
%       sampleTime_s, sample_s_deg)
%**************************************************************************
% PURPOSE
%   - Evaluate COPP v0.2.2's documented quadratic a(s), linear b(s), and
%     cubic stationary-boundary timing laws exactly.
%**************************************************************************
% INPUTS
%   - station_s_deg, stationTime_s, sampleTime_s, sample_s_deg (vectors)
%   - profile (copp.Profile3rd)
%**************************************************************************
% OUTPUTS
%   - Scalar path speed, acceleration, and jerk histories.
%**************************************************************************
% UNITS
%   - Outputs use deg/s, deg/s^2, and deg/s^3.
%**************************************************************************
station_s_deg = station_s_deg(:);
stationTime_s = stationTime_s(:);
sampleTime_s = sampleTime_s(:);
sample_s_deg = sample_s_deg(:);
sampleCount = numel(sampleTime_s);
pathSpeed_deg_s = zeros(sampleCount, 1);
pathAcceleration_deg_s2 = zeros(sampleCount, 1);
pathJerk_deg_s3 = zeros(sampleCount, 1);
stationCount = numel(station_s_deg);
headCount = profile.num_stationary_start;
tailCount = profile.num_stationary_end;
timeTolerance_s = 1e-12 * max(1, stationTime_s(end));

for sampleIndex = 1:sampleCount
    time_s = sampleTime_s(sampleIndex);
    if headCount > 0 && ...
            time_s <= stationTime_s(1 + headCount) + timeTolerance_s
        stationaryIndex = 1 + headCount;
        delta_s_deg = station_s_deg(stationaryIndex) - station_s_deg(1);
        coefficient_deg_s3 = ...
            sqrt(profile.a(stationaryIndex)) * ...
            profile.a(stationaryIndex) / (27 * delta_s_deg^2);
        localTime_s = time_s - stationTime_s(1);
        pathSpeed_deg_s(sampleIndex) = ...
            3 * coefficient_deg_s3 * localTime_s^2;
        pathAcceleration_deg_s2(sampleIndex) = ...
            6 * coefficient_deg_s3 * localTime_s;
        pathJerk_deg_s3(sampleIndex) = 6 * coefficient_deg_s3;
    elseif tailCount > 0 && ...
            time_s >= stationTime_s(stationCount - tailCount) - ...
            timeTolerance_s
        stationaryIndex = stationCount - tailCount;
        delta_s_deg = station_s_deg(end) - ...
            station_s_deg(stationaryIndex);
        coefficient_deg_s3 = ...
            sqrt(profile.a(stationaryIndex)) * ...
            profile.a(stationaryIndex) / (27 * delta_s_deg^2);
        localTime_s = time_s - stationTime_s(end);
        pathSpeed_deg_s(sampleIndex) = ...
            3 * coefficient_deg_s3 * localTime_s^2;
        pathAcceleration_deg_s2(sampleIndex) = ...
            6 * coefficient_deg_s3 * localTime_s;
        pathJerk_deg_s3(sampleIndex) = 6 * coefficient_deg_s3;
    else
        intervalIndex = find( ...
            station_s_deg <= sample_s_deg(sampleIndex), 1, "last");
        intervalIndex = min(max(intervalIndex, 1), stationCount - 1);
        delta_s_deg = station_s_deg(intervalIndex + 1) - ...
            station_s_deg(intervalIndex);
        local_s_deg = sample_s_deg(sampleIndex) - ...
            station_s_deg(intervalIndex);
        c_1_s2 = (profile.b(intervalIndex + 1) - ...
            profile.b(intervalIndex)) / delta_s_deg;
        a_deg2_s2 = profile.a(intervalIndex) + ...
            2 * profile.b(intervalIndex) * local_s_deg + ...
            c_1_s2 * local_s_deg^2;
        b_deg_s2 = profile.b(intervalIndex) + ...
            c_1_s2 * local_s_deg;
        pathSpeed_deg_s(sampleIndex) = sqrt(max(a_deg2_s2, 0));
        pathAcceleration_deg_s2(sampleIndex) = b_deg_s2;
        pathJerk_deg_s3(sampleIndex) = ...
            c_1_s2 * pathSpeed_deg_s(sampleIndex);
    end
end
end

function [velocity_deg_s, acceleration_deg_s2, jerk_deg_s3] = ...
        composeKinematics(path, pathSpeed_deg_s, ...
        pathAcceleration_deg_s2, pathJerk_deg_s3)
%% Section 0: Header & Readme
% SYNTAX
%   [velocity_deg_s, acceleration_deg_s2, jerk_deg_s3] = ...
%       composeKinematics(path, pathSpeed_deg_s, ...
%       pathAcceleration_deg_s2, pathJerk_deg_s3)
%**************************************************************************
% PURPOSE
%   - Apply the path-composition chain rule through third time derivative.
%**************************************************************************
% INPUTS
%   - path (sampled geometry struct)
%   - pathSpeed_deg_s, pathAcceleration_deg_s2, pathJerk_deg_s3 (N-by-1)
%**************************************************************************
% OUTPUTS
%   - Cartesian velocity, acceleration, and jerk histories (N-by-2).
%**************************************************************************
% UNITS
%   - Outputs use deg/s, deg/s^2, and deg/s^3.
%**************************************************************************
velocity_deg_s = path.tangent .* pathSpeed_deg_s;
acceleration_deg_s2 = ...
    path.secondDerivative_deg_inv .* pathSpeed_deg_s.^2 + ...
    path.tangent .* pathAcceleration_deg_s2;
jerk_deg_s3 = ...
    path.thirdDerivative_deg_inv2 .* pathSpeed_deg_s.^3 + ...
    3 * path.secondDerivative_deg_inv .* ...
    (pathSpeed_deg_s .* pathAcceleration_deg_s2) + ...
    path.tangent .* pathJerk_deg_s3;
end
